Fixed canonical URL
PennyLaneAI/qml pull request #1001
Opened 2023-12-14 14:48 UTC by BM7878

2023-12-14 15:41 UTC, Mandrenkov approved these changes

2023-12-14 18:19 UTC, Mandrenkov requested changes
Wait, do we need to change the `dateOfLastModification` field too?

2023-12-15 14:21 UTC, BM7878 commented
> Wait, do we need to change the `dateOfLastModification` field too?

Updated. @Mandrenkov

2023-12-15 15:23 UTC, Mandrenkov approved these changes
Thanks @BM7878!

2023-12-18 05:07 UTC, josh146 approved these changes

2023-12-18 14:17 UTC, merged