Quantum dropout demo
PennyLaneAI/qml pull request #1003
Opened 2023-12-18 10:48 UTC by fran-scala

Hi! This demo request refers to [Issue #4929](https://github.com/PennyLaneAI/pennylane/issues/4929) for Pennylane, about implementing dropout for Quantum Neural Networks directly in Pennylane.
------------------------------------------------------------------------------------------------------------

**Title:** 

Dropout for Quantum Neural Networks

**Summary:** 

In this demo we show how to exploit the quantum version of dropout technique to avoid the problem of
overfitting in deep Quantum Neural Networks (QNNs). What follows is based on the paper 
“A General Approach to Dropout in Quantum Neural Networks” by F. Scala, et al.

**Relevant references:**

- [1] Scala, F., Ceschini, A., Panella, M., & Gerace, D. (2023).  *A General Approach to Dropout in Quantum Neural Networks*. [Adv. Quantum Technol., 2300220](https://onlinelibrary.wiley.com/doi/full/10.1002/qute.202300220)
- [2] Kiani,B. T., Lloyd, S., & Maity, R. (2020).*Learning Unitaries by Gradient Descent*. [arXiv: 2001.11897](https://arxiv.org/abs/2001.11897)
- [3] Larocca, M., Ju, N., García-Martín, D., Coles, P. J., & Cerezo, M. (2023).  *Theory of overparametrization in quantum neural networks*. [Nat. Comp. Science, 3, 542–551](http://dx.doi.org/10.1038/s43588-023-00467-6)

**Possible Drawbacks:**

In this demo, to show the effectiveness of the technique, dropout is implemented by randomly setting some of the optimized parameters to 0 at each iteration. Actual dropout should be implemented by substituting a certain gate with the identity gate.

**Related GitHub Issues:**

Pennyalne [Issue #4929](https://github.com/PennyLaneAI/pennylane/issues/4929)

----
If you are writing a demonstration, please answer these questions to facilitate the marketing process.

* GOALS — Why are we working on this now?

We would like to implement dropout for QNNs directly in Pennylane, referring to paper [1]

* AUDIENCE — Who is this for?

This technique (hence this demo) is for all people interested in Quantum Machine Learning. Both researchers and enthusiasts may benefit by learning from this demo how to avoid overfitting when using overparametrized QNNs. We strongly believe that it will become a standard for QML just like its classical counterpart in ML.

* KEYWORDS — What words should be included in the marketing post?

"Quantum Neural Networks","QNN", "overfitting", "dropout", "regularization"

* Which of the following types of documentation is most similar to your file? 
(more details [here](https://www.notion.so/xanaduai/Different-kinds-of-documentation-69200645fe59442991c71f9e7d8a77f8))
    
- [ ] Tutorial
- [x] Demo
- [ ] How-to

2023-12-18 22:32 UTC, josh146 commented
thank you for this really nice demo contribution @fran-scala! The bot posted a link to the site preview above, but here is a direct link to the rendered demo: https://qml-build-previews.pennylane.ai/pull_request_build_preview/1003/qml/demos/tutorial_quantum_dropout/

I'll organize with the team for review on our end -- apologies, it might be a bit slow due to the christmas break!

2024-01-02 19:39 UTC, KetpuntoG reviewed
A great demo! Thanks for working on it 😊
Here I leave you some comments.
Let me know if you have any questions

2024-01-02 19:39 UTC, KetpuntoG commented on demonstrations/tutorial_quantum_dropout.py
> +# moderate values of dropout converges, whereas high drop probabilities impede any learning. On
```suggestion
# moderate values of dropout converge, whereas high drop probabilities impede any learning. On

```

2024-01-02 19:39 UTC, KetpuntoG commented on demonstrations/tutorial_quantum_dropout.py
> +# training ones. As the learning is not succesful for elevated drop probabilities the generalization
```suggestion
# training ones. As the learning is not successful for elevated drop probabilities the generalization

```

2024-01-02 19:39 UTC, KetpuntoG commented on demonstrations/tutorial_quantum_dropout.py
> +# training a little noisy. On the other hand, high drop probabilities only hinders the training
```suggestion
# training a little noisy. On the other hand, high drop probabilities only hinder the training

```

2024-01-02 19:39 UTC, KetpuntoG commented on demonstrations/tutorial_quantum_dropout.py
> +# To validate the technique we can also check how the model predict in the whole :math:`[-1,1]` range
```suggestion
# To validate the technique we can also check how the model predicts in the whole :math:`[-1,1]` range

```

2024-01-02 19:39 UTC, KetpuntoG commented on demonstrations/tutorial_quantum_dropout.py
> +# The model without dropout overfits the noisy data by trying to exactly predicting each of them,
```suggestion
# The model without dropout overfits the noisy data by trying to exactly predict each of them,

```

2024-01-29 23:03 UTC, josh146 commented
Hey @fran-scala! Just wondering if you saw the comments by @KetpuntoG :)

2024-01-30 09:50 UTC, fran-scala commented
> Hey @fran-scala! Just wondering if you saw the comments by @KetpuntoG :)

Hi @josh146! I saw the comments and I'm working on solving all the issues. This month was insane. I will commit the updated version ASAP.

2024-01-30 14:57 UTC, josh146 commented
No worries at all @fran-scala! Just wanted to check in :)

2024-02-10 09:34 UTC, fran-scala commented on demonstrations/tutorial_quantum_dropout.py
> +#
Yes! Thanks for the suggestion I will include a couple of references.

2024-02-10 09:45 UTC, fran-scala commented on demonstrations/tutorial_quantum_dropout.py
> +)
It was `black`.

2024-02-10 09:46 UTC, fran-scala commented on demonstrations/tutorial_quantum_dropout.py
> +######################################################################
The legend is in the cutted part, I will fix it

2024-02-10 10:06 UTC, fran-scala commented on demonstrations/tutorial_quantum_dropout.py
> +
thanks!

2024-02-10 10:09 UTC, fran-scala commented on demonstrations/tutorial_quantum_dropout.py
> +    @qml.qnode(device, interface="jax")
Good to ear that! Thanks!

2024-02-10 10:11 UTC, fran-scala commented on demonstrations/tutorial_quantum_dropout.py
> +# Quantum dropout of rotations in ``sin`` regression
Sounds perfect!

2024-02-10 10:23 UTC, fran-scala commented on demonstrations/tutorial_quantum_dropout.py
> +import matplotlib as mpl
Yes, I will definitely do it. I also noticed that there were some useless importations.

2024-02-10 11:04 UTC, fran-scala commented on demonstrations/tutorial_quantum_dropout.py
> +    # keep_rotations contains a list per inner_layer
In the new version, there is an expanded discussion about the QNN circuit. I hope this is more effective.

2024-02-10 11:23 UTC, fran-scala commented on demonstrations/tutorial_quantum_dropout.py
> +# Create :math:`\sin` dataset in presence of additive white Gaussian noise (noise with normal
I apologise for missing this. Now the choice of the dataset is explained also in relationship with dropout.

2024-02-10 12:29 UTC, fran-scala commented on demonstrations/tutorial_quantum_dropout.py
> +# of a QNN during the training phase.
done!

2024-02-11 11:52 UTC, fran-scala commented
Hi @josh146 and @KetpuntoG ! I updated the demo. The only thing left to fix is how to entirely display the plot with training and test losses. The problem is that I'm putting the legend outside the box to not cover the plots. In my notebook, there is no display problem. It happens something similar when I try to save the image (but this can be solved by passing an extra parameter to the `savefig` function).

Let me know if you have any ideas on how to solve this and if the made changes are good.

2024-02-12 14:32 UTC, josh146 commented on demonstrations/tutorial_quantum_dropout.py
> +# parameters, on the one hand, leading to faster and easier training, on the other hand it may drive
```suggestion
# changes the optimization landscape by removing lots of local minima [#Kiani2020]_, [#Larocca2023]_. If this increased number of
# parameters, on the one hand, leading to faster and easier training, on the other hand it may drive
```

2024-02-12 14:32 UTC, josh146 commented on demonstrations/tutorial_quantum_dropout.py
> +# data to achieve nonlinearity in the computation. This is why, inspired from classical DNNs, one
```suggestion
# the model to overfit the data. This is also strictly related to the `repeated encoding <https://pennylane.ai/qml/demos/tutorial_expressivity_fourier_series/>`__ of classical
# data to achieve nonlinearity in the computation. This is why, inspired from classical DNNs, one
```

2024-02-12 14:33 UTC, josh146 commented on demonstrations/tutorial_quantum_dropout.py
> +# define two functions ``true_cond`` and ``false_cond` to work with ``jax.lax.cond```, which is the JAX
```suggestion
# define two functions ``true_cond`` and ``false_cond`` to work with ``jax.lax.cond```, which is the JAX
```

2024-02-12 14:33 UTC, josh146 commented on demonstrations/tutorial_quantum_dropout.py
> +# (this will be called ``rot_drop_rate``), the probability :math:`p` that a
```suggestion
# dropout rate :math:`p_L` (this will be called ``layer_drop_rate``) and the gate dropout rate :math:`p_G`
# (this will be called ``rot_drop_rate``), the probability :math:`p` that a
```

2024-02-12 14:33 UTC, josh146 commented on demonstrations/tutorial_quantum_dropout.py
> +# This function will be called at each iteration.
```suggestion
# is nested: we have a list per ``inner_layer`` inside a list per each layer, all contained in another list.
# This function will be called at each iteration.
```

2024-02-12 14:34 UTC, josh146 commented on demonstrations/tutorial_quantum_dropout.py
> +# the right, we can see the difference in generalization during the optimization process. Standard
```suggestion
# moderate values of dropout converge, whereas high drop probabilities impede any learning. On
# the right, we can see the difference in generalization during the optimization process. Standard
```

2024-02-12 14:34 UTC, josh146 commented on demonstrations/tutorial_quantum_dropout.py
> +# error is huge. It is interesting to notice that the “not-learning” error is very close to the final
```suggestion
# training ones. As the learning is not successful for elevated drop probabilities the generalization
# error is huge. It is interesting to notice that the “not-learning” error is very close to the final
```

2024-02-12 14:34 UTC, josh146 commented on demonstrations/tutorial_quantum_dropout.py
> +#
```suggestion
# training a little noisy. On the other hand, high drop probabilities only hinder the training
# process.
#
```

2024-02-12 14:34 UTC, josh146 commented on demonstrations/tutorial_quantum_dropout.py
> +# whereas dropout actually mitigates overfitting and makes the approximation of the underlying ``sin``
```suggestion
# The model without dropout overfits the noisy data by trying to exactly predict each of them,
# whereas dropout actually mitigates overfitting and makes the approximation of the underlying ``sin``
```

2024-02-12 14:36 UTC, josh146 commented
Thanks @fran-scala!

> The only thing left to fix is how to entirely display the plot with training and test losses. The problem is that I'm putting the legend outside the box to not cover the plots. In my notebook, there is no display problem. It happens something similar when I try to save the image (but this can be solved by passing an extra parameter to the savefig function).

Are you referring to this plot?

![image](https://github.com/PennyLaneAI/qml/assets/2959003/4aab94bb-c20e-4353-bb7e-ec262cae90d7)

That is a bit odd 🤔 @KetpuntoG any suggestions?

2024-02-12 15:06 UTC, KetpuntoG commented
thank you very much for working on the changes! @fran-scala 
As soon as I can I'll take another look at the demo 🚀

2024-02-12 15:07 UTC, KetpuntoG commented
> Thanks @fran-scala!
> 
> > The only thing left to fix is how to entirely display the plot with training and test losses. The problem is that I'm putting the legend outside the box to not cover the plots. In my notebook, there is no display problem. It happens something similar when I try to save the image (but this can be solved by passing an extra parameter to the savefig function).
> 
> Are you referring to this plot?
> 
> ![image](https://private-user-images.githubusercontent.com/2959003/304121515-4aab94bb-c20e-4353-bb7e-ec262cae90d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NTA1ODYsIm5iZiI6MTcwNzc1MDI4NiwicGF0aCI6Ii8yOTU5MDAzLzMwNDEyMTUxNS00YWFiOTRiYi1jMjBlLTQzNTMtYmI3ZS1lYzI2MmNhZTkwZDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTJUMTUwNDQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OThlMTgxN2VlZjkzNTQ3NmYwYjhiMmFiN2Q3YzdkNjljYmZiZjY3YWQ0YTcxZTNjNjNlMWJiZWQ3M2ZmYThmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.y9SEfqKnyWbG4vC__ex0YcoEBnTfU9xqVLxBT7HuONE)
> 
> That is a bit odd 🤔 @KetpuntoG any suggestions?

I have seen this on several occasions
I would try to write this at the end:

`plt.subplots_adjust(bottom=0.3)`

2024-02-23 11:02 UTC, fran-scala commented
> plt.subplots_adjust(bottom=0.3)

Sorry for the delay but I was taking part in the QHack.

I tried to add this, but I'm having troubles in building the website locally so I don't know if this worked.

2024-02-23 20:12 UTC, isaacdevlugt requested changes
Nice demo! Just some grammatical suggestions and a couple things that I feel need clarification. Overall, nice work!

2024-02-23 20:12 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_dropout.py
> +# training without dropout initially reaches a low value of generalization error, but then, as the
```suggestion
# training without dropout initially reaches a low value of generalization error, but as the
```

2024-02-23 20:12 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_dropout.py
> +# back. Opposite, moderate values of dropout enable generalization errors comparable to the respective
```suggestion
# back. Oppositely, moderate values of dropout enable generalization errors comparable to the respective
```

2024-02-23 20:12 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_dropout.py
> +# training ones. As the learning is not successful for elevated drop probabilities the generalization
```suggestion
# training ones. As the learning is not successful for elevated drop probabilities, the generalization
```

2024-02-23 20:12 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_dropout.py
> +# whereas dropout actually mitigates overfitting and makes the approximation of the underlying ``sin``
```suggestion
# whereas dropout actually mitigates overfitting and makes the approximation of the underlying sinusoidal
```

2024-02-23 20:12 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_dropout.py
> +# To sum up, in this demo, we explained the basic idea behind quantum dropout and
```suggestion
# In this demo, we explained the basic idea behind quantum dropout and
```

2024-02-23 20:12 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_dropout.py
> +# we showed how to avoid overfitting by randomly "dropping" some rotation gates
```suggestion
# how to avoid overfitting by randomly "dropping" some rotation gates

```

2024-02-24 09:37 UTC, fran-scala commented on demonstrations/tutorial_quantum_dropout.py
> +sns.set()  # set seaborn theme, which is nice to see
sure!

2024-02-24 09:41 UTC, fran-scala commented on demonstrations/tutorial_quantum_dropout.py
> +# a specific layer.
I wanted to stress that the events A and B are both "*selection*" events. Mentioning B before A is a good suggestion, it looks clearer to me

2024-02-24 10:11 UTC, fran-scala commented on demonstrations/tutorial_quantum_dropout.py
> +# noisy data within this range. We fit the scaler from training data and then we apply it also to the
I tried to better clarify this. Let me know if it works in your opinion.

2024-02-28 13:40 UTC, KetpuntoG reviewed
Great job! I have seen that there are some rendering issues. I think with the extra "#" I've included, it should work :) Once the deployment works, I will contact the designer and marketing to proceed with publication. If you have a small sketch of how you would like the thumbnail, it would help us 😄

2024-02-28 13:40 UTC, KetpuntoG commented on demonstrations/tutorial_quantum_dropout.py
> +
```suggestion
# 
```

2024-02-28 13:40 UTC, KetpuntoG commented on demonstrations/tutorial_quantum_dropout.py
> +
```suggestion
#
```

2024-02-28 13:40 UTC, KetpuntoG commented on demonstrations/tutorial_quantum_dropout.py
> +
```suggestion
```

2024-02-28 13:40 UTC, KetpuntoG commented on demonstrations/tutorial_quantum_dropout.py
> +
```suggestion
```

2024-02-28 13:40 UTC, KetpuntoG commented on demonstrations/tutorial_quantum_dropout.py
> +# Now we define the embedding of classical data and the variational anstaz that will then be combined
```suggestion
# Now we define the embedding of classical data and the variational ansatz that will then be combined

```

2024-02-28 13:40 UTC, KetpuntoG commented on demonstrations/tutorial_quantum_dropout.py
> +# (If the trainig dataset is not exhaustively representative of the underlying distribution,
```suggestion
# (If the training dataset is not exhaustively representative of the underlying distribution,

```

2024-02-28 14:33 UTC, fran-scala commented
> Great job! I have seen that there are some rendering issues. I think with the extra "#" I've included, it should work :) Once the deployment works, I will contact the designer and marketing to proceed with publication. If you have a small sketch of how you would like the thumbnail, it would help us 😄

Perfect! Many thanks for your help!


About the sketch, I'm not very good at drawing but I think that a good idea can be a circuit from which some gates literally "drop/jump out" from the circuit or, alternatively, something like the image here below (that is something I used at some conferences)

<img width="415" alt="Schermata 2024-02-28 alle 15 30 20" src="https://github.com/PennyLaneAI/qml/assets/91551202/9d572e57-9be8-4725-806d-558954aacb0a">

2024-02-29 00:34 UTC, KetpuntoG commented
> > Great job! I have seen that there are some rendering issues. I think with the extra "#" I've included, it should work :) Once the deployment works, I will contact the designer and marketing to proceed with publication. If you have a small sketch of how you would like the thumbnail, it would help us 😄
> 
> Perfect! Many thanks for your help!
> 
> About the sketch, I'm not very good at drawing but I think that a good idea can be a circuit from which some gates literally "drop/jump out" from the circuit or, alternatively, something like the image here below (that is something I used at some conferences)
> 
> <img alt="Schermata 2024-02-28 alle 15 30 20" width="415" src="https://private-user-images.githubusercontent.com/91551202/308585211-9d572e57-9be8-4725-806d-558954aacb0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNjcwMzcsIm5iZiI6MTcwOTE2NjczNywicGF0aCI6Ii85MTU1MTIwMi8zMDg1ODUyMTEtOWQ1NzJlNTctOWJlOC00NzI1LTgwNmQtNTU4OTU0YWFjYjBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDAwMzIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzZjJkZWQ4Yjg4ZjhiNjA0OTI0ZDY1MjU3ZTljOTAyYmY1MTRjNmQ1ZDY4Mzg1OTMwYmJkYmRiZGYxOTI5MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CLDF7tfmoAz2r_OrdComm4Xou10IeAGDhgCvXXxZ8oo">

That helps, thanks! 🎨

2024-03-11 19:46 UTC, KetpuntoG commented
Hey @fran-scala , just wanted to double check
Is this the expected output? or is the image cut?

<img width="594" alt="Captura de pantalla 2024-03-11 a las 15 43 31" src="https://github.com/PennyLaneAI/qml/assets/65235481/f27c0d2e-3c16-49a3-a026-d4c4ce895c24">

2024-03-11 20:01 UTC, fran-scala commented
> Hey @fran-scala , just wanted to double check Is this the expected output? or is the image cut?
> 
> <img alt="Captura de pantalla 2024-03-11 a las 15 43 31" width="594" src="https://private-user-images.githubusercontent.com/65235481/311846108-f27c0d2e-3c16-49a3-a026-d4c4ce895c24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxODcyOTcsIm5iZiI6MTcxMDE4Njk5NywicGF0aCI6Ii82NTIzNTQ4MS8zMTE4NDYxMDgtZjI3YzBkMmUtM2MxNi00OWEzLWEwMjYtZDRjNGNlODk1YzI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDE5NTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNjc3N2M5ZDM0ODkyYTEyZWE1YzQ4MDRlOThhM2UwZTE2OGQxY2FmYzRhYTBkZTdiOTY3YzE2YzNkMjNiOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vT3mNgZxY2jn6g1i3zLoHcKd2yB0w--ygQgsaoNOo5M">

The output is now correct! But if you have any suggestions to make the plot clearer please tell me.

2024-03-11 20:08 UTC, KetpuntoG commented
I found it different than normal to see the blue curve cut in the middle. 
If you calculate it you could extend the y-axis up to maybe ~10^-4?

2024-03-11 20:12 UTC, fran-scala commented
> I found it different than normal to see the blue curve cut in the middle. If you calculate it you could extend the y-axis up to maybe ~10^-4? (if it will be too flat on the right side, ignore this comment)

Yeah the point is that on the left side the blue curve goes to 0 extremely fast, and this leads to overfitting. But if we go to 10^-4 it would be difficult to see wll in the right panel. If it's not a big deal I would rather leave it like this.

By the way I think there are still rendering problems in the section "The circuit".

I saw the thumbnail, cool!

2024-03-12 19:15 UTC, KetpuntoG commented
Hey ! for the publication it is possible that marketing may want to include your username in the post. Could you share with me your @username from Twitter (optional)?

2024-03-12 21:25 UTC, fran-scala commented
> Hey ! for the publication it is possible that marketing may want to include your username in the post. Could you share with me your @username from Twitter (optional)?

Unfortunately, I do not have a Twitter account but I would be happy to be tagged on LinkedIn (www.linkedin.com/in/fran-scala)

2024-03-13 13:58 UTC, KetpuntoG commented
Great thanks! It will probably be visible on the web today but we will announce it in two weeks time

2024-03-13 14:34 UTC, KetpuntoG approved these changes
Great job 🚀

2024-03-13 14:41 UTC, fran-scala commented
> Great thanks! It will probably be visible on the web today but we will announce it in two weeks time

Fantastic! Thanks you all for the provided help and for what you do for the community!🤩

2024-03-13 14:47 UTC, isaacdevlugt approved these changes

2024-03-13 15:39 UTC, merged

2024-03-14 23:11 UTC, KetpuntoG commented
Hi @fran-scala ! Marketing has scheduled the post for  March 28th :)

2024-03-15 14:24 UTC, fran-scala commented
> Hi @fran-scala ! Marketing has scheduled the post for March 28th :)

Sounds perfect! That day is my birthday so thanks a lot for the gift!🎉