Intro to QPE demo
PennyLaneAI/qml pull request #1006
Opened 2024-01-03 23:20 UTC by ixfoduap

New version of QPE demo

2024-01-04 10:09 UTC, KetpuntoG reviewed
Very good work! We will have it ready soon 😄🚀
Here I leave you some comments

2024-01-04 10:09 UTC, KetpuntoG commented on demonstrations/tutorial_qpe.py
> +# Cleaning the signal
I'm happy with removing this part. The reason that was before is because it linked perfectly with the interpretation that was given from the point of view of signal processing. Now could be more confusing in this context

2024-01-04 14:11 UTC, ixfoduap commented on demonstrations/tutorial_qpe.py
> +By measuring the second register we obtain :math:`\theta` directly. We refer to the first register as the **system**,
Fine to change to target, go ahead and do it. I guess I'm used to system from a quantum simulation perspective

2024-01-04 14:15 UTC, ixfoduap commented on demonstrations/tutorial_qpe.py
> +always be possible. From now on, we'll use :math:`n` for the number of estimation qubits.
Great suggestion. Add the sentence "For example, the binary expansion of 0.8 is 0.11001100... which does not terminate "

2024-01-04 14:15 UTC, ixfoduap commented on demonstrations/tutorial_qpe.py
> +How can we encode :math:`\phi` on a quantum computer? The answer is the first clever part of the algorithm: we represent
Another great suggestion! Go ahead and make that change

2024-01-04 14:16 UTC, ixfoduap commented on demonstrations/tutorial_qpe.py
> +
Right! It's wrong, I must have copy-pasted the wrong thing

2024-01-04 14:17 UTC, ixfoduap commented on demonstrations/tutorial_qpe.py
> +.. math::
Not sure. Let's discuss more on slack

2024-01-04 14:18 UTC, ixfoduap commented on demonstrations/tutorial_qpe.py
> +Notice something? This is just applying :math:`\psi\rangle |k\rangle \rightarrow \psi U^k\rangle |k\rangle` with
Yes! Please make the change

2024-01-04 14:18 UTC, ixfoduap commented on demonstrations/tutorial_qpe.py
> +# Cleaning the signal
Ok. Let's remove

2024-01-04 21:06 UTC, soranjh submitted a review, later dismissed
The demo looks good. I left some small comments and suggestions. 

My major suggestion is that the description of the controlled unitaries, which is an important building block of QPE, could be improved a bit. If possible, explaining it wrt phase kickback will be great.

2024-01-09 12:39 UTC, KetpuntoG commented on demonstrations/tutorial_qpe.py
> +Part 3: Controlled sequence
Controlled sequence has not Hadamard  or phases. I think QPE is the extension of phase kickback itself, let me rethink that

2024-01-11 21:12 UTC, ixfoduap reviewed
Left many minor suggestions. Once those are addressed, this should be mostly ready to merge.

But one final point. I think it may be good to do another pass and add more links to other demos, parts of the code, etc to help with search engine optimization

2024-01-11 21:12 UTC, ixfoduap commented on demonstrations/tutorial_qpe.py
> +If we pay attention carefully we can see that it would be enough to create an operator such that:
```suggestion
It would then be enough to create an operator such that:
```

2024-01-11 21:12 UTC, ixfoduap commented on demonstrations/tutorial_qpe.py
> +In this way, if we apply this operator to the uniform superposition we would have that:
```suggestion
In this way, if we apply this operator to the uniform superposition we obtain:
```

2024-01-11 21:12 UTC, ixfoduap commented on demonstrations/tutorial_qpe.py
> +In PennyLane we refer to this operator as a :class:`~.ControlledSequence` operation. Let's see how to build it.
```suggestion
In PennyLane we refer to this as a :class:`~.ControlledSequence` operation. Let's see how to build it.
```

2024-01-11 21:12 UTC, ixfoduap commented on demonstrations/tutorial_qpe.py
> +Let's see what happens with two qubits. After applying the Hadamards, omitting normalization factors,
```suggestion
Let's see what happens with two qubits. After applying the Hadamards (and omitting normalization factors),
```

2024-01-11 21:12 UTC, ixfoduap commented on demonstrations/tutorial_qpe.py
> +:math:`U^2` controlled on the second qubit. We can extend this idea to any number of qubits.
```suggestion
Notice something? The power of :math:`U` is the same as the binary representation of the corresponding basis state. For example,  :math:`U^3` is applied when the estimation register is in state :math:`|11\rangle`, and 11 is just the number 3 in binary. 
Therefore, the desired operation can be implemented by applying :math:`U` controlled on the first qubit, and
:math:`U^2` controlled on the second qubit. We can extend this idea to any number of qubits.
```

2024-01-11 21:12 UTC, ixfoduap commented on demonstrations/tutorial_qpe.py
> +binary representation of :math:`k`.
```suggestion
The following animation illustrates this effect.
```

2024-01-11 21:12 UTC, ixfoduap commented on demonstrations/tutorial_qpe.py
> +.. figure:: ../_static/demonstration_assets/qpe/controlledSequence.gif
Amazing gif! 

It may be good to add a short caption explaining what is going on

2024-01-11 21:12 UTC, ixfoduap commented on demonstrations/tutorial_qpe.py
> +.. figure:: ../_static/demonstration_assets/qpe/controlledSequence.gif
Also, in both this gif and the next image, can we make the controls bigger? As in the control-U operations? Right now the "circle" is too small

2024-01-11 21:12 UTC, ixfoduap commented on demonstrations/tutorial_qpe.py
> +# As mentioned above, since the eigenphase cannot be represented exactly using 4 bits, there is a
```suggestion
# Since the eigenphase cannot be represented exactly using 4 bits, there is a
```

2024-01-11 21:12 UTC, ixfoduap commented on demonstrations/tutorial_qpe.py
> +# through the mapping :math:`U=e^{-iHt}`, which can be implemented using Hamiltonian simulation techniques. QPE can then
```suggestion
# through the mapping :math:`U=e^{-iHt}`, which can be implemented using Hamiltonian simulation techniques. More advanced techniques employ a qubitization-based encoding. QPE can then
```

2024-01-23 21:39 UTC, isaacdevlugt requested changes
Some minor comments. Re-request me when you're ready!

2024-01-23 21:39 UTC, isaacdevlugt commented on demonstrations/tutorial_qpe.py
> +How would that work?
Optional suggestion but maybe nice!

```suggestion
where :math:`\phi` is the *phase* of the eigenvalue (remember, unitaries have eigenvalues with an 
absolute value of 1). The goal is to estimate :math:`\phi`,
hence the name *phase estimation*. Our challenge is to design a quantum algorithm to solve this problem.
How would that work?
```

2024-01-23 21:39 UTC, isaacdevlugt commented on demonstrations/tutorial_qpe.py
> +We could then obtain :math:`\phi` directly by measuring the second register.  We call this the **estimation register**, while the second one is the **estimation** register.
Typo here?
```suggestion
We could then obtain :math:`\phi` directly by measuring the second register.  We call this the **estimation register**.
```

2024-01-23 21:39 UTC, isaacdevlugt commented on demonstrations/tutorial_qpe.py
> +The second clever part of the algorithm is to follow an advice given to many physicists:
```suggestion
The second clever part of the algorithm is to follow advice given to many physicists:
```

2024-01-23 21:39 UTC, isaacdevlugt commented on demonstrations/tutorial_qpe.py
> +We follow another timeless physics advice: "If stuck, start with the simplest case".
```suggestion
We follow another timeless piece of physics advice: "If stuck, start with the simplest case".
```

2024-01-23 21:39 UTC, isaacdevlugt commented on demonstrations/tutorial_qpe.py
> +We follow another timeless physics advice: "If stuck, start with the simplest case".
some of the best advice one can give 😄

2024-01-23 21:39 UTC, isaacdevlugt commented on demonstrations/tutorial_qpe.py
> +(Note that 010111 is 23 in binary.)
```suggestion
Note that 010111 is 23 in binary.
```

2024-01-23 21:39 UTC, isaacdevlugt commented on demonstrations/tutorial_qpe.py
> +This operator facilitates, among other things, performing `arithmetics in quantum computers <tutorial_qft_arithmetics>`__.
🚀

2024-01-23 21:39 UTC, isaacdevlugt commented on demonstrations/tutorial_qpe.py
> +a matrix**. Wow. This is true even if we relax the assumption that the input is an eigenstate. By linearity, for an arbitrary
❗ 

```suggestion
a matrix**. Wow! This is true even if we relax the assumption that the input is an eigenstate. By linearity, for an arbitrary
```

2024-01-23 21:39 UTC, isaacdevlugt commented on demonstrations/tutorial_qpe.py
> +coupled with a clever use of Fourier transforms. This feature is crucial for quantum chemistry applications,
```suggestion
coupled with a clever use of quantum Fourier transforms. This feature is crucial for quantum chemistry applications,
```

2024-01-23 21:39 UTC, isaacdevlugt commented on demonstrations/tutorial_qpe.py
> +All the previous idea helps to also understand the Phase KickBack algorithm in the case of one qubit.
```suggestion
All the previous ideas help to also understand the Phase KickBack algorithm in the case of one qubit.
```

2024-01-23 21:39 UTC, isaacdevlugt commented on demonstrations/tutorial_qpe.py
> +If you want to learn more about this subroutine take a look at this :doc:`demo <tutorial_phase_kickback>`.
```suggestion
If you want to learn more about this subroutine, take a look at this :doc:`demo <tutorial_phase_kickback>`.
```

2024-01-23 21:39 UTC, isaacdevlugt commented on demonstrations/tutorial_qpe.py
> +# a 4-bit representation to the exact value :math:`0.2`.  🎊.
```suggestion
# a 4-bit representation to the exact value :math:`0.2`.  🎊
```

2024-01-23 22:03 UTC, isaacdevlugt approved these changes
LGTM!

2024-01-26 18:15 UTC, KetpuntoG approved these changes

2024-01-26 18:15 UTC, merged