[WIP] Demo about implementing Shor's algorithm with Catalyst
PennyLaneAI/qml pull request #1010
Opened 2024-01-07 23:09 UTC by glassnotes

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Remember to do a grammar check of the content you include.
- [ ] All tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

----
If you are writing a demonstration, please answer these questions to facilitate the marketing process.

* GOALS — Why are we working on this now?

  *Eg. Promote a new PL feature or show a PL implementation of a recent paper.*

* AUDIENCE — Who is this for?

  *Eg. Chemistry researchers, PL educators, beginners in quantum computing.*

* KEYWORDS — What words should be included in the marketing post?

* Which of the following types of documentation is most similar to your file? 
(more details [here](https://www.notion.so/xanaduai/Different-kinds-of-documentation-69200645fe59442991c71f9e7d8a77f8))
    
- [ ] Tutorial
- [ ] Demo
- [ ] How-to

2024-01-08 13:54 UTC, KetpuntoG commented on demonstrations/tutorial_shor_catalyst.py
> +# best include these, because some are quite large)
If you don't want to go into too much detail here, there is an option to upload a .py and simply import the operator. However, I think it would be worth a small tutorial in the future. People would love it!

2024-01-08 14:01 UTC, KetpuntoG commented on demonstrations/tutorial_shor_catalyst.py
> +just-in-time compiled from end-to-end, classical control structure and all.
I think we should recommend to the reader something about just-in-time since I think it is super important here and it is not a known term in quantum computing: "If you still don't know what this Jit thing is and the potential it has, I invite you to take a look to ..." or similar

2024-11-04 20:45 UTC, KetpuntoG commented on demonstrations/tutorial_shor_catalyst.py
> +# TODO: explain how the modular exponentiation circuits work (not sure yet how to
Update: pennylane now has [qml.ModExp](https://docs.pennylane.ai/en/stable/code/api/pennylane.ModExp.html). So we can probably save the explanation here 😄

2024-11-06 18:29 UTC, glassnotes commented on demonstrations/tutorial_shor_catalyst.py
> +# TODO: explain how the modular exponentiation circuits work (not sure yet how to
I saw! Are they `qjit` compatible?  There is a fair amount of customization in my implementation so I will probably still provide brief explanations, and the circuits, but only what's needed.

2024-11-07 20:37 UTC, KetpuntoG commented on demonstrations/tutorial_shor_catalyst.py
> +# TODO: explain how the modular exponentiation circuits work (not sure yet how to
It should be, let me know if you have any problems :)

2024-11-15 21:18 UTC, glassnotes commented on demonstrations/tutorial_haar_measure.py
> +#
```suggestion
#
```

2025-02-07 19:09 UTC, josh146 commented on demonstrations/tutorial_shor_catalyst.py
> +# TODO: explain how the modular exponentiation circuits work (not sure yet how to
Curious if this ended up working!

2025-02-07 20:20 UTC, KetpuntoG commented on demonstrations/tutorial_shor_catalyst.py
> +            qml.ControlledPhaseShift(shifts[j], wires=[wires[(i + 1) + j], wires[i]])
The demo is looking great! Just a comment to make this more visible
In Pennylane the number 4 is represented as:

|1>---
|0>---
|0>--

In qiskit as:

|0>---
|0>-
|1>--

I see you are going with the qiskit format. Perhaps it may cause confusion as the results will not match the Pennylane arithmetic operators

2025-02-07 22:52 UTC, glassnotes commented on demonstrations/tutorial_shor_catalyst.py
> +            qml.ControlledPhaseShift(shifts[j], wires=[wires[(i + 1) + j], wires[i]])
Ah, I am using the normal PennyLane ordering, but I written things to prevent a bunch of unnecessary SWAPs. It should match the order in the circuits here.

2025-02-07 22:53 UTC, glassnotes commented on demonstrations/tutorial_shor_catalyst.py
> +# TODO: explain how the modular exponentiation circuits work (not sure yet how to
I haven't tried - I stayed with my own implementations because there are  "higher-level" optimizations being applied (like removing entire QFTs, etc.).

2025-02-07 22:57 UTC, glassnotes commented
Marking as ready-for-review to test the build (it worked locally). I'll tag people once a full first draft of all the text and code is finished.

2025-02-07 23:02 UTC, josh146 commented on demonstrations/tutorial_shor_catalyst.py
> +# TODO
```suggestion
# TODO!
```

2025-02-09 21:36 UTC, josh146 commented on demonstrations/tutorial_shor_catalyst.py
> +#    with more shots. Eventually, we try with a different value of a.
```suggestion
# - First, we randomly select a candidate integer, :math:`a`, between 2 and
#   :math:`N-1` (before proceeding, we double check that we did not get lucky and randomly select one of the true factors)
# - Using our chosen a, we proceed to the quantum part of the algorithm: order-finding.
#   Quantum circuits are generated, and the circuit is executed on a device. The results
#   are used to make a guess for a non-trivial square root.
# - If the square root is non-trivial, we test whether we found the factors. Otherwise, we try again
#   with more shots. Eventually, we try with a different value of a.
```

2025-02-11 01:03 UTC, glassnotes reviewed
@KetpuntoG @josh146 @dime10 At long last, here is a first draft for review. It's a long one, so please feel free to tag whoever has some bandwidth. I left some comments within. Two other top-level things:
 - Most of the 90000 lines of this PR is SVG. The actual demo is ~1100
 - The webpage does not seem to fully build. I can find the demo from the front, but most of the links give me XML access denied errors. I don't know if that's expected.

2025-02-11 01:03 UTC, glassnotes commented on demonstrations/tutorial_shor_catalyst.py
> +plt.ylabel("Runtime (s)");
I can't figure out how to suppress the text output of the plot. Adding a semicolon does not help. Also, would be great to get some feedback on clarity of the plot and whether it is effective in capturing the main points

2025-02-11 01:03 UTC, glassnotes commented on demonstrations/tutorial_shor_catalyst.py
> +# parts of workflows.
Suggestions welcome. Honestly this was so long in the making that I was at a loss for what to write here :sweat_smile:

2025-02-19 21:36 UTC, dime10 reviewed
First of all, this is an incredible demo!! I'm amazed how well you explain and show the different pieces going in to this, must have been a lot work 😍 The introduction is also really nice :)

2025-02-19 21:36 UTC, dime10 commented on demonstrations/tutorial_shor_catalyst.py
> +# currently be QJITted. Passing ``n_bits`` as a static argument is also to work
Oh does this not work? Generating random numbers is possible with JAX, the main difference to numpy is that the PRNG state is [explicit rather than implicit](https://docs.jax.dev/en/latest/random-numbers.html#explicit-random-state). We also use them in the MSD demo: https://docs.pennylane.ai/projects/catalyst/en/stable/demos/magic_distillation_demo.html#T-Type-Magic-States

2025-02-19 21:36 UTC, dime10 commented on demonstrations/tutorial_shor_catalyst.py
> +def factor_with_shor(N, n_shots=100):
I'm hesitant about the term shots here, since they could be confused with the concept of PennyLane/device shots. Should we just call these trials or similar?

2025-02-19 21:36 UTC, dime10 commented on demonstrations/tutorial_shor_catalyst.py
> +# long.
Was this saying that the JIT compilation time is long for large N or that "traditional" (e.g. PennyLane) circuit construction and processing becomes very expensive?
I think when I measured it the increase in JIT compilation time was relatively flat now. 
```suggestion
# particularly valuable for large :math:`N`, where traditional circuit processing times can
# grow very large.
```

2025-02-19 21:36 UTC, dime10 commented on demonstrations/tutorial_shor_catalyst.py
> +plt.ylabel("Runtime (s)");
This plot does show the lack of recompilation for different `a`s and even `N`s, but I think what might be missing is demonstrating why that is valuable to the user 🤔 
What about comparing to the non-jitted version where re-computing and processing new circuits for each `a` takes a lot of time?

2025-02-19 21:36 UTC, dime10 commented on demonstrations/tutorial_shor_catalyst.py
> +# parts of workflows.
I remember you mentioning how great it was to be able to implement optimizations that are dependent on `a` without any extra cost, maybe that is something we could highlight in the conclusion? :) 
> The fact that you can make all these really specific, a-dependent optimizations in the circuit, and it just works after the first run because of jit, is seriously amazing

2025-02-19 21:45 UTC, dime10 commented on demonstrations/tutorial_shor_catalyst.py
> +plt.ylabel("Runtime (s)");
> I can't figure out how to suppress the text output of the plot. 

Have you tried this version?
```suggestion
plt.ylabel("Runtime (s)")
plt.show()
```

2025-02-27 18:35 UTC, glassnotes commented on demonstrations/tutorial_shor_catalyst.py
> +# together. This demo leverages that integration to implement a version of
Ahh, this was written as things had just changed from functions like `adjoint` and `ctrl` needing special Catalyst versions to being able to just use `qml.adjoint`. I will adjust the language.

2025-02-27 18:44 UTC, glassnotes commented on demonstrations/tutorial_shor_catalyst.py
> +# .. figure:: ../_static/demonstration_assets/shor_catalyst/compilation-stack.svg
Yeah I'll change that! I usually use this diagram in talks, not text, so I'm explaining as I go :sweat_smile:

2025-02-27 19:40 UTC, glassnotes commented on demonstrations/tutorial_shor_catalyst.py
> +# Quantum subroutines
Alright so I've relegated three big chunks of circuit explanations to an appendix at the end - see what you think!

2025-02-27 19:44 UTC, glassnotes commented on demonstrations/tutorial_shor_catalyst.py
> +# .. figure:: ../_static/demonstration_assets/shor_catalyst/c-ua.svg
I see what you mean - check out the new version, I tried putting it inside a curly brace. If this makes it clearer, I can update the other diagrams too.

2025-02-27 19:48 UTC, glassnotes commented on demonstrations/tutorial_shor_catalyst.py
> +# currently be QJITted. Passing ``n_bits`` as a static argument is also to work
Admittedly I haven't tried in a long time - the last time I did, I couldn't get it to work, but I don't remember what the issue was. I'll see if I can work it out!

2025-02-27 19:48 UTC, glassnotes commented on demonstrations/tutorial_shor_catalyst.py
> +def factor_with_shor(N, n_shots=100):
Sure, `trials` works!

2025-03-06 22:54 UTC, glassnotes commented on demonstrations/tutorial_shor_catalyst.py
> +def shors_algorithm(N, key, a, n_bits, n_trials):
@dime10 I got the random number generation working within the qjitted algorithm. The reason it wasn't working before is that previously, I was generating a list of valid `a` using `jnp.arange` and then using `jnp.random.choice`. But if I simply use `randint` between a range, this avoids the problem. 

I've also made it so `a` can still be sent in manually (which bypasses the random generation, and allows us to time and do resource estimates for specific `a`).

Finally, I've made `n_trials` a parameter as well, so we really can qjit the whole thing! :tada:

```python
p, q, _, a, success_prob = shors_algorithm(N, key.astype(jnp.uint32), 0, n_bits, 100)
```

2025-03-10 00:03 UTC, glassnotes commented
The demo is now ready for re-review (requested from David, but please add anyone else who will be taking a look). The major updates include:
 - moving a lot of the circuit construction details and diagrams into appendices
 - adding a couple more plots to demonstrate results, including a comparison against a standard PennyLane implementation (which leads to a lot of code duplication, unfortunately)
 - expanding the scope of the qjitted function to include also random generation of `a`. So *everything* (except the static argument for bit width) is now qjitted  :tada:

2025-03-11 15:02 UTC, dime10 commented on demonstrations/tutorial_shor_catalyst.py
> +def shors_algorithm(N, key, a, n_bits, n_trials):
Sweet 🚀 🚀

2025-03-11 17:40 UTC, dime10 approved these changes
Love it 😍 The demo is more concise now, and I like the new results section which the comparison to PennyLane! High-quality demo :)

The below are all very minor:

2025-03-11 17:47 UTC, dime10 commented on demonstrations/tutorial_shor_catalyst.py
> +# .. figure:: ../_static/demonstration_assets/shor_catalyst/c-ua.svg
Much clearer now :)

2025-03-11 17:48 UTC, dime10 commented on demonstrations/tutorial_shor_catalyst.py
> +# effectively terminate the algorithm early.
👌

2025-03-11 17:57 UTC, dime10 commented on demonstrations/tutorial_shor_catalyst.py
> +    while jnp.logical_and(i < 300, mantissa != jnp.floor(mantissa)):
Omg 😆 Okay I went digging a bit and found the source again, this function is a conversion of the Python `float_as_integer_ratio` implementation to JAX:
https://github.com/python/cpython/blob/e0bc9d2a0c448cf46df233f8d84344c1f55a190f/Objects/floatobject.c#L1562-L1565

2025-03-11 18:01 UTC, dime10 commented on demonstrations/tutorial_shor_catalyst.py
> +    while jnp.logical_and(i < 300, mantissa != jnp.floor(mantissa)):
I just had another thought, I think the implementation is bit-width limited (besides memory restrictions on simulators), such that we can only have `n_bits < 64`. I think the reason is the use of integers to do bit-string manipulations in some places. Is it worth mentioning in the demo?

2025-03-11 18:04 UTC, dime10 commented on demonstrations/tutorial_shor_catalyst.py
> +def phase_to_order(phase, max_denominator):
Hmm it might be kind of awkward to insert attributions in the middle of the demo code. So maybe at the bottom of the demo if it fits but I don't think it's a big deal either way, you did most of the hard work here :)

2025-03-11 18:04 UTC, dime10 commented on demonstrations/tutorial_shor_catalyst.py
> +# Quantum subroutines
Looks great!

2025-03-18 13:38 UTC, glassnotes commented on demonstrations/tutorial_shor_catalyst.py
> +# advance, we can vary circuit structure on the fly and save resources.
Yeah good point - I will adjust that!

2025-03-18 13:41 UTC, glassnotes commented on demonstrations/tutorial_shor_catalyst.py
> +    while jnp.logical_and(i < 300, mantissa != jnp.floor(mantissa)):
Oh good catch! I think we can just leave it - it's actually mentioned in the docstring.

2025-03-18 13:43 UTC, glassnotes commented on demonstrations/tutorial_shor_catalyst.py
> +            a = random.randint(subkey, (1,), 2, N - 1)[0]
I like it! `jnp.gcd` is efficient anyways, and this looks much cleaner.

2025-03-18 14:49 UTC, glassnotes commented
@josh146 @dime10 All changes are now incorporated - I think we just need a check on the metadata, and a new thumbnail once available :+1: :tada:

2025-04-01 18:01 UTC, justinpickering commented on demonstrations/tutorial_shor_catalyst.py
> +#
About the author section should go at the end. Like this demo: https://pennylane.ai/qml/demos/learning2learn

```suggestion
```

2025-04-01 18:02 UTC, justinpickering commented on demonstrations/tutorial_shor_catalyst.py
> +#
Insert About the author section at the end.

```suggestion
#
# About the author
# ----------------
#
```

2025-04-01 18:06 UTC, justinpickering commented on demonstrations/tutorial_shor_catalyst.py
> +# At first glance ,it not clear how this produces :math:`a x`. The qubits in
typo
```suggestion
# At first glance, it's not clear how this produces :math:`a x`. The qubits in
```

2025-04-01 18:26 UTC, justinpickering commented on demonstrations/tutorial_shor_catalyst.metadata.json
> +    "title": "JIT compiling Shor's algorithm with PennyLane and Catalyst",
Typically, we avoid having acronyms in the title, unless they're very well known (like NASA :D).
See other demos that 'spell-out' JIT:
- [How to optimize a QML model using Catalyst and quantum just-in-time (QJIT) compilation](https://pennylane.ai/qml/demos/tutorial_How_to_optimize_QML_model_using_JAX_catalyst_and_Optax)
- [How to quantum just-in-time (QJIT) compile Grover’s algorithm with Catalyst](https://pennylane.ai/qml/demos/tutorial_qjit_compile_grovers_algorithm_with_catalyst)

Perhaps this can be:
- `Quantum just-in-time (QJIT) compiling Shor's algorithm with PennyLane and Catalyst`, or
- `Compiling Shor's algorithm with PennyLane and Catalyst`

We may also do without `PennyLane` in the title, since it mentions Catalyst, and this implies that PennyLane is used.

2025-04-01 21:05 UTC, alvaro-at-xanadu requested changes
Thank you! It looks great, just minor copy-edits. My major piece of feedback is that the code blocks are super hard to read. I was wondering if we can comment on them more?

2025-04-01 21:05 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_shor_catalyst.py
> +
Code blocks are so long and hard to parse 😓 Is it possible to add some comments to explain some of the key pieces (nothing too long)

2025-04-02 13:24 UTC, glassnotes commented on demonstrations/tutorial_shor_catalyst.py
Sure - this conflicts with the suggested title change to remove PennyLane, though. Maybe `tutorial_shors_algorithm_catalyst` (`shors` with an s)?

2025-04-02 13:26 UTC, glassnotes commented on demonstrations/tutorial_shor_catalyst.py
> +#
Do you mean from a rendering standpoint? (I wanted to have the description visually separate, whether it's in a box or not makes no difference on my side)

2025-04-02 13:32 UTC, glassnotes commented on demonstrations/tutorial_shor_catalyst.metadata.json
> +    "title": "JIT compiling Shor's algorithm with PennyLane and Catalyst",
I'm a fan of "Quantum just-in-time compiling Shor's algorithm with Catalyst"

2025-04-02 14:10 UTC, josh146 commented on demonstrations/tutorial_shor_catalyst.metadata.json
> +    "title": "JIT compiling Shor's algorithm with PennyLane and Catalyst",
I like @glassnotes's suggestion!

2025-04-03 13:58 UTC, glassnotes commented
@alvaro-at-xanadu @justinpickering I've incorporated your feedback - the comments didn't transfer over when I changed the filename, but I adjusted the language about Fourier adders as requested, and added a couple comments to the code (though I'm not sure how useful they are :sweat_smile: ). 

I did a quick check of the rendering locally, but won't have time to check on the build output until later today. Let me know if you'd like more updates, or if anything looks amiss!

2025-04-03 18:27 UTC, justinpickering commented on demonstrations/tutorial_shor_catalyst.py
That sounds good, thanks!

2025-04-03 21:33 UTC, alvaro-at-xanadu approved these changes

2025-04-04 17:24 UTC, justinpickering approved these changes

2025-04-04 17:26 UTC, merged