tutorial eqnn force field
PennyLaneAI/qml pull request #1015
Opened 2024-01-12 15:10 UTC by orielkiss

------------------------------------------------------------------------------------------------------------

**Title:**
Symmetry-invariant quantum machine learning force fields
**Summary:**
Tutorial on equivariant QML for learning energy and forces in a H2O molecule
**Relevant references:**
https://arxiv.org/abs/2311.11362
**Possible Drawbacks:**
long to train ~10 min

**Related GitHub Issues:**

----
If you are writing a demonstration, please answer these questions to facilitate the marketing process.

* GOALS — Why are we working on this now?
implementation of a recent paper

* AUDIENCE — Who is this for?
Chemistry and QML researchers

* KEYWORDS — What words should be included in the marketing post?
Geometric quantum machine learning, force field

* Which of the following types of documentation is most similar to your file? 
Demos

2024-01-12 15:20 UTC, KetpuntoG commented on demonstrations/tutorial_eqnn_force_field.metadata.json
> +    "basedOnPapers": [{
Thanks for opening the PR! Here you should only specify a link to the paper

2024-01-12 15:59 UTC, orielkiss commented on demonstrations/tutorial_eqnn_force_field.metadata.json
> +    "basedOnPapers": [{
thanks, just updated

2024-01-12 17:14 UTC, KetpuntoG commented
Good to see it is deploying! 😄
You can check here the demo PR on the website:
https://qml-build-previews.pennylane.ai/pull_request_build_preview/1015/qml/demos/tutorial_eqnn_force_field/

2024-01-13 12:26 UTC, orielkiss commented
I think we can get to the reviews. There is a minor problem with the second image I don't know how to fix. But apart from that, it looks in good shape. Thank you! :)

2024-01-15 15:16 UTC, KetpuntoG commented
> I think we can get to the reviews. There is a minor problem with the second image I don't know how to fix. But apart from that, it looks in good shape. Thank you! :)

Great, Thanks Oriel 💪
@alvaro-at-xanadu will take a first look at it :)

2024-01-15 22:11 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_eqnn_force_field.py
> +ergodic systems. Within the simulation, the Newton equations are numerically integrated. Therefore,
```suggestion
ergodic systems. Within the simulation, the Newton's equations of motion are numerically integrated. Therefore,
```

2024-01-15 22:12 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_eqnn_force_field.py
> +it is crucial to have access to the forces acting on the constituents of the system or equivalently
```suggestion
it is crucial to have access to the forces acting on the constituents of the system or, equivalently,
```

2024-01-15 22:12 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_eqnn_force_field.py
> +exemplary molecules from *ab initio* reference data.
```suggestion
`[Kiss22] <https://iopscience.iop.org/article/10.1088/2632-2153/ac7d3c/meta>`__ presented variational
quantum learning models (VQLMs) that were able to learn the potential energy and atomic forces of
exemplary molecules from *ab initio* reference data.
```

2024-01-15 22:12 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_eqnn_force_field.py
> +exemplary molecules from *ab initio* reference data.
Or "has presented".

2024-01-16 19:31 UTC, alvaro-at-xanadu submitted a review, later dismissed
I think this is a really good first draft 🚀 ! Thank you for this demo, I learned a lot. I'll summarize some of the main points that I think need to be addressed in order to polish this demo.
- I've found a lot of misuse of language. We need to put this through a language checker before publication, or have a native English speaker check it (I am not a native speaker, so I probably didn't find everything).
- The concepts of invariance and equivariance might need to be introduced in a more systematic and clear way. While some readers may be familiar with it, the words were used way before they were properly introduced, and do remain undefined for certain types of mathematical objects. 
- It was not clear when we chose the size of the molecule. We need to mention explicitly when we're working with two vs. three atoms in the theory.
- The distinction between a transformation and its representation is a bit loose. At all times there is a reference to a $g$, which some people will know is the element of a symmetry/coordinate transformation. But we never define what it is. 
- In general, the mathematical notation has to be better explained. Many variables are loosely defined. 
- Towards the end, the code lacks narrative. While some things may  be straightforward, it's good to guide the reader through each block of code and summarize what's going on.
- Some discussion of what we observe in plots would be nice too. 
- Some graphs lack a y-axis label and I have no idea why.
- Citations and bibliography need to be fixed to be in the style of other demos.

I know it's a lot of bullet points 😅 , but they should all be easy to address! Great work 💪🏼 !

2024-01-16 19:31 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_eqnn_force_field.py
> +# We train using stochastic gradient descent
```suggestion
# We train our VQLM using stochastic gradient descent.
```

2024-01-16 19:31 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_eqnn_force_field.py
> +
Code could use some commenting so readers can understand it better.

2024-01-16 19:31 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_eqnn_force_field.py
> +
Y label not showing in plot

2024-01-16 19:31 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_eqnn_force_field.py
> +
Let's improve the narrative here. What do we see in the plots? What are we plotting?

2024-01-16 19:31 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_eqnn_force_field.py
> +
I still feel there's no need for the graph on the right, but feel free to leave it if you think it's useful.

2024-01-16 19:31 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_eqnn_force_field.py
> +# As stated in the beginning, we are interested by obtaining the forces to drive MD simulations. Since
```suggestion
# As stated at the beginning, we are interested by obtaining the forces to drive MD simulations. Since
```

2024-01-16 19:31 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_eqnn_force_field.py
> +# are the trainable parameters. In our framework, we can simply do the following.
Improve code narrative here, since it's hard to parse. We suddenly have Jacobians where only part is kept and it's not that clear what's going on.

2024-01-16 19:31 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_eqnn_force_field.py
> +# supported by the original paper `[Le 23] <https://arxiv.org/abs/2311.11362>`__.
```suggestion
# In this demo, we saw how to implement a symmetry-invariant VQLM to learn the energy and forces of
# small chemical systems and trained it for the specific example of water. The strong points with
# respect to symmetry-agnostic techniques are better generalization, more accurate force predictions,
# resilience to small data corruption, and reduction in classical pre- and postprocessing, as
# supported by the original paper `[Le 23] <https://arxiv.org/abs/2311.11362>`__.
```

2024-01-16 19:31 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_eqnn_force_field.py
> +# which can be easily operated and trained at scale.
```suggestion
# Further work could be devoted to studying larger systems by adopting a more systematic fragmentation as
# discussed in the original paper. As an alternative to building symmetry-invariant quantum
# architectures, the symmetries could instead be incorporated into the training routine, such as
# recently proposed by `[Wierichs 23] <https://arxiv.org/abs/2312.06752>`__. Finally, symmetry-aware
# models could be used to design quantum symmetry functions, which in turn could serve as
# symmetry-invariant descriptors of the chemical systems within classical deep learning architectures,
# which can be easily operated and trained at scale.
```

2024-01-16 20:07 UTC, KetpuntoG commented
Notice that we have also [this demo](https://pennylane.ai/qml/demos/tutorial_equivariant_graph_embedding/). You can link some concepts like equivariant or invariant

2024-01-17 10:14 UTC, orielkiss commented on demonstrations/tutorial_eqnn_force_field.py
> +
i am not sure how to resolve that, any idea?

2024-01-17 10:45 UTC, orielkiss commented on demonstrations/tutorial_eqnn_force_field.py
> +        # We have to fixe the correct wires ..., also i think it does not work with jax ... TBD
works for us

2024-01-17 10:48 UTC, orielkiss commented on demonstrations/tutorial_eqnn_force_field.py
> +        qml.TrotterProduct(Heisenberg, weight, order=1, n=1)
done

2024-01-17 11:01 UTC, orielkiss commented on demonstrations/tutorial_eqnn_force_field.py
> +atoms = 2  # Number of atoms, here two since we fixe the oxygen at the origin
yes we have 3 atoms but only work with 2 active atoms since we fix the oxygen at the center. we will remove LiH entirely at it is confusing and make it more clear we are dealing with H2O only

2024-01-17 11:03 UTC, orielkiss commented on demonstrations/tutorial_eqnn_force_field.py
> +def eqnn(data, params):
done

2024-01-17 11:11 UTC, orielkiss commented on demonstrations/tutorial_eqnn_force_field.py
> +# Parameters initialization
adding warm start and no SB

2024-01-23 16:11 UTC, KetpuntoG commented
Thanks @orielkiss ! Catalina will do the second review 😊

2024-02-14 21:15 UTC, KetpuntoG commented
Just to say that we did not forget to take a look to this demo 💪 With QHack we have a little less capacity but we will get to it soon!

2024-02-20 20:29 UTC, CatalinaAlbornoz requested changes
Looks good but requires some changes.

2024-02-20 20:29 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_eqnn_force_field.py
> +# We start by dowloading the `dataset <https://zenodo.org/records/2634098>`__, which we have prepared for
```suggestion
# We start by downloading the `dataset <https://zenodo.org/records/2634098>`__, which we have prepared for
```

2024-02-20 20:29 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_eqnn_force_field.py
> +# convenience as a python ndarray. In the following, we will load, preprocess and split the data into a
```suggestion
# convenience as a Python ndarray. In the following, we will load, preprocess and split the data into a
```

2024-02-20 20:29 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_eqnn_force_field.py
> +# We will know define the cost function and how to train the model using jax. We will use the mean-square-error loss function.
```suggestion
# We will know define the cost function and how to train the model using Jax. We will use the mean-square-error loss function.
```

2024-02-20 20:29 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_eqnn_force_field.py
> +# To speed up the computation, we use the decorator ``jax.jit`` to compile this execution just-in-time. This means the first execution will typically take a little longer with the
```suggestion
# To speed up the computation, we use the decorator ``@jax.jit`` to do just-in-time compilation for this execution. This means the first execution will typically take a little longer with the
```

2024-02-20 20:29 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_eqnn_force_field.py
> +# benefit that all following executions will be significantly faster, see the `jax docs on jitting <https://jax.readthedocs.io/en/latest/jax-101/02-jitting.html>`_.
```suggestion
# benefit that all following executions will be significantly faster, see the `Jax docs on jitting <https://jax.readthedocs.io/en/latest/jax-101/02-jitting.html>`_.
```

2024-02-20 20:29 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_eqnn_force_field.py
> +# **Parameters initialization:**
```suggestion
# **Parameter initialization:**
```

2024-02-20 20:29 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_eqnn_force_field.py
> +# we disable the symmetry breaking strategy, as it is mainly useful for larger systems.
```suggestion
# we disable the symmetry-breaking strategy, as it is mainly useful for larger systems.
```

2024-02-20 20:29 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_eqnn_force_field.py
> +# energy as a scatter plot. The model is able to make fair predictions, especially near the equilibrium possition. However, a few points in the higher energy range
```suggestion
# energy as a scatter plot. The model is able to make fair predictions, especially near the equilibrium position. However, a few points in the higher energy range
```

2024-02-20 20:29 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_eqnn_force_field.py
> +# could be improved, e.g. by using a deeper model.
Is this true? Deeper models don't necessarily improve performance. Did you make a test that shows this or is it in a paper?

2024-02-20 20:50 UTC, orielkiss commented on demonstrations/tutorial_eqnn_force_field.py
> +epsilon = jax.lax.stop_gradient(epsilon)  # Uncomment if we wish to train the SB weights as well.
indeed, i meant comment instead of uncomment

2024-02-20 20:52 UTC, orielkiss commented on demonstrations/tutorial_eqnn_force_field.py
> +# could be improved, e.g. by using a deeper model.
in the paper, we go to D=20 and obtain a slightly better performance, at the cost of a longer training time. so we know for sure the performance can be improved in that way. I have added a comment referring to the paper

2024-02-20 23:05 UTC, orielkiss commented
Hi! Thanks a lot for your feedback @CatalinaAlbornoz. I have just committed to all the language changes you requested. I have also precised that in the paper better performances are obtained with a deeper model. Also, I have better explained the part with the swapping in line 245 as
"This is fulfilled by coupling only the qubits with are neighbors with respect to the 1-2-3-4-1 ring topology, leading to the following operation".

2024-02-28 13:26 UTC, KetpuntoG commented
Thank you so much @orielkiss ! 🚀 I'll talk to the designer to create a Thumbnail and marketing to set a publication date. I estimate it will be within approximately 3-4 weeks. As soon as I have news I'll tell you :)

2024-03-11 20:56 UTC, CatalinaAlbornoz approved these changes

2024-03-12 19:15 UTC, KetpuntoG commented
Hey ! for the publication it is possible that marketing may want to include your username in the post. Could you share with me your @username from Twitter (optional)?

2024-03-12 22:12 UTC, KetpuntoG approved these changes
🚀🚀🚀

2024-03-12 22:12 UTC, merged

2024-03-12 22:30 UTC, orielkiss commented
Hi @KetpuntoG ! Thank you for the great work, i really feel our demo improved a lot from the first version. Sure you can use my twitter name @oriel_kiss for marketing (and i think Isabel does not have twitter)

2024-03-12 23:46 UTC, KetpuntoG commented
Thanks to you for the good work! Tomorrow it will appear on the website but we will officially announce it next week. I will tell you the exact date as soon as marketing confirm me

2024-03-14 23:12 UTC, KetpuntoG commented
Hey! Marketing has scheduled the post for March 20 :)

2024-03-15 09:19 UTC, orielkiss commented
Awesome! i just remarked something weird happened at training time that never happened with the preview: it seems the training was stopped and then started again with random parameters. is the process different from the preview and the official website? (not a big deal otherwise)

2024-03-17 02:59 UTC, larawatson commented
@orielkiss Awesome! Just to follow up on Guillermo's note, we are pushing to Marketing of this by 1 week, so it will be out on Thursday March 28th

2024-03-17 12:16 UTC, larawatson commented
@orielkiss Hey Oriel,

We have to push the Marketing on this one slightly. I will get back to you with a new date shortly, thanks for your patience!

2024-03-19 07:50 UTC, larawatson commented
Hey @orielkiss this will be marketed on April 2nd :)