Learning shallow quantum circuits
PennyLaneAI/qml pull request #1023
Opened 2024-01-22 21:00 UTC by Qottmann

First draft of a quick turnover demo on [2401.10095](https://arxiv.org/abs/2401.10095)

It mainly shows the sewing procedure and one possible way of obtaining local inversions (which is not really discussed in the paper unfortunately)

Still a draft. In particular, the numerical example part at the end still needs text. Just happy that it works now for the moment.

2024-01-23 15:59 UTC, mariaschuld requested changes

2024-01-23 15:59 UTC, mariaschuld commented on demonstrations/tutorial_learningshallow.py
> +introduce and prove performance bounds on efficient algorithms to learn constant depth circuits.
```suggestion
prove performance bounds on efficient algorithms to reconstruct constant-depth circuits.
```
* shorter
* explains what learning means by using an alternative word to their title
* consider hyphen everywhere, I'm not sure though

2024-01-23 15:59 UTC, mariaschuld commented on demonstrations/tutorial_learningshallow.py
> +technique that let's one construct a global inversion from those.
```suggestion
technique that lets one construct a global inversion from those.
```

2024-01-23 15:59 UTC, mariaschuld commented on demonstrations/tutorial_learningshallow.py
> +At the same time, quantum neural networks are known to be difficult to train [#Anschuetz]_.
This is a very sweeping statement, we train them all the time ;) I am not sure if a reference to QNNs is needed here, since it insinuates a non-existing QML flavour? 

Rather say:

```suggestion
At the same time, they lead to optimization problems whose landscape has many local minima [#Anschuetz]_.
```

Not ideal yet though...maybe move or remove that reference here?

2024-01-23 15:59 UTC, mariaschuld commented on demonstrations/tutorial_learningshallow.py
> +The authors of [#Huang]_ tackle the question of whether or not shallow circuits are efficiently learnable.
Mention that learn = find a unitary whose effect is similar to the unknown one? Even the next sentence does not really say what learn means, and it is important to understand the problem setting...

2024-01-23 15:59 UTC, mariaschuld commented on demonstrations/tutorial_learningshallow.py
> +At the heart of the solutions to all these scenarios lies local inversions and sewing them together to form a global inversion.
```suggestion
At the heart of the solutions to all these scenarios lies the use of local inversions that undo the effect of the unitary, and sewing them together to form a global inversion.
```

2024-01-23 15:59 UTC, mariaschuld commented on demonstrations/tutorial_learningshallow.py
> +In this demo, we are mainly going to focus on learning :math:`\hat{U}` s.t. :math:`\hat{U}|0^{\otimes n} \rangle = U|0^{\otimes n} \rangle`.
Can be merged with previous sentence to avoid repetition? 

"They go through various relevant learning scenarios, like learning :math:`U` directly,
learning :math:`\hat{U}` s.t. :math:`\hat{U}|0^{\otimes n} \rangle = U|0^{\otimes n} \rangle`, for general and restricted cases in terms of
available gates and locality criteria. We will focus here on ..."

2024-01-23 15:59 UTC, mariaschuld commented on demonstrations/tutorial_learningshallow.py
> +# :math:`V_0` s.t. :math:`\text{tr}_{\neq 0} \left[V_0 U (|0 \times 0|)^{\otimes n} U^\dagger V^\dagger_0\right] = |0 \times 0|_0`.
Explain what `tr_{\neq 0}` means?

2024-01-23 15:59 UTC, mariaschuld commented on demonstrations/tutorial_learningshallow.py
> +# For that, we just follow the light-cone of the qubit that we want to invert
```suggestion
# For that, we just follow the light-cone of the qubit that we want to invert -- in other words all wires entangled with it by gates -- 
```
is this right?

2024-01-23 15:59 UTC, mariaschuld commented on demonstrations/tutorial_learningshallow.py
> +# In fact, constructing a global inversion from all possible local inversions is highly non-trivial.
```suggestion
# But constructing a global inversion from all possible local inversions is highly non-trivial.
```
"In fact" sounds like the sentence explains the former one, which it doesn't?

2024-01-23 15:59 UTC, mariaschuld commented on demonstrations/tutorial_learningshallow.py
> +# However, the circuit sewing technique introduced in [#Huang]_ let's us circumvent that problem and construct
```suggestion
# However, the circuit sewing technique introduced in [#Huang]_ lets us circumvent that problem and construct
```

2024-01-23 15:59 UTC, mariaschuld commented on demonstrations/tutorial_learningshallow.py
> +# For that, we first also find (construct) variants of the other local inversions.
Is this where you try to hide that it is not clear how to find them? :) 

I would be honest here and say that in this example we can see what they are, but overall this might have to be done with brute force search?

2024-01-23 15:59 UTC, mariaschuld commented on demonstrations/tutorial_learningshallow.py
> +# a global inversion from just a set of single local inversions per qubit.
I am confused here, do we need one inversion per qubit? I think you mean

```suggestion
# a global inversion from just a single local inversion per qubit.
```

2024-01-23 15:59 UTC, mariaschuld commented on demonstrations/tutorial_learningshallow.py
> +# So how does knowing local inversions :math:`\{V_0, V_1, V_2, V_3\}` help us with solving the original goal of finding a global inversion :math:`U V = \mathbb{1}`?
Avoid repeating the same stament from above:

```suggestion
# So how does knowing local inversions :math:`\{V_0, V_1, V_2, V_3\}` help us with solving the original goal of finding a global inversion :math:`U V = \mathbb{1}` -- a task which constitutes a variant of the `quantum marginal problem <https://arxiv.org/abs/1404.1085>`_?
```

2024-01-23 16:07 UTC, co9olguy commented on demonstrations/tutorial_learningshallow.py
> +# :math:`V_0` s.t. :math:`\text{tr}_{\neq 0} \left[V_0 U (|0 \times 0|)^{\otimes n} U^\dagger V^\dagger_0\right] = |0 \times 0|_0`.
Better to not use `\times` for `\rangle\langle`, as it renders strangely in the final latex (occurs a couple times in the demo)

2024-01-23 16:16 UTC, KetpuntoG commented on demonstrations/tutorial_learningshallow.metadata.json
> +            "uri": "/_static/large_demo_thumbnails/thumbnail_learningshallow.png"
```suggestion
            "uri": "/_static/large_demo_thumbnails/thumbnail_large_learningshallow.png"
```

2024-01-23 16:16 UTC, KetpuntoG commented on demonstrations/tutorial_learningshallow.metadata.json
> +            "uri": "/_static/large_demo_thumbnails/thumbnail_learningshallow.png"
This should solve the current issue

2024-01-23 16:17 UTC, Qottmann commented on demonstrations/tutorial_learningshallow.metadata.json
> +            "uri": "/_static/large_demo_thumbnails/thumbnail_learningshallow.png"
thanks, already changed that locally just havent pushed it :)

2024-01-23 16:28 UTC, Qottmann commented on demonstrations/tutorial_learningshallow.py
> +At the same time, quantum neural networks are known to be difficult to train [#Anschuetz]_.
Maybe this?
```suggestion
At the same time, training quantum neural networks, just like their classical counterparts, are non-trivial to optimize [#Anschuetz]_.
```

2024-01-23 16:58 UTC, Qottmann commented on demonstrations/tutorial_learningshallow.py
> +# We label all ancilla wires by ``[n + 0, n + 1, .. 2n-1]`` to have an easy 1-to-1 correpsondence and we see that qubit ``1`` is successfully decoupled.
I am not sure about changing the numbering of wires.
I like to use pythonic numbering for wires because I find that easier in python (`range(n)` instead of writing them out) and less error prone in pennylane (wires with strings are always good for a surprise).
Is this a matter of taste or you think this could genuinly confuses readers?

2024-01-23 16:58 UTC, mariaschuld submitted a review, later dismissed

2024-01-23 16:58 UTC, mariaschuld commented on demonstrations/tutorial_learningshallow.py
> +# So how does knowing local inversions :math:`\{V_0, V_1, V_2, V_3\}` help us with solving the original goal of finding a global inversion :math:`U V = \mathbb{1}`?
Also check the use of \hat{U} and V, are they the same?

2024-01-23 16:58 UTC, mariaschuld commented on demonstrations/tutorial_learningshallow.py
> +# For this, we would construct :math:`V_i` that fully, locally inverts the circuit such that :math:`\text{tr}_{\neq i}\left[U V_i \right] = \mathbb{1}_i`.
```suggestion
# For this, we would construct :math:`V_i` that fully, locally invert the circuit such that :math:`\text{tr}_{\neq i}\left[U V_i \right] = \mathbb{1}_i`.
```
?

2024-01-23 16:58 UTC, mariaschuld commented on demonstrations/tutorial_learningshallow.py
> +# For this, we would construct :math:`V_i` that fully, locally inverts the circuit such that :math:`\text{tr}_{\neq i}\left[U V_i \right] = \mathbb{1}_i`.
I am not immediately sure what the difference is to what you've done above?

2024-01-23 17:02 UTC, Qottmann commented on demonstrations/tutorial_learningshallow.py
> +# nicely captures the main technical method that is circuit sewing. This is different to learning the full unitary, i.e. :math:`V` such that :math:`U V = 1`.
Yeah $V^\dagger U |0 \rangle = |0 \rangle$

2024-01-23 17:03 UTC, mariaschuld commented on demonstrations/tutorial_learningshallow.py
> +# We label all ancilla wires by ``[n + 0, n + 1, .. 2n-1]`` to have an easy 1-to-1 correpsondence and we see that qubit ``1`` is successfully decoupled.
Just taste...

2024-01-23 17:05 UTC, mariaschuld commented on demonstrations/tutorial_learningshallow.py
> +At the same time, quantum neural networks are known to be difficult to train [#Anschuetz]_.
Actually, the statement as such wasn't my concern, but that the logical flow is unclear: a) shallow circuits are good, b) QNNs are difficult to train, c) the paper asks how shallow circuits can be trained -> what have the QNNs to do with this?

In order to not explain this complicated relationship I'd just remove the QNNs!

2024-01-23 17:07 UTC, Qottmann commented on demonstrations/tutorial_learningshallow.py
> +# For this, we would construct :math:`V_i` that fully, locally inverts the circuit such that :math:`\text{tr}_{\neq i}\left[U V_i \right] = \mathbb{1}_i`.
Its two time the same with different flavors.
In the first case we do everything analytically from just having a simple structure, thereby introducing the concepts of local inversion and circuit sewing.

In the Numerical example we have a more complicated, somewhat random target unitary, and we specifically look at an ansatz that has a different structure, for which we find solutions that locally invert the target circuit. This is done numerically and approximately now (whereas before it was analytical and exact)

Are you saying it reads like the first and second example we work through are different learning scenarios?

2024-01-23 17:13 UTC, mariaschuld commented on demonstrations/tutorial_learningshallow.py
> +# For this, we would construct :math:`V_i` that fully, locally inverts the circuit such that :math:`\text{tr}_{\neq i}\left[U V_i \right] = \mathbb{1}_i`.
Oh, sorry, I got confused by something, I thought you'd tell the reader here how to solve Robert's second flavour of problem... (don't know why - it has been a long day!)

I would still think that a reader may appreciate a bit more explanation of how to turn the methods you show above into the full solution - this seems important, and is not as easy to follow as the rest of the demo...

2024-01-23 17:18 UTC, Qottmann commented on demonstrations/tutorial_learningshallow.py
> +At the same time, quantum neural networks are known to be difficult to train [#Anschuetz]_.
I am not sure I understand 😅 

To me the hook of the paper is a) shallow circuits are powerful b) training in general is hard, also constant-depth ones, c) here is a version to train them that is provably not hard.

Is the problem that I am using qnn and circuit interchangably?

2024-01-23 17:27 UTC, Qottmann commented on demonstrations/tutorial_learningshallow.py
> +The authors of [#Huang]_ tackle the question of whether or not shallow circuits are efficiently learnable.
Oh yeah that was definitely confusing. I rewrote this part now 👍

2024-01-23 17:28 UTC, Qottmann commented on demonstrations/tutorial_learningshallow.py
> +# For that, we first also find (construct) variants of the other local inversions.
Updated this part as well, I think there was some old text that clarified that which got lost in some refactor

2024-01-23 17:46 UTC, Qottmann commented on demonstrations/tutorial_learningshallow.py
> +# For this, we would construct :math:`V_i` that fully, locally inverts the circuit such that :math:`\text{tr}_{\neq i}\left[U V_i \right] = \mathbb{1}_i`.
Yeah I was thinking of actually doing it but there is no space and time anymore. Maybe in a v2. I tried to clarify it a bit better and also made the whole thing a note.

2024-01-23 18:05 UTC, Qottmann commented on demonstrations/tutorial_learningshallow.py
> +# Either way, the circuit sewing after obtaining the learned local inversions is the same as described above.
Agreed that this was rather confusing! Updated the text and moved it into a note!

2024-01-23 18:14 UTC, Qottmann commented on demonstrations/tutorial_learningshallow.py
> +At the same time, quantum neural networks are known to be difficult to train [#Anschuetz]_.
I just rephrased the sentence now to "Shallow, constant depth quantum circuit are provably powerful [#Bravyi]_.
At the same time, they are known to be difficult to train [#Anschuetz]_."

2024-01-23 19:59 UTC, KetpuntoG reviewed
Great job! 💪 Here I few comments

2024-01-23 19:59 UTC, KetpuntoG commented on demonstrations/tutorial_learningshallow.py
> +A local inversion is a unitary circuit that locally disentangles one qubit after a previous, different unitary entangled them. Let us
Curious that you start at the end. Maybe it's better to say that you first entangle them and then disentagle them

2024-01-23 19:59 UTC, KetpuntoG commented on demonstrations/tutorial_learningshallow.py
> +# where we trace out all but wire ``i``.
i? or 0?

2024-01-23 19:59 UTC, KetpuntoG commented on demonstrations/tutorial_learningshallow.py
> +# The authors introduce a clever trick that they coin _circuit sewing_. It works by swapping out the decoupled qubit with an ancilla register and restoring ("repairing") the unitary on the remaining
Rendering issue, I think you have to put asterisks

2024-01-23 19:59 UTC, KetpuntoG commented on demonstrations/tutorial_learningshallow.py
> +
You could put a sentence inviting the reader to substitute in the above example to see that it is correct

2024-01-23 19:59 UTC, KetpuntoG commented on demonstrations/tutorial_learningshallow.py
> +print(f"rho_1 = |0x0| {np.allclose(r1, np.array([[1, 0], [0, 0]]))}")
Not super fan of the x, can you use this symbols?
print("|0⟩⟨0|")

2024-01-23 19:59 UTC, KetpuntoG commented on demonstrations/tutorial_learningshallow.py
> +    V_3()                 # disentangle qubit 2
three right?

2024-01-23 19:59 UTC, KetpuntoG commented on demonstrations/tutorial_learningshallow.py
> +    V_3()                 # disentangle qubit 2
3 here too

2024-01-23 19:59 UTC, KetpuntoG commented on demonstrations/tutorial_learningshallow.py
> +In this demo, we are mainly going to focus on learning the action on :math:`|0^{\otimes n}\rangle`, i.e. :math:`U |0^{\otimes}\rangle = V |0^{\otimes}\rangle`.
In this paragraph , I would say de correct way is |0>^n instead of |0^n>

2024-01-23 19:59 UTC, KetpuntoG commented on demonstrations/tutorial_learningshallow.py
> +# .. math:: V^\text{sew} |0^{\otimes 2n}\rangle = U^\dagger \otimes U |0^{\otimes 2n}\rangle.
Was this the goal? I was not expecting that U^\dagger

2024-01-23 19:59 UTC, KetpuntoG commented on demonstrations/tutorial_learningshallow.py
> +fig, _ = draw(U_target, wires)
qml.draw_mpl(U_target)(wires)

2024-01-23 19:59 UTC, KetpuntoG commented on demonstrations/tutorial_learningshallow.py
> +    V_i(params, wires)
Why you don't pass i as a parameter? because it is not needed? or for jax reasons?

2024-01-23 19:59 UTC, KetpuntoG commented on demonstrations/tutorial_learningshallow.py
> +    X, Y, Z = qnode_i(params, i)
This name was taken before 
An option could be avoid the line:
X, Y, Z = qml.PauliX, qml.PauliY, qml.PauliZ

2024-01-23 19:59 UTC, KetpuntoG commented on demonstrations/tutorial_learningshallow.py
> +In this demo, we are mainly going to focus on learning the action on :math:`|0^{\otimes n}\rangle`, i.e. :math:`U |0^{\otimes}\rangle = V |0^{\otimes}\rangle`.
(this apply to different places in the demo)

2024-01-23 20:06 UTC, KetpuntoG commented on demonstrations/tutorial_learningshallow.py
> +Shallow, constant depth quantum circuit are provably powerful [#Bravyi]_.
```suggestion
Shallow, constant depth quantum circuits are provably powerful [#Bravyi]_.
```

2024-01-23 20:06 UTC, KetpuntoG commented on demonstrations/tutorial_learningshallow.py
> +# back the light-cones of the resepctive qubits. In general these would have to be learned, more on that later. Here we just
```suggestion
# back the light-cones of the respective qubits. In general these would have to be learned, more on that later. Here we just
```

2024-01-23 20:06 UTC, KetpuntoG commented on demonstrations/tutorial_learningshallow.py
> +# We label all ancilla wires by ``[n + 0, n + 1, .. 2n-1]`` to have an easy 1-to-1 correpsondence and we see that qubit ``1`` is successfully decoupled.
```suggestion
# We label all ancilla wires by ``[n + 0, n + 1, .. 2n-1]`` to have an easy 1-to-1 correspondence and we see that qubit ``1`` is successfully decoupled.
```

2024-01-23 20:06 UTC, KetpuntoG commented on demonstrations/tutorial_learningshallow.py
> +#     Another possibility is to perform state tomography of the single qubit states and comparing that with the input state.
```suggestion
#     Another possibility is to perform state tomography of the single qubit states and compare that with the input state.
```

2024-01-23 22:43 UTC, Qottmann commented on demonstrations/tutorial_learningshallow.py
> +fig, _ = draw(U_test)
Oh nice I hadnt realized that, thanks!

2024-01-23 22:49 UTC, Qottmann commented on demonstrations/tutorial_learningshallow.py
> +print(f"rho_1 = |0x0| {np.allclose(r1, np.array([[1, 0], [0, 0]]))}")
How do you get these without latex 😮 ? nice!

2024-01-23 22:52 UTC, Qottmann commented on demonstrations/tutorial_learningshallow.py
> +# .. math:: V^\text{sew} |0^{\otimes 2n}\rangle = U^\dagger \otimes U |0^{\otimes 2n}\rangle.
Is it the fact that it has a dagger or because there are the two separate sub-systems?

2024-01-23 22:56 UTC, Qottmann commented on demonstrations/tutorial_learningshallow.py
> +# .. math:: V^\text{sew} |0^{\otimes 2n}\rangle = U^\dagger \otimes U |0^{\otimes 2n}\rangle.
I rewrote it such that the dagger is on the V instead of the U. Its just a matter of notation

2024-01-23 23:08 UTC, Qottmann commented on demonstrations/tutorial_learningshallow.py
> +    V_i(params, wires)
What do you mean? `V_i` is a fixed circuit ansatz, we get different `V_i` by using different parameters after optimization. The passed `i` here is for the return `P(i)`

2024-01-23 23:09 UTC, Qottmann commented on demonstrations/tutorial_learningshallow.py
> +    X, Y, Z = qnode_i(params, i)
Will change it here, thanks!

2024-01-23 23:14 UTC, Qottmann commented on demonstrations/tutorial_learningshallow.py
> +In this demo, we are mainly going to focus on learning the action on :math:`|0^{\otimes n}\rangle`, i.e. :math:`U |0^{\otimes}\rangle = V |0^{\otimes}\rangle`.
Thanks!

2024-01-23 23:15 UTC, Qottmann commented
Thanks @KetpuntoG for the thorough and helpful review, I hope your concerns are all addressed with the latest commits :)

2024-01-24 00:09 UTC, KetpuntoG commented on demonstrations/tutorial_learningshallow.py
> +qml.draw_mp(U_test)()
```suggestion
qml.draw_mpl(U_test)()
```

2024-01-24 00:45 UTC, KetpuntoG commented on demonstrations/tutorial_learningshallow.py
> +    V_i(params, wires)
It struck me that you used "i" inside V_i. maybe the best thing to do would have been to send params[i] instead of the whole matrix. But feel free to ignore this comment

2024-01-24 00:48 UTC, KetpuntoG commented on demonstrations/tutorial_learningshallow.py
> +# .. math:: V^\text{sew} |0^{\otimes 2n}\rangle = U^\dagger \otimes U |0^{\otimes 2n}\rangle.
In this equality it seemed to me that you need U^dagger to create V, but the goal of the algorithm was generate kind of a U^dagger

2024-01-24 00:49 UTC, KetpuntoG commented on demonstrations/tutorial_learningshallow.py
> +print(f"rho_1 = |0x0| {np.allclose(r1, np.array([[1, 0], [0, 0]]))}")
I always look it up on the internet or ask chatgpt to generate it. I copy and paste it directly 😄

2024-01-24 01:03 UTC, KetpuntoG approved these changes
Looks great! Thanks for address all the comments 🎉

2024-01-24 01:23 UTC, KetpuntoG commented on demonstrations/tutorial_learningshallow.py
> +# Numerical experiment
```suggestion
# Numerical Experiment
```

2024-01-24 01:23 UTC, KetpuntoG commented on demonstrations/tutorial_learningshallow.py
> +# Numerical experiment
Lara's suggestion

2024-01-24 01:40 UTC, CatalinaAlbornoz approved these changes

2024-01-24 01:42 UTC, merged

2024-01-24 06:45 UTC, mariaschuld commented on demonstrations/tutorial_learningshallow.py
> +At the same time, quantum neural networks are known to be difficult to train [#Anschuetz]_.
Yes! That's perfect!