Demo on Efficient Simulation of Clifford Circuits
PennyLaneAI/qml pull request #1032
Opened 2024-02-01 22:10 UTC by obliviateandsurrender

**Title:** Efficient Simulation of Clifford Circuits

**Summary:** Adds a demo for utilizing the new Clifford simulation device. 

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

----
    
- [X] Tutorial
- [ ] Demo
- [ ] How-to

2024-02-08 23:41 UTC, soranjh requested changes
The demo is a bit too long but can be easily changed to a short and sweet one. The main problem is that the demo is advertising Clifford+T decomposition and Clifford simulations at the same time, which makes it hard to build a consistent story. I suggest building up the story as follows (or a similar way):

1. Quantum circuits can be decomposed in terms of universal sets such as Clifford+T. 
2. It is the "T" that makes the the classical simulation hard, and mention Gottesman–Knill theorem.
3. Introduce Stabilizer Circuits and Clifford gates.
4. Give the PL simulation example with GHZ.

I am actually not sure if you need to talk about sk_decomposition and the transform here at all. They just do not seem to fit well.

2024-02-08 23:41 UTC, soranjh commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# Efficient classical simulability for a quantum simulation is often related to be able to accurately
The demo should start with this paragraph.

2024-02-08 23:41 UTC, soranjh commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +print("Pauli: ", paulis[idx], "Clifford: ", cliffords[idx], "C@P@C† :", conjugates[idx])
Seems irrelevant to this demo.

2024-02-08 23:41 UTC, soranjh commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# Gottesman-Knill theorem
This is important and should appear earlier.

2024-02-08 23:41 UTC, soranjh commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# Clifford Decomposition
I know you are trying to advertise `sk_decomposition` and the transfer, but the section is too long and breaks the story.

2024-02-08 23:41 UTC, soranjh commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# Another important class of the circuit that are efficiently classically simulable via the
This part should be right after Gottesman-Knill Theorem.

2024-02-08 23:41 UTC, soranjh commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +#    the local Clifford operators :math:`U`.
You can cite them but not explicitly mention all of them (except 1), simply because they are not used here.

2024-02-10 01:49 UTC, obliviateandsurrender commented
[sc-54319]

2024-02-28 20:26 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.metadata.json
> +            "uri": "/_static/large_demo_thumbnails/thumbnail_tutorial_clifford_simulation.png"
I am unsure who would make the final ones so made this for reference.

2024-03-05 15:40 UTC, soranjh commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# practical implementation of quantum computation. As a bonus, we will also see how to
Better to remove "As a bonus" because it is a PennyLane demo.

2024-03-05 15:40 UTC, soranjh commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# computation as well, we define a universal set of quantum gates, ``{H, S, CNOT, T}``,
I suggest ending the sentence after "quantum gates" and in the new sentence mention that one of the universal gate set is {H, S, CNOT, T} ....

2024-03-05 15:40 UTC, soranjh commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# .. figure:: ../_static/demonstration_assets/clifford_simulation/pauli-normalizer.jpeg
Might be better to separate the PauliX block into 4 X blocks. (You use Y, Z, X in the results row anyways.)

2024-03-05 15:40 UTC, soranjh commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# The elements of the Clifford group are called the *Clifford gates* and they include the
Will be good to highlight that Clifford gates are not limited to those used in the Clifford + T group by mentioning something like: "In fact, ..."

2024-03-05 15:40 UTC, soranjh commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# Another important class of the circuit that are efficiently classically simulable via the
```suggestion
# An important class of the circuit that are efficiently classically simulable via the
```

2024-03-08 19:57 UTC, soranjh reviewed
Looks great but we need a bit more refinement. The only part that requires some work is a good (clear and easy to understand) explanation of the simulation formalism, i.e., what is a tableau and how it gets updated efficiently.

2024-03-08 19:57 UTC, soranjh commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# the state.
This is a very important part of the demo. Assume that a user does not know anything about how Clifford circuits can be simulated efficiently and, with this assumption, try to explain it in simply and efficiently. It is fine if there is more than one paragraph to explain this. You can also talk about the tableaus here if it helps explaining the machinery behind the efficient classical simulation method.

2024-03-08 22:32 UTC, KetpuntoG reviewed
Good job @obliviateandsurrender ! I can see a lot of dedication to this project 🚀
 Here are some comments

2024-03-08 22:32 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# the state.
I agree with this , probably an example will help to understand it better

2024-03-08 22:32 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +dev = qml.device("default.clifford", tableau=True, wires=2)
What does `tableau = True`?

2024-03-08 22:32 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +def circuit(ret_state=True):
`ret_state` was not clear to me at the beginning I would suggest `return_state`. Also, is this logic necessary? this uncommon syntax in pennylane is a bit misleading to me

2024-03-08 22:32 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +def circuit(ret_state=True):
Thinking about it, I understand that it is optional since calculating the state would be too much with so many qubits (maybe it would be good to clarify it)

2024-03-08 22:32 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# in the following *Stabilizer Tableau* form [#aaronson-gottesman2004]_ -
```suggestion
# in the following *Stabilizer Tableau* form [#aaronson-gottesman2004]_ :
```

2024-03-08 22:32 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# for the ``destabilizers`` and ``stabilizers`` for the state as a `binary
This is the first time you talk about destabilizers

2024-03-08 22:32 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# vector <https://docs.pennylane.ai/en/latest/code/api/pennylane.pauli.binary_to_pauli.html>`__,
It would be better use :func:`pennylane.pauli.binary_to_pauli`
(not super sure of the syntax right now)
In that way we know it is a pennylane function and not just a link

2024-03-08 22:32 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +def circuit(ret_state=True):
(oh in fact state is not the state I was thinking about)

2024-03-08 22:32 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +tableau_to_pauli_rep(state)
Nice to see this representation 😄

2024-03-08 22:32 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# before and after the application of gate operation using :func:`~pennylane.snapshots`.
At this point, I feel somewhat disoriented. I don't quite understand why we are doing what we are doing. Why are the tableaus important? are they used for the simulator calculations and are you explaining how it works? or is it relevant information for the study of the circuits? It would be great to stop a little more at the beginning to make the motivation clear

2024-03-08 22:32 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +    ) + [qml.Snapshot()]
In the demos we prefer clear code to smart code. If it can be rewritten in a way that lets us know what is happening even if it is less efficient that would be great :) 

Maybe a for loop in the operations?

2024-03-08 22:32 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# :math:`|00\rangle` state -
```suggestion
# :math:`|00\rangle` state:
```

2024-03-08 22:32 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# following tableau -
```suggestion
# following tableau:
```

2024-03-08 22:32 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +
Cool!

2024-03-08 22:32 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# Clifford + T Decomposition
[Suggestion] In my opinion, this section doesn't quite fit in this demo. Even if it is somewhat short, I would suggest removing it and mentioning it in the conclusion somehow. Maybe in the future it can be a more Clifford + T focused demo

2024-03-11 10:07 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# :math:`\mathcal{C}_n = \{C \in U_{2^n}\ |\ C \mathcal{P}_n C^{\dagger} = \mathcal{P}_n\}`.
I have tried to rephrase this and also add a more helpful link for this.

2024-03-11 10:08 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# the state.
I have rephrased this to introduce the `Stabilizer tableau` here itself. Let me know if that works.

2024-03-11 10:09 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +#    :target: javascript:void(0)
I have added a sentence to lead to the figure and should explain it.

2024-03-11 10:10 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# for some of the gates we have listed above.
I added an example before the leading to the code. Let me know if this is sufficient.

2024-03-11 10:10 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +    # conjugate the Pauli operators
Yes, this basically does `C@P@C.adjoint()` and decomposes it into the Pauli basis.

2024-03-11 10:11 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# also have single-qubit measurements are known as *stabilizer circuits* and their corresponding
There are, like, Bell-basis measurements. I am using the standard definition from the literature here.

2024-03-11 10:13 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# :math:`n`-qubit Clifford circuit with :math:`m` Clifford gates can be simulated in time
Honestly, I would prefer not to as I belive the text is sufficient here to introduce the idea.

2024-03-11 10:14 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# for the ``destabilizers`` and ``stabilizers`` for the state as a `binary
I have rephrased this, let me know if it is better now. I am purposefully skipping giving a mathematical definition of destabilizers to keep things simple.

2024-03-11 10:16 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# vector <https://docs.pennylane.ai/en/latest/code/api/pennylane.pauli.binary_to_pauli.html>`__,
Nope. The sole intent of linking to the `binary_to_pauli` is to hint towards this is the same binary representation as used in the function. We don't explicitly need this function actually to explain the tableau, so I didn't use the `:func:`.

2024-03-11 10:18 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# before and after the application of gate operation using :func:`~pennylane.snapshots`.
Maybe this is better now with the rephrasing. Let me know. The overall idea is to explain how the stabilizer tableau evolves with each Clifford gate. We show this evolution by evolving the generator set representation based on the update rules described by the Clifford tableau of the gate.

2024-03-11 10:18 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +    ) + [qml.Snapshot()]
Changed this. :(

2024-03-11 10:20 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# Clifford + T Decomposition
I have rephrased the beginning to make it seem more relevant to the demo. Let me know if that slightly helps.

2024-03-11 10:29 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +def circuit(ret_state=True):
I changed this to `return_state`. I am using it to skip redefining the same circuit later on for the sampling case.

2024-03-11 19:35 UTC, KetpuntoG reviewed
It looks great! 🔥 
I leave some final comments, mostly small typos

2024-03-11 19:35 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# of the Clifford group :math:`\mathcal{C}_n` on :math:`n`-qubits transforms *Paulis* to
Okay, I was missing context 😄vI didn't know if this was a property or was the definition. I just saw that it is the definition so I would put the phrase something like:

"We will define the Clifford group of :math:`n`-qubits (:math:`\mathcal{C}_n`) as the set of unitaries that transform Pauli words into Pauli words under conjugation. That is,  :math:`C` belongs to the Clifford group if for any Pauli :math:`P`, it is satisfied that :math:`CPC^{\dagger}` is also a Pauli."

2024-03-11 19:35 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# programmatic manner using the ``clifford_tableau`` method we define below -
"-" is not the usual way we introduce code in the other demos

```suggestion
# programmatic manner using the ``clifford_tableau`` method we define below:
```

2024-03-11 19:35 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# ---------------------------------
This part is more clear, thanks!

2024-03-11 19:35 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# :math:`10,000` shots and compare the probability distribution with the analytic case -
Maybe in English is 10.000?

2024-03-11 19:35 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# `Eastin-Knill <https://en.wikipedia.org/wiki/Eastin%E2%80%93Knill_theorem>` theorem.
```suggestion
# `Eastin-Knill <https://en.wikipedia.org/wiki/Eastin%E2%80%93Knill_theorem>`__ theorem.
```

2024-03-11 19:35 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# Here, the first and the last :math:`n` rows of the tableau represents the generators
```suggestion
# Here, the first and the last :math:`n` rows of the tableau represent the generators
```

2024-03-11 19:35 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# and the phases gives the sign (:math:`\pm`) for the Pauli operator that represents them.
```suggestion
# and the phases give the sign (:math:`\pm`) for the Pauli operator that represents them.
```

2024-03-11 19:35 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# description that we desribed above [#aaronson-gottesman2004]_. We will show this evolution
```suggestion
# description that we described above [#aaronson-gottesman2004]_. We will show this evolution
```

2024-03-11 19:35 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# As we see, this worked as expected. So, to track and compute the evolved state, one simply need
```suggestion
# As we see, this worked as expected. So, to track and compute the evolved state, one simply needs
```

2024-03-11 19:35 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# it impact the execution timings for the circuit both the anaylytic and
```suggestion
# it impact the execution timings for the circuit both the analytic and
```

2024-03-11 19:43 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# :math:`10,000` shots and compare the probability distribution with the analytic case -
Uhmmm, using a dot feels confusing to me. I prefer using `10,000`. Alternatively, I could use the scientific notation but that would just make things look complex.

2024-03-11 20:08 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# of the Clifford group :math:`\mathcal{C}_n` on :math:`n`-qubits transforms *Paulis* to
Updated it with slight modifications.

2024-03-11 20:26 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# :math:`mathcal{C P C^{\dagger}` is also a Pauli. We can see this by conjugating Pauli `X`
```suggestion
# :math:`C P C^{\dagger}` is also a Pauli. We can see this by conjugating Pauli `X`
```

2024-03-12 12:25 UTC, KetpuntoG approved these changes
We still need to update the thumbnail. Otherwise it's ready from my part 😄
I see that the demo is targeting dev. Is it still necessary? If you can already point to master please update that

2024-03-12 12:25 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.metadata.json
> +        "Devices and Performance"
Feel free to also add Quantum Computing

2024-03-12 12:25 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +
This part have to be removed and the related content added in the metadata

```suggestion
```

2024-03-12 12:25 UTC, KetpuntoG commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# .. include:: ../_static/authors/utkarsh_azad.txt
this is extracted from metadata
```suggestion
```

2024-03-21 16:05 UTC, soranjh requested changes

2024-03-21 16:05 UTC, soranjh commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# Clifford + T Decomposition
This section still looks as irrelevant. Let's reconsider having it or not.

2024-03-21 20:49 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +operation with the elements of the universal set defined above:
Removed the sentence, calling it a normalizer to improve the flow.

2024-03-21 20:50 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +~~~~~~~~~~~~~~~~~
Removed the title.

2024-03-21 20:50 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +for any given Clifford gates.
Removed this part.

2024-03-21 20:51 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +*Gottesman-Knill* theorem, which states that any :math:`n`-qubit Clifford circuit with
I didn't wanna repeat the word `theroem` twice.

2024-03-21 20:53 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +This representation is based on the ``stabilizers`` :math:`\mathcal{S}` of the state,
Reworked the definition of stabilizer a little. As for the destabilizer, I describe it only in the context of stabilizers to avoid giving a math-heavy definition.

2024-03-21 20:53 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +For evolving the state, i.e., replicating the application of the Clifford gates on the state,
Added it.

2024-03-21 20:53 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# default. For example, the tableau for the above circuit is -
Renders properly for me. You could attach a screenshot if you'd like.

2024-03-21 20:58 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# Looking at the tableaus in a matrix form could be difficult to comprehend. Instead, one can
The rest of this section describes the evolution of the stabilizer tableau by applying Clifford gates. For a reader, this essentially aims to show how the evolution of the state could be tracked in the tableau formalism without doing any matrix-vector multiplication that happens in the state vector formalism.

I have shifted finite-shots section with the initial simulation results and separated this out under a new subsection - "Simulating Stabilizer Tableau".

2024-03-22 19:18 UTC, soranjh commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# from :math:`+Z_0` to :math:`-Z_0`, while keeping the destabilizer generators the same.
Please double-check the indices. Seems to me that the socond one should be Z1?

2024-03-22 19:19 UTC, soranjh approved these changes

2024-03-22 19:22 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# from :math:`+Z_0` to :math:`-Z_0`, while keeping the destabilizer generators the same.
`X(0)` will just flip the sign for the stabilizers with index `0`. The indices should be the same since it is a single-qubit gate.

2024-03-22 19:23 UTC, soranjh commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +assert qml.math.allclose(original_probs, unrolled_probs, atol=1e-3)
[optional] Might consider removing assert, if the build version prints True, just for nicer visibility.

2024-03-22 19:24 UTC, soranjh commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +set :math:`\mathcal{D}`.
Please read this paragraph carefully, to make sure there is no typo or missing word etc.

2024-03-22 19:30 UTC, soranjh commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# from :math:`+Z_0` to :math:`-Z_0`, while keeping the destabilizer generators the same.
Then the order in the print version is correct?
![image](https://github.com/PennyLaneAI/qml/assets/40344468/0c8bf3fe-63f9-4d7a-8b25-0070e20729e2)

2024-03-22 19:39 UTC, obliviateandsurrender commented on demonstrations/tutorial_clifford_circuit_simulations.py
> +# from :math:`+Z_0` to :math:`-Z_0`, while keeping the destabilizer generators the same.
Yep. Only `ZI` (Z_0) gets its phase flipped and not `IZ` (Z_1).

2024-03-22 21:07 UTC, obliviateandsurrender commented
[sc-57834]

2024-03-22 22:00 UTC, merged