[WIP] qft demo
PennyLaneAI/qml pull request #1048
Opened 2024-03-05 19:27 UTC by KetpuntoG

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Remember to do a grammar check of the content you include.
- [ ] All tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

----
If you are writing a demonstration, please answer these questions to facilitate the marketing process.

* GOALS — Why are we working on this now?

  *Eg. Promote a new PL feature or show a PL implementation of a recent paper.*

* AUDIENCE — Who is this for?

  *Eg. Chemistry researchers, PL educators, beginners in quantum computing.*

* KEYWORDS — What words should be included in the marketing post?

* Which of the following types of documentation is most similar to your file? 
(more details [here](https://www.notion.so/xanaduai/Different-kinds-of-documentation-69200645fe59442991c71f9e7d8a77f8))
    
- [ ] Tutorial
- [ ] Demo
- [ ] How-to

2024-03-08 15:03 UTC, ixfoduap requested changes
Leaving some comments for now, will continue the review later. Looking very nice so far!

2024-03-08 15:03 UTC, ixfoduap commented on demonstrations/tutorial_qft.py
> +# This is a huge advantage when we are working with large quantum systems.
```suggestion
```
I think the exponential separation speaks enough for itself that we don't need this sentence

2024-03-08 15:04 UTC, ixfoduap commented on demonstrations/tutorial_qft.py
> +r"""Intro to Quantum Fourier Transform
```suggestion
r"""Intro to the Quantum Fourier Transform
```

2024-03-08 19:02 UTC, KetpuntoG commented on demonstrations/tutorial_qft.py
> +# Great, the generated matrices are the same.
yes, I noticed
It is equivalent but it looks ugly, I'll see if I can fix it

2024-03-08 22:05 UTC, ixfoduap requested changes
Mostly minor suggestions, but there were parts at the end that where unclear and confusing, so please pay close attention to those.

Looking great overall!

2024-03-08 22:05 UTC, ixfoduap commented on demonstrations/tutorial_qft.py
> +# number of qubits.
```suggestion
# The output has a clear peak at  :math:`|x\rangle = 3`.
# This value corresponds to an approximation of :math:`2^nf`, where :math:`f` is the frequency and :math:`n` is the
# number of qubits.
```

2024-03-08 22:05 UTC, ixfoduap commented on demonstrations/tutorial_qft.py
> +# Now it's time to put it into practice. Let's imagine that we have a ``prep`` operator, which prepare some state:
```suggestion
# We have seen how to define the QFT and how to build it with basic gates; 
# now it's time to put it into practice. Let's imagine that we an operator that prepares some state, as defined in the code below:
```

2024-03-08 22:05 UTC, ixfoduap commented on demonstrations/tutorial_qft.py
> +# Now it's time to put it into practice. Let's imagine that we have a ``prep`` operator, which prepare some state:
I suggest writing down explicitly the mathematical formula for the function that you are encoding, and stating up front its period and frequency, so we can compare with the output later

2024-03-08 22:05 UTC, ixfoduap commented on demonstrations/tutorial_qft.py
> +#    T = \frac{1}{f},
This is a primary school formula, no need to show it so prominently. Just say that once we know the frequency, we invert it to obtain the period

2024-03-08 22:05 UTC, ixfoduap commented on demonstrations/tutorial_qft.py
> +# certain value is encoded in the period and then, we use the QFT to find that value.
I don't understand this sentence. Please revise for clarity

2024-03-08 22:05 UTC, ixfoduap commented on demonstrations/tutorial_qft.py
> +# In this tutorial, we've journeyed through the fundamentals and construction of the Quantum Fourier Transform (QFT), a
```suggestion
# In this tutorial, we've journeyed through the fundamentals and construction of the quantum Fourier transform, a
```

2024-03-08 22:05 UTC, ixfoduap commented on demonstrations/tutorial_qft.py
> +# It is a technique that deserves to be mastered to detect potential key applications in the future!
```suggestion
# cornerstone in quantum computing. We explored its mathematical
# formulation, its implementation with basic quantum gates, and its application demonstrating its powerful utility in algorithms like quantum phase estimation.
# It is a technique that deserves to be mastered!
```

2024-03-08 22:06 UTC, ixfoduap commented on demonstrations/tutorial_qft.py
> +# .. figure:: ../_static/demonstration_assets/qft/qft_gif.gif
Awesome gif :star_struck:

2024-03-11 14:19 UTC, KetpuntoG commented on demonstrations/tutorial_qft.py
> +# That is why we should make a last step and change the order of all the qubits. For this reason, it is common to find some swap operators at the end of the template.
Reading about the subject I have seen that it is actually a convention. Swaps are used because it makes more sense to send the most significant bit in one base to the most significant bit in the other and not vice versa. I will simply say that it is a convention anyway we do not to overcomplicate it 👍

2024-03-11 14:38 UTC, KetpuntoG commented on demonstrations/tutorial_qft.py
> +# Using the QFT
I changed it to: "Quantum Fourier transform in practice"

2024-03-11 14:57 UTC, KetpuntoG commented on demonstrations/tutorial_qft.py
> +# certain value is encoded in the period and then, we use the QFT to find that value.
I have deleted it for simplicity

2024-03-11 17:06 UTC, KetpuntoG commented on demonstrations/tutorial_qft.py
> +# Great, the generated matrices are the same.
Any possible solution makes worse the readability of the code. I'll leave it like this at the end

2024-03-11 17:28 UTC, ixfoduap approved these changes
Looks great! Just a couple more minor changes and should be good to go

2024-03-11 17:28 UTC, ixfoduap commented on demonstrations/tutorial_qft.py
> +# we apply SWAPs gates. Let's see how its decomposition looks like using the drawer:
```suggestion
# In the case PennyLane, we rearrange the qubits in the opposite ordering; that is why we
# apply SWAPs gates at the end. Let's see how the decomposition looks like using the drawer:
```

2024-03-11 17:28 UTC, ixfoduap commented on demonstrations/tutorial_qft.py
> +# Note that the numerical arguments are :math:`\frac{\pi}{2} = 1.57`, :math:`\frac{\pi}{4} = 0.79` and  :math:`\frac{\pi}{8} = 0.39` (rounded to the first two decimal places).
Very nice!

2024-03-11 17:28 UTC, ixfoduap commented on demonstrations/tutorial_qft.py
> +# whose associated period, unknown to us,  is :math:`10`. We will use the QFT in PennyLane to find that period,
```suggestion
# whose associated period is :math:`10`. We will use the QFT in PennyLane to find that period,
```
We know the period, you just wrote it down :)  You can consider instead saying later that this same trick could be used to find periods in much more complicated functions/states

2024-03-11 17:28 UTC, ixfoduap commented on demonstrations/tutorial_qft.py
> +# formulation, its implementation with basic quantum gates, and its application demonstrating its powerful utility in algorithms like quantum phase estimation.
```suggestion
# formulation, its implementation with basic quantum gates, and its application demonstrating its usefulness in algorithms like quantum phase estimation.
```

2024-03-11 17:30 UTC, ixfoduap commented on demonstrations/tutorial_qft.py
> +# Note that the numerical arguments are :math:`\frac{\pi}{2} = 1.57`, :math:`\frac{\pi}{4} = 0.79` and  :math:`\frac{\pi}{8} = 0.39` (rounded to the first two decimal places).
```suggestion
# Note that the numerical arguments are :math:`\frac{\pi}{2} \approx 1.57`, :math:`\frac{\pi}{4} \approx 0.79` and  :math:`\frac{\pi}{8} \approx 0.39` (rounded to the first two decimal places).
```

2024-03-11 17:31 UTC, ixfoduap commented on demonstrations/tutorial_qft.py
> +# In this case, the period is :math:`T = 2^5 / 3 \sim 10.33` close to the real value of :math:`10`.
```suggestion
# In this case, the period is :math:`T = 2^5 / 3 \sim 10.33`, close to the real value of :math:`10`.
```

2024-03-15 19:53 UTC, ixfoduap approved these changes

2024-04-17 13:53 UTC, merged