[MCM 1/3] How-to: Statistics of mid-circuit measurements
PennyLaneAI/qml pull request #1066
Opened 2024-04-09 08:47 UTC by dwierichs

**Title:**
How to collect statistics of mid-circuit measurements

**Summary:**
PennyLane supports mid-circuit measurements not only to create dynamic circuits with control flow using the measurement results, but also supports a wide range of postprocessing options of the measured values.
This how-to explains the usage of `qml.measure` and briefly compares `qml.defer_measurements` and `qml.dynamic_one_shot`. Then it shows how (not) to measure qubit correlations with MCMs, and afterwards walks through the supported postprocessing of MCM values and the allowed return functions such as `qml.expval` or `qml.counts`.
Finally, ____ is shown as an application for obtaining statistics of MCMs.

**Relevant references:**
N/A

**Possible Drawbacks:**
N/A

**Related GitHub Issues:**
N/A

----
If you are writing a demonstration, please answer these questions to facilitate the marketing process.

* GOALS — Why are we working on this now?

This how-to promotes mid-circuit measurement functionality in PennyLane, which has been extended in recent releases. In particular, it contains a comparison of the brand-new native MCM support via `dynamic_one_shot` with `defer_measurements` and can serve to advertise this new feature.

In addition, this how-to is part of the broader goal of emphasizing MCMs and dynamic circuits in our contents.

* AUDIENCE — Who is this for?

Typical how-to audience: Fundamental concepts of measurements and quantum computing are known, but the audience may not yet be familiar with PennyLane's syntax for MCMs and returning their outcomes, or they may want to consult this how-to as a reference of how to realize their circuit with MCMs.
Anyone really with the goal of coding up a circuit that returns MCM values can be in the audience.

* KEYWORDS — What words should be included in the marketing post?

  - Mid-circuit measurements
  - Statistics
  - [optional] postprocessing

* Which of the following types of documentation is most similar to your file? 
(more details [here](https://www.notion.so/xanaduai/Different-kinds-of-documentation-69200645fe59442991c71f9e7d8a77f8))
    
- [ ] Tutorial
- [ ] Demo
- [x] How-to

[sc-60836]

2024-04-09 08:48 UTC, dwierichs commented on demonstrations/tutorial_how_to_collect_mcm_stats.metadata.json
> +    "dateOfLastModification": "2024-03-08T00:00:00+00:00",
Placeholder comment as reminder to update.

2024-04-24 14:00 UTC, josh146 requested changes
Thanks @dwierichs! First half of the how-to is really great, but I struggled to follow it a bit once the MCM processing started

2024-04-24 14:00 UTC, josh146 commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +#     arithmetics. E.g. ``mcm0 and mcm1`` often is equivalent to ``mcm0 * mcm1``.
@dwierichs sorry I find this section very hard to follow!

It definitely comes a bit out of left field, and with the lack of examples I'm tempted to just skip it (as a reader).

My suggestions:

- this is something that should definitely live in the reference documentation if it does not already, and we can just link out to it.
- in the examples above, when we _do_ use MCM combination operators, we can briefly discuss it there, but it does not need this level of depth.

2024-04-24 14:00 UTC, josh146 commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# standard terminal measurements.
This section does fit much more with the how-to! If you could slim it down slightly that would be great, otherwise this one is really helpful.

2024-04-24 14:35 UTC, dwierichs commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +in PennyLane, stay tuned for the related how-to on that topic appearing soon!
Fair enough! I'd think to edit this part in the next how-to PR, but we can also just skip it.

2024-04-24 20:55 UTC, josh146 approved these changes
Really nice work @dwierichs! I think it's almost there. I've 'pre-approved' but left some additional comments and suggestions (some marked optional)

2024-04-24 20:55 UTC, josh146 commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +        mcms.append(qml.measure(w))
Do you need to set `reset=True` here?

2024-04-24 20:55 UTC, josh146 commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +        qml.CNOT([first_wire, w])
optional suggestion: it might be easier to simply have

```python
def ansatz(x):
    mcms = []

    # Rotate all qubits
    for w, x_ in enumerate(x):
        qml.RX(x_, w)

    # Measure first qubit
    mcms.append(qml.measure(0))

    # Entangle all qubits with first qubit
    for w in range(1, 4):
        qml.CNOT([0, w])

    # Measure and reset all qubits but the first
    for w in range(1, 4):
        mcms.append(qml.measure(w))
```

That is, rather than abstract away the wires behind variable names, I think it would be fine to just be explicit (especially since you already have the comment that specifies 'first wire', etc.)

I say optional here, because I haven't read further yet and don't know if you have another reason for abstracting away wires :)

2024-04-24 20:55 UTC, josh146 commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +    mcm1, *mcms2 = ansatz(x)
```suggestion
    # apply the ansatz, and collect mid-circuit measurements.
    # here, mcm1 is the measurement of wire 0, and mcm2 is
    # a list of measurements of the remaining wires.
    mcm1, *mcms2 = ansatz(x)
```
optional suggestion, wasn't entirely clear to me

2024-04-24 20:55 UTC, josh146 commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# bit strings sampled from the other three MCMs. To implement the ``QNode``, we also define a
```suggestion
# let's construct a simple :class:`~.pennylane.QNode` and look at the statistics of the four
# performed MCMs:
#
# 1. We compute the probability vector for the MCM on the first qubit, and
#
# 2. count the bit strings sampled from the other three MCMs.
#
# To implement the ``QNode``, we also define a
```

2024-04-24 20:55 UTC, josh146 commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +plt.show()
Nice 😎 But shouldn't the import come before the `qml.draw()`?

2024-04-24 20:55 UTC, josh146 commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# reasons and is not required in general.
What do you mean by this @dwierichs?

2024-04-24 20:55 UTC, josh146 commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# reasons and is not required in general.
I would move this comment to right _before_ you use `defer_measurements`, so that a user understands clearly that it is optional.

It could also be worth (briefly) explaining why you use it.

---

Or preferentially, I would swap! Show the example _without_ `defer_measurements`, and then briefly introduce it, explain why it is useful, and then run it again with it.

2024-04-24 20:55 UTC, josh146 commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# Is this an analytic probability or just because we did not sample enough?)
I appreciate the quiz question @dwierichs but might not be fully appropriate for this type of content 😆 

I'm trying to work out how we could keep it here. I think at the very least, we would need to provide the answer to the reader

2024-04-24 20:55 UTC, josh146 commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# get to that shortly):
I skim read past this and was definitely confused for a second 😆

2024-04-24 20:55 UTC, josh146 commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +#
💯

2024-04-24 20:55 UTC, josh146 commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +    return equal_first & equal_parity
This is great!

2024-04-24 20:55 UTC, josh146 commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# mid-circuit measurements.**
```suggestion
# This concludes our how-to on statistics and post-processing of
# mid-circuit measurements.
```

2024-04-24 20:55 UTC, josh146 commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# mid-circuit measurements.**
This is also a good place for some CTAs (calls to action). E.g.,

```rest
This concludes our how-to on statistics and post-processing of
mid-circuit measurements. If you would like to explore mid-circuit measurement
applications, be sure to check out :doc:`demo1` and :doc:`demo2`. Or,
see all available functionality in our :doc:`quickstart <etc>`.
```

2024-04-24 20:55 UTC, josh146 commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# :func:`~.pennylane.defer_measurements` and :func:`~.pennylane.dynamic_one_shot`.
Something that has always struck me: I don't know what `dynamic_one_shot` refers to (I see a lot of people talking about it) 😅

Maybe more a problem that's out of scope here, but here we could briefly explain these two functions before linking out to them.

2024-04-24 20:55 UTC, josh146 commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# ----------------------
We could make this section heading 'Appendix: supported MCM return types' (or something similar) to avoid the double nesting.

Not sure I am sold on this idea though --- happy to leave it as is :)

2024-04-24 20:55 UTC, josh146 commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +#     only if they do not contain arithmetic expressions of these MCMs.
```suggestion
# - ``qml.sample`` and ``qml.counts`` are not supported for ``shots=None``.
# - ``qml.probs`` is not supported for MCMs collected in arithmetic expressions.
# - ``qml.expval`` and ``qml.var`` are not supported for sequences of MCMs.
#   ``qml.probs``, ``qml.sample``, and ``qml.counts`` are supported for sequences but
#   only if they do not contain arithmetic expressions of these MCMs.
```

2024-04-24 20:55 UTC, josh146 commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# Furthermore, available return types depend on whether or not the device is
```suggestion
# which probabilities are being requested.
#
# Furthermore, available return types depend on whether or not the device is
```

Just adding a line break for clarity

2024-04-24 20:55 UTC, josh146 commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# **are supported** with the following exceptions:
```suggestion
# **are supported** for mid-circuit measurements with the following exceptions:
```
maybe good to be explicit here

2024-04-25 07:11 UTC, dwierichs commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +        mcms.append(qml.measure(w))
Ah yes! Thanks!

2024-04-25 07:13 UTC, dwierichs commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +        qml.CNOT([first_wire, w])
I thought that in this case it might be nice to have an variable assignment: This way, the wires _are_ the integer values we give them. For `range`, I feel like more thinking has to happen to understand what exactly is going on.

I'm fine with doing it either way.

2024-04-25 07:14 UTC, dwierichs commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +    mcm1, *mcms2 = ansatz(x)
Included locally.

2024-04-25 07:16 UTC, dwierichs commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +plt.show()
We actually don't need this in the repository, this is left over from running locally. But funnily enough, we don't need to import before `draw_mpl`, because PennyLane also imports internally.

2024-04-25 07:20 UTC, dwierichs commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# reasons and is not required in general.
I argued now that it is nice to use here because we can pick a larger number of shots without paying computational cost.

2024-04-25 07:21 UTC, dwierichs commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# Is this an analytic probability or just because we did not sample enough?)
I added the answer to the end of the how-to. I think it's a cute sidetrack that people may or may not want to think about. Also, it could be seen as a reminder that sampling behaviour is not necessarily representative for small shot counts :D

2024-04-25 07:22 UTC, dwierichs commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# Is this an analytic probability or just because we did not sample enough?)
If it _is_ in the way, I can just take it out.

2024-04-25 07:22 UTC, dwierichs commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# get to that shortly):
Should I change something here?

2024-04-25 07:28 UTC, dwierichs commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# :func:`~.pennylane.defer_measurements` and :func:`~.pennylane.dynamic_one_shot`.
I abstractly describe the two:
>For performance considerations, take a look at
:func:`~.pennylane.defer_measurements` and :func:`~.pennylane.dynamic_one_shot`,
two simulation techniques that PennyLane uses under the hood to run circuits
like the ones in this how-to.

2024-04-25 07:29 UTC, dwierichs commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# ----------------------
No, I like the reduction! It was more useful before with the two appendix sections, but now we can just have one :)

2024-04-25 07:30 UTC, dwierichs commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# ----------------------
It made me notice that there was some redundancy in the text as well, so now it's even more compact :)

2024-04-25 07:31 UTC, dwierichs commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +#     only if they do not contain arithmetic expressions of these MCMs.
Ohhh, that makes so much sense :facepalm:

2024-04-25 14:56 UTC, KetpuntoG reviewed
Cool how-to! Thanks for working on this 🚀
Here I left some comments

2024-04-25 14:56 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# of entangling two-qubit gates (:class:`~.pennylane.CNOT`) between the first and all other qubits.
What is important here is the definition of the ansatz rather than the libraries. I would say that the first thing is to define the circuit we are going to work with, explain it, and then merge the two code cells into one.

2024-04-25 14:56 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +
```suggestion
#
```

2024-04-25 14:56 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +    mcm1, *mcms2 = ansatz(x)
I am not used to this notation but it simplifies things a lot 👌

2024-04-25 14:56 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# (Quiz question: Is this an analytic probability or just because we did not sample enough?
I was a bit confused about the question, what do you think about:

(Quiz question: Is this an expected behavior or maybe we did not sample enough?

2024-04-25 14:56 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# equal between the two sets of MCMs, and do the other three measured values have the same parity?
I don't think parity in this context is a well-known concept. Could you clarify?

2024-04-25 14:56 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +    equal_parity = first_parity == second_parity
Would this work?

`equal_parity = sum(first_mcms[1:]) == sum(second_mcms[1:])`

2024-04-25 14:56 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +    # Computing the parity can be done with bitwise "and" with the number 1
A common mistake for users is to use "and" instead of "&", maybe you could put a note?

2024-04-25 14:56 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +fig, ax = qml.draw_mpl(interesting_qnode)(x)
I really like see this circuits 😄

2024-04-25 14:56 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# ------------------------------------
To follow the structure of other demos, I would put this part under the title "Conclusion", (or at the end of the how-to). 
Also, in this title I would remove the word "Appendix:" and start the paragraph by saying. "Before finishing, it would be good to show some final clarifications" or similar :)

2024-04-25 14:56 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +print(f"Bit string counts on last three qubits: {counts}")
Here is missed:
```
About the author
----------------
```

no need the #include......., but yes the title

2024-04-25 14:56 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# will treat the first wire different than all other wires, we define it as separate variable.
```suggestion
# will treat the first wire differently than all other wires, we define it as separate variable.
```

2024-04-25 15:00 UTC, dwierichs commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# (Quiz question: Is this an analytic probability or just because we did not sample enough?
```suggestion
# (Quiz question: Is this expected behaviour or did we just not sample often enough?
```

2024-04-25 15:02 UTC, dwierichs commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +    equal_parity = first_parity == second_parity
Not quite, because we want even and odd numbers to be "equal", i.e. the condition should return `True` on `2` and `4`, for example.

2024-04-25 15:03 UTC, dwierichs commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# ------------------------------------
Sounds good! 

>(or at the end of the how-to)

You mean behind the quiz question's answer?

2024-04-25 15:35 UTC, dwierichs commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# of entangling two-qubit gates (:class:`~.pennylane.CNOT`) between the first and all other qubits.
Good call! Modified the ordering/structure and merged the code cells. How is it now?

2024-04-25 15:38 UTC, josh146 commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# ------------------------------------
Sorry @KetpuntoG but I would disagree here! The appendix isn't a conclusion, in the sense that a user does not need to read this to finish the how-to.

Since a how-to is focused more on readers who are _working_, the natural end point is when the last step required to achieve the objective is complete. Anything beyond that is not necessary.

Also I would add we don't need to finish every demo with a conclusion section :)

2024-04-25 15:40 UTC, josh146 commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# get to that shortly):
Oh, more so that I had the same thought: 'wait, `comparing_function` has not yet been defined!' and only then did I notice you also said this

2024-04-25 15:41 UTC, dwierichs commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# ------------------------------------
I did not go for the conclusion but really moved everything else that is not part of this "appendix" to the section before. I think this should underline the structure, let me know what you think :)

2024-04-25 15:41 UTC, josh146 commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# :func:`~.pennylane.defer_measurements` and :func:`~.pennylane.dynamic_one_shot`.
That's perfect, and all that's needed here 😎

2024-04-25 15:41 UTC, josh146 commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# ------------------------------------
@dwierichs I would say the way you have it now is perfect:

<img width="664" alt="image" src="https://github.com/PennyLaneAI/qml/assets/2959003/207f3385-065c-407c-8a65-595e8314ee68">

2024-04-26 13:02 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# ------------------------------------
Sounds good, let's keep it this way then

2024-04-26 13:03 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_collect_mcm_stats.py
> +# of entangling two-qubit gates (:class:`~.pennylane.CNOT`) between the first and all other qubits.
Now it's great! 💪

2024-04-26 13:29 UTC, KetpuntoG approved these changes
Good job 🚀🚀🚀

2024-04-26 13:30 UTC, merged