AmpAmp demo2
PennyLaneAI/qml pull request #1072
Opened 2024-04-12 19:50 UTC by KetpuntoG

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Remember to do a grammar check of the content you include.
- [ ] All tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

----
If you are writing a demonstration, please answer these questions to facilitate the marketing process.

* GOALS — Why are we working on this now?

  *Eg. Promote a new PL feature or show a PL implementation of a recent paper.*

* AUDIENCE — Who is this for?

  *Eg. Chemistry researchers, PL educators, beginners in quantum computing.*

* KEYWORDS — What words should be included in the marketing post?

* Which of the following types of documentation is most similar to your file? 
(more details [here](https://www.notion.so/xanaduai/Different-kinds-of-documentation-69200645fe59442991c71f9e7d8a77f8))
    
- [ ] Tutorial
- [ ] Demo
- [ ] How-to

2024-04-22 13:50 UTC, soranjh reviewed
Thanks @KetpuntoG, left some high level comments.

2024-04-29 15:05 UTC, ixfoduap commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +if the given state meets the properties of being a solution, we change its sign.
```suggestion
Amplitude Amplification usually assumes access to an oracle implementing this reflection operator. For example, in a search problem, this is the usual Grover oracle that "marks" the target state with a phase flip. In practice, the way to explicitly build the oracle is just a classic check:
if the given state meets the properties of being a solution, we change its sign.
```

2024-04-29 15:07 UTC, ixfoduap commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +we know the gate :math:`U` that generate it. This can be built directly in PennyLane with :class:`~.pennylane.Reflection`.
```suggestion
The second reflection is the one with respect to :math:`|\Psi\rangle`. This operator is easier to build since
we know the gate :math:`U` that generate it. This can be built directly in PennyLane with :class:`~.pennylane.Reflection`.
```

2024-04-29 15:10 UTC, ixfoduap commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +angle that forms our state. To approach the target state, we must perform this rotation :math:`\text{iters}` times where:
```suggestion
These two reflections are equivalent to rotating the state by :math:`2\theta` degrees from its original position, where :math:`\theta=\arcsin(\alpha/\beta)` is the
angle that defines the initial state. To amplify the amplitude and approach the target state, we perform this sequence of rotations multiple times. More precisely, we repeat them:
```

2024-04-29 15:11 UTC, ixfoduap commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +    \text{iters} \sim \frac{\pi}{4 \arcsin \alpha}-\frac{1}{2}.
```suggestion
   N =  \frac{\pi}{4 \arcsin \alpha}-\frac{1}{2}.
```
times.

2024-04-29 15:14 UTC, ixfoduap commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +dictionary = {
Extremely confusing. Unfortunately, I think it needs to be redone from scratch. Let's chat in person about it

2024-04-30 14:00 UTC, ixfoduap commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +Grover's algorithm is one of the most important algorithms developed in quantum computing. This technique belongs to a
Add links to Grover's

2024-05-01 16:30 UTC, soranjh requested changes
Thanks @KetpuntoG, overall looks good. I have three main points:

1. The first section, Amplitude Amplification, needs some refinement.
2. The algorithm is introduced based on two Reflections but the examples use Generator, Oracle, Sum without making it clear how these are related to the original Reflections. 
3. The text could be a bit more improved by better explaining the code. Currently, the code is there but the text is not supportive enough. I left some comments which probably fix this.

2024-05-01 16:30 UTC, soranjh commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +we know the operator :math:`U` that generate it. This can be built directly in PennyLane with :class:`~.pennylane.Reflection`.
I suggest moving the sentence about PennyLane to the PennyLane section. By the time I reach that section, probably I forgot that the reflection wrt psi is created by qml.Reflection that uses U.

2024-05-01 16:30 UTC, soranjh commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# Great, we have flipped the sign of the searched states without knowing what they are, simply by making use of their
Is this equivalent to the first Reflection?

2024-05-01 16:30 UTC, soranjh commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# The four peaks are obtained in :math:`0`, :math:`27`, :math:`35` and :math:`61`, whose binary
Clearly say something like: We have amplified the amplitudes of ...

2024-05-01 16:30 UTC, soranjh commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# implemented in PennyLane as :class:`~.AmplitudeAmplification`, template that we will use to see the evolution of the
```suggestion
# The combination of these two reflections is
# implemented in PennyLane as :class:`~.AmplitudeAmplification`. We now use this template that we will use to see the evolution of the
```

2024-05-01 16:30 UTC, soranjh commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# it or the results will start to get worse. This phenomenon is known as the "overcooking" of the state and is a
```suggestion
#  the iterations or the results will start to get worse, as you can see for 5 iterations in our example. This phenomenon is known as "overcooking" the state and is a
```

2024-05-01 16:30 UTC, soranjh commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# of Amplitude Amplification that solve this issue, the Fixed-point quantum search variant [#fixedpoint]_.
```suggestion
# of Amplitude Amplification that solves this issue, the Fixed-point quantum search variant [#fixedpoint]_.
```

2024-05-01 16:30 UTC, soranjh commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# in the paper and has a very interesting interpretation related to the approximation of the
```suggestion
# in reference [#unification]_ and has a very interesting interpretation related to the approximation of the
```

2024-05-01 16:30 UTC, soranjh commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# As the number of iterations increases, the probability of success increases as well, but be careful not to overdo
```suggestion
# We can see that as the number of iterations increases, the probability of success increases as well. But we should be careful to not overdo
```

2024-05-01 16:30 UTC, soranjh commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# Unlike before, we can see that the probability of success does not decrease.
```suggestion
# Unlike before, we can see that the probability of success does not decrease for large number of iterations.
```

2024-05-01 16:30 UTC, soranjh commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# We presented some of its limitations and learned how to overcome them with the Fixed-point version.
Fixed-point or fixed-point?

2024-05-01 16:30 UTC, soranjh commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# The PennyLane template also helps you with other variants such as Oblivious Amplitude Amplification [#oblivious]_.
```suggestion
# PennyLane supports Amplitude Amplification and its variants including Fixed-point and Oblivious Amplitude Amplification [#oblivious]_.
```

2024-05-01 16:51 UTC, KetpuntoG commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +but we can do better. One choice is to make :math:`|\phi\rangle` an element of the basis. We can then write
|phi> does not have to be an element of the computational basis. We don't know anything about phi. is that where the confusion comes from?

2024-05-01 16:56 UTC, KetpuntoG commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +where :math:`\theta=\arcsin(\alpha)` is the angle that defines the initial state. To amplify the amplitude and
arcsin removed from this paragraph and the equation 👍

2024-05-01 17:09 UTC, KetpuntoG commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +    oracle(range(n), range(n, n+5))   # Apply oracle
The oracle is one of the reflections, I have just clarified it throughout the text 👍

2024-05-01 21:18 UTC, soranjh commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# of Amplitude Amplification that solves this issue, the Fixed-point quantum search variant [#fixedpoint]_.
```suggestion
# of Amplitude Amplification that solves this issue: the Fixed-point quantum search variant [#fixedpoint]_.
```

2024-05-01 21:18 UTC, soranjh commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# We presented some of its limitations and learned how to overcome them with the fixed-point version.
```suggestion
# We discussed some of the limitations of the algorithm and learned how to overcome them with the fixed-point version.
```

2024-05-01 21:18 UTC, soranjh commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# of Amplitude Amplification that solves this issue, the Fixed-point quantum search variant [#fixedpoint]_.
Fixed-point or fixed-point?

2024-05-01 21:18 UTC, soranjh commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# We encourage you to explore these variants and see how they can help you in your quantum algorithms.
Can you point the reader to a few important workflows that use AmpAmp? e.g., Molecular simulation with QPE  ...

2024-05-01 22:20 UTC, KetpuntoG commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +#     \text{Sum}|\text{subset}\rangle|0\rangle = |\text{subset}\rangle|\sum v_ix_i\rangle,
- added clarification (the ith integer)

- the subset is any configuration |x_0 x_1 ... x_n>, I changed the name to "x"

2024-05-01 22:23 UTC, KetpuntoG commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +
Done in all circuits 👌

2024-05-01 22:27 UTC, KetpuntoG commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +but we can do better. One choice is to make :math:`|\phi\rangle` an element of the basis. We can then write
Not exactly, I am referring to the basis concept. Any state can be expressed in computational basis for certain c_s but another basis can be chosen. 
I have clarified a little but I don't know if it will be clear enough

2024-05-01 22:36 UTC, KetpuntoG commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# of Amplitude Amplification that solves this issue, the Fixed-point quantum search variant [#fixedpoint]_.
"fixed-point" , updated ✅

2024-05-02 14:27 UTC, ixfoduap requested changes

2024-05-02 14:27 UTC, ixfoduap commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# Fixed-point Quantum Search
```suggestion
# Fixed-point Amplitude Amplification
```

2024-05-02 14:27 UTC, ixfoduap commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# of Amplitude Amplification that solves this issue: the fixed-point quantum search variant [#fixedpoint]_.
```suggestion
# In the above example, we have a problem: we do not know the number of solutions. Because of this we cannot
# calculate the exact number of iterations needed, so we do not know when to stop and might overcook the state. However, there is a variant
# of Amplitude Amplification that solves this issue: the fixed-point quantum search variant [#fixedpoint]_.
```

2024-05-02 14:27 UTC, ixfoduap commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# sign function [#unification]_.
```suggestion
# The idea behind this technique is to avoid overcooking by gradually reducing the intensity of the resulting rotation with
# the help of an auxiliary qubit.
# The speed at which we decrease this intensity is carefully studied
# in reference [#fixedpoint]_ and has a very interesting interpretation related to the approximation of the
# sign function [#unification]_.
```

2024-05-02 14:27 UTC, ixfoduap commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# We encourage you to explore them and see how they can help you in your quantum algorithms.
```suggestion
# This algorithm is important in a variety of workflows such as molecular simulation with QPE. This shouldn't eb surprising, as it is generally helpful to rapidly amplify the amplitude of a target state. Moreover, the idea of using
# the reflections can be extrapolated to algorithms such as Qubitization or QSVT.
# PennyLane supports the Amplitude Amplification algorithm and its variants such as fixed-point and Oblivious Amplitude Amplification [#oblivious]_.
# We encourage you to explore them and see how they can help you in your quantum algorithms.
```
Should add a link to oblivious amp amp since we haven't mentioned it at all

2024-05-02 14:49 UTC, KetpuntoG commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# The four peaks are obtained in :math:`0`, :math:`27`, :math:`35` and :math:`61`, whose binary
It is indeed, I will say that I had a hard time finding that solution too 😆

2024-05-02 14:49 UTC, KetpuntoG commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# The Amplitude Amplification algorithm is implemented in PennyLane as :class:`~.AmplitudeAmplification`.
I don't think it works yet but once merge is done it will work. We have had this situation before

2024-05-02 14:50 UTC, KetpuntoG commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# Fixed-point Quantum Search
I would say the official name is with [Quantum Search](https://arxiv.org/abs/1409.3305)

2024-05-02 15:58 UTC, KetpuntoG commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +
(gif will be made with time and added later)

2024-05-02 16:49 UTC, KetpuntoG commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +Our goal is to prepare an unknown state :math:`|\phi\rangle`.
I had "knowing certain property of the state" written on it.
Don't you think that's important @ixfoduap ?

2024-05-02 17:03 UTC, KetpuntoG commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +@qml.prod
clarified 👍 

# This decorator converts the quantum function U into an operator.
# It is useful for later use in the AmplitudeAmplification template.

2024-05-02 20:33 UTC, soranjh approved these changes
Looks great, thanks @KetpuntoG.

2024-05-02 20:33 UTC, soranjh commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +In this taks, we are given a list of :math:`n` integers and our goal is to find all subsets of numbers
```suggestion
In this task, we are given a list of :math:`n` integers and our goal is to find all subsets of numbers
```

2024-05-02 20:33 UTC, soranjh commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +a useful extension called fixed-point amplitude amplification.
```suggestion
**Amplitude Amplification** (Amp Amp). In this demo, you will learn its basic principles of the algorithm and also learn
how to implement it in PennyLane using the new functionality :class:`~.AmplitudeAmplification`. We also discuss
a useful extension of the algorithm called fixed-point amplitude amplification.
```

2024-05-02 20:33 UTC, soranjh commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +A first approach is to design a quantum circuit described by a unitary :math:`U` that generates an initial state :math:`U|0\rangle := |\Psi\rangle`
"A first approach"? You mean "The first step"?

2024-05-02 20:33 UTC, soranjh commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# We can see that as the number of iterations increases, the probability of success increases as well. But we should be careful to not overdo it. As you can see, after 5 iterations in our example the
```suggestion
# We can see that as the number of iterations increases, the probability of success increases as well. But we should be careful to not overdo it. As you can see, after 5 iterations in our example, the amplitudes have in fact decreased. This phenomenon is known as "overcooking" and is a
```

2024-05-03 13:19 UTC, ixfoduap approved these changes
Please address my comments before merging

2024-05-03 13:19 UTC, ixfoduap commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +approach the target state, we perform this sequence of rotations multiple times, i.e. :math:`\dots R_{\Psi}R_{\phi^{\perp}}R_{\Psi}R_{\phi^{\perp}}`. More precisely, we repeat them :math:`k` times:
```suggestion
approach the target state, we perform this sequence of rotations multiple times, i.e. :math:`\dots R_{\Psi}R_{\phi^{\perp}}R_{\Psi}R_{\phi^{\perp}}`. More precisely, we repeat them :math:`k` times, with :math:`k` given by:
```

2024-05-03 13:19 UTC, ixfoduap commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +classical :math:`\mathcal{O}(N)` brute-force approach.
```suggestion
As we will see below, Amp Amp can be applied to unstructured dataset searching problems. Let's suppose that in a set
of N elements we are looking for a single one, and we begin with an equal superposition state such that :math:`\alpha=\frac{1}{\sqrt{N}}`.
The number of iterations required in this case is :math:`k \sim \frac{\pi \sqrt{N}}{4}`, making the complexity
of the algorithm :math:`\mathcal{O}(\sqrt{N})`. This provides a quadratic speedup compared to the
classical :math:`\mathcal{O}(N)` brute-force approach.
```

2024-05-03 13:19 UTC, ixfoduap commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +classical :math:`\mathcal{O}(N)` brute-force approach.
Fantastic explanation!

2024-05-03 13:19 UTC, ixfoduap commented on demonstrations/tutorial_intro_amplitude_amplification.py
>  # subset and :math:`0` otherwise.
```suggestion
# First we define a binary variable :math:`x_i` that takes the value :math:`1` if we include the :math:`i`-th element in the
# subset and takes the value :math:`0` otherwise.
```

2024-05-03 13:19 UTC, ixfoduap commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# step by step showing each part of the algorithm.
```suggestion
# Later on, we will see how to solve it directly with :class:`~.AmplitudeAmplification`, but it is worthwhile to go
# step by step showing each part of the algorithm.
```

2024-05-03 13:19 UTC, ixfoduap commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# step by step showing each part of the algorithm.
awesome!

2024-05-03 13:19 UTC, ixfoduap commented on demonstrations/tutorial_intro_amplitude_amplification.py
>  # look at `Basic arithmetic with the QFT <https://pennylane.ai/qml/demos/tutorial_qft_arithmetics/>`_.
```suggestion
# look at `Basic arithmetic with the Quantum Fourier Transform <https://pennylane.ai/qml/demos/tutorial_qft_arithmetics/>`_.
```

2024-05-03 13:19 UTC, ixfoduap commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +how to implement it in PennyLane using the new functionality :class:`~.AmplitudeAmplification`. We also discuss
Links to pennylane functions are not working, i.e., I can't click on them to take me to the corresponding page. PLEASE FIX BEFORE MERGING

2024-05-03 13:19 UTC, ixfoduap commented on demonstrations/tutorial_intro_amplitude_amplification.py
>  # These states satisfy the property that the sum of the subset is :math:`0`.
```suggestion
# representation corresponds to :math:`|000000\rangle`, :math:`|011011\rangle`, :math:`|100011\rangle` and :math:`|111101\rangle` respectively. From these we recognize the non-trivial subsets :math`[-2, 3, 5,-6]`,  :math`[1, 5,-6]` and  :math`[1, -2, 3, 4, -6]` whose sum is zero`.
```

2024-05-03 13:19 UTC, ixfoduap commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# consequence of rotating the state too much. It can be addressed using fixed-point amplitude amplification, which we discuss below.
```suggestion
# We can see that as the number of iterations increases, the probability of success increases as well. But we should be careful to not overdo it: after 5 iterations in our example, the amplitudes have in fact decreased. This phenomenon is known as "overcooking" and is a
# consequence of rotating the state too much. It can be addressed using fixed-point amplitude amplification, which we discuss below.
```

2024-05-03 13:19 UTC, ixfoduap commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# Fixed-point Quantum Search
Let's change it for the purpose of this demo :smiling_imp:

2024-05-03 13:19 UTC, ixfoduap commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +# Fixed-point Quantum Search
If you feel strongly against it, feel free to keep quantum search

2024-05-03 13:19 UTC, ixfoduap commented on demonstrations/tutorial_intro_amplitude_amplification.py
>  #    :align: center
Let's add a short explanation of what the AmplitudeAmplification template expects as input

2024-05-03 13:29 UTC, KetpuntoG commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +how to implement it in PennyLane using the new functionality :class:`~.AmplitudeAmplification`. We also discuss
links to the new functions do not yet work until the merge

2024-05-03 13:38 UTC, KetpuntoG commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +Our goal is to prepare an unknown state :math:`|\phi\rangle`.
I'll keep this time

2024-05-03 16:14 UTC, KetpuntoG commented on demonstrations/tutorial_intro_amplitude_amplification.py
> +A first approach is to design a quantum circuit described by a unitary :math:`U` that generates an initial state :math:`U|0\rangle := |\Psi\rangle`
The first idea, I'll keep in this way

2024-05-03 18:30 UTC, merged