Add fermionic to qubit mapping demo
PennyLaneAI/qml pull request #1077
Opened 2024-04-23 16:00 UTC by ddhawan11

**Title:**
Mapping fermionic Hamiltonian to qubit Hamiltonian

**Summary:**

**Relevant references:**
Tranter, Andrew, et. al. "A comparison of the Bravyi-Kitaev and the Jordan-Wigner transformations for the quantum simulation of quantum _chemistry." _Journal of chemical theory and computation_ 14.11 (2018): 5617-5630.

**Possible Drawbacks:**

**Related GitHub Issues:**

----
If you are writing a demonstration, please answer these questions to facilitate the marketing process.

* GOALS — Why are we working on this now?
Promote a new PL feature.
  
* AUDIENCE — Who is this for?
Chemistry researcher

* KEYWORDS — What words should be included in the marketing post?
Fermionic Mapping

* Which of the following types of documentation is most similar to your file? 
(more details [here](https://www.notion.so/xanaduai/Different-kinds-of-documentation-69200645fe59442991c71f9e7d8a77f8))
    
- [ ] Tutorial
- [x] Demo
- [ ] How-to

2024-04-26 18:15 UTC, soranjh requested changes
Thanks @ddhawan11, left some high-level comments for now.

2024-04-26 18:17 UTC, soranjh commented on _static/authors/diksha_dhawan_original.png
Seems to be duplicated?

2024-04-26 18:18 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +h_ferm = qchem.fermionic_hamiltonian(mol)()
Please remove the duplicated code.

2024-04-26 18:18 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +# <https://www.jacobtseeley.com/files/tranter2015.pdf>`__
Please link the journal.

2024-04-26 22:56 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +                                                  + str(excitation[1])+ "- " + str(excitation[0]) + "-"))
Please check Eq3 1-2 of this [paper](https://arxiv.org/abs/2005.14475) and the code I provided above for correct equations.

2024-04-29 17:55 UTC, soranjh requested changes
Thanks @ddhawan11, left a second round of high-level comments. When they are addresses, I will put some minor modification comments on the text.

2024-04-29 17:55 UTC, soranjh commented on demonstrations/tutorial_mapping.metadata.json
> +        }
```suggestion
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/qft/thumbnail_QFT.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/large_demo_thumbnails/thumbnail_large_QFT_2024-04-04.png"
        }
```

2024-04-29 17:55 UTC, soranjh commented on demonstrations/tutorial_mapping.metadata.json
> +        }
Placeholder for now.

2024-04-29 17:55 UTC, soranjh commented on demonstrations/tutorial_mapping.metadata.json
> +            "authors": "Efficient quantum circuits for quantum computational chemistry",
Needs update.

2024-04-29 17:55 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +========================================
```suggestion
Mapping Fermionic operators to Qubit operators
==============================================
```

2024-04-29 17:55 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +Jordan-Wigner Mapping works in the occupation number basis, i.e. qubits store the occupation state of spin orbitals.
In one sentence describe what creation and annihilation operators are.

2024-04-29 17:55 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +Next to map fermionic creation(:math:`a^{\dagger}_j`) and annihilation(:math:`a_j`)
You can mention that creation and annihilation in the qubit basis can be done with (X +/- iY/2) and then continue by saying what you have "However, an important property ..."

[]optional you can also add small phrases such as "can you verify that yourself" when you talk about the correspondence between fermionic and qubit operators.

2024-04-29 17:55 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +molecular system and calling fermionic_hamiltonian :math:`~.pennylane.qchem.fermionic_hamiltonian` function to calculate
Make sure that all PL functions and classes are properly cited using `:func: `and `:class:`. Look at the other demos for example.

2024-04-29 17:55 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +# In Parity mapping, the parity information of spin orbital j is stored in qubit j while the occupation
Use `:math:` for all variables.

2024-04-29 17:55 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +
You can briefly explain the difference between this Hamiltonian with one obtained with JW method.

2024-04-29 17:55 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +
Try to briefly explain why the long Z string is problematic.

2024-04-29 17:55 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +# Bravyi-Kitaev mapping aims to improve the linear scaling of Jordan-Wigner and Parity mappings, and uses
You should mention the problem with JW and Parity before talking about "improvement". Please see my comments above.

2024-04-29 17:55 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +h_ferm = qml.qchem.fermionic_hamiltonian(mol)()
I am not sure a molecular Hamiltonian is a good example here. Think about using a simple fermionic operator that easily allows you to explain the non-local issues with JW and parity and how BK solves it.

2024-04-29 17:55 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +
We need a section on HF state. Readers need to know that they have to map three components: Hamiltonian, State, Gates.

2024-04-29 17:55 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +# In this section, we want to explore the use of these mappings to map fermionic excitation operators to quantum gates
Phrase this as: now that we learned how to map Hamiltonian and states to the proper basis, we should also make our excitation gates comply with the selected mapping.

Then mention excitation gates, basically Eqs 1-2 of Ref. [#HWBarnes2020]_, and take it from there.

We also need to talk about Eq 4 in the text because it is an important equation.

2024-04-29 17:55 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +for excitation in singles:
You can import `from_string` one time so you do not need to repeat the `qml.fermi.` part. 

Please also consider a shorter name for excitation, so the code is a bit more compact.

You can actually create a function here that maps the list format, e.g., [0, 1, 2, 3] to the proper fermionic operator.

2024-04-29 17:55 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +singles, doubles = qchem.excitations(active_electrons, qubits)
Comment for future: we can update this function to optionally return Fermi objects not a list of integers.

2024-04-29 17:55 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +# how a user can employ these different mappings in VQE calculations through an example.
This is a nice summary but think about having a few sentences of conclusions as well.

2024-04-29 19:46 UTC, KetpuntoG commented
Hey @soranjh , Until next Monday, the master branch will continue with the previous version of pennylane. I recommend point to `dev` to be able to merge this week

2024-04-29 19:56 UTC, soranjh commented
> Hey @soranjh , Until next Monday, the master branch will continue with the previous version of pennylane. I recommend point to `dev` to be able to merge this week

It was originally based on master, we will fix this.

2024-05-02 03:07 UTC, soranjh requested changes
Looks good @ddhawan11, left another set of comments.

2024-05-02 03:07 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +# for :math:H_{3}^{+} molecule. For simplicity, we limit ourselves to singles and doubles.
We do not have triples for H3+ anyways.

2024-05-02 03:07 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +# Next, we generate the fermionic operators for these excitations, using Eqs 1-2 of Ref. [#HWBarnes2020]_
I think we should write the equations and say that we are forming a UCCSD ansatz for the simulation.

2024-05-02 03:07 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +params = np.zeros(len(op_doubles_bk) + len(op_singles_bk))
Please use a pre-computed parameter obtained from an actual VQE optimisation.

2024-05-02 03:07 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +# however relies in the fact that it allows us to taper two qubits based on symmetries.
Can you put a quick example on how to save qubits? Not necessary if it is not easy and short.

2024-05-06 19:00 UTC, KetpuntoG commented on demonstrations/tutorial_mapping.py
> +    a_{j}^{\dagger} = \otimes_{i<j} Z_{i} \frac{1}{2}(X_j - iY_j),
Not ideal use the sub-indice "i_" since we have the imaginary part, but feel free to leave like this

2024-05-06 19:01 UTC, KetpuntoG commented on demonstrations/tutorial_mapping.py
> +fermi_op = from_string("5+")
is "+" the $\dagger$ ?

2024-05-06 19:11 UTC, obliviateandsurrender reviewed
Looks good @ddhawan11! Leaving some minor comments and suggestions.

2024-05-06 19:11 UTC, KetpuntoG commented on demonstrations/tutorial_mapping.py
> +# Parity mapping solves the non-locality problem of the parity information by storing
Oh it's cool! I had a hard time understanding it though. Maybe it would be good to explain some first steps. That to the left of the vector there is a one implies that the layer is occupied. In the second position we have a 0, that is, an even number. As we have an even number and we are in layer 2, it means that this layer is also occupied (not blocking).

2024-05-06 19:15 UTC, KetpuntoG commented on demonstrations/tutorial_mapping.py
> +#     a_{j}^{\dagger} = \frac{1}{2}(Z_{j-1} \otimes X_j - iY_j) \otimes_{i>j} X_{i}
```suggestion
#     a_{j}^{\dagger} = \frac{1}{2}Z_{j-1} \otimes (X_j - iY_j) \otimes_{i>j} X_{i}

```

inuitively I would have put this, could you check just in case?

2024-05-06 19:17 UTC, KetpuntoG commented on demonstrations/tutorial_mapping.py
> +#     a_{j}^{\dagger} = \frac{1}{2}(Z_{j-1} \otimes X_j - iY_j) \otimes_{i>j} X_{i}
Never mind, i just saw the output on pennylane 😄

2024-05-06 19:21 UTC, KetpuntoG commented on demonstrations/tutorial_mapping.py
> +# `qubit tapering <https://pennylane.ai/qml/demos/tutorial_qubit_tapering>`__ demo.
Maybe the sentence "you can find..." it is better after the code

2024-05-06 19:23 UTC, KetpuntoG commented on demonstrations/tutorial_mapping.py
> +# qubits store the occupation number of spin orbitals and odd-labelled qubits store parity
As a reader who is new to this topic, I'm finding really interesting!

2024-05-06 19:24 UTC, KetpuntoG commented on demonstrations/tutorial_mapping.py
> +
I have missed the formula of the a and a^t operators, is it possible to show?

2024-05-06 19:26 UTC, KetpuntoG commented on demonstrations/tutorial_mapping.py
> +#
I was curious to know if it has any drawback, or is it the state of the art? if it is easy to answer, it could be indicated in one sentence :)

2024-05-06 19:28 UTC, KetpuntoG commented on demonstrations/tutorial_mapping.py
> +
I would have liked to see both decompositions, or are they too big?

2024-05-06 19:30 UTC, KetpuntoG commented on demonstrations/tutorial_mapping.py
> +
"Note that the number of occupied orbitals is 2 even though we only see a 1 in this representation" or similar.

(optional)

2024-05-06 19:32 UTC, KetpuntoG commented on demonstrations/tutorial_mapping.py
> +# and :func:`~.pennylane.DoubleExcitation` operators which are very efficient, but they are only
It would be really cool to be able to indicate the mapping used in Pennylane for these operators at some point 😃

2024-05-06 19:33 UTC, KetpuntoG commented on demonstrations/tutorial_mapping.py
> +h_pauli = qml.bravyi_kitaev(h_fermi, qubits, tol=1e-16)
it is unexpected to me that there is a tolerance here

2024-05-06 19:36 UTC, KetpuntoG commented on demonstrations/tutorial_mapping.py
> +# Summary
```suggestion
# Conclusion

```

2024-05-06 19:37 UTC, KetpuntoG commented on demonstrations/tutorial_mapping.metadata.json
> +    "dateOfLastModification": "2024-04-30T00:00:00+00:00",
```suggestion
    "dateOfPublication": "2024-05-06T00:00:00+00:00",
    "dateOfLastModification": "2024-05-06T00:00:00+00:00",
```

2024-05-06 19:37 UTC, KetpuntoG commented on demonstrations/tutorial_mapping.metadata.json
> +        "Quantum Computing"
Quantum chemistry too?

2024-05-06 19:38 UTC, KetpuntoG commented on demonstrations/tutorial_mapping.py
> +*Author: Diksha Dhawan — Posted: April 2024. Last updated: April 2024.*
```suggestion
```

We don't need this anymore :)

2024-05-06 19:38 UTC, KetpuntoG commented on demonstrations/tutorial_mapping.py
> +# .. include:: ../_static/authors/diksha_dhawan.txt
```suggestion

```

2024-05-06 19:41 UTC, KetpuntoG commented on demonstrations/tutorial_mapping.py
> +then mapp the operator using :func:`~.pennylane.fermi.jordan_wigner`.
```suggestion
then map the operator using :func:`~.pennylane.fermi.jordan_wigner`.

```

2024-05-06 19:42 UTC, KetpuntoG commented on demonstrations/tutorial_mapping.py
> +# are define in :func:`~.pennylane.fermi.bravyi_kitaev`. Let's use the
```suggestion
# are defined in :func:`~.pennylane.fermi.bravyi_kitaev`. Let's use the

```

2024-05-06 19:42 UTC, KetpuntoG commented on demonstrations/tutorial_mapping.py
> +# :func:`~.pennylane.fermi.bravyi_kitaev` function to mapp our :math:`a_{5}^{\dagger}` operator.
```suggestion
# :func:`~.pennylane.fermi.bravyi_kitaev` function to map our :math:`a_{5}^{\dagger}` operator.

```

2024-05-06 19:43 UTC, KetpuntoG commented on demonstrations/tutorial_mapping.py
> +# improve the scaling. This adavantage becomes even more clear if you work with a larger qubit
```suggestion
# improve the scaling. This advantage becomes even more clear if you work with a larger qubit

```

2024-05-06 19:47 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +    Q^{\dagger}_j = \frac{1}{2}(X_j - iY_j),
Qdag/Q are the qubit creation/annihilation operator but adag/a are the fermionic ones. I will clarify this with an example.

2024-05-06 20:12 UTC, obliviateandsurrender commented on demonstrations/tutorial_mapping.py
> +                         - from_string(str(ex[0]) + "+ " + str(ex[1]) + "-"))
```suggestion
                         - from_string(f"{ex[0]}+ {ex[1]}-"))

```

2024-05-06 20:12 UTC, obliviateandsurrender commented on demonstrations/tutorial_mapping.py
> +    doubles_fermi.append(from_string(str(ex[3]) + "+ " + str(ex[2]) + "+ "
```suggestion
    doubles_fermi.append(from_string(f"{ex[3]}+ {ex[2]}+ {ex[1]}- {ex[0]}-")

```

2024-05-06 20:12 UTC, obliviateandsurrender commented on demonstrations/tutorial_mapping.py
> +                                     + str(ex[1]) + "- " + str(ex[0]) + "-")
```suggestion
```

2024-05-06 20:12 UTC, obliviateandsurrender commented on demonstrations/tutorial_mapping.py
> +                         - from_string(str(ex[0]) + "+ " + str(ex[1]) + "+ "
```suggestion
                         - from_string(f"{ex[0]}+ {ex[1]}+ {ex[2]}- {ex[3]}-"))
                         

```

2024-05-06 20:12 UTC, obliviateandsurrender commented on demonstrations/tutorial_mapping.py
> +                                       + str(ex[2]) + "- " + str(ex[3]) + "-"))
```suggestion
```

2024-05-06 21:18 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +fermi_op = from_string("5+")
Yes.

2024-05-06 21:21 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +# and :func:`~.pennylane.DoubleExcitation` operators which are very efficient, but they are only
It is already mentioned: "but they are only compatible with the Jordan-Wigner mapping."

2024-05-06 21:22 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +h_pauli = qml.bravyi_kitaev(h_fermi, qubits, tol=1e-16)
It is to remove the negligible imaginary part.

2024-05-06 21:33 UTC, KetpuntoG commented on demonstrations/tutorial_mapping.py
> +
```suggestion
```

Sometimes when writing a comment, github adds blanks. I think this is the rendering problem. Once fixed, the references should work correctly

2024-05-06 21:33 UTC, obliviateandsurrender commented on demonstrations/tutorial_mapping.py
> +    a_{j}^{\dagger} = \otimes_{i<j} Z_{i} \frac{1}{2}(X_j - iY_j),
```suggestion
    a_{j}^{\dagger} = \frac{1}{2}(X_j - iY_j) \otimes_{i<j} Z_{i} ,

```

2024-05-06 21:33 UTC, obliviateandsurrender commented on demonstrations/tutorial_mapping.py
> +    a_{j} = \otimes_{i<j} Z_{i} \frac{1}{2}(X_j + iY_j) .
```suggestion
    a_{j} =  \frac{1}{2}(X_j + iY_j) \otimes_{i<j} Z_{i} .

```

2024-05-06 21:33 UTC, obliviateandsurrender commented on demonstrations/tutorial_mapping.py
> +simulations typically require mapping schemes that transform fermionic systems into qubit
```suggestion
simulations typically require mapping schemes that transform fermionic representations into qubit

```

2024-05-06 21:33 UTC, obliviateandsurrender commented on demonstrations/tutorial_mapping.py
> +# resources needed to implement the operator in quantum hardware, as it may require using entangling
```suggestion
# resources needed to implement the operator on quantum hardware, as it may require using entangling

```

2024-05-06 21:34 UTC, KetpuntoG commented on demonstrations/tutorial_mapping.py
> +
```suggestion
```

2024-05-06 21:34 UTC, KetpuntoG commented on demonstrations/tutorial_mapping.py
> +
```suggestion
```

2024-05-06 21:41 UTC, KetpuntoG approved these changes
Good job @ddhawan11 🚀
A great first contribution

2024-05-06 21:44 UTC, obliviateandsurrender approved these changes

2024-05-06 23:45 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +# scaling of the Jordan-Wigner mapping as the :math:`Z` strings are now replaced by :math:`X`
Removed the term scaling and just mentioned that the long Z chain is replaced by a long X chain.

2024-05-06 23:45 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +    Q^{\dagger}_j = \frac{1}{2}(X_j - iY_j),
Added better explanation.

2024-05-06 23:47 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +anti-commutation relations between them, which is not preserved by directly using the analogous
Added definition.

2024-05-06 23:51 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +
They are pretty big, added a link instead.

2024-05-06 23:52 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +#
The challenge is that everything should be presented in this basis.

2024-05-07 00:04 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +# Parity mapping solves the non-locality problem of the parity information by storing
Added extra explanations before the code.

2024-05-07 01:11 UTC, soranjh approved these changes

2024-05-07 01:33 UTC, merged