Update DLA intro demo with new qml.pauli.dla functionality
PennyLaneAI/qml pull request #1079
Opened 2024-04-24 16:35 UTC by Qottmann

Updating the existing demo with new DLA functionality in PennyLane.

No change to the story of the demo, just making some things more convenient and pointing out functionality to do some things that we do here manually, more easily using that new functionality

2024-04-24 16:37 UTC, Qottmann commented on demonstrations/tutorial_liealgebra.py
> +# For more qubits :math:`n`, the associated DLA for the transverse field Ising model is :math:`\mathfrak{so}(2n)` for open boundary conditions
Had this wrong in the first version

2024-04-24 20:55 UTC, KetpuntoG commented on demonstrations/tutorial_liealgebra.py
> +
```suggestion

###############################################################
```

This should solve the tenderization issue

2024-04-24 20:56 UTC, KetpuntoG commented on demonstrations/tutorial_liealgebra.py
> +
```suggestion
###############################################################
```

2024-04-24 22:11 UTC, KetpuntoG approved these changes
Awesome! Thanks for the update 💪

2024-04-25 13:32 UTC, dwierichs requested changes
Nice extension! :100: I had a few minor comments, but otherwise looks :ok_hand:

2024-04-25 13:32 UTC, dwierichs commented on demonstrations/tutorial_liealgebra.metadata.json
> +    "dateOfLastModification": "2024-04-24T00:00:00+00:00",
:grimacing: 
```suggestion
    "dateOfLastModification": "2024-04-25T00:00:00+00:00",
```

2024-04-25 13:32 UTC, dwierichs commented on demonstrations/tutorial_liealgebra.py
> +# PennyLane provides some dedicated functionality for Lie algebras. We can compute the Lie closure using ``qml.lie_closure`` of the generators.
```suggestion
# PennyLane provides some dedicated functionality for Lie algebras. We can compute the Lie closure of the generators using ``qml.lie_closure``.
```

2024-04-25 13:32 UTC, dwierichs commented on demonstrations/tutorial_liealgebra.py
> +    for op2 in dla.basis.copy()[i+1:]:
Why do we need the `copy` calls here? Does `qml.commutator` mutate inplace?

2024-04-25 13:32 UTC, dwierichs commented on demonstrations/tutorial_liealgebra.py
> +dla = qml.pauli.PauliVSpace(generators, dtype=complex) # collection of linearly independent basis vectors, automatically discards linearly dependent ones
This causes a horizontal scrollbar in the code box
```suggestion
# collection of linearly independent basis vectors, automatically discards linearly dependent ones
dla = qml.pauli.PauliVSpace(generators, dtype=complex)
```
Not sure whether this is sufficient or the comment should be reduced/broken into two lines?

2024-04-25 13:32 UTC, dwierichs commented on demonstrations/tutorial_liealgebra.py
> +dla2
Could again do
```suggestion
for op in dla2.basis:
    print(op)
```

2024-04-25 14:03 UTC, Qottmann commented on demonstrations/tutorial_liealgebra.py
> +    for op2 in dla.basis.copy()[i+1:]:
No, but the `dla.add` below

2024-04-25 15:31 UTC, Qottmann commented on demonstrations/tutorial_liealgebra.py
> +for op in dla2.basis:
```suggestion
for op in dla2:
```

2024-04-25 15:38 UTC, dwierichs commented on demonstrations/tutorial_liealgebra.py
> +    for op2 in dla.basis.copy()[i+1:]:
Oh, of course :facepalm:  Thanks!

2024-04-25 15:39 UTC, dwierichs approved these changes
Thanks, looks good to me! :)

2024-04-26 07:47 UTC, merged

2024-04-26 09:00 UTC, Qottmann commented
DLA module demo [sc-51428]