Error Tracking Demo
PennyLaneAI/qml pull request #1083
Opened 2024-04-25 19:42 UTC by Jaybsoni

**Title: How to Track Algorithmic Errors in PennyLane**

**Summary:**
A "How to" guide teaching users about the newest error tracking functionality in PennyLane.

----
If you are writing a demonstration, please answer these questions to facilitate the marketing process.

* GOALS — Why are we working on this now?

- Error tracking is important for resource estimation, we want to create content targeting this.
- Show off new error tracking functionality from PennyLane.

* AUDIENCE — Who is this for?

- Pennylane Users 
- Algorithmic Researchers 
- Applications Scientists 
- Students

* KEYWORDS — What words should be included in the marketing post?

- Error Tracking
- Error Propagation
- Algorithmic Error 
- Quantum
- Software

* Which of the following types of documentation is most similar to your file? 
(more details [here](https://www.notion.so/xanaduai/Different-kinds-of-documentation-69200645fe59442991c71f9e7d8a77f8))
    
- [ ] Tutorial
- [ ] Demo
- [x] How-to

2024-04-25 19:44 UTC, Jaybsoni commented
[sc - 61123]

2024-04-25 19:45 UTC, Jaybsoni commented
[sc-61123]

2024-04-25 19:45 UTC, Jaybsoni commented
[sc-61124]

2024-04-26 19:01 UTC, soranjh reviewed
Looks good overall. My main comment: the intro and conclusion sections need a bit more work, specially the intro.

2024-04-26 20:19 UTC, KetpuntoG requested changes
Great job Jay, glad to see all this working already in PennyLane! 💪
Here are a few comments

2024-04-26 20:19 UTC, KetpuntoG commented on demonstrations/tutorial_error_prop.py
> +# With the new abstract classes it's easy for anyone to define and track custom operations with error.
At this point, as a reader, I don't understand why I would want to define my own error operator. I think if you said we can combine them (which you tell at the end), I would love to be able to create my own pieces 🙌

2024-04-26 20:19 UTC, KetpuntoG commented on demonstrations/tutorial_error_prop.py
> +# hardware does not natively support X-axis rotation gate :class:`~.pennylane.RX`.
You could do $H R_Z H$ instead. As an alternative you could have a quantum computer only has clifford + T gates for example :)

2024-04-26 20:19 UTC, KetpuntoG commented on demonstrations/tutorial_error_prop.py
> +np.allclose(qml.matrix(op1), qml.matrix(op2))
I feel like this paragraph cuts the thread of the explanation, could you put it as a .. note: without the code?

2024-04-26 20:19 UTC, KetpuntoG commented on demonstrations/tutorial_error_prop.py
> +#     \epsilon = \sqrt{2 - 2 * sin(\theta)}
Not sure why it is not rendering correctly 🤔

2024-04-26 20:19 UTC, KetpuntoG commented on demonstrations/tutorial_error_prop.py
> +            decomposition += [qml.Hadamard(0), qml.T(0), qml.Hadamard(0)]
qml.Hadamard(wires)?

2024-04-26 20:19 UTC, KetpuntoG commented on demonstrations/tutorial_error_prop.py
> +        return SpectralNormError(error)
Could you clarify why `SpectralNormError(error)`? Intuitively I would have written `return error`

2024-04-29 16:01 UTC, josh146 commented on demonstrations/tutorial_error_prop.py
> +How to: Track Algorithmic error using PennyLane
```suggestion
How to track Algorithmic error using PennyLane
```
:)

2024-04-29 16:04 UTC, josh146 commented on demonstrations/tutorial_error_prop.py
> +Introduction
Note that a title of "Understanding the types of error" implies a very different type of content and goal than "How to track algorithmic error in PennyLane". If the goal of this content is to show someone the steps to track algorithmic error, we should keep the current title.

If instead the focus is to _teach someone about different types of errors_, the suggested title is more appropriate.

@Jaybsoni what is the main purpose of this content?

2024-04-29 16:05 UTC, josh146 commented on demonstrations/tutorial_error_prop.py
> +- Measurement Uncertainty
Is there something we could link out to here for these error types? For a how-to (i.e., that is, a recipe) we should try and refrain from teaching concepts.

2024-04-29 16:15 UTC, soranjh commented on demonstrations/tutorial_error_prop.py
> +- Measurement Uncertainty
@josh my point is that some of these names look a bit ambiguous. For example, if there is clear definition of "Approximation Error" in the literature that experts agree upon, then no need to explain here.

2024-04-30 18:51 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +Introduction
@josh146 and @KetpuntoG, 

I think first and foremost we want to showcase the new features we have implemented on the error tracking front. I have tried to highlight the features by choosing some simply, yet realistic applications with which to apply them. 

I think the best way to present the code without failing into the trap of having to explain all the theory behind error tracking would be this approach. I think it is more of a "how to", then a "tutorial", but I would love to get your opinion on its current state and what needs to be added or removed.

2024-04-30 18:54 UTC, josh146 commented on demonstrations/tutorial_error_prop.py
> +Introduction
sounds great, I agree @Jaybsoni!

2024-05-01 16:09 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +- Measurement Uncertainty
Added explanation

2024-05-01 16:10 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +*rounding* error and apply :code:`qml.RX(1.2)`; how much error would we have?
I rephrased the paragraph

2024-05-01 16:18 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +
Added

2024-05-01 16:19 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +# diagonalizing the operators. For this reason, we tend to use upper bounds on the spectral norm error
Added

2024-05-01 16:19 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +    Hamiltonian, time, n=10, order=4
Nice catch, updated them to match!

2024-05-01 16:30 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +# Custom Error Operations
I see your point, I don't think I have any concrete reason why it should come after. I think it just flows better this way in my opinion.

2024-05-01 16:32 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +# hardware does not natively support X-axis rotation gate :class:`~.pennylane.RX`.
I hesitate to say that, because I don't perform a true Clifford + T decomposition. In this case I prefer having a simple example as opposed to a realistic one. I updated the paragraph to extend the restriction to all rotations :+1:

2024-05-01 16:35 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +            decomposition += [qml.Hadamard(0), qml.T(0), qml.Hadamard(0)]
Nice catch!

2024-05-01 16:36 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +        return SpectralNormError(error)
This is because the Error Operation class needs to return an instance of AlgorithmicError (in this case SpectralNormError) in order to properly track it through the circuit. I don't think the user needs to know that?

2024-05-01 16:57 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +to help track algorithmic error.
Updated

2024-05-01 16:57 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +# The most common of which is  the Suzuki-Trotter product formula. This subroutine introduces **algorithmic**
There is a reference for the Theory of Trotter Error Paper

2024-05-01 16:59 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +# Tracking Errors in Hamiltonian Simulation
How do you mean? I updated the paragraph slightly, but it does talk about the error in Hamiltonian simulation.

2024-05-01 17:00 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +# Conclusion
Any Ideas 😂? I am not sure what else to add.

2024-05-01 17:01 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +Introduction
I rephrased it, trying to be a little more verbose, but without over explaining to keep it a "how to"

2024-05-01 17:01 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +One way to quantify the error of an operator is to compute the spectral norm of the difference between the approximate
Updated 👍🏼

2024-05-01 17:01 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +# With the new abstract classes it's easy for anyone to define and track custom operations with error.
I rephrased it

2024-05-01 17:03 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +#     \epsilon = \sqrt{2 - 2 * sin(\theta)}
This renders correctly for me. Try emptying your cache?

2024-05-01 19:13 UTC, KetpuntoG reviewed
A great improvement! Thanks for working on all the suggestions

2024-05-01 19:13 UTC, KetpuntoG commented on demonstrations/tutorial_error_prop.py
> +- **Measurement Uncertainty:** The nature of quantum measurement uncertainity.
```suggestion
- **Measurement Uncertainty:** The nature of quantum measurement uncertainty. 
```

2024-05-01 19:13 UTC, KetpuntoG commented on demonstrations/tutorial_error_prop.py
> +Consider for example, that instead of applying :code:`qml.RX(1.234)` we incure some *rounding* error in the rotation angle;
```suggestion
Consider for example, that instead of applying :code:`qml.RX(1.234)` we incur some *rounding* error in the rotation angle;
```

2024-05-01 19:13 UTC, KetpuntoG commented on demonstrations/tutorial_error_prop.py
> +# The *approximation* error we incure from this decomposition is given by the expression:
```suggestion
# The *approximation* error we incur from this decomposition is given by the expression:
```

2024-05-01 19:13 UTC, KetpuntoG commented on demonstrations/tutorial_error_prop.py
> +# absolute difference between the true rotation angle and the next lowest mulitple of :math:`\frac{\pi}{4}`.
```suggestion
# absolute difference between the true rotation angle and the next lowest multiple of :math:`\frac{\pi}{4}`.
```

2024-05-01 19:13 UTC, KetpuntoG commented on demonstrations/tutorial_error_prop.py
> +# Conclusion
Maybe something similar to this?

In this demonstration, we show the new PennyLane [...] classes and explain how to build a custom error operation. Knowing the error can help us to compare the efficiency of algorithms or to make decisions when building our circuits. So we hope that you can make use of these tools in cutting edge research workflows to track errors.

2024-05-01 19:13 UTC, KetpuntoG commented on demonstrations/tutorial_error_prop.py
> +# .. include:: ../_static/authors/jay_soni.txt
```suggestion
```
not needed anymore :)

2024-05-01 19:24 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +# .. include:: ../_static/authors/jay_soni.txt
Should I remove the whole section? Or just the line you highlighted?

2024-05-01 19:27 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +phi1, phi2 = (phi + 0.12, phi - 3.45)
Nice catch! I think I was just trying to reuse to phi from earlier on, but its not required. I will change it.

2024-05-01 19:27 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +phi1, phi2 = (phi + 0.12, phi - 3.45)
```suggestion
phi1, phi2 = (0.12, 3.45)
```

2024-05-01 19:28 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +# Notice that the sequence :math:`\hat{H} \cdot \hat{T} \cdot \hat{H} = \hat{RX}(\frac{\pi,4})`
Fixed

2024-05-01 19:53 UTC, soranjh requested changes
Looks good, left some final suggestions. Will approve when they are addressed.

2024-05-01 19:53 UTC, soranjh commented on demonstrations/tutorial_error_prop.py
> +We refer to the first three of these as "Algorithmic Errors"; typically, these types of computations are performed by
These errors are typically computed ...

2024-05-01 19:53 UTC, soranjh commented on demonstrations/tutorial_error_prop.py
> +# computing. Tracking the error for time evolving a quantum state under a given Hamiltonian!
Consider this:
workflows in quantum computing: time evolving a quantum state under a given Hamiltonian!

2024-05-01 19:53 UTC, soranjh commented on demonstrations/tutorial_error_prop.py
> +# The most common method to accomplish this the Suzuki-Trotter product formula. This subroutine introduces
You can put a reference here as "Suzuki-Trotter product formula [1]" or link to the wiki page.

2024-05-01 19:53 UTC, soranjh commented on demonstrations/tutorial_error_prop.py
> +# The most common method to accomplish this the Suzuki-Trotter product formula. This subroutine introduces
```suggestion
# The most common method to accomplish this is the Suzuki-Trotter product formula. This subroutine introduces
```

2024-05-01 19:53 UTC, soranjh commented on demonstrations/tutorial_error_prop.py
> +- **Algorithm Specific Error:** The error caused by the algorithm itself (eg. QPE with limited readout qubits).
algorithm-specific?

2024-05-01 19:53 UTC, soranjh commented on demonstrations/tutorial_error_prop.py
> +# Tracking Errors in Hamiltonian Simulation
Not very important, but from the title, I expected to see an example that tracks several errors that can occur in the Hamiltonian simulation workflow, e.g. state prep, ...

The text kind of fits a title like Tracking Error in Time Evolution. Maybe I miss something here, so you can keep the existing title if you want.

2024-05-01 19:53 UTC, soranjh commented on demonstrations/tutorial_error_prop.py
> +# With the new abstract classes it's easy for anyone to define and track custom operations with error.
Consider something like this:
With the new :class:`~.pennylane.resource.SpectralNormError` :class:`~.pennylane.resource.ErrorOperation` abstract classes implemented in PL for tracking and computing error ...

2024-05-01 19:53 UTC, soranjh commented on demonstrations/tutorial_error_prop.py
> +# to :math:`\hat{RX}(\frac{\pi}{4}) \ ` (up to a global phase :math:`e^{i \frac{\pi}{8}}`):
This does not render correctly in the built version.

2024-05-01 19:53 UTC, soranjh commented on demonstrations/tutorial_error_prop.py
> +#     \epsilon = \sqrt{2 - 2 * sin(\theta)}
```suggestion
#     \epsilon = \sqrt{2 - 2 \times sin(\theta)}
```

2024-05-01 19:53 UTC, soranjh commented on demonstrations/tutorial_error_prop.py
> +print("Error from function: ", error_from_theory)
The current output is:
```
Explicit computation:  0.22184346764856389
Error from function:  SpectralNormError(0.22184346764856405)
```

You might just return the error with print("Error from function: ", error_from_theory.error)

2024-05-01 19:53 UTC, soranjh commented on demonstrations/tutorial_error_prop.py
> +    # Approx Time evolution:
```suggestion
    # Approx time evolution:
```

2024-05-01 19:53 UTC, soranjh commented on demonstrations/tutorial_error_prop.py
> +# :class:`~.pennylane.resource.ErrorOperation` classes in PennyLane. We highlighted the new functionality
```suggestion
# :class:`~.pennylane.resource.ErrorOperation` classes in PennyLane. We also highlighted the new functionality
```

2024-05-01 19:53 UTC, soranjh commented on demonstrations/tutorial_error_prop.py
> +# We explained how to construct a custom error operation. We used this in a simple circuit to track and
```suggestion
# We explained how to construct a custom error operation and used it in a simple circuit to track and
```

2024-05-01 19:53 UTC, soranjh commented on demonstrations/tutorial_error_prop.py
> +# Conclusion
A few ideas to think about:
* you can dream about what ambitious things can be done with this, e.g., maybe this can help to optimise the errors
* test new upper bound errors for a given component that a researcher developed and see how they work in a workflow (or something on that line)
* what this ultimately leads to? where we want to go from here?
* how researchers can upgrade and use this beyond the simple examples we provided

2024-05-01 19:53 UTC, soranjh commented on demonstrations/tutorial_error_prop.py
> +# Tracking the error for each of these components individually is great, but we ultimately want to put these
Make it more general:
Tracking the error for each component individually

2024-05-01 20:21 UTC, trbromley reviewed
Thanks @Jaybsoni

2024-05-01 20:21 UTC, trbromley commented on demonstrations/tutorial_error_prop.py
> +print(f"Error from Suzuki-Trotter algorithm: {error:.5f}")
Suppose you look at the `TrotterProduct` error in `qml.specs`:
```python
time = 0.1
Hamiltonian = qml.X(0) + qml.Y(0)

exact_op = qml.exp(Hamiltonian, 1j * time)  #  U = e^iHt ~ TrotterProduct(..., order=2)

@qml.qnode(qml.device("default.qubit"))
def approx_op():
    qml.TrotterProduct(  #  eg: e^iHt ~ e^iXt/2 * e^iYt * e^iXt/2
        Hamiltonian,
        time,
        order=2,
    )
    return qml.state()

qml.specs(approx_op)()["errors"]
# {'SpectralNormError': SpectralNormError(0.01066666666666667)}
```
This is different to the error in the demo of `0.00037`. Should it be?

2024-05-01 20:21 UTC, trbromley commented on demonstrations/tutorial_error_prop.py
> +one_norm_error_bound = op.error(method="one-norm")  # one-norm based scaling
I understand having read the text more carefully, but on an initial look it feels weird to have `"one-norm"` be a method for calculating an error of the spectral norm - instead it just looks like we're calculating the one-norm error.

2024-05-01 20:21 UTC, trbromley commented on demonstrations/tutorial_error_prop.py
> +In order to accurately determine the resources required to run a given quantum workflow, one must carefully track
> determine the resources required to run a given quantum workflow

We mention resource tracking in the first line but don't actually show it in code in this how-to guide. Was this a conscious decision that it makes the guide to heavy?

2024-05-02 14:40 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +print(f"Error from Suzuki-Trotter algorithm: {error:.5f}")
Yes, when using TrotterProduct in a circuit we use the upper-bounds on the error as its more efficient to compute.

2024-05-02 14:42 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +one_norm_error_bound = op.error(method="one-norm")  # one-norm based scaling
Ah, I can see how it could be misleading. We could potentially change the keyword string to be `method="one-norm-bound"`? This would have to be a follow up PR and then update to the demo.

2024-05-02 14:47 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +# computing. Tracking the error for time evolving a quantum state under a given Hamiltonian!
Added

2024-05-02 14:49 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +# The most common method to accomplish this the Suzuki-Trotter product formula. This subroutine introduces
Added

2024-05-02 15:28 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +# to :math:`\hat{RX}(\frac{\pi}{4}) \ ` (up to a global phase :math:`e^{i \frac{\pi}{8}}`):
It renders correctly for me? Try clearing your cache?

2024-05-02 15:32 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +# With the new abstract classes it's easy for anyone to define and track custom operations with error.
Added

2024-05-02 15:33 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +print("Error from function: ", error_from_theory)
Fixed

2024-05-02 15:35 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +# Tracking the error for each of these components individually is great, but we ultimately want to put these
Fixed

2024-05-02 15:59 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +# Conclusion
Updated

2024-05-02 15:59 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +
Updated

2024-05-02 15:59 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +this demo, we present the latest tools in PennyLane which *automatically* track algorithmic error.
Made it more consistent

2024-05-02 16:00 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +# Time evolving a quantum state under a hamiltonian requires generating the unitary :math:`\hat{U} = exp(iHt)`.
The code example uses +iHt. I think it's just a choice of convention.

2024-05-02 16:01 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +- **Algorithm Specific Error:** The error caused by the algorithm itself (eg. QPE with limited readout qubits).
Yes, I added the dash, if you have a better name suggestion, than happy to change it.

2024-05-02 16:02 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +We refer to the first three of these as "Algorithmic Errors"; typically, these types of computations are performed by
Re-worded

2024-05-02 16:20 UTC, DSGuala reviewed
Left a few minor suggestions:
- Capitalizing "Hamiltonian"
- Adding hyphens
- Links to docs

2024-05-02 16:20 UTC, DSGuala commented on demonstrations/tutorial_error_prop.py
> +# Time evolving a quantum state under a hamiltonian requires generating the unitary :math:`\hat{U} = \exp(iHt)`.
```suggestion
# Time evolving a quantum state under a Hamiltonian requires generating the unitary :math:`\hat{U} = \exp(iHt)`.
```

2024-05-02 16:20 UTC, DSGuala commented on demonstrations/tutorial_error_prop.py
> +# Let's explicitly compute the error from this algorithm for a simple hamiltonian:
```suggestion
# Let's explicitly compute the error from this algorithm for a simple Hamiltonian:
```

2024-05-02 16:20 UTC, DSGuala commented on demonstrations/tutorial_error_prop.py
> +# we did for hamiltonian simulation, using :func:`op.error()`.
```suggestion
# we did for Hamiltonian simulation, using :func:`op.error()`.
```

2024-05-02 16:20 UTC, DSGuala commented on demonstrations/tutorial_error_prop.py
> +# use of these tools in your cutting edge research workflows.
```suggestion
# make more resource-efficient algorithms, ultimately unlocking new applications. We hope that you can make
# use of these tools in your cutting-edge research workflows.
```

2024-05-02 16:20 UTC, DSGuala commented on demonstrations/tutorial_error_prop.py
> +- **Hardware Noise Error:** The error introduced by noisy quantum channels (eg. Bitflip, Phaseflip).
Optional: link to :class:\`\~.pennylane.BitFlip\` and :class:\`\~.pennylane.PhaseFlip\`

2024-05-02 16:39 UTC, trbromley commented on demonstrations/tutorial_error_prop.py
> +one_norm_error_bound = op.error(method="one-norm")  # one-norm based scaling
That could work! What do you think @DSGuala? Might be a bit too late to respond in this release.

2024-05-02 16:48 UTC, DSGuala commented on demonstrations/tutorial_error_prop.py
> +one_norm_error_bound = op.error(method="one-norm")  # one-norm based scaling
+1 it should be `method="one-norm-bound"` or `bounding_method="one-norm"`
+1 it's too late to respond in this release

@trbromley shall we just open a ticket to address this in the next release? It should be a quick update when there is more availability for PR reviews and CI time.

2024-05-02 18:14 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +- **Hardware Noise Error:** The error introduced by noisy quantum channels (eg. Bitflip, Phaseflip).
I think it would make the bullet points too cluttered. Choosing to leave it as is for now 👍🏼

2024-05-02 18:18 UTC, Jaybsoni commented
@KetpuntoG or @trbromley , Do you know where I can find the the thumbnail for this demo? You mentioned that Tarik was working on one?

2024-05-02 20:02 UTC, soranjh approved these changes
Thanks @Jaybsoni, please check the consistency of the links to PL functions.

2024-05-02 20:02 UTC, soranjh commented on demonstrations/tutorial_error_prop.py
> +# Along with executing the circuit, we can also compute the error in the circuit through :func:`qml.specs()`:
:func:`~pennylane.specs()`

The link does not work as is. Please check everywhere for broken links.

2024-05-02 20:08 UTC, soranjh commented on demonstrations/tutorial_error_prop.py
> +- **Hardware Noise Error:** The error introduced by noisy quantum channels (eg. Bitflip, Phaseflip).
Might link to PL classes for Bitflip, Phaseflip.

2024-05-02 20:26 UTC, KetpuntoG requested changes
Thanks Jay! 🚀 I'm blocking the merge until we update the thumbnail but it's ready for me ✅

2024-05-02 20:26 UTC, KetpuntoG commented on demonstrations/tutorial_error_prop.py
> +# Notice that :math:`\hat{Rx}(\frac{\pi}{4}) \  = \ \hat{H} \cdot \hat{T} \cdot \hat{H}`
```suggestion
# Notice that :math:`\hat{R_x}(\frac{\pi}{4}) \  = \ \hat{H} \cdot \hat{T} \cdot \hat{H}`
```

2024-05-02 20:26 UTC, KetpuntoG commented on demonstrations/tutorial_error_prop.py
> +# :class:`~.pennylane.RY`, :class:`~.pennylane.RZ`). How could we decompose the RX gate?
Maybe :math:`\hat{R_x}`?

2024-05-02 20:26 UTC, KetpuntoG commented on demonstrations/tutorial_error_prop.py
> +# Summary
I would prefer "Conclusion" for consistency with other demos
(Optional)

2024-05-02 20:26 UTC, KetpuntoG commented on demonstrations/tutorial_error_prop.metadata.json
> +    "dateOfLastModification": "2024-04-26T00:00:00+00:00",
You could update to tomorrow

2024-05-02 20:31 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +- **Input / Encoding Error:** The error from embedding classical data into the quantum circuit (eg. initial state prep).
Fixed

2024-05-02 20:34 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +- **Hardware Noise Error:** The error introduced by noisy quantum channels (eg. Bitflip, Phaseflip).
Linked 👍🏼

2024-05-02 20:39 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +# :class:`~.pennylane.RY`, :class:`~.pennylane.RZ`). How could we decompose the RX gate?
I linked `RX` to the pennylane class everywhere except for one instances where I have `qml.RX(1.234)` for the purpose of the example in the code below.

2024-05-02 20:46 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +# Along with executing the circuit, we can also compute the error in the circuit through :func:`qml.specs()`:
Working on this

2024-05-02 20:57 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +# Notice that :math:`\hat{Rx}(\frac{\pi}{4}) \  = \ \hat{H} \cdot \hat{T} \cdot \hat{H}`
Good idea! Added 👍🏼

2024-05-02 20:57 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.py
> +# Summary
Changed it back to this 👍🏼

2024-05-02 21:16 UTC, Jaybsoni commented on demonstrations/tutorial_error_prop.metadata.json
> +    "dateOfLastModification": "2024-04-26T00:00:00+00:00",
Updated

2024-05-02 22:41 UTC, KetpuntoG approved these changes
Good to go!

2024-05-02 23:18 UTC, merged