Lie-sim demo
PennyLaneAI/qml pull request #1085
Opened 2024-04-29 13:18 UTC by Qottmann

A demo and discussion of Lie algebraic simulation techniques, i.e. papers https://arxiv.org/abs/1012.2873 and https://arxiv.org/abs/2308.01432

If you are writing a demonstration, please answer these questions to facilitate the marketing process.

If you are writing a demonstration, please answer these questions to facilitate the marketing process.

* GOALS — Why are we working on this now?
g-sim is a hot topic. Most prominently, it shows that systems with provably absent barren plateaus can be simulated efficiently. This is conceptually interesting, though likely not very relevant in practice since the systems for which this is indeed the case are very rare.

* AUDIENCE — Who is this for?
Quantum researchers, practitioners with a fair understanding. In combination with the linked Intro to DLA demo this should also be suitable for beginners.

* KEYWORDS — What words should be included in the marketing post?
  - dynamical Lie algebra / Lie groups
  - g-sim
  - barren plateaus

* Which of the following types of documentation is most similar to your file? 
(more details [here](https://www.notion.so/xanaduai/Different-kinds-of-documentation-69200645fe59442991c71f9e7d8a77f8))
    
- [ ] Tutorial
- [x] Demo
- [ ] How-to

[sc-58429]

2024-05-02 13:07 UTC, dwierichs requested changes
Amazing demo, @Qottmann :100: 
A very nice read and well-balanced between giving context, introducing theory and showing off code. The simulation code is much neater than I would have anticipated due to the new `qml.dla` module :heart_eyes: 

I left a couple of comments.

Would it be an option to show off the evaluation for a qubit count that is clearly out of reach for a state vector simulator? just because we can and this hammers home the complexity point :)

2024-05-02 13:07 UTC, dwierichs commented on demonstrations/tutorial_liesim.py
> +# .. include:: ../_static/authors/korbinian_kottmann.txt
I think this is no longer needed :thinking:

2024-05-02 13:07 UTC, dwierichs commented on demonstrations/tutorial_liesim.py
> +#     `arXiv:2403.04844 <https://arxiv.org/abs/2403.04844>`__, 2024.
So those are needed in addition to the metadata? Feels a bit redundant :thinking:

2024-05-02 14:22 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +# We are doing a trick of representing the initial state as a Pauli operator, :math:`|0 \rangle \langle 0 |^{\otimes n} = \sum_{i=1}^n (I_i + Z_i)/2`,
Oh yeah you are right 🤔 Have to be a bit more clever to avoid exponentials here, I updated it.

Essentially you can do it analytically and locally for every generator, and thereby avoid exponential complexity

2024-05-02 14:22 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +    e_in = e_in.at[i].set(expectation_h_alpha)
Yeah I think the setting of jnp.array below is from debugging / or just a relic. Perhaps it would indeed be nicer to do normal numpy and then convert to jax numpy later because its just so ugly with the `.at[..].set` method. Updated it.

2024-05-02 14:22 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +def forward(coeffs):
sure!

2024-05-02 14:22 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +def forward(coeffs):
Could even call them `theta` to be in line with the formulas ✅

2024-05-02 14:22 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +from datetime import datetime
I think its fine for this purpose here, its not a benchmark just a print statement to give the reader an idea of the elapsed time. It also has the nicer formatting in `h:mm:ss`

2024-05-02 14:22 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +        print(f"final loss: {val - E_exact}; min loss: {np.min(energy) - E_exact}; after {t1 - t0}")
see above

2024-05-02 14:22 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +        e_t = expm(jnp.einsum("j,jkl->kl", coeffs[i], adjoint_repr[:len(generators)])) @ e_t
yeah good point! ✅

2024-05-02 14:22 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +H = H.simplify()
Oh yes good point! ✅

2024-05-02 14:22 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +#     `arXiv:2403.04844 <https://arxiv.org/abs/2403.04844>`__, 2024.
Yeah I always dread that task, would love for this to be redundant! AFAIK they are two separate things and the metadata is not automatically pulled from the demo 😢

2024-05-02 14:22 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +# .. include:: ../_static/authors/korbinian_kottmann.txt
The `readme` says to put this section at the end, but perhaps without the `.. include::` macro? Is that what you meant?

2024-05-02 14:23 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +are relevant in practice for variational methods [#Mazzola]_, with some arguing for better initialization methods [#Park]_.
did that now ✅

2024-05-02 14:43 UTC, dwierichs commented on demonstrations/tutorial_liesim.py
> +can be computed via the Lie closure :math:`\langle \cdot \rangle_\text{Lie}` (see :func:`~pennylane.lie_closure`),
Is this because of latest/stable links?

2024-05-02 14:43 UTC, dwierichs commented on demonstrations/tutorial_liesim.py
> +can be computed via the Lie closure :math:`\langle \cdot \rangle_\text{Lie}` (see :func:`~pennylane.lie_closure`),
I mean, maybe the objects are not in the version of the docs that sphinx is browsing because they are not in the corresponding version of PL.

2024-05-02 14:44 UTC, dwierichs commented on demonstrations/tutorial_liesim.py
> +# .. include:: ../_static/authors/korbinian_kottmann.txt
Yes, sorry, should have been more precise!
The header is required but the `.. include::` is not.

2024-05-02 14:44 UTC, dwierichs commented on demonstrations/tutorial_liesim.py
> +#     `arXiv:2403.04844 <https://arxiv.org/abs/2403.04844>`__, 2024.
Ah, i would have thought the other way around: The metadata automatically is included in a References section in the demo. Because that's what happens with the "about the author" section...

2024-05-02 14:50 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +#     `arXiv:2403.04844 <https://arxiv.org/abs/2403.04844>`__, 2024.
Maybe that is what is happening and I just didnt get the memo ^^ Havent tried! But I actually dont think so, I usually update the metadata at the very end and didnt run into problems beforehand

2024-05-02 15:33 UTC, josh146 commented on demonstrations/tutorial_liesim.py
> +#     `arXiv:2403.04844 <https://arxiv.org/abs/2403.04844>`__, 2024.
Yeah unfortunately it is redundant rn. The metadata is used for the database (which helps with automatic recommendations and searching), whereas the version in the rst file is simply for preview :(

2024-05-02 15:34 UTC, josh146 commented on demonstrations/tutorial_liesim.py
> +#     `arXiv:2403.04844 <https://arxiv.org/abs/2403.04844>`__, 2024.
What I would love is a tool for automatically generating the metadata file given the demo.

2024-05-03 07:59 UTC, dwierichs commented on demonstrations/tutorial_liesim.py
> +#     `arXiv:2403.04844 <https://arxiv.org/abs/2403.04844>`__, 2024.
Alright, thanks @josh146 for context! :) 
Yeah, that sounds like a nice tool!

2024-05-03 13:29 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +Let us see what the fuzz is all about and learn about the conceptually interesting, yet practically not-too-relevant
Oops, I meant "fuss", actually

2024-05-03 13:33 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +or `Lemma 3.14 in Introduction to Lie Groups and Lie Algebras <https://www.math.stonybrook.edu/~kirillov/mat552/liegroups.pdf>`__),
https://www.math.stonybrook.edu/~kirillov/mat552/liegroups.pdf or https://en.wikipedia.org/wiki/Adjoint_representation ?

The former is a PDF, on mobile or some browsers without pdf preview it may directly download the file. Is that what is happening?
For me it works on MacOS Firefox, safari and brave browsers

2024-05-03 13:34 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +.. math:: \text{Ad}_{e^{-ih_\mu}} = e^{-i \text{ad}_{h_\mu}}.
Hm no, I dont think so. Why do you think so? Both exponentials have an explicit `-i` in the exponent

2024-05-03 13:35 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +
I agree that the diagrams are not really necessary at this point. But there is going to be an extension of this (second demo) where the diagrams will be crucial so I deemed it sensible to introduce them here already

2024-05-06 14:08 UTC, trbromley commented on demonstrations/tutorial_liesim.py
> +.. math:: \text{Ad}_{e^{-ih_\mu}} = e^{-i \text{ad}_{h_\mu}}.
In this equation we have a $+i$ in the left-hand unitary and a $-i$ in the right-hand unitary:
![image](https://github.com/PennyLaneAI/qml/assets/49409390/729df487-249a-4c9a-a0cb-b062515f9478)

But, in this equation we fix a $-i$ in the left-hand unitary and a $+i$ in the right-hand unitary:
![image](https://github.com/PennyLaneAI/qml/assets/49409390/22c6f45d-4836-4371-b528-b7f4abe3326d)

So this just made me question whether we're consistent with $\pm i$.

2024-05-06 14:20 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +.. math:: \text{Ad}_{e^{-ih_\mu}} = e^{-i \text{ad}_{h_\mu}}.
Oh nice catch! One of those is inconsistent, indeed. let me fix that!

2024-05-06 14:33 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +Let us see what the fuzz is all about and learn about the conceptually interesting, yet practically not-too-relevant
I'd trust the native speaker here: buzz or fuss or are they synonymous here?

2024-05-06 14:35 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +can be computed via the Lie closure :math:`\langle \cdot \rangle_\text{Lie}` (see :func:`~pennylane.lie_closure`),
Sphinx was indeed pulling from latest, I changed that in the conf.py but the links still seem to be broken 🤔 I am using the same references as in some docs so it _should_ in principle work after the release at least

2024-05-06 14:43 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +inversely proportional to the dimension of the circuit's dynamical Lie algebra (DLA) in the uniform average case.
✅ updated

I wouldnt start with that admittedly catchy question since that is not really what the demo is about

2024-05-06 20:03 UTC, dwierichs commented on demonstrations/tutorial_liesim.py
> +Lie-algebraic simulation techniques of variaitonal quantum circuits.
Might actually be good to get a sign off from someone relations-related here :upside_down_face:

2024-05-06 20:05 UTC, dwierichs commented on demonstrations/tutorial_liesim.py
> +
Agreed! They can be easily read over if a reader does not find them helpful, and it's very cool to be able to refer back to a very simple usage once it gets more complicated :)

2024-05-06 20:14 UTC, dwierichs commented on _static/demonstration_assets/liesim/thumbnail_liesim.png
Ah, I see! In this case I'd expect them to be different somehow, to differentiate from the "case" where the same $\tilde{U}$ needs to be multiplied to $w$ and $e$. It's clear from the demo text, but as it is the thumbnail, it might be nice to clarify?

2024-05-07 07:42 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +Lie-algebraic simulation techniques of variaitonal quantum circuits.
Perhaps @trbromley

2024-05-07 14:39 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +Let us see what the fuzz is all about and learn about the conceptually interesting, yet practically not-too-relevant
fuss it is then 😆

2024-05-16 09:10 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +Given Hermitian operators :math:`G = \{h_i\}` (think, Hermitian observables like terms of a Hamiltonian),
I added a note :)

2024-05-16 09:10 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +can be computed via the Lie closure :math:`\langle \cdot \rangle_\text{Lie}` (see :func:`~pennylane.lie_closure`),
Some links work now, some still dont (in particular lie_closure and structure constants, which is weird because I am using the exact same link format as in other parts of the docs, where the links work.

2024-05-16 09:11 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +# and use the analytic, normalized trace method :meth:`~pennylane.pauli.PauliSentence.trace`, all to avoid having to go to the full Hilbert space.
this one works now :)

2024-05-16 09:50 UTC, dwierichs approved these changes
Thanks @Qottmann for this nice demo! :) 

I left a number of very small suggestions/ideas, but am approving as none of those are blocking.

2024-05-16 09:50 UTC, dwierichs commented on demonstrations/tutorial_liesim.py
> +The coefficients :math:`f^\gamma_{\alpha \beta}` are called the structure constants of the DLA and can be computed via standard
Maybe?
```suggestion
The coefficients :math:`f^\gamma_{\alpha \beta}` are called the structure constants of the DLA and can be computed via the standard
```

2024-05-16 09:50 UTC, dwierichs commented on demonstrations/tutorial_liesim.py
> +complex vectors in state vector simulators, we evolve a :math:`\text{dim}(\mathfrak{g})`-dimensional expectation
```suggestion
complex vector in state vector simulators, we evolve a :math:`\text{dim}(\mathfrak{g})`-dimensional expectation
```

2024-05-16 09:50 UTC, dwierichs commented on demonstrations/tutorial_liesim.py
> +vector in :math:`\mathfrak{g}`-sim, which is more efficient whenever :math:`\text{dim}(\mathfrak{g}) < 2^n`. In general, it is efficient
maybe "vector of expetation values" or "expectation _value_ vector"? :thinking:

2024-05-16 09:50 UTC, dwierichs commented on demonstrations/tutorial_liesim.py
> +# So just the generators with some coefficient. Here we choose :math:`J=h=0.5` for simplicity.
```suggestion
# So just the generators with some coefficients. Here we choose :math:`J=h=0.5` for simplicity.
```

2024-05-16 09:50 UTC, dwierichs commented on demonstrations/tutorial_liesim.py
> +can be computed via the Lie closure :math:`\langle \cdot \rangle_\text{Lie}` (see :func:`~lie_closure`),
```suggestion
can be computed via the Lie closure :math:`\langle \cdot \rangle_\text{Lie}` (see :func:`~pennylane.lie_closure`),
```

2024-05-16 09:50 UTC, dwierichs commented on demonstrations/tutorial_liesim.py
> +# Beyond 6 qubits, :math:`\mathfrak{g}`-sim is more efficient in simulating the TFIM Hamiltonian.
I guess it mostly simulates the circuit, rather than the Hamiltonian? Or am I misunderstanding the statement?

2024-05-16 09:52 UTC, dwierichs commented on demonstrations/tutorial_liesim.py
> +can be computed via the Lie closure :math:`\langle \cdot \rangle_\text{Lie}` (see :func:`~pennylane.lie_closure`),
I found that all links work now, except for one, which I suggested a modification for in my new review (it was indeed the old formatting, whereas the new one including "pennylane" works :) )

2024-05-16 11:05 UTC, Qottmann commented on demonstrations/tutorial_liesim.metadata.json
> +        }
Dont know to be honest, so far I just cited any other demo I linked in the demo here

2024-05-16 11:05 UTC, Qottmann commented on demonstrations/tutorial_liesim.metadata.json
> +        }
And since I didnt link to the clifford demo I am not sure this is necessary/appropriate here

2024-05-16 11:06 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +The coefficients :math:`f^\gamma_{\alpha \beta}` are called the structure constants of the DLA and can be computed via standard
thats my euro-english lol

2024-05-16 11:08 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +vector in :math:`\mathfrak{g}`-sim, which is more efficient whenever :math:`\text{dim}(\mathfrak{g}) < 2^n`. In general, it is efficient
Changed all occurences of "expectation vector" -> "expectation value vector" ✅

2024-05-16 11:09 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +# Beyond 6 qubits, :math:`\mathfrak{g}`-sim is more efficient in simulating the TFIM Hamiltonian.
good point, yes, will clarify ✅

2024-05-16 11:17 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +In particular, the infamous barren plateau problem has been fully characterized by the underlying
nice! ✅

2024-05-16 11:40 UTC, dwierichs commented on demonstrations/tutorial_liesim.metadata.json
> +        }
Ah, got it! :) Sounds good

2024-05-16 11:41 UTC, dwierichs commented on demonstrations/tutorial_liesim.py
> +vector in :math:`\mathfrak{g}`-sim, which is more efficient whenever :math:`\text{dim}(\mathfrak{g}) < 2^n`. In general, it is efficient
:100:

2024-05-27 13:26 UTC, ikurecic reviewed
Hey @Qottmann , here are just a few comments.

Also a note that there's a rendering issue with headings (the ToC in the right-side panel doesn't respond well to the used inline math) that I'm following up about.

2024-05-27 13:26 UTC, ikurecic commented on demonstrations/tutorial_liesim.py
> +# As mentioned before, polynomially sized DLAs are rare with the transverse field Ising model (TFIM) with nearest neighbors being one of them.
```suggestion
# As mentioned before, polynomially sized DLAs are rare, with the transverse-field Ising model (TFIM) with nearest neighbors being one of them.
```

2024-05-27 13:26 UTC, ikurecic commented on demonstrations/tutorial_liesim.py
> +# We take for simplicity the one dimensional variant with open boundary conditions,
```suggestion
# We take, for simplicity, the one-dimensional variant with open boundary conditions,
```

2024-05-27 13:26 UTC, ikurecic commented on demonstrations/tutorial_liesim.py
> +plt.show()
Could you add the ordinate label?

2024-05-27 13:26 UTC, ikurecic commented on demonstrations/tutorial_liesim.py
> +# Let us do a quick run of the variational quantum eigensolver (VQE) on the system at hand.
```suggestion
# Let us do a quick run of the :doc:`variational quantum eigensolver (VQE) </demos/tutorial_vqe/>` on the system at hand.
```

2024-05-27 13:26 UTC, ikurecic commented on demonstrations/tutorial_liesim.py
> +# We can use the Hamiltonian variational ansatz as a natural parametrization of an Ansatz circuit to obtain
```suggestion
# We can use the Hamiltonian variational ansatz as a natural parametrization of an ansatz circuit to obtain
```
Unless there's a reason to capitalize here?

2024-05-27 13:26 UTC, ikurecic commented on demonstrations/tutorial_liesim.py
> +# the ground state energy.
```suggestion
# the ground-state energy.
```
Hyphen when it acts as a compound adjective.

2024-05-27 13:26 UTC, ikurecic commented on demonstrations/tutorial_liesim.py
> +# Now we can run the optimization to find the ground state energy.
```suggestion
# Now we can run the optimization to find the ground-state energy.
```

2024-05-27 13:26 UTC, ikurecic commented on demonstrations/tutorial_liesim.py
> +# We see good convergence to the true ground state energy after ``100`` epochs.
```suggestion
# We see good convergence to the true ground-state energy after ``100`` epochs.
```

2024-05-27 13:26 UTC, ikurecic commented on demonstrations/tutorial_liesim.py
> +# expectation values.
This is a good hook for the lead paragraph. Maybe you can mention there, too, to announce it.

2024-06-04 12:02 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +:math:`\mathfrak{g}`-sim
if the math mode headings are a problem I can just remove them

2024-06-04 12:24 UTC, ikurecic commented on demonstrations/tutorial_liesim.py
> +Lie-algebraic simulation techniques of variational quantum circuits in :math:`\mathfrak{g}`-sim.
You know what, maybe you should say that outright, then?
Just because, if I read this opening paragraph without any other context, I would not have any interest in continuing. 🤔
Does that make sense? You don't have to endorse or recommend anything, but you spent a lot of time writing this, and there's got to be a reason for that. :) We _do_ want people to read and learn from your work, so we should tell them why. Explicitly adding this 'disclaimer' in the opener might be a very good way of doing that. Would something like that vibe with you?

2024-06-04 12:30 UTC, ikurecic commented on demonstrations/tutorial_liesim.py
> +plt.show()
That's totally fair. In my mind the $2^n$ felt kind of detached from the matter and I would have spelled out dim(g) on the ordinate, but it's fine like this.

2024-06-07 11:36 UTC, ikurecic commented on demonstrations/tutorial_liesim.py
> +Lie-algebraic simulation techniques of variational quantum circuits in :math:`\mathfrak{g}`-sim.
Nice!
The in-between version ([this one](https://github.com/PennyLaneAI/qml/pull/1085/commits/19d9b2294cb23b35dba907114b0e2a9f192a2709), right?) is great.
If you want to revert to that, shall we call it done?

2024-06-07 12:01 UTC, Qottmann commented on demonstrations/tutorial_liesim.py
> +Lie-algebraic simulation techniques of variational quantum circuits in :math:`\mathfrak{g}`-sim.
Yeah I also like that one better. Pushing the revert now

2024-06-07 12:19 UTC, ikurecic approved these changes
Thanks, @Qottmann , looks great — looking forward to seeing the next one.

2024-06-07 12:42 UTC, merged