Qae
PennyLaneAI/qml pull request #1099
Opened 2024-05-09 21:57 UTC by asymptoticgains

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Remember to do a grammar check of the content you include.
- [ ] All tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

----
If you are writing a demonstration, please answer these questions to facilitate the marketing process.

* GOALS — Why are we working on this now?

  *Eg. Promote a new PL feature or show a PL implementation of a recent paper.*

* AUDIENCE — Who is this for?

  *Eg. Chemistry researchers, PL educators, beginners in quantum computing.*

* KEYWORDS — What words should be included in the marketing post?

* Which of the following types of documentation is most similar to your file? 
(more details [here](https://www.notion.so/xanaduai/Different-kinds-of-documentation-69200645fe59442991c71f9e7d8a77f8))
    
- [ ] Tutorial
- [ ] Demo
- [ ] How-to

2024-08-07 18:47 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qnn_multivariate_regression.py
> +In this tutorial, we show how to use a variational quantum circuit to fit a simple multivariate function,
```suggestion
In this tutorial, we show how to use a variational quantum circuit to fit the simple multivariate function
```

2024-08-07 20:04 UTC, alvaro-at-xanadu requested changes
I think this is looking pretty good, just some minor comments. Once addressed, I'll put it through a grammar checker

2024-08-07 20:53 UTC, gmlejarza commented on demonstrations/tutorial_qnn_multivariate_regression.py
> +#
We could, but theoretically speaking, what is going on under the hood is that "Hamiltonian encoding". We need this theoretical framework to claim that what we are doing is going to work (because the circuit represents a Fourier series). I'd suggest that if we want to keep some theoretical fundamentals of what we are doing, I'll keep it. On the other hand, if we just want to provide an easy "how-to" we can omit it.

2024-08-07 21:00 UTC, gmlejarza commented on demonstrations/tutorial_qnn_multivariate_regression.py
> +# We define x_train, y_train
```suggestion
# We define ``x_train``, ``y_train``
```

2024-08-07 21:03 UTC, gmlejarza commented on demonstrations/tutorial_qnn_multivariate_regression.py
> +
This is just some reshaping we need in order to use JAX and its optimizer. I could add a print to show which shapes they have 👍

2024-08-07 21:07 UTC, gmlejarza commented on demonstrations/tutorial_qnn_multivariate_regression.py
> +# of a variational quantum circuit to solve a regression problem for a two dimensional function.
That's true, we made use that the circuit represents a Fourier series in the sense that's what make this to work. But we don't match any Fourier series explicitly. Maybe the wording is not very accurate here and I can omit the mention to the Fourier series, since it's been already explained

2024-08-07 21:09 UTC, gmlejarza commented on demonstrations/tutorial_qnn_multivariate_regression.py
> +
Good point, I'll add some comments 👍

2024-08-07 21:12 UTC, gmlejarza commented on demonstrations/tutorial_qnn_multivariate_regression.py
> +def mse(params,x,targets):
```suggestion
def mse(params,x,targets):
    # We compute the Mean Square Error between the target function and the quantum circuit to quantify the quality of our estimator
```

2024-08-07 21:15 UTC, gmlejarza commented on demonstrations/tutorial_qnn_multivariate_regression.py
> +def loss_fn(params, x,targets):
```suggestion
def loss_fn(params, x,targets):
    # We define the loss function to feed our optimizer
```

2024-08-08 13:31 UTC, gmlejarza commented
My author "id" is missing somewhere and the "demo preview" doesn't render my name in the authors section

2024-09-09 08:15 UTC, ikurecic commented
[sc-63360]

2024-09-09 14:06 UTC, alvaro-at-xanadu approved these changes

2024-09-13 11:27 UTC, ikurecic reviewed
Thanks, @asymptoticgains . I've left some suggestions and comments here for you.

2024-09-13 11:27 UTC, ikurecic commented on demonstrations/tutorial_qnn_multivariate_regression.py
> +# Now we will specify the range of :math:`x_1` and :math:`x_2` values and store those values in an input data vector. We are fitting the function for :math:`x_1, x_2 \in [-1, 1]` using 30 evenly-spac
```suggestion
# Now we will specify the range of :math:`x_1` and :math:`x_2` values and store those values in an input data vector. We are fitting the function for :math:`x_1, x_2 \in [-1, 1]` using 30 evenly spaced samples for each variable.
```

2024-09-13 11:27 UTC, ikurecic commented on demonstrations/tutorial_qnn_multivariate_regression.py
> +# create a 2D grid to make sure that, for each value of
```suggestion
# create a two-dimensional grid to make sure that, for each value of
```

2024-09-13 11:27 UTC, ikurecic commented on demonstrations/tutorial_qnn_multivariate_regression.py
> +# We define ``x_train``, ``y_train`` using the above vectors, reshaping them for our convenience
```suggestion
# We define ``x_train`` and ``y_train`` using the above vectors, reshaping them for our convenience
```

2024-09-13 11:27 UTC, ikurecic commented on demonstrations/tutorial_qnn_multivariate_regression.py
> +# ------------------------------------------
```suggestion
# Optimizing the circuit
# ----------------------
```

2024-09-13 11:27 UTC, ikurecic commented on demonstrations/tutorial_qnn_multivariate_regression.py
> +    # We compute the Mean Square Error between the target function and the quantum circuit to quantify the quality of our estimator
```suggestion
    # We compute the mean square error between the target function and the quantum circuit to quantify the quality of our estimator
```

2024-09-13 11:27 UTC, ikurecic commented on demonstrations/tutorial_qnn_multivariate_regression.py
> +#Here, we are choosing an Adam Optimizer with a learning rate of 0.05 and 300 steps.
```suggestion
#Here, we are choosing an Adam optimizer with a learning rate of 0.05 and 300 steps.
```

2024-09-13 11:27 UTC, ikurecic commented on demonstrations/tutorial_qnn_multivariate_regression.py
> +# Cool! We have managed to successfully fit a multidimensional function using a Parametrized Quantum Circuit!
```suggestion
# Cool! We have managed to successfully fit a multidimensional function using a parametrized quantum circuit!
```

2024-09-13 11:27 UTC, ikurecic commented on demonstrations/tutorial_qnn_multivariate_regression.py
> +# can be trained further, increasing number of iterations in the training to maximize the accuracy. It also
```suggestion
# can be trained further, increasing the number of iterations in the training to maximize the accuracy. It also 
```

2024-09-13 11:27 UTC, ikurecic commented on demonstrations/tutorial_qnn_multivariate_regression.py
> +# paves the way for addressing a regression problem for a :math:`N`-dimensional function, as everything presented
```suggestion
# paves the way for addressing a regression problem for an :math:`N`-dimensional function, as everything presented 
```

2024-10-01 14:57 UTC, ikurecic approved these changes

2024-10-01 14:57 UTC, merged