[WIP] Qubitization demo
PennyLaneAI/qml pull request #1113
Opened 2024-05-22 15:25 UTC by KetpuntoG

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Remember to do a grammar check of the content you include.
- [ ] All tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

----
If you are writing a demonstration, please answer these questions to facilitate the marketing process.

* GOALS — Why are we working on this now?

  *Eg. Promote a new PL feature or show a PL implementation of a recent paper.*

* AUDIENCE — Who is this for?

  *Eg. Chemistry researchers, PL educators, beginners in quantum computing.*

* KEYWORDS — What words should be included in the marketing post?

* Which of the following types of documentation is most similar to your file? 
(more details [here](https://www.notion.so/xanaduai/Different-kinds-of-documentation-69200645fe59442991c71f9e7d8a77f8))
    
- [ ] Tutorial
- [ ] Demo
- [ ] How-to

2024-05-27 22:22 UTC, KetpuntoG commented on demonstrations/tutorial_qubitization.py
> +.. figure:: ../_static/demonstration_assets/qubitization/qubitization_qpe.jpeg
Hmm, actually this is an abuse of notation; I have to change it

2024-06-25 15:58 UTC, gmlejarza commented
Very nice demo @KetpuntoG! It explains the basics of qubitization in a very accessible way.
I'll write you here some suggestions that we have discussed in person.

Rendering/format suggestions:
1. ** its eigenvalues encode the eigenvalues of  H**
2. { $1,e^{\pm i \theta}$ } -> $e^{\pm i \theta}$
3. `$\text{PSP}_{\mathcal{H}$`

Content suggestions
1. In `Qubitization as a rotation`: emphasize why we need a rotation (eigenvalue $e^{\pm i \theta}$) and not a reflexion (eigenvalue $\pm 1$)
2.  In `Qubitization in PennyLane`: maybe include the form of the matrix of the Qubitization operator $Q$.
3.  In `Qubitization in PennyLane`: in `where k is the number of terms in the Hamiltonian` specify that you refer to the number of Pauli matrices in the LCU decomposition. Otherwise it might seem like the number of terms in the Hamiltonian matrix.
4. In `Qubitization in PennyLane`: maybe including a picture of the circuit for QPE using the $Q$ operator as our $U$ will be clarifying.
5. In `Qubitization in PennyLane`: in the comment `Apply QPE with the walk operator` maybe change walk operator for Qubitization operator.

2024-08-19 18:55 UTC, ixfoduap requested changes
Stopping here due to lack of time

2024-08-19 18:55 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +and we will code one of its more important applications in PennyLane via the :class:`~.pennylane.Qubitization` template.
```suggestion
Encoding a Hamiltonian into a quantum computer is a fundamental task for many applications, but the way to do it is not unique.
One method that has gained special status is known as **Qubitization**. In this demo, we will introduce the qubitization operator and explain how to view it as a rotation operator. We then explain how to combine it with quantum phase estimation in an example application, illustrated with example code in PennyLane using the :class:`~.pennylane.Qubitization` template.
```

2024-08-19 18:55 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +Going directly to the point, the Qubitization operator is defined as:
```suggestion
For a Hamiltonian 'math:`\mathcal{H}`, the Qubitization operator is defined as:
```

2024-08-19 18:55 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +used on `this demo <https://pennylane.ai/qml/demos/tutorial_lcu_blockencoding/>`_.
```suggestion
where :math:`\text{Prep}_{\mathcal{H}}` and :math:`\text{Sel}_{\mathcal{H}}` are the preparation and selection operators. They are explained `this demo <https://pennylane.ai/qml/demos/tutorial_lcu_blockencoding/>`_, which you can check out for more details.
```

2024-08-19 18:55 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +:math:`Q` is a block encoding operator with a key property: its eigenvalues encode the Hamiltonian eigenvalues.
```suggestion
The operator :math:`Q` is a block encoding operator with a key property: its eigenvalues encode the eigenvalues of the Hamiltonian.
```

2024-08-19 18:55 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +
```suggestion
```
No need for new paragraph here

2024-08-19 18:55 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +of Quantum Phase Estimation to approximate the eigenvalues of a given Hamiltonian.
```suggestion
As we will soon explain in detail, if :math:`E` is an eigenvalue of :math:`\mathcal{H}`, then :math:`e^{i\arccos(E/\lambda)}` is an
eigenvalue of :math:`Q`, where :math:`\lambda` is a known normalization factor. This property is very useful because it means that we can use the Quantum Phase Estimation  algorithm to estimate the eigenvalues of  :math:`Q`, and then use them to retrieve the eigenvalues of the encoded Hamiltonian.
```

2024-08-19 18:55 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +of Quantum Phase Estimation to approximate the eigenvalues of a given Hamiltonian.
And please add link to QPE demo

2024-08-19 18:55 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +Below, we will show you how to reach these conclusions in a simple way!
```suggestion
This is the essence of why qubitization is attractive for applications: it provides a method to exactly encode eigenvalues of a Hamiltonian into a unitary operator that can be used inside the quantum phase estimation algorithm to sample Hamiltonian eigenvalues. But where this decomposition come from? Why are the eigenvalues are encoded in this way? 🤔 We explain these concepts below.
```

2024-08-19 18:55 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +inside the matrix associated to the circuit:
```suggestion
First, we introduce some useful concepts about block encodings.
Given a Hamiltonian :math:`\mathcal{H}`, we define as a block encoding any operator that embeds :math:`\mathcal{H}`
inside the matrix associated to the circuit (up to a normalization factor):
```

2024-08-19 18:55 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +generates a state:
```suggestion
Given an eigenvector of :math:`\mathcal{H}` such that :math:`\mathcal{H}| \phi \rangle = E | \phi \rangle`, we deduce that any :math:`\text{Block Encoding}_\mathcal{H}`
generates a state:
```

2024-08-19 18:55 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +in a two-dimensional space  — idea that we have exploited in our `Amplitude Amplification <https://pennylane.ai/qml/demos/tutorial_intro_amplitude_amplification/>`_ demo.
```suggestion
in a two-dimensional space  — an idea that we have explored in our `Amplitude Amplification <https://pennylane.ai/qml/demos/tutorial_intro_amplitude_amplification/>`_ demo. The state :math:`|\Psi\rangle` forms an angle :math:`\theta =\arccos {\frac{E}{\lambda}}` with respect to the axis defined by the initial state :math:`|0\rangle |\phi\rangle`, as shown in the image below.
```

2024-08-19 18:55 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +and we can use algorithms such as QPE to obtain this information.
```suggestion
Any Block Encoding operator manages to transform the state :math:`|0\rangle |\phi\rangle` into the state :math:`|\Psi\rangle`.
The Qubitization operator does this by applying a rotation in that two-dimensional subspace by an angle of :math:`\theta=\arccos {\frac{E}{\lambda}}`.
The advantage of a rotation operator is that the angle :math:`\theta` appears directly in its eigenvalues as the phases  :math:`e^{\pm i\theta}`. Therefore, if the rotation angle encodes useful information, it can be retrieved by estimating the phase of the rotation operator, for example using QPE.
```

2024-08-19 18:55 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +of :math:`Q` as :math:`e^{\pm i\arccos {\frac{E}{\lambda}}}`.
```suggestion
```
Can remove since now we explain this before

2024-08-19 18:55 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +In order to build this rotation we will follow the same idea of Amplitude Amplification:
```suggestion
We now show that the qubitization operator is a rotation by using the same idea of Amplitude Amplification:
```

2024-08-19 22:01 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +#    Qubitization rotation in pennylane is clockwise defined as the adjunct of the operator described above.
Why? I find this confusing :dizzy_face:

2024-08-19 22:01 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +    qml.QuantumPhaseEstimation(qml.Qubitization(H, control_wires), estimation_wires = estimation_wires)
We should mention in the text that we can also easily apply QPE using a built-in operation

2024-08-19 22:01 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +# techniques and apply them in your research.
Good to add links again to all these algorithms

2024-08-19 22:47 UTC, KetpuntoG commented on demonstrations/tutorial_qubitization.py
> +As we can see, this reflection achieves a rotation of :math:`\theta` degrees with respect to the initial state.
Yes, that's the idea! 🙌 I'll clarify it

2024-08-19 22:51 UTC, KetpuntoG commented on demonstrations/tutorial_qubitization.py
> +#    Qubitization rotation in pennylane is clockwise defined as the adjunct of the operator described above.
I know... What happened is that I came up with this intuition after creating the operator. The actual construction is based on the [Xanadu paper](https://arxiv.org/abs/2204.11890).  People do not give it much importance because within QPE it does not matter to put one or the other (since the algorithm returns $\theta$ and $-\theta$ indistinctly). However, in other contexts, it is important to know in which direction we are rotating.

2024-08-20 20:06 UTC, KetpuntoG commented
I have already worked on it @ixfoduap. I hope everything is much clearer now 💪

2024-08-21 15:23 UTC, ixfoduap reviewed
Looks great! :star_struck:  Just please address my final comments

2024-08-21 15:23 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +Encoding a Hamiltonian into a quantum computer is a fundamental task for many applications, but the way to do it is not unique. One method that has gained special status is known as **Qubitization**.
```suggestion
Encoding a Hamiltonian into a quantum computer is a fundamental task for many applications, but the way to do it is not unique. One method that has gained special status is known as **qubitization**. In this demo, we will introduce the qubitization operator and explain how to view it as a rotation operator. This perspective is useful when combining qubitization with quantum phase estimation (QPE). We will demonstrate this by implementing qubitization-based quantum phase estimation, with code provided using the :class:`~.pennylane.Qubitization` template in PennyLane.
```

2024-08-21 15:23 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +Encoding a Hamiltonian into a quantum computer is a fundamental task for many applications, but the way to do it is not unique. One method that has gained special status is known as **Qubitization**.
Please also add a link to the QPE demo here (just add link first time we write quantum phase estimation).

I'm also suggesting to drop the capitalization of qubitization and quantum phase estimation. In my opinion text reads more fluently this way. If you agree, please make this change consistently throughout the demo

2024-08-21 15:23 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +For a Hamiltonian :math:`\mathcal{H}` given in its `LCU representation <https://pennylane.ai/qml/demos/tutorial_lcu_blockencoding/>`_, the Qubitization operator is defined as:
```suggestion
For a Hamiltonian :math:`\mathcal{H}`, given in its `LCU representation <https://pennylane.ai/qml/demos/tutorial_lcu_blockencoding/>`_, the Qubitization operator is defined as:
```

2024-08-21 15:23 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +eigenvalue of :math:`Q`, where :math:`\lambda` is a known normalization factor. This property is very useful because it means that we can use the `Quantum Phase Estimation algorithm <https://pennylan
```suggestion
where :math:`\text{PSP}_{\mathcal{H}}` refers to the block encoding :math:`\text{Prep}_{\mathcal{H}}^{\dagger} \text{Sel}_{\mathcal{H}} \text{Prep}_{\mathcal{H}}`, as explained in `this demo <https://pennylane.ai/qml/demos/tutorial_lcu_blockencoding/>`_.

The operator :math:`Q` is also a block encoding operator with a key property: its eigenvalues encode the eigenvalues of the Hamiltonian.
As we will soon explain in detail, if :math:`E` is an eigenvalue of :math:`\mathcal{H}`, then :math:`e^{i\arccos(E/\lambda)}` is an
eigenvalue of :math:`Q`, where :math:`\lambda` is a known normalization factor. This property is very useful because it means that we can use the `Quantum Phase Estimation algorithm <https://pennylane.ai/qml/demos/tutorial_qpe/>`_  to estimate the eigenvalues of  :math:`Q`, and then use them to retrieve the eigenvalues of the encoded Hamiltonian.
```

2024-08-21 15:23 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +eigenvalue of :math:`Q`, where :math:`\lambda` is a known normalization factor. This property is very useful because it means that we can use the `Quantum Phase Estimation algorithm <https://pennylan
Start new paragraph

2024-08-21 15:23 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +For a Hamiltonian :math:`\mathcal{H}` given in its `LCU representation <https://pennylane.ai/qml/demos/tutorial_lcu_blockencoding/>`_, the Qubitization operator is defined as:
It's a stylistic choice, but I recommend using :math:`H` instead of :math:`\mathcal{H}`

2024-08-21 15:23 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +----------------
```suggestion
Block Encodings
----------------
```

2024-08-21 15:23 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +generates a state:
```suggestion
Given an eigenvector of :math:`\mathcal{H}` such that :math:`\mathcal{H}| \phi \rangle = E | \phi \rangle`, any :math:`\text{Block Encoding}_\mathcal{H}`
generates a state:
```

2024-08-21 15:23 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +The advantage of a rotation operator is that the angle :math:`\theta` appears directly in its eigenvalues as the phases  :math:`e^{\pm i\theta}`. Therefore, if the rotation angle encodes useful infor
```suggestion
Any block encoding operator manages to transform the state :math:`|0\rangle |\phi\rangle` into the state :math:`|\Psi\rangle`.
The Qubitization operator does this by applying a rotation in that two-dimensional subspace by an angle of :math:`\theta=\arccos {\frac{E}{\lambda}}`.
The advantage of a rotation operator is that the angle :math:`\theta` appears directly in the eigenvalues, which are simply :math:`e^{\pm i\theta}`. Therefore, if the rotation angle encodes useful information, it can be retrieved by estimating the phase of the rotation operator, for example using QPE.
```

2024-08-21 15:23 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +    To verify that an operator is indeed a reflection, one must square the operator and check if the result is the identity operator.
```suggestion
    An operator :math:`U` is a reflection if :math:`U^2=I`.
```
I'm not a fan of thes enotes; they break the flow of reading the demo. I suggest just adding this as a sentence, e.g., recall that an operator is a reflection if...

2024-08-21 15:23 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +As an example, let’s take :math:`|\Psi\rangle` as the initial state to visualize the rotation. The first reflection, given by :math:`(2|0\rangle\langle 0| - I)`, mirrors the state around the axis def
```suggestion
As an example, let’s take :math:`|\Psi\rangle` as the initial state to visualize the rotation. The first reflection, given by :math:`(2|0\rangle\langle 0| - I)`, mirrors the state around the axis defined by :math:`|0\rangle |\phi\rangle`. This occurs because the operator flips the sign of any component not aligned with :math:`|0\rangle` in the first register. The result is to prepare state :math:`|\Psi_1\rangle`, as illustrated below:
```

2024-08-21 15:23 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +Given the effect that :math:`\text{PSP}_{\mathcal{H}}` has on the state :math:`|0\rangle|\phi\rangle`, it can be verified that the second reflection occurs along the line that bisects the angle betwe
```suggestion
The block encoding operator :math:`\text{PSP}_{\mathcal{H}}` performs a second reflection along the line that bisects the angle between :math:`|\Psi\rangle` and :math:`|0\rangle |\phi\rangle`. Let's now examine the effect this reflection has on the previous state :math:`|\Psi_1\rangle`:
```

2024-08-21 15:23 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +After applying the reflection, the new state is rotated by :math:`\theta` degrees relative to the initial state :math:`|\Psi\rangle`. This shows that the Qubitization operator successfully creates a
```suggestion
After applying the reflection, the new state :math:`|\Psi_2\rangle` is rotated by :math:`\theta` degrees relative to the initial state :math:`|\Psi\rangle`. This shows that the Qubitization operator successfully creates a rotation of :math:`\theta` degrees within the subspace.
```

2024-08-21 15:23 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +First, let's define a Hamiltonian to use as an example:
```suggestion
First, let's define a simple Hamiltonian to use as an example:
```

2024-08-21 15:23 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +# eigenvalues and eigenvectors, but this would work with any Hamiltonian. We are going to take
```suggestion
# eigenvalues and eigenvectors, but the algorithm works with any Hamiltonian. We are going to take
```

2024-08-21 15:23 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +print(qml.matrix(H))
Let's please print only the real values for clarity

2024-08-21 15:23 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +# In PennyLane, the Qubitization operator can be easily constructed using the built-in :class:`~.pennylane.Qubitization` operation. You simply need to provide the Hamiltonian and the control qubits t
```suggestion
# In PennyLane, the Qubitization operator can be easily constructed using the built-in class:class:`~.pennylane.Qubitization`. You simply need to provide the Hamiltonian and the control qubits that define the block encoding. The number of control wires is :math:`⌈\log_2 k⌉`, where :math:`k` is the number of terms in the `LCU representation <https://pennylane.ai/qml/demos/tutorial_lcu_blockencoding/>`_ of the Hamiltonian.
```

2024-08-21 15:23 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +#    The Qubitization rotation in PennyLane is defined clockwise as the adjoint of the operator described above.
What do you mean "clockwise" here? Isn't just the adjoint?

2024-08-21 15:23 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +#    The Qubitization rotation in PennyLane is defined clockwise as the adjoint of the operator described above.
Also, for curiosity, why is this the case? Seems weird to talk about an operator, then say we implement the adjoint

2024-08-21 15:23 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +# Great! We successfully approximated the real value of :math:`E = 0.5`. 🚀
```suggestion
# Great! We successfully approximated the correct eigenvalue of :math:`E = 0.5`. 🚀
```

2024-08-23 15:02 UTC, KetpuntoG commented on demonstrations/tutorial_qubitization.py
> +#    The Qubitization rotation in PennyLane is defined clockwise as the adjoint of the operator described above.
Removed 👍 We'll update the template

2024-08-23 15:02 UTC, KetpuntoG commented on demonstrations/tutorial_qubitization.py
> +For a Hamiltonian :math:`\mathcal{H}` given in its `LCU representation <https://pennylane.ai/qml/demos/tutorial_lcu_blockencoding/>`_, the Qubitization operator is defined as:
I'll keep mathcal for this one

2024-09-03 10:00 UTC, ikurecic reviewed
Hi @KetpuntoG and @soranjh , thanks for sharing!
I have a few minor suggestions (for Guillermo?), and I can also make an update to the image paths, if you'd be happy with me adding a small commit here.

Please let me know what you think.

2024-09-03 10:00 UTC, ikurecic commented on demonstrations/tutorial_qubitization.metadata.json
> +    "dateOfLastModification": "2024-05-07T00:00:00+00:00",
tk

2024-09-03 10:00 UTC, ikurecic commented on demonstrations/tutorial_qubitization.metadata.json
> +    "title": "Qubitization",
tk — maybe something with a bit more descriptive quality, can be decided as a last step.

2024-09-03 10:00 UTC, ikurecic commented on demonstrations/tutorial_qubitization.metadata.json
> +        }
```suggestion
        {
            "username": "KetPuntoG"
        },
        {
            "username": "ixfoduap"
        }
```

2024-09-03 10:00 UTC, ikurecic commented on demonstrations/tutorial_qubitization.metadata.json
> +    ],
tk

2024-09-03 10:00 UTC, ikurecic commented on demonstrations/tutorial_qubitization.metadata.json
> +    "seoDescription": "Learn qubitization, how to visualize it, and its applications",
tk

2024-09-03 10:00 UTC, ikurecic commented on demonstrations/tutorial_qubitization.py
> +r"""Intro to Qubitization
tk

2024-09-03 10:00 UTC, ikurecic commented on demonstrations/tutorial_qubitization.py
> +Encoding a Hamiltonian into a quantum computer is a fundamental task for many applications, but the way to do it is not unique. One method that has gained special status is known as **qubitization**.
> "[…] it is not unique."

Do you want to list some links/examples here?

> One method that has gained special status is known as **qubitization**.

Could you add a short explanation of the 'special status'?

Also, it would be great if you could add an inline link to the QPE Demo, and maybe even Josh's old qubit rotation Demo.

2024-09-03 10:00 UTC, ikurecic commented on demonstrations/tutorial_qubitization.py
> +    :width: 50%
```suggestion
    :width: 70%
```
For consistency.

2024-09-03 10:00 UTC, ikurecic commented on demonstrations/tutorial_qubitization.py
> +.. figure:: ../_static/demonstration_assets/qubitization/OGthumbnail_large_Qubitization.png
tk

2024-09-03 10:00 UTC, ikurecic commented on demonstrations/tutorial_qubitization.py
> +
I think you should open this section with a sentence explaining what qubitization is. Or you could even add it to the introduction above.

2024-09-03 10:00 UTC, ikurecic commented on demonstrations/tutorial_qubitization.py
> +where :math:`\text{PSP}_{\mathcal{H}}` refers to the block encoding :math:`\text{Prep}_{\mathcal{H}}^{\dagger} \text{Sel}_{\mathcal{H}} \text{Prep}_{\mathcal{H}}`, as explained in `this demo <https:/
```suggestion
where :math:`\text{PSP}_{\mathcal{H}}` refers to the block encoding :math:`\text{Prep}_{\mathcal{H}}^{\dagger} \text{Sel}_{\mathcal{H}} \text{Prep}_{\mathcal{H}}`, as explained in the `LCU PennyLane Demo <https://pennylane.ai/qml/demos/tutorial_lcu_blockencoding/>`_.
```

2024-09-03 10:00 UTC, ikurecic commented on demonstrations/tutorial_qubitization.py
> +For a Hamiltonian :math:`\mathcal{H}`, given in its `LCU representation <https://pennylane.ai/qml/demos/tutorial_lcu_blockencoding/>`_, the qubitization operator is defined as:
```suggestion
For a Hamiltonian :math:`\mathcal{H}`, given in its `representation via a linear combination of unitaries (LCU) <https://pennylane.ai/qml/demos/tutorial_lcu_blockencoding/>`_, the qubitization operator is defined as:
```
Or something similar, so the acronym isn't a surprise.

2024-09-03 10:00 UTC, ikurecic commented on demonstrations/tutorial_qubitization.py
> +The operator :math:`Q` is also a block encoding operator with a key property: its eigenvalues encode the eigenvalues of the Hamiltonian.
```suggestion
The operator :math:`Q` is also a block-encoding operator with a key property: its eigenvalues encode the eigenvalues of the Hamiltonian.
```

2024-09-03 10:00 UTC, ikurecic commented on demonstrations/tutorial_qubitization.py
> +----------------
```suggestion
Block encodings
---------------
```

2024-09-03 10:00 UTC, ikurecic commented on demonstrations/tutorial_qubitization.py
> +in a two-dimensional space  — an idea that we have explored in our `Amplitude Amplification <https://pennylane.ai/qml/demos/tutorial_intro_amplitude_amplification/>`_ demo. The state :math:`|\Psi\ran
```suggestion
in a two-dimensional space  — an idea that we have explored in our `amplitude amplification <https://pennylane.ai/qml/demos/tutorial_intro_amplitude_amplification/>`_ demo. The state :math:`|\Psi\rangle` forms an angle :math:`\theta =\arccos {\frac{E}{\lambda}}` with respect to the axis defined by the initial state :math:`|0\rangle |\phi\rangle`, as shown in the image below.
```

2024-09-03 10:00 UTC, ikurecic commented on demonstrations/tutorial_qubitization.py
> +Any block encoding operator manages to transform the state :math:`|0\rangle |\phi\rangle` into the state :math:`|\Psi\rangle`.
```suggestion
Any block-encoding operator manages to transform the state :math:`|0\rangle |\phi\rangle` into the state :math:`|\Psi\rangle`.
```

2024-09-03 10:00 UTC, ikurecic commented on demonstrations/tutorial_qubitization.py
> +We now show that the qubitization operator is a rotation by using the same idea of Amplitude Amplification:
```suggestion
We now show that the qubitization operator is a rotation by using the same idea of amplitude amplification:
```

2024-09-03 10:00 UTC, ikurecic commented on demonstrations/tutorial_qubitization.py
> +The term "qubitization" comes from the fact that this process occurs within a two-dimensional subspace, which can be viewed as a qubit. For each eigenstate of the Hamiltonian, the qubitization operat
```suggestion
The term "qubitization" comes from the fact that this process occurs within a two-dimensional subspace, which can be viewed as a qubit. For each eigenstate of the Hamiltonian, the qubitization operator acts within this two-dimensional space, effectively treating it as a qubit. This is why we say the system has been *qubitized*.
```
Either this, or the period should be inside the quotation.

2024-09-03 10:00 UTC, ikurecic commented on demonstrations/tutorial_qubitization.metadata.json
> +    ]
Maybe the LCU Demo should also be listed as related here?

2024-09-03 13:59 UTC, KetpuntoG commented on demonstrations/tutorial_qubitization.py
> +
Added here: "Qubitization is a block encoding technique that, as we will see, is particularly useful for tasks such as estimating eigenvalues, among other applications.
"

2024-09-03 13:59 UTC, KetpuntoG commented on demonstrations/tutorial_qubitization.py
> +Encoding a Hamiltonian into a quantum computer is a fundamental task for many applications, but the way to do it is not unique. One method that has gained special status is known as **qubitization**.
added link to QPE 👍

and for the “special status”, I just want to say that it is becoming more and more important

2024-09-03 15:22 UTC, KetpuntoG commented on demonstrations/tutorial_qubitization.py
> +For a Hamiltonian :math:`\mathcal{H}`, given in its `representation via a linear combination of unitaries (LCU) <https://pennylane.ai/qml/demos/tutorial_lcu_blockencoding/>`_, the qubitization operat
I'm going to delete it as it was too repetitive with the link after it

```suggestion
For a Hamiltonian :math:`\mathcal{H}`, given in its representation via a linear combination of unitaries (LCU), the qubitization operator is defined as:
```

2024-09-04 18:27 UTC, ixfoduap approved these changes
Looks great! Just a few suggestions more

2024-09-04 18:27 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +This is the essence of why qubitization is attractive for applications: it provides a method to exactly encode eigenvalues of a Hamiltonian into a unitary operator that can be used inside the quantum
```suggestion
This is the essence of why qubitization is attractive for applications: it provides a method to exactly encode eigenvalues of a Hamiltonian into a unitary operator. It can then be used inside quantum phase estimation to sample Hamiltonian eigenvalues. 

But where does this decomposition come from? Why are the eigenvalues encoded in this way? 🤔 We explain these concepts below.
```

2024-09-04 18:27 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +eigenvalue of :math:`Q`, where :math:`\lambda` is a known normalization factor. This property is very useful because it means that we can use the `quantum phase estimation algorithm <https://pennylan
```suggestion
eigenvalue of :math:`Q`, where :math:`\lambda` is a known normalization factor. This property is very useful because it means that we can use the `QPE algorithm <https://pennylane.ai/qml/demos/tutorial_qpe/>`_  to estimate the eigenvalues of  :math:`Q`, and then use them to retrieve the eigenvalues of the encoded Hamiltonian.
```

2024-09-04 18:27 UTC, ixfoduap commented on demonstrations/tutorial_qubitization.py
> +eigenvalue of :math:`Q`, where :math:`\lambda` is a known normalization factor. This property is very useful because it means that we can use the `quantum phase estimation algorithm <https://pennylan
Generally, we are using both QPE and quantum phase estimation in the demo. I guess this may be for SEO purposes, but then maybe still good to add a few more QPEs

2024-09-05 10:28 UTC, ikurecic commented on demonstrations/tutorial_qubitization.py
> +Encoding a Hamiltonian into a quantum computer is a fundamental task for many applications, but the way to do it is not unique. One method that has gained special status is known as **qubitization**.
That might actually be a better way of saying that, then. When I read "special status," I wonder if something specific happened that I'm not aware of.

2024-09-05 13:49 UTC, ikurecic reviewed
Hi @KetpuntoG , with these few minor comments, this looks done to me. Could you please get explicit approval of the pull request from the technical reviewer? I can take care of the further steps after that. Thanks!

2024-09-05 13:49 UTC, ikurecic commented on demonstrations/tutorial_qubitization.metadata.json
> +    "title": "Intro to Qubitization",
```suggestion
    "title": "Intro to qubitization",
```

2024-09-05 13:49 UTC, ikurecic commented on demonstrations/tutorial_qubitization.metadata.json
> +    "seoDescription": "Learn qubitization, how to visualize it, and its applications",
```suggestion
    "seoDescription": "Learn how to use, visualize and apply qubitization, a block-encoding technique in quantum computing.",
```
How's this?

2024-09-05 13:49 UTC, ikurecic commented on demonstrations/tutorial_qubitization.py
> +r"""Intro to Qubitization
```suggestion
r"""Intro to qubitization
```

2024-09-05 13:49 UTC, ikurecic commented on demonstrations/tutorial_qubitization.py
> +Encoding a Hamiltonian into a quantum computer is a fundamental task for many applications, but the way to do it is not unique. One method that has gained special status is known as **qubitization**.
```suggestion
Encoding a Hamiltonian into a quantum computer is a fundamental task for many applications, but the way to do it is not unique. One method that has gained special status is known as **qubitization** — a block-encoding technique that can be used to estimate eigenvalues and for many other applications.

In this demo, we will introduce the qubitization operator and explain how to view it as a rotation operator. This perspective is useful when combining qubitization with `quantum phase estimation <https://pennylane.ai/qml/demos/tutorial_qpe/>`_ (QPE). We will demonstrate this by implementing qubitization-based quantum phase estimation, with code provided using the :class:`~.pennylane.Qubitization` template in PennyLane.
```

What do you think about this?

2024-09-09 08:38 UTC, ikurecic commented on demonstrations/tutorial_qubitization.metadata.json
> +    "dateOfLastModification": "2024-05-07T00:00:00+00:00",
```suggestion
    "dateOfPublication": "2024-09-09T00:00:00+00:00",
    "dateOfLastModification": "2024-09-09T00:00:00+00:00",
```

2024-09-09 09:14 UTC, ikurecic approved these changes

2024-09-09 09:47 UTC, merged