Ultimate guide to PennyLane knowing Qiskit
PennyLaneAI/qml pull request #1117
Opened 2024-05-24 16:23 UTC by isaacdevlugt

**Title:** Your Ultimate Guide to PennyLane if You Know Qiskit

https://app.shortcut.com/xanaduai/objective/59641/convert-qiskit-users-to-pennylane

* Which of the following types of documentation is most similar to your file? 
(more details [here](https://www.notion.so/xanaduai/Different-kinds-of-documentation-69200645fe59442991c71f9e7d8a77f8))
    
- [ x ] Tutorial
- [ ] Demo
- [ ] How-to

2024-05-28 18:34 UTC, isaacdevlugt commented on demonstrations/ultimate_guide_to_pennylane_knowing_qiskit.py
> +######################################################################
huh? 

![Screenshot 2024-05-28 at 2 33 46 PM](https://github.com/PennyLaneAI/qml/assets/34751083/8d8586d2-40ee-4cab-91ef-8021a020d1c1)

2024-05-28 20:05 UTC, isaacdevlugt commented on demonstrations/ultimate_guide_to_pennylane_knowing_qiskit.py
> +# Now that you know how to make quantum circuits in PennyLane, let’s apply it 👇.
```suggestion
# A minor point, but both approaches work. Now that you know how to make quantum circuits in PennyLane, let’s apply it 👇.
```

2024-05-28 20:06 UTC, isaacdevlugt commented on demonstrations/ultimate_guide_to_pennylane_knowing_qiskit.py
> +
```suggestion
```

2024-05-28 20:06 UTC, isaacdevlugt commented on demonstrations/ultimate_guide_to_pennylane_knowing_qiskit.py
> +# ====================
```suggestion
# -------------------
```

2024-06-07 20:58 UTC, co9olguy commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +# breaking changes were to be expected. Although learning a new language can be hard, PennyLane has very
well done :ok_hand:

2024-06-12 16:20 UTC, isaacdevlugt commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +#
@austingmhuang does your work that you've been doing with the qiskit plugin allow for importing `Estimator` primitives 🤔 ? If so, this might be nice to include here

2024-06-14 13:29 UTC, austingmhuang commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +print(counts)
This would also be changed if you switched to [SamplerV2](https://docs.quantum.ibm.com/api/qiskit/qiskit.primitives.StatevectorSampler). See link for more info on the syntax.

2024-06-14 13:29 UTC, austingmhuang commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +    return qml.counts(wires=1)
Should we print this out as well in the demo?

2024-06-14 13:30 UTC, austingmhuang commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +#    framwork, and “wires” is a hardware agnostic term for quantum degrees of freedom that
```suggestion
#    framework, and “wires” is a hardware agnostic term for quantum degrees of freedom that
```

2024-06-14 13:31 UTC, austingmhuang commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +    return qml.counts(wires=1)
Ah I see it's a bit further down.

2024-06-14 16:57 UTC, soranjh requested changes
Thanks @isaacdevlugt, looks good overall. Left some comments. I think the second part of the section "Get to Know PennyLane" where you talk about qnode, device, function etc can become a bit more smooth and well-explained.

2024-06-14 20:10 UTC, austingmhuang commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +pl_func = qml.from_qiskit(qc, measurements=[qml.expval(pl_pauli_op)])
No I don't think `pl_circuit` is mutable. I think you would have to redefine it as @isaacdevlugt has done here.

2024-06-14 20:18 UTC, josh146 commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
@isaacdevlugt curious why this demo is non-executable? Isn't qiskit installed in the QML repo?

2024-06-14 20:49 UTC, austingmhuang commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +When it comes to quantum programming SDKs, PennyLane and Qiskit (``v1.0`` and ``<=v0.46``) are two
Another two things:
1. To be precise, Version 0.46 is not supported by Pennylane right now. Version <=0.45 is though.
2. After the feature_branch is merged, Version <=0.45 will not be supported either. If a User wants to use Qiskit <=0.45 they will have to keep PL and the plugin at v0.36 (or 0.37 if we can't make the 0.37 release).

2024-06-14 21:18 UTC, austingmhuang commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +pl_circuit = qml.from_qiskit(qc)
Think `pl_circuit` should be changed to `pl_func` maybe. `pl_circuit` is a more appropriate name for something like this: `QNode(pl_func())`

2024-06-14 21:26 UTC, austingmhuang commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +    """Equivalent to doing pl_circuit = qml.from_qiskit(qc)"""
```suggestion
    """Equivalent to doing pl_circuit = qml.from_qiskit(qc, measurements=qml.counts(wires=1))"""
```

2024-06-14 21:38 UTC, austingmhuang commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +pl_func = qml.from_qiskit(qc, measurements=[qml.expval(pl_pauli_op)])
Could also do 
```
def pl_circuit():
   pl_func()
   return qml.expval(pl_pauli_op)
```

instead, but it seems a bit confusing.

2024-06-15 21:48 UTC, josh146 approved these changes
Thanks Isaac 🙁 Conditionally approving based on mine, @soranjh, and @austingmhuang's comments!

2024-06-15 21:48 UTC, josh146 commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +   plugin <https://docs.pennylane.ai/projects/qiskit/en/stable/>`__.
Minor comment @isaacdevlugt, but adding a blank line inbetween each item in the list will make it spaced a bit more nicely when rendered :)

2024-06-15 21:48 UTC, josh146 commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +# ``pip install pennylane pennylane-qiskit torch tensorflow`` (the plugin will install Qiskit-1.0). Now,
```suggestion
# .. code-block:: console
#
#     pip install pennylane pennylane-qiskit torch tensorflow
#
# (the plugin will install Qiskit-1.0). Now,
```

2024-06-15 21:48 UTC, josh146 commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +#    PennyLane.
```suggestion
# 2. :func:`~pennylane.from_qiskit_op`: converts a ``SparsePauliOp`` in Qiskit 1.0 to the equivalent operator in
#    PennyLane.
```

2024-06-15 21:48 UTC, josh146 commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +#
@isaacdevlugt you need to include blank lines inbetween all items of lists.

2024-06-15 21:48 UTC, josh146 commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +#     :width: 10%
Yep, @isaacdevlugt I recommend checking the rendered version and adjusting sizes throughout.

Also recommend using `:align: left` to match other demos :)

2024-06-15 21:48 UTC, josh146 commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +# case, ``qml.counts(wires=1)`` is the measurement, which counts the number of times a ``0`` or
```suggestion
# case, :func:`qml.counts(wires=1) <pennylane.counts>` is the measurement, which counts the number of times a ``0`` or
```

2024-06-15 21:48 UTC, josh146 commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +# the quantum function with ``qml.QNode``.
```suggestion
# the quantum function with :func:`~pennylane.QNode`.
```

2024-06-15 21:48 UTC, josh146 commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +# way of doing this is simple: (1) define a device with ``qml.device`` and (2) pair the device with
```suggestion
# way of doing this is simple: (1) define a device with :func:`qml.device <pennylane.device>` and (2) pair the device with
```

2024-06-15 21:48 UTC, josh146 commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +#    ``"default.qubit"`` is our battle-tested Python statevector simulator.
```suggestion
# 1. **A quantum function that contains quantum instructions**. This is ``pl_func``, which just contains
#    quantum operations (gates) and returns a measurement. In this case, ``qml.counts(wires=1)`` is
#    the measurement, which counts the number of times a ``0`` or a ``1`` occurs on wire ``1`` and
#    returns a dictionary whose values are NumPy arrays.
#
# 2. **A device** (e.g., ``qml.device("default.qubit")``). PennyLane has many devices you can choose from, but
#    ``"default.qubit"`` is our battle-tested Python statevector simulator.
```

2024-06-15 21:48 UTC, josh146 commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +#    ``"default.qubit"`` is our battle-tested Python statevector simulator.
I recommend also linking to the plugins/devices page in the second bullet point :)

2024-06-15 21:48 UTC, josh146 commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +# the expectation value of a provided operator).
Please use `:func:` here :)

2024-06-15 21:48 UTC, josh146 commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +# primitives. `PennyLane's measurement API <https://docs.pennylane.ai/en/stable/introduction/measurements.html>`__
```suggestion
# primitives. :doc:`PennyLane's measurement API <introduction/measurements>`
```
(will need to double check this renders correctly!)

2024-06-15 21:48 UTC, josh146 commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +# function with ``qml.QNode`` is the same as *decorating* it with ``@qml.qnode(dev)``:
```suggestion
# function with :func:`qml.QNode <pennylane.QNode>` is the same as *decorating* it with :func:`@qml.qnode(dev) <pennylane.qnode>`:
```

2024-06-15 21:48 UTC, josh146 commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +# `primitives <https://docs.quantum.ibm.com/api/qiskit/primitives>`__. Stay tuned for that!
```suggestion
# `plugin homepage <https://docs.pennylane.ai/projects/qiskit/en/stable/>`__.
```

2024-06-15 21:48 UTC, josh146 commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +# rotation tutorial <https://pennylane.ai/qml/demos/tutorial_qubit_rotation/>`__.
```suggestion
# same people that develop PennyLane. If you’re just starting out, I recommend reading our :doc:`qubit
# rotation tutorial <tutorial_qubit_rotation>`.
```

2024-06-15 21:48 UTC, josh146 commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +# `pennylane.ai <https://pennylane.ai>`__, to see the latest and greatest PennyLane features, demos,
```suggestion
# Forum <https://discuss.pennylane.ai>`__ and we’ll promptly respond. You can also keep exploring our website,
# `pennylane.ai <https://pennylane.ai>`__, to see the latest and greatest PennyLane features, demos,
```

2024-06-17 15:38 UTC, isaacdevlugt commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +   researching or learning. That’s why we have a mandate to make our documentation easy to navigate,
Hey @soranjh! I'm reading this a little differently, but I see your confusion:

> "we have a mandate ..., dedicated ..., and an active ..." 

I'll reword!

2024-06-17 15:40 UTC, isaacdevlugt commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +3. **Community-focused**: Let’s face it, you’re going to get stuck at some point when you’re
```suggestion
1. **Hardware agnostic**: PennyLane has no opinions on what hardware or simulator backends you want
   to use for your research. You can program an emporium of real hardware and simulator backends all
   from the easy-to-use PennyLane API. This includes IBM’s hardware with the `PennyLane-Qiskit
   plugin <https://docs.pennylane.ai/projects/qiskit/en/stable/>`__.
   
2. **Everything is differentiable**: A quantum circuit in PennyLane is designed to behave like a
   differentiable function, unlocking quantum differentiable programming and allowing to integrate
   seamlessly with your favourite machine learning frameworks.
   
3. **Community-focused**: Let’s face it, you’re going to get stuck at some point when you’re
```

2024-06-17 15:44 UTC, isaacdevlugt commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +
```suggestion
3. **Community-focused**: Let’s face it, you’re going to get stuck at some point when you’re
   researching or learning. That’s why we have dedicated teams for creating new 
   demonstrations when we release new features, an `active discussion forum <https://discuss.pennylane.ai>`__ for answering 
   your questions, and a mandate to make our documentation easy to navigate.


```

2024-06-17 15:44 UTC, isaacdevlugt commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +
@soranjh how's this?

2024-06-17 15:51 UTC, isaacdevlugt commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +# 1. ``qml.from_qiskit``: converts an entire Qiskit ``QuantumCircuit`` — the whole thing — into
```suggestion
# 1. :func:`~.from_qiskit`: converts an entire Qiskit ``QuantumCircuit`` — the whole thing — into
```

2024-06-17 15:56 UTC, isaacdevlugt commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +# Both of these functions give you the functionality you need to access PennyLane’s features and user-interface
Good point!

2024-06-17 15:56 UTC, isaacdevlugt commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +#
```suggestion
# These two functions give you all that you need to access PennyLane’s features and user-interface
# starting from the Qiskit side. As an example, let’s say you have the following code in Qiskit that
# prepares a Bell state.
#
```

2024-06-18 19:05 UTC, isaacdevlugt commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +#
@josh146 I tagged you in my other demo for the same problem. Any ideas?

![Screenshot 2024-06-18 at 3 04 03 PM](https://github.com/PennyLaneAI/qml/assets/34751083/e80a4b40-d80c-4dec-b0d8-a6d4cdd4e378)

2024-06-18 19:05 UTC, isaacdevlugt commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +# do I use it further?” To answer those questions, we need to get to know PennyLane a little better.
pourquuuooooooi

![Screenshot 2024-06-18 at 3 05 36 PM](https://github.com/PennyLaneAI/qml/assets/34751083/72935838-7b6c-4d3a-a446-54531f9d4a4c)

2024-06-18 19:06 UTC, isaacdevlugt commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +#
Not spaced nicely 🤔 

![Screenshot 2024-06-18 at 3 06 17 PM](https://github.com/PennyLaneAI/qml/assets/34751083/c28154da-4741-488d-bbb3-55ef96ae6ff2)

2024-06-18 20:09 UTC, josh146 commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +# do I use it further?” To answer those questions, we need to get to know PennyLane a little better.
:ohno:

2024-06-18 20:09 UTC, josh146 commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +#
😱

2024-06-18 20:09 UTC, josh146 commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +#
No unfortunately :( Might need to go back to :align:center

2024-06-18 20:10 UTC, josh146 commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
It would be nice :) Means its automatically tested

2024-06-18 23:00 UTC, soranjh commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +
Probably need # here to fix the built.

2024-06-18 23:01 UTC, soranjh commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +#
You are probably missing # in a blank line after the image description.

2024-06-18 23:02 UTC, soranjh commented on demonstrations/guide_to_pennylane_knowing_qiskit.py
> +
Add #.

2024-06-19 15:35 UTC, soranjh approved these changes
Looks good @isaacdevlugt!

2024-06-26 13:52 UTC, isaacdevlugt commented
This demo requires v0.37 to be executable. Will have to hold off merging until then

2024-06-26 14:24 UTC, austingmhuang commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +result_sampler = job_sampler.result()[0].data.meas.get_counts() # or call get_counts()
```suggestion
result_sampler = job_sampler.result()[0].data.meas.get_counts()
```
Minor mistake I think

2024-07-10 23:42 UTC, josh146 commented
🤞

2024-07-11 12:32 UTC, trbromley commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +print(qml.draw_mpl(pl_func)())
```suggestion
print(qml.draw_mpl(pl_func, style="pennylane")())
```
Not major, but just to match styles.

2024-07-15 13:34 UTC, trbromley commented
@isaacdevlugt - are we blocked on merging this until August 6th?

Or could this be merged in sooner, even though the marketing happens later?

2024-07-15 14:22 UTC, isaacdevlugt commented
@trbromley this is @ikurecic's decision — let's see! It's been scheduled for August 6 for quite some time, so if it's baked into the content schedule then I think it's still okay to leave it until then.

2024-07-16 13:53 UTC, trbromley commented
> @trbromley this is @ikurecic's decision — let's see! It's been scheduled for August 6 for quite some time, so if it's baked into the content schedule then I think it's still okay to leave it until then.

Thanks @isaacdevlugt. Up to @ikurecic, and I don't have all the context, but we've generally tried to separate publishing a demo from marketing it.

E.g., if it can be published now and potentially help people out now, why wait?

2024-07-16 14:00 UTC, isaacdevlugt commented
> we've generally tried to separate publishing a demo from marketing it.
@trbromley Yep! For context, switching (or not switching) the date for this demo has nothing to do with the marketing schedule. We're just talking about when the content is published. As you said, marking can happen later 🙂 

We discussed in a meeting this morning and we can move this to next week. Worked out well, actually, since the other demos that were scheduled earlier could use a little more marinating 🥩. I'll give a last once-over myself this afternoon, @ikurecic will also review it this week, and then it's ready to merge 🎉

2024-07-17 13:28 UTC, ikurecic reviewed
Thanks a lot, @isaacdevlugt ! I love this, you did a really good job.

I've just gone through and left some suggestions and a couple of comments... I'm wondering if you'd want to call it (instead of "ultimate guide") something closer to "introduction" or "start" ... because these are the fundamentals/basics you're showing here, and it's nice and compact, fantastic for a beginner just looking for a quick start.

2024-07-17 13:28 UTC, ikurecic commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# And just like that, you’re in PennyLane land! Now you might be asking: “What is ``pl_func`` and how
I am shocked and offended you didn't try to stretch this into a pun. :) PennyLaneLand?

2024-07-17 13:28 UTC, ikurecic commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# do I use it further?” To answer those questions, we need to get to know PennyLane a little better.
```suggestion
# could I use it further?” To answer those questions, we need to get to know PennyLane a little better.
```

2024-07-17 13:28 UTC, ikurecic commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# Let’s go back to that Qiskit circuit (``qc``) that we created earlier. If we want to execute that
```suggestion
# Let’s go back to that Qiskit circuit (``qc``) that we created `earlier <#pennylane-qiskit>`_. If we want to execute that
```

2024-07-17 13:28 UTC, ikurecic commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +#    Qubits in PennyLane are called “wires”. Why? As was mentioned, PennyLane is a hardware agnostic
```suggestion
#    Qubits in PennyLane are called *wires*. Why? As was mentioned, PennyLane is a hardware-agnostic
```

2024-07-17 13:28 UTC, ikurecic commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +#    framework, and “wires” is a hardware agnostic term for quantum degrees of freedom that
```suggestion
#    framework, and “wires” is a hardware-agnostic term for quantum degrees of freedom that
```

2024-07-17 13:28 UTC, ikurecic commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +#    quantum computers can be based off of.
```suggestion
#    quantum computers can be based on.
```

2024-07-17 13:28 UTC, ikurecic commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# (a new `V2 primitive <https://pennylane.ai/qml/glossary/what-are-qiskit-primitives/>`__). PennyLane’s
```suggestion
# what the circuit runs on, just like how we defined a ``StatevectorSampler`` instance in Qiskit
# (a new `V2 primitive <https://pennylane.ai/qml/glossary/what-are-qiskit-primitives/>`__). PennyLane’s
```

2024-07-17 13:28 UTC, ikurecic commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# are *functions*, returning measurements that behave like NumPy arrays. The function ``pl_circuit`` is
```suggestion
# are *functions*, returning measurements that behave like `NumPy arrays <https://numpy.org/doc/stable/reference/generated/numpy.array.html>`__. The function ``pl_circuit`` is 
```
Links, links everywhere

2024-07-17 13:28 UTC, ikurecic commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# called a *quantum node* (QNode), which is the sum of two things:
A sum? I feel like we could find a better word... set doesn't sound perfect to me. Neither does combination. But both are better than sum. Any ideas?

2024-07-17 13:28 UTC, ikurecic commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +#   but ``"default.qubit"`` is our battle-tested Python statevector simulator.
```suggestion
#   but ``"default.qubit"`` is our battle-tested Python state vector simulator.
```
For consistency.

2024-07-17 13:28 UTC, ikurecic commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# you specified and returning the measurement you asked for — simple as that 🌈.
```suggestion
# you specified and returning the measurement you asked for — as simple as that 🌈.
```

2024-07-17 13:28 UTC, ikurecic commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# Alternatively, because PennyLane’s primitive is a glorified Python function, wrapping a quantum
You sure you wanna keep the word "glorified" here? It can have negative connotations in this case.

2024-07-17 13:28 UTC, ikurecic commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# A minor point, but both approaches work.
```suggestion
# This is a minor point, but both approaches work.
```
Or just "Both approaches work."

2024-07-17 13:28 UTC, ikurecic commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# of PennyLane's plugins, meaning you can run your Qiskit circuit on more than just IBM hardware! All
```suggestion
# of `PennyLane's plugins <https://pennylane.ai/plugins/>`__, meaning you can run your Qiskit circuit on more than just IBM hardware! All
```

2024-07-17 13:28 UTC, ikurecic commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# you need to do is install the plugin of interest, and change the name of the device in ``qml.device``.
```suggestion
# you need to do is install the plugin of interest and change the name of the device in ``qml.device``.
```

2024-07-17 13:28 UTC, ikurecic commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# There’s so much more to learn about what’s possible in PennyLane, and if you’re coming from Qiskit
```suggestion
# There’s so much more to learn about what’s possible in PennyLane, and if you’re coming from Qiskit,
```
Normally this comma would be optional, but not in this case.

2024-07-17 13:28 UTC, ikurecic commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# demos <https://pennylane.ai/search/?contentType=DEMO&sort=publication_date>`__ maintained by the
@Lorraine-at-Xanadu , would we prefer linking to this search view, or the raw PennyLane Demo homepage?

2024-07-17 13:28 UTC, ikurecic commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# PennyLane, or even Qiskit, drop a question on our `Discussion
```suggestion
# PennyLane, or even Qiskit, drop us a question on the `PennyLane Discussion
```
Either "us" or change "on" to "into."

2024-07-17 13:28 UTC, ikurecic commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# (formerly Twitter) <https://twitter.com/PennyLaneAI>`__ to stay updated!
```suggestion
# and blogs, receive the `monthly Xanadu newsletter <https://xanadu.us17.list-manage.com/subscribe?u=725f07a1d1a4337416c3129fd&id=294b062630>`__, or follow us on `LinkedIn <https://www.linkedin.com/company/pennylaneai/>`__ or `X
# (formerly Twitter) <https://twitter.com/PennyLaneAI>`__ to stay updated!
```

2024-07-17 13:28 UTC, ikurecic commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# .. include:: ../_static/authors/isaac_de_vlugt.txt
You can remove this part, it gets pulled straight from the metadata nowadays.

2024-07-17 13:29 UTC, ikurecic commented
Also, @isaacdevlugt and @trbromley , I think this is good to go to merge as soon as we get a couple more glances at it, so I'll schedule the promotion for next week, as well. Thank you.

2024-07-17 18:22 UTC, isaacdevlugt commented on _static/demonstration_assets/regular_demo_thumbnails/placeholder_demo_thumbnail.png
Ah yes! Forgot to delete. I was using this as a placeholder thumbnail while Tarik was working on one for this demo. I'll delete :)

2024-07-17 18:23 UTC, isaacdevlugt commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.metadata.json
> +    "canonicalURL": "/qml/demos/tutorial_ultimate_guide_to_pennylane_knowing_qiskit",
I originally called it "ultimate ..." but decided to get rid of that 😅. Should I rename the file(s) to `tutorial_your_guide_to_pennylane_knowing_qiskit`, for example?

2024-07-17 18:26 UTC, isaacdevlugt commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +When it comes to quantum programming SDKs, PennyLane and Qiskit (``v1.0`` and ``<=v0.46``) are two
```suggestion
When it comes to quantum programming SDKs, `PennyLane <https://pennylane.ai/install/>`__ and `Qiskit <https://github.com/Qiskit/qiskit>`__ (``v1.0`` and ``<=v0.46``) are two
```

2024-07-17 18:26 UTC, isaacdevlugt commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# These two functions give you all that you need to access PennyLane’s features and user-interface
```suggestion
# These two functions give you all that you need to access PennyLane’s features and user interface
```

2024-07-17 18:35 UTC, isaacdevlugt commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# And just like that, you’re in PennyLane land! Now you might be asking: “What is ``pl_func`` and how
How's this? 🤠 

```suggestion
# And just like that, you’re in PennyLaneLand! ... _It's in your ears and in your eyes!_ 🎶 . Now you might be asking: “What is ``pl_func`` and how
```

2024-07-17 18:36 UTC, isaacdevlugt commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# called a *quantum node* (QNode), which is the sum of two things:
Union? ... Marriage? lol

2024-07-17 18:37 UTC, isaacdevlugt commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# Alternatively, because PennyLane’s primitive is a glorified Python function, wrapping a quantum
```suggestion
# Alternatively, wrapping a quantum
```

2024-07-17 18:38 UTC, isaacdevlugt commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# .. include:: ../_static/authors/isaac_de_vlugt.txt
```suggestion
```

That's it?

2024-07-17 18:42 UTC, isaacdevlugt commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +
```suggestion
# .. figure:: ../_static/demonstration_assets/guide_to_pennylane_knowing_qiskit/guide_to_pennylane_knowing_qiskit_thumbnail.png
#     :align: center
#     :width: 70%
```

2024-07-17 19:05 UTC, isaacdevlugt commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +
```suggestion
.. figure:: ../_static/demonstration_assets/guide_to_pennylane_knowing_qiskit/guide_to_pennylane_knowing_qiskit_thumbnail.png
    :align: center
    :width: 70%
```

2024-07-18 08:57 UTC, ikurecic commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# called a *quantum node* (QNode), which is the sum of two things:
I actually like union. Let's go with that? 'Fusion' would be a bit insane.

2024-07-18 08:57 UTC, ikurecic commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# And just like that, you’re in PennyLane land! Now you might be asking: “What is ``pl_func`` and how
Why not. :)

2024-07-18 08:58 UTC, ikurecic commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# Alternatively, because PennyLane’s primitive is a glorified Python function, wrapping a quantum
Yeah, why not. I thought about just removing the word "glorified" or replacing it with something like "actual," but this works.

2024-07-18 08:58 UTC, ikurecic commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# .. include:: ../_static/authors/isaac_de_vlugt.txt
Should work.

2024-07-18 09:00 UTC, ikurecic commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +  researching or learning. That’s why we have a mandate to make our `documentation <https://docs.pennylane.ai/en/stable/index.html>`__easy to navigate,
```suggestion
  researching or learning. That’s why we have a mandate to make our `documentation <https://docs.pennylane.ai/en/stable/index.html>`__ easy to navigate,
```
Whoops, missing a space, I think.

2024-07-18 13:42 UTC, isaacdevlugt commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.metadata.json
> +    "canonicalURL": "/qml/demos/tutorial_ultimate_guide_to_pennylane_knowing_qiskit",
Will do!

2024-07-18 13:44 UTC, isaacdevlugt commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# called a *quantum node* (QNode), which is the sum of two things:
Lol yeah this isn't a restaurant that's combining international culinary experiences into a single dish

2024-07-18 13:44 UTC, isaacdevlugt commented on demonstrations/tutorial_guide_to_pennylane_knowing_qiskit.py
> +# called a *quantum node* (QNode), which is the sum of two things:
```suggestion
# called a *quantum node* (QNode), which is the union of two things:
```

2024-07-18 13:59 UTC, isaacdevlugt commented on demonstrations/how_to_use_qiskit1_with_pennylane.metadata.json
> +        },
@ikurecic added this in the related content section for my other demo

2024-07-19 15:53 UTC, Lorraine-at-Xanadu approved these changes
This looks great, @ikurecic. All of the links worked for me.

2024-07-22 14:26 UTC, merged