[WIP] [g-sim 3] (g + P)-sim
PennyLaneAI/qml pull request #1118
Opened 2024-05-25 20:25 UTC by Qottmann

Noticed that my approach in https://github.com/PennyLaneAI/qml/pull/1106 _might_ not work (in the sense that examples just becomes too large to confirm), doing the branching approach instead here. This has neater illustrations anyway 👍

2024-05-28 10:55 UTC, Qottmann commented
In the end I managed to combine both approaches into one, as they are effectlvely the same. The branching one is nice to understand the underlying transformations and the required maximum moment order. The g-sim in moment vector spaces approach is more practical and what one would do in the end, though I finally argue based on some scaling numbers that this approach is overall of limited practical utility and should be understood as a mere theoretical insight.

2024-05-28 12:28 UTC, dwierichs requested changes
Nice that you made this work, and in two ways, even! Congrats for this nice work @Qottmann :100:
Very nice and concise read, really liked it.

I left a number of comments, as usual a good bit of them are subjective suggestions.

Regarding the direction of the drawings: I think reverting it might actually be a good idea. However, I think it should be consistent with the other demo, and as the depicted matrices/tensors are _not_ a circuit diagram directly, it might be useful to have this visual differentiation. Also, the current ordering works with matrix product notation, which is nice :)  So I think both directions have their perks.

2024-05-28 12:28 UTC, dwierichs commented on demonstrations/tutorial_liesim3.py
> +E_in[1] = np.zeros((dim_g, dim_g), dtype=float)
Would this make sense?
```suggestion
E0_in = np.zeros((dim_g), dtype=float)
E1_in = np.zeros((dim_g, dim_g), dtype=float)
E_in = [E0_in, E1_in]
```

2024-05-28 12:28 UTC, dwierichs commented on demonstrations/tutorial_liesim3.py
> +# --U-==-+--------+   -+------+
Nice!

2024-05-28 12:28 UTC, dwierichs commented on demonstrations/tutorial_liesim3.py
> +# We can extend the above approach by more than one :math:`P` gate in the circuit.
This might connect more neatly to the next sentence?
```suggestion
# We can extend the above approach by a second :math:`P` gate in the circuit.
```

2024-05-28 12:28 UTC, dwierichs commented on demonstrations/tutorial_liesim3.py
> +# :math:`\mathcal{M}^m := \{p | p= h_{\alpha_1} .. h_{\alpha_m+1} \notin \mathcal{M}^{m-1} \}`
Technically, this would not exclude $\mathfrak{g}$ from $\mathcal{M}^2$, because $\mathfrak{g}$ is not in $\mathal{M}^1$, right?

2024-05-28 12:28 UTC, dwierichs commented on demonstrations/tutorial_liesim3.py
> +# We can now choose arbitrary DLA gates and maximum `one` :math:`p` gate to evolve the expectation value vector.
```suggestion
# We can now choose arbitrary DLA gates and a maximum of `one` :math:`p` gate to evolve the expectation value vector.
```
or 
```suggestion
# We can now choose arbitrary DLA gates and maximally `one` :math:`p` gate to evolve the expectation value vector.
```

2024-05-28 12:28 UTC, dwierichs commented on demonstrations/tutorial_liesim3.py
> +# First, we note that the maximum moment is quickly reached for small system sizes.
and this leads to exponential simulation cost, right?

2024-05-28 12:28 UTC, dwierichs commented on demonstrations/tutorial_liesim3.py
> +.. math:: H_\text{Ising} = J \sum_{i=1}^{n-1} X_i X_j + h \sum_{i=1}^n Z_i.
```suggestion
.. math:: H_\text{Ising} = J \sum_{i=1}^{n-1} X_i X_{i+1} + h \sum_{i=1}^n Z_i.
```

2024-05-28 12:28 UTC, dwierichs commented on demonstrations/tutorial_liesim3.py
> +# - P - U - E^0_in
Should `V` be in here?
```suggestion
# - V - P - U - E^0_in
```

2024-05-28 12:28 UTC, dwierichs commented on demonstrations/tutorial_liesim3.py
> +#  --| P^1 |    | res  |
Again, could include `V` in this comment?

2024-05-28 12:28 UTC, dwierichs commented on demonstrations/tutorial_liesim3.py
> +# for some fixed maximum moment order :math:`M_{\text{max}}` with some additional reductions due to the redundancies in the moment spaces.
Is this a different $M_\text{max}$ than $m_\text{max}$ in the introduction?

2024-05-30 11:35 UTC, Qottmann commented on demonstrations/tutorial_liesim3.py
> +a product of DLA elements. We do so by looking at `moments` of :math:`\mathfrak{g}` instead. The :math:`m`-th order moments are products of :math:`(m+1)` DLA elements.
I think its fine like that, dont want to overload the already packed sentence

2024-05-30 11:38 UTC, Qottmann commented on demonstrations/tutorial_liesim3.py
> +    generators = [op.pauli_rep for op in generators]
Haha I know you are not a fan of them! They are mostly from copy-pasting ancient code :) Changed it back ✅

2024-05-30 11:49 UTC, Qottmann commented on demonstrations/tutorial_liesim3.py
> +# elements that we need to keep track of.
I simplified it a bit. For some things I dont want to / cant make general statements about how things transform as we dont actually know that for sure. But since this is all very much a case study I can reformulate it like so

2024-05-30 12:24 UTC, Qottmann commented on demonstrations/tutorial_liesim3.py
> +# Now, we compute :math:`e^{i \theta h_{\mu_1} h_{\mu_2}} h_\alpha e^{-i \theta h_{\mu_1} h_{\mu_2}}` and decompose it in the DLA and first moments.
Yes good point! Though it should be on the first I think since I define $\mathcal{P} = e^{-i \theta p}$

2024-05-30 12:26 UTC, Qottmann commented on demonstrations/tutorial_liesim3.py
> +P_dagger = exppw(-theta, p) # complex conjugate
The conjugate of $\mathcal{P} = e^{-i \theta p}$ is $\mathcal{P}^\dagger = e^{i \theta p^\dagger}$ but since all $h_\alpha$ are Pauli words, so is $p$ and therefore hermitian (assuming we throw away imaginary factors - this is not really formalized here, should perhaps add that)

2024-05-30 12:28 UTC, Qottmann commented on demonstrations/tutorial_liesim3.py
> +# We want to confirm that the adjoint action of :math:`\mathcal{P}` is indeed fully described by the first moments.
✅

2024-05-30 12:33 UTC, Qottmann commented on demonstrations/tutorial_liesim3.py
> +# We can now choose arbitrary DLA gates and maximum `one` :math:`p` gate to evolve the expectation value vector.
Oh yeah I struggled with that one, thanks :D !

2024-05-30 12:38 UTC, Qottmann commented on demonstrations/tutorial_liesim3.py
> +.. math:: H_\text{Ising} = J \sum_{i=1}^{n-1} X_i X_j + h \sum_{i=1}^n Z_i.
Hm here we never actually set $J=h=1$ because we only look at the expectation value vectors.

2024-05-30 12:40 UTC, Qottmann commented on demonstrations/tutorial_liesim3.py
> +.. math:: H_\text{Ising} = J \sum_{i=1}^{n-1} X_i X_j + h \sum_{i=1}^n Z_i.
$J$ and $h$ are irrelevant in a sense but I am not sure just removing them helps here 🤔

2024-05-30 12:41 UTC, Qottmann commented on demonstrations/tutorial_liesim3.py
> +# - P - U - E^0_in
yeah good point!

2024-05-30 12:44 UTC, Qottmann commented on demonstrations/tutorial_liesim3.py
> +# For example, in all cases here there are no non-trivial :math:`3`-rd order moments. We would have to go :math:`n = 6`
Nope same thing (modulo the identity)

2024-05-30 12:45 UTC, Qottmann commented on demonstrations/tutorial_liesim3.py
> +:math:`\mathfrak{g}`-sim
yeah will have to wait and see if this gets fixed in time or if we just remove the math mode. For $\mathfrak{g}$ its not crucial but looks cooler 😎

2024-05-30 12:45 UTC, Qottmann commented on demonstrations/tutorial_liesim3.metadata.json
> +        }
yes :) have not updated the metadata

2024-05-30 20:32 UTC, dwierichs commented on demonstrations/tutorial_liesim3.py
> +P_dagger = exppw(-theta, p) # complex conjugate
Yes, exactly, it would be about those factors $i$. I get that we have not been dealing with them explicitly, but here a comment might be nice to calm down the confused mathematicians :P

2024-05-30 20:33 UTC, dwierichs commented on demonstrations/tutorial_liesim3.py
> +.. math:: H_\text{Ising} = J \sum_{i=1}^{n-1} X_i X_j + h \sum_{i=1}^n Z_i.
Ah, fair enough! Just leave them in, then :)

2024-05-30 20:33 UTC, dwierichs commented on demonstrations/tutorial_liesim3.py
> +# For example, in all cases here there are no non-trivial :math:`3`-rd order moments. We would have to go :math:`n = 6`
Ah okay, I was looking at the plot and seeing a slight difference, is that the identity then? :thinking:

2024-05-30 20:38 UTC, dwierichs reviewed
Thanks for all the updates! :tada: Sorry to keep you waiting but I'd like to do one more math-only pass before approving.

2024-05-30 20:38 UTC, dwierichs commented on demonstrations/tutorial_liesim3.py
> +and let us assume that :math:`p` is the product of two DLA operators that, itself, is not part of the DLA itself.
This line has "itself" twice :)

2024-05-30 20:38 UTC, dwierichs commented on demonstrations/tutorial_liesim3.py
> +the case :math`m_\text{comp} < m_\text{max}`.
Nice!

2024-05-31 10:40 UTC, dwierichs approved these changes
Took another look and I'm comfortable with the second approach now as well :) 
Just had some tiny additional comments, including one typo for math mode.

Remember to update metadata before merging :innocent:

2024-05-31 10:40 UTC, dwierichs commented on demonstrations/tutorial_liesim3.py
> +# Let us look at the case where we use a first order product, :math:`\mathcal{P} = e^{-i \theta h_{\mu_1} h_{\mu_2}}`, and only first order moments contribute to the adjoint action.
```suggestion
# Let us look at the case where we use a first order product, :math:`\mathcal{P} = e^{-i \theta h_{\mu_1} h_{\mu_2}}`, and only DLA operators and first order moments contribute to the adjoint action. 
```

2024-05-31 10:40 UTC, dwierichs commented on demonstrations/tutorial_liesim3.py
> +#    :align: center
For my taste, the first two images could be a tad smaller, and the last one should be bigger, because it has two images stacked horizontally.

2024-05-31 10:40 UTC, dwierichs commented on demonstrations/tutorial_liesim3.py
> +# .. math:: \mathcal{M}^m := \{p | p= h_{\alpha_1} .. h_{\alpha_m+1} \notin \mathcal{M}^{m-1} \} \cup \mathcal{M}^{m-1}
Nice!

2024-05-31 10:40 UTC, dwierichs commented on demonstrations/tutorial_liesim3.py
> +
Could add a comment on the fact that only the DLA operators are transformed correctly. No need to go into detail about the pseudoness of the adjoint rep and so on, but might be nice to underline that we can not treat M^1 as a new DLA entirely.

2024-05-31 10:40 UTC, dwierichs commented on demonstrations/tutorial_liesim3.py
> +# First, we note that the maximum moment is quickly reached for small system sizes. In that case we have :math`m_\text{comp} = m_\text{max}`
```suggestion
# First, we note that the maximum moment is quickly reached for small system sizes. In that case we have :math:`m_\text{comp} = m_\text{max}`
```

2024-06-05 09:59 UTC, Qottmann commented on demonstrations/tutorial_liesim3.py
> +P_dagger = exppw(-theta, p) # complex conjugate
yeah good point! Added a comment on this here, as well as adding a line of code that strips the scalar coefficient (not necessary here because thw to dla elements dont have overlapping wires, but to be sure and for the general case)

2024-06-05 12:05 UTC, Qottmann commented on demonstrations/tutorial_liesim3.py
> +# For example, in all cases here there are no non-trivial :math:`3`-rd order moments. We would have to go :math:`n = 6`
Actually there was a typo, i=0 is just the DLA, indeed for i=2 (the third line) there is a difference but those are the second moments, and for the third moments there is no difference as I originally meant

2024-06-12 09:57 UTC, ikurecic reviewed
Thanks for sharing, @Qottmann !

A note: I found some inconsistency in gate nomenclature — it would be worth it to check that the P gate is consistently capitalized and in mathcal or not.

Also, why is it called `tutorial_liesim3`? I assume this is for historical reasons; it might be better to pick something different (`_extension`)?

2024-06-12 09:57 UTC, ikurecic commented on demonstrations/tutorial_liesim3.py
> +Let us briefly recap the core principles of :math:`\mathfrak{g}`-sim. We consider a Lie algebra :math:`\mathfrak{g} = \{h_1, .., h_d\}`, which is closed
```suggestion
Let us briefly recap the core principles of :math:`\mathfrak{g}`-sim and construct a DLA. We consider a Lie algebra :math:`\mathfrak{g} = \{h_1, .., h_d\}`, which is closed
```

2024-06-12 09:57 UTC, ikurecic commented on demonstrations/tutorial_liesim3.py
> +#     For DLAs consisting of Pauli words - as is the case for the TFIM, we can simply remove any scalar factors to avoid having additional imaginary factors in the exponent of gates.
```suggestion
#     For DLAs consisting of Pauli words — as is the case for the TFIM — we can simply remove any scalar factors to avoid having additional imaginary factors in the exponent of gates.
```

2024-06-12 09:57 UTC, ikurecic commented on demonstrations/tutorial_liesim3.py
> +    # assert that it is indeed a pure pauli word, not a sentence
```suggestion
    # assert that it is indeed a pure Pauli word, not a sentence
```

2024-06-12 09:57 UTC, ikurecic commented on demonstrations/tutorial_liesim3.py
> +success = True
Sorry, what is this for?

2024-06-12 09:57 UTC, ikurecic commented on demonstrations/tutorial_liesim3.py
> +# let us look how entering it in a circuit transforms DLA elements (and therefore expectation value vector elements):
```suggestion
# let us look how entering it in a circuit transforms DLA elements (and therefore expectation value vector elements).
```

2024-06-12 09:57 UTC, ikurecic commented on demonstrations/tutorial_liesim3.py
> +# We also obtain the :math:`3`-rd order diagram containing both :math:`\boldsymbol{P}^1` tensors.
```suggestion
# First, the zeroth- and first-order contribution. This can be seen as the branching off from the first previous diagram.
#
# .. figure:: /_static/demonstration_assets/liesim3/2P_first_second.png
#    :width: 35%
#    :align: center
#
# We also obtain the third-order diagram containing both :math:`\boldsymbol{P}^1` tensors.
```
Unless there's a reason to keep the math-mode and hyphens? Alternatively, 3rd-order (etc.) would work.

2024-06-12 09:57 UTC, ikurecic commented on demonstrations/tutorial_liesim3.py
> +# To get the correct results, we also obtain intermediate :math:`2`-nd order diagrams.
```suggestion
# To get the correct results, we also obtain intermediate second-order diagrams.
```

2024-06-12 09:57 UTC, ikurecic commented on demonstrations/tutorial_liesim3.py
> +# :math:`98` dimensional first order moment vector space :math:`\mathcal{M}^1`.
```suggestion
# maximum moment already for the second order 
# (the additional operator in the third moment space is just the identity).
#
# We can repeat our original computation for the first moments using the 
# :math:`98`-dimensional first-order moment vector space :math:`\mathcal{M}^1`.
```

2024-06-12 09:57 UTC, ikurecic commented on demonstrations/tutorial_liesim3.py
> +# Next, we compute the (pseudo) adjoint representation of :math:`\mathcal{M}^1`.
```suggestion
# Next, we compute the (pseudo-)adjoint representation of :math:`\mathcal{M}^1`.
```

2024-06-12 09:57 UTC, ikurecic commented on demonstrations/tutorial_liesim3.py
> +# We can now choose arbitrary DLA gates and a maximum of `one` :math:`p` gate to evolve the expectation value vector.
```suggestion
# We can now choose arbitrary DLA gates and a maximum of `one` :math:`P` gate to evolve the expectation value vector.
```
Would this be right?

2024-06-12 09:57 UTC, ikurecic commented on demonstrations/tutorial_liesim3.py
> +# The above diagrams are handy to understand the maximum moment order required for adding :math:`P`-gates of a certain order.
```suggestion
# The above diagrams are handy to understand the maximum moment order required for adding :math:`P` gates of a certain order.
```

2024-06-12 09:57 UTC, ikurecic commented on demonstrations/tutorial_liesim3.py
> +# get away with a polynomial cost in :math:`n`, as we have :math:`O(\text{dim}(\mathfrak{g})^{m_{\text{comp}}})` sized objects
```suggestion
# get away with a polynomial cost in :math:`n`, as we have :math:`O(\text{dim}(\mathfrak{g})^{m_{\text{comp}}})`-sized objects
```

2024-06-12 09:57 UTC, ikurecic commented on demonstrations/tutorial_liesim3.py
> +# for some fixed maximum moment order :math:`m_{\text{comp}}` in the computation with some additional reductions due to the redundancies in the moment spaces.
```suggestion
# for some fixed maximum moment order :math:`m_{\text{comp}}` in the computation, with some additional reductions due to the redundancies in the moment spaces.
```

2024-06-12 09:57 UTC, ikurecic commented on demonstrations/tutorial_liesim3.py
> +# For example, in all cases here there are no non-trivial :math:`3`-rd order moments. We would have to go :math:`n = 6`
```suggestion
# For example, in all cases here there are no non-trivial third-order moments. We would have to go to :math:`n = 6`,
```

2024-06-12 09:57 UTC, ikurecic commented on demonstrations/tutorial_liesim3.py
> +# :math:`1980^3 \approx 2^{32}` commutators to compute the (pseudo) adjoint representation. This is
```suggestion
# :math:`1980^3 \approx 2^{32}` commutators to compute the (pseudo-)adjoint representation. This is
```

2024-06-12 09:57 UTC, ikurecic commented on demonstrations/tutorial_liesim3.py
> +# Hence, this method is effectively restricted to very few non-DLA gates of Ising-type DLAs
```suggestion
# Hence, this method is effectively restricted to very few non-DLA gates of Ising-type DLAs,
```

2024-06-12 09:57 UTC, ikurecic commented on demonstrations/tutorial_liesim3.py
> +
The limitations are clear, but I would love to see a concluding paragraph (if not a section). What good is this, what is an alternative? Ideally a pointer to some other available resource, too. Do you have any ideas?

2024-06-12 09:57 UTC, ikurecic commented on demonstrations/tutorial_liesim3.metadata.json
> +        }
You probably wanted to remove the third one and replace it with the first `liesim` demo?

2024-06-12 09:57 UTC, ikurecic commented on demonstrations/tutorial_liesim3.metadata.json
> +    ],
tk note to replace when available

2024-06-12 09:57 UTC, ikurecic commented on demonstrations/tutorial_liesim3.metadata.json
> +    "seoDescription": "An extension of g-sim with non-DLA operators",
Should this be closer to the final title?

2024-06-12 09:57 UTC, ikurecic commented on demonstrations/tutorial_liesim3.metadata.json
> +    "canonicalURL": "/qml/demos/tutorial_liesim",
tk to be changed

2024-06-13 14:10 UTC, Qottmann reviewed
I will update the metadata together with the thumbnail

> A note: I found some inconsistency in gate nomenclature — it would be worth it to check that the P gate is consistently capitalized and in mathcal or not.

The mathcal $\mathcal{P}$ is referring to the unitary gate $\mathcal{P} = e^{-i \theta h_{\mu}}$ whereas the $P$ is the adjoint action "gate" $P = e^{-i \theta ad_{h_{\mu}}}$. There was one case where a regular $p$ was not capitalized that you found, I corrected that 👍 

> Also, why is it called tutorial_liesim3? I assume this is for historical reasons; it might be better to pick something different (_extension)?

Good point! Will update the file names 👍

2024-06-17 07:18 UTC, ikurecic commented on demonstrations/tutorial_liesim3.py
> +r"""(g + P)-sim: Extending g-sim by non-DLA observables and gates
At least one part of that problem was recently fixed, as you can see here:
![image](https://github.com/PennyLaneAI/qml/assets/4939555/c5c84e80-d90d-465d-b4d9-bc20e628f3e9)
Could you try changing it to inline? If it breaks, then revert.

2024-06-17 07:19 UTC, ikurecic commented on demonstrations/tutorial_liesim3.py
> +
Love it, that's what was missing. Thanks.

2024-06-17 07:36 UTC, ikurecic reviewed
Thanks, @Qottmann .
Two items remain:
- I'll look into fixing the rendering issue in the first note.
- If you could check if the demo title would display correctly if math-mode is used within it, that would be great. This issue in section titles was fixed recently.

2024-06-17 07:36 UTC, ikurecic commented on demonstrations/tutorial_liesim_extension.py
> +    :doc:`dynamical Lie algebras </demos/tutorial_liealgebra>` and :doc:`:math:`\mathfrak{g}`-sim in PennyLane </demos/tutorial_liesim>` are advised.
![image](https://github.com/PennyLaneAI/qml/assets/4939555/878e4851-f275-4887-8793-3dbbd049c11b)
Something went wrong here.
I'll look into it.

2024-06-17 08:25 UTC, Qottmann commented on demonstrations/tutorial_liesim_extension.py
> +    :doc:`dynamical Lie algebras </demos/tutorial_liealgebra>` and :doc:`:math:`\mathfrak{g}`-sim in PennyLane </demos/tutorial_liesim>` are advised.
Yeah I think I've seen this before, just gonna remove the mathmode from the link 🙃

2024-06-17 09:19 UTC, ikurecic commented on demonstrations/tutorial_liesim.py
> +:math:`\mathfrak{g}`-sim theory
Ahh, it doesn't work, @Qottmann  :[ 
I'll check about this as well, but I guess reverting to no-math in the title is the right choice here. Thanks.

2024-06-18 14:58 UTC, ikurecic commented on demonstrations/tutorial_liesim_extension.py
> +    :doc:`dynamical Lie algebras </demos/tutorial_liealgebra>` and :doc:`g-sim in PennyLane </demos/tutorial_liesim>` are advised.
```suggestion
    :doc:`dynamical Lie algebras </demos/tutorial_liealgebra>` and :doc:`g-sim in PennyLane </demos/tutorial_liesim>` is advised.
```

2024-06-18 15:19 UTC, ikurecic approved these changes

2024-06-18 15:19 UTC, merged