converted demo notebook
PennyLaneAI/qml pull request #1119
Opened 2024-05-27 15:22 UTC by JosephRRB

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Remember to do a grammar check of the content you include.
- [ ] All tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**
Generative quantum eigensolver demo using Pennylane

**Summary:**
We use Pennylane to generate a static molecular dataset and calculate the corresponding energies to train a small GPT model as described by https://arxiv.org/abs/2401.09253. We show that as training progresses, the GPT model generates operator sequences whose predicted energies more accurately resembles the true energies calculated by Pennylane. In addition, the sampling process is shown to better generate the ground state for better performing models. 

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

----
If you are writing a demonstration, please answer these questions to facilitate the marketing process.

* GOALS — Why are we working on this now?

  *Eg. Promote a new PL feature or show a PL implementation of a recent paper.*

* AUDIENCE — Who is this for?

  *Eg. Chemistry researchers, PL educators, beginners in quantum computing.*

* KEYWORDS — What words should be included in the marketing post?

* Which of the following types of documentation is most similar to your file? 
(more details [here](https://www.notion.so/xanaduai/Different-kinds-of-documentation-69200645fe59442991c71f9e7d8a77f8))
    
- [ ] Tutorial
- [ ] Demo
- [ ] How-to

2024-05-29 01:56 UTC, josh146 commented
Hey @JosephRRB! You'll want to rename the tutorial file, to remove the `tutorial_` part of the filename. this instructs to our build system not to try and execute it.

2024-06-03 20:44 UTC, josh146 commented on demonstrations/gqe_training.metadata.json
> +    "categories": [],
```suggestion
    "categories": ["Quantum Machine Learning"],
```

2024-06-03 20:46 UTC, josh146 commented on demonstrations/gqe_training.metadata.json
> +    "basedOnPapers": [],
```suggestion
    "references": [
        {
            "id": "gqe_paper",
            "type": "article",
            "title": "The generative quantum eigensolver (GQE) and its application for ground state search",
            "authors": "K. Nakaji, L. B. Kristensen, J. A. Campos-Gonzalez-Angulo, M. G. Vakili, H. Huang, M. Bagherimehrab, C. Gorgulla, F. Wong, A. McCaskey, J. S. Kim, T. Nguyen, P. Rao, A. Aspuru-Guzik",
            "year": "2024",
            "journal": "",
            "url": "https://arxiv.org/abs/2401.09253"
        }
    ],
    "basedOnPapers": [
        "10.48550/arXiv.2401.09253"
    ],
```

2024-06-03 22:13 UTC, josh146 commented on demonstrations/gqe_training.py
> +#    Molecule: H2, n_ops: 32, num_qubits: 4
```suggestion
#  .. code-block: none
# 
#     Molecule: H2, n_ops: 32, num_qubits: 4
```

2024-06-03 22:14 UTC, josh146 commented on demonstrations/gqe_training.py
> +#    Wall time: 47 s
```suggestion
#  .. code-block: none
# 
#     CPU times: user 47 s, sys: 37.5 ms, total: 47 s
#     Wall time: 47 s
```

2024-06-03 22:14 UTC, josh146 commented on demonstrations/gqe_training.py
> +#    num non-decayed parameter tensors: 25, with 19,200 parameters
```suggestion
#  .. code-block: none
# 
#     number of parameters: 84.98M
#     num decayed parameter tensors: 50, with 84,963,072 parameters
#     num non-decayed parameter tensors: 25, with 19,200 parameters
```

2024-06-03 22:14 UTC, josh146 commented on demonstrations/gqe_training.py
> +#      from .autonotebook import tqdm as notebook_tqdm
```suggestion
#  .. code-block: none
# 
#       from .autonotebook import tqdm as notebook_tqdm
```

2024-06-03 22:15 UTC, josh146 commented on demonstrations/gqe_training.py
> +#    using fused AdamW: True
```suggestion
#  .. code-block: none
# 
#     using fused AdamW: True
```

2024-06-03 22:15 UTC, josh146 commented on demonstrations/gqe_training.py
> +#    Wall time: 2h 12min 32s
```suggestion
#  .. code-block: none
# 
#     Iteration: 500, Loss: 0.004496691238049528, MAE: 0.13945468622863236, Ave E: -1.1161227981406456
#     Saved model!
#     Iteration: 1000, Loss: 0.001162520404255374, MAE: 0.11792013497926974, Ave E: -1.116178063434579
#     Saved model!
#     Iteration: 1500, Loss: 0.0006311882560414964, MAE: 0.08421050347067748, Ave E: -1.1304435666682537
#     Saved model!
#     Iteration: 2000, Loss: 0.0002220232025956396, MAE: 0.03313205549288038, Ave E: -1.13411711385679
#     Saved model!
#     Iteration: 2500, Loss: 9.021296506465553e-05, MAE: 0.03720317687198404, Ave E: -1.1360217383940532
#     Iteration: 3000, Loss: 0.00011929328764308375, MAE: 0.010246824522607662, Ave E: -1.1355033629645301
#     Saved model!
#     Iteration: 3500, Loss: 4.015137835017087e-05, MAE: 0.008332604993116905, Ave E: -1.1362737218253494
#     Saved model!
#     Iteration: 4000, Loss: 0.00025425587370956726, MAE: 0.03346923599957368, Ave E: -1.13442109812976
#     Iteration: 4500, Loss: 4.590269966149363e-05, MAE: 0.0086580669691949, Ave E: -1.1344678899103924
#     Iteration: 5000, Loss: 2.7407370499136962e-05, MAE: 0.006680762382889203, Ave E: -1.136412143925528
#     Saved model!
#     Iteration: 5500, Loss: 3.778071550021417e-05, MAE: 0.014272903220676704, Ave E: -1.1362969016861684
#     Iteration: 6000, Loss: 2.2792776141250974e-05, MAE: 0.007428675818214263, Ave E: -1.1367647064449693
#     Iteration: 6500, Loss: 1.9002385742602413e-05, MAE: 0.004431537870071902, Ave E: -1.135880723613281
#     Saved model!
#     Iteration: 7000, Loss: 1.5268728079291623e-05, MAE: 0.002464256235883442, Ave E: -1.1356989137037925
#     Saved model!
#     Iteration: 7500, Loss: 1.1030378864566936e-05, MAE: 0.007000517223791054, Ave E: -1.1360445255294285
#     Iteration: 8000, Loss: 7.638036884241474e-06, MAE: 0.0044611951680048586, Ave E: -1.1352658877947734
#     Iteration: 8500, Loss: 1.616690860258467e-05, MAE: 0.004094392133172753, Ave E: -1.1356437076129735
#     Iteration: 9000, Loss: 7.37882245331426e-06, MAE: 0.004240113290004896, Ave E: -1.1358971131175264
#     Iteration: 9500, Loss: 1.004411104422562e-05, MAE: 0.010631562300185794, Ave E: -1.1368761600775912
#     Iteration: 10000, Loss: 1.809862392776087e-05, MAE: 0.01987725166307399, Ave E: -1.1345492765523346
#     CPU times: user 2h 12min 24s, sys: 8.18 s, total: 2h 12min 32s
#     Wall time: 2h 12min 32s
```

2024-06-03 22:16 UTC, josh146 commented on demonstrations/gqe_training.py
> +#
```suggestion
np.log(losses).hvplot(title="Training loss progress", ylabel="log(loss)", xlabel="Training epochs").opts(fig_size=500)
######################################################################
# .. rst-class :: sphx-glr-script-out
# 
```

2024-06-03 22:17 UTC, josh146 commented on demonstrations/gqe_training.py
> +# # df_true.to_csv(f"./seq_len={seq_len}/true_Es_t.csv")
@JosephRRB should these comments be present/be deleted?

2024-06-03 22:17 UTC, josh146 commented on demonstrations/gqe_training.py
> +#       .Curve.Ground_State_Energy       :Curve   [x]   (y)
```suggestion
#  .. code-block: none
# 
#     :Overlay
#        .Scatter.Mean_True_Energies      :Scatter   [index]   (Ave True E)
#        .Curve.I                         :Curve   [index]   (Ave True E)
#        .Area.I                          :Area   [index]   (Min True E,Max True E)
#        .Scatter.Mean_Predicted_Energies :Scatter   [index]   (Ave Pred E)
#        .Curve.II                        :Curve   [index]   (Ave Pred E)
#        .Area.II                         :Area   [index]   (Min Pred E,Max Pred E)
#        .Curve.Ground_State_Energy       :Curve   [x]   (y)
```

2024-06-03 22:18 UTC, josh146 commented on demonstrations/gqe_training.py
> +# hv.save(fig, f"./seq_len={seq_len}/gqe_progress.html")
Should these comments be deleted?

2024-06-03 22:18 UTC, josh146 commented on demonstrations/gqe_training.py
> +fig
Based on this line, would we include a plot image below?

2024-06-03 22:18 UTC, josh146 commented on demonstrations/gqe_training.py
> +#    -1.1372633205048763
```suggestion
#  .. code-block: none
# 
#     -1.1372633205048763
```

2024-06-03 22:19 UTC, josh146 commented on demonstrations/gqe_training.py
> +#    -1.114531299423375
```suggestion
#  .. code-block: none
# 
#     -1.114531299423375
```

2024-06-03 22:20 UTC, josh146 commented on demonstrations/gqe_training.py
> +#    -1.1369822088041555
```suggestion
#  .. code-block: none
# 
#     -1.1369822088041555
```

2024-06-03 22:21 UTC, josh146 commented on demonstrations/gqe_training.py
> +#    1.9988353331759405
```suggestion
#  .. code-block: none
# 
#     1.9988353331759405
```

2024-06-03 22:21 UTC, josh146 commented on demonstrations/gqe_training.py
> +#    0.02471825967235751
```suggestion
#  .. code-block: none
# 
#     0.02471825967235751
```

2024-06-03 22:21 UTC, josh146 commented on demonstrations/gqe_training.py
> +#    -1.1321997471813732
```suggestion
#  .. code-block: none
# 
#     -1.1321997471813732
```

2024-06-03 22:21 UTC, josh146 commented on demonstrations/gqe_training.py
> +#    -1.1370380157299025
```suggestion
#  .. code-block: none
# 
#     -1.1370380157299025
```

2024-06-03 22:21 UTC, josh146 commented on demonstrations/gqe_training.py
> +#    0.4452419446056904
```suggestion
#  .. code-block: none
# 
#     0.4452419446056904
```

2024-06-03 22:21 UTC, josh146 commented on demonstrations/gqe_training.py
> +#    0.01981113528517062
```suggestion
#  .. code-block: none
# 
#     0.01981113528517062
```

2024-06-03 22:21 UTC, josh146 commented on demonstrations/gqe_training.py
> +#    -1.135559902483167
```suggestion
#  .. code-block: none
# 
#     -1.135559902483167
```

2024-06-03 22:21 UTC, josh146 commented on demonstrations/gqe_training.py
> +#    -1.1372625492981558
```suggestion
#  .. code-block: none
# 
#     -1.1372625492981558
```

2024-06-03 22:21 UTC, josh146 commented on demonstrations/gqe_training.py
> +#    0.14978220004079995
```suggestion
#  .. code-block: none
# 
#     0.14978220004079995
```

2024-06-03 22:22 UTC, josh146 commented on demonstrations/gqe_training.py
> +#    6.781250274933829e-05
```suggestion
#  .. code-block: none
# 
#     6.781250274933829e-05
```

2024-06-03 22:22 UTC, josh146 commented on demonstrations/gqe_training.py
> +#    2    Best Model -1.135560 -1.137263 -1.125118
```suggestion
#  .. code-block: none
# 
#              Source      Aves      Mins      Maxs
#     0        Random -1.114531 -1.136982 -1.027878
#     1  Latest Model -1.132200 -1.137038 -1.125118
#     2    Best Model -1.135560 -1.137263 -1.125118
```

2024-06-03 22:22 UTC, josh146 commented on demonstrations/gqe_training.py
> +#    -1.1372633205048763
```suggestion
#  .. code-block: none
# 
#     -1.1372633205048763
```

2024-06-04 14:39 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# # df_true.to_csv(f"./seq_len={seq_len}/true_Es_t.csv")
They could be deleted, yes. They were just helping me remember what to do when I was running the analysis

2024-06-04 14:40 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# hv.save(fig, f"./seq_len={seq_len}/gqe_progress.html")
Yes, as well

2024-06-04 14:43 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +fig
It should have a resulting plot but it seems that the conversion didn't render it? I can manually upload the image to the repo but where can I put it and how can we link it to the demo?

2024-06-04 16:59 UTC, josh146 commented on demonstrations/gqe_training.py
> +fig
@ikurecic @KetpuntoG do you know the best place to upload the images :)

2024-06-04 16:59 UTC, josh146 commented on demonstrations/gqe_training.py
> +# hv.save(fig, f"./seq_len={seq_len}/gqe_progress.html")
thanks!

2024-06-04 16:59 UTC, josh146 commented on demonstrations/gqe_training.py
> +# # df_true.to_csv(f"./seq_len={seq_len}/true_Es_t.csv")
Ah okay, if they are not needed I recommend deleting them, and optionally adding a text description if any explanation of the analysis here is helpful :)

2024-06-04 16:59 UTC, josh146 commented on demonstrations/gqe_training.py
> +# .. rst-class :: sphx-glr-script-out
@JosephRRB there is a typo here and below; this should be
```suggestion
# .. rst-class:: sphx-glr-script-out
```

Do you mind fixing the other ones as well, thanks!

2024-06-04 16:59 UTC, josh146 commented on demonstrations/gqe_training.py
> +#  .. code-block: none
this should be:
```suggestion
#  .. code-block:: none
```

this is why outputs are not appearing. Do you mind fixing this in the other places this typo occurs, thanks!

2024-06-04 17:18 UTC, KetpuntoG commented on demonstrations/gqe_training.py
> +fig
I suggest create the folder `_static/demostration_assets/gpe_training/`

2024-06-07 02:15 UTC, josh146 commented on demonstrations/gqe_training.py
> +#  .. code-block: none
Unfortunately this looks like a bug in the converter script :(

2024-06-10 17:33 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +fig
Hello @KetpuntoG , I've uploaded the images now. Can you tell me how to reference those images in the demo py file? :)

2024-06-11 12:52 UTC, ikurecic commented on demonstrations/gqe_training.py
> +fig
Hey @JosephRRB , to include images in the demo file, you can use the syntax described in the [readme](https://github.com/PennyLaneAI/qml):

```
##############################################################################
#.. figure:: ../_static/demonstrations_assets/<demo name>/image.png
#    :align: center
#    :width: 90%
```

I hope that helps! ☺

2024-08-29 10:11 UTC, ikurecic reviewed
Quick feedback re metadata file. I'll update the images and image paths now.

2024-08-29 10:11 UTC, ikurecic commented on demonstrations/gqe_training.metadata.json
> +    "dateOfLastModification": "2024-05-27T00:00:00+00:00",
TK

2024-08-29 10:11 UTC, ikurecic commented on demonstrations/gqe_training.metadata.json
> +            "id": "joseph_bunao"
Do you have a PennyLane Profile? You should make one if you don't have one already. :) Then you should use this:
```suggestion
            "username": "your_username"
```

2024-08-29 10:11 UTC, ikurecic commented on demonstrations/gqe_training.metadata.json
> +    "title": "Generative quantum eigensolver training using Pennylane data",
```suggestion
    "title": "Generative quantum eigensolver training using PennyLane data",
```

2024-08-29 10:11 UTC, ikurecic commented on demonstrations/gqe_training.metadata.json
> +    ],
tk

2024-08-29 10:11 UTC, ikurecic commented on demonstrations/gqe_training.metadata.json
> +    "seoDescription": "Training a small GPT model using Pennylane data",
```suggestion
    "seoDescription": "Learn how you can train a small GPT model using PennyLane data.",
```

2024-08-29 10:11 UTC, ikurecic commented on demonstrations/gqe_training.metadata.json
> +    "relatedContent": [],
tk

2024-08-29 12:00 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# exponentially.
Are these hyphens supposed to be bullet points? If yes, you need line breaks. But I'm not sure if you want to have such a long-winded amount of text here. Maybe make two or three paragraphs out of it instead?

2024-08-29 12:02 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# training efficiency as well. - This was not clear in the paper. Instead, what they described is
Maybe this sentence can be a bit gentler?

2024-08-29 12:02 UTC, ikurecic commented on demonstrations/gqe_training.py
> +#       corresponding to ``0`` so that it will never be chosen in the later parts of the sequence.
This feels a little out-of-context. What are you describing here? What does this have to do with the rest of the Demo? And why is it in bullet points? If you can improve this, that would be nice. If not, please share the information with me, and I will take care of it.

2024-08-29 12:04 UTC, ikurecic commented on demonstrations/gqe_training.py
> +#     using fused AdamW: True
Is there a reason why there are multiple separate outputs here?

2024-08-29 12:04 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# everytime the metric gets better)
To create a list, you should use line breaks.

2024-08-29 12:04 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# For each nth iteration (500 here), evaluate the GPT model by: - Generating a batch of sequences and
```suggestion
# For each n-th iteration (500 here), evaluate the GPT model by: - Generating a batch of sequences and
```

2024-08-29 12:05 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# everytime the metric gets better)
Also, use the same verb tense across all bullet points and write PennyLane with the capitalized L.

2024-08-29 12:06 UTC, ikurecic commented on demonstrations/gqe_training.py
> +        # For evaluation of gpt
```suggestion
        # For GPT evaluation
```

2024-08-29 12:06 UTC, ikurecic commented on demonstrations/gqe_training.py
> +            temperature=0.001, # use low temp to emphasize difference in logits
```suggestion
            temperature=0.001, # Use a low temperature to emphasize the difference in logits
```

2024-08-29 12:06 UTC, ikurecic commented on demonstrations/gqe_training.py
> +
This is missing some text to explain what is going on in this section.

2024-08-29 12:07 UTC, ikurecic commented on demonstrations/gqe_training.py
> +#.. figure:: ../_static/demonstration_assets/gqe_training/gqe_training_loss.png
The font size of the labels and title here could be increased, and this image should be included after the corresponding code that generates it.

2024-08-29 12:08 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# In this plot, we track the performance of the GPT model throughout its training. As mentioned
```suggestion
# In this section, we will track the performance of the GPT model throughout its training. As mentioned
```

2024-08-29 12:08 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# before, every after 500th iteration, we let the model generate a batch of sequences. Alongside, we
```suggestion
# before, after every 500th iteration, we let the model generate a batch of sequences. Alongside, we
```

2024-08-29 12:08 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# Once we have the generated sequences, we can also let Pennylane calculate the true sequence
```suggestion
# Once we have the generated sequences, we can also let PennyLane calculate the true sequence
```

2024-08-29 12:09 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# sampled gets closer to the ground state energy (the dashed line).
This paragraph should go after the plot.

2024-08-29 12:09 UTC, ikurecic commented on demonstrations/gqe_training.py
> +#.. figure:: ../_static/demonstration_assets/gqe_training/gqe_performance.png
The same comment as for the other plot: please increase the font size of labels and titles. Ideally, maybe even numbers.

2024-08-29 12:10 UTC, ikurecic commented on demonstrations/gqe_training.py
> +######################################################################
This section doesn't have any text?

2024-08-29 12:10 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# ~~~~~~~~~~~~~~~~
This section is missing an explanation. What is going on here? Could you please describe a bit?

2024-08-29 12:10 UTC, ikurecic commented on demonstrations/gqe_training.py
> +#    -  Already gives a minimum value close to the ground state energy
I don't follow these bullet points. Could you please write a paragraph instead?

2024-08-29 12:11 UTC, ikurecic commented on demonstrations/gqe_training.py
> +#    -  Already gives a minimum value close to the ground state energy
It would also be good to add text after every output to explain the results you are showing here.

2024-08-29 12:11 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# Latest model
What does 'latest model' mean?

2024-08-29 12:11 UTC, ikurecic commented on demonstrations/gqe_training.py
> +#    energies in the training set**
Could you please write a paragraph instead of bullet points here?

2024-08-29 12:12 UTC, ikurecic commented on demonstrations/gqe_training.py
> +#
Please add explanations and conclusions after code outputs in this section.

2024-08-29 12:12 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# ~~~~~~~~~~~~~~~~
The same comments here as in the previous sections. What does 'best model saved' mean? Could you add sentences instead of bullet points? Could you explain what you are doing here and what the results are and what they mean?

2024-08-29 12:13 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# ------------------------------------------------------------
Is there a reason this is a section? Were you planning on adding some text here and this is a placeholder?

2024-08-29 12:13 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# -  try other generative algorithms?
I think this section is still a draft? Could you please write it out? Thanks.

2024-08-29 12:15 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# each nth iteration, evaluate the GPT model
I think this section is also still a draft?

2024-09-05 19:59 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +We will show that the model gradually better approximates the correct energies for operator
Included a section for this

2024-09-05 20:04 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# (especially, a pool of unitary operators) from Pennylane.
Replaced with: "Recall that we would need a vocabulary of operators :math:`U_j`'s, ..."

2024-09-05 20:12 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +#
I added an introduction for the subsection. Although I'm not familiar concretely with `qml.DoubleExcitation` and `qml.SingleExcitation`. They should be returning unitary operators but I don't know their specifics. Do you think we should be that detailed here?

2024-09-05 20:16 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# To generate a dataset, we would be creating an operator sequence of fixed length and calculating the
Text in this subsection was reworked

2024-09-05 20:26 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# energy corresponding to that sequence by using Eq. 1 of the paper. This function ``energy_circuit``
Changed to " ... Eq. 1 of [1]." And the citation for [1] is written in the Reference section

2024-09-05 20:34 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# was implemented by Utkarsh using Pennylane.
I removed it now. We can include him in the authors. Would it be just simply adding him in the metadata?

2024-09-05 20:35 UTC, zeyueN commented on demonstrations/gqe_training.py
> +# The architecture of the GPT model we instantiate here is similar to that described in the paper.
we are not sure if it's really similar to the paper since their code is not public, right?

2024-09-05 20:35 UTC, zeyueN commented on demonstrations/gqe_training.py
> +# repo <https://github.com/XanaduAI/gpt-qe/tree/dev>`__ and was originally from this `nanoGPT
Instead of referencing our repo, let's provide a code block defining our `GPT` class inheriting from nanogpt with the necessary overloaded methods

2024-09-05 20:35 UTC, zeyueN commented on demonstrations/gqe_training.py
> +# in the default values of ``GPTConfig``. For our demo, the model then has a default of around 85
@JosephRRB let's just say `the default configurations for nano-gpt` with a link to the specific line in his repo.

2024-09-05 20:52 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +    """Computes Eq. 1 based on selected time evolution operators"""
Replaced as: "Computes Eq. 1 of [1] based on the selected unitary operators"

2024-09-05 20:52 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +        qml.apply(op) # Applies each of the time evolution operator
Replaced as: "Applies each of the unitary operators"

2024-09-05 20:53 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +    return qml.expval(hamiltonian) # Computes the energy via (1)
It should be Eq. 1. Replaced the comment as: "Computes the energy expectation value as in Eq. 1 of [1]"

2024-09-05 20:54 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# Note: Energy offsets are included for other molecules in the paper
I removed it as it's not relevant in the demo

2024-09-05 21:03 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +
Added "# Calculate the energies for each subsequence in the training set". Is that what you meant?

2024-09-05 21:25 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +#       corresponding to ``0`` so that it will never be chosen in the later parts of the sequence.
These should be the changes we made from the original nano-gpt code. I'll include the code this is referring to so that the reader will have more context.

2024-09-05 21:26 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# repo <https://github.com/XanaduAI/gpt-qe/tree/dev>`__ and was originally from this `nanoGPT
I'll just show the code that we made on top of the original nano-gpt repo.

2024-09-05 21:28 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# exponentially.
Yes, they were supposed to be bullet points for the code we changed and the differences on what was done in the paper. I'll make them into a paragraph instead.

2024-09-06 19:39 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# The architecture of the GPT model we instantiate here is similar to that described in the paper.
They specify these in the paper:

> featuring 12 attention layers, 12 attention heads, and 768 embedding dimension

That is just what I meant. I'll refer to them as model hyperparameters instead to avoid confusion

2024-09-09 16:51 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# repo <https://github.com/XanaduAI/gpt-qe/tree/dev>`__ and was originally from this `nanoGPT
Done!

2024-09-09 16:52 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# exponentially.
Done!

2024-09-09 16:53 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +#       corresponding to ``0`` so that it will never be chosen in the later parts of the sequence.
Done!

2024-09-09 16:56 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +#     using fused AdamW: True
Should come from this part of the notebook. I just removed the others instead. Just displaying the number of parameters

![Screenshot from 2024-09-09 12-54-59](https://github.com/user-attachments/assets/97b245fa-629e-479b-ae6e-0206cc7e7d10)

2024-09-09 17:05 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# In this plot, we track the performance of the GPT model throughout its training. As mentioned
Sentence was changed to: "We now track the performance of the GPT model throughout its training in Figure 2. "

2024-09-09 17:09 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +######################################################################
Subsection is now expounded and results are better collated into a table

See in: "4c. Sequence generation comparison"

2024-09-09 17:10 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# ~~~~~~~~~~~~~~~~
Results are better compiled in: 4c. Sequence generation comparison

2024-09-09 17:11 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +#    -  Already gives a minimum value close to the ground state energy
The bullet points are better compiled and explained in: 4c. Sequence generation comparison

2024-09-09 17:13 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# Latest model
The latest model is the model after all the training iterations are done. It's now described alongside the others as:

# Here, we compare some statistics of the true energies corresponding to sequences generated
# by a "random" model, the latest model after all the training iterations, and the best model
# saved based on the mean absolute error between the true and predicted energies during training

2024-09-09 17:15 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +#    energies in the training set**
Explained better now in: 4c. Sequence generation comparison

2024-09-09 17:45 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +proposed. A GQE is then a generative model where quantum states represented by quantum circuits are
The paper does not explicitly state what the scalability issue is for VQEs. From what I understand in the paper and some papers they referenced, it's because of the barren plateau landscape of the VQE cost function?

2024-09-09 17:53 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +proposed. A GQE is then a generative model where quantum states represented by quantum circuits are
Specifically:

> Potentially then, the barren plateau landscape of VQE and the quantum gradient evaluation of large circuits will be sidestepped by GQE. Thus, becoming more amenable for larger problems.

2024-09-09 18:16 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# %%time
Not necessary, but still informative to say where a bottleneck might be

2024-09-09 18:20 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# batch_size = 128
Removed batch_size, but time shouldn't be commented out code

2024-09-09 20:19 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# training efficiency as well. - This was not clear in the paper. Instead, what they described is
Currently, I rewrote it as:

> Since it was not explicitly shown in [#nakaji2024]_, another possible deviation we made is the logit calculation during offline training. It seems that the logits were accumulated by looping through the sequential generation of tokens. This is inefficient and unnecessary   
 for offline training since we can directly pass the fixed training sequences to the model and retrieve the relevant logits from it. This can be done because we are using a causal mask for the attention blocks so that the logits of the earlier tokens in the sequence are not affected by tokens in the later part of the sequence. Thus, having the same effect of the sequential token generation.

2024-09-12 03:14 UTC, zeyueN commented on demonstrations/gqe_training.py
> +# state. And lastly, we conclude.
```suggestion
# state. And lastly, we discuss the results, potential ways optimizing the code, and its extension into the "online training" phase.
```

2024-09-12 03:14 UTC, zeyueN commented on demonstrations/gqe_training.py
> +# molecules. Code optimization here can be done in the future.
I'm not sure if it's worth discussing the timing information. Maybe we can simply remove the timing output and this?

2024-09-12 03:14 UTC, zeyueN commented on demonstrations/gqe_training.py
> +# optimization. For instance, using `PennyLane Lightning GPU <https://docs.pennylane.ai/projects/lightning/en/latest/lightning_gpu/device.html>`__
```suggestion
# optimization. For instance, using `PennyLane Lightning<https://docs.pennylane.ai/projects/lightning/en/latest/lightning_gpu/device.html>`__ 
```
I wonder if Catalyst's JIT can help, maybe not since the generated circuit is not static?

2024-09-12 09:37 UTC, ikurecic reviewed
Thanks for the ping, @JosephRRB , this looks amazing. I left some comments and suggestions for you — please let me know if any of them don't seem good to you.

As I mentioned on Slack, you can just 'manually' uncomment the lines that were commented here, directly in teh PY file, that's not a problem at all. So I'll leave it to you to do that.

2024-09-12 09:37 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# More concretely, we summarize the "pre-"training loop in the Figure 3. This is called
```suggestion
# More concretely, we summarize the "pre-"training loop in Figure 3. This is called
```

2024-09-12 09:37 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# Recall that we would need a vocabulary of operators :math:`U_j`'s, an initial state :math:`\rho_0`, and
```suggestion
# Recall that we would need a vocabulary of operators :math:`U_j`, an initial state :math:`\rho_0`, and 
```

2024-09-12 09:37 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# the hamiltonian :math:`\hat{H}` for hydrogen gas. We also get the ground state energy for later comparison
```suggestion
# the Hamiltonian :math:`\hat{H}` for hydrogen gas. We also get the ground state energy for later comparison
```

2024-09-12 09:37 UTC, ikurecic commented on demonstrations/gqe_training.py
> +    # Get the same molecules as in the paper, with the addition of water
```suggestion
    # Get the same molecules as in the GQE paper, with the addition of water
```

2024-09-12 09:37 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# Currently, 47s is acceptable
```suggestion
# Currently, 47 s is acceptable, 
```

2024-09-12 09:37 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# or the jupyter notebook. Since nanoGPT is trained as a language model, its loss function and sampling method are
```suggestion
# or the Jupyter Notebook. Since nanoGPT is trained as a language model, its loss function and sampling method are 
```

2024-09-12 09:37 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# 3. For each n-th iteration (500 here), evaluate the GPT model:
```suggestion
# 3. For each n-th iteration (n is 500 here), evaluate the GPT model: 
```

2024-09-12 09:37 UTC, ikurecic commented on demonstrations/gqe_training.py
> +#    3a. Generate a batch of sequences and the predicted energies (total logits). Note that these are not necessarily same sequences in training set.
```suggestion
#    3a. Generate a batch of sequences and the predicted energies (total logits). Note that these are not necessarily same sequences as in training set.
```

2024-09-12 09:37 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# With a preliminary look at the training logs above, we see that the offline training took 2h and 12min for 10000
```suggestion
# With a preliminary look at the training logs above, we see that the offline training took 2 h and 12 min for 10,000 
```

2024-09-12 09:37 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# saved at the 7000th iteration where the mean absolute error is at its lowest. Another quantity we observe is the
```suggestion
# saved at the 7,000th iteration, where the mean absolute error is at its lowest. Another quantity we observe are the
```

2024-09-12 09:37 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# continues to decrease until around the 4000th iteration. There, the model was erroraneous but is quick
```suggestion
# continues to decrease until around the 4,000th iteration. There, the model was erroraneous but is quick
```

2024-09-12 09:37 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# the average predicted energies corresponds to the red markers and the distribution of predicted
```suggestion
# the average predicted energies correspond to the red markers and the distribution of predicted
```

2024-09-12 09:37 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# Note that at around the 4000th iteration, the predicted energies are very far from the true energies.
```suggestion
# Note that at around the 4,000th iteration, the predicted energies are very far from the true energies.
```

2024-09-12 09:37 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# This makes sense considering our observation in Figure 4. Also note that at the 7000th
```suggestion
# This makes sense considering our observation in Figure 4. Also note that at the 7,000th
```

2024-09-12 09:37 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# the GPT model is not restricted on a fixed dataset to overfit on.
```suggestion
# the GPT model is not restricted on a fixed dataset on which to overfit.
```

2024-09-12 09:37 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# (for our case, this is the model saved at the 7000th iteration).
```suggestion
# (for our case, this is the model saved at the 7,000th iteration).
```

2024-09-12 09:37 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# Contrast this with the minimum energy error for the best version which is 3 orders of magnitude smaller.
```suggestion
# Contrast this with the minimum energy error for the best version, which is 3 orders of magnitude smaller.
```

2024-09-12 09:37 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# the 7000th iteration worsened. That is, the predicted energies started to deviate further from the true energies
```suggestion
# This behavior is supported by our observation in Figure 5, where the performance of the model after
# the 7,000th iteration worsened. That is, the predicted energies started to deviate further from the true energies,
```

2024-09-12 09:37 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# (like an early stopping mechanism, and a learning rate schedule). The code itself is also open to
```suggestion
# (like an early stopping mechanism and a learning rate schedule). The code itself is also open to
```

2024-09-12 09:37 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# to evaluate the energies faster. An online training loop can also be implemented similar to our offline
```suggestion
# to evaluate the energies faster. An online training loop can also be implemented similarly to our offline
```

2024-09-12 09:37 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# version. The reader would just need to sample sequences from the current GPT model instead of a fixed
```suggestion
# version, the reader would just need to sample sequences from the current GPT model instead of a fixed
```

2024-09-12 09:37 UTC, ikurecic commented on demonstrations/gqe_training.py
> +# a high temperature then gradually decreasing so that the GPT model focuses more on the higher probability
```suggestion
# a high temperature, then gradually decreasing so that the GPT model focuses more on the higher probability
```

2024-09-12 13:49 UTC, ikurecic commented on demonstrations/gqe_training.metadata.json
> +    "categories": ["Quantum Machine Learning"],
Could you add Quantum Chemistry here? Maybe even Algorithms? What do you think?

2024-09-12 14:28 UTC, JosephRRB commented on demonstrations/gqe_training.metadata.json
> +    "seoDescription": "Learn how you can train a small GPT model using PennyLane data.",
I think I'll replace "technique" with "algorithm". Does it sound better?

2024-09-12 14:40 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +application for ground state search". We will only train on a fixed training dataset using the molecular data
Should we remove the "GQE" in the first sentence? Because the acronym is also defined in the paper title. It feels repetitive

2024-09-12 14:41 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +available in `PennyLane Datasets <https://pennylane.ai/datasets/>`__ as opposed to learning directly from the data
The phrase "... as opposed to learning directly from the data ..." was removed

2024-09-12 14:42 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +online training and only minor changes to the training loop code needs to be changed for it.
This phrase was also removed instead

2024-09-12 14:50 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# `Documentation <https://docs.pennylane.ai/projects/catalyst/en/stable/demos/adaptive_circuits_demo.html>`__.
There's a figure after this paragraph describing the VQE mentioned here. Should we move it as well? I'll leave the figure where it is for now

2024-09-12 15:35 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# With a preliminary look at the training logs above, we see that the offline training took 2h and 12min for 10000
If I uncomment-out `%%time`, the py file seems to complain. It might break the build much like the `curl` command before. I can just remove it and the output.

![Screenshot from 2024-09-12 11-28-48](https://github.com/user-attachments/assets/04764a61-e454-42fa-bf68-806b2c4eac3d)

2024-09-12 15:49 UTC, JosephRRB commented on demonstrations/gqe_training.metadata.json
> +    "categories": ["Quantum Machine Learning"],
Sure!

2024-09-12 17:27 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# With a preliminary look at the training logs above, we see that the offline training took 2h and 12min for 10000
Added the sentence:

"The code execution time was measured by including ``%%time`` before the code block. "

2024-09-12 18:02 UTC, zeyueN commented on demonstrations/gqe_training.py
> +# optimization. For instance, using `PennyLane Lightning GPU <https://docs.pennylane.ai/projects/lightning/en/latest/lightning_gpu/device.html>`__
I say yes

2024-09-12 18:36 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# of operators :math:`U_j`'s loaded from `PennyLane Datasets <https://pennylane.ai/datasets/>`__. We interpret these integers as
Looking at the PennyLane dataset loading, it seems that the operators `U_j` did not come directly from the PennyLane dataset? Instead, the operators were generated from `qml.SingleExcitation` and `qml.DoubleExcitation` but with the wire indices depend on the molecular data (namely, `n_electrons` and `n_orbitals`)

Something like:
``
import pennylane as qml

[dataset] = qml.data.load("qchem", molname="H2")
molecule = dataset.molecule

num_electrons, num_qubits = molecule.n_electrons, 2 * molecule.n_orbitals
singles, doubles = qml.qchem.excitations(num_electrons, num_qubits)
single_excs = [qml.SingleExcitation(2 / 160, wires=single) for single in singles] ## some of the operators
``
Is it still accurate then to mention that the operators we need are loaded from PennyLane Datasets?

2024-09-12 18:41 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# of operators :math:`U_j`'s loaded from `PennyLane Datasets <https://pennylane.ai/datasets/>`__. We interpret these integers as
The info we directly take from the `dataset` are

-  `dataset.molecule.n_electrons` and `dataset.molecule.n_orbitals`
-  `dataset.hamiltonian`
-  The initial state `dataset.hf_state`
-  The ground state energy `dataset.fci_energy`

2024-09-13 10:10 UTC, ikurecic reviewed
Nice, thanks.

2024-09-13 10:10 UTC, ikurecic commented on demonstrations/gqe_training.py
> +#    Figure 1: VQE diagram from [#nakaji2024]_
No, it's okay. :) I got confirmation that this is fine, thank you!

2024-09-13 17:40 UTC, zeyueN approved these changes
Thanks so much @JosephRRB  and @ikurecic 🏅 . The improvements have been transformative. Here's my LGTB on the ML side of things.

2024-09-18 15:04 UTC, obliviateandsurrender requested changes
Amazing work @JosephRRB! Leaving the first set of comments.

2024-09-18 15:04 UTC, obliviateandsurrender commented on demonstrations/gqe_training.py
> +# training iterations. The code execution time was measured by including ``%%time`` before the code block.
```suggestion
# training iterations. The code execution time was measured by including ``%%time`` magic command before the code block. 
```

2024-09-18 15:04 UTC, obliviateandsurrender commented on demonstrations/gqe_training.py
> +# ~~~~~~~~~~~~~~
```suggestion
# ~~~~~~~~~~~~~~~~~~
```

2024-09-18 15:04 UTC, obliviateandsurrender commented on demonstrations/gqe_training.py
> +# of a hydrogen gas molecule. The best underlying GPT model version can generate a state whose energy is
```suggestion
# of a hydrogen molecule. The best underlying GPT model version can generate a state whose energy is 
```

2024-09-18 15:04 UTC, obliviateandsurrender commented on demonstrations/gqe_training.py
> +# (like an early stopping mechanism and a learning rate schedule). The code itself is also open to
```suggestion
# (like an early stopping mechanism and a learning rate schedule). The code itself is also open to further
```

2024-09-19 13:32 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# instances" [#nakaji2024]_. This shortcoming makes it less competitive against the performance of
We included the double quotations since the phrase was directly quoted from the paper. We wanted to motivate the use of GQE as opposed to VQE but I was unsure about the logic behind the scalability problem of VQE. That's why we quoted directly instead. 

Would it be sufficient to just state the issue of trainability for large problem instances?

2024-09-19 13:37 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +    # Computes Eq. 1 of [1] based on the selected unitary operators
We included the reference to the paper because we didn't explicitly define an Eq 1 in the demo

2024-09-19 14:57 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +to find the optimal parameters that minimizes the corresponding energy :math:`E`. For more details on
Replaced with:

> It has been proposed as a scalable alternative to the `variational quantum eigensolver (VQE) <https://pennylane.ai/qml/demos/tutorial_vqe/>`__ approach,
where the quantum state is represented as a quantum circuit with tunable parameters which are then optimized during training in order to arrive at a 
state minimizing the corresponding energy :math:`E`. Instead, in GQE, the structure of the quantum circuit is given by a trained generative model.

2024-09-19 15:00 UTC, ddhawan11 reviewed
Great work @JosephRRB. Please find my comments, some of them are a bit nitpicky.

2024-09-19 15:27 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +design of the GQE algorithm which uses a GPT model), what it generates, and how we train it.
Replaced with:

> Firstly, we compare the GQE and VQE algorithms, and afterwards, we dive deeper in 
describing GPT-QE, i.e., the GQE algorithm which uses a GPT model, and its training.

2024-09-19 15:36 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# transformer (GPT) [#radford2019]_, [#vaswani2017]_ architecture. So, a GQE using a transformer is called GPT-QE.
Changed to:

 > In particular, the model architecture used by Nakaji et al. [#nakaji2024]_ for GQE was a generative pre-trained transformer (GPT) [#radford2019]_, [#vaswani2017]_. This choice is then reflected in the name GPT-QE.

2024-09-19 17:04 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# <https://github.com/karpathy/nanoGPT>`__ (a reimplementation of the `OpenAI GPT-2 <https://github.com/openai/gpt-2>`__) as the
It seems that the one without the hyphen is "more" correct :)

2024-09-19 17:09 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# saved at the 7,000th iteration, where the mean absolute error is at its lowest. Another quantity we observe are the
Changed to:

> ... The other quantities we observe ...

2024-09-19 17:45 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +application for ground state search* [#nakaji2024]_. The GQE algorithm is an alternative approach in estimating the
It seems that they want to leave the paper title here in the first paragraph

2024-09-19 17:51 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +application for ground state search* [#nakaji2024]_. The GQE algorithm is an alternative approach in estimating the
Changed to:

> The GQE algorithm is a quantum eigensolver using a classical generative model to estimate the ground state of any molecular Hamiltonian.

2024-09-19 18:14 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# the ground state.
Note to self:
- Write about the architecture of GQE -> samples circuits which gives the state
- model samples, not gqe itself

2024-09-19 18:24 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +    # Computes Eq. 1 of [1] based on the selected unitary operators
Changed to:

> Computes Eq. 1 from Nakaji et al. based on the selected unitary operators

2024-09-19 18:26 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +#    Figure 1: Diagrams of GQE and VQE from [#nakaji2024]_
Changed to:

> Figure 1: Diagrams of GQE and VQE from Figure 1 in [#nakaji2024]_

2024-09-19 18:47 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +By the end of the demo, we will show that the model gradually better approximates the correct energies and, in turn,
Changed "approximation" to "estimate"

2024-09-19 18:49 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# the ground state.
Changed to:

> Specifically, GQE uses a classical generative model where quantum circuits are sampled. Quantum 
> states are then constructed for each of these circuits. The generative model is then trained so that the
> states corresponding to the quantum circuits being sampled gives a better approximation for the ground state.

2024-09-19 18:55 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +application for ground state search* [#nakaji2024]_. The GQE algorithm is an alternative approach in estimating the
Changed to:

> We will be demonstrating and evaluating the algorithm described in `the
paper <https://arxiv.org/abs/2401.09253>`__ by Nakaji et al., titled *The generative quantum eigensolver (GQE) and its 
application for ground state search* [#nakaji2024]_. The aforementioned GQE algorithm is a quantum eigensolver using a classical 
generative model to estimate the ground state of any molecular Hamiltonian.

2024-09-19 23:53 UTC, obliviateandsurrender reviewed
Few minor nitpciks that are not blocking in anyway. I will approve once these are taken care of.

2024-09-19 23:53 UTC, obliviateandsurrender commented on demonstrations/gqe_training.py
> +generative model to estimate the ground state of any molecular Hamiltonian.
```suggestion
We will be demonstrating and evaluating a novel algorithm proposed by Nakaji et al. in their paper
`The generative quantum eigensolver (GQE) and its application for ground state search <https://arxiv.org/abs/2401.09253>`__
that employs a classical generative model of quantum circuits for the purpose of ground-state
energy estimation of any molecular Hamiltonian [#nakaji2024]_.  
```

2024-09-19 23:53 UTC, obliviateandsurrender commented on demonstrations/gqe_training.py
> +#    Figure 1: Diagrams of GQE and VQE from Figure 1 in [#nakaji2024]_
```suggestion
#    Figure 1: Diagrams of GQE and VQE from Fig. 1 in [#nakaji2024]_
```

2024-09-19 23:53 UTC, obliviateandsurrender commented on demonstrations/gqe_training.py
> +# states corresponding to the quantum circuits being sampled gives a better approximation for the ground state.
```suggestion
# proposed. Specifically, GQE uses a classical generative model where quantum circuits are sampled as a
# sequence of unitaries from a given operator pool. This generative model is then trained so that it learns to
# predict quantum circuits that evolves an input state to the states better approximating the ground state. 
```

2024-09-19 23:53 UTC, obliviateandsurrender commented on demonstrations/gqe_training.py
> +# In this demo, we see that GPT-QE is a viable alternative in estimating the ground state
```suggestion
# In this demo, we see that GPT-QE is a viable alternative in estimating the ground-state energy 
```

2024-09-19 23:53 UTC, obliviateandsurrender commented on demonstrations/gqe_training.py
> +# only around ``7.71e-07`` away from ground state energy. Additionally, since the GPT model being optimized
```suggestion
# only around ``7.71e-07 Ha`` away from ground state energy. Additionally, since the GPT model being optimized 
```

2024-09-19 23:53 UTC, obliviateandsurrender commented on demonstrations/gqe_training.py
> +# to the ground state energy ``grd_E=-1.1372633205048763`` with an error of around ``2.81e-04``. But we notice that the maximum energy
```suggestion
# to the ground state energy ``grd_E=-1.1372633205048763 Ha`` with an error of around ``2.81e-04 Ha``. But we notice that the maximum energy
```

2024-09-19 23:53 UTC, obliviateandsurrender commented on demonstrations/gqe_training.py
> +# and a ``7.71e-07`` error for the best model version. It is then very interesting that
```suggestion
# training set. Namely, around a ``2.25e-04 Ha`` error for the minimum energy generated by the latest model version
# and a ``7.71e-07 Ha`` error for the best model version. It is then very interesting that
```

2024-09-20 01:28 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# states corresponding to the quantum circuits being sampled gives a better approximation for the ground state.
I'll change "input" to "initial"

2024-09-20 01:33 UTC, JosephRRB commented on demonstrations/gqe_training.py
> +# and a ``7.71e-07`` error for the best model version. It is then very interesting that
Also changed ``grd_E=-1.1372633205048763 Ha`` in line 476

2024-09-20 01:39 UTC, obliviateandsurrender approved these changes
Looks good to go from my end.

2024-09-20 01:39 UTC, obliviateandsurrender commented on demonstrations/gqe_training.py
> +# As a slight extension of [#nakaji2024]_, we can also calculate the energies for each subsequence of
```suggestion
# As a slight extension, we can also calculate the energies for each subsequence of
```

2024-09-20 01:39 UTC, obliviateandsurrender commented on demonstrations/gqe_training.py
> +# only around ``7.71e-07 Ha`` away from ground state energy. Additionally, since the GPT model being optimized
```suggestion
# only around ``7.71e-07 Ha`` away from ground state energy, which is well below the chemical accuracy. Additionally, since the GPT model being optimized 
```

2024-09-20 13:02 UTC, merged