QROM demo
PennyLaneAI/qml pull request #1123
Opened 2024-06-06 15:31 UTC by KetpuntoG

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Remember to do a grammar check of the content you include.
- [ ] All tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

----
If you are writing a demonstration, please answer these questions to facilitate the marketing process.

* GOALS — Why are we working on this now?

  *Eg. Promote a new PL feature or show a PL implementation of a recent paper.*

* AUDIENCE — Who is this for?

  *Eg. Chemistry researchers, PL educators, beginners in quantum computing.*

* KEYWORDS — What words should be included in the marketing post?

* Which of the following types of documentation is most similar to your file? 
(more details [here](https://www.notion.so/xanaduai/Different-kinds-of-documentation-69200645fe59442991c71f9e7d8a77f8))
    
- [ ] Tutorial
- [ ] Demo
- [ ] How-to

2024-06-06 15:33 UTC, KetpuntoG commented
[sc-63852]

2024-06-10 16:36 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qrom.metadata.json
> +        "Algorithms",
The metadata I usually updated at the end when we already have the thumbnails

2024-06-21 14:32 UTC, ixfoduap requested changes
The overall structure is great, but I think there is a lot of room for improvement in the presentation

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +dev = qml.device("default.qubit", shots = 1)
Why shots=1? Isn't this unnecessary?

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +@partial(qml.devices.preprocess.decompose,
What does this do to affect the drawing? I've never seen this before and as a reader it leaves me puzzled

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +    print(f"The bitstring stored in the {i}-index is: {circuit(i)}")
```suggestion
    print(f"The bitstring stored in index{i} is: {circuit(i)}")
```

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +    return qml.sample(wires=target_wires)
Oh you're getting the output state by sampling? This seems very hacky. Isn't there a more elegant way to do this? :thinking:

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +qml.draw_mpl(circuit, style = "pennylane")(0)
Looking at the plot, I find the `BasisEmbedding` uninsightful, since it seems to indicate we do the same thing every time, even though we don't. I think it's better to explicitly construct the unitary that prepares each basis state. This is simply as it is only a sequence of X gates

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +# Nice, you can see that the outputs match the elements of our initial data list.
Maybe good to write down the list here again fir easy reference

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +# of the circuit. Another clever approach was introduced in [#selectSwap]_ , with a smart structure known as SelectSwap.
```suggestion
# Although the algorithm works correctly, the number of multicontrol gates is high.
# The decomposition of these gates is expensive and there are numerous works that attempt to simplify this.
# We highlight the work [#unary]_ which introduces an efficient technique using measurements in the middle
# of the circuit. Another clever approach was introduced in [#selectSwap]_ , with a smart structure known as SelectSwap, which we describe below.
```

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +In this demonstration, we will introduce the concept of Quantum Read-Only Memory (QROM), a data structure designed to facilitate these tasks.
In particular, we should probably mention that we have a specific QROM operation that implements it directly, and link to it already at the beginning for easy access

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +# reduce the number of gates required to build the QROM. We can detail the algorithm in two steps.
```suggestion
# The goal of the SelectSwap construction is to trade depth for width. That is, using multiple auxiliary qubits,
# we reduce the circuit depth required to build the QROM. We can detail the algorithm in two steps.
```

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +# First we use the auxiliary qubits to store more than one bitstring per column.
```suggestion
# First, we use the auxiliary qubits to store more than one bitstring per column.
```

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +# swap it to the target wires.
```suggestion
# In this way, we reduce the number of operators that Select requires. The main idea is to organize the data in two dimensions, with each bitstring labelled by a column index and a row index. 
# The control qubits of the Select block determine the column index, while a
# swap block is used to detect the row index and swap the data to the
# the target wires.
```

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +# swap it to the target wires.
I like this way of presenting it; let me know what you think

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +# .. figure:: ../_static/demonstration_assets/qrom/select_swap.jpeg
Move the figure to be below the text that explains it, not before

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +# Select operator.
```suggestion
# Select operator. Below we show an example with two columns and four rows:
```

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +# swap it to the target wires.
I think this could also use an step-by-step example for a specific bitstring showing how this circuits successfully implements QROM

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +# Select operator.
Could also use an explicit example here

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +# bitstring is located and those of the swap block the row :math:`r`.
```suggestion
# Following the same idea as before, the control wires of the select block will choose the column :math:`c` where the
# bitstring is located, and the control wires of the swap block determine the row :math:`r`.
```

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +# bitstring is located and those of the swap block the row :math:`r`.
Should introduce the labels c and r earlier in the text

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +# 1. **We start by generating the uniform superposition on the r-th register**.
The figure doesn't use r-register. Please use control, target, and work wires instead, or label the figure with r-wires etc

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +# bitstring is located and those of the swap block the row :math:`r`.
I think this is missing one or two sentences explaining the intuition behind the construction. Right now it appears a bit too much out of the blue for my taste

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +#       |c\rangle |r\rangle |0\rangle \dots |b_{cr}\rangle_r \dots |0\rangle
I find this description confusing. Let's chat in person so you can guide me through it

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +# Coding these ideas from scratch can be painful but with the help of PennyLane you can use it in just one line.
```suggestion
# Coding a QROM circuit from scratch can be painful, but with the help of PennyLane you can do it in just one line.
```

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +# We are going to encode the same bitstrings, using the first SelectSwap approach. In this example we use two work wires
```suggestion
# We are going to encode the same bitstrings, using the SelectSwap approach. In this example we use two work wires
```

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +@partial(qml.devices.preprocess.decompose, stopping_condition = my_stop, max_expansion=2)
What's the purpose of this @partial?

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +  qml.Hadamard(control_wires[-2])
I find this confusing, like you're trying to do too much. I suggest instead creating a more complicated QROM circuit and drawing it to show that it's correct and easy to implement with PL

2024-06-21 14:32 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +# State Preparation [#StatePrep]_ techniques by reducing the number of required gates, which I recommend you explore.
```suggestion
# state preparation [#StatePrep]_ techniques by reducing the number of required gates, which we recommend you explore.
```
Use "we", not "I"

2024-07-02 15:22 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qrom.py
> +@partial(qml.devices.preprocess.decompose,
otherwise it would be a box that says "QROM".  In demos like QFT I also use it. It's not ideal but it's the only way to do it with PennyLane right now

2024-07-02 15:44 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qrom.py
> +qml.draw_mpl(circuit, style = "pennylane")(0)
I clarified the text

2024-07-02 15:59 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qrom.py
> +# Select operator.
I added the example in the previous case. I think it is clear with that, so I add here a line inviting the reader to try it

2024-07-02 18:03 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qrom.py
> +#       |c\rangle |r\rangle |0\rangle \dots |b_{cr}\rangle_r \dots |0\rangle
I have added clarifications. Happy to talk in person if still needed

2024-07-02 18:04 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qrom.py
> +@partial(qml.devices.preprocess.decompose, stopping_condition = my_stop, max_expansion=2)
so that a box saying "QROM" does not appear

2024-07-02 19:30 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qrom.py
> +dev = qml.device("default.qubit", shots = 1)
This returns the bitstring directly so it is easy to check that it is the wanted element. If we want to go by probabilities (or state) we would have to see in which position we have a 1 in the output vector and pass that index to binary. I think it might be a bit more confusing

2024-07-02 23:03 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qrom.py
> +    return qml.sample(wires=target_wires)
https://github.com/PennyLaneAI/qml/pull/1123#discussion_r1663057198

2024-07-03 15:58 UTC, soranjh commented on demonstrations/tutorial_intro_qrom.py
> +We will now explain three different implementations of a QROM: Select, SelectSwap, and an extension of SelectSwap.
```suggestion
We will now explain three different implementations of QROM: Select, SelectSwap, and an extension of SelectSwap.
```

2024-07-03 15:58 UTC, soranjh commented on demonstrations/tutorial_intro_qrom.py
> +More generally, Select is an operator that prepares quantum states associated with indices. It is defined as:
```suggestion
Select is an operator that prepares quantum states associated with indices. It is defined as:
```

2024-07-03 15:58 UTC, soranjh commented on demonstrations/tutorial_intro_qrom.py
> +More generally, Select is an operator that prepares quantum states associated with indices. It is defined as:
You might want to link to the Select operator in PennyLane.

2024-07-03 15:58 UTC, soranjh commented on demonstrations/tutorial_intro_qrom.py
> +    \text{Sel}|i\rangle|0\rangle = |i\rangle U_i|0\rangle =|i\rangle|\phi_i\rangle,
```suggestion
    \text{Select}|i\rangle|0\rangle = |i\rangle U_i|0\rangle =|i\rangle|\phi_i\rangle,
```

2024-07-03 15:58 UTC, soranjh commented on demonstrations/tutorial_intro_qrom.py
> +where :math:`|\phi_i\rangle` is the i-th state we want to encode generated by a known-gate :math:`U_i`.
```suggestion
where :math:`|\phi_i\rangle` is the :math:`i`-th state we want to encode, generated by a known unitary :math:`U_i`.
```

2024-07-03 15:58 UTC, soranjh commented on demonstrations/tutorial_intro_qrom.py
> +
The drawing is better to come right after the circuit.

2024-07-03 15:58 UTC, soranjh commented on demonstrations/tutorial_intro_qrom.py
> +# Note that in this case we generate in the control qubits the state :math:`|011\rangle`, representation of the
This sentence is not very clear.

2024-07-03 15:58 UTC, soranjh commented on demonstrations/tutorial_intro_qrom.py
> +Since the bitstrings are encoded in computational basis states, we can view QROM as a special case of a Select operator.
This sentence is a bit vague. You might reorder it as: QROM can be considered a special case of the Select operator where the encoded states are computational basis states. Or something similar to this. Then continue with: Then the unitaries Ui can be simply X gates ...

2024-07-03 15:58 UTC, soranjh commented on demonstrations/tutorial_intro_qrom.py
> +We use :class:`~.pennylane.BasisEmbedding` as a useful template where given the bitstrings, it places the :math:`X` gates
"... as a useful template for preparing bitstrings, it places ...." seems better to me.

2024-07-03 15:58 UTC, soranjh commented on demonstrations/tutorial_intro_qrom.py
> +bitstrings = ["01", "11", "11", "00", "01", "11", "11", "00"]
Why you change the example?

2024-07-03 15:58 UTC, soranjh commented on demonstrations/tutorial_intro_qrom.py
> +# Once we have defined the circuit, we can check that the outputs are as expected.
Better if you use 000 as example, I got confused for a moment when I saw you add X, and you just mentioned using BasisEmbedding instead of adding X.

2024-07-03 15:58 UTC, soranjh commented on demonstrations/tutorial_intro_qrom.py
> +# We highlight the work [#unary]_ which introduces an efficient technique using measurements in the middle
```suggestion
# We highlight reference [#unary]_ which introduces an efficient technique using measurements in the middle
```

2024-07-03 15:58 UTC, soranjh commented on demonstrations/tutorial_intro_qrom.py
> +# We highlight the work [#unary]_ which introduces an efficient technique using measurements in the middle
It shows as reference 4, but it should be 1.

2024-07-03 15:58 UTC, soranjh commented on demonstrations/tutorial_intro_qrom.py
> +# Let's look at an example by assuming we want to load in the target wires the bitstring with
This paragraph is not easy to follow. What are b0, b1 ...? Also, seems better to stick with one example instead of using different examples in different sections.

2024-07-03 15:58 UTC, soranjh commented on demonstrations/tutorial_intro_qrom.py
> +# Reusable qubits
This section is not easy to follow.

2024-07-03 15:58 UTC, soranjh commented on demonstrations/tutorial_intro_qrom.py
> +# Coding a QROM circuit from scratch can be painful, but with the help of PennyLane you can do it in just one line.
```suggestion
# Coding a QROM circuit from scratch can be painful, but with the help of PennyLane you can do it in just one line of code.
```

2024-07-03 15:58 UTC, soranjh commented on demonstrations/tutorial_intro_qrom.py
> +# We are going to encode longer bitstrings and we will use enough work wires to group four bitstrings per column:
```suggestion
# Let's see an example where we encode longer bitstrings and we will use enough work wires to group four bitstrings per column:
```

2024-07-03 15:58 UTC, soranjh commented on demonstrations/tutorial_intro_qrom.py
> +# This function is included for drawing purposes only.
You can skip the drawing, or just show QROM in the circuit to make the code more compact and easier to understand.

2024-07-03 15:58 UTC, soranjh commented on demonstrations/tutorial_intro_qrom.py
> +# for enhanced performance and scalability. Numerous studies demonstrate the efficacy of these methods in improving
You mention several studies but cite only one. You can simply say that these methods improve state prep and cite the ref.

2024-07-03 15:58 UTC, soranjh commented on demonstrations/tutorial_intro_qrom.py
> +# .. [#unary]
Seems like a duplication of the first one.

2024-07-03 17:55 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qrom.py
> +bitstrings = ["01", "11", "11", "00", "01", "11", "11", "00"]
Based on [this comment](https://github.com/PennyLaneAI/qml/pull/1123#discussion_r1649006413)

In text it would be a very large example (with 8 items) and in code it is too small (4 items) to visualize it

2024-07-03 18:28 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qrom.py
> +# Let's look at an example by assuming we want to load in the target wires the bitstring with
These are the operators that generate the bitstrings. I can change it to U_i for consistency. Would it be better?

2024-07-04 14:36 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qrom.py
> +@partial(qml.devices.preprocess.decompose,
Since Soran found it confusing as well, I have removed the drawing part

2024-07-04 23:27 UTC, EmilianoG-byte reviewed
Great demo! 🤩  Just left some comments here and there regarding clarity of the text, and particularly on the qubit reuse section.

2024-07-04 23:27 UTC, EmilianoG-byte commented on demonstrations/tutorial_intro_qrom.py
> +#       |c\rangle |r\rangle |b_{c0}\rangle \dots |+\rangle_r \dots |b_{cR}\rangle
Were we introduced to what big `R` is?

2024-07-04 23:27 UTC, EmilianoG-byte commented on demonstrations/tutorial_intro_qrom.py
> +# 1. **We start by generating the uniform superposition on the r-th register**. To do this, we put the Hadamard in the target wires and moved it to the :math:`r` -row with the swap block.
I think what is confusing for me is that the register `r` is called the same as the `r` row in the work wires 🤔

2024-07-04 23:27 UTC, EmilianoG-byte commented on demonstrations/tutorial_intro_qrom.py
> +# 1. **We start by generating the uniform superposition on the r-th register**. To do this, we put the Hadamard in the target wires and moved it to the :math:`r` -row with the swap block.
I think I get the idea that the value of the `r` register will determine the specific row on which the superposition is created, but then maybe we can differentiate the name of the row-register and its value

2024-07-04 23:27 UTC, EmilianoG-byte commented on demonstrations/tutorial_intro_qrom.py
> +# 1. **We start by generating the uniform superposition on the r-th register**. To do this, we put the Hadamard in the target wires and moved it to the :math:`r` -row with the swap block.
```suggestion
# 1. **We start by generating the uniform superposition on the r-th register of the work wires**. To do this, we put the Hadamard in the target wires and move it to the :math:`r` -row with the swap block.
```

2024-07-04 23:27 UTC, EmilianoG-byte commented on demonstrations/tutorial_intro_qrom.py
> +# 1. **We start by generating the uniform superposition on the r-th register**. To do this, we put the Hadamard in the target wires and moved it to the :math:`r` -row with the swap block.
I think is worth emphasizing here that the specific row :math:`r` is determined by the binary representation of the row-register in the control wires. As mentioned in my comment above, I think it might be useful to make a distinction between the name of these two registers (the one controlling the row, and the actual row in the work wires)

2024-07-04 23:27 UTC, EmilianoG-byte commented on demonstrations/tutorial_intro_qrom.py
> +# 3. **We apply the Hadamard's in r-th register.** The two swap blocks and the Hadamard gate in target wires achieve this.
```suggestion
# 3. **We apply the Hadamard's in r-th register of the work wires.** The two swap blocks and the Hadamard gate in target wires achieve this.
```

2024-07-05 20:07 UTC, EmilianoG-byte commented on demonstrations/tutorial_intro_qrom.py
> +# 3. **We apply the Hadamard's in r-th register of the work wires.** The two swap blocks and the Hadamard gate in target wires achieve this.
```suggestion
# 3. **We apply the Hadamard's to the  r-th register of the work wires.** The two swap blocks and the Hadamard gate applied to the target wires achieve this.
```

2024-07-05 20:44 UTC, EmilianoG-byte commented on demonstrations/tutorial_intro_qrom.py
> +# control qubits of the swap block are used to specify the row index :math:`r`.
Do you think it's worth showcasing the relation:

$2^{len(r)} \times 2^{len(c)} = N$ 

to emphasize that together with the columns and dimensions we want to be able to reach the $N$ different $b_i$'s?

2024-07-05 20:44 UTC, EmilianoG-byte commented on demonstrations/tutorial_intro_qrom.py
> +# control qubit (i.e., :math:`r`) is a :math:`|1\rangle`, it will activate the swap block, generating the state :math:`|101\rangle|11\rangle|01\rangle`
```suggestion
# control qubit (i.e., :math:`|r\rangle`) is a :math:`|1\rangle`, it will activate the swap block, generating the state :math:`|101\rangle|11\rangle|01\rangle`
```

to make it consistent with the labels in the diagram

2024-07-05 20:44 UTC, EmilianoG-byte commented on demonstrations/tutorial_intro_qrom.py
> +#       |c\rangle |r\rangle |b_{c0}\rangle_0 |b_{c1}\rangle_1 \dots |+\rangle_r \dots |b_{c(R-1)}\rangle_{R-1}
Initially this notation (with the additional sub indices) seems a bit loaded, but IMO it makes it easier to follow the transformation of the registers after each step

2024-07-05 21:11 UTC, EmilianoG-byte commented on demonstrations/tutorial_intro_qrom.py
> +control_wires = [0, 1, 2]
To make a parallel with the explanation in the text, one can also divide the control wires as:

```suggestion
column_wires = [0,1]
row_wires = [2]
control_wires = column_wires + row_wires
```

2024-07-05 21:25 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qrom.py
> +control_wires = [0, 1, 2]
Good idea! However I'll leave it as it is because I hope the demo will help people to know how to use the template (and that would not be the expected use)

2024-07-05 21:27 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qrom.py
> +# control qubits of the swap block are used to specify the row index :math:`r`.
Let me see if I can fit it in somewhere

2024-07-08 18:39 UTC, soranjh commented on demonstrations/tutorial_intro_qrom.py
> +bitstrings = ["01", "11", "11", "00", "01", "11", "11", "00"]
This is what the comment suggests:
QROM |00> |00> = |00>|11>
QROM |01> |00> = |01>|01>
QROM |10> |00> = |10>|11>
QROM |11> |00> = |11>|00>

But the demo has:

QROM |00> |000> = |00>|011>

2024-07-17 14:23 UTC, austingmhuang commented on demonstrations/tutorial_intro_qrom.py
> +where :math:`|b_i\rangle` is the bitstring associated with the :math:`i`-th computational basis and :math:`m` is the length of the bitstrings. We have assumed all the bistrings are of equal length.
```suggestion
where :math:`|b_i\rangle` is the bitstring associated with the :math:`i`-th computational basis and :math:`m` is the length of the bitstrings. We have assumed all the bitstrings are of equal length.
```
Typo

2024-07-22 18:56 UTC, ixfoduap requested changes
Overall this looks great, but the explanation of the SelectSwap construction, arguably the most important part of the demo, needs to be improved as it is currently not very clear

2024-07-22 18:56 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +You will also see how easy it is to use this operator in PennyLane through the :class:`~.pennylane.QROM` template.
```suggestion
You will also see how easy it is to use this operator in PennyLane using the :class:`~.pennylane.QROM` template.
```

2024-07-22 18:56 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +The QROM is an operator that allows us to load classical data into a quantum computer. Data is represented as a collection of bitstrings (list of 0s and 1s) that we denote by :math:`b_0, b_2, \ldots,
```suggestion
The QROM is an operator that allows us to load classical data into a quantum computer. Data is represented as a collection of bitstrings (list of 0s and 1s) that we denote by :math:`b_0, b_1, \ldots, b_{N-1}`. The QROM operator is then defined as:
```
ATTENTION TO DETAILS! How did multiple reviewers miss this?

2024-07-22 18:56 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +qubits (:math:`3 = \log_2 8`) and the target register of two qubits (e.g., :math:`m = 2`). For instance, for the
```suggestion
qubits (:math:`3 = \log_2 8`) and the target register of two qubits (:math:`m = 2`). For instance, for the
```

2024-07-22 18:56 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +     \text{QROM}|011\rangle|00\rangle &= |011\rangle|00\rangle
```suggestion
     \text{QROM}|011\rangle|00\rangle &= |011\rangle|00\rangle.
```

2024-07-22 18:56 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +Then the unitaries :math:`U_i` can be simply :math:`X` gates that determine whether each bit is a :math:`0` or a :math:`1` satisfying:
```suggestion
Then the unitaries :math:`U_i` can be simply products of :math:`X` gates satisfying:
```
Your previous wording made it sound like the U_i are themselves X gates, which is not the case

2024-07-22 18:56 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +We use :class:`~.pennylane.BasisEmbedding` as a useful template for preparing bitstrings, it places the :math:`X` gates
In light of the upcoming changes to state preparation, do we still want to use basis embedding here?

2024-07-22 18:56 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +in the right position. Let's see how it could be implemented:
```suggestion
We use :class:`~.pennylane.BasisEmbedding` as a useful template for implementing the gates :math:`U_i`. Let's see how it could be written in code:
```

2024-07-22 18:56 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +@partial(qml.devices.preprocess.decompose,
Any way we can expand the BasesEmbedding blocks to show the X gates instead? Because that would be better

2024-07-22 18:56 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +# Nice, the outputs match the elements of our initial data list: :math:`[01, 11, 11, 00, 01, 11, 11, 00]`.
```suggestion
# The outputs match the elements of our initial data list: :math:`[01, 11, 11, 00, 01, 11, 11, 00]`. Nice!
```
Just a suggestion

2024-07-22 18:56 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +
I find this a bit random here at the beginning without any explanation. Consider moving it to a later part after the main explanation

2024-07-22 18:56 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +# Let's look at an example by assuming we want to load in the target wires the bitstring with
This explanation is indeed not very clear. @KetpuntoG You can do better! Take another look and figure out how to explain this more clearly

2024-07-22 18:56 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +# The QROM template will put as many rows as possible using the ``work_wires`` we pass.
Good place for another code block showing how to implement it. For this code, it would be good to see a circuit diagram from the code that matches the schematic one in the drawing

2024-07-22 18:56 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +# been returned to state :math:`|00\rangle`. This can cause unwanted behaviors but in PennyLane can be easily solved
```suggestion
# been returned to state :math:`|00\rangle`. This can cause unwanted behaviors, but in PennyLane can be easily solved
```

2024-07-22 18:56 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +# Great! To achieve this, we have followed the technique shown in [#cleanQROM]_ where the proposed circuit is as follows:
```suggestion
# Great! We confirm that all the work wires have been reset. To achieve this, we have followed the technique shown in [#cleanQROM]_ where the proposed circuit is as follows:
```

2024-07-22 18:56 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +# where :math:`R` the number of rows. To see how this circuit works, let's suppose we want to load the bitstring :math:`b_{cr}` in the target wires, where :math:`b_{cr}`
```suggestion
# where :math:`R` is the number of rows. To see how this circuit works, let's suppose we want to load the bitstring :math:`b_{cr}` in the target wires, where :math:`b_{cr}`
```

2024-07-22 18:56 UTC, ixfoduap commented on demonstrations/tutorial_intro_qrom.py
> +# indispensable tool for developing new algorithms and an interesting field for further study.
```suggestion
# state preparation [#StatePrep]_ techniques. After all, state preparation is a special case of data encoding, where the data are the coefficients that define the state.
# As the availability of qubits increases, QROM methods will become more attractive as a practical due to their superior asymptotic efficiency. 
# This makes them an indispensable tool for developing new algorithms.
```

2024-07-23 10:46 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qrom.py
> +We use :class:`~.pennylane.BasisEmbedding` as a useful template for preparing bitstrings, it places the :math:`X` gates
I will be able to upgrade it to `BasisState`, although `BasisEmbedding` will still exist as an alias for `BasisState`

2024-07-23 10:50 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qrom.py
> +
The objective of this change is that the user who simply wants to learn how to use it, does not get lost with the theory. Let me see how I can readjust it

2024-07-23 10:54 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qrom.py
> +@partial(qml.devices.preprocess.decompose,
Ok, I will update it with an example so the number 3 is encoded with two PauliX gates

2024-08-30 18:20 UTC, gmlejarza commented on demonstrations/tutorial_intro_qrom.py
> +#       |c\rangle |r\rangle |b_{cr}\rangle |0\rangle \dots |0\rangle_r \dots |0\rangle.
I get the general idea of applying Hadamard gates and then a combination of controlled SWAPs and SELECT blocks to make sure the work_wires are cleaned. However, I really think an example after this could be great to fully grasp everything that is going on, because the math is not trivial. Maybe you can even use the same example as in the previous section, so everything is more self-contained. Usually, what I like about Pennylane demos is that after a very technical explanation, from which I understand let's say 50-70%, there's a particular example, and after going through the example, I can go back to the technical explanation and understand up to 90-100%.

2024-09-04 20:54 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qrom.py
> +#       |c\rangle |r\rangle |b_{cr}\rangle |0\rangle \dots |0\rangle_r \dots |0\rangle.
I hope that with the clarifications in the previous section now it is easier to follow

2024-09-04 20:54 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qrom.py
> +# is the bitstring whose operator :math:`U` is placed in the c-th column and r-th row in the two dimensional representation shown in the Select block.
Added an extra image

2024-09-04 23:07 UTC, josh146 commented
@KetpuntoG I think this can be changed to merge into the `master` branch now

2024-09-05 00:11 UTC, KetpuntoG commented
> @KetpuntoG I think this can be changed to merge into the `master` branch now

This includes a lot of changed files  and can complicate the review. 
I will wait for Juan Miguel's review and then I will make the change to master to avoid problems
Do you know of a way to rebase and not modify extra files @josh146 ?

2024-09-05 19:06 UTC, KetpuntoG commented
Reopened only to continue the review here

2024-09-05 19:08 UTC, mudit2812 commented
> > @KetpuntoG I think this can be changed to merge into the `master` branch now
> 
> This includes a lot of changed files and can complicate the review. I will wait for Juan Miguel's review and then I will make the change to master to avoid problems Do you know of a way to rebase and not modify extra files @josh146 ?

This might require some fancy git commands. I don't have any suggestions other than using stack overflow or other forums/tools of the sort.

2024-09-06 14:21 UTC, closed without merging