Update old Codebook links and mentions on pennylane.ai
PennyLaneAI/qml pull request #1138
Opened 2024-06-21 09:15 UTC by ikurecic

As described in Shortcut.

Note that this update does not include the following:
* tutorial_apply_qsvt (node not yet available)
* tutorial_fermionic_operators (node not yet available)
* tutorial_teleportation (node not yet available)

2024-06-21 14:21 UTC, justinpickering approved these changes
LGTM - thanks for making these changes @ikurecic !

2024-06-24 14:09 UTC, alvaro-at-xanadu requested changes
Thank you @ikurecic Just a few things that I noticed here!

2024-06-24 14:09 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
>  algorithm, proposed by Lov Grover [#Grover1996]_. In the original description, the author approaches the
This link doesn't seem to do anything except taking you to the codebook (anchor doesn't seem to work?) Maybe I'd remove this link altogether, since the codebook is cited throughout anyways.

2024-06-24 14:09 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
>  #
https://youtu.be/EfUfwVnicP8?si=Qnzl0gU7hfKCC-Bn is the PennyLaneAI video, the current link takes you to the XanaduAI channel

2024-06-24 14:09 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
>  #
Let's remove this link. Amplitude Amplification is, unfortunately, used for two things, and the content in this node is not the one being referred to here.

2024-06-24 14:17 UTC, ikurecic commented on demonstrations/tutorial_grovers_algorithm.py
>  algorithm, proposed by Lov Grover [#Grover1996]_. In the original description, the author approaches the
This is interesting and might be a larger issue. Let me see in the QA channel on Slack if it's expected behavior. Thanks.

2024-06-24 14:19 UTC, ikurecic commented on demonstrations/tutorial_grovers_algorithm.py
>  #
Great, thank you. I'm including the full link instead.

2024-06-24 15:28 UTC, ikurecic commented on demonstrations/tutorial_grovers_algorithm.py
>  algorithm, proposed by Lov Grover [#Grover1996]_. In the original description, the author approaches the
Let's leave it like this — there's no harm, and it is likely to get updated to work.

2024-06-24 15:48 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
>  algorithm, proposed by Lov Grover [#Grover1996]_. In the original description, the author approaches the
Sounds good

2024-06-24 15:49 UTC, alvaro-at-xanadu approved these changes
LGTM 🚀 ! Thanks!

2024-06-24 16:08 UTC, merged