[WIP] How to use wire registers
PennyLaneAI/qml pull request #1167
Opened 2024-07-23 18:05 UTC by austingmhuang

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Remember to do a grammar check of the content you include.
- [ ] All tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**
How to use wire registers

**Summary:**
Describes how to use wire registers using two different examples

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**
[sc-67898]

----
If you are writing a demonstration, please answer these questions to facilitate the marketing process.

* GOALS — Why are we working on this now? Promote new PL feature - wire registers

* AUDIENCE — Who is this for? People who implement quantum algorithms

* KEYWORDS — What words should be included in the marketing post? Quantum Registers

* Which of the following types of documentation is most similar to your file? 
(more details [here](https://www.notion.so/xanaduai/Different-kinds-of-documentation-69200645fe59442991c71f9e7d8a77f8))
    
- [ ] Tutorial
- [ ] Demo
- [x] How-to

2024-07-24 14:01 UTC, soranjh commented on demonstrations/tutorial_how_to_use_registers.py
> +# Finally, we apply the Hadamard gate to our ancilla qubit once again, and measure in the Z basis.
Not sure if the step-by-step building is necessary. The circuit is simple and can be built in one step.

2024-07-26 19:36 UTC, austingmhuang commented on demonstrations/tutorial_how_to_use_registers.py
> +def swap_test():
Discussed in person: basically it is useful if you want to modify the wires frequently, otherwise no, not really.

2024-07-26 19:36 UTC, austingmhuang commented on demonstrations/tutorial_how_to_use_registers.py
> +# Finally, we apply the Hadamard gate to our ancilla qubit once again, and measure in the Z basis.
Done in 1 step now instead

2024-07-26 19:38 UTC, austingmhuang commented on demonstrations/tutorial_how_to_use_registers.metadata.json
> +    "dateOfLastModification": "2024-07-23T00:00:00+00:00",
```suggestion
    "dateOfPublication": "2024-07-26T00:00:00+00:00",
    "dateOfLastModification": "2024-07-26T00:00:00+00:00",
```
Update on merge.

2024-07-29 16:46 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_registers.py
> +# Finally, let's define our Hamiltonian. We'll choose the H2 molecule for simplicitiy, but feel
In fact, you may want to use spin Hamiltonians from the datasets

2024-07-29 16:48 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_registers.py
> +    return qml.probs(wires=estimation)
As I said before, I suggest removing. This is how to use registers demo, not a wires vs registers demo

2024-07-29 16:51 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_registers.py
> +# we expect. This should give an eigenvalue of about -1.1359091600247835, which is close to the
It's not clear how you are converting from values of the estimation register to eigenvalues. I suggest you just don't execute the circuit. Also, that's too many decimal places, especially after using "about" in front

2024-07-29 16:52 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_registers.py
> +# algorithm. For example, changing the number of wires in your estimation register is very easy
```suggestion
# Changing the number of wires in your estimation register is very easy
```

2024-07-29 16:52 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_registers.py
> +control = range(14, 18)  # change 12 to 14, 16 to 18
```suggestion

```

2024-07-29 16:53 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_registers.py
> +# bigger and more complex algorithms, this can quickly become a serious issue!
```suggestion
# The complexity of wire management only gets more difficult as you start working with more
# and more registers. As you start building
# bigger and more complex algorithms, this can quickly become a serious issue!
```

2024-07-29 16:54 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_registers.py
> +# wire registers and use them to implement quantum algorithms.
```suggestion
# Wire registers provide a neat way of organizing and managing wires. Often, algorithms are
# described as acting upon registers and sub-registers; using wire registers can greatly
# streamline the implementation from theory to code. In this demo, we showed how to construct
# wire registers and use them to implement quantum algorithms.
```

2024-07-29 18:34 UTC, austingmhuang commented on demonstrations/tutorial_how_to_use_registers.py
> +        control=wire_register["estimation"],
No, this is not a typo. Admittedly it is a little confusing... The control in`control=wire_register["estimation"]` is for `qml.ControlledSequence`. In QPE the control qubits are the ones in the estimation register. 

`wire_register["control"]" refers to the control register in qubitization.

2024-08-06 13:14 UTC, isaacdevlugt commented
Hey @austingmhuang! Feel free to tag me for review when you think it's time 👍

2024-08-15 13:04 UTC, soranjh requested changes
The how-to looks good, left some final comments and suggestions.

2024-08-15 13:04 UTC, soranjh commented on demonstrations/tutorial_how_to_use_registers.py
> +    # Initialize state register to Hartree-Fock State
```suggestion
    # Initialize state register to initial state
```

2024-08-16 20:24 UTC, isaacdevlugt requested changes
Thanks @austingmhuang! Nice and to-the-point. I left some suggestions.

When entering a new text block after, say, a code block, there needs to be a line of `#`s to tell sphinx that this is now a text block. I left some suggestions showing what I mean, but you'll have to do so elsewhere 🙂.

2024-08-16 20:24 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_use_registers.py
> +# We'll use `qubitization <https://docs.pennylane.ai/en/stable/code/api/pennylane.Qubitization.html>`_, which means we have to define another "prep" register.
```suggestion
# Let's opt for :func:`qubitization <~.pennylane.Qubitization>`_, which means we have to define another "prep" register.
```

2024-08-16 20:24 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_use_registers.py
> +register = qml.registers({"state": 4, "estimation": 8, "prep": 4})
I think I prefer that we define `register` once with `"prep"` included. The reader might think that it's a bit odd that we defined it twice 🤔

2024-08-16 20:24 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_use_registers.py
> +# PennyLane's `quantum datasets <https://pennylane.ai/datasets/qspin/transverse-field-ising-model>`_,
@DSGuala are there sphinx directives for linking to a dataset? E.g., `:dataset:`blah blah <potato_data>`_

2024-08-16 20:24 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_use_registers.py
> +import pennylane as qml
```suggestion
```

2024-08-16 20:24 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_use_registers.py
> +# overlap with the eigenstate we want the eigenvalue of. In PennyLane code:
```suggestion
# overlap with the eigenstate we want the eigenvalue of.
```

2024-08-16 20:24 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_use_registers.py
> +
If you have auto-format on, it'll add white spaces that we don't want for content (adds extra scroll time). It's annoying, but I have to turn off automatic formatting when I do demos 😅 

```suggestion
```

2024-08-16 20:24 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_use_registers.py
> +
```suggestion
```

2024-08-16 20:24 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_use_registers.py
> +# be very error-prone when using wires. The complexity of wire management only gets more difficult
🤔

2024-08-16 20:24 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_use_registers.py
> +# wire registers and use them to implement quantum algorithms.
```suggestion
# In this demo, we showed how to construct
# wire registers and use them to implement quantum algorithms.
# Wire registers provide a neat way of organizing and managing wires. Often, algorithms are
# described as acting upon registers and sub-registers; using wire registers can greatly
# streamline the implementation from theory to code. 
```

Might be nice to have a call-to-action at the end here telling people to go to the forum (discuss.pennylane.ai) if they have questions 👍

2024-08-17 04:09 UTC, austingmhuang commented on demonstrations/tutorial_how_to_use_registers.py
> +
Ah yeah auto-format was on for this demo. I'll turn it off next time :)

2024-08-17 04:11 UTC, austingmhuang commented on demonstrations/tutorial_how_to_use_registers.py
> +# to the documentation for :func:`~pennylane.registers`.
Do we prefer not to refer people to the documentation?

2024-08-17 04:13 UTC, austingmhuang commented on demonstrations/tutorial_how_to_use_registers.py
> +# product of two input states. It requires one auxiliary qubit and takes two input states :math:`|\psi\rangle`
More like overlap I'd say.

2024-08-17 04:18 UTC, austingmhuang commented on demonstrations/tutorial_how_to_use_registers.py
> +print(swap_test())
Should work now :)

2024-08-28 19:19 UTC, austingmhuang commented on demonstrations/tutorial_how_to_use_registers.py
> +register = qml.registers({"state": 4, "estimation": 8, "prep": 4})
You mean like it's weird to define `register` twice? I guess it is a little weird, but it would also be strange to define register with `prep` immediately without explain that it's used for qubitization... hmm... let me think about this (is this blocking?)

2024-08-28 20:23 UTC, josh146 commented on demonstrations/tutorial_how_to_use_registers.metadata.json
> +    ],
Hey @austingmhuang, since you merged in `dev`, the location of images for demos has changed. See https://github.com/PennyLaneAI/qml/blob/69c55edfba8ab14e05f38d933ba627b805327729/demonstrations/tutorial_initial_state_preparation.metadata.json#L14-L23

2024-08-29 16:03 UTC, soranjh approved these changes
Thanks @austingmhuang, looks good. Left some optional comments and a question.

2024-08-29 16:03 UTC, soranjh commented on demonstrations/tutorial_how_to_use_registers.py
> +    return qml.probs(wires=register["estimation"])
How expensive is to run the circuit? I assume this is the reason for not executing it?

2024-08-29 16:06 UTC, austingmhuang commented on demonstrations/tutorial_how_to_use_registers.py
> +    return qml.probs(wires=register["estimation"])
It is a little expensive. Takes my laptop about 1 or 2 minutes to run, significantly more if you increase the number of wires in the estimation register.

2024-08-29 16:08 UTC, soranjh commented on demonstrations/tutorial_how_to_use_registers.py
> +    return qml.probs(wires=register["estimation"])
Can we decrease the number of qubits and add a sentence explaining we do that for the sake of execution time?

2024-08-29 16:12 UTC, austingmhuang commented on demonstrations/tutorial_how_to_use_registers.py
> +    return qml.probs(wires=register["estimation"])
Yeah I can do that.

2024-08-29 18:38 UTC, isaacdevlugt approved these changes
Nice @austingmhuang! Minor comments :)

2024-08-29 18:38 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_use_registers.py
> +print(nested_register["bob1a"][0])
Very minor, but reduces scroll time 😎 

```suggestion
print(nested_register["alice"], nested_register["bob1a"])

######################################################################
# You can access a specific wire index via its index in a register.

print(nested_register["all_registers"][2], nested_register["bob1a"][0])
```

2024-08-29 18:38 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_use_registers.py
> +# :func:`~.pennylane.registers`.
```suggestion
# For more details on what set operations are supported, refer to the documentation of
# :func:`Wires <~.pennylane.wires.Wires.difference>`_.
```

2024-08-29 18:38 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_use_registers.py
> +    return qml.probs(wires=register["estimation"])
Agree with @soranjh!

2024-08-29 18:38 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_use_registers.py
> +# be very error-prone when using wires. The complexity of wire management only gets more difficult
```suggestion
# Changing the number of wires in your estimation register is very easy with registers, but human errors
# can happen when using wires. The complexity of wire management only gets more difficult
```

2024-08-29 18:46 UTC, austingmhuang commented on demonstrations/tutorial_how_to_use_registers.py
> +print(nested_register["bob1a"][0])
time is money friend

2024-09-03 13:51 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_registers.py
> +            "bob": {"bob1": {"bob1a": 1}, "bob2": 1},
It's weird that bob1 and bob1a are the same wire; makes the nesting redundant. Consider changing please

2024-09-03 13:53 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_registers.py
> +# elements is based on the order of appearance and nestedness. For more details on ordering, refer
Not clear what "order of nestedness" means. Please revise

2024-09-03 13:53 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_registers.py
> +# to the documentation for :func:`~pennylane.registers`.
Add link to the docs. Generally the links to `registers()` are not working for me, so please revise

2024-09-03 13:54 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_registers.py
> +# :func:`Wires <~.pennylane.wires.Wires.difference>`_.
This appears broken to me in the build. Please revise

2024-09-03 13:57 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_registers.py
> +@qml.qnode(dev)
I'm not crazy about an example that performs a SWAP tets on identical states, then also doesn't output exactly 1. Consider changing to a different example

2024-09-03 13:57 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_registers.py
> +# "estimation", or measurement, register and the other is the state register where we apply our
```suggestion
# "estimation" or "measurement" register, and the other is the state register where we apply our
```

2024-09-03 13:58 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_registers.py
> +# but feel free to try this with any other Hamiltonian you want to find the eigenvalues of.
```suggestion
# but feel free to try this with any other Hamiltonian.
```

2024-09-03 13:58 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_registers.py
> +# With this, we can now define our QPE circuit like so:
```suggestion
# With this, we can now define our QPE circuit:
```

2024-09-03 13:59 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_registers.py
> +# algorithms, this can quickly become a serious issue!
```suggestion
# Changing the number of wires in your estimation register is very easy with registers. 
# The complexity of wire management only gets more difficult
# as you start working with more and more registers. As you start building bigger and more complex
# algorithms, this can quickly become a serious issue!
```

2024-09-03 14:00 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_registers.py
> +# can greatly streamline the implementation from theory to code.
```suggestion
# In this demo, we showed how to construct wire registers and use them to implement quantum
# algorithms. Wire registers provide an elegant way of organizing and managing wires. Often, 
# algorithms are described as acting upon registers and sub-registers; using wire registers
# can greatly streamline the implementation from theory to code. 
```

2024-09-03 15:20 UTC, austingmhuang commented on demonstrations/tutorial_how_to_use_registers.py
> +@qml.qnode(dev)
The test is performed on orthogonal states instead, but it won't be exactly 0.5 either due to the floating point error mentioned above.

2024-09-03 16:17 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_registers.py
> +@qml.qnode(dev)
Maybe just print it with a few significant figures so it's rounded up properly?

2024-09-03 16:21 UTC, ixfoduap approved these changes
:shipit:

2024-09-03 17:50 UTC, isaacdevlugt commented
Can be merged when https://github.com/XanaduAI/pennylane.ai-react/pull/1652 is live

2024-09-04 11:15 UTC, ikurecic reviewed
Thank you, @isaacdevlugt and @austingmhuang . I left some comments and suggestions to address today.

2024-09-04 11:15 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_registers.metadata.json
> +            "id": "austin_huang"
@austingmhuang , we need this format here:
```suggestion
            "username": "your_PennyLane_Profile_username"
```
If you don't have a profile yet, please make one on pennylane.ai. It should contain your name, an image and a headline, but adding more information is good.
If you have any questions, you can also ask me on Slack.

2024-09-04 11:15 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_registers.metadata.json
> +    "dateOfLastModification": "2024-07-23T00:00:00+00:00",
tk, dates in suggestion here not correct.

2024-09-04 11:15 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_registers.metadata.json
> +        "Getting Started"
```suggestion
        "Getting Started", "How-to"
```

2024-09-04 11:15 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_registers.metadata.json
> +    ],
tk, I'll fix this for you.

2024-09-04 11:15 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_registers.py
> +algorithms. In this tutorial, we will explore how wire registers are constructed and used
```suggestion
algorithms. In this tutorial, we will explore how you can construct and use wire registers
```

2024-09-04 11:15 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_registers.py
> +algorithms. In this tutorial, we will explore how wire registers are constructed and used
Can you please add a sentence definining the term here?

2024-09-04 11:15 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_registers.py
> +# You can access a specific wire index via its index in a register.
```suggestion
# Accessing a particular register is the same as accessing any element in a dictionary…

print(nested_register["alice"], nested_register["bob1a"])

######################################################################
# …and you can access a specific wire index via its index in a register.
```
So we don't have choppy sentences.

2024-09-04 11:15 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_registers.py
> +# The `SWAP test <https://en.wikipedia.org/wiki/Swap_test>`_
```suggestion
# In this example, we demonstrate how one can implement the swap test with registers.
# The `swap test <https://en.wikipedia.org/wiki/Swap_test>`_
```

2024-09-04 11:15 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_registers.py
> +# -------------------------------------
```suggestion
# A simple example
# ----------------
```
For consistency.

2024-09-04 11:15 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_registers.py
> +# --------------------
```suggestion
# An advanced example
# -------------------
```

2024-09-04 11:15 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_registers.py
> +# by simplifying wire management. In this example, we use :doc:`Quantum Phase Estimation (QPE) </demos/tutorial_qpe>` to
```suggestion
# by simplifying wire management. In this example, we use :doc:`quantum phase estimation (QPE) </demos/tutorial_qpe>` to
```

2024-09-04 11:15 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_registers.py
> +# PennyLane's `quantum datasets <https://pennylane.ai/datasets/qspin/transverse-field-ising-model>`_,
@DSGuala , I would also like to know.

2024-09-04 11:15 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_registers.py
> +# PennyLane's `quantum datasets <https://pennylane.ai/datasets/qspin/transverse-field-ising-model>`_,
```suggestion
# Finally, let's define our Hamiltonian. We'll use the `transverse-field Ising model <https://pennylane.ai/datasets/qspin/transverse-field-ising-model>`_ from
# `PennyLane Datasets <https://pennylane.ai/datasets/>`_,
```

2024-09-04 11:20 UTC, ikurecic commented on _static/demo_thumbnails/opengraph_demo_thumbnails/OGthumbnail_how_to_use_registers.png.png
@isaacdevlugt and @austingmhuang , you can use this images as an in-body image at 70% if you'd like. I would suggest putting it before the first section heading.

2024-09-04 13:35 UTC, DSGuala commented on demonstrations/tutorial_how_to_use_registers.py
> +# PennyLane's `quantum datasets <https://pennylane.ai/datasets/qspin/transverse-field-ising-model>`_,
No, I don't think so. So far we've been linking directly.

2024-09-04 14:19 UTC, isaacdevlugt commented
The blog has been merged and v0.38 is live. So, this demo is ready to go :)

2024-09-04 14:26 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_use_registers.metadata.json
> +    "dateOfLastModification": "2024-07-23T00:00:00+00:00",
```suggestion
    "dateOfPublication": "2024-09-05T00:00:00+00:00",
    "dateOfLastModification": "2024-09-05T00:00:00+00:00",
```

2024-09-04 20:57 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_use_registers.py
> +algorithms. In this tutorial, we will explore how wire registers are constructed and used
```suggestion
A register of wires represents a collection of wires that serves a purpose (e.g., an "estimation" register in the :doc:`quantum phase estimation </demos/tutorial_qpe>`) and abstract away the finer details of running quantum
algorithms. In this tutorial, we will explore how wire registers are constructed and used
```

2024-09-04 21:38 UTC, austingmhuang commented on demonstrations/tutorial_how_to_use_registers.metadata.json
> +            "id": "austin_huang"
Hi @ikurecic,

I made [my profile](https://pennylane.ai/profile/austingmhuang) just now, so I'll just write in `austingmhuang` following "username":

2024-09-04 22:01 UTC, isaacdevlugt commented
Closing and moving to https://github.com/PennyLaneAI/qml/pull/1205

2024-09-04 22:02 UTC, closed without merging