[WIP] Shadow Hamiltonian Simulation
PennyLaneAI/qml pull request #1177
Opened 2024-08-02 11:11 UTC by Qottmann

Shadow Hamiltonian Simulation Rapid demo [sc-70411]

First example / draft

2024-08-02 13:49 UTC, dwierichs reviewed
wow, very nicely put together in this short time @Qottmann 
I left a number of opinionated comments as usual, overall it already reads very fluently except for the bitstring sampling business, and maybe the introduction of the set $S$ in the first place, which could take readers by their hands a little more.

2024-08-02 13:49 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +In common quantum Hamiltonian simulation, we evolve a state vector :math:`|\psi(t)\rangle` according to the Schrödinger equation
Could drop og Schroedinger here for later comparison.

2024-08-02 13:49 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +.. math:: |\rho\rangle = \frac{1}{\sqrt{A}} \begin{pmatrix} \langle O_1 \\ \vdots \\ \langle O_M \rangle \end{pmatrix}
```suggestion
.. math:: |\rho\rangle = \frac{1}{\sqrt{A}} \begin{pmatrix} \langle O_1 \rangle \\ \vdots \\ \langle O_M \rangle \end{pmatrix}
```

2024-08-02 13:49 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +.. math:: (H_S)_{m m'} = -\frac{\text{tr}\left( O_{m'} [H, O_m] \right)}{|| O_{m'} ||^2}.
One of these three equations should not have a - sign I believe?

2024-08-02 13:49 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +:math:`\exp(-i t H)` and encoding the whole process on a quantum computer instead of in classical simulation.
Maybe
```suggestion
:math:`\exp(-i t H)` and encoding the whole process on a quantum computer instead of simulating it classically.
```

2024-08-02 13:49 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +the full Lie algebra :math:`\langle \{ H \} \cup S \rangle_\text{Lie}` to just therequired support of :math:`[H, O_m]`, but conceptually everything else is the same.
```suggestion
the full Lie algebra :math:`\langle \{ H \} \cup S \rangle_\text{Lie}` to just the required support of :math:`[H, O_m]`, but conceptually everything else is the same.
```

2024-08-02 13:49 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +the full Lie algebra :math:`\langle \{ H \} \cup S \rangle_\text{Lie}` to just therequired support of :math:`[H, O_m]`, but conceptually everything else is the same.
Maybe this last point can be made a _bit_ more explicit. It might be nice to mention the invariance property (not with name, just as a criterion for "when am I done finding my set S")

2024-08-02 13:49 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +These abstract concepts are best illustrated with a simple but concrete example.
```suggestion
These abstract concepts are best illustrated with a simple example.
```

2024-08-02 13:49 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +after :math:`t = 1s` and compute the expectation values of :math:`\{X, Y, Z, I \}`.
We might not want to do units? :grimacing: :sweat_smile:

2024-08-02 13:49 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +H_S == H_S.conj().T
Could do a `np.all` around it

2024-08-02 13:49 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +res = np.array(evolve(H, t))
Might be nice to call `res` something explicit like `O_t_standard` or so, because it is used later on to compare to.

2024-08-02 13:49 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +H_S_qubit = qml.pauli_decompose(H_S)
Nice!

2024-08-02 13:49 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# In the first case, the measurement is directly obtained, however, in the shadow Hamiltonian simulation, we need to access the amplitudes of the underlyding state.
```suggestion
# In the first case, the measurement is directly obtained, however, in the shadow Hamiltonian simulation, we need to access the amplitudes of the underlying state.
```

2024-08-02 13:49 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# :math:`p_m = |\langle O_m\rangle|^2`. The ability to sample from such a :math:`p_m = |\langle O_m\rangle|^2` is a unique and new feature to shadow Hamiltonian simulation.
This was not quite clear to me

2024-08-02 13:49 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# Something a bit more involved? I am not sure if this is actually necessary. The above example illustrates the basic concepts already quite nicely and keeps things concise. Happy to hear feedback he
Could do something just to show that the dimensions of the problems differ for larger initial problem formulations with small sets $S$?
On the other hand, if you do correlators below, maybe no need to do this second example?
Or could combine the second example and the correlator part?

2024-08-02 13:49 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# Shadow Hamiltonian simulation is g-sim on a quantum computer.
Nice :D :rofl:

2024-08-02 13:58 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +In common quantum Hamiltonian simulation, we evolve a state vector :math:`|\psi(t)\rangle` according to the Schrödinger equation
drop as in put the schrödinger equation, or drop as in leave out that term? :D

2024-08-02 14:01 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +.. math:: (H_S)_{m m'} = -\frac{\text{tr}\left( O_{m'} [H, O_m] \right)}{|| O_{m'} ||^2}.
yes!

2024-08-02 14:01 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +:math:`\exp(-i t H)` and encoding the whole process on a quantum computer instead of in classical simulation.
updated this whole section

2024-08-02 14:03 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +res = np.array(evolve(H, t))
good point!

2024-08-02 14:06 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# :math:`p_m = |\langle O_m\rangle|^2`. The ability to sample from such a :math:`p_m = |\langle O_m\rangle|^2` is a unique and new feature to shadow Hamiltonian simulation.
So the expectation values that we are interested in in shadow Hamiltonian simulation are encoded in the _state_ of the output quantum circuit. I am trying to describe ways of obtaining them in a realistic setting since `qml.state()` is not a valid quantum computer measurement / outcome

2024-08-02 14:25 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +In common quantum Hamiltonian simulation, we evolve a state vector :math:`|\psi(t)\rangle` according to the Schrödinger equation
Haha, sorry :facepalm: 

The former, i.e., write it out so that the similarity to the shadow Schroedinger equation is yelling at people :)

2024-08-02 14:27 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# :math:`p_m = |\langle O_m\rangle|^2`. The ability to sample from such a :math:`p_m = |\langle O_m\rangle|^2` is a unique and new feature to shadow Hamiltonian simulation.
Ahh, got it! That's interesting! I like the point that this allows to sample from an unconventional probability distribution!

2024-08-02 20:51 UTC, alvaro-at-xanadu reviewed
Minor content things, it's looking super good 🚀 (I understood it, mostly). Will not request changes since I'll be out on Monday, but please look at the suggestions! It'll be great 😃

2024-08-02 20:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +
I think a better summary could be written. I haven't read the other demos, but some self-contained cliff notes would be great.
- Are we given the set $\{g_i\}$ and then wonder what kind of circuits we can generate with them? Then we find the closure of this subset of elements (as a Lie Algebra) to see what kinds of dynamics we can write?
- The structure constant are introduced for no reason, we can (and actually do already) assume knowledge of the adjoint representation
- We can assume the reader knows Lie Algebra concepts here, and refer them to the other demos. E.g, they already know what Lie closure, adjoint representation, etc are, so there's no need to write anything about it. We should be clear about Lie closure notation though.

2024-08-02 20:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +:math:`\langle g_i \rangle` then corresponds then corresponds to evolving :math:`\vec{g}` by :math:`\prod_\ell \exp(-i \thata_\ell \text{ad}_{g_\ell})`.
```suggestion
:math:`\langle g_i \rangle` then corresponds then corresponds to evolving :math:`\vec{g}` by :math:`\prod_\ell \exp(-i \theta_\ell \text{ad}_{g_\ell})`.
```

2024-08-02 20:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +One striking difference is that because
```suggestion
One striking difference is that, because
```

2024-08-02 20:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +we only have one specific "gate", we do not need the full Lie closure of the operators that we want to compute the expectation values of.
```suggestion
we only have one specific "gate", we do not need the full Lie closure of the operators whose expectation values we want to compute.
```

2024-08-02 20:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +we only have one specific "gate", we do not need the full Lie closure of the operators that we want to compute the expectation values of.
Reads better, and English teachers lied to us when they said we couldn't use *whose* with objects.

2024-08-02 20:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +after :math:`t = 1` and compute the expectation values of :math:`\{X, Y, Z, I \}`.
```suggestion
after a time :math:`t = 1` and compute the expectation values of :math:`\{X, Y, Z, I \}`.
```

2024-08-02 20:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +n = 1
What is $n$? Is it ever used?

2024-08-02 20:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# In shadow Hamiltonian simulation, we encode :math:`4` expectation values in a :math:`2^2 = 4` dimensional
Not sure why this whole section is rendering weird (like in a green box)

2024-08-02 20:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +after :math:`t = 1` and compute the expectation values of :math:`\{X, Y, Z, I \}`.
```suggestion
after :math:`t = 1` and compute the expectation values of :math:` S = \{X, Y, Z, I \}`.
```

2024-08-02 20:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +after :math:`t = 1` and compute the expectation values of :math:`\{X, Y, Z, I \}`.
In some way we should make clear that this is the $S$ (as defined above) that we'll be using going forward.

2024-08-02 20:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# We now go on to construct the shadow Hamiltonian :math:`H_S` by means of computing the elements
```suggestion
# We now go on to construct the shadow Hamiltonian :math:`H_S` by computing the elements
```

2024-08-02 20:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# Now the main novelty for shadow Hamiltonian simulation is to perform this on a quantum computer by encoding the
```suggestion
# Now, the main novelty for shadow Hamiltonian simulation is to perform this on a quantum computer by encoding the 
```

2024-08-02 20:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# This can be done by decomposing the numerical matrix :math:`H_S` into Pauli operators, which then in turn can
```suggestion
# This can be done by decomposing the numerical matrix :math:`H_S` into Pauli operators, which in turn can
```

2024-08-02 20:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# We see that the results match with both approaches.
```suggestion
# We see that the results of both approaches match.
```

2024-08-02 20:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# We are making use of the abstract quantum sub-routines :func:`~evolve` and :class:`~StatePrep`, which each warrant their
```suggestion
# We should also note that we made use of the abstract quantum sub-routines :func:`~evolve` and :class:`~StatePrep,` which each warrant their
```

2024-08-02 20:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# by :class:`TrotterProduct`, though that shall not be the focus of this demo.
```suggestion
# by :class:`TrotterProduct`, but that is beyond the scope of this demo.
```

2024-08-02 20:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# by :class:`TrotterProduct`, though that shall not be the focus of this demo.
Shall is future tense but the demo already ended XD

2024-08-02 20:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# We have introduced the basic concepts of shadow Hamiltonian simulation and seen how this fundamentally differs from the common approach to Hamiltonian simulation.
```suggestion
# In this demo, we introduced the basic concepts of shadow Hamiltonian simulation and learned how this fundamentally differs from the common approach to Hamiltonian simulation.
```

2024-08-02 20:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +Instead, here it is sufficient to choose :math:`O_m` such that they support all :math:`[H, O_m]`.
```suggestion
Instead, here it is sufficient to choose :math:`O_m` as the element of the support of :math:`[H, O_m]`.
```

2024-08-02 20:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +Instead, here it is sufficient to choose :math:`O_m` such that they support all :math:`[H, O_m]`.
I didn't really understand what you means with "such that they support." Is this what you mean?

2024-08-02 22:43 UTC, josh146 commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +#
```suggestion
#     `arXiv:2408.00081 <https://arxiv.org/abs/2408.00081>`__, 2024.
#
```

2024-08-02 22:43 UTC, josh146 commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# quantum state, i.e. :math:`n_S = 2`.
```suggestion
# quantum state, i.e., :math:`n_S = 2`.
```

2024-08-02 22:43 UTC, josh146 commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +from which we can read off the matrix elements of :math:`H_S`, i.e.
```suggestion
from which we can read off the matrix elements of :math:`H_S`, i.e.,
```

2024-08-03 08:24 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +
so just scrap the abstract? I'd be fine with that!

2024-08-03 09:09 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +and, in particular simultaneously all absolute values of observables.
Good point about $p_m$! Though I do think it's apt to use "On the other hand," as it is contrasting the previous sentence (see also e.g. [stackexchange](https://ell.stackexchange.com/questions/41619/can-on-the-other-hand-be-used-without-its-on-the-one-hand), our one true source of truth)

2024-08-03 09:13 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +Instead, here it is sufficient to choose :math:`O_m` such that they support all :math:`[H, O_m]`.
Yeah I mean the support in a linear algebra sense, I rephrased the sentence and added a reference to this fact in the derivation above as well

2024-08-03 09:56 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +
The connection to g-sim is a crucial point the demo is trying to make, so I think it's required to be explicit. I rephrased this paragraph and hope it is a bit clear now and explains why I make all these mentions

2024-08-05 08:41 UTC, dwierichs approved these changes
Left some more opinions, just to gather some ideas for the abstract and some very small nitpicky things.

2024-08-05 08:41 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.metadata.json
> +        }
I suppose we don't need to reference the basedOnPapers paper here?
The Aguilar ref is missing though:
```suggestion
        },
        {
            "id": "Aguilar",
            "type": "preprint",
            "title": "Full classification of Pauli Lie algebras",
            "authors": "Gerard Aguilar, Simon Cichy, Jens Eisert, Lennart Bittel",
            "year": "2024",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.2408.00081",
            "url": "https://arxiv.org/abs/2408.00081"
        }
```

2024-08-05 08:41 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +:math:`O_m,` for :math:`m=1,\ldots ,M,` under some unitary evolution.
Maybe
```suggestion
In quantum simulation, the goal is typically to simulate the time evolution of expectation values
of :math:`M` observables :math:`O_m,` for :math:`m=1,\ldots ,M,`.
```

2024-08-05 08:41 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +as there are conditions of completeness for the shadow encoding to succeed (called invariance property in the original paper).
I think it might be nice to state the differences first, without (resource) requirements, and move on to those in a separate paragraph. Maybe something like this:

```suggestion

In quantum simulation, the goal is typically to simulate the time evolution of expectation values of
:math:`M` observables :math:`O_m,` for :math:`m=1,\ldots ,M`.
The common approach is to evolve the wave function :math:`|\psi\rangle` in the Schrödinger picture
and then measure the desired observables.
In shadow Hamiltonian simulation, we instead encode the initial expectation values themselves in a proxy
state—the **shadow state**—and evolve that state instead of :math:`|\psi\rangle`. 
This evolution is defined by a so-called shadow Schrödinger equation [, which combines the Heisenberg picture
with the adjoint representation of Lie algebras.]

In addition to the conceptual differences, shadow Hamiltonian simulation also differs from the common
approach in terms of its (resource) requirements. The dimensionality of the 
shadow system no longer depends on the number of constituents :math:`n` of the system. Instead,
it is dependent on the number of observables :math:`M` that we are interested in. Additionally, we require 
a property from the set of observables :math:`O_m` and the system Hamiltonian that guarantees the shadow
encoding to succeed (this is called invariance property in the original paper).
```

2024-08-05 08:41 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +:math:`p_m = |\langle O_m \rangle|^2` and measure the absolute value of all observables simultaneously.
What do you mean by " measure the absolute value of all observables simultaneously." 
Do you mean that it can happen in one basis? :)

2024-08-05 08:41 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +:math:`p_m = |\langle O_m \rangle|^2` and measure the absolute value of all observables simultaneously.
Not sure whether the requirement that we need to be able to do an almost _arbitrary_ Hamiltonian time evolution on a quantum computer is worth mentioning? It seems like it can easily prevent this algorithm from working, if we don't know how to implemnet H_S?

2024-08-05 08:41 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +In shadow Hamiltonian simulation, we encode a set of expectation values in the amplitudes of a quantum state,
```suggestion
In shadow Hamiltonian simulation, we encode a set of initial expectation values in the amplitudes of a quantum state,
```

2024-08-05 08:41 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +Since the operators under consideration are elements of the vector space of Hermitian operators, we can use that to compute :math:`H_S`.
?
```suggestion
Since the operators under consideration are elements of the vector space of Hermitian operators, we can use this to compute :math:`H_S`.
```

2024-08-05 08:41 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +From this we can readily see that the operators :math:`O_m` need to be chosen such that they support :math:`[H, O_m]`.
```suggestion
From this we can readily see that the operators :math:`O_m` need to be chosen such that they support :math:`[H, O_m]`.
This property is called *invariance property* in the original paper.
```

2024-08-05 08:41 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +[#Somma]_ [#Somma2]_ [#Galitski]_ [#Goh]_, we have operators :math:`\{ g_i \}` that are potential generators or observables for a parametrized quantum circuit,
The "potential" reads a bit funny in my head, I personally would skip it.

2024-08-05 08:41 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +:doc:`demo on g-sim </demos/tutorial_liesim>` that makes extensive use of it.
Note that we do not need to close the set S under commutators, so it is not really the adjoint rep of an algebra, right?

2024-08-05 08:41 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +
I agree with @Qottmann but would agree with @alvaro-at-xanadu that the adjoint rep does not need to be introduced in detail/with formulas. You clearly point to the adjoint rep below, and where to read up on it, in case a reader wants to understand the connection with g-sim in technical detail :)

2024-08-05 08:41 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +:doc:`demo on g-sim </demos/tutorial_liesim>` that makes extensive use of it.
Ah yes, you also say this right below :sweat_smile: So maybe
```suggestion
In particular, :math:`H_S` corresponds to a part of the adjoint representation :math:`\text{ad}_H` of the 
:doc:`dynamical Lie algebra </demos/tutorial_liealgebra>`
:math:`\langle \{ H \} \cup S \rangle_\text{Lie}`. We explain the concept of the adjoint representation in our
:doc:`demo on g-sim </demos/tutorial_liesim>` that makes extensive use of it.
```

2024-08-05 08:41 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +This is a significant difference, as the Lie closure in most cases leads to an exponentially large DLA [#Wiersema]_ [#Aguilar]_.
So nice to ref the Aguilar paper here in addition :100:

2024-08-05 08:41 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# the resulting shadow system is significantly smaller. It may also be noted that having a smaller shadow system may not
```suggestion
# the resulting shadow system is significantly smaller than the original system. It may also be noted that having a smaller shadow system may not
```

2024-08-05 08:41 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# as sampling from the distribution :math:`p_m = |\langle O_m \rangle |^2`.
Is this maybe a "connection" to shadows? In shadows you don't specify your observables in advance, just a class, and then you do random stuff to have a good data set to reproduced those observables. Here, we know the observable set, but we do random sampling when extracting the evolved expectation values :sweat_smile:

2024-08-05 08:41 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# In this demo, we introduced the basic concepts of shadow Hamiltonian simulation and learned how this fundamentally differs from the common approach to Hamiltonian simulation.
```suggestion
# In this demo, we introduced the basic concepts of shadow Hamiltonian simulation and learned how it fundamentally differs from the common approach to Hamiltonian simulation.
```

2024-08-05 08:41 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# This is a tremendous difference as the Lie closure in most cases leads to an exponential amount of operators [#Wiersema]_ [#Aguilar]_.
```suggestion
# This usually makes a tremendous difference as the Lie closure in most cases leads to an exponential amount of operators [#Wiersema]_ [#Aguilar]_.
```

2024-08-05 08:41 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +Let us solve for the matrix elements :math:`(H_S)_{m m'}$.  To do this, recall that a vector :math:`\boldsymbol{v}` can always be decomposed in an orthogonal basis :math:`\boldsymbol{e}_j` via
```suggestion
Let us solve for the matrix elements :math:`(H_S)_{m m'}`.  To do this, recall that a vector :math:`\boldsymbol{v}` can always be decomposed in an orthogonal basis :math:`\boldsymbol{e}_j` via
```

2024-08-05 08:41 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +print(O_t_quantum)
Could print real part only here to simplify visual comparison :)

2024-08-05 08:57 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.metadata.json
> +        }
Yep havent touched the metadata 👍  will add

2024-08-05 09:06 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +In shadow Hamiltonian simulation, we encode a set of expectation values in the amplitudes of a quantum state,
We also encode it throughout the evolution no?

2024-08-05 09:11 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# as sampling from the distribution :math:`p_m = |\langle O_m \rangle |^2`.
you can use classical shadows to estimate the expectation values of shadow hamiltonian simulation lol 
but i wouldnt say that's a connection

2024-08-05 09:17 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +print(O_t_quantum)
I agree that it would look more sleek but I actually think its a nice little technical detail as the state vector is in general a complex valued vector, whereas the observable meaasurements are by definition real valued

2024-08-05 09:29 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.metadata.json
> +    "basedOnPapers": ["arxiv:2407.21775"],
@josh146 for some reason this paper actually doesnt have a arxiv doi (perhaps this is opt out?)
What best to put here?

2024-08-05 09:31 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.metadata.json
> +    "basedOnPapers": ["arxiv:2407.21775"],
just realized that the canonical doi link still works though so put that doi.org/10.48550/arXiv.2407.21775

2024-08-05 09:55 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +as there are conditions of completeness for the shadow encoding to succeed (called invariance property in the original paper).
I've rewritten it a bit again. I think the main conceptual difference is highlighted in the first paragraph "In shadow Hamiltonian simulation, we instead directly encode..." and then I list the differences, of which the dimensionality is an important factor. I added the side sentence that the underlying state can in fact be infinite dimensional, which is quite a significant difference and cool

2024-08-05 09:56 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +:doc:`demo on g-sim </demos/tutorial_liesim>` that makes extensive use of it.
> so it is not really the adjoint rep of an algebra, right?

Not quite, but the mathematical definition is the same. I didnt want to get into calling this a pseudo-adjoint repr and just figured it'd be fine to make the general connection to the adjoint repr and then specify that the full thing is not needed and we can just use a subset of that 🤔

2024-08-05 10:41 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +as there are conditions of completeness for the shadow encoding to succeed (called invariance property in the original paper).
Oh yeah, that is very cool! I did not intend for the suggestion to go in as is, just wanted to put some ideas. So I'm happy with this! :)

2024-08-05 10:42 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +:math:`p_m = |\langle O_m \rangle|^2` and measure the absolute value of all observables simultaneously.
> Yeah you can simultaneously measure all by sampling in the Z basis according to no?

Yeah, it's a bit funky because we need the full tomography as you stated, but I agree regarding the basis change :)

2024-08-05 10:44 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +:math:`p_m = |\langle O_m \rangle|^2` and measure the absolute value of all observables simultaneously.
>I think this is kind of the premise here, that problem exists in either case. If anything, it'd be worth mentioning that it may be non-trivial to translate into a qubit basis, but also that is better explained later in the code example when doing the translation. In the examples in the paper they do those things analytically, I'm brute-forcing it with qml.pauli_decompose. It's hard to make a general statement

Ah I see, thanks for the explanation! :) 
Yeah, sounds fair not to mention this detailed fine print at this point :)

2024-08-05 10:45 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +:doc:`demo on g-sim </demos/tutorial_liesim>` that makes extensive use of it.
I understand. I think it might be nice to leave whichever small indication that the full rep is not needed at this point already, in order to avoid
- confusion
- people stopping here, thinking that things are not efficient for large DLAs
:thinking:

2024-08-05 10:49 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.metadata.json
> +    "basedOnPapers": ["arxiv:2407.21775"],
>for some reason this paper actually doesnt have an arxiv doi 

Just out of curiosity, where do you not see the DOI link? For me the page of the preprint looks like this, with the DOI above "submission history":
![image](https://github.com/user-attachments/assets/0ac5ff2b-76ca-42f3-9b77-f1b181a85afb)

2024-08-05 11:13 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +:doc:`demo on g-sim </demos/tutorial_liesim>` that makes extensive use of it.
yeah good point! will incorporate!

2024-08-05 11:14 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.metadata.json
> +    "basedOnPapers": ["arxiv:2407.21775"],
Very odd 🤔 
<img width="1162" alt="image" src="https://github.com/user-attachments/assets/43321993-4fff-4c05-a9f3-72e881e8e405">

2024-08-05 11:15 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.metadata.json
> +    "basedOnPapers": ["arxiv:2407.21775"],
Seems to be a firefox thing, on safari I see the link, sorry for the confusion and nevermind the thread 🙃

2024-08-05 11:18 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +
Counter proposal in the exact opposite direction 😆:
I give actually more details, in particular the explicit definition for the structure constants that makes that connection more evident. I think seeing that connection directly would be super nice aha-moment and take away from the demo. I'm gonna push an updated version doing that.

2024-08-05 14:24 UTC, isaacdevlugt requested changes
Nice @Qottmann! Crazy that you can churn these out so fast 🐎. Tag me for re-review as soon as you can and I won't be a blocker 😁

2024-08-05 14:24 UTC, isaacdevlugt commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# In shadow Hamiltonian simulation, we encode :math:`4` expectation values in a :math:`2^2 = 4` dimensional
Lol this is super weird. I suggested deleting the line-break at the top of this text cell and added some line-breaks after other text cells, but if that doesn't fix it, I would notify Ivana to see if we can make a ticket for this?

2024-08-05 14:24 UTC, isaacdevlugt commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# always be its sole purpose, as there are conceptually new avenues one can explore with shadow Hamiltonian simulation such
This also seems to be in a smaller font size???

2024-08-05 14:24 UTC, isaacdevlugt commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# We should also note that we made use of the abstract quantum sub-routines :func:`~.pennylane.evolve` and :class:`~.pennylane.StatePrep` which each warrant their
```suggestion
# We should also note that we made use of the abstract quantum sub-routines :func:`~.pennylane.evolve` and :class:`~.pennylane.StatePrep`, which each warrant their
```

2024-08-05 14:24 UTC, isaacdevlugt commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# We have seen how classical Hamiltonian simulation is tightly connected to g-sim, but run on a quantum computer.
```suggestion
# We have seen how classical Hamiltonian simulation is tightly connected to g-sim, but runs on a quantum computer.
```

2024-08-05 14:24 UTC, isaacdevlugt commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# which allows us to just look at the support of :math:`[H, O_m]`, instead of the full Lie closure.
```suggestion
# A significant difference comes from the fact that the authors in [#SommaShadow]_ specifically look at Hamiltonian simulation, :math:`\exp(-i t H)`,
# which allows us to just look at the support of :math:`[H, O_m]`, instead of the full Lie closure.
```

2024-08-05 14:24 UTC, isaacdevlugt commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# This usually makes a tremendous difference as the Lie closure in most cases leads to an exponential amount of operators [#Wiersema]_ [#Aguilar]_.
```suggestion
# This usually makes a tremendous difference, as the Lie closure leads to an exponential amount of operators, in most cases [#Wiersema]_ [#Aguilar]_.
```

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.metadata.json
> +    "dateOfLastModification": "2024-06-18T00:00:00+00:00",
Leave this unresolved, we don't want to accidentally forget.

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.metadata.json
> +    "title": "Shadow Hamiltonian Simulation",
```suggestion
    "title": "Shadow Hamiltonian simulation",
```

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.metadata.json
> +            "uri": "/_static/large_demo_thumbnails/shadow_hamiltonian_simulation_large_thumbnail.png"
TK
I'll update later

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.metadata.json
> +    "seoDescription": "Shadow Hamiltonian Simulation",
@Qottmann This is worth expanding into a sentence.

I'm also wondering if it might be worth it to explicitly refer to the paper?

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +
Remove the 'Introduction' subtitle below and put the figure after the second paragraph, at width 70%.

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +The common approach is to evolve the wave function :math:`|\psi\rangle` and then measure the desired observables after the evolution.
```suggestion
of :math:`M` observables :math:`O_m,` for :math:`m=1,\ldots ,M,`, and the common approach is to evolve the wave function :math:`|\psi\rangle` and then measure the desired observables after the evolution.
```

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +shadow system no longer depends on the number of constituents :math:`n` of the system. In fact, the underlying state can be mixed or even infinite dimensional.
```suggestion
shadow system no longer depends on the number of constituents, :math:`n`, of the system. In fact, the underlying state can be mixed or even infinite-dimensional.
```
Or put the n at the end of the sentence, after a comma.
Also, either hyphen or use 'infinitely'.

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +(there are conditions of completeness for the shadow encoding to succeed, called invariance property in the original paper).
```suggestion
Instead, the shadow system's size is dependent on the number of observables :math:`M` that we are interested in.
(In the original paper [#SommaShadow]_ there are conditions of completeness for the shadow encoding to succeed, called the invariance property.)
```

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +We will also see later how shadow Hamiltonian simulation comes down to :doc:`g-sim </demos/tutorial_liesim>`,
No fancy g?

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +a Lie algebraic classical simulation tool, but run on a quantum computer with some simplifications due to considering specifically Hamiltonian simulation.
```suggestion
a Lie-algebraic classical simulation tool, but run on a quantum computer with some simplifications that arise due to considering specifically Hamiltonian simulation.
```

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +-----------------------------
Do you want to give this a more specific heading? Like...
```suggestion
Shadow Hamiltonian simulation — Definition
------------------------------------------
```

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +The shadow state evolves according to its shadow Schrödinger equation
```suggestion
The shadow state evolves according to its shadow Schrödinger equation:
```

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +they support :math:`[H, O_m]`. In the paper this is called the **invariance property**.
Something missing in the sentence, not sure what exactly you wanted to say here. But "such that they support _commutator_" does't quite do it for me.

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +How this relates to g-sim
Fancy g?

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +In :doc:`g-sim </demos/tutorial_liesim>`
Fancy g y/n? Might be worth replacing-all so I don't add comments for each.

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +[#Somma]_ [#Somma2]_ [#Galitski]_ [#Goh]_, we have operators :math:`\{ g_i \}` that are generators or observables for a parametrized quantum circuit,
Whoosh, why a million references? Why not just leave it at the link to the Demo?

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +:math:`\mathfrak{g} = \langle \{ g_i \} \rangle_\text{Lie} = \{ g_1, .., g_{|\mathfrak{g}|} \}` of the circuit as well as
```suggestion
For that, we are looking at the so-called dynamical Lie algebra (DLA) of the circuit,
:math:`\mathfrak{g} = \langle \{ g_i \} \rangle_\text{Lie} = \{ g_1, .., g_{|\mathfrak{g}|} \}`, as well as
```

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +after a time :math:`t = 1` and compute the expectation values of :math:`S = \{X, Y, Z, I \}`.
```suggestion
after a time :math:`t = 1` and computing the expectation values of :math:`S = \{X, Y, Z, I \}`.
```

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# We evolved a :math:`2^n = 2` dimensional quantum state and performed :math:`3` independent measurements (non-commuting).
```suggestion
# We evolved a :math:`2^n = 2` dimensional quantum state and performed :math:`3` independent (non-commuting) measurements.
```

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# In shadow Hamiltonian simulation, we encode :math:`4` expectation values in a :math:`2^2 = 4` dimensional
This is truly weird. Is the repository haunted? Something looks really odd with the following 'paragraphs', as well.

@Qottmann , can you give it a kick and figure out what's going wrong here? I'm not seeing it right away.

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# In shadow Hamiltonian simulation, we encode :math:`4` expectation values in a :math:`2^2 = 4` dimensional
Also
```suggestion
# In shadow Hamiltonian simulation, we encode :math:`4` expectation values in a :math:`2^2 = 4`-dimensional
```

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# always be its sole purpose, as there are conceptually new avenues one can explore with shadow Hamiltonian simulation such
```suggestion
# always be its sole purpose, as there are conceptually new avenues one can explore with shadow Hamiltonian simulation, such
```

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +Shadow Hamiltonian simulation is a new approach to quantum simulation on quantum computers [#SommaShadow]_.
Do you want to be cheeky here and explicitly say "(published last week)" or something of the sort? I think it would hit nicely.

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +O_0
![image](https://github.com/user-attachments/assets/024dfa9f-76eb-4006-a28f-baa1e54dd3af)
A choice. 🥰

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# :class:`~.pennylane.StatePrep`.
```suggestion
# There is a variety of methods to encode this vector in a qubit basis, but we will just be using
# :class:`~.pennylane.StatePrep` later.
```
To remove some of the repetition.

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# We again make use of the :meth:`~.pennylane.pauli.PauliSentence.trace` method.
```suggestion
# :math:`(H_S)_{m m'} = \frac{\text{tr}\left( O_{m'} [H, O_m] \right)}{|| O_{m'} ||^2}`, and
# we again make use of the :meth:`~.pennylane.pauli.PauliSentence.trace` method.
```

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# This can be done by decomposing the numerical matrix :math:`H_S` into Pauli operators, which in turn can
```suggestion
# This can be done by decomposing the numerical matrix :math:`H_S` into Pauli operators, which can, in turn,
```

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# by :class:`TrotterProduct`, though that shall not be the focus of this demo.
Agreed.

2024-08-05 14:31 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# This usually makes a tremendous difference as the Lie closure in most cases leads to an exponential amount of operators [#Wiersema]_ [#Aguilar]_.
Can you include some of these thoughts in the very opening? I wasn't sold on this by reading the intro paragraphs, because you explained what it was, but didn't straight away tell me why it was cool or why I should care.

2024-08-05 14:46 UTC, josh146 commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +Shadow Hamiltonian simulation is a new approach to quantum simulation on quantum computers [#SommaShadow]_.
The only problem is that this will go out of date relatively quickly. I suggest we do this with the marketing copy, but not the demo copy 🤔

2024-08-05 15:45 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.metadata.json
> +    "seoDescription": "Shadow Hamiltonian Simulation",
good call will add 👍

2024-08-05 15:54 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +We will also see later how shadow Hamiltonian simulation comes down to :doc:`g-sim </demos/tutorial_liesim>`,
It was just such a pain in headlines and links that I didnt bother in this demo ^^

2024-08-05 15:56 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +[#Somma]_ [#Somma2]_ [#Galitski]_ [#Goh]_, we have operators :math:`\{ g_i \}` that are generators or observables for a parametrized quantum circuit,
Because even though the people that published the g-sim paper and popularized the term last year were not the first to have these ideas, and you gotta give credit where credit is due 🙃

2024-08-05 16:00 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +How does it work, what does it do, and how does it relate to g-sim? All that shall be answered in this quick demo.
lol what version where you looking at? 😅

2024-08-05 16:01 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +We will also see later how shadow Hamiltonian simulation comes down to :doc:`g-sim </demos/tutorial_liesim>`,
"Comes down to" is strong indeed, but I think its fair to say here. This is the same concepts, "just" put on a quantum computer, and using a very specific, single, gate

2024-08-05 16:03 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +they support :math:`[H, O_m]`. In the paper this is called the **invariance property**.
You're not the first confused by this so I'll try to add a little bracket explainer and maybe the link to wikipedia

2024-08-05 16:05 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +with a single, specific gate :math:`U(\theta) = e^{-i \theta H}` and parameter :math:`\theta = t`, and run on a quantum computer.
well "run" as in past participle of "run" for passive form (as in "the algorithm is run on a quantum computer") or "runs" for present form. I'm personally more weirded out by "runs" 😅

2024-08-05 16:05 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +See :doc:`our demo on g-sim </demos/tutorial_liesim>` for further details.
I believe redundancy is good in educational resources :) would leave

2024-08-05 16:09 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +with a single, specific gate :math:`U(\theta) = e^{-i \theta H}` and parameter :math:`\theta = t`, and run on a quantum computer.
.. because in my mind an algorithm is not an entity that actively does something, but is rather something that is run on a (quantum) computer, if that makes sense :D

2024-08-05 16:11 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +We will also see later how shadow Hamiltonian simulation comes down to :doc:`g-sim </demos/tutorial_liesim>`,
could add with a replace all in the end, but would have to double check links etc.

2024-08-05 16:13 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +
I think this is actually super important to make explicit because in the end it was not as obvious as it first seemed

2024-08-05 16:18 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.metadata.json
> +    "dateOfLastModification": "2024-06-18T00:00:00+00:00",
we're pretty set on tomorrow, right? I put that date now 👍

2024-08-05 16:27 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +(there are conditions of completeness for the shadow encoding to succeed, called invariance property in the original paper).
Updated this with an alt text

2024-08-05 16:37 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +they support :math:`[H, O_m]`. In the paper this is called the **invariance property**.
Yeah those links are more misleading than helping so I am going to rephrase that sentence and add a quick example to make clear what is meant, I thought this concept was more widespread

2024-08-05 16:46 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +they support :math:`[H, O_m]`. In the paper this is called the **invariance property**.
Updated this part

2024-08-05 16:46 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +they support :math:`[H, O_m]`. In the paper this is called the **invariance property**.
Updated now 👍

2024-08-05 17:05 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# This usually makes a tremendous difference as the Lie closure in most cases leads to an exponential amount of operators [#Wiersema]_ [#Aguilar]_.
added ✅  also expanded here that because we are encoding stuff in a quantum state an exponentially large DLA is actually not necessarily a problem

2024-08-05 17:06 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# :math:`2^{2n}-1`, so :math:`n_S = 2n` and thus doubling the size number of qubits.
CC @dwierichs checking if you agree if this

2024-08-05 17:50 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# :math:`2^{2n}-1`, so :math:`n_S = 2n` and thus doubling the size number of qubits.
(see updated version)

2024-08-05 20:10 UTC, isaacdevlugt approved these changes
Well done 👨‍🍳 !

2024-08-05 21:55 UTC, josh146 commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# For this specific example, the number of operators is larger than the number of qubits, leading to a shadow system that
```suggestion
##############################################################################
# We evolved a :math:`2^n = 2` dimensional quantum state and performed :math:`3` independent (non-commuting) measurements.
# In shadow Hamiltonian simulation, we encode :math:`4` expectation values in a :math:`2^2 = 4`-dimensional
# quantum state, i.e., :math:`n_S = 2`.
# For this specific example, the number of operators is larger than the number of qubits, leading to a shadow system that
```

2024-08-06 07:30 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +    :width: 35%
```suggestion
    :width: 70%
```
That was the number that was okayed in a Tarik review for OG images.

2024-08-06 07:51 UTC, dwierichs reviewed
Had three other tiny comments.

2024-08-06 07:51 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +so we can drop the denominator. Further, by means of the cyclic property of the trace, we can rewrite this expression to obtain
```suggestion
so we can drop the denominator for simplicity. Further, by means of the cyclic property of the trace, we can rewrite this expression to obtain
```
or
```suggestion
in which case we can drop the denominator. Further, by means of the cyclic property of the trace, we can rewrite this expression to obtain
```

2024-08-06 07:51 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +.. math:: f^\gamma_{\alpha \beta} = - \frac{\text{tr}\left(g_\alpha [g_\gamma, g_\beta] \right)}{||g_\gamma||^2}.
Now we didn't drop the denominator?

2024-08-06 07:51 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# :math:`2^{2n}-1`, so :math:`n_S = 2n` and thus just doubling the number of qubits.
You requested me taking a look in an earlier version I think. This makes sense and is a nice addition I think :) :rocket:

2024-08-06 07:51 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# encode the problem and allows for efficient retrieval of all the relevant information.
applications being plural:
```suggestion
# encode the problem and allow for efficient retrieval of all the relevant information.
```

2024-08-06 07:59 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +    :width: 35%
just felt unnecessarily huge here, would you prefer to change it?

2024-08-06 07:59 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +.. math:: f^\gamma_{\alpha \beta} = - \frac{\text{tr}\left(g_\alpha [g_\gamma, g_\beta] \right)}{||g_\gamma||^2}.
Is this an older version?

2024-08-06 08:15 UTC, dwierichs commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +.. math:: f^\gamma_{\alpha \beta} = - \frac{\text{tr}\left(g_\alpha [g_\gamma, g_\beta] \right)}{||g_\gamma||^2}.
Ah, yes it was, sorry.

2024-08-06 11:06 UTC, ikurecic reviewed
Thanks, @Qottmann , these are the last ones from me.

2024-08-06 11:06 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +:math:`\mathfrak{g} = \langle \{ g_i \} \rangle_\text{Lie} = \{ g_1, .., g_{|\mathfrak{g}|} \}` of the circuit as well as
I stand by this suggestion, please change it to improve readability.

2024-08-06 11:06 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# by :class:`TrotterProduct`, though that shall not be the focus of this demo.
Even if you don't use Alvaro's suggestion, please change this sentence a tiny bit so it doesn't seem like there is more to come, and not just the conclusion.

2024-08-06 11:06 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# Note that even in the case of an exponentially sized set of operators, we have - at least in principle - an exponentially large state vector to store the
```suggestion
# Note that even in the case of an exponentially sized set of operators, we have — at least in principle — an exponentially large state vector to store the
```

2024-08-06 11:06 UTC, ikurecic commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +# :math:`2^{2n}-1`, so :math:`n_S = 2n` and thus just doubling the number of qubits.
```suggestion
# :math:`2^{2n}-1`, so :math:`n_S = 2n` and thus it is just doubling the number of qubits.
```
Or something similar.

2024-08-06 11:30 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +Shadow Hamiltonian simulation is a new approach to quantum simulation on quantum computers [#SommaShadow]_.
I added it 👍

2024-08-06 11:31 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +Shadow Hamiltonian simulation is a new approach to quantum simulation on quantum computers [#SommaShadow]_.
Like this:
> Shadow Hamiltonian simulation is a new approach (published last week) to quantum simulation on quantum computers [#SommaShadow]_.

Is this what you had in mind?

2024-08-06 11:32 UTC, Qottmann commented on demonstrations/tutorial_shadow_hamiltonian_simulation.py
> +We will also see later how shadow Hamiltonian simulation comes down to :doc:`g-sim </demos/tutorial_liesim>`,
pushed it, lets see if any links break

2024-08-06 12:24 UTC, merged