Tutorial: tensor network basics
PennyLaneAI/qml pull request #1193
Opened 2024-08-16 04:35 UTC by EmilianoG-byte

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Remember to do a grammar check of the content you include.
- [ ] All tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

----
If you are writing a demonstration, please answer these questions to facilitate the marketing process.

* GOALS — Why are we working on this now?

  *Eg. Promote a new PL feature or show a PL implementation of a recent paper.*

* AUDIENCE — Who is this for?

  *Eg. Chemistry researchers, PL educators, beginners in quantum computing.*

* KEYWORDS — What words should be included in the marketing post?

* Which of the following types of documentation is most similar to your file? 
(more details [here](https://www.notion.so/xanaduai/Different-kinds-of-documentation-69200645fe59442991c71f9e7d8a77f8))
    
- [ ] Tutorial
- [ ] Demo
- [ ] How-to

2024-08-16 08:03 UTC, Qottmann reviewed
Great skeleton @EmilianoG-byte @Shiro-Raven !

Mainly minor suggestions, and one bigger one towards the last section for quantum circuit applications

2024-08-16 08:03 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +- show examples on https://arxiv.org/pdf/1912.10049 page 8 and 9 showing a quantum circuit for a bell state, defining each component as a tensor and show their contraction.
I would suggest to do concrete examples of gates already above, e.g. single qubit gates = matrices, 2 qubit gates like CNOT = 4 leg tensor with 2 "in" and 2 "out" legs etc.

and then focus here on how e.g. an expectation value $\langle \psi_0 | U^\dagger H U |\psi_0\rangle$ is a tensor network contraction of the initial state - unitary circuit - hamiltonian unitary circuit and initial state again. From the above we should be able to understand all the sub-components and here we are fusing them together

there are some subtleties here:
- While in priciple a n-qubit state is a n-legged (=2^n sized) tensor, $\psi_0$ is often a product state, so it is just n independent vectors.
- H is often the sum of multiple operators. It is beyond the scope of this tutorial to go in depth, but there are ways to efficiently represent such a sum of tensors (e.g. MPOs and generalizations thereof). The "naive" thing to do for a sum of operators $H = \sum_i h_i$ is to do separate evaluations for each $\langle \psi_0 | U^\dagger h_i U |\psi_0\rangle$ and sum them in the end.
- $\langle \psi_0 | U^\dagger$ and $U |\psi_0\rangle$ appear twice in the equation, if one can represent their result efficiently we can re-use it (not a given as it may result in a large 2^n tensor)

2024-08-16 14:51 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +- Definition of a tensor network as an n-dimensional array. Show notation with n indices, stating that it belongs to C^{d1,...,dn}. Define rank, index, dimension (mention how these terms are sometime
Sorry, that was a typo, I meant to write tensor as an n-dimensional array.

2024-08-16 14:52 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +- CODE: include code using numpy creating a >2 dimensional array.
:D

2024-08-16 14:53 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +The cost of contracting a network (bubbling):
Yeah I think is probably not the most wide-spread term, but the hand-wavy paper calls it like that:

<img width="977" alt="Screenshot 2024-08-16 at 10 53 08 AM" src="https://github.com/user-attachments/assets/dc62703d-6809-498d-a60a-fea1c442c4bc">

I left it there in the title mostly for me to remember that we can call it like that

2024-08-16 14:54 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +The cost of contracting a network (bubbling):
https://arxiv.org/pdf/1603.03039

2024-08-16 14:54 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +- CODE: show this using np.einsum, timeit, and very large dimensions expecting to see a difference.
good idea!

2024-08-16 14:56 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +    Link to quimb examples.
Same. I don't think I have properly dived into a paper where they explain a heuristic method. I see Gray's paper being cited a lot so I am guessing this can be a good reference: https://arxiv.org/pdf/2002.01935

However, this might be enough material to even make its own demo. What is suggestion of how much of this to include?

2024-08-16 14:58 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +The cost of contracting a network (bubbling):
Oh interesting! Never heard that term before. So bubbling = one-by-one contracting?

2024-08-16 15:05 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +- show examples on https://arxiv.org/pdf/1912.10049 page 8 and 9 showing a quantum circuit for a bell state, defining each component as a tensor and show their contraction.
Great suggestions! Do you think is worth going into the details of boolean tensor networks when talking about the CNOT (for instance):

<img width="1020" alt="Screenshot 2024-08-16 at 11 01 28 AM" src="https://github.com/user-attachments/assets/66c83786-a921-4e4f-bb87-f03d8e72e0de">

2024-08-16 15:14 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +- show examples on https://arxiv.org/pdf/1912.10049 page 8 and 9 showing a quantum circuit for a bell state, defining each component as a tensor and show their contraction.
> While in priciple a n-qubit state is a n-legged (=2^n sized) tensor, $\psi_0$
 is often a product state, so it is just n independent vectors.
 
 doesn't this go more into the direction of MPS (which is out of the scope of this tutorial)?
 
 >The "naive" thing to do for a sum of operators
 
 If I am not mistaken, since we are assuming an exact contraction of the tensor network without approximating it as an MPS, this naive way is the only option, no? Or is it possible to use the Hamiltonian as an MPO and contract it with the state vector even tho this is not in MPS form?
 
 > if one can represent their result efficiently we can re-use it (not a given as it may result in a large 2^n tensor)
 
 here again you mean efficiently as an MPS? Or do you mean this thing that Quimb does where it reuses contraction paths and other parts of the computation? (I couldn't find the link but I remember seeing something along these lines)

2024-08-16 16:02 UTC, Shiro-Raven commented on demonstrations/tutorial_tn_basics.py
> +The cost of contracting a network (bubbling):
Yes exactly, and particularly contracting sequentially around adjacent tensors, so no notion of concurrency.

2024-08-16 16:30 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +    Link to quimb examples.
I would leave that up to you, if you get a grasp of it and have something valuable to share here feel free to include it, but it is also okay just to link the respective papers/docs

2024-08-16 16:30 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +    Link to quimb examples.
The minimum required info would be that there are heuristics that work reasonably well, where one can find these heuristics and ideally how to set them in `default.tensor`

2024-08-16 16:35 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +- show examples on https://arxiv.org/pdf/1912.10049 page 8 and 9 showing a quantum circuit for a bell state, defining each component as a tensor and show their contraction.
>If I am not mistaken, since we are assuming an exact contraction of the tensor network without approximating it as an MPS, this naive way is the only option, no? Or is it possible to use the Hamiltonian as an MPO and contract it with the state vector even tho this is not in MPS form?

Update: Actually I thought more about it, and I think I was wrong on this. I cannot think of a real constraint of why just contracting a general tensor circuit (no MPS) with an MPO would not work.

2024-08-16 16:36 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +- show examples on https://arxiv.org/pdf/1912.10049 page 8 and 9 showing a quantum circuit for a bell state, defining each component as a tensor and show their contraction.
> doesn't this go more into the direction of MPS (which is out of the scope of this tutorial)?

A product state is something different. You can interpret it as an MPS with trivial virtual bond dimension 1 but that is not the point

> If I am not mistaken, since we are assuming an exact contraction of the tensor network without approximating it as an MPS, this naive way is the only option, no? Or is it possible to use the Hamiltonian as an MPO and contract it with the state vector even tho this is not in MPS form?

MPOs are typically exact and of course you can contract them with something that is not an MPS :) 

> here again you mean efficiently as an MPS? Or do you mean this thing that Quimb does where it reuses contraction paths and other parts of the computation? (I couldn't find the link but I remember seeing something along these lines)

The latter :) though I am actually not sure what https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/devices/default_tensor.py#L799 does

> Do you think is worth going into the details of boolean tensor networks when talking about the CNOT (for instance):

Up to you! I personally dont find that too important but if you like it feel free to include it :)

2024-08-16 16:36 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +The cost of contracting a network (bubbling):
cool :)

2024-08-30 19:10 UTC, EmilianoG-byte commented
Initial draft from last week:

"""
DRAFT:

1) 
- Definition of a tensor as an n-dimensional array. Show notation with n indices, stating that it belongs to C^{d1,...,dn}. Define rank, index, dimension (mention how these terms are sometimes used (wrongly?) interchangeably in literature).
- Graphical notation. Mention that there exist certain representations in the literature that allow to represent properties of the tensors (e.g. symmetry, orthogonality). In our case, we can adhere to a general circle.
- Specific examples used in a day-to-day: scalars, vectors, matrices. Mention that for quantum states, we can adopt the convention that the legs in one direction mean that the state belongs to one Hilbert space, and the legs to the other side to the dual space.
- CODE: include code using numpy creating a >2 dimensional array.

2)

- Show the matrix multiplication in terms of summation over indices, then using the diagrammatic representation. This results in another rank 2 tensor (matrix)
- Analagously, we can represent matrix-vector multiplication resulting in a rank 1 tensor (vector). Just as we expected!
- We can generalize this concept to tensors. This is done by summing over repeated indices (just as in einstein convention - external link for it) resulting in another tensor made up of the open legs of all the tensors together.
    In diagrammatic notation, this is simply sticking together legs with same indices! (show nice diagram with >3 tensors). We have just formed a network of tensors, i.e. a Tensor Network!
- CODE: Talking about einstein convetion, we can perform this contraction of tensors using `np.einsum`.

3)
- Mention that the resulting tensor network doesn't change but the way we arrive to the final tensor affects how expensive it is to get there.
- Show how can we can calculate the complexity of a contraction by means of a simple example using 2 matrices (rank 2 tensors): dimension_contracted x (dimensions_open).
- Intuition behind: we perform one operation (contraction) and repeat many times to "populate" the resulting tensor (dimension_open1 x dimension_open2). Show the equation with indices.
- Show an example with at least three tensors where they all have different dimensions. Walk through it showing that choosing to contract two indices (the ones with lower dimensions) results in a worst computational complexity than contracting other ones (the ones with higher dimensions).
"""

2024-09-06 12:36 UTC, ikurecic commented
[sc-63359]

2024-09-06 12:53 UTC, ikurecic commented
Hi @EmilianoG-byte and @Shiro-Raven , I'm just checking in. Would this Demo already be ready for a 'proper' review by Korbinian? Once it is, please share a quick tag or ping in a comment. :)

2024-09-10 08:41 UTC, Qottmann reviewed
Hi @EmilianoG-byte @Shiro-Raven I took the liberty to take an early peak. I think this is going overall in the right direction, good job so far 👍 The quantum computing part, which should be a substantial part of the demo obviously still needs a lot of work. Let us know how feasible you deem this in the next month or so.

General comment: make sure to clearly state what is _general_ convention and what is specific convention relevant for this demo (e.g. all the isometry stuff). I.e. if we are not going to use these conventions in this demo, there is little point to introducing it.

2024-09-10 08:41 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +Some authors choose to give the shape of the tensor an additional meaning. For example, you might encounter square tensors representing symmetric matrices, to represent its invariance under transposi
If you are not going to use certain conventions, I don't think we need to introduce them here, because they are usually specific to author's and their works and not general

2024-09-10 08:41 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +import numpy as np
this is great 👍

2024-09-10 08:41 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +tensor_rank3 = np.array([tensor_rank2])
do two matrices so the first index is not trivial

2024-09-10 08:41 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +#   A common question arising when drawing a tensor is "what is the correct order to draw the indices". For instance, in the figure above we have adopted the convention that a tensor :math:`A_{i,j,k}
what are you trying to convey here?

2024-09-10 08:41 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +# That is, if the control qubit is in the :math:`|1\rangle` state, we apply the :math:`X` gate on the target qubit, otherwise, we leave them untouched. However, we can also rewrite this equation as a
Is this bit of tearing up a CNOT necessary for the remainder and/or to understand the overall topic of the demo? I.e. are you aiming to use this in the quantum computing part below?
I found it personally a bit confusing.

2024-09-10 08:41 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +# The cost of contracting a network:
this section is great! will be even greater with some illustrations :)

2024-09-10 08:41 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +
would be great also to get something in about contraction path optimizers and heuristics

2024-09-17 22:24 UTC, EmilianoG-byte commented
Hi @ikurecic and @Qottmann! Sorry for the delay, I was on vacation :). I will work on the demo again starting this week!

2024-09-17 22:41 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +#   A common question arising when drawing a tensor is "what is the correct order to draw the indices". For instance, in the figure above we have adopted the convention that a tensor :math:`A_{i,j,k}
I think this will make more sense after I add figures 😅. I was trying to explain that when labeling the indices of a tensor and drawing them - or coding them-  one can choose the order in which we label the tensors. For instance, in two courses I took they had different convention for the ordering of the labels of the MPS legs,

- course A:  0) left bond dimension , 1) physical leg, 2) right bond dimension
- course B:  0) left bond dimension , 1) right bond dimension, 2) physical leg

This confused a bit in the beginning. But as I mention in the demo, it is all about choices, and sticking to one convention.

2024-09-17 22:47 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +# That is, if the control qubit is in the :math:`|1\rangle` state, we apply the :math:`X` gate on the target qubit, otherwise, we leave them untouched. However, we can also rewrite this equation as a
I thought this is what you meant by:

> I would suggest to do concrete examples of gates already above, e.g. single qubit gates = matrices, 2 qubit gates like CNOT = 4 leg tensor with 2 "in" and 2 "out" legs etc.

Since the CNOT is not a single tensor per-se but a contraction of two tensors, I thought of explaining it this way. Otherwise, I can ommit this and just draw the CNOT as a box with four legs (single tensor), but the standard CNOT notation does not necessarily look as a single tensor - or at least it wouldn't be obvious to me - so I thought that would be confusing.

What do you think? - open to change it if you think is too confusing

2024-09-17 22:49 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +# The cost of contracting a network:
Thank you!! I have already some drawings in my Ipad but since we are not able to insert figures as part of an equation, I was leaving the equations here as place holders until I can incorporate them into the figure itself

2024-09-17 22:50 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +
Yes 😬. I didn't have time for that. I was thinking of reading up about this and writing something about it and then leaving the last section to Ahmed

2024-09-17 22:50 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +import numpy as np
Thank you :D

2024-09-17 22:51 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +tensor_rank3 = np.array([tensor_rank2])
Sounds good!

2024-09-18 08:47 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +# That is, if the control qubit is in the :math:`|1\rangle` state, we apply the :math:`X` gate on the target qubit, otherwise, we leave them untouched. However, we can also rewrite this equation as a
> and just draw the CNOT as a box with four legs (single tensor)

this is what I had in mind, but your explanation makes sense and could be nice to convey. A more general approach would be to show that you can always SVD such tensors and find decompositions. I am showing that in the mps demo, perhaps you can just link it once it is merged (hopefully soon) https://github.com/PennyLaneAI/qml/pull/1201

2024-09-18 08:50 UTC, Qottmann commented
> Maybe I misunderstood the purpose of the demo. I had understood from the story around this demo that this is an introductory tutorial for general Tensor Networks. There are some things like these other conventions (which I say we won't use here) that I mention because I think can be useful to clarify questions for people who are new to the topic.
> For instance, people searching over the vast literature might encounter these conventions and get confused with the different shapes of tensors and their meaning - this is a question I had when I started.
> What do you think? Perhaps I was trying to cover more than what we originally intended (?)

My general suggestion would be to try to explain the things that are either common knowledge or important for the content of the demo itself. Discussing different conventions that one may or may not encounter in other literature doesnt fall in either of those categories, so I would drop those.

2024-09-25 19:55 UTC, EmilianoG-byte commented
Hi! I have added now a section on contractions and heuristics. However, since I am no longer part of the Xanadu organization I created a PR on my fork targeting this branch. See: https://github.com/PennyLaneAI/qml/pull/1225

I am still missing to address some of the minor comments you left, but the only major thing from my part should be draw the diagrams with the equations. 

Then perhaps @Shiro-Raven can work on the last section on TN-QC :)

2024-09-26 13:28 UTC, Qottmann commented
hey @EmilianoG-byte you should be able to continue to push on here as the `qml` repo is public. Let's keep it all in one place 👍  Please let me know if that is not the case, and I can arrange to have you granted the appropriate rights

2024-09-30 17:02 UTC, EmilianoG-byte commented
Hi @Qottmann, I get this error:

```bash
ERROR: Permission to PennyLaneAI/qml.git denied to EmilianoG-byte.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
```

2024-10-01 08:12 UTC, Qottmann commented
hey @EmilianoG-byte @Shiro-Raven you should both have access to push to this branch again now :) Sorry for the confusion

2024-10-01 10:14 UTC, EmilianoG-byte commented
Thank you @Qottmann! 

I have added the figures on all the sections (need to be reshaped to fit nicely) :)

2024-10-08 22:34 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +- CODE: show this using np.einsum, timeit, and very large dimensions expecting to see a difference.
Coming back to this, I printed the dimensions locally but I don't quite get what insight we get from this. Since we only have three tensors, the dimensions of intermediate tensors (AB) and (BC) are actually exactly the same. This also by construction to get the expected scaling in the computational cost.

I could come up with an example where the dimensions vary between contraction paths but probably would have to be more complex and not just a "triangle-like" tensor network

2024-10-09 09:47 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +- CODE: show this using np.einsum, timeit, and very large dimensions expecting to see a difference.
Yeah sounds like the example is too simple to show the desired property

> I could come up with an example where the dimensions vary between contraction paths

💯

2024-10-09 09:48 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +- CODE: show this using np.einsum, timeit, and very large dimensions expecting to see a difference.
just to be sure, I guess also the timing is the same in the situation you describe rn?

2024-10-14 17:06 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +- CODE: show this using np.einsum, timeit, and very large dimensions expecting to see a difference.
Well the timing varies and that is what I was trying to convey here, as the timing scales exactly as we would expect it from the complexity analysis I discussed some lines before. What would you like to show with the dimensions? That some paths result in tensors of larger intermediate size?

2024-10-15 08:49 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +- CODE: show this using np.einsum, timeit, and very large dimensions expecting to see a difference.
> What would you like to show with the dimensions? That some paths result in tensors of larger intermediate size?

exactly :)

2024-10-18 11:42 UTC, Qottmann commented
hey @EmilianoG-byte @Shiro-Raven how are things coming along? Please let me know when you have a first draft that is ready for review (don't forget to self-review first) :)

2024-10-19 13:51 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +- show examples on https://arxiv.org/pdf/1912.10049 page 8 and 9 showing a quantum circuit for a bell state, defining each component as a tensor and show their contraction.
I have now added a section on tensor networks-quantum computing. Lmk what you think!

2024-10-21 07:49 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +- show examples on https://arxiv.org/pdf/1912.10049 page 8 and 9 showing a quantum circuit for a bell state, defining each component as a tensor and show their contraction.
is the demo overall ready for review?

2024-10-21 15:44 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +- show examples on https://arxiv.org/pdf/1912.10049 page 8 and 9 showing a quantum circuit for a bell state, defining each component as a tensor and show their contraction.
I would think so @Qottmann :). I can read the whole thing between today and tomorrow to find typos but content-wise, I am happy with what it has.

I just have two TODO's on the script for myself which are to add some details to some figures.

2024-10-21 15:48 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +- show examples on https://arxiv.org/pdf/1912.10049 page 8 and 9 showing a quantum circuit for a bell state, defining each component as a tensor and show their contraction.
Great! Then I'd suggest to do a self-review first, and when it's ready for a full review please tag me in the PR :)

2024-10-29 09:02 UTC, EmilianoG-byte commented
Hi @Qottmann ! I have finished checking the spelling and grammar so I believe the demo is now ready for a review :). 

If anything, I saw my last 3 drawings could use some improvement in the thickness of the lines, but I guess that’s a minor detail I can correct in the following days :D

2024-10-29 09:04 UTC, Qottmann commented
@EmilianoG-byte awesome :) you can expect a review at the latest by eow

2024-11-04 11:02 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +# Contraction paths
this section is very nice!

2024-11-04 11:02 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +# Until now, we have looked at general tensor networks, while ✨sparkling✨ the discussions with examples related to quantum circuits. Here, we leverage the components we have learned to explore this r
🤣

2024-11-04 11:03 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +# In the right-hand side of the equality we have assumed a specific form for the U tensor in terms of local 2-qubit gates, which is often the case when dealing with real quantum hardware. In addition
Note that in the diagram depicted as it is right now, also the initial state is assumed to be a product state since all tensors are independent

a general input state would be one big rank-#qubits tensor

2024-11-04 11:06 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +# .. figure:: ../_static/demonstration_assets/tn_basics/12-expectation-local.png
the convention you chose in the beginning with bras and kets is not doing you any favors here, the reversal of bra and ket is unnecessarily confusing the image imo

2024-11-04 11:06 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +# Then, the sections outside of the light cone (grayed-out gates in the figure above) can be ignored since these are contractions resulting in the identity: :math:`G G^\dagger = I`. This helps us dec
👌

2024-11-04 11:10 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +# .. figure:: ../_static/demonstration_assets/tn_basics/13-sample.png
very cool illustration!

2024-11-04 11:13 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +# Analogously as done with the expectation values, these contractions only involve the sections of the circuit within the light cone of **both** the projection with :math:`| \hat{x}_1 \rangle` and th
what do you mean by this?
> this is what makes every sample _memoryless_

2024-11-10 13:41 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +For example, a scalar :math:`s` is a rank-0 tensor, a vector :math:`v_i` is a rank-1 tensor, and a matrix :math:`G_{i,j}` is a rank-2 tensor.
✅

2024-11-10 13:55 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +    Some authors refer to the indices of the tensors as their dimensions. In this tutorial, these two concepts will have different meanings, although related.
I have cleaned a bit the explanation on the index-dimension relation. Strictly speaking, I also think is not truly necessary, but perhaps could be helpful for beginners that can get confused with the terminology when coming from other tutorials :)

2024-11-10 14:08 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +When working within the quantum computing notation, we adopt the convention that drawing the leg of a quantum state (i.e., a vector) to the right corresponds to a ket, i.e., a vector living in the Hi
I would say for "general tensor networks" (like in condensed matter) this is the opposite convention. But since in quantum computing we read from left to right, you can see that all kets result in legs pointing right. Analogously the bra $\langle v|$ is a tensor with legs pointing left. Again, this is probably just the convention that arisis in quantum circuit circuit diagrams and is not a general convention. I am not sure i understand the second part of your comment 🤔

2024-11-10 14:16 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +#     (G^3)_{i,k} = G^2 \cdot G^1 = \sum_j G^{2}_{j,k} G^{1}_{i,j}
So you suggest also changing the diagram? I was wondering this as well. But i guess this is rooted in the "unlucky" convention that circuits are read from left to right while we apply the matrices to the vector from right to left. I can change the diagram to the $G^2$ be before $G^1$ but this seemed odd to me because I thought it was more natural for gate's labels to increase over time (from left to right).

2024-11-10 14:18 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +#   A common question arising when drawing a tensor is "What is the correct order to draw the indices?". For instance, in the figure above, we have adopted the convention that a tensor :math:`A_{i,j,
:D

2024-11-10 14:24 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +# We can now generalize this concept to tensors, and consequently, to more than two legs being contracted. For example, let us look at three tensors :math:`A_{i,j,k}`, :math:`B_{j,l,m}`, and :math:`C
Oh I am not not a fan of einstein convetion 😅. I would much rather have the summation over the indices be explicit rather that having to keep track of what are the repeated indices :D.

2024-11-10 14:37 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +#   CNOT = \sum_j (T^1)_{i,j,k} \otimes (T^2)_{l,j,m}.
I chose to write it like this to express a parallel witht the initial equation:

$CNOT = |0\rangle \langle 0 | \otimes I + |1\rangle \langle 1 | \otimes X.$

So that for example the first term corresponds to:

$(T^1)_{0,j,k} \otimes (T^2)_{l,0,m} = |0\rangle \langle 0 | \otimes I$

You can see this definition for contractions in Eq.1.7 of: https://arxiv.org/pdf/1603.03039

However, you are right that we are also using the "convention" of just writing the $\sum_j T^1{i, j, k} T^2_{l, j, m}$ in other parts of the tutorial, so for coherence I can write it as a third part of the equation? I am unsure if this is rather a "sloppy" convention that has been widely adopted so now we all know what it means 🤔.

Maybe I can add this as a note where I introduce the generalization of contractions to tensors?

2024-11-10 14:44 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +#   Actually, finding the optimal contraction path of a tensor network is an NP-complete problem [#Arad]_.
Sort of, also I am trying to keep the "notes" as "interesting fact/good to know/good to keep in mind" kind fo things, which are not stricly necessary for the main explanations.

2024-11-10 14:45 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +#   Actually, finding the optimal contraction path of a tensor network is an NP-complete problem [#Arad]_.
So I thought writing this here with a source they can check falls into those categories.

2024-11-10 14:54 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +# In this case, the tensors are such that :math:`A_{i,j,k} \in \mathcal{C}^{d_i \times d_j \times d_j}`, :math:`B_{j,l,m} \in \mathcal{C}^{d_j \times 1 \times d_m}`, and :math:`C_{k,m,n} \in \mathcal
Good catch, I should have used mathbb! However, regarding the values of the indices. It is on purpose that I wrote (for instance) $d_j$ twice for A instead of $d_k$, and similarly for all the other indices. This is just a particular example so that we can see the different scalings. Otherwise, if have general $d_i, d_j, d_k$ I wouldn't be able to say anything about the complexities of one path or the other. To make it simpler, I also chose one of the indices to be $1$.

What I can do is to use your suggestion and then say explicitely the assumptions for this specific example?

2024-11-10 20:26 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +When working within the quantum computing notation, we adopt the convention that drawing the leg of a quantum state (i.e., a vector) to the right corresponds to a ket, i.e., a vector living in the Hi
when writing tensor diagrams, transposition becomes irrelevant as it is always clear from context. So the only thing you need to differentiate a bra from a ket is complex conjugation, which you can indicate with a star or bar over the tensor name :)

2024-11-10 20:28 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +#     (G^3)_{i,k} = G^2 \cdot G^1 = \sum_j G^{2}_{j,k} G^{1}_{i,j}
No I would just change the formula so it matches the diagram. The formula stays the same, its just notation

2024-11-10 20:29 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +# We can now generalize this concept to tensors, and consequently, to more than two legs being contracted. For example, let us look at three tensors :math:`A_{i,j,k}`, :math:`B_{j,l,m}`, and :math:`C
Also fine, but then I'd not bother introducing it 👍

2024-11-10 20:31 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +#   CNOT = \sum_j (T^1)_{i,j,k} \otimes (T^2)_{l,j,m}.
Whatever you deem most clear, just wanted to point out that it confused me :)

2024-11-10 20:31 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +#   Actually, finding the optimal contraction path of a tensor network is an NP-complete problem [#Arad]_.
👍

2024-11-10 20:32 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +# In this case, the tensors are such that :math:`A_{i,j,k} \in \mathcal{C}^{d_i \times d_j \times d_j}`, :math:`B_{j,l,m} \in \mathcal{C}^{d_j \times 1 \times d_m}`, and :math:`C_{k,m,n} \in \mathcal
yes I think otherwise it gets too confusing, and also is not necessary to showcase what you intend

2024-11-10 22:48 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +# This means the second contraction path results in an asymptotic cost of :math:`\mathcal{O}(d_i^2 \times d_j^2)`—lower than the first contraction path.
I see. I thought this was the purpose of the code below. By leaving the asymptotic expressions in terms of variables, I think is more clear that one of the them scales quadratically with some dimensions, and linearly using a different contraction. Then the code makes this more tangible connection you mention.

2024-11-10 22:51 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +# Then, we perform the individual contractions between pairs of tensors and time them using ``timeit``. We repeat the contraction ``20`` times and average the computation time to account for smaller
Thank you! I am not sure I follow what you want me to do here though... which two sections do you want to merge? Do you want to erase the asymptotic expressions?

2024-11-10 23:00 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +# Contraction paths
Thank you 😊

2024-11-10 23:01 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +# Until now, we have looked at general tensor networks, while ✨sparkling✨ the discussions with examples related to quantum circuits. Here, we leverage the components we have learned to explore this r
😎

2024-11-10 23:04 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +# In the right-hand side of the equality we have assumed a specific form for the U tensor in terms of local 2-qubit gates, which is often the case when dealing with real quantum hardware. In addition
True! That's what I meant with the last sentence of this paragraph. Should I also write what you mentioned on:
> a general input state would be one big rank-#qubits tensor
?

2024-11-10 23:09 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +# .. figure:: ../_static/demonstration_assets/tn_basics/12-expectation-local.png
I see your point, but once again this comes down to the convention used in quantum computing. Should I then instead draw all kets point left and bras to the right? Then the diagram here would make more sense but then all the circuit diagrams would go agains the usual convention 🤔

2024-11-10 23:50 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +# Then, the sections outside of the light cone (grayed-out gates in the figure above) can be ignored since these are contractions resulting in the identity: :math:`G G^\dagger = I`. This helps us dec
😊

2024-11-10 23:51 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +# .. figure:: ../_static/demonstration_assets/tn_basics/13-sample.png
Thank you :D

2024-11-10 23:57 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +# Analogously as done with the expectation values, these contractions only involve the sections of the circuit within the light cone of **both** the projection with :math:`| \hat{x}_1 \rangle` and th
Memoryless here means that we don't use a markov chain, or information from previous samples to generate the next full sample. This is contrary to the other "non-perfect"/markov sampling algorithms like the one used back in the day in: https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.100.040501
I haven't read the old paper myself, but this difference was mentoined in the perfecting sampling source I mentioned in the text and https://tensornetwork.org/mps/algorithms/sampling/

2024-11-11 00:16 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +In this tutorial, we aim to provide an introduction to tensor networks with a focus on their applications in quantum computing. We choose to start by discussing the basic notions and definitions of t
Should I make the changes you were referring about being more clear about the scope of the demo?

2024-11-11 09:27 UTC, ikurecic commented on demonstrations/tutorial_tn_basics.metadata.json
> +            "id": "ahmed_darwish"
Please swap this out like this:
```suggestion
            "username": "emiliano"
        },
        {
            "username": "ShiroRaven"
```
Also, @Shiro-Raven , you're still missing a picture and the _Headline_ on your account.

2024-11-11 09:28 UTC, ikurecic commented on demonstrations/tutorial_tn_basics.metadata.json
> +    "dateOfLastModification": "2024-08-06T00:00:00+00:00",
tk

2024-11-11 10:32 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +# Then, we perform the individual contractions between pairs of tensors and time them using ``timeit``. We repeat the contraction ``20`` times and average the computation time to account for smaller
the symbolic and concrete part, but you argue in the other comment that you prefer it this way 👍

2024-11-11 10:35 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +# .. figure:: ../_static/demonstration_assets/tn_basics/12-expectation-local.png
When you compute expectation values of hermitian observables the order in what you call the bra and what the ket is actually unimportant. I'd leave it ambiguous and clear from context, but I see your point if you want to be more precise. Up to you! Just wanted to mention it as a possibility :)

2024-11-11 10:36 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +# Analogously as done with the expectation values, these contractions only involve the sections of the circuit within the light cone of **both** the projection with :math:`| \hat{x}_1 \rangle` and th
cool 👍 I'd either mention _and explain_ it or leave it :)

2024-11-11 10:38 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.metadata.json
> +            "id": "ahmed_darwish"
is @Shiro-Raven still an author of the demo?

2024-11-24 17:00 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +#     (G^3)_{i,k} = G^2 \cdot G^1 = \sum_j G^{2}_{j,k} G^{1}_{i,j}
Ah I think I now know what you mean. Should it then be:
```suggestion
#     (G^3)_{i,k} = G^2 \cdot G^1 = \sum_j G^{1}_{i,j} G^{1}_{j,k}
```

Since we are reading the diagram from left to right and thus, the $G_1$ should appear before $G_2$ in the diagram but after it in the equation (similarly to how in the figure before its $G \cdot v$ and not $v \cdot G$)?

2024-11-25 11:21 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +When working within the quantum computing notation, we adopt the convention that drawing the leg of a quantum state (i.e., a vector) to the right corresponds to a ket, i.e., a vector living in the Hi
I personally have never seen these definitions and conventions outside of this particular review by Biamonte. There is nothing wrong with it, I was just wondering if it's adding something to your demo or making things unnecessarily comlicated. I'm sharing this observation and, but in the end it is up to you as the author to decide :)

2024-11-25 11:30 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +In this tutorial, we aim to provide an introduction to tensor networks with a focus on their applications in quantum computing. We choose to start by discussing the basic notions and definitions of t
I quite like the idea of the intermezzo :) from reading that the context is clear. do you think there is also a way you could specify in the intro which parts of the contents are going to be "the first part"? Because technically this currently consists of 3 sub-parts, perhaps you can introduce main headings "part1" and "part 2", with the current headings (minus intermezzo) being sub-headings.

In particular, this structure
```
1. Part 1
1.1 from matrices to tensors
1.2 from matrix multiplication to tensor contractions
1.2.1 CNOT gate
1.3 cost of contraction
2. Intermezzo
3. Part 2
...
```

(note that I dont mean that the headings in the content actually have this numbering, this is just to explain the logic)

2024-11-26 00:13 UTC, Shiro-Raven commented on demonstrations/tutorial_tn_basics.metadata.json
> +            "id": "ahmed_darwish"
Hey there! Very sorry for the radio silence. Emiliano and I actually agreed a long time ago that he will go on and have complete authorship of this demo, so please remove me from the metadata and the authors section

2024-12-01 21:17 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +#     (G^3)_{i,k} = G^2 \cdot G^1 = \sum_j G^{2}_{j,k} G^{1}_{i,j}
Done, thank you for the suggestion! 😃

2024-12-02 09:52 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +In this tutorial, we aim to provide an introduction to tensor networks with a focus on their applications in quantum computing. We choose to start by discussing the basic notions and definitions of t
Thank you for the suggestion! I have added an extra level of headers and reference the main two parts in the intro but it does not seem to be deploying correctly for some reason 🤔

2024-12-02 10:13 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +In this tutorial, we aim to provide an introduction to tensor networks with a focus on their applications in quantum computing. We choose to start by discussing the basic notions and definitions of t
yeah sphinx is odd sometimes, I'd suggest to check other demos that reference sections and see how they do it

2024-12-02 16:46 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +In this tutorial, we aim to provide an introduction to tensor networks with a focus on their applications in quantum computing. We choose to start by discussing the basic notions and definitions of t
It's solved :)

2024-12-02 16:47 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +In this tutorial, we aim to provide an introduction to tensor networks with a focus on their applications in quantum computing. We choose to start by discussing the basic notions and definitions of t
I think @ikurecic fixed it by merging the main branch, thank you! 🙏

2024-12-18 19:04 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +When working within the quantum computing notation, we adopt the convention that drawing the leg of a quantum state (i.e., a vector) to the right corresponds to a ket, i.e., a vector living in the Hi
I had forgotten to reply to this comment. Thank you for giving me the freedom to choose :). I will then leave this definition. I have used quite often e.g. in my own paper https://arxiv.org/pdf/2409.08127 - to make some self propaganda, and in general when using tensor networks to formulate equations.

In this particular demo, I think is useful to have a distinction between the ket and the bra's pointing in different directions as shown in the last figure.

2024-12-18 19:08 UTC, EmilianoG-byte commented
Hi @Qottmann, please let me know what you think of the new headers :)

2025-01-01 23:40 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +# In the previous section, we explored how the choice of the contraction path affects the computational cost of the tensor network contraction through a toy example. As shown in [#Lam1997]_, finding
I have added a note! Thank you :)

2025-01-02 00:04 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +#     (G^3)_{i,k} = G^2 \cdot G^1 = \sum_j G^{1}_{i,j} G^{2}_{j,k}
I think it's again the confusion that the diagrams I am writing are supposed to be read from left to right (like you do with quantum circuits). That's why in the vector-matrix diagram, we have a vector (not the transpose) multiplied with a matrix (a gate) from the right.

Similarly, with matrix-matrix multiplication, G2 @ G1 $= G_2 \cdot G_1$ is equivalent to drawing the G1 first, and then being contracted from the right with G2 (because G1 would act first on the state, and then G2). Like:

$G_2 \cdot G_1 \ket{\psi}$ -> quantum circuit: ($\psi$)--($G_1$)--($G_2$)--

If we write $G_1 \cdot G_2 \ket{\psi}$ that would be something totally different.

And whether we write $\sum_i v_i G_{i, j}$ or $\sum_i G_{i, j} v_i$ doesn't really matter since here both $v_i$ and $G_{i, j}$  since they are both scalars, I just think we changed it to match the equation order ($G \cdot v$).

2025-01-02 00:24 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +# This means the second contraction path results in an asymptotic cost of :math:`\mathcal{O}(d_i^2 \times d_j^2)`—lower than the first contraction path.
I have added some numbers now next to the general expressions :)

2025-01-02 10:54 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +#     (G^3)_{i,k} = G^2 \cdot G^1 = \sum_j G^{1}_{i,j} G^{2}_{j,k}
On one hand there is conventions (reading things from left to right and vice versa) and on the other there are standard definitions, like the matrix multiplication. I just wanna make sure we are not putting "objectively" wrong things (as objective as standard definitions can be).

In particular here, if you want the right-hand side of the equation to be the thing you convey, i.e. $\sum_j G^{1}_{i,j} G^{2}_{j,k}$, then this is equal to $G^1 \cdot G^2$ in the sense of the standard definition of matrix multiplication.

If your point is to write $G^2 \cdot G^1$, you can update the right-hand-side accordingly, instead. (i.e. $\sum_j G^{2}_{i,j} G^{1}_{j,k}$

The choice is yours, my only point was that the way it is currently written is "wrong" (as in not matching the standard definition of the matrix multiplication)

2025-01-05 19:18 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +#     (G^3)_{i,k} = G^2 \cdot G^1 = \sum_j G^{1}_{i,j} G^{2}_{j,k}
Ohhhh damn, I think (I hope) I now see what you mean. There was definitely something wrong in how I was writing the multiplication. I think the main issue is how I was labeling the matrix tensors and that this was incongruent with the definitions of the multiplications. 

I have now (hopefully) fixed this. Another improvement is that now I write $(G)_{i,j}$ to refer to the $(i,j)$-th term of $G_{i,j}$. This was also causing a bit of a confusion. Based on this, I erased the $Gv$ and $G^2 \cdot G^1$ from the equations since the equations we were working with were for a **single** element of the final tensor, while the expressions I erased produce a vector and a matrix, respectively (not a scalar like the rest of the equation).

I hope now this is correct 😅. Really sorry for not understanding it before @Qottmann

2025-01-07 11:27 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +#   \sum_{j} (A)_{i,j,k} (B)_{j,l,m} \implies \mathcal{O}(d_i \times d_m \times d_j^2 ) = \mathcal{O}(10^7)
Great to have the explicit numbers there now :) Just one small thing to make it even more readable: can you do the explicit split with the numbers as well, e.g. here $\mathcal{O}(d_i \times d_m \times d_j^2 ) = \mathcal{O}(10^3 10^2 (10^1)^2) = \mathcal{O}(10^7)$, same for the below

2025-01-07 11:27 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +#     (G^3)_{k,i} = \sum_j (G^2)_{k,j} (G^1)_{j,i} .
thanks for the fix👌 
(with this you could write $G^2 \cdot G^1$ again as well if you want, no need though)

2025-01-07 11:27 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +#     (G^3)_{k,i} = \sum_j (G^2)_{k,j} (G^1)_{j,i} .
Just cosmetics, but the brackets around the $G$ looks a bit awkward, why not just $G^2_{k, j}$?

2025-01-07 11:27 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +#     (G^3)_{i,k} = G^2 \cdot G^1 = \sum_j G^{1}_{i,j} G^{2}_{j,k}
Thanks for the fix, looks good now! And really no need to apologize 🙃

2025-01-07 11:28 UTC, Qottmann approved these changes
Looks good from the technical side now, the rest is cosmetics :) Good job @EmilianoG-byte

2025-01-08 10:06 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +#   \sum_{j} (A)_{i,j,k} (B)_{j,l,m} \implies \mathcal{O}(d_i \times d_m \times d_j^2 ) = \mathcal{O}(10^7)
Sounds good, just did!

2025-01-08 10:10 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +#     (G^3)_{k,i} = \sum_j (G^2)_{k,j} (G^1)_{j,i} .
Yes, I added a new line in the very beginning that reads:

> We will denote the :math:`(i_1, i_2, \ldots, i_r)`-th entry of the tensor :math:`T` as :math:`(T)_{i_1, i_2, \ldots, i_r}` — this is a single number.

Because before I was not being consistent with it. So now writing (G)_{k,i} means that this is the (k,i)-th element of the G_{k,i} tensor (following the convention in notation in the wikipedia article for multiplication).

That's also why I erased $G^2 \cdot G^1$ because that equation gives a matrix and not a single element, while the $\sum_j (G^2)_{k,j} (G^1)_{j,i}$ gives just the ${k,i}$ element.

2025-01-08 10:12 UTC, EmilianoG-byte commented
Thank you @Qottmann :D.

What is the next step? I am still missing adding an author profile and a thumbnail 🤔

2025-01-08 10:20 UTC, Qottmann commented
> What is the next step? 

Next step will be another round of review, this time focussing on the presentation, grammar and pennylane.ai website standards. I informed the people in charge and you should here back in this PR. Please ping me if this doesnt happen in due time

> I am still missing adding an author profile and a thumbnail 🤔

Feel free to add those! Note that they will not be rendered in the deployment previews, but in the final version on the website

2025-01-08 10:22 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.py
> +#     (G^3)_{k,i} = \sum_j (G^2)_{k,j} (G^1)_{j,i} .
Ah gotcha!

2025-01-09 22:01 UTC, alvaro-at-xanadu requested changes
Looks great! I've learned a lot! Minor copy things and some confusion I have with the notation.

I just have to figure out how to add you photo and bio, you don't need to worry about it. Then we'll be good to go 🚀

2025-01-12 22:51 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +The :ref:`first part of this tutorial <part_one>` aims to introduce the basic notions and definitions of tensor networks to those quantum practitioners familiar with quantum computing but who are new
This is great! I always try to but struggle writing things more concisely 😅

2025-01-12 22:52 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +Then, building on this introduction, in the :ref:`second part <part_two>` we explore topics akin to more seasoned 🧂 readers who want to learn about concepts and algorithms used to connect tensor netw
sad to see my emojis go, but I kind of understand 😢

2025-01-12 23:20 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +
I think this is standard notation when working with vectors and matrices (see https://www.math.uwaterloo.ca/~hwolkowi/matrixcookbook.pdf and https://en.wikipedia.org/wiki/Matrix_multiplication#Matrix_times_matrix#Notation). However, I do see a lot of authors using something like $T_{i,j,k}$ for both the tensor and the elements, which can be confusing. That's why I clarify it in the beginning. 

A thing that a lot of authors do as well (related to this issue) is that they write a contraction like this:
<img width="542" alt="Screenshot 2025-01-13 at 00 16 58" src="https://github.com/user-attachments/assets/8e05d10e-5cac-4dee-b75a-0f16d2d685b0" />

I would say this is rather common, but more of a lazy notation than an actual mathematically correct definition. If one wants to be precise, we would need to use the definition of contraction for full tensors, like the one given here https://arxiv.org/pdf/1603.03039 in 1.2.3. I also mention this definition below :)

2025-01-12 23:29 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +#
As mentioned in my previous comment, this definition comes from the source I cite in the text: https://arxiv.org/pdf/1603.03039 on section "1.2.3 Contraction".  In this context, $A$ and $A_{i,j,k}$ are both the full tensor, just that one enumerates explicitly the rank and indices of the tensor

2025-01-12 23:29 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +
Right?! :D

2025-01-14 17:05 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +#
If you look at the ratio:

$\mathcal{O}(d_j \times d_m \times d_i^2)/\mathcal{O}(d_i \times d_m \times d_j^2 ) = \mathcal{O}(d_j/d_i)$

For general $d_i, d_j$ we cannot really draw any conclusion, but since $d_j < d_i$, we then know that one contraction is bigger than the other. Then the second contraction path includes $d_m$ and we have a similar argument.

2025-01-14 17:17 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +# Then, the diagonal of this :math:`2 \times 2` density matrix gives us the probability of sampling 0 or 1, i.e., :math:`p(x_1 = 0)` and :math:`p(x_2 = 1)`. This diagonal corresponds to the following
You are completely right, thank you for catching this typo! 😳

2025-01-14 17:18 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +#
Exactly! I thought it was standard notation in linear algebra, but I can also mention it explicitly (?)

2025-01-14 17:42 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.metadata.json
> +    "title": "Tutorial: ABC of tensor networks",
Oh that's a very hard question since I don't have much experience on making things "engine friendly". I am very open to your suggestions.

That said, how about:

"Intro to tensor networks: a quantum practitioner's guide to tensor networks"

making a reference to "a hitchhiker's guide to the galaxy" book. In that case my thumbnail draft would not be applicable, but that's fine for me.

What do you think @alvaro-at-xanadu ? Also very open for suggestions from @Qottmann :)

2025-01-14 18:07 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +#
I see. I have added it now, I am a bit concerned those expressions are getting kinda cluttered

2025-01-14 18:11 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +#
I have now moved the definition to this part! Thank you :)

2025-01-15 08:32 UTC, Qottmann commented on demonstrations/tutorial_tn_basics.metadata.json
> +    "title": "Tutorial: ABC of tensor networks",
could follow the pattern "introducing XXX for quantum practicioners"
e.g.
https://pennylane.ai/qml/demos/tutorial_mps
https://pennylane.ai/qml/demos/tutorial_liealgebra

2025-01-15 16:53 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_tn_basics.metadata.json
> +    "title": "Tutorial: ABC of tensor networks",
That's a good idea @Qottmann

2025-01-15 16:55 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_tn_basics.py
> +#
Yeah I think this is the more intuitive use for me. Looks good then :) we can leave as is.

2025-01-15 21:09 UTC, justinpickering reviewed
Some comments below for the `metadata.json` file. 

I will also leave some for the content in a second review thread :)

2025-01-15 21:09 UTC, justinpickering commented on demonstrations/tutorial_tn_basics.metadata.json
> +    "seoDescription": "An introductory tutorial to tensor networks.",
This SEO description is too short and lacks substance.

Do you have any thoughts on an improved on @alvaro-at-xanadu @EmilianoG-byte, and which keywords we should include ?
An idea below:

```suggestion
    "seoDescription": "Discover the fundamentals of tensor networks with this comprehensive demo. Learn how tensors extend vectors and matrices, explore their intuitive diagrams, and see how they connect to quantum circuits.",
```

2025-01-15 21:09 UTC, justinpickering commented on demonstrations/tutorial_tn_basics.metadata.json
> +    "dateOfLastModification": "2024-08-06T00:00:00+00:00",
TK

2025-01-15 21:09 UTC, justinpickering commented on demonstrations/tutorial_tn_basics.metadata.json
This filename will be the URL of the demo, therefore it should be descriptive and avoid use of short formed words.

I recommend tutorial_tensor_network_basics.py. It should be close enough to the title.

2025-01-15 22:30 UTC, justinpickering reviewed
Great work! Please see my comments below.

2025-01-15 22:30 UTC, justinpickering commented on demonstrations/tutorial_tn_basics.py
> +#   A common question arising when drawing a tensor is "What is the correct order to draw the indices?". For instance, in the figure above, we have adopted the convention that a tensor :math:`A_{i,j,
```suggestion
#   A common question arising when drawing a tensor is "What is the correct order to draw the indices?" For instance, in the figure above, we have adopted the convention that a tensor :math:`A_{i,j,k}` corresponds to a diagram with the first leg (:math:`i`) pointing left, the second leg (:math:`j`) pointing upwards, and the third leg (:math:`k`) pointing right, and similarly for the other two tensors. However, this need not be the case. We could have defined the first leg to be the one pointing upwards, for example. Based on the use case, and the user, some conventions might seem more natural than others. The only important thing to keep in mind is to be consistent. In other words, once we choose a convention for the order, we should apply it to all the tensors to avoid contracting the wrong indices.
```

2025-01-15 22:30 UTC, justinpickering commented on demonstrations/tutorial_tn_basics.py
> +# This means :math:`T^1_{i,j,k}` and :math:`T^2_{l,j,m}` are two rank-3 tensors, where the index :math:`j` *picks* the elements in the column vector while the other two indices correspond to the indi
equation `math:`|1\rangle \langle 1|`` not rendering correctly in preview:
![image](https://github.com/user-attachments/assets/d258f8be-ecfc-4139-84ff-10a759befd48)

2025-01-15 22:30 UTC, justinpickering commented on demonstrations/tutorial_tn_basics.py
> +#   More generally, we can find decompositions of multi-qubit gates into local tensors employing the ubiquitous singular value decomposition (SVD). This method is explained in detail in our :doc:`MPS
```suggestion
#   More generally, we can find decompositions of multi-qubit gates into local tensors employing the ubiquitous singular value decomposition (SVD). This method is explained in detail in our :doc:`introduction to matrix product states for quantum practitioners demo </demos/tutorial_mps>`. This decomposition is helpful when contracting non-local tensors, as is often required in quantum circuits.
```

2025-01-15 22:30 UTC, justinpickering commented on demonstrations/tutorial_tn_basics.py
> +# From this, we see that the second contraction path results in a lower complexity compared to the first one, just as we expected! 💪
```suggestion
# From this, we see that the second contraction path results in a lower complexity compared to the first one, just as we expected!
```

2025-01-15 22:30 UTC, justinpickering commented on demonstrations/tutorial_tn_basics.py
> +# Perhaps you even feel motivated to dive deeper into the vast world of tensor networks! 🧐
```suggestion
# Perhaps you even feel motivated to dive deeper into the vast world of tensor networks!
```

2025-01-15 22:30 UTC, justinpickering commented on demonstrations/tutorial_tn_basics.py
> +Part 1: A first glimpse into the tensor networks world
I don't think separating into two parts is necessary (in the section title). It does not follow consistent format with other demos on the PennyLane site.

```suggestion
A first glimpse into the tensor networks world
```

2025-01-15 22:30 UTC, justinpickering commented on demonstrations/tutorial_tn_basics.py
> +# Intermezzo
lol is this Italian? I would suggest at least putting a word in parentheses for readers that may not know what this word means.
```suggestion
# Intermezzo (interlude)
```

2025-01-15 22:30 UTC, justinpickering commented on demonstrations/tutorial_tn_basics.py
> +# Part 2: Connecting tensor networks and quantum circuits 🔌
I don't think separating into two parts is necessary (in the section title). It does not follow consistent format with other demos on the PennyLane site.

```suggestion
# Connecting tensor networks and quantum circuits
```

2025-01-15 22:30 UTC, justinpickering commented on demonstrations/tutorial_tn_basics.py
> +# To end this demo, let us answer the question: **how can we use tensor networks to simulate the output of a quantum circuit** ⁉️
```suggestion
# To end this demo, let us answer the question: **how can we use tensor networks to simulate the output of a quantum circuit?**
```

2025-01-15 22:30 UTC, justinpickering commented on demonstrations/tutorial_tn_basics.py
> +# The different types of values accepted for ``contraction_optimizer`` are determined by the ``optimize`` parameter in ``Quimb`` (see `docs <https://quimb.readthedocs.io/en/latest/tensor-circuit.html
The hyperlinked text needs to be more descriptive.
```suggestion
# The different types of values accepted for ``contraction_optimizer`` are determined by the ``optimize`` parameter in ``Quimb`` (see `docs <https://quimb.readthedocs.io/en/latest/tensor-circuit.html#finding-a-contraction-path-the-optimize-kwarg>`_) as this is the backend behind the :class:`~pennylane.devices.default_tensor.DefaultTensor` device. See our `simulate quantum circuits with tensor networks demo <https://pennylane.ai/qml/demos/tutorial_How_to_simulate_quantum_circuits_with_tensor_networks/>`_ to learn more about the use of this device in ``Pennylane``.
```

2025-01-15 22:30 UTC, justinpickering commented on demonstrations/tutorial_tn_basics.py
> +
We've transitioned from using the word tutorial to demo.

```suggestion
# Conclusion
# ----------
# 
# And that is it for this demo! 🎉
# 
# Although the world of tensor networks and their relation to quantum computing is vastly wider than what we could ever cover in one tutorial, we hope that after these explanations you now feel equipped with the tools needed to dive deeper into this topic by yourself.
# 
# If you want to learn more about using tensor networks as a diagrammatic tool, check out `these amazing lecture notes <https://arxiv.org/pdf/1912.10049>`_ by J.Biamonte. In addition, check out `this website <https://tensornetwork.org/about/>`_ for great explanations on many important algorithms and tensor network structures by Flatiron Institute  .  

```

2025-01-19 23:29 UTC, EmilianoG-byte commented
Thank you for the comments @justinpickering! I will be addressing them latest by Tuesday :)

I just wanted to ask: is there room to leave any emoji? I understand the need to make it a relatively serious demo, but as a long-term Pennylane fan, one of the things I appreciate the most about the brand was how approachable/playful everything Pennylane do is. That was something that, in my perspective as a user, differentiated Pennylane from all the dozens of papers/tutorials out there addressing the same topic.

I understand I might have overused emojis, so I cut already quite a few using @alvaro-at-xanadu's comments. Perhaps some of them can be left strategically, similar to this other demo that also uses them: https://pennylane.ai/qml/demos/tutorial_how_to_import_qiskit_noise_models

2025-01-19 23:32 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.metadata.json
> +    "title": "Tutorial: ABC of tensor networks",
Sounds good to me :)

Not sure about a cool idea for the thumbnail in that case 🤔

2025-01-20 10:18 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +If you are well-versed in the topics of quantum computing or quantum information, chances are you have heard (maybe a lot) about tensor networks. In fact, tensor networks are a rather widespread "too
I am not sure, since the notation used there is slightly different than the one used in this tutorial and can end up being a bit confusing. See for instance the conversation on the difference between $T_{i,j}$ and $(T)_{i,j}$ we had below with @alvaro-at-xanadu.

Maybe instead we can link the other tutorial: https://pennylane.ai/qml/demos/tutorial_How_to_simulate_quantum_circuits_with_tensor_networks

this is actually what I had in mind when writing this paragraph.

2025-01-20 10:22 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +Then, building on this introduction, in the :ref:`second part <part_two>` we explore topics aimed at more seasoned readers. Check this section out if you want to understand how tensor networks and qu
I have seen this expression used in other demos: https://pennylane.ai/qml/demos/tutorial_constant_depth_mps_prep

which I think keeps the "relaxed"/approachable tone I mentioned in my main comment.

2025-01-20 12:21 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.metadata.json
> +    "relatedContent": []
Sounds good, I have also the `tutorial_mps`one!

2025-01-20 12:29 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.metadata.json
> +    ],
I have added "quantum computing" and "algorithms" (a bit of a stretch but somehow related since we explain algorithms to use tn to simulate a qc). Should I erase "Getting Started" since it was not part of the options you mentioned?

2025-01-20 12:56 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +# Intermezzo
The origin is Italian but is widely used in plays, opera and arts. I thought it was a  commonly (enough) known word. We can add the clarification but I am afraid it takes away "the charm" by adding a synonym - similar to explaining a joke

2025-01-20 13:16 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +# This means :math:`T^1_{i,j,k}` and :math:`T^2_{l,j,m}` are two rank-3 tensors, where the index :math:`j` *picks* the elements in the column vector while the other two indices correspond to the indi
Thank you for catching this! Fixed :)

2025-01-20 13:23 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.metadata.json
> +    "seoDescription": "An introductory tutorial to tensor networks.",
How about something similar to yours emphasising its applicability to both beginners and advanced users:

```suggestion
    "seoDescription": "Discover the fundamentals of tensor networks with this comprehensive demo. Learn how tensors generalize vectors and matrices, explore their intuitive diagrams, and see how they connect to quantum circuits, with insights for both beginners and advanced readers."",
```

2025-01-20 13:37 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +# Matrix-matrix and matrix-vector multiplications are familiar operations within the context of quantum computing. We can now study these operations through the lens of the tensor notation introduced
Do you mean a demo that uses this or a `Pennylane.operation`? https://docs.pennylane.ai/en/stable/code/api/pennylane.operation.Operation.html

2025-01-20 14:54 UTC, justinpickering commented on demonstrations/tutorial_tn_basics.py
> +# Intermezzo
Thanks @EmilianoG-byte - let's leave as-is :)

2025-01-20 14:56 UTC, justinpickering commented on demonstrations/tutorial_tn_basics.metadata.json
> +    "seoDescription": "An introductory tutorial to tensor networks.",
Looks good to me! :+1:

2025-01-20 14:57 UTC, justinpickering commented on demonstrations/tutorial_tn_basics.metadata.json
> +    ],
"Getting started" is a category that isn't included in my list, sorry for the confusion. Let's leave it in.

2025-01-20 15:17 UTC, Qottmann commented on demonstrations/tutorial_tensor_network_basics.py
> +=============================================================
```suggestion
r"""Introducing tensor networks for quantum practicioners
=========================================================
```

2025-01-20 15:17 UTC, Qottmann commented on demonstrations/tutorial_tensor_network_basics.py
> +----------------------------------------------------------
do the same here (super minor stuff)

2025-01-20 21:55 UTC, justinpickering commented on demonstrations/tutorial_tn_basics.py
> +# This means :math:`T^1_{i,j,k}` and :math:`T^2_{l,j,m}` are two rank-3 tensors, where the index :math:`j` *picks* the elements in the column vector while the other two indices correspond to the indi
Hey @EmilianoG-byte - I still see this rendering issue 🤔, I will re-open this

2025-01-20 22:11 UTC, justinpickering commented on demonstrations/tutorial_tn_basics.py
> +First, we start by answering the question: **what is a tensor** ⁉️
@EmilianoG-byte - The main problem here is SEO. A question mark before the demo title might improve SEO for tensor searches. This may signal to Google that the following content provides an explanation.

2025-01-20 22:53 UTC, justinpickering reviewed
Thanks for addressing the comments, @EmilianoG-byte :) Just another suggestion here for the outro.

>I just wanted to ask: is there room to leave some of the emojis/phrases I didn't commit from your suggestions? I understand the need to make it a relatively serious demo, but as a long-term Pennylane fan, one of the things I appreciate the most about the brand is how approachable/playful everything Pennylane does is. That was something that, in my perspective as a user, differentiated Pennylane from all the dozens of papers/tutorials out there addressing the same topic.


Great point! We definitely want to make sure the demos stay engaging and approachable, especially with this type of introductory material. It's about finding a balance throughout, and we appreciate you being mindful of that in your edits.

2025-01-20 22:53 UTC, justinpickering commented on demonstrations/tutorial_tensor_network_basics.py
> +# If you want to learn more about using tensor networks as a diagrammatic tool, check out `these amazing lecture notes <https://arxiv.org/pdf/1912.10049>`_ by J.Biamonte. In addition, check out `this
```suggestion
# If you want to learn more about using tensor networks as a diagrammatic tool, check out these amazing `lecture notes on quantum tensor networks <https://arxiv.org/pdf/1912.10049>`_ by J.Biamonte. In addition, check out the `Tensor Network website <https://tensornetwork.org/about/>`_ for great explanations on many important algorithms and tensor network structures by Flatiron Institute  .  
```

2025-01-21 11:47 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +# This means :math:`T^1_{i,j,k}` and :math:`T^2_{l,j,m}` are two rank-3 tensors, where the index :math:`j` *picks* the elements in the column vector while the other two indices correspond to the indi
There was a missing semicolon before "math", which I added. Now the problem I think is that the demo hasn't rendered because there is an issue with the metadata. I fixed it a couple of times but I don't understand what the latest error is asking me to do with the references section 😰. Could you please take a look?

2025-01-21 11:58 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +First, we start by answering the question: **what is a tensor** ⁉️
Oh I see. I had not thought about it 🤔 but actually that makes a lot of sense.. Thank you for clarifying it! I have now changed it :)

2025-01-21 12:00 UTC, EmilianoG-byte commented on demonstrations/tutorial_tensor_network_basics.py
> +----------------------------------------------------------
Done :)

2025-01-21 22:32 UTC, justinpickering commented on demonstrations/tutorial_tn_basics.py
> +# This means :math:`T^1_{i,j,k}` and :math:`T^2_{l,j,m}` are two rank-3 tensors, where the index :math:`j` *picks* the elements in the column vector while the other two indices correspond to the indi
Ah right, thanks for fixing that, too :) @EmilianoG-byte

2025-01-21 22:48 UTC, justinpickering commented on demonstrations/tutorial_tn_basics.py
> +# Matrix-matrix and matrix-vector multiplications are familiar operations within the context of quantum computing. We can now study these operations through the lens of the tensor notation introduced
I mean if a PennyLane operation can accomplish this, then we should add a link in here for it.

2025-01-21 23:05 UTC, justinpickering reviewed
Just a couple more areas that can get hyperlinked :)

2025-01-21 23:05 UTC, justinpickering commented on demonstrations/tutorial_tensor_network_basics.py
> +If you are well-versed in the topics of quantum computing or quantum information, chances are you have heard (quite often) about tensor networks. In fact, tensor networks are a widely used tool with
```suggestion
If you are well-versed in the topics of `quantum computing <https://pennylane.ai/qml/what-is-quantum-computing>`__ or quantum information, chances are you have heard (quite often) about tensor networks. In fact, tensor networks are a widely used tool with applications ranging across physics, math, and computer science.
```

2025-01-21 23:05 UTC, justinpickering commented on demonstrations/tutorial_tensor_network_basics.py
> +#
```suggestion
# To end this section, we want to discuss a common example of a tensor network contraction arising in quantum computing, namely the **CNOT** gate. The `CNOT gate <https://docs.pennylane.ai/en/stable/code/api/pennylane.CNOT.html>`__ can be expressed in the computational basis as
#
```

2025-01-21 23:05 UTC, justinpickering commented on demonstrations/tutorial_tensor_network_basics.py
> +#   More generally, we can find decompositions of multi-qubit gates into local tensors employing the ubiquitous singular value decomposition (SVD). This method is explained in detail in our :doc:`int
```suggestion
#   More generally, we can find decompositions of multi-qubit gates into local tensors employing the ubiquitous singular value decomposition (`SVD <https://docs.pennylane.ai/en/stable/code/api/pennylane.math.svd.html>`__). This method is explained in detail in our :doc:`introduction to matrix product states for quantum practitioners demo </demos/tutorial_mps>`. This decomposition is helpful when contracting non-local tensors, as is often required in quantum circuits.
```

2025-01-22 22:11 UTC, EmilianoG-byte commented on demonstrations/tutorial_tn_basics.py
> +# Matrix-matrix and matrix-vector multiplications are familiar operations within the context of quantum computing. We can now study these operations through the lens of the tensor notation introduced
How about this: https://docs.pennylane.ai/en/stable/code/api/pennylane.math.dot.html?

2025-01-23 15:56 UTC, justinpickering reviewed
Fix for spelling mistake in title.

2025-01-23 15:56 UTC, justinpickering commented on demonstrations/tutorial_tensor_network_basics.metadata.json
> +    "title": "Introducing tensor networks for quantum practicioners",
```suggestion
    "title": "Introducing tensor networks for quantum practitioners",
```

2025-01-23 15:56 UTC, justinpickering commented on demonstrations/tutorial_tensor_network_basics.py
> +r"""Introducing tensor networks for quantum practicioners
```suggestion
r"""Introducing tensor networks for quantum practitioners
```

2025-01-23 17:14 UTC, merged

2025-01-23 18:51 UTC, EmilianoG-byte commented
Thank you for adding the final fixes and merging the tutorial @justinpickering and @alvaro-at-xanadu, and thank you for the reviews @Qottmann :). I learned a lot through the thorough reviews.

I am really glad to see this finally merged! What is the next step? (i.e. when can I expect to see the tutorial up?) :D.

2025-01-24 04:20 UTC, justinpickering commented
Great work @EmilianoG-byte on this demo and seeing it through to the finish line! 👏 :) The demo has been deployed live: https://pennylane.ai/qml/demos/tutorial_tensor_network_basics

It is planned to be featured on PennyLane socials on Wed, Jan 29 at 9AM ET. 

Feel free to contact Alvaro or myself (justin@xanadu.ai) if you have any other suggestions/requests.