ZNE demo using catalyst
PennyLaneAI/qml pull request #1207
Opened 2024-09-05 06:54 UTC by natestemen

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Remember to do a grammar check of the content you include.
- [x] All tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

----
If you are writing a demonstration, please answer these questions to facilitate the marketing process.

* GOALS — Why are we working on this now?

  *Eg. Promote a new PL feature or show a PL implementation of a recent paper.*

* AUDIENCE — Who is this for?

  *Eg. Chemistry researchers, PL educators, beginners in quantum computing.*

* KEYWORDS — What words should be included in the marketing post?

* Which of the following types of documentation is most similar to your file? 
(more details [here](https://www.notion.so/xanaduai/Different-kinds-of-documentation-69200645fe59442991c71f9e7d8a77f8))
    
- [ ] Tutorial
- [ ] Demo
- [ ] How-to

2024-09-05 22:43 UTC, josh146 commented on demonstrations/tutorial_zne_catalyst.py
> +========================================
```suggestion
Digital Zero-Noise Extrapolation with Catalyst
==============================================
```

2024-09-06 11:46 UTC, vprusso reviewed
I know this is still a WIP and some of the chunks I made comments are are block-commented out, so happy to take subsequent passes on this as it is developed!

2024-09-06 11:46 UTC, vprusso commented on demonstrations/tutorial_zne_catalyst.py
> +The circuits we use here will be ..., and the method of execution will be a noisy simulation
```The circuits we use here will be ..., ```. Is the ellipsis a placeholder for types of circuits used?

2024-09-06 11:46 UTC, vprusso commented on demonstrations/tutorial_zne_catalyst.py
> +# for ZNE. In particular we will need to specify
```suggestion
In particular we will need to specify:
```

2024-09-06 11:46 UTC, vprusso commented on demonstrations/tutorial_zne_catalyst.py
> +# Next we'll choose a method for scaling the noise. This needs to be defined as a python string.
```suggestion
# Next, we'll choose a method to scale the noise. This needs to be defined as a Python string.
```

2024-09-06 11:46 UTC, vprusso commented on demonstrations/tutorial_zne_catalyst.py
> +# But there's still a big unanswered question! _If I can do this all in PennyLane, what is Catalyst
This is actually a great question and one that took me a while to thoroughly understand and appreciate!

2024-09-07 05:56 UTC, natestemen commented on demonstrations/tutorial_zne_catalyst.py
> +The circuits we use here will be ..., and the method of execution will be a noisy simulation
Yup exactly! @cosenal is going to fill in some of the code, and I wasn't sure what he was changing the circuits too :)

2024-09-07 06:00 UTC, natestemen commented on demonstrations/tutorial_zne_catalyst.py
> +# Next we'll choose a method for scaling the noise. This needs to be defined as a python string.
Thanks! Done in https://github.com/PennyLaneAI/qml/pull/1207/commits/faa3c18a47afe62a06f691868cf69a5465c702f5.

2024-09-07 06:00 UTC, natestemen commented on demonstrations/tutorial_zne_catalyst.py
> +# for ZNE. In particular we will need to specify
Changed in https://github.com/PennyLaneAI/qml/pull/1207/commits/faa3c18a47afe62a06f691868cf69a5465c702f5.

2024-09-19 14:45 UTC, cosenal commented
@josh146 @dime10 @nathanshammah The tutorial is ready for review. 
(I am not the owner of the PR, so I can't change the title, but please ignore the `[Draft]` label)

2024-09-19 16:12 UTC, vprusso approved these changes

2024-09-30 17:14 UTC, cosenal commented on pyproject.toml
> +pennylane-qrack = "0.9.4"
I will move these to a section outside the note

2024-09-30 17:14 UTC, cosenal commented on pyproject.toml
> +    { version = "2.1.2", source = "PyPI", markers = "sys_platform == 'darwin' and platform_machine == 'arm64'" },
This is out-of-scope of the PR, but it was useful to set up the poetry ennvironment for me locally on Mac OS X Sequoia on M2

2024-10-01 18:30 UTC, WrathfulSpatula approved these changes

2024-10-01 18:30 UTC, WrathfulSpatula commented on demonstrations/tutorial_zne_catalyst.py
> +os.environ["QRACK_GATE_DEPOLARIZATION"] = str(NOISE_LEVEL)
The default setting for `QRACK_GATE_DEPOLARIZATION` in the absence of any explicit environment variable just happens to be 0.01, happily. So, even if this environment variable isn't picked up from the shell, the behavior will match what's expected. Further, for reasons that aren't totally clear to me, I think that setting `os.environ` key-value pairs _will_ work as expected in a Jupyter-Notebook environment, but it might be worth pointing out to users (as I just recently learned) that, in a simple Python script shell, the environment variables _must_ be set in the shell _before_ the Python interpreter has the opportunity to set `os.environ` key-value pairs, to be seen by any shared library called by the Python code.

I'm not requesting a specific change, though maybe we want to explain this to readers of the tutorial, just "FYI."

2024-10-01 18:30 UTC, WrathfulSpatula commented on pyproject.toml
> +pennylane-qrack = "0.9.4"
This should be `pennylane-qrack = "0.9.7"`, now. (The PyQrack version is already the latest.)

2024-10-01 19:29 UTC, dime10 commented on demonstrations/tutorial_zne_catalyst.py
> +os.environ["QRACK_GATE_DEPOLARIZATION"] = str(NOISE_LEVEL)
Any chance we can move the parameter to the device constructor? I think that would circumvent all these issues

2024-10-03 01:25 UTC, josh146 requested changes
Really nicely written tutorial, thanks @natestemen!

I've left some comments and suggestions.

---

One thing that comes to mind -- it would be quite nice to show that the _compilation_ time scales a lot better when using Catalyst compared to not. However, this would require choosing a circuit that has a large amount of structure, and automatically capturing the for/if statements.

The two-design template does indeed have a lot of structure, but it unfortunately won't be captured here:

https://github.com/PennyLaneAI/pennylane/blob/1a143d2762aecc9637c3106a1d737d3c4b8a97b0/pennylane/templates/layers/simplified_two_design.py#L171-L187

The only way we could capture it here is by manually coding up the decomposition in the tutorial, and using `@qjit(autograph=True)`.

Having said that, this suggestion is likely a lot of work, so not needed/a nice-to-have improvement!

2024-10-03 01:25 UTC, josh146 commented on demonstrations/tutorial_zne_catalyst.metadata.json
> +    "title": "Digital Zero-Noise Extrapolation with Catalyst",
```suggestion
    "title": "Digital zero-noise extrapolation with Catalyst",
```

2024-10-03 01:25 UTC, josh146 commented on demonstrations/tutorial_zne_catalyst.py
> +Digital Zero-Noise Extrapolation with Catalyst
```suggestion
Digital zero-noise extrapolation with Catalyst
```

2024-10-03 01:25 UTC, josh146 commented on demonstrations/tutorial_zne_catalyst.py
> +`Catalyst <https://docs.pennylane.ai/projects/catalyst/en/stable/index.html>`_.
```suggestion
In this tutorial, you will learn how to use error mitigation, and in particular 
the Zero-Noise Extrapolation (ZNE) technique, in combination with `Catalyst <https://docs.pennylane.ai/projects/catalyst>`_, a framework for quantum
just-in-time (JIT) compilation with PennyLane. 
We'll demonstrate how to generate noise-scaled circuits, execute them on a noisy quantum
simulator, and use extrapolation techniques to estimate the zero-noise result, all while
leveraging JIT compilation through
Catalyst.
```

2024-10-03 01:25 UTC, josh146 commented on demonstrations/tutorial_zne_catalyst.py
> +the demo `QJIT compilation with Qrack and Catalyst <https://pennylane.ai/qml/demos/qrack/>`_.
```suggestion
the demo :doc:`QJIT compilation with Qrack and Catalyst <qrack>`.
```

2024-10-03 01:25 UTC, josh146 commented on demonstrations/tutorial_zne_catalyst.py
> +2. **Exponential extrapolation**.
```suggestion
Catalyst provides two methods for perfoming this extrapolationl; **polynomial extrapolation**, and **exponential extrapolation**.
```

2024-10-03 01:25 UTC, josh146 commented on demonstrations/tutorial_zne_catalyst.py
> +a Python library developed by Unitary Fund.
```suggestion
Using ZNE with Pennylane
------------------------

The demo :doc:`Error mitigation with Mitiq and PennyLane <tutorial_error_mitigation>`
shows how ZNE, along with other error mitigation techniques, can be carried out in Pennylane by using `Mitiq <https://github.com/unitaryfund/mitiq>`__, 
a Python library developed by Unitary Fund.
```

Could also be a nice place to cite the mitiq paper :)

2024-10-03 01:25 UTC, josh146 commented on demonstrations/tutorial_zne_catalyst.py
> +`Differentiating quantum error mitigation transforms <https://pennylane.ai/qml/demos/tutorial_diffable-mitigation/>`_.
```suggestion
ZNE in particular is also offered out of the box in Pennylane as a *differentiable* error mitigation technique,
for usage in combination with variational workflows. More on this in the tutorial 
:doc:`Differentiating quantum error mitigation transforms <tutorial_diffable-mitigation>`.
```

2024-10-03 01:25 UTC, josh146 commented on demonstrations/tutorial_zne_catalyst.py
> +---------------------
```suggestion
```
I think this new section title is not so much needed, it can be merged into the previous section

2024-10-03 01:25 UTC, josh146 commented on demonstrations/tutorial_zne_catalyst.py
> +(JIT) compilation, starting from Catalyst v0.8.1.
```suggestion
On top of the error mitigation routines offered in Pennylane, ZNE is also available for just-in-time 
(JIT) compilation.
```
(since the tutorial is 'time invariant')

2024-10-03 01:25 UTC, josh146 commented on demonstrations/tutorial_zne_catalyst.py
> +pure Pennylane vs. Pennylane Catalyst with JIT.
@natestemen I feel like this section (everything from "Using ZNE with Pennylane" to here) could actually be moved and merged into the tutorial introduction (it almost reads a bit like the introduction, and has some useful info, e.g., 'at the end of the tutorial, we will compare...')

2024-10-03 01:25 UTC, josh146 commented on demonstrations/tutorial_zne_catalyst.py
> +--------------
```suggestion
Defining the mirror circuit
---------------------------
```

Maybe a bit more explanatory?

2024-10-03 01:25 UTC, josh146 commented on demonstrations/tutorial_zne_catalyst.py
> +from catalyst import qjit, mitigate_with_zne
Minor, but we typically don't import `qjit` from `catalyst`, but instead use `qml.qjit`.

2024-10-03 01:25 UTC, josh146 commented on demonstrations/tutorial_zne_catalyst.py
> +#    `local`)
```suggestion
# 1. The method for scaling this noise up (in Catalyst there are two options: ``global`` and
#    ``local``)
```

2024-10-03 01:25 UTC, josh146 commented on demonstrations/tutorial_zne_catalyst.py
> +pure Pennylane vs. Pennylane Catalyst with JIT.
This also reduces the amount of text in the tutorial and allows the reader to get to the code faster

2024-10-03 01:25 UTC, josh146 commented on demonstrations/tutorial_zne_catalyst.py
> +# to measure execution time of `mitigated_circuit_qjit` vs. `mitigated_circuit`.
```suggestion
# to measure execution time of ``mitigated_circuit_qjit`` vs. ``mitigated_circuit``:
```

2024-10-03 01:25 UTC, josh146 commented on demonstrations/tutorial_zne_catalyst.py
> +# To showcase the impact of JIT compilation, let's use Python's timeit module
```suggestion
# To showcase the impact of JIT compilation, let's use Python's ``timeit`` module
```

2024-10-03 01:25 UTC, josh146 commented on demonstrations/tutorial_zne_catalyst.py
> +# whenever the device of choice is not supported by Catalyst. To help the users orient themselves,
```suggestion
# whenever the device of choice is not supported by Catalyst. To help,
```
Minor, but I tend to try and avoid using 'users' in, uh, user-facing documentation 😅

2024-10-03 01:25 UTC, josh146 commented on demonstrations/tutorial_zne_catalyst.py
> +#          -
```suggestion
# .. list-table::
#     :widths: 30 20 20 20 20 30
#     :header-rows: 1
#
#     * - **Framework**
#       - **ZNE folding**
#       - **ZNE extrapolation**
#       - **Differentiable**
#       - **JIT**
#       - **other QEM techniques**
#     * - Pennylane + Mitiq
#       - global, local, random
#       - polynomial, exponential
#       -
#       -
#       - PEC, CDR, DDD, REM
#     * - Pennylane transforms
#       - global, local
#       - polynomial, exponential
#       - ✅
#       -
#       -
#     * - Catalyst (experimental)
#       - global, local
#       - polynomial, exponential
#       - ✅
#       - ✅
#       -
```

2024-10-03 13:52 UTC, cosenal commented on demonstrations/tutorial_zne_catalyst.py
> +2. **Exponential extrapolation**.
I'll commit this manually, because of the typo.

2024-10-03 13:53 UTC, cosenal commented on demonstrations/tutorial_zne_catalyst.py
> +(JIT) compilation, starting from Catalyst v0.8.1.
I agree that the tutorial is 'time invariant', but it won't work if the users have Catalyst v<0.8.1

2024-10-03 13:56 UTC, cosenal commented on demonstrations/tutorial_zne_catalyst.py
> +from pennylane import numpy as np
fair, here we aren't using any feature of the pennylane numpy wrapper anyway

2024-10-03 13:58 UTC, cosenal commented on demonstrations/tutorial_zne_catalyst.py
> +os.environ["QRACK_GATE_DEPOLARIZATION"] = str(NOISE_LEVEL)
I support this. In fact a nice API would be if we could pass the noise model to the device. Something like
```
..., noise_model('depolarizing', NOISE_LEVEL), ...
```

2024-10-03 22:11 UTC, dime10 commented on demonstrations/tutorial_zne_catalyst.py
> +(JIT) compilation, starting from Catalyst v0.8.1.
Note that since we'll have to make another release, we should update this to 8.2 (if we plan on keeping it).

2024-10-05 16:15 UTC, WrathfulSpatula commented on demonstrations/tutorial_zne_catalyst.py
> +os.environ["QRACK_GATE_DEPOLARIZATION"] = str(NOISE_LEVEL)
Done! With `pennylane-qrack>=0.10.0` and `pyqrack>=1.31.0`, you have a numeric constructor argument: `noise`. (I took the liberty of updating the tutorial.)

2024-10-05 18:07 UTC, cosenal commented on demonstrations/tutorial_zne_catalyst.py
> +os.environ["QRACK_GATE_DEPOLARIZATION"] = str(NOISE_LEVEL)
Love it, thanks @WrathfulSpatula. And I appreciate you updating the tutorial directly!

2024-10-09 10:01 UTC, ikurecic reviewed
Thank you, @natestemen . I've left some comments and suggestions for non-technical aspects of the Demo. Please let me know if you have any questions or concerns.

After you take a look at these comments, we will still be missing @josh146 's approval, and then it will be ready for merging and we can coordinate the launch via Discord.

2024-10-09 10:10 UTC, ikurecic commented on demonstrations/tutorial_zne_catalyst.py
> +#       - **other QEM techniques**
```suggestion
#       - **Other QEM techniques**
```

2024-10-09 10:11 UTC, ikurecic commented on demonstrations/tutorial_zne_catalyst.py
> +# .. list-table::
The resultant table doesn't look super perfect in the preview, in case you want to tweak something with the widths? Or even use an image instead.
![image](https://github.com/user-attachments/assets/9bc72e81-4716-4ad0-984a-cb214fd5ed47)

2024-10-09 14:58 UTC, cosenal commented on demonstrations/tutorial_zne_catalyst.metadata.json
> +            "affiliation": "Unitary Fund"
@ikurecic do we also remove the files in `_static/authors` then?

2024-10-09 15:04 UTC, cosenal commented on demonstrations/tutorial_zne_catalyst.metadata.json
> +            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_qjit_compile_grovers_algorithm_with_catalyst.png"
are those thumbnails just placeholders?

2024-10-09 15:08 UTC, cosenal commented on demonstrations/tutorial_zne_catalyst.py
> +and implements a noise model. For more about the integration of Qrack and Catalyst, see
Imo that link would confuse the reader, since the Qrack noise model we use in this tutorial isn't an instance of actual Pennylane `NoiseModel`s, which in turn can't be used because they aren't yet supported by Catalyst.

2024-10-09 15:48 UTC, ikurecic commented on demonstrations/tutorial_zne_catalyst.metadata.json
> +            "affiliation": "Unitary Fund"
@cosenal , yes, you can remove those files.

2024-10-09 15:49 UTC, ikurecic commented on demonstrations/tutorial_zne_catalyst.metadata.json
> +            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_qjit_compile_grovers_algorithm_with_catalyst.png"
@cosenal , whoops, I mistakenly put the wrong thumbnails in, thanks so much for noticing. I'll fix this now.

2024-10-09 15:54 UTC, ikurecic commented on demonstrations/tutorial_zne_catalyst.metadata.json
> +            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_qjit_compile_grovers_algorithm_with_catalyst.png"
That should be fixed now. Thanks for the tip.

2024-10-09 19:27 UTC, natestemen commented on demonstrations/tutorial_zne_catalyst.py
> +# .. include:: ../_static/authors/nate_stemen.txt
@ikurecic should this stay here, or is this created as part of the build process now?

2024-10-10 08:47 UTC, ikurecic commented on demonstrations/tutorial_zne_catalyst.py
> +# .. include:: ../_static/authors/nate_stemen.txt
@natestemen You can remove it. It doesn't cause any trouble to keep it, but you can remove it.

2024-10-10 10:54 UTC, ikurecic commented on demonstrations/tutorial_zne_catalyst.py
> +and implements a noise model. For more about the integration of Qrack and Catalyst, see
If you don't like it, then we can keep it out, for sure.

2024-10-10 10:55 UTC, ikurecic commented on demonstrations/tutorial_zne_catalyst.py
> +------------------------
Would it be possible to either rename this section (for example, 'Demo overview') or simply put in an image (the OGthumbnail at 70% width) instead of the section title?
It's quite a confusing structure for readers as it is right now.

2024-10-10 10:56 UTC, ikurecic commented on demonstrations/tutorial_zne_catalyst.py
> +pure PennyLane vs. PennyLane Catalyst with JIT.
```suggestion
At the end of the tutorial, we will compare the execution time of ZNE routines in
pure PennyLane vs. PennyLane and Catalyst with JIT.
```
For example, this would be more correct.

2024-10-10 14:51 UTC, cosenal commented on demonstrations/tutorial_zne_catalyst.py
> +# .. list-table::
Regarding this table, Romain mentioned on Discord that those zne functions in Catalyst are not yet differentiable. @rmoyard is that still the case? In which case, should I remove the checkmark from the Catalyst/Differentiable cell?

2024-10-10 14:51 UTC, cosenal commented on demonstrations/tutorial_zne_catalyst.py
> +------------------------
I agree, good suggestion. Done in https://github.com/PennyLaneAI/qml/pull/1207/commits/bc166cff32447e039fcc305a12aad611a4296762

2024-10-10 18:39 UTC, josh146 commented on demonstrations/tutorial_zne_catalyst.py
> +-----------
```suggestion
What is zero-noise extrapolation (ZNE)
--------------------------------------
```

2024-10-10 18:40 UTC, josh146 approved these changes
Tutorial looks great 😍

2024-10-10 18:40 UTC, josh146 commented on demonstrations/tutorial_zne_catalyst.py
> +and the references therein), let's first review what happens when using the protocol in practice.
nice!

2024-11-07 14:19 UTC, rmoyard commented on pyproject.toml
> +pennylane-qrack = "0.10.0"
```suggestion
pennylane-qrack = "0.10.6"
```

2024-11-07 14:19 UTC, rmoyard commented on pyproject.toml
> +pyqrack = "1.31.0"
```suggestion
pyqrack = "1.32.12"
```

2024-11-08 11:04 UTC, ikurecic reviewed
Thanks @cosenal and @natestemen , I have left just a couple of minor suggestions, and I will check in with you about the timeline.

2024-11-08 11:04 UTC, ikurecic commented on demonstrations/tutorial_zne_catalyst.py
> +Here we build a simple mirror circuit starting off a unitary 2-design.
```suggestion
Here we build a simple mirror circuit starting off a `unitary 2-design <https://en.wikipedia.org/wiki/Quantum_t-design>`__. 
```
Let's include a web reference.

2024-11-13 12:28 UTC, cosenal commented on demonstrations/tutorial_zne_catalyst.metadata.json
> +            "username": "cosenal"
done – thanks

2024-11-15 11:15 UTC, ikurecic commented on demonstrations/tutorial_zne_catalyst.py
> +# we conclude with a landscape of the QEM techniques available on the PennyLane ecosystem.
```suggestion
# we conclude with a landscape of the QEM techniques available in the PennyLane ecosystem.
```

2024-11-15 11:16 UTC, ikurecic commented on demonstrations/tutorial_zne_catalyst.metadata.json
> +    "dateOfLastModification": "2024-09-09T00:00:00+00:00",
```suggestion
    "dateOfPublication": "2024-11-15T00:00:00+00:00",
    "dateOfLastModification": "2024-11-15T00:00:00+00:00",
```

2024-11-15 16:52 UTC, ikurecic approved these changes

2024-11-15 16:52 UTC, merged