Update qchem demos to be JAX or JAX/JIT compatible
PennyLaneAI/qml pull request #1211
Opened 2024-09-05 18:32 UTC by austingmhuang

Title:
Update qchem demos to be JAX or JAX/JIT compatible

Summary:
As we phase out autograd, we need to ensure that our current qchem demos can work with either vanilla numpy or jax. Demos that are JIT compatible were made to use JIT as well. For demos that don't have any differentiation, we opt to use vanilla numpy.

Notes: the qubit tapering demo is not JIT compatible due to 2 issues: 1) Wire ordering is not ascending (Not a bug, but might need attention) 2) qml.taper_operation() uses the Exp operator, which has a conditional statement (https://github.com/PennyLaneAI/pennylane/issues/5993)

Relevant references:

Possible Drawbacks:

Related GitHub Issues:
[[sc-69776](https://app.shortcut.com/xanaduai/story/69776)]

2024-10-06 21:48 UTC, josh146 commented on demonstrations/tutorial_adaptive_circuits.py
> +    qml.BasisState.compute_decomposition(hf_state, wires=range(qubits))
@austingmhuang I'm curious, what is causing the issue here?

2024-10-15 17:34 UTC, austingmhuang commented on demonstrations/tutorial_adaptive_circuits.py
> +    qml.BasisState.compute_decomposition(hf_state, wires=range(qubits))
Think this is a mistake on my part. You need to use qml.BasisState.compute_decomposition for JIT but for this demo there's no such requirement.

2024-10-21 15:33 UTC, soranjh requested changes
Thanks @austingmhuang for these updates. Left some comments.

2024-10-21 15:33 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +H_tapered = qml.Hamiltonian(jnp.real(jnp.array(H_tapered_coeffs)), H_tapered_ops)
Why we need to recast to jax array again?

2024-10-21 15:33 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +    qml.BasisState.compute_decomposition(jnp.array([1, 1]), wires=H_tapered.wires)
Not sure we should decompose.

2024-10-21 15:33 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +    qml.BasisState.compute_decomposition(state_tapered, wires=H_tapered.wires)
Not sure we should decompose.

2024-10-21 15:33 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +    grads = catalyst.grad(tapered_circuit)(params)
Is `catalyst.grad` advantageous over `jax.grad`?

2024-10-22 15:26 UTC, austingmhuang commented on demonstrations/tutorial_mapping.py
> -
I reverted this change since it was accidental.

2024-10-22 18:16 UTC, austingmhuang commented on demonstrations/tutorial_chemical_reactions.py
> +        qml.BasisState.compute_decomposition(hf, wires=range(qubits))
For this one you do need compute_decomposition since we are jitting the update_step function. For reference it's done in this [demo ](https://pennylane.ai/qml/demos/tutorial_how_to_quantum_just_in_time_compile_vqe_catalyst/) as well.

`from jax import numpy as jnp

hf = np.array(dataset.hf_state)

@qml.qjit
@qml.qnode(dev)
def cost(params):
    qml.BasisState.compute_decomposition(hf, wires=range(qubits))
    qml.DoubleExcitation(params[0], wires=[0, 1, 2, 3])
    qml.DoubleExcitation(params[1], wires=[0, 1, 4, 5])
    return qml.expval(H)

init_params = jnp.array([0.0, 0.0])

cost(init_params)`

2024-10-22 18:18 UTC, austingmhuang commented on demonstrations/tutorial_chemical_reactions.py
> +    @qml.qjit
If I remember correctly,`qml.grad` dispatches to `catalyst.grad` when using jax arrays. The previous version I had catalyst.grad but qml.grad also works just as fine. I can change it back to catalyst.grad though.

2024-10-22 18:22 UTC, austingmhuang commented on demonstrations/tutorial_chemical_reactions.py
> +        grads = qml.grad(circuit)(params)
I think they all work. [In the closed PR we mention that qml.grad dispatches to catalyst.grad, which works for quantum gradients, as opposed to jax.grad which only works for classical gradients.](https://github.com/PennyLaneAI/qml/pull/1183#discussion_r1708429551)

2024-10-22 18:24 UTC, austingmhuang commented on demonstrations/tutorial_chemical_reactions.py
> +    @qml.qjit
qjit is also more performant here since we're using the lightning device.

2024-10-22 18:41 UTC, austingmhuang commented on demonstrations/tutorial_initial_state_preparation.py
> +def cost_fn(param):
Not a duplicate. I renamed it to cost_fn_cisd to make it clear that we are using a different initial state here.

2024-10-22 18:42 UTC, austingmhuang commented on demonstrations/tutorial_initial_state_preparation.py
> +    if len(results_hf) % 5 == 0:
copy paste error 😅

2024-10-22 18:43 UTC, austingmhuang commented on demonstrations/tutorial_qubit_tapering.py
> +H_tapered = qml.Hamiltonian(jnp.real(jnp.array(H_tapered_coeffs)), H_tapered_ops)
`jnp.real()` needs jnp.array for its argument. H_tapered_coeffs is not a jax array initially so there is no recasting.

2024-10-22 18:44 UTC, austingmhuang commented on demonstrations/tutorial_qubit_tapering.py
> +    grads = catalyst.grad(tapered_circuit)(params)
Not in this case I think. Should be the same.

2024-10-22 18:46 UTC, austingmhuang commented on demonstrations/tutorial_classically_boosted_vqe.py
> +jax.config.update("jax_enable_x64", True) # use double-precision numbers
For most of the tutorials I did add this line. I think maybe it should be added to all tutorials but it's not necessary if you're working with only H2.

2024-10-22 21:05 UTC, austingmhuang commented on demonstrations/tutorial_initial_state_preparation.py
> +mol = gto.M(atom=[["H", (0, 0, 0)], ["H", (0, 0, R)], ["H", (0, 0, 2 * R)]], charge=1)
This looks fine I think. 
![Screenshot 2024-10-22 at 5 04 54 PM](https://github.com/user-attachments/assets/3c8410c5-7492-4d3e-be0d-d50a990a4992)

2024-10-23 15:19 UTC, soranjh requested changes
Thanks @austingmhuang, left my final set of comments. They are mainly about being consistent in using `qml.grad` and `jax.config.update`.

2024-10-23 15:19 UTC, soranjh commented on demonstrations/tutorial_chemical_reactions.py
> +        qml.BasisState.compute_decomposition(hf, wires=range(qubits))
OK.

2024-10-23 16:41 UTC, austingmhuang commented on demonstrations/tutorial_qubit_tapering.py
> +H_tapered = qml.Hamiltonian(jnp.real(jnp.array(H_tapered_coeffs)), H_tapered_ops)
It's cause it's pointed to master right now. On master everything gets hard casted to pnp arrays so that's why this line is here. I think if we use the latest changes in the jax qchem pr then we shouldnt need to do this, but I can double check.

2024-10-23 16:42 UTC, austingmhuang commented on demonstrations/tutorial_qubit_tapering.py
> +    grads = catalyst.grad(tapered_circuit)(params)
We are not qjitting so qml.grad will dispatch to autograd.

2024-10-23 16:49 UTC, austingmhuang commented on demonstrations/tutorial_adaptive_circuits.py
> +    qml.BasisState.compute_decomposition(hf_state, wires=range(qubits))
Think I missed this one. Removed as well.

2024-10-23 16:52 UTC, austingmhuang commented on demonstrations/tutorial_eqnn_force_field.py
> -jax.config.update("jax_enable_x64", True)
Not sure. I reverted the changes back to what is in the original demo. I'm assuming one is to set it so that jax uses the CPU and the other is just to enable 64 bit precision, whereas all the other demos only need to enable 64 bit precision.

2024-10-24 13:58 UTC, obliviateandsurrender submitted a review, later dismissed

2024-10-24 13:58 UTC, obliviateandsurrender commented on demonstrations/tutorial_adaptive_circuits.py
>  geometry = np.array([[0.0, 0.0, 0.0], [0.0, 0.0, 2.969280527]])
Consider fixing the `UserWarning: Contains tensors of types {'autograd', 'jax'};` in this tutorial.

2024-10-24 13:58 UTC, obliviateandsurrender commented on demonstrations/tutorial_chemical_reactions.py
> +# .. include:: ../_static/authors/juan_miguel_arrazola.txt
I think we could include his username instead of the author file.

2024-10-24 13:58 UTC, obliviateandsurrender commented on demonstrations/tutorial_classically_boosted_vqe.py
>  coordinates = np.array([[0.0, 0.0, -0.6614], [0.0, 0.0, 0.6614]])
Consider using `jnp` here or somewhere later to deal with the `UserWarning: Contains tensors of types {'autograd', 'jax'};`.

2024-10-24 13:58 UTC, obliviateandsurrender commented on demonstrations/tutorial_eqnn_force_field.py
> +jax.config.update('jax_platform_name', 'cpu')
Do we really need this? Shouldn't by default this run on the `CPU`?

2024-10-24 13:58 UTC, obliviateandsurrender commented on demonstrations/tutorial_eqnn_force_field.py
> +            np.kron(Z, Z)
Could be squeezed in one line I guess.

2024-10-24 13:58 UTC, obliviateandsurrender commented on demonstrations/tutorial_givens_rotations.py
> +# .. include:: ../_static/authors/juan_miguel_arrazola.txt
Same as above.

2024-10-24 13:58 UTC, obliviateandsurrender commented on demonstrations/tutorial_givens_rotations.py
>  import numpy as np
We could shift this to where we use `binary_repr` (unless `jax.numpy` doesn't have any equivalent functionality)

2024-10-24 13:58 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_quantum_just_in_time_compile_vqe_catalyst.py
> +import numpy as np
We don't need `jax` numpy here?

2024-10-24 13:58 UTC, obliviateandsurrender commented on demonstrations/tutorial_initial_state_preparation.py
>  wf_hf = import_state(hf_primer)
Does `import_state` work with `jnp`?

2024-10-24 14:25 UTC, austingmhuang commented on demonstrations/tutorial_eqnn_force_field.py
> +jax.config.update('jax_platform_name', 'cpu')
It's in the original demo... I could delete it or just leave it be.

2024-10-24 17:16 UTC, austingmhuang commented on demonstrations/tutorial_how_to_quantum_just_in_time_compile_vqe_catalyst.py
> +import numpy as np
No, this part of the demo is not JIT compiled so we don't necessarily need JAX.

2024-10-24 17:17 UTC, austingmhuang commented on demonstrations/tutorial_initial_state_preparation.py
>  wf_hf = import_state(hf_primer)
When I did my checks it did work with jnp as well. But we don't use jnp here since vanilla np works just as fine (might be even faster with vanilla np, not sure though)

2024-10-24 17:44 UTC, austingmhuang commented on demonstrations/tutorial_chemical_reactions.py
> +# .. include:: ../_static/authors/juan_miguel_arrazola.txt
External user here so I keep

2024-10-24 17:52 UTC, obliviateandsurrender commented on demonstrations/tutorial_initial_state_preparation.py
>  wf_hf = import_state(hf_primer)
I just thought if we could use `jnp` instead we wouldn't need to import `numpy` 🤔 makes things more uniform (only if it is possible)

2024-10-24 18:10 UTC, austingmhuang commented on demonstrations/tutorial_initial_state_preparation.py
>  wf_hf = import_state(hf_primer)
I think it's preferred to only import jnp when it's necessary e.g. the VQE portion where we start doing jax.grad

For the beginning of the demo, i think we should stick to vanilla numpy since initial state preparation itself doesn't require `jnp`; I personally find it a little weird to use jnp there. I can delete this additional import numpy as np though since numpy is imported at the start of the demo 😅

2024-10-24 18:32 UTC, austingmhuang commented on demonstrations/tutorial_adaptive_circuits.py
>  geometry = np.array([[0.0, 0.0, 0.0], [0.0, 0.0, 2.969280527]])
Silencing this means I have to redefine H later. (Because the H created here needs to use pnp since we use the old optimizers). it is a bit strange but that's the only way to silence the errors

2024-10-24 18:35 UTC, austingmhuang commented on demonstrations/tutorial_classically_boosted_vqe.py
>  coordinates = np.array([[0.0, 0.0, -0.6614], [0.0, 0.0, 0.6614]])
Won't be silenced until we merge the jax qchem PR. It is silenced locally from what I can tell though once I switch to jnp.

2024-12-11 15:02 UTC, austingmhuang commented on demonstrations/tutorial_adaptive_circuits.py
> +*Author: Soran Jahangiri — Posted: 13 September 2021. Last updated: 8 August 2024*
Reminder to self: change these dates and etc.. to when we merge

2024-12-11 15:07 UTC, austingmhuang commented on demonstrations/tutorial_qubit_tapering.py
> +H_tapered = qml.Hamiltonian(jnp.real(jnp.array(H_tapered_coeffs)), H_tapered_ops)
Will revisit this before merging.

2024-12-11 18:46 UTC, soranjh reviewed
Thanks @austingmhuang, they all look good. Left some final comments mainly on using `jax.config.update("jax_enable_x64", True)`. Also, we shouldn't change PL numpy import in a [demo](https://github.com/PennyLaneAI/qml/pull/1211/files#diff-982958ef925d5917e90a062a6a3136f8e2eaeac386da1094fc8d6e98aab64a69) as it intentionaly uses an optimizer based on autograd in the first section.

2024-12-11 18:46 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +import jax
```suggestion
import jax
jax.config.update("jax_enable_x64", True)
```

2024-12-11 18:46 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +from jax import numpy as jnp
We also need 

```
import jax
jax.config.update("jax_enable_x64", True)
```

2024-12-11 20:41 UTC, soranjh approved these changes
Thanks @austingmhuang, please change the dates of modification before merging.

2024-12-12 18:26 UTC, KetpuntoG requested changes
Nice! Just a few comments

2024-12-12 18:26 UTC, KetpuntoG commented on demonstrations/tutorial_adaptive_circuits.py
> +*Author: Soran Jahangiri — Posted: 13 September 2021. Last updated: 8 August 2024*
This line can we removed directly 
The "last updated" should be changed in the metadata (`name_of_the_demo.metadata.json`)

2024-12-12 18:26 UTC, KetpuntoG commented on demonstrations/tutorial_adaptive_circuits.py
> +for n in range(10):
Why is this changed?

2024-12-12 18:26 UTC, KetpuntoG commented on demonstrations/tutorial_adaptive_circuits.py
> +*Author: Soran Jahangiri — Posted: 13 September 2021. Last updated: 8 August 2024*
(same for all the demos)

2024-12-12 18:26 UTC, KetpuntoG commented on demonstrations/tutorial_chemical_reactions.py
> +# .. include:: ../_static/authors/juan_miguel_arrazola.txt
Are you including a new author? If that is the case, you should include it too in the metadata

2024-12-12 18:26 UTC, KetpuntoG commented on demonstrations/tutorial_classically_boosted_vqe.py
>  relevant_basis_states = np.array(
should this be jnp?

2024-12-12 18:26 UTC, KetpuntoG commented on demonstrations/tutorial_givens_rotations.py
>  states = [np.binary_repr(i, width=6) for i in range(len(output)) if output[i] != 0]
I guess `binary_repr` is not in jax.numpy, right?

2024-12-12 18:26 UTC, KetpuntoG commented on demonstrations/tutorial_initial_state_preparation.py
> +import numpy as np
why we don't you jax here?

2024-12-12 18:26 UTC, KetpuntoG commented on demonstrations/tutorial_measurement_optimize.py
> +eigenvalues_XIZ = jnp.kron(jnp.kron(jnp.array([1, -1]), jnp.array([1, 1])), jnp.array([1, -1]))
Is it not possible to pass the lists as in numpy?

2024-12-12 18:26 UTC, KetpuntoG commented on demonstrations/tutorial_qchem_external.py
>      tutorial_givens_rotations Givens rotations for quantum chemistry
I get this warning on the demo:
`/home/runner/work/qml/qml/venv/lib/python3.10/site-packages/pennylane/qchem/molecule.py:145: UserWarning: The parameters coordinates, coeff, and alpha are not of the same interface. Please use the same interface for all 3 or there may be unintended behavior.
`

Not a blocker but putting in here just in case it is a potential bug

2024-12-12 20:55 UTC, austingmhuang commented on demonstrations/tutorial_adaptive_circuits.py
> +for n in range(10):
For performance reasons

2024-12-12 20:56 UTC, austingmhuang commented on demonstrations/tutorial_chemical_reactions.py
> +# .. include:: ../_static/authors/juan_miguel_arrazola.txt
No, I think I deleted an empty line at the bottom of the notebook or something.

2024-12-12 20:57 UTC, austingmhuang commented on demonstrations/tutorial_givens_rotations.py
>  states = [np.binary_repr(i, width=6) for i in range(len(output)) if output[i] != 0]
Don't think so. For some of these demos, since differentiability is not needed, we can just use vanilla numpy instead.

2024-12-12 20:59 UTC, austingmhuang commented on demonstrations/tutorial_initial_state_preparation.py
> +import numpy as np
We do use JAX when it is time to differentiate stuff (See 2nd half of demo). For the beginning parts, vanilla numpy is more performant I think.

2024-12-12 21:00 UTC, austingmhuang commented on demonstrations/tutorial_classically_boosted_vqe.py
>  relevant_basis_states = np.array(
No, I don't think this is being differentiated in any part of the workflow. So I don't think it's necessary to use jnp here. I mean you could probably use it without any error...

2024-12-12 21:02 UTC, austingmhuang commented on demonstrations/tutorial_measurement_optimize.py
> +eigenvalues_XIZ = jnp.kron(jnp.kron(jnp.array([1, -1]), jnp.array([1, 1])), jnp.array([1, -1]))
I think so, but we would basically be importing vanilla numpy just for these few lines of code I think.

2024-12-12 21:03 UTC, austingmhuang commented on demonstrations/tutorial_qchem_external.py
>      tutorial_givens_rotations Givens rotations for quantum chemistry
We have a PR to fix this bug. https://github.com/PennyLaneAI/pennylane/pull/6707

2024-12-12 22:59 UTC, KetpuntoG approved these changes
Thanks, looks good!
(the metadata would still need to be updated)

2024-12-13 20:29 UTC, merged