Fix complex warnings
PennyLaneAI/qml pull request #1217
Opened 2024-09-11 18:46 UTC by mudit2812

As name says.

* Updated `tutorial_vqe_vqd` to cast `h2.hf_state` as a numpy array. It's a pennylane numpy array by default, which was causing warnings about mixing autograd and jax interfaces.
* Cast `data` in `tutorial_eqnn_force_field` as complex, since we're `einsum`-ing it with a complex tensor.

These changes will not fix all `ComplexWarning`s. That will require changes in pennylane (see [here](https://github.com/PennyLaneAI/pennylane/pull/6256)).

2024-09-12 14:50 UTC, mudit2812 commented
Once `v0.38.1` is released, I will run CI in this PR with the `build-all-demos` label and add filter all `ComplexWarning`s to be errors.

2024-09-16 18:40 UTC, dwierichs requested changes
Had 3 small suggestions.

There seems to be a problem with the deployed version, not sure what that is?

Otherwise lgtm!

2024-09-16 18:40 UTC, dwierichs commented on demonstrations/tutorial_vqe_vqd.py
> +#     To improve veiwability of this tutorial, we will suppress any ``ComplexWarning``'s which may raised during optmization.
```suggestion
#     To improve viewability of this tutorial, we will suppress any ``ComplexWarning``'s which may be raised during optimization.
```

2024-09-16 18:40 UTC, dwierichs commented on demonstrations/tutorial_eqnn_force_field.py
> +        equivariant_encoding(alphas[i, 0], jnp.asarray(data, dtype=complex)[i % active_atoms, ...], wires=[i])
These two changes lead to horizontal scrollbars, unfortunately...

```suggestion
        equivariant_encoding(
            alphas[i, 0], jnp.asarray(data, dtype=complex)[i % active_atoms, ...], wires=[i]
        )
```

2024-09-16 18:40 UTC, dwierichs commented on demonstrations/tutorial_eqnn_force_field.py
> +                alphas[i, d + 1], jnp.asarray(data, dtype=complex)[i % active_atoms, ...], wires=[i]
```suggestion
                alphas[i, d + 1],
                jnp.asarray(data, dtype=complex)[i % active_atoms, ...],
                wires=[i],
```

2024-09-16 18:43 UTC, mudit2812 commented
> There seems to be a problem with the deployed version, not sure what that is?

Yeah I'm not sure what that's about. If I manually try to open the deployment I'm seeing the most recent changes, so I'm confused. Regardless, after committing your suggestions, hopefully the next deployment will succeed.

2024-09-16 18:57 UTC, dwierichs approved these changes
:rocket:

2024-09-16 19:42 UTC, mudit2812 commented
Looks like the deployment is successful, but the action showed as failed because the step for adding/updating the comment about the deployment on the PR fails.See [here](https://github.com/PennyLaneAI/qml/actions/runs/10890656245/job/30219849910).

2024-09-16 19:46 UTC, mudit2812 commented
Since I've verified that all demos build and no new warnings are introduced, I'm removing the build-all-demos label.

2024-09-16 20:03 UTC, soranjh approved these changes

2024-09-16 21:18 UTC, mudit2812 commented on demonstrations/tutorial_vqe_vqd.py
> +#     To improve viewability of this tutorial, we will suppress any ``ComplexWarning``'s which may be raised during optimization.
Sphinx fails without the tick. You can't have an alphabet immediately after inline code or latex.

2024-09-16 21:18 UTC, merged