Add demo "How to Quantum Just-In-Time Compile Grover's Algorithm with Catalyst"
PennyLaneAI/qml pull request #1219
Opened 2024-09-18 19:47 UTC by joeycarter

**Title:** How to Quantum Just-In-Time Compile Grover's Algorithm with Catalyst

**Summary:** This demo uses the existing [Grover's Algorithm](https://pennylane.ai/qml/demos/tutorial_grovers_algorithm/) tutorial to describe how to just-in-time (JIT) compile a quantum circuit using Catalyst. It also includes runtime benchmarks to demonstrate the performance improvements that JIT compiling with Catalyst offers.

**Relevant references:** [L. K. Grover (1996) "A fast quantum mechanical algorithm for database search"](https://dl.acm.org/doi/10.1145/237814.237866)

**Possible Drawbacks:** None

**Related GitHub Issues:** None

[[sc-72939](https://app.shortcut.com/xanaduai/story/72939/convert-another-selected-demo)]

----
If you are writing a demonstration, please answer these questions to facilitate the marketing process.

* GOALS — Why are we working on this now?

  * Promote Catalyst by demonstrating the performance improvements it offers by QJIT compiling a relatively simple quantum circuit.

* AUDIENCE — Who is this for?

  * Users of PennyLane looking to compile and optimize their circuits for better performance.

* KEYWORDS — What words should be included in the marketing post?

  * Grover's algorithm
  * Catalyst
  * QJIT

* Which of the following types of documentation is most similar to your file? 
(more details [here](https://www.notion.so/xanaduai/Different-kinds-of-documentation-69200645fe59442991c71f9e7d8a77f8))
    
- [ ] Tutorial
- [ ] Demo
- [x] How-to

2024-09-18 20:13 UTC, rauletorresc approved these changes
I would use by default the `lightning.qubit` device in the baseline algorithm explanation, instead of doing it with the `default.qubit` device, for the same reason explained in the demo: Catalyst does not support the latter at the moment.  I would also remove it from the benchmark and show only the results with  `lightning.qubit`. Finally, I would write a small note stating non-supported devices of Catalyst. What do you think?

2024-09-18 20:13 UTC, rauletorresc commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +"""
```suggestion

*Author: Joey Carter
"""
```

2024-09-19 13:22 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +"""
Thanks! Fixed.

2024-09-19 13:34 UTC, joeycarter commented
> I would use by default the `lightning.qubit` device in the baseline algorithm explanation, instead of doing it with the `default.qubit` device, for the same reason explained in the demo: Catalyst does not support the latter at the moment. I would also remove it from the benchmark and show only the results with `lightning.qubit`. Finally, I would write a small note stating non-supported devices of Catalyst. What do you think?

My reasoning for using `default.qubit` as the baseline device was that the spirit of this demo was to take an existing PennyLane circuit, in this case the one from https://pennylane.ai/qml/demos/tutorial_grovers_algorithm/, and make it work with Catalyst. Switching the device from `default.qubit` to `lightning.qubit` is one of the required steps, and so including it in this demo makes it explicit what needs to be done for the circuit to work with Catalyst. My preference would be to leave it in.

There's an argument to be made to leave `default.qubit` out of the benchmarks, since it does consume the most CPU time to execute. I included it to really drive home each incremental performance improvement a user gets as they make the necessary modifications to their circuit. I'll go with popular opinion on this one whether to include or exclude it.

I would prefer not to list out the devices that Catalyst does not support, and just refer to the documentation. Suppose the list of supported devices changes over time, I think it would be better to not have to keep the demo in sync with that list.

2024-09-19 13:51 UTC, rmoyard reviewed
Great demo, can you double check the build failure? After that we can check that it renders properly.

2024-09-19 13:51 UTC, rmoyard commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +        Catalyst to quantum just-in-time (QJIT) compile a PennyLane circuit
Minor: just-in-time compile quantum circuits and not quantum just-in-time compile

2024-09-19 13:51 UTC, rmoyard commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +circuit_qjit = qml.qjit(circuit_lightning)
Autograph is not =True in the qjit, therefore it is not able to capture the control flow like the for loops. Either turn it on here or change the code to use catalyst for loops

2024-09-19 13:51 UTC, rmoyard commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# 1. Executing the circuit using ``"default.qubit"``.
I think just make it clear that the first option does not use Catalyst, but I think it is good to keep.

2024-09-19 15:03 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +circuit_qjit = qml.qjit(circuit_lightning)
Is that necessary in this example? The range of the for loops depend on constant values, rather than on traced objects, i.e. `wires`, `omega`, `M`, and `N`, which are all constant once `NUM_QUBITS` has been set. The code runs as-is, so using autograph or Catalyst-style for loops seems like unnecessary complexity.

2024-09-19 15:12 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +        Catalyst to quantum just-in-time (QJIT) compile a PennyLane circuit
Fixed.

2024-09-19 15:13 UTC, joeycarter commented
> Great demo, can you double check the build failure? After that we can check that it renders properly.

Thanks @rmoyard! The build failure was due to the path to the preview image thumbnail not existing. I've put in the original Grover's algorithm preview image as a placeholder, just to check the build and rendering, which we can replace later on.

2024-09-19 17:27 UTC, rmoyard commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +circuit_qjit = qml.qjit(circuit_lightning)
Can you try to benchmark it and see if there is any advantage? Just do `qjit(autograph=true)`

2024-09-19 17:38 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +circuit_qjit = qml.qjit(circuit_lightning)
Actually when I do `qjit(autograph=True)` without changing anything else, I get the familiar JAX `TracerBoolConversionError` in the call to `qml.FlipSign` because of its native-python branching control flow :facepalm:

Shall I just leave it as-is?

2024-09-19 17:55 UTC, rmoyard commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +circuit_qjit = qml.qjit(circuit_lightning)
Thanks, yes keep it as it is!

2024-09-19 17:55 UTC, rmoyard approved these changes
Great first demo :100:

2024-09-20 21:25 UTC, dime10 reviewed
Nice work @joeycarter, that's a cool demo! :)

The benchmarking is done quite nicely, I like the comparison of the different stages (include the first load!).

2024-09-20 21:25 UTC, dime10 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# additional, small overhead incurred to cache the compiled code for faster access later on. Every
Wow I didn't think this overhead would be so big, an order of magnitude in this case! Is thus just the time spent on loading the shared libraries (like the program.so and the device.so)?

2024-09-23 02:51 UTC, josh146 requested changes
Wow, really nicely written how-to guide @joeycarter! Super clear and very well written.

I've left some suggestions throughout.

2024-09-23 02:51 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.metadata.json
> +    "dateOfLastModification": "2024-09-19T00:00:00+00:00",
Reminder to update this before merging :)

2024-09-23 02:51 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.metadata.json
> +    "seoDescription": "How to QJIT compile Grover's Algorithm with Catalyst",
```suggestion
    "seoDescription": "See how to use Catalyst to just-in-time (QJIT) compile a PennyLane circuit implementing Grover's algorithm.",
```

2024-09-23 02:51 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.metadata.json
> +        }
```suggestion
        {
            "type": "demonstration",
            "id": "tutorial_grovers_algorithm",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_how_to_quantum_just_in_time_compile_vqe_catalyst",
            "weight": 1.0
        }
```

2024-09-23 02:51 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# proposed by Lov Grover in 1996 [#Grover1996]_, to solve "unstructured search" problems using a
```suggestion
# proposed by Lov Grover in 1996 [#Grover1996]_, to solve unstructured search problems using a
```

2024-09-23 02:51 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# `Grover's algorithm <https://pennylane.ai/qml/demos/tutorial_grovers_algorithm/>`__ is an `oracle
```suggestion
# :doc:`Grover's algorithm <tutorial_grovers_algorithm>` is an `oracle
```

2024-09-23 02:51 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# In the `Grover's Algorithm <https://pennylane.ai/qml/demos/tutorial_grovers_algorithm/>`__
```suggestion
# In the :doc:`Grover's Algorithm <tutorial_grovers_algorithm>`
```

2024-09-23 02:51 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# <https://docs.pennylane.ai/projects/catalyst/en/stable/dev/devices.html>`__.
```suggestion
# Catalyst. See the :doc:`Catalyst documentation <catalyst:dev/devices>`
# for the full list of devices supported by Catalyst.
```

For accessibility reasons, it's better to have the link text be descriptive of the page :)

2024-09-23 02:51 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# measure below. Furthermore, when we call the compiled QJIT object for the first time, there is an
```suggestion
# rather than at instantiation.
#
# The compilation step will incur some runtime overhead, which we will
# measure below. Furthermore, when we call the compiled QJIT object for the first time, there is an
```

2024-09-23 02:51 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# measure below. Furthermore, when we call the compiled QJIT object for the first time, there is an
@joeycarter at this point (where you are talking about executing the compiled code), it would be good to execute the function to show the output!

That would demonstrate to the reader that it is will return the exact same result as before.

2024-09-23 02:51 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +circuit_qjit = qml.qjit(circuit_lightning)
@joeycarter I had the same thought when reading the how-to, and so the context is this thread is useful context for a reader!

I recommend adding an aside to the text, e.g.,

```rest
.. note::

    The Catalyst :class:`~.qjit` decorator supports capturing
    control flow when specified using the :func:`~.for_loop`,
    :func:`~.while_loop`, and :func:`~.cond` functions, or additionally,
    can automatically capture native Python control flow via
    experimental :doc:`AutoGraph <catalyst:dev/autograph>` support.

    In this tutorial, however, as the for loops depend on custom
    values, ...

```

2024-09-23 02:51 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# <https://docs.pennylane.ai/projects/catalyst/en/stable/dev/quick_start.html>`__ guide for more
```suggestion
# documentation in the Catalyst :doc:`Quick Start <catalyst:dev/quick_start>` guide for more
```

2024-09-23 02:51 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# -----
```suggestion
# Footnotes
# ---------
```

2024-09-23 02:51 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# <https://docs.pennylane.ai/projects/catalyst/en/stable/index.html>`__.
```suggestion
# <https://docs.pennylane.ai/projects/catalyst>`__.
```

2024-09-23 02:51 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# <https://docs.pennylane.ai/projects/catalyst/en/stable/index.html>`__, a quantum just-in-time
```suggestion
# <https://docs.pennylane.ai/projects/catalyst>`__, a quantum just-in-time
```

2024-09-23 02:51 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# <https://docs.pennylane.ai/projects/lightning/en/stable/index.html>`__, which is a PennyLane
```suggestion
# <https://docs.pennylane.ai/projects/lightning>`__, which is a PennyLane
```

2024-09-23 02:51 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.metadata.json
> +    "title": "How to Quantum Just-In-Time Compile Grover's Algorithm with Catalyst",
```suggestion
    "title": "How to quantum just-in-time compile Grover's algorithm with Catalyst",
```

2024-09-23 02:51 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +How to Quantum Just-In-Time Compile Grover's Algorithm with Catalyst
```suggestion
How to quantum just-in-time compile Grover's algorithm with Catalyst
```

2024-09-23 02:51 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# Generalized Grover's Algorithm with PennyLane
```suggestion
# Generalized Grover's algorithm with PennyLane
```

2024-09-23 02:51 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# Quantum Just-In-Time Compiling the Circuit
```suggestion
# Quantum just-in-time compiling the circuit
```

2024-09-23 02:51 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# ----------------------
```suggestion
# Benchmarking
# ------------
```

2024-09-23 02:51 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +
```suggestion
dev = qml.device("default.qubit", wires=NUM_QUBITS)

@qml.qnode(dev)
def circuit_default_qubit():
    return grover_circuit(NUM_QUBITS)
```

2024-09-23 02:51 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +
Note: you could also do the following, for something more succinct:

```python
dev = qml.device("default.qubit", wires=NUM_QUBITS)
circuit_default_qubit = qml.QNode(dev, lambda: grover_circuit(NUM_QUBITS))
```

2024-09-23 02:51 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +
```suggestion
dev = qml.device("lightning.qubit", wires=NUM_QUBITS)

@qml.qnode(dev)
def circuit_lightning():
    return grover_circuit(NUM_QUBITS)
```

2024-09-23 02:51 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +
Similarly, you could also consider

```suggestion
dev = qml.device("lightning.qubit", wires=NUM_QUBITS)
circuit_lightning = qml.QNode(dev, lambda: grover_circuit(NUM_QUBITS))
```

2024-09-23 02:51 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.metadata.json
> +            "id": "joey_carter"
@joeycarter you'll need to make a PL profile, and set the `id` to be your username :)

You should then set the 'headline' of your profile to be the same as your bio in `joey_carter.txt`.

2024-09-23 15:10 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.metadata.json
> +            "id": "joey_carter"
Done—thanks for the reminder!

2024-09-23 15:35 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# additional, small overhead incurred to cache the compiled code for faster access later on. Every
Possibly, although I'm not sure exactly. When I have the time I'll profile the first and second calls to better pinpoint where the extra runtime is happening in the first.

2024-09-25 16:28 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +circuit_qjit = qml.qjit(circuit_lightning)
@josh146 I added this aside, along with a few more details. Let me know what you think.

2024-09-25 16:29 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# measure below. Furthermore, when we call the compiled QJIT object for the first time, there is an
Good point, I've added this in.

2024-09-25 16:38 UTC, joeycarter commented
I've refactored the `timeit` benchmarking; since I'm now running the compiled circuit earlier in the script to print out the results, we have to create a new qjit object of the circuit to get the runtime of the first call. I'm doing so with the `setup` input argument of `timeit`.

Interestingly, when I run this locally I no longer see a difference between the first-call runtime and subsequent-call runtimes. It's possible that when `timeit` was executing these commands in its own namespace, the compiled circuit ended up in some funky state that led to the small runtime overhead on the first call.

I'll see if I get the same result in the deployed version. If so, I'll remove the paragraph on the caching overhead, since this is likely the wrong interpretation of the larger runtime in the first call of the compiled circuit.

2024-09-25 17:31 UTC, dime10 commented
> Interestingly, when I run this locally I no longer see a difference between the first-call runtime and subsequent-call runtimes. It's possible that when `timeit` was executing these commands in its own namespace, the compiled circuit ended up in some funky state that led to the small runtime overhead on the first call.

If the first call is primarily spent on loading shared libraries, then creating a new QJIT object may not recreate that state accurately. This is just a wild guess, but it could be that a lot of the shared libs (besides the program one, since that one should be new) that are needed to execute a catalyst program are still loaded in the Python process.

If you comment out the first call earlier in the demo, does it revert it to the old results?

2024-09-25 18:02 UTC, joeycarter commented
> If the first call overhead is primarily spent on loading shared libraries, then creating a new QJIT object may not recreate that state accurately. This is just a wild guess, but it could be that a lot of the shared libs (besides the program one, since that one should be new) that are needed to execute a catalyst program are still loaded in the Python process.
> 
> If you comment out the first call earlier in the demo, does it revert it to the old results?

Ah, yes if I comment out the first call then it reverts to the old results, with the first QJIT call taking significantly longer than subsequent calls. On my machine I get

```
Native (default.qubit) runtime: (13.31 +/- nan) s
Native (lightning.qubit) runtime: (5.359 +/- 0.023) s
QJIT compilation runtime: (0.4419 +/- nan) s
QJIT (first call) runtime: (0.007347 +/- nan) s
QJIT (subsequent calls) runtime: (0.001503 +/- 0.00021) s
```

So the overhead appears to be in calling for the first time *any* instance of a qjit-compiled circuit, rather than calling every new `QJIT` object for the first time. Loading shared libraries sounds like a plausible explanation, I'll run a profiler on this script to see if that reveals where the runtime hotspot is.

2024-09-25 18:05 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +circuit_qjit = qml.qjit(circuit_lightning)
Awesome, thanks!

2024-09-25 18:07 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +#     documentation for more details on this subject.
```suggestion
#     The Catalyst :class:`~.qjit` decorator supports capturing control flow when specified using
#     the :func:`~pennylane.for_loop`, :func:`~pennylane.while_loop`, and :func:`~pennylane.cond` functions, or additionally,
#     can automatically capture native Python control flow via experimental :doc:`AutoGraph
#     <catalyst:dev/autograph>` support.
#
#     In this tutorial, however, you'll notice that our ``grover_circuit`` function is able to use
#     native Python control flow without the need to convert the Python ``for`` loops to the
#     qjit-compatible :func:`~.for_loop`, for instance, and without using AutoGraph. The reason we
#     are able to do so here is because the circuit we have compiled, ``circuit_lightning``, is:
#
#     * unparameterized, meaning it takes in no input argument, thus the control flow of the circuit
#     does not depend on any dynamic variables (whose values are known only at run time); and
#
#     * the ranges of the ``for`` loops depend only on static variables (i.e.,
#     constants known at compile time), in this case native-Python numerics and lists, and NumPy
#     arrays.
#
#     Hence, the complete control flow of the circuit is known at compile time, which allows
#     us to use native Python control-flow statements.
#
#     See the :doc:`Sharp bits and debugging tips <catalyst:dev/sharp_bits>` section of the Catalyst
#     documentation for more details on this subject.
```

2024-09-25 18:08 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +#     documentation for more details on this subject.
Minor, but bullet points might make the itemized list slightly easier to read!

2024-09-25 18:25 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +plt.yscale("log")
@joeycarter I might recommend actually removing the log scaling here, I'm not sure it's fully needed (and it seems to make compilation time look as slow as lightning, when it is 4x faster!)

2024-09-25 18:50 UTC, josh146 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +plt.yscale("log")
Perhaps, but as the qjit execution is already so much faster, maybe that will still be the main takeaway?

This feedback was based on three of us in the office looking at the plot, and saying

> wow, qjit execution is so much faster, but it takes just as long to compile as to execute with lightning!

2024-09-25 19:43 UTC, joeycarter commented
I profiled the first and second calls to the qjit-compiled circuit and in fact the hotspot is in the call to `jnp.asarray()` in [`CompiledFunction._exec()`](https://github.com/PennyLaneAI/catalyst/blob/v0.8.1/frontend/catalyst/compiled_functions.py#L172).

If we trace down the function call stack from `jnp.asarray`, we get to a jax function `dispatch.py:390(_device_put_sharding_impl)`. In the first call, this takes ~0.0086 s, and in the second only ~0.00005 s. Tracing down one step further in the stack, in the second (fast) call, the most time is spent in `dispatch.py:331(_put_x)`, but in the first call, the most time is spent in `pxla.py:1669(_get_default_device)` (~0.008 s). Tracing down even further in the slow call, a lot of time is spent in XLA, e.g. in `xla_bridge.py:737(_discover_and_register_pjrt_plugins)` (~0.0047 s) and in `xla_client.py:67(make_cpu_client)` (~0.0024 s). These functions are not called in the second qjit-object call.

That's a lot of text so here's a visualization! First, the first (slow) call:

![Screenshot from 2024-09-25 15-14-39](https://github.com/user-attachments/assets/2b6a5086-b86e-43f1-b72f-4f267b1bea59)

and the second (fast) call:

![Screenshot from 2024-09-25 15-14-52](https://github.com/user-attachments/assets/11118389-e13d-4a3c-a7dd-232178c0aee0)

If I'm understanding all of this correctly, the overhead isn't in Catalyst *per se*, but in loading a bunch of JAX and XLA things the first time we call `jnp.asarray()`.

In fact, if I throw in a `jnp.asarray([0.])` before the first qjit-object call, I can get the first and subsequent calls to be roughly on par with one another! (The first call is still a bit slower, perhaps because of some smaller overheads elsewhere).

This is getting far into the nitty-gritty details of the performance of Catalyst and JAX, and well beyond the scope of this demo, I think. I propose we not show the difference between the first call and the subsequent calls in the benchmarks, since I think it's a reasonable assumption that any user who cares about that level of performance will already be using JAX arrays in their programs and not notice any difference in the first and second calls to an AOT-compiled circuit. @josh146, @dime10, how does that sound?

2024-09-25 20:09 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# additional, small overhead incurred to cache the compiled code for faster access later on. Every
I've posted the more detailed profiling results below in the comments, we can follow-up there.

2024-09-25 20:12 UTC, josh146 commented
@joeycarter yep that sounds good to me! On another note, we discovered that the decomposition pathway for lightning+noqjit for `GroverOperator` is dynamic, and uses a magic number to change strategy at <13 qubits:

https://github.com/PennyLaneAI/pennylane-lightning/blob/master/pennylane_lightning/lightning_qubit/lightning_qubit.py#L177-L178

This is likely not optimal, as these magic numbers are not always the best and can lead to slowdowns near the boundary (e.g., 10-12 qubits). I'd be curious to rerun the demo at 13 or 14 qubits (where lightning and catalyst should use the _same_ decomposition strategy) to see what the outcome is?

2024-09-25 20:23 UTC, dime10 commented
Thanks @joeycarter, nice digging! So the overhead is not related to catalyst, happy to leave it at that and not show 1st vs 2nd call 👍

2024-09-25 20:35 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +plt.yscale("log")
This is what the benchmark plot looks like with the y-axis in linear scale:

![image](https://github.com/user-attachments/assets/b641c9a4-1f6d-49c3-9ed5-ac68ed50a9be)

I'm inclined to agree with @josh146. Normally when I'm displaying data on a plot that spans more than three orders of magnitude, I tend to put it in log scale. But, putting it in linear scale here really does drive home how much faster the QJIT calls are (it's so fast you can't even see the runtime on the plot!). The annotations are there with the numerical values, so no real information is lost putting it in linear scale either; someone can still look at this plot and easily determine that the QJIT call time is ~3000x faster than with `lighnting.qubit`.

2024-09-25 20:41 UTC, joeycarter commented
> Thanks @joeycarter, nice digging! So the overhead is not related to catalyst, happy to leave it at that and not show 1st vs 2nd call 👍

Thanks @dime10! Sounds good.

2024-09-25 21:05 UTC, dime10 commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +plt.yscale("log")
One thing of note is that there is quite a bit of variance in these measurements, an earlier plot had DQ at 7 seconds, now 16 🤔  Probably the build systems with highly variable load, but that is unfortunate.

2024-09-25 21:09 UTC, joeycarter commented
> On another note, we discovered that the decomposition pathway for lightning+noqjit for `GroverOperator` is dynamic, and uses a magic number to change strategy at <13 qubits:
> 
> https://github.com/PennyLaneAI/pennylane-lightning/blob/master/pennylane_lightning/lightning_qubit/lightning_qubit.py#L177-L178
> 
> This is likely not optimal, as these magic numbers are not always the best and can lead to slowdowns near the boundary (e.g., 10-12 qubits). I'd be curious to rerun the demo at 13 or 14 qubits (where lightning and catalyst should use the _same_ decomposition strategy) to see what the outcome is?

The results for 13+ qubits don't paint a very pretty picture, unfortunately.

Here's 13 qubits:

![qjit_13_qubits](https://github.com/user-attachments/assets/6ca2dcee-7dd8-4fd8-ad14-506a49b6c4f3)

14 qubits:

![qjit_14_qubits](https://github.com/user-attachments/assets/3b09cbb6-89fc-4b89-a1de-9c6edcae4079)

and 20 qubits:

![qjit_20_qubits](https://github.com/user-attachments/assets/d6ce81b3-a7ac-400c-9445-51a55f7bb5f2)

The general trend is that the qjit call times outperform lightning, although the advantage drops off as the number of qubits increases, but overall qjit compile time + call time is always slower than lightning for n_qubits > 12.

Choosing `NUM_QUBITS = 12` may be misleading if we're trying to advertise the performance improvements that Catalyst offers, but at the same time, for circuits with fewer than 13 qubits the performance gains are real. One option is to plot the runtimes as a function of the number of qubits, although that might warrant an explanation of the "magic" number 13 in lightning, which is probably beyond the scope of this demo. How would you like to proceed?

2024-09-30 15:06 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +plt.yscale("log")
**Conclusion:** The demo now uses a linear y-axis scale for the benchmarks.

2024-09-30 15:13 UTC, joeycarter commented
After discussing with @josh146 and others, we will keep this demonstration as is with 12 qubits for now, and revisit it should the behaviour of Lightning's decomposition strategy change.

I've also combined the benchmarks for the first and subsequent calls to the QJIT-compiled circuit, for the reasons discussed above. I've also modified the text to account for this change.

Finally, I've bumped the publication date in the metadata to Sep 30; I'll keep Josh's review comment open as a reminder in case we need to bump this date again. Otherwise, I believe the demo is now complete.

2024-10-01 12:09 UTC, ikurecic reviewed
Thanks, @joeycarter . I've added some easy suggestions to make sure everything looks good before we merge.
Please text me if you have any questions or concerns.

2024-10-01 12:09 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# At the time of writing, Catalyst does not support the ``"default.qubit"`` state-simulator device,
```suggestion
# At the time of writing, Catalyst is developed natively for `PennyLane's high-performance simulators <https://pennylane.ai/performance/>`__ and does not support the ``"default.qubit"`` state-simulator device,
```

2024-10-01 12:09 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# performant state simulators written in C++, and which is supported by Catalyst. See the
```suggestion
# performant state simulators written in C++. See the
```
Rephrased this part in the previous suggestion.

2024-10-01 12:09 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +#       compile time), in this case native-Python numerics and lists, and NumPy arrays.
```suggestion
#       compile time), in this case Python-native numerics and lists, and NumPy arrays.
```

2024-10-01 12:09 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# of magnitude better than the same circuit implemented in native Python.
Can you add a sentence 'selling' Catalyst, telling people where to go next if they'd like to use it further? I would suggest just linking the Quick Start page, as you already did earlier.

2024-10-01 12:09 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.metadata.json
> +    "references": [],
Can you add the references from the Demo here?

2024-10-01 13:44 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.metadata.json
> +            "id": "joeycarter"
Already done; `joeycarter` is my pennylane.ai username (https://pennylane.ai/profile/joeycarter).

2024-10-01 15:20 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +How to quantum just-in-time compile Grover's algorithm with Catalyst
I would prefer to avoid using (or defining) any acronyms in the title; the acronym "QJIT" is already defined in the text.

2024-10-01 15:24 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# respect to the native Python implementation.
Do you have a suggestion? I think the statements "which makes it possible to compile, optimize, and execute hybrid quantum–classical worflows" and "We will also measure the performance improvement we get from using Catalyst with respect to the native Python implementation" already explain why a PennyLane user would want to use Catalyst.

2024-10-01 15:29 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# the previous tutorial:
I would prefer to keep this as is. I start this section with

> In the :doc:\`Grover's Algorithm <tutorial_grovers_algorithm>\` tutorial, we saw how to implement...

so I think it should be clear from context that this is the "previous" tutorial we are referring to. I could also add the link again here to avoid any ambiguity.

2024-10-01 15:31 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# Quantum just-in-time compiling the circuit
We have already defined the acronym QJIT at this point, so I don't think we should redefine it in the section heading here.

2024-10-01 17:19 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +
I've changed the first link from the original Grover's algorithm demo to the codebook:

> [Grover’s algorithm](https://pennylane.ai/codebook/05-grovers-algorithm/) is an [oracle](https://pennylane.ai/codebook/04-basic-quantum-algorithms/02-the-magic-8-ball/)-based quantum algorithm...

I link to the original demo later on, so this connection is not lost.

2024-10-01 17:20 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# 3. Measure the resulting quantum state in the computational basis.
Thanks for pointing this out! Fixed.

2024-10-01 17:21 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +    """Prints the most probable states, and their probabilities, in descending order."""
I removed both commas.

2024-10-01 17:22 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# of magnitude better than the same circuit implemented in native Python.
I've added the line

> To learn more about Catalyst and how to use it to compile and optimize your quantum programs and workflows, check out the Catalyst [Quick Start](https://docs.pennylane.ai/projects/catalyst/en/stable/dev/quick_start.html) guide.

2024-10-01 17:25 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.metadata.json
> +    "references": [],
Done.

2024-10-01 17:28 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# [#NandC2000]_
Changed to

> We also saw (in Ref. [#NandC2000]_) that...

2024-10-01 17:32 UTC, joeycarter commented
Hi @ikurecic, thanks for your review! I've had a look at all your suggestions; I've made most of the changes you requested and had some follow-up questions and alternate suggestions for the others. Let me know what you think—feel free to resolve the conversations I've left open if you're happy with the changes.

2024-10-01 18:03 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.metadata.json
> +    "seoDescription": "See how to use Catalyst to just-in-time (QJIT) compile a PennyLane circuit implementing Grover's algorithm.",
This text (without the word "quantum") was suggested by @josh146. In some places we say, e.g. "use Catalyst to just-in-time compile a PennyLane circuit", while in others we say "use Catalyst to *quantum* just-in-time compile a PennyLane circuit". From a pure grammatical perspective, the former sounds better to me (it's not a quantum-just-in-time compilation, it's a just-in-time compilation of a quantum circuit). Although, I can see why we might want to include the word "quantum" to have the QJIT acronym make sense. Thoughts?

2024-10-02 09:32 UTC, ikurecic reviewed
Thanks, @joeycarter . A couple of minor things I spotted and that should be it. Ping me on Slack when you're done, so we can get it off the ground. I'll text Josh about approval, too.

2024-10-02 09:32 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.metadata.json
> +    "seoDescription": "See how to use Catalyst to just-in-time (QJIT) compile a PennyLane circuit implementing Grover's algorithm.",
I know what you mean, but for SEO description I would rather stuff more keywords than less. However, Josh's preference trumps mine. Thanks for explaining.

2024-10-02 09:32 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +How to quantum just-in-time compile Grover's algorithm with Catalyst
I think I will insist on this one, in that case. It looks a bit less 'clean', but it will make it a lot more likely the Demo gets picked up in search (nobody will be searching for the full expression).

2024-10-02 09:32 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# respect to the native Python implementation.
For example, in the conclusion you have this: 

> Catalyst offers a runtime performance several orders of magnitude better than the same circuit implemented in native Python.

That's a strong statement, you can include a small drop of it here. For example, like this:
> We will also measure the performance improvement we get from using Catalyst with respect to the native Python implementation, and show that the runtime performance of circuits implemented with Catalyst can be several orders of magnitude better!

2024-10-02 09:32 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# the previous tutorial:
Yeah, that's a great idea — do that, please.

2024-10-02 09:32 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# Quantum just-in-time compiling the circuit
I'm only adding these for search purposes. But if you add 'QJIT' to the main Demo title, you can forget about this suggestion.

2024-10-02 09:32 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# of magnitude better than the same circuit implemented in native Python.
Perfect, thank you.

2024-10-02 09:32 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.metadata.json
> +            "id": "joeycarter"
You didn't change `id` to `username`, though. :)
```suggestion
            "username": "joeycarter"
```

2024-10-02 09:32 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.metadata.json
> +            "id": "joeycarter"
By the way, you have a grammar error in the first sentence of your profile headline.

2024-10-02 09:33 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.metadata.json
> +    "dateOfLastModification": "2024-10-01T00:00:00+00:00",
```suggestion
    "dateOfPublication": "2024-10-02T00:00:00+00:00",
    "dateOfLastModification": "2024-10-02T00:00:00+00:00",
```

2024-10-02 13:35 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.metadata.json
> +            "id": "joeycarter"
Ah sorry! Didn't realize the keyword is `username` :slightly_smiling_face:

I fixed the type in my profile headline as well.

2024-10-02 13:37 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +How to quantum just-in-time compile Grover's algorithm with Catalyst
Fair enough. I'll add the "(QJIT)" to the title in the metadata as well.

2024-10-02 13:39 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# Quantum just-in-time compiling the circuit
Got it, thanks. I've added it to the main title so I'll keep it as is here.

2024-10-02 13:51 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# the previous tutorial:
Fixed!

2024-10-02 14:18 UTC, joeycarter commented
I've added the "do not merge" label since there's some discussion in the Performance Team about changing the decomposition strategy, which will change the benchmarks that we present. We'll need to re-evaluate these benchmarks before merging.

2024-10-08 16:03 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.metadata.json
> +    "dateOfLastModification": "2024-10-02T00:00:00+00:00",
tk

2024-10-08 16:03 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.metadata.json
> +    "canonicalURL": "/qml/demos/tutorial_qjit_compile_grovers_algorithm_with_catalyst",
```suggestion
```
An upcoming update removes this line.

2024-10-10 15:54 UTC, joeycarter commented
I pulled in the latest version of Lightning (@maliasadi confirmed that the issue with the decomposition strategy depending on a "magic" number of qubits has been fixed) and reran the benchmarks. Here are the results (running on my machine):

![grover_qjit_benchmark_nqubit_12](https://github.com/user-attachments/assets/4a356006-aa61-4e66-a0e2-2022c2e8dc83)

qjit execution time still wins out vs Lightning by about an order of magnitude, but the Catalyst compilation runtime is 20x longer than the Lightning runtime for this circuit.

@josh146 shall we go ahead and remove the benchmarks from this demo? If so, we'll also need to reword the text since we can't demonstrate a Catalyst compile+runtime advantage over Lightning.

2024-10-10 18:10 UTC, josh146 commented
@joeycarter oh, actually this plot is quite nice! I would be happy to keep it in informationally, but we would need to change the text in the demo. E.g., rather than talking about QJIT being faster for a _single_ execution, we could say that: while there is compilation overhead, runtime is then significantly faster, which will be beneficial if the function is executed multiple times with different inputs.

2024-10-11 17:13 UTC, dime10 commented
> > @joeycarter oh, actually this plot is quite nice! I would be happy to keep it in informationally, but we would need to change the text in the demo. E.g., rather than talking about QJIT being faster for a _single_ execution, we could say that: while there is compilation overhead, runtime is then significantly faster, which will be beneficial if the function is executed multiple times with different inputs.
> 
> Great, thanks! Let's do that then.

I agree with the framing of the compilation / runtime tradeoff that is typical for JIT, but note that the program in the demo is not parametrized at all. So as written, you would pay the compilation price for every input change.

2024-10-11 18:14 UTC, joeycarter commented
> I agree with the framing of the compilation / runtime tradeoff that is typical for JIT, but note that the program in the demo is not parametrized at all. So as written, you would pay the compilation price for every input change.

True, this is originally why I wanted to frame the demo in such a way that the circuit is parameterized to accept an arbitrary solution state. That way we could have JIT compiled the circuit once, and then run it multiple times with different solution states as input. Of course that led us to uncover the qjit-compatibility issues in the FlipSign and controlled-Z operators. I hope it's clear from the text earlier in the demo that the circuit is "static" as written, and compiled for specific solution states.

@josh146 and @ikurecic, I've updated the text to reflect the new benchmarks. Let me know if you have any additional feedback or suggestions.

Also, I see in [pyproject.toml](https://github.com/PennyLaneAI/qml/blob/master/pyproject.toml#L45) that we're pinned to Catalyst v0.8.1, so we'll need to update this to 0.8.2 when it's released to pull in the decomposition-strategy bug fix in Lightning.

2024-10-11 19:35 UTC, joeycarter commented
> Right, but as the demo is now, that invalidates the framing no?

I wouldn't say so, no. As it is now, the "objective" of the demo is to search for the $\vert 0\rangle ^{\otimes n}$ and $\vert 1\rangle ^{\otimes n}$ solution states with Grover's algo. We hard-code these solution states into the circuit, QJIT compile it and demonstrate that the circuit execution runtime is an order of magnitude faster than with `lightning.qubit`. So there's no need in this example to recompile the circuit with different inputs, since this is beyond the demo objective as we've defined it. All we're saying is that should a user need to need to compile their own circuit once and execute in multiple times, this is where they're especially likely to see an improvement from qjit, but this is not the purpose of this demonstration (it would have been nice to demonstrate this advantage with Grover's, we're just not able to with Catalyst right now).

2024-10-17 15:37 UTC, joeycarter commented
I've rebased to the `dev` branch to use the nightly releases of PennyLane/Lightning/Catalyst, which contain the fix to the magic-number decomposition issue discussed above.

2024-10-31 23:26 UTC, josh146 approved these changes

2024-11-05 17:13 UTC, ikurecic reviewed
I'm glad we got technical approval, @joeycarter , congrats!
I've left you just minor copy editing suggestions (please let me know if you'd like to have any support with these), and after that we should be ready to merge.
You should also rebase to master now.

2024-11-05 17:13 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +#       :class:`~.pennylane.FlipSign`, for each solution index :math:`\omega`.
```suggestion
#       :class:`~.pennylane.FlipSign`, for each solution index :math:`\omega.`
```

2024-11-05 17:13 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# the :doc:`previous tutorial <tutorial_grovers_algorithm>`:
```suggestion
# the :doc:`previous tutorial <tutorial_grovers_algorithm>`.
```

2024-11-05 17:13 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# states to be measured:
```suggestion
# states to be measured.
```

2024-11-05 17:13 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# Then, to QJIT compile our circuit with Catalyst, we simply wrap it with :func:`~pennylane.qjit`:
```suggestion
# Then, to QJIT compile our circuit with Catalyst, we simply wrap it with :func:`~pennylane.qjit`.
```

2024-11-05 17:13 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +#     qjit-compatible :func:`~.for_loop`, for instance, and without using AutoGraph. The reason we
```suggestion
#     QJIT-compatible :func:`~.for_loop`, for instance, and without using AutoGraph. The reason we
```

2024-11-05 17:13 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# We now have our QJIT object ``circuit_qjit``. A small detail to note in this case is that because
```suggestion
# We now have our QJIT object, ``circuit_qjit``. A small detail to note in this case is that because
```

2024-11-05 17:13 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# the function ``circuit_lightning`` takes no input arguments, Catalyst will in fact *ahead-of-time*
```suggestion
# the function ``circuit_lightning`` takes no input arguments, Catalyst will, in fact, *ahead-of-time*
```

2024-11-05 17:13 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# documentation in the Catalyst :doc:`Quick Start <catalyst:dev/quick_start>` guide for more
```suggestion
# documentation in the :doc:`Catalyst Quick Start<catalyst:dev/quick_start>` guide for more
```

2024-11-05 17:13 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# call the compiled circuit and confirm that we get the same results:
```suggestion
# call the compiled circuit and confirm that we get the same results.
```

2024-11-05 17:13 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +#     * unparameterized, meaning it takes in no input arguments, thus the control flow of the circuit
```suggestion
#     * Unparameterized, meaning it takes in no input arguments, thus the control flow of the circuit
```
For consistency.

2024-11-05 17:13 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +#     * the ranges of the ``for`` loops depend only on static variables (i.e., constants known at
```suggestion
#     * The ranges of the ``for`` loops depend only on static variables (i.e., constants known at
```

2024-11-05 17:13 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# achieved execution runtimes approximately an order of magnitude less than the PennyLane circuit
```suggestion
# achieved execution runtimes approximately an order of magnitude shorter than the PennyLane circuit
```

2024-11-05 17:13 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# workflows, check out the Catalyst :doc:`Quick Start <catalyst:dev/quick_start>` guide.
```suggestion
# workflows, check out the :doc:`Catalyst Quick Start<catalyst:dev/quick_start>` guide.
```

2024-11-05 17:13 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# .. include:: ../_static/authors/joey_carter.txt
```suggestion
```
You can remove this.

2024-11-05 19:31 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# searched by performing :math:`O(\sqrt{N})` queries on the database, whereas a classical search
Yes works with me.

2024-11-05 19:33 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# :math:`N` entries and say with high probability that the database contains the number being
I'll apply the other suggestion instead of this one (since they both add parentheses around "with high probability").

2024-11-05 19:46 UTC, joeycarter commented on _static/authors/joey_carter.png
Thanks! Removed in 7b40bcb9.

2024-11-05 19:46 UTC, joeycarter commented on _static/authors/joey_carter.txt
Removed in 7b40bcb9.

2024-11-05 19:47 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +"""
Removed in 4732beef

2024-11-05 19:48 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +
Seems not, this was copied over from the original Grover's algorithm demo. Removed in 4732beef

2024-11-05 19:50 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# More formally, the problem is defined as a search for a string of bits in a list containing
I'd prefer to keep this as is; "the problem" is defined above as the "unstructured search problem".

2024-11-05 19:56 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +#
Just so I understand what the problem is, is it that a line break might appear between the rendered math and the comma if the display width of the page is too narrow? i.e. something like this?

> Apply the Grover diffusion operator, $U_D$
> , implemented using...

I haven't observed this—the rendered math and the comma always stick together when making the display width narrower. Although maybe that's just on my browser.

I only bring this up because now the comma outside math mode and inside math mode are slightly different fonts and it looks odd. :slightly_smiling_face:

2024-11-05 19:59 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +#     * the ranges of the ``for`` loops depend only on static variables (i.e., constants known at
The first words in these bullets points shouldn't be capitalized here since they're part of a complete sentence: https://www.btb.termiumplus.gc.ca/tcdnstyl-chap?lang=eng&lettr=chapsect4&info0=4.33#zz4

2024-11-05 19:59 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +#     * unparameterized, meaning it takes in no input arguments, thus the control flow of the circuit
The first words in these bullets points shouldn't be capitalized here since they're part of a complete sentence: https://www.btb.termiumplus.gc.ca/tcdnstyl-chap?lang=eng&lettr=chapsect4&info0=4.33#zz4

2024-11-05 19:59 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +#     * the ranges of the ``for`` loops depend only on static variables (i.e., constants known at
Ditto

2024-11-06 08:52 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +#
I think this is on your browser. I understand what you mean, but these are orders from above and we have to do it.

2024-11-06 08:58 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +#     * unparameterized, meaning it takes in no input arguments, thus the control flow of the circuit
This is not a mandatory rule, but a suggestion. Because you have a very long run-on sentence here, which is not a common use case for this suggestion, I would recommend to capitalize the entries or rephrase them (into standalone sentences?) as a matter of internal consistency within the text. However, of course, if you have a strong opinion about this, please use the option that works best for you.

2024-11-06 14:16 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +#     * unparameterized, meaning it takes in no input arguments, thus the control flow of the circuit
I reworded this section in 07e8eeb5 to make the bullets standalone sentences.

2024-11-06 14:16 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +#     * the ranges of the ``for`` loops depend only on static variables (i.e., constants known at
Following up in the comment above.

2024-11-06 14:27 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +#
Done (f09e0a17)

2024-11-06 14:37 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# More formally, the problem is defined as a search for a string of bits in a list containing
Done (f137240d)

2024-11-06 14:51 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +# More formally, the problem is defined as a search for a string of bits in a list containing
Perfect!

2024-11-06 17:02 UTC, co9olguy commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +#
@joeycarter for interest, here's some examples of the rendering issues that can occur when punctuation is outside math and at the ege of the horizontal break

![image (3)](https://github.com/user-attachments/assets/291a24c8-538e-4bcc-acb2-422ccc4a1a14)
![image (2)](https://github.com/user-attachments/assets/afdf1565-9e4b-4663-8e60-81e0ff85b60d)

2024-11-06 19:31 UTC, joeycarter commented
Heads up, I've rebased this demo onto the `master` branch.

2024-11-06 20:01 UTC, joeycarter commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +#
Interesting, thanks @co9olguy for sharing. Shame that Sphinx can't automatically put a [non-breaking space](https://en.wikipedia.org/wiki/Non-breaking_space) in-between inline math and punctuation that immediately follows.

2024-11-06 20:20 UTC, co9olguy commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.py
> +#
yeah it's annoying that this doesn't work easily :cry:

2024-11-07 08:57 UTC, ikurecic commented on demonstrations/tutorial_qjit_compile_grovers_algorithm_with_catalyst.metadata.json
> +    "dateOfLastModification": "2024-11-06T00:00:00+00:00",
```suggestion
    "dateOfPublication": "2024-11-07T00:00:00+00:00",
    "dateOfLastModification": "2024-11-07T00:00:00+00:00",
```

2024-11-07 19:11 UTC, merged