[WIP] Fix demos to use jax that require grads
PennyLaneAI/qml pull request #1226
Opened 2024-10-01 20:08 UTC by austingmhuang

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Remember to do a grammar check of the content you include.
- [ ] All tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

----
If you are writing a demonstration, please answer these questions to facilitate the marketing process.

* GOALS — Why are we working on this now?

  *Eg. Promote a new PL feature or show a PL implementation of a recent paper.*

* AUDIENCE — Who is this for?

  *Eg. Chemistry researchers, PL educators, beginners in quantum computing.*

* KEYWORDS — What words should be included in the marketing post?

* Which of the following types of documentation is most similar to your file? 
(more details [here](https://www.notion.so/xanaduai/Different-kinds-of-documentation-69200645fe59442991c71f9e7d8a77f8))
    
- [ ] Tutorial
- [ ] Demo
- [ ] How-to

2024-10-15 21:23 UTC, austingmhuang commented on demonstrations/tutorial_mol_geo_opt.py
> +dev = qml.device("default.qubit", wires=num_wires)
For some reason lightning.qubit doesn't work with JAX here. Not sure why but I had to change to using default to get it working.

2024-10-21 15:49 UTC, soranjh requested changes
Thanks @austingmhuang. befor doing a full review, could you please make sure that this PR targets dev instead of master? Also, if there is any demo that does not require features in dev, their upgrade should be done in this [PR](https://github.com/PennyLaneAI/qml/pull/1211).

2024-10-21 15:49 UTC, soranjh commented on demonstrations/tutorial_resource_estimation.py
> +import jax
Let's just use vanilla numpy in this demo.

2024-10-21 15:49 UTC, soranjh commented on demonstrations/tutorial_mapping.py
> +                     [0.0, 0.0,  0.69434785]])
This demo is already updated in another [PR](https://github.com/PennyLaneAI/qml/pull/1211), correct?

2024-10-21 15:49 UTC, soranjh commented on demonstrations/tutorial_fermionic_operators.py
> +import numpy as np
Can we update this demo in this [PR](https://github.com/PennyLaneAI/qml/pull/1211) as well?

2024-10-22 18:47 UTC, austingmhuang commented on demonstrations/tutorial_mapping.py
> +                     [0.0, 0.0,  0.69434785]])
No, it's not updated in that PR. Well that PR had a one line change in this demo by accident.

2024-10-22 18:48 UTC, austingmhuang commented on demonstrations/tutorial_mapping.py
> +                     [0.0, 0.0,  0.69434785]])
This demo doesn't work without the requires_grad changes because it calls fermionic_hamiltonian directly

2024-10-22 18:49 UTC, austingmhuang commented on demonstrations/tutorial_fermionic_operators.py
> +import numpy as np
No, it cannot be done. This demo calls `electronic_integrals()` directly, which checks for requires_grad, leading to an error.

2024-12-12 18:28 UTC, KetpuntoG commented on demonstrations/tutorial_differentiable_HF.py
> +qml.qchem.hf_energy(mol)()
What is this line doing?

2024-12-12 20:47 UTC, austingmhuang commented on demonstrations/tutorial_differentiable_HF.py
> +    g_param = jax.grad(energy(), argnums=[0, 1, 2, 3])(*args)[0]
Yes 👍

2024-12-12 20:48 UTC, austingmhuang commented on demonstrations/tutorial_differentiable_HF.py
> +    g_param = jax.grad(energy(), argnums=[0, 1, 2, 3])(*args)[0]
We were doing that beforehand too (geom, alpha, coeff, and circuit_param were all labelled with `requires_grad=True`. We just update the UI to use jax UI instead.

2024-12-12 20:52 UTC, austingmhuang commented on demonstrations/tutorial_differentiable_HF.py
> +qml.qchem.hf_energy(mol)()
It is a bit of a hack to reset the information in `mol` to use numpy arrays instead of jax arrays. When we did `jax.grad(qml.qchem.hf_energy(mol), argnums=0)(geometry, mol.coeff, mol.alpha)`, internally some of the information of the molecule automatically uses jax arrays. This is great, but not for this graphing part, where we want to stick to using numpy.

2024-12-12 20:53 UTC, austingmhuang commented on demonstrations/tutorial_differentiable_HF.py
>  # The use of ``requires_grad=True`` specifies that the nuclear coordinates are differentiable
We should delete this line.

2024-12-12 20:54 UTC, austingmhuang commented on demonstrations/tutorial_mol_geo_opt.py
> +    bond_length.append(jnp.linalg.norm(x[0] - x[1]) * bohr_angs)
`x` is still the nuclear gradients. Just now we are manually updating its value instead of letting opt_x.step() take care of that.

2024-12-12 21:14 UTC, KetpuntoG approved these changes
Look good! please update the metadata before merging

2024-12-13 21:13 UTC, merged