How-to: Quantum Arithmetic
PennyLaneAI/qml pull request #1229
Opened 2024-10-04 10:54 UTC by gmlejarza

**Title:** How to use Quantum Arithmetic Operators [sc-74430]

**Summary:**  We show how to load a function into a quantum computer using Pennylane arithmetic operators.

----
If you are writing a demonstration, please answer these questions to facilitate the marketing process.

* GOALS — Why are we working on this now?

Promote and make people understand how to use quantum arithmetic operators in Pennylane.

* AUDIENCE — Who is this for?

Researchers working in quantum algorithms, beginners starting in quantum computing.

* KEYWORDS — What words should be included in the marketing post?

Quantum Arithmetic, Loading functions into quantum computers, Addition, Multiplication,

* Which of the following types of documentation is most similar to your file? 
(more details [here](https://www.notion.so/xanaduai/Different-kinds-of-documentation-69200645fe59442991c71f9e7d8a77f8))
    
- [x] How-to

2024-10-04 12:38 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +   qml.OutPoly(f, registers_wires=[wires["x"], wires["y"], wires["output"]])
I'm going to comment this line so we can deploy the demo in the meantime

2024-10-04 19:50 UTC, KetpuntoG reviewed
Great job @gmlejarza 🚀
I made a push to try to simplify the code as much as possible as it could be “intimidating” at first. In general everything is fine and to improve it I would try to be much more direct trying to keep this how-to short
On the other hand, if you have a thumbnail suggestion, I will request it on Monday 🎨

2024-10-04 19:50 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +are integer values. We will take the values :math:`a = 4`, :math:`b = 5`,:math:`c = 3` and :math:`d = 3`, defining the desired operator as:
some rendering issue  that I can't see now 🧐

2024-10-04 19:50 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +#  to load the constant :math:`a = 4` by using the Inplace addition operator :class:`~.pennylane.Adder`:
```suggestion
# Now, we can introduce the first quantum arithmetic operation to load :math:`f(x, y)`. The first step will be
# to load the constant :math:`a = 4` by using the Inplace addition operator :class:`~.pennylane.Adder`:
```

2024-10-04 19:50 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# the OutPlace addition operator :class:`~.pennylane.OutAdder` and the :class:`~.pennylane.Multiplier` previously employed.
```suggestion
#The last step will involve to load the monomial terms :math:`5x` and :math:`3y` by using the OutPlace addition operator :class:`~.pennylane.OutAdder` and the :class:`~.pennylane.Multiplier` previously employed.
```

2024-10-04 19:50 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +#  `wires[output]`. With 5 wires, we can represent numbers up to :math:`2^5=32`. Any number larger than that gets reduced to its modulo with
```suggestion
# `wires[output]`. With 5 wires, we can represent numbers up to :math:`2^5=32`. Any number larger than that gets reduced to its modulo with 
```

2024-10-04 19:50 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# Now we get the correct result :math:`f(x=1,y=4)=33`!
```suggestion
# Now we get the correct result :math:`f(x=1,y=4)=33`
```

I would suggest not using exclamations so frequently

2024-10-04 19:50 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +#  of quantum computing. While it may not replace classical efficiency for simple tasks, its role in complex algorithms
```suggestion
# of quantum computing. While it may not replace classical efficiency for simple tasks, its role in complex algorithms 
```

2024-10-04 19:50 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +
I'd recommend mentioning that we will do it in two ways.  Through the concatenation of simple arithmetic operators and finally with the OutPoly template. 

Then the following two sections are subsection of this one.
Then, I think you have to use:
"~~~~~~~~"

2024-10-09 18:54 UTC, ixfoduap requested changes
Left suggestions :smiling_imp:

2024-10-09 18:54 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# PennyLane function that handles the arithmetic for you? Pretty cool, right? I'm talking about :class:`~.pennylane.OutPoly`.
Overall this paragraph is a bit too informal, please revise

2024-10-09 18:54 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +print(circuit_with_Poly(x=1,y=4))
By the way, I'm thinking it may be nice to code up a simple function to convert binary into integers so we can print out the numerical value directly alongside the bitstring description. If I remember correctly, numpy or scipy have these already

2024-10-09 18:54 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +print(circuit_with_Poly(x=1,y=4))
Also, is there a way to visualize the circuits that doesn't just show `OutPoly` or something? It would be great to see how they are decomposed into basic operations

2024-10-09 18:54 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# of quantum computing. While it may not replace classical efficiency for simple tasks, its role in complex algorithms
Remove the second sentence

2024-10-15 12:45 UTC, gmlejarza commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +Loading a function :math:`f(x, y)`
I changed the order as suggested

2024-10-15 12:48 UTC, gmlejarza commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +    return [qml.sample(wires=wires[name]) for name in ["x", "y", "output"]]
The idea is that if sampling we are showing that these results can also be obtained in hardware, where access to the state is not possible. I added an explanation in case it was not clear 👍

2024-10-15 12:57 UTC, gmlejarza commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +    # |3x>|y>|0> ---> |3x>|y>|3xy>
As suggested, I added an explanation about how the subtraction and division can be achieved by using the adjoint. Regarding the possibility of multiplying by non-integer numbers, the documentation of each operator specifies that the constant used for addition/multiplication _is_ an integer: https://docs.pennylane.ai/en/stable/code/api/pennylane.Adder.html , https://docs.pennylane.ai/en/stable/code/api/pennylane.Multiplier.html

2024-10-15 12:59 UTC, gmlejarza commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# The result doesn't seem right, as we expect to get :math:`f(x=1, y=4) = 33`. Can you guess why?
Good point! I clarified from the beginning that all arithmetic is modular. Then, changed the order to show first the "expected" result (33) and then reduce the number of wires to showcase the overflow and remember that quantum arithmetic is modular.

2024-10-15 13:17 UTC, gmlejarza commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +print(circuit_with_Poly(x=1,y=4))
Unfortunately, there's no such built-in function that automatically converts a list representing a binary number into its decimal form. However, I've coded a custom function to print out the numerical value alongside the bitstring.

Regarding visualization, I included a printout of the Adder circuit, showing that the addition uses a QFT to switch the basis and then applies rotations to perform the addition in the Fourier basis. I think, this operator is the most pedagogical to showcase, since it serves as a building block to build the others. I also referred the reader to this demo, where the decomposition is further explained: https://pennylane.ai/qml/demos/tutorial_qft_arithmetics/

2024-10-16 13:00 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +represent numbers up to :math:`2^n`, so it's important to keep this in mind when working with quantum arithmetic.
Okay, I see that you comment on it later. I think it can be rephrased a bit for clarity

2024-10-16 13:01 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +The :class:`~.pennylane.Adder` performs an **Inplace** operation, adding a constant value :math:`k` to the state of the wires :math:`|w \rangle`. It is defined as:
I would clarify $k \in \mathbb{Z}$ or k integer

2024-10-16 13:03 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# operation, where we initialize specific values to :math:`x` and :math:`y`.
It may  be convenient to say that we will use basic states in the example but you could introduce any quantum state

2024-10-16 13:09 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +
This example does not convince me because it gives the feeling that it must be linked to the above but it is something totally different

2024-10-16 13:13 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# use these operations for subtraction or division in a quantum computer. The answer is yes!
"modular division", to avoid confusion

2024-10-16 13:14 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# Loading a polynomial into a quantum computer
Let's not use the work "Load", maybe "apply?

2024-10-16 13:14 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# Loading a polynomial into a quantum computer
If you agree, take a look at the text that appears in more occasions

2024-10-16 13:17 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +    # We return the x-register to its original value using the adjoint operation
I've been told that it is not clear why we do this. I would emphasize in the text or here that by the definition of U, the inputs |x> and |y> are not modified.

2024-10-16 13:18 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# Cool, we get the correct result 33!
I like this new approach 🚀

2024-10-16 13:19 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +wires = qml.registers({"x": 4, "y": 4, "output": 5, "work_wires": 4})
We can remove work_wires 😎

2024-10-16 14:19 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +   qml.OutPoly(f, registers_wires=[wires["x"], wires["y"], wires["output"]])
Based on new interface 

```suggestion
wires = qml.registers({"x": 4, "y":4, "output":6,"work_wires": 4})
@qml.qnode(dev)
def circuit_with_Poly(x,y):

   prepare_initial_state(x, y)
   qml.OutPoly(
       f, 
       x_wires = wires["x"],
       y_wires = wires["y"],
       output_wires = wires["output"])
```

2024-10-17 15:05 UTC, gmlejarza commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +
I included a line explaining and added the initialization of `prepare_initial_state` to link it with what it's above

2024-10-23 15:15 UTC, KetpuntoG reviewed
Easy and simple 💪 It's looking good

2024-10-23 15:15 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# the input registers ``wires["x"]`` and ``wires["y"]`` after the operation.
I think we can delete this sentence so as not to repeat ourselves

2024-10-23 15:15 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# Cool, we get the correct result 33!
```suggestion
# Cool, we get the correct result :math:`f(1,4)=33`!
```

2024-10-23 15:15 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +       y_wires = wires["y"],
```suggestion
       input_registers= [wires["x"], wires["y"]],
```

new UI again 🙈

2024-10-23 15:15 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +
```suggestion
# adjoint function to undo certain multiplications and clean up the input registers after performing the operations since :math:`U` does not modify the input registers.

```

What do you think about clarifying this?

2024-10-24 07:20 UTC, gmlejarza commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +too few qubits in a quantum register could lead to overflow errors. We will come back to this point later.
I changed "errors" for "issues"

2024-10-26 01:29 UTC, ixfoduap requested changes
Tutorial is in much better shape now, but still needs improvements. I think my suggestions should be easy to address

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +print("x register: ", output[0]," which represents the number ", state_to_decimal(output[0]))
Too long! I suggest [0001] --> 1, or something similarly compact

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +print("x register: ", output[0]," which represents the number ", state_to_decimal(output[0]))
And too long because code blocks that are to long horizontally show up in the build with a scroll bar which is ugly and annoying

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# We obtained the result :math:`6`, as expected. At this point, it's worth taking a moment to look
```suggestion
# We obtained the result :math:`5+1=6`, as expected. At this point, it's worth taking a moment to look
```

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# Taking a look at the decomposition of :class:`~.pennylane.Adder` we can see that the addition is performed
```suggestion
# Taking a look at the decomposition of :class:`~.pennylane.Adder`, we can see that the addition is performed 
```

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# [#demo_qft_arith]_.
No don't use a citation! This is not a paper. Use a hyperlink, e.g. can be found in out [tutorial on quantum arithmetic with QFT] (I forget the html/markdown code for hyperlinks)

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# We obtained the result :math:`5`, just as we expected.
```suggestion
# We obtained the result :math:`4+1=5`, as expected.
```

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# The class :class:`~.pennylane.Multiplier` performs an **Inplace** operation, multiplying the state of the wires :math:`|w \rangle` by an integer :math:`k`. It is defined as:
why are Inplace and Outplace in bold here? Different from before. I don't like it, I suggest removing the bold

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +#   \text{Multiplier}(k) |w \rangle = | kw \rangle,
```suggestion
#   \text{Multiplier}(k) |w \rangle = | kw \rangle.
```

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +#   \text{OutMultiplier} |x \rangle |y \rangle |0 \rangle = |x \rangle |y \rangle |xy \rangle.
```suggestion
# The :class:`~.pennylane.OutMultiplier` performs an **Outplace** operation, where the states of two 
# registers :math:`|x \rangle` and :math:`|y \rangle`, 
# are multiplied together and the result is stored in a third register:
#
# .. math::
#
#   \text{OutMultiplier} |x \rangle |y \rangle |0 \rangle = |x \rangle |y \rangle |xy \rangle.
```

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +#   \text{OutMultiplier} |x \rangle |y \rangle |0 \rangle = |x \rangle |y \rangle |xy \rangle.
|x> and |y> are registers, not wires (typically they are multiple wires)

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# for instance :math:`k=3`:
```suggestion
# We proceed to implement these operators in PennyLane. First, let's see an example for the 
# :class:`~.pennylane.Multiplier` operator. We will multiply the state  :math:`|x \rangle=|1 \rangle` by 
# the integer :math:`k=3`:
```

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# for instance :math:`k=3`:
All the examples have the boring case of x=1. Consider changing to different numbers

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +def prepare_initial_state(x,y):
I don't like the name "prepare initial state". Actually preparing a target quantum state is very difficult. This is just initializing registers to a basis state. Consider a better name. `product_basis_state` comes to mind

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# for instance :math:`k=3`:
I get that you can run into overflow, but (i) you can still avoid it, e.g. doing 2 x 3, (ii) it may eb nice actually to show an example where there is overflow and modular arithmetic comes into play

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# Note that even though we only covered addition and multiplication, modular subtraction
This needs a bit more explanation. Say that subtraction and division are inverses of addition and multiplication, and inverses of circuits can be implemented with adjoint. Then give a simple code example, e.g. for subtraction

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# Loading a polynomial into a quantum computer
Definitely not loading! This is a circuit that applies a polynomial transformation to input registers. "Loading" has the connotation of loading data

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# Now that you are familiar with these operations, let's take it a step further and see how we can use them for something practical.
```suggestion
# Now that you are familiar with these operations, let's take it a step further and see how we can use them for something more complicated. 
```

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# where :math:`x` and :math:`y` are the binary representations of the integers on which we want to apply the function.
```suggestion
#    U|x\rangle |y\rangle |0\rangle = |x\rangle |y\rangle |4 + 3xy + 5x + 3y\rangle.
```

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# We will show how to load this function in two different ways: first, by concatenating simple modular arithmetic operators,
```suggestion
# We will show how to implement this circuit in two different ways: first, by concatenating simple modular arithmetic operators,
```

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +    # |x> --->  |3x>
These code comments, in this case `# |x> --->  |3x>` are really great! Well done!

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# Now we can combine all these functions to load the function :math:`f(x,y)= 4 + 3xy + 5 x+ 3 y` into a quantum state.
```suggestion
# Now we can combine all these circuits to implement the transformation by the polynomial  :math:`f(x,y)= 4 + 3xy + 5 x+ 3 y`.
```

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# Cool, we get the correct result :math:`f(1,4)=33`!
```suggestion
# Cool, we get the correct result :math:`f(1,4)=33`.
```
otherwise looks like a factorial

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# For instance, if we had selected one less wire for the output, we would have obtained the result :math:`33 \mod 2^5 = 1`.
```suggestion
# For instance, if we had selected one less wire, we would have obtained the result :math:`33 \mod 2^5 = 1`.
```

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# Let's check out how to load a function like :math:`f(x, y)` using :class:`~.pennylane.OutPoly`.
```suggestion
# There is a more direct method to apply polynomial transformations in PennyLane: 
# using :class:`~.pennylane.OutPoly`. 
# This operator automatically takes care of all the arithmetic under the hood. 
# Let's check out how to load a function like :math:`f(x, y)` using :class:`~.pennylane.OutPoly`.
```

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# Now, we load it into a quantum circuit.
```suggestion
# Now, we create a quantum circuit using :class:`~.pennylane.OutPoly`.
```

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# Now, it's up to you to decide, depending on the problem you are tackling, whether to go for the versatility
```suggestion
# You can decide, depending on the problem you are tackling, whether to go for the versatility 
```

2024-10-26 01:29 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# operators, you are now equipped to tackle the exciting quantum challenges ahead.
```suggestion
# of quantum computing. By leveraging quantum arithmetic operations in PennyLane, you can streamline 
# the coding of your quantum algorithms. So, 
# whether you choose to customize your arithmetic operations or take advantage of the built-in 
# convenience offered by PennyLane 
# operators, you are now equipped to tackle the exciting quantum challenges ahead.
```

2024-10-29 21:34 UTC, KetpuntoG reviewed
Great job! 🚀 Happy to approve after these final comments are addressed

2024-10-29 21:34 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +In quantum computing, all arithmetic operations are inherently `modular <https://en.wikipedia.org/wiki/Modular_arithmetic/>`_.
This link seems an empty wikipedia page

2024-10-29 21:34 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +added together and the result is stored in a third wire:
third "register" or "set of wires" is more accurate

2024-10-29 21:34 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +we will work with. Note that we always need to define the `work_wires` register to implement the :class:`~.pennylane.Multiplier` operator.
```suggestion
we will work with. Note that we always need to define the ``work_wires`` register to implement the :class:`~.pennylane.Multiplier` operator.
```

2024-10-29 21:34 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +we will work with. Note that we always need to define the `work_wires` register to implement the :class:`~.pennylane.Multiplier` operator.
I would eliminate “Always”, it sounds better to me.

2024-10-29 21:34 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +def product_basis_state(x,y):
I suggest :
`def product_basis_state(x=0,y=0):`

so that, in the examples where you do not need “y” you can leave it blank instead of:

`    product_basis_state(x, 0)       # |x>
`

2024-10-29 21:34 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +#     `Pennylane: Basic arithmetic with the quantum Fourier transform (QFT) <https://pennylane.ai/qml/demos/tutorial_qft_arithmetics/>`__, 2024.
I really don't know why it doesn't render correctly. Maybe it would be more correct to remove it, put a link in the text and put it in metadata as a related demo

2024-10-29 21:47 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# can be implemented with the :func:`~.pennylane.adjoint` operator. Let's see an example of modular substraction:
```suggestion
# can be implemented with the :func:`~.pennylane.adjoint` operator. Let's see an example of modular subtraction:
```

2024-10-29 21:48 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# and division are the inverse operations of addition and multiplication, respectively. The inverse of a quantum cirucit
```suggestion
# and division are the inverse operations of addition and multiplication, respectively. The inverse of a quantum circuit 
```

2024-10-30 16:18 UTC, KetpuntoG approved these changes
looks great! Good job @gmlejarza 😊

2024-10-31 01:13 UTC, ixfoduap approved these changes
Just a few more suggestions and this will be ready to go. Great job!

2024-10-31 01:13 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# Taking a look at the decomposition of :class:`~.pennylane.Adder`, we can see that the addition is performed
```suggestion
# From the :class:`~.pennylane.Adder` circuitwe can see that the addition is performed 
```

2024-10-31 01:13 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +print("x register: ", output[0]," ---> ", state_to_decimal(output[0]))
I know I suggested it, but I'm not super sold on this [0 0 1 0] ---> 2 format. See if you can find a better way (if not it's fine)

2024-10-31 01:13 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# We got the expected result of :math:`3 \cdot 2 = 6`.
```suggestion
# We got the expected result of :math:`3 \times 2 = 6`.
```

2024-10-31 01:13 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# can be implemented with the :func:`~.pennylane.adjoint` operator. Let's see an example of modular subtraction:
```suggestion
# Nice! Modular subtraction and division can also be implemented as the inverses of addition and 
# multiplication, respectively. The inverse of a quantum circuit can be implemented with the 
# :func:`~.pennylane.adjoint` operator. Let's see an example of modular subtraction:
```

2024-10-31 01:13 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +
Good to say this is 6-3 = 3

2024-10-31 01:13 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# are integer values. Therefore, the operator we want to build is:
```suggestion
# In particular, we will use :math:`f(x,y)= 4 + 3xy + 5 x+ 3 y`  as an example, where the variables :math:`x` and
# :math:`y` are integer values. Therefore, the operator we want to build is:
```

2024-10-31 01:13 UTC, ixfoduap commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# since :math:`U` does not modify the input registers.
```suggestion
# adjoint function to undo certain multiplications since :math:`U` does not modify the input registers.
```

2024-10-31 12:31 UTC, gmlejarza commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +print("x register: ", output[0]," ---> ", state_to_decimal(output[0]))
I've changed for this:  [0 0 1 0] (binary) ---> 2 (decimal)

2024-11-04 12:45 UTC, ikurecic reviewed
Thanks, @KetpuntoG and @gmlejarza .
I've left some suggestions and corrections, but they are fairly minor. If you can address these, we can hopefully have this Demo ready for merging soon.

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +InPlace and OutPlace arithmetic operations
I think what you mean is this:
```suggestion
In-place and out-place arithmetic operations
```

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +The :class:`~.pennylane.Adder` performs an Inplace operation, adding an integer value :math:`k` to the state of the wires :math:`|x \rangle`. It is defined as:
```suggestion
The :class:`~.pennylane.Adder` operator performs an in-place operation, adding an integer value :math:`k` to the state of the wires :math:`|x \rangle`. It is defined as:
```

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +On the other hand, the :class:`~.pennylane.OutAdder` performs an Outplace operation, where the states of two
```suggestion
On the other hand, the :class:`~.pennylane.OutAdder` operator performs an out-place operation, where the states of two 
```

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +wires, :math:`|x \rangle` and :math:`|y \rangle` are
```suggestion
wires, :math:`|x \rangle` and :math:`|y \rangle`, are 
```

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +To implement these operators in Pennylane, the first step is to define the `registers of wires <https://pennylane.ai/qml/demos/tutorial_how_to_use_registers/>`_
```suggestion
To implement these operators in PennyLane, the first step is to define the `registers of wires <https://pennylane.ai/qml/demos/tutorial_how_to_use_registers/>`_
```

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +To implement these operators in Pennylane, the first step is to define the `registers of wires <https://pennylane.ai/qml/demos/tutorial_how_to_use_registers/>`_
Please also add this PennyLane Demo to the related demos section in the metadata file.

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +serving as fundamental building blocks in their design and execution. For example:
Can you add half a sentence here explaining what this crucial role is? As in, why the reader should care about this Demo?

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# operation, where we initialize specific values to :math:`x` and :math:`y`. Note that in this example we use computational basis states, but
```suggestion
# Now, we write a circuit to prepare the state :math:`|x \rangle|y \rangle|0 \rangle`, which will be needed for the out-place
# operation, where we initialize specific values to :math:`x` and :math:`y`. Note that in this example we use computational basis states, but
```

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# Now we can implement an example for the :class:`~.pennylane.Adder`. We will add the integer :math:`5` to the ``wires["x"]`` register
```suggestion
# Now we can implement an example for the :class:`~.pennylane.Adder` operator. We will add the integer :math:`5` to the ``wires["x"]`` register
```

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# in the Fourier basis. This includes a QFT transformation, followed by rotations to perform the addition, and
```suggestion
# in the Fourier basis. This includes a quantum Fourier transformation (QFT) followed by rotations to perform the addition, and 
```

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# `this demo <https://pennylane.ai/qml/demos/tutorial_qft_arithmetics/>`_ on quantum arithmetic with the QFT.
```suggestion
# `the PennyLane Demo on quantum arithmetic with the QFT <https://pennylane.ai/qml/demos/tutorial_qft_arithmetics/>`_. 
```

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# The class :class:`~.pennylane.Multiplier` performs an Inplace operation, multiplying the state of the wires :math:`|x \rangle` by an integer :math:`k`. It is defined as:
```suggestion
# The class :class:`~.pennylane.Multiplier` performs an in-place operation, multiplying the state of the wires :math:`|x \rangle` by an integer :math:`k`. It is defined as:
```

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# The :class:`~.pennylane.OutMultiplier` performs an Outplace operation, where the states of two
```suggestion
# The :class:`~.pennylane.OutMultiplier` performs an out-place operation, where the states of two 
```

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# registers :math:`|x \rangle` and :math:`|y \rangle`,
```suggestion
# registers, :math:`|x \rangle` and :math:`|y \rangle`, 
```

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# We got the expected result of :math:`3 \times 2 = 6`.
```suggestion
# We got the expected result of :math:`3 \cdot 2 = 6`.
```

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# :func:`~.pennylane.adjoint` operator. Let's see an example of modular subtraction:
```suggestion
# :func:`~.pennylane.adjoint` operator. Let's see an example of modular subtraction.
```

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# Applying a polynomial into a quantum computer
This seems like an awkward title. Are you trying to say this?
```suggestion
# Implementing a polynomial on a quantum computer
```

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# adjoint function to undo certain multiplications since :math:`U` does not modify the input registers.
```suggestion
# adjoint function to undo certain multiplications, since :math:`U` does not modify the input registers.
```

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +    # We return the x and y registers to its original value using the adjoint operation
```suggestion
    # We return the x and y registers to their original value using the adjoint operation
```

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# Cool, we get the correct result :math:`f(1,4)=33`.
```suggestion
# Cool, we get the correct result, :math:`f(1,4)=33`.
```

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# For instance, if we had selected one less wire, we would have obtained the result :math:`33 \mod 2^5 = 1`.
```suggestion
# For instance, if we had selected one wire fewer, we would have obtained the result :math:`33 \mod 2^5 = 1`.
```

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# With one less wire, we get :math:`1`, just like we predicted. Remember, we are working with modular arithmetic!
```suggestion
# With one fewer wire, we get :math:`1`, just like we predicted. Remember, we are working with modular arithmetic!
```

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# Using OutPoly
```suggestion
# Using the OutPoly function
```

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# using :class:`~.pennylane.OutPoly`.
Will this be updated with the new PennyLane release?

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# We will start by explicitly defining our function:
```suggestion
# We will start by explicitly defining our function.
```

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +
```suggestion
```

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +With PennyLane, you will see how easy it is to build these operations as subroutines for your quantum algorithms!
```suggestion
With PennyLane, you will see how easy it is to build quantum arithmetic operations as subroutines for your quantum algorithms!
```

2024-11-04 12:45 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.metadata.json
> +    ],
Is this supposed to be a How-to?
```suggestion
    "categories": [
        "Quantum Computing",
        "Algorithms",
        "How-to"
    ],
```

2024-11-04 14:43 UTC, gmlejarza commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +# using :class:`~.pennylane.OutPoly`.
Yes, new PennyLane release includes qml.OutPoly

2024-11-04 14:43 UTC, gmlejarza commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +InPlace and OutPlace arithmetic operations
The original idea was to name the operators InAdder, OutAdder, InMultiplier, and OutMultiplier, which made InPlace and OutPlace sound like a good fit (for consistency). However, since the operators were later renamed to Adder, OutAdder, Multiplier, and OutMultiplier, keeping InPlace and OutPlace might be less clear now. It’s probably better to update these terms to in-place and out-place throughout, thanks for bringing that up

2024-11-04 14:50 UTC, gmlejarza commented on demonstrations/tutorial_how_to_use_arithmetic_operators.metadata.json
> +    "canonicalURL": "/qml/demos/tutorial_how_to_use_arithmetic_operators",
We can change it throughout, but I thought that it would make all the file names too long without bringing any additional value. We know that we are talking about `quantum` arithmetic. Anyway, if you think it's clearer to add the word quantum, I'm happy to change it throughout.

2024-11-04 15:48 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.metadata.json
> +    "canonicalURL": "/qml/demos/tutorial_how_to_use_arithmetic_operators",
Please do change the canonicalURL and the file names, if that's all right with you. It adds clarity in the SEO sense.

2024-11-04 15:50 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +serving as fundamental building blocks in their design and execution. For example:
```suggestion
serving as fundamental building blocks in their design and execution, and knowing your way around quantum arithmetic with PennyLane could be just the thing to take your algorithms from simple to complex. For example:
```
Is this what you would like to say? I just think it needs a bit of a 'hook', you know?

2024-11-04 16:20 UTC, gmlejarza commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +serving as fundamental building blocks in their design and execution. For example:
I see your point now. While I prefer to keep the original sentence before the examples as it is, we can definitely add a 'hook' after the examples. I suggest the following change:

With PennyLane, you will see how easy it is to build quantum arithmetic operations as subroutines for your quantum algorithms! -> With PennyLane, you’ll see how easy it is to build quantum arithmetic operations as subroutines for your algorithms. Knowing your way around these operators could be just the thing to streamline your algorithm design!

2024-11-04 16:28 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_arithmetic_operators.py
> +serving as fundamental building blocks in their design and execution. For example:
Yeah, why not — if you're happy with this, that's great.

2024-11-04 18:37 UTC, KetpuntoG commented
It is important that the file name starts with “tutorial_” . Otherwise, the demo will not run and the outputs will not appear. I just updated it in the last commit

2024-11-05 12:01 UTC, KetpuntoG approved these changes

2024-11-05 12:01 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_use_quantum_arithmetic_operators.py
> +# Conclusion
```suggestion
# Conclusion 
```

empty suggestion to see if the merge problem is solved

2024-11-05 13:04 UTC, ikurecic commented
"Unresolved conversation" issue solved in #1255

2024-11-05 13:04 UTC, closed without merging