[WIP] how to build spin hamiltonians
PennyLaneAI/qml pull request #1230
Opened 2024-10-04 17:36 UTC by soranjh

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Remember to do a grammar check of the content you include.
- [ ] All tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**
How to build spin hamiltonians [sc-74419]

**Summary:**
This how-to explains the features added to the `qml.spin` module for constructing spin Hamiltonians.

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

----
If you are writing a demonstration, please answer these questions to facilitate the marketing process.

* GOALS — Why are we working on this now?

  *Eg. Promote a new PL feature or show a PL implementation of a recent paper.*

* AUDIENCE — Who is this for?

  *Eg. Chemistry researchers, PL educators, beginners in quantum computing.*

* KEYWORDS — What words should be included in the marketing post?

* Which of the following types of documentation is most similar to your file? 
(more details [here](https://www.notion.so/xanaduai/Different-kinds-of-documentation-69200645fe59442991c71f9e7d8a77f8))
    
- [ ] Tutorial
- [ ] Demo
- [ ] How-to

2024-10-10 19:39 UTC, KetpuntoG reviewed
This new functionality really seems to make the job easier 🚀

2024-10-10 19:39 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# constructed in PennyLane by passing the hoping and interaction parameters to the fermi_hubbard
even if the link doesn't work now, I would add this

```suggestion
# constructed in PennyLane by passing the hoping and interaction parameters to the :func:`fermi_hubbard <pennylane.spin.fermi_hubbard>`
```

2024-10-10 19:39 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# `Fermi-Hubbard <https://pennylane.ai/datasets/qspin/fermi-hubbard-model>`__ model as an example.
I was confused by your pointing to the dataset as I thought we were using it but they are different things

2024-10-10 19:39 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# with the dedicated functions available in the spin module, by just providing the lattice
I don't know if we can link it now but it would be good to add a link here to the spin module

2024-10-10 19:39 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# PennyLane has a range of functions for constructing spin model Hamiltonians with minimal input
Can you mention a couple of different Hamiltonian examples?

2024-10-10 19:39 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +lattice = qml.spin.lattice._generate_lattice('square', [3, 3])
curious about why this is a private function

2024-10-10 19:39 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +plot(lattice)
nice!

2024-10-10 19:39 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# constructed in PennyLane by passing the hoping and interaction parameters to the fermi_hubbard
the same for all other functions. Another option is to put \`\`function name\`\`, so that it is not seen in plain text

2024-10-10 19:39 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# our transverse field Ising model Hamiltonian. We just need to define the coupling and onsite
You might remember the reader that these are J and h

2024-10-10 19:39 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +nodes = [[0.5, 0.5 / 3 ** 0.5], [1, 1 / 3 ** 0.5]]
Not sure I understand what the nodes are here

2024-10-10 19:39 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +plot(Lattice(n_cells, vectors, nodes), figsize=(5, 3))
😮

2024-10-10 19:39 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# Similarity, a broad range of other well-investigated spin model Hamiltonians can be constructed
```suggestion
# Similarly, a broad range of other well-investigated spin model Hamiltonians can be constructed
```

2024-10-10 19:39 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# how to use this tools by constructing the Hamiltonian for the
```suggestion
# how to use these tools by constructing the Hamiltonian for the
```

2024-10-10 19:50 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +lattice = qml.spin.lattice._generate_lattice('square', [3, 3])
It will become public in a WIP PR.

2024-10-15 13:43 UTC, ddhawan11 reviewed
Thanks @soranjh. I have added my first set of comments.

2024-10-15 13:43 UTC, ddhawan11 commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# constructed in PennyLane by passing the hoping and interaction parameters to the fermi_hubbard
```suggestion
# constructed in PennyLane by passing the hopping and interaction parameters to the fermi_hubbard
```

2024-10-15 13:43 UTC, ddhawan11 commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +u = 0.3
Shall we add comments here to say which term describes what parameter or rename the parameters? This might get confusing as we don't provide the equation here.

2024-10-15 13:43 UTC, ddhawan11 commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# construct the Hamiltonian for a cubic lattice with 3 sites on each direction as
```suggestion
# construct the Hamiltonian for a cubic lattice with 3 sites in each direction as
```

2024-10-15 13:43 UTC, ddhawan11 commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# model on a two-dimension lattice.
```suggestion
# model on a two-dimensional lattice.
```

2024-10-15 13:43 UTC, ddhawan11 commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# manually is more flexible while generate_lattice only works for some predefined lattice shapes.
We can link the generate_lattice function here, so that a reader can see which pre-defined shapes are available.

2024-10-15 13:43 UTC, ddhawan11 commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# customising them. The lattice can be constructed in a very flexible way that allows constructing
```suggestion
# customising them. The lattice can be constructed in a more flexible way that allows constructing
```

2024-10-15 13:43 UTC, ddhawan11 commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# the new spin functions and classes allows constructing any new spin model Hamiltonian intuitively.
```suggestion
# the new spin functions and classes allows construction of any new spin model Hamiltonian intuitively.
```

2024-10-28 15:03 UTC, ixfoduap requested changes
It's a good tutorial overall, but I see a lot of room for improvement

2024-10-28 15:03 UTC, ixfoduap commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# the Kitaev model and verify that the Hamiltonians are the same.
Maybe good to actually do it?
Generally, it doesn't make sense to me to build custom lattices and Hamiltonians that we already support automatically. This should be a chance to do something more unusual that we don't otherwise support. A good chance to have fun! It comes to mind to have triangular lattice, or maybe some Penrose tesselation. It's also nice to build a very large Hamiltonian

2024-10-28 15:03 UTC, ixfoduap commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# Hamiltonians. Here we learned how to use these tools to construct pre-defined Hamiltonian
```suggestion
# The spin module in PennyLane provides a set of powerful tools for constructing spin 
# Hamiltonians. Here we learned how to use these tools to construct pre-defined Hamiltonian
```

2024-10-28 15:03 UTC, ixfoduap commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# the new spin functions and classes allows constructing any new spin model Hamiltonian intuitively.
```suggestion
# the new spin functions and classes allow you to quickly construct any new spin Hamiltonian.
```

2024-10-30 16:37 UTC, ddhawan11 requested changes
Thanks @soranjh

2024-10-30 16:37 UTC, ddhawan11 commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +nodes = [[0.5, 0.5 / 3 ** 0.5], [1, 1 / 3 ** 0.5]]
We should probably rename this variable as something like node_positions, node_coordinates

2024-10-30 16:37 UTC, ddhawan11 commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# transverse magnetic field, and :math:`i,j> represent spins indices. The notation :math:`<i,j>` indicates the sum is taken over neighbouring spins in the lattice.
```suggestion
# transverse magnetic field, and :math:`<i,j>` represent spins indices. The notation :math:`<i,j>` indicates the sum is taken over neighbouring spins in the lattice.
```

2024-10-30 16:54 UTC, ddhawan11 approved these changes

2024-10-30 19:09 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# `Fermi-Hubbard <https://pennylane.ai/datasets/qspin/fermi-hubbard-model>`__ model as an example.
Changed the link.

2024-10-30 19:13 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# with the dedicated functions available in the spin module, by just providing the lattice
I have linked to the spin module docs which has all the information. I can put examples for all the Hamiltonians we support if this is still needed, after linking to the spin docs.

2024-10-30 19:13 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# PennyLane has a range of functions for constructing spin model Hamiltonians with minimal input
I have linked to the spin docs with the full list.

2024-10-30 19:14 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# our transverse field Ising model Hamiltonian. We just need to define the coupling and onsite
Added them in the sentence below, just before the code block.

2024-10-30 19:15 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +nodes = [[0.5, 0.5 / 3 ** 0.5], [1, 1 / 3 ** 0.5]]
I have added a few sentences to explain what they are, basically coordinates of the cites inside the unit cell. Also changed the arg name to positions.

2024-10-30 19:16 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# manually is more flexible while generate_lattice only works for some predefined lattice shapes.
Used a square-octagon lattice.

2024-10-30 19:18 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +u = 0.3
Used more descriptive names. Also explained why this is a list: the reason is chain is a special case which has one dimension, but in general we can have up to three dimensions to grow a unit cell.

2024-10-30 19:24 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +hamiltonian = qml.spin.fermi_hubbard("chain", n, t, u)
Added some explanations as suggested. Also linked to the spin module in the first sentence.

2024-10-30 19:26 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +def plot(lattice, figsize=None):
Yes, this is the plan for future. We need to agree on the details of the visualization, e.g., colors, fonts etc., which requires proper discovery. For now, we just provided the helper function directly.

2024-10-30 19:27 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +nodes = [[0, 0]]  # coordinates of nodes inside the unit cell
Added couple of sentences to explain the details and also a link.

2024-10-30 19:29 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +for vertex in range(lattice.n_sites):
Added some sentences to explain that.

2024-10-30 19:32 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# Building customized Hamiltonians
The distinction between the two sections is mainly about adding custom edges defined by the user for specific nodes and with specific parameters in the second section. Changed the title of the second section to "Adding custom nodes and edges".

2024-10-30 19:33 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +custom_edges = [[(0, 1), ('XX', 0.5)],
Updated the example and added more explanation. It should be clear now.

2024-10-30 19:34 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +hamiltonian
I have used it actually in the lines before. Here just wanted to show how things can be done manually. Added a sentence starting with "Alternatively, you can build the Hamiltonian manually by ..." to make things more clear. I think the users benefit from seeing the manual construction.

2024-10-30 19:34 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# these tools.  You can compare the constructed Hamiltonian with the template we already have for
Revised.

2024-10-30 19:38 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# the Kitaev model and verify that the Hamiltonians are the same.
Added a new Hamiltonian for a new lattice.

2024-10-30 20:20 UTC, KetpuntoG approved these changes
cool new feature! 
Here are a couple of typo-corrections and optional suggestions, otherwise it's ready to go 🚀

2024-10-30 20:20 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# node 0 to 2 and the third and forth types connect node 1 to 3 and 2 to 3, respectively. Note that
```suggestion
# node 0 to 2 and the third and fourth types connect node 1 to 3 and 2 to 3, respectively. Note that
```

2024-10-30 20:20 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# edges: the first types is the one that connects node 0 to 1, the second type is defined to connect
```suggestion
# edges: the first type is the one that connects node 0 to 1, the second type is defined to connect
```

2024-10-30 20:20 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# the Kitaev honeycomb Hamiltonian. The versatility of the new spin functions and classes allow you
```suggestion
# the Kitaev honeycomb Hamiltonian. The versatility of the new spin functions and classes allows you
```

2024-10-30 20:20 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# ----------------
```suggestion
# About the authors
# ------------------
```

2024-10-30 20:20 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# :math:`9 = 3 \times 3` sites which are all connected to their nearest neighbor.
[Optional] I'm more used to seeing it this way

```suggestion
# :math:`3 \times 3 = 9` sites which are all connected to their nearest neighbor.
```

2024-10-30 20:20 UTC, KetpuntoG commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +    plt.axis("off")
[optional] I think it would have helped me to situate the points, if I could see the axes

2024-10-30 20:36 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +    plt.axis("off")
Showing axis doesn't look very nice unfortunately.

2024-10-31 19:19 UTC, alvaro-at-xanadu requested changes
This is an amazing PennyLane feature! I am still a bit confused about how it works in some instances, in particular the difference between number of cells and number of sites, but that may just be me? 

A lot of the feedback is me being confused about this. I feel this is a demo that would benefit from more drawings from square one. If you need support with this, please let me know!

2024-10-31 19:19 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +######################################################################
I am apparently super confused about the difference between cell and site. Why does the previous one give me a lattice with $3\times 3$, but this one gives me $3\times 3$ cells?

2024-10-31 19:19 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# Constructing the lattice manually is more flexible while :func:`~.pennylane.spin.generate_lattice`
```suggestion
# Constructing the lattice manually is more flexible, while :func:`~.pennylane.spin.generate_lattice`
```

2024-10-31 19:19 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# In this example we just used the in-built attributes of the lattice we created without further
```suggestion
# In this example, we just used the built-in attributes of our custom lattice without further
```

2024-10-31 19:19 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# ``XX`` edge with coupling constant 0.5 between nodes 0 and 1, we use:
```suggestion
# Now we work on a more complicated Hamiltonian to see how our existing tools allow us to build it
# intuitively. We construct the anisotropic square-trigonal [#jovanovic]_ model, where the coupling parameters
# depend on the orientation of the bonds. We can construct the Hamiltonian by building the
# lattice manually and adding custom edges between the nodes. For instance, to define a custom
# ``XX`` edge with coupling constant 0.5 between nodes 0 and 1, we use:
```

2024-10-31 19:19 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# Let's plot the lattice to see how it looks like.
```suggestion
# Let's plot the lattice to see what it looks like.
```

2024-10-31 19:37 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# Similarly, we can construct the Hamiltonian for a cubic lattice with 5 sites in each direction as
It is the the number of cells. Will make it consistent everywhere to not use sites.  (in many of the supported lattice structures, the unit cell contains only one site, so the number of cells and sites are equivalent, but anyways will use cell everywhere)

2024-10-31 19:39 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +
` coupling = [Jx, Jy, Jz]`

2024-10-31 20:03 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +######################################################################
n_cells is always the number of cells. However, in many cases, e.g., 'chain;, 'square', 'rectangle`, ..., the lattice is constructed from unit cells that contain only one point while in others, e.g., 'honeycomb', the unit cell needs to have two points in it. Added some explanations to the text to clarify that.

2024-10-31 20:13 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +######################################################################
Thanks! That makes sense :)

2024-10-31 20:34 UTC, obliviateandsurrender reviewed
Looks good, some minor suggestions

2024-10-31 20:34 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# degree of freedom, and :math:`n_{i \uparrow}, n_{i \downarrow}` are the number operators for the spin-up
We should add details for the values in the spin degree of freedom (`up` and `down` state).

2024-10-31 20:34 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# a ``square`` lattice which is repeated two times in each direction.
No need to format `square`.

2024-10-31 20:34 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +coulomb = 0.3
Can rename coulomb to `on-site`?

2024-10-31 20:34 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +hamiltonian = qml.spin.heisenberg("square", n_cells=[2, 2], coupling=np.array([0.5, 0.5, 0.5]))
Might want to define `coupling` before removing horizontal scrolling. [optional]

2024-10-31 20:34 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# describes fermions on a honeycomb lattice with real-space bond directions :math:`X,` :math:`Y,` and :math:`Z`
We can add a reference to the honeycomb lattice as well.

2024-10-31 20:34 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +#  given by :math:`[0, 1], [\frac{\sqrt{3}}{2}, \frac{1}{2}], \frac{\sqrt{3}}{2}, -\frac{1}{2}].` The Hamiltonian reads
Renders incorrectly, not sure why 🤔

2024-10-31 20:34 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +hamiltonian = qml.spin.haldane("square", n_cells=[2, 2], hopping=0.5, hopping_next=1.0, phi=0.1)
split into multiple lines - to remove horizontal scroll
```
qml.spin.haldane(
    "square", n_cells=[2, 2], hopping=0.5, hopping_next=1.0, phi=0.1
)
```

2024-10-31 20:34 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +hamiltonian = qml.spin.emery("square", n_cells=[2, 2], hopping=0.5, coulomb=1.0, intersite_coupling=0.2)
Same comment to remove horizontal scrolling.

2024-10-31 20:34 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# their connectivity. This is done by using the :class:`~.pennylane.spin.Lattice` class, which can be
The lattice class doesn't add a reference in the built version for some reason.

2024-10-31 20:34 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +        plt.figure(figsize=lattice.n_cells[::-1])
We can simply update the figsize by `lattice.n_cells[::-1]` if it is `None`, instead of using the `else` clause.

2024-10-31 20:34 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# add the coupling terms
```suggestion
    hamiltonian += -onsite * X(vertex)

# add the coupling terms
```

2024-10-31 20:34 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +hamiltonian
```suggestion
print(hamiltonian)
```

2024-10-31 20:34 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# ``XX`` edge with coupling constant 0.5 between nodes 0 and 1, we use:
```suggestion
# ``XX`` edge with coupling constant :math:`0.5` between nodes 0 and 1, we use:
```

2024-10-31 20:34 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +positions = [[0.1830127018922193, 0.3169872981077807],
Might be nice to comment on how we get these (at least intuitively).

2024-10-31 20:34 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +hamiltonian
```suggestion
print(hamiltonian)
```

2024-10-31 20:37 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +hamiltonian = qml.spin.kitaev(n_cells=[2, 2], coupling=np.array([0.5, 0.6, 0.7]))
```suggestion
hamiltonian = qml.spin.kitaev(n_cells=[2, 2], coupling=[0.5, 0.6, 0.7])
```

2024-10-31 20:37 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +hamiltonian = qml.spin.heisenberg("square", n_cells=[2, 2], coupling=np.array([0.5, 0.5, 0.5]))
```suggestion
hamiltonian = qml.spin.heisenberg("square", n_cells=[2, 2], coupling=[0.5, 0.5, 0.5])
```

2024-11-01 13:28 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# degree of freedom, and :math:`n_{i \uparrow}, n_{i \downarrow}` are the number operators for the spin-up
Added "denoted by :math:`0` and :math:`1`." Is that what you mean?

2024-11-01 13:28 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +coulomb = 0.3
Yes.

2024-11-01 13:28 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +hamiltonian = qml.spin.haldane("square", n_cells=[2, 2], hopping=0.5, hopping_next=1.0, phi=0.1)
Defined parameters outside everywhere.

2024-11-01 13:28 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# their connectivity. This is done by using the :class:`~.pennylane.spin.Lattice` class, which can be
It is normal for new features, will be corrected automatically when merged.

2024-11-01 13:28 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +positions = [[0.1830127018922193, 0.3169872981077807],
Added the link to the paper.

2024-11-01 14:46 UTC, alvaro-at-xanadu approved these changes
Thanks! It's looking good :)

2024-11-04 14:02 UTC, ikurecic reviewed
Thanks for sharing, @soranjh and @ddhawan11 !
I have left some comments, corrections, and suggestions. Please let me know (via Slack?) if you have any questions or concerns about these and I'm sure we can sort through them quickly.

Other than that, great work! This is going to be an amazing resource.

2024-11-04 14:02 UTC, ikurecic commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# Hamiltonians. Here we learned how to use these tools to construct pre-defined Hamiltonian
```suggestion
# Hamiltonians. Here we learned how to use these tools to construct predefined Hamiltonian
```
For consistency.

2024-11-04 14:02 UTC, ikurecic commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# templates, such as the Fermi-Hubbard model Hamiltonian, and use the
```suggestion
# templates, such as the Fermi–Hubbard model Hamiltonian, and used the
```

2024-11-04 14:02 UTC, ikurecic commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +#
```suggestion
```

2024-11-04 16:22 UTC, ikurecic commented on demonstrations/tutorial_how_to_spin_hamiltonian.metadata.json
> +            "username": "diksha_dhawan"
@ddhawan11 , this also doesn't exist. Could you please check or text me on Slack if we need to troubleshoot?

2024-11-04 16:25 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +to intuitively construct a broad range of spin Hamiltonians. Here we show you how to use these tools
The second one might be relevant, we can add if helps.

2024-11-04 16:25 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# `Hamiltonian <https://docs.pennylane.ai/en/latest/code/api/pennylane.spin.transverse_ising.html>`__
If we use the acronym, then we should use it everywhere and it will be the only model model that is abbreviated. So, I kept as is for now for consistency but can use TFIM if it makes more sense.

2024-11-04 16:25 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +#
The subsection was an independent section initially and I made it a section again with the title:  Building anisotropic Hamiltonians. I think this feature is important enough to deserve a section.

2024-11-04 16:29 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.metadata.json
> +            "username": "diksha_dhawan"
Corrected to diksha_dhawan.

2024-11-04 16:33 UTC, ikurecic commented on demonstrations/tutorial_how_to_spin_hamiltonian.metadata.json
> +            "username": "diksha_dhawan"
I think this means @ddhawan11 probably doesn't have a pennylane.ai account at the moment, or has changed the username. This wasn't in our database. I'll contact directly.

2024-11-04 16:34 UTC, ikurecic commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +to intuitively construct a broad range of spin Hamiltonians. Here we show you how to use these tools
Please do, if you think it might make sense. If not, that's perfectly fine.

2024-11-04 16:35 UTC, ikurecic commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# `Hamiltonian <https://docs.pennylane.ai/en/latest/code/api/pennylane.spin.transverse_ising.html>`__
I'm in this field, and this would be the only model I would use an initialism for instead of the full name, so I thought it would help to add it to the link, for SEO reasons. It is absolutely not mandatory, but it may make your Demo more easily searchable.

2024-11-04 16:36 UTC, ikurecic commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +#
I see what you mean. That makes a lot of sense to me, thanks!

2024-11-04 20:24 UTC, ixfoduap commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +model and more!
Please add links for these models. Wikipedia should be good

2024-11-04 20:24 UTC, ixfoduap commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# provided in the :func:`~.pennylane.spin.generate_lattice` documentation.
`generate_lattice` is not working for me

2024-11-04 20:24 UTC, ixfoduap commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# sites and :math:`\sigma` is a Pauli operator. The Hamiltonian can be constructed as follows.
```suggestion
# sites, and :math:`\sigma` is a Pauli operator. The Hamiltonian can be constructed as follows.
```

2024-11-04 20:24 UTC, ixfoduap commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +hamiltonian = qml.spin.heisenberg("square", n_cells, coupling)
All the examples from here on just use a `square` lattice. Please change to include the other examples. From the docs I see a large list : 'chain', 'square', 'rectangle', 'triangle', 'honeycomb', 'kagome', 'lieb', 'cubic', 'bcc', 'fcc' or 'diamond'.

2024-11-04 20:24 UTC, ixfoduap commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# sites and :math:`\sigma` is a Pauli operator. The Hamiltonian can be constructed as follows.
No need to repeat what <i,j> means, nor what \sigma is. We already did that. Please make this change for all other Hamiltonians

2024-11-04 20:24 UTC, ixfoduap commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +hamiltonian = qml.spin.heisenberg("square", n_cells, coupling)
Is it too much work to define the lattice plotting function above, then extract the lattice for each example and plot it? Right now these examples for each new model are a bit bare and boring. It even makes me think we may benefit from a built-in function for plotting lattices

2024-11-04 20:24 UTC, ixfoduap commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +hamiltonian = qml.spin.heisenberg("square", n_cells, coupling)
For these examples, consider printing the Hamiltonian

2024-11-04 20:24 UTC, ixfoduap commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# transverse magnetic field, and :math:`\left< i,j \right>` represents the indices of neighbouring spins.
We already define this above so no need to repeat

2024-11-04 20:24 UTC, ixfoduap commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# direction [#ashcroft]_. Recall that a unit cell is the smallest repeating unit of a lattice.
not so useful to link to a textbook. IS there an internet link we can use instead?

2024-11-06 20:09 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# describes fermions on a honeycomb lattice with real-space bond directions :math:`X,` :math:`Y,` and :math:`Z`
The paper has the full info about the lattice shape. Adding a ref for the lattice might make this a bit crowded with links and confusing.

2024-11-06 20:11 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +import matplotlib.pyplot as plt
Brought it to the beginning.

2024-11-06 20:13 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +from pennylane.spin import Lattice
Is it still confusing after the latest changes? The unit cell in most cases has only 1 cite, so not sure visualising it helps. If you please elaborate on what part is confusing, I can probably add more information.

2024-11-06 20:14 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# provided in the :func:`~.pennylane.spin.generate_lattice` documentation. We can also define the
That is normal for new features, will be fixed when merged.

2024-11-06 20:16 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# direction [#ashcroft]_. Recall that a unit cell is the smallest repeating unit of a lattice.
There are some other resources but I think the book chapter is very comprehensive, which is not explicitly mentioned in the link. There is also this [link](https://unlcms.unl.edu/cas/physics/tsymbal/teaching/SSP-927/Section%2001_Crystal%20Structure.pdf), but not sure if it is stable enough to cite here.

2024-11-06 20:19 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# a ``square`` lattice which is repeated two times in each direction.
I kind of used it for better highlighting, but can change them all if it is confusing?

2024-12-02 19:03 UTC, ixfoduap approved these changes
Just left a couple of very minor suggestions. Demo looks amazing, well done!

2024-12-03 09:22 UTC, ikurecic commented on demonstrations/tutorial_how_to_spin_hamiltonian.metadata.json
> +    "dateOfLastModification": "2024-11-04T00:00:00+00:00",
tk

2024-12-03 09:25 UTC, ikurecic commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +the `transverse-field Ising <https://en.wikipedia.org/wiki/Transverse-field_Ising_model>`__ model,
https://pennylane.ai/datasets/transverse-field-ising-model

2024-12-03 09:26 UTC, ikurecic commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +the `Emery <https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.58.2794>`__ model,
Also, please include the full "name model" expression in the hyperlink text to aid with searchability.

2024-12-03 09:27 UTC, ikurecic commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +#     H = -t\sum_{\left< i,j \right>, \sigma} c_{i\sigma}^{\dagger}c_{j\sigma} + U\sum_{i}n_{i \uparrow} n_{i\downarrow}.
```suggestion
# potential energy component which is parameterized by the on-site interaction strength, :math:`U`:
#
# .. math::
#
#     H = -t\sum_{\left< i,j \right>, \sigma} c_{i\sigma}^{\dagger}c_{j\sigma} + U\sum_{i}n_{i \uparrow} n_{i\downarrow}.
```
Or say "as follows:" or something to that effect.

2024-12-03 09:29 UTC, ikurecic commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# that describes the positions of the spin sites. A full list of supported lattice shapes is
```suggestion
# that describes the positions of the spin sites. We will show an example here, and the full list of supported lattice shapes is
```
Or something similar, to improve the paragraph flow.

2024-12-03 09:30 UTC, ikurecic commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# create a simple plotting function and also the helper function
```suggestion
# create a simple plotting function, as well as the helper function
```
There are a lot of instances of "also" in the lead-up to this sentence.

2024-12-03 09:32 UTC, ikurecic commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +plot(lattice)
As this is a how-to, it might be nice to add a few inline comments to the code here.
For example, it might already be helpful for users to understand what you're doing when setting figsize options without having to research from scratch in the documentation.

2024-12-03 09:35 UTC, ikurecic commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +plot(lattice)
I also suggest to separate the last part (lattice definition and plotting) from the plot definition codeblock, to make it easier for users to pick and use the code they need.
With this in mind, I would strongly suggest to put the code up until these last two lines in the parent section instead of as part of this subsection or even explicitly name it to make it easier for users to find. The plot definition is used in other subsections, as well, and a how-to is intended to be used as quick reference material.

2024-12-03 09:39 UTC, ikurecic commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# Hamiltonian.
```suggestion
# class. We also need to define the coupling, :math:`J`, and onsite parameters of the
# Hamiltonian, :math:`h`.
```

2024-12-03 09:40 UTC, ikurecic commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +# The spin module in PennyLane provides a set of powerful tools for constructing spin Hamiltonians.
I suggest you to link to it here: https://docs.pennylane.ai/en/latest/code/qml_spin.html

2024-12-04 14:18 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +to easily construct spin Hamiltonians for the `Fermi–Hubbard <https://en.wikipedia.org/wiki/Hubbard_model>`__ model,
It was the original link but reviewers found it is confusing, so changed them.

2024-12-04 14:19 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +plot(lattice)
Added some comments. Please note that we will have proper plotting functionality in the Lattice class, just pending discovery. So this simple function will be removed from the demo when that plotting functionality is merged to Lattice.

2024-12-04 17:25 UTC, soranjh commented on demonstrations/tutorial_how_to_spin_hamiltonian.py
> +to easily construct spin Hamiltonians for the `Fermi–Hubbard <https://en.wikipedia.org/wiki/Hubbard_model>`__ model,
Sure, thanks.

2024-12-05 13:38 UTC, merged