How to import noise models from Qiskit
PennyLaneAI/qml pull request #1235
Opened 2024-10-09 16:46 UTC by obliviateandsurrender

**Title:** How to import noise models from Qiskit

**Summary:** Importing and creating noise models in PennyLane using the noise models in Qiskit

----
If you are writing a demonstration, please answer these questions to facilitate the marketing process.

* GOALS — Why are we working on this now? 
   - This is meant to promote the noise model PennyLane feature. 
   - In particular, how to use `from_qiskit_noise` method to import noise models from Qiskit.

* AUDIENCE — Who is this for?
   - This is meant for both users and researchers who utilize PennyLane and also users.
   - This is also meant for users who use Qiskit noise models in their workflows.

* KEYWORDS — What words should be included in the marketing post?
   - Noise models, 
   - Noisy simulation.

* Which of the following types of documentation is most similar to your file? 
(more details [here](https://www.notion.so/xanaduai/Different-kinds-of-documentation-69200645fe59442991c71f9e7d8a77f8))

- [X] How-to

2024-10-21 14:17 UTC, isaacdevlugt requested changes
Thanks @obliviateandsurrender! I have some suggestions to try and make the how-to a little shorter. Beyond those suggestions, I like it!

2024-10-21 14:17 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_import_noise_models.py
> +dev_qk_noisy = qml.device("qiskit.aer", wires=n_qubits, shots=n_shots, noise_model=noise_model_qk)
There's a horizontal scroll from this line. Suggestion:

```
dev_qk_noisy = qml.device(
    "qiskit.aer", 
    wires=n_qubits, 
    shots=n_shots, 
    noise_model=noise_model_qk
)
```

Or call `noise_model_qk` something like `noise_qk` (less characters)

2024-10-21 14:17 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_import_noise_models.py
> +print(qml.draw(pl_noisy_circ, decimals=1, max_length=250)())
Not really needed
```suggestion
```

2024-10-21 14:17 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_import_noise_models.py
> +pl_noisy_circ = qml.add_noise(pl_ideal_circ, noise_model=noise_model_pl)
Might be worth having 1 sentence to explain how one _adds_ noise to a circuit with the qiskit plugin vs regular pennylane

Aside: can you use `add_noise` on a qiskit device? 🤔

2024-10-21 14:17 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# and sampled randomly from historical IBM backend data:
```suggestion
# Conversion of a Qiskit noise model into an equivalent PennyLane noise model can be automated with :func:`~.pennylane.from_qiskit_noise`!
# We can see this in practice for a
# `GenericBackendV2 <https://docs.quantum.ibm.com/api/qiskit/qiskit.providers.fake_provider.GenericBackendV2>`_
# backend that gets instantiated with the error data generated
# and sampled randomly from historical IBM backend data:
```

2024-10-21 14:17 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_import_noise_models.py
> +print(pl_noise_model)
This outputs

```
/home/runner/work/qml/qml/venv/lib/python3.10/site-packages/pennylane_qiskit/noise_models.py:131: UserWarning: Readout errors are not supported currently and will be skipped.
  warn("Readout errors are not supported currently and will be skipped.")
```

Is there a noise model in Qiskit that doesn't have readdout errors that won't throw this error?

2024-10-21 14:17 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# these will be supported soon too! 🧑‍💻
```suggestion
# This can be done for any noise model defined in Qiskit, with a minor catch that the
# classical readout errors are not supported yet in PennyLane. 
```

2024-10-21 14:17 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# devices. Integrating them into PennyLane is a powerful way to enable users to perform noisy
```suggestion
# devices. Integrating them into PennyLane is a powerful way to enable users to perform differentiable noisy
```

2024-10-21 14:17 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# on the Qiskit ones either manually by building one-to-one mapping for each kind of error or
```suggestion
# on the Qiskit ones by either manually building a one-to-one mapping for each kind of error or
```

2024-10-21 14:17 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# automatically using the provided conversion functionality. 💪
```suggestion
# automatically using :func:`~.pennylane.from_qiskit_noise`. 💪
```

2024-10-21 14:17 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# the :doc:`noise model how-to <tutorial_how_to_use_noise_models>`, the PennyLane Codebook
```suggestion
# our :doc:`how-to for noise models in PennyLane <tutorial_how_to_use_noise_models>`, the PennyLane Codebook
```

2024-10-22 15:48 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_import_noise_models.py
> +print(pl_noise_model)
Not really. All of the fake backends-based noise models will throw this error! That's why I added a line to explain this to the users.

2024-10-22 15:49 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_import_noise_models.py
> +pl_noisy_circ = qml.add_noise(pl_ideal_circ, noise_model=noise_model_pl)
> can you use add_noise on a qiskit device?

I don't think so, as we ultimately use their device to perform the computation.

2024-10-28 19:53 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_import_noise_models.py
> +
I wanted to keep the measurement errors to show readout errors as well. Modified it to make it more concise.

2024-10-30 15:59 UTC, isaacdevlugt approved these changes

2024-10-30 15:59 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# noise is to be inserted and ``noise functions`` (callables) that apply the corresponding
```suggestion
# noise is to be inserted and noise functions that apply the corresponding
```

2024-10-30 15:59 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_import_noise_models.py
> +print("Are results equal? ", np.allclose(pl_probs, qk_probs, atol=0.01))
```suggestion
```
![Screenshot 2024-10-30 at 11 37 37 AM](https://github.com/user-attachments/assets/c7e932d0-cbcd-4849-9203-421e088a56b0)

Not necessary I think :) The results stacked on each other are self-evident

2024-10-30 15:59 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# the classical readout errors are not supported yet in PennyLane.
```suggestion
# This can be done for any noise model defined in Qiskit, with a minor catch that converting
# classical readout errors from Qiskit are not supported yet in PennyLane. 
# However, we can easily re-insert readout errors into our converted noise model. Here's an
# example that adds `rmeas_fcond` and `rmeas_noise` (defined earlier) to the above
# `pl_noise_model`:

pl_noise_model += {"meas_map": {rmeas_fcond: rmeas_noise}}
pl_noise_model.meas_map
```

If we merge this after v0.39, this will work!

2024-10-30 15:59 UTC, isaacdevlugt commented on pyproject.toml
> -pennylane-qiskit = "0.38.0"
re: comment above, maybe we can wait for v0.39 to go live 🤔

2024-10-30 15:59 UTC, isaacdevlugt commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# using the ``default.mixed`` and ``qiskit.aer`` devices. Note that while we
```suggestion
# using the ``default.mixed`` and ``qiskit.aer`` devices. Note that while we
```
Not sure what the sphinx directive would be for `default.mixed`, but can we link to this? https://docs.pennylane.ai/en/stable/code/api/pennylane.devices.default_mixed.DefaultMixed.html

2024-10-30 19:39 UTC, obliviateandsurrender commented on pyproject.toml
>  pennylane = "0.38.0"
```suggestion
pennylane = "0.39.0"
```

2024-10-30 19:39 UTC, obliviateandsurrender commented on pyproject.toml
> +pennylane-qiskit = "0.38.1"
```suggestion
pennylane-qiskit = "0.39.0"
```

2024-11-01 13:46 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_import_noise_models.py
> +print(pl_noise_model.meas_map)
```suggestion
print(pl_noise_model)
```

2024-11-01 13:46 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# Here's an example that adds ``rmeas_fcond``` and ``rmeas_noise``` (defined earlier) to the above:
```suggestion
# Here's an example that adds ``rmeas_fcond`` and ``rmeas_noise`` (defined earlier) to the above:
```

2024-11-01 13:46 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_import_noise_models.py
> +print(pl_noise_model)
```suggestion
```

2024-11-01 13:46 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# using the :mod:`default.mixed <pennylane.devices.default_mixed>` and ``qiskit.aer``
```suggestion
# `GHZ state <https://en.wikipedia.org/wiki/Greenberger–Horne–Zeilinger_state>`_ using the
# `default.mixed <https://docs.pennylane.ai/en/stable/code/api/pennylane.devices.default_mixed.html>`_
# and `qiskit.aer <https://docs.pennylane.ai/projects/qiskit/en/latest/devices/aer.html>`_
```

2024-11-01 21:33 UTC, soranjh reviewed
Thanks @obliviateandsurrender, nice demo overall, left some comments.

2024-11-01 21:33 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# metadata. This allows for a more functional construction, as we can see by
Please split the sentence, it is not super clear how this is different than Qiskit approach unless I spend some time decoding the text.

2024-11-01 21:33 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# :doc:`how-to for noise models in PennyLane <tutorial_how_to_use_noise_models>`. 🧑‍🏫
Please bring this before the code.

2024-11-01 21:33 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# Importing Qiskit noise models
Do we really need anything discussed up to this point? Creation of the PL and Qiskit noise models seem rather unnecessary.

2024-11-04 17:28 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_import_noise_models.py
> +`Kraus operators <https://pennylane.ai/qml/demos/tutorial_noisy_circuits/#noisy-operations>`_
The demo explains the Kraus operators in the subsection I am tagging here, which I feel has a more relevant explanation than the wiki one.

2024-11-04 17:31 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# In contrast, the noise models in PennyLane are :class:`~.pennylane.NoiseModel`
Since we aim to map a qiskit noise model, we would need to describe it first.

2024-11-04 17:32 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# Importing Qiskit noise models
As one of the requirements for the epic is to compare the UIs for both libraries, we would need the first section to fulfill it.

2024-11-04 19:51 UTC, soranjh requested changes
Thanks @obliviateandsurrender, left my final suggestions which are mainly about rephrasing the text. Some of them are optional. Will be good to go from my side then.

2024-11-04 19:51 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +then learn how to convert a Qiskit noise model into an equivalent PennyLane one.
```suggestion
Noise models describe how a quantum system interacts with its environment.
These models are typically represented by a set of
`Kraus operators <https://pennylane.ai/qml/demos/tutorial_noisy_circuits/#noisy-operations>`_
that encapsulates the probabilistic nature of quantum errors. ⚡ A quantum noise process can be described by different sets of Kraus operators. The non-unique nature of these representations allows quantum computing libraries to use different approaches for storing and building Kraus operators to construct
noise models. In this how-to guide, we will first compare the construction of noise models in
`Qiskit <https://docs.quantum.ibm.com/>`_ and
`PennyLane <https://docs.pennylane.ai/en/stable/code/qml.html>`_, and
then learn how to convert a Qiskit noise model into an equivalent PennyLane one.
```

2024-11-04 19:51 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +then learn how to convert a Qiskit noise model into an equivalent PennyLane one.
Rephrased the first paragraph a bit to make it easier to follow. Feel free to revert or rephrase if needed.

2024-11-04 19:51 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# contains `QuantumError <https://qiskit.github.io/qiskit-aer/stubs/qiskit_aer.noise.QuantumError.html>`_
```suggestion
# contains `QuantumError <https://qiskit.github.io/qiskit-aer/stubs/qiskit_aer.noise.QuantumError.html>`_ operations
```

2024-11-04 19:51 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# contains `QuantumError <https://qiskit.github.io/qiskit-aer/stubs/qiskit_aer.noise.QuantumError.html>`_
[optional]

2024-11-04 19:51 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# `ReadoutError <https://qiskit.github.io/qiskit-aer/stubs/qiskit_aer.noise.ReadoutError.html>`_
```suggestion
# to describe the errors encountered in gate operations. Optionally, it may also have
# `ReadoutError <https://qiskit.github.io/qiskit-aer/stubs/qiskit_aer.noise.ReadoutError.html>`_ operations
```

2024-11-04 19:51 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# `ReadoutError <https://qiskit.github.io/qiskit-aer/stubs/qiskit_aer.noise.ReadoutError.html>`_
[optional]

2024-11-04 19:51 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# and amplitude damping errors for each measurement:
```suggestion
# Let's build a Qiskit noise model that inserts *depolarization* errors for single-qubit gates,
# *bit-flip* errors for the target qubit of the two-qubit gates,
# and *amplitude* damping errors for each measurement:
```

2024-11-04 19:51 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# and amplitude damping errors for each measurement:
Will be nice to have this in italic.

2024-11-04 19:51 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# noise is to be inserted. These conditions are mapped to noise functions
```suggestion
# we want to apply noise. These conditions are mapped to noise functions
```

2024-11-04 19:51 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# Now let us compare the results to see the equivalence between the two noise models:
```suggestion
# Now let's compare the results to see the equivalence between the two noise models:
```

2024-11-04 19:51 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +
Please add one sentence saying that the computed probabilities are the same for both.

2024-11-04 19:51 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# Conversion of a Qiskit noise model into an equivalent PennyLane noise model
Better to rephrase it as:
PennyLane provides the from_qiskit_noise() function to easily convert a Qiskit noise model into an equivalent PennyLane noise model.

2024-11-04 19:51 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +#
No need to have separate paragraphs.

2024-11-04 19:51 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# We can see this in practice for a
```suggestion
# Let's look at an example for a
```

2024-11-04 19:51 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# To import this into PennyLane we can use the :func:`~pennylane.from_qiskit_noise` function:
```suggestion
# We use the :func:`~pennylane.from_qiskit_noise` function to import this noise model into PennyLane :
```

2024-11-04 19:51 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# for each kind of error or automatically using the :func:`~.pennylane.from_qiskit_noise`. 💪
```suggestion
# and develop noise-robust quantum algorithms. In this how-to guide, we learned how to construct
# PennyLane noise models from Qiskit ones by manually building one-to-one mappings
# for each kind of error and also by using the :func:`~.pennylane.from_qiskit_noise` function to convert the Qiskit noise model automatically. 💪
```

2024-11-06 15:27 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# objects with Boolean conditions that help select the operation for which
```suggestion
# objects with Boolean conditions that select the operation for which
```

2024-11-06 15:27 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# or measurement process based on some user-provided metadata. This allows
```suggestion
# or measurement process based on user-provided metadata. This allows
```

2024-11-06 15:29 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# the device definition itself:
```suggestion
# devices. Note that we require :func:`~.pennylane.add_noise` transform
# for adding the PennyLane noise model but the Qiskit noise model is provided in
# the device definition itself:
```

2024-11-06 15:32 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# stored in the ``qk_noise_model``. Internally, this is done in a smart three-step process:
```suggestion
# stored in the Qiskit ``qk_noise_model``. Internally, this is done in a smart three-step process:
```

2024-11-06 15:32 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# stored in the ``qk_noise_model``. Internally, this is done in a smart three-step process:
[optional]

2024-11-06 15:33 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# This can be done for any noise model defined in Qiskit, with a minor catch that
```suggestion
# This can be done for any noise model defined in Qiskit with a minor catch that
```

2024-11-06 15:33 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# Here's an example that adds ``rmeas_fcond`` and ``rmeas_noise`` (defined earlier) to the above:
```suggestion
# Here is an example that adds ``rmeas_fcond`` and ``rmeas_noise`` (defined earlier) to the noise model we created before:
```

2024-11-06 15:36 UTC, soranjh commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# Qiskit provides noise models and tools that one could use to mirror the behaviour of quantum
```suggestion
# Qiskit provides noise models and tools that could be used to mirror the behaviour of quantum
```

2024-11-20 17:20 UTC, ikurecic reviewed
Thanks, @obliviateandsurrender . I've left some comments for you to address.
Also, as a suggestion, you might want to update Poetry so the lock file doesn't regress in versions.

2024-11-20 17:20 UTC, ikurecic commented on demonstrations/tutorial_how_to_import_noise_models.py
> +then learn how to convert a Qiskit noise model into an equivalent PennyLane one.
That's great, but could you also write why a reason why somebody would want to do that?

2024-11-20 17:20 UTC, ikurecic commented on demonstrations/tutorial_how_to_import_noise_models.py
> +print(model_qk)
It's fairly obvious, but could you still add inline comments within this codeblock to designate the different errors? Among other things, this will help with searchability.

2024-11-20 17:20 UTC, ikurecic commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# Building the qiskit noise model
```suggestion
# Building the Qiskit noise model
```

2024-11-20 17:20 UTC, ikurecic commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# Building the pennylane noise model
```suggestion
# Building the PennyLane noise model
```

2024-11-20 17:20 UTC, ikurecic commented on demonstrations/tutorial_how_to_import_noise_models.py
> +
The results aren't actually equal and this sentence wasn't added. I second the request for an explanatory sentence.

2024-11-20 17:20 UTC, ikurecic commented on demonstrations/tutorial_how_to_import_noise_models.py
> +# `Noisy Quantum Theory <https://pennylane.ai/codebook/#06-noisy-quantum-theory>`_,
```suggestion
# the `PennyLane Codebook module on Noisy Quantum Theory <https://pennylane.ai/codebook/#06-noisy-quantum-theory>`_,
```

2024-11-20 17:20 UTC, ikurecic commented on demonstrations/tutorial_how_to_import_noise_models.py
> +print(model_pl)
It would be good to add inline comments to this codeblock, as well.

2024-11-20 17:24 UTC, ikurecic commented
@obliviateandsurrender , could you change the file nomenclature to be `…how_to_import_qiskit_noise_models`, to help with searchability and other matters? This would also include image file names.

2024-11-21 15:02 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_import_noise_models.py
> +then learn how to convert a Qiskit noise model into an equivalent PennyLane one.
Added a sentence for it.

2024-11-22 12:46 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_noise_models.metadata.json
@obliviateandsurrender , this file still has the old file name. Could you change that?

2024-11-22 12:47 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_noise_models.metadata.json
> +            "id": "tutorial_how_to_import_noise_models",
```suggestion
            "id": "tutorial_how_to_import_qiskit_noise_models",
```

2024-11-22 12:49 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_noise_models.metadata.json
> +            "id": "tutorial_how_to_import_noise_models",
I fogot to tag you, @obliviateandsurrender .
I think this is what you meant to do here?

2024-11-22 12:49 UTC, ikurecic commented on demonstrations/tutorial_how_to_use_noise_models.metadata.json
> +            "id": "tutorial_how_to_import_noise_models",
Also, this metadata file should have an update to its date of last modification, otherwise the change won't appear.

2024-11-22 15:43 UTC, ikurecic commented on demonstrations/tutorial_how_to_import_qiskit_noise_models.metadata.json
> +    "dateOfLastModification": "2024-11-22T00:00:00+00:00",
tk
Utkarsh, please don't delete my notes. Thanks.

2024-11-22 16:03 UTC, obliviateandsurrender commented on demonstrations/tutorial_how_to_import_qiskit_noise_models.metadata.json
> +    "dateOfLastModification": "2024-11-22T00:00:00+00:00",
Didn't do it, renaming files made the previous comments disappear.

2024-11-25 08:42 UTC, ikurecic approved these changes

2024-11-25 08:42 UTC, merged