Adapt example data in demo to fit Sphinx Gallery's image dimensions
PennyLaneAI/qml pull request #1246
Opened 2024-10-22 14:13 UTC by doctorperceptron

**Title:**
Adapt example data in demo to fit Sphinx Gallery's image dimensions

**Summary:**
Sphinx Gallery renders single images at 640px by 480px. Adjusting the layout of the example data to better fit these dimensions and reduce white space. 

**Relevant references:**
https://app.shortcut.com/xanaduai/story/76532

2024-10-22 18:02 UTC, DanielNino27 requested changes
Thanks @doctorperceptron ! Just one small question. If the settings on sphix negate specifying `figsize` than your fix looks good to me.

2024-10-22 18:02 UTC, DanielNino27 commented on demonstrations/tutorial_post-variational_quantum_neural_networks.py
> +fig, axes = plt.subplots(nrows=2, ncols=3, layout="constrained")
Would specifying` figsize `inside of subplots help or would that be superseded by the display settings in sphinx? It looks better but seems disproportionately big

2024-10-22 18:21 UTC, doctorperceptron commented on demonstrations/tutorial_post-variational_quantum_neural_networks.py
> +fig, axes = plt.subplots(nrows=2, ncols=3, layout="constrained")
It might! Let's find out...

2024-10-22 18:26 UTC, doctorperceptron commented on demonstrations/tutorial_post-variational_quantum_neural_networks.py
> +fig, axes = plt.subplots(nrows=2, ncols=3, layout="constrained")
Hmm small problem, because we use `matplotlib inline` the figure gets cropped by Jupyter and makes the actual size unpredictable. I think this is the best we can do without disabling matplotlib inline (currently set globally for all demos).

https://matplotlib.org/stable/gallery/subplots_axes_and_figures/figure_size_units.html#id1

2024-10-22 18:47 UTC, DanielNino27 commented on demonstrations/tutorial_post-variational_quantum_neural_networks.py
> +fig, axes = plt.subplots(nrows=2, ncols=3, layout="constrained")
Ok - thanks for checking it out. In that case, the fix is fine with me.

2024-10-22 19:37 UTC, DanielNino27 approved these changes
lgtm

2024-10-24 13:58 UTC, justinpickering approved these changes
LGTM!
Just a note, this new figure layout introduces a 6th figure. Not sure if that's an issue or not given the context of this demo. cc @ikurecic

2024-10-25 12:17 UTC, doctorperceptron commented
> LGTM! Just a note, this new figure layout introduces a 6th figure. Not sure if that's an issue or not given the context of this demo. cc @ikurecic

These figures are a representative sample of the data. Afaik the initial choice of 5 was arbitrary, so changing it to 6 shouldn't material affect the demo.

2024-10-25 12:17 UTC, merged