Fixed Depth Hamiltonian Simulation via Cartan Decomposition demo
PennyLaneAI/qml pull request #1261
Opened 2024-11-11 19:46 UTC by Qottmann

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Remember to do a grammar check of the content you include.
- [ ] All tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

----
If you are writing a demonstration, please answer these questions to facilitate the marketing process.

* GOALS — Why are we working on this now?

  *Eg. Promote a new PL feature or show a PL implementation of a recent paper.*

* AUDIENCE — Who is this for?

  *Eg. Chemistry researchers, PL educators, beginners in quantum computing.*

* KEYWORDS — What words should be included in the marketing post?

* Which of the following types of documentation is most similar to your file? 
(more details [here](https://www.notion.so/xanaduai/Different-kinds-of-documentation-69200645fe59442991c71f9e7d8a77f8))
    
- [ ] Tutorial
- [ ] Demo
- [ ] How-to

2024-11-22 10:22 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +print(len(h_0))
the resulting h_0 is actually not in $\mathfrak{h}$ at all, do you see any obvious mistake in the construction? @dwierichs

2024-11-22 10:29 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +plt.show()
seems wild to me that both 50 and 500 steps seem to do equally bad 🤔

2024-11-22 14:13 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +print(len(h_0))
Let me know whether I should push these changes.

2024-11-22 14:28 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +plt.show()
I think we want to do `time=-t` in `TrotterProduct` because it implements $e^{iHt}$ instead of $e^{-iHt}$ :grimacing:

2024-11-22 14:30 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +plt.show()
Turns out 50 steps is waaay to precise already :D :)

2024-11-24 11:05 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +print(len(h_0))
Those changes of $K^\dagger$ and $K$, arent they just switching roles overall?

> Let me know whether I should push these changes.

That'd be great thanks!

2024-11-25 09:48 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +print(len(h_0))
> arent they just switching roles overall?

I _think_ they currently are not quite consistent between `loss` and the construction of the output Hamiltonian in the CSA.

2024-11-26 21:54 UTC, dwierichs requested changes
Really nice concise demo, packing an advanced topic into comprehensive code and description! :100:
It was very nice to read, clear structure and easy to follow from top to bottom.
I'm also very impressed how quickly/easily you got to the decomposition result in code. This really feels easy! 

I just had the typical nagging to do :P

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +One of them is that the Lie algebra of H, in terms of which
```suggestion
One of them is that the Lie algebra of :math:`H`, in terms of which
```

In addition, the "in terms of which this decomposition is based" reads a bit funny to me personally.
My gut feeling was "in terms on which.." but that also doesn't sound right.

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +    Otherwise this demo should be self-contained. For the mathematically inclined we further recommend our :doc:`demo on the KAK theorem </demos/tutorial_kak_theorem>`
Could unify whether "our" is part of the link text in the two links :upside_down_face: 

The KAK demo link does not work (yet?) in the current preview. Probably will fix itself.

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +Unitary gates in quantum computing are described by the special orthogonal Lie group :math:`SU(2^n)`, so we can use the KAK
```suggestion
Unitary gates in quantum computing are described by the special unitary Lie group :math:`SU(2^n)`, so we can use the KAK
```

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +In particular, we are going to consider the problem of time-evolving a Hermitian operator :math:`H` the generates the time-evolution unitary :math:`U = e^{-i t H}`.
```suggestion
In particular, we are going to consider the problem of time-evolving a Hermitian operator :math:`H` that generates the time-evolution unitary :math:`U = e^{-i t H}`.
```

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +We are going to perform a special case of KAK decomposition, a "KhK decomposition" if you will, on the algebra level of H in terms of
Would suggest one of the following 
```suggestion
We are going to perform a special case of KAK decomposition, a "KhK decomposition" if you will, on the algebra level of :math:`H` in terms of
```

```suggestion
We are going to perform a special case of KAK decomposition, a "KhK decomposition" if you will, on the algebraic level in terms of
```

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +For that we are going to use the Heisenberg model generators and Hamiltonian for :math:`n=4` qubits.
Maybe
```suggestion
For that we are going to use the generators and the Hamiltonian of the Heisenberg model for :math:`n=4` qubits.
```

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +H = qml.sum(*gens)
[super optional] You could include coefficients here, in order to show that the Hamiltonian, while dictating the generators, does not have to be a simple sum, but can be something more complex in the span of generators.

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +For that we are going to use the Heisenberg model generators and Hamiltonian for :math:`n=4` qubits.
It might be nice to state the Hamiltonian and/or generators in math mode here, to relate to the implementation :)

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# A Cartan decomposition is a bipartition :math:`\mathfrak{g} = \mathcal{k} \oplus \mathcal{m}` into a vertical subspace
I think?
```suggestion
# A Cartan decomposition is a bipartition :math:`\mathfrak{g} = \mathfrak{k} \oplus \mathfrak{m}` into a vertical subspace
```

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# (see `wikipedia <https://en.wikipedia.org/wiki/Symmetric_space#Classification_result>`__).
```suggestion
# (see `Wikipedia <https://en.wikipedia.org/wiki/Symmetric_space#Classification_result>`__).
```

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# involution function :math:`\Theta` that fulfils :math:`\Theta(\Theta(g)) = g \forall g \in \mathfrak{g}`. Different
[super optional] 
```suggestion
# involution function :math:`\Theta` that fulfils :math:`\Theta(\Theta(g)) = g \ \forall g \in \mathfrak{g}`. Different 
```

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# In particular, we have :math:`\Theta(\mathfrak{k}) = \mathfrak{k}` and :math:`\Theta(\mathfrak{m}) = - \mathfrak{m}`.
I think for the demo this is fine, but just to have mentioned it:
$\Theta(\mathfrak{m})=-\mathfrak{m}$ does not quite work mathematically, because as a space we have $-\mathfrak{m}=\mathfrak{m}$. So it's definitely true, but strictly speaking does not fix the eigenvalue :upside_down_face:

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +        m (List[PauliSentence]): the odd parity subspace :math:`\Theta(\mathfrak{m}) = \mathfrak{m}` """
Horizontal scrollbar
```suggestion
        involution (callable): Involution function :math:`\Theta(\cdot)` to act on
            PauliSentence ops, should return ``0/1`` or ``True/False``.
    
    Returns:
        k (List[PauliSentence]): the even parity subspace :math:`\Theta(x) = x`
        m (List[PauliSentence]): the odd parity subspace :math:`\Theta(x) = -x` 
    """
```

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +        if involution(op): # odd parity
This does not match the docstring. But I was convinced by the docstring, now I am confused :thinking:

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# sort the operators by whether or not they yield a plus or minus sign from the involution function.
[optional]
You could mention that this is because the Pauli words nicely align with the eigenspace decomposition.

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# A Cartan decomposition is a bipartition :math:`\mathfrak{g} = \mathcal{k} \oplus \mathcal{m}` into a vertical subspace
Just dropping here that in the KAK demo I went for $\mathfrak{k}$, $\mathfrak{p}$ and $\mathfrak{a}$ for the subalgebra, horizontal space and CSA, respectively. They don't have to match, just thought I mention it :)

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +    """Check if ``candidate commutes with all ``ops``"""
```suggestion
    """Check if ``candidate`` commutes with all ``ops``"""
```

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +        a (List): Cartan subalgebra
Horizontal scrollbar
```suggestion
    """Compute the Cartan subalgebra from the odd parity space :math:`\mathfrak{m}`
    of the Cartan decomposition

    This implementation is specific for cases of bases of m with pure Pauli words as
    detailed in Appendix C in `2104.00728 <https://arxiv.org/abs/2104.00728>`__.
    
    Args:
        m (List[PauliSentence]): the odd parity subspace :math:`\Theta(x) = -x
        which (int): Choice for initial element of m from which to construct 
            the maximal Abelian subalgebra
    
    Returns:
        mtilde (List): remaining elements of :math:`\mathfrak{m}` 
            s.t. :math:`\mathfrak{m} = \tilde{\mathfrak{m}} \oplus \mathfrak{h}`.
        a (List): Cartan subalgebra
```
Should it be `a` in the last line?

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +                h.append(m_i)
[super optional reduction]
```suggestion
    m.remove(h[0])
    for m_i in m:
        if _commutes_with_all(m_i, h):
            h.append(m_i)
```

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# In [#Kökcü]_, the authors propose to find the extrema of the cost function
[super optional]
one is enough :) 
```suggestion
# In [#Kökcü]_, the authors propose to find the a local extremum of the cost function
```

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# The latter means that for any point in :math:`e^{i \mathcal{h}}` there is a :math:`t` such that :math:`e^{i t v}` reaches it.
[optional]
```suggestion
# The latter means that for any point in :math:`e^{i \mathcal{h}}` there is a :math:`t` such that :math:`e^{i t v}` approximates it.
```

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +        updates, opt_state = optimizer.update(grad_circuit, opt_state, theta, value=val, grad=grad_circuit, value_fn=loss)
Horizontal scrollbar
```suggestion
        updates, opt_state = optimizer.update(
            grad_circuit, opt_state, theta, value=val, grad=grad_circuit, value_fn=loss
        )
```

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# This trivially reproduces the original Hamiltonian.
"trivially" repeated here.

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# Note that this is valid for arbitrary :math:`t`, such that in that sense the Hamiltonian simulation operator has a fixed depth.
[super optional]
Would be fair in my opinion to be more direct
```suggestion
# Note that this is valid for arbitrary :math:`t`, such that the Hamiltonian simulation operator has a fixed depth.
```

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# We can compute multiple time evolutions and see that the
To be done

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +res_trotter50 = 1 - jnp.abs(jnp.einsum("bij,bji->b", Us_exact.conj(), Us_trotter50)) / 2**n_wires
Not sure whether it will be better, but could consider to write a tiny function that directly produces `res_trotter` for inputs `t` and `n`.

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# DLA and specifically decomposed the Heisenberg model Hamiltonian with :math:`n=4` qubits that has a DLA of dimension :math:`64-1` (:math:`\mathfrak{s u}(2^{n-1})`).
The code said that $\mathfrak{g}$ is $60$-dimensional :eyes: :thinking:

2024-11-26 21:54 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +res_trotter50 = 1 - jnp.abs(jnp.einsum("bij,bji->b", Us_exact.conj(), Us_trotter50)) / 2**n_wires
Also.. sorry... horizontal scrollbar :D

2024-11-28 18:07 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +One of them is that the Lie algebra of H, in terms of which
I just removed the Hamiltonian bit completely and simplified the sentence

2024-11-28 18:08 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +    Otherwise this demo should be self-contained. For the mathematically inclined we further recommend our :doc:`demo on the KAK theorem </demos/tutorial_kak_theorem>`
✅

2024-11-28 18:11 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +For that we are going to use the Heisenberg model generators and Hamiltonian for :math:`n=4` qubits.
I prefer the following

```
For that we are going to use the generators of the Heisenberg model Hamiltonian for :math:`n=4` qubits on a one dimensional chain,

.. math:: \{X_i X_{i+1}, Z_i Z_{i+1}, Z_i Z_{i+1}\}_{i=0}^{2}.
```

2024-11-28 18:12 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +# A Cartan decomposition is a bipartition :math:`\mathfrak{g} = \mathcal{k} \oplus \mathcal{m}` into a vertical subspace
I first did that, but then changed it to match the paper this is based on 🙃

2024-11-28 18:13 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +# In particular, we have :math:`\Theta(\mathfrak{k}) = \mathfrak{k}` and :math:`\Theta(\mathfrak{m}) = - \mathfrak{m}`.
*assuming a 1to1 correspondence in the statement haha :D

2024-11-28 18:14 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +# In particular, we have :math:`\Theta(\mathfrak{k}) = \mathfrak{k}` and :math:`\Theta(\mathfrak{m}) = - \mathfrak{m}`.
I took this from the paper actually, I'd leave it but its a good point !

2024-11-28 18:14 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +# sort the operators by whether or not they yield a plus or minus sign from the involution function.
✅

2024-11-28 18:18 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +        if involution(op): # odd parity
The terminology is a bit confusing because even number => `False` => going to theta(x)=-x subspace

2024-11-28 18:26 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +H = qml.sum(*gens)
would keep it simple 👍

2024-11-28 21:02 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +# We can compute multiple time evolutions and see that the
✅

2024-11-28 21:03 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +# DLA and specifically decomposed the Heisenberg model Hamiltonian with :math:`n=4` qubits that has a DLA of dimension :math:`64-1` (:math:`\mathfrak{s u}(2^{n-1})`).
Oh yeah its actually $\left(\mathfrak{s u}(2^{n-2})\right)^{\oplus 4}$ (a7 in https://arxiv.org/pdf/2309.05690)

2024-11-28 21:03 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +# DLA and specifically decomposed the Heisenberg model Hamiltonian with :math:`n=4` qubits that has a DLA of dimension :math:`64-1` (:math:`\mathfrak{s u}(2^{n-1})`).
✅

2024-11-29 08:11 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +For that we are going to use the Heisenberg model generators and Hamiltonian for :math:`n=4` qubits.
Yeah, that looks great I think :)

2024-11-29 08:12 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +        if involution(op): # odd parity
Ohhh, this had me utterly confused :sweat_smile: Could we pass a around a sign, i.e. `1` or `-1` explicitly, instead?

2024-11-29 08:12 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# A Cartan decomposition is a bipartition :math:`\mathfrak{g} = \mathcal{k} \oplus \mathcal{m}` into a vertical subspace
Ah, good point! Thanks :)

2024-11-29 08:27 UTC, dwierichs requested changes
Thanks for the quick update, @Qottmann :pray: 
I left some suggestions regarding math mode and punctuation.
Otherwise I only wanted to remind to update the metadata, and would have the (optional!) question whether it might be nice for readers to return a sign rather than a Boolean/integer from the involution, in order to avoid the confusion I ran into and stay closer to the main text :) 

Happy to approve after the non-optional changes :) :tada:

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.metadata.json
> +    "references": [
To be updated.

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.metadata.json
> +    "dateOfLastModification": "2024-10-07T00:00:00+00:00",
Reminder to update date.

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.metadata.json
> +    "relatedContent": [
To be updated.

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +.. math:: \{X_i X_{i+1}, Z_i Z_{i+1}, Z_i Z_{i+1}\}_{i=0}^{2}.
```suggestion
.. math:: \{X_i X_{i+1}, Y_i Y_{i+1}, Z_i Z_{i+1}\}_{i=0}^{2}.
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# In particular, we have :math:`\Theta(\mathfrak{k}) = \mathfrak{k}` and :math:`\Theta(\mathfrak{m}) = - \mathfrak{m}`.
Oh wow, then it's definitely fine to inherit the "it is implied" attitude from the paper, I'd say :)

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +We introduce the powerful Lie theoretic decomposition technique for Hamiltonians, :math:`H = K h K^\dagger`,
Trailing punctuation is supposed to go into the math mode part, I recently learned. :upside_down_face:

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +We introduce the powerful Lie theoretic decomposition technique for Hamiltonians, :math:`H = K h K^\dagger`,
```suggestion
We introduce the powerful Lie theoretic decomposition technique for Hamiltonians, :math:`H = K h K^\dagger,`
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +that lets you time-evolve by arbitrary times with fixed depth, :math:`e^{-i t H} = K e^{-i t h} K^\dagger`.
```suggestion
that lets you time-evolve by arbitrary times with fixed depth, :math:`e^{-i t H} = K e^{-i t h} K^\dagger`.
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +decomposition of the unitaries :math:`K` and :math:`e^{-i t h}`.
```suggestion
decomposition of the unitaries :math:`K` and :math:`e^{-i t h}.`
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +as :math:`U = K_1 A K_2`, where :math:`K_{1, 2}` and :math:`A` are elements of two special sub-groups
```suggestion
as :math:`U = K_1 A K_2,` where :math:`K_{1, 2}` and :math:`A` are elements of two special sub-groups
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +:math:`\mathcal{K}` and :math:`\mathcal{A}`, respectively. In special cases, the decomposition simplifies to :math:`U = K A K^\dagger`.
```suggestion
:math:`\mathcal{K}` and :math:`\mathcal{A},` respectively. In special cases, the decomposition simplifies to :math:`U = K A K^\dagger.`
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +matrix :math:`M \in \mathbb{C}^{m \times n}` can be decomposed as :math:`M = U \Lambda V^\dagger`, where :math:`\Lambda`
```suggestion
matrix :math:`M \in \mathbb{C}^{m \times n}` can be decomposed as :math:`M = U \Lambda V^\dagger,` where :math:`\Lambda`
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +are left- and right-unitary with :math:`\mu = \min(m, n)`.
```suggestion
are left- and right-unitary with :math:`\mu = \min(m, n).`
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +Unitary gates in quantum computing are described by the special unitary Lie group :math:`SU(2^n)`, so we can use the KAK
```suggestion
Unitary gates in quantum computing are described by the special unitary Lie group :math:`SU(2^n),` so we can use the KAK
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +theorem to decompose quantum gates into :math:`U = K_1 A K_2`. While the mathematical statement is rather straight-forward,
```suggestion
theorem to decompose quantum gates into :math:`U = K_1 A K_2.` While the mathematical statement is rather straight-forward,
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +In particular, we are going to consider the problem of time-evolving a Hermitian operator :math:`H` the generates the time-evolution unitary :math:`U = e^{-i t H}`.
```suggestion
In particular, we are going to consider the problem of time-evolving a Hermitian operator :math:`H` the generates the time-evolution unitary :math:`U = e^{-i t H}.`
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +The foundation to a KAK decomposition is a Cartan decomposition of the associated Lie algebra :math:`\mathfrak{g}`.
```suggestion
The foundation to a KAK decomposition is a Cartan decomposition of the associated Lie algebra :math:`\mathfrak{g}.`
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# :math:`\mathfrak{k}` and an orthogonal horizontal subspace :math:`\mathfrak{m}`. In practice, it can be induced by an
```suggestion
# :math:`\mathfrak{k}` and an orthogonal horizontal subspace :math:`\mathfrak{m}.` In practice, it can be induced by an
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# involution function :math:`\Theta` that fulfils :math:`\Theta(\Theta(g)) = g \ \forall g \in \mathfrak{g}`. Different
```suggestion
# involution function :math:`\Theta` that fulfils :math:`\Theta(\Theta(g)) = g \ \forall g \in \mathfrak{g}.` Different 
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# :math:`P = P_1 \otimes P_2 .. \otimes P_n` where :math:`P_j \in \{I, X, Y, Z\}`.
```suggestion
# :math:`P = P_1 \otimes P_2 .. \otimes P_n` where :math:`P_j \in \{I, X, Y, Z\}.`
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# In particular, we have :math:`\Theta(\mathfrak{k}) = \mathfrak{k}` and :math:`\Theta(\mathfrak{m}) = - \mathfrak{m}`.
```suggestion
# In particular, we have :math:`\Theta(\mathfrak{k}) = \mathfrak{k}` and :math:`\Theta(\mathfrak{m}) = - \mathfrak{m}.`
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# So in order to perform the Cartan decomposition :math:`\mathfrak{g} = \mathfrak{k} \oplus \mathfrak{m}`, we simply
```suggestion
# So in order to perform the Cartan decomposition :math:`\mathfrak{g} = \mathfrak{k} \oplus \mathfrak{m},` we simply
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# of the associated Lie group :math:`\mathcal{G} := e^{i \mathfrak{g}}`.
```suggestion
# of the associated Lie group :math:`\mathcal{G} := e^{i \mathfrak{g}}.`
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# is induced by the so-called (horizontal) Cartan subalgebra :math:`\mathfrak{h}`. This is a maximal Abelian subalgebra of :math:`\mathfrak{m}` and is not unique.
```suggestion
# is induced by the so-called (horizontal) Cartan subalgebra :math:`\mathfrak{h}.` This is a maximal Abelian subalgebra of :math:`\mathfrak{m}` and is not unique.
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# We then obtain a further split of the vector space :math:`\mathfrak{m} = \tilde{\mathfrak{m}} \oplus \mathfrak{h}`,
```suggestion
# We then obtain a further split of the vector space :math:`\mathfrak{m} = \tilde{\mathfrak{m}} \oplus \mathfrak{h},`
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# where :math:`\tilde{\mathfrak{m}}` is just the remainder of :math:`\mathfrak{m}`.
```suggestion
# where :math:`\tilde{\mathfrak{m}}` is just the remainder of :math:`\mathfrak{m}.`
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# We now have the Cartan decomposition :math:`\mathfrak{g} = \mathfrak{k} \oplus \tilde{\mathfrak{m}} \oplus \mathfrak{h}``
```suggestion
# We now have the Cartan decomposition :math:`\mathfrak{g} = \mathfrak{k} \oplus \tilde{\mathfrak{m}} \oplus \mathfrak{h}`
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# that is such that :math:`e^{i t v}` is dense in :math:`e^{i \mathcal{h}}`.
```suggestion
# that is such that :math:`e^{i t v}` is dense in :math:`e^{i \mathcal{h}}.`
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# This gives us the optimal values of the parameters :math:`\theta_\text{opt}` of :math:`K(\theta_\text{opt}) =: K_c`.
```suggestion
# This gives us the optimal values of the parameters :math:`\theta_\text{opt}` of :math:`K(\theta_\text{opt}) =: K_c.`
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# rotating the Hamiltonian by the critical :math:`K_c`.
I think comma fits well here?
```suggestion
# rotating the Hamiltonian by the critical :math:`K_c,`
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# This gives us the KhK decomposition of :math:`H`,
```suggestion
# This gives us the KhK decomposition of :math:`H,`
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# .. math:: H = K_c^\dagger h_0 K_c
```suggestion
# .. math:: H = K_c^\dagger h_0 K_c.
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# Note that this is valid for arbitrary :math:`t`, such that the Hamiltonian simulation operator has a fixed depth.
```suggestion
# Note that this is valid for arbitrary :math:`t,` such that the Hamiltonian simulation operator has a fixed depth.
```

2024-11-29 08:27 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# dimension of the subspaces, in particular :math:`2 |\mathfrak{k}| + |\mathfrak{h}|`. Note, however,
```suggestion
# dimension of the subspaces, in particular :math:`2 |\mathfrak{k}| + |\mathfrak{h}|.` Note, however,
```

2024-11-29 09:28 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +        if involution(op): # odd parity
Ah sorry, I did not. I like the new version!! :heart_eyes:

2024-12-03 11:59 UTC, Qottmann commented on _static/demo_thumbnails/opengraph_demo_thumbnails/OGthumbnail_fdhs.png
I only just now realize that perhaps this should read $K - A - K^\dagger$ 😬

2024-12-03 12:16 UTC, Qottmann commented on _static/demo_thumbnails/opengraph_demo_thumbnails/OGthumbnail_fdhs.png
I'd like to hear what @dwierichs thinks about it

2024-12-03 13:09 UTC, dwierichs approved these changes
Just two tiny optional suggestions :) 
Nice job @Qottmann :100:
 Looking forward to sharing this one, actually :sweat_smile:

2024-12-03 13:09 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +For that, let us first construct it and import some libraries that we are going to use later.
```suggestion
For that, let us first construct it from the generators. We also import some libraries that we are going to use later.
```

2024-12-03 13:09 UTC, dwierichs commented on demonstrations/tutorial_fdhs.py
> +# .. note::
If you like you could do
```suggestion
# .. admonition:: Notation
#     :class: note
```

2024-12-03 13:28 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +# .. note::
ouh nice!

2024-12-03 13:32 UTC, Qottmann commented on _static/demo_thumbnails/opengraph_demo_thumbnails/OGthumbnail_fdhs.png
> Ah, I just noticed that the demo puts K † first, maybe that should be made matching, then, if you go for the † :)

because circuits are read backwards? i.e. $U = K A K^\dagger$ would be $K^\dagger - A- K$ on the circuit order?

2024-12-03 13:58 UTC, dwierichs commented on _static/demo_thumbnails/opengraph_demo_thumbnails/OGthumbnail_fdhs.png
Ah, of course :facepalm:

2024-12-12 23:05 UTC, justinpickering commented on demonstrations/tutorial_fdhs.metadata.json
> +        "Quantum Computing"
Should Algorithms be added as a category?
```suggestion
    "categories": [
        "Quantum Computing",
        "Algorithms"
```

2024-12-13 11:07 UTC, Qottmann commented on demonstrations/tutorial_fdhs.metadata.json
> +        "Quantum Computing"
Yes good idea 👍  will add ✅

2024-12-13 13:00 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +In particular, we follow the approach in [#Kökcü]_ that directly provides us with a (fixed depth) circuit
@justinpickering fixed-depth

2024-12-13 13:02 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +powerful mathematical result integral for quantum compilation, circuit optimization, and Hamiltonian simulation.
@justinpickering "mathemtical result integral" ?

2024-12-13 13:04 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +    Otherwise this demo should be self-contained. For the mathematically inclined we further recommend our :doc:`demo on the KAK theorem </demos/tutorial_kak_theorem>`
This shouldn't be a separate sentence @justinpickering

2024-12-13 13:05 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +Goal
@justinpickering Title is too vague.

2024-12-13 13:06 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +`Fixed Depth Hamiltonian Simulation via Cartan Decomposition <https://arxiv.org/abs/2104.00728>`__ [#Kökcü]_,
@justinpickering instead of apostrophes, use text formatting (if necessary) or simply state "the paper" or similar.

2024-12-13 13:07 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +For that, we are going to use the generators of the Heisenberg model Hamiltonian for :math:`n=4` qubits on a one-dimensional chain,
@justinpickering there are good links for this on pennylane.ai

2024-12-13 13:08 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# (see `Wikipedia <https://en.wikipedia.org/wiki/Symmetric_space#Classification_result>`__).
@justinpickering not a good link name

2024-12-13 13:08 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +#     common - not our - choice for the vertical subspace in a Cartan decomposition.
@justinpickering  should be mdashes instead of hyphens

2024-12-13 13:08 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# One common choice of involution is the so-called even-odd involution for Pauli words
@justinpickering missing comma

2024-12-13 13:09 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# :math:`P = P_1 \otimes P_2 .. \otimes P_n` where :math:`P_j \in \{I, X, Y, Z\}.`
@justinpickering missing comma

2024-12-13 13:10 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# We have successfully decomposed the :math:`60`-dimensional Lie algebra
@justinpickering shouldn't be inline math

2024-12-13 13:10 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# For that, the subspaces need to fulfill the following three commutation relations
@justinpickering missing interpunction

2024-12-13 13:11 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# We mentioned earlier that we are aiming to do a special case of KAK decomposition where the second unitary :math:`K_2 = K_1^\dagger`.
@justinpickering period should be inside math environment.
Also see following lines.

2024-12-13 13:11 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# With this we have identified the first subgroup (:math:`\mathcal{K}`) of the KAK decomposition. The other subgroup
@justinpickering also here

2024-12-13 13:12 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# is induced by the so-called (horizontal) Cartan subalgebra :math:`\mathfrak{h}.` This is a maximal Abelian subalgebra of :math:`\mathfrak{m}` and is not unique.
"it is" @justinpickering

2024-12-13 13:13 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# Variational KhK
@justinpickering title is missing the noun

2024-12-13 13:13 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# Obtaining the actual decomposition is highly non-trivial and there is no canonical way to go about computing it in terms of linear algebra sub-routines.
@justinpickering sentence missing detail

2024-12-13 13:13 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# where :math:`\langle \cdot, \cdot \rangle` is some inner product (in our case the trace inner product :math:`\langle A, B \rangle = \text{tr}(A^\dagger B)`).
@justinpickering interpunction issue

2024-12-13 13:14 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# Let us construct it. To numerically avoid very large vectors, we take :math:`\pi (\text{mod} 2)` which preserves the dense property of :math:`v`.
@justinpickering interpunction

2024-12-13 13:14 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# .. note::
@justinpickering to improve link naming

2024-12-13 13:15 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +    """Boilerplate jax optimization"""
@justinpickering incorrect capitalization. Also see above.

2024-12-13 13:15 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# trivially decompose its unitary as :math:`e^{-i t h_0} = e^{-i t \sum_{j=1}^{|\mathfrak{h}|} c_j h_j}` as :math:`\prod_{j=1}^{|\mathfrak{h}|} e^{-i t c_j h_j}`.
@justinpickering  interpunction

2024-12-13 13:16 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# We compute multiple time evolutions for different times and compare Suzuki-Trotter products with the KAK decomposition circuit.
@justinpickering ndash

2024-12-13 13:16 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# We see the expected behavior of Suzuki-Trotter product formulas getting worse with an increase in time
@justinpickering ndash

2024-12-13 13:17 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# DLA and specifically decomposed the Heisenberg model Hamiltonian with :math:`n=4` qubits that has a DLA of dimension :math:`60` (:math:`\left(\mathfrak{s u}(2^{n-2})\right)^{\oplus 4}`).
@justinpickering initialism not defined

2024-12-13 13:17 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# .. include:: ../_static/authors/korbinian_kottmann.txt
@justinpickering remove

2024-12-13 13:49 UTC, Qottmann commented on demonstrations/tutorial_fdhs.metadata.json
> +    "title": "Fixed Depth Hamiltonian Simulation via Cartan Decomposition",
note that this is taken over 1-to-1 from the original paper this demo is reproducing https://arxiv.org/abs/2104.00728

2024-12-13 13:59 UTC, ikurecic commented on demonstrations/tutorial_fdhs.metadata.json
> +    "title": "Fixed Depth Hamiltonian Simulation via Cartan Decomposition",
Thanks, @Qottmann , I know — copying it 1-1 has several issues, one of which is consistency on the pennylane.ai website, and another is related to mimicking the original publication too closely, which may lead readers to assume it is authored by the authors of the related paper. So we'll address that, as well.

2024-12-13 15:33 UTC, josh146 commented on demonstrations/tutorial_fdhs.metadata.json
> +    "title": "Fixed Depth Hamiltonian Simulation via Cartan Decomposition",
I am generally okay with using the same title if that makes sense for the demo, as it means that people searching for the paper will also find the demo (which will be helpful for them).

Do we feel that the byline on the demo would clearly indicate the demo authorship?

2024-12-13 21:30 UTC, justinpickering commented on demonstrations/tutorial_fdhs.metadata.json
> +    "seoDescription": "Using Cartan decomposition and the KAK theorem to decompose unitary gates following the approach in 'Fixed Depth Hamiltonian Simulation via Cartan Decomposition' (arXiv:2104.00
@ikurecic 
```suggestion
    "seoDescription": "Using Cartan decomposition and the KAK theorem to decompose unitary gates following the approach in Fixed Depth Hamiltonian Simulation via Cartan Decomposition (arXiv:2104.00728) with code implementation in PennyLane.",
```

2024-12-13 21:31 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +We introduce the powerful Lie theoretic decomposition technique for Hamiltonians, :math:`H = K h K^\dagger,`
@ikurecic 
```suggestion
We introduce the powerful Lie-theoretic decomposition technique for Hamiltonians, :math:`H = K h K^\dagger,`
```

2024-12-13 21:43 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +that lets you time-evolve by arbitrary times with fixed depth, :math:`e^{-i t H} = K e^{-i t h} K^\dagger.`
@ikurecic @Qottmann - thoughts on this?
```suggestion
that lets you time-evolve quantum states by arbitrary times with fixed depth, :math:`e^{-i t H} = K e^{-i t h} K^\dagger.`
```

2024-12-13 21:44 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +In particular, we follow the approach in [#Kökcü]_ that directly provides us with a (fixed depth) circuit
@ikurecic 
```suggestion
In particular, we follow the approach in [#Kökcü]_ that directly provides us with a (fixed-depth) circuit
```

2024-12-13 21:47 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +powerful mathematical result integral for quantum compilation, circuit optimization, and Hamiltonian simulation.
@ikurecic 
```suggestion
powerful mathematical result, integral to quantum compilation, circuit optimization, and Hamiltonian simulation.
```

2024-12-13 21:56 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +the singular value decomposition to Lie groups. For that, recall that the singular value decomposition states that any
@ikurecic Do you suggest linking to [qml.math.svd](https://docs.pennylane.ai/en/stable/code/api/pennylane.math.svd.html)? Though, this demo's code doesn't use `qml.math.svd`. 

Note, there are not 'great' content links on pennylane.ai for SVD.

2024-12-13 21:59 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +.. note:: We recommend a basic understanding of Lie algebras, see e.g. our :doc:`intro for quantum practitioners </demos/tutorial_liealgebra>`.
@ikurecic 
```suggestion
.. note:: We recommend a basic understanding of Lie algebras, see e.g. :doc:`Introducing (Dynamical) Lie Algebras for quantum practitioners </demos/tutorial_liealgebra>`.
```

2024-12-13 22:04 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +Goal
@ikurecic @Qottmann What could this section be updated to, for it to be more descriptive? Perhaps `KAK Decomposition and Time-Evolution`?

2024-12-13 22:08 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +`Fixed Depth Hamiltonian Simulation via Cartan Decomposition <https://arxiv.org/abs/2104.00728>`__ [#Kökcü]_,
>instead of apostrophes, use text formatting (if necessary) 

Can you provide an example for this? I'm not sure I understand.

2024-12-13 22:32 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +# (see `Wikipedia <https://en.wikipedia.org/wiki/Symmetric_space#Classification_result>`__).
@ikurecic 
```suggestion
# (see `classification result <https://en.wikipedia.org/wiki/Symmetric_space#Classification_result>`__).
```

2024-12-13 22:37 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +#     common - not our - choice for the vertical subspace in a Cartan decomposition.
@ikurecic  I don't see this 'admonition' section in the demo preview, should I?

2024-12-13 22:39 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +# :math:`P = P_1 \otimes P_2 .. \otimes P_n` where :math:`P_j \in \{I, X, Y, Z\}.`
```suggestion
# :math:`P = P_1 \otimes P_2 .. \otimes P_n`, where :math:`P_j \in \{I, X, Y, Z\}.`
```

2024-12-13 22:41 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +# We have successfully decomposed the :math:`60`-dimensional Lie algebra
```suggestion
# We have successfully decomposed the 60-dimensional Lie algebra 
```

2024-12-13 22:43 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +# For that, the subspaces need to fulfill the following three commutation relations
What exactly do you suggest here? @ikurecic

2024-12-13 22:46 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +# into a :math:`24`-dimensional vertical subspace and a :math:`36`-dimensional subspace.
```suggestion
# We have successfully decomposed the 60-dimensional Lie algebra 
# into a 24-dimensional vertical subspace and a 36-dimensional subspace.
```

2024-12-13 22:46 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +# We have successfully decomposed the :math:`60`-dimensional Lie algebra
https://github.com/PennyLaneAI/qml/pull/1261/files/a42ab1c991c491279d73b27501cf74ca2d8edea4#r1884621118

2024-12-13 22:47 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +# We mentioned earlier that we are aiming to do a special case of KAK decomposition where the second unitary :math:`K_2 = K_1^\dagger`.
```suggestion
# We mentioned earlier that we are aiming to do a special case of KAK decomposition where the second unitary :math:`K_2 = K_1^\dagger.`
```

2024-12-13 22:50 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +# With this we have identified the first subgroup (:math:`\mathcal{K}`) of the KAK decomposition. The other subgroup
I'm not sure what you mean here, @ikurecic

2024-12-13 22:51 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +# is induced by the so-called (horizontal) Cartan subalgebra :math:`\mathfrak{h}.` This is a maximal Abelian subalgebra of :math:`\mathfrak{m}` and is not unique.
```suggestion
# is induced by the so-called (horizontal) Cartan subalgebra :math:`\mathfrak{h}.` This is a maximal Abelian subalgebra of :math:`\mathfrak{m}` and it is not unique.
```

2024-12-13 22:53 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +# We compute multiple time evolutions for different times and compare Suzuki-Trotter products with the KAK decomposition circuit.
```suggestion
# We compute multiple time evolutions for different times and compare Suzuki—Trotter products with the KAK decomposition circuit.
```

2024-12-13 22:54 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +# We see the expected behavior of Suzuki-Trotter product formulas getting worse with an increase in time
```suggestion
# We see the expected behavior of Suzuki—Trotter product formulas getting worse with an increase in time
```

2024-12-13 22:55 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +# trivially decompose its unitary as :math:`e^{-i t h_0} = e^{-i t \sum_{j=1}^{|\mathfrak{h}|} c_j h_j}` as :math:`\prod_{j=1}^{|\mathfrak{h}|} e^{-i t c_j h_j}`.
Hm not sure what you mean here. Can you show me? @ikurecic

2024-12-13 22:59 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +# DLA and specifically decomposed the Heisenberg model Hamiltonian with :math:`n=4` qubits that has a DLA of dimension :math:`60` (:math:`\left(\mathfrak{s u}(2^{n-2})\right)^{\oplus 4}`).
```suggestion
# DLA (:doc:`Dynamic Lie Algebras <tutorial_liealgebra>`) and specifically decomposed the Heisenberg model Hamiltonian with :math:`n=4` qubits that has a DLA of dimension :math:`60` (:math:`\left(\mathfrak{s u}(2^{n-2})\right)^{\oplus 4}`).
```

2024-12-13 23:15 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +    Otherwise this demo should be self-contained. For the mathematically inclined we further recommend our :doc:`demo on the KAK theorem </demos/tutorial_kak_theorem>`
```suggestion
    Otherwise, this demo should be self-contained, though for the mathematically inclined, we further recommend our :doc:`demo on the KAK theorem </demos/tutorial_kak_theorem>`
```

2024-12-13 23:18 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +# where :math:`\langle \cdot, \cdot \rangle` is some inner product (in our case the trace inner product :math:`\langle A, B \rangle = \text{tr}(A^\dagger B)`).
```suggestion
# where :math:`\langle \cdot, \cdot \rangle` is some inner product (in our case, the trace inner product :math:`\langle A, B \rangle = \text{tr}(A^\dagger B)`).
```

2024-12-13 23:19 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +# Let us construct it. To numerically avoid very large vectors, we take :math:`\pi (\text{mod} 2)` which preserves the dense property of :math:`v`.
This? @ikurecic 
```suggestion
# Let us construct it. To numerically avoid very large vectors, we take :math:`\pi (\text{mod} 2)`, which preserves the dense property of :math:`v`.
```

2024-12-13 23:21 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +    """Boilerplate jax optimization"""
```suggestion
    """Boilerplate JAX optimization"""
```

2024-12-13 23:24 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +#     :doc:`JAXOpt </demos/tutorial_How_to_optimize_QML_model_using_JAX_and_JAXopt>`.
```suggestion
# We are going to use ``jax`` and ``optax`` and write some boilerplate for the optimization procedure.
#
# .. note:: 
#     You can check our demos on parameter optimization in JAX with 
#     :doc:`Optax </demos/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax>` or 
#     :doc:`JAXOpt </demos/tutorial_How_to_optimize_QML_model_using_JAX_and_JAXopt>`.
```

2024-12-16 08:31 UTC, ikurecic reviewed
@justinpickering FYI

2024-12-16 08:31 UTC, ikurecic commented on demonstrations/tutorial_fdhs.metadata.json
> +    "seoDescription": "Using Cartan decomposition and the KAK theorem to decompose unitary gates following the approach in 'Fixed Depth Hamiltonian Simulation via Cartan Decomposition' (arXiv:2104.00
```suggestion
    "seoDescription": "Using Cartan decomposition and the KAK theorem to decompose unitary gates following the approach in the paper Fixed Depth Hamiltonian Simulation via Cartan Decomposition (arXiv:2104.00728) with a code implementation in PennyLane.",
```

2024-12-16 08:31 UTC, ikurecic commented on demonstrations/tutorial_fdhs.metadata.json
> +    "title": "Fixed Depth Hamiltonian Simulation via Cartan Decomposition",
Thanks, @josh146 . As I am leaving, I will defer this to @justinpickering then. My recommendation would be to not engage in SEO-related behavior that may be interpreted as malicious by authors of existing content.

2024-12-16 08:31 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +powerful mathematical result integral for quantum compilation, circuit optimization, and Hamiltonian simulation.
I would say no, @justinpickering .
@Qottmann , could you maybe try to rephrase this sentence so it's a bit clearer? Thanks.

2024-12-16 08:31 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +the singular value decomposition to Lie groups. For that, recall that the singular value decomposition states that any
After we chatted, I agree. Thanks! As I suggested, this would be a good glossary term to point out to @alvaro-at-xanadu .

2024-12-16 08:31 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +.. note:: We recommend a basic understanding of Lie algebras, see e.g. our :doc:`intro for quantum practitioners </demos/tutorial_liealgebra>`.
Wow, the capitalization of the title of that PennyLane Demo is very incorrect. I would suggest to fix it and use the correct case here, @justinpickering .

2024-12-16 08:31 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +Goal
I am leaving the feedback to @Qottmann here, but note that it should be in sentence case.

2024-12-16 08:31 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +`Fixed Depth Hamiltonian Simulation via Cartan Decomposition <https://arxiv.org/abs/2104.00728>`__ [#Kökcü]_,
Whoops, I saw this incorrectly on Friday afternoon (traditionally my best time to be doing reviews…), I saw apostrophes instead of backticks.

2024-12-16 08:31 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +For that, we are going to use the generators of the Heisenberg model Hamiltonian for :math:`n=4` qubits on a one-dimensional chain,
The first one — this is a very recent PennyLane Demo and we would like to promote it more.

2024-12-16 08:31 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# (see `Wikipedia <https://en.wikipedia.org/wiki/Symmetric_space#Classification_result>`__).
Adding more context on links is respectful to users. For example, "(see the results of the classification of Riemannian symmetric spaces)"

2024-12-16 08:31 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +#     common - not our - choice for the vertical subspace in a Cartan decomposition.
Great catch, @justinpickering ! This supports my thesis of checking the code at the same time as the rendering. ☺
Try using the 'note' syntax (can be found higher up in this Demo, for example).

2024-12-16 08:31 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# :math:`P = P_1 \otimes P_2 .. \otimes P_n` where :math:`P_j \in \{I, X, Y, Z\}.`
@justinpickering 
```suggestion
# :math:`P = P_1 \otimes P_2 .. \otimes P_n,` where :math:`P_j \in \{I, X, Y, Z\}.`
```

2024-12-16 08:31 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# We have successfully decomposed the :math:`60`-dimensional Lie algebra
I'm sorry, @justinpickering , what is this link to?

2024-12-16 08:31 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# For that, the subspaces need to fulfill the following three commutation relations
A colon, period, or comma. And the math environment after can be adapted based on that choice.

2024-12-16 08:31 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# With this we have identified the first subgroup (:math:`\mathcal{K}`) of the KAK decomposition. The other subgroup
As we noted on Friday, there are brackets directly following inline math, and what immediately follows inline math (if not a space) should be inside the inline math environment. However, this would look strange with the closing bracket, so here I had suggested this format instead:
```suggestion
# With this we have identified the first subgroup, :math:`\mathcal{K},` of the KAK decomposition. The other subgroup
```

2024-12-16 08:31 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# where :math:`\langle \cdot, \cdot \rangle` is some inner product (in our case the trace inner product :math:`\langle A, B \rangle = \text{tr}(A^\dagger B)`).
No, if you remember our chat on Friday, @justinpickering , this is the issue of the brackets having to be within the inline math to assist with rendering. Your suggestion here with the comma is actually unnecessary, the original text is a correct variant.

2024-12-16 08:31 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# Let us construct it. To numerically avoid very large vectors, we take :math:`\pi (\text{mod} 2)` which preserves the dense property of :math:`v`.
No, as you may remember from our talk on Friday, interpunction directly following inline math should be inside the inline math environment. @justinpickering

2024-12-16 08:31 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# trivially decompose its unitary as :math:`e^{-i t h_0} = e^{-i t \sum_{j=1}^{|\mathfrak{h}|} c_j h_j}` as :math:`\prod_{j=1}^{|\mathfrak{h}|} e^{-i t c_j h_j}`.
As we talked on Friday, interpunction directly following inline math should be within the inline math environment.
```suggestion
# trivially decompose its unitary as :math:`e^{-i t h_0} = e^{-i t \sum_{j=1}^{|\mathfrak{h}|} c_j h_j}` as :math:`\prod_{j=1}^{|\mathfrak{h}|} e^{-i t c_j h_j}.`
```

2024-12-16 12:05 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +that lets you time-evolve by arbitrary times with fixed depth, :math:`e^{-i t H} = K e^{-i t h} K^\dagger.`
since we are working on the unitary level and not actually evolving any states here I'd leave it as is

2024-12-16 12:07 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +the singular value decomposition to Lie groups. For that, recall that the singular value decomposition states that any
There is a SVD intro in https://pennylane.ai/qml/demos/tutorial_mps but I think linking this here is not a good fit

2024-12-16 12:20 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +Goal
I'd like to keep the "goal" in the section title; I pushed the following

```
Goal: Fast-forwarding time evolutions using the KAK decomposition
-----------------------------------------------------------------
```

2024-12-16 12:29 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +# We have successfully decomposed the :math:`60`-dimensional Lie algebra
the link goes to a comment/suggestion fixing this and other inline-math numbers. marking this as resolved

2024-12-16 12:36 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +that lets you time-evolve by arbitrary times with fixed depth, :math:`e^{-i t H} = K e^{-i t h} K^\dagger.`
A wait, could do this
```suggestion
that lets you perform time-evolution by arbitrary times with fixed depth, :math:`e^{-i t H} = K e^{-i t h} K^\dagger.`
```

2024-12-16 12:37 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +powerful mathematical result integral for quantum compilation, circuit optimization, and Hamiltonian simulation.
rephrased slightly based on @justinpickering suggestion, that covers it well

2024-12-16 12:39 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +# For that, the subspaces need to fulfill the following three commutation relations
updated

2024-12-16 12:42 UTC, Qottmann commented on _static/demo_thumbnails/opengraph_demo_thumbnails/OGthumbnail_fdhs.png
decided to leave as is

2024-12-17 12:38 UTC, ikurecic commented on demonstrations/tutorial_fdhs.metadata.json
> +    "seoDescription": "Using Cartan decomposition and the KAK theorem to decompose unitary gates following the approach in 'Fixed Depth Hamiltonian Simulation via Cartan Decomposition' (arXiv:2104.00
Thanks for asking, @Qottmann . This is related to SEO.

2024-12-17 17:24 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +# (see `Wikipedia <https://en.wikipedia.org/wiki/Symmetric_space#Classification_result>`__).
Thanks @ikurecic 
```suggestion
# (see `the results of the classification of Riemannian symmetric spaces <https://en.wikipedia.org/wiki/Symmetric_space#Classification_result>`__).
```

2024-12-17 17:28 UTC, justinpickering commented on demonstrations/tutorial_fdhs.metadata.json
> +    "seoDescription": "Using Cartan decomposition and the KAK theorem to decompose unitary gates following the approach in 'Fixed Depth Hamiltonian Simulation via Cartan Decomposition' (arXiv:2104.00
Thanks @ikurecic, noted.

2024-12-17 17:38 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +# trivially decompose its unitary as :math:`e^{-i t h_0} = e^{-i t \sum_{j=1}^{|\mathfrak{h}|} c_j h_j}` as :math:`\prod_{j=1}^{|\mathfrak{h}|} e^{-i t c_j h_j}`.
Thanks @ikurecic

2024-12-17 18:45 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +# Variational KhK
@ikurecic @Qottmann 
```suggestion
# Variational KhK decomposition
```

2024-12-17 18:52 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +# .. note::
@ikurecic I think the links are clear given the preceding sentence:: `You can check our demos on parameter optimization in JAX with`. I don't think any changes here are necessary, though feel free to unresolve if you feel otherwise.

2024-12-17 18:54 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +# .. include:: ../_static/authors/korbinian_kottmann.txt
@ikurecic 
```suggestion
```

2024-12-17 19:01 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +#     common - not our - choice for the vertical subspace in a Cartan decomposition.
Thanks for fixing the linebreak issue, I can now see this section in the preview. @Qottmann 
I've added the emdashes following @ikurecic feedback, let me know if the below looks correct

```suggestion
#     common—not our—choice for the vertical subspace in a Cartan decomposition.
```

2024-12-17 19:04 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +# Obtaining the actual decomposition is highly non-trivial and there is no canonical way to go about computing it in terms of linear algebra sub-routines.
I will have to defer this to @Qottmann. 
_Why_ is the decomposition highly non-trivial + no canonical way to go about computing it?

2024-12-17 19:17 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +.. note:: We recommend a basic understanding of Lie algebras, see e.g. our :doc:`intro for quantum practitioners </demos/tutorial_liealgebra>`.
@ikurecic - see suggested update below, and PR to change the Lie algebra demo title casing: https://github.com/PennyLaneAI/qml/pull/1282
```suggestion
.. note:: We recommend a basic understanding of Lie algebras, see e.g. :doc:`Introducing (dynamical) Lie algebras for quantum practitioners </demos/tutorial_liealgebra>`.
```
cc @Qottmann

2024-12-17 19:32 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +For that, we are going to use the generators of the Heisenberg model Hamiltonian for :math:`n=4` qubits on a one-dimensional chain,
I think this comes down to our priorities: do we want to prioritize our own content over external sites, even if the external link provides more descriptive context for readers? If we do, we can link to the PennyLane demo; if not, we link to the Wikipedia page. Given the context @Qottmann provided, I think the Wikipedia link is the most appropriate choice here.

```suggestion
For that, we are going to use the generators of the `Heisenberg model <https://en.wikipedia.org/wiki/Quantum_Heisenberg_model>`__ Hamiltonian for :math:`n=4` qubits on a one-dimensional chain,
```

2024-12-17 19:43 UTC, justinpickering commented on demonstrations/tutorial_fdhs.metadata.json
> +    "title": "Fixed Depth Hamiltonian Simulation via Cartan Decomposition",
Hi @Qottmann - Are there any alternative titles you can suggest that would be equally representative (as using the paper title)? If so, I’d recommend updating it for the reasons @ikurecic mentioned above.

If not, we should keep the same title (although change it sentence case). 
cc @josh146

2024-12-17 19:44 UTC, justinpickering commented on demonstrations/tutorial_fdhs.metadata.json
> +            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_fdhs.png"
waiting on decision with demo title name

2024-12-17 19:45 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +r"""Fixed Depth Hamiltonian Simulation via Cartan Decomposition
Waiting on decision with demo title name https://github.com/PennyLaneAI/qml/pull/1261/files#r1883899552

2024-12-18 10:11 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +# Variational KhK
👍

2024-12-18 10:12 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +#     common - not our - choice for the vertical subspace in a Cartan decomposition.
looks good to me 👍

2024-12-18 10:25 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +.. note:: We recommend a basic understanding of Lie algebras, see e.g. our :doc:`intro for quantum practitioners </demos/tutorial_liealgebra>`.
@ikurecic @justinpickering any reason to force the full demo name? I agree with making the link more descriptive, and think something like this would read more smoothly

```suggestion
.. note:: We recommend a basic understanding of Lie algebras, see e.g. our :doc:`introduction to (dynamical) Lie algebras for quantum practitioners </demos/tutorial_liealgebra>`.
```

2024-12-18 10:32 UTC, Qottmann commented on demonstrations/tutorial_fdhs.metadata.json
> +    "title": "Fixed Depth Hamiltonian Simulation via Cartan Decomposition",
We've done several demos on papers in the past where we used the title of the paper. So far I've heard only positive feedback from authors that appreciated the shoutout and form of praise. That is, of course, as long as the origin of the provided contents are appropriately acknowledged. Since we cite their paper, and, specifically say that this is what we cover in this demo, in the first paragraph, I have no worries of stepping on anyone's toes.

This + the title really is perfect in that it encapsulates the contents well

2024-12-18 11:59 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +.. note:: We recommend a basic understanding of Lie algebras, see e.g. our :doc:`intro for quantum practitioners </demos/tutorial_liealgebra>`.
I agree. This is why I wrote "missing capitalization _and/or_ the link text is too vague."

2024-12-18 12:01 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +#     common - not our - choice for the vertical subspace in a Cartan decomposition.
@justinpickering On pennylane.ai we usually use spaces around mdashes, so I would recommend to continue using that convention, when possible.

2024-12-18 12:06 UTC, ikurecic commented on demonstrations/tutorial_fdhs.py
> +# Obtaining the actual decomposition is highly non-trivial and there is no canonical way to go about computing it in terms of linear algebra sub-routines.
The sentence itself, as an opening sentence of a standalone section, is missing detail. This is still not a review comment that is relevant for @Qottmann , this is a Product Team review, where we attempt to improve the external messaging across the pennylane.ai web properties and improve user experience with PennyLane products. CC @justinpickering 

I suggest this:
```suggestion
# Despite the process shown in the previous section, performing the actual KAK decomposition is usually highly non-trivial and there is no canonical way to go about computing it in terms of linear algebra sub-routines.
```

2024-12-18 12:08 UTC, Qottmann commented on demonstrations/tutorial_fdhs.py
> +#     common - not our - choice for the vertical subspace in a Cartan decomposition.
it already renders with spaces, will adding additional spaces create a wider gap?
<img width="1465" alt="image" src="https://github.com/user-attachments/assets/233bd6a6-40b5-4e43-a1ee-e78615b5b991" />

2024-12-18 21:03 UTC, josh146 commented on demonstrations/tutorial_fdhs.metadata.json
> +    "title": "Fixed Depth Hamiltonian Simulation via Cartan Decomposition",
👆

2024-12-18 21:04 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +r"""Fixed Depth Hamiltonian Simulation via Cartan Decomposition
@ikurecic @Qottmann 
```suggestion
r"""Fixed depth Hamiltonian simulation via Cartan decomposition
```

2024-12-18 21:15 UTC, justinpickering commented on demonstrations/tutorial_fdhs.py
> +#     common - not our - choice for the vertical subspace in a Cartan decomposition.
>it already renders with spaces, will adding additional spaces create a wider gap?

It renders with spaces since there is a physical space currently between every dash. There shouldn't be a wider space gap with the emdashes.

>@justinpickering On pennylane.ai we usually use spaces around mdashes, so I would recommend to continue using that convention, when possible.

Thanks, updated below!

```suggestion
#     common — not our — choice for the vertical subspace in a Cartan decomposition.
```

2024-12-18 21:18 UTC, justinpickering commented on demonstrations/tutorial_fdhs.metadata.json
> +    "dateOfLastModification": "2024-12-13T00:00:00+00:00",
tk

2024-12-18 21:42 UTC, justinpickering commented on demonstrations/tutorial_fdhs.metadata.json
> +            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_fdhs.png"
@ikurecic  - I've updated the tutorial's .py and metadata 'slug' name to the demo name, and updated the image names, too. See https://github.com/PennyLaneAI/qml/pull/1261/commits/39b1e00f18134184e6d4d3d68db9544fc50a8174.
Let me know if anything else is needed!

2024-12-18 21:45 UTC, justinpickering commented on demonstrations/tutorial_fdhs.metadata.json
> +            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_fdhs.png"
tk - this affects the URL of the demo. To confirm final URL with Ashley once published.

2024-12-19 19:19 UTC, justinpickering approved these changes

2024-12-19 19:49 UTC, merged