add pl angles
PennyLaneAI/qml pull request #1273
Opened 2024-12-04 16:33 UTC by soranjh

**Summary:**
The PR updates QSVT on hardware how-to to use PennyLane `poly_to_angles` function following [sc-79728].

2024-12-04 17:02 UTC, KetpuntoG requested changes
Great to see the functionality in action!
Could you update the last modification date in the metadata?

2024-12-04 17:02 UTC, KetpuntoG commented on demonstrations/tutorial_qsvt_hardware.py
> +print(angles_pg)
What do you mean by "pg"?

2024-12-04 17:26 UTC, soranjh commented on demonstrations/tutorial_qsvt_hardware.py
> +print(angles_pg)
```suggestion
angles_pq = convert_angles(ang_seq)
print(angles_pq)
```

2024-12-04 17:27 UTC, soranjh commented on demonstrations/tutorial_qsvt_hardware.py
> +print(angles_pg)
Corrected to pq for pyqsp.

2024-12-04 17:29 UTC, soranjh commented on demonstrations/tutorial_qsvt_hardware.py
> +print(angles_pg)
@KetpuntoG Why the angles_pl and angles_pq are not the same?

2024-12-04 18:19 UTC, KetpuntoG commented on demonstrations/tutorial_qsvt_hardware.py
> +print(angles_pg)
They follow different strategies. In fact, if you run pyqsp again it will probably give you a different set. This is because an optimization is being done and there may be more than one global minimum

2024-12-04 18:19 UTC, KetpuntoG commented on demonstrations/tutorial_quantum_analytic_descent.metadata.json
> +    "dateOfLastModification": "2024-12-04T00:00:00+00:00",
It is not the correct file

2024-12-04 20:47 UTC, soranjh commented on demonstrations/tutorial_quantum_analytic_descent.metadata.json
> +    "dateOfLastModification": "2024-12-04T00:00:00+00:00",
Corrected.

2024-12-04 22:47 UTC, KetpuntoG approved these changes
🚀

2024-12-05 16:57 UTC, KetpuntoG commented
I updated one cell to use the new `qml.transform_angles` functionality. Now it is perfect :)

2024-12-05 22:16 UTC, Jaybsoni commented on demonstrations/tutorial_qsvt_hardware.py
> +print(angles_pyqsp)
These angles don't match the ones generated by PL even after we transformed them. Maybe you should add a comment explaining that even though the angles are different, they will both produce the same polynomial transformation.

2024-12-05 22:16 UTC, Jaybsoni approved these changes
Looks good, left one comment. Otherwise good to go from my side 👍🏼

2024-12-06 13:58 UTC, merged