Update QSVT demos
PennyLaneAI/qml pull request #1276
Opened 2024-12-04 23:04 UTC by KetpuntoG

This PR updates "intro to qsvt" and "apply qsvt" to be compatible with the updated qsvt functionality.
[sc-72638]

2024-12-09 22:07 UTC, soranjh requested changes
Thanks @KetpuntoG, looks good overall. Left some minor comments.

2024-12-09 22:07 UTC, soranjh commented on demonstrations/tutorial_intro_qsvt.py
> +    out = qml.matrix(qml.qsvt([[a]], target_poly, encoding_wires=[0], block_encoding="embedding"))
Why it should be `[[a]]` instead of `[a]`?

2024-12-09 22:07 UTC, soranjh commented on demonstrations/tutorial_apply_qsvt.py
> +as input: the block encoding of the matrix to be transformed and a set projectors which determine the polynomial
```suggestion
as input: the block encoding of the matrix to be transformed and a set of projectors which determine the polynomial
```

2024-12-09 22:07 UTC, soranjh commented on demonstrations/tutorial_apply_qsvt.py
> +phi_qsvt = qml.transform_angles(phi_pyqsp, "QSP", "QSVT")  # convert pyqsp angles to qsvt
```suggestion
phi_qsvt = qml.transform_angles(phi_pyqsp, "QSP", "QSVT")  # convert pyqsp angles to be compatible with QSVT
```

2024-12-09 22:07 UTC, soranjh commented on demonstrations/tutorial_apply_qsvt.py
> +    qml.ctrl(qml.QSVT, control=(ancilla_wire,), control_values=(0,))(
Please add a small comment saying why you do this. Originally we had "apply even and odd polynomial approx".

2024-12-09 22:07 UTC, soranjh commented on demonstrations/tutorial_apply_qsvt.py
> +        )
Wht this is changed?

2024-12-09 22:07 UTC, soranjh commented on demonstrations/tutorial_apply_qsvt.py
> +    )
Same here, why the change?

2024-12-09 22:07 UTC, soranjh commented on demonstrations/tutorial_apply_qsvt.py
> +        A.T, phi, "ancilla2", [0, 1, 2])
Why we need to change this?

2024-12-09 23:03 UTC, KetpuntoG commented on demonstrations/tutorial_apply_qsvt.py
> +        )
I passed black in the demo, and these lines were updated. Should I put them as they were (idem next comments)?

2024-12-09 23:12 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qsvt.py
> +    out = qml.matrix(qml.qsvt([[a]], target_poly, encoding_wires=[0], block_encoding="embedding"))
To clarify that it is a matrix (2 dimensions)
Let me solve it as the user may pass just "a"

2024-12-10 13:58 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +    qml.ctrl(qml.QSVT, control=(ancilla_wire,), control_values=(0,))(
Trying to do everything in this one function is making it a little messy, could we construct the blockencoding operator, the projectors and compute the 'dim' outside of the function and pass them in as inputs?

2024-12-10 13:58 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +
why the extra space?

2024-12-10 13:59 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +        )
I don't think we usually pass black in the demo because we care more about the rendering of the code on the website ?

2024-12-10 14:02 UTC, Jaybsoni commented on demonstrations/tutorial_intro_qsvt.py
> +    out = qml.matrix(qml.qsvt([[a]], target_poly, encoding_wires=[0], block_encoding="embedding"))
I don't like that we have to pass [[a]] to get the expected behaviour. Is this just how the UI is? or will we get the same output if we pass "a"?

2024-12-10 14:07 UTC, Jaybsoni reviewed
Nothing blocking from my side. Just left some suggestions to make the code blocks flow better. Happy to approve once the questions are answered.

2024-12-10 19:39 UTC, KetpuntoG commented on demonstrations/tutorial_apply_qsvt.py
> +    qml.ctrl(qml.QSVT, control=(ancilla_wire,), control_values=(0,))(
I tried it but it was a bit messy too. I have simplified the code, let me know what you think

2024-12-10 20:58 UTC, soranjh approved these changes
Thanks @KetpuntoG, looks good to go. Please check the built versions to make sure they render correctly.

2024-12-10 20:58 UTC, soranjh commented on demonstrations/tutorial_intro_qsvt.py
> +                              block_encoding="embedding"))
Better to have a single line.

2024-12-10 21:48 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qsvt.py
> +                              block_encoding="embedding"))
```suggestion
    out = qml.matrix(qml.qsvt(a,  target_poly, encoding_wires=[0], block_encoding="embedding"))
```

2024-12-11 19:01 UTC, Jaybsoni commented on demonstrations/tutorial_intro_qsvt.py
> +methods is an active area of research. The :class:`~pennylane.qsvt` function in PennyLane computes the angles internally.
Maybe provide a link to the method we use? It was based on the RiverLane paper right?

2024-12-11 19:02 UTC, Jaybsoni approved these changes
Looks good from my side 👍🏼

2024-12-11 19:43 UTC, merged