Create a demos hub draft
PennyLaneAI/qml pull request #133
Opened 2020-09-11 00:21 UTC by thisac

A first draft of the new QML website redesign. The new Demos hub page is reachable by clicking the Demos card on the current QML page. This Demos hub contains 3 cards in a similar style as the ones on the parent page:

* **Learn QML/PennyLane**:
    * Containing reviewed/endorsed tutorials divided into the subsections:
        * Basic algorithms
        * Using near term devices
        * Learning QML

* **QML Research**:
    * Containing research-related demonstrations divided into subsections:
        * Extending classical machine learning
        * Exploring quantum effects/data

* **Community**:
    * Containing demonstrations created by the community (no subsections).

**Still to do:**

- [ ] Add new images to the three demos cards
- [ ] Look through and sort the demos into pages/sections
- [ ] Update the filter system
- [ ] Create a "How to submit demos" subpage

...to be continued...

2020-09-11 16:18 UTC, trbromley commented on demos_learning.rst
> +    :figure: demonstrations/vqe_parallel/vqe_diagram.png
Is it worth having a separate QChem subheading, so that interested readers can find the qchem demos in one spot

2020-09-12 03:47 UTC, josh146 commented on demos_learning.rst
> +    :figure: demonstrations/vqe_parallel/vqe_diagram.png
I would argue no, for a couple of reasons:

* We already have a 'quantum chemistry' filter (and I think 'quantum chemistry' is a better grouping than 'qchem')

* I want to minimize the number of categories we have (for now); only include a category if it is a no-brainer. Too many categories means longer vertical scrolling and emptier looking categories.

* Tutorials that are grouped due to some API similarity (such as qchem), rather than a general topic (quantum chemistry) I think should be grouped in the documentation instead. I would like to do what we have in the SF docs; at the bottom of each quickstart/module, all relevant tutorials are linked. E.g., see https://strawberryfields.readthedocs.io/en/stable/introduction/photonic_hardware.html#tutorials.

  In this case, we would add a link to relevant tutorials for QChem here: https://pennylane.readthedocs.io/en/stable/introduction/chemistry.html

2020-09-12 03:49 UTC, josh146 commented on demos_learning.rst
> +----------------
I would call this category 'Learning PennyLane'. All tutorials below focus more on the 'how to use PennyLane' aspect rather than the theory.

2020-09-12 04:13 UTC, josh146 commented on demonstrations.rst
> +            </blockquote>
This looks really nice!

2020-09-12 04:14 UTC, josh146 commented on demos_submission.rst
> +How to submit a demo
I imagine, in the short term, we could simply duplicate the 'Contributing' section of the README here

2020-09-18 05:07 UTC, josh146 reviewed
Looks great so far @thisac!

I suppose the next action items are:

* Fill out the `demos_submission.rst` page

* Update the readme (perhaps delete most of the contributing info, and just link to `demos_submission.rst`)

* Add related demo links (probably this could be done in a separate PR?)

* Make sure URLs redirect properly

2020-09-18 05:07 UTC, josh146 commented on demos_community.rst
> +Community
This page looks a bit empty. Might be good to have a placeholder image?

2020-09-18 05:07 UTC, josh146 commented on demos_research.rst
> +algorithms under `Optimization`_.
I'm not sure this paragraph explains the difference between the two sections. However, I'm not 100% sure I can offer anything better... might be good to get @mariaschuld's thoughts here.

2020-09-18 05:07 UTC, josh146 commented on demos_community.rst
> +Community
Options we have on hand include
![image](https://user-images.githubusercontent.com/2959003/93558108-de2e5380-f9bb-11ea-921b-3411d1dfcf53.png)

2020-09-18 05:07 UTC, josh146 commented on demos_community.rst
> +Community
Or even something like 
![image](https://user-images.githubusercontent.com/2959003/93558136-e6868e80-f9bb-11ea-9335-09726aa3d49c.png)

^ would be better as a card background, maybe something from https://mdbootstrap.com/docs/jquery/components/cards/ or https://mdbootstrap.com/docs/jquery/components/jumbotron/?

2020-09-18 05:07 UTC, josh146 commented on demos_submission.rst
> +Write this when implementing the community page.
Looks like this still needs to be written :)

2020-09-18 12:39 UTC, trbromley reviewed
Thanks @thisac, looks awesome! Will the follow up changes be done in this PR or another?

2020-09-18 12:39 UTC, trbromley commented on demonstrations.rst
> +                                <img src="_static/board.png" class="img-fluid" style="max-width: 88px;"></img>
This icon feels a little like the "What is QML" one - are there any candidate alternatives? If not, then I think it's ok

2020-09-18 12:39 UTC, trbromley commented on demonstrations.rst
> +                    Do you want to make you're own demo using PennyLane? Read
What about making this another card? E.g. we have
- Basics
- Research
- Community
- Submit

2020-09-18 12:39 UTC, trbromley commented on demonstrations.rst
> +                            <p class="card-text">Using a quantum graph recurrent neural network to learn quantum dynamics</p>
```suggestion
                            <p class="card-text">Use a quantum graph recurrent neural network to learn quantum dynamics</p>
```

2020-09-18 12:39 UTC, trbromley commented on demonstrations.rst
> +                            <p class="card-text">Perform QAOA for MaxCut.</p>
Maybe we should have e.g., a target of two sentences for each box to make them more comparable

2020-09-18 12:39 UTC, trbromley commented on demos_basics.rst
> +    :tags: autograd
We should revisit this one soon with the new updates to core, since we don't need to worry about keyword arguments.

2020-09-18 12:39 UTC, trbromley commented on demos_research.rst
> +algorithms under `Optimization`_.
Not a big thing, but the order they were mentioned in the text didn't match the order they are given below

2020-09-18 12:39 UTC, trbromley commented on demos_research.rst
> +algorithms under `Optimization`_.
Also maybe QML first as it might be of interest to a wider audience

2020-09-18 12:39 UTC, trbromley commented on demos_submission.rst
> +    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/css/mdb.min.css" rel="stylesheet">
What's this for?

2020-09-18 12:54 UTC, josh146 commented on demonstrations.rst
> +                    Do you want to make you're own demo using PennyLane? Read
I don't know, I prefer the look of the current 'call to arms' below the three main cards.

2020-09-18 13:01 UTC, thisac commented on demonstrations.rst
> +                                <div class="white-text d-flex justify-content-center"><h5>Read more <i class="fas fa-angle-double-right"></i></h5></div>
Oh noes! Thanks for catching this. :facepalm:

2020-09-18 13:04 UTC, thisac commented on demonstrations.rst
> +                            <p class="card-text">Perform QAOA for MaxCut.</p>
I think that sounds good. I actually only took the text from the hover box of the cards, while I probably should've rewritten them to fit the cards better.

2020-09-18 13:05 UTC, thisac commented on demos_basics.rst
> +---------------
That'd be nice! I'll add that!

2020-09-18 13:05 UTC, thisac commented on demos_community.rst
> +Community
Agree that it looks a bit empty now. Thanks for the suggestions @josh146!

2020-09-18 13:07 UTC, thisac commented on demos_submission.rst
> +Write this when implementing the community page.
Yes, I've actually written this in a separate branch, since I thought the community page would entail a lot more work. I'll create a separate PR for it today and then merged it into this branch. :slightly_smiling_face:

2020-09-18 13:12 UTC, thisac commented on demonstrations.rst
> +                                <img src="_static/board.png" class="img-fluid" style="max-width: 88px;"></img>
Yes, agreed. I took the images from the already existing image folder, and these were the best I could find (that didn't seem to be used as obviously in other places). I would be happy to put other, new images for all three cards, although I'm not very keen on creating them myself (will probably not look very good).

I would reckon it's OK to keep these for now and then perhaps in the future do a more thorough update of images on the website? Not sure exactly how we wish to proceed here. @josh146 @mariaschuld @glassnotes

2020-09-18 13:17 UTC, thisac commented on demos_submission.rst
> +    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/css/mdb.min.css" rel="stylesheet">
Honestly, I'm not really sure. Things don't show properly without it though. Perhaps @josh146 can explain why this is needed?

2020-09-18 13:23 UTC, thisac commented
Thanks @josh146 and @trbromley for the quick reviews.
 
> I suppose the next action items are:
> 
> * Fill out the `demos_submission.rst` page

Yes, that's almost done (but in a separate branch that'll be merged into this one).

> * Update the readme (perhaps delete most of the contributing info, and just link to `demos_submission.rst`)

Good point! I'll fix that. :+1: 

> * Add related demo links (probably this could be done in a separate PR?)

I was thinking this could be done separately as well. :slightly_smiling_face: 

> * Make sure URLs redirect properly

Also a good point!

> Will the follow up changes be done in this PR or another?

Yes, as noted above the plan was to have two more PRs: one with the community page updated (that's why it's quite empty) + the submission guide, and one with the related demo links. Other than those two, this PR should contain all other changes.

2020-09-18 14:20 UTC, glassnotes commented on demos_research.rst
> +    :tooltip: Fit one dimensional noisy data with a quantum neural network.
```suggestion
    :tooltip: Fit one-dimensional noisy data with a quantum neural network.
```

2020-09-18 15:32 UTC, thisac commented on demos_basics.rst
> +The `Getting started`_ section is a great place to start if you've just
That's a very good point @glassnotes. I've noticed that as well, and I think that it'd be nicer if the heading would be visible as well, but I'm not sure how this could be fixed. Maybe @josh146 knows?

2020-09-18 16:21 UTC, co9olguy commented on demos_basics.rst
> +The `Getting started`_ section is a great place to start if you've just
This is a long-standing bug in our webpage theme. I think it's fixable, but we haven't yet been able to properly fix

2020-09-18 17:38 UTC, glassnotes commented on demos_basics.rst
> +The `Getting started`_ section is a great place to start if you've just
Think I managed to hack something together. @thisac I hope you don't mind I committed it to your branch here.

2020-09-18 18:49 UTC, co9olguy commented on demos_basics.rst
> +    :tags: autograd
This one is pretty out of date (not wrong, just not really focusing on the things we want to)

2020-09-18 18:51 UTC, co9olguy commented on demos_basics.rst
> +The `Getting started`_ section is a great place to start if you've just
If you managed to fix this, @josh146 will buy you a :beer:

2020-09-18 20:10 UTC, thisac commented on demos_community.rst
> +Community
I added this to the other, slightly unnecessary, [community page PR](https://github.com/PennyLaneAI/qml/pull/136/).

2020-09-19 01:46 UTC, josh146 commented on demos_basics.rst
> +The `Getting started`_ section is a great place to start if you've just
@glassnotes I once spent a week *solely* trying to fix this bug. Thanks you!!!

2020-09-19 04:44 UTC, josh146 commented on demos_basics.rst
> +    :tags: autograd
Yep, almost all of it is out of date. Perhaps we just take it down?

2020-09-19 17:16 UTC, glassnotes commented on demos_basics.rst
> +The `Getting started`_ section is a great place to start if you've just
No problem! :smile:

2020-09-21 01:17 UTC, josh146 commented on demos_submission.rst
> +    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/css/mdb.min.css" rel="stylesheet">
Oh, this is because the `mdb` CSS is not included by default on most pages (as it is not needed, and minimizing the amount of CSS to load decreases page load time). On pages where MDB components are used, however, it has to be included.

2020-09-21 01:57 UTC, josh146 approved these changes
Thanks @thisac, loving the new look!

This looks good from my end, I think there are only a couple of things from my end that must be done before merging into master:

* Get input from @mariaschuld regarding https://github.com/PennyLaneAI/qml/pull/133/files#r490703646

* The demo submission guide page is still unwritten - is the plan to merge #136 into this PR before merging this PR?

2020-09-21 01:57 UTC, josh146 commented on demonstrations.rst
> +                                <img src="_static/board.png" class="img-fluid" style="max-width: 88px;"></img>
Yep, there aren't any pre-existing alternatives --- we would have to make more. I'm happy to leave this as-is until we have new icons/images.

2020-09-21 01:57 UTC, josh146 commented on demonstrations.rst
> +                            <p class="card-text">Optimize variational quantum algorithms with a minimized number of shots by using the Rosalin optimizer.</p>
The new descriptions are great!

2020-09-21 01:57 UTC, josh146 commented on demonstrations.rst
> +                                <p class="mb-1 grey-text px-3">Begin your journey into PennyLane and quantum machine learning.</p>
This card is slightly 'shorter' (in height) than the other cards. This could be fixed by adding a couple of extra words into the description, or perhaps better to simply modify the CSS to make them all the same height?

2020-09-21 01:57 UTC, josh146 commented on demos_basics.rst
> +    :tags: autograd
I'm thinking we just remove this card for now?

2020-09-21 17:22 UTC, trbromley approved these changes
Thanks @thisac, I have a few comments on the wording in places, but it's overall awesome!

2020-09-21 17:22 UTC, trbromley commented on demos_research.rst
> +applications; either on your own local hardware, using simulators from Xanadu,
"On your own local hardware" made me think that users would need to buy a mini chip and take it home :laughing: 
How about "on your own computer"?

2020-09-21 17:22 UTC, trbromley commented on demos_research.rst
> +QML. Explore various different optimizers and applications such as the
The "not strictly related to" didn't read so well to me, maybe something like:
"Here you will find demonstrations showcasing quantum optimization"

2020-09-21 20:33 UTC, thisac commented on demonstrations.rst
> +                            <p class="card-text">Optimize variational quantum algorithms with a minimized number of shots by using the Rosalin optimizer.</p>
@trbromley I can do that, but I'm guessing it's something that was put there on purpose. Do you think it's better without the zooming-in-when-hovering? @josh146?

2020-09-21 20:40 UTC, co9olguy commented on demos_basics.rst
> +The `Getting started`_ section is a great place to start if you've just
Is this fix portable to other repos using the same theme (and hence having the same bug)?

2020-09-21 21:09 UTC, glassnotes commented on demos_basics.rst
> +The `Getting started`_ section is a great place to start if you've just
Hmm it should be - it just adds some padding to the the specific type of CSS element that those sections are. Which other repos is this in? I can try one out.

2020-09-22 05:24 UTC, mariaschuld commented on demos_research.rst
> +algorithms under `Optimization`_.
Sounds good, I tried to edit it a bit:

```suggestion
Explore cutting-edge research using PennyLane. The demonstrations below implement 
ideas from inspiring papers that investigate the training of quantum circuits. 
You can find research that targets quantum machine learning in the `QML`_ section, 
or discover other variational quantum optimization algorithms under `Optimization`_.
```

2020-09-22 09:01 UTC, josh146 commented on demonstrations.rst
> +                            <p class="card-text">Optimize variational quantum algorithms with a minimized number of shots by using the Rosalin optimizer.</p>
I'm happy for it to be removed! The only reason it's there is I thought it looked cool 😆 But I have no great attachment to it.

2020-09-23 13:48 UTC, co9olguy commented on demonstrations.rst
> +                                <p class="mb-1 grey-text px-3">Begin your journey into PennyLane and discover the wonders of quantum machine learning.</p>
:facepalm: :laughing:

2020-09-23 15:20 UTC, thisac commented on demonstrations.rst
> +                                <p class="mb-1 grey-text px-3">Begin your journey into PennyLane and discover the wonders of quantum machine learning.</p>
Perhaps not the best wording... any other suggestions? :laughing:

2020-09-23 15:29 UTC, josh146 commented on demonstrations.rst
> +                                <p class="mb-1 grey-text px-3">Begin your journey into PennyLane and discover the wonders of quantum machine learning.</p>
'Begin your journey into quantum machine learning with PennyLane'? 🤔

2020-09-23 19:52 UTC, glassnotes commented on demonstrations.rst
>                                  <div class="white-text d-flex justify-content-center"><h5>Read more <i class="fas fa-angle-double-right"></i></h5></div>
Does this mis-alignment happen for anyone else when viewing in a narrower window? (Screencap is from Firefox on Linux).

![image](https://user-images.githubusercontent.com/2068515/94062376-95f4a400-fdb4-11ea-9078-e9bd191da83e.png)

2020-09-24 03:44 UTC, thisac commented on demonstrations.rst
> +                                <p class="mb-1 grey-text px-3">Begin your journey into PennyLane and discover the wonders of quantum machine learning.</p>
```suggestion
                                <p class="mb-1 grey-text px-3">Begin your journey into quantum machine learning with PennyLane.</p>
```

2020-09-24 04:26 UTC, josh146 commented on demos_basics.rst
> +The `Getting started`_ section is a great place to start if you've just
I think almost all repos that use the same theme have the same bug 😢 So the Photonics repo, PL docs, and SF docs.

It would be good to host the theme separately/centrally, so that we don't have to fix bugs multiple times.

P.S. @glassnotes, what app did you use to capture that gif?

2020-09-24 04:28 UTC, josh146 commented on demonstrations.rst
>                                  <div class="white-text d-flex justify-content-center"><h5>Read more <i class="fas fa-angle-double-right"></i></h5></div>
This occurs for me as well. This is an artifact of me designing the website and using only a maximized Firefox window and a mobile phone screen for testing 🤦 @co9olguy has a list of rendering issues and bugs that occur with windows of width ~700px

2020-09-24 12:05 UTC, glassnotes commented on demos_basics.rst
> +The `Getting started`_ section is a great place to start if you've just
@josh146 I used [peek](https://github.com/phw/peek)

2020-09-24 19:10 UTC, co9olguy commented on demonstrations.rst
>                                  <div class="white-text d-flex justify-content-center"><h5>Read more <i class="fas fa-angle-double-right"></i></h5></div>
Yes, the "reduced browser window" blind spot has led to a few small glitches, but I hadn't noticed this one before, thanks @glassnotes!

2020-09-24 21:16 UTC, thisac commented on demos_basics.rst
> +The `Getting started`_ section is a great place to start if you've just
<img src="https://user-images.githubusercontent.com/6934626/94200962-49c76380-fe89-11ea-918f-cc73425aaa9a.gif" width="512">

2020-09-24 21:27 UTC, thisac commented
I just merged in the community placeholder page + submission guide into this branch, so everything is finally here (sorry for any possible confusion). I've gone through all the suggestions here in this PR and updated some things; the only ones being left is whether we should keep the hovering effect for the featured cards and the "Open an issue" section of the submission guide. I think it looks good as it is now, but I'm happy to change these things if that's preferred. :slightly_smiling_face: 

Let me know if anyone wants to go for another final review before merging.
@josh146 @trbromley @mariaschuld @co9olguy @glassnotes

2020-09-24 21:38 UTC, glassnotes commented
> hovering effect for the featured card

Do you mean how it zooms in a little bit when you mouse over? I actually didn't notice that before, but I like it, it makes things look more lively!

2020-09-24 21:48 UTC, glassnotes commented on demonstrations.rst
> +                          <img class="card-img-top" src="_static/thumbs/training.png" alt="Card image cap">
This image doesn't show up in the featured demo carousel, the file seems to no longer be in this branch (at least not in that specific directory). Should it link to a different image?

2020-09-24 22:31 UTC, thisac commented on demonstrations.rst
> +                          <img class="card-img-top" src="_static/thumbs/training.png" alt="Card image cap">
Oh, good catch @glassnotes! I'm not sure why the image is not there. It's created locally for me (and I think it should be generated when building the demos). I'll look into it, although @josh146 might already know why this is?

2020-09-25 02:15 UTC, co9olguy commented on demos_submission.rst
> +    John Doe
```suggestion
    Ada Lovelace
```
Good to be balanced :)

2020-09-25 02:45 UTC, josh146 commented on demonstrations.rst
> +                          <img class="card-img-top" src="_static/thumbs/training.png" alt="Card image cap">
Oh, I believe this is because this demo has been temporarily taken down in #137. It will need to be removed from the carousel (potentially replaced with something else)

2020-09-25 13:07 UTC, thisac commented on demonstrations.rst
> +                          <img class="card-img-top" src="_static/thumbs/training.png" alt="Card image cap">
Oh, right. I forgot about that.Thanks for reminding me @josh146 and thanks @glassnotes for noticing it. :tada:

2020-09-28 19:29 UTC, mariaschuld commented
@thisac  looks great. I would only have a super minor suggestion, to change the "QML" header (and link) to "Quantum Machine Learning". Sorry for not spotting it earlier, but I think there is no need here for confusing abbreviations...

Other than that good to go.

2020-09-28 20:21 UTC, thisac commented on demos_research.rst
> +You can find research that targets quantum machine learning in the `QML`_ section,
```suggestion
You can find research that targets quantum machine learning in the `Quantum machine learning`_ section, 
```

2020-09-28 20:21 UTC, thisac commented on demos_research.rst
> +QML
```suggestion
Quantum machine learning
```

2020-09-28 20:22 UTC, thisac commented on demonstrations.rst
>  QML Demos
```suggestion
Demos
```

2020-09-29 19:14 UTC, co9olguy commented on demonstrations.rst
> +                        <div class="text-center d-flex align-items-center pb-2">
```suggestion
                        <div class="text-center d-flex align-items-center pb-2" style="justify-content: center;">
```

2020-09-29 19:16 UTC, co9olguy commented on demonstrations.rst
> +                        <div class="text-center d-flex align-items-center pb-2">
```suggestion
                        <div class="text-center d-flex align-items-center pb-2" style="justify-content: center;">
```

2020-09-29 19:17 UTC, co9olguy commented on demonstrations.rst
> +                        <div class="text-center d-flex align-items-center pb-2">
```suggestion
                        <div class="text-center d-flex align-items-center pb-2" style="justify-content: center;">
```

2020-09-29 19:22 UTC, co9olguy commented on demos_submission.rst
> +hosting service such as GitHub, Bitbucket or GitLab. Good formats for a demonstration include:
```suggestion
hosting service such as GitHub, Bitbucket, or GitLab. Good formats for a demonstration include:
```

2020-09-29 19:23 UTC, co9olguy commented on demos_submission.rst
> +  `example2 <https://github.com/hsim13372/quantum_natural_gradient>`__].
```suggestion
* Jupyter notebooks [`example <https://github.com/lanabozanic/quantum_natural_gradient/blob/master/qng_tutorial.ipynb>`__]

* Python scripts with detailed comments and explanations
  [`example <https://github.com/PennyLaneAI/qml/blob/master/demonstrations/tutorial_vqe.py>`__]

* Repositories containing a collection of Python scripts, Jupyter notebooks, and
  documentation/dependencies [`example1 <https://github.com/PatrickHuembeli/vqc_loss_landscapes>`__,
  `example2 <https://github.com/hsim13372/quantum_natural_gradient>`__]
```

2020-09-29 19:23 UTC, co9olguy commented on demos_submission.rst
> +Alternatively, you can also submit a link to a rendered Jupyter notebook using e.g. `Colab
```suggestion
Alternatively, you can also submit a link to a rendered Jupyter notebook using e.g., `Colab
```

2020-09-29 19:23 UTC, co9olguy commented on demos_submission.rst
> +<https://nbviewer.jupyter.org/>`_, `Sagemaker <https://aws.amazon.com/sagemaker/>`_ or `Binder <https://mybinder.org/>`_.
```suggestion
<https://nbviewer.jupyter.org/>`_, `Sagemaker <https://aws.amazon.com/sagemaker/>`_, or `Binder <https://mybinder.org/>`_.
```

2020-09-29 19:24 UTC, co9olguy commented on demos_submission.rst
> +couple of guidelines that might be good keep in mind.
```suggestion
couple of guidelines that might be good to keep in mind.
```

2020-09-29 19:25 UTC, co9olguy commented on demos_submission.rst
> +* Include the demos dependencies (e.g. PennyLane version along with any relevant
```suggestion
* Include the demo's dependencies (e.g., PennyLane version along with any relevant
```

2020-09-29 19:25 UTC, co9olguy commented on demos_submission.rst
> +using the "Community demo" template. Please include at least your name, a title, an abstract and a
```suggestion
using the "Community demo" template. Please include at least your name, a title, an abstract, and a
```

2020-09-29 19:26 UTC, co9olguy commented on demos_submission.rst
> +The title of your issue should be "[DEMO] your-demo-title" (e.g. "[DEMO] Frugal shot optimization with
```suggestion
The title of your issue should be "[DEMO] your-demo-title" (e.g., "[DEMO] Frugal shot optimization with
```

2020-09-29 19:27 UTC, co9olguy commented on demos_submission.rst
> +right-hand side.
```suggestion
Rosalin", without the quotes), and make sure the "demos" label on the
right-hand side is checked.
```

2020-09-29 20:05 UTC, co9olguy commented
Thanks @thisac :smiley: 

There are still a number of things to polish before merging. Some are just keeping grammar conventions consistent across our pages or improving phrasings, but there is one "breaking" thing with the bad rendering of "Quantum Machine Learning" (which I'm surprised wasn't noticed by anyone else)

2020-09-29 20:05 UTC, co9olguy requested changes

2020-09-29 20:05 UTC, co9olguy commented on demos_submission.rst
> +   :property="og:description": Take a deeper dive into quantum machine learning by exploring cutting-edge algorithms using PennyLane and near-term quantum hardware.
Please use a separate description for each page

2020-09-29 20:28 UTC, thisac commented on demos_research.rst
> +You can find research that targets quantum machine learning in the `Quantum machine learning`_ section,
Oh, my bad. Just updated the heading based on a last minute code review (it wasn't there before). Forgot to lengthen the underline.

2020-09-29 20:30 UTC, thisac commented on demonstrations.rst
>  =========
```suggestion
Demos
=====
```

2020-09-29 20:33 UTC, glassnotes commented
I found another bug related to window resizing - at certain widths, the cards are not the same height. 

![card-height-mismatch](https://user-images.githubusercontent.com/2068515/94612638-612f9380-0271-11eb-8fbf-f910ab8b8b6e.gif)

2020-09-29 20:50 UTC, thisac commented on demonstrations.rst
> +                            <p class="card-text">Calculate the ground-state energy of the hydrogen molecule by sampling from terms in the VQE Hamiltonian, getting the doubly stochastic gradient desce
I removed the "getting the doubly stochastic gradient descent"; I agree that it doesn't make sense. I think it looks fine just keeping the first part though (without adding anything else to the descriptions). @co9olguy @josh146

2020-09-29 20:56 UTC, thisac commented on demos_basics.rst
> +   :property="og:description": Take a deeper dive into quantum machine learning by exploring cutting-edge algorithms using PennyLane and near-term quantum hardware.
Thanks @co9olguy. Would it be fine having the same text on the cards linking to a specific page and the page itself, or should they all be different? Not sure exactly where/how these texts would show up. E.g. having "Begin your journey into quantum machine learning using PennyLane." both on the "Basics" card text and the meta description in `demos_basics.rst`?

2020-09-29 22:03 UTC, co9olguy commented on demonstrations.rst
> +                            <p class="card-text">Calculate the ground-state energy of the hydrogen molecule by sampling from terms in the VQE Hamiltonian, getting the doubly stochastic gradient desce
yup, I was thinking of suggesting that

2020-09-29 22:05 UTC, co9olguy commented on demos_basics.rst
> +   :property="og:description": Take a deeper dive into quantum machine learning by exploring cutting-edge algorithms using PennyLane and near-term quantum hardware.
If you think that those descriptions would make sense when seen by themselves in search engine results (i.e., without the other cards for context), then yes. 

I like to imagine what I would want to see if I searched for a particular thing in a search engine and this result came up. What would make me want to click on it over all other results?

2020-09-29 22:08 UTC, thisac commented on demos_basics.rst
> +   :property="og:description": Take a deeper dive into quantum machine learning by exploring cutting-edge algorithms using PennyLane and near-term quantum hardware.
> I like to imagine what I would want to see if I searched for a particular thing in a search engine and this result came up. What would make me want to click on it over all other results?

Makes sense. Thanks! :slightly_smiling_face:

2020-09-29 23:12 UTC, thisac commented
Thanks @co9olguy for the review. I've gone through your comments and updated the things you mentioned. It would be great if you can proof-read the new meta-descriptions at the top of each demo-subpage. Let me know if they sound alright or if there's anything else that you find that needs to be updated.

@glassnotes Thanks for discovering this bug as well. I'm not sure how to solve it right now, but I could look into it if needed. I think this is an issue with most cards on the website though and maybe best left till later?

2020-09-30 01:03 UTC, co9olguy commented on demos_community.rst
> +   :property="og:description": Discover PennyLane demonstrations created by other users; showcasing quantum machine learning and other research.
```suggestion
   :property="og:description": PennyLane demonstrations created by the community showcasing quantum machine learning and other research.
```

2020-09-30 01:05 UTC, co9olguy commented on demos_research.rst
> +   :property="og:description": Implement papers that investigate the training of quantum circuits and explore cutting-edge research in quantum machine learning using PennyLane.
```suggestion
   :property="og:description": Implementations of the latest cutting-edge ideas and research from quantum machine learning using PennyLane.
```

2020-09-30 01:07 UTC, co9olguy approved these changes

2020-09-30 06:53 UTC, merged