[WIP] Expand glossary
PennyLaneAI/qml pull request #135
Opened 2020-09-16 21:08 UTC by glassnotes

**Title:**
Expansion of 'key concepts' glossary.

**Summary:** 
Glossary has been expanded to include additional terminology and a list of various QML algorithms.

**Relevant references:** 
Contained within linked files; collection still ongoing.

**Possible Drawbacks:**
The list got quite long - it might be better to separate things into terminology entries, and an algorithm zoo. I'd also like to add links to the tutorials for a number of the algorithms, as they provide tons of information and it's maybe not necessary to write up new explanations.

**Related GitHub Issues:** 
#54

2020-09-17 12:04 UTC, josh146 reviewed
These new pages look awesome 💯

2020-09-17 12:04 UTC, josh146 commented on glossary.rst
> +=======================
Sphinx can be a bit nitpicky, and will raise a warning if the title underline length does not match the title length!
```suggestion
QML glossary
============
```

2020-09-17 12:04 UTC, josh146 commented on glossary.rst
> +        Points at which the gradient of a parameterized circuit disappear. The mortal enemy of many a variational algorithm.
😆 I love this

2020-09-17 12:04 UTC, josh146 commented on glossary.rst
> +        A variational framework that can be used to teach quantum neural networks to perform both linear and nonlienar function approximation and classification tasks.
```suggestion
        A variational framework that can be used to teach quantum neural networks to perform both linear and nonlinear function approximation and classification tasks.
```

2020-09-17 12:04 UTC, josh146 commented on glossary/barren_plateaus.rst
> +--------------
This would be a great page to have. There are a lot of quality papers coming out of Los Alamos by Coles et al. exploring barren plateaus/

2020-09-17 12:04 UTC, josh146 commented on xanadu_theme/static/xanadu.css_t
> +}
I had a skim above, but couldn't see where this was being used?

2020-09-17 12:10 UTC, glassnotes commented on xanadu_theme/static/xanadu.css_t
> +}
Ah yes I haven't yet committed the file that uses it. But basically it will draw a nice green box around examples, similar to what the "note" and "see also" directives do.

2020-09-17 15:09 UTC, trbromley reviewed
Thanks @glassnotes, looks like a good improvement!

> The list got quite long - it might be better to separate things into terminology entries, and an algorithm zoo

I also was thinking similarly, potentially with the algo zoo being split into short and long term algos

2020-09-17 15:09 UTC, trbromley commented on glossary.rst
> +        A generalization of the :abbr:`VQE (Variational Quantum Eigensolver)` to systems with non-zero temperatures. Uses :abbr:`QHBMs (Quantum Hamiltonian-Based Models)` to generate thermal states o
I like the abbreviations

2020-09-17 15:14 UTC, glassnotes commented on glossary.rst
> +        A variational framework that can be used to teach quantum neural networks to perform both linear and nonlinear function approximation and classification tasks.
I'm also not 100% sure of the delineation. This may be one where we keep the term there in case someone looks it up, but then put "see quantum neural network".

2020-09-17 15:24 UTC, glassnotes commented
> Thanks @glassnotes, looks like a good improvement!
> 
> > The list got quite long - it might be better to separate things into terminology entries, and an algorithm zoo
> 
> I also was thinking similarly, potentially with the algo zoo being split into short and long term algos

One thing that might be cool is if we could tag the entries like "algorithm", "short term", "long term", and then have options to filter the glossary by tags. Not sure how feasible it would be to set up something like this within the page design.

2020-09-17 17:16 UTC, amirebrahimi commented on glossary.rst
> +        Points at which the gradient of a parameterized circuit disappear. The mortal enemy of many a variational algorithm.
Perhaps mention variance?
Points at which the gradient of a parameterized circuit disappear (i.e. variance close to zero)

2020-09-17 17:30 UTC, co9olguy commented on glossary.rst
> +        Points at which the gradient of a parameterized circuit disappear. The mortal enemy of many a variational algorithm.
Good point @amirebrahimi! 

Definitely, a barren plateau is not just where the gradient is zero at a point, but doesn't change anywhere around that point (indeed, the gradient is also zero at minima)

2020-09-17 18:35 UTC, glassnotes commented on glossary.rst
> +        Points at which the gradient of a parameterized circuit disappear. The mortal enemy of many a variational algorithm.
Thanks, I incorporated this in the updated version!

2020-09-18 12:45 UTC, mariaschuld commented on glossary.rst
> +        Points at which the gradient of a parameterized circuit disappear. The mortal enemy of many a variational algorithm, the variance of the gradient at these points is also close to 0.
Just to be more precise with regards to "plateau"... :)

```suggestion
        Areas in the cost landscape at which the gradient of a parameterized circuit disappear. The mortal enemy of many a variational algorithm, the variance of the gradient at these points is also close to 0. 
```

2020-09-18 12:46 UTC, mariaschuld commented on glossary.rst
> +        A hybrid variational algorithm that is used to find approximate solutions for combinatorial optimization problems. Characterized by a circuit ansatz featuring two alternating, parameterized c
Nice!

2020-09-18 12:46 UTC, mariaschuld commented on glossary.rst
> +    Quantum Boltzmann Machine
Nice!

2020-09-18 12:46 UTC, mariaschuld commented on glossary.rst
> +        Refers to the paradigm of using a quantum computer to perform machine learning tasks that, like classical deep learning, may require multiple layers of abstraction to learn.
Lol, I was never too sure what that term meant :P

2020-09-18 12:48 UTC, mariaschuld commented on glossary.rst
> +    /glossary/barren_plateaus
Wait, are you planning to write all of those pages?

2020-09-18 13:25 UTC, glassnotes commented on glossary.rst
> +    /glossary/barren_plateaus
I was thinking about it for some of them, but for the foreseeable future things will link to tutorials where applicable :)

2020-10-13 07:47 UTC, josh146 commented
Hey @glassnotes, just double checking the status of this PR. Is it still WIP? If it is, is it worth getting final reviews and merging it in, if it is a net improvement to the existing glossary?

2020-10-13 12:01 UTC, glassnotes commented
@josh146 I'm planning to write up info pages for the terms that don't currently link to tutorials, but if everyone is happy with the list, I think we should merge it in so that the number of new pages becomes well-defined :+1: @mariaschuld @co9olguy what do you think?

2020-10-13 13:11 UTC, mariaschuld commented
Looks good to me!

2020-10-13 13:19 UTC, glassnotes commented
Oh, one other immediate question is if we should go with "Key concepts" or "QML glossary" as is currently written. I think "Key concepts" would be better for now so it matches the graphic, but it's something we can change later.

2020-10-13 21:43 UTC, co9olguy commented
I'm definitely in favour of "Key concepts", not really a big fan of "glossary" :smiley:

2020-10-13 22:02 UTC, co9olguy requested changes
Thanks @glassnotes for these nice additions!

I left a few comments & suggestions below, but my main suggestion would be to still keep the number of terms from becoming too big. I'd recommend focusing on the key ones that people are likely to search for, and omit (for now) the more obscure ones.

Recommendations for ones we could omit:

- Quantum Deep Learning
- Quantum Graph NN
- Quantum Hamiltonian-based model
- Quantum Perceptron
- Quantum VAE

2020-10-13 22:09 UTC, glassnotes commented on glossary.rst
> +        A type of generative, energy-based quantum neural network characterized by its use of a parametererized Hamiltonian.
Yep, it's related to the VQT: https://arxiv.org/abs/1910.02071

2020-10-13 22:10 UTC, glassnotes commented
@co9olguy thanks so much for the review! I agree with the suggestions for the ones to cut; I will take those ones out when merging in #144 .

2020-10-13 22:16 UTC, glassnotes commented on glossary.rst
> +        *quanvolutional* neural networks.
That's a good point - let me look into that.

2020-10-14 04:01 UTC, josh146 commented on glossary.rst
> +    </script>
Another downside is the duplication - it can be easy to update the rendered text below, and forget to update the structured data :(

But I've never been able to think of a good solution to this. In the pennylane.ai repo we use Jinja templating to automate the 'copying' of the structured data, but it is a middling solution, and likely harder to get to work here due to Sphinx.

It would be nice if there was a `sphinx-structured-data` extension 😆

2020-10-14 17:12 UTC, glassnotes commented on glossary.rst
> +        *quanvolutional* neural networks.
I looked into this and there is actually quite an interesting distinction. 

So quantum convolutional neural networks are quantum circuits that are a direct analogy of CNNs. They look something like this (fig 1 of [this paper](https://arxiv.org/abs/1810.03787):

![image](https://user-images.githubusercontent.com/2068515/96021860-00ca5580-0e1e-11eb-933f-c2ab0c67f1aa.png)
 
On the other hand, quanvolutional neural networks are an augmented version of CNNs that incorporate a quantum layer (or *quanvolutional* layer). They look like this (fig 1 of [this other paper](https://arxiv.org/abs/1904.04767)):

![image](https://user-images.githubusercontent.com/2068515/96021950-29524f80-0e1e-11eb-86d0-12537044aec0.png)

I think it might be a good idea to add *both* terms as entries in the glossary so that this is made clearer for people learning about it. Also, the tutorial on our page is a quanvolutional network, so we should link to it from the proper term.

2020-10-14 17:19 UTC, glassnotes commented on glossary.rst
> +    </script>
Yeah agreed. We *could* write a script to automate the creation of `glossary.rst` based on a dictionary of term/definition or question/answer pairs. But I'm thinking that might be too much overhead, once everything here is set up there will not be much maintenance except for occasionally adding new entries.

2020-10-15 18:31 UTC, co9olguy approved these changes

2020-10-15 18:31 UTC, co9olguy commented on glossary.rst
> +        A hybrid variational algorithm that is used to find approximate solutions for combinatorial optimization problems. Characterized by a circuit ansatz featuring two alternating, parameterized c
```suggestion
        A hybrid variational algorithm that is used to find approximate solutions for combinatorial optimization problems. Characterized by a circuit ansatz featuring two alternating parameterized components. 
```

2020-10-15 18:31 UTC, co9olguy commented on glossary.rst
> +                    optimization problems. It's characterized by a circuit ansatz featuring two alternating, parameterized components."
```suggestion
                    optimization problems. It's characterized by a circuit ansatz featuring two alternating parameterized components."
```

2020-10-15 18:31 UTC, co9olguy commented on glossary.rst
> +                "name" : "What is the parameter shift rule?",
```suggestion
                "name" : "What is the parameter-shift rule?",
```

2020-10-15 20:09 UTC, merged

2020-10-16 06:49 UTC, mariaschuld commented on glossary.rst
> +        *quanvolutional* neural networks.
Sounds good. By the way, I'd be a bit careful about taking names so serious. From experience, they shift a lot, and one paper may still use it very different to another. In some sense I would make clear that these are expressions used in particular papers. 

I am sure the will be 100 more quantum convolutional neural nets to come, for example :) And they may have any architecture, maybe even the quanvolutional one.