qsim supremacy demo
PennyLaneAI/qml pull request #160
Opened 2020-11-13 23:35 UTC by thisac

**Title:**
qsim supremacy demo

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2020-11-20 05:54 UTC, josh146 commented
Thanks @thisac!

Could you modify `requirements.txt` to include `qsimcirq` when you get the chance? Hopefully it will then build 🤞

2020-11-23 10:03 UTC, josh146 commented on demonstrations/qsim_supremacy.py
> +samples = dev.generate_samples()
I have to admit, I'm not so keen on using a `QubitDevice` method directly in the tutorial 🤔 I know you were looking into this before, but is there no way to use `return qml.sample(..)`? Or do we need to allow `return qml.sample()` to sample from the computational basis in PennyLane?

2020-11-23 10:05 UTC, josh146 commented on demonstrations/qsim_supremacy.py
> +#    Circuit's distribution:    1.0016549
How come the fidelity is above 1 here? I would have expected it to _approach_ 1, but be bound <= 1 🤔

2020-11-23 10:05 UTC, josh146 commented on demonstrations/qsim_supremacy.py
> +#     Theoretical:               0.9995118
I'm also a bit surprised that the theoretical fidelity is < the sampled fidelity!

2020-11-23 10:33 UTC, josh146 commented on demonstrations/qsim_supremacy.py
> +# this experiment is able to show quantum supremacy.
A nice way to finish off the demo :)

2020-11-23 10:34 UTC, josh146 commented on demonstrations/qsim_supremacy.py
> +# deeper into the maths and physics of the experiment. The blogpost in [5],
```suggestion
# deeper into the maths and physics of the experiment. The blog post in [5],
```

2020-11-23 10:35 UTC, josh146 commented on demonstrations/qsim_supremacy.py
> +# including the effects of added noise models.
```suggestion
# along with the accompanying GitHub repo, also provides a nice introduction
# to the cross-entropy benchmark fidelity, and includes calculations
# highlighting the effects of added noise models.
```
(to avoid the repeat of 'along')

2020-11-23 10:36 UTC, josh146 commented on demos_research.rst
> +    :tags: cirq qsim
For some reason, this thumbnail does not render. Perhaps because the thumbnail image has not been committed?

2020-11-23 23:13 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +shots = 500000
:100:

2020-11-24 01:15 UTC, co9olguy requested changes
Thanks for taking a deep dive into this demo @thisac! It's not a straightforward one to do! :tada: 

I agree with Josh that some images would help bring the reader along. My other major recommendation would be to bring some more of the motivations for the quantum supremacy experiment up front before diving deeply into the code implementation. 

As a minor suggestion, I'd recommend trying to be a bit less verbose in the text, just to make things easier on the reader. A good test is to see if you can look at a sentence and remove words from it without any sacrifice to the clarity.

2020-11-24 01:15 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# circuit, and the average is over the observed bitstrings.
It read a bit weird to have the index `i` appearing in the RHS in a quantity that does not depend on the index. Are you going for an implicit Einstein summation with the two `i`s used this way? :thinking:

2020-11-24 01:15 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# The values above might seem a bit arbitrary. To show that the fidelity
Why are they arbitrary? You've just gone to some length to explain and motivate them :thinking:

2020-11-24 01:15 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# .. rst-class:: sphx-glr-script-out
Maybe I missed something, but why are the outputs hand-coded as mock code cells? Is it because we won't be running this demo in CI?

2020-11-24 01:15 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +#    as the number of circuit evaluations below. Running the following code
The second sentence here could use another round of polish, read somewhat awkwardly

2020-11-24 01:15 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +    print(f"\r{i + 1:4d} / {num_of_evaluations:4d}{' ':17}{np.mean(f_circuit):.7f}", end="")
Line length causing horizontal scrollbars

2020-11-24 01:15 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# this experiment is able to show quantum supremacy.
I agree, but it might be useful to have some of this up front as well, to make sure readers are interested enough to read through the entire demo

2020-11-24 01:15 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# effectively get a value close to 1 by any classical sampling methods.
```suggestion
# It should be effectively impossible to get a value close to 1 for this
# fidelity by any classical sampling methods.
```

2020-11-24 01:15 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# for a future demonstration: the addition of noise in quantum hardware.
let's not make any promises :stuck_out_tongue_winking_eye:

2020-11-24 01:15 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# Simply put, this noise will lower the cross-entropy benchmark fidelity
```suggestion
# Simply put, this noise will lower the cross-entropy benchmark fidelity,
```

2020-11-24 01:15 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# tractable sampling from probability distributions. The larger the
What does it mean "classically tractable sampling" here? I didn't understand :thinking:

2020-11-24 01:15 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# fidelity will be. By calculating the specific single-qubit, two-qubit and
```suggestion
# fidelity will be. By calculating the specific single-qubit, two-qubit, and
```

2020-11-24 01:15 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# circuit as they do with the Sycamore chip (see Fig. 4 in `[1]
run-on sentence; recommend splitting up or rephrasing

2020-11-24 01:15 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# For more reading on this, the original Nature paper [1] is highly
```suggestion
# For more reading on this, the original paper [1] is highly
```

2020-11-24 01:15 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# deeper into the maths and physics of the experiment. The blogpost in [5],
```suggestion
# recommended (along with the suplementary information if you want to dive
# deeper into the math and physics of the experiment). The blog post in [5],
```

2020-11-24 01:15 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +#
```suggestion
#

```

2020-11-24 06:39 UTC, josh146 commented on demonstrations/qsim_supremacy.py
> +# Here comes one of the tricky parts. The way the paper decides which
Makes the paper sound sentient!

2020-11-24 23:57 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +pattern. This is basically a way of building a random unitary that is also
Yes, they have a very nice figure, but I was a bit unsure if we can use images directly from the paper (not sure if this is something we've done for other demos). Would you say that this is alright?

2020-11-25 00:00 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +explained as a suffient measure of quantum supremacy. [1]
This is much better. I just added these references early, without thinking twice about how references should be implemented. :smile: Thanks!

2020-11-25 00:03 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +    cirq.GridQubit(3, 3),
This is just taken from their own code (they used these qubits). I don't know exactly why, but I could probably change it to 0 to 3 instead. It makes more sense.

2020-11-25 00:11 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +qb2wire = {i: j for i, j in zip(qubits, range(wires))}
It doesn't seem to work to pass a `cirq.qubit` as a wire for a gate (should it?), so that is why this `qb2wire` is defined. E.g. when I later apply `ops.ISWAP(wires=(qb_1, qb_2))`, `qb_1` and `qb_2` must be the indices of the the qubits (and not the `cirq.GridQubit`s themselves).

2020-11-25 00:16 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +# with the ``wires`` and ``qubits`` keywords that we defined above. qsim is
I'm not sure. Both the paper and the GitHub repo uses "qsim" (and not `qsim`). Once in the paper it's referred to as "Qsim" (at the start of a sentence). qsim isn't really used in code at all though, since the module were using is called `qsimcirq`. What do you think is best? I'm happy with whichever. :slightly_smiling_face:

2020-11-25 00:16 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +# be. We will use 500.000 shots; the same number of samples that are used
Very true!

2020-11-25 00:18 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +sqrtXgate = lambda wires: qml.RX(np.pi / 2, wires=wires)
Oh, I completely missed that. Nice!

2020-11-25 00:20 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +# if you wish.
Thanks, I think that's good. Sometimes I have a tendency to over-complicate my sentences.

2020-11-25 00:23 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +# Each circuit-loop consists of alternating layers of single-qubit gates
Bad wording on my side. It's just each gate sequence step. "A" corresponds to one "circuit-loop" with random single-qubit gates applied on all wires and two-qubit gates on all wires connected by "A". It's the "main" loop in the circuit.

2020-11-25 00:34 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +# without needing to add it as a return statement in the circuit.
Yes, I can update this. I just thought it looked fairly nice this way. It also avoids having to update, and explain, the sample values: -1 to 1 and 1 to 0. Would you say it's OK to simply return samples, and then use `dev.probability` to get the probabilities instead (I still need them for the fidelity calculations), or is it nicer if I have an if-statement in the circuit, like this:

```python
if return_probs:
    return qml.probs(wires=range(wires))
else:
    return [qml.sample(qml.PauliZ(w)) for w in range(wires)]
```

2020-11-25 00:35 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +            np.random.choice(single_qubit_gates)(wires=w)
I almost forgot about this. I should attempt to fix it. The same single-qubit gate should never be applied to the same wire twice in a row (with potential two-qubit gates in-between). That's possible as it's currently implemented.

2020-11-25 00:37 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +    return qml.probs(wires=range(wires))
We're interested in both. We need to sample from the circuit and then use the sampled bitstrings ideal probability (calculated from `qml.probs`) to calculate the fidelity. Either way we need to get one from the circuit output and one from `dev`, or both from the circuit.

2020-11-25 00:41 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +seed=np.random.randint(0, 42424242)
The range is completely cherry-picked by me (although the seed will be fairly random). Is there a nice way of getting a random seed or do I have to randomize an integer, like I'm doing here? :thinking:

2020-11-25 00:44 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +samples = dev.generate_samples()
As I also mentioned in a comment to Nathan above, this could easily be done, but I would have to change -1 to 1 and 1 to 0 for all samples, and either way I would need to get the probabilities later, either via an if statement in the circuit or by using `dev.probabilities`. I guess the later wouldn't really solve your issue, so maybe the former is the best way to go.

2020-11-25 00:47 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +# .. rst-class:: sphx-glr-script-out
`qsimcirq` didn't want to get installed via the CI (not sure why, but it was complaining about not having `cmake` installed, and when I installed it it complained some more, so I gave up and hard-coded the output). The script, as it is now, takes some time to finish, although it would be easy to lower the number of runs and/or samples to get it done quicker.

2020-11-25 00:53 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +#    Circuit's distribution:    1.0016549
That's shouldn't actually be too surprising, since this cross-entropy benchmarking fidelity isn't strictly bound between 0 and 1 unless using an infinite amount of shots/trials. 

For examples, following the definition F = 2^n * <P(x)> - 1, where <P(x)> is the mean of the simulated probabilities of the measured bitstrings, if we measure only one bitstring with P(x) = 0.0005, then F = 2^12 * 0.0005 - 1 = 1.048 > 1 for 12 qubits. Same goes for the negative values.

2020-11-25 00:55 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +#     Theoretical:               0.9995118
Same reasoning as above, that's why I added the next part, which (when run) shows clearly how the fidelity gets closer to the theoretical value the more runs there are.

2020-11-25 00:58 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +# The values above might seem a bit arbitrary. To show that the fidelity
Oh, maybe arbitrary is the wrong word to use here. I mean that they aren't particularly close to the theoretical values, and they are, as you both noted, both >1 and <0. :smile: The code snippet below shows that the calculated fidelity actually gets closer to the theoretical value the more times it's run.

2020-11-25 01:02 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +# tractable sampling from probability distributions. The larger the
I just mean that sampling _effectively_ from any distribution classically (e.g. without using a quantum circuit) would always produce a value close to zero. Although, I might need to reword this a bit, since Haoyu commented that this might not always be the case.

2020-11-25 01:03 UTC, thisac commented on demos_research.rst
> +    :tags: cirq qsim
There is no image yet. I still need to create one. :pensive:

2020-11-25 07:09 UTC, josh146 commented on demonstrations/qsim_supremacy.py
> +# without needing to add it as a return statement in the circuit.
The if statement approach is my preference 👍

2020-11-25 07:12 UTC, josh146 commented on demonstrations/qsim_supremacy.py
> +# .. rst-class:: sphx-glr-script-out
Yep - no binary wheel is provided by `qsimcirq`, so when you pip install it it will be compiled from source.

Which requires setting up CircleCI to install all the C++ toolchain required for compilation, which is non-trivial. I suggested best to handcode the demo output for now so that we are not blocked. We can always look back into installing `qsimcirq` on Circle later if we have time.

2020-11-25 07:12 UTC, josh146 commented on demonstrations/qsim_supremacy.py
> +#    Circuit's distribution:    1.0016549
Ah! Got it.

2020-11-25 17:54 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +qb2wire = {i: j for i, j in zip(qubits, range(wires))}
Yes, IIRC you can't pass the qubits directly, you need to pass their index. In this case, since the qubits are already `sorted`, then you can get away with `range(wires)` as your index set.

After thinking about it, I think you've got the nicest approach here. Otherwise, you'd have to manually remember which qubit was, e.g., the fifth in the `sorted` list, e.g., wire `5`

2020-11-25 17:56 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +samples = dev.generate_samples()
Doesn't sound too hard?
```
samples = [0, 1, 1, 0 ..., 0]
ints = np.array(samples) * 2 - 1
```

2020-11-25 17:57 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +pattern. This is basically a way of building a random unitary that is also
I think it's ok if you give attribution

2020-11-25 17:59 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# with the ``wires`` and ``qubits`` keywords that we defined above. qsim is
I like `qsim`

2020-11-25 18:01 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# with the ``wires`` and ``qubits`` keywords that we defined above. qsim is
Honestly it feels weird to refer to a proper noun/name without a capital. Putting it in a "code" format gives us a plausible reason for keeping lowercase

2020-11-25 18:03 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +seed=np.random.randint(0, 42424242)
You mean you want a random seed that changes every time?

2020-11-27 19:16 UTC, co9olguy requested changes
Thanks @thisac! Amazing work.

I've left a number of suggestions, but they are all in the spirit of polishing, clarifying, or simplifying as much as we can.

2020-11-27 19:16 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# The performance metric that is used in the paper, and the one that we
```suggestion
# The performance metric that is used in the supremacy experiment, and the one that we
```

2020-11-27 19:16 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# above, and close to zero for a normal probability distribution, that can
Unless you specifically mean a "Normal distribution", I think it's best to avoid the word "normal" here

2020-11-27 19:16 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# in the circuit. Sampling a bitstring from a random quantum circuit would
```suggestion
# be effectively sampled from classically. 
# Sampling a bitstring from a random quantum circuit would
```

2020-11-27 19:16 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# sampling probabilities for the same noise-less circuit.
```suggestion
# sampling probabilities for the same noiseless circuit.
```

2020-11-27 19:16 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +samples = circuit(seed=seed).T
How come we need to transpose? :thinking: Just so we can iterate over axis 0 in the `for` loop below?

2020-11-27 19:16 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +    new_sam = -(sam - 1) // 2
Instead of explaining the math in the comment, I think we can just give more clear names, and the reader should be able to follow along.
e.g., `samples`->`circuit_samples` or `pauliZ_samples`
and `new_sam` = `bittring_sample`

2020-11-27 19:16 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# Similarly, we can sample random bitstrings from a normal distribution by
Again, do you really mean *the* Normal distribution here? :thinking:. What does a normal distribution over bitstrings mean?

2020-11-27 19:16 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# Finally, let us print the two different values. Sampling from the
```suggestion
# Finally, let's compare the two different values. Sampling from the
```

2020-11-27 19:16 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +#     Theoretical:               0.9995118
It was a bit weird to have only the theoretical value printed here, but not the sampling value. Later the theoretical value is printed again, so I'd recommend just merging this block with the next one, and dropping one of the `print`s

2020-11-27 19:16 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# In the supremacy paper, they typically calculate each of their
```suggestion
# In the supremacy experiment, they typically calculate each of their
```
Just felt that the demo refers too much to the paper itself, as if it is the primary agent, not the overall supremacy undertaking

2020-11-27 19:16 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# has done.
```suggestion
# supremacy can be claimed. This is exactly what Google's supremacy experiment
# has done.
```

2020-11-27 19:16 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# of the Sycamore chip, using them to simulate a noisy circuit, the Google
```suggestion
# of the Sycamore chip, and using them to simulate a noisy circuit, the Google
```

2020-11-27 20:41 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +# neighbouring qubits with the key as their connection label. We will use
My bad. Should have said:

The logic below iterates through all connections and returns a dictionary
``gate_order`` with lists of tuples as **values**. Each tuple contains two
neighbouring qubits with the key as their connection label.

I'll rewrite this.

2020-11-27 20:44 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +# the states :math:`\left|0\right>` and :math:`\left|1\right>`.
It didn't render properly due to a missing space after the first math part earlier for me, though I think it's working now.

2020-11-27 20:50 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +# above, and close to zero for a normal probability distribution, that can
I specifically meant a "Normal distribution", although when thinking about it, it should be "uniform distribution". I'll update this. Thanks for spotting it!

2020-11-27 20:57 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +samples = circuit(seed=seed).T
Yes. I think it makes more sense to have the samples with shape `(shots, modes)` although, due to the list comprehension loop to return the samples, they are actually returned with shape `(modes, shots)`.

2020-11-27 20:58 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +# Similarly, we can sample random bitstrings from a normal distribution by
I'll clarify.

2020-11-27 20:58 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +# In the supremacy paper, they typically calculate each of their
I think you're right here! :+1:

2020-11-27 22:37 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +seed=np.random.randint(0, 42424242)
I think it's a valid way of choosing a seed for the demonstration, but it would be equally fine to set a specific seed here as well. In the second place that this is done, the seed needs to be different each time, so there it is needed (unless I use a set of predefined, different seeds, but I think setting a random one makes more sense). The important thing is that we use the same seed to calculate both the probabilities and the samples for each run (so that the circuits are identical).

2020-11-28 19:07 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# results, as well raw samples. To facilitate this, we add a keyword
```suggestion
# results, as well as raw samples. To facilitate this, we add a keyword
```

2020-11-28 19:08 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# From the QNode, we also need both the probabilities of the measurement
```suggestion
# From the QNode, we need both the probabilities of the measurement
```

2020-11-28 19:09 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +# above, and close to zero for a uniform probability distribution, that can
```suggestion
# above, and close to zero for a uniform probability distribution, which can
```

2020-11-28 19:14 UTC, co9olguy approved these changes

2020-11-29 03:45 UTC, co9olguy commented on demos_research.rst
> +.. customgalleryitem::
:thinking: We're due for a new subsection of the website, covering general quantum computing (quantum volume I think can go in there too)

2020-11-30 09:53 UTC, josh146 reviewed
Looking great @thisac! Huge improvements across the board.

2020-11-30 09:53 UTC, josh146 commented on demonstrations/qsim_supremacy.py
> +#     **Image taken from Arute, F., Arya, K., Babbush, R. et al.** [#Arute2019]_
![g18](https://user-images.githubusercontent.com/2959003/100589975-bdc13480-332e-11eb-8459-95fb6bcd22a9.png)

Had a go re-doing this one (and tried to remove some of the overlap), feel free to use it if you would like :)

2020-11-30 09:53 UTC, josh146 commented on demonstrations/qsim_supremacy.py
> +gate_sequence = np.resize(["A", "B", "C", "D"], m)
It might look slighter nice to leave both uncommented, e.g.,
```suggestion
gate_sequence_longer = np.resize(["A", "B", "C", "D", "C", "D", "A", "B"], m)
gate_sequence = np.resize(["A", "B", "C", "D"], m)
```

2020-11-30 09:53 UTC, josh146 commented on demonstrations/qsim_supremacy.py
> +gate_sequence = np.resize(["A", "B", "C", "D"], m)
(even though `gate_sequence_longer` isn't used)

2020-11-30 09:53 UTC, josh146 commented on demonstrations/qsim_supremacy.py
> +# specifies the order in which the single-qubit
```suggestion
# twice in a row. We do this by creating a helper function ``generate_single_qubit_gate_list()`` that
# specifies the order in which the single-qubit
```

2020-11-30 09:53 UTC, josh146 commented on demonstrations/qsim_supremacy.py
> +    # from `single_qubit_gates`
```suggestion
    # from single_qubit_gates
```

2020-11-30 09:53 UTC, josh146 commented on demonstrations/qsim_supremacy.py
> +        return [qml.sample(qml.PauliZ(i)) for i in range(wires)]
I like this!

2020-11-30 09:53 UTC, josh146 commented on demonstrations/qsim_supremacy.py
> +        return [qml.sample(qml.PauliZ(i)) for i in range(wires)]
Do we want to make it PEP8 compliant, e.g.,
```suggestion
    if return_probs:
        return qml.probs(wires=range(wires))

    return [qml.sample(qml.PauliZ(i)) for i in range(wires)]
```

I'm in two minds, because an explicit if-else makes it easier for readers to follow.

2020-11-30 09:53 UTC, josh146 commented on demonstrations/qsim_supremacy.py
> +# possible bitstrings. We can then sample from the same circuit, transform
Maybe worth restructuring this to avoid both sentences beginning with "We"?

2020-11-30 09:53 UTC, josh146 commented on demonstrations/qsim_supremacy.py
> +    bitstring_samples.append("".join(str(bs) for bs in bitstring_sample))
Perhaps worth explaining more explicitly why this is needed, for those unsure (e.g., sampling Z returns -1, 1, but we need computational basis samples)

2020-11-30 09:53 UTC, josh146 commented on demonstrations/qsim_supremacy.py
> +#     lie in the 0-to-1 interval.
Nice!

2020-11-30 09:53 UTC, josh146 commented on demonstrations/qsim_supremacy.py
> +print("Uniform distribution:", f"{f_uniform:.7f}".rjust(14))
I like the alignment of the digits 😆

2020-11-30 09:53 UTC, josh146 commented on demonstrations/qsim_supremacy.py
> +# circuit, the more noise there will be, and thus the lower the fidelity.
```suggestion
# noise in quantum hardware. Simply put, this noise will lower the
# cross-entropy benchmark fidelity---the larger the
# circuit, the more noise there will be, and thus the lower the fidelity, with the
# fidelity approaching 0 as the noise increases.
```

2020-11-30 09:53 UTC, josh146 commented on demonstrations/qsim_supremacy.py
> +#     includes calculations highlighting the effects of added noise models.
I find this a really strong conclusion 💪

2020-11-30 15:20 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +#     **Image taken from Arute, F., Arya, K., Babbush, R. et al.** [#Arute2019]_
@josh146 you're a legend

2020-11-30 15:20 UTC, co9olguy commented on demonstrations/qsim_supremacy.py
> +        return [qml.sample(qml.PauliZ(i)) for i in range(wires)]
I vote no. I actually find explicit `if/else` more readable

2020-11-30 16:48 UTC, josh146 commented on demonstrations/qsim_supremacy.py
> +        return [qml.sample(qml.PauliZ(i)) for i in range(wires)]
I think I agree

2020-11-30 16:53 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +world's most powerful supercomputers—using a classical statevector simulator called
Thanks @josh146. I thought so too, but I think it got changed to `-` during code-review, so I was a bit unsure (and just went with the suggestion). Is `---` preferred? :slightly_smiling_face:

2020-11-30 16:54 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +#     **Image taken from Arute, F., Arya, K., Babbush, R. et al.** [#Arute2019]_
This is awesome @josh146! Thanks a lot for drawing this. :tada:

2020-11-30 16:57 UTC, thisac commented on demonstrations/qsim_supremacy.py
> +        return [qml.sample(qml.PauliZ(i)) for i in range(wires)]
Thanks. I've started following this PEP8 suggestion recently (and I've actually started to like it), although I don't mind either way to be honest. I'll keep it like this then since there are 2 no and 1 abstain. :laughing:

2020-11-30 16:59 UTC, thisac commented on demos_research.rst
> +.. customgalleryitem::
I was thinking that as well. This demo didn't really fit into neither Optimization nor QML. :thinking:

2020-11-30 17:34 UTC, josh146 commented on demonstrations/qsim_supremacy.py
> +world's most powerful supercomputers—using a classical statevector simulator called
Oops. If that was me, it was accidental. I prefer `---`, but it is personal preference!

2020-12-01 02:26 UTC, josh146 approved these changes
🏆

2020-12-01 02:29 UTC, merged