Adds tutorial on using the SPSA optimizer
PennyLaneAI/qml pull request #195
Opened 2020-12-24 00:10 UTC by antalszava

2021-01-13 19:53 UTC, trbromley commented
[ch1031]

2021-02-24 01:29 UTC, antalszava commented on demonstrations/spsa.py
> +print("Expected device executions = {max_dev_execs}")
```suggestion
print(f"Expected device executions = {max_dev_execs}")
```

2021-03-19 01:05 UTC, antalszava commented on demonstrations/spsa.py
> +# Note: do not run the simulation on this device, as it will send it to a real hardware
```suggestion
# Note: you will need to be authenticated to IBMQ to run the following code.
# Do not run the simulation on this device, as it will send it to a real hardware
```

2021-03-19 21:05 UTC, glassnotes commented on demonstrations/spsa.py
> +# It seems that SPSA performs great and it does with a significant saving when
```suggestion
# It seems that SPSA performs great and it does so with a significant savings when
```

2021-03-19 21:05 UTC, glassnotes commented on demonstrations/spsa.py
> +# Let's take a deeper dive to see how much better it is actually.
```suggestion
# Let's take a deeper dive to see how much better it actually is.
```

2021-03-19 21:05 UTC, glassnotes commented on demonstrations/spsa.py
> +# total number of device executions
```suggestion
# all 15 terms. Factoring in the number of iteration steps (20), we estimate the
# total number of device executions as follows:
```

2021-03-19 21:05 UTC, glassnotes commented on demonstrations/spsa.py
> +# Our next step will be to run the same VQE simulation on our simulated version
```suggestion
# Our next step will be to run the same VQE simulation on a simulated version
```

2021-03-19 21:05 UTC, glassnotes commented on demonstrations/spsa.py
> +# to save significant time and resources. It can be a good alternative to
```suggestion
# to save time and resources. It can be a good alternative to
```

2021-03-19 21:05 UTC, glassnotes commented on demonstrations/spsa.py
> +# convergence rate of SPSA. [#spall_overview]_ The proposed technique can also
```suggestion
# convergence rate of SPSA [#spall_overview]_. The proposed technique can also
```

2021-03-19 21:05 UTC, glassnotes commented on demonstrations/spsa.py
> +#    `<https://www.jhuapl.edu/SPSA/PDF-SPSA/Spall_An_Overview.PDF>`__, 1998
```suggestion
#    James C. Spall, "`An Overview of the Simultaneous Perturbation Method
#    for Efficient Optimization <https://www.jhuapl.edu/SPSA/PDF-SPSA/Spall_An_Overview.PDF>`__", 1998
```

2021-03-19 21:12 UTC, antalszava commented on demonstrations/spsa.py
> +hence offer an alternative approach for computing the gradients of quantum circuits.
Thanks! Rephrased this sentence.

2021-03-22 17:50 UTC, josh146 reviewed
A really awesome tutorial @antalszava!

I left comments throughout, but I think writing an awesome introduction, and shortening the VQE section, would really help elevate the demo 🙂

2021-03-22 17:50 UTC, josh146 commented on demonstrations/spsa.py
> +   Image source: [#spall_overview]_
If you would like, I can contribute a hand drawn image for this one!

2021-03-22 17:50 UTC, josh146 commented on demonstrations/spsa.py
> +<https://pennylaneqiskit.readthedocs.io/en/latest/>`_ that samples quantum
How come you choose pl-qiskit here?

2021-03-22 17:50 UTC, josh146 commented on demonstrations/spsa.py
> +* a template: :func:`~.pennylane.templates.layers.StronglyEntanglingLayers`,
Maybe good to instead say 'circuit ansatz' here?

2021-03-22 17:50 UTC, josh146 commented on demonstrations/spsa.py
> +
I know that this is added by Black, but I find that the double line breaks are a bit wasted on rendered websites...

2021-03-22 17:50 UTC, josh146 commented on demonstrations/spsa.py
> +# this is done for compatibility.
```suggestion
# After this, we'll initialize the parameters in a way that is compatible with
# the ``noisyopt`` package. The ``noisyopt`` package requires the trainable parameters
# be a flattened array. As a result, our cost function must accept a flat array of parameters
# to be optimized.
```

2021-03-22 17:50 UTC, josh146 commented on demonstrations/spsa.py
> +from noisyopt import minimizeSPSA
It's definitely cool showing off using `noisyopt` with PL, but a part of me was slightly disappointed, as I thought you were going to show how to code up SPSA 😆 

I wonder if it is worth having a very basic SPSA implementation at the end of the "Simultaneous perturbation stochastic approximation (SPSA)" section, but then say 'now lets use ``noisyopt``...' in this section.

2021-03-22 17:50 UTC, josh146 commented on demonstrations/spsa.py
> +from noisyopt import minimizeSPSA
In fact, having a basic version of SPSA coded up in the previous section (even to optimize a basic classical function) would be very nice to help understand the SPSA math?

2021-03-22 17:50 UTC, josh146 commented on demonstrations/spsa.py
> +dev_sampler._num_executions = 0
Shouldn't this already be 0?

2021-03-22 17:50 UTC, josh146 commented on demonstrations/spsa.py
> +dev_sampler._num_executions = 0
I hesitate a bit having a private attribute being set

2021-03-22 17:50 UTC, josh146 commented on demonstrations/spsa.py
> +# evaluating the cost function, while the :math:`a` is analogous to a learning
```suggestion
# evaluating the cost function, while the :math:`a` coefficients are analogous to a learning
```

2021-03-22 17:50 UTC, josh146 commented on demonstrations/spsa.py
> +#     Iteration = 19, Cost = -0.996
It might be useful to add `Quantum evaluations:` to this list, since, at first though, I thought that GD was doing better! Since it converges to -0.996 after 19 iterations, but SPSA takes 200.

But then I remembered that 19 iterations for grad descent -> a _very_ large number of parameter shifts

2021-03-22 17:50 UTC, josh146 commented on demonstrations/spsa.py
> +# same; we'll simply swap out the device.
I worry it feels like this section (and the previous one) feels like a bit of a divergence --- it suddenly feels like a VQE demo, and the focus is no longer on SPSA. Is it possible to combine the two sections and reduce the explanations where it makes sense (instead linking to other demos), so that VQE + SPSA can be emphasized?

2021-03-23 02:22 UTC, antalszava commented on demonstrations/spsa.py
> +from noisyopt import minimizeSPSA
Sure, if it would help with putting the theory into context. The main aim of the demo was to show that SPSA can be useful, so using `noisyopt` was a convenient way to meet the optimizer and to offer an introduction to it. But if it brings value to have a custom implementation, then will swap it.

2021-03-23 02:24 UTC, antalszava commented on demonstrations/spsa.py
> +<https://pennylaneqiskit.readthedocs.io/en/latest/>`_ that samples quantum
We use noise models and we can simulate a real device later using PL-Qiskit.

2021-03-23 02:24 UTC, antalszava commented on demonstrations/spsa.py
> +   Image source: [#spall_overview]_
That would be awesome, thank you! 🙂

2021-03-23 02:26 UTC, antalszava commented on demonstrations/spsa.py
> +dev_sampler._num_executions = 0
We used `dev_sampler` for gradient descent too, so the number of executions was recorded. A clear way can be just to create a new device.

2021-03-23 02:29 UTC, antalszava commented
Thank you for the comments @josh146! :)

2021-03-23 07:38 UTC, josh146 commented on demonstrations/spsa.py
> +from noisyopt import minimizeSPSA
This is definitely a subjective opinion, but I definitely expected to see SPSA coded up based on the intro! It might be quite a bit of extra work, I'm curious what @glassnotes thinks?

2021-03-23 11:51 UTC, glassnotes commented on demonstrations/spsa.py
> +from noisyopt import minimizeSPSA
It would take some effort but it is not too challenging to implement (plus, it would save us a dependency where we had to do a bit of tweaking to get the parameter shapes to fit right, I can't remember the details). We can also add it afterwards to the selection of optimizers in PL. The biggest concern is just time, since we were wanting to get the demo out ASAP.

2021-03-23 20:24 UTC, antalszava commented on demonstrations/spsa.py
> +As previously mentioned, SPSA is robust to any noise that may occur
It was hinted at on line 48, will rephrase though to make it less ambiguous.

2021-03-23 21:58 UTC, antalszava commented on demos_research.rst
> +    :figure: demonstrations/spsa/spsa_thumbnail.png
Updated!

2021-03-23 21:58 UTC, antalszava commented on demonstrations/spsa.py
> +Fortunately, there are certain optimization techniques that offer an
Added an intro.

2021-03-23 22:27 UTC, agran2018 requested changes
Thanks @antalszava for the nice demo!. I have left few comments/suggestions. Happy to give it a second round when is ready.

2021-03-23 22:27 UTC, agran2018 commented on demonstrations/spsa.py
> +)
Here is another tutorial to update in terms of the new ``molecular_hamiltonian`` function :-)). Also, if we want to avoid deviating the attention of the user to the qchem specifics I would suggest to keep it as simple as possible. For example:
```python
h2_ham, num_qubits = qchem.molecular_hamiltonian(name, geometry) 
```
It can be done later when we update the tutorial.

2021-03-23 22:27 UTC, agran2018 commented on demonstrations/spsa.py
> +# local minimum around :math:`-0.47` Hartree that the gradient descent
This is tangential. This is the lowest excited state of H2 with S=1, S_z=0 :-)). See [HERE](https://pennylane.ai/qml/demos/tutorial_vqe_uccsd_obs.html)

2021-03-23 23:08 UTC, antalszava commented on demonstrations/spsa.py
> +# same; we'll simply swap out the device.
Some things can be cut down when loading H2, though the biggest gain would be omitting optimization with the ideal (non-noisy device). Optimization using that was already showcased in the VQE intro tutorial.

Just double-checking that that's something valuable to leave out, also tagging @glassnotes.

2021-03-24 04:55 UTC, josh146 commented on demonstrations/spsa.py
> +from noisyopt import minimizeSPSA
> The biggest concern is just time, since we were wanting to get the demo out ASAP.

yep not a big issue at all, happy to keep the demo as is :+1:

Perhaps it's just a matter of reframing the intro, which made me think 'this demo will show me how to code SPSA' instead of 'this demo will showcase how using SPSA can benefit optimization'

2021-03-24 04:56 UTC, josh146 commented on demonstrations/spsa.py
> +# same; we'll simply swap out the device.
> Optimization using that was already showcased in the VQE intro tutorial.

If that's the case, could we just link to that demo very prominently, and then go straight into the noisy optimization?

2021-03-24 05:16 UTC, josh146 commented on demonstrations/spsa.py
> +   Image source: [#spall_overview]_
![image](https://user-images.githubusercontent.com/2959003/112259369-24ce7480-8ca3-11eb-94e5-958743ce715a.png)

Gave it a shot, let me know if you want any changes!

2021-03-24 15:23 UTC, antalszava commented on demonstrations/spsa.py
> +<https://pennylane.ai/qml/glossary/parameter_shift.html>`_). For qubit
Thanks! Based on your suggestion, updating to:
>Computing quantum gradients involves evaluating the partial derivative of the
quantum function with respect to every free parameter. The partial derivatives
are used to apply the product rule to compute the gradient of the quantum
circuit.

2021-03-24 15:31 UTC, antalszava commented on demonstrations/spsa.py
> +linearly with the number of free parameters, i.e., :math:`O(p)` with :math:`p` being
Thanks rephrased this part.

2021-03-24 15:32 UTC, antalszava commented on demonstrations/spsa.py
> +alternative to computing the gradients of quantum circuits. One such technique
Not quite sure about this suggestion.

2021-03-24 15:38 UTC, antalszava commented on demonstrations/spsa.py
> +algorithm. SPSA is an optimization method that involves *approximating* the
Added.

2021-03-24 16:25 UTC, antalszava commented on demonstrations/spsa.py
> +where :math:`\hat{g}_{k}` is the estimate of the gradient :math:`g(u) = \frac{
Good catch! Should be `\theta`. Thanks

2021-03-24 16:30 UTC, antalszava commented on demonstrations/spsa.py
> +# dependent on the specific problem), [#spall_implementation]_ includes
Choosing the hyperparameters for the optimizers (e.g., step size) is problem dependent and for stochastic approximation methods, it is, even so, the case.

2021-03-24 16:34 UTC, antalszava commented on demonstrations/spsa.py
> +)
Good idea, thanks! Just double-checking:
```
    active_electrons=2, active_orbitals=2
```
would be default?

Also, is the `molecular_hamiltonian` function due to be changed? (not sure about this)

2021-03-24 16:50 UTC, antalszava commented on demonstrations/spsa.py
> +possible, or too resource intensive. SPSA provides a stochastic method for approximating the gradient of a
We know that quantum functions are differentiable, yet their gradients are not necessarily available. The parameter-shift rules are neat tricks that help us get the gradients, but they are not completely general. Therefore there are cases indeed, where we know that a function is differentiable, can evaluate the function itself (running the circuit on a quantum computer) but we have no information about its gradient (cannot run a quantum experiment that yields the gradient of the quantum function).

On another note, the demo is more focused on the other example hinted on:
>  evaluating the gradient is not possible, **or too resource intensive**.

Let me know if it's good to incorporate parts of this description in the text.

2021-03-24 17:22 UTC, agran2018 commented on demonstrations/spsa.py
> +alternative to computing the gradients of quantum circuits. One such technique
No problem Antal, this is a matter of style, totally optional.

2021-03-24 17:36 UTC, agran2018 reviewed
Thanks @antalszava!, looks good to me.

2021-03-24 17:36 UTC, agran2018 commented on demonstrations/spsa.py
> +# dependent on the specific problem), [#spall_implementation]_ includes
oh yes. Sorry Antal for my ambigous comment. What I wanted to suggest was to rephrase the sentence within parenthesis, also optional.

2021-03-24 17:39 UTC, agran2018 commented on demonstrations/spsa.py
> +)
The default for ``active_electrons`` and ``active_orbitals`` is ``None`` which means to consider all electrons and orbitals as active. In the case of H2 in a minimal basis they are both equal to ``2``.

2021-03-24 17:47 UTC, agran2018 commented on demonstrations/spsa.py
> +possible, or too resource intensive. SPSA provides a stochastic method for approximating the gradient of a
I see. Thanks @antalszava for the explanation.

2021-03-24 17:47 UTC, antalszava commented on demonstrations/spsa.py
> +# dependent on the specific problem), [#spall_implementation]_ includes
Oh got it! Rephrased

2021-03-24 20:50 UTC, co9olguy commented on demonstrations/spsa.py
> +   Image source: [#spall_overview]_
I don't know what it is, this optimization landscape frightens me :fearful:

2021-03-25 00:57 UTC, antalszava commented on demonstrations/spsa.py
> +   Image source: [#spall_overview]_
Oh gosh @josh146, completely missed this thread on my first pass today and only found it after our earlier chat from today! 😲 Thank you for the drawing!!! 😊 🎊

-----
It would look as follows, perhaps making the two optimization paths, the dots for each data point and the font bigger could help with identifying what the picture showcases?


![image](https://user-images.githubusercontent.com/24476053/112402359-c88b4500-8ce2-11eb-950a-a42357b5bab4.png)

2021-03-25 00:59 UTC, antalszava commented on demonstrations/spsa.py
> +#     Iteration = 19, Cost = -0.996
Thanks! Added

2021-03-25 00:59 UTC, antalszava commented on demonstrations/spsa.py
> +dev_sampler._num_executions = 0
Removed the occurrences of `dev_sampler._num_executions`

2021-03-25 01:03 UTC, antalszava commented on demonstrations/spsa.py
> +from noisyopt import minimizeSPSA
Got it! 🙂  Maybe it's better to keep it as is for now and could update later if we'd like.

2021-03-25 13:39 UTC, glassnotes commented on demonstrations/spsa.py
> +Simultaneous Perturbation Stochastic Approximation (SPSA) to optimize quantum
```suggestion
the Simultaneous Perturbation Stochastic Approximation (SPSA) algorithm to optimize quantum
```

2021-03-25 13:39 UTC, glassnotes commented on demonstrations/spsa.py
> +positive number. [#spall_overview]_
```suggestion
positive number [#spall_overview]_.
```

2021-03-25 13:39 UTC, glassnotes commented on demonstrations/spsa.py
> +    Just with other PennyLane devices, the number of samples taken for a device
```suggestion
    Just as with other PennyLane devices, the number of samples taken for a device
```

2021-03-25 13:39 UTC, glassnotes commented on demonstrations/spsa.py
> +)
```suggestion
all_pauliz_tensor_prod = qml.operation.Tensor(*[qml.PauliZ(i) for i in range(num_wires)])
```

This got expanded when I ran the code through Black (with a conservative number of lines), so we can either keep as is or put back to the original - it doesn't cause a horizontal scrollbar.

2021-03-25 13:39 UTC, glassnotes commented on demonstrations/spsa.py
> +# remaining component required for the optimization: the *SPSA optimizer*.
```suggestion
# remaining component required: the *SPSA optimizer*.
```

2021-03-25 13:39 UTC, glassnotes commented on demonstrations/spsa.py
> +# rate and affects the degree to which the parameters change at each update
```suggestion
# rate and affect the degree to which the parameters change at each update
```

2021-03-25 13:39 UTC, glassnotes commented on demonstrations/spsa.py
> +# convergence. Note that we also reset the number of executions of the device.
```suggestion
# convergence. Note that we also create a new device in order to reset the execution count to 0. 
```

2021-03-25 13:39 UTC, glassnotes commented on demonstrations/spsa.py
> +# At this point, nothing else remains, but to check which of these approaches did
```suggestion
# At this point, nothing else remains but to check which of these approaches did
```

2021-03-25 13:39 UTC, glassnotes commented on demonstrations/spsa.py
> +plt.scatter(
```suggestion
plt.plot(
```

2021-03-25 13:47 UTC, antalszava commented on demonstrations/spsa.py
> +)
Thank you for checking that! The one-liner seems good

2021-03-26 14:43 UTC, agran2018 approved these changes
Nice tutorial!, thank you @antalszava, @glassnotes !. I just left a comment regarding line 587

``# TODO: update comment if verified``

2021-03-26 14:43 UTC, agran2018 commented on demonstrations/spsa.py
> +
Nice condensed intro!

2021-03-26 14:43 UTC, agran2018 commented on demonstrations/spsa.py
> +    # TODO: update comment if verified
should this comment be updated/deleted?

2021-03-26 15:03 UTC, antalszava commented on demonstrations/spsa.py
> +    # TODO: update comment if verified
Good catch, thanks!

2021-03-26 17:41 UTC, merged