Make it more genric
PennyLaneAI/qml pull request #196
Opened 2020-12-26 13:57 UTC by YumiA

The modifications aim to make the algorithm generic that it can deal with any number of features, hence any number of qubits.

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Add a thumbnail link to your tutorial in `beginner.rst`, or if a
      QML implementation, in `implementations.rst`.

- [ ] All QML tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2021-01-05 21:30 UTC, antalszava requested changes
Hi @YumiA :slightly_smiling_face: Thank you so much for looking into this!

Left a couple of suggestions and questions for my own understanding. One of the key things to consider would be how exactly the architecture generalizes for more than 4 features.

2021-01-05 21:30 UTC, antalszava commented on demonstrations/tutorial_multiclass_classification.py
> +    return qml.expval(PZ)
Might be worth running `black -l 100 tutorial_multiclass_classification.py` on this file to pick up some formatting details here like adding whitespace (might change some further parts of the script, which is okay).

2021-01-05 21:30 UTC, antalszava commented on demonstrations/tutorial_multiclass_classification.py
> +        qml.CNOT(wires=[j*2, j*2+1])
This approach will pairwise entangle qubits that is qubits 0-1, qubits 2-3, etc will be entangled. Would that be what we'd aim for here?

2021-01-05 21:30 UTC, antalszava commented on demonstrations/tutorial_multiclass_classification.py
> +    X = torch.tensor(data[:, 1:feature_size+1])
How come this was changed? It seems like now we'd classify features 1-4 instead of 0-3.

2021-01-05 22:13 UTC, albi3ro commented on demonstrations/tutorial_multiclass_classification.py
> +    even_wirelist = [i for i in range(num_qubits) if i%2 == 0]
Thanks for the pull request!

You might want to add some commenting here to explain what is going on.

2021-01-06 15:19 UTC, YumiA commented on demonstrations/tutorial_multiclass_classification.py
> +    qml.templates.embeddings.AmplitudeEmbedding(feat, range(0,num_qubits), pad=(2**num_qubits-feature_size), normalize=True)
Hi @antalszava :) and thanks for the review and the suggestions.
Yes there is a reason for using the formula ((2**num_qubits-feature_size); as per my understanding the AmplitudeEmbedding function needs to have exactly 2^n numbers (n = # of qubits) to encode them and the pad is used to complement the features in case their size was less than 2^n.

2021-01-06 15:58 UTC, YumiA commented on demonstrations/tutorial_multiclass_classification.py
> +    X = torch.tensor(data[:, 1:feature_size+1])
This is was done by mistake as I used it to run one some dataset whose first column was just a sequence number.
```suggestion
    X = torch.tensor(data[:, 0:feature_size])
```

2021-01-06 16:03 UTC, YumiA commented on demonstrations/tutorial_multiclass_classification.py
> +    return qml.expval(PZ)
I'm not sure how to do that, maybe because I'm new here!

2021-01-06 16:06 UTC, YumiA commented on demonstrations/tutorial_multiclass_classification.py
> +        qml.CNOT(wires=[j*2, j*2+1])
When I ran the code as is after increasing the number of qubits to fit my dataset, I got bad accuracy. After I applied the above modifications, I got 98% accuracy. Could you please suggest and explain the right approach?

2021-01-06 23:45 UTC, antalszava commented on demonstrations/tutorial_multiclass_classification.py
> +    qml.templates.embeddings.AmplitudeEmbedding(feat, range(0,num_qubits), pad=(2**num_qubits-feature_size), normalize=True)
Sure thing! :slightly_smiling_face: 

>  as per my understanding the AmplitudeEmbedding function needs to have exactly 2^n numbers (n = # of qubits) to encode them 

Correct!

> the pad is used to complement the features in case their size was less than 2^n.

Padding indeed involves making up for the case when `m<2^n` where `m` is the number of features and `n` is the number qubits. The `pad` argument, however, defines the constant to pad with rather than the remaining values that could be embedded (it does not stand for the difference `d` of `m+d==2^n`, but rather the padding value). See the `pad` and `pad_with` arguments in the [latest version of the `AmplitudeEmbedding` documentation](https://pennylane.readthedocs.io/en/latest/code/api/pennylane.templates.embeddings.AmplitudeEmbedding.html) for more details.

2021-01-06 23:54 UTC, antalszava commented on demonstrations/tutorial_multiclass_classification.py
> +    return qml.expval(PZ)
No worries there! `black` is a formatting tool for Python that reformats Python code such that the result conforms with PEP8 coding standards. We use that for developing PennyLane. In this case, it could help with adding some whitespace in the code.

When using `pip`, `black` can be installed by running `pip install black` from the command line. Once installed, the command `black` is available to be used. `black -l 100 tutorial_multiclass_classification.py` can then be run in the folder where the `tutorial_multiclass_classification.py` file is located.

You can find more details on submitting a Pull Request [here](https://pennylane.readthedocs.io/en/latest/development/guide/pullrequests.html).

2021-01-07 00:05 UTC, antalszava commented on demonstrations/tutorial_multiclass_classification.py
> +    X = torch.tensor(data[:, 1:feature_size+1])
Got it! Maybe it could be reverted then. The reason is that the demo continues to use the Iris dataset, which could also potentially have `feature_size==5` with `data[:, 0:feature_size]`, whereas `data[:, 1:feature_size+1]` would result in an `IndexError` as the first features were skipped.

```suggestion
    X = torch.tensor(data[:, 0:feature_size])
```

2021-01-07 00:06 UTC, antalszava commented on demonstrations/tutorial_multiclass_classification.py
> +    X = torch.tensor(data[:, 1:feature_size+1])
Got it! Reverted this then. The reason is that the demo continues to use the Iris dataset, which could also potentially have `feature_size==5` with `data[:, 0:feature_size]`, whereas `data[:, 1:feature_size+1]` would result in an `IndexError` as the first features were skipped.

2021-01-07 00:28 UTC, antalszava commented on demonstrations/tutorial_multiclass_classification.py
> +        qml.CNOT(wires=[j*2, j*2+1])
> When I ran the code as is after increasing the number of qubits to fit my dataset, I got bad accuracy.

Would that mean only having `qml.CNOT(wires=[0, 1])`?

> Could you please suggest and explain the right approach?

Sure! It's great that the accuracy was already such. Another step forward would be to apply even more `CNOT` operations. In the case of having two qubits, applying a single `CNOT` can create entanglement between qubits 0 and 1.

However, as the number of qubits increases, the ability to create pairwise entanglement between any two qubits of the entire system requires applying a CNOT operation between every qubit. That is, for three qubits, we'll need to apply three `CNOT`s, for four qubits four, etc.

This is demonstrated in the [`StronglyEntanglingLayers` template](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.templates.layers.StronglyEntanglingLayers.html?highlight=strongly#pennylane.templates.layers.StronglyEntanglingLayers). This template consists:
1. Applying arbitrary single-qubit rotations on each qubit
2. Pairwise entangling every qubit

As a matter of fact, this code snippet actually corresponds to using `StronglyEntanglingLayers` with `W` weights! Therefore, having a logic similar as [here](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/templates/layers/strongly_entangling.py#L100) could work: applying CNOTs in a ring structure between every two qubit.

2021-01-07 03:09 UTC, antalszava commented
Hi @YumiA, left a couple of comments, hope they help! The two checks fail due to something unrelated to the changes made in this pull request, we are looking into solving that.

2021-01-07 13:13 UTC, YumiA commented on demonstrations/tutorial_multiclass_classification.py
> +    qml.templates.embeddings.AmplitudeEmbedding(feat, range(0,num_qubits), pad=(2**num_qubits-feature_size), normalize=True)
Got it, thank you. But wouldn't be better to use something like the following:
```suggestion
    qml.templates.embeddings.AmplitudeEmbedding(feat, range(0,num_qubits), pad=np.mean(feat), normalize=True)
```

2021-01-07 14:35 UTC, YumiA commented on demonstrations/tutorial_multiclass_classification.py
> +    return qml.expval(PZ)
Thanks again for the explanation. I ran the tool and here is the result:
```suggestion
    even_wirelist = [i for i in range(num_qubits) if i % 2 == 0]
    PZ = qml.PauliZ(0)
    for wi in even_wirelist[1:]:
        PZ = PZ @ qml.PauliZ(wi)
    if num_qubits % 2 != 0:
        PZ = PZ @ qml.PauliZ(num_qubits - 1)
    return qml.expval(PZ)
```
!

2021-01-07 14:45 UTC, YumiA commented on demonstrations/tutorial_multiclass_classification.py
> +        qml.CNOT(wires=[j*2, j*2+1])
So this should achieve the required strong entanglement:
```suggestion
    for j in range(int(num_qubits/2)):
        qml.CNOT(wires=[j*2, j*2+1])
```

2021-01-07 15:54 UTC, antalszava commented on demonstrations/tutorial_multiclass_classification.py
> +        qml.CNOT(wires=[j, j + 1])
1. As `num_qubits` is an integer, we can get away with not having a type conversion.
2. To complete the "ring" pattern of CNOTs, we need to apply a CNOT such that the last qubit is the control and the first qubit is the target.

(Note: worth trying that the suggestion indeed works correctly, did not run it.)
```suggestion
    for j in range(num_qubits - 1):
        qml.CNOT(wires=[j, j + 1])
    if num_qubits >=2:
        # Apply additional CNOT to complete the ring pattern
        qml.CNOT(wires=[num_qubits - 1, 0])    
```

2021-01-07 15:54 UTC, antalszava commented on demonstrations/tutorial_multiclass_classification.py
> +    qml.templates.embeddings.AmplitudeEmbedding(feat, range(0,num_qubits), pad=(2**num_qubits-feature_size), normalize=True)
Not quite. `np.mean(feat)` could actually be a value mistaken to be a feature. This is something we'd like to avoid by using "non-informative constants", see reasons for this in the paragraph after equation (2) in section 2. A on page 4 from the [second ref](https://arxiv.org/pdf/1804.00633.pdf) of the original tutorial.

2021-01-07 15:55 UTC, antalszava commented on demonstrations/tutorial_multiclass_classification.py
> +        qml.CNOT(wires=[j*2, j*2+1])
See this [comment](https://github.com/PennyLaneAI/qml/pull/196#discussion_r553410032).

2021-01-08 14:28 UTC, antalszava commented on demonstrations/tutorial_multiclass_classification.py
> +        PZ = PZ @ qml.PauliZ(num_qubits - 1)
One more question here: how come only even wires were measured here? (And additionally the last wire `if num_qubits % 2 != 0`) @mariaschuld might also have insights here

2021-01-08 14:29 UTC, antalszava commented
@YumiA thanks for the changes! This is looking great, only had one last question from my side. After no more modifications are being done, it might be worth running `black` for another time.

2021-01-11 13:34 UTC, mariaschuld commented on demonstrations/tutorial_multiclass_classification.py
> +        # Apply additional CNOT to complete the ring pattern
Since this is just an example circuit, is this really needed? Does it change the performance of the example?

And if so, maybe better to be explicit?
```suggestion
        # Apply additional CNOT to entangle the last with the first qubit
```

2021-01-11 13:34 UTC, mariaschuld commented on demonstrations/tutorial_multiclass_classification.py
> +    qml.templates.embeddings.AmplitudeEmbedding(feat, range(0,num_qubits), pad=0.0, normalize=True)
Should do the same thing :)

```suggestion
    qml.templates.embeddings.AmplitudeEmbedding(feat, range(num_qubits), pad=0.0, normalize=True)
```

2021-01-11 13:36 UTC, mariaschuld commented on demonstrations/tutorial_multiclass_classification.py
> +        PZ = PZ @ qml.PauliZ(num_qubits - 1)
To be honest, I am not sure I understand this piece of code. What would you want to do?

2021-01-11 13:38 UTC, mariaschuld reviewed
Hey @YumiA, thanks so much for the contribution, it's great to generalise this demo. 

Like Antal, I was only wondering about the measurement. Maybe you could explain, and add a comment so other users understand it too?

2021-01-11 17:47 UTC, YumiA commented on demonstrations/tutorial_multiclass_classification.py
> +        # Apply additional CNOT to complete the ring pattern
Thanks Dr. @mariaschuld for the review.

2021-01-11 17:49 UTC, YumiA commented on demonstrations/tutorial_multiclass_classification.py
> +    qml.templates.embeddings.AmplitudeEmbedding(feat, range(0,num_qubits), pad=0.0, normalize=True)
:)
yes that's better.

2021-01-11 17:58 UTC, YumiA commented on demonstrations/tutorial_multiclass_classification.py
> +        PZ = PZ @ qml.PauliZ(num_qubits - 1)
Thanks Dr. @mariaschuld .
I wanted to measure one qubit of each two and in case of odd number of qubits the last qubit will be measured as well. I just thought that I follow the same way of the original code:
` return qml.expval(qml.PauliZ(0))`

It measured only one qubit out of two.

2021-01-12 09:06 UTC, mariaschuld commented on demonstrations/tutorial_multiclass_classification.py
> +        PZ = PZ @ qml.PauliZ(num_qubits - 1)
Ah, I see, thanks for explaining! 

Hmm, I haven't written the demo, but I strongly suspect that the idea is to just measure the first qubit no matter how many classes there are. This is a mere design decision: your generalisation is surely not wrong (and I cannot tell if one would work better than the other), but just leaving the ``qml.expval(qml.PauliZ(0))`` could be much simpler to understand for readers? 

So I suggest, unless your solution has a significant performance gain in the optimisation, just measure the expval of the first qubit?

2021-01-12 13:53 UTC, YumiA commented on demonstrations/tutorial_multiclass_classification.py
> +        PZ = PZ @ qml.PauliZ(num_qubits - 1)
Actually, this change came out due to the failure of the original code to classify my dataset. Once I applied the above change I got the expected accuracy (98%). I took the dataset from an experiment that used the classical neural network with 200 hidden nodes  to achieve 99% accuracy.
However, I rerun the new code after the changes we committed here and unfortunately the accuracy went down to 85%.
I'm doing a last run with nonzero padding and let's see how will be the result!

2021-01-12 18:10 UTC, YumiA commented on demonstrations/tutorial_multiclass_classification.py
> +        PZ = PZ @ qml.PauliZ(num_qubits - 1)
Here are the results:
1- Applying all the changes approved here:
![Figure_6](https://user-images.githubusercontent.com/18194254/104354313-74195b80-5522-11eb-9aa3-1d08736358e8.png)
2- Same but with non-zero padding
`qml.templates.embeddings.AmplitudeEmbedding(feat, range(num_qubits), pad=float((2**num_qubits)-feature_size), normalize=True)`
![Figure_7](https://user-images.githubusercontent.com/18194254/104354595-db371000-5522-11eb-95f1-ea2c73eb8ca8.png)

I have no explanation, I hope you may help me.

2021-01-13 11:45 UTC, mariaschuld commented on demonstrations/tutorial_multiclass_classification.py
> +        PZ = PZ @ qml.PauliZ(num_qubits - 1)
Thanks so much for the plots! 

Wait, I am a bit confused now. Aren't your changes supposed to reproduce the result of the demo, but generalise the code only? So shouldn't the single-qubit measurement work exactly as before, if you choose the features so that the number of qubits is 2?

But overall this question of yours is always tricky, is the demo there to show a simple example that may not work super well, or is it better to add some more complex design decisions? I personally find clarity more important than performance, because ultimately we would need a full-blown systematic benchmark analysis to see which measurement/template setting works best, and even then it will only be true for the particular dataset. So I find that as long as a demo has reasonable results (i.e. it learns something) then it should be fine.

I would suggest the following: 
* If you can use `PauliZ(wires=0)` and make the generalised demo reproduce the earlier results, then I'd go for that. 
* If for some reason (maybe because I understood things wrong) you want to use a more "global" measurement constructed from tensor products, then maybe would one constructed from all qubits (`for wi in range(num_qubits)`) do the job? Or from the first half  (`for wi in range(num_qubits//2)`)?
* If none of the above works for you, then I'd explain your choice in a comment in the code. I'd still have a question about the logic though. When I print what wires you use in the tensor product, I get this:
``` python
num_qubits = 3

even_wirelist = [i for i in range(num_qubits) if i % 2 == 0]
for wi in even_wirelist[1:]:
    print(wi)
if num_qubits % 2 != 0:
    print(num_qubits - 1)
# 2
# 2
```
Surely that is not what you want? Or am I overlooking something?

2021-01-13 16:43 UTC, YumiA commented on demonstrations/tutorial_multiclass_classification.py
> +        PZ = PZ @ qml.PauliZ(num_qubits - 1)
Well, let me tell you the story. I'm studying Quantum Machine Learning and I'm trying to understand how things work. (I'm a senior high school student)

So, no I didn't make those changes for the sake of the demo. Actually, I got a dataset from an experiment on the Azure ML gallery: https://gallery.azure.ai/Experiment/Breast-cancer-dataset
The experiment achieved very high accuracy so it was a good practice for me to try to achieve the same using this tutorial here. Accordingly, the changes were meant to really generalize the tutorial for any dataset could be used.

2021-01-13 17:14 UTC, YumiA commented on demonstrations/tutorial_multiclass_classification.py
> +        PZ = PZ @ qml.PauliZ(num_qubits - 1)
So according to the plots above, I would say that we may need a better way of padding the data!!

2021-01-13 18:19 UTC, YumiA commented
> Hey @YumiA, thanks so much for the contribution, it's great to generalise this demo.
> 
> Like Antal, I was only wondering about the measurement. Maybe you could explain, and add a comment so other users understand it too?

I put some comments and rerun the black tool again.

2021-01-14 10:12 UTC, mariaschuld commented on demonstrations/tutorial_multiclass_classification.py
> +        PZ = PZ @ qml.PauliZ(num_qubits - 1)
Hey @YumiA. Thanks for the clarification. 

If you don't mind, let us do the following, to merge your PR as fast as possible:

We leave the old measurement, so instead of 

``` python
    even_wirelist = [i for i in range(num_qubits) if i % 2 == 0]
    PZ = qml.PauliZ(0)
    for wi in even_wirelist[1:]:
        PZ = PZ @ qml.PauliZ(wi)
    if num_qubits % 2 != 0:
        PZ = PZ @ qml.PauliZ(num_qubits - 1)
    return qml.expval(PZ)
```
you revert to
 
```python
   return qml.expval(qml.PauliZ(0))
```
I checked myself, and the results are the same as in the current demo (as expected, since the experiment is the same, it just uses more general code).

We add a note stating that global or more complicated measurements could be beneficial, so every user can make their own choices.

I will make the suggestions in the code, if you want you can just accept them and we can proceed to merging.

2021-01-14 10:14 UTC, mariaschuld commented on demonstrations/tutorial_multiclass_classification.py
> +# since the data should be encoded into the circuit
```suggestion
# the number of the required qubits is calculated from the number of features
```

2021-01-14 10:14 UTC, mariaschuld commented on demonstrations/tutorial_multiclass_classification.py
> +    return qml.expval(PZ)
```suggestion
    return qml.expval(qml.PauliZ(0))
```

2021-01-14 10:18 UTC, mariaschuld commented on demonstrations/tutorial_multiclass_classification.py
>  # Data is embedded in each circuit using amplitude embedding:
```suggestion
# Data is embedded in each circuit using amplitude embedding.
# .. note::
#     For demonstration purposes we are using a very simple circuit here. 
#     You may find that other choices, for example more 
#     elaborate measurements, increase  the power of the classifier.      
```

2021-01-14 13:08 UTC, antalszava approved these changes
Looks good to me! :100: Thank you so much for adjusting it along the way @YumiA and for the nice contribution! :blush:

2021-01-14 14:57 UTC, YumiA commented
Thanks @antalszava for the approval. Is this done now? Should I close the request?

2021-01-14 15:40 UTC, antalszava commented
Hi @YumiA, we'll merge in the pull request at a convenient time and it will also close it automatically. :)

2021-01-15 13:01 UTC, merged