[WIP] Demo about Haar measure
PennyLaneAI/qml pull request #217
Opened 2021-02-24 13:31 UTC by glassnotes

Still TODO:
 - [ ] Mathematical description of SU(n) / multi-qubit case
 - [ ] QR decomposition
 - [ ] Levy's lemma
 - [ ] Derive structure of matrix entries as Gaussian-distributed complex numbers
 - [ ] Sphere graphics

2021-03-19 18:05 UTC, co9olguy requested changes
Nice tutorial @glassnotes!

I left quite a few comments and suggestions, but the overall demo is :100:. More a matter of tweaking and slight improvements to make it even better :muscle:

2021-03-19 18:05 UTC, co9olguy commented on demonstrations/tutorial_haar_measure.py
> +# applications!
Nice! Looking forward to that one! :muscle:

2021-03-19 18:05 UTC, co9olguy commented on demonstrations/tutorial_haar_measure.py
> +#    <https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.73.58>`__.
No arxiv? :crying_cat_face:

2021-03-19 18:05 UTC, co9olguy commented on demonstrations/tutorial_haar_measure.py
> +#     (`lecture notes <http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.679.2560?>`__).
link didn't work for me

2021-03-19 18:05 UTC, co9olguy commented on demonstrations/tutorial_haar_measure.py
> +# parametrizations of the :math:`N`-dimensional `special unitary group
Felt this change of direction could have been better motivated.
e.g., "a lot of the our understanding of decompositions for unitaries can be taken from
the study of photonics, because..."  etc

2021-03-19 19:53 UTC, glassnotes commented on demonstrations/tutorial_haar_measure.py
> +#     (`lecture notes <http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.679.2560?>`__).
```suggestion
#     (`lecture notes <http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.679.2560>`__).

```

2021-03-19 19:54 UTC, glassnotes commented on demonstrations/tutorial_haar_measure.py
> +#    <https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.73.58>`__.
Sadly not :frowning_face:

2021-03-22 15:44 UTC, glassnotes commented on demonstrations/tutorial_haar_measure.py
> +# of the Haar measure. The decomposition is formulated recursively such that an
Subtle difference is that in the third one the modes are being swapped around; the triangle in the first picture is a different parametrization built to explicitly avoid this, and allow for the recursive aspect :+1:

2021-03-22 17:24 UTC, co9olguy commented on demonstrations/tutorial_haar_measure.py
> +#    obtained an uneven distribution.
:100:

2021-03-22 17:28 UTC, co9olguy commented on demonstrations/tutorial_haar_measure.py
> +[TODO: simple graphic of spherical coordinates (?)]
Agreed, not needed, since the pic below has most of the same things in it

2021-03-22 17:31 UTC, co9olguy commented on demonstrations/tutorial_haar_measure.py
> +analogous terms we need for working with the unitary group.
Great improvement!

2021-03-22 17:33 UTC, co9olguy commented on demonstrations/tutorial_haar_measure.py
> +#plt.rcParams.update({"text.usetex" : True})
?

2021-03-22 17:34 UTC, co9olguy commented on demonstrations/tutorial_haar_measure.py
> +    fig.subplots_adjust(left=0, right=1, bottom=0, top=1)
I'd still like to "zoom in" on these 3d plots a bit more to avoid too so extra whitespace

2021-03-22 17:49 UTC, co9olguy approved these changes
Awesome tutorial :heart_eyes:

2021-03-22 17:49 UTC, co9olguy commented on demonstrations/tutorial_haar_measure.py
> +# much-better distributed over the sphere. Putting this information together,
```suggestion
# much better distributed over the sphere. Putting this information together,
```

2021-03-22 17:49 UTC, co9olguy commented on demonstrations/tutorial_haar_measure.py
> +# [TODO: hand-draw graphics]
Agree that, while it would be nice to have these drawn by hand, we can probably make do with these

2021-03-22 18:38 UTC, co9olguy commented on demonstrations/tutorial_haar_measure.py
> +    :property="og:image": https://pennylane.ai/qml/_images/tutorial_haar_thumb.png
Does this image exist? Couldn't find it in the PR

2021-03-22 19:37 UTC, merged