Jax tutorial
PennyLaneAI/qml pull request #229
Opened 2021-03-10 05:01 UTC by Thenerdstation

Adding a WIP draft to get early comments. Would also like some help getting links correctly embedded. 

This tutorial goes over the most common use cases for JAX transforms, mainly gradient decent and ES. We keep the examples simple and short to not confuse new users.

2021-03-10 05:20 UTC, josh146 reviewed
Looks great so far! touches on the two things I think the JAX backend excels at --- JIT and vmap. I reckon it would be quite cool to have an informal benchmark plot showing the advantage of jitting the QNode.

You could even show an example where you have a complex hybrid cost function with multiple QNodes, and JIT the cost function.

2021-03-10 05:20 UTC, josh146 commented on demonstrations/tutorial_jax_transformations.py
> +many of its transformations are also useful for QML, and can be used directly with Pennylane.
```suggestion
many of its transformations are also useful for quantum machine learning (QML), and can be used directly with Pennylane.
```

2021-03-10 05:20 UTC, josh146 commented on demonstrations/tutorial_jax_transformations.py
> +# for this tutorial.
As of https://github.com/PennyLaneAI/pennylane/pull/1008, no need to specify `default.qubit.jax` --- using `default.qubit` with `interface="jax"` should Just Work™

I think I want to move away from specifying `default.qubit.interface` in demos and examples; everything should just be `default.qubit`

2021-03-10 05:20 UTC, josh146 commented on demonstrations/tutorial_jax_transformations.py
> +# for this tutorial.
Although I support a complication is the random + jit behaviour of `default.qubit.jax`. But this is an issue of documentation --- there should be a single docs page for `default.qubit`, and all TF/JAX/etc subtleties are available there as call outs.

2021-03-10 05:20 UTC, josh146 commented on demonstrations/tutorial_jax_transformations.py
> +# Here, we will be using the jax.vmap transform to make running batches of circuits much easier.
This is awesome!

2021-03-10 05:20 UTC, josh146 commented on demonstrations/tutorial_jax_transformations.py
> +vcircuit = jax.vmap(circuit)
😍

2021-03-10 16:04 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +# for this tutorial.
I could make it `default.qubit` for the first device and then use `default.qubit.jax` for the one that needs the prng_key

2021-03-10 18:29 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +# Let's start with a simple one. The code we wrote above is entirely continuous, so
```suggestion
# Let's start with a simple one. The code we wrote above is entirely differentiable, so
```

2021-03-10 18:31 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +# batch of expectations.
```suggestion
# a batch of expectations.
```

2021-03-10 18:32 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +# To set the random number generating key, you'll have to pass the jax.random.PRNGKey
```suggestion
# To set the random-number-generating key, you'll have to pass the jax.random.PRNGKey
```

2021-03-10 18:34 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +# JAX was designed to have experiments be as repeatable as possible. Because of this,
There is a lot of discussion here about JAX RNGs, but you should lead up front with `jit`. As that is one aspect of JAX that may not be as familiar to the QML audience, it's a good opportunity to describe it in some more detail

2021-03-10 18:37 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +# JAX was designed to have experiments be as repeatable as possible. Because of this,
👍 Good advice.

2021-03-24 04:53 UTC, josh146 commented on demonstrations/tutorial_jax_transformations.py
> +dev = qml.device("default.qubit", wires=2, shots=None)
flyby comment because I saw this diff from an email notification:

- the `master` branch of `qml` tracks PennyLane stable (v0.14.1)
- the `dev` branch of `qml` tracks PennyLane master (v0.15.0-dev)

Since this is being merged into master (likely releasing it prior to the v0.15 release), just need to make sure this is v0.14.1 compatible (e.g., `analytic=True` rather than `shots=None`).

2021-03-24 04:53 UTC, josh146 commented on requirements.txt
> +jaxlib==0.1.64
new JAX was released 2 hours ago 🤩

2021-03-24 14:18 UTC, Thenerdstation commented on requirements.txt
> +jaxlib==0.1.64
They release a new JAX like every 2 days lol

2021-03-24 14:19 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +dev = qml.device("default.qubit", wires=2, shots=None)
👍🏼

2021-03-24 14:57 UTC, josh146 commented on requirements.txt
> +jaxlib==0.1.64
I noticed this one because it broke PL lol

I pushed a sneaky 3am fix though so everything is under control

2021-03-24 20:16 UTC, glassnotes requested changes
@Thenerdstation this is a cool demo, it looks like there is some really powerful functionality in there! 

I've left some specific comments as well as some suggestions for wording/typos. My general comments are mostly pedagogical. This is mentioned in a comment within, but it's good practice to outline the structure and some learning goals for the reader at the beginning, and refer back to them later (sometimes throughout, but mostly in the conclusion).  There currently aren't any concluding remarks so I recommend to add a couple lines at the end to tie things up. There are also a few places where code is run and results are printed, but there is no interpretation provided - for these, just a line or two discussing the results is helpful for showing the reader that things worked as expected.

2021-03-24 20:16 UTC, glassnotes commented on demonstrations/tutorial_jax_transformations.py
> +# In this tutorial, we will highlight some ways to use JAX transformations with Pennylane
Recommend to rephrase and expand this to a learning outcome(s). What specific skills or facts will the reader know by the end of this tutorial that they didn't know before? (e.g., "By the end of this tutorial, you will be able to leverage JAX to run calculations in PennyLane in an [adjective] way", or something like this). This is helpful for the reader because it sets goals and direction for the rest of the tutorial.

2021-03-24 20:16 UTC, glassnotes commented on demonstrations/tutorial_jax_transformations.py
> +print(f"key2: {circuit(key2, jnp.pi/2)}")
Add concluding remarks - refer back to the learning outcomes and remind the reader what they should now know how to do. Also helpful to link to any resources that would offer more details or a more advanced treatment of the material here, in case they're interested.

2021-03-24 20:16 UTC, glassnotes commented on demonstrations/tutorial_jax_transformations.py
> +print(f"key1: {circuit(key1, jnp.pi/2)}")
A warning appears when this runs in the build - we can suppress those the phrase to the `conf.py` file (there are some examples already there around line 90).

2021-03-24 20:16 UTC, glassnotes commented on demonstrations/tutorial_jax_transformations.py
> +# Batching and Evolutionary Strategies.
```suggestion
# Batching and Evolutionary Strategies

```

2021-03-24 20:16 UTC, glassnotes commented on demonstrations/tutorial_jax_transformations.py
> +# Shots and Sampling with JAX.
```suggestion
# Shots and Sampling with JAX

```

2021-03-24 20:32 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +JAX is an incredibly powerful deep learning library that has been gaining traction in
Suggest replacing first "deep learning" with something like "scientific computing" or similar to avoid repetition in this first sentence

2021-03-24 20:32 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +# If this is your first time reading Pennylane code, we recommend going through
```suggestion
# If this is your first time reading PennyLane code, we recommend going through
```

2021-03-24 20:32 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +and can be used directly with Pennylane.
This is a decent starting paragraph, but I wonder if we can think of a bit more of a "hook" to entice the reader to continue reading rather than bounce

2021-03-24 20:32 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +# then evaluates the expectation value of the Pauli Z operator on the first wire.
```suggestion
# then evaluates the expectation value of the Pauli-Z operator on the first wire.
```

2021-03-24 20:32 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +# Notice that the output of the circuit is a JAX ``DeviceArray``.
Where should a user look to notice this? it's not evident from the output of the print statement above (which just gives `circuit(jnp.pi / 2): 0.0`)

2021-03-24 20:32 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +# Let's start with a simple one. The code we wrote above is entirely differentiable, so
It may not be clear to readers what "one" is here. Suggest "example" or "transformation"—or even "example transformation" :wink:

2021-03-24 20:32 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +
```suggestion
# We can then use this grad_circuit function to optimize the parameter value
via gradient descent.
```

2021-03-24 20:32 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +    param -= grad_circuit(param) # Gradient decent param.
```suggestion
    param -= grad_circuit(param) # Gradient-descent update.
```

2021-03-24 20:32 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +the deep learning community. While JAX was originally designed for classical ML,
since we provide the definition of QML acronym, probably should do the same for ML

2021-03-24 20:32 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +# or learning to sample thermal energy states. (LINK TO https://pennylane.ai/qml/demos/tutorial_vqt.html)
```suggestion
# QML is most useful for learning on quantum systems, like :doc:`finding chemical ground states <tutorial_vqe>`
# or  :doc:`learning to sample thermal energy states <tutorial_vqt>`
```

2021-03-24 20:33 UTC, co9olguy commented
Saw that @glassnotes submitted a review while I was in-progress with my review, with a lot of the same suggestions, so I switched over to "just comments" so you could see them before they got stale

2021-03-24 20:35 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +# Here, we will be using the jax.vmap transform to make running batches of circuits much easier.
```suggestion
# Here, we will be using the ``jax.vmap`` transform to make running batches of circuits much easier.
```

2021-03-24 20:35 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +# Let's now setup our ES training loop. The idea is pretty simple. First, we
```suggestion
# Let's now set up our ES training loop. The idea is pretty simple. First, we
```

2021-03-24 20:37 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +
```suggestion
```

2021-03-24 20:38 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +# cross compile computation to different hardware including CPUs, GPUs, etc.
```suggestion
# cross-compile computation to different hardware including CPUs, GPUs, etc.
```
not 100% sure about this one tbh

2021-03-24 20:39 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +# Jitting, compiling circuit execution
Doesn't parse for me. Do you mean "Jitting and compiling circuit execution"?

2021-03-24 20:40 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +print("First run:", circuit(0.123)) # Compile overhead the first time time method is executed.
This line leads to horizontal scrollbar in code block when rendered. Suggest using two lines

2021-03-24 20:41 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +# We recommend reading up
Seems like this sentence is unfinished

2021-03-24 20:41 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +# Note: This example only applies if you are using jax.jit. Otherwise, we automatically
"we" being PennyLane? Might be better to say that explicitly

2021-03-24 20:42 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +print(f"key1: {circuit(key1, jnp.pi/2)}")
```/home/circleci/project/venv/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py:5179: UserWarning: Explicitly requested dtype <class 'numpy.int64'> requested in astype is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.
  lax._check_user_dtype_supported(dtype, "astype")```

2021-03-24 20:43 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +print(f"key1: {circuit(key1, jnp.pi/2)}")
If possible, better to code the example to avoid warnings. Users who run locally might encounter warning and ask us about it

2021-03-24 20:45 UTC, co9olguy commented
Thanks @Thenerdstation! Gonna be awesome to have this tutorial

Generally my feedback (probably similar to @glassnotes) is there is a solid foundation here, but would be nice to have a bit more narrative elements (e.g., more explicit conclusions at each section than a print statement, alternative methods to visualize, a more compelling hook at the beginning, and a nice wrap-up at the end

2021-03-26 21:52 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +# Notice that the output of the circuit is a JAX ``DeviceArray``.
Aw good catch. Changed it to print the `repr` instead.

2021-03-26 22:02 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +# In this tutorial, we will highlight some ways to use JAX transformations with Pennylane
👍🏼 Good advice. I added a lot more info.

2021-03-26 22:02 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +print(f"key1: {circuit(key1, jnp.pi/2)}")
Updated the config to run in x64 mode, silencing this error.

2021-03-26 22:33 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +    # In this line, we run all 100 circuits in parallel.
Yes, kinda of. It's more complicated than that but essentially yes.

2021-03-26 22:34 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +    params = jax.random.normal(split, (100,)) * jnp.sqrt(var) + mean
Yes.

2021-03-26 22:36 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +# JAX is built on top of XLA,  an incredibly powerful numerics library that can
Added

2021-03-26 22:36 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +# We recommend reading up
For got to delete that sorry.

2021-03-26 22:36 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +# Note: This example only applies if you are using jax.jit. Otherwise, we automatically
👍🏼

2021-03-26 22:37 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +# Jitting, compiling circuit execution
Yes haha.

2021-03-26 22:37 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +# In this tutorial, we will highlight some ways to use JAX transformations with Pennylane
Added.

2021-03-26 22:37 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +print(f"key2: {circuit(key2, jnp.pi/2)}")
Added.

2021-03-26 22:38 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +JAX is an incredibly powerful deep learning library that has been gaining traction in
Changed to scientific computing

2021-03-26 22:41 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +# Let's start with a simple one. The code we wrote above is entirely differentiable, so
Changed.

2021-03-26 22:48 UTC, Thenerdstation commented
Thanks for the comments, @co9olguy @glassnotes. Very helpful.

I added narrative hooks and the JAX logo, but I'm not sure what more what more images I should add. I don't really want to add scatter plots since the examples are all 1D, and the plots would distract from the more important code examples.

Maybe some hand draw `fn -> jax.jit -> faster_fn` diagrams?

2021-03-29 16:01 UTC, glassnotes requested changes
@Thenerdstation, these are great improvements! Just left a couple comments, mostly small phrasing things and typos.

One thing left to be done is to put this in the TOC - I think as good place could be the 'basic' page in the 'getting started' category? Or maybe 'applications', since that's where the keras/torch stuff is and this feels similar in spirit?

2021-03-29 17:57 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +# neural network code.
Yep! Your suggestion feels fine to me.

2021-03-29 17:57 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +# With that said, we begin by importing PennyLane, JAX and the JAX-provided version of NumPy and
Oxford comma -_-

2021-03-29 17:58 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +# Notice that the output of the circuit is a JAX ``DeviceArray``.
Changed it to print the `repr` of the object which does print `DeviceArray`

2021-03-29 17:59 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +# that calcuates the gradient of the parameter relative to the output.
I think it should actually be `that calculates the gradient the output relative to the input`.

2021-03-29 18:01 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +# Another approach is to use evolutionary strategies (ES) to learn these parameters.
Good idea.

2021-03-29 18:02 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +vcircuit = jax.vmap(circuit)
<3

Transforms are great. We're adding them into pennylane now too. We've already added `qml.metric_tensor`, `qml.adjoint`, `qml.ctrl`, `qml.draw` with more to come!

2021-03-29 18:05 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +
Not quite. What were doing here is try to optimize a single circuit, but we run multiple of the same circuit with different parameters. These parameter's expectation values are calculated and are used to determine what the next batch of attempted parameters should be. 

It's basically guessing and checking with statistics.

2021-03-29 18:08 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +    # Notice how the device construction now happens within the jitted method.
I believe I do in line 234?

2021-03-29 18:26 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +# the same circuit over and over but with different parameters.
Nice!

2021-03-29 18:27 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +# with its easy access to quantum computers. We're still in early days of
```suggestion
# complement each other very nicely; JAX with its powerful transforms, and PennyLane 
# with its easy access to quantum computers. We're still in early days of 
```

2021-03-29 18:33 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +
```suggestion
```

2021-03-29 18:33 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +
```suggestion
```

2021-03-29 18:34 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +
```suggestion
```

2021-03-29 18:34 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +
```suggestion
```

2021-03-29 18:34 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +
```suggestion
```

2021-03-29 18:34 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +
```suggestion
```

2021-03-29 18:34 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +
```suggestion
```

2021-03-29 18:36 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +
these blank lines will prevent the tutorial from rendering properly
https://2820-214003948-gh.circle-artifacts.com/0/_build/html/demos/tutorial_jax_transformations.html

2021-03-30 17:44 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +.. meta::
What is TOC?

2021-03-30 18:45 UTC, glassnotes commented on demonstrations/tutorial_jax_transformations.py
> +.. meta::
Ah sorry, "table of contents". Just mean here that it needs to go on one of the gallery pages so people can find it :)

2021-03-31 19:36 UTC, glassnotes commented on demos_basics.rst
> +
A line will also have to be added down at the end of the list of demos below for it to appear in the list. (I can't seem to make a code suggestion for this, I guess since that part of the file was not changed)

2021-03-31 19:44 UTC, glassnotes approved these changes
@Thenerdstation looks good! Once the new suggestions are addressed and the demo thumbnail renders properly on the page, it's good to go :+1:

2021-03-31 19:44 UTC, glassnotes commented on demonstrations/tutorial_jax_transformations.py
> +# .. figure:: ../demonstrations/jax_logo/jaxjit.png
I love this drawing :laughing:

2021-03-31 19:44 UTC, glassnotes commented on demonstrations/tutorial_jax_transformations.py
> +# but on real QC hardware, calculating gradients can be really expensive and noisy.
```suggestion
# but on real quantum computing hardware, calculating gradients can be really expensive and noisy.

```
Just noticed that this acronym is not actually defined anywhere.

2021-03-31 19:44 UTC, glassnotes commented on demonstrations/tutorial_jax_transformations.py
> +# so if we want our JAX to mimic a real QC, we'll have to handle randomness ourselves.
```suggestion
# so if we want our JAX to mimic a real device, we'll have to handle randomness ourselves.

```

2021-04-01 03:37 UTC, Thenerdstation commented on demonstrations/tutorial_jax_transformations.py
> +# .. figure:: ../demonstrations/jax_logo/jaxjit.png
@co9olguy made it haha

2021-04-01 03:43 UTC, Thenerdstation commented
Everything built but I don't see it on the demo basics page...

2021-04-01 04:27 UTC, josh146 commented on demos_basics.rst
> +    :description: :doc:`demons/tutorial_jax_transformations`
```suggestion
    :description: :doc:`demos/tutorial_jax_transformations`
```

2021-04-01 04:37 UTC, josh146 commented on demos_basics.rst
> +    :figure: _static/jax_logo.png
```suggestion
    :figure: demonstrations/jax_logo/jax.png
```

2021-04-01 04:46 UTC, josh146 commented on demos_basics.rst
> +    :tags: jax
```suggestion
    :description: :doc:`demos/tutorial_jax_transformations`
    :tags: beginner
```

2021-04-01 04:57 UTC, josh146 commented
>Everything built but I don't see it on the demo basics page...

@Thenerdstation I got it working,

![image](https://user-images.githubusercontent.com/2959003/113245537-c0866300-92e9-11eb-8e0f-6ecf6d419ca9.png)

it was a combination of:

* a typo in the card link (Sphinx has a terrible habit where it will just not display non-existing links, rather than giving a build error)
* The JAX tag not yet existing - I temporarily swapped it for the `beginner` tag while troubleshooting 🤔 

We could make a new PR after this is merged to add in a JAX tag (this requires modifications to the CSS, HTML and JS, so likely out of scope to do that here)

2021-04-01 13:37 UTC, Thenerdstation commented
Awesome. Thank you josh!

2021-04-12 21:18 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +# QML is most useful for learning about quantum systems. For exampleL finding chemical
```suggestion
# QML is most useful for learning about quantum systems. For example, finding chemical 
```

2021-04-12 21:27 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +# ground states or learning to :doc:`sample thermal energy states </demos/tutorial_vqt>`.
```suggestion
# QML is most useful for learning about quantum systems. For example, 
# :doc:`finding chemical ground states </demos/tutorial_vqe>` 
# or learning to :doc:`sample thermal energy states </demos/tutorial_vqt>`.
```

2021-04-12 21:31 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +# including CPUs, GPUs, etc. JAX can compile it's computation to XLA via the ``jax.jit``
```suggestion
# including CPUs, GPUs, etc. JAX can compile its computation to XLA via the ``jax.jit`` 
```

2021-04-12 21:36 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +# Note: This example only applies if you are using ``jax.jit``. Otherwise, PennyLane
```suggestion
.. note::
     This example only applies if you are using ``jax.jit``. Otherwise, PennyLane 
```

2021-04-12 21:36 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +# automatically seeds and resets the random-number-generator for you on each call.
```suggestion
# .. note:: This example only applies if you are using ``jax.jit``. Otherwise, PennyLane 
# automatically seeds and resets the random-number-generator for you on each call.
```

2021-04-12 21:45 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +    tutorial_vqt Variation Quantum Thermalizer
```suggestion
    tutorial_vqt Variational Quantum Thermalizer
```

2021-04-12 21:46 UTC, co9olguy commented on demonstrations/tutorial_jax_transformations.py
> +# to make running batches of circuits much easier. Vmap essentially transforms a single quantum computer into
```suggestion
# to make running batches of circuits much easier. ``vmap`` essentially transforms a single quantum computer into
```

2021-04-12 21:47 UTC, co9olguy approved these changes

2021-04-12 21:52 UTC, merged