Fix non-qchem tutorials using the 'molecular_hamiltonian()' function
PennyLaneAI/qml pull request #243
Opened 2021-04-08 15:27 UTC by agran2018

The ``molecular_hamiltonian()`` function in the ``structure`` module was modified to take independently the list of the atomic symbols and the array with the nuclear coordinates that defines the molecular geometry.

This PR updates the following four non-qchem tutorials using this function.

1- VQE with parallel QPUs on Rigetti Forest
2- Accelerating VQEs with quantum natural gradient
3- Measurement optimization
4- Optimization using SPSA

2021-04-08 19:26 UTC, ixfoduap requested changes

2021-04-08 19:26 UTC, ixfoduap commented on demonstrations/spsa.py
> +h2_ham, num_qubits = qchem.molecular_hamiltonian(symbols, coordinates, name="h2")
Can we just not pass any name to keep this simpler? We never read the local file again, so there's no real use in giving it a name

2021-04-08 19:26 UTC, ixfoduap commented on demonstrations/tutorial_vqe_parallel.py
> +# the Hamiltonian.
```suggestion
# We do this by first reading the molecular geometry from the external file using the
# :func:`~.pennylane_qchem.qchem.read_structure` function and passing the atomic symbols
# and coordinates to :func:`~.pennylane_qchem.qchem.molecular_hamiltonian`.

```

2021-04-08 19:26 UTC, ixfoduap commented on demonstrations/tutorial_measurement_optimize.py
> +function to read the geometry of the molecule from a external file.
```suggestion
function to read the geometry of the molecule from an external file.

```

2021-04-08 19:26 UTC, ixfoduap commented on demonstrations/tutorial_measurement_optimize.py
> +H, num_qubits = qml.qchem.molecular_hamiltonian(symbols, coordinates, name="h2o")
Isn't this an unnecessary repetition of lines 156-157 above?

2021-04-08 19:26 UTC, ixfoduap commented on demonstrations/tutorial_vqe_qng.py
> +# built using the :func:`~.pennylane_qchem.qchem.molecular_hamiltonian` function.
```suggestion
# To construct our system Hamiltonian, we first read the molecular geometry from
# the external file :download:`h2.xyz </demonstrations/h2.xyz>` using the
# :func:`~.pennylane_qchem.qchem.read_structure` function (see more details in the
# :doc:`tutorial_quantum_chemistry` tutorial). The molecular Hamiltonian is then
# built using the :func:`~.pennylane_qchem.qchem.molecular_hamiltonian` function.
```

2021-04-08 19:26 UTC, ixfoduap commented on demonstrations/tutorial_vqe_qng.py
> +hamiltonian, qubits = qml.qchem.molecular_hamiltonian(symbols, coordinates, name="h2")
Can we get rid of `name`? This shouldn't be needed for the purpose of this tutorial

2021-04-08 19:32 UTC, agran2018 commented on demonstrations/tutorial_measurement_optimize.py
> +H, num_qubits = qml.qchem.molecular_hamiltonian(symbols, coordinates, name="h2o")
I think so. Was tempted to remove it but as it appears after 608 lines since the first time this is mentioned above it is probably useful to keep it to help the user keep track.

2021-04-08 20:51 UTC, agran2018 commented
Note: I have included in this PR a fix of a minor rendering issue we missed [HERE](https://github.com/PennyLaneAI/qml/pull/242) and have also updated the "Last updated" dates of the tutorials using the refactored ``molecular_hamiltonian()`` function.

2021-04-08 22:12 UTC, ixfoduap approved these changes

2021-04-09 01:36 UTC, antalszava commented on .circleci/config.yml
> +            - pip-v23f-{{ .Branch }}-{{ checksum "requirements.txt" }}
Hi @agran2018, these changes and the one in the `requirements.txt` were added to check how the CI performs with changes in PennyLane-Forest. They should be reverted before merging (can revert the commits using `git revert <commit hash>` where `<commit hash>` is the hash for the two commits added).

The Forest plugin error seems to have been resolved well with the changes from the `pre_v0_15_fixes` branch.

2021-04-14 17:14 UTC, josh146 commented on requirements.txt
> +git+https://github.com/rigetti/pennylane-forest.git@pre_v0_15_fixes
```suggestion
git+https://github.com/rigetti/pennylane-forest.git
```

2021-04-15 06:28 UTC, merged