[WIP] Adds demo on unitary designs
PennyLaneAI/qml pull request #252
Opened 2021-04-15 18:46 UTC by glassnotes

WIP. Companion demo to the Haar measure one.

TODO:
 - [ ] formal progression from spherical to unitary designs
 - [ ] description of Pauli/Clifford group
 - [ ] finalize computational experiment examples
 - [ ] conclusions

2021-05-18 20:42 UTC, glassnotes commented on requirements.txt
> +git+https://github.com/PennyLaneAI/pennylane.git@better-transforms
Note to self: revert this change once the transforms branch is merged in.

2021-05-19 04:57 UTC, josh146 commented on demonstrations/tutorial_unitary_designs.py
> +# it's a list of tapes, and we are doing something with the execution results.
Nice! Something like this?

```python

@qml.single_tape_transform
def add_noisy_operation_sequence(tape, damp_factor, depo_factor, flip_prob):
    """Add the noisy operation sequence to a tape prior to measurement"""
    for op in tape.operations:
        op.queue()

    noisy_operation_sequence(damp_factor, depo_factor, flip_prob)

    for m in tape.measurements:
        m.queue()


@qml.single_tape_transform
def return_state(tape):
    """Modify a tape to simply return the quantum state"""
    for op in tape.operations:
        op.queue()

    qml.state()


@qml.qnode_transform
def fidelity_comparison(qnode, damp_factor, depo_factor, flip_prob, single_qubit_cliffords):
    tape = return_state(qnode.qtape)

    ideal_tapes = []
    noisy_tapes = []

    for clifford in single_qubit_cliffords:
        # Set up the ideal tape
        twirled_tape = conjugate_with_clifford(tape, clifford)
        ideal_tapes.append(twirled_tape)

        # Set up the noisy tape
        noisy_tape = add_noisy_operation_sequence(tape, damp_factor, depo_factor, flip_prob)
        twirled_tape = conjugate_with_clifford(noisy_tape, clifford)
        noisy_tapes.append(twirled_tape)

    def fidelity_fn(res):
        # Use the results to compute the fidelities
        fidelities = []
        ideal_results = res[:len(ideal_tapes)]
        noisy_results = res[len(ideal_tapes):]

        for state_1, state_2 in zip(ideal_results, noisy_results):
            fidelities.append(fidelity(state_1[0], state_2[0]))

        return fidelities

    return ideal_tapes + noisy_tapes, fidelity_fn


@qml.qnode(dev)
def test_qnode():
    qml.SX(wires=0)
    return qml.expval(qml.PauliZ(0))

fidelity = fidelity_comparison(test_qnode)
fidelity(damp_factor, depo_factor, flip_prob, single_qubit_cliffords)
```

2021-05-19 16:00 UTC, glassnotes commented on demonstrations/tutorial_haar_measure.py
> +
```suggestion

```

2021-05-27 18:20 UTC, glassnotes commented on demonstrations/tutorial_unitary_designs.py
> +# it's a list of tapes, and we are doing something with the execution results.
Yes this is similar to what I was thinking. I played around with it a bit more and, given that we haven't quite ironed out everything with QNode transforms, I've rewritten it to use qfunc transforms instead. The result is really nice because it's a lot more modular, and for the most part eliminates the need for tapes except for within the quantum function transforms explicitly.

2021-05-27 18:25 UTC, josh146 commented on demonstrations/tutorial_unitary_designs.py
> +# it's a list of tapes, and we are doing something with the execution results.
Oh nice! I just had a look, I was super curious. It seems much more concise!

One question though: how come you made `apply_single_clifford(tape, clifford_string, inverse=False)` a tape transform, could it just be a simple qfunc? e.g., remove the decorator and the unused `tape` argument?

```python
def apply_single_clifford(clifford_string, inverse=False):
    for gate in clifford_string:
        if gate == 'H':
            qml.Hadamard(wires=0)
        else:
            if inverse:
                qml.PhaseShift(np.pi/2, wires=0)
            else:
                qml.PhaseShift(-np.pi/2, wires=0)
```

2021-05-27 18:26 UTC, josh146 commented on demonstrations/tutorial_unitary_designs.py
> +# it's a list of tapes, and we are doing something with the execution results.
I just deleted my comment because I was looking at the old build version, not the new one 🙈

2021-05-28 15:22 UTC, glassnotes commented on demonstrations/tutorial_unitary_designs.py
> +*Author: PennyLane dev team. Posted: XX May 2021. Last updated: XX May 2021.*
Note to self: update the date before merging.

2021-05-31 21:18 UTC, ixfoduap requested changes
Another outstanding tutorial, wow! :star_struck: 

The tutorial could go live as is after correcting a couple of typos. However, I am hoping it can get even better. My main comments are:

- I would like to see a short explanation/example of why designs work. How come we can get an exact answer by evaluating on only a few points?
-  I felt that the flow was broken in different parts, specially after a really, really great introduction. I think the tutorial may be trying to do too much (overly enthusiastic) and could benefit from a bit more focus and compactness
- The images in the beginning are so great! I wish there were more like this throughout

2021-05-31 21:18 UTC, ixfoduap commented on demonstrations/tutorial_unitary_designs.py
> +single_qubit_cliffords = [
Wait, I'm not sure I understand this. How exactly do the ways that X and Z can be transformed lead to these products of S and H defining the Clifford group?

2021-05-31 21:18 UTC, ixfoduap commented on demonstrations/tutorial_unitary_designs.py
> +# .. admonition:: Fun fact
This text is great, but I would remove the "fun fact" format and leave it as a normal paragraph

2021-05-31 21:18 UTC, ixfoduap commented on demonstrations/tutorial_unitary_designs.py
> +dev = qml.device("default.mixed", wires=1)
:star_struck: I'm always happy to see defaut.mixed being used :grin:

2021-05-31 21:18 UTC, ixfoduap commented on demonstrations/tutorial_unitary_designs.py
> +noisy_experiment = apply_noise(damp_factor, depo_factor, flip_prob)(ideal_experiment)
This is so beautiful! :heart_eyes:

2021-05-31 21:18 UTC, ixfoduap commented on demonstrations/tutorial_unitary_designs.py
> +            # We must manually apply the inverse as it is not yet supported on default.mixed
:crying_cat_face:

2021-05-31 21:18 UTC, ixfoduap commented on demonstrations/tutorial_unitary_designs.py
> +# of exact designs [#Dankert]_. It particular, it has been shown that
```suggestion
# of exact designs [#Dankert]_. In particular, it has been shown that
```

2021-05-31 21:18 UTC, ixfoduap commented on demonstrations/tutorial_unitary_designs.py
> +# distinction problem [#Ambainis]_.
State distinction instead of state discrimination? First time I hear this. Is it because discrimination is a loaded word?

2021-05-31 21:18 UTC, ixfoduap commented on demonstrations/tutorial_unitary_designs.py
> +# planes, bringing us full circle back to the Fano plane from which we began.
Full triangle :wink:

2021-06-01 13:15 UTC, glassnotes commented on demonstrations/tutorial_unitary_designs.py
> +:math:`k`-design for all :math:`k < t` as well!
I wasn't kidding about the overly-enthusiastic part! :sweat_smile:  But yes good point, I will tone it down :grin:

2021-06-01 13:17 UTC, glassnotes commented on demonstrations/tutorial_unitary_designs.py
> +# distinction problem [#Ambainis]_.
Ah it's just called "state distinction" in that reference and a couple others that refer to it as an application of 4-designs; I thought maybe it was a slightly different task than state discrimination? I will look into it :+1:

2021-06-01 13:17 UTC, glassnotes commented on demonstrations/tutorial_unitary_designs.py
> +# planes, bringing us full circle back to the Fano plane from which we began.
Love it :smiling_imp:

2021-06-01 13:18 UTC, glassnotes commented on demonstrations/tutorial_unitary_designs.py
> +noisy_experiment = apply_noise(damp_factor, depo_factor, flip_prob)(ideal_experiment)
I know :heart_eyes: Being able to use the transforms like this has streamlined the code so much, huge improvement over the original version.

2021-06-01 13:23 UTC, glassnotes commented on demonstrations/tutorial_unitary_designs.py
> +single_qubit_cliffords = [
These are just the 24 unique elements generated by H and S. We can see why there are 24 using the combinatorial argument above, but then it takes some work to generate the set. There are two approaches, one of which is to look at all possible ways that X and Z can be mapped to {+/-X, +/- Y, +/-Z}, and determine which Clifford performs each mapping. The other is simpler and is to just multiply together generators until you get 24 unique combinations.  In any case I'll work on improving this explanation :+1:

2021-06-01 13:24 UTC, glassnotes commented on demonstrations/tutorial_unitary_designs.py
> +
That's a good point. I'll work on putting an explicit example of a calculation with a spherical design, I think that will be really helpful for illustrating the point (and also help break up the long amount of text that comes before the main code example).

2021-06-01 18:25 UTC, glassnotes commented
> Another outstanding tutorial, wow! star_struck
> 
> The tutorial could go live as is after correcting a couple of typos. However, I am hoping it can get even better. My main comments are:
> 
>     * I would like to see a short explanation/example of why designs work. How come we can get an exact answer by evaluating on only a few points?
> 
>     * I felt that the flow was broken in different parts, specially after a really, really great introduction. I think the tutorial may be trying to do too much (overly enthusiastic) and could benefit from a bit more focus and compactness
> 
>     * The images in the beginning are so great! I wish there were more like this throughout

@ixfoduap ready for re-review. I've made the following major changes to address your comments:
 - added an example for the spherical designs
 - removed the section about complex projective designs (helps the demo get to the point faster, plus I wasn't actually doing anything with them; I've left the idea in one of the callout boxes)
 - added a bit more intuition behind how the Clifford group works and is constructed

In terms of the definitions, it feels too hand-wavy if I just omit them; it's important to show that `=` sign between the finite sum and the integral. But now that I've removed complex projective design, each definition is preceded by some motivation and associated with an explicit example, which hopefully provides enough detail to grasp the concept even if some of the formal math is fuzzy.

2021-06-01 18:27 UTC, glassnotes commented on demonstrations/tutorial_unitary_designs.py
> +We see from these illustrations that spherical designs are sets of
Haven't said exactly this, but tried to rework the contents.

2021-06-01 18:28 UTC, glassnotes commented on demonstrations/tutorial_unitary_designs.py
> +#
This could be a nice spot for another graphic that shows a cube and a dodecahedron; the earlier graphic can be modified so that they are swapped out for an octahedron and icosahedron respectively. Allows us to show more examples of shapes without cluttering the original drawing.

2021-06-01 18:29 UTC, glassnotes commented on demonstrations/tutorial_unitary_designs.py
> +plt.hist(fidelities, bins=20)
I'm considering to remove this histogram - it's neat to see the distribution, but I don't actually use any results about the distribution save for the average.

2021-06-01 18:30 UTC, glassnotes commented on demonstrations/tutorial_unitary_designs.py
> +# distinction problem [#Ambainis]_.
```suggestion
# discrimination problem [#Ambainis]_.
```

2021-06-01 18:30 UTC, glassnotes commented on demonstrations/tutorial_unitary_designs.py
> +*Author: PennyLane dev team. Posted: XX May 2021. Last updated: XX May 2021.*
```suggestion
*Author: PennyLane dev team. Posted: XX June 2021. Last updated: XX June 2021.*
```

2021-06-02 17:55 UTC, ixfoduap commented on demonstrations/tutorial_unitary_designs.py
> +unit sphere, :math:`S(R^d)`. One can do so by integrating that function over the
Consider using "we" instead of "one" for a tutorial.

2021-06-02 17:55 UTC, ixfoduap commented on demonstrations/tutorial_unitary_designs.py
> +One could alternatively approximate the average by sampling thousands of points
Great paragraph! For me it makes the connection with Monte Carlo integration very clear.

In fact, it makes me think that t-designs are a form of quasi-Monte Carlo, which involve strategies that perform the integration over a fixed set of points, e.g., evenly spaced. The magic here is that they can be chosen so the result is exact

2021-06-02 17:55 UTC, ixfoduap commented on demonstrations/tutorial_unitary_designs.py
> +points and thus more complex configurations for the design.  Spherical designs
```suggestion
points and thus more intricate configurations for the design.  Spherical designs
```
or other synonym to avoid repeated use of complex

2021-06-02 17:55 UTC, ixfoduap commented on demonstrations/tutorial_unitary_designs.py
> +# The golden ratio
:star_struck:

2021-06-02 17:55 UTC, ixfoduap commented on demonstrations/tutorial_unitary_designs.py
> +# This is exactly the value we expect. What happens if we try to do this using
LOOOOOVE this example!

2021-06-02 17:55 UTC, ixfoduap commented on demonstrations/tutorial_unitary_designs.py
> +# We've demonstrated how spherical are sets of evenly-spaced points on a sphere
Revise this sentence

2021-06-02 17:55 UTC, ixfoduap commented on demonstrations/tutorial_unitary_designs.py
> +# do so as well (in group theory terms, the single-qubit Clifford group is
Consider putting the sentence in parenthesis as a regular new sentence, without parenthesis

2021-06-02 17:55 UTC, ixfoduap commented on demonstrations/tutorial_unitary_designs.py
> +# While we do not explore it here, the multi-qubit Clifford can also be
```suggestion
# The multi-qubit Clifford can also be
```

2021-06-02 17:59 UTC, ixfoduap requested changes
I really love the changes!

My only remaining suggestions:
- The tutorial could use more images like the ones appearing in the beginning. Maybe you're working on them already?
- I think you commented that it may be a good idea to remove the plot with the distribution of averages. I agree, I think it's best to just quote the average and standard deviation

2021-06-02 21:26 UTC, glassnotes commented
> I really love the changes!
> 
> My only remaining suggestions:
> 
>     * The tutorial could use more images like the ones appearing in the beginning. Maybe you're working on them already?
> 
>     * I think you commented that it may be a good idea to remove the plot with the distribution of averages. I agree, I think it's best to just quote the average and standard deviation

Done, and done! Added two new colourful graphics. Let me know if you think of any other places where one could be nice.

2021-06-03 13:51 UTC, glassnotes commented on requirements.txt
> +git+https://github.com/PennyLaneAI/pennylane.git@better-transforms
```suggestion
git+https://github.com/PennyLaneAI/pennylane.git@master
```

2021-06-04 13:25 UTC, ixfoduap commented on demonstrations/tutorial_unitary_designs.py
> +# saw how they can be used as a short cut to evaluate the average of a
```suggestion
# saw how they can be used as a shortcut to evaluate the average of a
```
I think short cut is used too, but I've always thought of it as a single word

2021-06-04 13:27 UTC, ixfoduap approved these changes
:shipit:

2021-06-04 14:39 UTC, glassnotes commented on demonstrations/tutorial_unitary_designs.py
> +# saw how they can be used as a short cut to evaluate the average of a
Oh you're right! :exploding_head:

2021-06-07 14:04 UTC, merged