[Not ready to Merge yet] tutorial on studying chemical reactions using VQE
PennyLaneAI/qml pull request #261
Opened 2021-04-26 12:36 UTC by varunrishi

A tutorial on to using Pennylane to study chemical reactions and constructing potential energy surfaces.
[ Work-In-Progress ]

**Title: Studying Chemical reactions and constructing potential energy surfaces using VQE**

**Summary: A basic introduction on how to study chemical reactions using quantum computing algorithms such as VQE. We introduce the idea of potential energy surfaces (PES) and then show how to construct them for diatomic bond dissociations and  a simple hydrogen exchange reaction. Finally, it is show that useful reaction parameters such as activation energy barrier and rate constant could be calculated from the PES**

2021-04-28 22:43 UTC, ixfoduap requested changes
Quick review of the introduction. Will continue review tomorrow

2021-04-28 22:43 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +Chemical reaction is another name for transformation of molecules - breaking and forming of bonds - accompanied with energy cost. This energy cost determines the feasibility of a particular transform
```suggestion
The term chemical reaction is another name for the transformation of molecules -- breaking and forming of bonds -- and their associated energy cost. The energy cost determines the feasibility of a particular transformation amongst many different alternate possibilities. The field of computational chemistry has several theoretical methods for modelling chemical reactions. In this tutorial, you will learn how to use PennyLane to simulate chemical reactions. 
```

2021-04-28 22:43 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +Chemical reaction is another name for transformation of molecules - breaking and forming of bonds - accompanied with energy cost. This energy cost determines the feasibility of a particular transform
I'm not sure what python editor you're using, but it is treating every paragraph as a single line. This makes it very difficult to read the text and to add suggestions. Instead, you want to set up your editor such that it starts a new line after a fixed number of characters, usually 100

2021-04-28 22:43 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +Quantum computing aims to revolutionalize this exploration of chemical reactions. We could possibly build the exact energy landscapes and thus unearth the most feasible routes for any general chemica
I think this paragraph can be removed

2021-04-28 22:43 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +In a previous tutorial, we looked at how a hybrid quantum-classical algorithm, Variational Quantum Eigensolver (VQE), [#peruzzo2014]_ is used to compute molecular energies which are the expectation v
You can add a link to a previous tutorial using :doc:`tutorial_vqe`

2021-04-28 22:43 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +In a previous tutorial, we looked at how a hybrid quantum-classical algorithm, Variational Quantum Eigensolver (VQE), [#peruzzo2014]_ is used to compute molecular energies which are the expectation v
```suggestion
In a previous tutorial, we looked at how the variational quantum eigensolver (VQE), [#peruzzo2014]_ can be used to compute molecular energies. Here, we show how VQE can be used to construct potential energy surfaces (PESs) for any general molecular transformation. This lends the way to the calculation of important quantities such as activation energy barriers, reaction energies, and reaction rates. As illustrative examples, we use tools implemented in PennyLane to study diatomic bond dissociation and reactions involving the exchange of hydrogen atoms. Let's get started! 
```

2021-04-28 22:43 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +In a previous tutorial, we looked at how a hybrid quantum-classical algorithm, Variational Quantum Eigensolver (VQE), [#peruzzo2014]_ is used to compute molecular energies which are the expectation v
Note that the official spelling is PennyLane, not Pennylane

2021-04-28 22:43 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +r"""
Note that checks are not passing. It's best practice that they are always passing before asking for reviews!

2021-04-28 22:43 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +=======================
```suggestion
Modeling chemical reactions using VQE
==============================
```

2021-04-28 22:43 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +An illustration of potential energy surface of H-H bond dissociation for hydrogen molecule. On the y-axis is the total molecular energy and x-axis is the H-H bond distance. By looking at this curve,
```suggestion
An illustration of the potential energy surface of bond dissociation for the hydrogen molecule. On the y-axis is the total molecular energy and x-axis is the H-H bond distance. By looking at this curve we can estimate the H-H equilibrium bond distance and the energy required to break the H-H bond.   
```

You can turn this into a caption for the figure by indenting all text to be aligned with the other figure attributes, like :width: and :align:

2021-04-29 20:10 UTC, ixfoduap requested changes
The overall content of the tutorial is great! It's very useful to finally have an explanation of how to build a PES and use it to study chemical reactions.

The actual execution needs more work, both on the text and code. I've left suggestions for improvements. 

I still have to review from line 380 onwards

2021-04-29 20:10 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +    # optimization of the gate parameters.
```suggestion
##############################################################################
# We evaluate the cost function and use the gradient descent algorithm in an iterative
# optimization of the gate parameters.
```

2021-04-29 20:10 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +    print("At bond distance \n", r_HH)
As above, we don't want a kabillion printouts. I think this whole optimization can happen without printing anything

2021-04-29 20:10 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# which is also the reaction coordinate and thus, we have the potential energy curve for
What is a reaction coordinate? This hasn't been explained so far. Either spend some time explaining it (ideal), or add a link

2021-04-29 20:10 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# .. figure:: /demonstrations/vqe_bond_dissociation/h3_mol_movie.gif
Awesome! 

Is it possible to use a white background? All this black clashes with the general style of the pennylane website

2021-04-29 20:10 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +        qml.PauliX(2)
Same comment as in previous circuit

2021-04-29 20:10 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +        # Prepare the HF state |111000> by flipping the qubits 0, 1 and 2
Since this circuit is built using the same principles as the first one, you can remove basically all of the comments to make the code cleaner

2021-04-29 20:10 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +    opt = qml.GradientDescentOptimizer(stepsize=0.4)
remove vertical spaces, i.e., these can fit in three lines

2021-04-29 20:10 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +        # define your convergence criteria, we choose modest value of 1E-6 Ha
Here and in the following circuit, you can remove a lot of this vertical white space. Also, for a tutorial you don't need to print the time

2021-04-29 20:10 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +    dcircuit(params)
What is the purpose of this? I believe you can just remove it, same in following circuit

2021-04-29 20:10 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +ax.plot(r, vqe_energy, label="VQE(S+D)")
```suggestion
ax.plot(r, vqe_energy)
```

2021-04-29 21:49 UTC, ixfoduap requested changes
In my opinion, the last part of the tutorial is the most important one, yet many of the crucial calculations are not being explicitly performed. 

Remember, one of the main goals of a tutorial is to give readers a template of code that they can basically copy-paste to solve their own specific problems.

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# The activation energy barrier is defined as the difference between the
This paragraph should go right after the first sentences that mention energy barriers for the first time

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# and the transition state (maxima). VQE(S+D) reproduces the exact result in the small
Using VQE(S+D) is not standard, so I suggest removing it. You can just refer to it as "our VQE circuit"

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# basis (STO-3G). The plot below compares the performance of many methods with each other
```suggestion
# basis (STO-3G). The plot below compares the performance of different methods.
```

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# the quantum chemistry methods, CCSD and CISD.
```suggestion
# The PEC obtained from the quantum algorithm overlaps with
# the quantum chemistry methods, CCSD and CISD.
```
And you should add links to CCSD and CISD, since these haven't been defined and are not familiar to all readers

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# DOCI stands for Doubly occupied CI where only pure pair excitations are allowed
It's great that you explored DOCI, but I don't think it's helpful to mention it in this tutorial. I advise that you remove it from the text and plot

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# using tools in Pennylane used here such as qml.DoubleExcitation and qml.SingleExcitation.
Remove this

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# transition state (:math:`H--H--H`).
I'm not sure what H--H--H means. It will be clearer to also explain it in words, e.g.,  the transition state corresponding to a linear arrangement of the atoms with two hydrogen bonds formed

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# In this case, VQE(S+D) reproduces the exact theoretical result in the
Maybe good to explain how do you know what the exact theoretical result is

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# .. math:: E_{Activation Barrier} = 0.0274 Ha = 17.24 Kcal/mol
It is really important to explain to the readers how to compute this number! You really need to add some code that computes this calue

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# that would hopefully become available in future quantum computers.
You can remove this. The tutorial should be focused on learning key concepts and used as a reference for coding such problems using pennylane

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# in larger basis, triple and quadruple zeta basis or higher, to reach basis set
Again, basis sets haven't been defined and most readers, including myself, won't know what you mean by triple and quadruple zeta bases are. It's enough to add a link to such basis sets

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# So, in principle, if we know the constant (A) we could calculate the rate of the reaction.
In my mind, this should be the central goal of the tutorial: how do I compute the reaction rate? Yet you're just showing the formula, not actually performing the calculation.

Really important to write code that computes this reaction rate.

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# So, in principle, if we know the constant (A) we could calculate the rate of the reaction.
Also: how do we find the value of the constant A? This seems really important but not really addressed in the tutorial

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +#
remove this white space

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +#     :width: 50%
You can make the plot bigger, right now it is a bit difficult to read

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# .. math:: E_{Activation Barrier} = E_{TS} - E_{Reactant}
_{ActivationBarrier} is a very long subscript that looks quite clunky. Can we just abbreviate it to _{AB}? And for reactant just use _{R}?

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# constitutes a multireference problem. [#purvis1983]_ It needs two different
I don't understand this sentence

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# HF Slater determinants to qualitatively describe the full potential energy suface
good to use Hartree-Fock here; it's been a while since we last used HF

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# for one half of the PES while another determinant is good reference for rest of PES.
Then you can say that the formation of the BeH2 moelcule from a single Be atom and H2 molecule is a good example of such a multi-reference problem

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# Here, we construct the potential energy surface for this reaction and see how
Again, you need to show us how to actually do this, with code! This is not a paper, but rather a detailed guide on how to use pennylane to perform these calculations. You need to show what those calculations are!

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# To figure out the reaction coordinate or the trajectory of
Again, this tutorial needs a short definition of what a reaction coordinate is

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# approach of :math:`H_2` to Beryllium atom, we refer to the work by
```suggestion
# approach of the :math:`H_2` molecule to the Beryllium atom, we refer to the work by
```

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# Coe et al. [#coe2012]_
Nice to add this reference! Shows it's an important problem, even recently

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# and :math:`x \in [1, 4]`.
```suggestion
# We fix the Beryllium atom at the origin and the coordinates for the hydrogen atoms are given by
#  :math:`(x, y, 0)` and :math:`(x, −y, 0)`, where :math:`y = 2.54 − 0.46x`
# and :math:`x \in [1, 4]`. All distances are in Bohr.
```

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# :math:`6` spin MOs with core electrons frozen.
```suggestion
# The generation of the PES is straightforward and follows from our previous examples.
# For the sake of saving computational cost, we try a smaller active space with a total of
# :math:`6` spin-orbitals with core electrons frozen.
```

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# choosing a smaller active space - 6 spin MOs
```suggestion
# choosing a smaller active space of 6 spin-orbitals
```

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +    def circuit(params, wires):
Side note: 
This exact circuit may be how we implement the new UCCSD template

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +
I think it's worth commenting more on why this plot looks so different, with a sharp change around the maximum. Why is this the case? What does it have to do with this being a multi-reference problem?

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# as CASCI, CCSD and CISD. we can see VQE(S+D) does really well for both sides
There are too many techniques being compared here, which makes the plot look messy. Let's just use VQE, FCI, and CASCI. CASCI needs to be explained a bit more, again, just a link is probably enough

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# geometry.
This last sentence is very confusing, please revise

2021-04-29 21:49 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +#
The tutorial needs a short conclusion. What did we learn and why is it important?

2021-05-07 20:34 UTC, ixfoduap requested changes
The tutorial is in better shape, but it still needs a lot of work to meet the high standards expected from everything we do at Xanadu. Please address my comments with utmost urgency so that we can finally open the PR for other reviewers as soon as possible

2021-05-07 20:34 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# of the system at the dissociation limit (farthest right of the curve)
```suggestion
# of the system at the dissociation limit, where the atoms are far apart and 
the total energy plateaus to a constant: the sum of each atom's individual energy.
```

2021-05-07 20:34 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# (the difference in energy at equilibrium and energy at dissociation limit)
You just defined the bond dissociation energy above, no need to repeat it here

2021-05-07 20:34 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +vqe_energy_disoc = vqe_energy[-1]
can remove vqe from the name, i.e., just `energy_equil`

2021-05-07 20:34 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +bond_dissociation_energy_kcal = np.multiply(bond_dissociation_energy, 627.5)
why not just `vqe_energy_disoc - vqe_energy_equil` and `bond_dissociation_energy * 627.5`?

2021-05-07 20:34 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# extrapolating to the complete basis set (CBS) limit. [#motta2020]_
No need to include the acronyms (F12) and (CBS) if they won't be used again

2021-05-07 20:34 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# .. math:: H_2 + H \rightarrow H + H_2
```suggestion
# .. math:: H_2 + H \rightarrow H + H_2.
```

2021-05-07 20:34 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# occupation number representation is :math:`|111000\rangle`. As there is an unpaired
```suggestion
# This means it is a :math:`6` qubit problem and the Hartree-Fock state in
# occupation number representation is :math:`|111000\rangle`. As there is an unpaired
```

2021-05-07 20:34 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +multiplicity = 2
Can remove all this

2021-05-07 20:34 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# Then we plot the energy as a function of distance between atoms :math:`1` and :math:`2`
```suggestion
# Then we plot the energy as a function of distance between atoms :math:`1` and :math:`2`,
```

2021-05-07 20:34 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# and thus, we have the potential energy curve for
```suggestion
# which is also the `reaction coordinate <https://en.wikipedia.org/wiki/Reaction_coordinate>`_,
# and thus we have the potential energy curve for
```

2021-05-07 20:34 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# A model multireference problem: :math:`Be + H_{2} \rightarrow BeH_{2}`
Having re-read the tutorial, I agree that we should probably remove this BeH2 example. The tutorial is quite long as it is and the fact that this takes so long to run is a major drawback. Instead, maybe we can just add the nice plot at the end and comment on the meaning of a multi-reference problem

2021-05-07 20:34 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# and products.
```suggestion
# The utility of potential energy surfaces lies in estimating
# reaction energies and activation energy barriers, as well as the
# geometric configurations of key reactants, intermediates,
# `transition states <https://en.wikipedia.org/wiki/Transition_state>`_
# and products.
```

2021-05-07 20:34 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# a good estimate of the energies of the reactants (minima :math:`1`), products (minima :math:`2`)
```suggestion
# a good estimate of the energies of the reactants (minima :math:`1`), products (minima :math:`2`),
```

2021-05-07 20:34 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# .. math:: E_{Activation Barrier} = E_{TS} - E_{Reactant}
Why hasn't this been addressed? It's been 8 days since the comment was made

2021-05-07 20:34 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +
```suggestion
```

2021-05-07 20:34 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +activation_energy_kcal = np.multiply(activation_energy, 627.5)
Again, you should be able to just use `-` and `*`

2021-05-07 20:34 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# .. math:: k = Ae^{-{E_{Activation Barrier}}/RT}
```suggestion
# .. math:: k = Ae^{-{E_{Activation Barrier}}/RT}.
```

2021-05-07 20:34 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# So, in principle, if we know the constant (A) we could calculate the rate of the reaction
```suggestion
# So, in principle, if we know the constant (A) we could calculate the rate of the reaction,
```

2021-05-07 20:34 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +#
again, why hasn't this been done?

2021-05-07 20:34 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# problems. However, there exist situations where more than one different reference states are
```suggestion
# problems. However, there exist situations where more than one reference state is
```

2021-05-07 20:34 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# for the transformation. This is to say that one Slater Determinant is a good HF reference
```suggestion
# for the transformation. This is to say that one Slater determinant is a good reference
```

2021-05-07 20:34 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +    # Begin VQE iteration. The max number of iterations is set to 150
I suggest keeping the code that build the Hamiltonian and defines the circuit, but don't run any optimization. Instead just say that we can run the optimization as before, but we omit it since it takes long to run. Then jump to the plot

2021-05-07 20:34 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# results that match conventional quantum chemistry methods.
```suggestion
# their potential energy curves. We calculated the bond dissociation energy,
# activation energy, and bond lengths for each case.
# We also saw how quantum computing algorithms such as VQE can in principle
# provide results that match conventional quantum chemistry methods for these systems.
```

2021-05-10 08:55 UTC, varunrishi commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# results that match conventional quantum chemistry methods.
We are not calculating "the bond dissociation energy, activation energy, and bond lengths for **each case**". We cannot. We calculate what is relevant in each case

2021-05-10 08:59 UTC, varunrishi commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +
JM suggests [skip CI]

2021-05-10 11:14 UTC, varunrishi commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +doubly-excited state :math:`|0011\rangle`. These are the only states out of :math:`2^4 (=16)`
It is important to explain this here in the first section. Edited the text to add the justification suggested.

2021-05-10 12:05 UTC, varunrishi commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +vqe_energy_disoc = vqe_energy[-1]
agree

2021-05-10 12:12 UTC, varunrishi commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +multiplicity = 2
multiplicity needs to be specified here I guess. Others have been removed

2021-05-12 14:50 UTC, glassnotes requested changes
@varunrishi this is a cool tutorial! :rocket: The underlying story is clear, and this is quite a neat application of PL and the VQE. I've left a number of comments throughout, please let me know if you have any questions.

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +and transition states are the hill peaks to climb.
```suggestion
and transition states are the peaks.
```

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +Potential Energy Surfaces: Hills to die and be reborn
Suggest to rephrase or leave title as "Potential Energy Surfaces".

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +of all reactions.
```suggestion
of all reactions:
```

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +Using a minimal basis set (STO-3G), this system can be described by :math:`2` electrons in :math:`4`
Would be helpful to add link to reference on STO-3G

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +energetically lowest orbitals are occupied and rest two are unccupied. To form the complete basis of
```suggestion
spin-orbitals. When mapped to a qubit representation, we need a total of four qubits to represent it. 
The Hartree-Fock (HF) ground state is  represented as :math:`|1100\rangle`, where the two
lowest-energy orbitals are occupied, and the remaining two are unoccupied. To form the complete basis of
```
Also consider adding link to reference about the Hartree-Fock state.

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +there are two electrons in this system, single and double excitations suffice. The singly-excited
```suggestion
states, we consider excitations of the HF state that conserve the spin. In this case, where 
there are two electrons, single and double excitations suffice. The singly-excited 
```

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +the expansion coefficients would change as the reaction proceeds and the  system moves figuratively
```suggestion
the expansion coefficients would change as the reaction proceeds and the  system moves around (figuratively) 
```

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# We build the VQE circuit by first
I felt there is a conceptual jump here. What I imagined, from the previous paragraph, is that we'd set up some function to compute the energy and evaluate is over points on a "grid" (I guess a line in this case since it's just one distance being varied). Instead it goes right to the VQE - is the VQE what's being used to compute the energy for each bond distance? If so, add some sentences to link the two ideas together.

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# double excitation gates which use the Givens rotations. This approach is similar to
Introduce Givens rotations conceptually, or add a reference.

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# the Unitary Coupled Cluster (UCCSD) approach often used.
Add reference to UCCSD.

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# :class:`~.ExpvalCost` class.
```suggestion
# :class:`~.ExpvalCost`.
```

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# For the problems dicussed here, we use gradient descent optimizer to optimize
```suggestion
# For the problems discussed here, we use gradient descent to optimize
```

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# i.e. start from the HF state as the approximation to the exact state.
```suggestion
# i.e., start from the HF state as the approximation to the exact state.
```

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# This process is repeated till convergence.
```suggestion
# This process is repeated until convergence.
```
Recommend to state the convergence criteria here.

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +    # get all the singles and doubles excitations
Oh cool, I didn't know there was such a function! :smile: 

The results, `singles` and `doubles` don't appear to be used later on in the function; are they being used to inform the contents of `circuit`? If so I recommend to take this part out of the main loop and discuss it separately earlier on, then explain how that fits into `circuit`.

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +    print("Hamiltonian is ", H)
Printing the Hamiltonian every time makes the output quite extensive; suggest to just print the Hamiltonian once and explain that the coefficients will change but the structure won't, and  and then just show the outputs of the optimization protocol after this code block.

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +r = np.arange(0.5, 5.0, 0.1)
This is used in the for loop earlier to vary the internuclear distance; suggest to save it as a variable earlier on, and use it in both the previous code block as well as here.

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +plt.show()
Nice! :tada:

Could be nice to relate back to the image at the beginning.

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# This is a simple potential energy surface (or more appropriately a potential energy curve) for
```suggestion
# This is a simple potential energy surface (or more appropriately, a potential energy curve) for
```

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# the dissociation of hydrogen molecule into two hydrogen atoms.
```suggestion
# the dissociation of a hydrogen molecule into two hydrogen atoms.
```

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# us the bond length:
```suggestion
# us the bond length---
```

(Can't remember if it's three - or two - in markdown, but this may be a better place for an emdash rather than a colon.

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# the total energy plateaus to a constant: the sum of each atom's individual energy.
Suggest to rework and streamline this section, I found it a bit hard to parse. Maybe focus on using the present example to illustrate the idea.

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# by using bigger basis sets and extrapolating to the complete basis set limit. [#motta2020]_
```suggestion
# by using bigger basis sets and extrapolating to the complete basis set limit [#motta2020]_.
```

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# We construct the PES for a simple hydrogen exchange reaction
Add a little more preamble here; "Having now worked out the simplest case, let's explore a slightly more complex reaction, the hydrogen exchange reaction"... or something like this.

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# this system consists of :math:`3` electrons in :math:`6` spin molecular orbitals.
```suggestion
# this system consists of :math:`3` electrons in :math:`6` molecular spin orbitals.
```
(not sure about this one, ignore if suggestion is incorrect)

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# Then we setup the PES loop, incrementing the :math:`H(1)-H(2)` distance from :math:`1.0`
Recommend to ust ccall them the "first H" and "second H" since I don't think this notation has been used before.

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# :class:`~.BasisState` class to construct the HF state in this case.
```suggestion
# to :math:`3.0` Bohrs in steps of :math:`0.1` Bohr. We use PennyLane's
# :class:`~.BasisState` operation to construct the HF state in this case.
```

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +    vqe_energy.append(energy)
To keep things more streamlined, suggest to just print a table with the final output energy, and the distance between the Hs instead of the per-iteration data.

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +#
```suggestion

```

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +r = np.arange(1.0, 3.0, 0.1)
Same comment here regarding fixing a variable earlier for the range of distances.

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +##############################################################################
Add some comments on the output plot - why are there two peaks? What does the maximum in between correspond to?

[EDIT:] I see this is literally in the next paragraph; but still suggest to add those details here so it can be immediately related to the plot.

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +#
```suggestion

```

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# .. math:: E_{a} = 0.0274 Ha = 17.24 Kcal/mol
Can the units here be made "regular" text, instead of math mode?

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# In this case, the activation energy barrier is
```suggestion
# In the case of the hydrogen exchange reaction, the activation energy barrier is
```

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# The reaction rate constant (k) has an exponential dependence on the activation energy barrier
```suggestion
# The reaction rate constant (:math:`k`) has an exponential dependence on the activation energy barrier
```

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# So, in principle, if we know the constant (A) we could calculate the rate of the reaction,
```suggestion
# So, in principle, if we know the constant (:math:`A`) we could calculate the rate of the reaction,
```

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# reaction.
I got a bit confused in this sentence by how all the quantities are related. Would it read fine with the second part ("which depends on the rate constant, the concentration...") removed?

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# The PEC obtained from the quantum algorithm (VQE) overlaps with
This seems important; is there anything more to say about this (after the figure?).

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# .. figure:: /demonstrations/vqe_bond_dissociation/h3_comparison.png
The axis labels here are quite huge; there is also the H(1) - H(2) notation I mentioned above, so maybe since it's used here, it is better to define it more clearly when it is introduced earlier.

2021-05-12 14:50 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# A model multireference problem: :math:`Be + H_{2} \rightarrow BeH_{2}`
Yes, usually we like to keep the executable demo build time to < 10 minutes. Does this example make up most of the 19 minutes?

I agree with @ixfoduap though. There is also a jump in conceptual complexity that I feel requires more explanation, which will increase the reading length, so may be better to just mention it as a potential application and add some references.

2021-05-13 17:28 UTC, varunrishi commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +   tutorial_vqe
I did not understand this comment. There is a title for the tutorial.

2021-05-13 19:06 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +   tutorial_vqe
In order to link to related tutorials, the lines have to be formatted like the one in the line below for `tutorial_vqe_parallel`. The format is

```
    tutorial_x Title of tutorial X
```

The line for `tutorial_vqe` is missing the tutorial name.

2021-05-14 08:14 UTC, varunrishi commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# this system consists of :math:`3` electrons in :math:`6` spin molecular orbitals.
spin molecular orbital is the right way to refer to it

2021-05-14 08:20 UTC, varunrishi commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# reaction.
Thanks, too many new things introduced. Have removed them now

2021-05-14 10:08 UTC, varunrishi commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# The PEC obtained from the quantum algorithm (VQE) overlaps with
Have added more text as an explanation

2021-05-19 15:09 UTC, glassnotes requested changes
Changes are looking good @varunrishi ! Have left mostly wording suggestions and caught typos this time. 

I noted a couple places in the code where you could take stuff out of loops, but nothing that I think will provide any significant decrease in run time. Some options could be to decrease the range of H-H distance in the first example to around 4.4-4.5 instead of 5, and/or increase the spacing between points for both examples so that fewer instances are run (however, the resulting plots would not be as nice :disappointed: )

2021-05-19 15:09 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +#
```suggestion
# ground state for all points on the potential energy surface:
#
# .. math:: \langle \Psi_{HF}| \Psi_{exact}\rangle \simeq 1.
#
```

2021-05-19 15:09 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# A symmetric approach of :math:`H_2` to :math:`Be` atom to form :math:`BeH_2`
```suggestion
# A symmetric approach of two hydrogen atoms to a :math:`Be` atom to form :math:`BeH_2`
```
(?)

2021-05-19 15:09 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# Let us first understand the problem in more detail. Once we have solved the mean-field HF
Add reference link for "mean-field"

2021-05-19 15:09 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# for one half of the PES while another is good reference for the rest of PES. [#purvis1983]_
```suggestion
# for one half of the PES while another is good reference for the rest of PES [#purvis1983]_.
```

2021-05-19 15:09 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# approach of the :math:`H_2` molecule to the Beryllium atom, we refer to the work by
```suggestion
# approach of the :math:`H_2` molecule to the :math:`Be` atom, we refer to the work by
```

2021-05-19 15:09 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# We fix the Beryllium atom at the origin and the coordinates for the hydrogen atoms
```suggestion
# We fix the :math:`Be` atom at the origin and the coordinates for the hydrogen atoms
```

2021-05-19 15:09 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# Coe et al. [#coe2012]_
```suggestion
# Coe et al. [#coe2012]_.
```

2021-05-19 15:09 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# the performance of VQE with Full CI results.
```suggestion
# the performance of VQE with FCI results.
```

2021-05-19 15:09 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# The performance of VQE depends on the active space chosen i.e. the number of electrons and
```suggestion
# The performance of VQE depends on the active space chosen, i.e., the number of electrons and
```

2021-05-19 15:09 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# the VQE results when the number of active orbitals is constrained to :math:`3` spatial orbitals
```suggestion
# the VQE results when the number of active orbitals is constrained to :math:`3` spatial orbitals,
```

2021-05-19 15:09 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# which is equal to :math:`6` spin orbitals. As a simple exercise, try increasing
```suggestion
# which is equal to :math:`6` spin orbitals. As an additional exercise, try increasing
```

2021-05-19 15:09 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +#
```suggestion
# reproduce the FCI result shown below if we increase the active orbitals to include
# all the unoccupied orbitals, i.e., 12 spin orbitals in total?
#
```

2021-05-19 15:09 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +#     :align: center
Decrease size of font in axis labels.

2021-05-19 21:11 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +    the variational quantum eigensolver algorithm in PennyLane.
```suggestion
    :property="og:description": Construct potential energy surfaces for chemical reactions
```

2021-05-19 21:11 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +In a previous tutorial on :doc:`Variational Quantum Eigensolver (VQE) </demos/tutorial_vqe>`,
```suggestion
In a previous tutorial on the :doc:`Variational Quantum Eigensolver (VQE) </demos/tutorial_vqe>`, 
```

2021-05-19 21:11 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +electrons and thus move much slowly, allowing us to decouple their motion. This is known as the
```suggestion
electrons and thus move more slowly, allowing us to decouple their motion. This is known as the
```

2021-05-20 02:25 UTC, agran2018 requested changes
Thank you @varunrishi! I have left some comments. I will continue reviewing it tomorrow morning.

2021-05-20 02:25 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +:math:`n`-dimensional plot of the energy with the respect to the degrees of freedom. It gives us a
Comment on the paragraph above. Perhaps it could be rephrase it. 

For example,

The concept originates from the fact that since the electrons are much lighter than the nuclei, they will instantaneously follow the motion of the nuclei while remaining always in the same state of the electronic Hamiltonian. This is known as the `Born-Oppenheimer approximation <https://en.wikipedia.org/wiki/Born–Oppenheimer_approximation>`_ which allows us to write the molecule's wave function as the product of the electronic and nuclear wave functions. The electronic wave function satisfies the Schrödinger equation

.. math:: H_{e}(R) \Psi(r) = E(R) \Psi(r),

where the :math:`H_{e}(R)` and :math:`E(R)` are, respectively, the electronic Hamiltonian and the total energy which depend on the frozen set of nuclear coordinates :math:`R`. The n-dimensional surface describing the dependence of the electronic energy :math:`E(R)` on the nuclear coordinates is refer to as the potential energy surface (PES). PES can be explored to understand chemical reactions. For example, by locating stable molecules is possible to identify reactants and products while the local minima and transition states mark the routes of possible reaction paths.

2021-05-20 18:06 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# Once we have the converged VQE energy at the specified internuclear distance, we
```suggestion
# Once we have the converged VQE energy at the specified internuclear distance, we move on to the next point of the PES and repeat the entire process using the previously optimized circuit parameters to define the initial state of the VQE calculation.
```

2021-05-20 18:07 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# increment the distance and the whole cycle of HF calculation, building quantum circuits and
```suggestion

```

2021-05-20 18:08 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# the iterative VQE optimization of gate parameters is repeated. After we have covered the grid of
```suggestion
# After we have covered the grid of
```

2021-05-20 18:09 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +    # define the circuit
I agree

2021-05-20 18:13 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +        qml.PauliX(1)
Yes, you can just use 
```python
init = qml.qchem.hf_state(2, 4)
qml.BasisState(init, wires=wires )
```

2021-05-20 18:19 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +        qml.SingleExcitation(params[2], wires=[1, 3])
I think that _within a minimal basis set_ we don't need single excitations to prepare the **ground**-state. The circuit would be simpler in this example.

2021-05-20 18:21 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +    xlabel="H-H distance (in Bohr)",
```suggestion
    xlabel="H-H distance (Bohr)",
```

2021-05-20 18:21 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +    ylabel="Total energy (in Hartree)",
```suggestion
    ylabel="Total energy (Hartree)",
```

2021-05-20 18:26 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# internuclear distance tells us the bond length ---
```suggestion
# internuclear distance tells us the equilibrium bond length ---
```

2021-05-20 18:27 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# the distance between the two atoms when the energy is at a minimum and the system is in
```suggestion
# the distance between the two atoms that minimizes the total electronic energy
```

2021-05-20 18:29 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# equilibrium --- and the bond dissociation energy.
```suggestion
# --- and the bond dissociation energy.
```

2021-05-20 18:31 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# of the system at the dissociation limit, where the atoms are far apart and
```suggestion
# of the system where the atoms are far apart and
```

2021-05-20 18:31 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# the total energy plateaus to a constant: the sum of each atom's individual energy.
```suggestion
# the total energy plateaus to the sum of each atom's individual energy.
```

2021-05-20 18:35 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# this system consists of :math:`3` electrons in :math:`6` spin molecular orbitals.
```suggestion
# this system consists of :math:`3` electrons in :math:`6` molecular spin-orbitals.
```

2021-05-20 18:37 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +basis_set = "sto-3g"
Since this is the default in ``molecular_hamiltonian`` we can probably remove this

2021-05-20 18:38 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +
The same here. Since we are doing an all electron calculation with no active space being defined we can remove these lines as well.

2021-05-20 18:40 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +    )
Then here we can reduce it to:

```python
H, qubits = qchem.molecular_hamiltonian(symbols, coordinates, mult=multiplicity)
```

2021-05-20 18:44 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +    singles, doubles = qchem.excitations(active_electrons, active_orbitals * 2)
```suggestion
   electrons = 3
   orbitals = 6
   singles, doubles = qchem.excitations(electrons, orbitals)
```

2021-05-20 18:45 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +
```suggestion
hf = qml.qchem.hf_state(electrons, orbitals)
```

2021-05-20 18:45 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +        qml.BasisState(np.array([1, 1, 1, 0, 0, 0]), wires=(0, 1, 2, 3, 4, 5))
```suggestion
        qml.BasisState(hf, wires=wires)
```

2021-05-20 18:47 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +#     Did you notice a trick we used to speed up the convergence of VQE energy? The converged
I added this above in the case of H2. I assume that it is always done this way, right?

2021-05-20 19:24 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +    def circuit(params, wires):
```suggestion
    hf = qml.qchem.hf_state(electrons=2, orbitals=4)
    def circuit(params, wires):
```

2021-05-20 19:25 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +        qml.PauliX(0)
```suggestion
        qml.BasisState(hf, wires=wires )
```

2021-05-20 19:25 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +        qml.PauliX(1)
```suggestion

```

2021-05-21 10:02 UTC, varunrishi commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# this system consists of :math:`3` electrons in :math:`6` spin molecular orbitals.
I guess spin MOs is the word conventionally used.

2021-05-21 10:08 UTC, varunrishi commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +#     Did you notice a trick we used to speed up the convergence of VQE energy? The converged
Thanks, I used it in both cases. It is a technique used in case of difficult convergence or to stick to one solution in case of presence of multiple solutions

2021-05-23 14:53 UTC, varunrishi commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# .. figure:: /demonstrations/vqe_bond_dissociation/h3_mol_movie.gif
Indeed! It is actually the logo of the molecular visualization software used 'JMOL'. I have not yet found a way to remove them.

2021-05-24 07:52 UTC, varunrishi commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# Let us first understand the problem in more detail. Once we have solved the mean-field HF
removed the mention of mean-field. Will stick with HF everywhere

2021-05-24 07:53 UTC, varunrishi commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# A symmetric approach of :math:`H_2` to :math:`Be` atom to form :math:`BeH_2`
It is actually a H2 molecule approaching a Be atom.

2021-05-25 13:47 UTC, varunrishi commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +    # define the circuit
Thanks for this suggestion. I moved the the definition of circuit outside the loop. Does not have any impact on time taken though.

2021-05-25 13:50 UTC, varunrishi commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +df = pd.DataFrame(list_dist_energy, columns=["H-H distance (in Bohr)", "Energy (in Ha)"])
Thanks Olivia for the suggestion. I thought about it and would like to keep it as it is. Unless we do not want to import other libraries at all.

2021-05-25 16:21 UTC, varunrishi commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +    opt = qml.GradientDescentOptimizer(stepsize=0.4)
Thanks for this great suggestion. This reduces the total tutorial time to < 10 mins! I hadn't played with stepsize. The optimal value is larger than one I used and it indeed speeds up the convergence.

2021-06-15 17:45 UTC, glassnotes requested changes
@ixfoduap looks awesome :rocket: I've left mostly minor comments for phrasing and rendering issues. The only substantial points to address relate to contents of the last section and leading into a conclusion.

2021-06-15 17:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +    An example chemical reaction
```suggestion
    An example chemical reaction.
```
That's an understatement :laughing:

2021-06-15 17:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +the likelihood that the reaction occurs. These energy landscapes formed by these barriers are the
```suggestion
the likelihood that the reaction occurs. The energy landscapes formed by these barriers are the
```

2021-06-15 17:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +over the ground state :math:`|\Psi_0(R)`. The potential energy surface is
```suggestion
over the ground state :math:`|\Psi_0(R)\rangle`. The potential energy surface is
```

2021-06-15 17:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +and subsequently move the nuclei in incremental steps, computing the new energies at each point.
```suggestion
and subsequently adjust the positions of the nuclei in incremental steps, computing the energies at each new configuration.
```
(just a phrasing suggestion, optional)

2021-06-15 17:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +.. figure:: /demonstrations/vqe_bond_dissociation/pes.png
:heart:

2021-06-15 17:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +    Illustration of a potential energy surface for a diatomic molecule
```suggestion
    Illustration of a potential energy surface for a diatomic molecule.
```
Should there be periods after captions? (I added one to the first graphic too, ignore if not necessary)

2021-06-15 17:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +The `Hartree-Fock (HF) state is represented as :math:`|1100\rangle`, where the two
```suggestion
The *Hartree-Fock (HF) state* is represented as :math:`|1100\rangle`, where the two
```
There is a rendering issue in this line due to a missing ` around Hartree-Fock, was this originally a link? In any case I've italicized it here to fix it but change it however you like.

2021-06-15 17:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# Hamiltonian, optimize the circuit using gradient descent to obtain the ground-state energy.
```suggestion
# Hamiltonian, then optimize the circuit using gradient descent to obtain the ground-state energy.
```

2021-06-15 17:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# :math:`0.1` Bohr. This covers the point where the :math:`H-H` bond is formed,
```suggestion
# :math:`0.25` Bohr. This covers the point where the :math:`H-H` bond is formed,
```
(based on the `arange` in the code below)

2021-06-15 17:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# the atoms no longer form a molecule, which is therefore dissociated.
```suggestion
# obtain the bond dissociation energy, which is the difference in the energy of the system at
# equilibrium and the energy when the atoms are far apart. At sufficiently large separations,
# the atoms no longer form a molecule, which is therefore dissociated.
```

2021-06-15 17:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# The molecular movie ⚛️🎥 below is an illustration of the reaction trajectory --- how the distance
```suggestion
# The molecular movie ⚛️🎥 below is an illustration of the reaction trajectory. It depicts how the distance
```

2021-06-15 17:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# molecular orbitals. This translates into a six-qubit problem, and the Hartree-Fock state
```suggestion
# molecular orbitals. This translates into a six-qubit problem, for which the Hartree-Fock state
```

2021-06-15 17:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# :class:`~qml.templates.AllSinglesDoubles` template. The rest of the procedure follows as before.
This link doesn't render; is this template under development?

2021-06-15 17:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# Transition state is local maxima between reactant and products
```suggestion
# Transition state is local maximum between reactant and products
```

2021-06-15 17:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# The activation energy barrier (:math:`E_{a}`) is defined as the difference between the
I felt this section needs an extra line or two of preamble to help with flow from the previous section. e.g., _"The potential energy surfaces we computed so far can be leveraged for other important tasks, such as computing activation energy barriers and reaction rates. The activiaton energy barrier, ..."_

2021-06-15 17:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# of performing highly-accurate calculations in quantum chemistry!
This section ends abruptly - the intro and the heading suggested to me that a reaction rate would be explicitly calculated, but here just the formula is given. Is it straightforward to just grab some value for A and T, and computing something numerically. Would doing so be meaningful?

2021-06-15 17:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +#
Add a short conclusion here and refer back to the learning outcomes.

2021-06-15 18:57 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# :math:`0.1` Bohr. This covers the point where the :math:`H-H` bond is formed,
Great catch! I changed it to speed up the calculation, but didn't alter the text

2021-06-15 18:58 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# :class:`~qml.templates.AllSinglesDoubles` template. The rest of the procedure follows as before.
It was merged recently. I'll take a look and fix it

2021-06-15 19:00 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# of performing highly-accurate calculations in quantum chemistry!
Great point. Yes, we should actually calculate it here

2021-06-15 19:37 UTC, agran2018 requested changes
Thank you @ixfoduap for polishing this tutorial! I have left some comments. Really great to see the usage of some of the advanced features to build Hamiltonians and the new template ``AllSinglesDoubles``!

2021-06-15 19:37 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +    if pes_point > 1:
```suggestion
    if pes_point > 0:
```
??

2021-06-15 19:37 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# the atoms no longer form a molecule, which is therefore dissociated.
I think dissociation energy is positive, the way is defined above seems to indicate that it is a negative quantity. In the code is OK, so it is probably worth to rephrase it here.

2021-06-15 19:37 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +#     calculation at the adjacent geometry. With a better guess, the iterations converge
```suggestion
#     calculation at the adjacent geometry. With a better guess, the VQE algorithm converges
```

2021-06-15 19:37 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +#     relatively quickly and we save considerable time.
two adverbs here
```suggestion
#     faster and we save considerable time.
```

2021-06-15 19:37 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# from the default value of one.
nice!

2021-06-15 19:37 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# :class:`~qml.templates.AllSinglesDoubles` template. The rest of the procedure follows as before.
It is already merged in the master branch of PL.

2021-06-15 19:37 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# get all the singles and doubles excitations, amd Hartree-Fock state
```suggestion
# get all the singles and doubles excitations, and Hartree-Fock state
```

2021-06-15 19:37 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +    dev = qml.device("default.qubit", wires=qubits)
Totally optional:
Since the number of qubits does not change, this line could, in principle, stay outside the loop , right?

In this case we only need here `` H = qchem.molecular_hamiltonian(symbols, coordinates, mult=multiplicity)[0]``

2021-06-15 19:37 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +    opt = qml.GradientDescentOptimizer(stepsize=1.5)
same comment here

2021-06-15 19:37 UTC, agran2018 commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +    if pes_point > 1:
am I missing something here? Why not to take the opt parameters already for the second configuration?
```suggestion
    if pes_point > 0:
```

2021-06-15 20:36 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# an :math:`H` atom fixed at the origin and change only the
It should be an, not a, if we read it as "H", not Hydrogen.

2021-06-17 14:10 UTC, glassnotes approved these changes
@ixfoduap the changes look great! I've left just some optional phrasing suggestions.

2021-06-17 14:10 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# Transition state is local maximum between reactant and products
```suggestion
# Transition state is the local maximum between reactant and products
```

2021-06-17 14:10 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# depend exponentially on the results of this calculation. It is a good reminder of the importance
```suggestion
# pre-exponential factor that can be determined empirically for each reaction. Crucially, the rate at which
# a chemical reaction occurs depends exponentially on the activation energy computed from the PES --- this is a good reminder of the importance
```

2021-06-17 14:10 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# Doubling the temperature can increase the rate by a factor of almost two million! For a similar
WHOA :exploding_head:

2021-06-17 14:10 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# depend exponentially on the results of this calculation. It is a good reminder of the importance
After reading through the rest of this section, I notice that the end of it emphasizes the importance of computing things accurately. I think that point is actually more effective there (since it follows the illustrative example), so consider removing the part "this is a good reminder..." from this paragraph.

2021-06-17 14:10 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# providing accurate simulations in sufficiently short time scales. If successful, this quest will
```suggestion
# improve both hardware and algorithms to reach the regime where providing accurate simulations
# becomes intractable for existing methods. If successful, this quest will
```

2021-06-17 14:10 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# reach.
Awesome conclusion :100:

2021-06-17 14:10 UTC, glassnotes commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +*Author: PennyLane dev team. Posted: . Last updated: .*
Leaving a reminder here to update the date before merging.

2021-06-17 16:31 UTC, agran2018 approved these changes
Thanks @ixfoduap ! Just left couple of suggestions.

2021-06-17 19:23 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# Let's plot the results 📈
It's one of the deepest mysteries of life

2021-06-17 19:28 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +    dev = qml.device("default.qubit", wires=qubits)
You could do that, but I prefer to leave as is

2021-06-17 19:35 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +##########################################################
Great catch! A side effect of cutting out content

2021-06-18 14:04 UTC, ixfoduap approved these changes

2021-07-21 17:42 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +*Author: PennyLane dev team. Posted: . Last updated: 17 June 2021*
```suggestion
*Author: PennyLane dev team. Posted: 26 July 2021. Last updated: 26 July 2021*
```

2021-07-21 18:07 UTC, ixfoduap commented on demonstrations/tutorial_vqe_bond_dissociation.py
> +# :class:`~qml.templates.AllSinglesDoubles` template. The rest of the procedure follows as before.
```suggestion
# :class:`~.pennylane.templates.subroutines.AllSinglesDoubles` template. The rest of the procedure follows as before.
```

2021-07-23 15:58 UTC, co9olguy commented on demos_basics.rst
> +    :description: :doc:`demos/tutorial_vqe_bond_dissociation`
@ixfoduap Can we change the tutorial name to match the title better before merging?

2021-07-23 17:46 UTC, co9olguy commented on demos_basics.rst
> +    :description: :doc:`demos/tutorial_vqe_bond_dissociation`
```suggestion
    :description: :doc:`demos/tutorial_chemical_reactions`
```

2021-07-23 18:33 UTC, co9olguy commented on demonstrations/tutorial_chemical_reactions.py
> +*Author: PennyLane dev team. Posted: 26 July 2021. Last updated: 26 July 2021*
```suggestion
*Author: PennyLane dev team. Posted: 23 July 2021. Last updated: 23 July 2021*
```

2021-07-23 18:54 UTC, merged