[WIP] Tutorial Classical Shadows
PennyLaneAI/qml pull request #263
Opened 2021-05-06 19:48 UTC by bdoolittle

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Add a thumbnail link to your tutorial in `beginner.rst`, or if a
      QML implementation, in `implementations.rst`.

- [ ] All QML tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2021-05-06 19:55 UTC, co9olguy commented
Great choice @bdoolittle!

2021-05-12 16:31 UTC, bdoolittle reviewed
Hey @therooler, I've added some comments to the code you submitted. Let me know if you have any questions.

2021-05-12 16:31 UTC, bdoolittle commented on demonstrations/tutorial_classical_shadows.py
> +                      device=device_shadow, measure='sample')(params)
There is a potential problem here with the creation of the `QNodeCollection` via `map`. Basically, `unitaries` is a list of one-qubit observables and a separate circuit is made for each observable  in this list. That means we aren't sampling the outputs for multiple qubits from the same shot. Any entanglement correlations between qubits are destroyed by this sampling procedure.

Unfortunately, I don't think `map` can do what we need it to do. We'll need to set this up by constructing qnodes in a loop and instantiating a `QNodeCollection` with a list of qnodes.

The main idea is that for each shot , we need  a list of all `num_qubits` classical outcomes for the respective  observable at each site

2021-05-12 16:31 UTC, bdoolittle commented on demonstrations/tutorial_classical_shadows.py
> +        unitaries.extend(unitary_ensemble[int(randints[ns, i])](i) for i in range(nqubits))
```suggestion
        unitaries.extend(unitary_ensemble[int(randints[ns, i])](i) for i in range(num_qubits))
```

2021-05-12 16:31 UTC, bdoolittle commented on demonstrations/tutorial_classical_shadows.py
> +    randints = np.random.randint(1, 4, size=(number_of_shadows, nqubits))
It would be ideal for `randints` to be converted to integer values on construction.

2021-05-12 16:31 UTC, bdoolittle commented on demonstrations/tutorial_classical_shadows.py
> +    samples = samples.reshape((number_of_shadows, nqubits))
```suggestion
    samples = samples.reshape((num_shadows, num_qubits))
```

2021-05-12 16:31 UTC, bdoolittle commented on demonstrations/tutorial_classical_shadows.py
> +    return np.concatenate([samples, randints], axis=1)
probably better if `samples` and `randints` are not concatenated together and returned as a tuple instead. This will require fixes down the line

2021-05-12 16:31 UTC, bdoolittle commented on demonstrations/tutorial_classical_shadows.py
> +    samples = samples.reshape((number_of_shadows, nqubits))
a name like `classical_outcomes` or `b_samples` might be more descriptive or fit with the paper better

2021-05-12 16:31 UTC, bdoolittle commented on demonstrations/tutorial_classical_shadows.py
> +def estimate_shadow_obervable(shadows, observable):
the input argument should probably  be  `shadow`

2021-05-12 16:31 UTC, bdoolittle commented on demonstrations/tutorial_classical_shadows.py
> +            product *= single_measurement[position]
the  terminology used  in the paper:
* shadow: a list of n snapshots
* snapshot: classical outcomes and measurements used for a single shot of a quantum circuit

We should use this terminology for clarity and consistency  e.g. `for  snapshot in  shadow` or  something similar depending on the format of the  shadow data structure

2021-05-12 16:31 UTC, bdoolittle commented on demonstrations/tutorial_classical_shadows.py
> +            if pauli_XYZ != single_measurement[position + nqubits]:
calculate `nqubits` from the shadow, don't rely on global state

2021-05-12 16:31 UTC, bdoolittle commented on demonstrations/tutorial_classical_shadows.py
> +            if pauli_XYZ != single_measurement[position + nqubits]:
the indexing here will be simpler if we don't concatenate the shadow outcomes with the measurements.

2021-05-12 16:31 UTC, bdoolittle commented on demonstrations/tutorial_classical_shadows.py
> +          3: qml.PauliZ(0).matrix}
```suggestion
paulis = [
    qml.Identity(0).matrix,
    qml.PauliX(0).matrix,
    qml.PauliY(0).matrix,
    qml.PauliZ(0).matrix
]
```

2021-05-12 16:31 UTC, bdoolittle commented on demonstrations/tutorial_classical_shadows.py
> +          3: qml.PauliZ(0).matrix}
I actually use this too, we might want to consider a function `def pauli_matrices():` to avoid redundancy

2021-05-12 16:33 UTC, josh146 commented on demonstrations/tutorial_classical_shadows.py
> +def classical_shadow(circuit_template, params, num_shadows: int) -> np.ndarray:
The type hinting policy in PL is currently 'type hint if you want but it's not required' 🙂 So feel free to include type hints here if you want

2021-05-28 21:28 UTC, bdoolittle commented
@trbromley The classical shadows tutorial is ready for code review. Please take a look when you get a chance. Thanks!

2021-05-31 19:34 UTC, glassnotes reviewed
I've done a quick first pass and have some general comments: 

- Choice of examples is great! I like that there's an example in each subsection too :smile: 
 - It's not necessary to discuss or include any formal testing; even full docstrings aren't necessary, as long as it's clear what the functions are doing through comments. The demos are meant to be more expository and tell a story about the concept through the text and code.
 - It was a bit confusing to keep track of how the functions were meant to be spread across multiple files, since there is only one file in the PR. It should be possible for a reader to download the `.ipynb` from the sidebar and run the demo top to bottom without any auxiliary files or information, so I'd recommend to restructure some of the discussion / code blocks to assume that everything is within the same file (even if, in a proper module, things would be separated).

Please let me know if there is anything I can clarify here :+1:

2021-06-02 20:03 UTC, trbromley reviewed
Thanks @bdoolittle @therooler!

Really cool topic and it was interesting to learn more. Although I liked the idea of having a resource for writing tests in PennyLane, I felt like the testing here and the resulting split into 3 files took away from the nice story about classical shadows. I was more drawn to the examples, plots, and points where data was printed out. Would it make sense to focus on the core piece on classical shadows here, resulting in a shorter demo, and leave ideas on testing free for a potential how-to guide?

2021-06-03 21:43 UTC, therooler commented on demonstrations/tutorial_classical_shadows.py
> +def calculate_classical_shadow(
Yes, we thought about the most efficient way to do this but I think these new QNode transforms would be ideal for this.

2021-06-04 14:33 UTC, glassnotes requested changes
@bdoolittle @therooler great work incorporating the structural changes! The story of the demo reads really nicely, and the implementation seems to work quite well :tada:

Have left a number of questions and comments to help with clarity, and pointed out a few places where the code could be streamlined.

2021-06-04 14:33 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +shadow_state
```suggestion
print(np.round(shadow_state, decimals=6))
```
(Just helps with readability of the output)

2021-06-04 14:33 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +# We will add this utility method to the notebook for convenience.
```suggestion
```

2021-06-04 14:33 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +operator_2_norm(bell_state - shadow_state)
Since below you are plotting the trace distance, perhaps just define that function explicitly rather than the operator norm.

2021-06-04 14:33 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +# becomes closer to the ideal state.
That's really neat!! :tada:

Why does it increase around 3000 snapshots, is that just due to random deviation? Maybe worth mentioning that. 

[This is a purely optional idea] Another thing you can try is to run this multiple times for each number of snapshots and add error bars showing the standard deviation.

2021-06-04 14:33 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +# We have confirmed that our code produces classical shadows that can be used to reconstruct
```suggestion
# We have confirmed that classical shadows can be used to reconstruct
```

2021-06-04 14:33 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +# bound. Also, the bound has a failure probability :math:`\delta`, and by choosing the number of splits :math:`K` to be
Recommend to switch the order of this sentence and the next one, or move the discussion of failure probability to later on, once "splits" has been defined.

2021-06-04 14:33 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +# corresponding measurement basis :math:`U_j` and is 0 otherwise. Hence if a single :math:`U_j` in the snapshot
```suggestion
# Due to the orthogonality of the Pauli operators, this evaluates to :math:`\pm 3` if :math:`P_j` is the
# corresponding measurement basis :math:`U_j` and to 0 otherwise. Hence if a single :math:`U_j` in the snapshot
```

2021-06-04 14:33 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +def shadow_bound(error: float, max_k: int, observables: List[np.ndarray]) -> int:
This is maybe more personal preference, but I'm not a huge fan of the type hinting; it's also used a bit irregularly throughout the demo, so I'd suggest to either include it everywhere or not include it at all.

2021-06-04 14:33 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +        np.ceil(np.log(M) * (4 ** max_k) * max(shadow_norm(o) for o in observables) / error ** 2)
This line is just slightly too long and creates a scrollbar; maybe try to shorten one of the variable names, or include the log as part of the definition of M.

2021-06-04 14:33 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +        means.append(sum_product / cnt_match)
```suggestion

    if cnt_match == 0:
        means.append(0)
    else:
        means.append(sum_product / cnt_match)
        
```

2021-06-04 14:33 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +# an error of 1e-1 for this set of observables
```suggestion
# an error of :math:`10^{-1}` for this set of observables
```

2021-06-04 14:33 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +    )
```suggestion
    circuit(params, wires=dev_exact.wires, observable=[o])
```

2021-06-04 14:33 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +plt.show()
Hm, the plot I see looks quite different, incl. the scale, were there major changes to the code since this original comment?
![image](https://user-images.githubusercontent.com/2068515/120816217-8d956100-c51e-11eb-8954-151ea32267ec.png)

2021-06-04 14:33 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +
Add a couple concluding sentences here to recap (e.g., revisit the learning outcomes), highlight what worked well and what didn't, and maybe mention any interesting future directions people are taking.

2021-06-04 14:33 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +plt.plot(shadow_size_grid, [1e-1 for _ in shadow_size_grid], linestyle="--", color='gray')
Please label the axes here for clarity.

2021-06-04 14:33 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +    Adapted from https://github.com/momohuang/predicting-quantum-properties
The style of this function looks notably different than the rest of the code in the demo. Consider whether any of the nested for loops or if/else statements can be streamlined using list comprehensions or single-line statements.

2021-06-04 14:33 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +def local_qubit_rotation_circuit(params, wires, **kwargs):
Does `wires` need to be included as a parameter her? Internally, `dev.wires` is used instead of the argument.

2021-06-04 14:33 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +# 2. Tensor products of random single-qubit Clifford circuits.
See comment below re. Cliffords - should this be Paulis?

2021-06-04 16:12 UTC, josh146 commented on demonstrations/tutorial_classical_shadows.py
> +<https://arxiv.org/pdf/2002.08953.pdf>`_ [[#Huang2020]_].
This is a Sphinx inconsistency. I believe this repo is using Sphinx 1.8.5, which doesn't require the extra brackets.

Sphinx > 2.0, however, _does_ require the extra brackets.

2021-06-07 02:57 UTC, therooler commented on demonstrations/tutorial_classical_shadows.py
> +# The shadow norm :math:`||O_i||^2_{\text{shadow}}` again depends on the unitary ensemble that is chosen.
This is explained a bit below that part:

||O_i||^2_{\text{shadow}} \leq 4^k ||O_i||_\infty^2.

So we calculate the bound on the shadow norm through the infinity norm

2021-06-07 03:17 UTC, therooler commented on demonstrations/tutorial_classical_shadows.py
> +        # for each shadow, add a random Clifford observable at each location
This should say Pauli :\

2021-06-07 03:21 UTC, therooler commented on demonstrations/tutorial_classical_shadows.py
> +    unitary_ensemble = [qml.PauliX, qml.PauliY, qml.PauliZ]
Oh cool, I didn't know that was a thing. I think we may run into troubles later on when we estimate observables though, because there we need to know the pauli at each location individually.

2021-06-07 03:26 UTC, therooler commented on demonstrations/tutorial_classical_shadows.py
> +# becomes closer to the ideal state.
Yes, the estimation is subject to statistical flucatuations. I will add errobars.

2021-06-07 13:07 UTC, therooler commented on demonstrations/tutorial_classical_shadows.py
> +    b_lists = shadow[:, 0:num_qubits]
The reason for working with a single array was to stay close to the conceptual idea of the shadow; it is the combination of unitaries and measurement outcomes. I agree that it would be clearer to separate them in terms of code. For now I will leave it like this but if you're convinced that separating would be better then we can change it.

2021-06-07 13:12 UTC, therooler commented on demonstrations/tutorial_classical_shadows.py
> +def shadow_bound(error: float, max_k: int, observables: List[np.ndarray]) -> int:
removed it everywhere

2021-06-09 00:40 UTC, therooler commented
Thanks for all the comments, I think we've been able to address all the feedback.

2021-06-09 13:12 UTC, glassnotes requested changes
Changes are looking great! Have left a mostly minor comments, for typos and phrasing, but there are a few important points to address re. the example at the end.

2021-06-09 13:12 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +# Here, we give an example for estimating multiple observables on a 10 qubit circuit.
```suggestion
# Here, we give an example for estimating multiple observables on a 10-qubit circuit.
```

2021-06-09 13:12 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +#   O = \sum_i^{n-1} X_i X_{i+1}
```suggestion
#   O = \sum_i^{n-1} X_i X_{i+1}.
```

2021-06-09 13:12 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +# given by `shadow_bound`.
```suggestion
# given by ``shadow_bound``.
```

2021-06-09 13:12 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +# estimate expectation values of observables. This is but the top of the iceberg of what is possible
```suggestion
# estimate expectation values of observables. This is but the tip of the iceberg of what is possible
```

2021-06-09 13:12 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +# calculate entanglement witnesses even find a way to approximate the Von Neumann entropy.
```suggestion
# calculate entanglement witnesses even find a way to approximate the von Neumann entropy.
```

2021-06-09 13:12 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +# of classical shadows for the characterization of quantum systems.
Great conclusion!

2021-06-09 13:12 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +#             Ph.D. thesis, Caltech, eprint quantph/9705052
Make the link clickable; add arXiv links to all references if applicable.

2021-06-09 13:12 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +    print([e for e in estimates])
I'm not really sure how to interpret these numbers; are they the distances between the true and estimated states? Why not just print the last array as it seems to contain all the data of the earlier calculations?

2021-06-09 13:12 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +# As expected, the bound is satisfied and the accuracy increases, up to statistical fluctuations.
The text before the code and plot suggests there should be a steady decrease in the error, but I am still seeing a plot that doesn't steadily decrease: 
![image](https://user-images.githubusercontent.com/2068515/121360470-72519980-c902-11eb-80be-333a2a4eb4d7.png)
Is this the expected result, and if so, why is there so much fluctuation?

2021-06-09 20:41 UTC, therooler commented on demonstrations/tutorial_classical_shadows.py
> +# :math:`U^\dagger |b\rangle\langle b| U` efficiently in classical memory as a bit string and an index corresponding to the chosen unitary :math:`U`.
Storing the computed value would also be efficient, since that would mean storing the eigenstates of X and Y, instead of just |0>, |1>. For numerical reasons, we just choose to keep them separate because it makes it easier to compute stuff. I removed the part of how we store things for now.

2021-06-10 13:31 UTC, glassnotes requested changes
Just minor phrasing and formatting comments now, the updated contents and plot all look great :+1:  Nice work!

2021-06-10 13:31 UTC, glassnotes commented on demos_research.rst
> +    :tags: classical-shadows
```suggestion
    :tags: quantumcomputing characterization
```

2021-06-10 13:31 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +# We call this a *snapshot* :math:`\hat{\rho}_j = U^\dagger |b\rangle\langle b| U` of the state.
```suggestion
# We call this a *snapshot* of the state.
```
There is an overload of the notation for `\hat{\rho}_j` - here it was used for `U\dag |b><b| U`, whereas in the actual definition of the shadow it gets used to define the inverted measurement channel applied to `U\dag |b><b|U`.

2021-06-10 13:31 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +# Since the shadow approximates the :math:`rho`, we can now estimate **any** observable with the empirical mean:
```suggestion
# Since the shadow approximates :math:`\rho`, we can now estimate **any** observable with the empirical mean:
```

2021-06-10 13:31 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +# Note that the inverted channel is not physical, i.e., it is not completely postive and trace preserving (CPTP).
```suggestion
# The inverted channel is not physical, i.e., it is not completely postive and trace preserving (CPTP).
```
(To prevent repetition of "Note that" in the paragraph after the next)

2021-06-10 13:31 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +# This is a serious limitation. Say that we want to estimate the single expectation value of a Pauli observable
```suggestion
# Say that we want to estimate the single expectation value of a Pauli observable
```
Remove repetition.

2021-06-10 13:31 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +# becomes dependent on the locality :math:`k` of the observables that we want to estimate
```suggestion
# becomes dependent on the locality :math:`k` of the observables that we want to estimate:
```

2021-06-10 13:31 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +# 4. The snapshot is recorded as the observed eigen value :math:`1,-1` for :math:`|0\rangle,|1\rangle`, respectively,
```suggestion
# 4. The snapshot is recorded as the observed eigenvalue :math:`1,-1` for :math:`|0\rangle,|1\rangle`, respectively,
```
This bullet point didn't render properly it appears as part of the main text rather than in the list; please check the spacing, it may be that the line that starts "and the index of the..." must be on the same line as the point.

2021-06-10 13:31 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +     and the index of a unitary operation.
```suggestion
    and the index of a unitary operation.
```

2021-06-10 13:31 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +# setting up a two-qubit device. Setting shots = 1 ensures that we only get a single measurement
```suggestion
# set up a two-qubit device with shots = 1 to ensure that we only get a single measurement
```
shortens the line to prevent a horizontal scrollbar in the code

2021-06-10 13:31 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +shadows[0][1]
```suggestion
print(shadows[0][0])
print(shadows[0][1])
```
Otherwise only the second one actually shows up in the output.

2021-06-10 13:31 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +    Reconstruct a state from a single snapshot in a shadow.
Mention that this is a helper function for `shadow_state_reconstruction`.

2021-06-10 13:31 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +    snapshots in the shadow. Use median of means to improve ameliorate the effects of outliers.
```suggestion
    snapshots in the shadow. Use median of means to ameliorate the effects of outliers.
```

2021-06-10 13:31 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +        operators e.g. qml.PauliX(0) @ qml.PauliY(1).
```suggestion
            operators e.g. qml.PauliX(0) @ qml.PauliY(1).
```

2021-06-10 13:31 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +        measure.
```suggestion
            measure.
```

2021-06-10 13:31 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +# the shadow.
The new plot looks great! Just mention briefly after the plot here what each point corresponds to, as well as what the points on the dotted line are. There is a lot of code that separates this from the explanations, so it is helpful to reiterate here.

2021-06-10 13:31 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +            estimate_shadow_obervable(
Similar to the comment below, this can be condensed into fewer lines.

2021-06-11 16:59 UTC, therooler commented on demonstrations/tutorial_classical_shadows.py
> +            estimate_shadow_obervable(
black wont let me :(, it keeps changing back to the long formatting

2021-06-14 12:08 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +# The points in the plot indicate the individual errors for all :math`O_i` at a given shadow size. The dashed line
```suggestion
# The points in the plot indicate the individual errors for all :math:`O_i` at a given shadow size. The dashed line
```

2021-06-14 13:52 UTC, therooler commented
I think we're ready for merging. @trbromley, could you take a final look?

2021-06-14 18:20 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +Posted: 8 June 2021. Last updated: 8 June 2021.*
```suggestion
Posted: 14 June 2021. Last updated: 14 June 2021.*
```

2021-06-14 21:02 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +#   O = \sum_i^{n-1} X_i X_{i+1} + Y_i Y_{i+1} + Z_i Z_{i+1}.
```suggestion
#   O = \sum_{i=0}^{n-1} X_i X_{i+1} + Y_i Y_{i+1} + Z_i Z_{i+1}.
```

2021-06-14 21:02 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +estimates = []
```suggestion
estimates = []

```

2021-06-14 21:02 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +expval_exact = [circuit(params, wires=dev_exact.wires, observable=[o]) for o in list_of_observables]
```suggestion
expval_exact = [
    circuit(params, wires=dev_exact.wires, observable=[o]) for o in list_of_observables
]
```

2021-06-14 21:02 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +# Finally, we plot the errors :math:`|\langle{O_i}\rangle_{shadow} - \langle{O_i}\rangle_{exact}|`,
```suggestion
# Finally, we plot the errors :math:`|\langle{O_i}\rangle_{shadow} - \langle{O_i}\rangle_{exact}|`
```

2021-06-14 21:04 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +#   O = \sum_i^{n-1} X_i X_{i+1} + Y_i Y_{i+1} + Z_i Z_{i+1}.
@therooler @bdoolittle could one of you please confirm this edit is correct?

2021-06-14 21:09 UTC, trbromley approved these changes
Thanks @bdoolittle @therooler, great demo!

2021-06-14 21:09 UTC, trbromley commented on demonstrations/tutorial_classical_shadows.py
> +    return [qml.expval(o) for o in observables]
Why not `qml.sample()`?

2021-06-14 21:09 UTC, trbromley commented on demonstrations/tutorial_classical_shadows.py
> +print(np.round(shadow_state, decimals=6))
Cool to see!

2021-06-14 21:48 UTC, therooler commented on demonstrations/tutorial_classical_shadows.py
> +        obs = [unitary_ensemble[int(unitary_ids[ns, i])](i) for i in range(num_qubits)]
This is a good point that also confused me in the beginning. I added some extra explanation.

2021-06-14 21:50 UTC, glassnotes approved these changes

2021-06-14 21:50 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +    # undo the rotations that were added implicitely added to the circuit for the pauli measurements
```suggestion
    # undo the rotations that were added implicitly added to the circuit for the Pauli measurements
```

2021-06-14 21:50 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +    # applying the single qubit clifford circuit is equivalent to measuring a pauli
```suggestion
    # applying the single-qubit Clifford circuit is equivalent to measuring a Pauli
```

2021-06-14 22:03 UTC, glassnotes commented on demonstrations/tutorial_classical_shadows.py
> +    # undo the rotations that were added implicitly added to the circuit for the Pauli measurements
```suggestion
    # undo the rotations that were added implicitly to the circuit for the Pauli measurements
```

2021-06-14 22:14 UTC, merged