[WIP] Adds Feedback-Based Quantum Optimization (FALQON) Tutorial
PennyLaneAI/qml pull request #265
Opened 2021-05-10 21:13 UTC by Lucaman99

**Title:**

Adds a tutorial on Feedback-Based Quantum Optimization (FALQON) to the QML gallery. This PR is a work-in-progress.

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2021-05-14 21:04 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +convergence isn't guaranteed, and the optimization procedure can become "stuck" in local minima.
```suggestion
it has drawbacks: convergence isn't guaranteed, and the optimization procedure can become
"stuck" in local minima.
```
It's not accurate that optimization over a parameter space (is there any other typo of optimization?) implies that convergence isn't guaranteed

2021-05-14 21:08 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +the system from an initial state into this ground state. FALQON falls under this broad scheme.
```suggestion
the system from an initial state into the ground state of :math:`H_c`. FALQON falls under this broad scheme.
```

2021-05-14 21:09 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +Hamiltonians come up quite often in the theory of `quantum control <https://quantiki.org/wiki/quantum-control-theory>`__,
```suggestion
Hamiltonians appear often in the theory of `quantum control <https://quantiki.org/wiki/quantum-control-theory>`__,
```

2021-05-14 21:10 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +which studies how we may go about driving a quantum system from one state to another. The choice of :math:`\beta(t)` allows
I suggest removing "which studies how we may go about driving a quantum system from one state to another"

2021-05-14 21:10 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +us to decide which state we want a system governed by such a Hamiltonian to evolve towards.
this sentence is awkward; consider revising

2021-05-14 21:11 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +The time-dependent Schrodinger equation tells us that the dynamics of the system are given by:
```suggestion
The time-dependent Schrödinger equation tells us that the dynamics of the system are given by:
```

2021-05-14 21:11 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +where we set :math:`\hbar = 1`. Now, let us suppose that the objective of our quantum control experiment is to drive our system
```suggestion
where we set :math:`\hbar = 1`. Now suppose that the objective of the quantum control experiment is to drive the system
```

2021-05-14 21:12 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +value :math:`\langle H_c\rangle`. Therefore, a reasonable goal is to construct our system such that the expectation decreases with time:
```suggestion
value :math:`\langle H_c\rangle`. Therefore, a reasonable goal is to construct the system such that the expectation decreases with time:
```
And look elsewhere for cases where the use of "we" and "our" can be smoothly avoided. And of course, keep it when it the text reads better

2021-05-14 21:13 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +.. math:: \frac{d}{dt} \langle H_c\rangle_t = \frac{d}{dt} \langle \psi(t)|H_c|\psi(t)\rangle = i \beta(t)\langle [H_d, H_c] \rangle_t \leq 0
```suggestion
.. math:: \frac{d}{dt} \langle H_c\rangle_t = \frac{d}{dt} \langle \psi(t)|H_c|\psi(t)\rangle = i \beta(t)\langle [H_d, H_c] \rangle_t \leq 0,
```
and similarly elsewhere make sure to add punctuation to equations too

2021-05-14 21:13 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +The time-dependent Schrodinger equation tells us that the dynamics of the system are given by:
And make this change throughout

2021-05-14 21:14 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +where we used the product rule and Schrodinger's equation to derive the above formula. Recall that our control experiment depends on the choice of :math:`\beta(t)`. Thus,
This line is too long

2021-05-14 21:14 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +eventually drive the system into the ground state of :math:`H_c`! Thus, if we evolve some initial state :math:`|\psi_0\rangle` under the
```suggestion
eventually drive the system into the ground state of :math:`H_c`. Thus, if we evolve some initial state :math:`|\psi_0\rangle` under the
```

2021-05-14 21:15 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +eventually drive the system into the ground state of :math:`H_c`! Thus, if we evolve some initial state :math:`|\psi_0\rangle` under the
I love exclamation marks and emojis, but they have to be used with extreme care, otherwise makes the text look like it should not be taken seriously.

2021-05-14 21:16 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +time-evolution operator corresponding to :math:`H`, given by :math:`U(t) = e^{-iHt}`, we will arrive at the ground state of :math:`H_c`.
```suggestion
time-evolution operator :math:`U(t) = e^{-iHt}`, we will arrive at the ground state of :math:`H_c`.
```

2021-05-14 21:18 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +time-evolution operator corresponding to :math:`H`, given by :math:`U(t) = e^{-iHt}`, we will arrive at the ground state of :math:`H_c`.
I think the explanation so far is good as it is, but in general we have to be careful when evolving under time-dependent hamiltonians, as it's not as simple as applying e^{-iH(t) t} . Ultimately, what you will do is to evolve under time-*independent* hamiltonians, which get changed with each new step, mimicking the process of evolving under a time-dependent one

2021-05-14 21:18 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# FALQON is an algorithm for combinatorial optimization. Therefore, we must select some kind of combinatorial problem
I think these first two sentences can be removed

2021-05-14 21:19 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# where each qubit is a node in the graph, and the states :math:`|0\rangle` and :math:`|1\rangle` represent if the vertex
```suggestion
# where each qubit is a node in the graph, and the states :math:`|0\rangle` and :math:`|1\rangle` represent whether the vertex
```

2021-05-14 21:21 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# is able to "mix up" our system sufficiently so that it may be driven towards the ground state (similar to the mixer Hamiltonian in QAOA).
```suggestion
# In addition to defining :math:`H_c`, we also require a driver Hamiltonian :math:`H_d`, which does not commute with :math:`H_c`. This is similar to the mixer Hamiltonian in QAOA.
```
Pro-tip: don't over-explain! The reader only takes away the important information anyway and the less "noise" there is the easier it becomes to focus on what really matters

2021-05-14 21:21 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# To keep things simple, we choose a sum over Pauli-X operations on each qubit:
```suggestion
# To keep things simple, we choose a sum over Pauli X operations on each qubit:
```

2021-05-14 21:22 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# As you may recall from the Theory section, one of the main ingredients in the FALQON algorithm is the operator :math:`i [H_d, H_c]`. In
```suggestion
# One of the main ingredients in the FALQON algorithm is the operator :math:`i [H_d, H_c]`. In
```

2021-05-14 21:22 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# the case of MaxClique, we can write down the commutator :math:`[H_d, H_c]` explicitly, exploiting the commutator's bilinearity:
```suggestion
# the case of MaxClique, we can write down the commutator :math:`[H_d, H_c]` explicitly:
```

2021-05-14 21:22 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# Clearly, there are two distinct commutators that we must calculate, :math:`[X_k, Z_j]` and :math:`[X_k, Z_i Z_j]`.
```suggestion
# There are two distinct commutators that we must calculate, :math:`[X_k, Z_j]` and :math:`[X_k, Z_i Z_j]`.
```
If it's clear, do we really need to say so? :wink:

2021-05-14 21:25 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# into the above equation, and multiplication by :math:`i` that:
```suggestion
# where :math:`\delta_{kj}` is the `Kronecker delta <https://en.wikipedia.org/wiki/Kronecker_delta>`__. Therefore it follows from substitution
# into the above equation and multiplication by :math:`i` that:
```

2021-05-14 21:25 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# Note that this method works for any graph:
Wonderful!

2021-05-14 21:26 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# We now must build the actual FALQON algorithm. Our goal is to evolve some initial state under the Hamiltonian :math:`H`, with our
```suggestion
# We now build the actual FALQON algorithm. Our goal is to evolve some initial state under the Hamiltonian :math:`H`, with our
```

2021-05-14 21:27 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# Hamiltonian, and :math:`\Delta t`. This simply involves repeating the FALQON layer multiple times. Note that the
```suggestion
# Hamiltonian, and :math:`\Delta t`. This involves repeating the FALQON layer multiple times. The
```
To soften the use of easily, simply, etc.
Also, note that using "note that" isn't always necessary or helpful

2021-05-14 21:32 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# Finally, before we put everything together and run the circuit, there is still one issue that must be addressed.
I think that this should eb explained earlier. You make it sound like it's an issue that has to be dealt with, but I see it as a crucial (and clever!) characteristic of the algorithm. I would prefer to see this explained together with the main idea of the algorithm, before any code is written

2021-05-14 21:33 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# This leads immediately to the FALQON algorithm as a recursive process that feeds back into itself.
```suggestion
# This leads to the FALQON algorithm as a recursive process that feeds back into itself.
```
Another tip: keep adjectives and adverbs to a minimum; makes for smoother writing

2021-05-14 21:33 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# This leads immediately to the FALQON algorithm as a recursive process that feeds back into itself.
Also, isn't feeding back into itself the definition of recursive? :thinking:

2021-05-14 21:34 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# Implementing this recursive process isn't too difficult, we simply make use of the methods defined above:
```suggestion
# Implementing this recursive process can be done using the methods defined above:
```

2021-05-14 21:35 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# Without further delay, we can run FALQON for our MaxClique problem! It is important that we choose :math:`\Delta t` small enough
```suggestion
# We can now run FALQON for our MaxClique problem! It is important that we choose :math:`\Delta t` small enough
```
Was the above content a delay? I don't think so! It was important and useful information

2021-05-14 21:35 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# such that our approximate time-evolution is close enough to the real time-evolution, otherwise we the expectation value of
```suggestion
# such that the approximate time-evolution is close enough to the real time-evolution, otherwise we the expectation value of
```

2021-05-14 21:36 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# As expected, the expectation value of the cost Hamiltonian strictly decreases!
```suggestion
# As expected, cost function strictly decreases!
```
This avoids repeated use of expected, expectation

2021-05-14 21:37 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# FALQON did, we can create a graph showing the probability of measuring each possible bitstring. We create
```suggestion
# To get a better understanding of the performance of the FALQON algorithm,
# we can create a graph showing the probability of measuring each possible bitstring. We define
```

2021-05-14 21:37 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# Clearly, the bitstring occurring with the highest probability is the state :math:`|28\rangle = |11100\rangle`.
```suggestion
# The bitstring occurring with the highest probability is the state :math:`|28\rangle = |11100\rangle`.
```

2021-05-14 21:38 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# and is clearly the maximum clique. FALQON has solved the MaxClique problem!
```suggestion
# This corresponds to nodes :math:`0`, :math:`1`, and :math:`2`, which is precisely the maximum clique.
# FALQON has solved the MaxClique problem!
```

2021-05-14 21:39 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# the complete graph on :math:`n` vertices and then keep each edge with probability :math:`p`. We then find the maximum cliques on
Funny, I always viewed it as starting from an empty graph and adding nodes with probability p. Worth double-checking what your code actually does

2021-05-14 21:40 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# these graphs, classically, using the `Bron-Kerbosch algorithm <https://en.wikipedia.org/wiki/Bron%E2%80%93Kerbosch_algorithm>`__.
```suggestion
# these graphs using the `Bron-Kerbosch algorithm <https://en.wikipedia.org/wiki/Bron%E2%80%93Kerbosch_algorithm>`__.
```

2021-05-14 21:41 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# expensive, so we will only show the final results for these figures of merit (along with the values of :math:`\beta`) as a function of layer.
```suggestion
# expensive, so we only show the final results for these figures of merit along with the values of :math:`\beta`.
```
What do you mean by "as a function of layer?"

2021-05-14 21:42 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# Note that, due to computational constraints, we have average over only :math:`3` random graphs per node size, for size :math:`n = 6, 7, 8`,
```suggestion
# Due to computational constraints, we have averaged over :math:`3` random graphs per node size, for size :math:`n = 6, 7, 8`,
```

2021-05-14 21:42 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# decreases with layers, and also improves with graph size. Although :math:`r_A = 0.9` is a large relative error, we expect further improvement
Should this be "decreases with the number of layers?"

2021-05-14 21:44 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# decreases with layers, and also improves with graph size. Although :math:`r_A = 0.9` is a large relative error, we expect further improvement
I would remove the sentence "Although r=0.9 is a large relative error..."

2021-05-14 21:47 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# Bonus: Seeding QAOA with FALQON (Bird Seed 🦅)
I would remove the Bonus: I made it all the way here and I'm actually interested in reading! So why make it sound like it's something extra rather than something important?

2021-05-14 21:49 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# with each iteration, its circuit depth grows linearly with the number of iterations. On the other hand, QAOA
Like I asked you on slack, I think this is not the only catch. I think it's fine to leave as is, but maybe other experienced readers may wonder about additional drawbacks

2021-05-14 21:50 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# Despite having unique issues, QAOA and FALQON have many similarities, most notably, their circuit structure. Both involve alternating layers
```suggestion
# Despite having unique featurs, QAOA and FALQON have many similarities, most notably their circuit structure. Both involve alternating layers
```

2021-05-14 21:50 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# to combine FALQON and QAOA to yield a new optimization algorithm that leverages the benefits of both algorithms!
```suggestion
# to combine FALQON and QAOA to yield a new optimization algorithm that leverages the benefits of both!
```

2021-05-14 21:51 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# If we run FALQON for :math:`p` steps, setting :math:`H_d = H_m` and use the same cost Hamiltonian, we will end up with
```suggestion
# If we run FALQON for :math:`p` steps, setting :math:`H_d = H_m`, and use the same cost Hamiltonian, we will end up with
```

2021-05-14 21:51 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# we set :math:`\alpha_k = \Delta t \beta_k` and :math:`\gamma_k = \Delta t`. We then optimize over these parameters. Our hope is that
```suggestion
# we set :math:`\alpha_k = \Delta t \beta_k` and :math:`\gamma_k = \Delta t`. We then optimize over these parameters. The goal is that
```

2021-05-14 21:52 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# technique, we will attempt to solve MaxClique on a slightly more complicated graph:
```suggestion
# technique, we attempt to solve MaxClique on a slightly more complicated graph:
```

2021-05-14 21:52 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# demonstration, we will set the depth to :math:`5`:
```suggestion
# demonstration, we set the depth to :math:`5`:
```

2021-05-14 21:52 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# We will set :math:`\Delta t = 0.02`:
```suggestion
# Now all we have to do is run FALQON for :math:`5` steps to get our initial QAOA parameters.
# We set :math:`\Delta t = 0.02`:
```

2021-05-14 21:53 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# Clearly, the state :math:`|112\rangle = |1110000\rangle` occurs with highest probability.
```suggestion
# The state :math:`|112\rangle = |1110000\rangle` occurs with highest probability.
```

2021-05-14 22:07 UTC, Lucaman99 commented on demonstrations/tutorial_falqon.py
> +over parameters, therefore avoiding the issue of local minima. We will show how to implement FALQON in PennyLane
This is true, although it avoids the issue to a large degree, at least empirically. The catch is massive circuit depth.

2021-05-14 22:08 UTC, Lucaman99 commented on demonstrations/tutorial_falqon.py
> +time-evolution operator corresponding to :math:`H`, given by :math:`U(t) = e^{-iHt}`, we will arrive at the ground state of :math:`H_c`.
Ah, true!

2021-05-17 19:43 UTC, glassnotes requested changes
@Lucaman99 @hapax This is a really neat demo! It's clear how much effort you've put into understanding the paper (and beyond!), so great work :100:

I've left a number of specific comments. As general feedback, I found especially the first section to be quite math heavy (though, well-explained!). I recommend to consider again each equation and remove any that aren't absolutely essential to explaining how things work. Another option to help break up the theory is to move the explanation and diagram of the FALQON algorithm earlier on, and use the algorithm itself to motivate the equations (i.e., show the diagram with the curvy arrows, and then explain that expectation values of these specific commutators are measured because it guarantees a strict decrease).

2021-05-17 19:43 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +want a system governed by such a Hamiltonian to evolve towards.
I found this sentence a bit confusing. It means to say here that tuning the choice of beta(t) affects the state that the system evolves towards? Won't the driver Hamiltonian also play a role?

2021-05-17 19:43 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +to the state :math:`|\psi\rangle`: the ground state of :math:`H_c`. Phrased differently, we would like to minimize
```suggestion
to the ground state of :math:`H_c`, which we denote by :math:`|\psi\rangle`. Phrased differently, we would like to minimize
```

Just to emphasize what the state conceptually is before giving it a label.

2021-05-17 19:43 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +Hamiltonians appear often in the theory of `quantum control <https://quantiki.org/wiki/quantum-control-theory>`__: a
```suggestion
Hamiltonians appear often in the theory of `quantum control <https://quantiki.org/wiki/quantum-control-theory>`__, a
```

2021-05-17 19:43 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +
```suggestion
by

.. math:: U(T) = \mathcal{T} \exp \Big[ -i \displaystyle\int_{0}^{T} H(t) \ dt \Big],
```

2021-05-17 19:43 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +for some small time-step :math:`\Delta t`. Thus, we will have:
```suggestion
for some small time step :math:`\Delta t`. Thus, we will have:
```

2021-05-17 19:43 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +to perform approximate time-evolution. We know that:
```suggestion
to perform approximate time-evolution. We know that
```

2021-05-17 19:43 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +For each layer of the time-evolution, we need to know the value :math:`\beta_k`. However,
```suggestion
For each layer of the time evolution, we need to know the value :math:`\beta_k`. However,
```

2021-05-17 19:43 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +We repeat for all :math:`k` from :math:`1` to :math:`n`. At the final step, we can evaluate :math:`\langle H_c \rangle`.
How is the number of steps, n, selected?

2021-05-17 19:43 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +#     :align: center
For these and other networkx drawings, it would be helpful to have the nodes a lighter colour so that the labels are more clearly visible.

2021-05-17 19:43 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +# We must first encode this combinatorial problem into a cost Hamiltonian :math:`H_c`. This ends up being:
```suggestion
# We must first encode this combinatorial problem into a cost Hamiltonian :math:`H_c`. This ends up being
```

2021-05-17 19:43 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +# .. math:: H_c = 3 \sum_{(i, j) \in E(\bar{G})} (Z_i Z_j - Z_i - Z_j) + \displaystyle\sum_{i \in V(G)} Z_i,
In the main text, define what \bar{G} is. This helps explain why it is computed in the Hamiltonian construction function below.

2021-05-17 19:43 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +# with our chosen :math:`\beta(t)`. We first define one layer of our Trotterized time-evolution, which is of
```suggestion
# with our chosen :math:`\beta(t)`. We first define one layer of our Trotterized time evolution, which is of
```

2021-05-17 19:43 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +    hamiltonian = build_commutator(graph) # Builds the commutator
Since `cost_h` and `driver_h` are defined, maybe keep with that convention and call this `commutator_h` or `comm_h` so it's clear which Hamiltonian it is.

2021-05-17 19:43 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +        print("Step {} Done, Cost = {}".format(i + 1, energy))
To save length, and since the results are going in a plot afterwards anyways, I recommend to remove the print statement.

2021-05-17 19:43 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +# value of :math:`H_c` may not strictly decrease. For this demonstration, we set :math:`\Delta t = 0.03`,
What is the motivation behind these choices?

2021-05-17 19:43 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +#
Might be nice to show a picture of the same graph, to remind the reader what it looks like, but with the max clique nodes in a different colour.

2021-05-17 19:43 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +# criteria. Let's see how FALQON performs on a batch of graphs! We generate graphs randomly using the
```suggestion
# criteria on a batch of graphs! We generate graphs randomly using the
```

2021-05-17 19:43 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +# as a function of layer. Due to computational constraints, we have averaged over :math:`3` random graphs per node
I think there needs to be a lot more random graphs to make this section valuable (now that I see it in context, the version I ran had only 5 per step, which is still very low). Where is the bottleneck in these simulations?

2021-05-17 19:43 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +#     :width: 60%
The metric \phi is not very intuitive because of the degeneracy; can it be normalized to between 0 and 1?

2021-05-17 19:43 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +# decreases with the number of layers, and also improves with graph size.
Why would the graph size have an effect on the results?

2021-05-17 19:43 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +# involve alternating layers of time-evolution operators corresponding to a cost and a mixer/driver Hamiltonian.
```suggestion
# involve alternating layers of time evolution operators corresponding to a cost and a mixer/driver Hamiltonian.
```

2021-05-17 19:43 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +# optimization problem 🎉.
This is an interesting application!

2021-05-17 19:43 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +print("Running QAOA")
I think this is out of scope for inclusion in the demo, but it could be interesting to explore and then discuss; can we quantify how much better it is to use initial parameters from FALQON rather than choosing them at random? Is the convergence time perhaps faster? If FALQON is resource intensive, what is the optimal number of FALQON layer that is likely to improve convergence? (Maybe just a few iterations is enough to show significant benefit?)

2021-05-17 19:43 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +While the
It might be worth adding a note somewhere in the introduction recommending that readers are familiar with QAOA before reading this demo (you can link to the Intro QAOA demo as a reference). Without that background, some of the theory especially might be tricky.

2021-05-17 19:43 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +# Seeding QAOA with FALQON (Bird Seed 🦅)
This appears to be something that is not explicitly in the paper, but just mentioned as a possible extension in the conclusion. I think it'd be worth briefly mentioning that here to differentiate this section from the demonstration of the original work.

2021-05-18 00:57 UTC, hapax commented on demonstrations/tutorial_falqon.py
> +# as a function of layer. Due to computational constraints, we have averaged over :math:`3` random graphs per node
For these small graphs, my computer, I would happy ask your computer for more :) For larger n, we need to tune Delta t more carefully to ensure the Trotterization works, which is a pain and will slow it down.

2021-05-18 12:54 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +# as a function of layer. Due to computational constraints, we have averaged over :math:`3` random graphs per node
Feel free to shoot over another script and I can run it. Also, since the problems are independent, it may also be helpful to add some simple multiprocessing to parallelize it, either at the level of n, or the graph instances themselves (4-6 threads is reasonable and would go a long way towards speeding things up).

2021-05-20 13:48 UTC, Lucaman99 commented on demonstrations/tutorial_falqon.py
> +want a system governed by such a Hamiltonian to evolve towards.
Well, yes, but it's best to think about the driver playing the role analogous to the mixer in QAOA. We don't really think of the mixer itself as determining which state QAOA evolves towards, that is the job of the parameters and the cost Hamiltonian. Nevertheless, we could make a bit more clear 👍

2021-05-20 14:02 UTC, Lucaman99 commented on demonstrations/tutorial_falqon.py
> +    hamiltonian = build_commutator(graph) # Builds the commutator
Sure!

2021-05-20 14:16 UTC, Lucaman99 commented on demonstrations/tutorial_falqon.py
> +# value of :math:`H_c` may not strictly decrease. For this demonstration, we set :math:`\Delta t = 0.03`,
Well, the choice of beta_1 is pretty arbitrary, so setting it to 0 just makes sense. As for n and delta_t, they just work 🤷 . It is possible to derive exactly what delta_t should be such that the expectation value strictly decreases, but that just seemed too complicated for this tutorial.

2021-05-20 14:19 UTC, Lucaman99 commented on demonstrations/tutorial_falqon.py
> +print("Running QAOA")
Yeah, this would be very cool, especially since it is not explored at all in the paper. However, I think you're right: it's outside the scope of this tutorial. Perhaps we could look into it in the future though!

2021-05-20 14:38 UTC, Lucaman99 commented on demonstrations/tutorial_falqon.py
> +# Seeding QAOA with FALQON (Bird Seed 🦅)
I see, what do you think we should say?

2021-05-20 22:15 UTC, ixfoduap requested changes
Fantastic tutorial! Congratulations to the authors :medal_sports: :medal_sports: 

I made a few suggestions as a final round of polish. Once they are addressed, I'm happy to approve :eagle:

2021-05-20 22:15 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +        # Creates a function which returns the expectation value of the cost Hamiltonian
```suggestion
        # Creates a function that returns the expectation value of the cost Hamiltonian
```

2021-05-20 22:15 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +        # Creates a function which can evaluate the expectation value of the commutator
```suggestion
        # Creates a function that can evaluate the expectation value of the commutator
```

2021-05-20 22:15 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# As expected, the expectation value decreases!
```suggestion
# The expectation value decreases!
```
I don't like "as expected, the expectation value"

2021-05-20 22:15 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# we can create a graph showing the probability of measuring each possible bitstring. We define
```suggestion
# we can create a graph showing the probability of measuring each possible bitstring. We define the
```

2021-05-20 22:15 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# FALQON has solved the MaxClique problem!
Good place for an emoji, if you want to add one :tada:

2021-05-20 22:15 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# criteria on a batch of graphs! We generate graphs randomly using the
```suggestion
# criteria on a batch of graphs. We generate graphs randomly using the
```

2021-05-20 22:15 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# The rate of decrease also slows. Even though the algorithm will converge to the ground state,
```suggestion
# The rate of decrease also slows down. Even though the algorithm will converge to the ground state,
```

2021-05-20 22:15 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# no one said anything about how quickly it gets there!
Maybe you should have said something? :wink:

2021-05-20 22:15 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# how the reduction in cost slows with layer, and the additional burden of correctly tuning the time step. On the other hand, QAOA
```suggestion
# how the reduction in cost slows with each layer, and the additional burden of correctly tuning the time step. On the other hand, QAOA
```
or maybe "slows with the number of layers"

2021-05-20 22:15 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# how the reduction in cost slows with layer, and the additional burden of correctly tuning the time step. On the other hand, QAOA
```suggestion
# how the reduction in cost slows with each layer, and the additional burden of correctly tuning the time step. On the other hand, QAOA
```
or maybe "slows with the number of layers"

2021-05-20 22:15 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# leverages the benefits of both! In this final section of the tutorial, we will implement this procedure in PennyLane.
```suggestion
# leverages the benefits of both. In this final section of the tutorial, we will implement this procedure in PennyLane.
```
I feel there are too many exclamation marks in this section! AT LEAST YOU ARE NOT USING CAPS!

2021-05-20 22:15 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# .. math:: U_{\text{QAOA}} = e^{-i \alpha_p H_m} e^{-i \gamma_p H_c} \cdots e^{-i \alpha_1 H_m} e^{-i \gamma_1 H_c}
```suggestion
# .. math:: U_{\text{QAOA}} = e^{-i \alpha_p H_m} e^{-i \gamma_p H_c} \cdots e^{-i \alpha_1 H_m} e^{-i \gamma_1 H_c},
```

2021-05-21 15:12 UTC, ixfoduap commented on demonstrations/tutorial_falqon.py
> +# there in few time steps!
```suggestion
# there in a few time steps!
```

2021-05-21 15:12 UTC, ixfoduap approved these changes
:shipit:

2021-05-21 17:08 UTC, glassnotes approved these changes
@Lucaman99 @hapax this looks great! 

Just a couple typos and minor wording suggestions. Once addressed, remember to change the dates, and then we can merge it in :tada:

2021-05-21 17:08 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +# The authors of the FALQON paper therefore suggest combining FALQON and QAOA to yield a new optimization algorithm that
```suggestion
# The FALQON paper raises the idea of combining FALQON and QAOA to yield a new optimization algorithm that
```
(The original phrasing sounded like there was a discussion with the authors, but here it's just that the idea is  stated in the paper)

2021-05-21 17:08 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +# Suppose we want to run a QAOA circuit of depth :math:`p`. Our ansatz will be of the form:
```suggestion
# Suppose we want to run a QAOA circuit of depth :math:`p`. Our ansatz will be of the form
```

2021-05-21 17:08 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +print("Running FALQON")
```suggestion
```

2021-05-21 17:08 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +print("Running FALQON")
Perhaps print the resulting params instead (or just leave with no output)

2021-05-21 17:08 UTC, glassnotes commented on demonstrations/tutorial_falqon.py
> +print("Running QAOA")
```suggestion
```

2021-05-21 17:52 UTC, merged