[WIP] Add demonstration for kernels module
PennyLaneAI/qml pull request #266
Opened 2021-05-12 14:35 UTC by johannesjmeyer

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Add a thumbnail link to your tutorial in `beginner.rst`, or if a
      QML implementation, in `implementations.rst`.

- [ ] All QML tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**
Quantum Embedding Kernels with PennyLane's kernels module

**Summary:**
It is demonstrated how PennyLane's kernels module can be used to simplify the implementation of quantum embedding kernels.

**Relevant references:**
[Associated QHACK submission](https://github.com/thubregtsen/qhack)
[Associated preprint arXiv:2105.02276](https://arxiv.org/abs/2105.02276)

2021-05-12 15:01 UTC, josh146 commented
@johannesjmeyer feel free to modify the `requirements.txt` file to install PennyLane from your branch so that the demo builds!

2021-05-12 15:46 UTC, johannesjmeyer commented
@josh146, if I run 
``` 
return kernel_circuit(x1, x2, params)[0]
```
where the `kernel_circuit` returns `qml.probs()`, I get a `TypeError: 'MeasurementProcess' object is not subscriptable`. How do I mitigate this?

2021-05-12 15:47 UTC, josh146 commented
@johannesjmeyer, it sounds like `kernel_circuit` hasn't had the QNode decorator applied? As it is returning a 'bare' `qml.MeasurementProcess` rather than an array of numeric values

2021-05-12 15:48 UTC, johannesjmeyer commented
> @johannesjmeyer, it sounds like `kernel_circuit` hasn't had the QNode decorator applied? As it is returning a 'bare' `qml.MeasurementProcess` rather than an array of numeric values

Thanks, stupid mistake!

2021-06-04 20:58 UTC, co9olguy commented
Hi @johannesjmeyer, what is the status of this demo? We're super excited to have the kernels module in the next release (coming mid-June), so it would be awesome to have the demo come sometime near that if possible

2021-06-07 12:23 UTC, johannesjmeyer commented
@co9olguy I just realized that we have to add a fix to PL core to make the demo work, I'll do that. Otherwise the demo is more or less in shape I would say.

2021-06-07 14:04 UTC, co9olguy commented
@johannesjmeyer I think the ideal landing spot for a general-purpose non-quantum mathematical function is in `qml.math`. This will allow it to not only be automatically differentiable, but also make AD possible with every ML framework

@josh146 can comment more if he has more thoughts

2021-06-07 15:05 UTC, johannesjmeyer commented
Great, `qml.math` sounds like the right place! See https://github.com/PennyLaneAI/pennylane/pull/1388.

2021-06-24 14:01 UTC, dwierichs commented
I think this might be ready for review now. The example is not perfect by means of dataset complexity but previously the demo was running for quite a long time (still 7 minutes now for the updated reduced size). On the other hand, the benefit of alignment training is showcased and the functionalities are there.

2021-06-24 14:01 UTC, josh146 commented
Thanks @dwierichs and @johannesjmeyer!

2021-06-25 05:49 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +linear classification.
I would tell a reader more what to expect here...the header may help advanced users to jump to the next section.

```suggestion
Kernel methods are one of the cornerstones of classical machine
learning. This tutorial will introduce the basic functionality of PennyLane's  
[kernels module](https://pennylane.readthedocs.io/en/latest/code/qml_kernels.html). 

What are kernel methods?
-----------------------------------

To understand what a kernel method does, let’s first revisit
one of the simplest methods to assign binary labels to datapoints:
linear classification.
```

2021-06-25 05:50 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +can’t be treated.
```suggestion
can’t be classified without error.
```
Maybe more accurate?

2021-06-25 05:51 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +We call this function the *kernel*. The clue now is that we can often
```suggestion
We call this function the *kernel*. The important point is that we can often
```

Lol, I _think_ this is an exclusively German formulation.

2021-06-25 05:53 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +will be much more costlier to compute than the kernel :math:`k`.
```suggestion
will be much costlier to compute than the kernel :math:`k`.
```

2021-06-25 05:54 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +of the PennyLane ``kernels`` module implemented alongside with it.
Maybe remove that sentence and add the reference to the first sentence, so readers know this important paper from the start?

2021-06-25 05:55 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +# inner workings of our approach and the available functionalities
Maybe not clear here what "our approach" is: the idea of a kernel trick, or something you want to do in the demo?

2021-06-25 05:58 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +# class itself.
```suggestion
# plotting method. The details of the class are not important 
# to understand the remainder of the demo, so do not worry if it confuses you.
```
Maybe this is less negative?

2021-06-25 05:58 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +# need for this is an *Ansatz* that represents the unitary
```suggestion
# need for this is an *ansatz* that represents the unitary
```
not sure, but feels better

2021-06-25 05:58 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +# :math:`U(\boldsymbol{x})` we use for embedding the data into a quantum
```suggestion
# :math:`U(\boldsymbol{x})` we use to embed the data into a quantum
```

2021-06-25 05:59 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +# state as well as its adjoint :math:`U(\boldsymbol{x})^\dagger`.
```suggestion
# state, as well as its adjoint :math:`U(\boldsymbol{x})^\dagger`.
```

2021-06-25 06:31 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +# PennyLane’s ``kernels`` module allows for a particularly simple
Link to module? I immediately clicked the highlight, and there was this slightly disappointed feeling that comes with links not being links :)

2021-06-25 06:53 UTC, mariaschuld requested changes
Very cool, thanks so much for this great contribution. 

The demo is of a top quality already, and you'll find that all my suggestions are minor. The only ones that are important are to divide the first part into intro sentence and a new section, if possible to avoid using the template decorator, and to explain or reference an explanation for the kernel circuit.

Great work!

2021-06-25 06:53 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +@qml.template
I am wondering if one could simply delete this? We are kind of phasing this decorator out (unless it gets repurposed some time). `adjoint` should work without it!

2021-06-25 06:53 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +# Together with the Ansatz we only need a device to run the quantum circuit on.
```suggestion
# Together with the ansatz we only need a device to run the quantum circuit on.
```

2021-06-25 06:53 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +# For the purposes of this tutorial we will use PennyLane’s ``default.qubit``
```suggestion
# For the purpose of this tutorial we will use PennyLane’s ``default.qubit``
```

2021-06-25 06:53 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +    return qml.probs(wires=wires)
We now have a [projector observable](https://pennylane.readthedocs.io/en/latest/code/api/pennylane.Projector.html) :)  

Up to you if you want to use it, but could be cool.

Alternatively (or additionally) you could link the [other kernels](https://pennylane.ai/qml/demos/tutorial_kernel_based_training.html) demo here, where the logic of this adjoint circuit is explained with an equation, and the projector is used. Or add a note to clarify that there are different options?

2021-06-25 06:53 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +# Ansatz circuit to :math:`6`.
```suggestion
# ansatz circuit to :math:`6`.
```

2021-06-25 06:53 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +# Once we have this, we can let scikit adjust the SVM from our Quantum Embedding
```suggestion
# Once we have this, we can let scikit-learn adjust the SVM from our Quantum Embedding
```

2021-06-25 06:53 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +#     this step does *not* modify the variational parameters in our circuit
```suggestion
#     This step does *not* modify the variational parameters in our circuit
```

2021-06-25 06:53 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +#     :math:`\alpha` and :math:`b` vectors we introduced in the beginning.
Nice that you explain this, people get quite confused.

2021-06-25 06:53 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +    return qml.probs(wires=wires)
I think the link will be important because even advanced people sometimes get confused about this structure of the circuit.

2021-06-25 06:53 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +# -------------------------------------
Just a thought: Do you want to advertise this much higher up, maybe in the first sentence or even the title? This may increase clicks by a factor 10, people _love_ blindly training things, and kernels may be the next big thing to blindly train :)

2021-06-25 06:53 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +#     to objects, namely two kernels, being aligned in a vector space.
Interesting!

2021-06-25 06:53 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +#    k_{\boldsymbol{y}}(\boldsymbol{x}_i, \boldsymbol{x}_j) = y_i y_j
```suggestion
#    k_{\boldsymbol{y}}(\boldsymbol{x}_i, \boldsymbol{x}_j) = y_i y_j.
```

2021-06-25 06:53 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +#    k_{\boldsymbol{y}}(\boldsymbol{x}_i, \boldsymbol{x}_j) = y_i y_j
I am suddenly wondering if there should be punctuation in the equations? Ignore if not sure!

2021-06-25 06:53 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +# bring optimal training accuracy with it.
Great comment!

2021-06-25 06:53 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +#     We therefore first define a differentiable version of this function.
Just curious, could we simply rewrite it using the `qml.math` module?

2021-06-25 06:53 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +).fit(dataset.X, dataset.Y)
I wonder if it's worth breaking this up. I know lambda functions are pretty for those who know them, but beginners usually find them confusing. And even I had to state hard at the nested structure...

(Optional)

2021-06-25 06:58 UTC, josh146 requested changes
Agree with @mariaschuld, the content of the demo is very solid. My only main recommendation for improvement is structural; motivating what the demo will show/achieve early on, and breaking it into sections to help tell the story.

Other than that, my other suggestions are minor!

2021-06-25 06:58 UTC, josh146 commented on demonstrations/tutorial_kernel_module.py
> +=====================================================
I'm not too fussed either way, but we could shorten the title to simply "Quantum embedding kernels", and have use of the kernel module be implicit?

2021-06-25 06:58 UTC, josh146 commented on demonstrations/tutorial_kernel_module.py
> +linear classification.
Agree, was just about to suggest this 💯

2021-06-25 06:58 UTC, josh146 commented on demonstrations/tutorial_kernel_module.py
> +linear classification.
In terms of the summary/intro, could add

- an additional sentence inbetween the two, making note of the *quantum* nature of the tutorial
- extend the final sentence, so that a reader knows what the demo will achieve
- the paper this is based on.

```markdown
Kernel methods are one of the cornerstones of classical machine
learning. Something something extends to quantum.
This tutorial will introduce the basic functionality of PennyLane's  
[kernels module](https://pennylane.readthedocs.io/en/latest/code/qml_kernels.html)
by exploring...
```

2021-06-25 06:58 UTC, josh146 commented on demonstrations/tutorial_kernel_module.py
> +   :width: 30%
I love the drawings!

2021-06-25 06:58 UTC, josh146 commented on demonstrations/tutorial_kernel_module.py
> +can’t be treated.
(throughout this file): I recommend replacing unicode quotation marks with ASCII ones:
```suggestion
can't be treated.
```

There have been issues in the past with users on Windows attempting to run the demos, but experiencing invalid encoding errors.

2021-06-25 06:58 UTC, josh146 commented on demonstrations/tutorial_kernel_module.py
> +   k(\boldsymbol{x}, \boldsymbol{y}) = x_1^2 y_1^2 + 2 x_1 x_2 y_1 y_2 + x_2^2 y_2^2 = \langle \boldsymbol{x}, \boldsymbol{y} \rangle^2
```suggestion
.. math::
   \phi((x_1, x_2)) = (x_1^2, \sqrt{2} x_1 x_2, x_2^2), \qquad
   k(\boldsymbol{x}, \boldsymbol{y}) = x_1^2 y_1^2 + 2 x_1 x_2 y_1 y_2 + x_2^2 y_2^2 = \langle \boldsymbol{x}, \boldsymbol{y} \rangle^2.
```

2021-06-25 06:58 UTC, josh146 commented on demonstrations/tutorial_kernel_module.py
> +   k(\boldsymbol{x}, \boldsymbol{y}) = x_1^2 y_1^2 + 2 x_1 x_2 y_1 y_2 + x_2^2 y_2^2 = \langle \boldsymbol{x}, \boldsymbol{y} \rangle^2
Might be better to split this over two lines with `\\` rather than `\qquad`, for mobile users :)

2021-06-25 06:58 UTC, josh146 commented on demonstrations/tutorial_kernel_module.py
> +of the PennyLane ``kernels`` module implemented alongside with it.
Agree

2021-06-25 06:58 UTC, josh146 commented on demonstrations/tutorial_kernel_module.py
> +import matplotlib.pyplot as plt
Minor point, but we have slowly started preferring placing the imports directly above the first code-blocks that require them. This serves two purposes:

- Pedagogically, readers can more easily associate the imports with the portions of the code that use them
- If a reader can't easily install or use a third party dependency (such as matplotlib), they are not limited from running earlier parts of the demo

2021-06-25 06:58 UTC, josh146 commented on demonstrations/tutorial_kernel_module.py
> +@qml.template
The `qml.template` decorator is no longer required/used internally, so you can safely remove it.

2021-06-25 06:58 UTC, josh146 commented on demonstrations/tutorial_kernel_module.py
> +# the datapoint :math:`\boldsymbol{x}`.
I would place this directly before the `ansatz` code definition, for two reasons:

- breaks up the large code block
- the description of the code is closer to the code :)

2021-06-25 06:58 UTC, josh146 commented on demonstrations/tutorial_kernel_module.py
> +    return qml.probs(wires=wires)
```suggestion
    adjoint_ansatz(x2, params, wires=wires)
    return qml.probs(wires=wires)
```

2021-06-25 06:58 UTC, josh146 commented on demonstrations/tutorial_kernel_module.py
> +# of the ordering in `qml.probs`, this is the first entry:
```suggestion
# of the ordering in ``qml.probs``, this is the first entry:
```

2021-06-25 06:58 UTC, josh146 commented on demonstrations/tutorial_kernel_module.py
> +# for our noiseless simulation. To include the variational parameters, we
I assume it then only computes the k-1 upper-triangular portion of the matrix?

2021-06-25 06:58 UTC, josh146 commented on demonstrations/tutorial_kernel_module.py
> +#     this step does *not* modify the variational parameters in our circuit
```suggestion
#     This step does *not* modify the variational parameters in our circuit
```

2021-06-25 06:58 UTC, josh146 commented on demonstrations/tutorial_kernel_module.py
> +#     We therefore first define a differentiable version of this function.
Ah, I suppose we should open a github issue for this :)

2021-06-25 06:58 UTC, josh146 commented on demonstrations/tutorial_kernel_module.py
> +#     We therefore first define a differentiable version of this function.
Or is this covered by making `frobenius_inner_product` differentiable?

2021-06-25 06:58 UTC, josh146 commented on demonstrations/tutorial_kernel_module.py
> +        print(f"Step {i+1} - Alignment = {current_alignment:.3f}")
I admit I am surprised - I expected an alignment close to 1 for an accuracy of 1. Or am I thinking about it incorrectly?

2021-06-25 06:58 UTC, josh146 commented on demonstrations/tutorial_kernel_module.py
> +# Very well! We now achieved perfect classification!
```suggestion
# We have now achieved perfect classification! 🎆 
```

(Very well sounds a bit off to me. I tend to hear it more 'negatively'. E.g., 'Very well, I _won't_ do that 😠 ')

2021-06-25 06:58 UTC, josh146 commented on demos_research.rst
> +    :tags: kernels alignment classification
Thumbnail looks great!

2021-06-25 06:59 UTC, josh146 commented on demonstrations/tutorial_kernel_module.py
> +# class itself.
Alternatively, it might make it easier to follow by splitting the class into three functions? I admit, I cannot see too much motivation for it being a class?

2021-06-25 07:00 UTC, josh146 commented on demonstrations/tutorial_kernel_module.py
> +#     this step does *not* modify the variational parameters in our circuit
😆 I think @mariaschuld and I reviewed at the same time

2021-06-25 07:01 UTC, josh146 commented on demonstrations/tutorial_kernel_module.py
> +# -------------------------------------
I agree with placing this in the title!

2021-06-25 07:01 UTC, josh146 commented on demonstrations/tutorial_kernel_module.py
> +#     We therefore first define a differentiable version of this function.
yep! That is currently occurring in https://github.com/PennyLaneAI/pennylane/pull/1388

2021-06-25 07:14 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +=====================================================
I would vote for "Training and evaluating quantum kernels" (since this will wake a lot of interest).

Also, consider dropping "Embedding" from the title. I am in full favour for the specification during the demo, but since it is not known in the literature, it adds no information to 99% of the readers, while potentially confusing them.

2021-06-25 07:52 UTC, dwierichs commented on demonstrations/tutorial_kernel_module.py
> +We call this function the *kernel*. The clue now is that we can often
Good catch :D

2021-06-25 08:36 UTC, dwierichs commented on demonstrations/tutorial_kernel_module.py
> +    return qml.probs(wires=wires)
I'd suggest not to change it in order to have variety in the demos, but the link works super nicely here I think :)
Or do we prefer to have the demos use the same circuit structure?

2021-06-25 08:40 UTC, dwierichs commented on demonstrations/tutorial_kernel_module.py
> +#    k_{\boldsymbol{y}}(\boldsymbol{x}_i, \boldsymbol{x}_j) = y_i y_j
I think there should :) Good catch!

2021-06-25 08:40 UTC, mariaschuld commented on demonstrations/tutorial_kernel_module.py
> +    return qml.probs(wires=wires)
No, I totally agree about the variety.

2021-06-25 08:45 UTC, dwierichs commented on demonstrations/tutorial_kernel_module.py
> +=====================================================
Conceptually I find "Evaluating and training .. " better, but I "Training and evaluating.." sounds better to me. Any thought on that? :)

2021-06-25 08:46 UTC, dwierichs commented on demonstrations/tutorial_kernel_module.py
> +   :width: 30%
Me too! @johannesjmeyer :)

2021-06-25 08:54 UTC, dwierichs commented on demonstrations/tutorial_kernel_module.py
> +# for our noiseless simulation. To include the variational parameters, we
Added some details on this.

2021-06-25 09:48 UTC, dwierichs commented on demonstrations/tutorial_kernel_module.py
> +#     We therefore first define a differentiable version of this function.
Yes, it is :) This is where the fact that `frobenius_inner_product` isn't diffable became relevant in the first place :)

2021-06-25 09:49 UTC, dwierichs commented on demonstrations/tutorial_kernel_module.py
> +        print(f"Step {i+1} - Alignment = {current_alignment:.3f}")
It often does not optimize that far. IIRC we never saw alignments `>0.5` when working on qhack/the paper

2021-06-25 10:39 UTC, dwierichs commented
All proposed changes should be implemented now. I also moved the names to kernel**s**_module to match the module namespace.

2021-06-25 12:16 UTC, johannesjmeyer commented on demonstrations/tutorial_kernel_module.py
> +        print(f"Step {i+1} - Alignment = {current_alignment:.3f}")
An alignment of 1 essentially means that all training datapoints of the same class get mapped to the same state, so a value much lower than 1 is expected :)

2021-06-25 12:16 UTC, johannesjmeyer commented
Thanks again @dwierichs for finishing this off so well, I'm sorry that I didn't manage to pull through with this...

2021-06-25 12:58 UTC, dwierichs commented
All good @johannesjmeyer ! Given the diffability PR and the previous state of the demo, this was a :cake:

2021-06-28 06:08 UTC, josh146 commented on demonstrations/tutorial_kernel_module.py
> +        print(f"Step {i+1} - Alignment = {current_alignment:.3f}")
Got it :)

2021-06-28 06:52 UTC, mariaschuld commented on demonstrations/tutorial_kernels_module.py
> +`qhack <https://qhack.ai/>`__ hackathon.
Nice!

2021-06-28 06:52 UTC, mariaschuld commented on demonstrations/tutorial_kernels_module.py
> +Embedding Kernels (QEKs)*. These are kernels that arise from embedding
Nice introduction of the term!

2021-06-28 06:54 UTC, mariaschuld commented on demonstrations/tutorial_kernels_module.py
> +plot_double_cake_data(X, Y, plt.gca(), num_sectors=num_sectors);
Not blocking, but I wonder if `%inlineplot` would avoid the dummy output here:

![Uploading Screenshot from 2021-06-28 08-53-41.png…]()

2021-06-28 06:55 UTC, mariaschuld commented on demonstrations/tutorial_kernels_module.py
> +#     background information on the kernel circuit structure itself.
Very nice!

2021-06-28 06:57 UTC, mariaschuld commented on demonstrations/tutorial_kernels_module.py
> +# distrust the model. In this sense, our approach benefits from both: On
```suggestion
# distrust the model. In this sense, our approach benefits from both: on
```
Took me years of code review to internalise that opposed to German, English spelling lower cases here... :)

2021-06-28 06:59 UTC, mariaschuld approved these changes
Very cool, the last changes make it even better! 

I only have non-blocking comments.

2021-06-28 07:48 UTC, josh146 approved these changes
Great work, I love the new title and slight structure modifications!

2021-06-28 07:48 UTC, josh146 commented on demonstrations/tutorial_kernels_module.py
> +`qhack <https://qhack.ai/>`__ hackathon.
```suggestion
`QHack <https://qhack.ai/>`__ hackathon.
```

2021-06-28 07:48 UTC, josh146 commented on demonstrations/tutorial_kernels_module.py
> +thus determine its slope. The independent term :math:`b` specificies the
```suggestion
thus determine its slope. The independent term :math:`b` specifies the
```

2021-06-28 07:48 UTC, josh146 commented on demonstrations/tutorial_kernels_module.py
> +data into the space of quantum states. We formalize this by considering
Optional: I tend to prefer bolding new terms, since it stands out more than italics.

```suggestion
that can be realized on near-term quantum computers, namely **Quantum
Embedding Kernels (QEKs)**. These are kernels that arise from embedding
data into the space of quantum states. We formalize this by considering
```

2021-06-28 07:48 UTC, josh146 commented on demonstrations/tutorial_kernels_module.py
> +# so don't mind them if they are confusing.
```suggestion
# ``DoubleCake`` dataset. Firstly, we define two functions to enable us to
# generate the data.
# The details of these functions are not essential for understanding the demo,
# so don't mind them if they are confusing.
```

2021-06-28 07:48 UTC, josh146 commented on demonstrations/tutorial_kernels_module.py
> +def plot_double_cake_data(X, Y, ax, num_sectors=None):
```suggestion

##############################################################################
# Next, we define a function to help plot the ``DoubleCake`` data
# and classification boundaries:

def plot_double_cake_data(X, Y, ax, num_sectors=None):
```

2021-06-28 07:48 UTC, josh146 commented on demonstrations/tutorial_kernels_module.py
> +def plot_double_cake_data(X, Y, ax, num_sectors=None):
Optional, but breaks up the big code block :)

2021-06-28 07:48 UTC, josh146 commented on demonstrations/tutorial_kernels_module.py
> +plot_double_cake_data(X, Y, plt.gca(), num_sectors=num_sectors);
I'm not sure if `%inlineplot` works in Sphinx gallery 🤔

2021-06-28 07:48 UTC, josh146 commented on demonstrations/tutorial_kernels_module.py
> +#     background information on the kernel circuit structure itself.
We should update the kernel based training demo to use the new `qml.Projector` - it would probably make it a bit faster as well!

2021-06-28 07:48 UTC, josh146 commented on demonstrations/tutorial_kernels_module.py
> +    print(K_init)
Didn't know this could be used as a context 🤯

2021-06-28 07:48 UTC, josh146 commented on demonstrations/tutorial_kernels_module.py
> +# datapoints at random. Remember that PennyLane's inbuilt optimizer works
```suggestion
# datapoints at random. Remember that PennyLane's built-in optimizer works
```

2021-06-28 07:48 UTC, josh146 commented on demonstrations/tutorial_kernels_module.py
> +# datapoints at random. Remember that PennyLane's inbuilt optimizer works
Weirdly, I think 'inbuilt' is a common Australia/British English term, but _not_ a common Canadian English term 😆 I myself have been guilty of using it in other demos and confusing our resident Canadians.

2021-06-28 07:48 UTC, josh146 commented on demonstrations/tutorial_kernels_module.py
> +#     “Training Quantum Embedding Kernels on Near-Term Quantum Computers.”
```suggestion
#     "Training Quantum Embedding Kernels on Near-Term Quantum Computers."
```

2021-06-28 07:48 UTC, josh146 commented on demonstrations/tutorial_kernels_module.py
> +#     “An overview of kernel alignment and its applications.”
```suggestion
#     "An overview of kernel alignment and its applications."
```

2021-06-28 07:55 UTC, dwierichs commented on demonstrations/tutorial_kernels_module.py
> +#     background information on the kernel circuit structure itself.
Ah, does it not do so yet? :) I assumed this, so that there would be a demo using `qml.Projector` and one that doesn't.

2021-06-28 07:55 UTC, dwierichs commented on demonstrations/tutorial_kernels_module.py
> +# distrust the model. In this sense, our approach benefits from both: On
I'm definitely in the early stages of that process: still not liking it :D

2021-06-28 07:57 UTC, dwierichs commented on demonstrations/tutorial_kernels_module.py
> +def plot_double_cake_data(X, Y, ax, num_sectors=None):
Very nice! :)

2021-06-28 07:57 UTC, josh146 commented on demonstrations/tutorial_kernels_module.py
> +#     background information on the kernel circuit structure itself.
It does it conceptually, but not in practice; it uses `qml.Hermitian` and a projector matrix 😆 Should be a relatively small update, we could even make a GitHub issue and mark it as 'good first issue'

2021-06-28 08:05 UTC, dwierichs commented on demonstrations/tutorial_kernels_module.py
> +plot_double_cake_data(X, Y, plt.gca(), num_sectors=num_sectors);
No, unfortunately the line magic functionality does not seem to be supported. [This](https://matplotlib.org/sampledoc/extensions.html) extensions summary might contain something for this, but I think that's not worth it at this point.

2021-06-28 08:05 UTC, dwierichs commented on demonstrations/tutorial_kernels_module.py
> +#     background information on the kernel circuit structure itself.
Ah, I see :) Perfect! I could take care of this, if you want.

2021-06-28 08:47 UTC, dwierichs commented
That should be all, @mariaschuld @josh146  :-)

2021-07-12 21:33 UTC, co9olguy commented
Going live in 3...2...1 :rocket:

2021-07-12 21:33 UTC, merged