Add tutorial on molecular geometry optimization
PennyLaneAI/qml pull request #267
Opened 2021-05-14 22:23 UTC by agran2018

WIP: Add tutorial showing how to optimize molecular geometries using PennyLane.

2021-05-21 16:13 UTC, ixfoduap requested changes
The tutorial is in great shape already! Awesome work!

Besides stylistic suggestions, my main comment is that the current version is trying to explain too much about other aspects, rather than concentrating on the algorithm for geometry optimization. This makes the text harder to read and thus we are vulnerable to losing the reader's interest

2021-05-21 16:13 UTC, ixfoduap commented on demonstrations/tutorial_mol_geo_opt.py
> +# Setting the angles :math:`\theta_1` and :math:`\theta_2` to zero implies that
Better to say this before the code that initializes the angles! Also, keep Hartree-Fock without the (HF)

2021-05-21 16:13 UTC, ixfoduap commented on demonstrations/tutorial_mol_geo_opt.py
> +# This is a natural choice for the starting geometry that we are aiming to correct
```suggestion
# This is a natural choice for the starting geometry that we are aiming to improve
```

2021-05-21 16:13 UTC, ixfoduap commented on demonstrations/tutorial_mol_geo_opt.py
> +# (in Angstroms) of trihydrogen cation through the iterative procedure.
```suggestion
# (in Angstroms) through the iterative procedure.
```

2021-05-21 16:13 UTC, ixfoduap commented on demonstrations/tutorial_mol_geo_opt.py
> +for n in range(100):
Good to add some comments to the code

2021-05-21 18:56 UTC, glassnotes reviewed
I haven't gone too in depth yet, I've just left some comments from the first read through. I think the example problem is really interesting and accessible! :atom_symbol:  Most of my comments relate to streamlining the text to make things less dense, and adding more direction.

2021-05-21 18:56 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +molecule :math:`E(x)` depends on the nuclear coordinates :math:`x` which defines
```suggestion
molecule :math:`E(x)` depends on the nuclear coordinates :math:`x` which define
```

2021-05-21 18:56 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +triangle whose side length is the optimized H-H bond length :math:`d`.
```suggestion
geometry in the electronic ground state corresponds to the minimum energy of the PES. At this minimum, the three hydrogen atoms are located at the vertices of an equilateral
triangle whose side length is the optimized H-H bond length :math:`d`.
```

2021-05-21 18:56 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +In practice, `density functional theory <https://en.wikipedia.org/wiki/ensity_functional_theory>`_ methods [#dft_book]_ are used to obtain approximated geometries.
```suggestion
In practice, `density functional theory <https://en.wikipedia.org/wiki/Density_functional_theory>`_ methods [#dft_book]_ are used to obtain approximate geometries.
```

2021-05-21 18:56 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +
The intro is currently quite long, and there is a lot of discussion before the part that explains what is actually being done in the demo ("In this tutorial you will learn how to recast..."). 

I recommend to rework and streamline the intro into a series of smaller paragraphs, such that a concise description of the demo contents comes in the second paragraph, even if it needs to be a more high-level, conceptual one. Then, one can discuss the classical algorithm, and give a deeper overview of the quantum algorithm (this can even go in a new section).

2021-05-21 18:56 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +Here we demonstrate how to use PennyLane functionalities to implement a
Consider moving this sequence of steps out of the intro, and putting it in the next section to use as preamble for the implementation.

2021-05-21 18:56 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +# the wave function of this molecule requires six qubits to encode the occupation number
```suggestion
# :math:`\vert \Psi(\theta)\rangle` of the :math:`\mathrm{H}_3^+` molecule. 
# Six qubits are required to encode the occupation number
```

2021-05-21 18:56 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +#. Define the molecule for which we want to find the equilibrium geometry.
Later on in the demo, refer back to this list. For example, in the next section, discuss how we are addressing steps 1 and 2. In the section after that, mention that we are now on step 3, etc. This helps provide direction to the reader.

2021-05-21 18:56 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +# circuit parameters ``params`` and the nuclear coordinates ``x``.
```suggestion
```
I think this paragraph can be removed, as the lines before the code block explain what is happening.

2021-05-21 18:56 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +# the circuit and the Hamiltonian parameters during the iterative optimization.
```suggestion
```

2021-05-21 18:56 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +# We carry out the optimization over a maximum of 100 steps. In this example
```suggestion
# We carry out the optimization over a maximum of 100 steps. 
```

2021-05-21 18:56 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +for n in range(100):
I second this. There are also a number of places where algorithmic components are described in the text, e.g., "we use the lists `energy` and `bond_length` to keep track". Some of these can be repurposed as code comments to both streamline the text, and improve readability of the code.

2021-05-21 18:56 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +            "Iteration = {:},  Energy = {:.8f} Ha,  bond length = {:.5f} A".format(
Using `f` strings for printing here might save some space.

2021-05-21 18:56 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +#     :width: 50%
This is such a cool movie!

2021-05-21 18:56 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +# To summarize, this tutorial shows that the scope of variational quantum algorithms can be
```suggestion
# To summarize, we've shown how the scope of variational quantum algorithms can be
```

2021-05-25 16:42 UTC, agran2018 commented on demonstrations/tutorial_mol_geo_opt.py
> +In practice, `density functional theory <https://en.wikipedia.org/wiki/ensity_functional_theory>`_ methods [#dft_book]_ are used to obtain approximated geometries.
Yes, we can.

2021-05-25 16:45 UTC, agran2018 commented on demonstrations/tutorial_mol_geo_opt.py
> +Here we demonstrate how to use PennyLane functionalities to implement a
Nice!

2021-05-25 16:48 UTC, agran2018 commented on demonstrations/tutorial_mol_geo_opt.py
> +# (:math:`\mathrm{H}_3^+`) consisted of three hydrogen atoms (see figure above).
Good point. This is mentioned below but I think it is good to specify it here as well.

2021-05-25 16:53 UTC, agran2018 commented on demonstrations/tutorial_mol_geo_opt.py
> +    return qml.qchem.molecular_hamiltonian(symbols, x, charge=1, mapping="jordan_wigner")[0]
Just passed it to match with the explanation above but we can definitely make it simpler.

2021-05-25 17:12 UTC, agran2018 commented on demonstrations/tutorial_mol_geo_opt.py
> +#     :width: 50%
Credits to Soran!

2021-05-26 16:48 UTC, agran2018 commented on demonstrations/tutorial_mol_geo_opt.py
> +# .. figure:: /demonstrations/mol_geo_opt/fig_circuit.png
done

2021-05-26 16:48 UTC, agran2018 commented on demonstrations/tutorial_mol_geo_opt.py
> +hf = qml.qchem.hf_state(electrons=2, orbitals=6)
done

2021-05-26 16:48 UTC, agran2018 commented on demonstrations/tutorial_mol_geo_opt.py
> +for n in range(100):
done

2021-05-26 18:03 UTC, soranjh commented on demonstrations/tutorial_mol_geo_opt.py
> +electronic state, and the nuclear coordinates the equilibrium geometry of the molecule in
the nuclear coordinates "determine" the equilibrium geometry

2021-05-26 19:18 UTC, soranjh commented on demonstrations/tutorial_mol_geo_opt.py
> +# References
Will be good to cite the adapt-vqe paper of Grimsley _et al._

2021-05-26 19:18 UTC, soranjh approved these changes

2021-05-26 20:10 UTC, ixfoduap requested changes
The tutorial is in great shape! I left a few additional suggestions, but once these are taken care of I'm very likely willing to approve

2021-05-26 20:10 UTC, ixfoduap commented on demonstrations/tutorial_mol_geo_opt.py
> +print("\n" "Final value of the ground-state energy = {:.8f} Ha".format(energy[-1]))
```suggestion
print("\n" f"Final value of the ground-state energy = {energy[-1]:.8f} Ha")
```
Best to use f-strings here too, as you do below. I think this should work, but good to double-check

2021-05-26 20:10 UTC, ixfoduap commented on demonstrations/tutorial_mol_geo_opt.py
> +# optimized by the variational quantum algorithm.
```suggestion
# Next, we plot the values of the ground state energy of the molecule 
# and the H-H bond lengths as a function of optimization step.
```
Maybe there's a better formulation, but this paragraph was hard to read

2021-05-26 20:10 UTC, ixfoduap commented on demonstrations/tutorial_mol_geo_opt.py
> +# generated by perturbing the HF geometry. Note that the quantum algorithm
```suggestion
# generated by perturbing the HF geometry. The quantum algorithm
```

2021-05-26 20:10 UTC, ixfoduap commented on demonstrations/tutorial_mol_geo_opt.py
> +#     :width: 50%
And the Oscar goes to.....

2021-05-26 20:10 UTC, ixfoduap commented on demonstrations/tutorial_mol_geo_opt.py
> +# state is parametrized. By using the adaptive algorithm it is possible to reduce the
I wouldn't mention the adaptive part here; probably best to focus on the algorithm itself. 

I would suggest adding a bit more discussion on the role of parametrized Hamiltonians and the importance of including these in variational algorithms for quantum chemistry.

2021-05-26 20:34 UTC, glassnotes requested changes
@agran2018 the demo looks awesome! It reads very clearly. I've left only some minor suggestions.

2021-05-26 20:34 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +*Author: PennyLane dev team. Last updated: 25 May 2021.*
```suggestion
*Author: PennyLane dev team. Posted: 25 May 2021. Last updated: 25 May 2021.*
```
For the newer demos we've been adding posted dates as well.

2021-05-26 20:34 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +important tasks in quantum chemistry to simulate most properties of a
```suggestion
Predicting the most stable arrangement of the atoms in a molecule is an
important task in quantum chemistry, and is needed to simulate many properties of a 
```
Feel free to rephrase if this doesn't convey the intended meaning. Just tried to reduce instances of "most".

2021-05-26 20:34 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +circuit and the Hamiltonian parameters.
Great intro! :tada:

2021-05-26 20:34 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +with respect to the parameters :math:`\theta` of the circuit preparing the trial state and the
```suggestion
with respect to the parameters :math:`\theta` of the circuit preparing the trial state, and the
```

2021-05-26 20:34 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +nuclear coordinates :math:`x` entering the electronic Hamiltonian of the molecule. To that aim,
```suggestion
nuclear coordinates :math:`x` entering the electronic Hamiltonian of the molecule. To that end,
```

2021-05-26 20:34 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +molecular geometry optimization where the energy minimum is searched along the potential energy
```suggestion
parameters for each set of nuclear coordinates, as occurs in classical algorithms for
molecular geometry optimization, where the energy minimum is searched along the potential energy 
```

2021-05-26 20:34 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +Along this tutorial we demonstrate how to use PennyLane functionalities to implement
```suggestion
In this tutorial we demonstrate how to use PennyLane to implement
```

2021-05-26 20:34 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +# the operators :math:`\sigma_i` represents the Pauli group :math:`\{I, X, Y, Z\}` and
```suggestion
# the operators :math:`\sigma_i` represent the Pauli group elements :math:`\{I, X, Y, Z\}` and
```

2021-05-26 20:34 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +# the :func:`~.pennylane_qchem.qchem.hf_state` function to generate the
```suggestion
# :func:`~.pennylane_qchem.qchem.hf_state` function to generate the
```

2021-05-26 20:34 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +# method. To that aim, we have to compute the gradients with respect to both the
```suggestion
# method, and compute the gradients with respect to both the
```

2021-05-26 20:34 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +# optimizations of the circuit parameters for each set of the nuclear coordinates.
```suggestion
# each optimization step. This approach does not require nested VQE
# optimization of the circuit parameters for each set of nuclear coordinates.
```

2021-05-26 20:34 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +# the initial state :math:`\vert\Psi(\theta_1, \theta_2)\rangle`
```suggestion
# initial state :math:`\vert\Psi(\theta_1, \theta_2)\rangle` 
```

2021-05-26 20:34 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +        print(f"Iteration = {n},  Energy = {energy[-1]:.8f} Ha,  bond length = {bond_length[-1]:.5f} A")
This line is just a few characters too long and causes a horizontal scroll bar to appear (we try to avoid these in the demos whenever possible. Some ways to shorten it could be replacing "Iteration" with "Step", or "Energy" with just "E".

2021-05-26 20:34 UTC, glassnotes commented on demonstrations/tutorial_mol_geo_opt.py
> +# within chemical accuracy (:math:`0.001` Ha) after the fourth iteration, more
```suggestion
# within chemical accuracy (:math:`0.0016` Ha) after the fourth iteration, more
```
(I think?)

2021-05-26 21:06 UTC, agran2018 commented on demonstrations/tutorial_mol_geo_opt.py
> +important tasks in quantum chemistry to simulate most properties of a
Thanks @glassnotes

2021-05-26 21:15 UTC, agran2018 commented on demonstrations/tutorial_mol_geo_opt.py
> +Let's describe briefly the variational quantum algorithm that we are going to implement
Nice! I was thinking to do it but I was not sure.

2021-05-26 21:38 UTC, agran2018 commented on demonstrations/tutorial_mol_geo_opt.py
> +opt_x = qml.GradientDescentOptimizer(stepsize=0.8)
I played a bit in the past with the step size to optimize ``x`` and 0.8 was the optimal one. For the circuit parameters I did not do this analysis. I chose the same step size we use in the paper.

2021-05-26 21:45 UTC, agran2018 commented on demonstrations/tutorial_mol_geo_opt.py
> +# within chemical accuracy (:math:`0.001` Ha) after the fourth iteration, more
Typically, most people talk about 1 mHa but this is more precise.

2021-05-26 21:46 UTC, agran2018 commented on demonstrations/tutorial_mol_geo_opt.py
> +# References
Yes, probably we can find a place to add this citation.

2021-05-27 17:01 UTC, glassnotes approved these changes
@agran2018 looks great! Good to go from my end.

2021-05-27 18:11 UTC, ixfoduap commented on demonstrations/tutorial_mol_geo_opt.py
> +# References
We should also cite our paper!

2021-05-27 18:13 UTC, agran2018 commented
> @agran2018 looks great! Good to go from my end.
Thank you @glassnotes !

2021-05-27 21:00 UTC, ixfoduap requested changes
Last round of changes! Implement these and I'll approve!

2021-05-27 22:15 UTC, agran2018 commented on demonstrations/tutorial_mol_geo_opt.py
> +# Six qubits are required to encode the occupation number of the molecular spin-orbitals
I suggest to shorten the sentence to make it simpler.

" Six qubits are required to encode the occupation number of the molecular spin-orbitals."

2021-05-28 00:52 UTC, ixfoduap approved these changes

2021-06-30 18:20 UTC, ixfoduap commented on demonstrations/tutorial_mol_geo_opt.py
> +*Author: PennyLane dev team. Posted: 27 May 2021. Last updated: 27 May 2021.*
```suggestion
*Author: PennyLane dev team. Posted: 30 June 2021. Last updated: 30 June 2021.*
```

2021-06-30 18:24 UTC, ixfoduap commented on demonstrations/tutorial_mol_geo_opt.py
> +#     arXiv preprint (2021)
```suggestion
#     arXiv:2106.13840, (2021)
```

2021-07-01 16:04 UTC, merged