[WIP] Adds tutorial on Givens rotations
PennyLaneAI/qml pull request #270
Opened 2021-05-20 20:31 UTC by ixfoduap

This adds a new tutorial describing Givens rotations and their role in constructing quantum circuits for quantum chemistry.

2021-05-21 05:47 UTC, josh146 requested changes
It reads really really well! Most of my comments are just questions or minor polish.

2021-05-21 05:47 UTC, josh146 commented on demonstrations/tutorial_givens_rotations.py
> +singles, doubles = qml.qchem.excitations(3, 6)
oh, I see the print statement right below 🤦 

It might be better to have a ReST comment here, so that the output of the print statement is 'closer' to where the print statement is (this confused me for a second)

2021-05-21 05:47 UTC, josh146 commented on demonstrations/tutorial_givens_rotations.py
> +states = [np.binary_repr(i, width=6) for i in range(len(output)) if output[i] != 0]
I had NO IDEA about the `np.binary_repr` function!!!!!!!!

This is such a time saver, usually I end up using `bin()` and some crazy string manipulation.

2021-05-21 05:47 UTC, josh146 commented on demonstrations/tutorial_givens_rotations.py
> +#      \end{pmatrix},\\
```suggestion
#      \end{pmatrix},\\[12pt]
```

2021-05-21 05:47 UTC, josh146 commented on demonstrations/tutorial_givens_rotations.py
> +# to construct the circuits. 🧠
Although I suppose this begs the question - what is the decomposition of the Given's rotation in terms of single-qubit gates and CNOTs so that I can run this on hardware?

2021-05-21 05:47 UTC, josh146 commented on demonstrations/tutorial_givens_rotations.py
> +# Besides these Givens rotations, there are other versions that have been
So just to clarify, but `SingleExcitation` and `DoubleExcitation` are just specific Givens rotations? Could we add `qml.GivensRot(params, wires)` to PL, whereby some configuration of `params` and `wires` results in either `SingleExcitation` or `DoubleExcitation`?

2021-05-21 05:47 UTC, josh146 commented on demonstrations/tutorial_givens_rotations.py
> +#   CG(\theta) |110\rangle = \cos (\theta/2)|110\rangle - \sin (\theta/2)|101\rangle,
Consider aligning at the equals sign for display

2021-05-21 05:47 UTC, josh146 commented on demonstrations/tutorial_givens_rotations.py
> +ctrl_single0 = qml.ctrl(op, control=0)
Why not just do

```python
qml.qnode(dev)
def circuit4(x, y, z):
    qml.BasisState(np.array([1, 1, 0, 0, 0, 0]), wires=[i for i in range(6)])
    qml.DoubleExcitation(x, wires=[0, 1, 2, 3])
    qml.DoubleExcitation(y, wires=[0, 1, 4, 5])
    qml.ctrl(qml.SingleExcitation)(z, wires=[1, 3])
    return qml.state()
```

directly? This works because `qml.SingleExcitation` is already a callable.

Or alternatively, if you want to re-use this control gate, you could do

```python
ctrl_single0 = qml.ctrl(qml.SingleExcitation)

qml.qnode(dev)
def circuit4(x, y, z):
    qml.BasisState(np.array([1, 1, 0, 0, 0, 0]), wires=[i for i in range(6)])
    qml.DoubleExcitation(x, wires=[0, 1, 2, 3])
    qml.DoubleExcitation(y, wires=[0, 1, 4, 5])
    ctrl_single0(z, wires=[1, 3])
    return qml.state()
```

2021-05-21 05:47 UTC, josh146 commented on demonstrations/tutorial_givens_rotations.py
> +ctrl_single0 = qml.ctrl(op, control=0)
oh no I got so excited writing this response I just spilt coffee all over my laptop.

2021-05-21 11:24 UTC, glassnotes commented on demonstrations/tutorial_givens_rotations.py
> +states = [np.binary_repr(i, width=6) for i in range(len(output)) if output[i] != 0]
WHOA neither did I!!! My life is forever changed :star_struck:

2021-05-21 13:51 UTC, ixfoduap commented on demonstrations/tutorial_givens_rotations.py
> +In the book `“Sophie’s world” <https://en.wikipedia.org/wiki/Sophie%27s_World>`_, the young
At least it got your attention! Which is the whole point of this opening: make the tutorial captivating

2021-05-21 13:51 UTC, ixfoduap commented on demonstrations/tutorial_givens_rotations.py
> +Sophie decided that Lego really could be called the most ingenious toy in the world.*
Good idea! I may borrow one from @glassnotes :smiling_imp:

2021-05-21 13:51 UTC, ixfoduap commented on demonstrations/tutorial_givens_rotations.py
> +transformations that couple the states :math:`|01\rangle,|10\rangle`. These are gates of the form
Totally agree!

2021-05-21 13:51 UTC, ixfoduap commented on demonstrations/tutorial_givens_rotations.py
> +This gate is implemented in PennyLane as the :func:`~.pennylane.SingleExcitation` operation.
I was hoping you would know the answer.... I'll figure it out

2021-05-21 13:51 UTC, ixfoduap commented on demonstrations/tutorial_givens_rotations.py
> +# :math:`|100\rangle`, meaning we indeed prepare the desired state.
:thinking: Let me try and see which style I prefer

2021-05-21 13:51 UTC, ixfoduap commented on demonstrations/tutorial_givens_rotations.py
> +y = -2 * np.arcsin(np.sqrt(1/2))
I was wondering whether this could serve as a minor puzzle inside the tutorial, again to catch the reader's attention, but thinking about it more I'm probably just being lazy to add a short explanation, which would actually be helpful. I'll do it

2021-05-21 13:51 UTC, ixfoduap commented on demonstrations/tutorial_givens_rotations.py
> +# <https://en.wikipedia.org/wiki/Hartree%E2%80%93Fock_method>`_, and include only the excitations
I couldn't find a good link to it. I'll try harder

2021-05-21 13:51 UTC, ixfoduap commented on demonstrations/tutorial_givens_rotations.py
> +singles, doubles = qml.qchem.excitations(3, 6)
Oh, great suggestion!

2021-05-21 13:51 UTC, ixfoduap commented on demonstrations/tutorial_givens_rotations.py
> +states = [np.binary_repr(i, width=6) for i in range(len(output)) if output[i] != 0]
Teaching something to the masters: great feeling!

2021-05-21 13:51 UTC, ixfoduap commented on demonstrations/tutorial_givens_rotations.py
> +# Besides these Givens rotations, there are other versions that have been
Yes, they are just specific Givens rotations. You could in principle add something like `qml.GivensRot()`, and I have given that some thought, but it will be tricky to implement, specially to have decompositions. And you would need to pass also the particular states that span the space where the two-dimensional rotation takes place. We can think more about it

2021-05-21 13:51 UTC, ixfoduap commented on demonstrations/tutorial_givens_rotations.py
> +# to construct the circuits. 🧠
True, but here I prefer to make the strategic choice to not mention it in this tutorial. The main point is that we should stop thinking about single-qubit gates and CNOTs when it comes to quantum chemistry algorithms

2021-05-21 13:51 UTC, ixfoduap commented on demonstrations/tutorial_givens_rotations.py
> +ctrl_single0 = qml.ctrl(op, control=0)
:scream: :scream: :scream: :scream:

2021-05-21 14:13 UTC, josh146 commented on demonstrations/tutorial_givens_rotations.py
> +# :math:`|100\rangle`, meaning we indeed prepare the desired state.
The benefit of this approach is that
```python
circuit(x, y)[0, 1, 0]
```
returns the `|010>` amplitude.

2021-05-21 14:28 UTC, ixfoduap commented on demonstrations/tutorial_givens_rotations.py
> +# :math:`|100\rangle`, meaning we indeed prepare the desired state.
Prefer not to reshape!

2021-05-21 14:55 UTC, ixfoduap commented on demonstrations/tutorial_givens_rotations.py
> +ctrl_single0 = qml.ctrl(op, control=0)
This is so much cleaner!

2021-05-21 15:00 UTC, josh146 commented on demonstrations/tutorial_givens_rotations.py
> +ctrl_single0 = qml.ctrl(op, control=0)
Also a big reason why the `qml.adjoint(op)(params, wires)` syntax is a lot more flexible than the old `qml.inv(op(params, wires))` syntax :)

2021-05-21 17:07 UTC, josh146 approved these changes
Left some more comments, but these are all rendering/typos. Happy to approve on my end! 🚀

2021-05-21 17:07 UTC, josh146 commented on demonstrations/tutorial_givens_rotations.py
> +excitation gates with parameters :math:`\theta, \phi` yields the state
yes, thank you!

2021-05-21 17:07 UTC, josh146 commented on demonstrations/tutorial_givens_rotations.py
> +    \cos(\theta/2)sin(\phi/2)|001\rangle.
```suggestion
    |\psi\rangle = \cos(\theta/2)\cos(\phi/2)|100\rangle - \sin(\theta/2)|010\rangle -
    \cos(\theta/2)\sin(\phi/2)|001\rangle.
```

2021-05-21 17:07 UTC, josh146 commented on demonstrations/tutorial_givens_rotations.py
> +therefore :math:`-sin(\phi/2)=1/\sqrt{2}`. Thus, the prepare an equal superposition state we
```suggestion
therefore :math:`-\sin(\phi/2)=1/\sqrt{2}`. Thus, the prepare an equal superposition state we
```

2021-05-21 17:07 UTC, josh146 commented on demonstrations/tutorial_givens_rotations.py
> +#
Can this be removed?
```suggestion
```

2021-05-21 17:07 UTC, josh146 commented on demonstrations/tutorial_givens_rotations.py
> +#
```suggestion
##############################################################################
```

2021-05-21 17:07 UTC, josh146 commented on demonstrations/tutorial_givens_rotations.py
> +print("Amplitude of state |100> = ", tensor_state[1, 0, 0])
Even though it is a bit repetitive, I really like it (and repetition is a good pedagogical tool right?)

2021-05-21 17:07 UTC, josh146 commented on demonstrations/tutorial_givens_rotations.py
> +# Now we continue to build the circuit:
Flows much better!!

2021-05-21 17:49 UTC, glassnotes reviewed
@ixfoduap awesome! The concepts are all explained really clearly :tada:

I've left some comments, and I will take another look after the fixes for rendering are incorporated. (It was a bit hard to follow the middle section in the current version)

2021-05-21 17:49 UTC, glassnotes commented on demonstrations/tutorial_givens_rotations.py
> +molecules. Quantum computers tackle this problem by using systems of qubits to
```suggestion
Understanding the electronic structure of molecules is arguably the central problem in quantum chemistry. Quantum computers tackle this problem by using systems of qubits to
```

2021-05-21 17:49 UTC, glassnotes commented on demonstrations/tutorial_givens_rotations.py
> +.. figure:: ../demonstrations/givens_rotations/orbitals+states.png
This is very picky but can the | and > in the kets be drawn taller in order to better distinguish the |  from the 1s?

2021-05-21 17:49 UTC, glassnotes commented on demonstrations/tutorial_givens_rotations.py
> +This gate is implemented in PennyLane as the :func:`~.pennylane.SingleExcitation` operation.
Oh no :fearful:

2021-05-21 17:49 UTC, glassnotes commented on demonstrations/tutorial_givens_rotations.py
> +therefore :math:`-sin(\phi/2)=1/\sqrt{2}`. Thus, the prepare an equal superposition state we
```suggestion
therefore :math:`-\sin(\phi/2)=1/\sqrt{2}`. Thus, to prepare an equal superposition state we

```

2021-05-21 17:49 UTC, glassnotes commented on demonstrations/tutorial_givens_rotations.py
> +    # preares the reference state |100>
```suggestion
    # prepares the reference state |100>

```

2021-05-21 17:49 UTC, glassnotes commented on demonstrations/tutorial_givens_rotations.py
> +# :func:`~.pennylane_qchem.qchem.excitations`. Let's employ it to build a circuit that includes
What an amazing function!

2021-05-21 17:49 UTC, glassnotes commented on demonstrations/tutorial_givens_rotations.py
> +# based on the states of other qubits is essential, so also for this reason it's natural to study
```suggestion
# based on the states of other qubits is essential, so for this reason it's natural to study

```

2021-05-21 17:49 UTC, glassnotes commented on demonstrations/tutorial_givens_rotations.py
> +# all two-particle states on four qubits. We follow the same strategy as before, setting the angle
```suggestion
# all two-particle states on four qubits. We follow the same reasoning as before, setting the angle

```

2021-05-21 17:49 UTC, glassnotes commented on demonstrations/tutorial_givens_rotations.py
> +# of the :math:`i`-th Givens rotation as :math:`-2 \arcsin(1/\sqrt{n-i})`, where :math:`n` is the
Perhaps use k instead of i here, n - i looks like a complex number.

2021-05-21 17:49 UTC, glassnotes commented on demonstrations/tutorial_givens_rotations.py
> +# architectures that have been proposed. Researchers in the field are faced with the apparent
```suggestion
# When it comes to quantum circuits for quantum chemistry, a wide variety of
# architectures have been proposed. Researchers in the field are faced with the apparent

```

2021-05-21 18:21 UTC, ixfoduap commented on demonstrations/tutorial_givens_rotations.py
> +.. figure:: ../demonstrations/givens_rotations/orbitals+states.png
I can try with \left and see if they look better. Very picky! :wink:

2021-05-21 18:24 UTC, ixfoduap commented on demonstrations/tutorial_givens_rotations.py
> +print("Amplitude of state |100> = ", tensor_state[1, 0, 0])
:100:

2021-05-21 18:30 UTC, ixfoduap commented on demonstrations/tutorial_givens_rotations.py
> +# all two-particle states on four qubits. We follow the same strategy as before, setting the angle
I like strategy better...

2021-05-21 18:59 UTC, glassnotes commented on demonstrations/tutorial_givens_rotations.py
> +# all two-particle states on four qubits. We follow the same strategy as before, setting the angle
Ah, this suggestion was just because "strategy" is used in the previous sentence and saying it again felt repetitive.

2021-05-21 20:30 UTC, soranjh commented on demonstrations/tutorial_givens_rotations.py
> +    States of a system with six spin orbitals and three electrons.
This is a minor point but the colours indicate this molecule to be carbon dioxide which has more electrons and orbitals.

2021-05-21 20:48 UTC, soranjh commented on demonstrations/tutorial_givens_rotations.py
> +tensor_state = circuit(x, y)
Is this used?

2021-05-21 21:10 UTC, soranjh commented on demonstrations/tutorial_givens_rotations.py
> +# from the second to third qubit if the first (control) qubit is in state :math:`\ket{1}`. This
from the second to third qubit (and vice versa?)

2021-05-21 21:20 UTC, soranjh approved these changes

2021-05-25 17:47 UTC, ixfoduap commented on demonstrations/tutorial_givens_rotations.py
> +tensor_state = circuit(x, y)
Good catch!

2021-05-25 17:49 UTC, ixfoduap commented on demonstrations/tutorial_givens_rotations.py
> +# all two-particle states on four qubits. We follow the same strategy as before, setting the angle
Oh, got it! I changed the previous sentence :)

2021-05-25 21:39 UTC, glassnotes commented on demonstrations/tutorial_givens_rotations.py
> +.. figure:: ../demonstrations/givens_rotations/orbitals+states.png
New version looks excellent :tada:

2021-05-25 21:58 UTC, glassnotes approved these changes
@ixfoduap this looks awesome! All the explanations and examples are really clear. :100:

2021-05-25 21:58 UTC, glassnotes commented on demonstrations/tutorial_givens_rotations.py
> +excitation gates with parameters :math:`\theta, \phi` yields the state
What is the initial state, and what pairs of qubits are the gates applied to? (It's in the code, but since that doesn't come until later, it is worth mentioning here).

2021-05-25 21:58 UTC, glassnotes commented on demonstrations/tutorial_givens_rotations.py
> +
Add small preamble before the code block, like "We can implement this state preparation in PennyLane as follows".

2021-05-25 21:58 UTC, glassnotes commented on demonstrations/tutorial_givens_rotations.py
> +    \theta &= - 2 \arcsin(1/\sqrt{3})\\
```suggestion
    \theta &= - 2 \arcsin(1/\sqrt{3}),\\
```

2021-05-25 21:58 UTC, glassnotes commented on demonstrations/tutorial_givens_rotations.py
> +# :math:`|100\rangle`, meaning we indeed prepare the desired state. We can check this by
```suggestion
# :math:`|100\rangle`, meaning we indeed prepared the desired state. We can check this by

```

2021-05-25 21:58 UTC, glassnotes commented on demonstrations/tutorial_givens_rotations.py
> +#   CG(\theta) |101\rangle &= \cos (\theta/2)|101\rangle + \sin (\theta/2)|110\rangle\\
```suggestion
#   CG(\theta) |101\rangle &= \cos (\theta/2)|101\rangle + \sin (\theta/2)|110\rangle,\\

```

2021-05-25 21:58 UTC, glassnotes commented on demonstrations/tutorial_givens_rotations.py
> +# state and include only the excitations that preserve the spin orientation of the electron.
Maybe add an additional line to say "For a system with $n$ qubits and $k$ electrons, this reference state is typically chosen as  the state with the first $k$ qubits in state |1>, and the remainder in state |0>".

2021-06-30 18:06 UTC, ixfoduap commented on demonstrations/tutorial_givens_rotations.py
> +*Author: PennyLane dev team. Posted: June 1, 2021. Last updated: June 1, 2021*
```suggestion
*Author: PennyLane dev team. Posted: June 30, 2021. Last updated: June 30, 2021*

```

2021-06-30 18:13 UTC, ixfoduap commented on demonstrations/tutorial_givens_rotations.py
> +#   quantum circuits for quantum chemistry", arXiv:2021:1234, (2021)
```suggestion
#   quantum circuits for quantum chemistry", arXiv:2106.13839, (2021)

```

2021-06-30 18:14 UTC, ixfoduap commented on demonstrations/tutorial_givens_rotations.py
> +#   quantum circuits for quantum chemistry", arXiv:2106.13839, (2021)
```suggestion
#   quantum circuits for quantum chemistry", arXiv:2106.13839, (2021)
```

2021-06-30 18:15 UTC, ixfoduap commented on demonstrations/tutorial_givens_rotations.py
> +
```suggestion
```

2021-06-30 18:27 UTC, ixfoduap commented on demonstrations/tutorial_givens_rotations.py
> +# chosen as the state with the first :math:`k` qubits in state :math:`|1\rangle, and the remainder
```suggestion
# chosen as the state with the first :math:`k` qubits in state :math:`|1\rangle`, and the remainder

```

2021-07-01 15:30 UTC, merged