Quantum Analytic Descent Demo
PennyLaneAI/qml pull request #271
Opened 2021-05-21 14:57 UTC by dwierichs

2021-05-28 15:23 UTC, dwierichs commented
@mariaschuld and @hapax, we would be very happy if you could review this demo :)

2021-05-31 07:07 UTC, mariaschuld requested changes
Challenging topic choice for the demo, and the parts are all there, but I think it needs another iteration simplifying the presentation:

* Make use of sections with headers, and in each section tell the reader what is done in the section (i.e., we first look at the equations, and want to convince you that we can build a model of the cost that requires fewer evaluations for optimisation than the original cost function; now we implement the steps one by one and compare model and true cost;...).
* Simplify the presentation of the equations. Readers do not mind long equations if they are warned of them, it is clear what is important about them, and they are well-motivated (and all symbols explained). But limit difficult content to small, contained spots.
* Simplify the plots - I suggest one subplot per surface. Explain what the points and the black lines from the points are.

Also, would you be open to renaming the "model" (since we use this a lot to describe a ML model)? For example, you could speak of the "approximate cost", which says it all (and explains immediately why you plot a "deviation", which you could even call "approximation error")?

Lastly, is this tutorial based on a paper or your own idea? I think this should be stated clearly in the introduction.

Good luck!

2021-05-31 21:12 UTC, dwierichs commented on demonstrations/tutorial_quantum_analytic_descent.py
> +.. math:: E(\boldsymbol{\theta}) = |\langle0|V^\dagger(\boldsymbol{\theta})\mathcal{M}V(\boldsymbol{\theta})|0\rangle|^2,
Good catch! :)

2021-05-31 21:22 UTC, dwierichs commented on demonstrations/tutorial_quantum_analytic_descent.py
> +###############################################################################
Whoops, very good catch!

2021-05-31 21:31 UTC, dwierichs commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# The procedure of Quantum Analytic Descent is shown in this flowchart:
Unfortunately, this is the title of the paper and I think thus not up for negotiations :D

2021-05-31 22:35 UTC, dwierichs commented on demonstrations/tutorial_quantum_analytic_descent.py
> +plot_cost_and_model(circuit, mapped_model, parameters)
Good call! I will try plotting them separately but I am not sure how well one can resolve their similarity/differences then. I'll try :)

2021-06-02 15:09 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# The procedure of Quantum Analytic Descent is shown in this flowchart:
This is a reply to an earlier message, but which doesn't have a reply box:

> Also, would you be open to renaming the "model" (since we use this a lot to describe a ML model)? For example, you could speak of the "approximate cost", which says it all (and explains immediately why you plot a "deviation", which you could even call "approximation error")?

In the paper they also refer to it as the model everywhere and in there it feels right reading it.
I think we should maybe spend a bit more time motivating the name "model", and maybe change it to "classical model"?

2021-06-02 15:10 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +plot_cost_and_model(circuit, mapped_model, parameters)
As much as I like the double surface plot, it may be only because of how invested I am into it that I can read it.
Would it make sense to plot only one surface (either model or true), and the deviation next to it?

2021-06-03 08:20 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +    :target: javascript:void(0)
It shows it for me :O
Did David already solve this?

2021-06-03 09:25 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +thousands of update steps.
```suggestion
Using near-term devices for VQE becomes a non-convex optimization problem, which requires computing gradients at hundreds or thousands of update steps.
Computing gradients on a quantum computer carries the caveat of inefficiency when it comes to circuits with many parameters.
```

2021-06-03 09:29 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +Cashing in on this, the Quantum Analytic Descent algorithm constructs a
```suggestion
Cashing in on this, the authors of the `Quantum Analytic Descent paper <https://arxiv.org/pdf/2008.13774.pdf>`_ propose and algorithm to construct a
```

2021-06-03 09:30 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +local approximation to the landscape where gradient-based optimisation is much
```suggestion
classical model to approximate the landscape, so that the gradients can be calculated on a classical computer, which is much
```

2021-06-03 09:31 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +This approach avoids using the quantum computer to estimate the gradient
```suggestion
```

2021-06-03 09:32 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +at every single optimization step.
```suggestion
```

2021-06-03 09:34 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +Instead, we can use the quantum device to estimate the cost values at a few
```suggestion
In order to build the classical model, we need to use the quantum device to estimate the cost values on (a) a reference point :math:`\theta_0` and (b) a number of points in the vicinity of the reference one (more on that later).
```

2021-06-03 09:34 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +points close to the reference one.
```suggestion
```

2021-06-03 09:35 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +With the cost values at these points, we can build a classical model which
```suggestion
With the cost values at these points, we can build the classical model which
```

2021-06-03 09:35 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +approximates the landscape locally, and then perform the optimization routine
```suggestion
approximates the landscape.
```

2021-06-03 10:31 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +With these, the common choice of cost function :math:`E(\boldsymbol{\theta})` is
```suggestion
With these, our goal is to minimize the cost function :math:`E(\boldsymbol{\theta})`:
```

2021-06-03 10:31 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +where :math:`\rho(\boldsymbol{\theta})=V(\boldsymbol{\theta})|0\rangle\!\langle0|V^\dagger(\boldsymbol{\theta})` is the density matrix of the quantum state after applying the variational form on the
```suggestion
where :math:`\rho(\boldsymbol{\theta})=V(\boldsymbol{\theta})|0\rangle\!\langle0|V^\dagger(\boldsymbol{\theta})` is the density matrix of the quantum state after applying the variational form on :math:`|0\rangle`.
```

2021-06-03 11:24 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +ax.plot(theta_func, C1, label="$E(\\vartheta, \\theta_2^{(0)})$", color='r');
```suggestion
ax.plot(theta_func, C1, label="$E(\\theta, 0.5)$", color='r');
```

2021-06-04 08:32 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +ax.plot(theta_func, C2, label="$E(\\theta_1^{(0)}, \\vartheta)$", color='orange');
```suggestion
ax.plot(theta_func, C2, label="$E(3.3
, \\vartheta)$", color='orange');
```

2021-06-04 08:34 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# We have studied them since high-school and know how to find their minima.
```suggestion
# We have studied them since high-school and know how their graphs look!
```

2021-06-04 08:36 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# In our overly simplified example we had to query a quantum computer for every point on the surface.
```suggestion
# In our overly simplified example we had to query a quantum computer for every point on the surface.
# Querying the quantum computer in this example means calling the ``circuit`` function.
```

2021-06-04 08:54 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# Although in principle we should be able to reconstruct the cost function over the entire parameter space, in practice we are mostly interested in what is happening in the vicinity of a given refere
```suggestion
# One could aim at reconstructing the cost function over the entire parameter space.
# In practice, that would be *very* expensive in number of required quantum circuit evaluations, so the cure would be roughly as bad as the sickness.
# What can we do, then?
# Well, the authors of QAD claim that building a model that is only accurate in the region close to a given reference point is already good enough!
```

2021-06-04 08:54 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# If we wanted to reconstruct the entire landscape, we would need to estimate around :math:`3^m` independent parameters, which would require the same number of function evaluations.
```suggestion
# If we wanted to reconstruct the entire landscape, we would need to estimate around :math:`3^m` independent parameters, which would require a comparable amount of circuit evaluations.
```

2021-06-04 08:57 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# As explained in the paper, an approximation via trigonometric series up to second order is already a sound candidate.
```suggestion
# In the paper, the authors state that a trigonometric series up to second order is already a sound model candidate.
# Similar to Taylor's expansion, this requires we find the cost value at the reference point and compute the first and second order derivatives.
# Here, we will use parameter-shift rules (SHOULD WE CITE ANOTHER DEMO/PAPER?) for the derivatives.
```

2021-06-04 09:21 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# in the vicinity of a reference point :math:`\boldsymbol{\theta}_0`.
```suggestion
# START OF MAJOR RECONSTRUCTION, PLEASE KEEP OFF
# in the vicinity of a reference point :math:`\boldsymbol{\theta}_0`.
```

2021-06-04 09:23 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +#   \phantom{\tilde{E}(\boldsymbol{\theta})}&=A(\boldsymbol{\theta})\left[E^{(A)}+\sum_k \tan\left(\frac{\theta_k}{2}\right)E^{(B)}_k + \tan\left(\frac{\theta_k}{2}\right)^2 E^{(C)}_k + \sum_{l>k} \t
```suggestion
#   \phantom{\tilde{E}(\boldsymbol{\theta})}&=A(\boldsymbol{\theta})\left[E^{(A)}+\sum_k \tan\left(\frac{\theta_k}{2}\right)E^{(B)}_k + \tan\left(\frac{\theta_k}{2}\right)^2 E^{(C)}_k + \sum_{l>k} \tan\left(\frac{\theta_k}{2}\right)\tan\left(\frac{\theta_l}{2}\right)E^{(D)}_{kl}\right]
# END OF THE MAJOR RECONSTRUCTION, YOU MAY PROCEED
```

2021-06-07 06:24 UTC, mariaschuld commented
Hey @dwierichs and @emgilfuster. Just request a re-review when you are ready, so I can have a second look :)

2021-06-23 09:02 UTC, dwierichs commented
We did some major restructuring and hope that the demo is more appealing to read now.
Sorry for taking so long. @mariaschuld and @glassnotes we would be happy about another review! Thank you!

2021-06-23 09:44 UTC, dwierichs commented on demonstrations/tutorial_quantum_analytic_descent.py
> +    :target: javascript:void(0)
Yes, this was resolved, sorry!

2021-06-23 20:49 UTC, glassnotes requested changes
@dwierichs @emgilfuster great work, this is a very clear and detailed demonstration of the work! I'm a huge fan of the graphics, they look really nice and are well-chosen / placed throughout. 

My only major suggestion is to work on streamlining the content, as the demo is quite long. I've noted a few places where this can be done, and made some other wording/phrasing suggestions, but I suggest to go through yourselves as well, and ensure that all the contents that are there are essential to the structure of the explanation, and are as concise as possible (but without sacrificing all the personality!).

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# Before jumping in on the specifics of the classical model they use, we are already in a good position to review the general strategy.
This paragraph would benefit from an additional sentence connecting the ideas here to the previous section. Relate things to the previous plot, or the idea of computational challenge discussed in the note, and explain how instead of computing this surface with a quantum computer, we are going to approximate it classically.

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# And with that we know what type of terms we should expect to encounter in our local classical model:
```suggestion
# With that. we know what type of terms we should expect to encounter in our local classical model:
```

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# :math:`\{A(\boldsymbol{\theta})`, :math:`B_k(\boldsymbol{\theta})` and :math:`C_k(\boldsymbol{\theta})`
```suggestion
# :math:`A(\boldsymbol{\theta})`, :math:`B_k(\boldsymbol{\theta})` and :math:`C_k(\boldsymbol{\theta})`
```

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# However, as the trigonometric polynomials contain multiple orders in :math:`\boldsymbol{\theta}`, and both
```suggestion
# However, the trigonometric polynomials may contain multiple orders in :math:`\boldsymbol{\theta}`. For example, both
```

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# :math:`A(\boldsymbol{\theta})` and :math:`C_k(\boldsymbol{\theta})` contribute to the second order, we have to account
```suggestion
# :math:`A(\boldsymbol{\theta})` and :math:`C_k(\boldsymbol{\theta})` contribute to the second order, so we have to account
```

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +#     and by iterating the rule, we also obtain the second derivatives -- the Hessian (see for example [#higher_order_diff]_).
```suggestion
#     with the `parameter-shift rule <https://pennylane.ai/qml/glossary/parameter_shift.html>`_.
#     By iterating the rule, we can obtain the second derivatives -- the Hessian (see for example [#higher_order_diff]_).
```

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +#     and by iterating the rule, we also obtain the second derivatives -- the Hessian (see for example [#higher_order_diff]_).
Have note as part of main text, because it leads into the code section.

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +
```suggestion
```

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +    E_D = np.triu(hessian, 1)
```suggestion
    E_A = fun(params)
    
    # E_B contains the gradient.
    E_B = qml.grad(fun)(params)
    
    hessian = qml.jacobian(qml.grad(fun))(params)
    
    # E_C contains the slightly adapted diagonal of the Hessian.
    E_C = np.diag(hessian) + E_A / 2
    
    # E_D contains the off-diagonal parts of the Hessian.
    # We store each pair (k, l) only once, namely the upper triangle.
    E_D = np.triu(hessian, 1)
```

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +)
Nice!

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# Let us now take a few moments to breath deeply and admire the entirety of it.
Love the enthusiasm :star_struck:

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +    # For the other terms we only compute the prefactor relative to A
```suggestion

    # For the other terms we only compute the prefactor relative to A
```

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +    cost = A * np.sum(all_terms_over_A)
```suggestion
    D_over_A = np.outer(B_over_A, B_over_A)
    
    all_terms_over_A = [
        E_A,
        np.dot(E_B, B_over_A),
        np.dot(E_C, C_over_A),
        np.dot(B_over_A, E_D @ B_over_A),
    ]
    
    cost = A * np.sum(all_terms_over_A)
```

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +    return cost
Could also just do `return A * np.sum...` instead of splitting over separate lines.

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# As we can see, the model works fine and reproduces the correct energy at the parameter
```suggestion
# As we can see, the model reproduces the correct energy at the parameter
```

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +#     Now we can also summarize how many parameters our model has.
```suggestion
#     How many parameters does our model have?
```

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +#     Without going into detail on the parameter-shift rule for the gradient and Hessian, we remark that we need :math:`1\times 1 + 2\times m + 1\times m + 4\times (m-1)m/2` many circuit evaluations,
```suggestion
#     Without going into detail on the parameter-shift rule for the gradient and Hessian, we remark that we need a total of :math:`2m^2+m+1`.
```
Just show the result; maybe link to somewhere that does this computation though?

BTW this content works great as a note :+1:

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# Now this should be enough of theory, let's *take a look* at the model that results from our trigonometric expansion.
```suggestion
# Now this should be enough theory, so let's visualize the model that results from our trigonometric expansion.
```

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +            [[params[0] + s2, params[1] + s1, fun(params + np.array([s1, s2]))] for s2 in shifts]
This line is just a bit too long, and makes a horizontal scroll bar appear in the code. We try to avoid this in demos, so see if there is anywhere you can save some characters (e.g. variable names, `fun` ->`f`, something like this).

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# Define a mapped model that has the model coefficients fixed.
```suggestion

# Define a mapped model that has the model coefficients fixed.
```

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# was evaluated in order to obtain the model coefficients (we skip the additional
These plots look awesome!

I see now the reason for the earlier note about the number of samples. This might be a better place for it, like "notice how we evaluated the cost function at only a subset of points. this is because..." because it's directly required for the example.

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# In the first two plots, we see the true landscape in green, and the approximate model in orange.
```suggestion
# In the first two plots, we see the true landscape, and the approximate model.
```

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# Around the reference point this difference is very small and changes very slowly,
It would be helpful to mark on the plots where the reference point is

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# The underlying idea we are trying to exploit now for the optimization in VQEs is the following:
```suggestion
# The underlying idea we will now try to exploit for optimization in VQEs is the following:
```

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# If we can model the cost around the reference point well enough, we will be able to find a rough
```suggestion
# if we can model the cost around the reference point well enough, we will be able to find a rough
```

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# will bring us much closer to the minimum *of the true cost* than a random walk.
```suggestion
# will bring us much closer to the minimum *of the true cost* than a random choice.
```

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# And hereby, we recap the complete strategy from above:
```suggestion
# Recall the complete strategy from above:
```

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# The procedure of Quantum Analytic Descent is also shown in the following flowchart. Note that the minimization
```suggestion
# This provides an iterative strategy which will take us to a good enough solution 
# in fewer iterations than, for example, regular stochastic gradient descent (SGD).
# The procedure of Quantum Analytic Descent is also shown in the following flowchart. Note that the minimization
```
Good place to link to the SGD demo.

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +for iter_outer in range(N_iter_outer):
This is a very big code block, try to add a bit of spacing, and some lines could be saved by removing some comments that don't directly relate to the algorithm itself (e.g., `Logging`)

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# **Iteration 3:** Both, the model and the original cost function now show a minimum close to our parameter position, Quantum Analytic Descent converged.
This is a really cool progression to see!

(Only suggestion is to mark somewhere the original / reference parameters so it can be seen how they correspond to the minimum)

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# **Iteration 3:** Both, the model and the original cost function now show a minimum close to our parameter position, Quantum Analytic Descent converged.
```suggestion
# **Iteration 3:** Both the model and the original cost function now show a minimum close to our parameter position--- Quantum Analytic Descent converged.
```

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# in which both, the original energy and the model, form a convex bowl and the deviation plateaus at zero.
```suggestion
# Note how the larger deviations of the model close to the boundaries are not a problem at all because we only use the model in the central area
# in which both the original energy and the model form a convex bowl and the deviation plateaus at zero.
```

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +        range(i * N_iter_inner, (i + 1) * N_iter_inner + 1), model_logs[i], ls="--", color="#ED7D31"
This line is also a bit too long, try to shorten it a bit or spread over more lines.

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# We said the *true cost* values are bounded, yet, that does not mean the ones of the *model* are!
Move to the beginning of this paragraph, after the current first sentence? Also could ju
```suggestion
# You might be thinking, *Wasn't this forbidden? The function can only take values in* :math:`[-1,1]`  >:@ *
# While the *true cost* values are bounded, that does not mean the ones of the *model* are!
```
Just a suggestion to rephrase and streamline.

2021-06-23 20:49 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# only access it via very costly quantum computations.
Great recap!

2021-06-24 05:13 UTC, mariaschuld commented on demonstrations/tutorial_quantum_analytic_descent.py
> +*Authors: Elies Gil-Fuster, David Wierichs. Posted: ?? May 2021.*
Whoops sorry, I think I suggested to take that out previously. My bad!

2021-06-24 05:47 UTC, josh146 commented on xanadu_theme/static/xanadu.css_t
> +  background-color: #ebf2ee;
```suggestion
  background-color: #f2f9f5;
```

(Slightly less gray-ish 😆)

2021-06-24 06:11 UTC, mariaschuld approved these changes
@dwierichs @emgilfuster the demo is awesome now, well done. It explains a complex idea very clearly! Most of my comments coincide with those of @glassnotes, so if those are addressed it is ready to be merged from my side.

A tiny (optional) idea: do you want to show via vertical lines at epoch 50, 100 in the picture that there are different iterations of the model building algorithm? It is kind of clear from the text, but since the picture features at the start this could explain better what we see, i.e. why there are steps...

2021-06-24 07:14 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +point.
Hi! I'm not sure I'm seeing it wrong, but if we also remove the "which" in line 41 then the sentence stops making sense grammatically, right?

2021-06-24 07:15 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +After this purely classical phase, a new model is built at the next reference
```suggestion
After this purely classical phase, a new classical model is built at the next reference
```

2021-06-24 12:09 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +point.
Oops, that's my bad! Fixed it :)

2021-06-24 13:02 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +#     Without going into detail on the parameter-shift rule for the gradient and Hessian, we remark that we need :math:`1\times 1 + 2\times m + 1\times m + 4\times (m-1)m/2` many circuit evaluations,
we wrote it out explicitly because it's wrong on the paper. Is it fine if it stays? Maybe phrased differently if all those \times are too ugly?

2021-06-24 13:06 UTC, dwierichs commented on demonstrations/tutorial_quantum_analytic_descent.py
> +            [[params[0] + s2, params[1] + s1, fun(params + np.array([s1, s2]))] for s2 in shifts]
It seems like there is no scrollbar for us in this cell.
As we use black, shouldn't the line length limit of 100 avoid this happening? :-)

2021-06-24 13:29 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +            [[params[0] + s2, params[1] + s1, fun(params + np.array([s1, s2]))] for s2 in shifts]
Oh weird, what browser are you using? (I've found when testing demos in the past that black with limit between 90-95 is safest)

2021-06-25 15:52 UTC, dwierichs commented on demonstrations/tutorial_quantum_analytic_descent.py
> +            [[params[0] + s2, params[1] + s1, fun(params + np.array([s1, s2]))] for s2 in shifts]
Yes, sorry, actually there was a scrollbar in the end, I just fixed that.There must have been a change after I checked last...
I believe `black -l 94` should be around the limit :D

2021-06-27 09:23 UTC, emgilfuster commented
Hi! We implemented the suggested changes, we're ready for one more review iteration @glassnotes @mariaschuld

2021-06-29 20:31 UTC, glassnotes approved these changes
@dwierichs @emgilfuster Great work! Left just a few small suggestions and caught some typos. Otherwise, this is merge-ready. :tada:

2021-06-29 20:31 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +design with a gradient-based optimization to solve this task.
```suggestion
design with gradient-based optimization to solve this task.
```

2021-06-29 20:31 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +evaluate the cost function on (a) a reference point :math:`\boldsymbol{\theta}_0`
```suggestion
evaluate the cost function on (a) a reference point :math:`\boldsymbol{\theta}_0`,
```

2021-06-29 20:31 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +we try to solve.
```suggestion
we are trying to solve.
```

2021-06-29 20:31 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +That is, for each parameter :math:`\theta_i` there exist :math:`a_i`, :math:`b_i`, and :math:`c_i` such that the cost can be written as
```suggestion
That is, for each parameter :math:`\theta_i` there exist :math:`a_i`, :math:`b_i`, and :math:`c_i` such that the cost can be written as
```

2021-06-29 20:31 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +That is, for each parameter :math:`\theta_i` there exist :math:`a_i`, :math:`b_i`, and :math:`c_i` such that the cost can be written as
Fine to keep in the same paragraph since it is continuing the thought.

2021-06-29 20:31 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# We have studied them since high school and know how their graphs look!
```suggestion
# We have studied them since high school and know how their graphs look.
```

2021-06-29 20:31 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
>  #     In Calculus I we learnt a Taylor series in one variable :math:`x` uses the integer powers of the variable namely :math:`\{1, x, x^2, x^3, \ldots\}`, in short :math:`\{x^n\}_{n\in\mathbb{N}}`:
```suggestion
#     In Calculus I we learned that a Taylor series in one variable :math:`x` uses the integer powers of the variable namely :math:`\{1, x, x^2, x^3, \ldots\}`, in short :math:`\{x^n\}_{n\in\mathbb{N}}`:
```

2021-06-29 20:31 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +#     For higher-dimensional variables we have to take products of the basis functions of each coordinate, i.e. of monomials or trigonometric monomials respectively.
```suggestion
#     For higher-dimensional variables we have to take products of the basis functions of each coordinate, i.e., of monomials or trigonometric monomials respectively.
```

2021-06-29 20:31 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +#
This streamlined explanation looks great! I suggest actually to make this part of the main text, rather than an admonition, since it comprises most of the section.

2021-06-29 20:31 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# contribute to what order of th expansion (due to the fact that all order
```suggestion
# contribute to each order of the expansion (due to the fact that all 
```

2021-06-29 20:31 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
>  # Those are really large terms as compared to a Taylor series!
```suggestion
# Those are really large terms compared to a Taylor series!
```

2021-06-29 20:31 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# in the following table write them next to their non-trigonometric analogues.
Add a single line here that just describes how these forms were obtained.

2021-06-29 20:31 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# for each parameter, and :math:`D_{kl}(\boldsymbol{\theta})` for every pair of different variables :math:`(\theta_k,\theta_l)`.
```suggestion
# for each parameter, and :math:`D_{kl}(\boldsymbol{\theta})` for every pair of different parameters :math:`(\theta_k,\theta_l)`.
```

2021-06-29 20:31 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +#     In the following table we count them for an :math:`m`-dimensional input
Table looks great! Consider even moving it into the main text, because the contents are brief. But it's fine as-is too.

2021-06-29 20:31 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# The rod with the bead on top indicates the reference point around which the model
Awesome, this really helps with clarity.

2021-06-29 20:31 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# model and true landscape.
```suggestion
# the model and true landscapes.
```

2021-06-29 20:31 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# **Iteration 2:** Now we observe the model to stay closer to the original landscape. In addition, the minimum of the model is within the displayed range -- we're getting closer.
```suggestion
# **Iteration 2:** Now we observe the model better resembles the original landscape. In addition, the minimum of the model is within the displayed range -- we're getting closer.
```

2021-06-29 20:31 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# can be seen to be significantly lower than the true cost.
```suggestion
# can potentially be significantly lower than the true cost.
```

2021-06-29 20:31 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# using PennyLane for a toy-example of a Variational Quantum Eigensolver.
```suggestion
# using PennyLane for a toy example of a Variational Quantum Eigensolver.
```

2021-06-29 20:31 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +# By making extensive use of 3D-plots we have also tried to illustrate exactly
```suggestion
# By making extensive use of 3D plots we have also tried to illustrate exactly
```

2021-06-30 08:02 UTC, emgilfuster commented on demonstrations/tutorial_quantum_analytic_descent.py
> +#
At some point Maria proposed to somehow differentiate the scary/mathy stuff from the plain text. This used to be a note but you pointed out that might be too much of a separation given that it's critical information for the whole of the demo. It seemed to us this admonition thing could be a nice point inbetween, where you clearly see the margins are larger, so something is different, but it's not really that far away from the rest of the text.

2021-06-30 08:03 UTC, dwierichs commented on demonstrations/tutorial_quantum_analytic_descent.py
> +#     In the following table we count them for an :math:`m`-dimensional input
Maybe we'd leave it as-is then, since it's just an unnecessary elaboration on the statement "the model requires polynomially many parameters", which is the big message that should (and already does) appear in the main text.

2021-06-30 11:52 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +#
That's fair! :100:

2021-06-30 11:52 UTC, glassnotes commented on demonstrations/tutorial_quantum_analytic_descent.py
> +#     In the following table we count them for an :math:`m`-dimensional input
Cool sounds good :+1:

2021-07-19 17:58 UTC, merged