CH4398 | Fix Community Card Anchors
PennyLaneAI/qml pull request #275
Opened 2021-05-28 21:01 UTC by AndrewGardhouse

**Title:**
Fix community card anchors

**Summary:**
On the Community page, if a URL has the `id` of a community card, the page will scroll to that card and highlight it. 

**Relevant references:**
- [CH4398](https://app.clubhouse.io/xanaduai/story/4398/fix-community-card-anchors)
- https://github.com/PennyLaneAI/qml/pull/194

2021-05-29 04:31 UTC, josh146 requested changes
Thanks @AndrewGardhouse this is great! And kudos for puzzling out the community demos logical flow... it's very split between Jinja templates and Sphinx custom directives 😆 

It also works well in my testing when loading the URL from scratch 👍 The only thing I noticed though was that if you reload the URL, 

- The page scrolls just _below_ the card title
- The active class does not get re-added

I've added a small gif to show this:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/2959003/120057944-cabea680-c079-11eb-8944-1b3ccf8f2ce3.gif)

2021-05-29 04:31 UTC, josh146 commented on custom_directives.py
> +        title_first_letters = "".join(list(map(lambda word: word[0], title_iterable))).lower()
Just trying to parse this one; from what I can tell, it's taking the first letter of each word in the title? So

> Linear regression using angle embedding and a single qubit by Hemant Gahankari

becomes

```
id = lruaeaasq-gahankari
```

2021-05-29 04:31 UTC, josh146 commented on custom_directives.py
> +        title_first_letters = "".join(list(map(lambda word: word[0], title_iterable))).lower()
I was trying to work out if there was a way to make it more readable, but I can't come up with anything else, because there are so many chances of clashes otherwise 😆

2021-05-29 04:31 UTC, josh146 commented on xanadu_theme/layout.html
> -    </script>
How come this was removed?

2021-05-29 04:31 UTC, josh146 commented on demos_community.rst.template
> +            $(window).on('hashchange', function(e) {
This is great! My only nitpick (which is relatively minor) is that as soon as the mouse hovers over the card, the `active` class is lost. it would be great to keep this green glow more permanently while the URL hash is still present

2021-05-31 13:27 UTC, glassnotes commented on custom_directives.py
> +        title_first_letters = "".join(list(map(lambda word: word[0], title_iterable))).lower()
What if we did similar to how arXiv generates BibTeX citation IDs, like `nameYEARfirstword`. So `gahankari2020using`, `huembeli2020characterizing`. There are still chances for things to clash (my bib file has an awful lot of `nameYEARquantum`...)  but could we work around that by storing the list of IDs and postfixing a number to avoid duplicates, `nameYEARquantum`, `nameYEARquantum-2`, etc.

2021-05-31 13:39 UTC, glassnotes reviewed
Thanks @AndrewGardhouse !! :tada: 

This is maybe out of scope for this PR, but what if we also include a "copy link" button / text option on each card so that someone browsing the page can directly copy links to cards.

Like the same functionality as this:
![image](https://user-images.githubusercontent.com/2068515/120201709-c0281c80-c1f3-11eb-83a6-7585fdf4e122.png)

Then the readability of the IDs is not as critical, as you can just extract them through copying rather than inferring through the title.

2021-06-01 20:41 UTC, AndrewGardhouse commented on xanadu_theme/layout.html
> -    </script>
I removed this because the same code is in the `<script>` tag above it

2021-06-01 20:42 UTC, AndrewGardhouse commented
> Thanks @AndrewGardhouse !! 🎉
> 
> This is maybe out of scope for this PR, but what if we also include a "copy link" button / text option on each card so that someone browsing the page can directly copy links to cards.
> 
> Like the same functionality as this:
> ![image](https://user-images.githubusercontent.com/2068515/120201709-c0281c80-c1f3-11eb-83a6-7585fdf4e122.png)
> 
> Then the readability of the IDs is not as critical, as you can just extract them through copying rather than inferring through the title.

This is a great idea, but I do feel like this is out of scope for this PR

2021-06-01 20:48 UTC, AndrewGardhouse commented on custom_directives.py
> +        title_first_letters = "".join(list(map(lambda word: word[0], title_iterable))).lower()
This one was tricky to come up with a unique, yet readable ID 😅  I like @glassnotes' idea 👍

2021-06-01 21:19 UTC, AndrewGardhouse commented on custom_directives.py
> +        title_first_letters = "".join(list(map(lambda word: word[0], title_iterable))).lower()
<img width="851" alt="Screen Shot 2021-06-01 at 5 14 42 PM" src="https://user-images.githubusercontent.com/8475900/120391351-e2599180-c2fc-11eb-9b48-e4d9dff11887.png">
I just found another issue with the current approach, if the name being used in the ID has an accent it will break the JS

2021-06-01 21:52 UTC, glassnotes commented on custom_directives.py
> +        title_first_letters = "".join(list(map(lambda word: word[0], title_iterable))).lower()
Oh wow, good catch! Could we just replace the accented characters with the unaccented base character for the URL?

2021-06-02 14:37 UTC, AndrewGardhouse commented
@glassnotes @josh146 I addressed all of your comments 👍 Sorry for the delay, I didn't have notifications set up for GitHub PR mentions!

2021-06-02 14:44 UTC, josh146 approved these changes
Thanks @AndrewGardhouse! Played around with it and the new ids work well :+1:

Only two comments:

- It seems that the `active` class disappearing on mouse hover still occurs, which means that the green shading can quickly disappear.
- The scrolling behaviour in the gif I posted before still seems to occur if reloading a URL with the same id 🤔 

However, I think this PR is currently a net benefit against master, so I'm happy to merge it in as-is and address those issues later if need be.

Oh, just one more thing - best not to force push into PRs, since it messes up GitHub's history, and it makes it hard to (a) view previous conversations (since they get marked as 'outdated') and (b) compare current changes to previous commits 🙂 

Even if the history within the PR becomes unwieldy, we only do merge commits into master, so there's an opportunity to re-phrase commit messages if need be!

2021-06-02 14:44 UTC, josh146 commented on custom_directives.py
> +            return raw_text
nice! This should be sufficient accent coverage :)

2021-06-02 14:44 UTC, josh146 commented on custom_directives.py
> +            id=remove_accents(self.options["author"].split(" ")[-1].lower()) + self.options["date"].split("/")[-1] + self.options["title"].split(" ")[0].lower(),
:+1:

2021-06-02 14:44 UTC, josh146 commented on demos_community.rst.template
> +                    if ($(card).hasClass('active')) { $(card).removeClass('active'); }
I'm not sure exactly what is happening here, but it looks like this to me:

![image](https://user-images.githubusercontent.com/2959003/120500234-48284500-c3f3-11eb-8d82-7c5d5132a945.png)

GitHub failing to syntax highlight?

2021-06-02 14:59 UTC, glassnotes approved these changes
Thanks @AndrewGardhouse ! Looks good from my end :tada:

2021-06-02 14:59 UTC, glassnotes commented on custom_directives.py
> +            return raw_text
Yep, plus the way it's coded makes it easy to add more in the future should we need to. Awesome :tada:

2021-06-02 15:29 UTC, AndrewGardhouse commented
@josh146 

> * The scrolling behaviour in the gif I posted before still seems to occur if reloading a URL with the same id 🤔
I wasn't able to reproduce this, could you provide the URL that is causing this issue, please?

> * It seems that the active class disappearing on mouse hover still occurs, which means that the green shading can quickly disappear.

Do we want the active class to remain on the card as long as the card's hash was navigated to through the URL, regardless of if a user is hovering over any of the other cards? Right now, the active class is only removed if the user hovers over another card.

2021-06-02 15:40 UTC, josh146 commented
> Do we want the active class to remain on the card as long as the card's hash was navigated to through the URL, regardless of if a user is hovering over any of the other cards?

Yes, that was my intuition while browsing! So I found it a bit jarring when I saw the shadow change

2021-06-03 13:02 UTC, merged