Adjoint Differentiation
PennyLaneAI/qml pull request #276
Opened 2021-06-03 20:36 UTC by albi3ro

This tutorial explains how adjoint differentiation works.

2021-06-04 01:57 UTC, albi3ro commented on demonstrations/tutorial_adjoint_diff.py
> +    params = rng.standard_normal(param_shape)
```suggestion
    params = np.array(rng.standard_normal(param_shape))
```
This change can be reverted with the new release

2021-06-04 05:30 UTC, josh146 commented
Thanks @albi3ro! For reference, until the thumbnail is added, the currently rendered version is available here: https://3523-214003948-gh.circle-artifacts.com/0/_build/html/demos/tutorial_adjoint_diff.html.

Is this PR currently still WIP? If so, best to update the title to include `[WIP]`. Secondly, would you like a round of pre-review comments?

2021-06-04 13:22 UTC, albi3ro commented
Realized I still need an introduction, but I could use feedback on the rest of it.

2021-11-11 18:55 UTC, glassnotes requested changes
Looking good @albi3ro , comments are all pretty minor at this stage! :rocket:  I do recommend also tagging a second person for review who's more familiar with the finer points of the adjoint method, if possible.

2021-11-11 18:55 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# We will use the ``circuit`` QNode just for comparison purposes.  Thoughout this
```suggestion
# We will use the ``circuit`` QNode just for comparison purposes.  Throughout this
```

2021-11-11 18:55 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# the ket. Therefore we use the product rule to take the derivative with respect to both locations.
```suggestion
# the ket. Therefore, we use the product rule to take the derivative with respect to both locations.
```

2021-11-11 18:55 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# This :math:`|b_i\rangle` is different than the one defined above when we weren't taking
```suggestion
# This :math:`|b_i\rangle` is different from the one defined above when we weren't taking
```

2021-11-11 18:55 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# ------------
```suggestion
# Author: PennyLane dev team. Posted: XX Nov 2021. Last updated: XX Nov 2021.
```
There is a lot of blank space after the title so let's remove the header (and also add the standard author/date info).

2021-11-11 18:55 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# Adjoint differentiation straddles these two strategies taking benefits from each.
```suggestion
# Adjoint differentiation straddles these two strategies, taking benefits from each.
```

2021-11-11 18:55 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# quantum circuits with a statevector simulation.  It scales nicely in time without
```suggestion
# quantum circuits with a state vector simulation.  It scales nicely in time without 
```
(This spelling is used earlier; I think either as fine as long as they are the same)

2021-11-11 18:55 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# 3) taking an expectation value of a Hermitian operator,
```suggestion
# 3) measurement, such as estimating an expectation value of a Hermitian operator,
```

2021-11-11 18:55 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# The "adjoint" differentiation method takes advantage of the ability to erase, creating a time and
```suggestion
# The **adjoint differentiation method** takes advantage of the ability to erase, creating a time- and
```

2021-11-11 18:55 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +print(state)
I see, it might be worth mentioning that (but at the same time, it might also be confusing)?

2021-11-11 18:55 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# And gotten the exact same results.  I use :math:`n` to indicate that :math:`U_n`
```suggestion
# And gotten the exact same results.  Here, the subscript :math:`n` is used to indicate that :math:`U_n`
```

2021-11-11 18:55 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# We start near the center at :math:`U_n` and reverse through the operations list till we reach :math:`U_0`.
```suggestion
# We start near the center at :math:`U_n` and reverse through the operations list until we reach :math:`U_0`.
```

2021-11-11 18:55 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# Wherever we cut, we can stick additional things in the middle. What are we sticking in the middle?
```suggestion
# We showed how to calculate the same thing a bunch of different ways. Why is this useful? 
# Wherever we cut, we can stick additional things in the middle. What are we sticking in the middle?
```
There are two questions in quick succession here, consider rephrasing the first one to a statement instead.

2021-11-11 18:55 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# .. math:: | k \rangle =  |\Psi \rangle = U_n U_{n-1} \dots U_0 |0\rangle
```suggestion
# .. math:: \langle M \rangle = \langle b | k \rangle = \langle \Psi | M | \Psi \rangle,
#
# where
#
# .. math:: \langle b | = \langle \Psi| M = \langle 0 | U_0^{\dagger} \dots U_n^{\dagger} M,
#
# .. math:: | k \rangle =  |\Psi \rangle = U_n U_{n-1} \dots U_0 |0\rangle.
```
Add punctuation to equations throughout.

2021-11-11 18:55 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# Most parametrized gates can be represented in terms of Pauli Rotations, and Pauli rotations can be written as:
```suggestion
# Most parametrized gates can be represented in terms of Pauli Rotations, which can be written as
```

2021-11-11 18:55 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# for a matrix :math:`\hat{G}`, a constant :math:`c`, and the parameter :math:`\theta`.
```suggestion
# for a Pauli matrix :math:`\hat{G}`, a constant :math:`c`, and the parameter :math:`\theta`.
```
(?)

2021-11-11 18:55 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# But how fast? The provided script `here <https://pennylane.ai/qml/demos/adjoint_diff_benchmarking.py>`__
This currently doesn't load; I assume it will not be available until we merge into master?

2021-11-11 18:55 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# And use these to get the derivative
```suggestion
# For the actual expectation value calculation, we use a temporary version of the bra,
# 
# .. math:: \langle \tilde{b}_i | = \langle b_i | \frac{\text{d} U_i}{\text{d} \theta_i},
# 
# and use these to get the derivative
```

2021-11-11 18:55 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +#       \frac{\partial \langle M \rangle}{\partial \theta_i} = 2 \text{Real}\left( \langle \tilde{b}_i | k_i \rangle \right)
```suggestion
#       \frac{\partial \langle M \rangle}{\partial \theta_i} = 2 \text{Real}\left( \langle \tilde{b}_i | k_i \rangle \right).
```

2021-11-11 18:55 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# We do have to calculate the state first, a "forward" pass, but once we have that,
Be a bit more explicit here about what the forward pass calculates; it is |psi> = U_n ... U_0 |0> right?

2021-11-11 18:55 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# .. figure:: ../demonstrations/adjoint_diff/scaling.png
This is good for showing the scaling, but it would also be nice to see a comparison to one of the other gradient computation methods (which is initially what I expected when I saw the two lines).

2021-11-12 07:10 UTC, josh146 commented on demonstrations/adjoint_diff_benchmarking.py
> +    :property="og:image": https://pennylane.ai/qml/_static/thumbs/code.png
Don't forget to also include links to relevant demos here :) E.g., the backprop demo, the stochastic parameter-shift demo, the noisy parameter-shift demo, etc.

2021-11-12 07:10 UTC, josh146 commented on demonstrations/tutorial_adjoint_diff.py
> +    :property="og:image": https://pennylane.ai/qml/_static/thumbs/code.png
Don't forget to also include links to relevant demos here :) E.g., the backprop demo, the stochastic parameter-shift demo, the noisy parameter-shift demo, etc.

2021-11-12 07:49 UTC, josh146 commented on demonstrations/tutorial_adjoint_diff.py
> +# Classical automatic differentiation has two methods of calculation: forward and reverse.
Recommend linking to a resource, such as https://en.wikipedia.org/wiki/Automatic_differentiation#The_chain_rule,_forward_and_reverse_accumulation

2021-11-12 13:28 UTC, albi3ro commented on demonstrations/tutorial_adjoint_diff.py
> +# But how fast? The provided script `here <https://pennylane.ai/qml/demos/adjoint_diff_benchmarking.py>`__
Yep.  If you combine the temporary root and the end of the link to view the file:
https://4510-214003948-gh.circle-artifacts.com/0/_build/html/demos/adjoint_diff_benchmarking.html

2021-11-12 13:36 UTC, josh146 commented on demonstrations/tutorial_adjoint_diff.py
> +# But how fast? The provided script `here <https://pennylane.ai/qml/demos/adjoint_diff_benchmarking.py>`__
it renders quite nicely!!

2021-11-19 14:54 UTC, trbromley reviewed
Thanks @albi3ro. The tutorial reads nicely, excited to have it released!
I left a few comments/suggestions, but once resolved I'll be happy to approve.

2021-11-19 14:54 UTC, trbromley commented on demonstrations/tutorial_adjoint_diff.py
> +# We create our state by using the ``"default.qubit"`` methods ``_create_basis_state``
It might be nice to have a sentence that explains what we're doing next, e.g., showing that we can replicate the result of our `circuit` QNode

2021-11-19 14:54 UTC, trbromley commented on demonstrations/tutorial_adjoint_diff.py
> +# only the sum is an expectation value. Each component is not guaranteed to be real,
> only the sum is an expectation value

Naively, isn't it the derivative of an expectation value?

2021-11-19 14:54 UTC, trbromley commented on demonstrations/tutorial_adjoint_diff.py
> +#    2 \text{Real} \left( \langle b_i | \frac{\text{d} U_i }{\text{d} \theta_i} | k_i \rangle \right)
```suggestion
#    2 \text{Re} \left( \langle b_i | \frac{\text{d} U_i }{\text{d} \theta_i} | k_i \rangle \right)
```

2021-11-19 14:54 UTC, trbromley commented on demonstrations/tutorial_adjoint_diff.py
> +# for something else, it's derivative.  Only once the calculation is complete do we continue
I was confused by this sentence :thinking:

2021-11-19 14:54 UTC, trbromley commented on demonstrations/tutorial_adjoint_diff.py
> +#  Once we have that, we only have about the same amount of work to calculate all the derivatives,
```suggestion
# Once we have that, we only have about the same amount of work to calculate all the derivatives, 
```
![image](https://user-images.githubusercontent.com/49409390/142641043-3f8946e0-e51c-4d0a-baf3-bbff3c6a79c1.png)
This this is causing a rendering issue

2021-11-19 14:54 UTC, trbromley commented on demonstrations/tutorial_adjoint_diff.py
> +# method that can support arbitrary circuits, you can use ``diff_method=adjoint`` in PennyLane with
```suggestion
# method that can support arbitrary circuits, you can use ``diff_method="adjoint"`` in PennyLane with 
```

2021-11-19 14:54 UTC, trbromley commented on demonstrations/tutorial_adjoint_diff.py
> +# gradients require at least two execution per parameter, so that method gets more
```suggestion
# gradients require at least two executions per parameter, so that method gets more
```

2021-11-19 15:03 UTC, glassnotes reviewed
@albi3ro All formatting things from my side, happy to approve once the technical details from the other reviewers are sorted :+1:

2021-11-19 15:03 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# gradients require at least two execution per parameter, so that method gets more
```suggestion
# gradients require at least two executions per parameter, so that method gets more
```

2021-11-19 15:03 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# With adjoint differentiation on Lightning, you can get the best of both worlds: fast and
```suggestion
# With adjoint differentiation on ``"lightning.qubit"``, you can get the best of both worlds: fast and 
```

2021-11-19 15:03 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# .. figure:: ../demonstrations/adjoint_diff/scaling.png
New figure is :100: :star:

2021-11-19 15:03 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# quantum circuits with a state vector simulation.  It scales nicely in time without
```suggestion
# quantum circuits with state vector simulation.  It scales nicely in time without 
```

2021-11-22 20:40 UTC, glassnotes approved these changes
Thanks @albi3ro, this is ready to go! :rocket: Just caught a few last typos / punctuation things.

2021-11-22 20:40 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# Author: PennyLane dev team. Posted: XX Nov 2021. Last updated: XX Nov 2021.
```suggestion
# *Author: PennyLane dev team. Posted: 22 Nov 2021. Last updated: 22 Nov 2021.*
```

2021-11-22 20:40 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# .. math:: |k_n\rangle = U_n^{\dagger} |k\rangle
```suggestion
# the ket and add it to the bra:
# 
# .. math:: \langle b_n | = \langle b | U_n,
#
# .. math:: |k_n\rangle = U_n^{\dagger} |k\rangle .
```

2021-11-22 20:40 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# For the ket vector, you can think of :math:`U_n^{\dagger}` as "eating" it's
```suggestion
# For the ket vector, you can think of :math:`U_n^{\dagger}` as "eating" its
```

2021-11-22 20:40 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +#       \langle 0 | U_1^{\dagger} \dots \frac{\text{d} U_i^{\dagger}}{\text{d} \theta_i} \dots M \dots U_i \dots U_1 | 0\rangle
```suggestion
# the ket. Therefore, we use the product rule to take the derivative with respect to both locations:
# 
# .. math::
#       \frac{\partial \langle M \rangle}{\partial \theta_i} = 
#       \langle 0 | U_1^{\dagger} \dots \frac{\text{d} U_i^{\dagger}}{\text{d} \theta_i} \dots M \dots U_i \dots U_1 | 0\rangle.
```

2021-11-22 20:40 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +#       = 2 \cdot \text{Re}\left( \langle 0 | U_1^{\dagger} \dots U_i^{\dagger} \dots M \dots \frac{\text{d} U_i}{\text{d} \theta_i}  \dots U_1 |0\rangle \right)
```suggestion
# When we add them together, the imaginary part cancels out, and we obtain twice the
# value of the real part:
# 
# .. math::
#       = 2 \cdot \text{Re}\left( \langle 0 | U_1^{\dagger} \dots U_i^{\dagger} \dots M \dots \frac{\text{d} U_i}{\text{d} \theta_i}  \dots U_1 |0\rangle \right).
```

2021-11-22 20:40 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# .. math:: |\Psi\rangle = U_{n} U_{n-1} \dots U_0 |0\rangle
```suggestion
# .. math:: |\Psi\rangle = U_{n} U_{n-1} \dots U_0 |0\rangle.
```

2021-11-22 20:40 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# Thus we can write easily calculate their derivatives:
```suggestion
# Thus we can easily calculate their derivatives:
```

2021-11-22 20:40 UTC, glassnotes commented on demonstrations/tutorial_adjoint_diff.py
> +# memory-efficient method for computing quantum gradients on statevector simulators. Tyson Jones and Julien Gacon describe this
```suggestion
# memory-efficient method for computing quantum gradients on state vector simulators. Tyson Jones and Julien Gacon describe this
```

2021-11-22 20:42 UTC, albi3ro commented on demonstrations/tutorial_adjoint_diff.py
> +# Author: PennyLane dev team. Posted: 23 Nov 2021. Last updated: 23 Nov 2021.
```suggestion
# *Author: PennyLane dev team. Posted: 23 Nov 2021. Last updated: 23 Nov 2021.*
```

2021-11-22 20:56 UTC, trbromley approved these changes
Thanks @albi3ro, nice demo!

2021-11-22 22:49 UTC, co9olguy commented on demonstrations/tutorial_adjoint_diff.py
> +    :property="og:description": Learn how the adjoint differentiation method works.
```suggestion
    :property="og:description": Learn how to use the adjoint method to compute gradients of quantum circuits."
```

2021-11-22 22:49 UTC, co9olguy commented on demonstrations/tutorial_adjoint_diff.py
> +    :property="og:description": Learn how the adjoint differentiation method works.
Adjoint method is the name of a more general technique as well, so good to link to quantum computing here

2021-11-22 22:50 UTC, co9olguy commented on demos_getting-started.rst
> +    :tooltip: Learn how adjoint differentiation works
```suggestion
    :tooltip: Learn how to compute gradients of quantum circuits with the adjoint method.
```

2021-11-23 07:06 UTC, merged