Refactor the tutorial "Quantum Chemistry with PennyLane"
PennyLaneAI/qml pull request #282
Opened 2021-06-12 00:51 UTC by agran2018

WIP: Refactoring of the tutorial [Quantum chemistry with PennyLane](https://pennylane.ai/qml/demos/tutorial_quantum_chemistry.html)

**Summary:**
Proposed title: "Building molecular Hamiltonians with PennyLane"

Goal: The new version of the tutorial should be shorter, focused on the PL functionalities for building the electronic
Hamiltonian of a molecule and easy to digest for users with little or no background in quantum chemistry.

2021-06-15 20:36 UTC, glassnotes reviewed
Just leaving some first comments, have read up to "Advanced features" so far. Will go through more closely tomorrow :+1:

2021-06-15 20:36 UTC, glassnotes commented on demonstrations/tutorial_quantum_chemistry.py
> +:math:`\Psi(r)` satisfies the `Schr\"odinger equation
```suggestion
:math:`\Psi(r)` satisfies the `Schrödinger equation
```

2021-06-15 20:36 UTC, glassnotes commented on demonstrations/tutorial_quantum_chemistry.py
> +In this tutorial, we demonstrate how to use PennyLane's functionalities to build a
This is laid out really clearly :100: My only suggestion would be that these can be reframed in a more reader-centric way, e.g., "In this tutorial *you* will learn how to use PennyLane to build a representation"...

2021-06-15 20:36 UTC, glassnotes commented on demonstrations/tutorial_quantum_chemistry.py
> +.. figure:: ../demonstrations/quantum_chemistry/water_structure.png
It is a bit difficult to make out the labels on the graphic, perhaps it can be made larger, or the labels can be put beside the atoms instead of on top?

2021-06-15 20:36 UTC, glassnotes commented on demonstrations/tutorial_quantum_chemistry.py
> +the atoms and it can be specified using different `chemical file formats
```suggestion
its constituent atoms. It can be specified using different `chemical file formats

```

2021-06-15 20:36 UTC, glassnotes commented on demonstrations/tutorial_quantum_chemistry.py
> +# The :func:`~.pennylane_qchem.qchem.read_structure` can also be used to read the
```suggestion
# The :func:`~.pennylane_qchem.qchem.read_structure` function can also be used to read the

```

2021-06-15 20:36 UTC, glassnotes commented on demonstrations/tutorial_quantum_chemistry.py
> +# second-quantization [#fetterbook]_ formalism as it is shown with more details in the
```suggestion
# second-quantization [#fetterbook]_ formalism, which we will explore in more detail in the

```

2021-06-15 20:36 UTC, glassnotes commented on demonstrations/tutorial_quantum_chemistry.py
> +# particle that moves under the influence of the nuclei Coulomb potential and a mean
```suggestion
# particle that moves under the influence of the nucleus' Coulomb potential and a mean
```
(not sure about this one)

2021-06-15 20:36 UTC, glassnotes commented on demonstrations/tutorial_quantum_chemistry.py
> +# <https://sunqm.github.io/pyscf/>`_ or `Psi4 <http://www.psicode.org/>`_. In this case
```suggestion
# the Hartree-Fock calculation using either the quantum chemistry package `PySCF
# <https://sunqm.github.io/pyscf/>`_, or `Psi4 <http://www.psicode.org/>`_. Here

```

2021-06-15 20:36 UTC, glassnotes commented on demonstrations/tutorial_quantum_chemistry.py
> +# Once the calculation is completed,the string variable ``hf_file`` returned by the
```suggestion
# Once the calculation is completed, the string variable ``hf_file`` returned by the

```

2021-06-15 21:57 UTC, agran2018 commented on demonstrations/tutorial_quantum_chemistry.py
> +# particle that moves under the influence of the nuclei Coulomb potential and a mean
We can rephrase it as:

"under the influence of the Coulomb potential generated by the nuclei and ......"

2021-06-15 22:40 UTC, agran2018 commented on demonstrations/tutorial_quantum_chemistry.py
> +.. figure:: ../demonstrations/quantum_chemistry/water_structure.png
I have updated the figure, I think it looks better (?)
![Screenshot from 2021-06-15 18-38-43](https://user-images.githubusercontent.com/45397799/122132577-122e8c00-ce09-11eb-9a72-20cd1b54e407.png)

2021-06-16 22:01 UTC, ixfoduap requested changes
I like this version much more than the original; I'm happy we're making the refactoring.

I've left several suggestions for further improvements. The main comment is that the tutorial is still too heavy at parts

2021-06-17 05:19 UTC, josh146 commented on demonstrations/tutorial_quantum_chemistry.py
> +of the total energy of the molecule [#jensenbook]_.
Agree. Could be nice to have a ‘Further Reading’ section at the end for curious readers though — we get a *lot* of questions from readers asking us for textbook recommendations.

2021-06-17 05:21 UTC, josh146 commented on demonstrations/tutorial_quantum_chemistry.py
> +# Molecular orbitals are typically represented as a linear combination of *atomic* orbitals
(flyby comment: github has inserted lots of new lines into the comment suggestions, that will affect the rendering of the ReST blocks!)

2021-06-17 13:22 UTC, agran2018 commented on demonstrations/tutorial_quantum_chemistry.py
> +# Molecular orbitals are typically represented as a linear combination of *atomic* orbitals
Thanks @josh146. I have noticed that in previous tutorials.

2021-06-17 13:39 UTC, agran2018 commented on demonstrations/tutorial_quantum_chemistry.py
> +# go beyond the Hartree-Fock approximation [#kohanoff2006]. In the exact limit,
I am not sure about this one. From my perspective this is a key concept that may help the user to understand why we need to go beyond HF and where the bottleneck is. If you think this is obvious for the community, happy to remove it.

2021-06-17 19:09 UTC, agran2018 commented on demonstrations/tutorial_quantum_chemistry.py
done

2021-06-17 20:00 UTC, ixfoduap commented on demonstrations/tutorial_quantum_chemistry.py
> +# .. _hamiltonian:
What does this line do? Seems unnecessary to me

2021-06-17 20:01 UTC, ixfoduap commented on demonstrations/tutorial_quantum_chemistry.py
> +# symbols and the nuclear coordinates of the molecule as it is shown below:
```suggestion
# It is often convenient to use the :func:`~.pennylane_qchem.qchem.molecular_hamiltonian`
# function which encapsulates all the steps explained above. It simplifies the process of building
# the electronic Hamiltonian to a single line of code. We just need to input the
# symbols and the nuclear coordinates of the molecule, as shown below:

```

2021-06-17 20:04 UTC, ixfoduap commented on demonstrations/tutorial_quantum_chemistry.py
> +# molecular geometry from a external file.
```suggestion
# molecular geometry from an external file.

```

2021-06-17 20:05 UTC, ixfoduap approved these changes
:shipit:

2021-06-17 20:39 UTC, glassnotes approved these changes
Awesome @agran2018, this lays out all the methods and steps really clearly :tada:  Just some phrasing suggestions, otherwise I think it's good to go :+1:

2021-06-17 20:39 UTC, glassnotes commented on demonstrations/tutorial_quantum_chemistry.py
> +    :property="og:description": Learn how to build the electronic Hamiltonian of molecules.
```suggestion
    :property="og:description": Learn how to build electronic Hamiltonians of molecules.

```

2021-06-17 20:39 UTC, glassnotes commented on demonstrations/tutorial_quantum_chemistry.py
> +the electronic Hamiltonian depends parametrically on the nuclear coordinates.
```suggestion
the electronic Hamiltonian depend parametrically on the nuclear coordinates.

```

2021-06-17 20:39 UTC, glassnotes commented on demonstrations/tutorial_quantum_chemistry.py
> +.. figure:: ../demonstrations/quantum_chemistry/water_structure.png
Much better! :tada:

2021-06-17 20:39 UTC, glassnotes commented on demonstrations/tutorial_quantum_chemistry.py
> +#     \sum_j C_j \prod_i \sigma_i^{(j)},
```suggestion
#     \sum_j C_j \otimes_i \sigma_i^{(j)},
```

2021-06-17 20:39 UTC, glassnotes commented on demonstrations/tutorial_quantum_chemistry.py
> +# functionalities to compute the electron integrals using the previously generated
```suggestion
#  to compute the electron integrals using the previously generated
```

2021-06-17 20:39 UTC, glassnotes commented on demonstrations/tutorial_quantum_chemistry.py
> +print(H)
Is it worth pointing out that the Hamiltonian terms are in a different order here, just because the output looks very different than the output generated above.

2021-06-17 20:39 UTC, glassnotes commented on demonstrations/tutorial_quantum_chemistry.py
> +# As it was mentioned above, molecular orbitals are represented as linear combination
```suggestion
# As mentioned above, molecular orbitals are represented as a linear combination
```

2021-06-17 20:39 UTC, glassnotes commented on demonstrations/tutorial_quantum_chemistry.py
> +# of `Gaussian atomic basis <https://www.basissetexchange.org/>`_. In this example we
```suggestion
# of `Gaussian atomic bases <https://www.basissetexchange.org/>`_. In this example we

```

2021-06-17 20:39 UTC, glassnotes commented on demonstrations/tutorial_quantum_chemistry.py
>  #
```suggestion
```

(Merge into one paragraph?)

2021-06-17 20:47 UTC, agran2018 commented on demonstrations/tutorial_quantum_chemistry.py
> +print(H)
Good point.

2021-07-16 12:29 UTC, merged

2021-07-16 20:20 UTC, co9olguy commented on demonstrations/tutorial_quantum_chemistry.py
> +# of `Gaussian atomic basis <https://www.basissetexchange.org/>`_. In this example we
was this suggestion missed?