Remove QPU line from PyTorch demo
PennyLaneAI/qml pull request #288
Opened 2021-06-16 16:41 UTC by antalszava

[PennyLane-Forest has discontinued support for the Rigetti QPU](https://github.com/PennyLaneAI/pennylane-forest/pull/68), this PR removes the reference to that device.

2021-06-16 16:59 UTC, co9olguy commented on demonstrations/pytorch_noise.py
> +*Author: PennyLane dev team. Last updated: 16 Jun 2020.*
```suggestion
*Author: PennyLane dev team. Last updated: 16 Jun 2021.*
```

2021-06-16 17:00 UTC, co9olguy commented
We might want to consider more than a single-line change to this demo, since it seems specifically written for QPU examples, e.g., "Extend PyTorch with real quantum computing power, by using it to optimize a noisy quantum hardware device."

2021-06-16 22:06 UTC, co9olguy commented on demonstrations/pytorch_noise.py
> +# Note that to run the following script, you will need access to Rigetti's QPU.
maybe also update the reference to Forest here

2021-06-16 22:06 UTC, co9olguy commented on demonstrations/pytorch_noise.py
>  # As PyTorch natively supports GPU-accelerated classical processing, and Forest provides
whuggins@google.com

2021-06-16 22:07 UTC, co9olguy commented on demonstrations/pytorch_noise.py
>     tutorial_noisy_circuit_optimization Optimizing noisy circuits with Cirq
nathan+test@xanadu.ai

2021-06-16 23:06 UTC, albi3ro commented on demonstrations/pytorch_noise.py
> +# modification, we can run the above code as a hybrid GPU-QPU optimization.
```suggestion
# Braket provides quantum hardware access in the form of QPUs, we can run the above code 
# as a hybrid GPU-QPU optimization with very little modifications.
```

2021-06-16 23:45 UTC, albi3ro reviewed
First I was confused and thought everything forest related was deprecated, then I realized it was just QPU access.

I think out of the gate we should start saying we are using the Rigetti's ``forest.qvm`` simulator and comparing it to Rigetti's AWS Braket QPU.

Also, is `forext.qvm` a GPU simulator? The first time you mention GPU is during the hybrid optimization paragraph.  

A big bottleneck with GPU calculations is getting data to and from the GPU. If the data has to go to and from a remote QPU each time, what's the benefit of running it on a GPU? I'm not convinced.

2021-06-17 01:12 UTC, antalszava commented
Thanks for the comments!

> I think out of the gate we should start saying we are using the Rigetti's forest.qvm simulator and comparing it to Rigetti's AWS Braket QPU.

Added a mention at the beginning.

> Also, is forext.qvm a GPU simulator? The first time you mention GPU is during the hybrid optimization paragraph.

There is a mention of the QVM at the beginning of the tutorial. Torch provides the GPU support.

> A big bottleneck with GPU calculations is getting data to and from the GPU. If the data has to go to and from a remote QPU each time, what's the benefit of running it on a GPU? I'm not convinced.

Sounds reasonable, perhaps this could be a reason to reconsider the content of the demo.

2021-06-17 15:19 UTC, albi3ro commented on demonstrations/pytorch_noise.py
> +Amazon Braket.
👍

2021-06-17 15:25 UTC, albi3ro commented on demonstrations/pytorch_noise.py
> +# Braket](https://pennylane.ai/qml/demos/braket-parallel-gradients.html).
```suggestion
# on using Amazon Braket, see our tutorial on
# `Computing gradients in parallel with Amazon Braket <https://pennylane.ai/qml/demos/braket-parallel-gradients.html>`_
```
This link needs to be in rst form, not markdown form.

2021-06-17 15:26 UTC, albi3ro requested changes
Just need to fix the link that's not rendering properly, and then I'll approve :)

2021-06-17 15:29 UTC, antalszava commented
@albi3ro good catch, thanks! Updated

2021-06-17 15:29 UTC, albi3ro approved these changes
Good improvement :)

2021-06-17 17:25 UTC, merged