Refactor the tutorial "A brief overview of VQE"
PennyLaneAI/qml pull request #293
Opened 2021-06-21 02:46 UTC by agran2018

WIP: Refactoring the [tutorial on VQE.](https://pennylane.ai/qml/demos/tutorial_vqe.html)

2021-06-23 17:33 UTC, glassnotes requested changes
@agran2018 these improvements are great! The tutorial is very straightforward and reads clearly. I've just left some minor text and phrasing suggestions for variety.

2021-06-23 17:33 UTC, glassnotes commented on demonstrations/tutorial_vqe.py
> +cost function to evaluate the expectation value of the Hamiltonian in the
```suggestion
The inputs to the VQE algorithm are a molecular Hamiltonian, a
parametrized circuit preparing the quantum state of the molecule, and a
cost function to evaluate the expectation value of the Hamiltonian in the
```
For this sentence:
- "a" instead of "the" just to indicate that choices of these things are not unique
- for "inputs to the VQE algorithms", should algorithms be singular? There are many different variants of VQE, but since we are focusing on the "main" one.

2021-06-23 17:33 UTC, glassnotes commented on demonstrations/tutorial_vqe.py
> +by a classical optimizer which uses a quantum computer to evaluate the cost function
```suggestion
an iterative minimization of the cost function. Optimization is carried out
by a classical optimizer which leverages a quantum computer to evaluate the cost function
```

2021-06-23 17:33 UTC, glassnotes commented on demonstrations/tutorial_vqe.py
> +state of the molecule and the cost function to evaluate the expectation value
```suggestion
state of the molecule, and the cost function to evaluate the expectation value
```

2021-06-23 17:33 UTC, glassnotes commented on demonstrations/tutorial_vqe.py
> +basis set approximation. Next, we define the quantum circuit preparing the trial
```suggestion
basis set approximation. Next, we design the quantum circuit preparing the trial
```

2021-06-23 17:33 UTC, glassnotes commented on demonstrations/tutorial_vqe.py
> +of the Hamiltonian. Finally, we define the classical optimizer, initialize the
```suggestion
of the Hamiltonian. Finally, we select a classical optimizer, initialize the
```

2021-06-23 17:33 UTC, glassnotes commented on demonstrations/tutorial_vqe.py
> +# The molecular structure can also be imported from a external file using
```suggestion
# The molecular structure can also be imported from an external file using
```

2021-06-23 17:33 UTC, glassnotes commented on demonstrations/tutorial_vqe.py
> +# required for the quantum simulations. In this example, we use a
```suggestion
# required for the quantum simulations. For this example, we use a
```

2021-06-23 17:33 UTC, glassnotes commented on demonstrations/tutorial_vqe.py
> +# From here on, we can use PennyLane as usual, employing its entire stack of
Move this sentence to the start of the next section?

2021-06-23 17:33 UTC, glassnotes commented on demonstrations/tutorial_vqe.py
> +# tutorial :doc:`tutorial_givens_rotations`.
Just a note to double check rendering on this link when the other tutorial is available.

2021-06-23 17:33 UTC, glassnotes commented on demonstrations/tutorial_vqe.py
> +# Implementing the circuit above using PennyLane is straightforward. First, we use
```suggestion
# Implementing the circuit above using PennyLane is straightforward. First, we use the 
```

2021-06-23 17:33 UTC, glassnotes commented on demonstrations/tutorial_vqe.py
> +# class tailored for VQE optimization. It requires specifying the
```suggestion
# class, which is tailored for VQE optimization. It requires specifying the
```

2021-06-23 17:33 UTC, glassnotes commented on demonstrations/tutorial_vqe.py
> +# To that aim we need to define the classical optimizer. PennyLane offers different
```suggestion
# the :math:`\mathrm{H}_2` molecule. To start, we need to define the classical optimizer. PennyLane offers different
```

2021-06-23 17:33 UTC, glassnotes commented on demonstrations/tutorial_vqe.py
> +# see the tutorial :tutorial:`tutorial_vqe_qng`. Here we use a basic
```suggestion
# method which can speed up VQE simulations. Here we use a basic
```

2021-06-23 17:33 UTC, glassnotes commented on demonstrations/tutorial_vqe.py
> +# built-in optimizers including the quantum natural gradient
Make the "quantum natural gradient" text here link directly to the tutorial rather than having it in a separate sentence.

However, it may be worth removing mention of the QNG altogether since we're not using it, and just link to the list of optimizers in the docs.

2021-06-23 17:33 UTC, glassnotes commented on demonstrations/tutorial_vqe.py
>  # -6}`.
```suggestion
# We carry out the optimization over a maximum of 100 steps aiming to reach a
# convergence tolerance of :math:`\sim 10^{-6}` for the value of the cost function.
```

2021-06-23 17:33 UTC, glassnotes commented on demonstrations/tutorial_vqe.py
> +plt.show()
Awesome plots! :rocket:

2021-06-23 17:33 UTC, glassnotes commented on demonstrations/tutorial_vqe.py
> +# We have used the VQE algorithm to correct the Hartree-Fock energy of the
There is a conceptual jump here when mentioning electronic correlations; it feels a bit disjoint and the concept hasn't been mentioned earlier. For this paragraph, I recommend instead to just include a brief recap of the methods, and then mention some of the extensions or suggested further reading. Also since VQE is a popular tutorial, it would be a good idea to provide here some explicit suggestions of which demos to explore next.

2021-06-23 17:41 UTC, agran2018 commented on demonstrations/tutorial_vqe.py
> +# We have used the VQE algorithm to correct the Hartree-Fock energy of the
Good! Yesterday this paragraph was bothering me precisely for the conceptual jump. Thanks @glassnotes for your feedback on this.

2021-06-23 20:23 UTC, ixfoduap requested changes
Very smooth read! So much cleaner than before.

Left a few suggestions, the only major ones are:
- Let's use qml.expval(H) instead of ExpvalCost
- Conclusion needs to be improved

Great job! :rocket:

2021-06-23 20:23 UTC, ixfoduap commented on demonstrations/tutorial_vqe.py
> +Without loss of generality, we apply the algorithm to find the ground state of the hydrogen
```suggestion
As an illustrative example, we apply the algorithm to find the ground state of the hydrogen
```
It does lose generality, as you need a different circuit to tackle other molecules

2021-06-23 20:23 UTC, ixfoduap commented on demonstrations/tutorial_vqe.py
> +# using the :func:`molecular_hamiltonian` function.
link to `molecular_hamiltonian` is broken

2021-06-23 20:23 UTC, ixfoduap commented on demonstrations/tutorial_vqe.py
> +# a linear combination of Pauli operators and the number of qubits
```suggestion
# The outputs of the function are the Hamiltonian, represented as 
# a linear combination of Pauli operators, and the number of qubits
```

2021-06-23 20:23 UTC, ixfoduap commented on demonstrations/tutorial_vqe.py
> +# In this approximation, we have a four spin orbitals which defines the
```suggestion
# In this approximation, we have a four spin orbitals, which defines the
```

2021-06-23 20:23 UTC, ixfoduap commented on demonstrations/tutorial_vqe.py
> +# molecule. In the Jordan-Wigner [#seeley2012]_ encoding the
```suggestion
# molecule. In the Jordan-Wigner [#seeley2012]_ encoding, the
```

2021-06-23 20:23 UTC, ixfoduap commented on demonstrations/tutorial_vqe.py
> +# entangled state,
```suggestion
# entangled state
```

2021-06-23 20:23 UTC, ixfoduap commented on demonstrations/tutorial_vqe.py
> +# *ansatz* for the ground state of the :math:`\mathrm{H}_2` molecule is given by the
I find this confusing and misleading: how do we know the ground-state has this form? And if it is a ground state, then theta is not a variational parameter.

I think this should be rephrased to say that we want to prepare states of this form, and find the value of theta that leads to the best approximation to the true ground state.

2021-06-23 20:23 UTC, ixfoduap commented on demonstrations/tutorial_vqe.py
> +# shown in the figure below.
```suggestion
# schematically illustrated in the figure below.
```

2021-06-23 20:23 UTC, ixfoduap commented on demonstrations/tutorial_vqe.py
> +# function. We do this using the :class:`~.ExpvalCost`
```suggestion
# of the molecular Hamiltonian in the trial state prepared by the circuit.
# We do this using the :class:`~.ExpvalCost`
```

2021-06-23 20:23 UTC, ixfoduap commented on demonstrations/tutorial_vqe.py
> +# class tailored for VQE optimization. It requires specifying the
I suggest we change this usage in this tutorial, and instead pass `H` directly to `qml.expval()` as a return to the QNode.

This is new functionality implemented by Jack and it's good to steer users towards it

2021-06-23 20:23 UTC, ixfoduap commented on demonstrations/tutorial_vqe.py
> +# class tailored for VQE optimization. It requires specifying the
Of course, this means revising the paragraph above. We should say that the circuit returns the expectation value of the Hamiltonian, and so the cost function is the circuit itself

2021-06-23 20:23 UTC, ixfoduap commented on demonstrations/tutorial_vqe.py
>  # -6}`.
remove \sim, just use 10^-6

2021-06-23 20:23 UTC, ixfoduap commented on demonstrations/tutorial_vqe.py
> +# We have used the VQE algorithm to correct the Hartree-Fock energy of the
Yep, this conclusion needs further improvement

2021-06-23 20:37 UTC, agran2018 commented on demonstrations/tutorial_vqe.py
> +cost function to evaluate the expectation value of the Hamiltonian in the
Good point. Perhaps the cost function is an input for more general VQAs, for the VQE not clear. I will modify this.

2021-06-23 22:42 UTC, agran2018 commented on demonstrations/tutorial_vqe.py
> +# class tailored for VQE optimization. It requires specifying the
I just talked to Jack, it seems that this is not supported yet within a qnode. The example below throws an error when you try to evaluate the cost function.

```python
import pennylane as qml
import numpy as np

symbols = ['H', 'H']
coordinates = np.array([0.0, 0.0, -0.6614, 0.0, 0.0, 0.6614])

H, qubits = qml.qchem.molecular_hamiltonian(symbols, coordinates)

dev = qml.device('default.qubit', wires=qubits)

hf = qml.qchem.hf_state(electrons=2, orbitals=qubits)

@qml.qnode(dev)
def circuit(param):
    qml.BasisState(hf, wires=range(qubits))
    qml.DoubleExcitation(param, wires=[0, 1, 2, 3])
    return qml.expval(H)

def cost_fn(x):
    return circuit(x)   

print(cost_fn(0))
```

2021-06-23 23:52 UTC, agran2018 commented on demonstrations/tutorial_vqe.py
> +# We do this using the :class:`~.ExpvalCost`
I just talked to Jack, it seems that ``qml.expval(H)`` is not supported yet within a qnode. The example below throws an error when you try to evaluate the cost function.

```python
import pennylane as qml
import numpy as np

symbols = ['H', 'H']
coordinates = np.array([0.0, 0.0, -0.6614, 0.0, 0.0, 0.6614])

H, qubits = qml.qchem.molecular_hamiltonian(symbols, coordinates)

dev = qml.device('default.qubit', wires=qubits)

hf = qml.qchem.hf_state(electrons=2, orbitals=qubits)

@qml.qnode(dev)
def circuit(param):
    qml.BasisState(hf, wires=range(qubits))
    qml.DoubleExcitation(param, wires=[0, 1, 2, 3])
    return qml.expval(H)

def cost_fn(x):
    return circuit(x)   

print(cost_fn(0))
```

2021-06-24 05:55 UTC, josh146 commented on demonstrations/tutorial_vqe.py
> +# We do this using the :class:`~.ExpvalCost`
Yep, that's right - @Lucaman99 has provided all the logic required to support `qml.expval(H)`, the last stumbling block is making it accessible via the UI, which is non-trivial 🙂 Work towards supporting this is being done here: https://github.com/PennyLaneAI/pennylane/pull/1362

2021-06-24 18:48 UTC, ixfoduap commented on demonstrations/tutorial_vqe.py
> +# In the tutorial :doc:`tutorial_vqe_bond_dissociation` we use VQE to explore the
```suggestion
# In the tutorial :doc:`tutorial_vqe_bond_dissociation`, we use VQE to explore the
```

2021-06-24 19:05 UTC, ixfoduap requested changes
Just a few stylistic changes. Should be good to go once these are made!

2021-06-24 19:05 UTC, ixfoduap commented on demonstrations/tutorial_vqe.py
> +# In this figure the gate :math:`G^{(2)}` corresponds to the
```suggestion
# In this figure, the gate :math:`G^{(2)}` corresponds to the
```

2021-06-24 19:05 UTC, ixfoduap commented on demonstrations/tutorial_vqe.py
>  # circuit, target Hamiltonian, and the device, and returns a cost function that can
```suggestion
# circuit, target Hamiltonian, and the device, then returning a cost function that can
```

2021-06-24 19:05 UTC, ixfoduap commented on demonstrations/tutorial_vqe.py
> +# `optimizers <https://pennylane.readthedocs.io/en/stable/introduction/optimizers.html>`_
```suggestion
# `optimizers <https://pennylane.readthedocs.io/en/stable/introduction/optimizers.html>`_ .
```

2021-06-24 19:05 UTC, ixfoduap commented on demonstrations/tutorial_vqe.py
> +# We initialize the circuit parameter :math:`\theta` to zero so we start
```suggestion
# We initialize the circuit parameter :math:`\theta` to zero, meaning that we start
```

2021-06-24 19:05 UTC, ixfoduap commented on demonstrations/tutorial_vqe.py
> +#
I like the new conclusion, but it may eb good to add a header

Conclusion
---------------

To help with the flow

2021-06-25 19:36 UTC, glassnotes approved these changes
@agran2018 looks awesome! Happy to approve, and then we'll just have to update the date / links once it's ready to be merged.

2021-06-25 19:36 UTC, glassnotes commented on demonstrations/tutorial_vqe.py
>  # For a more details on how to use the excitation operations to build
```suggestion
# For more details on how to use the excitation operations to build
```

2021-06-25 19:36 UTC, glassnotes commented on demonstrations/tutorial_vqe.py
> +# circuit, target Hamiltonian, and the device, then returning a cost function that can
```suggestion
# circuit, target Hamiltonian, and the device, and it returns a cost function that can
```

2021-06-25 19:36 UTC, glassnotes commented on demonstrations/tutorial_vqe.py
> +# `optimizers <https://pennylane.readthedocs.io/en/stable/introduction/optimizers.html>`_ .
```suggestion
# PennyLane offers many different built-in
# `optimizers <https://pennylane.readthedocs.io/en/stable/introduction/optimizers.html>`_.
```

2021-06-25 19:36 UTC, glassnotes commented on demonstrations/tutorial_vqe.py
> +# Full configuration interaction (FCI) energy computed classically
It will not let me comment directly, but for the print statements on lines 193-195 in the example above, you can remove the first one that's just `print()` and add another `"\n"` in the line after.

2021-06-25 19:36 UTC, glassnotes commented on demonstrations/tutorial_vqe.py
> +# tutorial :doc:`tutorial_mol_geo_opt`.
Nice!! :tada:

Just leaving a reminder here as well to double check the link rendering once those demos are available.

2021-06-25 22:18 UTC, ixfoduap approved these changes

2021-07-16 12:39 UTC, merged