Refactor tutorial "VQE in different spin sectors"
PennyLaneAI/qml pull request #299
Opened 2021-06-24 20:32 UTC by agran2018

WIP: Refactoring of the tutorial [VQE in different spin sectors](https://pennylane.ai/qml/demos/tutorial_vqe_uccsd_obs.html).

**Summary:**

- Shorten the introduction.
- Replace UCCSD with the new [AllSinglesDoubles](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.templates.subroutines.AllSinglesDoubles.html) template.
- Add figure illustrating how to create excitations in different spin sectors.
- Polish style and English.

2021-07-02 19:45 UTC, glassnotes requested changes
@agran2018 I have just done a quick review, will take another look next week. Overall it reads smoothly and is very concise :rocket:

2021-07-02 19:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +to find the lowest-energy eigenstate of the electronic Hamiltonian of a molecule using a
```suggestion
for finding the lowest-energy eigenstate of the electronic Hamiltonian of a molecule using a
```
Consider also splitting this sentence into two, as it's a bit long.

2021-07-02 19:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +spectra of the hydrogen molecule. In this case, the ground state has total spin :math:`S=0`
```suggestion
spectrum of the hydrogen molecule. In this case, the ground state has total spin :math:`S=0`
```
?

2021-07-02 19:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +the eigenstates of the molecular Hamiltonian can be computed in a specific sector of the total
Briefly explain what is meant by sector - is it just a subset of the possible values of spin?

2021-07-02 19:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +For the sake of simplicity, we illustrate this for the hydrogen molecule although
```suggestion
For the sake of simplicity, we illustrate this for the hydrogen molecule, although
```

2021-07-02 19:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# We use the :func:`~.pennylane_qchem.qchem.spin2` function to build the
I was going to comment that the above equation looked a bit scary, but now I see that there is just a built-in function for it :tada:

2021-07-02 19:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# the UCCSD unitary is given by [#barkoutsos2018]_,
```suggestion
# the UCCSD unitary is given by [#barkoutsos2018]_
```

2021-07-02 19:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# .. figure:: /demonstrations/vqe_spin_sectors/fig_excitations.png
For this graphic, perhaps choose a colour like pink or red that is more easily differentiated from the black; I found it a bit hard to distinguish the black and blue.

2021-07-02 19:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# single and double excitations. Even and odd indices correspond, respectively, to to spin-up
```suggestion
# single and double excitations. Even and odd indices correspond, respectively, to spin-up
```

2021-07-02 19:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# We define a function to compute the total spin
```suggestion
# We define a function to compute the total spin.
```

2021-07-02 19:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# excitations whose total-spin projection differs by the quantity ``delta_sz=1`
```suggestion
# excitations whose total-spin projection differs by the quantity ``delta_sz=1``
```

2021-07-02 19:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# double excitations but only a spin-flip single excitation from qubit 1 to 2.
```suggestion
# double excitations, but only a spin-flip single excitation from qubit 1 to 2.
```

2021-07-02 19:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# And, that's it!. From this point on the algorithm is the same as described above.
```suggestion
# And, that's it! From this point on the algorithm is the same as described above.
```

2021-07-02 19:45 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# the trial states of molecule. By choosing the total-spin projection of the single- and
```suggestion
# the trial states of a molecule. By choosing the total-spin projection of the single- and 
```

2021-07-12 21:01 UTC, ixfoduap commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# mapping of the molecular Hamiltonian.
```suggestion
# :func:`~.pennylane_qchem.qchem.molecular_hamiltonian` function.
```

2021-07-12 21:02 UTC, ixfoduap commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# :math:`\hat{c}` and :math:`\hat{c}^\dagger` are, respectively, the electron annihilation and
```suggestion
# :math:`\hat{c}` and :math:`\hat{c}^\dagger` are respectively the electron annihilation and
```

2021-07-12 21:03 UTC, ixfoduap commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# In this example, we use the unitary coupled cluster *ansatz* truncated to the level of
```suggestion
# In this example, we use the unitary coupled cluster ansatz truncated to the level of
```

2021-07-12 21:04 UTC, ixfoduap commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# function to generate the vector representing the HF state :math:`\vert 1100 \rangle` of the
```suggestion
# function to generate the vector representing the Hartree-Fock state :math:`\vert 1100 \rangle` of the
```

2021-07-12 21:08 UTC, ixfoduap commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# .. figure:: /demonstrations/vqe_spin_sectors/fig_excitations.png
Agree with Olivia! Otherwise, very helpful image!

2021-07-12 21:11 UTC, ixfoduap commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# In the last part of the tutorial we use VQE to find the lowest-lying
```suggestion
# In the last part of the tutorial, we use VQE to find the lowest-lying
```

2021-07-12 21:18 UTC, ixfoduap commented on demonstrations/tutorial_vqe_spin_sectors.py
> +##############################################################################
I think this deserves a short paragraph emphasizing what is happening here. I'm actually still confused as to why this works. My understanding is:

We apply excitation gates that change the total spin projection. If the gate parameters are sufficiently large that the gates significantly transform the initial state, the output state of the circuit will have a large spin projection. As we optimize the gate parameters, we can converge to a local minima corresponding to a state with total spin projection 1.

Note that the energy of this excited state is larger than the HF energy of the ground state. So if the circuit parameters were initialized to 0, I expect that the optimizer would get stuck and remain in the HF state.

2021-07-16 00:41 UTC, agran2018 commented on demonstrations/tutorial_vqe_spin_sectors.py
> +##############################################################################
I think I understand why applying the ``SingleExcitation`` operation here doesn't work:

|Psi(theta)> = SingleExcitation(theta) |HF> = cos(theta/2) |1100> - sin(theta/2) |1010>

This is a superposition of two Slaters with ``Sz=0`` and ``Sz=1``. So, unless you pass ``theta=Pi``, which gives us the wave function of the excited state, the optimizer will always find the HF state (``theta = 2*n*Pi``). In other words, the trial state contains contributions from different sectors of ``Sz``.

On the other hand, UCCSD (in this case only given by the [SingleExcitationUnitary](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.templates.subroutines.SingleExcitationUnitary.html) always find the excited state with S=1, Sz=1, independently of the initial value of the circuit parameter. This makes me think that the state prepared by the UCCSD is of the form ``C(theta) |1010>`` which forces the optimizer to stay in this sector of Sz. Indeed, the excited state of the H2 molecule can not contain a contribution from the HF state.

2021-07-16 21:54 UTC, agran2018 commented on demonstrations/tutorial_vqe_spin_sectors.py
> +##############################################################################
The new version should clarify this.

2021-07-21 21:35 UTC, ixfoduap requested changes
In the end this may not be our best tutorial, but I still think the idea behind the optimization in a different spin sector needs to be explained better. Happy to discuss offline if needed

2021-07-21 21:35 UTC, ixfoduap commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# :class:`~.pennylane.templates.subroutines.AllSinglesDoubles` function.
```suggestion
# :class:`~.pennylane.templates.subroutines.AllSinglesDoubles` template.
```

2021-07-21 21:35 UTC, ixfoduap commented on demonstrations/tutorial_vqe_spin_sectors.py
> +#     + C_{0123}(\theta) \vert 0011 \rangle
make the coefficients lowercase, i.e., `c` instead of `C`

2021-07-21 21:35 UTC, ixfoduap commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# the Hartree-Fock (HF) state with all possible single and double excitations that preserve
```suggestion
# Hartree-Fock (HF) state with all possible single and double excitations that preserve
```

2021-07-21 21:35 UTC, ixfoduap commented on demonstrations/tutorial_vqe_spin_sectors.py
> +##############################################################################
I think it's still a bit unclear... See my comments below

2021-07-21 21:35 UTC, ixfoduap commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# excitation :math:`\vert 0011 \rangle`.
Need to explain why we initialize the circuit this way! This is crucial: we always talk about starting from the HF state, and all of a sudden we don't?

And why do we start from the doubly-excited state and not another one?

2021-07-21 21:35 UTC, ixfoduap commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# should vanish as the VQE algorithm minimizes the cost function. The optimized state will
Wait, so the excited state is just |0101>? Then isn't the optimization trivial?

Also, it's not why the fact that evolution under the Hamiltonian conserves spin implies that this coefficient vanishes

2021-07-22 19:41 UTC, glassnotes requested changes
The demo flows really nice, and the code examples are clear! My only suggestion is to include some details at the beginning to more explicitly lay out what is about to happen. For example, it would be good to discuss conceptually how the optimization process / VQE will be different for different sectors.  I know this is a vague suggestion, so for context, what happened for me on this readthrough is that I think I suddenly understood things because of a line in the conclusion (I noted which one). Being aware of the algorithmic differences early on would help show how and why things were changing when we switched from S = 0 to S = 1.

2021-07-22 19:41 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +spin quantum numbers. For example, this allows us to find the energy of the electronic states
```suggestion
spin quantum numbers. This allows us to compute quantities such as the energy of the electronic states
```

2021-07-22 19:41 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# all possible single- and double-excitations of the Hartree-Fock reference state. The indices
```suggestion
# all possible single and double excitations of the Hartree-Fock reference state. The indices
```
Don't think the `-` are needed here; in any case please check for consistency of usage throughout.

2021-07-22 19:41 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +    qml.templates.AllSinglesDoubles(params, wires, hf, singles, doubles)
Just learned about this template today, super convenient! :100:

2021-07-22 19:41 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# expectation value :math:`\langle \hat{S}^2 \rangle` as,
```suggestion
# expectation value :math:`\langle \hat{S}^2 \rangle` as
```

2021-07-22 19:41 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# We carry out the optimization over a maximum of 100 steps aiming to reach a
```suggestion
# We carry out the optimization over a maximum of 100 steps, aiming to reach a
```

2021-07-22 19:41 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# In the last part of the tutorial, we use VQE to find the lowest-lying
```suggestion
# In the last part of the tutorial, we will use VQE to find the lowest-lying
```

2021-07-22 19:41 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# The trial states prepared by the circuit above have the form,
```suggestion
# The trial states prepared by the circuit above have the form
```

2021-07-22 19:41 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# As it was mentioned in the introduction, the electronic Hamiltonian conserves the total
```suggestion
# As mentioned in the introduction, the electronic Hamiltonian conserves the total
```

2021-07-22 19:41 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# Now, we defined the new functions to compute the expectation values of the Hamiltonian
```suggestion
# Now, we define the new functions to compute the expectation values of the Hamiltonian
```

2021-07-22 19:41 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# to prepare the trial states of a molecule. By choosing the total-spin projection of the
Something clicked for me while reading this line. Perhaps this is something that can be emphasized in an earlier section (before or as the first example starts), that the way to access the different sectors is to use different kinds of excitations.

2021-07-22 19:41 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +#
This ends a bit abruptly, I think the conclusion would benefit from another line or two that briefly discuss utility / outlook for this method.

2021-07-28 23:04 UTC, agran2018 commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# to prepare the trial states of a molecule. By choosing the total-spin projection of the
I have added a brief explanation in the last paragraph of the introduction.

2021-07-28 23:14 UTC, agran2018 commented on demonstrations/tutorial_vqe_spin_sectors.py
> +#
I have been doing some tests to check whether this method is also valid to study more complicated molecules and unfortunately this is not the case. Honestly, I wouldn't know what else we could say here :-(.

2021-07-28 23:19 UTC, agran2018 commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# should vanish as the VQE algorithm minimizes the cost function. The optimized state will
The idea I wanted to convey above is that an eigenstate of the electronic Hamiltonian can not be superposition of states with different values of the total-spin projection. I just rephrased it to make it more clear.

2021-07-28 23:24 UTC, agran2018 commented on demonstrations/tutorial_vqe_spin_sectors.py
> +##############################################################################
I have added changes to improve on this.

2021-07-29 14:20 UTC, ixfoduap approved these changes
In retrospect, not our strongest demo, but the refactoring definitely makes it better. I suggest not sinking much more time on it.

2021-07-29 14:20 UTC, ixfoduap commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# operation. Additionally, as we want to probe the excited state of hydrogen molecule
```suggestion
# operation. Additionally, as we want to probe the excited state of the hydrogen molecule
```

2021-07-29 14:20 UTC, ixfoduap commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# Note that this allows us to prepare trial states of the form
```suggestion
# This allows us to prepare trial states of the form
```

2021-07-29 14:20 UTC, ixfoduap commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# Since an eigenstate of the electronic Hamiltonian can not contain a superposition of
```suggestion
# Since an eigenstate of the electronic Hamiltonian cannot contain a superposition of
```

2021-07-29 14:25 UTC, glassnotes requested changes
@agran2018 I caught just a couple typos in this pass, a few of them are mathematical so please double check those in case I got mixed up! Otherwise, pending thoughts on the conclusion, this looks good to go :+1:

2021-07-29 14:25 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# to prepare the trial states of a molecule. By choosing the total-spin projection of the
:100:

2021-07-29 14:25 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +build the electronic Hamiltonian and the total-spin operator :math:`\hat{S}^2`. Next, we use
```suggestion
build the electronic Hamiltonian and the total spin operator :math:`\hat{S}^2`. Next, we use
```

2021-07-29 14:25 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +:math:`S=0` and :math:`S=1`, we apply excitation operations which preserve and modify, respectively,
```suggestion
the trial states of the molecule. In order to probe the molecular states with different total spin,
:math:`S=0` and :math:`S=1`, we apply excitation operations which preserve and modify, respectively,
```

2021-07-29 14:25 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +:math:`S=0` and :math:`S=1`, we apply excitation operations which preserve and modify, respectively,
New additions are awesome, really helps clarify how the method will work at a high level.

2021-07-29 14:25 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# Hamiltonian in different sectors of the spin quantum numbers. We also showed how to build
```suggestion
# Hamiltonian in different sectors of the spin quantum number. We also showed how to build
```
(not sure about this one)

2021-07-29 14:25 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# which act as Givens rotations on the subspace of two and four qubits, respectively
```suggestion
# which act as Givens rotations on subspaces of two and four qubits, respectively
```

2021-07-29 14:25 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +#     + c_{23}(\theta) \vert 1001 \rangle,
```suggestion
#     + c_{13}(\theta) \vert 1001 \rangle,
```
(I think, based on which electron is excited)

2021-07-29 14:25 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# :math:`\vert 0011 \rangle`.
Isn't |0011> a double excitation away?

2021-07-29 14:25 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# lowest-lying excited states of the hydrogen molecule. We have used the single and
```suggestion
# lowest-lying excited states of the hydrogen molecule. We used the single and
```
Just to avoid repetition with previous line.

2021-07-29 14:25 UTC, glassnotes commented on demonstrations/tutorial_vqe_spin_sectors.py
> +#
Hm, in that case I'm not sure either. Maybe @ixfoduap has some suggestions?

2021-07-29 14:35 UTC, agran2018 commented on demonstrations/tutorial_vqe_spin_sectors.py
> +#     + c_{23}(\theta) \vert 1001 \rangle,
good catch! Thanks.

2021-07-29 14:46 UTC, agran2018 commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# Hamiltonian in different sectors of the spin quantum numbers. We also showed how to build
Yes, better the plural as we are probing a state with S=1, Sz=-1.

2021-07-29 15:42 UTC, agran2018 commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# :math:`\vert 0011 \rangle`.
I see. In order to avoid confusion I can rephrase it as:
"Additionally, as we want to probe the excited state of the hydrogen molecule
, we initialize the qubit register to the state :math:`\vert 0011 \rangle`"

2021-07-29 16:43 UTC, glassnotes approved these changes

2021-07-29 17:56 UTC, merged