[WIP] add adaptive circuits tutorial
PennyLaneAI/qml pull request #300
Opened 2021-06-25 15:27 UTC by soranjh

This PR adds a tutorial for building adaptive quantum chemistry circuits. It also shows how to use the sparse functionality in PL to make quantum chemistry simulations more efficient.

2021-07-09 19:56 UTC, ixfoduap requested changes
I left a lot of comments, but the tutorial is in overall great shape: very organized and clear. Once these suggestions are implemented, should hopefully be close to completion.

The only remaining part is adding nice figures, which I can take care of

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +exact ground state wavefunction and including all possible excitations increases the cost of the
```suggestion
exact ground state wavefunction. Including all possible excitations increases the cost of the
```

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +simulations without improving the accuracy of the results. This motivates implementing an strategy
```suggestion
simulations without improving the accuracy of the results. This motivates implementing a strategy
```

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +construction of the ansatz straightforward for any given molecule. However, we know that in
```suggestion
construction of the ansatz straightforward for any given molecule. However, in
```

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +that allows approximating the contribution of the excitations and select only those excitations
```suggestion
that allows approximating the contribution of the excitations and selecting only those excitations
```
What does "approximating the contribution of the excitations" means

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +gates based on the magnitude of the computed gradients. There are different ways to select the gates
```suggestion
The main idea behind building adaptive circuits is to compute the gradients with respect to all
possible excitation gates and select gates based on the magnitude of the computed gradients. 
There are different ways to select the gates
```

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +UCCSD. In this approach, one includes all possible single and double excitations of electrons from
It may also be good here to link to the Givens rotations tutorial, for readers that may not be familiar with excitations

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +based on the computed gradients and here we discuss one of these strategies to compute the ground
```suggestion
based on the computed gradients. Here we discuss one of these strategies to compute the ground
```

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +state energy of LiH. Both of these methods require constructing the Hamiltonian
I'm confused, you're mentioning discussing one strategy, then talk about two methods?

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +and determining all possible excitations which we can do with PennyLane functionalities shown below.
```suggestion
and determining all possible excitations, which we can do with PennyLane functionalities shown below.
```

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +    symbols, geometry, charge=0, mult=1, basis="sto-3g", active_electrons=2, active_orbitals=5
Any values that coincide with the default ones don't need to be passed explicitly. So you can omit charge, multiplicity, and basis.

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# We now compute the molecular Hamiltonian and the electronic excitations.
```suggestion
# We now compute the molecular Hamiltonian in the STO-3G basis, and the electronic excitations.
```

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# Note that we have a total number of 24 excitation gates. We now implement a strategy which
Maybe good to compute it directly, e.g.
`print(f"Total number of excitations = {len(singles) + len(doubles)}")`

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +    qml.BasisState(np.array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0]), wires=wires)
Consider using the `hf_state` function instead

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# gates to a reference Hartree-Fock state.
Need to better explain the connection between gates and excitations.

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +params = [0.0] * len(doubles)
Explain briefly why we initialize all to zero

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +dcircuit = qml.grad(cost_fn, argnum=0)
is this supposed to mean the derivative of the circuit? I find it a bit confusing, but not sure what else to name it. Consider revising it

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +geometry = np.array([0.000000000, 0.000000000, 0.000000000, 0.000000000, 0.000000000, 2.969280527])
```suggestion
geometry = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 2.969280527])
```

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +print(grads)
This expands horizontally with a scroll bar, which makes it difficult to grasp by the reader.

Maybe just print each gradient individually, potentially with the corresponding excitation

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# in the final state prepared by the circuit. We select those gates that have a gradient above a
Mention explicitly that many of these gradients are zero

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# pre-defined threshold which we set to 0.001.
```suggestion
# pre-defined threshold, which we set to 0.001.
```

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +doubles_select = [doubles[i] for i in range(len(doubles)) if abs(grads[i]) > 1.0e-5]
```suggestion
doubles_select = [doubles[i] for i in range(len(doubles)) if abs(grads[i]) > 1.0e-3]
```
In the text you said threshold is 0.001

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# parameters for the selected gates. We also need to define an optimizer. Note that the VQE
```suggestion
# We add the selected gates to the circuit and perform one optimization step to determine the updated
# parameters for the selected gates. We also need to define an optimizer. Note that the
```

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +doubles_select
Comment on how many are left compared to the total

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# optimization is not very costly as we only have two gate in our circuit.
I counted six gates from `doubles_select`?

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# the single excitation gates and select those that have a non-negligible gradient. To do that, we
```suggestion
# the single excitation gates, selecting those that have a non-negligible gradient. To do that, we
```

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +doubles_select
In fact, it would be good to have simple diagrams that show how we are building the circuit. So here we can have one consisting only of the selected gates

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +    print(energy)
I don't find it so useful to print the energy at this stage. Also, reading back, it's a bit confusing what we're doing: is the goal to fully optimize the double excitation gates before adding the single excitation ones?

Maybe this section could benefit from an enumerated description of the method, e.g.,

1. Generate all excitations
2. Compute gradients for all double excitations
3. etc

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +cost_fn = qml.ExpvalCost(circuit_2, H, dev, optimize=True)
Maybe remove vertical spaces here for more compact code

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +print(grads)
Again, print each one individually, maybe with corresponding excitation

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +singles_select = [singles[i] for i in range(len(singles)) if abs(grads[i]) > 1.0e-5]
```suggestion
singles_select = [singles[i] for i in range(len(singles)) if abs(grads[i]) > 1.0e-3]
```

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# Now, we have all of the gates we need to build our circuit and perform one final step of VQE
```suggestion
# We have all of the gates we need to build our circuit and perform one final step of

```

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +
Note, good to include circuit with the selected gates

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# only 10 gates in our circuit which is less than half of the total numbers of single and double
```suggestion
# only 10 gates in our circuit. This is less than half of the total number of single and double

```

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# Sparse method
This should be the title of a new section

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# in the computational basis using the sparse_hamiltonian function of PennyLane. This function
```suggestion
# we built for LiH. We can compute its matrix representation
# in the computational basis using the sparse_hamiltonian function of PennyLane. This function
```
And add link to the function

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# We can already see that the matrix has 1048576 entries which only 11264 of them
```suggestion
# The matrix has 1024^2=1048576 entries, but only 11264 of them
```

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# are non-zero. Leveraging this sparsity in the VQE simulations can significantly reduce the
```suggestion
# are non-zero. Leveraging this sparsity in the simulations can significantly reduce the
```

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# value of the sparse Hamiltonian observable. This can reduce the cost of the VQE simulations by
```suggestion
# value of the sparse Hamiltonian observable. This can reduce the cost of simulations by
```

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# steps and perform the final VQE step with the sparse method.
```suggestion
# steps and perform the final optimization step with the sparse method.
```

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# In conclusion, we have leaned that building quantum chemistry circuits adaptively and using the
Add a title header here for the conclusion

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# much shorter. The performance of the optimization will be more significant for larger molecules.
How will readers of the demo know that the simulation time is shorter?

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# the second method yourself and compare the results with the one we obtained above.
```suggestion
# can be extended such that the gates are selected one at time [#grimsley2019]_, or 
even to other more elaborate strategies.
```

2021-07-09 19:56 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +
Let's add an image here showing different circuits for different molecules

2021-07-12 03:16 UTC, josh146 commented on demonstrations/tutorial_adaptive_circuits.py
> +    :property="og:image": https://pennylane.ai/qml/_images/adaptive_circuits.png
```suggestion
    :property="og:description": Learn how to build quantum chemistry circuits adaptively
    :property="og:image": https://pennylane.ai/qml/_images/adaptive_circuits.png
```

2021-07-12 03:17 UTC, josh146 commented on demonstrations/tutorial_adaptive_circuits.py
> +# The matrix has 1024^2=1048576 entries, but only 11264 of them
```suggestion
# The matrix has :math:`1024^2=1048576` entries, but only 11264 of them
```

2021-07-13 19:42 UTC, soranjh commented on demonstrations/tutorial_adaptive_circuits.py
> +# optimization is not very costly as we only have two gate in our circuit.
Yes. The total number of double excitation gates is 16 and we select 6.

2021-07-15 15:14 UTC, soranjh commented on demonstrations/tutorial_adaptive_circuits.py
> +# gates to a reference Hartree-Fock state.
The previous paragraph and this one are modified to better explain the connection. The Givens rotation tutorial is also cited.

2021-07-15 15:17 UTC, soranjh commented on demonstrations/tutorial_adaptive_circuits.py
> +dcircuit = qml.grad(cost_fn, argnum=0)
Changed to `circuit_gradient`.

2021-07-15 15:17 UTC, soranjh commented on demonstrations/tutorial_adaptive_circuits.py
> +doubles_select
> Comment on how many are left compared to the total
Done.

2021-07-15 15:27 UTC, soranjh commented on demonstrations/tutorial_adaptive_circuits.py
> +    print(energy)
> I don't find it so useful to print the energy at this stage. Also, reading back, it's a bit confusing what we're doing: is the goal to fully optimize the double excitation gates before adding the single excitation ones?

Yes.

2021-07-15 15:32 UTC, soranjh commented on demonstrations/tutorial_adaptive_circuits.py
> +    print(energy)
The steps are summarised before defining the first circuit.

2021-07-21 22:36 UTC, ixfoduap requested changes
In much better shape, still some room fro improvement! At this stage it is ready to ask for other reviewers (Just Olivia should be enough)

2021-07-21 22:36 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +Quantum circuits for quantum chemistry are typically build using a pre-generated wavefunction ansatz
```suggestion
Quantum circuits for quantum chemistry are often built using a pre-generated circuit ansatz
```

2021-07-21 22:36 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +such as UCCSD [#romero2017]_. In this approach, one includes all possible single and double
```suggestion
such as UCCSD [#romero2017]_. In this approach, we include all possible single and double
```

2021-07-21 22:36 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +spin-orbitals [#givenstutorial]_. This makes construction of the ansatz
```suggestion
spin-orbitals [#givenstutorial]_. This makes the construction of the ansatz
```

2021-07-21 22:36 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +There are different ways to select the gates based on the computed gradients. Here we discuss one of
```suggestion
There are different ways to select the gates based on their gradients. Here we discuss one of
```

2021-07-21 22:36 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +these strategies to compute the ground state energy of LiH. This method require constructing the
```suggestion
these strategies to compute the ground state energy of LiH. This method requires constructing the
```

2021-07-21 22:36 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +Hamiltonian and determining all possible excitations, which we can do with PennyLane functionalities
```suggestion
Hamiltonian and determining all possible excitations, which we can do with the PennyLane functionalities
```

2021-07-21 22:36 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +including atomic symbols and coordinates. Note that the atomic coordinates are in Bohr.
Add link to Bohr https://en.wikipedia.org/wiki/Bohr_radius

2021-07-21 22:36 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# we restrict ourself to single and double excitations but higher-level excitations, such as
```suggestion
# we restrict ourselves to single and double excitations, but higher-level ones such as
```

2021-07-21 22:36 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# triple and quadruple, can be considered as well. Each of these electronic excitations is
```suggestion
# triple and quadruple excitations, can be considered as well. Each of these electronic excitations is
```

2021-07-21 22:36 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# methods in classical quantum chemistry.
```suggestion
# state and all of the excited states.
```

2021-07-21 22:36 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# the circuit by adding groups of gate at a time. We follow theses steps:
```suggestion
# excitation gates [#givenstutorial]_. We now implement a strategy that constructs
# the circuit by adding groups of gates one at a time. We follow these steps:
```

2021-07-21 22:36 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# We construct our first group of gates by including all of the double excitations and compute the
```suggestion
# We now construct our first group of gates by including all the double excitations and compute the
```

2021-07-21 22:36 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# function. We also initialize the parameter values to zero such that the gradients are computed
```suggestion
# function. We initialize the parameter values to zero such that the gradients are computed
```

2021-07-21 22:36 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +
```suggestion
```

2021-07-21 22:36 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# The computed gradients have different values which reflect the contribution of each gate
```suggestion
# The computed gradients have different values, reflecting the contribution of each gate
```

2021-07-21 22:36 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# those gates that have a gradient above a pre-defined threshold, which we set to 0.00001.
```suggestion
# those gates that have a gradient above a pre-defined threshold, which we set to :math:`10^{-5}`.
```

2021-07-21 22:36 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# optimization is not very costly as we only have two gate in our circuit.
But you're saying there are only two gates in the circuit. There actually 6 gates, right?

2021-07-21 22:36 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# Similar to the double excitation gates, we select those single excitations that have a gradient
```suggestion
# Similarly to the double excitation gates, we select those single excitations that have a gradient
```

2021-07-21 22:36 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# We have all of the gates we need to build our circuit and perform one final step of
```suggestion
# We now have all of the gates we need to build our circuit and perform one final step of
```

2021-07-21 22:36 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# optimization to get the ground state energy. The resulting energy must be the exact energy of the
```suggestion
# optimization to get the ground-state energy. The resulting energy must be the exact energy of the
```

2021-07-21 22:36 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# Sparse method
```suggestion
# Sparse Hamiltonians
```

2021-07-21 22:36 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +H_sparse
Should this have a print? :thinking:

2021-07-21 22:36 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# The matrix has :math:`1024^2=1048576` entries, but only 11264 of them
```suggestion
# The matrix has :math:`1024^2=1,048,576` entries, but only 11264 of them
```

2021-07-21 22:36 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# In conclusion, we have leaned that building quantum chemistry circuits adaptively and using the
```suggestion
# We have learnt that building quantum chemistry circuits adaptively and using the
```

2021-07-21 22:36 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# functionality for sparse objects makes molecular simulations significantly efficient. In this
```suggestion
# functionality for sparse objects makes molecular simulations significantly more efficient. In this
```

2021-07-21 22:57 UTC, soranjh commented on demonstrations/tutorial_adaptive_circuits.py
> +H_sparse
No, print(H_sparse) will print all the non-zero values and their coordinates.

2021-07-22 05:35 UTC, josh146 commented on demonstrations/tutorial_adaptive_circuits.py
> +# returns the matrix in the scipy 'sparse coordinate <https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.html>'_ format.
```suggestion
# returns the matrix in the SciPy `sparse coordinate <https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.html>`_ format.
```

2021-07-23 15:09 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +Quantum chemistry circuits
I think the contents of this section can be incorporated in the introduction. It would make the intro slightly longer, but allow you to then jump right into the main stuff.

2021-07-23 15:53 UTC, glassnotes requested changes
@soranjh this is a really cool tutorial, it's very concise and explains clearly how the algorithm wokrs! :rocket: :test_tube: 

My only substantial suggestion is to add some images (like the circuits before/after the adaptive gate selection). Everything else is just minor points for phrasing and code.

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +H, qubits = qchem.molecular_hamiltonian(symbols, geometry, active_electrons=2, active_orbitals=5)
This line is just slightly too long and causes a horizontal scroll bar; either split into 3 lines or shorten a variable name.

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +'Bohr <https://en.wikipedia.org/wiki/Bohr_radius>'_.
```suggestion
`Bohr <https://en.wikipedia.org/wiki/Bohr_radius>`_.
```

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +# We now compute the molecular Hamiltonian in the STO-3G basis and the electronic excitations. Here
May be helpful to add link to reference for STO-3G

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +    hf_state = qchem.hf_state(2, qubits)
Use the variable `active_electrons` (?) for clarity here instead of `2`.

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +# optimization is not very costly as we only have six gate in our circuit.
```suggestion
# optimization is not very costly as we only have six gates in our circuit.
```
In this section, check also `6` vs. `six` for consistency.

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +    hf_state = qchem.hf_state(2, qubits)
Also does the HF state need to be constructed inside the quantum function here? If not it can be moved out so it's not remade at every optimization step.

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +    hf_state = qchem.hf_state(2, qubits)
Same comment as above re. moving this out of the circuit.

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +    params, energy = opt.step_and_cost(cost_fn, params, excitations=doubles_select + singles_select)
Line is slightly too long here.

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +
```suggestion
```
This extra line is causing a rendering issue where the text below appears as a code comment. Deleting should fix it

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +    tutorial_vqe A brief ofverview of VQE
```suggestion
    tutorial_vqe A brief overview of VQE

```

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +appropriate circuit can be generated by using a pre-selected wavefunction ansatz, for example the
```suggestion
appropriate circuit can be generated by using a pre-selected wavefunction ansatz, for example, the
```

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +Quantum circuits can also be designed using specialized approachs that build a customized ansatz for
```suggestion
Quantum circuits can also be designed using specialized approaches that build a customized ansatz for

```

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +the given molecule. This approach helps improve performance at the cost of reducing generality.
```suggestion
the given molecule. This helps improve performance at the cost of reducing generality.

```

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +the desired state and neglecting those that have a small contribution. You will also learn how to use
```suggestion
This includes a recipe to adaptively select gates that have a significant contribution to
the desired state, while neglecting those that have a small contribution. You will also learn how to use
```

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +results. This motivates implementing a strategy that allows approximating the contribution of the
```suggestion
results. This motivates implementing a strategy that allows for approximation of the contribution of the
```

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +excitations and selecting only those excitations that are found to be important for the given
```suggestion
excitations and selects only those excitations that are found to be important for the given
```

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +possible excitation gates and select gates based on the magnitude of the computed gradients.
```suggestion
possible excitation gates, and then select gates based on the magnitude of the computed gradients. 

```

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +these strategies to compute the ground state energy of LiH. This method requires constructing the
```suggestion
There are different ways to make use of the gradient information, and here we discuss one of
these strategies and apply it to compute the ground state energy of LiH. This method requires constructing the
```

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +shown below. But we first need to import the required libraries and define the molecular parameters
```suggestion
Hamiltonian and determining all possible excitations, which we can do with functionality built-in to PennyLane.
But we first need to define the molecular parameters
```

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +# we restrict ourselves to single and double excitations, but higher-level ones such as
```suggestion
# we restrict ourselves to single and double excitations, but higher-level ones, such as
```

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +singles, doubles = qchem.excitations(2, qubits)
Define a variable instead of using the number `2` here

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +# Note that we have a total number of 24 excitations which can be represented by the same number of
```suggestion
# Note that we have a total of 24 excitations which can be represented by the same number of

```

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +# 4. Repeats steps 1 and 2 for the single excitations.
```suggestion
# 4. Repeat steps 1 and 2 for the single excitations.
```

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +# 5. Perform the final VQE optimization with all the selected excitations.
Nice, very clear outline of the algorithm! :tada:

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +# gradients for each of the double excitation gates. We also need to define a device and a cost
```suggestion
# We now construct our first group of gates by including all the double excitations, and compute the
# gradient for each one. We also need to define a device and a cost
```

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +# There are only 6 gates, among the total number of 16, that have gradients above the threshold.
```suggestion
# There are only 6 double excitation gates, out of the original 16, that have gradients above the threshold.
```
(Clarify the type of gate since there are  24 total)

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +    qml.BasisState(np.array(hf_state, requires_grad=False), wires=wires)
```suggestion
    qml.BasisState(np.array(hf_state, requires_grad=False), wires=wires)

```

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +    qml.BasisState(np.array(hf_state), wires=wires)
```suggestion
    qml.BasisState(np.array(hf_state), wires=wires)

```

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +    qml.BasisState(np.array(hf_state), wires=wires)
(Is `np.array` needed?)

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +for i in range(len(singles)):
```suggestion
params = [0.0] * len(singles)

grads = circuit_gradient(
    params, excitations=singles, gates_select=doubles_select, params_select=params_doubles
)

for i in range(len(singles)):
```

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +# Similarly to the double excitation gates, we select those single excitations that have a gradient
```suggestion
# Similar to the double excitation gates, we select those single excitations that have a gradient

```

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +# optimization to get the ground-state energy. The resulting energy must be the exact energy of the
```suggestion
# optimization to get the ground state energy. The resulting energy should match the exact energy of the

```

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +# only 10 gates in our circuit. This is less than half of the total number of single and double
Amazing! :tada:

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +# Sparse Hamiltonians
What do you think of having a separate demo (or maybe a blog post?) that showcases the sparse Hamiltonian functionality? I worry it could get lost if it's just at the end of this demo.

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +# function :func:`~.pennylane.utils.sparse_hamiltonian` of PennyLane. This function
```suggestion
# PennyLane function :func:`~.pennylane.utils.sparse_hamiltonian`. This function

```

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +# are non-zero. Leveraging this sparsity in the simulations can significantly reduce the
```suggestion
# are non-zero. Leveraging this sparsity can significantly reduce the

```

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +dev = qml.device("default.qubit", wires=qubits)
```suggestion
```
Not necessary to redefine if number of qubits hasn't changed.

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +@qml.qnode(dev, diff_method="parameter-shift")
Might be worth mentioning in the text that this only currently works for `parameter-shift`, right?

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +    qml.BasisState(np.array(hf_state, requires_grad=False), wires=range(qubits))
```suggestion
    qml.BasisState(np.array(hf_state, requires_grad=False), wires=range(qubits))
```
Not sure this needs the `np.array` here either.

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +# Using the sparse method reproduces the exact ground state energy while the optimization time is
Would be nice to include a speedup factor here, e.g., ratio of average iteration times.

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +# We have learnt that building quantum chemistry circuits adaptively and using the
```suggestion
# We have learned that building quantum chemistry circuits adaptively and using the

```

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +# tutorial, we followed an adaptive strategy that selects a group of gates at each time. This method
```suggestion
# tutorial, we followed an adaptive strategy that selects a group of gates 
# based on information about the gradients. This method
```

2021-07-23 15:53 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +# even to other more elaborate strategies.
Add reference to more elaborate strategies?

2021-07-27 02:20 UTC, soranjh commented on demonstrations/tutorial_adaptive_circuits.py
> +# Sparse Hamiltonians
We thought about it but decided to not have a separate demo. We will use other ways, e.g., discussing it in a white paper on qchem with PL, to advertise the sparse method.

2021-07-28 20:12 UTC, soranjh commented on demonstrations/tutorial_adaptive_circuits.py
> +Quantum chemistry circuits
Done.

2021-07-29 14:48 UTC, glassnotes requested changes
@soranjh demo contents look great!

The only issues right now are rendering, because of rogue new lines. I think I caught them all, but we'll have to double check the page looks okay before merging.

2021-07-29 14:48 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +
```suggestion
```
The extra line here caused a rendering issue and the references did not display properly.

2021-07-29 14:48 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +ground state wavefunction. Including all possible excitations usually increases the cost of the
```suggestion

In practical applications, including all possible excitations usually increases the cost of the
```

2021-07-29 14:48 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +But we first need to define the molecular parameters including atomic symbols and coordinates.
```suggestion
But we first need to define the molecular parameters, including atomic symbols and coordinates.
```

2021-07-29 14:48 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +    active_orbitals=5)
```suggestion
    active_orbitals=5
)

```

2021-07-29 14:48 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +
```suggestion
```

2021-07-29 14:48 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +
```suggestion
```

2021-07-29 14:48 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
```suggestion
```
Rendering issue here as well

2021-07-29 14:48 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +
```suggestion
```

2021-07-29 14:48 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +
```suggestion
```

2021-07-29 14:48 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +
```suggestion
```

2021-07-29 14:48 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +# only works with the parameter-shift differentiation method currently.
```suggestion
# currently only works with the parameter-shift differentiation method.
```

2021-07-29 14:49 UTC, ixfoduap approved these changes
Looks great! Just left a few minor suggestions.

I'll find some time to create figures for this

2021-07-29 14:49 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +
Maybe add also the Givens rotations tutorial

2021-07-29 14:49 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +Hamiltonian and determining all possible excitations, which we can do with functionality built-in to PennyLane.
```suggestion
Hamiltonian and determining all possible excitations, which we can do with functionality built into PennyLane.
```

2021-07-29 14:49 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# optimization to get the ground state energy. The resulting energy should match the exact energy of the
```suggestion
# optimization to get the ground-state energy. The resulting energy should match the exact energy of the

```

2021-07-29 14:49 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +
```suggestion
```

2021-07-29 14:49 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# only works with the parameter-shift differentiation method currently.
```suggestion
# currently only works with the parameter-shift differentiation method.
```

2021-07-29 14:49 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +
```suggestion
```

2021-07-30 13:03 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +# ground electronic state of LiH which is -7.8825378193 Ha.
```suggestion
# We now have all of the gates we need to build our circuit and perform one final step of
# optimization to get the ground-state energy. The resulting energy should match the exact energy of the
# ground electronic state of LiH which is -7.8825378193 Ha.
```
This section is still not rendering; trying a multi-line suggestion instead.

2021-07-30 13:06 UTC, glassnotes reviewed
Contents look great, happy to approve once it's determined whether additional figures will be included. (Also, need to double check the rendered version before merging.)

2021-08-19 16:42 UTC, glassnotes approved these changes
@soranjh new figures look awesome :100:

2021-08-19 16:42 UTC, glassnotes commented on demonstrations/tutorial_adaptive_circuits.py
> +# .. figure:: /demonstrations/adaptive_circuits/adapted_circuit.png
Oooh, I love this graphic!

2021-08-19 19:16 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +    Examples of selecting specific single and double excitation gates to generate adaptive circuits.
```suggestion
    Examples of selecting specific gates to generate adaptive circuits.
```

2021-08-19 19:16 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +#   :width: 100%
maybe good to make a bit smaller, e.g., 90% of the size

2021-08-19 19:16 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +#   :align: center
Maybe a short caption for this figure?

2021-09-13 20:59 UTC, merged