[WIP] demo classical kernels
PennyLaneAI/qml pull request #321
Opened 2021-08-17 15:38 UTC by emgilfuster

This demo introduces a re-uploading in depth quantum embedding kernel and demonstrates how it can approximate any stationary classical kernel up to arbitrary precision.

2021-08-23 16:28 UTC, emgilfuster commented
Hi @mariaschuld, would you like to have a look? :)

2021-08-24 05:40 UTC, mariaschuld commented on demonstrations/tutorial_expressivity_fourier_series.py
> +        exponent = np.complex128(scaling * (idx+1) * x * 1j)
why is this needed I wonder?

2021-08-24 05:42 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +    :property="og:description": Show how to approximate the Gaussian kernel.
```suggestion
    :property="og:description": Approximating the Gaussian kernel with quantum circuits.
```
Just a suggestion...

2021-08-24 05:42 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +We will also use this QEK to demonstrate we can approximate a large class of
```suggestion
We will use this QEK to demonstrate we can approximate a large class of
```

It's  kind of the main thing...

2021-08-24 05:43 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +We will also use this QEK to demonstrate we can approximate a large class of
Maybe "important" class? Size is relative in function spaces...

2021-08-24 05:44 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +will not be reviewing all the notins of kernels in-depth here.
```suggestion
will not be reviewing all the notions of kernels in-depth here.
```

2021-08-24 05:44 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +Now, a kernel for us is a real-valued function of two variables
```suggestion
Now, for the purpose of this demo, a kernel is a real-valued function of two variables
```

2021-08-24 05:45 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +all kernels featuring in this demo are positive semi-definite.
I like this, it gives the reader the feeling she is looked after somehow :)

2021-08-24 05:45 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +``prominent", chances are you'll find it next to the word ``example" in a
```suggestion
"prominent", chances are you'll find it next to the word "example" in a
```
This is not latex ;)

2021-08-24 05:46 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +:math:`k_\sigma`.
This required me to think for a while, but I had to laugh - you are so right!

2021-08-24 05:47 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +sentence that introduces the so-called Gaussian (Radial Basis Function) kernel
```suggestion
sentence that introduces the so-called Gaussian (or Radial Basis Function) kernel
```

2021-08-24 05:48 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +Euclidean norm :math:`\lVert x_1 - x_2 \rVert_2^2`.)
```suggestion
where the variance :math:`\sigma` is a positive real tunable parameter. The
generalization to higher-dimensional data is straightforward using the
Euclidean norm :math:`\lVert x_1 - x_2 \rVert_2^2`.
```

2021-08-24 05:49 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +real-life tasks.
```suggestion
simple enough to study as a function, while yielding good performance for a wide range of
real-life tasks.
```
Actually, it is quite puzzling how good this simple kernel is - we don't only use it for ease of analysis! Also, a Gaussian kernel can be shown to be universal, which means that the RKHS of that kernel contains _all_ functions.

2021-08-24 05:51 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +shift-invariant function (also called stationary).
```suggestion
shift-invariant (also called *stationary*) function .
```

(I think this is the italics in rst, but always mix them up)

2021-08-24 05:52 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +Also, this combined with the property :math:`k(x_1, x_2) = k(x_2, x_1)` results
```suggestion
Combined with the property :math:`k(x_1, x_2) = k(x_2, x_1)`, this results
```

2021-08-24 05:52 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +As it turns out, there are many others (REFERENCES OR POINTERS OR SOMETHING!)
You could link to the Rasmussen textbook, I think it is free for download!

2021-08-24 05:54 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +#. Smoothness (seen as quickly decaying Fourier spectrum).
```suggestion
.. math:: k_1(\delta) = e^{-\delta^2}.

All the arguments and code we use are also amenable to other kernels which
fulfill the following mild restrictions:

* Shift-invariance.
* Normalization :math:`k(0)=1`.
* Smoothness (seen as quickly decaying Fourier spectrum).
```

The hashtags don't seem to work?

2021-08-24 05:55 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +Let's warm up our coding by writing the simple Gaussian kernel!
```suggestion
Let's warm up by implementing a classical Gaussian kernel!
```

2021-08-24 05:55 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +First, importers gonna import B-)
```suggestion
First, importers gonna import B-).
```

I am not sure I get this one, but that should not be a criterion :)

2021-08-24 05:56 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +
```suggestion
import math 
```

2021-08-24 05:56 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# now we define the function and plot it as a mild sanity check:
```suggestion
# Now we define the kernel function and plot it as a mild sanity check:
```

2021-08-24 05:57 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +plt.show();
I think we need a x axis label here - people plot kernels usually by fixing one argument and varying the other, but since things are stationary, this is the same as varying the delta. So good to be explicit

2021-08-24 05:59 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +Of course the Gaussian kenrel is not the only shift-invariant kernel out there.
```suggestion
Of course the Gaussian kernel is not the only shift-invariant kernel out there.
```

2021-08-24 06:00 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# So far so good!
About the above section: Even if it's short a few subtitles may work well. It's like a magazine vs a long newspaper article - people keep reading. For example "The Gaussian kernel", "Shift-invariance", and ... hm.. maybe "Visualisation"? Ok, the last one is not too great

2021-08-24 06:01 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# Embedding Kernels (QEKs), introduced in the paper [#QEK]_ corresponding to
I know someone who may jump on your roof when you make this public :) It sounds like quantum kernels were invented in the paper. To be safe, one could be more specific and say that the name was introduced there, after others proposed the idea of quantum kernels?

2021-08-24 06:02 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# qu:math`d`it:
Not rendering

2021-08-24 06:03 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# one shortcoming: in general :math:`k_Q` won't be a shift-invariant function
```suggestion
# one shortcoming: In general, :math:`k_Q` won't be a shift-invariant function
```

2021-08-24 06:04 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# (but is this really a shortcoming?)
```suggestion
# (but is this really a shortcoming?).
```

I think this is too contrived, I would just state that they have a shortcoming when our goal is to emulate the Gaussian kernel on a quantum computer (and it may be a good opportunity to repeat what we're trying to do here).

2021-08-24 06:04 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# which restrictions do we have to impose for these kernels to be
```suggestion
# Which restrictions do we have to impose for these kernels to be
```

2021-08-24 06:07 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# Behold, ladies and gents, *the Boring kernel*!
Lol, you really gonna put this name out into the wild?

I fear this won't make external review :) The reason is not that one cannot use humorous names, but that it is not a very useful description of what we are doing. Is there any alternative? 

In my mind, what this is is a toy model! (And if it turns out to be a good one, it may keep thousands of physicists of future generations restless...)

2021-08-24 06:07 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# The boring kerne is a stationary kernel that can be estimated with a
```suggestion
# The boring kernel is a stationary kernel that can be estimated with a
```

2021-08-24 06:08 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# :math:`d` dimensions (also called a qu-:math:`d`-it), we have the associated
Some readers may be worrying "but my Master thesis is about qubits not qudits, how can I use this?" I think we need a sentence that explains how this can be thought of as multiple qubits, or just go the qubit route from the start!

2021-08-24 06:09 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# d-1)`.
We definitely need a circuit drawing here, this is confusing even me :)

2021-08-24 06:12 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# .. math:: k_d(\delta) = \sum_{s=-(d-1)}^{d-1} a_s e^{i\delta s},
Hmm, I agree that we cannot roll out the theory here, but this innocent line is only obvious to a handful of people in the universe. Maybe we can at least mention the flavour, i.e., "we know that many quantum kernels, ours included, can be expressed as Fourier series of only a few terms". You can also cite my kernels paper, I think this is the first (and only?) reference that has an explicit Fourier expression of general quantum kernels...

2021-08-24 06:13 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# that relized the quantum circuit, right?
```suggestion
# that realized the quantum circuit, right?
```

2021-08-24 06:16 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# number-operator hamiltonian :math:`H_d=\operatorname{diag}(0, 1, \ldots,
I don't think many people know what this is, so maybe say "to make things simple, we need a Hamiltonian with consecutive integers on its diagonal; this is known in continuous-variable quantum computing as a number operator". And then move the explanation of how to do it in qubits to here? 

The goal is that people know why we do this, and that we can do this easily with the tools they know.

2021-08-24 06:16 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# prof would say, the derivation is left as an exercise for the reader), but
```suggestion
# Prof would say, the derivation is left as an exercise for the reader), but
```

2021-08-24 06:18 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# With this, we can *finally* start getting our hands dirty!
A slow reader will have spent half an hour getting here. Maybe sprinkling the text with reminders of the goal (to approximate a Gaussian kernel with a quantum circuit) could help to keep the thread going?

2021-08-24 06:18 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# with the cirrect size.
```suggestion
# with the correct size.
```

2021-08-24 06:19 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# we need to feed to :math:`S(x)`
```suggestion
# we need to feed to :math:`S(x)`:
```

2021-08-24 06:19 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# That is to say, on the ``default.qubit`` PL quantum simulator ;)
```suggestion
# That is to say, on the ``default.qubit`` PL quantum simulator ;).
```

2021-08-24 06:19 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# This is also the point where we need the vector of ``thetas``
```suggestion
# This is also the point where we need the vector of ``thetas``:
```

2021-08-24 06:21 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# :math:`\vert00000\rangle` being measured:
A lot of students find this totally opaque. Maybe here (and before) you can point them towards places where they can read up on why this circuit evaluates a kernel, and what the alternatives are!

Actually, it would be so helpful to have a demo that just introduces the different circuits one can use to compute quantum kernels!

2021-08-24 06:21 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# Quality of life improvement: let's make this small function that evaluates
```suggestion
# Quality of life improvement: Let's make this small function that evaluates
```

2021-08-24 06:21 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# Quality of life improvement: let's make this small function that evaluates
Check the grammar, something is not right?

2021-08-24 06:23 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# .. figure:: ../demonstrations/classical_kernels/salesman.PNG
Ah, there you got the circuit picture you can use above!

2021-08-24 06:33 UTC, mariaschuld requested changes
A well-written and entertaining demo. When introducing humour into professional spaces one must be absolutely on point (else it is not taken serious), so we may need a few more revisions when other reviewers leave comments.

I have a few suggestions: 

1) Can we crystallise the main message even more throughout the demo, i.e., we want to approximate a Gaussian kernel using a quantum computer. [To give an example: when you plot the Gaussian kernel, just mention that this is what we want to do on a quantum computer.]
2) Sometimes you introduce small innocent bits that require years of study to understand, for example the idea of d-dits and number operators, or the idea of a Fourier representation of a quantum kernel. You don't need to go into depths, but acknowledge that this is something people need to swallow and give them references to look it up if needed.
3) I am in two minds about this one, but the real cool thing you do is totally swept under the rug (I guess to keep it simple): You construct a quantum kernel whose spectrum we can control [at least asymptotically], and use this to design kernels - in our example a classical kernel. This is an extremely powerful idea! What about the following: make this the main idea of the tutorial ("designing quantum kernels by shaping their Fourier spectrum") and sell the Gaussian kernel as a mere example! I fear though that one may have to move some sections around, but it is worth it I think! The demo could become a "build your own kernel on a quantum computer" sandbox.
4) The big weakness of the demo is the part when things are learnt - if we are trying to sell a simple toy model for playing, but then we need the huge apparatus of optimisation to get the final result, there is a certain anti-climax. I would at least explain this, namely that we can shape the right spectrum, but it is hard to guess which circuit leads to the right coeffs. 

PS: There is NO way we could analytically find the gates needed to form the coeffs, right? Even if we do something as rough as we did with the number operator, and construct the right W, and then use compilation to find the right gates?

2021-08-24 08:07 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +We will also use this QEK to demonstrate we can approximate a large class of
yes, important is definitely more accurate

2021-08-24 08:08 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +``prominent", chances are you'll find it next to the word ``example" in a
oopsie!

2021-08-24 08:09 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +:math:`k_\sigma`.
if it's too confusing we could also take it out!

2021-08-24 08:10 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +real-life tasks.
I like your suggestion, sounds much better!

2021-08-24 08:12 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +As it turns out, there are many others (REFERENCES OR POINTERS OR SOMETHING!)
sorry, this slipped past me, I was supposed to have the link here, not the reminder to add a link! That's a good idea though

2021-08-24 08:13 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +First, importers gonna import B-)
It's an adaption from "haters gonna hate", but it's probably one too many, I'll leave this comment open and rethink in next iteration whether we keep it or discard it

2021-08-24 08:14 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +
There is no suggested change, is that right?
Probably I could get away with only numpy, no need for math?

2021-08-24 08:14 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +plt.show();
yes, true!

2021-08-24 08:16 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# So far so good!
ok I'll try that out

2021-08-24 08:18 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# Embedding Kernels (QEKs), introduced in the paper [#QEK]_ corresponding to
yeah the wording is quite unfortunate, my bad! I only wanted to mention the paper as a more comprehensive explanation than the demo. But actually the demo is already quite comprehensive, so maybe we don't even need it. I'll try reshuffling things and see what works best!

2021-08-24 08:20 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# :math:`d` dimensions (also called a qu-:math:`d`-it), we have the associated
Since I argue everything in terms of qubits below, should I just add a disclaimer saying that noone should worry about qudits, because when it comes to implementation we do everything with qubits? 

Or rather add a sentence building a bridge between one qudit and several qubits and keep the other things as they are?

2021-08-24 08:22 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# d-1)`.
right!

2021-08-24 08:23 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# Behold, ladies and gents, *the Boring kernel*!
hehe will change

2021-08-24 08:23 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# number-operator hamiltonian :math:`H_d=\operatorname{diag}(0, 1, \ldots,
yes, very good call!

2021-08-24 08:24 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# .. math:: k_d(\delta) = \sum_{s=-(d-1)}^{d-1} a_s e^{i\delta s},
yip, I'll do that

2021-08-24 08:24 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# With this, we can *finally* start getting our hands dirty!
yes sire

2021-08-24 08:25 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# :math:`\vert00000\rangle` being measured:
agree, and agree!

2021-08-24 08:26 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# Quality of life improvement: let's make this small function that evaluates
I think it's a confusing use of "this", I was trying to go for the use in oral storytelling "there was this guy, who...". But it's probably too confusing here, will change!

2021-08-24 08:27 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# .. figure:: ../demonstrations/classical_kernels/salesman.PNG
right! it's also in the thumbnail so I already have it ready

2021-08-24 08:27 UTC, emgilfuster commented on demonstrations/tutorial_expressivity_fourier_series.py
> +        exponent = np.complex128(scaling * (idx+1) * x * 1j)
this is from the earlier PR, I'll get rid of it

2021-08-24 09:17 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +#. Smoothness (seen as quickly decaying Fourier spectrum).
the problem was that I didn't leave an empty line between the paragraph and the list

2021-08-24 10:27 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# Behold, ladies and gents, *the Boring kernel*!
I called it "the stationary toy QEK"

2021-11-23 17:48 UTC, emgilfuster commented
Hi @mariaschuld, the demo is ready for code review after the major rewriting.

I still don't have the option to assign reviewers myself, sorry I'm tagging you this way.

2021-12-06 08:01 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# ----------------------------------
I think it is important to explain here what you are actually doing. I.e. you could say that we could of course just take the function implementing the classical kernel and the function implementing the quantum kernel and find the amplitudes so that they match. But we want to go a different route here and derive an equation that links the amplitudes to the spectrum we want to construct, and then use old-fashioned convex optimisation to find the solution...

That reminds me, do you mention anywhere that this design of your circuit is cool because we could approximate any stationary kernel? Is that even true?

2021-12-06 08:01 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# These closed form equations allow us to find the solution numerically, using
```suggestion
# These closed-form equations allow us to find the solution numerically, using
```

2021-12-06 08:02 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# I *guess* I was lucky enough that the first one I tried already gave good
Ah here you are going first person again. I have no opinion on this style, I wonder if the others will comment on it though. Let's see?

2021-12-06 08:03 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# Good coding praxis tells us we should probably turn this step into a function
```suggestion
# Good coding practice tells us we should probably turn this step into a function
```

I am not sure though :)

2021-12-06 08:04 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +#       :target: javascript:void(0)
Again, I am not sure the reader understands how general this ansatz is!

2021-12-17 14:27 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +insight into their inner workings.
:)

2021-12-17 14:28 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +In particular, how can we exploit the Fourier representation of quantum
yes, that sounds very good!

2021-12-17 14:34 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +sense.
yes, I like it!

2021-12-17 14:45 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +will not be reviewing all the notions of kernels in-depth here.
missing a "We"

2021-12-17 14:45 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +Start importing the usual suspects:
yep, better!

2021-12-17 14:46 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# mild restrictions:
^^

2021-12-17 15:03 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# are well captured.
I added more explanation to this. I'm not sure whether it's a critical point, so maybe it would be better to remove the entire thing altogether? I think an external look would be very helpful here

2021-12-17 15:06 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# :math:`3` qubits, which would correspond to :math:`2^3=8` frequencies.
I added a couple lines here, let me know what you think

2021-12-17 15:18 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +#     Schematic of the steps covered in this demo
yeah, I guess it wasn't the right place for the distinction since I haven't talked enough about the distinction yet. Do you think I should have another visual schematic later on that stretches the two very different parts?

2021-12-17 15:21 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# Contrary to the usual Ans\"atze used in supervised and unsupervised learning,
hm, maybe now it's better

2021-12-17 15:24 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# I don't really know what I was expecting to come out of there, but that's
agree! Also later, too hard change of style

2021-12-17 15:32 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# ----------------------------------
I said towards the very beginning that it would work for all kernels that fulfill the three conditions.
It might be too far above for anyone to remember, so should I drop a reminder somewhere around here?

2021-12-17 15:34 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# ----------------------------------
I added a paragraph along the lines of what you proposed

2021-12-17 15:35 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# ``probabilities`` :math:`(w_0, w_1, w_2, \ldots, w_{2^n-1})`, and we define as
good question, maybe I should!

2021-12-17 15:40 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# I *guess* I was lucky enough that the first one I tried already gave good
I tuned it down, that was again too much

2021-12-17 15:41 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +#       :target: javascript:void(0)
Do you identify an optimal spot to repeat the message at the start of the demo? :)

2021-12-18 15:16 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# Indeed, we start from a classical kernel, obtain its spectrum, and then
I tried to rewrite it, does it sound less confusing now? I'm not yet 100% sure I'm happy with it, I might change it a bit when I do a final end-to-end read.

2021-12-18 15:21 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +wires = dev.wires.tolist()
yep agree!

2021-12-18 15:51 UTC, emgilfuster commented
Hi @mariaschuld, I implemented the proposed, see unresolved conversations for the places where I wasn't sure.
I replaced all "QEK" mentions for "QK", also in the code

2022-01-10 06:02 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +classical one could be posed as a supervised learning regression problem.
```suggestion
classical one could be posed as an optimisation problem.
```

Would you mind this change? Learning is one option to match kernels via optimisation, but this is more general...

2022-01-10 06:04 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +of the kernels, though.
```suggestion
This sort of approach does not help us much to gain theoretical insights about the 
structure of kernel-reproducing quantum circuits, though.
```

As a reader I wondered: Why on earth should I care about Fourier? :) 
Maybe this is a bit more general - we want to be more theoretical, and in the next sentence you 
say which approach is chosen...

2022-01-10 06:06 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +classical ML.
```suggestion
In order to build intuition, we will instead study the link between classical and quantum kernels through the
lens of the Fourier representation of a kernel, which is a common tool in
classical ML.
```

Does that link it well?

2022-01-10 06:08 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +Kernels) and their Fourier representation.
```suggestion
who'd like to see the underlying theory of QKs (and also so-called _Quantum Embedding
Kernels_) and their Fourier representation.
```

2022-01-10 06:09 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +    :width: 80%
```suggestion
    :width: 70%
```
Or even smaller? I always like pictures to be scaled such that the text they contain is of the same size as the normal text... [Minor one]

2022-01-10 06:10 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +demo are positive semi-definite.
I really like how this section abstracts away some details and refers to other resources!

2022-01-10 06:11 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +
```suggestion
import pennylane as qml
from pennylane import numpy as np
import matplotlib.pyplot as plt
import math

```

2022-01-10 06:11 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +
```suggestion

```

2022-01-10 06:12 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +
```suggestion
```

A matter of taste :)

2022-01-10 06:12 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +plt.suptitle("The gaussian kernel with $\sigma=1/\sqrt{2}$")
```suggestion
plt.suptitle("The Gaussian kernel with $\sigma=1/\sqrt{2}$")
```

2022-01-10 06:13 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# The first next step will be to find the Fourier spectrum of the Gaussian
```suggestion
# The next step will be to find the Fourier spectrum of the Gaussian
```

2022-01-10 06:14 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# Once we've found it, we'll build a QK that produces a finite Fourier series
Just a thought: is there any reason to use an abbreviation? Doesn't it trade clarity with the advantage of saving a few characters? :) Even I had to think what QK meant here...

2022-01-10 06:15 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# Because the Gaussian kernel is an even function, we know the imaginary part
```suggestion
# Because the Gaussian kernel is an even function, we know that the imaginary part
```

2022-01-10 06:16 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +    # because `coefficients` treats the negative frequencies
```suggestion
    # because coefficients() treats the negative frequencies
```

2022-01-10 06:16 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +    # we only take the first d coefficients [:d]
```suggestion
    # We only take the first d coefficients [:d]
```

If it has a fullstop the first word is capitalised...

2022-01-10 06:17 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# would have to be :math:`0` in any case.
```suggestion
# Since we know the Gaussian kernel is a smooth function, we expect that the
# coefficients converge to :math:`0` at some point, and we will only need to 
# consider terms up to this point.
```

Minor one, but I think the argument was repeated here!

2022-01-10 06:20 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +#     Schematic of the steps covered in this demo
I think it's not necessary.

In fact, this image is so spot on  that I wonder if it should appear as an icon and as the first picture of the demo...it is much more specific than the one showing the circuit!

2022-01-10 06:20 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# In the second one we input the data, and call it :math:`S(x)`.
...and the image that is currently in the first section would be an excellent fit here, because you explain what the 16x, 8x... actually mean!

2022-01-10 06:21 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# We need a few more functions for that!
Very nicely explained this section!

2022-01-10 06:22 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +plt.show();
This section is very well explained. I think some people will get distracted by the detail of how one determines how many coefficients are needed. But the last plot should bring them back...

2022-01-10 06:23 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# decorator
```suggestion
# Next we construct the quantum node:
```

2022-01-10 06:23 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# That corresponds to the :math:`0^\text{th}` entry of ``qml.probs``:
Nicely explained!

2022-01-10 06:29 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# solution.
```suggestion
# If we knew exactly which amplitudes to choose in order to build a given Fourier spectrum,
# our job would be done here. However, the equations derived in the literature are not 
# trivial to solve.
#
# As mentioned in the introduction, one could just "learn" this relation: 
# take the function implementing the classical kernel and the
# function implementing the quantum kernel and then tune the parameters of the
# quantum kernel in a gradient-based manner until it matches the classical one.
#
# We want to take an intermediate route between analytical solution and black-box optimisation here.
# For that, we derive an equation that links the amplitudes to the spectrum we
# want to construct, and then use old-fashioned convex optimisation to find the
# solution.
```

2022-01-10 06:29 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# solution.
What about this one?

2022-01-10 06:32 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# solution.
Actually, why not making this its own subsection under the header "How to find the amplitudes emulating a Gaussian kernel" or so. And then a reader can jump the next few sections if necessary, which most of them will probably do at first.

2022-01-10 06:33 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +
```suggestion
```

2022-01-10 06:34 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# Here is a tame one that works for the gaussian kernel.
```suggestion
# Here is a tame one that works for the Gaussian kernel.
```

2022-01-10 06:34 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# Fix the hyperparameters for Newton's method
```suggestion
# We fix the hyperparameters for Newton's method:
```

2022-01-10 06:35 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# arguments, which is the componentwise square root of ``probabilities`` so it
```suggestion
# arguments, which is the component-wise square root of ``probabilities`` so it
```

2022-01-10 06:38 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +plt.show();
Hm I wonder if you could shorten this thresholding, because it is a small technical detail that can be quite distracting...took me a while to understand that you are just cleaning the results a bit to not run into numerical problems with the square root.

2022-01-10 06:39 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +plt.show();
Very cool Finale!

2022-01-10 06:43 UTC, mariaschuld requested changes
Hey @emgilfuster. Great job. From the outside it looks like the same number of comments, but they are a lot lighter, and all of them are just suggestions or layout practices that other demos adopted...so it is just that extra cherry on top.

The only two serious ones are also minor:
1. consider swapping the 4 circles graphic with the QEK one
2. shorten the "thresholding probablilites" part to hide it as much as you can

I hope it'll be very quick to implement these, and then we open for other reviewers - but I think it's in a very good shape to be accepted soon.

Thanks for working on it!

2022-01-10 11:26 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +classical one could be posed as a supervised learning regression problem.
yes makes sense

2022-01-10 12:58 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +of the kernels, though.
no, you're totally right! I think this was here from an earlier version where I had already mentioned our desire to explore the Fourier side of things. Off it goes!

2022-01-10 12:59 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +classical ML.
yes I think so!

2022-01-10 13:03 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# Once we've found it, we'll build a QK that produces a finite Fourier series
hm fair point. I usually like abbreviations where there are paragraphs that just repeat "quantum kernels" all the times. But glancing the document up and down I couldn't find any such instance. That being said, I think I'd leave it as is?

2022-01-10 13:03 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +    # we only take the first d coefficients [:d]
correcto! That one slipped past me

2022-01-10 13:04 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# would have to be :math:`0` in any case.
agree, I was splitting hairs when I wrote it down, and it doesn't make much sense

2022-01-10 13:05 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +plt.show();
I had my doubts here. Maybe it wasn't necessary to go into this level of detail but I didn't want people to think the cut-off came from under a stone or was arbitrary.

2022-01-10 13:06 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# In the second one we input the data, and call it :math:`S(x)`.
a-ha! that's a good one, thanks!

2022-01-10 13:06 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# We need a few more functions for that!
very kind, and thanks for the patience on your side!

2022-01-10 16:01 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# solution.
ok so I changed the title from "the necessary bit of math" into "How to find the amplitudes emulating a Gaussian kernel" and demoted it from being a section to being a subsection of the previous one "Computing the QK function on a quantum device"

2022-01-10 16:03 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +plt.show();
hm the code is necessary, otherwise we get nan in the vector of amplitudes in a lot of places. What I could do is cut the text? But then again I fear it would feel like it's coming from under a stone, and maybe a bit arbitrary. What do you think? For now I don't touch anything here.

2022-01-10 16:04 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +#     Schematic of the steps covered in this demo
I did the swap, do the captions now sound misplaced? I'd say no, but wanted to ask

2022-01-10 16:15 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
I changed the title from "the necessary bit of math" to this, and demoted it from being a standalone section to being a subsection of "Computing the QK function on a quantum device", is this more or less what you had in mind?

2022-01-11 08:40 UTC, emgilfuster commented
Hi @mariaschuld thank you very much for the on-point feedback!
I think I implemented everything except for the thresholding thing, which I don't really know how to do further. I considered turning it into a note or a warning, but it's really necessary for the core of the code, so I didn't do it in the end. In the text I dress it as "good coding practise", but the truth is that if I don't include the thresholding everything breaks, because some of the amplitudes that come from Newton's method are very small but negative, so taking the square root just kills us.

Do you think it can stay as it is? Should I add a disclaimer about skippability?

2022-01-11 10:46 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sounds good!

2022-01-11 10:51 UTC, mariaschuld commented on demonstrations/tutorial_classical_kernels.py
> +plt.show();
Ok convinced, no worries unless another reviewer brings it up :)

2022-01-11 10:52 UTC, mariaschuld approved these changes
Thanks for making the changes @emgilfuster ! I will tag external reviewers, let's see what they think of the stuff we cooked up...

2022-01-11 18:25 UTC, peterse reviewed
very cool. I made some minor comments and think it could use a bit of clarification in places but overall seems good to go.

2022-01-11 18:25 UTC, peterse commented on demonstrations/tutorial_classical_kernels.py
> +# :math:`p_j=a_j^2`.
nit: |a_j|^2

2022-01-11 18:25 UTC, peterse commented on demonstrations/tutorial_classical_kernels.py
> +# There is a crazy formula that matches the entries of *probabilities* with the
I'm curious about this formula. Where does it come from? Does this just fall out of the specific choices of W, S made for this kernel?

2022-01-11 18:25 UTC, peterse commented on demonstrations/tutorial_classical_kernels.py
> +# These closed-form equations allow us to find the solution numerically, using
for readers unfamiliar with convex optimization it might be helpful to mention why this function is guaranteed to be convex?

2022-01-11 18:25 UTC, peterse commented on demonstrations/tutorial_classical_kernels.py
> +plt.ylabel("probabilities $w_j$")
maybe be a bit more specific about which probabilities these are? are these our estimates for the things we were calling $p_j$ earlier?

2022-01-11 18:25 UTC, peterse commented on demonstrations/tutorial_classical_kernels.py
> +# There is a crazy formula that matches the entries of *probabilities* with the
this seems especially relevant considering the closing meme :p - this choice is general to _any_ translation invariant kernel then?

2022-01-12 10:45 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +    plt.plot(N, F, 'x', label='{}'.format(n))
I'm no expert myself on the fast fourier transform, which is what's being called under the hood here.
But when I read a bit, apparently one requirement is to have a good frequency cut-off, otherwise the coefficients have some artifacts, which is what we're seeing here.
I think the reason is that specifying the cut-off specifies a set of functions with which you want to approximate a target function.
If I want to approximate cos(4x) as a linear combination of {1, cos(x), cos(2x), cos(3x), cos(4x)}, then of course I'll find coefficients (0, 0, 0, 0, 1).
Yet, if I tried to approximate it as a linear combination of {1, cos(x), cos(2x)}, I'd probably be able to find some coefficients (a, b, c)!=(0, 0, 0) that achieve a lower approximation error.

Exact same thing happens here, the Gaussian kernel "needs" at least up to {cos(6x)}, so anywhere below that we get artifacts from poor choice of hyperparameters at the FFT level.

2022-01-12 10:58 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# state into a state with amplitudes :math:`a=(a_1,a_2,\ldots,a_{2^n-1})`,
I added two sentences regarding the confusion.
I changed a_1 into a_0

2022-01-12 15:52 UTC, co9olguy commented on demos_qml.rst
> +    :figure: demonstrations/classical_kernels/gaussian_kernel.png
The picture with the circuit (or even the meme!) would make a more eye-catching thumbnail here

2022-01-12 16:29 UTC, emgilfuster commented on demos_qml.rst
> +    :figure: demonstrations/classical_kernels/gaussian_kernel.png
hm, I thought the text in the meme would become too small to be understood? And similar with the other one, wouldn't it appear like any other circuit? Plus wouldn't the aspect ratio be a problem? 
I'm asking because you have more experience here, ofc I'll go for the most blatant clickbait!

2022-01-12 16:44 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# There is a crazy formula that matches the entries of *probabilities* with the
It follows directly from S, and how the entries of W relate to each Fourier frequency!
I added three lines on this :)

2022-01-12 16:46 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# These closed-form equations allow us to find the solution numerically, using
yes, I agree! 
I added two sentences on this

2022-01-12 16:48 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +plt.ylabel("probabilities $w_j$")
uh, precisely! this slipped past me, thank you!

2022-01-12 16:57 UTC, mariaschuld commented on demos_qml.rst
> +    :figure: demonstrations/classical_kernels/gaussian_kernel.png
Thanks, I overlooked this...I would put the 4 circle graphic?

2022-01-12 16:59 UTC, emgilfuster commented on demos_qml.rst
> +    :figure: demonstrations/classical_kernels/gaussian_kernel.png
right away! chop chop

2022-01-12 17:12 UTC, emgilfuster commented
Hi @peterse I think I implemented all your proposals.
I left some answers to your comments, feel free to resolve them if you agree with what I wrote :)

Thank you very much for the review! 
I found it very spot on and agreed with everything you said.

2022-01-12 17:23 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +who'd like to see the underlying theory of QKs (and also so-called *Quantum Embedding
*Quantum Embedding Kernels* not rendering well for me, for some reason.

2022-01-12 17:26 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +x_2\in\mathcal{X}`.
Is \mathcal{X} a subset of the real numbers? It can be an abstract set, but I guess we're restricting to something less abstract in this tutorial?

2022-01-12 17:28 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +demo are positive semi-definite.
I agree that not much mathematical abstraction is needed, and I think this is great! However positive-semidefiniteness can be defined in one line and is not a hard concept, and since it's already mentioned I think it's worth to define.

2022-01-12 17:31 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +:math:`k(x_1+\zeta,x_2+\zeta)=k(x_1,x_2)` holds.
Here is where it is implied that \mathcal{X} should be a vector space (this shift-rule doesn't make sense, for example, if \mathcal{X} does not contain a zero element.

2022-01-12 17:35 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +to both inputs. That means, for any suitable shift vector
```suggestion
to both inputs. Explicitly, for any suitable shift vector
```

2022-01-12 17:36 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +At the same time, having this property means the function can be written in
```suggestion
Having this property means the function can be written in
```

2022-01-12 17:37 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +:math:`\delta:=x_1-x_2\in\mathcal{X}`, abusing notation a bit:
```suggestion
:math:`\delta:=x_1-x_2\in\mathcal{X}`.  Abusing notation a bit:
```

2022-01-12 17:42 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# .. math:: f(x) = a_0 + \sum_n a_n\cos(n\omega_0x) + b_n\sin(n\omega_0x).
Sums have to range over a set (1 to infinity in this case)

2022-01-12 17:45 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# infinity.
Which means that it's not periodic anymore, this confuses me a bit.

2022-01-12 18:00 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +    # For real functions, they are the same.
You can comment using """ (yes even in this markdown language) It looks better than writing a lot of #

2022-01-13 14:21 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +demo are positive semi-definite.
hm, positive semidefiniteness for matrices can be defined in one line, I agree.
But PSDness for functions requires a bit more, wouldn't you agree?
Either you need to introduce the Gramm matrix, or you spell out Mercer's condition.

It's still not that much, but given that it doesn't add much content, maybe I'd leave it out

2022-01-13 14:24 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +x_2\in\mathcal{X}`.
I added a line mentioning vector spaces, so that we avoid the problem you mention later.
Would you say this is enough?

Thanks for pointing this one out, indeed at no point did I introduce the extra structure required for shift invariant kernels to make sense, nice catch!

2022-01-13 14:47 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# infinity.
I paraphrased the text here, hope it's more understandable now

2022-01-13 14:53 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +who'd like to see the underlying theory of QKs (and also so-called *Quantum Embedding
there was an earlier version where the itallics was written with underscores instead of asterisks, and that didn't render for me either. In theory it should be fixed now, does the problem persist your end?

2022-01-13 14:58 UTC, emgilfuster commented
Hi @alvaro-at-xanadu thanks for the review.
I implemented most of your suggestions and resolved them.
Would you check the ones I didn't resolve, and see if you're happy with what I wrote?

2022-01-17 19:00 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +who'd like to see the underlying theory of QKs (and also so-called *Quantum Embedding
This is fixed now :)

2022-01-17 19:02 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +x_2\in\mathcal{X}`.
This will do I think!

2022-01-17 19:04 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +demo are positive semi-definite.
Ah you're right, I thought it was easier! Better leave as is!

2022-01-17 19:11 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# Let's take a moment to refresh the big scheme of things, with the following
```suggestion
# Let's take a moment to refresh the big scheme of things with the following
```

2022-01-17 19:12 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# The first one, trainable, will be a parametrised general state preparation
```suggestion
# The first one, trainable, will be a parametrized general state preparation
```

2022-01-17 19:13 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# The first one, trainable, will be a parametrised general state preparation
Since Xanadu is a Canadian company, so let's keep Canadian spelling throughout tutorials.

2022-01-17 19:17 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# In the second one we input the data, and call it :math:`S(x)`.
```suggestion
# In the second one we input the data, denoted by :math:`S(x)`.
```

2022-01-17 20:43 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# By setting the ``thetas`` properly, we achieve the integer-valued spectrum:
It was not clear to me why we need an integer valued spectrum. Is there an ultimate reason for it, or just a matter of taste?

2022-01-17 20:44 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# In order to use Newton's method we need the Jacobian of :math:`F_s`.
It would be nice to write the Jacobian explicitly here. You wrote it in code, but if someone wants to verify that this is indeed the case, it would be better for them to actually see the formula.

2022-01-17 20:46 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# This isn't necessarily bad in general, only for us.
So it wasn't a problem in the end? There seems to be no further comment on how we went around this.

2022-01-17 20:49 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +More specifically, in this demo we want to look into quantum kernels and ask
```suggestion
More specifically, in this demo, we want to look into quantum kernels and ask
```

2022-01-17 20:50 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +Usually, in quantum machine learning (QML) we use parametrized quantum circuits
```suggestion
Usually, in quantum machine learning (QML), we use parametrized quantum circuits
```

2022-01-17 20:53 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +Consequently, since kernels are just one specific kind of well-defined
```suggestion
Since kernels are just one specific kind of well-defined
```

2022-01-17 20:54 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +Consequently, since kernels are just one specific kind of well-defined
Let's start trimming down words to not be unnecessarily wordy. Always a good exercise!

2022-01-17 20:56 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +The way to attack this task would be to define a loss function directly
```suggestion
The way to attack this task is to define a loss function
```

2022-01-17 20:58 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +function, and it turns out that for certain classes of quantum circuits `we can
```suggestion
function. It turns out that for certain classes of quantum circuits `we can
```

2022-01-17 20:59 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +Using this theory together with some good old-fashioned convex optimisation, we
```suggestion
Using this theory together with some good old-fashioned convex optimization, we
```

2022-01-17 21:00 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +In order to keep the demo short and sweet, we focus on one simple example, but
```suggestion
In order to keep the demo short and sweet, we focus on one simple example. The```

2022-01-17 21:00 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +the same ideas would apply for more general scenarios.
```suggestion
same ideas apply to more general scenarios.
```

2022-01-17 21:04 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +quantifying the distance between both functions (the classical kernel function,
```suggestion
quantifying the distance between both functions (the classical kernel function
```

2022-01-17 21:07 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +Instead, we only need to know that there's an entire branch of ML which
```suggestion
Instead, we only need to know that an entire branch of ML which
```

2022-01-17 21:09 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +classical ML.
```suggestion
classical machine learning.
```

2022-01-17 21:09 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +classical ML.
Haven't defined ML acronym.

2022-01-17 21:12 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +If you'd like to see a more comprehensive introduction to where these functions
```suggestion
If you'd like to learn more about where these functions
```

2022-01-17 21:12 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +If you'd like to see a more comprehensive introduction to where these functions
More trimming down. Important when sentences are too long :)

2022-01-17 21:13 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +PennyLane), you could check out the following demos, which cover different
```suggestion
PennyLane), check out the following demos, which cover different
```

2022-01-17 21:14 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +Most often, and in this demo, we'll deal with real vector spaces as the data
```suggestion
In this demo, we'll deal with real vector spaces as the data
```

2022-01-17 21:15 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +lost in mathematical lingo, you can trust that all kernels featuring in this
```suggestion
lost in mathematical lingo. You can trust that all kernels featuring in this
```

2022-01-17 21:18 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +First, let's introduce a simple classical kernel that we will try to
```suggestion
First, let's introduce a simple classical kernel that we will
```

2022-01-17 21:19 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +First, let's introduce a simple classical kernel that we will try to
Sounds more confident 💪

2022-01-17 21:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# In this demo we will consider only this one example, but the arguments we
```suggestion
# In this demo, we will consider only this one example. However, the arguments we
```

2022-01-17 21:25 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# This way, we would be able to study the behavior when the period approaches
```suggestion
# This way, we can study the behaviour when the period approaches
```

2022-01-17 21:26 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# This way, we would be able to study the behavior when the period approaches
Trimming down! "Behaviour" is the Canadian variant of the spelling (confusing since it's a mix of US and UK spellings 😖 )

2022-01-17 21:30 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# With this we are restricted to considering only a finite number of Fourier
```suggestion
# We are restricted to considering only a finite number of Fourier
```

2022-01-17 21:31 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# number of coefficients, and then letting it slowly grow:
```suggestion
# number of coefficients and then slowly letting it grow:
```

2022-01-17 21:33 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# At the same time, it seems like starting :math:`5` or :math:`6` all the
```suggestion
# At the same time, it seems like starting at :math:`5` or :math:`6` all the
```

2022-01-17 21:34 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# This is important for us, since it tells us how many qubits we should use at
```suggestion
# This is important for us, since it tells us the minimum number of qubits we should use.
```

2022-01-17 21:35 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# least.
```suggestion

```

2022-01-17 21:36 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# So, at least :math:`6` frequencies means at least :math:`3` qubits, which
```suggestion
# At minimum of :math:`6` frequencies means at least :math:`3` qubits, corresponding
```

2022-01-17 21:37 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# would correspond to :math:`2^3=8` frequencies.
```suggestion
# to :math:`2^3=8` frequencies.
```

2022-01-17 21:43 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# Next we introduce the only trainable gate we neet to make use of.
```suggestion
# Next, we introduce the only trainable gate we need to make use of.
```

2022-01-17 22:27 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# In the code, we call :math:`a` ``amplitudes``:
```suggestion
# In the code below, the variable ``amplitudes`` corresponds to our set  :math:`a`.
```

2022-01-17 22:30 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# So far we only wrote the gate layout for the quantum circuit, no measurement!
```suggestion
# So far, we only wrote the gate layout for the quantum circuit, no measurement!
```

2022-01-17 22:31 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# Also, at this point we need to set the number of qubits of our computer.
```suggestion
# Also, at this point, we need to set the number of qubits of our computer.
```

2022-01-17 22:31 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# Next we construct the quantum node:
```suggestion
# Next, we construct the quantum node:
```

2022-01-17 22:36 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# Recall that the outputs of QKs can be defined as the probability of obtaining
```suggestion
# Recall that the output of QK is defined as the probability of obtaining
```

2022-01-17 22:38 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# the outcome :math:`\lvert0\rangle` when measuring on the computational basis.
```suggestion
# the outcome :math:`\lvert0\rangle` when measuring in the computational basis.
```

2022-01-17 22:40 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# the QK with the lag :math:`\delta` as argument, and one that implements it
```suggestion
# the QK with the lag :math:`\delta` as its argument, and one that implements it
```

2022-01-17 22:41 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# As a couple quality-of-life improvements, we write a function that implements
```suggestion
# As a couple of quality-of-life improvements, we write a function that implements
```

2022-01-17 22:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# a decaying spectrum which looks similar to :math:`1/\lvert x\rvert` - but not
```suggestion
# a decaying spectrum that looks similar to :math:`1/\lvert x\rvert` - but not
```

2022-01-17 22:58 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# As mentioned in the introduction, one could just "learn" this relation: take
As mentioned in the introduction, one could just “learn” this relation, that is, tune the parameters of the quantum kernel in a gradient-based manner until it matches the classical one.

2022-01-17 22:59 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# As mentioned in the introduction, one could just "learn" this relation: take
This sentence is too long and convoluted. Suggested change above ⏫

2022-01-17 22:59 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# black-box optimisation here.
```suggestion
# black-box optimization here.
```

2022-01-17 23:01 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# want to construct, and then use old-fashioned convex optimisation to find the
```suggestion
# want to construct and then use old-fashioned convex optimization to find the
```

2022-01-17 23:04 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# of this demo and confirm that it allows us to emulate the Gaussian kernel
```suggestion
# of this demo and confirm that we can to emulate the Gaussian kernel
```

2022-01-17 23:04 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# of this demo and confirm that it allows us to emulate the Gaussian kernel
Not clear what 'it' refers to.

2022-01-17 23:08 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# Newton's method is a classical one from convex optimisation theory.
```suggestion
# Newton's method is a classical one from convex optimization theory.
```

2022-01-17 23:10 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# For Newton's method we also need an initial guess.
```suggestion
# For Newton's method, we also need an initial guess.
```

2022-01-17 23:10 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# Finding a good initial guess requires some tinkering, different problems will
```suggestion
# Finding a good initial guess requires some tinkering; different problems will
```

2022-01-17 23:12 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# For ``MottonenStatePreparation`` we'll need to give ``amplitudes`` as one of the
```suggestion
# For ``MottonenStatePreparation``, we'll need to give ``amplitudes`` as one of the
```

2022-01-17 23:13 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# arguments, which is the component-wise square root of ``probabilities`` so it
```suggestion
# arguments, which is the component-wise square root of ``probabilities``, so it
```

2022-01-17 23:14 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# But as we just said this is still only the predicted spectrum.
```suggestion
# But as we just said, this is still only the predicted spectrum.
```

2022-01-17 23:15 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# And with this we can finally visualize how the Fourier spectrum of the
```suggestion
# And with this, we can finally visualize how the Fourier spectrum of the
```

2022-01-17 23:18 UTC, alvaro-at-xanadu reviewed
I think this is a well-written and interesting tutorial. I only have a few comments about the content, but it may be that I don't know much about quantum kernels.

I suggested some changes to the grammar, since some sentences were hard to parse. Most corrections are minor. 

Excellent work :)

2022-01-18 16:15 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# This way, we would be able to study the behavior when the period approaches
thanks! oh my, I had honestly never heard about Canadiant spelling 😅 thanks for taking the time to check that!

2022-01-18 16:18 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +Consequently, since kernels are just one specific kind of well-defined
Thank you for this, I've been battling with this demo for too long and have become unaware of finding these superfluous words :(

2022-01-18 16:29 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# By setting the ``thetas`` properly, we achieve the integer-valued spectrum:
in Fourier analysis we approximate functions f(x) with linear combinations of {sin(nwx), cos(nwx)}, for some fundamental frequency w and integer valued n. Without the condition that n is integer, {sin(nwx), cos(nwx)} don't form an orthonormal basis, and then Fourier theory doesn't hold.
It's a bit weird, we could construct kernels with arbitrary frequencies, but if we want to do this thing of learning a function by matching its Fourier spectrum, then we need to restrict the frequencies to be integer-valued. 

Said otherwise, we have a mechanism that gives us a frequency spectrum and a set of coefficients for any given function. With this quantum kernel first we try to match the frequency spectrum (by fixing the thetas), and then we try to match the coefficients (with the array of amplitudes lower down). The fact we want our spectrum to be integer valued comes from the fact we've chosen the FFT as our mechanism.

I'm not sure I'd know how to convey this in a condensed and non-technical way here. Do you think it's coming too much out of nowhere?

2022-01-18 16:31 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# of this demo and confirm that it allows us to emulate the Gaussian kernel
agree, thanks!

2022-01-18 16:36 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# In order to use Newton's method we need the Jacobian of :math:`F_s`.
hm I'm not sure about that one, it's a bit of a big matrix. It's not complicated, but might look scary from the outset? (it's from an old iteration, these w what we call p now)
![image](https://user-images.githubusercontent.com/44003229/149978822-bdbee46d-9397-4e75-bd7b-0861cc137826.png)

Of course I value your zoomed-out perspective more than mine here, just wanted to make sure you don't think this matrix would scare more than it helps.

2022-01-18 16:41 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# By setting the ``thetas`` properly, we achieve the integer-valued spectrum:
Ok, I see, this comes from $\omega = 1$. Maybe just add: "as required by the Fourier series expansion of a function of period $2\pi$".

2022-01-18 16:44 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# As mentioned in the introduction, one could just "learn" this relation: take
good, thanks!

2022-01-18 16:49 UTC, emgilfuster commented on demonstrations/tutorial_classical_kernels.py
> +# This isn't necessarily bad in general, only for us.
hm yeah that sentence is a bit misleading maybe.
I change it into "This would be fatal for us" and add one sentence on this.
Does it sound better now?

2022-01-18 16:52 UTC, emgilfuster commented
Thank you so much for that review @alvaro-at-xanadu!
I appreciate the effort you gave to improving the demo, also the misaligned spelling!

I implemented all the suggestions except for one, see the comment on the jacobian matrix :)
I also tried to explain the necessity for the spectrum to be integer valued, and why it might be difficult to explain in the demo.

Have a nice week

2022-01-27 15:46 UTC, mariaschuld commented
@alvaro-at-xanadu could you kindly approve when you're happy? We'll then be merge ready!

2022-01-27 15:52 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +classical one could be posed as an optimisation problem.
```suggestion
classical one could be posed as an optimization problem.
```

2022-01-27 15:58 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# period :math:`2L` (we take :math:`2\pi` as default):
```suggestion
# period :math:`2L` (we take :math:`L=\pi` as default):
```

2022-01-27 16:28 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# a decaying spectrum that looks similar to :math:`1/\lvert x\rvert` - but not
```suggestion
# a decaying spectrum that looks similar to :math:`1/\lvert x\rvert` — but not
```

2022-01-27 16:28 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_classical_kernels.py
> +# a decaying spectrum that looks similar to :math:`1/\lvert x\rvert` - but not
Changed to em dash

2022-01-27 16:43 UTC, emgilfuster commented
Implemented the last changes, thanks for the new catches!

2022-01-27 16:58 UTC, alvaro-at-xanadu approved these changes
We're good to go!

2022-02-02 22:46 UTC, peterse commented on demonstrations/tutorial_classical_kernels.py
> +def make_thetas(m_wires):
```suggestion
def make_thetas(n_wires):
```

2022-02-28 14:39 UTC, emgilfuster commented
Hi hi!

I couldn't resist adding the 300th comment on this discussion :)
Is everything release-ready? I guessed this was put on hold because of qhack ^^

2022-03-01 07:05 UTC, mariaschuld commented
@emgilfuster sorry, I should have followed up on this. @CatalinaAlbornoz, would it be possible to merge this soon? :)

2022-03-01 16:03 UTC, merged