Adds demo link to navbar
PennyLaneAI/qml pull request #327
Opened 2021-09-01 20:24 UTC by AndrewGardhouse

[CH8526](https://app.clubhouse.io/xanaduai/story/8526/add-demos-link-to-the-navbar)
Add a demos link to the navbar that directs to the demos page

2021-09-22 06:50 UTC, josh146 approved these changes

2021-09-22 06:53 UTC, josh146 requested changes
Hey @AndrewGardhouse - minor change here before I merge this in --- do you think you could add a green underline to the 'Demos' navbar entry when on the `demonstrations.html` and `demos/` part of the website? Should hopefully be simply with a bit of javascript?

2021-09-22 19:05 UTC, AndrewGardhouse commented
> Hey @AndrewGardhouse - minor change here before I merge this in --- do you think you could add a green underline to the 'Demos' navbar entry, and remove it from the 'Quantum Machine Learning' navbar entry, when on the `demonstrations.html` and `demos/` part of the website? Should hopefully be simply with a bit of javascript?

@josh146 Done 🙂

2021-09-23 05:59 UTC, josh146 commented
🙌 Looks great!

2021-09-23 06:01 UTC, josh146 approved these changes

2021-09-23 06:01 UTC, merged