[WIP] CH8527 | Update The Pennylane Demos Landing Page
PennyLaneAI/qml pull request #328
Opened 2021-09-03 20:09 UTC by AndrewGardhouse

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Add a thumbnail link to your tutorial in `beginner.rst`, or if a
      QML implementation, in `implementations.rst`.

- [ ] All QML tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2021-09-07 09:15 UTC, josh146 commented
@AndrewGardhouse looking really nice so far! I only have two main comments:

- The main demos page, the cards are all different heights. This is partially my fault - when I first made it, I wasn't sure how to get a 'grid' pattern, and so re-sized all the images so that the vertical card spacing was identical. But it would be nice to enforce this in the CSS, rather than by image + text height!

- The 'back' button on each category page _and_ the demos themselves takes you to the main QML page, rather than the demos page:
  
  ![image](https://user-images.githubusercontent.com/2959003/132318647-e2e5e5ce-62db-4165-8eee-ec6e7365c888.png)

  This should just be a matter of changing the location of the Sphinx TOC entries (since I think the back button follows that hierarchy - it goes to the page that 'contains' the TOC listing of the current page).

2021-09-08 14:05 UTC, AndrewGardhouse commented
> * The main demos page, the cards are all different heights. This is partially my fault - when I first made it, I wasn't sure how to get a 'grid' pattern, and so re-sized all the images so that the vertical card spacing was identical. But it would be nice to enforce this in the CSS, rather than by image + text height!

@josh146 I'm going to hold off on any more styling changes until we have finalized the copy and images for the cards on the main page

2021-09-17 07:56 UTC, josh146 reviewed
Thanks @AndrewGardhouse! new categories are looking really slick.

A couple of more general comments:

- @ixfoduap tweaked the demo ordering on the Google doc last week, which doesn't look like it is reflected here (sorry, I should have sent a message that it got updated!). So the orderings of the demo cards on each category page will need to be slightly modified.

- In addition a couple of demos have moved category - ones I could spot straight away include VQT and 'Accelerating VQE with QNG'.

- I'm curious if the `max-width` CSS rules on the category cards still affect the height/layout of the card grid?

- Finally, it might be time to update the page metadata (used for social media cards) to have distinct images per category page?

  They currently look like this (using the [Twitter card validator](https://cards-dev.twitter.com/validator)): 

  ![image](https://user-images.githubusercontent.com/2959003/133746320-ec4dc2bb-280e-4fe8-8783-bf1b1069a9f0.png)

2021-09-17 07:56 UTC, josh146 commented on demonstrations.rst
> +                                    <img src="_static/community.png" class="img-fluid" style="max-width: 130px;"></img>
Might be good to reduce the size of this image, it looks quite large now compared to the others 😆

2021-09-17 07:56 UTC, josh146 commented on demonstrations.rst
> +                                    <img src="_static/quantum-chemistry.png" class="img-fluid" style="max-width: 110px;"></img>
Are the card heights still dependent on the value of `max-width` here?

2021-09-17 07:56 UTC, josh146 commented on demos_getting-started.rst
> +======
```suggestion
Getting Started
===============
```

2021-09-17 07:56 UTC, josh146 commented on demos_getting-started.rst
> +    :tags: autograd
Slight reorganization here. Could we change the order as follows?

- Basic tutorial: qubit rotation
- Quantum gradients with backpropagation
- Plugins and hybrid computation
- Noisy circuits
- Gaussian transformation
- Computing gradients in parallel with Amazon Braket
- Using JAX with PennyLane
- Turning quantum nodes into Keras layers
- Turning quantum nodes into Torch layers
- Training a quantum circuit with PyTorch
- Pytorch and noisy devices
- Optimizing noisy circuits with cirq

This matches the google doc, but I think the Google doc must have been updated after you made the changes here, sorry!

2021-09-17 07:56 UTC, josh146 commented on demos_quantum-chemistry.rst
> +    :tags: chemistry
These ones I believe should be moved to the `Optimization` page, based on the latest google doc

2021-09-17 07:56 UTC, josh146 commented on demos_quantum-chemistry.rst
> +============
```suggestion
Quantum Chemistry
=================
```

2021-09-17 07:56 UTC, josh146 commented on demos_quantum-chemistry.rst
> +   :property="og:image": https://pennylane.ai/qml/_static/demos_card.png
We should:

- Update the metadata description to be more specific to quantum chemistry
- Add an intro paragraph introducing quantum chemistry at the top of the page, as we do on the other demo categories.

@ixfoduap, any preferences for the content?

2021-09-17 18:32 UTC, ixfoduap requested changes
@AndrewGardhouse It looks so good! :star_struck: :star_struck: 

I left some suggestions on wording and proposed a header and intro text for the quantum chemistry section.

The main request is to please re-order the demos according to the google doc, to help us highlight key demos in each section. My apologies for not communicating this clearly enough from the start, I realize it's an annoying change to make :disappointed:

2021-09-17 18:32 UTC, ixfoduap commented on demonstrations.rst
> +   :property="og:description": Take a deeper dive into quantum computing by exploring cutting-edge algorithms using PennyLane and near-term quantum hardware.
```suggestion
   :property="og:description": Take a deeper dive into quantum computing by exploring cutting-edge algorithms using PennyLane and quantum hardware.
```

2021-09-17 18:32 UTC, ixfoduap commented on demonstrations.rst
> +            Take a deeper dive into quantum computing by exploring cutting-edge algorithms using PennyLane and near-term quantum hardware.</p>
```suggestion
            Take a deeper dive into quantum computing by exploring cutting-edge algorithms using PennyLane and quantum hardware.</p>
```

2021-09-17 18:32 UTC, ixfoduap commented on demonstrations.rst
> +                                    <p class="mb-1 grey-text px-3">Investigate, simulate, and infer properties of molecules and materials using quantum computing.</p>
```suggestion
                                    <p class="mb-1 grey-text px-3">Study the properties of molecules and materials using quantum computing.</p>
```

2021-09-17 18:32 UTC, ixfoduap commented on demonstrations.rst
> +                                    <p class="mb-1 grey-text px-3">Explore general quantum computing tasks and algorithms, from quantum volume to Boson sampling.</p>
```suggestion
                                    <p class="mb-1 grey-text px-3">Explore general quantum computing tasks and algorithms, from quantum volume to boson sampling.</p>
```

2021-09-17 18:32 UTC, ixfoduap commented on demos_optimization.rst
> +   :property="og:description": Explore various topics and ideas, such as the shots-frugal Rosalin optimizer, the variational quantum thermalizer, or the issue of barren plateaus in quantum neural net
```suggestion
   :property="og:description": Explore various topics and ideas, such as the shots-frugal Rosalin optimizer, the variational quantum thermalizer, or barren plateaus in quantum neural networks.
```

2021-09-17 18:32 UTC, ixfoduap commented on demos_optimization.rst
> +plateaus in quantum neural networks.
```suggestion
optimizer, the variational quantum thermalizer, or barren plateaus
in quantum neural networks.
```

2021-09-17 18:32 UTC, ixfoduap commented on demos_optimization.rst
> +    :tooltip: Learn how to implement QAOA workflows with PennyLane
Echoing what Josh mentioned, it would be great to reorder the demos in accordance to the google doc. My apologies for not communicating this change clearly enough. In this case the order should be

- Intro to QAOA
- Quantum natural gradient
- Accelerating VQEs with quantum natural gradient
- Barren plateaus in quantum neural networks
- Alleviating barren plateaus with local shot functions
- Optimization using SPSA
- Generalized parameter-shift rules
- Doubly stochastic gradient descent
- The Stochastic parameter-shift rule
- Quantum structure learning
- Frugal shot optimization with Rosalin
- Feedback-based quantum optimization (FALQON)
- Quantum analytic descent
- Variationally optimizing measurement protocols
- Variational quantum thermalizer
- Variational quantum linear solver
- Coherent quantum variational linear solver
- Optimizing a quantum optical neural network
- 3 qubit Ising model in Pytorch
- QAOA for maxcut

2021-09-17 18:32 UTC, ixfoduap commented on demos_quantum-chemistry.rst
> +   :property="og:description": Implementations of the latest cutting-edge ideas and research from quantum machine learning using PennyLane.
```suggestion
   :property="og:description": Explore and master quantum algorithms for quantum chemistry.
```

2021-09-17 18:32 UTC, ixfoduap commented on demos_quantum-chemistry.rst
> +   :property="og:image": https://pennylane.ai/qml/_static/demos_card.png
Intro paragraph:

Quantum chemistry is one the leading application areas of quantum computers. Master how to use PennyLane to construct molecular Hamiltonians, design quantum circuits for quantum chemistry, and simulate properties of molecules and materials.

2021-09-17 18:32 UTC, ixfoduap commented on demos_quantum-chemistry.rst
> +
Order here should be:

-Building molecular Hamiltonians
- A brief overview of VQE
- Givens rotations for quantum chemistry
- Modelling chemical reactions on a quantum computer
- Optimization of molecular geometries
- VQE in different spin sectors
- Measurement optimization
- VQE with parallel QPUs on Rigetti Forest

2021-09-17 18:32 UTC, ixfoduap commented on demos_quantum-computing.rst
> +   :property="og:description": Explore the applications of PennyLane to more general quantum computing tasks such as benchmarking and characterizing quantum processors.
```suggestion
   :property="og:description": Explore the applications of PennyLane to general quantum computing tasks such as benchmarking and characterizing quantum processors.
```

2021-09-17 18:32 UTC, ixfoduap commented on demos_quantum-computing.rst
> +Explore the applications of PennyLane to more general quantum computing tasks
```suggestion
Explore the applications of PennyLane to general quantum computing tasks
```

2021-09-17 18:32 UTC, ixfoduap commented on demos_quantum-computing.rst
> +
Order here:

- Quantum volume
- Understanding the Haar measure
- Classical shadows
- Quantum computation with neutral atoms
- Beyond classical computing with qsim
- Quantum advantage with Gaussian Boson Sampling

2021-09-17 19:18 UTC, AndrewGardhouse commented on demonstrations.rst
> +                                    <img src="_static/quantum-chemistry.png" class="img-fluid" style="max-width: 110px;"></img>
Not the height of the cards, but the alignment of the content of the cards. The images aren't all the same size, so the `max-width` is being used to make the images look more consistent 🙂

2021-09-17 19:19 UTC, AndrewGardhouse commented on demonstrations.rst
> +                                    <img src="_static/community.png" class="img-fluid" style="max-width: 130px;"></img>
Does this work for you?
<img width="954" alt="Screen Shot 2021-09-17 at 3 18 50 PM" src="https://user-images.githubusercontent.com/8475900/133842368-ce0d4651-3775-4ecb-8e61-0ba843c1937b.png">

2021-09-17 20:07 UTC, AndrewGardhouse commented
> * Finally, it might be time to update the page metadata (used for social media cards) to have distinct images per category page?
>   They currently look like this (using the [Twitter card validator](https://cards-dev.twitter.com/validator)):
>   ![image](https://user-images.githubusercontent.com/2959003/133746320-ec4dc2bb-280e-4fe8-8783-bf1b1069a9f0.png)

@josh146 I think this is out of scope for this ticket

2021-09-17 20:56 UTC, AndrewGardhouse commented on demos_quantum-chemistry.rst
> +
What about "The Variational Quantum Thermalizer" and "Adaptive circuits for quantum chemistry"?
<img width="1269" alt="Screen Shot 2021-09-17 at 4 55 08 PM" src="https://user-images.githubusercontent.com/8475900/133852546-5417a24d-b112-4253-8b51-ab1e4e8baf5b.png">

2021-09-17 21:25 UTC, ixfoduap commented on demos_quantum-chemistry.rst
> +
The variational thermalizer should be removed from here and used only in the optimization folder.

The adaptive circuits one is new, which is why we missed it. Great catch! It can go between Givens rotations and modelling reactions. So the order is

Building molecular Hamiltonians
A brief overview of VQE
Givens rotations for quantum chemistry
Adaptive circuits for quantum chemistry
Modelling chemical reactions on a quantum computer
Optimization of molecular geometries
VQE in different spin sectors
Measurement optimization
VQE with parallel QPUs on Rigetti Forest

2021-09-18 15:39 UTC, josh146 commented
> @josh146 I think this is out of scope for this ticket

Yes you're right 🙂

2021-09-18 15:40 UTC, josh146 commented on demonstrations.rst
> +                                    <img src="_static/quantum-chemistry.png" class="img-fluid" style="max-width: 110px;"></img>
Ah, got it!

2021-09-18 15:40 UTC, josh146 commented on demonstrations.rst
> +                                    <img src="_static/community.png" class="img-fluid" style="max-width: 130px;"></img>
Looks great, thanks @AndrewGardhouse!

2021-09-20 13:46 UTC, AndrewGardhouse commented on demos_optimization.rst
> +    :tooltip: Learn how to implement QAOA workflows with PennyLane
@ixfoduap I can't find the demo `Alleviating barren plateaus with local shot functions` anywhere 🤔

2021-09-20 13:59 UTC, josh146 commented on demos_optimization.rst
> +    :tooltip: Learn how to implement QAOA workflows with PennyLane
@AndrewGardhouse it's this one https://pennylane.ai/qml/demos/tutorial_local_cost_functions.html 🙂

2021-09-20 14:25 UTC, AndrewGardhouse commented on demos_optimization.rst
> +    :tooltip: Learn how to implement QAOA workflows with PennyLane
Thank you!

2021-09-21 11:21 UTC, josh146 approved these changes
Thanks @AndrewGardhouse, looks fantastic! Good to go from my end, but will wait for @ixfoduap's final review

2021-09-21 16:00 UTC, ixfoduap requested changes
Looks great! It just needs re-organizing the QML page according to the order in the google doc, which I replicated in the comments. Once that's done I'm happy to approve.

Thanks @AndrewGardhouse for the amazing work! :man_dancing: :tada:

2021-09-22 13:16 UTC, AndrewGardhouse commented on demos_qml.rst
> +
@ixfoduap Done 🙂

2021-09-22 14:33 UTC, ixfoduap approved these changes
:shipit:

2021-09-22 16:48 UTC, merged

2021-09-22 18:14 UTC, co9olguy commented
:tada: