[WIP]Update demos to make use of the new qml.sample and qml.expval(H) functionality (story #: 8118)
PennyLaneAI/qml pull request #330
Opened 2021-09-10 20:05 UTC by Jaybsoni

### Before submitting

Please complete the following checklist when submitting a PR:

- [n] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [y] Add a thumbnail link to your tutorial in `beginner.rst`, or if a
      QML implementation, in `implementations.rst`.

- [y] All QML tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Update demos to use qml.sample and qml.expval(H):**

**Summary:**
Updating the tutorials to make use of the new functionality in qml.sample and removing the dependance on qml.ExpvalCost as it will be redacted

**Relevant references:**
story id: 8118

**Possible Drawbacks:**

**Related GitHub Issues:**

2021-09-15 03:06 UTC, Jaybsoni commented on demonstrations/tutorial_measurement_optimize.py
>  print("Number of quantum evaluations:", dev.num_executions)
Two things I would like to point out regarding the updates to this file: 
- This particular line of code (156), in the original tutorial produces 15 'executions'. The updated one only generates a single 'execution'. Not sure if this is a bug. If it isn't then I am not sure if we still want to keep this line of code. 
- Secondly, some of the results generated (in this entire tutorial) vary from the results of the original tutorial in the last 10^-13 ~ 10^-15 decimal places. I assume this is just noise on the python side. Not sure if that is worth looking into.

2021-09-15 05:59 UTC, josh146 commented on demonstrations/tutorial_measurement_optimize.py
>  print("Number of quantum evaluations:", dev.num_executions)
Good catches @Jaybsoni! I can provide some insights.

> This particular line of code (156), in the original tutorial produces 15 'executions'. The updated one only generates a single 'execution'. Not sure if this is a bug. If it isn't then I am not sure if we still want to keep this line of code.

This is because `return expval(H)` acts very differently to `ExpvalCost` internally. While `ExpvalCost` always creates a separate circuit per Hamiltonian commuting group (as you need to do on hardware), `return expval(H)` tries to be smarter:

- If `shots=None`, it computes the expectation value `<psi|H|psi>` _directly_, without needing to group Hamiltonian terms.
- If `shots>0`, it reverts to the existing behaviour of grouping.

In most case when running a simulation, we only care about the expectation value --- _how_ we computed the expectation value is not so important. But in this case, this particular demo actually _explores_ the grouping behaviour!

So we want to preserve the old behaviour here. We have several options:

1. One option is to _manually_ group the Hamiltonian, and print the commuting groups:

  ```pycon
  >>> H.compute_grouping()
  >>> len(H.grouping_indices)
  5
  ```

  (and ignore that the simulation is actually just doing one execution!). I don't really like this though, doesn't feel very clear.

2. Another option is to set `shots=1000` (or something similar) for the sections that use `ExpvalCost` (e.g., the first section, and the very last code-block). The rest can be left at `shots=None` for speed/accuracy.

3. A third option, which I think I like the most (but which doesn't exist yet!) is to extend PennyLane so that you can specify that you want grouping to occur even if `shots=None`. But this requires (a) thinking about how we want the UI to look, and (b) changes to PL master 🙂 

> Secondly, some of the results generated (in this entire tutorial) vary from the results of the original tutorial in the last 10^-13 ~ 10^-15 decimal places. I assume this is just noise on the python side. Not sure if that is worth looking into.

Yep, this would be related to the different logical pathway taken by `expval(H)` and `ExpvalCost` 🙂

2021-09-15 06:00 UTC, josh146 commented on demonstrations/tutorial_measurement_optimize.py
>  print("Number of quantum evaluations:", dev.num_executions)
Another tangential thought: I just realized that `dev.num_executions` is now outdated, and has been replaced with the device tracker: https://pennylane.readthedocs.io/en/stable/code/api/pennylane.Tracker.html

2021-09-22 03:26 UTC, Jaybsoni commented on demonstrations/tutorial_vqe_qng.py
> +@qml.qnode(dev)
The documentation paragraph associated with this bit of code (lines 58 - 60) describes some capabilities of qml.ExpvalCost, not sure if this is still true for qml.expval. Let me know how I should update that bit of documentation.

2021-09-22 04:19 UTC, josh146 commented on demonstrations/tutorial_vqe_qng.py
> +@qml.qnode(dev)
good catch @Jaybsoni, I would remove the "using the ``ExpvalCost`` class," part :)

2021-09-22 05:13 UTC, Jaybsoni commented on demonstrations/tutorial_vqe_parallel.py
>  # Calculating the potential energy surface
The paragraph below also describes some functionality which is specific to ExpvalCost, any suggestions on how we can edit this one?

2021-09-22 05:13 UTC, Jaybsoni commented on demonstrations/tutorial_vqe_qng.py
> +@qml.qnode(dev)
Ah awesome thanks !

2021-09-22 05:33 UTC, Jaybsoni commented on demonstrations/learning2learn.py
> +        # cost = qml.ExpvalCost(circuit, cost_h, dev, interface="tf", diff_method="backprop")
It seems ExpvalCost has keyword arguments which (I assume) specify how derivatives are computed of the underlying expectation value with respect to the trainable parameters. How can I preserve these settings otherwise ?

2021-09-22 06:02 UTC, antalszava commented on demonstrations/learning2learn.py
> +        # cost = qml.ExpvalCost(circuit, cost_h, dev, interface="tf", diff_method="backprop")
It should be possible to simply pass them to the QNode:

```python

@qml.qnode(dev, interface="tf", diff_method="backprop")
def circuit():
    # some circuit
    return expval(H)
```

2021-09-22 06:07 UTC, antalszava commented on demonstrations/tutorial_vqe_parallel.py
>  # Calculating the potential energy surface
Oh, that's a good question :thinking: Frankly, I'm not sure if using `parallel` option of QNodeCollection is still accessible with the `expval(H)` syntax.

@josh146 any thoughts?

2021-09-22 06:46 UTC, josh146 commented on demonstrations/tutorial_vqe_parallel.py
>  # Calculating the potential energy surface
I don't think it is! Perhaps best to leave this demo using `ExpvalCost`?

2021-09-22 15:55 UTC, Jaybsoni commented on demonstrations/tutorial_vqe_parallel.py
>  # Calculating the potential energy surface
Cool, I will revert the changes for this demo then!

2021-09-22 16:02 UTC, Jaybsoni commented on demonstrations/learning2learn.py
> +        # cost = qml.ExpvalCost(circuit, cost_h, dev, interface="tf", diff_method="backprop")
Ahh I see, thanks !

2021-09-22 16:36 UTC, Jaybsoni commented on demonstrations/tutorial_measurement_optimize.py
>  print("Number of quantum evaluations:", dev.num_executions)
Cool! I replaced `dev.num_executions` with `qml.Tracker`. I went with your 2nd suggestion as the 3rd one seems to be worth a separate PR. 

Also wanted to mention that I didn't set the shots for the very last code block because I don't think it is required, I think it explicitly computes the groupings.

2021-09-23 14:25 UTC, antalszava reviewed
Hi @Jaybsoni, this is looking nice! :tada: :slightly_smiling_face: Left some questions/suggestions.

1. There seem to be some occurrences of `ExpvalCost` in https://github.com/PennyLaneAI/qml/blob/master/demonstrations/tutorial_vqe_parallel.py too. Would they need to be changed?
2. Did the changed demos produce the expected outputs? (Including the ones that are not automatically run.)

2021-09-23 14:25 UTC, antalszava commented on demonstrations/tutorial_measurement_optimize.py
> +print("Number of quantum evaluations:", tracker.totals['executions'])
Nice!

2021-09-23 14:25 UTC, antalszava commented on demonstrations/tutorial_qaoa_maxcut.py
> +# to an int
```suggestion
# We will need a way to sample a measurement of multiple qubits in the computational basis
#  in integer form.
```

2021-09-23 15:00 UTC, Jaybsoni commented on demonstrations/tutorial_vqls.py
> +q_probs = np.bincount(samples, minlength=2 ** n_qubits) / n_shots
I think I specified it because I wanted to cover the case where we don't sample some of the bit strings at either end of the distributions. If we miss it, then the distribution might have fewer bins. But I guess its not necessary in this case as it wasn't included last time?

2021-09-23 15:38 UTC, antalszava commented on demonstrations/tutorial_vqls.py
> +q_probs = np.bincount(samples, minlength=2 ** n_qubits) / n_shots
Yep, maybe best left as is, if the change is not required. :)

2021-09-23 17:28 UTC, Jaybsoni commented on demonstrations/tutorial_measurement_optimize.py
> +dev = qml.device("default.qubit", wires=num_qubits, shots=1000)
Because when shots=None, the result is computed analytically the tracker only registers a single execution, but in this tutorial we want to track the number of executions if we were to explicitly run it.

2021-09-24 14:20 UTC, Jaybsoni commented on demonstrations/tutorial_vqls.py
> +q_probs = np.bincount(samples, minlength=2 ** n_qubits) / n_shots
Got it !

2021-09-24 14:23 UTC, Jaybsoni commented on demonstrations/tutorial_qaoa_intro.py
> +# function :func:`~.pennylane.expval(H)` is designed for this purpose: it returns the
Got it,

2021-09-24 14:27 UTC, Jaybsoni commented on demonstrations/tutorial_measurement_optimize.py
> +    return qml.expval(H)
Ahh I see!

2021-09-24 16:12 UTC, Jaybsoni commented on demonstrations/tutorial_falqon.py
> +
Got it!

2021-09-24 16:26 UTC, Jaybsoni commented on demonstrations/tutorial_falqon.py
> +@qml.qnode(dev)
Ok, I think I get what you are suggesting, I implemented it in, let me know if this is what you had in mind.

2021-09-24 16:35 UTC, Jaybsoni commented
> Hi @Jaybsoni, this is looking nice! 🎉 🙂 Left some questions/suggestions.
> 
> 1. There seem to be some occurrences of `ExpvalCost` in https://github.com/PennyLaneAI/qml/blob/master/demonstrations/tutorial_vqe_parallel.py too. Would they need to be changed?
> 2. Did the changed demos produce the expected outputs? (Including the ones that are not automatically run.)

Hey Antal, I believe we discussed with Josh that we should leave the vqe_parallel tutorial as is. I have addressed all of your comments above. I confirmed that all of the automatically running demos are working as expected. I will go over the rest of them today and get back to you.

2021-09-24 16:37 UTC, josh146 commented
> I believe we discussed with Josh that we should leave the vqe_parallel tutorial as is.

Yep, the reason was that the parallel VQE tutorial is designed to highlight the Dask parallelization of `ExpvalCost`, which no longer exists in the `expval(H)` pipeline, we may have to revisit this demo later

2021-09-24 20:57 UTC, Jaybsoni commented
Hi @antalszava and @josh146,

I finished checking most of the demos, there are just 2 left to check which I am having trouble running. 

1st: [qsim beyond classical demo](https://pennylane.ai/qml/demos/qsim_beyond_classical.html)
In this case I am running into a weird import error with qsimcirq: 
<img width="581" alt="image" src="https://user-images.githubusercontent.com/21964864/134738391-32d6bddf-0043-4918-be7e-60068d34f51e.png">
<img width="577" alt="image" src="https://user-images.githubusercontent.com/21964864/134738543-61edc511-9333-4dad-9694-3d4cc543ac78.png">
<img width="574" alt="image" src="https://user-images.githubusercontent.com/21964864/134738613-4a4c0627-8c0d-4852-a113-51ab9e241616.png">

Have either of you come across this error before ? 

2nd: [braket parallel gradients](https://pennylane.ai/qml/demos/braket-parallel-gradients.html)
This one requires a Braket account to complete. 

If you could help me debug the first issue and provide me with at Braket account I can finish the reviews my self, otherwise it might be faster if someone who has a working setup can review them quickly so we can get this merged in? I am 90% sure it shouldn't cause any issues. 

Cheers,

2021-09-27 08:24 UTC, josh146 commented
>  In this case I am running into a weird import error with qsimcirq:

I'm not 100% sure here, but I think @rmoyard or @thisac might know, I think they have run into similar issues!

>  This one requires a Braket account to complete.

Sure, that can be arranged!

2021-09-27 11:39 UTC, mariaschuld commented on demonstrations/tutorial_qaoa_maxcut.py
> +#  in integer form.
```suggestion
# in integer form.
```

2021-09-27 11:42 UTC, mariaschuld commented on demonstrations/tutorial_vqe_qng.py
> +# Again, we define the cost function using ``expval(H)``.
I was wondering if here and in other places it would be clearer to say "we define the cost to be the expectation of the Hamiltonian" or "we define the cost to be the QNode itself"...It's not so important though.

2021-09-27 11:43 UTC, mariaschuld commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# Next, we use the :func:`~.pennylane.expval` function to define the cost function.
For example, we are not using the expval function, but the entire qnode to define the cost. Or in other words, the measurement outcome.

2021-09-27 11:48 UTC, mariaschuld reviewed
Thanks for taking on this cumbersome task @Jaybsoni! 

@josh146  and I had a chat about how to deal with demos that use `ExpvalCost(..,parallel=True)` and we were wondering if one should just "unpack" the ExpvalCost and use dask explicitly. I.e., one could make one Qnode per Hamiltonian term, and then execute all Qnodes with dask. What do you think? 

This could be useful for users to get used to dask, and should have the same performance! It also shows an alternative, manual way to do VQE...

If you agree, just ping me if there are any problems! The important dask code is in the `QNodeCollection` class if I remember correctly.

2021-09-27 13:50 UTC, Jaybsoni commented on demonstrations/tutorial_vqe_qng.py
> +# Again, we define the cost function using ``expval(H)``.
That feels clearer to me as well,

2021-09-27 20:17 UTC, Jaybsoni commented on demonstrations/tutorial_vqe_spin_sectors.py
> +# Next, we use the :func:`~.pennylane.expval` function to define the cost function.
Agreed!

2021-09-27 20:35 UTC, antalszava commented
@Jaybsoni just a guess, could there be something going on with the [`libomp` installation](https://formulae.brew.sh/formula/libomp)? That image seems to be missing. :thinking:

If it doesn't come around, let us know. :slightly_smiling_face:

2021-09-27 21:09 UTC, thisac commented
>  In this case I am running into a weird import error with qsimcirq:

I don't recognize the error, so I'm not sure what's causing it. Have you tried both installing with `pip` as well as directly from the GitHub master branch? I think I remember only getting one of them to work before.

@Jaybsoni I'm able to run the demo fine on my personal laptop, so I could help testing it out if you'd like.

2021-09-28 19:11 UTC, Jaybsoni commented
Hey all (@antalszava, @josh146), 

I can now confirm that all of the demos are running as expected. I was able to run the Braket parallel gradients demo today and @antalszava ran the Qsim beyond classical demo. Beyond that I have addressed any comments left on my changes. 


> Thanks for taking on this cumbersome task @Jaybsoni!
> 
> @josh146 and I had a chat about how to deal with demos that use `ExpvalCost(..,parallel=True)` and we were wondering if one should just "unpack" the ExpvalCost and use dask explicitly. I.e., one could make one Qnode per Hamiltonian term, and then execute all Qnodes with dask. What do you think?

@mariaschuld, thank you for the comments! That does seem to be a more informative solution, I think it might be better suited as its own separate story/ticket which I can take on after merging this one. 

I think the everything is good to go, let me know if you have any other suggestions and I can address them. 
Cheers,

2021-09-28 20:59 UTC, antalszava commented
[ch8118]

2021-09-28 21:26 UTC, antalszava approved these changes
Looks good to me :champagne: :tada: :blush: Awesome addition @Jaybsoni, thank you! No major comments remain from my side.

Just double-checking: might it be that we're restoring the old cached outputs for the automatically executed demos? (ccing @josh146)

2021-09-28 21:26 UTC, antalszava commented on demonstrations/braket-parallel-gradients.py
> +my_bucket = "amazon-braket-Your-Bucket-Name"  # the name of the bucket, keep the 'amazon-braket-' and then include name
```suggestion
my_bucket = "amazon-braket-Your-Bucket-Name"  # the name of the bucket, keep the 'amazon-braket-' prefix and then include the bucket name
```

2021-09-28 21:26 UTC, antalszava commented on demonstrations/tutorial_falqon.py
> +    for w in new_graph.nodes:
How come this was changed?

2021-09-28 21:26 UTC, antalszava commented on demonstrations/tutorial_mol_geo_opt.py
> +    return run_circuit(params, obs=hamiltonian, wires=range(6))
It might be worth creating an object for the number of wires e.g., on line 219 (`num_wires = 6`). Then this object can be used in the device definition and when passing the wires to `circuit`.

This would help with:
* Allowing that the number of wires needs to be changed only at one place (if applicable);
* Making the code slightly more descriptive by using a name such as `num_wires` or so.

2021-09-28 21:52 UTC, Jaybsoni commented on demonstrations/tutorial_falqon.py
> +    for w in new_graph.nodes:
Ah nice catch @antalszava, it must be a residual change left over when I was experimenting with the demo. I was sure I changed it back but I guess I must have missed it.

2021-09-28 21:59 UTC, Jaybsoni commented on demonstrations/tutorial_mol_geo_opt.py
> +    return run_circuit(params, obs=hamiltonian, wires=range(6))
Ahh yes, it improves code readability!

2021-09-28 22:01 UTC, Jaybsoni commented
> Looks good to me 🍾 🎉 😊 Awesome addition @Jaybsoni, thank you! No major comments remain from my side.
> 
> Just double-checking: might it be that we're restoring the old cached outputs for the automatically executed demos? (ccing @josh146)

Thanks for the comments! I made sure to run each demo script locally as opposed to relying on the CI tests, so I can confidently say that each of the demos that have been changed here should run (at least locally on my setup). Let me know if there is anything else.

2021-09-29 06:28 UTC, mariaschuld commented on demonstrations/tutorial_coherent_vqls.py
> +    # Therefore, sampling the device will give us a value of 0 or 1 for each qubit (n_qubits)
```suggestion
    # Therefore, sampling from the device will give us a value of 0 or 1 for each qubit (n_qubits)
```

I think this is more correct :)

2021-09-29 06:29 UTC, mariaschuld commented on demonstrations/qsim_beyond_classical.py
> +# take samples from the computational basis from all wires, which will give us
```suggestion
# take samples from the computational basis state using all wires, which will return bitstrings of
```

2021-09-29 06:30 UTC, mariaschuld commented on demonstrations/tutorial_coherent_vqls.py
> +# Here we convert the raw samples (bit strings) into integers and count them
```suggestion
# convert the raw samples (bit strings) into integers and count them
```

Not so important... :)

2021-09-29 06:30 UTC, mariaschuld commented on demonstrations/tutorial_mol_geo_opt.py
> +# expectation values of the hamiltonian.
Nice!

2021-09-29 06:32 UTC, mariaschuld commented on demonstrations/tutorial_qaoa_intro.py
> +# use the function :func:`~.pennylane.expval` by passing it a Hamiltonian `H`: it returns the
```suggestion
# use the function :func:`~.pennylane.expval` which returns the
```

I am not sure if "passing it" is grammatically correct? Could just be simplified like this...

2021-09-29 06:33 UTC, mariaschuld commented on demonstrations/tutorial_vqe_qng.py
> +# Again, we define the cost function to be the following QNode using the ``expval(H)`` function.
```suggestion
# Again, we define the cost function to be the following QNode that measures ``expval(H)``:
```

Only a suggestion...

2021-09-29 06:34 UTC, mariaschuld commented on demonstrations/tutorial_vqls.py
> +# Here we convert the raw samples (bit strings) into integers and count them
```suggestion
# convert the raw samples (bit strings) into integers and count them
```
just a suggestion

2021-09-29 06:35 UTC, mariaschuld approved these changes
Again, thanks so much for taking this on! I did not check if the demos return the correct results, and I added some suggestions to polish the comments, but they are not blocking. Other than that it looks good to me!

2021-09-29 07:53 UTC, josh146 requested changes
Awesome work @Jaybsoni! I've left some very minor suggestions, once these have been considered, happy to approve 💪

2021-09-29 07:53 UTC, josh146 commented on demonstrations/tutorial_chemical_reactions.py
>          prev_energy = energy
By switching to `expval(H)`, this demo went from 6 minutes to 1 minute execution time!

![image](https://user-images.githubusercontent.com/2959003/135223142-e842fdd1-455a-4009-99fa-e8165883ee42.png)

![image](https://user-images.githubusercontent.com/2959003/135223153-81fb926a-51da-4948-9219-1d49b5eff94d.png)

2021-09-29 07:53 UTC, josh146 commented on demonstrations/tutorial_falqon.py
>  plt.ylabel("Measurement Probability")
This one is another amazing speed improvement 😍 

![image](https://user-images.githubusercontent.com/2959003/135223580-e445c5f9-be4d-4f8e-b7a8-173f7657aa7c.png)

![image](https://user-images.githubusercontent.com/2959003/135223595-f6d685e9-f2ad-43aa-afd5-c6ea7dcb380e.png)

2021-09-29 07:53 UTC, josh146 commented on demonstrations/tutorial_falqon.py
>  plt.ylabel("Measurement Probability")
@Jaybsoni oddly enough, after your changes here, the output is also _better_; the state |112> has a higher probability!

2021-09-29 07:53 UTC, josh146 commented on demonstrations/tutorial_measurement_optimize.py
>  # How about a larger molecule? Let's try the water molecule :download:`h2o.xyz </demonstrations/h2o.xyz>`:
@Jaybsoni is there a reason for leaving this at the bottom?

![image](https://user-images.githubusercontent.com/2959003/135224203-4f0af70f-7993-41ae-aacb-b8ca74c881af.png)

@mariaschuld, I suppose in order to change this, we need to modify `qml.expval(H)` in order to optionally support grouping when requested with `shots=None`?

2021-09-29 07:53 UTC, josh146 commented on demonstrations/tutorial_mol_geo_opt.py
> +# expectation values of the hamiltonian.
```suggestion
# expectation values of the Hamiltonian.
```

2021-09-29 07:53 UTC, josh146 commented on demonstrations/tutorial_mol_geo_opt.py
>  # The ``hf`` array is used by the :class:`~.pennylane.BasisState` operation to initialize
![image](https://user-images.githubusercontent.com/2959003/135224411-10e9bf46-264c-4eb3-ba63-5c52f46f4a1a.png)

![image](https://user-images.githubusercontent.com/2959003/135224429-30b78068-eedf-4d22-9473-9e54828d5fb1.png)

😻

2021-09-29 07:53 UTC, josh146 commented on demonstrations/tutorial_mol_geo_opt.py
> +# Next, we define the `cost`` function :math:`g(\theta, x)` which depends on
```suggestion
# Next, we define the ``cost`` function :math:`g(\theta, x)` which depends on
```

2021-09-29 07:53 UTC, josh146 commented on demonstrations/tutorial_mol_geo_opt.py
> +    return run_circuit(params, obs=hamiltonian, wires=range(num_wires))
@Jaybsoni since it appears that the QNode is only really needed to be created once, should we instead use the decorator above,

```python
num_wires = 6
dev = qml.device("default.qubit", wires=num_wires)

@qml.qnode(dev)
def circuit(params, obs, wires):
    qml.BasisState(hf, wires=wires)
    qml.DoubleExcitation(params[0], wires=[0, 1, 2, 3])
    qml.DoubleExcitation(params[1], wires=[0, 1, 4, 5])
    return qml.expval(obs)
```
and then here, we can simply have

```python
def cost(params, x):
    hamiltonian = H(x)
    return circuit(params, obs=hamiltonian, wires=range(num_wires)
```

2021-09-29 07:53 UTC, josh146 commented on demonstrations/tutorial_mol_geo_opt.py
> +    grad = [qml.QNode(circuit, dev)(params, obs=obs, wires=range(num_wires)) for obs in grad_h]
The above suggestion would also make this line more efficient:

```python
grad = [circuit(params, obs=obs, wires=range(num_wires)) for obs in grad_h]
```

2021-09-29 07:53 UTC, josh146 commented on demonstrations/tutorial_qaoa_intro.py
>  # ``params[0]`` and ``params[1]`` into each layer of the circuit. That's it! The last
@mariaschuld this demo is actually a good example of the slowdown incurred for QAOA using the new sparse default when `shots=None`:

Before:
![image](https://user-images.githubusercontent.com/2959003/135225127-159a7599-efb3-4819-b8fb-232a01c007e5.png)

After:
![image](https://user-images.githubusercontent.com/2959003/135225147-b79b2949-b42d-4509-8566-683049e5c241.png)

Makes me think we should definitely consider how to avoid the sparse pipeline when all terms commute

2021-09-29 07:53 UTC, josh146 commented on demonstrations/tutorial_qaoa_maxcut.py
Interestingly, since we are using `shots=1` here, this demo has no speed increase/decrease :)

2021-09-29 07:53 UTC, josh146 commented on demonstrations/tutorial_qaoa_maxcut.py
> -    return qml.Hermitian(np.diag(range(2 ** n_wires)), wires=wires)
So glad this is finally gone!

2021-09-29 07:53 UTC, josh146 commented on demonstrations/tutorial_qaoa_maxcut.py
> +# in integer form.
```suggestion
# We will need a way to convert a bitstring, representing a sample of multiple qubits
# in the computational basis, to integer or base-10 form.
```
Perhaps this is slightly clearer?

2021-09-29 07:53 UTC, josh146 commented on demonstrations/tutorial_qaoa_maxcut.py
> +        return qml.sample()
🔥

2021-09-29 07:53 UTC, josh146 commented on demonstrations/tutorial_vqe_qng.py
![image](https://user-images.githubusercontent.com/2959003/135226012-b3922d5b-8b1d-4cf6-9dce-2fc4c98ba981.png)

![image](https://user-images.githubusercontent.com/2959003/135226031-cb6464c0-16ff-4539-97b2-1f301688233d.png)

💪

2021-09-29 11:42 UTC, Jaybsoni commented on demonstrations/tutorial_chemical_reactions.py
>          prev_energy = energy
Thats amazing!

2021-09-29 11:43 UTC, Jaybsoni commented on demonstrations/tutorial_falqon.py
>  plt.ylabel("Measurement Probability")
Interesting!

2021-09-29 11:49 UTC, Jaybsoni commented on demonstrations/tutorial_measurement_optimize.py
>  # How about a larger molecule? Let's try the water molecule :download:`h2o.xyz </demonstrations/h2o.xyz>`:
I think we decide to leave it in because the `optimize=True` keyword argument wasn't accessible through `expval(H)`? 

> Likely we'd have to keep this as is as if I recall correctly `optimize=False` is the default under the hood when using a QNode & `qml.expval(H)`.

2021-09-29 11:56 UTC, josh146 commented on demonstrations/tutorial_measurement_optimize.py
>  # How about a larger molecule? Let's try the water molecule :download:`h2o.xyz </demonstrations/h2o.xyz>`:
Thanks for the reminder!

2021-09-29 13:33 UTC, Jaybsoni commented on demonstrations/tutorial_mol_geo_opt.py
> +    return run_circuit(params, obs=hamiltonian, wires=range(num_wires))
Ahh yes this is much cleaner. I didn't think of moving the device definition up to the circuit definition because in a few of the demos the device was example specific, but in this case its just a standard 6 wire device.

2021-09-29 13:33 UTC, Jaybsoni commented on demonstrations/tutorial_mol_geo_opt.py
> +    grad = [qml.QNode(circuit, dev)(params, obs=obs, wires=range(num_wires)) for obs in grad_h]
Got it

2021-09-29 14:43 UTC, antalszava approved these changes
:100:

2021-09-29 14:47 UTC, josh146 approved these changes
Looks great @Jaybsoni 💪

2021-09-29 15:06 UTC, merged