First draft of trapped ions
PennyLaneAI/qml pull request #355
Opened 2021-10-19 14:26 UTC by alvaro-at-xanadu

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Add a thumbnail link to your tutorial in `beginner.rst`, or if a
      QML implementation, in `implementations.rst`.

- [ ] All QML tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2021-11-02 20:40 UTC, glassnotes requested changes
Finished going through everything now. As an overall comment, I recommend to reduce the length (especially at the beginning), which might be tricky to do in some places because I wouldn't want to sacrifice the high-quality explanations. But this was super informative, and it was especially cool to learn about how the gates are implemented! :atom_symbol: My formerly hand-wavy explanations of trapped ions are going to be so much better now :grin:

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# fundamental constant :math:`\hbar` times a fundamental frequency
It would be cool here to show a little schematic of a chain of ions and some arrows indicating the directions in which they can vibrate

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# by the same amount. When we shine laser light on a particular atom of
```suggestion
# :math:`\hbar\omega`, in packets of energy known as phonons. 
# When we shine laser light on a particular atom of
```

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# the two-qubit gates are implemented. When an ion is on the ground state
```suggestion
# the two-qubit gates are implemented. When an ion is in the ground state
```

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# similarly when the ion is on the excited state
```suggestion
# :math:`\left\lvert g \right\rangle \left\lvert n \right\rangle`, and
# similarly when the ion is in the excited state
```

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# :math:`\left\lvert g, e \right\rangle\left\lvert g, e \right\rangle\left\lvert n \right\rangle`,
The comma in the ket is a bit confusing, perhaps show just one example and the other cases can be inferred.

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# :math:`\omega_b=\omega+\Delta` on a particular ion. If it is on the
```suggestion
# :math:`\omega_b=\omega+\Delta` on a particular ion. If it is in the
```

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# following **blue-sideband** transition:
Oh that's really cool!

Why are they called blue and red sidebands?

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# excite the ion and de-excite the ion chain, also known as a
This one makes less sense to me; the ion chain is getting kicked down a state because we aren't adding enough energy, and not that we are taking some of it away?

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# .. figure:: ../demonstrations/trapped_ions/sidebands.png
Beautiful!

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# both the red and blue sideband frequencies, the Hamiltonian turns out to
```suggestion
# both the red- and blue-sideband frequencies, the Hamiltonian turns out to
```
(check usage of hyphens throughout)

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +#    **Entangled states primer:** Systems that have two or more components
I don't think the full box is needed here, we can assume that if a reader is familiar with entanglement. Maybe need just a sentence or two to lead into the Cirac-Zoller gate.

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# .. figure:: ../demonstrations/trapped_ions/CZgate2.png
Since colour is essential to the picture here (and I suppose the one before as well), just make sure to use a colour-blind-safe palette. Personally I like [this one](https://remcoproducts.com/wp-content/uploads/2017/09/cc.png), and it has a good blue, red, and pink.

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# .. figure:: ../demonstrations/trapped_ions/CZgate2.png
I also had a bit of trouble following the picture here;  could be helpful to number the different steps and add a bit more spacing between the horizontal rows of states.

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# .. figure:: ../demonstrations/trapped_ions/CZgate2.png
Minor detail, the result of the picture is also a different maximally entangled state than the one shown above; is it straightforward to show the example for the "normal" Bell state?

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# However, the implementation of the Circac-Zoller gate in real life is
```suggestion
# However, the implementation of the Cirac-Zoller gate in real life is
```

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# Using a quantum mechanical technnique known as perturbation theory, we
```suggestion
# Using a quantum mechanical technique known as perturbation theory, we
```

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# can deduce that that there is also a Rabi frequency :math:`\Omega_{MS}`
```suggestion
# can deduce that there is also a Rabi frequency :math:`\Omega_{MS}`
```

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# Using Schrodinger's equation allows us to derive how the qubits evolve
```suggestion
# Using Schrödinger's equation allows us to derive how the qubits evolve
```
Update to include umlaut in other instances of Schrödinger as well

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +def Molmer_Sorensen(t):
I think it would be clearer here to show the matrix in latex, rather than in code.

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# CNOT gate since it allows for universal quantum computation. How can we
(Okay later, I see that you actually use the MS gate to implement a CNOT!)

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +#    Circuit for the CNOT gate using rotations and an MS gate
Define the acronym MS somewhere in the text, or just write in full here

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# time :math:`t=\pi/2\Omega`. Let us verify that this is indeed the case
```suggestion
# Let us verify that this is indeed the case
```
I think we can assume knowledge of what these gates are.

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# by building the circuit on Pennylane:
```suggestion
# by building the circuit in PennyLane:
```

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +    qml.QubitUnitary(Molmer_Sorensen(np.pi/2/Omega),wires=[0,1])
Oh darn, we don't have the MS gate in PennyLane? Could be something nice to add as a "good first issue".

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +print(np.exp(-1j*np.pi/4)*ion_cnot([0,1]))
Similar comment as earlier, suppress the small values so that it's clearer what the output is.

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +    if st[0] == 1:
Oh instead of this you could use the [basis state preparation template](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.templates.state_preparations.BasisStatePreparation.html):

```python
qml.templates.BasisStatePreparation(st, wires=[0, 1])
```

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# 100, our current gate technology becomes practically unusable.
Great explanation!

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# grows more. However, a combination of approaches involving QCCDs and
```suggestion
# of the laser pulse [#Blumel2021]_. Such a speedup might not be enough as the ion chain
# grows. However, a combination of approaches involving QCCDs and
```

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# Implementing multi-qubit ion gates is not the only problem for
```suggestion
# Implementing multi-qubit gates is not the only problem for
```

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# volume so far. The big unknown is whether such devices can scale as much as we
```suggestion
# Moreover, what could be considered simple prototypes of such technologies have 
# already proven extremely powerful. The big unknown is whether such devices can scale as much as we 
```
There are lots of issues with quantum volume as a benchmark, so I wouldn't mention it here in this context as an indicator of power.

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# as much as they have. We hope to have drawn you attention to these latest
```suggestion
# as much as they have. We hope to have drawn your attention to these latest 
```

2021-11-02 20:40 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# References
The references will not render unless you cite them.

2021-11-03 15:27 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +superconducting circuits, or photons**. Discussing whether one of them
I think there will be a fourth tutorial in the series, which I'm thinking will be "other approaches", in a bit less detail. These are just the most widespread.

2021-11-03 15:29 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +long-lived and can easily interact with their neighbours. They do have
I'll rephrase it, it reads poorly.

2021-11-03 15:29 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +
Got it!

2021-11-03 15:33 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +# concrete objectives. In the year 2000, David DiVincenzo proposed a
Done!

2021-11-03 15:44 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +# today. Let us write them down and outline how trapped ions satisfy these
I'm still thinking of how to do this properly... since it'll be needed in the other tutorials. You're probably right that I don't need to overexplain how trapped ions satisfy these criteria just yet though.

2021-11-03 15:48 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +#    the qubits we already have without the need to generate more. All we
Maybe I should say "without the ion escaping". I'm thinking of when you count photons by absorbing them, you can never measure them again. Not so with the ions. Yes, the state collapses, but I can re-measure the collapsed state.

2021-11-03 15:50 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +# .. figure:: ../demonstrations/trapped_ions/Rotating.gif
Yep, just one line of code that needs to be changed

2021-11-03 15:50 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +# operations with two qubits.
Thanks!

2021-11-03 15:52 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# today. Let us write them down and outline how trapped ions satisfy these
I think just listing them in bullet form would be fine here. I imagine that the target audience for this tutorial is people who already know enough about QC to understand the context / rationale for these.

2021-11-03 15:53 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +# qubit.
My English teacher told me I couldn't use 'whose' for objects. Now I checked Merriam-Webster and saw that she was not correct. My life is instantly improved. I like your rephrasing better.

2021-11-03 15:54 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +#    excited state . If a photon hits an electron, it will go to that
nice!

2021-11-03 16:00 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +# the matrix:
I'm writing the Hamiltonian, which is a particular matrix.

2021-11-03 16:04 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +S_plus = np.array([[0,0],[1,0]])
Still need to black the whole thing

2021-11-03 16:05 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +print(1j*ion_hadamard(0))
Guess I should mention it's up to a global phase.

2021-11-03 16:08 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +# to get a Hadamard gate, we do five pulses, all of them with duration
I guess my idea as to magically obtain the Hadamard, but I guess I should comment on what is the reasoning behind it.

2021-11-03 16:14 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +# following **blue-sideband** transition:
I guess because one is red shifted and the other is blue shifted with respect to the energy gap. Don't know if I should go there?

2021-11-03 16:15 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +# excite the ion and de-excite the ion chain, also known as a
I'll add a note on this being counterintuitive. In fact, it all comes from the Hamiltonian and we just interpret it this way to make sense of it. Maybe I'll say that it's related to the resonant frequencies of the system as a whole.

2021-11-03 16:22 UTC, co9olguy commented on test-results/sphinx-gallery/junit.xml
> +<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="0" name="sphinx-gallery" skipped="0" tests="0" time="0.0"></testsuite>
Please `git rm` this file, it seems to be an accidental commit :slightly_smiling_face:

2021-11-03 16:23 UTC, co9olguy commented on demos_quantum-computing.rst
> +    :figure: demonstrations/trapped_ions/trapped_ions_tn.png
seems like its been fixed?

2021-11-03 16:25 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +superconducting circuits, or photons**. Discussing whether one of them
I'd recommend not stating the "main" ones here at all. Rather, you could just mention some examples without committing to which ones are the frontrunners (or subjects of our tutorial series)

2021-11-03 16:27 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +is always produced in the process. This series of tutorials aims not to
It won't be clear to a reader what "This series" refers to. This is just one tutorial, and we haven't introduced the idea that we will have a whole series (in fact, I think it's fine to have the series by putting out the content without making it an "official" thing)

2021-11-03 16:34 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +In this first part of the series, we introduce **trapped ion quantum
Again, the "series" is only mentioned obliquely. A reader has clicked on an article called "Trapped ion quantum computers". What sense do they have that they are reading through a series, other than these implicit references to it?

2021-11-03 16:34 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +Honeywell and IonQ. In particular, Honeywell has achieved a quantum
+1

2021-11-03 16:36 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +volume of 64, the largest in the market! As the name suggests, the
Yep, good to link to the demo. Also, IonQ claims a 4 bajillion quantum volume for some non-public devices (which may not even be built yet, who knows). Not that I think we should repeat their unvetted claims, but just something to keep in mind.

2021-11-03 16:41 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# Why do we use ions, that is, charged atoms, as qubits? The main reason
Might be a good place for an emdash instead?, e.g., 
```suggestion
# Why do we use ions—that is, charged atoms—as qubits? The main reason
```

2021-11-03 16:43 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# Dehmelt the 1989 Physics Nobel Prize since it is used to make highly
```suggestion
# Paul proposed his now-called Paul trap [#Paul1953]_. For this invention, Paul and
# Dehmelt were awarded the 1989 Physics Nobel Prize, since it is used to make highly
```

2021-11-03 16:43 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# Dehmelt the 1989 Physics Nobel Prize since it is used to make highly
sounded like the technique is the one giving out awards :stuck_out_tongue_winking_eye:

2021-11-03 16:46 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# region of space. The sought-for potential would look like this:
"potential" will definitely be jargon to non-physicists. Recommend finding another phrasing or giving the briefest of explanations of what it is
e.g., could be something like
```
The ideal configuration of the electric field—also known as a _potential_—would look like this:
```

2021-11-03 16:48 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# .. figure:: ../demonstrations/trapped_ions/Rotating.gif
Looking good! A tad bit slower wouldn't hurt

2021-11-03 16:51 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +#
Let's think about whether or not to include DiVincenzo's criteria up front. I feel like jumping straight into "How to trap an ion" would fit very well on its own. This part kind of bogs down the intro too much

Perhaps we can put DiVincenzo's critreia at the end as a summary instead? (and do so for each post?)

2021-11-03 16:55 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# used by IonQ and Honeywell. These elements have two valence electrons,
probably worth using a quick aside to remind the reader what a valence electron is, rather than having it on the next sentence

e.g., "These elements have two valence electrons—i.e., electrons that are not so tightly bound to the atom—and their ..."

2021-11-03 16:56 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# and their ionized version only has one. The valence electron is not so
probably worth using a quick aside to remind the reader what a valence electron is, rather than having it on the next sentence

e.g., "These elements have two valence electrons—i.e., electrons that are not so tightly bound to the atom—and their ..."

2021-11-03 17:02 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +#    excited state . If a photon hits an electron, it will go to that
Note: to avoid comment conflicts, I amended @glassnotes's suggestion (removed space)

2021-11-03 17:05 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# However, quantum mechanics forbids a direct transition between these two
Any brief intuition we can give as to why?

2021-11-03 17:12 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# momentum tells us that, in a matter of nanoseconds, the excited electron
I think that mentioning angular momentum, and the circularly polarized light beam in the image, is perhaps getting a bit too much into details that are tangential and could probably be removed without harm

2021-11-03 17:15 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# alternative is to use an ion, such as Calcium-43, that has a hyperfine
When using terms that readers may not be familiar with, it's good to communicate to them right away either what the term means, or use italics to indicate "yes we know you may not know this term, we're introducing it". I know you get to this already in the next sentence, but consider adding these quick definitions in the same sentence.

2021-11-03 17:20 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# infinite lifespan. We can use a procedure similar to optical pumping to
Intuition why this is the case may not be there for non-physicists

2021-11-03 17:23 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# electric currents.
Great example of having the definition/intuition right next to the term that may not be familiar :+1:

2021-11-03 17:25 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# of uncertainty is two use two species of ions: one for the ancilla and
```suggestion
# of uncertainty is two use to species of ions: one for the ancilla and
```

2021-11-03 17:28 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# the **ancilla**. If these ions emit light, they can accidentally excite
plural would be "ancillae"

2021-11-03 17:29 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# extra trouble when we want to implement arbitrary qubit operations [#Hughes2020].
citation didn't get built, something wrong with format?

2021-11-03 17:35 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +
```suggestion
```

2021-11-03 17:36 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# T gate using consecutive pulses with different times and phases. Namely,
first time "pulse" is mentioned in text; would be good to have it mentioned a bit earlier so it doesn't seem so spontaneous here

2021-11-03 17:38 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +#    :align: center
plot title and caption don't agree

2021-11-03 17:40 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +#    :math:`\varphi=\pi/2`, Rabi oscillations allow us to build a
on my screen, the comma shows on a newline. If you put the comma inside the `:math:`, it will prevent this
![image](https://user-images.githubusercontent.com/7213358/140163070-43e362d5-53b8-42a2-b411-4b18948faa51.png)

2021-11-03 17:47 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# chain is ideal for multiple qubit gate implementations. When cooled
```suggestion
# chain is ideal for multiple-qubit gate implementations. When cooled
```

2021-11-03 17:48 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# fundamental constant :math:`\hbar` times a fundamental frequency
There seem to be two different sense of "fundamental" in use here, which could be confusing? :thinking: 
The first is more like "universal constant", the second is akin to "relevant to this particular system"

2021-11-03 17:54 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +#     within the Lamb-Dicke regime. This means that the separation between
```suggestion
#     within something called the Lamb-Dicke regime. This means that the separation between
```

2021-11-03 17:54 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +#     within the Lamb-Dicke regime. This means that the separation between
Might also be good to italicize?

2021-11-03 17:55 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +#    <div class = "alert alert-block alert-info">
I just noticed you were doing custom html here. Did he ``.. note:: `` command not work for your purposes?

2021-11-03 17:57 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +#    <div class = "alert alert-block alert-info">
https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html

2021-11-03 18:00 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# The net effect this interaction with laser light is to excite
seems to be a word or two missing in this sentence? :thinking:

2021-11-03 18:02 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# use it to obtain it? Indeed, it is possible by using a combination of
I get what the sentence is saying, but "use it to obtain it" could be made more clear w.r.t. what "it" is in each case

2021-11-03 18:04 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# where :math:`RX` and :math:`RY` are rotations over around the X and Y
I'll leave this up to your taste, but the PennyLane convention for rotation gate names is somewhat ambigious, e.g., see here: 
https://pennylane.readthedocs.io/en/stable/code/api/pennylane.RX.html
We use `RX` for the "code" name of the gate, but in the math there we use `R_x`

2021-11-03 18:05 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# multi-qubit gates with high accuracy. What is not to like? As in every
```suggestion
# multi-qubit gates with high accuracy. What's not to like? As in every
```

2021-11-03 18:10 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# to the detector. One can do this using a waveguide architecture inside
```suggestion
# ions during a measurement are lost, so it would be good to find ways to 
# direct more of them to the detector. One can do this using a waveguide architecture inside
```

2021-11-03 18:11 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# imposing. After all, personal computers were the fruit of hard-work and
```suggestion
# imposing. After all, personal computers were the fruit of hard work and 
```

2021-11-03 18:11 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# as much as they have. We hope to have drawn you attention to these latest
The "We hope" sentence is a bit weak. Suggest rephrasing/updating a bit

2021-11-03 18:12 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# superconducting qubits and photonics to learn more about the latest quantum
let's not call out specifics yet. We can update this tutorial as more in the series come online :slightly_smiling_face:

2021-11-03 18:13 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# quantum computing algorithms with trapped ions.
What about photonic interconnects? I know people haven't really demonstrated these at any sort of production level (or even in labs?), but might be worth mentioning as one future pathway? (I believe IonQ is thinking about this approach)

2021-11-03 18:20 UTC, co9olguy requested changes
Thanks @alvaro-at-xanadu! I very in-depth and informative tutorial! :muscle: 

There is a lot of great stuff here, so I'm hesitant to suggest many substantial changes. Perhaps I can offer some high-level thoughts as someone who has just read the whole thing:

- It's a big tutorial, which can make it a substantial task to read all the way through. Could we find ways to streamline the introduction maybe so readers can jump to topic at hand right away? Otherwise, I recommend going through and trying to clip off words here or there (always a good exercise; I do it myself for my own writing). It's not that it's too verbose, but if we can communicate the same ideas with fewer words, it makes it easier to digest
- You've done a great job at reducing jargon. I spotted a few spots that could still be improved, but it's a big leap forward from previous version. 
- Images look great! Some of the ones with atoms, energy levels, kets, and lasers might have a bit too much going on, so I can second what @glassnotes said about maybe having a bit more whitespace in between to make them easier to parse visually
- We have plugins to both Honeywell and IonQ in PennyLane. It would be great to mention/link these in the tutorial. Ideally we could have some example code (e.g., for implementing an MS gate in either of these two libraries), but since they are online-only it might not make sense for a tutorial that is run with every commit

But overall this is all polish now to make the tutorial top-notch and more digestible to wider audiences. No major blockers from me in terms of structure/content

2021-11-03 20:07 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +superconducting circuits, or photons**. Discussing whether one of them
I'll just change to: Some common approaches are ... , among others.

2021-11-03 20:08 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +is always produced in the process. This series of tutorials aims not to
Sounds good. I'll just get rid of any mention of a series.

2021-11-03 20:11 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +#
Yes, I'm still thinking about this. Olivia thinks I should just include a bullet list with the criteria at the beginning. I don't know if I want them at the end since I mention them in-text. I'm thinking of putting them in another blue box. I have to sleep on it.

2021-11-03 20:18 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +# However, quantum mechanics forbids a direct transition between these two
I can try, don't want to go into selection rules. I could say something about conservation of ang momentum, but should I really go there?

2021-11-03 20:19 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +# momentum tells us that, in a matter of nanoseconds, the excited electron
I'll just mention the circular polarization, but delete the circular polarization text in image

2021-11-03 20:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +# infinite lifespan. We can use a procedure similar to optical pumping to
Fermi's golden rule XD? I'll try to come up with something

2021-11-03 20:24 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +# the **ancilla**. If these ions emit light, they can accidentally excite
My understanding is that this set of qubits is knows as ancilla, so no need for a plural. I could also say ancilla qubits, if this is preferred. I don't want to go into Latin plurals.

2021-11-03 20:25 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +# one for the qubits that are not measured, or **logical qubits**.
It's what I've heard before but I'll check if there's an alternative name.

2021-11-03 20:30 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +#    <div class = "alert alert-block alert-info">
This is a consequence of the random behaviour of the Jupyter Notebook to Markdown converter. I'll fix it.

2021-11-03 20:50 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +# use it to obtain it? Indeed, it is possible by using a combination of
Yes, this reads terribly. I'll rephrase.

2021-11-03 20:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +# time :math:`t=\pi/2\Omega`. Let us verify that this is indeed the case
Can't assume that they know MS(pi/2) is, so I'll rephrase this a little.

2021-11-03 20:53 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +# quantum computing algorithms with trapped ions.
That was the ultimate reason that I did not include this, but I'll add a paragraph on it.

2021-11-04 18:48 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# quantum computing algorithms with trapped ions.
Given the existing length, even an existing sentence or a `.. note::` might be sufficient

2021-11-04 18:49 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +# the **ancilla**. If these ions emit light, they can accidentally excite
:+1:

2021-11-04 18:50 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +#
actually the blue box might work, and you could do the same for each tutorial in the series to give them a common link

2021-11-04 18:55 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +#
+1 for the blue box, it'll help them stand out more too.

2021-11-05 14:15 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +# one for the qubits that are not measured, or **logical qubits**.
I do not want to get into the details in the text, but the ancilla described here is used for error syndrome measurements. This is why the other qubits are referred to as logical qubits.

2021-11-05 14:22 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +# excite the ion and de-excite the ion chain, also known as a
Actually the explanation is a little too involved. I think I'll leave it there for the reader to ponder...

2021-11-08 22:35 UTC, glassnotes requested changes
@alvaro-at-xanadu this looks great :+1: No major suggestions, mostly just caught typos and made some phrasing suggestions. I do still think it's a bit long, so see if you can find ways to trim things in places throughout, but otherwise once the suggestions here are addressed I think it's good to go :rocket:

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
>  # commonly used in university laboratories [#Bergou2021]_. The rare earth Yterbium-171 is
```suggestion
# commonly used in university laboratories [#Bergou2021]_. The rare earth Ytterbium-171 is
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# criterion. Introducing more ions will also pose additional challenges to
```suggestion
# criterion. Introducing more ions will pose additional challenges to
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# short-lived; it will quickly go back to so :math:`\left\lvert g \right\rangle`,
```suggestion
# short-lived; it will quickly go back to :math:`\left\lvert g \right\rangle`,
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# energy gap. To understand how we would achieve a state superposition by
```suggestion
# energy gap. To understand how we would achieve a superposition by
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# the operator:
```suggestion
# the operator
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# :math:`S_-` are given by:
```suggestion
# :math:`S_-` are 
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# .. math:: S_+=\left( \begin{array}{cc} 0 & 0 \\ 1 & 0\end{array}\right) \qquad S_-=\left( \begin{array}{cc} 0 & 1 \\ 0 & 0\end{array}\right).
```suggestion
# .. math:: S_+=\left( \begin{array}{cc} 0 & 0 \\ 1 & 0\end{array}\right), \qquad S_-=\left( \begin{array}{cc} 0 & 1 \\ 0 & 0\end{array}\right).
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# change in time in the presence of external interactions. In quantum
```suggestion
# change with time in the presence of external interactions. In quantum
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# time-dependent state:
```suggestion
# depend on time, a qubit starting in state 
# :math:`\left\lvert g \right\rangle` will evolve into the following
# time-dependent state:
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# the duration of the interaction, which is controlled using *pulses*, i.e. short
```suggestion
# the duration of the interaction, which is controlled using *pulses*, i.e., short
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# :math:`\left\lvert e \right\rangle` in PennyLane) evolve under the action of this
Not sure what the difference here in the brackets is meant to be?

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# with different phases and durations yield the Hadamard gate.
```suggestion
# With this operator implemented, we can determine the sequences of pulses that
# produce common gates. For example,  there is a combination of pulses
# with different phases and durations that yield the Hadamard gate:
```
Suggested rephrasing to help with flow into the code example

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +#For comparison, we use the built-in Hadamard on PennyLane
```suggestion
#For comparison, we use the Hadamard built into PennyLane
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# Where we note that the desired gate was obtained up to a global phase factor.
```suggestion
# Note that the desired gate was obtained up to a global phase factor.
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# A similar excersise can be done for the T-gate:
```suggestion
# A similar exercise can be done for the :math:`T` gate:
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# This Pennylane code shows that we can obtain a Hadamard gate and a
```suggestion
# This PennyLane code shows that we can obtain a Hadamard gate and a
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# have a phase of :math:`\pi/2`. The Hadamard and T gates together can be used to
```suggestion
# :math:`T` gate using consecutive pulses with different times and phases. Namely,
# to get a Hadamard gate, we need five pulses, all of them with duration
# :math:`t=\frac{\pi}{2\Omega}`, where the second and the fourth pulse
# have a phase of :math:`\pi/2`. The Hadamard and :math:`T` gates together can be used to
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# see that timing and dephasing our laser pulses provide a versatile way
```suggestion
# see that timing and dephasing our laser pulses provides a versatile way
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +ax1.set(xlabel="time (in units of 1/Ω)", ylabel="Probability", title="Probability of measuring the excited state")
```suggestion
ax1.set(
    xlabel="time (in units of 1/Ω)", 
    ylabel="Probability", 
    title="Probability of measuring the excited state"
)
```
Line was too long and made a horizontal scroll bar; we generally like to avoid those so that all the code is always visible

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# .. math::  U(\Omega,\varphi,t)=\left( \begin{array}{cc} \cos\left(\frac{\Omega t}{2}\right) & -i\sin\left(\frac{\Omega t}{2}\right)e^{-i\varphi} \\ -i\sin\left(\frac{\Omega t}{2}\right)e^{i\varphi}
```suggestion
# .. math::  U(\Omega,\varphi,t)=\left( \begin{array}{cc} \cos\left(\frac{\Omega t}{2}\right) & -i\sin\left(\frac{\Omega t}{2}\right)e^{-i\varphi} \\ -i\sin\left(\frac{\Omega t}{2}\right)e^{i\varphi} & \cos\left(\frac{\Omega t}{2}\right)\end{array}\right),
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# :math:`\left\lvert g \right\rangle` and the chain in is in the state
```suggestion
# :math:`\left\lvert g \right\rangle` and the chain is in the state
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# **red sideband** transition
```suggestion
# **red sideband** transition:
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# Crucially, this frequency will do nothing if the ion-chain is in the
```suggestion
# Crucially, this frequency will do nothing if the ion chain is in the
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# If the light frequency is exactly :math:`\Delta`,
```suggestion
# state of zero energy. This seems counterintuitive, as
# if the light's frequency is exactly :math:`\Delta`,
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# .. figure:: ../demonstrations/trapped_ions/CZgate.png
Graphic is greatly improved!

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# to obtain the maximally entangled state
Adjust language here; currently reads "obtain the state x to obtain the state y"

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# derive how to obtain it from the Mølmer-Sørensen gate.
```suggestion
# determine how to obtain it from the Mølmer-Sørensen gate.
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# It is possible to obtain the CNOT gate by using a combination of
```suggestion
# It is possible to obtain do so using a combination of
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# is not free of problems. As we already saw, we can use two different
```suggestion
# of a problem thanks to optical pumping technology. However, problems remain for criterion 5.
# As we already saw, we can use two different
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# between different ion species: strategies like the Mølmer-Sørensen
```suggestion
# between different ion species; strategies like the Mølmer-Sørensen
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# collaborators [#QCCD2002]_ came up with an intelligent solution: if the size is a
```suggestion
# collaborators [#QCCD2002]_ came up with an intelligent solution: if size is a
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +#    is still in the earlier stages of development.
```suggestion
#    is still in the early stages of development.
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# architecture, this optical integration would equip us well to run
```suggestion
# architecture, this optical integration would well-equip us to run
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# in a time scale of micro to milliseconds. The energy difference between the ground and
```suggestion
# on a timescale of micro to milliseconds. The energy difference between the ground and
```

2021-11-08 22:35 UTC, glassnotes commented on demonstrations/tutorial_trapped_ions.py
> +# would like them to. It would we unwise to give up only because the challenge is
```suggestion
# would like them to. It would be unwise to give up only because the challenge is
```

2021-11-08 23:32 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +# :math:`\left\lvert e \right\rangle` in PennyLane) evolve under the action of this
Classic copy paste error

2021-11-08 23:36 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +# If the light frequency is exactly :math:`\Delta`,
Wanted to add a comment on the counterintuitiveness of this, but since the explanation is involved, I'll just leave it as it. I'll delete this sentence and move on to carrier frequencies.

2021-11-08 23:36 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_trapped_ions.py
> +# It is possible to obtain the CNOT gate by using a combination of
just "to do so" I guess

2021-11-09 19:35 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_trapped_ions.py
> +# If you're not yet participating in the carnival go to our
```suggestion
# If you're not yet participating in the PennyLane quantum carnival go to our 
```

2021-11-09 19:35 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_trapped_ions.py
> +#    :width: 300px
```suggestion
#    :width: 500px
```

2021-11-09 19:54 UTC, co9olguy commented on demonstrations/tutorial_trapped_ions.py
> +*Author: PennyLane dev team. Posted: XX November 2021. Last updated: 05 November 2021.*
```suggestion
*Author: PennyLane dev team. Posted: 10 November 2021. Last updated: 10 November 2021.*
```

2021-11-09 20:33 UTC, co9olguy approved these changes

2021-11-09 22:29 UTC, glassnotes approved these changes
:tada:

2021-11-10 00:32 UTC, merged