Added new community demo on hybrid NN and data-reuploading
PennyLaneAI/qml pull request #377
Opened 2021-11-10 21:38 UTC by CatalinaAlbornoz

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Add a thumbnail link to your tutorial in `beginner.rst`, or if a
      QML implementation, in `implementations.rst`.

- [ ] All QML tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2021-11-11 21:30 UTC, CatalinaAlbornoz commented on demos_community.yaml
> +  code: https://github.com/nsansen/Quantum-Machine-Learning/blob/main/Pennylane%20DEMO%20v2.ipynb
```suggestion
  code: https://github.com/nsansen/Quantum-Machine-Learning/blob/main/Pennylane%20DEMO%20v4.ipynb

```

2021-11-11 21:34 UTC, CatalinaAlbornoz commented on demos_community.yaml
> +    we create a new Qnode which is then used as a quantum layer in a Hybrid Neural Network.
```suggestion
    we create a new Qnode which is then used as a quantum layer in a Hybrid Neural Network.
    Note: this demo only runs on Python 3.6-3.8

```

2021-11-11 21:37 UTC, CatalinaAlbornoz commented on demos_community.yaml
> +    we create a new Qnode which is then used as a quantum layer in a Hybrid Neural Network.
```suggestion
    we create a new Qnode which is then used as a quantum layer in a Hybrid Neural Network.
    Note: this demo only works on Python version 3.7-3.8

```

2021-11-11 22:09 UTC, CatalinaAlbornoz commented on demos_community.yaml
> +    Note: this demo only works on Python version 3.7-3.8
```suggestion
    Note: this demo only works on Python versions 3.7-3.8.

```

2021-11-12 08:10 UTC, josh146 commented on demos_community.yaml
> +    Note: this demo only works on Python versions 3.7-3.8.
```suggestion
    We combine a standard Variational Classifier with a Data-Reuploading Classifier,
    and integrate the resulting QNode as a quantum layer in a Hybrid Neural Network.
```

- I removed the acronyms, since they are never used 😆 
- I don't think the note needs to be included here, if needed it can be mentioned at the top of the notebook.

2021-11-12 08:11 UTC, josh146 requested changes
Thanks @CatalinaAlbornoz! Have left one minor comment, but good to merge once done!

2021-11-12 15:01 UTC, josh146 approved these changes

2021-11-12 15:02 UTC, merged