[WIP] - Maximum Independent Set with DQVA ansatz
PennyLaneAI/qml pull request #386
Opened 2021-11-20 02:23 UTC by pangara

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Add a thumbnail link to your tutorial in `beginner.rst`, or if a
      QML implementation, in `implementations.rst`.

- [ ] All QML tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:** Maximum Independent Set with DQVA ansatz

**Summary:**

**Relevant references:** [Approaches to Constrained Quantum Approximate Optimization](https://arxiv.org/abs/2010.06660)

**Possible Drawbacks:**

**Related GitHub Issues:**

2022-01-19 21:26 UTC, anthayes92 requested changes
Amazing work @pangara! :sparkles: I certainly felt like I understand DQVA better after reading this demo!

I've left some comments and suggestions throughout and admittedly will need to come back to go through the code in more detail

2022-01-19 21:26 UTC, anthayes92 commented on demonstrations/tutorial_dqva_mis.py
> +# initialization. Furthermore, they propose the first useful application
```suggestion
# initialization. They also propose the first useful application
```

2022-01-19 22:39 UTC, pangara commented on demonstrations/tutorial_dqva_mis.py
> +#    b_i = \frac{1}{2} (1 - Z_i).
This is what is in the paper> The way I understood it was that Z_i is PauliZ applied to qubit i

2022-01-19 22:40 UTC, pangara commented on demonstrations/tutorial_dqva_mis.py
> +#    \tilde{b}_{v_j} = \frac{1+Z_{v_j}}{2}.
Same here> The way I understood it was that Z__v_j is PauliZ applied to qubit v_j

2022-01-20 22:00 UTC, angusjlowe commented on demonstrations/tutorial_dqva_mis.py
> +#    b_i = \frac{1}{2} (1 - Z_i).
I think Ant is referring to the fact that Z_i is an operator, whereas the notation you've chosen for the identity operation "1" could be confused for the integer 1. I know the paper does this, but I would second Ant's suggestion to change this to "I", perhaps.

2022-01-20 22:35 UTC, pangara commented on demonstrations/tutorial_dqva_mis.py
> +#    b_i = \frac{1}{2} (1 - Z_i).
Ah okay, I was being cautious, but yes.. its more unambiguous this way 👍

2022-01-20 22:38 UTC, pangara commented on demonstrations/tutorial_dqva_mis.py
> +# layer (even elements) and cost layer (odd elements).
Followed the structure of the authors here, but I can update it to two separate lists if that's easier.

2022-01-20 22:47 UTC, pangara commented on demonstrations/tutorial_dqva_mis.py
> +# 3. *Randomizing the ordering of the partial mixers* in the mixer unitaries
I could be wrong but I think it doesn't evolve outside the set of feasible states (when I was running the algorithm, I didn't see probabilities for the infeasible states). The paper doesn't mention anything in this regard as far as I know.

2022-01-20 22:58 UTC, pangara commented on demonstrations/tutorial_dqva_mis.py
> +# 2. By constructing the variational ansatz in a way such that constraints are satisfied at all times
Would it be the other way around? "unconstrained" add penalty terms to the cost Hamiltonian, and "constrained" is QAO-Ansatz style where complexity is added to the mixer Hamiltonian?

2022-01-21 00:59 UTC, angusjlowe commented on demonstrations/tutorial_dqva_mis.py
> +# 2. By constructing the variational ansatz in a way such that constraints are satisfied at all times
^What you have described is correct

2022-01-21 03:15 UTC, angusjlowe requested changes
Awesome work @pangara :) I just finished a pass through the first half of the tutorial and will leave additional comments soon.

2022-01-21 03:15 UTC, angusjlowe commented on demonstrations/tutorial_dqva_mis.py
> +# sets of states by focusing on unitaries rather than Hamiltonians. For
```suggestion
# Hadfield et al., extend QAOA by introducing the **Quantum
# Alternating Operator Ansatz (QAO-Ansatz)** which alternates between more
# general families of unitary operators. This has the potential to narrow the focus 
# of the algorithm on a more useful set of states. For
```

2022-01-21 03:15 UTC, angusjlowe commented on demonstrations/tutorial_dqva_mis.py
> +# time evolution under a fixed mixer Hamiltonian :math:`H_M`.
```suggestion
# example, a mixing operator :math:`U_M (\beta)` may not correspond to
# time evolution under a fixed mixer Hamiltonian :math:`H_M`.
```

2022-01-21 03:15 UTC, angusjlowe commented on demonstrations/tutorial_dqva_mis.py
> +# infeasible solutions). However, the QAO-Ansatz requires more complex
```suggestion
# The QAO-Ansatz can be used to guarantee that the state of the circuit never leaves the set of
# feasible states. In contrast, the penalty term approach requires an
# additional pruning step since the output can correspond to an
# infeasible solution. However, the QAO-Ansatz requires more complex
```

2022-01-21 15:38 UTC, anthayes92 requested changes
Code is looking really well structured @pangara! Easy to follow and learn from :mortar_board: 

I've added some suggestions, mainly tidying up. One of the bigger suggestion would be to add dosctrings for some of the bigger functions. This will help users if they wanted to re-use some of your code (which I'm sure they will!). I've left and example to follow in the code.

There's a couple more function toward the end of the demo I need to come back to review

2022-01-21 15:38 UTC, anthayes92 commented on demonstrations/tutorial_dqva_mis.py
> +
```suggestion
def mixer_layer(beta: List, ancilla: int, mixer_order: Optional[List]=None):
      """
      Builds the QAO-Ansatz mixer layer for max independent set problem using PennyLane operations
      
      Args:
          beta (List): A list of values for the mixing parameter
          ancilla (int): The qubit to be used as the ancilla
          mixer_order (Optional[List]=None): The desired permutation of the partial mixers
          
      Returns: 
          None
      """
```

2022-01-21 15:38 UTC, anthayes92 commented on demonstrations/tutorial_dqva_mis.py
> +
Note that this will require adding
```python
from typing import List, Optional
```
before calling these type hints

2022-01-21 15:38 UTC, anthayes92 commented on demonstrations/tutorial_dqva_mis.py
> +# layer (even elements) and cost layer (odd elements).
I think it's fine to leave as it is, was just wondering if there was an advantage I missed!

2022-01-21 15:38 UTC, anthayes92 commented on demonstrations/tutorial_dqva_mis.py
> +    assert len(params) == 2 * P, "Incorrect number of parameters!"
```suggestion
    if len(params) == 2 * P:
      raise Exception("Incorrect number of parameters!")
```

2022-01-21 15:38 UTC, anthayes92 commented on demonstrations/tutorial_dqva_mis.py
> +    assert len(params) == 2 * P, "Incorrect number of parameters!"
Seems a bit more natural to raise an exception here

2022-01-21 15:38 UTC, anthayes92 commented on demonstrations/tutorial_dqva_mis.py
> +    cur_init_state = init_state
```suggestion
    best_indset = best_init_state = cur_init_state = init_state
```

2022-01-21 15:38 UTC, anthayes92 commented on demonstrations/tutorial_dqva_mis.py
> +print("Init string: {}, Best MIS: {}".format("".join(base_str), out[0]))
```suggestion
print(f"Init string: {base_str}, Best MIS: {out[0]}")
```

2022-01-21 15:38 UTC, anthayes92 commented on demonstrations/tutorial_dqva_mis.py
> +    print("Init string: {}, Best MIS: {}".format("".join(init_str), out[0]))
```suggestion
    print(f"Init string: {init_str}, Best MIS: {out[0]}")
```

2022-01-21 15:38 UTC, anthayes92 commented on demonstrations/tutorial_dqva_mis.py
> +            )
```suggestion
            print(
                f"Start round {mixer_round}.{inner_round}, Initial state = {cur_init_state}"
            )
```

2022-01-21 15:38 UTC, anthayes92 commented on demonstrations/tutorial_dqva_mis.py
> +            )
Just an aesthetic preference for [f-strings](https://www.geeksforgeeks.org/formatted-string-literals-f-strings-python/)

2022-01-21 15:38 UTC, anthayes92 commented on demonstrations/tutorial_dqva_mis.py
> +            )
```suggestion
            print(
                f"\tFound new independent set: {best_indset}, Hamming weight = {new_hamming_weight}"
            )
```

2022-01-21 15:38 UTC, anthayes92 commented on demonstrations/tutorial_dqva_mis.py
> +            # print (top_counts)
```suggestion
```

2022-01-23 02:06 UTC, angusjlowe requested changes
Second pass, still more comments to come!

2022-01-23 02:06 UTC, angusjlowe commented on demonstrations/tutorial_dqva_mis.py
> +# :math:`N`.
I know this is inherited from the paper as well, but this notation doesn't really make sense to me. (I can infer the meaning, but not ideal to have to do that.)

2022-01-24 20:18 UTC, anthayes92 requested changes
Final few suggestion on the code have been added, the main suggestion being to break down some of the code that gets repeated into smaller helper functions that can be re-used. 

The logic within the code is looking fantastic, amazing work @pangara :raised_hands:

2022-01-24 20:18 UTC, anthayes92 commented on demonstrations/tutorial_dqva_mis.py
> +    return best_indset, best_params, best_init_state, best_perm
This function uses a lot of the same code that `solve_mis_qaoa` uses on line `363`. Again we could think abut creating smaller functions to be reused here. The above examples of helper function suggestions can be used as a guide here :smiley:  

This may also have the bonus of breaking up these mis solver functions into smaller digestible pieces

2022-01-24 20:18 UTC, anthayes92 commented on demonstrations/tutorial_dqva_mis.py
> +    print("Init string: {}, Best MIS: {}".format("".join(init_str), out[0]))
```suggestion
    print(f"Init string: {init_str}, Best MIS: {out[0]}")
```

2022-01-24 20:18 UTC, anthayes92 commented on demonstrations/tutorial_dqva_mis.py
> +all_init_strs = []
```suggestion
```

2022-01-24 20:18 UTC, anthayes92 commented on demonstrations/tutorial_dqva_mis.py
> +all_init_strs = []
unused variable

2022-01-24 20:18 UTC, anthayes92 commented on demonstrations/tutorial_dqva_mis.py
> +    print()
This could be made into a function since it is used again after using DQVA to solve MIS on line `754`

2022-01-26 19:47 UTC, pangara commented on demonstrations/tutorial_dqva_mis.py
> +def mixer_layer(beta: List, ancilla: int, mixer_order: Optional[List]=None):
```suggestion
def mixer_layer(beta, ancilla, mixer_order):
```

2022-01-26 20:35 UTC, angusjlowe commented on demonstrations/tutorial_dqva_mis.py
> +# from classical minimization of the cost function using gradient descent:
```suggestion
# permutations. To evaluate the cost function ``f``, the expectation value
# :math:`\langle C_{obj}\rangle is obtained by running the probability circuit 
# and calculating the average Hamming weight. In each iteration, an
# ansatz is constructed based on the mixer order and the optimal parameters
# are determined by a classical minimization of the cost function using gradient descent.
```

2022-01-26 20:35 UTC, angusjlowe commented on demonstrations/tutorial_dqva_mis.py
> +#
Would suggest removing this, or mentioning that the function f(\beta,\gamma) is defined to be this quantity earlier.

2022-01-26 20:35 UTC, angusjlowe commented on demonstrations/tutorial_dqva_mis.py
> +# We will now formulate the MIS using the DQVA Ansatz [#Saleem2020]. The cost function
The reference "[#Saleem2020]" doesn't seem to be working on my end.

2022-01-26 20:35 UTC, angusjlowe commented on demonstrations/tutorial_dqva_mis.py
> +# where :math:`k = 1, 2 \cdots p`.
```suggestion
# where :math:`k = 1, 2, \dots, p`.
```

2022-01-26 20:35 UTC, angusjlowe commented on demonstrations/tutorial_dqva_mis.py
> +# a better Hamming weight is found. The number of randomizations is controlled via a hyperparameter.
Seems so on my end as well

2022-01-27 17:13 UTC, anthayes92 commented on demonstrations/tutorial_dqva_mis.py
> +@qml.qnode(dev)
Oh didn't notice! In what way is this not a real circuit?

2022-01-27 17:15 UTC, anthayes92 commented on demonstrations/tutorial_dqva_mis.py
> +# a better Hamming weight is found. The number of randomizations is controlled via a hyperparameter.
```suggestion
# 5. If no new Hamming weight is obtained, the partial mixers are randomized and steps 2 and 3 are repeated to check if
#     a better Hamming weight is found. The number of randomizations is controlled via a hyperparameter.
```

2022-01-31 18:14 UTC, pangara commented on demonstrations/tutorial_dqva_mis.py
> +@qml.qnode(dev)
Do you mean that because it is run on a simulator?

2022-02-03 19:18 UTC, pangara commented on demonstrations/tutorial_dqva_mis.py
> +    return True
This makes a lot of sense and is much cleaner! I will use this.

2022-02-03 21:22 UTC, pangara commented on demonstrations/tutorial_dqva_mis.py
> +    return best_indset, best_params, best_init_state, best_perm
I have made two helpers for this - hopefully it's better.  This is a long function!

2022-02-05 21:40 UTC, glassnotes reviewed
@pangara great to see this come together :tada: I've just done a quick pass, I didn't go thoroughly through all the math or code examples.

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +# Hadfield et al., extend QAOA by introducing the **Quantum
```suggestion
# Hadfield et al. extend QAOA by introducing the **Quantum
```

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +# For solving constrained combinatorial optimization problems such as maximal independent set (MIS)
```suggestion
# For solving constrained combinatorial optimization problems such as maximum independent set (MIS) 
```

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +# of partial mixers :math:`U_{M, x}(\beta)` which may not commute.
Here it would be helpful to describe, in a few words in parens, what a partial mixer is.

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +# Multi-Controlled Toffoli gates that require high connectivity between
```suggestion
# multi-controlled Toffoli gates that require high connectivity between
```

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +# 1. *Warm starting the optimization* by starting with an initial state that is a feasible state
The rendering of this firs bullet point looks odd:

![image](https://user-images.githubusercontent.com/2068515/152659207-cf759e2a-3b96-4447-8df7-4f80a258a0f3.png)

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +# --------------------------
```suggestion
# QAO-Ansatz and DQVA
# --------------------------
```
Make sure the --- line matches the line length of the above. This is not properly rendering as a section header

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +# Given a graph, :math:`G = (V, E)` where :math:`V` is the set of vertices
```suggestion
# Given a graph :math:`G = (V, E)` where :math:`V` is the set of vertices
```

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +# :math:`b = \{b_1, b_2, \cdots b_n\} \in \{0, 1\}^n`, where the i'th bit being one represents inclusion of the ith vertex in the set. This is convenient as the outputs of
```suggestion
# :math:`b = \{b_1, b_2, \cdots b_n\} \in \{0, 1\}^n`, where the i'th bit being 1 represents inclusion of the ith vertex in the set. This is convenient as the outputs of 
```
Check throughout and make usage of i'th consistent (have seen ith and $i$th other places).

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +# Here :math:`Z_i` is the Pauli-Z operator acting on the :math:`i`-th
Check consistency between Pauli-Z and PauliX, etc. throughout.

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +# calculates the Hamming weight of a given bitstring and ``is_indset``,
```suggestion
# calculates the Hamming weight of a given bitstring, and ``is_indset``,
```

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +def is_indset(bitstr:str, G: nx.Graph) -> bool:
Would be good to run the code through black to ensure that the formatting is consistent.

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +# :math:`H` and is parameterized by :math:`\gamma`:
```suggestion
# :math:`H`, and is parameterized by :math:`\gamma`:
```

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +        None
```suggestion
```

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +        None
Some of the docstrings include explicit parameter descriptions and some don't, recommend to make uniform.

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +# where P is the permutation's function of labels from :math:`1` to
```suggestion
# where P is the permutation's function of labels from :math:`1` to
```
Make p mathcal?

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +# In the figure above, a PauliX rotation is applied to qubit :math:`\vert i \rangle` between two multi-controlled Toffoli gates
```suggestion
# In the figure above, an :math:`X` rotation is applied to qubit :math:`\vert i \rangle` between two multi-controlled Toffoli gates
```

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +# We are now ready to build the mixer layer for the QAO-Ansatz by applying the
```suggestion
######################################################################
# We are now ready to build the mixer layer for the QAO-Ansatz by applying the
```
(presumably want this to be parto f the main text?)

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +# We are now ready to build the circuit consisting of alternating cost and
Rephrase to avoid repetition with previous sentences of text

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +            if bit == "1":
Could use `qml.BasisStatePreparation` here in lieu of the loop

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +def qaoa_ansatz(P: int, params: Optional[List]=[], init_state: Optional[str]=None, mixer_order: Optional[List]=None) -> None:
Line is too long; reformat (running through `black` with line length of about 90 should take care of it)

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +@qml.qnode(dev)
I don't quite understand the comment ehre :confused:

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +# :math:`\langle C_{obj}\rangle is obtained by running the probability circuit
```suggestion
# :math:`\langle C_{obj}\rangle` is obtained by running the probability circuit 
```

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +# We will also define a helper function that compares the independent sets
```suggestion

######################################################################
# We will also define a helper function that compares the independent sets 
```

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +# This is done by comparing the hamming weights of the bitstrings
```suggestion
# This is done by comparing the Hamming weights of the bitstrings 
```

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +def solve_mis_qaoa(init_state: str, P: Optional[int]=1, m: Optional[int]=1, mixer_order: Optional[List]=None,
Format header and docstring here.

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +    return best_indset, best_params, best_init_state, best_perm
This is a large amount of code and I lost track of what we were trying to do here; recommend to split into parts and have some more explanation throughout

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +        cur_permutation = np.random.permutation(list(graph.nodes)).tolist()
Set a seed for the random number generator to ensure reproducibility

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +# Starting with an all-zero initial string will give us an independent
Depending on how the randomness works out this may be confusing; in my local build, the all-zero start found an MIS of size 3, but the subsequent code block, not all of them did, and I had to scroll through a lot of output. Maybe for this case it would be better to streamline the output so that it only returns the final result of the loop  (like only indicate which string was the starting string and the best MIS it found)

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +# QAO-Ansatz and are allowed to be independent.
```suggestion
# QAO-Ansatz and are allowed to be independent:
```
Independent of what?

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +# In the DQVA, whenever the :math:`j`-th bit of the initial state is one,
```suggestion
# In the DQVA, whenever the :math:`j`-th bit of the initial state is 1,
```

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +def solve_mis_dqva(init_state: Optional[str], P: Optional[int]=1, m: Optional[int]=1, mixer_order: Optional[List]=None, threshold: Optional[float]=1e-5, cutoff: Optional[int]=1) -> Tuple[str, np.ndar
As a general comment, I had a hard time following the code blocks and outputs because there was just a lot of "stuff" in them (type hints, full docstrings, print statements, etc.) For a demo, there isn't usually full documentation unless there is something particularly unclear (e.g., parameters that weren't discussed in the text), since in a sense the prose is documenting what is being done.

2022-02-05 21:40 UTC, glassnotes commented on demonstrations/tutorial_dqva_mis.py
> +# stitching together solutions.
Nice conclusion :+1:

2022-02-08 20:13 UTC, angusjlowe commented on demonstrations/tutorial_dqva_mis.py
> +@qml.qnode(dev)
Sorry for the unclear wording -- the unitary operation is of course fine. What I mean to say is that returning the probabilities of obtaining the various outcomes by measuring in the computational basis corresponds to estimating the (noiseless) expectations of 2^n observables. I wanted to potentially flag this up for readers so as not to give the impression that this subroutine can be executed any more efficiently than a brute force search over every possible solution to the optimization problem, even with an ideal quantum computer... Note that this magic "compute distribution" subroutine is required to execute the proposed algorithm on real hardware -- it is not an artifact of the classical simulation being performed for the demo. @glassnotes @anthayes92 did you have any thoughts about what the appropriate disclaimer might look like here?

2022-02-08 20:30 UTC, angusjlowe commented on demonstrations/tutorial_dqva_mis.py
> +@qml.qnode(dev)
^Just a follow up -- contrary to my initial comment it seems like the original paper does indeed give the pseudocode in a way that does not manipulate the probabilities directly. Perhaps a simple comment like "this circuit can only be executed on a simulator, but it is also possible to run the algorithm on real hardware" will suffice.

2022-02-09 14:08 UTC, anthayes92 commented on demonstrations/tutorial_dqva_mis.py
> +# more than the number of nodes (the extra wire is an ancilla).
It would be useful to introduce why we need an ancilla wire here

2022-02-09 14:28 UTC, anthayes92 commented on demonstrations/tutorial_dqva_mis.py
> +@qml.qnode(dev)
Thanks for clarifying @angusjlowe! This sounds like a good idea to highlight that the probabilities are being obtained in using a different method to the original paper and doing this on hardware would be expensive!

2022-02-09 14:46 UTC, anthayes92 commented on demonstrations/tutorial_dqva_mis.py
> +def solve_mis_dqva(init_state: Optional[str], P: Optional[int]=1, m: Optional[int]=1, mixer_order: Optional[List]=None, threshold: Optional[float]=1e-5, cutoff: Optional[int]=1) -> Tuple[str, np.ndar
Ah so I actually advocated for docstrings and typehints but perhaps I was too quick to assume that this is makes things clearer for everyone! 

IMO typehints could be dropped but docstrings could be useful for re-usability (though not sure if this is the intention of demos). Happy to leave this to your best judgement.

2022-02-09 14:59 UTC, josh146 commented on demonstrations/tutorial_dqva_mis.py
> +def solve_mis_dqva(init_state: Optional[str], P: Optional[int]=1, m: Optional[int]=1, mixer_order: Optional[List]=None, threshold: Optional[float]=1e-5, cutoff: Optional[int]=1) -> Tuple[str, np.ndar
As @glassnotes notes, we generally avoid docstrings and typehints in demos 🙂 They can be a distraction from the content and code for readers that are not familiar with Python software development, and can in some cases hinder from the flow of the text

2025-01-15 21:27 UTC, JerryChen97 requested changes

2025-01-15 21:27 UTC, JerryChen97 commented on demonstrations/tutorial_dqva_mis.py
> +    )
It would be much better if we can update the call of `qml.MultiControlledX` to be compatible with latest interface here. See https://docs.pennylane.ai/en/stable/code/api/pennylane.MultiControlledX.html for more details.

Specifically, the following two features have been deprecated and will be soon removed:
 - string values of `control_values`
 - `control_wires`. Instead, we should specify `wires` to be control wire(s) followed by a single target wire where the operation acts on.

2025-08-01 16:18 UTC, Alan-eMartin commented
Hey @pangara,

As we transition our demo pipeline, we're closing PRs that haven't been updated in a while. Don't worry, the history is saved, and you can always reopen it if it's still relevant. We can help you transfer any changes to the new pipeline, or you can do it yourself once it's ready.

Feel free to reach out to the @PennyLaneAI/cloud-software team if you have any concerns.

2025-08-01 16:18 UTC, closed without merging