Removed tickets from trapped ions demo, adjoint diff demo and removed…
PennyLaneAI/qml pull request #395
Opened 2021-11-30 20:16 UTC by CatalinaAlbornoz

… tkt demo

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Add a thumbnail link to your tutorial in `beginner.rst`, or if a
      QML implementation, in `implementations.rst`.

- [ ] All QML tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2021-12-01 20:41 UTC, co9olguy requested changes

2021-12-01 20:41 UTC, co9olguy commented on demonstrations/tutorial_tkt.py
> -"""
Don't forget to remove the link to this "tutorial" from the `demos_getting-started.rst` file

2021-12-01 21:53 UTC, alvaro-at-xanadu approved these changes
All good! Agree with Nathan's reminder of deleting the relevant parts of the rst file.

2021-12-02 18:15 UTC, co9olguy approved these changes

2021-12-02 18:15 UTC, merged