[WIP] add tutorial for the differentiable HF solver
PennyLaneAI/qml pull request #399
Opened 2021-12-07 21:23 UTC by soranjh

**Title:**
Autodifferentiable Hartree-Fock calculations

**Summary:**
Adds a tutorial for using the differentiable Hartree-Fock solver. The tutorial explains the theory and showcases a workflow to jointly optimize circuit parameters, nuclear coordinates, and basis set parameters in a variational quantum eigensolver algorithm.

**Relevant references:**
https://arxiv.org/abs/2111.09967

**Possible Drawbacks:**
NA
**Related GitHub Issues:**
NA

2021-12-21 16:26 UTC, ixfoduap requested changes
Looking great! Fantastic job!

I left many comments but they are mostly minor suggestions.

I would like to prioritize fixing the checks that are currently failing so that I can also review the built demo in the documentation

2021-12-21 16:26 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +# `S1.alpha`, `S1.coeff` and `S1.r`, respectively. You can verify that both of the S1 and S2
```suggestion
# `S1.alpha`, `S1.coeff` and `S1.r`, respectively. You can verify that both of the `S1` and `S2`
```

2021-12-21 16:26 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +# This gives you a tuple of three integers, representing the exponents of the `x`, `y` and `z`
```suggestion
# This gives us a tuple of three integers, representing the exponents of the `x`, `y` and `z`
```

2021-12-21 16:26 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +# Note that the centres of the orbitals are those of the hydrogen atoms by default and are therefore
```suggestion
# The centres of the orbitals are those of the hydrogen atoms by default and are therefore
```
Note that you don't always have to use "note that" :wink:

2021-12-21 16:26 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +qml.hf.generate_overlap(S1, S2)([geometry[0], geometry[1]])
It may be good to define the overlap integral

2021-12-21 16:26 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +# You can verify that the overlap integral between two identical atomic orbitals is one. We can now
```suggestion
# You can verify that the overlap integral between two identical atomic orbitals is equal to one. We can now
```

2021-12-21 16:26 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +# Let's now do a cool thing and plot the atomic orbitals and their overlap. We can do it by using
```suggestion
# Let's now plot the atomic orbitals and their overlap. We can do it by using
```

2021-12-21 16:26 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +# the :func:`~.pennylane.hf.molecule.atomic_orbital` function. This function computes the actual
```suggestion
# the :func:`~.pennylane.hf.molecule.atomic_orbital` function, which computes the actual
```
to aovid repeated use of "function"

2021-12-21 16:26 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +S1 = mol.atomic_orbital(0)
Doesn't seem wise to also use `S1` here as the name for what is technically another object

2021-12-21 16:26 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +parameters in a variational quantum eigensolver algorithm. Let's get started!
It may be good to have an image somewhere in this introductory section

2021-12-21 16:26 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +mol.mo_coefficients = mol.mo_coefficients.T
Why is this line needed?

2021-12-21 16:26 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +# circuit parameters and the atomic coordinates are optimized simultaneously by using gradients
Maybe remove mention of autograd which seems unnecessary

2021-12-21 16:26 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +# to construct the exact ground state and the second set contains the atomic coordinates of the
```suggestion
# to construct the exact ground state. The second set contains the atomic coordinates of the
```

2021-12-21 16:26 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +# Notice that after 35 steps of optimization the forces on the atomic nuclei and the gradient of the
```suggestion
# After 35 steps of optimization the forces on the atomic nuclei and the gradient of the
```

2021-12-21 16:26 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +# optimized geometry at the full-CI level: :math:`-1.1373060483` Ha. You can print the optimized
Not clear if readers now what full-CI means. Maybe add a link or consider saying "exact diagonalization" instead

2021-12-21 16:26 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +# We are now ready to perform a full optimization where the circuit parameter, the atomic
```suggestion
# We are now ready to perform a full optimization where the circuit parameters, the nuclear
```
It should be nuclear coordinates and not atomic coordinates, right? The atom includes electrons too so I feel the coordinates of the atom are not well defined

2021-12-21 16:26 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +# basis functions. Can you think of other interesting molecular parameters that cab be optimized
```suggestion
# basis functions. Can you think of other interesting molecular parameters that can be optimized
```

2021-12-21 16:45 UTC, josh146 commented
I think the failure is potentially related to this: https://github.com/readthedocs/readthedocs.org/issues/8775

One way of fixing it could be pinning `setuptools<0.60` in the requirements file?

2021-12-21 23:06 UTC, soranjh commented
> I think the failure is potentially related to this: [readthedocs/readthedocs.org#8775](https://github.com/readthedocs/readthedocs.org/issues/8775)
> 
> One way of fixing it could be pinning `setuptools<0.60` in the requirements file?

Thanks @josh146.

2021-12-22 18:18 UTC, soranjh commented on demonstrations/tutorial_differentiable_HF.py
> +qml.hf.hf_energy(mol)(geometry)
Mentioned transform. There is  a link to the function with :func:`~.pennylane.hf.hf_energy`.

2021-12-22 18:18 UTC, soranjh commented on demonstrations/tutorial_differentiable_HF.py
> +# previously optimized at the Hartree-Fock level. You can use a different geometry and verify that
I thought it might be more interesting if the user discover this when the forces are computed.

2021-12-22 18:18 UTC, soranjh commented on demonstrations/tutorial_differentiable_HF.py
> +mol.mo_coefficients = mol.mo_coefficients.T
The natural way that the C matrix is obtained in our solver and also pyscf is such that the c_j values of mo_i are the columns of the matrix. The transpose just makes sure that they become rows of the matrix and can be accessed with one index in the array. We should probably modify [here](https://github.com/PennyLaneAI/pennylane/blob/deffcee1615687d74a25f4385dd1f097d0d7e9cd/pennylane/hf/molecule.py#L180) then no need to transpose it here.

2021-12-22 18:21 UTC, soranjh commented on demonstrations/tutorial_differentiable_HF.py
> +generate differentiable second-quantized molecular Hamiltonians in the fermionic and qubit basis.
Added the equations.

2021-12-22 18:26 UTC, soranjh commented on demonstrations/tutorial_differentiable_HF.py
> +parameters. This can be beneficial to solve problems such as molecular geometry optimization where
Modifies the intro according to these.

2021-12-24 15:10 UTC, ixfoduap requested changes
Amazing tutorial! Besides a few minor suggestions, I think only the following is needed:

- It would be great to have a figure in the begining of the tutorial. Maybe we can reproduce the last animation and tell the user they will learn how to perform calculations like that
- Some of the equations are appearing inside of a blue box in the rendered demo. Don't know why but should be fixed
- Some of the code print outs have a format that perhaps could be improved
- Text in code form, for example `SingleExcitation` is appearing in italics in the demo. Don't know why but also should be fixed

2021-12-24 15:10 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +# by passing the orbitals and the initial values of their centres to the
```suggestion
# between the atomic orbitals :math:`\chi`, by passing the orbitals and the initial values of their centres to the
```
Please check spacing after adding this suggestion

2021-12-24 15:10 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +grad(qml.hf.generate_overlap(S1, S2))([geometry[0], geometry[1]])
This prints out with a wide spacing for entries equal to zero, which requires scrolling horizontally to see the entire output. Can we fix this somehow?

2021-12-24 15:10 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +V2 = mol.atomic_orbital(1)
This is awesome!

2021-12-24 15:10 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +# Note that we only use the `DoubleExcitation` gate as the `SingleExcitation` ones can be neglected
I wonder why text in inverted commas like `SingleExcitation` is showing in italics rather than in the usual code form. This is happening throughout the demo. We should fix it

2021-12-24 15:10 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +#     The bonding molecular orbital of hydrogen visualized during a full geometry, circuit and
```suggestion
#     The bonding molecular orbital of hydrogen visualized during a full geometry, circuit, and
```
Oxford comma I think is helpful here

2021-12-24 15:10 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +#     Juan Miguel Arrazola, Soran Jahangiri, Alain Delgado, Jack Ceroni *et al.*, "Differentiable
This is showing with a (1,2), which I believe shouldn't be happening? Or is that normal?

2021-12-24 15:10 UTC, ixfoduap commented on .circleci/config.yml
> +            pip install pip "setuptools==50.3.1" cmake --upgrade
Why are these changes being made in this PR?

2021-12-24 15:10 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +        print(f'n: {n}, E: {energy(mol)(*args):.8f}, Force-max: {abs(forces).max():.8f}')
This printout begins with a strange `/home/circleci/project...`. Do we know why this is happening? Any way to remove it?

2021-12-24 16:57 UTC, agran2018 requested changes
Thank you @soranjh for the nice tutorial! Just left some suggestions.

2021-12-24 16:57 UTC, agran2018 commented on demonstrations/tutorial_differentiable_HF.py
> +principle increase the accuracy of the computed molecular electronic energy without increasing the
```suggestion
principle increase the accuracy of the computed energy without increasing the

```

2021-12-24 16:57 UTC, agran2018 commented on demonstrations/tutorial_differentiable_HF.py
> +implicit solvent effects or external potentials.
Totally optional:
Probably just say that "The joint optimization of the circuit and Hamiltonian
parameters can also be used when the chemical problem involves optimizing the parameters of external potentials."

2021-12-24 16:57 UTC, agran2018 commented on demonstrations/tutorial_differentiable_HF.py
> +over optimized molecular orbitals. These optimized orbitals are obtained by solving the Hartree-Fock
```suggestion
over optimized molecular orbitals that are obtained by solving the Hartree-Fock

```

2021-12-24 16:57 UTC, agran2018 commented on demonstrations/tutorial_differentiable_HF.py
> +and molecular orbitals, building Fock matrices, and solving the self-consistent Hartree-Fock
```suggestion
and molecular orbitals, building Fock matrices, and solving the self-consistent field

```

2021-12-24 16:57 UTC, agran2018 commented on demonstrations/tutorial_differentiable_HF.py
> +To get started, we need to define the atomic symbols and coordinates of the desired molecule. For
```suggestion
To get started, we need to define the atomic symbols and the nuclear coordinates of the molecule. For

```

2021-12-24 16:57 UTC, agran2018 commented on demonstrations/tutorial_differentiable_HF.py
> +the hydrogen molecule we define the symbols and geometry as
```suggestion
the hydrogen molecule we have

```

2021-12-24 16:57 UTC, agran2018 commented on demonstrations/tutorial_differentiable_HF.py
> +# parameters. We can now compute the Hartree-Fock energy and its gradient with respect to the atomic
```suggestion
# parameters. We can now compute the Hartree-Fock energy and its gradient with respect to the nuclear

```

2021-12-24 16:57 UTC, agran2018 commented on demonstrations/tutorial_differentiable_HF.py
> +# coordinates for the hydrogen molecule. To do that, we create a molecule object that stores all the
```suggestion
# coordinates. To do that, we create a molecule object that stores all the

```

2021-12-24 16:57 UTC, agran2018 commented on demonstrations/tutorial_differentiable_HF.py
> +# We now compute the gradient of the energy with respect to the atomic coordinates
I typically prefer use "nuclear" instead of "atomic" to match the terminology nuclear gradients, but this is just a preference. Please, feel free to disregard these suggestions if you like more "atomic".
```suggestion
# We now compute the gradient of the energy with respect to the nuclear coordinates

```

2021-12-24 16:57 UTC, agran2018 commented on demonstrations/tutorial_differentiable_HF.py
> +# the newly computed  gradients are not all zero.
```suggestion
# the newly computed gradients are not all zero.

```

2021-12-24 16:57 UTC, agran2018 commented on demonstrations/tutorial_differentiable_HF.py
> +# three contracted Gaussian functions. These basis functions can be accessed from the molecule
```suggestion
# three primitive Gaussian functions. These basis functions can be accessed from the molecule

```

2021-12-24 16:57 UTC, agran2018 commented on demonstrations/tutorial_differentiable_HF.py
> +#     \int \chi_\mu (r) \chi_\nu (r) dr
```suggestion
#     \int \chi_\mu^* (r) \chi_\nu (r) dr

```

2021-12-24 16:57 UTC, agran2018 commented on demonstrations/tutorial_differentiable_HF.py
> +# the :func:`~.pennylane.hf.molecule.atomic_orbital` function, which computes the actual
```suggestion
# the :func:`~.pennylane.hf.molecule.atomic_orbital` function, which evaluates

```

2021-12-24 16:57 UTC, agran2018 commented on demonstrations/tutorial_differentiable_HF.py
> +# value of the atomic orbital at a given coordinate. For instance, the value of the S orbital on the
```suggestion
# the atomic orbital at a given coordinate. For instance, the value of the S orbital on the

```

2021-12-24 16:57 UTC, agran2018 commented on demonstrations/tutorial_differentiable_HF.py
> +# We can compute the value of this orbital on different points along the `x` axis and plot it.
It sounds weird to me "computing the value of an orbital". 
```suggestion
# We can evaluate this orbital at different points along the `x` axis and plot it.

```

2021-12-24 16:57 UTC, agran2018 commented on demonstrations/tutorial_differentiable_HF.py
> +# to the circuit parameter and the atomic coordinates and update the parameters iteratively. Note
```suggestion
# to the circuit parameter and the nuclear coordinates and update the parameters iteratively. Note

```

2021-12-24 16:57 UTC, agran2018 commented on demonstrations/tutorial_differentiable_HF.py
> +# that the atomic coordinate gradients are simply the forces on the atomic nuclei.
```suggestion
# that the nuclear gradients are simply the forces on the atomic nuclei.

```

2021-12-24 19:04 UTC, soranjh commented on demonstrations/tutorial_differentiable_HF.py
> +#     Juan Miguel Arrazola, Soran Jahangiri, Alain Delgado, Jack Ceroni *et al.*, "Differentiable
This is normal, links to places where the ref is cited.

2021-12-24 22:04 UTC, agran2018 approved these changes
Very nice tutorial @soranjh with awesome plots!

2021-12-24 22:18 UTC, soranjh commented on demonstrations/tutorial_differentiable_HF.py
> +grad(qml.hf.generate_overlap(S1, S2))([geometry[0], geometry[1]])
Changed the print option to decrease the length. No sure why there is some space after zeros.

2021-12-24 22:21 UTC, soranjh commented on demonstrations/tutorial_differentiable_HF.py
> +        print(f'n: {n}, E: {energy(mol)(*args):.8f}, Force-max: {abs(forces).max():.8f}')
It also appears in the notebooks, need to dig down to see where autograd numpy crates the warning. It is harmless as far as our tests show.

2021-12-24 23:58 UTC, CatalinaAlbornoz reviewed
Hi Soran,

I think this will be a good guide for someone wanting to use the solver. It's very technical and slightly long but I believe it's well tailored to the public who will most likely read it, which will be people that know about quantum chemistry already.

I added a few comments but in general great job!

2021-12-24 23:58 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_differentiable_HF.py
> +# the :func:`~.pennylane.hf.molecule.atomic_orbital` function, which evaluates the atomic orbital at
The link to the docs of the atomic_orbital is not working.

2021-12-24 23:58 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_differentiable_HF.py
> +mol.mo_coefficients = mol.mo_coefficients.T
If you do keep the transpose then it's important to comment this line to explain what is happening here.

2021-12-24 23:58 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_differentiable_HF.py
> +# circuit parameter are both approaching zero and the energy of the molecule is that of the
```suggestion
# After 35 steps of optimization, the forces on the atomic nuclei and the gradient of the
# circuit parameter are both approaching zero, and the energy of the molecule is that of the

```

2021-12-24 23:58 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_differentiable_HF.py
> +# differentiable Hartree-Fock and subsequently VQE simulations. This feature provides two major
```suggestion
# This tutorial introduces an important feature of PennyLane that allows performing fully-differentiable
# Hartree-Fock and subsequently VQE simulations. This feature provides two major

```

2021-12-24 23:58 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_differentiable_HF.py
> +# of circuit and Hamiltonian parameter in applications such as VQE molecular geometry optimizations.
```suggestion
# of circuit and Hamiltonian parameters in applications such as VQE molecular geometry optimizations.

```

2022-01-17 19:20 UTC, ixfoduap approved these changes
I left a few suggestions, please address them before merging.

Thanks!

2022-01-17 19:20 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +Differentiable Hartree-Fock Solver
@soranjh It's ultimately up to you to decide, but I personally prefer just "Differentiable Hartree-Fock" for the title (I know Catalina suggested to add solver)

2022-01-17 19:20 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +molecular orbital and create images like this:
Technically, we don't really explain how to create images like this in the rest of the demo. Maybe rephrase to
> You will also learn how to visualize the atomic and molecular orbital, which could be sued to create images like this

2022-01-17 19:20 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +import pennylane.hf
why is this needed? I see use of `qml.hf` everywhere...

2022-01-17 19:20 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +# Hartree-Fock calculations. We plot the cross section of the bonding orbital on the ``x-y`` plane.
@soranjh Ultimately up to you, but you could consider using :math:`x` instead of ` x` for the corodinates x,y,z

2022-01-17 19:20 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +# rotation angles of the ``Excitation`` gates which are applied to the reference Hartree-Fock state
```suggestion
# rotation angles of the excitation gates which are applied to the reference Hartree-Fock state
```

2022-01-17 19:20 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +# Note that we only use the ``DoubleExcitation`` gate as the ``SingleExcitation`` ones can be
It would be nice to have a link to the documentation for these excitation gates

2022-01-17 19:20 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +        print(f'n: {n}, E: {energy(mol)(*args):.8f}, Force-max: {abs(forces).max():.8f}')
In the built demo page, there is a very long warning `/home/circleci/project/venv/lib/python3.7/site-packages/autograd/numpy/numpy_vjps.py:698: ComplexWarning: Casting complex values to real discards the imaginary part`
We should maybe take the real part of the energy, or do something else to avoid this warning being printed.

Same goes for the example below

2022-01-17 19:20 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +        print(f'n: {n}, E: {energy(mol)(*args):.8f}, Force-max: {abs(forces).max():.8f}')
Let's remove here the warning about casting complex numbers to real

2022-01-19 16:18 UTC, soranjh commented on demonstrations/tutorial_differentiable_HF.py
> +        print(f'n: {n}, E: {energy(mol)(*args):.8f}, Force-max: {abs(forces).max():.8f}')
I have found the way to fix it and will create either an issue or smuggle it in a PR. Copying here for the record:
This [line](https://github.com/PennyLaneAI/pennylane/blob/a19c744bba5eb1e45df56273d81bb0df90a472a6/pennylane/hf/hamiltonian.py#L250) should be replaced with:

```
coeffs = anp.array([0.0])
coeffs = coeffs + np.array([h_ferm[0][n]])
```

2022-04-22 15:16 UTC, ixfoduap requested changes
Demo looks great! Taking the opportunity to add some new improvements.

The most important one is that I think we should begin the demo with the last paragraph of the introduction, which is great and concise. Then the other paragraphs could be moved to a new section afterwards

2022-04-22 15:16 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +# principle leads to a larger number of qubits.
```suggestion
# means that we can reach a lower energy for hydrogen without increasing the basis set size, which
# would otherwise lead to a larger number of qubits.
```

2022-04-26 20:43 UTC, ixfoduap approved these changes
Approving pre-emptively, but please address the final comments I left

2022-04-26 20:43 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +[#arrazola2021]_. The Hartree-Fock module in PennyLane provides built-in methods for constructing
```suggestion
[#arrazola2021]_. The quantum chemistry module in PennyLane provides built-in methods for constructing
```
Maybe good to add a link to it too

2022-04-26 20:43 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +atomic and molecular orbital, which could be sued and create images like this:
```suggestion
atomic and molecular orbital, which can be used to create animations like this:
```

2022-04-26 20:43 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +# The Hartree-Fock energy can now be computed with the :func:`~.pennylane.hf.hf_energy` function
This link is not working for me

2022-04-26 20:43 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +# centres to the :func:`~.pennylane.qchem.overlap_integral` function. The centres of the orbitals
This link also not working for me

2022-04-26 20:43 UTC, ixfoduap commented on demonstrations/tutorial_differentiable_HF.py
> +# :func:`~.pennylane.qchem.molecular_hamiltonian` function.
This link also not working for me

2022-05-09 22:31 UTC, CatalinaAlbornoz reviewed
Added a few minor comments.

2022-05-09 22:31 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_differentiable_HF.py
> +# Hartree-Fock calculations. We plot the cross section of the bonding orbital on the :math:`x-y`
```suggestion
# Hartree-Fock calculations. We plot the cross-section of the bonding orbital on the :math:`x-y`

```

2022-05-09 22:32 UTC, josh146 commented on demonstrations/tutorial_differentiable_HF.py
> +`automatic differentiation <https://en.wikipedia.org/wiki/Automatic_differentiation>`_. We
@CatalinaAlbornoz it looks like your comments (here and below) might be introducing new lines unexpectedly!

2022-05-09 22:40 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_differentiable_HF.py
> +#     Structure Theory". Dover Publications, 1996.
```suggestion
#     Structure Theory". Dover Publications, 1996.

 ##############################################################################
  #.. bio:: Soran Jahangiri
  #    :photo: ../_static/avatar.webp
  #
  #    Soran Jahangiri is a quantum chemist working at Xanadu. His work is focused on developing and implementing quantum algorithms for chemistry applications.
```

2022-05-09 23:09 UTC, CatalinaAlbornoz reviewed
Updated bio and added author name on top

2022-05-09 23:09 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_differentiable_HF.py
> +  #    Soran Jahangiri is a quantum chemist working at Xanadu. His work is focused on developing and implementing quantum algorithms for chemistry applications.
```suggestion
#.. bio:: Soran Jahangiri
#    :photo: ../_static/Soran.png
#
#    Soran Jahangiri is a quantum chemist working at Xanadu. 
#    His work is focused on developing and implementing quantum algorithms for chemistry applications.
```

2022-05-09 23:09 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_differentiable_HF.py
> +*Author: PennyLane dev team. Posted: 9 May 2022. Last updated: 9 May 2022*
```suggestion
*Author: Soran Jahangiri. Posted: 9 May 2022. Last updated: 9 May 2022*
```

2022-05-09 23:18 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_differentiable_HF.py
> + ##############################################################################
```suggestion
##############################################################################
```

2022-05-09 23:27 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_differentiable_HF.py
> +#    His work is focused on developing and implementing quantum algorithms for chemistry applications.
```suggestion
#    Soran Jahangiri is a quantum chemist working at Xanadu. His work is focused on developing and implementing quantum algorithms for chemistry applications.
```

2022-05-09 23:36 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_differentiable_HF.py
> +
```suggestion
# About the author
# ----------

```

2022-05-10 01:31 UTC, merged