[WIP] add tutorial for qubit tapering
PennyLaneAI/qml pull request #413
Opened 2021-12-23 22:34 UTC by soranjh

**Title:**
Qubit tapering

**Summary:**
Adds a tutorial for using the qubit tapering functionality of PennyLane. The tutorial explains the theory and showcases a step-by-step workflow to generate symmetry operators, apply them to a molecular Hamiltonian such that it acts trivially on some qubits and taper-off those qubits by replacing them with a set of generated optimal eigenvalues. The resulting Hamiltonian acts on a fewer number of qubits. The process of reducing the number of qubits in the reference Hartree-Fock state is also explained.

**Relevant references:**
https://github.com/PennyLaneAI/adrs/blob/master/documents/051-qubit-reduction.rst
https://arxiv.org/abs/1701.08213
https://arxiv.org/abs/1910.14644

2022-01-17 19:59 UTC, ixfoduap requested changes
Run out of time to perform full review, but sharing some initial comments

2022-01-17 19:59 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +Qubit tapering with symmetries
Great title! Consider also just "Qubit tapering"

2022-01-17 19:59 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +required to prepare the trial wave function ansatz. In the context of quantum chemistry, this
```suggestion
required to represent wave functions. In the context of quantum chemistry, this
```

2022-01-17 19:59 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +A molecular Hamiltonian in the qubit basis is constructed as a linear combination of Pauli words
```suggestion
A molecular Hamiltonian in the qubit basis can be expressed as a linear combination of Pauli words
```

2022-01-17 19:59 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +.. math:: H = \sum_{i=1}^r c_i \eta_i
Why \eta_i? Consider using P_i instead, which is e.g. the notation in the white paper

2022-01-17 19:59 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +.. math:: H = \sum_{i=1}^r c_i \eta_i
Also, c_i could be h_i

2022-01-17 19:59 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +operator, on a set of qubits. This allows tapering-off those qubits from the Hamiltonian. We can
But it can also be acting with the same Pauli, no? Consider rephrasing it for more clarity.

It may be a good idea to have a simple example, which may involve a Hamiltonian that is not necessarily a molecular Hamiltonian, to illustrate this idea.

2022-01-17 19:59 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +to :math:`j`-th qubit and
```suggestion
to the :math:`j`-th qubit:
```

2022-01-17 19:59 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +.. math:: [H', \sigma_x^{q_j}] = 0.
Let's check the documentation and other demos for consistency on how to represent Pauli matrices. I feel we use X,Y,Z instead of sigma_x, sigma_y, sigma_z

2022-01-17 19:59 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +Recall that two commuting operators share an eigenbasis. This means that the eigenfunction of the
```suggestion
Recall that two commuting operators share an eigenbasis. This means that the eigenvectors of the
```

2022-01-17 19:59 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +transformed Hamiltonian :math:`H'` is also an eigenfunction of each of the :math:`\sigma_x^{q_j}`
```suggestion
transformed Hamiltonian :math:`H'` are also eigenvectors of each of the :math:`\sigma_x^{q_j}`
```

2022-01-17 19:59 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +:math:`\left \{ q_j \right \}, j \in \left \{ l, ..., k \right \}` qubits are eliminated.
Again, a short example here may be helpful

2022-01-17 19:59 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +The unitary operator :math:`U` can be constructed as a Clifford operator [#bravyi2017]_
Maybe nice to explain what a Clifford operator is, but it may be too long. Otherwise, adding a link for the reader that may not be familiar with Clifford operations

2022-01-17 19:59 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +The symmetry group of the Hamiltonian is defined as an abelian group of pauli words that commute
```suggestion
The symmetry group of the Hamiltonian is defined as an Abelian group of Pauli words that commute
```

2022-01-17 19:59 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +those elements of the group that can be linearly combined, along with their inverses, to create any
is it linearly combined? I recall generators can be used to obtain all other group members through multiplication

2022-01-17 19:59 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +from the binary matrix representation of the Hamiltonian [#bravyi2017]_ with the functions of the
What is the binary matrix representation? This may be good to explain in a couple of lines, possibly also with a simple example

2022-01-17 21:00 UTC, ixfoduap requested changes

2022-01-17 21:00 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +# of the Hamiltonian terms will act on the qubits :math:`0, 1` either with Identity or with a
what does "the qubits 0,1" mean? Are these the labels of the qubits?

2022-01-17 21:00 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +# of its eigenvalues :math:`+1` or :math:`-1`. This results in a total number of :math:`2^n`
What is `n` here?

2022-01-17 21:00 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +# ground state energy of the molecule can be obtained from the reference Hartree-Fock state and the
As with the documentation, I feel that the concept of a "sector" is not very clear. 

I keep thinking that having an illustrative non-chemistry example at the beginning of the demo could be really helpful. The example could guide readers by showing all the mathematical steps.

I'm happy to chat about this in person if it's not so clear

2022-01-17 21:00 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +# The new Hamiltonian has only 9 non-zero terms acting on only 2 qubits! We can verify that the
Nice!

2022-01-17 21:00 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +print(np.linalg.eig(qml.utils.sparse_hamiltonian(H_tapered).toarray())[0])
This is great!

Maybe good to advertise this capability a bit more. For example, something like "In PennyLane, it's possible to build a sparse matrix representation of Hamiltonians. This allows us to directly diagonalize them to obtain exact values of the ground-state energies"

2022-01-17 21:00 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +# tapered Hartree-Fock state to build a circuit that prepares a variational qubit coupled-cluster
Interesting choice! How do we know that this is the ansatz you are defining in the circuit below? Even to me it's not so clear that this is a qubit coupled-cluster circuit

2022-01-17 21:00 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +# Hamiltonian and the tapered reference state is straightforward, however, building the wavefunction
```suggestion
# Hamiltonian and the tapered reference state is straightforward, but building the wavefunction
```

2022-01-17 21:00 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +# model for building the variational ansatz.
This argument regarding the ansatz is weak and a bit confusing... consider revising

2022-01-19 18:55 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +# applied to the qubits that we will be tapering-off from the Hamiltonian. In PennyLane, these are
It is modified for clarity.

2022-01-19 18:59 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +# of the Hamiltonian terms will act on the qubits :math:`0, 1` either with Identity or with a
Yes, modified the symbols to q_0, q_1.

2022-01-19 19:03 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +# of its eigenvalues :math:`+1` or :math:`-1`. This results in a total number of :math:`2^n`
Replaced with k for consistency. k is the number of tapered-off qubits

2022-01-19 19:04 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +# ground state energy of the molecule can be obtained from the reference Hartree-Fock state and the
The term "sector" is used in the literature, but we can use something else. I am open for suggestions. An example will be added.

2022-01-19 19:09 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +# qubits :math:`0, 1` by replacing the Pauli-X operators acting on those qubits with the optimal
Borrowed the expression from the literature. It basically means transforming `'XYZ'` to `+1 * 'IYZ' `,  assuming I understood the question correctly.

2022-01-20 20:52 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +from the binary matrix representation of the Hamiltonian [#bravyi2017]_ with the functions of the
I decided to remove this because explaining such details makes the intro very long.

2022-01-24 20:25 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +.. math:: H_{tapered} = \pm1 (Z_0 - I_0 + Y_0).
Love this example! Makes the concept so much clearer, at least to me

2022-01-24 20:25 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +of the transformed Hamiltonian commutes with each of the the Pauli-X operator applied to the
```suggestion
of the transformed Hamiltonian commutes with each of the Pauli-X operators applied to the
```

2022-01-24 20:25 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +set of tapered Hamiltonians, depending on which eigenvalue :math:`\pm 1` we chose for each
This makes it sounds as if we have a free choice over the eigenvalues, but in reality there are only some choices that are compatible with a true ground state. I think that's worth clarifying here

2022-01-24 20:25 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +sector: :math:`[+1, +1]`, :math:`[-1, +1]`, :math:`[+1, -1]`, :math:`[-1, -1].
```suggestion
qubits are eliminated. For instance, in the case of two tapered qubits, we have four eigenvalue
sectors: :math:`[+1, +1]`, :math:`[-1, +1]`, :math:`[+1, -1]`, :math:`[-1, -1].
```

2022-01-24 20:25 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +sector: :math:`[+1, +1]`, :math:`[-1, +1]`, :math:`[+1, -1]`, :math:`[-1, -1].
I wonder if we can continue with the example Hamiltonian from before and explain what is the correct sector in that case

2022-01-24 20:25 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +# :math:`q_0, q_1` either with Identity or with a Pauli-X operator. For each of these qubits, we can
```suggestion
# :math:`q_0, q_1` either with the Identity or with a Pauli-X operator. For each of these qubits, we can
```

2022-01-24 20:25 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +# tapered-off qubits. Each Hamiltonian corresponding to one eigenvalue sector. The optimal sector
```suggestion
# tapered-off qubits and each Hamiltonian corresponds to one eigenvalue sector. The optimal sector
```

2022-01-24 20:25 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +# corresponding to the ground state energy of the molecule can be obtained from the reference
```suggestion
# corresponding to the ground-state energy of the molecule can be obtained from the reference
```

2022-01-25 19:05 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +# tapered Hartree-Fock state to build a circuit that prepares a variational qubit coupled-cluster
Modified the text to not mention QCC which we cannot afford to explain in detail in this tutorial.

2022-01-25 19:06 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +# model for building the variational ansatz.
Revised the conclusions.

2022-01-25 19:56 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +sector: :math:`[+1, +1]`, :math:`[-1, +1]`, :math:`[+1, -1]`, :math:`[-1, -1].
Added the details for the example Hamiltonian.

2022-01-25 19:57 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +set of tapered Hamiltonians, depending on which eigenvalue :math:`\pm 1` we chose for each
Explained this more and also added the details for the example Hamiltonian above.

2022-01-26 20:14 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +.. math:: H|\psi \rangle = \pm1 (Z_0 I_1 - I_0 I_1 + Y_0 I_1)|\psi \rangle.
added: 

> where :math:`|\psi \rangle` is an eigenvector of :math:`H'`

2022-02-10 14:18 UTC, obliviateandsurrender requested changes
Overall looks solid to me. Just left a few suggestions and comments.

2022-02-10 14:18 UTC, obliviateandsurrender commented on demonstrations/tutorial_qubit_tapering.py
> +:math:`\left \{ j \right \}, j \in \left \{ l, ..., k \right \}` where :math:`j` is the qubit label.
I don't know why but the qubit indices \left{l,\ldots,\right} looks confusing to me at the first glance. Did you want to show a decreasing qubit sequence or just random/arbitrary?

2022-02-10 14:18 UTC, obliviateandsurrender commented on demonstrations/tutorial_qubit_tapering.py
> +the following.
By following did you mean to add some reference or the next paragraph?

2022-02-10 14:18 UTC, obliviateandsurrender commented on demonstrations/tutorial_qubit_tapering.py
> +generators, paulix_ops = qml.hf.generate_symmetries(H, len(H.wires))
I am assuming that these results are from the time before `taper_hf` PR was merged. There will be some slight changes because of a minor tweak I had introduced in selecting the generator to prefer tapering from the end instead of from the start.

2022-02-10 14:18 UTC, obliviateandsurrender commented on demonstrations/tutorial_qubit_tapering.py
> +    qml.BasisState(np.array([0, 0]), wires=H_tapered.wires)
This HF state will change because of the tweak I mention before.

2022-02-10 14:18 UTC, obliviateandsurrender commented on demonstrations/tutorial_qubit_tapering.py
> +# rotation gates [#ryabinkin2018] since we cannot use the typical particle-conserving gates
```suggestion
# rotation gates [#ryabinkin2018]_ since we cannot use the typical particle-conserving gates

```

2022-02-10 14:18 UTC, obliviateandsurrender commented on demonstrations/tutorial_qubit_tapering.py
> +    print(f'n: {n}, E: {energy:.8f} Ha')
Can we show the output for the VQE routine as well? If not complete, maybe every `kth` step.

2022-03-01 22:14 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +    qml.BasisState(np.array([0, 0]), wires=H_tapered.wires)
Corrected.

2022-03-01 22:14 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +generators, paulix_ops = qml.hf.generate_symmetries(H, len(H.wires))
Corrected.

2022-03-01 22:15 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +the following.
No, used "... in the following sections".

2022-03-01 22:15 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +:math:`\left \{ j \right \}, j \in \left \{ l, ..., k \right \}` where :math:`j` is the qubit label.
The order of the tapered qubits is arbitrary.

2022-03-01 22:15 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +The tapered Hamiltonian :math:`H_{tapered}` has the eigenvalues :math:`[-2.41421, 0.41421]` and
Added the eigenvalues of `H'`.

2022-03-21 11:08 UTC, obliviateandsurrender requested changes

2022-03-21 11:08 UTC, obliviateandsurrender commented on demonstrations/tutorial_qubit_tapering.py
> +that transforms :math:`H` to a new Hamiltonian :math:`H'` which has the same eigenvalues as
Can you cross-check whether all the eigenvalues remain conserved or a k-subset of it for a larger Hamiltonian other than the one shown in the example?

2022-03-21 11:08 UTC, obliviateandsurrender commented on demonstrations/tutorial_qubit_tapering.py
> +# .. [#bravyi2017]
The reference number looks weird in the build. Check that once.

2022-03-21 21:41 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +[#bravyi2017]_ [#setia2019]_.
We use this format in the other tutorials, used it here for consistency.

2022-03-21 21:44 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +that transforms :math:`H` to a new Hamiltonian :math:`H'` which has the same eigenvalues as
They have the same eigvals, see for example [here](https://arxiv.org/pdf/1701.08213.pdf), the line after Eq (59).

2022-03-21 21:45 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +# .. [#bravyi2017]
Yep, they are correct. The extra numbers are links to the text where the ref is cited.

2022-04-22 12:53 UTC, obliviateandsurrender requested changes
Looks good @soranjh. Just leaving a few suggestions.

2022-04-22 12:53 UTC, obliviateandsurrender commented on demonstrations/tutorial_qubit_tapering.py
> +the :func:`~.pennylane.qchem.symmetry_generators` function in PennyLane.
Maybe add the link to the function instead of just mentioning it.

2022-04-22 12:53 UTC, obliviateandsurrender commented on demonstrations/tutorial_qubit_tapering.py
> +print(f'generator: {generators[0]}, paulix_op: {paulixops[0]}')
```suggestion
for idx, generator in enumerate(generators):
    print(f'generator {idx+1}: {generator}, paulix_op: {paulixops[idx]}')
```

2022-04-22 12:53 UTC, obliviateandsurrender commented on demonstrations/tutorial_qubit_tapering.py
> +H_tapered = qml.taper(H, generators, paulixops, paulix_sector)
I just noticed an interesting feature that clicking this opens `qml.Hamiltonian`.

2022-04-22 12:53 UTC, obliviateandsurrender commented on demonstrations/tutorial_qubit_tapering.py
> +print(np.linalg.eig(qml.utils.sparse_hamiltonian(H).toarray())[0])
```suggestion
print("Energies of H\n", np.linalg.eig(qml.utils.sparse_hamiltonian(H).toarray())[0])

```

2022-04-22 12:53 UTC, obliviateandsurrender commented on demonstrations/tutorial_qubit_tapering.py
> +print(np.linalg.eig(qml.utils.sparse_hamiltonian(H_tapered).toarray())[0])
```suggestion
print(r"Energies of H_tapered\n", np.linalg.eig(qml.utils.sparse_hamiltonian(H_tapered).toarray())[0])

```

2022-04-22 12:53 UTC, obliviateandsurrender commented on demonstrations/tutorial_qubit_tapering.py
> +    print(f'n: {n}, E: {energy:.8f} Ha, Params: {params}')
```suggestion
    if n%2:
        print(f'n: {n}, E: {energy:.8f} Ha, Params: {params}')

```
Will reduce the block length.

2022-04-22 13:16 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +the :func:`~.pennylane.qchem.symmetry_generators` function in PennyLane.
There is a link: `:func:`~.pennylane.qchem.symmetry_generators``

2022-04-22 13:18 UTC, obliviateandsurrender commented on demonstrations/tutorial_qubit_tapering.py
> +the :func:`~.pennylane.qchem.symmetry_generators` function in PennyLane.
I can only see a highlight but not a link. 🤔

2022-04-22 13:40 UTC, josh146 commented on demonstrations/tutorial_qubit_tapering.py
> +the :func:`~.pennylane.qchem.symmetry_generators` function in PennyLane.
This _should_ be automatically linking 🤔 I wonder why it is not

2022-04-22 14:04 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +the :func:`~.pennylane.qchem.symmetry_generators` function in PennyLane.
The link seems to be automatically looking for the function in `https://pennylane.readthedocs.io/en/stable/` which doesn't have that function in that location.

2022-04-22 15:47 UTC, antalszava commented on demonstrations/tutorial_qubit_tapering.py
> +the :func:`~.pennylane.qchem.symmetry_generators` function in PennyLane.
Let me create an update.

2022-04-22 15:49 UTC, antalszava commented on demonstrations/tutorial_qubit_tapering.py
> +the :func:`~.pennylane.qchem.symmetry_generators` function in PennyLane.
Could someone jump on a review? https://github.com/PennyLaneAI/qml/pull/477/

2022-04-22 15:52 UTC, ixfoduap requested changes

2022-04-22 15:52 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +.. math:: H = \sum_{i=1}^r h_i P_i
```suggestion
.. math:: H = \sum_{i=1}^r h_i P_i,
```

2022-04-22 15:52 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +Identity operators acting on M qubits
```suggestion
identity operators acting on M qubits
```
here and elsewhere, there is no need to capitalize identity

2022-04-22 15:52 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +such that each :math:`\mu_i` term in the new Hamiltonian acts trivially, e.g., with an Identity
```suggestion
such that each :math:`\mu_i` term in the new Hamiltonian always acts trivially, e.g., with an identity
```

2022-04-22 15:52 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +ground state eigenvector of :math:`H'` is also an eigenvector of :math:`I_0 X_1` with eigenvalues
```suggestion
ground-state eigenvector of :math:`H'` is also an eigenvector of :math:`I_0 X_1` with eigenvalues
```

2022-04-22 15:52 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +.. math:: H' = (Z_0 I_1 - I_0 I_1 + Y_0 I_1) I_0 X_1
```suggestion
.. math:: H' = (Z_0 I_1 - I_0 I_1 + Y_0 I_1) I_0 X_1,
```

2022-04-22 15:52 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +:math:`[2.41421, -0.41421]` for the :math:`+1` and :math:`-1` eigenvalues, respectively. The
```suggestion
:math:`[2.41421, -0.41421]` depending on the value of the :math:`\pm 1` prefactor. The
```

2022-04-22 15:52 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +:math:`[2.41421356, -2.41421356,  0.41421356, -0.41421356]`
```suggestion
:math:`[2.41421356, -2.41421356,  0.41421356, -0.41421356]`, which are thus reproduced by the tapered Hamiltonian.
```

2022-04-22 15:52 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +operators applied to the :math:`j` qubit:
```suggestion
operators applied to the :math:`j`-th qubit:
```

2022-04-22 15:52 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +of the eigenvalues that corresponds to the ground-state. This has been explained in more details in
```suggestion
of the eigenvalues that corresponds to the ground state. This is explained in more details in
```
"ground-state" is a compound adjective, while ground state is a an adjective "ground" describing a noun "state"

2022-04-22 15:52 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +# :math:`q_2, q_3` either with the Identity or with a Pauli-X operator. For each of these qubits,
```suggestion
# :math:`q_2, q_3` either with the identity or with a Pauli-X operator. For each of these qubits,
```

2022-04-22 15:52 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +# configuration interaction (FCI) method. In PennyLane, it's possible to build a sparse matrix
I think this should be changed to make use of `qml.eigvals()`, right?

2022-04-22 15:52 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +# tapered Hamiltonian. It can be done with the :func:`~.pennylane.qchem.taper_hf`.
```suggestion
# tapered Hamiltonian. It can be done with the :func:`~.pennylane.qchem.taper_hf` function.
```

2022-04-22 15:52 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +# Finally, we can use the tapered Hamiltonian and the tapered references state to perform a VQE
```suggestion
# Finally, we can use the tapered Hamiltonian and the tapered reference state to perform a VQE
```

2022-04-22 15:52 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +# simulation and compute the ground state energy of the :math:`\textrm{HeH}^+` cation. We use the
```suggestion
# simulation and compute the ground-state energy of the :math:`\textrm{HeH}^+` cation. We use the
```

2022-04-22 15:52 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +# Molecular Hamiltonians posses symmetries that can be leveraged to the number of qubits required
```suggestion
# Molecular Hamiltonians posses symmetries that can be leveraged to reduce the number of qubits required
```

2022-04-22 15:52 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +# in quantum computing simulations. This tutorial introduces the PennyLane functionality that can
```suggestion
# in quantum computing simulations. This tutorial introduces PennyLane functionality that can
```

2022-04-22 16:34 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +the :func:`~.pennylane.qchem.symmetry_generators` function in PennyLane.
The link works now.

2022-04-22 16:53 UTC, josh146 commented on demonstrations/tutorial_qubit_tapering.py
> +the :func:`~.pennylane.qchem.symmetry_generators` function in PennyLane.
@antalszava I think this is independent of the cache :) the cache only avoids the `.py` -> `.rst` conversion, however the `.rst` -> `.html` (including inserting links) will always occur still.

2022-04-22 17:05 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +# configuration interaction (FCI) method. In PennyLane, it's possible to build a sparse matrix
Yes, modified.

2022-04-26 20:33 UTC, ixfoduap approved these changes
Demo is good to go!

Just please check a couple of links that for some reason are not working for me in the build

2022-04-26 20:33 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +# :func:`~.pennylane.qchem.optimal_sector` function
This link isn't working for me in the built docs

2022-04-26 20:33 UTC, ixfoduap commented on demonstrations/tutorial_qubit_tapering.py
> +# tapered Hamiltonian. It can be done with the :func:`~.pennylane.qchem.taper_hf` function.
This link is also not working for me

2022-04-27 15:30 UTC, obliviateandsurrender approved these changes
Just leaving the final set of suggestions. Thanks, @soranjh!

2022-04-27 15:30 UTC, obliviateandsurrender commented on demonstrations/tutorial_qubit_tapering.py
> +# The new Hamiltonian has only 9 non-zero terms acting on only 2 qubits! We can verify that the
```suggestion
# The new Hamiltonian has only nine non-zero terms acting on only two qubits! We can verify that the

```

2022-04-27 15:30 UTC, obliviateandsurrender commented on demonstrations/tutorial_qubit_tapering.py
> +# :func:`~.pennylane.qchem.optimal_sector` function
```suggestion
# :func:`~.pennylane.qchem.optimal_sector` function.

```

2022-05-13 16:19 UTC, CatalinaAlbornoz approved these changes

2022-05-13 16:46 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qubit_tapering.py
> +# ----------
```suggestion
# About the author
# -----------------
```

2022-05-13 17:14 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qubit_tapering.py
> +##############################################################################
```suggestion
#
# About the author
# ----------------
#
##############################################################################
```

2022-05-13 18:01 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qubit_tapering.py
> +#
```suggestion

```

2022-05-13 18:02 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qubit_tapering.py
> +# ----------------
```suggestion
# ----------------

```

2022-05-14 16:47 UTC, josh146 commented on demonstrations/tutorial_qubit_tapering.py
> +eigensolver (VQE). Several approaches have been developed to reduce the qubit requirements for
the VQE mention should be a hyperlink to the VQE tutorial :)
````suggestion
limitation hinders the treatment of large molecules with algorithms such as the :doc:`variational quantum
eigensolver (VQE) <tutorial_vqe>`. Several approaches have been developed to reduce the qubit requirements for
````

2022-05-14 16:48 UTC, josh146 commented on demonstrations/tutorial_qubit_tapering.py
> +coordinates.
Perhaps a good place to link to https://pennylane.ai/qml/demos/tutorial_quantum_chemistry.html.

2022-05-16 23:14 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qubit_tapering.py
> +In PennyLane, a molecular Hamiltonian can be created by specifying the atomic symbols and
```suggestion
In PennyLane, a :doc:`molecular Hamiltonian <tutorial_quantum_chemistry>` can be created by specifying the atomic symbols and
```

2022-05-16 23:24 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qubit_tapering.py
> +*Author: PennyLane dev team. Posted: 17 May 2022. Last updated: 17 May 2022*
```suggestion
*Author: Soran Jahangiri. Posted: 16 May 2022. Last updated: 16 May 2022*

```

2022-05-16 23:30 UTC, merged