Add Tensor Network Quantum Circuits Demo
PennyLaneAI/qml pull request #425
Opened 2022-02-16 22:24 UTC by DSGuala

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Add a thumbnail link to your tutorial in `beginner.rst`, or if a
      QML implementation, in `implementations.rst`.

- [ ] All QML tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2022-03-03 20:29 UTC, ixfoduap requested changes

2022-03-03 20:29 UTC, ixfoduap commented on demonstrations/tutorial_tn_circuits.py
> +Import PennyLane and Numpy
Here and throughout the demo: do not use headers such as

Build the circuit with PennyLane
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Leave this only for major section titles. Instead use regular text to guide the reader through what you are doing

2022-03-03 20:29 UTC, ixfoduap commented on demonstrations/tutorial_tn_circuits.py
> +# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
You could preface this better. Maybe something like saying that the first step is to define the circuit that will be used in each block

2022-03-03 20:29 UTC, ixfoduap commented on demonstrations/tutorial_tn_circuits.py
> +# ^^^^^^^^^^^^^^^^^^
remove

2022-03-03 20:29 UTC, ixfoduap commented on demonstrations/tutorial_tn_circuits.py
> +
**IMPORTANT:** The entire rest of this demo needs text to clearly explain what each part of the code is doing. Right now you are basically just adding text as if they were comments in a python file. Not good

I will henceforth review only the code itself

2022-03-03 20:29 UTC, ixfoduap commented on demonstrations/tutorial_tn_circuits.py
> +qml.draw_mpl(circuit)(weights)
Not sure if there's anything we can do, but the circuit image also looks really big

2022-03-03 20:29 UTC, ixfoduap commented on demonstrations/tutorial_tn_circuits.py
> +# Using the `qml.MPS` template we can easily change the block type, depth, and size. For example:
```suggestion
# Using the :class:`~.pennylane.MPS` template we can easily change the block type, depth, and size. For example:
```
Maybe it should be class:`~.pennylane.templates.MPS`. Either way, you can check other demos to see how we reference functions in the code so that in the demo, there is a built hyperlink to the function in the docs

2022-03-03 20:29 UTC, ixfoduap commented on demonstrations/tutorial_tn_circuits.py
> +def different_block(weights, wires):
You may have too many examples. Here, the circuit is at first glance very similar to the one before. Consider skipping right to the next one

2022-03-03 20:29 UTC, ixfoduap commented on demonstrations/tutorial_tn_circuits.py
> +*Author: PennyLane dev team. Last updated: 2 March 2022.*
It may be good to add your name explicitly, as well as potentially Esther and Shaoming. It's a nice way to credit them and place their BMW affiliation. We would of course ask them to review the demo

2022-03-03 20:29 UTC, ixfoduap commented on demonstrations/tutorial_tn_circuits.py
> +def deep_block(weights, wires):
Nice!

2022-03-03 20:29 UTC, ixfoduap commented on demonstrations/tutorial_tn_circuits.py
> +def block(weights,wires):
For this and all following circuits: **the CNOTs should not be placed at the beginning** since they do nothing when acting on the initial state |00..0>

2022-03-03 20:29 UTC, ixfoduap commented on demonstrations/tutorial_tn_circuits.py
> +##############################################################################
I like that you are changing different parameters to show how we can build different types of circuits. For at least on of these examples, maybe actually two, please define the circuit directly in terms of a template. Besides strongly entangling layers, I think that the SimplifiedTwoDesign could make a nice example

2022-03-03 20:29 UTC, ixfoduap commented on demonstrations/tutorial_tn_circuits.py
> +# Then we define a tree tensor quantum circuit that will learn to label these images
```suggestion
# Then we define a tree tensor network quantum circuit that will learn to label these images
```

2022-03-03 20:29 UTC, ixfoduap commented on demonstrations/tutorial_tn_circuits.py
> +def costfunc(params):
There has got to be a more elegant way to write this cost function. How would you do it if the dataset had millions of images?

2022-03-09 22:32 UTC, DSGuala commented on demonstrations/tutorial_tn_circuits.py
> +
This method follows how affiliations are written in papers. But I'm not sure it looks very good here. Let me know if there are any ideas.

2022-03-10 15:12 UTC, ixfoduap requested changes
Looking great! After you've addressed this round of suggestions, please open for further review. I expect only minor additional suggestions

2022-03-10 15:12 UTC, ixfoduap commented on demonstrations/tutorial_tn_circuits.py
> +fig, ax = qml.draw_mpl(circuit)(template_weights)
This doesn't look like an MPS to me... Is there a mistake? Or am I missing something? :thinking: Either way, it is currently confusing

2022-03-10 15:12 UTC, ixfoduap commented on demonstrations/tutorial_tn_circuits.py
> +# either *bars* or *stripes*.
```suggestion
# either bars or stripes.
```

2022-03-10 15:12 UTC, ixfoduap commented on demonstrations/tutorial_tn_circuits.py
> +# A successful quantum circuit should accept any image from the data set as input, process
It's weird to say "a successful quantum circuit". Consider rephrasing

2022-03-10 15:12 UTC, ixfoduap commented on demonstrations/tutorial_tn_circuits.py
> +# and black pixels a value of 0:
There is a lot of white space in the image below. Try to see if there is something you can do about it

2022-03-10 15:12 UTC, ixfoduap commented on demonstrations/tutorial_tn_circuits.py
> +# for one-dimensional data [#Huggins]_,
Don't justify the use of TTN, just state that we use it

2022-03-10 15:12 UTC, ixfoduap commented on demonstrations/tutorial_tn_circuits.py
> +# we can now show the full circuits and the resulting output for each image input.
```suggestion
# we can now show the full circuits and the resulting output for each image.
```

2022-03-10 21:31 UTC, chaeyeunpark commented on demonstrations/tutorial_tn_circuits.py
> +    return qml.expval(qml.PauliZ(wires=3))
It may be worth mentioning that the resulting circuit can be represented by MPS with bond dimension 2.

2022-03-10 21:31 UTC, chaeyeunpark commented on demonstrations/tutorial_tn_circuits.py
> +##############################################################################
The generated MPS here is slightly more complicated. As just cutting between [0,1] and [2,3] gives 4 CNOTs which generate 16 indices, one naively expect that we have bond dim=16. However, as each side of the circuit has only 2 qubits, it is possible to compress this to an MPS with bond dim=4. Mentioning all these details must confuse readers, but I would suggest saying (at least), something like "we expect higher bond dimension for the corresponding MPS of this circuit (than the above case)".

2022-03-10 21:37 UTC, chaeyeunpark commented
I also have a general comment. A large subclass of MPS is a unitary MPS and can be generated by applying a unitary gate sequentially on a qubit and a big ancilla system (whose dimension is equal to the bond dimension) (https://arxiv.org/pdf/quant-ph/0612101.pdf). However, it seems like we cannot simulate this scheme directly in Pennylane right now as we cannot mix a device with a qubit and a general `d` dimensional system (qudit). Still, as it is possible that we use `log_2(d)` qubits instead of `d` dimensional ancilla, it would be also interesting to see this workaround in any future.

2022-03-11 10:25 UTC, esthercruz commented on demonstrations/tutorial_tn_circuits.py
> +.. image:: ../demonstrations/tn_circuits/MPS_TTN_Circuit_Color.PNG
I agree. We should maybe say that every quantum circuit can be represented as a tensor network, with the bond dimension related to the depth of the circuit. Moreover, one can design the architecture of the circuit to have the same connectivity as some well known subclasses of tensor networks. Note that the connectivity of these subclasses is related to how entanglement is distributed and how correlations spread in your system. So one can try to leverage this fact by "shaping" the quantum circuit in this way, with the hope that it captures best the information you want to extract.  (a bit informal explanation but may give intuition).

2022-03-11 10:25 UTC, esthercruz commented on demonstrations/tutorial_tn_circuits.py
> +.. image:: ../demonstrations/tn_circuits/MPS_TTN_Circuit_Color.PNG
Of course usually the main motivation when representing quantum circuits as tensor networks is to actually simulate them more efficiently. In that case the connectivity is chosen accordingly to how the bond dimension increases the least when applying the gates. But that's not the (main) motivation here.

Maybe one could say something like: "The motivation to represent quantum circuits as TN is two-folded. First, if the depth of the circuit is not too large, tensor networks provide a way of simulating the circuits in a much more efficient way than usual state-based simulators. Second, we can leverage the fact that tensor networks are a very successful Ansatz for quantum many-body systems where interactions are local and correlations are short range. If the states that our quantum circuit is preparing exhibit some locality in the way information is distributed, then tensor networks architectures might be advantageous with respect to more general variational architectures." (feel free to ignore this proposal or modify it to your taste).

2022-03-11 10:29 UTC, esthercruz commented on demonstrations/tutorial_tn_circuits.py
> +.. image:: ../demonstrations/tn_circuits/MPS_TTN_Circuit_Color.PNG
> We should talk more about the correspondence between the TNs and the corresponding circuits. I'm not sure we're interpreting this correctly

I agree. We should maybe say that every quantum circuit can be represented as a tensor network, with the bond dimension related to the depth of the circuit. Moreover, one can design the architecture of the circuit to have the same connectivity as some well known subclasses of tensor networks. Note that the connectivity of these subclasses is related to how entanglement is distributed and how correlations spread in your system. So one can try to leverage this fact by "shaping" the quantum circuit in this way, with the hope that it captures best the information you want to extract. (a bit informal explanation but may give intuition).



Of course usually the main motivation when representing quantum circuits as tensor networks is to actually simulate them more efficiently. In that case the connectivity is chosen accordingly to how the bond dimension increases the least when applying the gates. But that's not the (main) motivation here.

Maybe one could say something like: "The motivation to represent quantum circuits as TN is two-folded. First, if the depth of the circuit is not too large, tensor networks provide a way of simulating the circuits in a much more efficient way than usual state-based simulators. Second, we can leverage the fact that tensor networks are a very successful Ansatz for quantum many-body systems where interactions are local and correlations are short range. If the states that our quantum circuit is preparing exhibit some locality in the way information is distributed, then tensor networks architectures might be advantageous with respect to more general variational architectures." (feel free to ignore this proposal or modify it to your taste).

2022-03-11 10:34 UTC, esthercruz commented on demonstrations/tutorial_tn_circuits.py
> +We call these **tensor-network quantum circuits**.
> We should talk more about the correspondence between the TNs and the corresponding circuits. I'm not sure we're interpreting this correctly

I agree. We should maybe say that every quantum circuit can be represented as a tensor network, with the bond dimension related to the depth of the circuit. Moreover, one can design the architecture of the circuit to have the same connectivity as some well known subclasses of tensor networks. Note that the connectivity of these subclasses is related to how entanglement is distributed and how correlations spread in your system. So one can try to leverage this fact by "shaping" the quantum circuit in this way, with the hope that it captures best the information you want to extract. (a bit informal explanation but may give intuition).



Of course usually the main motivation when representing quantum circuits as tensor networks is to actually simulate them more efficiently. In that case the connectivity is chosen accordingly to how the bond dimension increases the least when applying the gates. But that's not the (main) motivation here.

Maybe one could say something like: "The motivation to represent quantum circuits as TN is two-folded. First, if the depth of the circuit is not too large, tensor networks provide a way of simulating the circuits in a much more efficient way than usual state-based simulators. Second, we can leverage the fact that tensor networks are a very successful Ansatz for quantum many-body systems where interactions are local and correlations are short range. If the states that our quantum circuit is preparing exhibit some locality in the way information is distributed, then tensor networks architectures might be advantageous with respect to more general variational architectures." (feel free to ignore this proposal or modify it to your taste).

2022-03-11 18:57 UTC, DSGuala commented on demonstrations/tutorial_tn_circuits.py
> +##############################################################################
Thanks Chae-Yeun. I'm puzzling over this.
Grouping them as in the picture I attached should lead to bond dim=2.
![Temp](https://user-images.githubusercontent.com/67476785/157933867-34f0363f-8227-4def-a59c-e746ed4514a4.png)

2022-03-11 20:11 UTC, chaeyeunpark commented on demonstrations/tutorial_tn_circuits.py
> +##############################################################################
![bond_dim](https://user-images.githubusercontent.com/13266959/157951667-52ba8451-4d39-48f4-bb03-5f1be2bcf2c4.png)
Hi Diego, this is the way we need to cut to make it MPS. Your cut makes it a proper tensor network, but a tensor has 4 legs (instead of a maximum 3 for MPS cases).

2022-03-14 18:19 UTC, DSGuala commented on demonstrations/tutorial_tn_circuits.py
> +states [#orus]_.
Thanks! I went with "certain many-body quantum states".

2022-03-14 18:24 UTC, DSGuala commented on demonstrations/tutorial_tn_circuits.py
> +We call these **tensor-network quantum circuits**.
I ended up adding the first paragraph of this comment. It's a great explanation of tensor-network quantum circuits and why we would use them/ what we try to do with them.

I think the explanation of why we would want to represent quantum circuits as tensor networks is not necessary in this demo since we don't discuss how to simulate quantum circuits with tensor networks.

2022-03-14 20:40 UTC, chaeyeunpark commented on demonstrations/tutorial_tn_circuits.py
> +# would correspond to an MPS with a bond dimension of four.
I like this wider circuit example.

2022-03-16 18:02 UTC, ixfoduap commented on demonstrations/tutorial_tn_circuits.py
> +# this circuit has a higher bond dimension than the previous ones and
```suggestion
# appear near the beginning of the circuit. Furthermore,
# this circuit has a higher bond dimension than the previous ones and
```
check for spacing since I'm removing text, don't just accept the suggestion

2022-03-16 18:04 UTC, ixfoduap commented on demonstrations/tutorial_tn_circuits.py
> +# value of a :class:`~pennylane.PauliZ` measurement as the output
```suggestion
# value of a :class:`~pennylane.PauliZ` measurement as the output.
```
Attention to details!

2022-03-16 18:04 UTC, ixfoduap commented on demonstrations/tutorial_tn_circuits.py
> +# otherwise we label it bars. Based on these labels, we define a cost function to train the circuit.
```suggestion
# When the output of the above circuit is less than zero, we label the image "stripes",
# otherwise we label it "bars". Based on these labels, we define a cost function to train the circuit.
```

2022-03-16 18:06 UTC, ixfoduap commented on demonstrations/tutorial_tn_circuits.py
> +for image in BAS:
Could you mage the BAS images a bit smaller? If it's too much trouble, don't worry about it

2022-03-16 18:42 UTC, DSGuala commented on demonstrations/tutorial_tn_circuits.py
> +for image in BAS:
:mage:

2022-03-17 07:26 UTC, josh146 commented on demonstrations/tutorial_tn_circuits.py
> +as in Ref. [#Huggins]_. Tensor-network quantum circuits emulate the shape and connectivity of tensor networks such as matrix product states
Ah, I think this is because Sphinx < 3.0 inserts the extra square brackets I think, whereas Sphinx > 3 doesn't 🤔 or something along those lines (not entirely sure I got the version numbers correct)

2022-03-17 13:33 UTC, DSGuala commented on demonstrations/tutorial_tn_circuits.py
> +as in Ref. [#Huggins]_. Tensor-network quantum circuits emulate the shape and connectivity of tensor networks such as matrix product states
Great. I added the brackets manually. Thanks Josh!

2022-03-22 20:49 UTC, antalszava reviewed
Hi @DSGuala, a note on references: the plan would be to add a CSS rule for how references are handled in the repository (see #452) and hence a ref like `\[[#orus]_\]` could become `[#orus]_` once the relevant PR is merged.

2022-03-28 20:38 UTC, co9olguy commented on demonstrations/tutorial_tn_circuits.py
> +as in Ref. \[[#Huggins]_\]. Tensor-network quantum circuits emulate the shape and connectivity of tensor networks such as matrix product states
```suggestion
as in Ref. [#Huggins]_. Tensor-network quantum circuits emulate the shape and connectivity of tensor networks such as matrix product states 
```

2022-03-28 20:38 UTC, co9olguy commented on demonstrations/tutorial_tn_circuits.py
> +states \[[#orus]_\]. Every quantum circuit can be represented as a tensor network, with the bond
```suggestion
states [#orus]_. Every quantum circuit can be represented as a tensor network, with the bond
```

2022-03-28 21:39 UTC, DSGuala commented on demonstrations/tutorial_tn_circuits.py
> +states \[[#orus]_\]. Every quantum circuit can be represented as a tensor network, with the bond
Thanks Nathan!

2022-03-28 23:42 UTC, merged