Demo for Machine Learning with Classical Shadows
PennyLaneAI/qml pull request #450
Opened 2022-03-21 16:59 UTC by obliviateandsurrender

**Title:** Learning ground state of 2D antiferromagnetic Heisenberg model

**Summary:** Explains how classical shadow formalism can be used with classical machine learning for predicting ground state properties of a Heisenberg model.

**Relevant references:** Provably efficient machine learning for quantum many-body problems, [arXiv:2106.12627](https://arxiv.org/pdf/2106.12627.pdf) (2021)

2022-03-21 19:05 UTC, obliviateandsurrender commented on demonstrations/tutorial_ml_classical_shadows.py
> +def build_coupling_mat(Nr, Nc):
I am thinking of seeding the `np.random` in this function. Might be possible by using an additional argument `num_coup`, which would be the number of coupling matrix.

2022-03-21 19:08 UTC, obliviateandsurrender commented on demonstrations/tutorial_ml_classical_shadows.py
> +        coupling_mat = build_coupling_mat(Nr, Nc)
Seeding `build_coupling_mat` would make `build_dataset` reproducible. Right now it is generating a brand new dataset every time script is run.

2022-03-21 19:10 UTC, obliviateandsurrender commented on demonstrations/tutorial_ml_classical_shadows.py
> +bar.set_label(r"$C_{ij}$", fontsize=18, rotation=0)
Same as above.

2022-03-22 16:12 UTC, soranjh reviewed
The demo looks good @obliviateandsurrender. Before providing a detailed review, I have some general comments and questions. 

1. The amount of text/explanation could be increased and the connections between different sections could be improved. Overall, the ratio of text/code is low and the concepts/ideas/methods could be explained more.

2. Some of the functions could be, or better to be, compressed, for example `build_coupling_mat()` and `H()` where you might use list comprehensions or other tricks to shorten the codes. Same might apply to the other functions. Also, there are some repetitions in the code blocks, e.g., `circuit()`.

3. Some of the function and argument names could be more expressive or better explained in the text, for example I could not easily say what is `x` in `H(x)`.

4. What is the benefit of having three different Kernel functions? Can you just select the best and free some space for better explanations of the other parts/concepts?

5. Some of the figures do not have captions, which is not a big problem, but adding clear captions always helps.

2022-03-22 16:15 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +def build_coupling_mat(Nr, Nc):
I prefer having a seed.

2022-03-22 16:16 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +# :math:`T` by looking at the Fidelity :math:`\mathcal{F}` of the actual
Might define or link to the definition of Fidelity.

2022-03-22 16:24 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +bar.set_label(r"$C_{ij}$", fontsize=18, rotation=0)
You can bring it closer to the plot, see [here](https://stackoverflow.com/questions/13310594/positioning-the-colorbar), or reduce the figure size.

2022-03-22 20:47 UTC, antalszava commented
Hi @obliviateandsurrender, a note on references: the plan would be to add a CSS rule for how references are handled in the repository (see #452) and hence a ref like `[[#preskill]_]` would have to become `[#preskill]_` once the relevant PR is merged.

2022-03-23 22:37 UTC, ixfoduap requested changes
First part of my review, will continue tomorrow

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +In general, simulating an :math:`n`-qubit quantum mechanical system
I suggest removing these first sentences. The are cliche and not so relevant to the demo. Besides, shadows are not addressing the problem of simulation, but rather of classically representing states

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +estimate their properties. In the past, this challenge has been
I suggest starting this sentence with 
"The challenge of classically representing states of quantum systems has been recently addressed ..."

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +of a quantum system. Recently, it has been shown by Hsin-Yuan Huang et
```suggestion
of a quantum system. It was argued in Ref. [[#preskill]_] that combining...
```

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +machine learning enables using ML methods to efficiently predict
```suggestion
machine learning enables methods to efficiently predict
```

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +Hamiltonian, correlations functions, entanglement entropies, etc.
```suggestion
Hamiltonian, correlations functions, and entanglement entropies.
```
Since you're saying "such as" it's ok to give a few concrete examples. In general it's problematic to use "etc." since it makes the text sound vague. You'll hardly ever see it in scientific writing

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +In this demo, we combine classical shadow formalism with classical
I think we should explicitly mention that we are demoing the ideas from that paper?

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +the 2-D antiferromagnetic Heisenberg model. So let's get started!
```suggestion
the 2D antiferromagnetic Heisenberg model. So let's get started!
```

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +Building the 2-D Heisenberg Model
```suggestion
Building the 2D Heisenberg Model
```

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +.. math::  H = \sum_{\langle ij\rangle} J_{ij}(X_i X_j + Y_i Y_j + Z_i Z_j)
```suggestion
.. math::  H = \sum_{\langle ij\rangle} J_{ij}(X_i X_j + Y_i Y_j + Z_i Z_j) .
```

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +:math:`\sigma^{z}_{i}` and :math:`\sigma^{z}_{j}` and is sampled
The random sampling is not a property of the model, but rather of the class you will be studying. Be more precise in saying that we consider the family of Hamiltonians where each coupling is sampled randomly from [0,2]

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +import pennylane as qml
I recommend import libraries as they are being used. We've learned this leads to better understanding and cleaner presentation

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# To completely describe the model, we begin by defining the coupling
```suggestion
# We define the coupling
```

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +def build_coupling_mat(Nr, Nc):
Definitely add a seed that should fix the randomness throughout the entire demo

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +    """Build the coupling matrix for the 2-D spin lattice of Heisenberg Model"""
```suggestion
    """Build the coupling matrix for the 2D spin lattice of Heisenberg Model"""
```

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# :math:`N_c` present in the lattice. The total spins in the model will be
```suggestion
# :math:`N_c` present in the lattice. The total number of spins in the model will be
```

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +        for idx in range(num_spins):
why `ind` and `indx` instead of `i` and `j`, so we can more easily relate to the mathematical definition above?

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +.. math::  H = \sum_{\langle ij\rangle} J_{ij}(X_i X_j + Y_i Y_j + Z_i Z_j)
I'm not familiar with the notation `<ij>`. Does this mean sum over different `i,j`? If so, consider using `i<j` instead

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# Here we study the model with :math:`4` spins arranged on the nodes of a
```suggestion
# Here we study the model with four spins arranged on the nodes of a
```
It's good practice in writing to use words (four, seven) to denote small numbers. You can use numerals for larger numbers (17, 35)

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# build the coupling matrix using ``build_coupling_mat``.
```suggestion
# build the coupling matrix using our previously defined function
```

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +                    coupling_mat[idx][ind] = coupling_mat[ind][idx]
This seems unnecessarily complicated to me. Is there an easier way to implement this? :thinking:

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# the corresponding coupling matrix ``coupling_mat``.
```suggestion
# We can visualize the model by representing the coupling matrix as a ``networkx`` graph:
```

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +G = nx.from_numpy_matrix(np.matrix(coupling_mat), create_using=nx.DiGraph)
This looks very verbose, largely because of the long `coupling_mat` definition. How about something shorter, like `J` or maybe `J_mat`?

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +plt.show()
Super cool to show this :star_struck:

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +
It may be nice to print the Hamiltonian here

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# For a Heisenberg model, a propetry of particular interest is usally the
```suggestion
# For a Heisenberg model, a property of interest is the
```

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# two-body correlation matrix :math:`C`, whose each element :math:`C_{ij}`
```suggestion
# two-body correlation matrix :math:`C`, whose each elements :math:`C_{ij}`
```

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# is defined as the following expectation value of the following operator
```suggestion
# are defined as the following expectation value of the following operator
```

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# for each pair of spin :math:`\sigma^{z}_{i}` and :math:`\sigma^{z}_{j}`
I find this sentence confusing. I suggest adding two equations: the one you have defining the operator, then another one defining the matrix elements as expvals with respect to the ground state

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +    """Build correlation function operator :math:`C_{ij}` for Heisenberg Model"""
```suggestion
    """Build the correlation function operator :math:`C_{ij}` for Heisenberg Model"""
```

2022-03-23 22:37 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +for op in corr_function_op(1, 2):
Consider removing this; not sure it adds much

2022-03-24 21:33 UTC, ixfoduap reviewed
Left more comments, still need to go through the last part of the demo

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# model, we use ``circuit_oshot`` that prepares the ground state that we
I'm not a fan of referring to a circuit by the name you gave in its definition. Just refer to it more directly, e.g., we employ the circuit we defined before

But I'm confused, isn't this exactly the same as the circuit you defined above?

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +    qml.QubitStateVector(psi / np.linalg.norm(psi), wires=range(int(np.log2(len(psi)))))
Same as my previous comment: it may be cleaner to define the normalized state and number of wires outside this operation

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# Now, we build the function ``gen_class_shadow`` that would make
```suggestion
# Now, we build a function to make the
```

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# :math:`T` the classical shadows for the quantum state prepared by a
```suggestion
# :math:`T` classical shadows for the quantum state prepared by a
```

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# :math:`T` the classical shadows for the quantum state prepared by a
I think you may be using confusing terminlogy, here and above. Isn't the single measurement outcome a snapshot and the collection of T of them the shadow?

Prior you said single snapshot and complete snapshot, then here use classical shadow for a single snapshot...

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +    Build classical shadow state for the given N-qubit system using T copies of
Same, in a demo it's not so important to have docstrings since you explain already in text

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +    return meas_outcomes, unitary_ensmb
Super nice!

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +shadow[0][:5], shadow[1][:5]
This may be better as an actual print statement to clarify what the quantities are:
```python
print("First five measurement outcomes = ", shadow[0][:5])
print("First five measurement bases = ", shadow[0][:5])
```

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# n-qubit state :math:`\rho`:
```suggestion
# Furthermore, :math:`S_{T}` can be used to construct an approximation of
# the :math:`n`-qubit state :math:`\rho`:
```

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +    """Build the \sigma_T snapshot for reconstructing the quantum state
again, remove docstring

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +def shadow_state_reconst(shadow):
```suggestion
def shadow_state(shadow):
```

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# :math:`T` by looking at the Fidelity :math:`\mathcal{F}` of the actual
```suggestion
# :math:`T` by looking at the fidelity :math:`\mathcal{F}` of the actual
```

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# quantum state w.r.t the reconstructed quantum state from the classical
```suggestion
# quantum state with respect to the reconstructed quantum state from the classical
```
It's ok to be a bit informal in a demo, but the text should still read well, and abbreviations like w.r.t. are not great at that

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# exact.
It may be nice to add *one sentence* explaining what the blue region refers to. I assume it's a standard deviation around the mean?

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# evaluate expectation values for some localized observable
```suggestion
# evaluate expectation values :math:`\text{Tr}(O\sigma_T)` for some localized observable
```

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# using :math:`\text{Tr}(O\sigma_T)`. However, as shown above,
```suggestion
# However, as shown above,
```

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# value of :math:`\langle O \rangle` for each of these chunks.
```suggestion
# :math:`K` equally-sized groups and estimate the median of the mean
# value of :math:`\langle O \rangle` for each of these groups.
```

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +
Is this median of means really needed for this demo to work? Seems to me like a bit of overkill

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# Let us try to estimate the correlation matrix :math:`C` from the
Consider removing this part. The more interesting reconstruction of the correlation matrices will happen later with the ML prediction

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# There are multiple ways in which one can combine classical shadows and
```suggestion
# There are multiple ways in which we can combine classical shadows and
```

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# :math:`C_{ij}`:
```suggestion
# machine learning. This could include training a
# model to learn the classical representation of quantum systems
# based on some system parameter, estimating a property from such learned
# classical representations, or a combination of both. In our case, we
# consider the problem of using neural networks to learn
# the ground-state representation of the Heisenberg model Hamiltonian :math:`H(x_l)` from
# the coupling vector :math:`x_l` and predict the correlation functions
# :math:`C_{ij}`:
```

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# :math:`C_{ij}`:
What is the coupling vector? Do you mean the coupling matrix J? If so, it may be good to use $H(J)$ instead of just $H$ in the first equation defining this

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# Using the theory of infinite-width neural networks [[#neurtangkernel]_], we
I'm not sure about this terminology of infinite-width neural networks. Seems non-standard to me. Where did you pick it from? Why not just say kernel methods?

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# consider the following form of classical machine learning models:
```suggestion
# consider the following machine learning models:
```
no need to add classical every time

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# where :math:`\lambda > 0` is a regularization paramter in cases when
```suggestion
# where :math:`\lambda > 0` is a regularization parameter in cases when
```

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# evaluating:
```suggestion
# Similarly, estimating an expectation value on the predicted ground state
# :math:`\sigma_T(x_l)` using the trained ML model can then be done by
# evaluating:
```

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# .. math::  \text{Tr}(\hat{O} \hat{\sigma}_{N} (x)) = \sum_{l=1}^{N} \kappa(x, x_l)\text{Tr}(O\sigma_T (x_l)),
```suggestion
# .. math::  \text{Tr}(\hat{O} \hat{\sigma}_{N} (x)) = \sum_{l=1}^{N} \kappa(x, x_l)\text{Tr}(O\sigma_T (x_l)).
```

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# Here, we train the classical kernel-based ML models using :math:`N = 70`
```suggestion
# We train the classical kernel-based ML models using :math:`N = 70`
```

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# :math:`C_{ij}`.
It may be good to add a couple of sentences explaining why we use jax and stax

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# Traditional ML methods and techniques
```suggestion
# ML methods and techniques
```

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# correlation matrix :math:`C`, computed w.r.t ground-state obtained from
```suggestion
# correlation matrix :math:`C`, computed with respect to the ground-state obtained from
```

2022-03-24 21:33 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +        coupling_mat = build_coupling_mat(Nr, Nc)
Yep, please use a seed

2022-04-05 14:18 UTC, obliviateandsurrender commented on demonstrations/tutorial_ml_classical_shadows.py
> +######################################################################
Yes, I have added a link to the tutorial. It is also available in the sidebar as well.

2022-04-05 14:18 UTC, obliviateandsurrender commented on demonstrations/tutorial_ml_classical_shadows.py
> +
It's needed for estimating values of C_ij from the shadow state.

2022-04-05 16:26 UTC, obliviateandsurrender commented on demonstrations/tutorial_ml_classical_shadows.py
> +In general, simulating an :math:`n`-qubit quantum mechanical system
I have tried to begin the paragraph with something new. Let me know if that fits in better.

2022-04-05 16:29 UTC, obliviateandsurrender commented on demonstrations/tutorial_ml_classical_shadows.py
> +    observables = kwargs.pop("observable")
It was supposed to allow for the passing of observables as `kwargs`. Have removed it now for simplicity.

2022-04-05 16:30 UTC, obliviateandsurrender commented on demonstrations/tutorial_ml_classical_shadows.py
> +# :math:`C_{ij}`:
A coupling vector in simple terms is the flattened upper triangular matrix, i.e., [J_ij  for i < j].

2022-04-05 16:32 UTC, obliviateandsurrender commented on demonstrations/tutorial_ml_classical_shadows.py
> +# Using the theory of infinite-width neural networks [[#neurtangkernel]_], we
Well, the [paper](https://arxiv.org/pdf/2106.12627.pdf) itself discusses and focuses on using them.

2022-04-05 17:36 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +# :math:`X`, :math:`Y`, or :math:`Z` to yeild random :math:`n` pure product
```suggestion
# :math:`X`, :math:`Y`, or :math:`Z` to yield random :math:`n` pure product
```

2022-04-05 17:37 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +# correlation matrix :math:`C`, computed with resepct to ground-state
```suggestion
# correlation matrix :math:`C`, computed with respect to ground-state
```

2022-04-05 17:38 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +    """Builds dataset for Heisenberg model: X (copling vector), y (correlation matrix)"""
```suggestion
    """Builds dataset for Heisenberg model: X (coupling vector), y (correlation matrix)"""
```

2022-04-05 17:39 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +                            [estimate_shadow_obervable(shadow, o, k=k + 1) for o in corrs]
..._observable?

2022-04-05 17:39 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +def estimate_shadow_obervable(shadow, observable, k=10):
..._observable?

2022-04-05 17:43 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +# For Gaussian kernel, the hyperaparemeter
```suggestion
# For Gaussian kernel, the hyperparameter
```

2022-04-05 18:03 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +such as the expectation value of such as Hamiltonian, correlations functions, and entanglement
```suggestion
such as the expectation value of a Hamiltonian, correlations functions and entanglement
```

2022-04-05 18:03 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +system as density matrices becomes classically intractable as the number of classical bits
This sentence seems to be missing a part. Maybe something like:
"Storing and ... _is challenging because the_ density matrices become ..."

The term "as" is used too many (3) times in the sentence.

2022-04-05 18:03 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +recently addressed this challenge using classical shadow formalism, which allows one to build
... by using the ...

2022-04-05 19:06 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +    Combining machine learning and classical shadow
Is this the caption? Does not appear for me in the built version.

2022-04-05 19:06 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +computing its ground state properties, and computing its classical shadow. Finally, we demonstrate
For consistency: computing => compute

2022-04-05 19:06 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +We define a two-dimensional antiferromagnetic Heisenberg model on a square
We define ... as a square lattice where ...
Also, maybe mention that the antiferromagnetic nature is determined by the coupling constant.

2022-04-05 19:06 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +where :math:`N_s = N_r \times N_c` is the total number of spins present in the model.
total number of particles?

2022-04-05 19:06 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +def build_coupling_mats(num_mats, num_rows, num_cols):
Does this function do anything other than creating a hollow symmetric matrix of random numbers between 0 and 2? If no, why we need such a complex function for this simple task? Maybe something like this does the job?
```
R = np.random.uniform(low=0, high=2.0, size=(2, 2))
M = np.tril(R, -1) + np.tril(R, -1).T
```

2022-04-05 19:06 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +# correlation function :math:`C_ij`, which for a pair of spins :math:`\sigma^{z}_{i}`
```suggestion
# correlation function :math:`C_{ij}`, which for a pair of spins :math:`\sigma^{z}_{i}`
```

2022-04-05 19:06 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +def corr_function_op(i, j):
\frac{1}{3} is missing or introduced elsewhere?

2022-04-05 19:06 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +fig, ax = plt.subplots(1, 1, figsize=(6, 6))
Maybe having a caption helps?

2022-04-05 19:06 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +# of the underlying :math:`n`-qubit state :math:`\rho` by averaging over \sigma_t:
```suggestion
# of the underlying :math:`n`-qubit state :math:`\rho` by averaging over :math:`\sigma_t`:
```

2022-04-05 19:10 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +    meas_outcomes = np.zeros((num_shadows, num_qubits))
What _meas_ in the parameter name represents?

2022-04-05 19:13 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +# effective with on an average higher fidelity values (orange) and lower variance (blue)
```suggestion
# effective with average higher fidelity values (orange) and lower variance (blue)
```

2022-04-05 19:15 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +# observable :math:`O = \bigotimes_{i}^{n} P_i`, where :math:`P_i \in \{I, X, Y, Z\}`
```suggestion
# observable :math:`O = \bigotimes_{i}^{n} P_i`, where :math:`P_i \in \{I, X, Y, Z\}`.
```

2022-04-05 19:21 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +# Once again, we visualize the :math:`C^{\prime}` as an image for comparing
Comparing the two images is not very informative. Maybe plotting some kind of error or deviation between the values of C and C' is more helpful.

2022-04-05 19:35 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +# randomly chosen value of coupling matrices :math:`J` with
Not sure I understood what N is here. Is it 70 different J matrices?

2022-04-05 19:35 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +# takes input as the size of the dataset (``num_points``), the topology of
```suggestion
# takes as input the size of the dataset (``num_points``), the topology of
```

2022-04-05 19:43 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +# .. math::  k(x, x^{\prime}) = \sum_{i\neq j}\sum_{k_i=-5}^{5}\sum_{k_j=-5}^{5} \cos{\big(\pi(k_i(x_i-x_i^{\prime}) + k_j(x_j-x_j^{\prime}))\big)} \tag{Dirichlet Kernel}
```suggestion

```

2022-04-05 19:44 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +# Dirichlet kernel is motivated by writing the :math:`\text{k}^{th}`
Better to bring the equation after this line.

2022-04-05 19:57 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +# is chosen to be the inverse of the average distance :math:`x_i` and
What does distance mean here? x is not just the correlation vector?

2022-04-05 19:58 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +# of the mentioned kernel:
```suggestion
# of the mentioned kernels:
```

2022-04-05 20:00 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +# .. math::  k(x, x^{\prime}) = \sum_{i\neq j}\sum_{k_i=-5}^{5}\sum_{k_j=-5}^{5} \cos{\big(\pi(k_i(x_i-x_i^{\prime}) + k_j(x_j-x_j^{\prime}))\big)} \tag{Dirichlet Kernel}
Is it common to have `k` for defining different parameters here?

2022-04-05 20:02 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +# partial sum of the Fourier series of function :math:`f` as a
Does `f` need to be defined here?

2022-04-05 20:09 UTC, soranjh requested changes
Thanks @obliviateandsurrender. Left some detailed comments and suggestions. Two general points:
1. Please check for the consistency in using "^" for operators.
2. You might consider _not_ using the [serial comma](https://en.wikipedia.org/wiki/Serial_comma) in the demo.

2022-04-06 04:21 UTC, obliviateandsurrender commented on demonstrations/tutorial_ml_classical_shadows.py
> +system as density matrices becomes classically intractable as the number of classical bits
Updated.

2022-04-06 04:40 UTC, obliviateandsurrender commented on demonstrations/tutorial_ml_classical_shadows.py
> +def build_coupling_mats(num_mats, num_rows, num_cols):
It makes a symmetric matrix based on the couplings present in the `Nr*Nc` system. Only the adjacent spin particles have couplings between them and therefore there are spin particles among which coupling is zero. For example, in (2,2) the latter would be the diagonally opposite ones. I made the function because I didn't want to hardcode it for the `(2,2) system`, rather have a function that outputs the correct generalized coupling matrix for every pair.

2022-04-06 04:44 UTC, obliviateandsurrender commented on demonstrations/tutorial_ml_classical_shadows.py
> +def corr_function_op(i, j):
Included explicitly when the function is called.

2022-04-06 04:44 UTC, obliviateandsurrender commented on demonstrations/tutorial_ml_classical_shadows.py
> +    Combining machine learning and classical shadow
Should be visible now.

2022-04-06 04:45 UTC, obliviateandsurrender commented on demonstrations/tutorial_ml_classical_shadows.py
> +    meas_outcomes = np.zeros((num_shadows, num_qubits))
"meas"urement_outcomes

2022-04-06 05:05 UTC, obliviateandsurrender commented on demonstrations/tutorial_ml_classical_shadows.py
> +# Once again, we visualize the :math:`C^{\prime}` as an image for comparing
Good thought! I am now plotting the deviations instead of `C'`.

2022-04-06 05:51 UTC, obliviateandsurrender commented on demonstrations/tutorial_ml_classical_shadows.py
> +# randomly chosen value of coupling matrices :math:`J` with
Yes.

2022-04-06 06:51 UTC, obliviateandsurrender commented on demonstrations/tutorial_ml_classical_shadows.py
> +# is chosen to be the inverse of the average distance :math:`x_i` and
Euclidean distance.

2022-04-06 06:58 UTC, obliviateandsurrender commented on demonstrations/tutorial_ml_classical_shadows.py
> +fig, ax = plt.subplots(1, 1, figsize=(6, 6))
I have added a figure title now.

2022-04-06 06:59 UTC, obliviateandsurrender commented on demonstrations/tutorial_ml_classical_shadows.py
> +# partial sum of the Fourier series of function :math:`f` as a
Not sure. I think it could be any function `f` with period 2pi.

2022-04-06 09:12 UTC, obliviateandsurrender commented on demonstrations/tutorial_ml_classical_shadows.py
> +# .. math::  k(x, x^{\prime}) = \sum_{i\neq j}\sum_{k_i=-5}^{5}\sum_{k_j=-5}^{5} \cos{\big(\pi(k_i(x_i-x_i^{\prime}) + k_j(x_j-x_j^{\prime}))\big)} \tag{Dirichlet Kernel}
Yes, that's what they use in the [paper](https://arxiv.org/pdf/2203.17181.pdf) (eq D10). Additionally, I saw the same in some lecture notes as well.

2022-04-06 14:37 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +            np.sum(np.array([estimate_shadow_obervable(shadow, o, k=k + 1) for o in corrs]))
```suggestion
            np.sum(np.array([estimate_shadow_observable(shadow, o, k=k + 1) for o in corrs]))
```

2022-04-06 14:37 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +                            [estimate_shadow_obervable(shadow, o, k=k + 1) for o in corrs]
```suggestion
                            [estimate_shadow_observable(shadow, o, k=k + 1) for o in corrs]
```

2022-04-06 22:51 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +    meas_outcomes = np.zeros((num_shadows, num_qubits))
Might consider using `measurement_outcomes`.

2022-04-06 22:51 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +# is chosen to be the inverse of the average distance :math:`x_i` and
Maybe use different notations then? (not `x` for both)

2022-04-06 22:51 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +# partial sum of the Fourier series of function :math:`f` as a
If there is no definition of `f` here, then might just say "... Fourier series of a function ...".

2022-04-07 21:55 UTC, ixfoduap requested changes

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +   :width: 100 %
Image is great, but it's way too big in the website. Please reduce size, maybe to 80% or 70%

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +    for i in range(J_mat.shape[0]):
maybe more elegant to do something like
```python
n = J_mat.shape[0]
for i in range(n):
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# For the Heisenberg model, a propetry of interest is usally the two-body
```suggestion
# For the Heisenberg model, a property of interest is usually the two-body
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# .. math::  \hat{C}_{ij} = \frac{1}{3} (X_i X_j + Y_iY_j + Z_iZ_j)
```suggestion
# .. math::  \hat{C}_{ij} = \frac{1}{3} (X_i X_j + Y_iY_j + Z_iZ_j).
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# Expectation value of each such element :math:`\hat{C}_{ij}` with respect to
```suggestion
# The expectation value of each such element :math:`\hat{C}_{ij}` with respect to
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +print(Hamiltonian(J_mat))
Might be nice to do something like
```python
print(f" Hamiltonian = {Hamiltonian(J_mat)}")
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# the correlation matrix :math:`C`, such that:
```suggestion
# the correlation matrix :math:`C`:
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +def corr_function_op(i, j):
```suggestion
def corr_function(i, j):
```
Or something else, but it's best to keep the number of underscores to a minimum in function and variable naming

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# model, we first diagonalize its corresponding Hamiltonian :math:`H`
```suggestion
# model, we first diagonalize its corresponding Hamiltonian
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# state represented by this eigenvector and measures the expectation value of
```suggestion
# We then build a circuit that initializes the qubits into the ground
# state and measure the expectation value of
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# function `imshow()``.
```suggestion
# Once built, we can visualize the correlation matrix:
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# Now that we have built our Heisenberg model, the next step is to construct
```suggestion
# Now that we have built the Heisenberg model, the next step is to construct
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# :math:`\rho`. Each measurement is chosen randomly among the Pauli bases
This is very nicely phrased!

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# .. math::  S_T(\rho) = \big\{|s_{i}^{(t)}\rangle: i\in\{1,\ldots, n\} t\in\{1,\ldots, T\} \big\} \in \{|0\rangle, |1\rangle, |+\rangle, |-\rangle, |i+\rangle, |i-\rangle\}.
Separate into two equations. One defines the set of states s_i^t, then the other clarifies that each state belongs to the set of Pauli eigenstates. What you have now is technically incorrect, you are saying that the set of states s_i^t is an element of the Pauli eigenstates

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# to a single snapshot of the :math:`\rho` and the :math:`nT`
```suggestion
# Each of the :math:`|s_i^{(t)}\rangle` provides us with
# a snapshot of the state :math:`\rho`, and the :math:`nT`
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# measurements yield the complete snapshot :math:`S_{T}`, which requires
```suggestion
# measurements yield the complete set :math:`S_{T}`, which requires
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# a qnode using a device that performs single-shot measurements.
```suggestion
# a QNode using a device that performs single-shot measurements.
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +#    :width: 100 %
Same as before, image should be smaller

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +    meas_outcomes = np.zeros((num_shadows, num_qubits))
Just use `outcomes`

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +def gen_class_shadow(circ_template, circuit_params, num_shadows, num_qubits):
All this is super nice! Great job!

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +    ]  # Z-basis
The comment # Z-basis should be in the line above

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# To see how well does the reconstruction work for different value of :math:`T`,
```suggestion
# To see how well does the reconstruction works for different value of :math:`T`,
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# :math:`\mathcal{F}` of the actual quantum state with respect to the reconstructed
```suggestion
# of the actual quantum state with respect to the reconstructed
```
No need to use this since we won't use a symbol for fidelity in any further equation. We can just say "fidelity" :smile: 

Also can remove from the y-axis in the plot

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# .. figure:: /demonstrations/ml_classical_shadows/fidel_snapshot.png
Title of this plot is too long. I suggest either removing a title, or using just "Fidelity of reconstructed state"

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# .. figure:: /demonstrations/ml_classical_shadows/fidel_snapshot.png
Since you have a caption saying this, probably best to remove title from the plot

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# actual :math:`\rho` for finite values of :math:`T`. Therefore to estimate
```suggestion
# :math:`\rho` for finite values of :math:`T`. Therefore to estimate
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +
:thinking: "Needed" seems too strong. What I'm saying is that perhaps you could just calculate the mean directly instead of the median of means. But this is not a big issue

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# classical shadow of our Heisenberg model this time.
```suggestion
# Now we estimate the correlation matrix :math:`C^{\prime}` from the
# classical shadow approximation
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +failure_rate = 1.0
What is this failure rate doing? Why include it if we're just dividing by one?

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +ax.set_title("Error in Estimating Correlation Matrix", fontsize=16)
```suggestion
ax.set_title("Error in estimating the correlation matrix", fontsize=16)
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# classical machine learning. This could include training a model to learn
```suggestion
# machine learning. This could include training a model to learn
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# infinite-width neural networks to learn the ground-state representation of the
Where did you get this notion of an infinite-width neural network from? This seems totally weird to me

If this is just another word for a tangent kernel, then please let's use tangent kernel

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# where :math:`x_l = [J_{i,j} \text{ for } i < j]` and predict the correlation
```suggestion
# where :math:`x_l = [J_{i,j} \text{ for } i < j]`. The goal is to predict the correlation
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# model constructed using :math:`T` randomized Pauli measurements and
```suggestion
# model constructed using :math:`T` randomized Pauli measurements, and
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# :math:`\sigma_T(x_l)` using the trained ML model can then be done by
```suggestion
# :math:`\sigma_T(x_l)` using the trained model can then be done by
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# We train the classical kernel-based ML models using :math:`N = 70`
```suggestion
# We train the classical kernel-based models using :math:`N = 70`
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# randomly chosen value of coupling matrices :math:`J` with
```suggestion
# randomly chosen values of the coupling matrices :math:`J`.
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# :math:`C_{ij}`.
```suggestion
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# the lattice (:math:`Nr` and :math:`Nc`) and the number of randomized
```suggestion
# the lattice (:math:`N_r` and :math:`N_c`) and the number of randomized
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# Pauli measurements (T) for construction of classical shadows. The
```suggestion
# Pauli measurements (:math:`T`) for the construction of classical shadows. The
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# stripped version of coupling matrix :math:`J`, where only non-duplicate
```suggestion
# stripped version of the coupling matrix :math:`J`, where only non-duplicate
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +def build_dataset(num_points, Nr, Nc, T=500):
This function is really long and hard to follow. Anything we can do to simplify it? Maybe break it up into simpler subfunctions?

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# .. math::  \lambda = \left\{ 0.0025, 0.0125, 0.025, 0.05, 0.125, 0.25, 0.5, 1.0, 5.0, 10.0 \right\}
```suggestion
# .. math::  \lambda = \left\{ 0.0025, 0.0125, 0.025, 0.05, 0.125, 0.25, 0.5, 1.0, 5.0, 10.0 \right\}.
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# For Gaussian kernel, the hyperparameter
```suggestion
# For the Gaussian kernel, the hyperparameter
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# .. math::  k(x, x^{\prime}) = e^{-\gamma||x - x^{\prime}||^{2}_{2}} \tag{Gaussian Kernel}
```suggestion
# .. math::  k(x, x^{\prime}) = e^{-\gamma||x - x^{\prime}||^{2}_{2}}. \tag{Gaussian Kernel}
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# .. math::  k(x, x^{\prime}) = \sum_{i\neq j}\sum_{k_i=-3}^{3}\sum_{k_j=-3}^{3} \cos{\big(\pi(k_i(x_i-x_i^{\prime}) + k_j(x_j-x_j^{\prime}))\big)} \tag{Dirichlet Kernel}
```suggestion
# .. math::  k(x, x^{\prime}) = \sum_{i\neq j}\sum_{k_i=-3}^{3}\sum_{k_j=-3}^{3} \cos{\big(\pi(k_i(x_i-x_i^{\prime}) + k_j(x_j-x_j^{\prime}))\big)}. \tag{Dirichlet Kernel}
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# Dirichlet kernel is motivated by writing the :math:`\text{k}^{th}`
```suggestion
# The Dirichlet kernel is motivated by writing the :math:`\text{k}^{th}`
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +## Dirichlet kernel ##
```suggestion
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +## Neural tangent kernel ##
```suggestion
```

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +from neural_tangents import stax
My brain is hurting at this stage of the demo. The work you have done is very impressive, but looking at three different kernels and validating them is excessive for a demo. 

I suggest we focus on the Gaussian kernel which performed best. This will make it much easier for the readers to follow the demo. You can simply add a line saying that you can consider other kernels, and maybe provide links to the respective documentation

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +def fit_predict_data(cij, kernel, opt="linear"):
I would prefer for this to not be in the demo. Instead, you can explain that this work was done offline and we select the best kernel and hyperparameters

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +
This figure is great! I think it still would look amazing with just one kernel

2022-04-07 21:55 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +
The demo is missing a short concluding paragraph

2022-04-13 18:57 UTC, chaeyeunpark requested changes
Hi Utkarsh, here are my first comments. I will come back tomorrow for another comment.

2022-04-13 18:57 UTC, chaeyeunpark commented on demonstrations/tutorial_ml_classical_shadows.py
> +shadow = gen_class_shadow(circuit_oshot, psi0, 100, num_qubits)
How about unpacking the result using `outcomes, basis = gen_class_shadow(...)`?

2022-04-13 18:57 UTC, chaeyeunpark commented on demonstrations/tutorial_ml_classical_shadows.py
> +        qml.Hadamard(wires=0).matrix, # X-basis
I think using a newly added `qml.matrix` can be better (https://pennylane.readthedocs.io/en/latest/code/api/pennylane.matrix.html?highlight=matrix#qml-matrix).

2022-04-19 20:51 UTC, ixfoduap requested changes
Almost good to go! Once you've addressed this final batch of comments, I'll be happy to approve

2022-04-19 20:51 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +Hamiltonian, correlation functions, and entanglement entropies.
```suggestion
that combining classical shadows with machine learning enables models
that efficiently predict properties of quantum systems, such as the expectation value of a
Hamiltonian, correlation functions, and entanglement entropies.
```

2022-04-19 20:51 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +In this demo, we demonstrate one of the ideas presented in Ref. [#preskill]_ for using classical
```suggestion
In this demo, we describe one of the ideas presented in Ref. [#preskill]_ for using classical
```

2022-04-19 20:51 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +shadow formalism and classical machine learning to predict the ground-state properties of the
```suggestion
shadow formalism and machine learning to predict the ground-state properties of the
```

2022-04-19 20:51 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +2D antiferromagnetic Heisenberg model. We begin by first learning how to build the Heisenberg model,
```suggestion
2D antiferromagnetic Heisenberg model. We begin by learning how to build the Heisenberg model,
```

2022-04-19 20:51 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +:math:`\sigma^{z}_{j}`. They determine the Hamiltonian associated with the model:
```suggestion
:math:`J_{ij}` present between the spins, as reflected in the Hamiltonian associated with the model:
```

2022-04-19 20:51 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +                                      2 * num_rows * num_cols - num_rows - num_cols))
indentation is a bit weird here, please revise

2022-04-19 20:51 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# i.e., one qubit for each spin. To begin instantiating the model, we start by
```suggestion
# a square lattice. We require four qubits for simulating this model;
# one qubit for each spin. We start by
```

2022-04-19 20:51 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# and :math:`\sigma^{z}_{j}` is defined as the following operator:
```suggestion
# correlation function :math:`C_{ij}`, which for a pair of spins :math:`i`
# and :j` is defined as the following operator:
```
Simpler to label the spins than to assign also a greek letter to them, which isn't really relevant anywhere

2022-04-19 20:51 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# ground state :math:`|\psi_{0}\rangle`. We do this by first diagonalizing
```suggestion
# Hence, to build :math:`C` for the model, we need to calculate its
# ground state :math:`|\psi_{0}\rangle`. We do this by diagonalizing
```
You often use "first" even though the meaning of the sentence is unchanged if we remove it :wink:

2022-04-19 20:51 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# a classical shadow representation for it. To construct an approximate
it's a classical shadow representation of the states, not of the model, right? Consider rephrasing

2022-04-19 20:51 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# the classical shadow with :math:`T` copies. We see that, on average, as the number
```suggestion
# the classical shadow with :math:`T` copies. On average, as the number
```

2022-04-19 20:51 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# infinite-width neural networks to learn the ground-state representation of the
Are you sticking to "infinite-width" neural networks? I personally don't like it since it breaks the flow of reading since it's such an unusual thing to see. Please consider revising

2022-04-19 20:51 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# For the gaussian kernel, the hyperparameter
```suggestion
# For the Gaussian kernel, the hyperparameter
```

2022-04-19 20:51 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# :math:`x_i` and :math:`x_j` and the kernel is implemented using the
```suggestion
# :math:`x_i` and :math:`x_j`. The kernel is implemented using the
```

2022-04-19 20:51 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# Radial-basis function (rbf) kernel in the ``sklearn`` library.
```suggestion
# radial-basis function (rbf) kernel in the ``sklearn`` library.
```

2022-04-19 20:51 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# to an infinite-width feed-forward neural network with four hidden
infinite-width is nice here actually!

2022-04-19 20:51 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# correlation function index ``cij``, kernel matrix ``kernel`` and internal
```suggestion
# correlation function index ``cij``, kernel matrix ``kernel``, and internal
```

2022-04-19 20:51 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# :math:`\lambda` could perform better than others at an average.
```suggestion
# kernels. 
```

2022-04-19 20:51 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +
This final text is too close to the image above. Please add some vertical space in between

2022-04-19 20:51 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# This demo concludes that classical machine learning models can benefit from
```suggestion
# This demo illustrates how machine learning models can benefit from
```

2022-04-19 20:51 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# classical shadow formalism derived from randomized Pauli measurements
```suggestion
# the classical shadow formalism
```

2022-04-19 20:51 UTC, ixfoduap commented on demonstrations/tutorial_ml_classical_shadows.py
> +# cannot be solved using classical methods alone.
```suggestion
# As argued in Ref. [#preskill]_, this raises the possibility that models trained
# on experimental or quantum data can effectively address quantum many-body problems that
# cannot be solved using classical methods alone. 
```

2022-04-19 21:40 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +    for col in ["Exact Diagnalization", "Gaussian Kernel", "Neur. Tang. Kernel"]
```suggestion
    for col in ["Exact Diagonalization", "Gaussian Kernel", "Neur. Tang. Kernel"]
```

2022-04-19 21:52 UTC, soranjh commented on demonstrations/tutorial_ml_classical_shadows.py
> +# .. figure::  /demonstrations/ml_classical_shadows/class_shadow_prep.png
Some words in this image seems to be randomly capitalized.

2022-04-19 21:52 UTC, soranjh approved these changes

2022-04-19 22:29 UTC, ixfoduap approved these changes

2022-04-20 13:15 UTC, chaeyeunpark approved these changes
Hi Utkarsh,

as it is already fruitful for a demo, I approve this PR. Some remaining thing I want to consider is size dependency, i.e. how the training epochs and fidelity depend on the number of qubits, but this may be further considered in a following project.

2022-05-02 22:49 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_ml_classical_shadows.py
> +*Author: PennyLane dev team. Posted: XX. Last Updated: XX April 2022*
```suggestion
*Author: PennyLane dev team. Posted: 2 May 2022. Last Updated: 2 May 2022*
```

2022-05-03 15:11 UTC, merged