Demo: quantum advantage in learning from experiments
PennyLaneAI/qml pull request #458
Opened 2022-04-04 16:35 UTC by josephbowles

------------------------------------------------------------------------------------------------------------

**Title:** Quantum advantage in learning from experiments.

**Summary:** Demo for the paper. I focus on one of the two tasks they perform using the google chip. Namely, how to distinguish time-symmetric and general unitaries in an unsupervised setting. 

**Relevant references:**
The paper: https://arxiv.org/pdf/2112.00778.pdf

**Possible Drawbacks:**

**Related GitHub Issues:**

2022-04-04 18:35 UTC, mariaschuld commented on demos_getting-started.rst
> +    :description: :doc:`demos/learning_from_experiments`
I forgot how it works, but at the moment the demo appears in the "getting started" section, and the thumbnail text is scrambled:
![Screenshot from 2022-04-04 14-34-12](https://user-images.githubusercontent.com/23052011/161609259-1a27bef2-d9d3-4d21-9f57-49f72bd7a429.png)

Would be better placed in the QML section?

2022-04-04 18:37 UTC, mariaschuld commented on demonstrations/tutorial_learning_from_experiments.py
> +John Preskill, and Jarrod R. McClean*
This should be the demo author :) 

I don't know if there is a new standard for this, but would prefer if the first sentence tells the reader what paper you are looking at here? Maybe even in italics, and with a hyperlink so it stands out immediately?

2022-04-04 18:40 UTC, mariaschuld commented on demonstrations/tutorial_learning_from_experiments.py
> +arXiv:2112.00778 for which this is the case: deciding if a unitary is
Make this a hyperlink?

I prefer in demos if the paper is always referred to by the author surnames, which are hyperlinked to the arxiv version. When mentioned for the first time one can also mention the title, and a ref like [1] which leads to the full reference at the bottom... 

Basically, how can a reader like you and me know exactly what paper you are referring to, especially if we know the paper already?

2022-04-04 18:40 UTC, mariaschuld commented on demonstrations/tutorial_learning_from_experiments.py
> +than those without.
Nice start!

2022-04-04 18:40 UTC, mariaschuld commented on demonstrations/tutorial_learning_from_experiments.py
> +evolution is the same both forward and backward in time.
Nice!

2022-04-04 18:41 UTC, mariaschuld commented on demonstrations/tutorial_learning_from_experiments.py
> +#    :width: 90%
Maybe make it a bit smaller? 

I personally always follow the rule that font size _in_ a figure should be comparable to the font size of the main text. This comes from the assumption that there is one font size that is nice for reading, and it should be used everywhere...

2022-04-04 18:42 UTC, mariaschuld commented on demonstrations/tutorial_learning_from_experiments.py
> +but we are not told which ones.
```suggestion
but we are not told which ones are which.
```

?

2022-04-04 18:43 UTC, mariaschuld commented on demonstrations/tutorial_learning_from_experiments.py
> +n_shots = 100  # the number of times we can use each unitary
Nice way to introduce the access as a parameter in the algorithm

2022-04-04 18:45 UTC, mariaschuld commented on demonstrations/tutorial_learning_from_experiments.py
> +# can still be very hard to see any difference! In fact, in [2] it is
[2] should be a hyperlink to the ref at the bottom - I forgot how this works, I think by using [#] or so?

2022-04-04 18:46 UTC, mariaschuld commented on demonstrations/tutorial_learning_from_experiments.py
> +# T-symmetric and the second 30 circuits are not.
Minor idea, but people may get confused why this is unsupervised if we know which data is from which class. Could add "of course, the algorithm does not know this" or so?

2022-04-04 18:50 UTC, mariaschuld commented on demonstrations/tutorial_learning_from_experiments.py
> +#
Nice section.

I immediately wondered: so if one would increase shots (and hence the estimation capability), would clustering work? 

I wonder if one could show this numerically? The added value would be the insight of what "cannot classically learn" means (= "cannot _efficiently_ classically learn", it can be learnt, but only with many resources).

2022-04-04 18:52 UTC, mariaschuld commented on demonstrations/tutorial_learning_from_experiments.py
> +# Now let’s see what difference having a quantum memory can make. Instead
I was always confused in talks about the paper what they mean by memory, and thought they mean some crazy device that stores data. For someone similar, explaining this term higher up could be very beneficial. 

Quantum memory = having access to copies of the unitary somehow?

2022-04-04 18:53 UTC, mariaschuld commented on demonstrations/tutorial_learning_from_experiments.py
> +fig.show()
Cool to draw here, but the drawing is super small :) not sure if there is a better way, i.e. using part of the circuit, or a slider?

2022-04-04 18:54 UTC, mariaschuld commented on demonstrations/tutorial_learning_from_experiments.py
> +# the two classes.
Maybe one last sentence as summary? Like: "We have seen an example where entangling quantum states can make a real difference to learning" or so?

2022-04-04 18:55 UTC, mariaschuld requested changes
A lot of changes are suggestions, only the formatting ones of the demo thumbnail and how to include references are important.

You got a real talent for communicating content, reads very nicely!

2022-04-05 10:31 UTC, josephbowles commented on demos_getting-started.rst
> +    :description: :doc:`demos/learning_from_experiments`
ah yes I put it in qml now. For some reason the thumbnail link isn't working. Am I supposed to edit something other than demos_qml.rst?

2022-04-05 13:10 UTC, josh146 commented on demos_getting-started.rst
> +    :description: :doc:`demos/learning_from_experiments`
@josephbowles the thumbnail link isn't working as the filename is not correct 🙂 Should be 
```rest
:description: :doc:`demos/tutorial_learning_from_experiments`
```

2022-04-05 13:10 UTC, josh146 commented on demos_qml.rst
> +    :description: :doc:`demos/learning_from_experiments`
```suggestion
    :description: :doc:`demos/tutorial_learning_from_experiments`
```

2022-04-05 13:34 UTC, josephbowles commented on demos_getting-started.rst
> +    :description: :doc:`demos/learning_from_experiments`
haha yes of course, thanks!

2022-04-07 16:13 UTC, josephbowles commented on demonstrations/tutorial_learning_from_experiments.py
> +John Preskill, and Jarrod R. McClean*
I've rewritten the into a little and the first sentence introduces the paper now.

2022-04-07 16:13 UTC, josephbowles commented on demonstrations/tutorial_learning_from_experiments.py
> +but we are not told which ones.
changed

2022-04-07 16:14 UTC, josephbowles commented on demonstrations/tutorial_learning_from_experiments.py
> +# allow us to discriminate the two classes of circuits easily. However,
done!

2022-04-07 16:14 UTC, josephbowles commented on demonstrations/tutorial_learning_from_experiments.py
> +# can still be very hard to see any difference! In fact, in [2] it is
done

2022-04-07 16:14 UTC, josephbowles commented on demonstrations/tutorial_learning_from_experiments.py
> +# T-symmetric and the second 30 circuits are not.
good point, I added this.

2022-04-07 16:15 UTC, josephbowles commented on demonstrations/tutorial_learning_from_experiments.py
> +# Now let’s see what difference having a quantum memory can make. Instead
There is now a small section where I try to explain this. I'm not sure how successful I was, let me know what you think.

2022-04-07 16:15 UTC, josephbowles commented on demonstrations/tutorial_learning_from_experiments.py
> +fig.show()
I agree it is really too small. I can't see a way around this so I just removed it.

2022-04-07 16:15 UTC, josephbowles commented on demonstrations/tutorial_learning_from_experiments.py
> +# the two classes.
added.

2022-04-07 16:17 UTC, josephbowles commented on demonstrations/tutorial_learning_from_experiments.py
> +# Now let’s see what difference having a quantum memory can make. Instead
I've also added some explanation of why the enhanced circuit always returns the same outcome (before this was an 'exercise' but I thought I might as well just do the calculation).

2022-04-07 16:25 UTC, josephbowles commented
I've made some changes following the review, let me know what you think. The plots are too large, so I will probably shrink them.

2022-04-08 12:12 UTC, mariaschuld commented on demonstrations/tutorial_learning_from_experiments.py
> +They show that access to quantum memory can make a big difference, and
```suggestion
The paper shows that access to quantum memory can make a big difference, and
```

2022-04-08 12:12 UTC, mariaschuld commented on demonstrations/tutorial_learning_from_experiments.py
> +# ---------------------------------------------
Awesome!

2022-04-08 12:13 UTC, mariaschuld commented on demonstrations/tutorial_learning_from_experiments.py
> +# but rather two classes of quantum algorithms.
That's actually true...the title of the paper really makes it sound as if they have a pure quantum advantage! :)

2022-04-12 18:10 UTC, KetpuntoG reviewed
I loved it! 🚀 I leave a few comments as a possible improvement

2022-04-12 18:10 UTC, KetpuntoG commented on demonstrations/tutorial_learning_from_experiments.py
> +#
Cool!🤩

2022-04-12 18:10 UTC, KetpuntoG commented on demonstrations/tutorial_learning_from_experiments.py
> +    noise_layer(np.pi/4) #added noise layer
Just curious, has the noise been placed in this particular location for any reason?

2022-04-13 07:29 UTC, josephbowles commented on demonstrations/tutorial_learning_from_experiments.py
> +#    ``n_shots`` number of times and measure each state to generate
good point thanks!

2022-04-13 07:29 UTC, josephbowles commented on demonstrations/tutorial_learning_from_experiments.py
> +# values are 0 for this class. For general unitaries this is not the case,
sure I'll add a bit more explanation

2022-04-13 07:31 UTC, josephbowles commented on demonstrations/tutorial_learning_from_experiments.py
> +    noise_layer(np.pi/4) #added noise layer
Not really, I just wanted to make as simple noise as possible to keep the execution time down, and just after the unitaries made the most sense to be. 

Thanks so much for the review!!

2022-04-13 07:31 UTC, josephbowles commented on demonstrations/tutorial_learning_from_experiments.py
> +    noise_layer(np.pi/4) #added noise layer
I'll make the changes today

2022-04-13 10:41 UTC, josephbowles commented
Demo is ready to be merged now. I have put tomorrows date (14th) as the 'date posted'. Thanks for the help!

2022-04-13 14:06 UTC, co9olguy commented
@josephbowles please don't merge the demo manually. We like to schedule these in advance. Just let me know when it's in a completed merge-ready state :slightly_smiling_face:

2022-04-13 14:11 UTC, co9olguy commented on demonstrations/tutorial_learning_from_experiments.py
> +*Posted: 14 April 2022*
Can go on same line (see other demos)

2022-04-13 14:15 UTC, josephbowles commented on demonstrations/tutorial_learning_from_experiments.py
> +"""
ah ok, will get this done today thanks!

2022-04-18 20:25 UTC, merged