Photonics Demo
PennyLaneAI/qml pull request #484
Opened 2022-05-02 16:42 UTC by alvaro-at-xanadu

**Title:** Photonic Quantum Computing

**Summary:** How photonic quantum computers work in real life

**Relevant references:** 

**Possible Drawbacks:**

**Related GitHub Issues:**

2022-05-04 13:42 UTC, jen-dodd commented on demonstrations/tutorial_photonics.py
> +progress has been made using trapped ions, superconducting circuits,
I think you should mention photons here as it seems like an odd omission in the context.

2022-05-20 19:44 UTC, co9olguy requested changes
Thanks @alvaro-at-xanadu! This is looking solid so far :slightly_smiling_face: 

I left quite a few smaller comments throughout the doc, but wanted to highlight three larger points here:

- Overall in the text, there is a conflation of qumodes with states. These are related but independent concepts. Think of qumodes as independently addressable systems (distinguishable by their quantum numbers), rather than states (of which each specific qumode has an infinite number). Since being inaccurate on these points will likely lead the readers to misunderstand the rest of the demo, it would be good to polish these statements up and make clearer

- There is also a conflation between photodetectors used for homodyne measurements and photon-number-resolving detectors like those used for approx. GKP generation. These are quite different in terms of what they can do (though both can be considered to be "measuring the number of photons". Would be good to make this distinction clearly

- Be careful in the description of GBS and quantum advantage. What you wrote there isn't really correct

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# (see `this tutorial <https://pennylane.ai/qml/demos/tutorial_qgbs.html>`__ for an in-depth discussion).
404 error. 
Also, make sure to use sphinx directives like `:doc_tutorial_gbs:` to link to internal content (that way if a URL changes, sphinx will show an error and we'll know to fix)

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# the first photonic quantum computer to achieve quantum advantage. But the most interesting
You'll have to be pretty careful stating this. GBS experiments do not give us probabilities (if they did, we would be able to compute hafnians of matrices). They give us samples from a probability distribution (specified by the Hafnian). The accomplishment of Jiuzhang was to sample from a distribution sufficiently difficult for classical adversaries to draw or spoof samples from

If the space of possible outputs is small (low number of modes, low photon numbers), we can convert samples into estimates of probabilities, and estimate hafnians from those. But this is really an edge case. Both the distribution itself is hard to sample from, and there are so many outcomes that getting good estimates of probabilities from population statistics would be prohibitively hard

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# produce a good approximation of any non-Gaussian state that we want. The reason is that the
I'm not sure about the "any" here. Be good to ask someone like Ilan about this

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# final state for the circuit is an entangled qumode, and we apply a non-Gaussian operation to some of the
conflation of state and qumode

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# .. math:: t_1 = 0.8624, \quad t_2=0.7688, \quad t_3 = 0.7848, \quad S_1 = -1.38, \quad S_2 = -1.22, \quad S_3 = 0.780 \quad S_4 = 0.196,
overflows when rendered on a "half size" browser window
![image](https://user-images.githubusercontent.com/7213358/169596277-b21a5293-1d61-4002-bc4f-5710cb0f592b.png)

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# non-Gaussian states (we can only interpret this function as a probability distribution for Gaussian states!).
```suggestion
# non-Gaussian states (we can only interpret this function as a true probability distribution for the case of Gaussian states!). 
```

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# The Walrus tutorial <https://the-walrus.readthedocs.io/en/latest/gallery/gkp.html>`__,
```suggestion
# tutorial <https://the-walrus.readthedocs.io/en/latest/gallery/gkp.html>`__ from PennyLane's sister library The Walrus, 
```

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +#    :width: 70%
See above comment on polishing this image (blurry, etc)

Note that with so many wiggles, it will take quite a lot of "render time" to make it look smoother compared to a single coherent state

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +#    Wigner function of non-Gaussian state
This is a really cool result, but the presentation kind of conflates to related, but separate ideas:
- we can use a GBS circuit, and measure on a subset of modes, to produce non-Gaussian states in the other modes
- with this specific combination of parameters, we will produce an approximate GKP state

It would be good to disentangle these two in the presentation (without adding significant new text)

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# .. math:: \vert \psi \rangle = S(0.196)\left(0.661 \vert 0\rangle -0.343 \vert 2\rangle + 0.253\vert 4\rangle -0.368\vert 6\rangle
What is S(0.196)?

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# Surely there's more than one way to encode a two dimensional space into an infinite-dimensional
```suggestion
# Surely there's more than one way to encode a two-dimensional subspace into an infinite-dimensional 
```

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# affecting the large Hilbert space. A way that has proven to be quite robust to errors is to
first mention of "Hilbert space". Probably not needed to introduce extra jargon-y words at this stage if it's just a one-off

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# where the subscrpit :math:`x` means that the kets in the sum are eigenstates of the quadrature observable
```suggestion
# where the subscript :math:`x` means that the kets in the sum are eigenstates of the quadrature observable 
```

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# can be expressed through the qumode
```suggestion
# can be expressed through the qumode as
```

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# Producing these GKP states is physically impossible. But we can produce an approximate version of it and still
```suggestion
# Producing these GKP states is physically impossible. But we can produce approximate versions of them and still
```

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# calculate with great precission. In fact, the non-Gaussian state that we wrote in the previous section is
```suggestion
# calculate with great precision. In fact, the non-Gaussian state that we wrote in the previous section is 
```

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# :math:`\vert 1 \rangle_{GKP}`, and viceversa. Therefore, the displacement operator corresponds to the qubit
```suggestion
# :math:`\vert 1 \rangle_{GKP}`, and vice versa. Therefore, the displacement operator corresponds to the qubit 
```

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# universal quantum computation using optical gates on  exact GKP states.
Great!

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +#     +---------------------+--------------------------------------------------------------+---------------------------------------------------------------------+
consider using versions of these gates without the hand-written text (hard to read)

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +#     +---------------------+--------------------------------------------------------------+---------------------------------------------------------------------+
(for the first two I think it's ok because they're simple or have been shown before, but the last one is new, and the text is probably important to have)

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# .. figure:: ../demonstrations/photonics/formula_qc.png
Consider a hand-written version of the text, I think it suit very well!

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# from scaling further? Let us analyze what we have learned in terms of Di Vincenzo's criteria.
```suggestion
# We have now learned the basics of how to build a quantum computer using photonics. So what challenges 
# are there to overcome for scaling further? 
# Let us analyze what we have learned in terms of Di Vincenzo's criteria. 
```

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# From what we've learned above, the third, fourth, and fifth criteria are satisfied by linear optical
"we've learned"/"we have learned" is repeated in two consecutive sentences. Suggest rephrasing one

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# quantum computers. There is room for improvement for gates precision and qubit measurements.
```suggestion
# quantum computers. There is room for improvement for gate precision and qubit measurements.
```

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# physically built, as opposed to, for example, using lasers to change the a qubit's state (see tutorials on
```suggestion
# physically built, as opposed to, for example, using lasers to change the qubit's state (see tutorials on 
```

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# physically built, as opposed to, for example, using lasers to change the a qubit's state (see tutorials on
use sphinx directives

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# which occupy physical space and require photon detectors held at low temperatures  Moreover, the GKP states
```suggestion
# which occupy physical space and require photon detectors held at low temperatures. Moreover, the GKP states
```

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# a squeezed state entangled with other qumodes. Should we just get rid of it? Not at all! Strongly entangled squeezed
If we've measured all the other qumodes, what systems is the entanglement between? :thinking:

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# a squeezed state entangled with other qumodes. Should we just get rid of it? Not at all! Strongly entangled squeezed
Is it the signal and idler modes within the waveguide that are entangled? In that case, it might be not be worth mentioning "other qumodes" and just saying "strongly-entangled squeezed states" (omitting the technical details of the subsystems that are entangled)

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# to use these highly entangled squeezed states as a resource for quantum computing, although they're more prone to error. This approach
```suggestion
# to use these highly-entangled squeezed states as a resource for quantum computing, although they're more prone to error. This approach
```

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# a squeezed state entangled with other qumodes. Should we just get rid of it? Not at all! Strongly entangled squeezed
```suggestion
# a squeezed state entangled with other qumodes. Should we just get rid of it? Not at all! Strongly-entangled squeezed
```

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +#    Xanadu's X8 chip
Nice to include this, but it isn't provided any context.
```suggestion
#    Xanadu's X8 Gaussian Boson Sampling chip. Variants of this chip can be used to generate approximate GKP states.
```

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# The approach of photonic devices to quantum computing is quite different from their qubit-based counterparts. Recent theoretical
I wouldn't use "qubit-based" here, since you've gone into great detail about how we can use photonics to create qubits (just like superconducting circuits aren't naturally qubits, you have to precisely architect them to create two preferred states)

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# remains troublesome. The variety of ways that we can encode qubits into photons state leave plenty of room for creativity, and open the
```suggestion
# remains a challenge to overcome. The variety of ways that we can encode 
# qubits into photonic states leave plenty of room for creativity, and opens the
```

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# as well as the references listed below.
Only one reference given, and not about photonics

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +#    :photo: ../_static/Alvaro.png
Photo not rendering for me, but I think it might be due to the rendering error that occurs at an earlier line (I also wasn't able to see any subheadings after that point).

2022-05-20 19:44 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +#    in quantum computing and PennyLane accessible to the community.
:raised_hands:

2022-05-20 20:30 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +# Although PennyLane does not allow us to sample ``qml.NumberOperator``, trying the above
I figured it out. I made a mistake in the bio and that did this...

2022-05-24 18:05 UTC, alvaro-at-xanadu commented on demos_quantum-computing.rst
> +    demos/photonics
This was all a merge conflict that vs code didn't fix properly

2022-05-24 18:15 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +    :property="og:image": https://pennylane.ai/qml/_images/photonics_tn.png
I'll make a unique one, that's on the to-do list

2022-05-24 18:18 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +Instead, it's based on qumodes: states of
I'll change some stuff here, but I think this explanation is too technical. I'll think of a more intuitive explanation.

2022-05-24 18:35 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +the same tasks as qubit-based devices. You will learn how to prepare,
Sounds good, I'll change this a bit.

2022-05-24 18:49 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +#    of a photon. They describe a state of many photons (e.g. a laser beam), and they are related
Yup! I see how this is not accurate.

2022-05-24 18:56 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +# Such representation of a quantum state is called a **qumode**. For example, we write
🤔 Maybe? Kind of depends on to what degree math and reality correspond to one another in whatever philosophy of physics we adhere to XD. I'll revamp the definition of qumode altogether anyway.

2022-05-24 18:57 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +# and define the device. Note that the number of wires corresponds to the number of qumodes.
Yep, I'll do this to introduce qumodes more explicitly.

2022-05-24 19:12 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +p_sample = vacuum_measure_p().numpy()
Is there a better way? This turns tensor objects into floats, which the function below can read.

2022-05-24 19:15 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +#    :width: 70%
🙏 Thanks!

2022-05-24 19:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +# coherent state in a beamsplitter. The target state is another coherent state
Ok! This I know, I just chose it to be a coherent state. But I can clarify that it's not needed.

2022-05-24 19:34 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +# produce a good approximation of any non-Gaussian state that we want. The reason is that the
He did state it in this [medium article](https://medium.com/xanaduai/riding-bosonic-qubits-towards-fault-tolerant-quantum-computation-95b92c78cb43)

2022-05-24 19:48 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +# as well as the references listed below.
Yep, I will add lots of them!

2022-05-24 19:48 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +#    :photo: ../_static/Alvaro.png
Fixed!

2022-05-24 21:16 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +#     |                     |                                                              | coming in through each port.                                        |
Technically t here is not the transmittivity T, but T^2 already. Didn't want to introduce these names, so I defined it as a fraction of light intensity transmitted. I can change letter so it's not confusing.

2022-05-24 22:26 UTC, ilan-tz reviewed
Good job, @alvaro-at-xanadu ! I've left a few comments for you. This is a very ambitious tutorial -- which can be a good thing, in that it immerses the reader in the topic, but it also means there is a lot of information for the reader to parse. It may benefit in a reduction in scope or being split up -- just something to keep in mind.

2022-05-24 22:26 UTC, ilan-tz commented on demonstrations/tutorial_photonics.py
> +# calculate with great precision. In fact, the non-Gaussian state that we wrote in the previous section is
A little ambiguous what is meant by calculate here (I guess run a quantum computation reliably?)

2022-05-24 22:26 UTC, ilan-tz commented on demonstrations/tutorial_photonics.py
> +# bit-flip gate :math:`X`. Similarly, a rotation operator by :math:`\pi/2` implements the Hadamard gate.
Consider adding a bar on top of the X and mentioning that this denotes a logical gate in your notation

2022-05-24 22:26 UTC, ilan-tz commented on demonstrations/tutorial_photonics.py
> +# universal quantum computation using optical gates on  exact GKP states.
These are the same gates for non-ideal GKP states -- it's just the effect becomes approximate at the qubit level

2022-05-24 22:26 UTC, ilan-tz commented on demonstrations/tutorial_photonics.py
> +#     | Displacement        | .. figure:: ../demonstrations/photonics/Displacement.png     | Pauli X gate if displacement is in :math:`x` direction.             |
Since you give a precise value for the rotation, I would give a precise values for the displacements (sqrt(pi))

2022-05-24 22:26 UTC, ilan-tz commented on demonstrations/tutorial_photonics.py
> +# The above already allow for a universal set of gates on the GKP qubits. Even if their effect is approximate, they are quick
This is not exactly true -- if you only had GKP pauli eigenstates, these only allow for arbitrary Clifford operations. For a universal gate set you would need a GKP magic state to help implement, say, the T gate.

2022-05-24 22:26 UTC, ilan-tz commented on demonstrations/tutorial_photonics.py
> +#    :width: 70%
Consider linking to the corresponding blog post(s) here

2022-05-24 22:26 UTC, ilan-tz commented on demonstrations/tutorial_photonics.py
> +# From what we've learned above, the third, fourth, and fifth criteria are satisfied by linear optical
Loss makes the third criteria a little trickier to satisfy

2022-05-24 22:26 UTC, ilan-tz commented on demonstrations/tutorial_photonics.py
> +# quantum computers. There is room for improvement for gate precision and qubit measurements.
The sentence is a little vague. I would either omit it or expand on it.

2022-05-24 22:26 UTC, ilan-tz commented on demonstrations/tutorial_photonics.py
> +# We do have well-defined and scalable qubits thanks to our ability to produce GKP states.
We know a lot about GKP states, but it is still not easy to characterize them after application of a bunch of different noise sources.

2022-05-24 22:26 UTC, ilan-tz commented on demonstrations/tutorial_photonics.py
> +# As a consequence, more powerful photonic quantum computers will occupy more physical space.
This part may need significant modification.

We actually argue that photonic architectures are the most scalable variety: once you create a single instance of a high-quality qubit, you leverage the expertise of the telecom industry to print millions of state preparation circuits on chip. This ties in with other benefits of particular architectures, like modularity, networkability via optical fibres, low cryogenic requirements, etc. On the other hand, trapped ions are notorious for being harder to scale up.

In light of this there is no reason to think the last statement is true

2022-05-24 22:26 UTC, ilan-tz commented on demonstrations/tutorial_photonics.py
> +# The main challenge lies in the second criterion: the ability to *prepare a qubit*.
There is some subtlety here. For us, preparing a qubit is hard, but entangling them is easy. For DV approaches, preparing a qubit (a single photon) is easy, but entangling them is hard (a probabilistic fusion operation requiring photon counters and hence cryogenics to be aware of failure modes due to loss)

2022-05-24 22:26 UTC, ilan-tz commented on demonstrations/tutorial_photonics.py
> +# which in turn exponentially decreases the probability of obtaining them.
I would phrase this more gently: "which can decrease the probability of obtaining them" . Exponential decay is under the assumption of sticking to our blueprint state generation proposal.

2022-05-24 22:26 UTC, ilan-tz commented on demonstrations/tutorial_photonics.py
> +# a squeezed state entangled with other qumodes. Should we just get rid of it? Not at all! Strongly-entangled squeezed
Not quite: when we fail to produce a GKP state, the resulting state may still be a non-Gaussian state, whether useful or not. In case of GBS failure, we use a separate squeezer to prepare squeezed state, and then deterministically entangle it to another squeezed state or GKP state via beamsplitter.

2022-05-25 18:31 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +#     | Beamsplitter        | .. figure:: ../demonstrations/photonics/Beam_splitter.png    | An element with two entry and two exit ports. It transmits a        |
Yes, I should add a link to directional coupler too.

2022-05-25 20:32 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +p_sample = vacuum_measure_p().numpy()
Oh yeah it does work, I think it didn't work for the plot I had before, but it's all good now.

2022-05-27 15:15 UTC, jen-dodd commented on demonstrations/tutorial_photonics.py
> +    2. **Qubit initialization**. We must be able to prepare the same repeatedly within
Missing word after "same"

2022-05-27 15:16 UTC, jen-dodd commented on demonstrations/tutorial_photonics.py
> +    we must accurately measure the final of a pre-chosen set of qubits.
Missing "state" after "final"

2022-05-27 16:03 UTC, jen-dodd reviewed
Overall good, a bunch of mostly very minor comments. A couple of medium ones but shouldn't take too much to resolve them!

2022-05-27 16:03 UTC, jen-dodd commented on demonstrations/tutorial_photonics.py
> +#    Alvaro Ballon is a quantum computing educator at Xanadu. His work involves making the latest developments in quantum computing accesible to the community
```suggestion
#    Alvaro Ballon is a quantum computing educator at Xanadu. His work involves making the latest developments in quantum computing accessible to the community.
```

2022-05-27 16:03 UTC, jen-dodd commented on demonstrations/tutorial_photonics.py
> +# The state of the art
In this section you move to discussing what Xanadu is doing, rather than what PL can do. I think it would help to say something like "Since I work at Xanadu, I'd like to shift gears here and say a little more about what we're doing to develop a photonic quantum computer." That way it makes it clear why a PL tutorial is suddenly full of Xanadu stuff.

2022-05-27 17:58 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +# :math:`\left\lvert \psi \right\rangle` we need infinitely many basis vectors!
The comma in the previous sentence shouldn't be there, so I'll just address this one locally.

2022-05-27 18:00 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +#     |                     |    :width: 100%                                              | port, and reflects a fraction :math:`R=1-T`. The input qumodes can         |
It is defined in a block that I labeled "Important" XD

2022-05-27 18:03 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +# Producing these GKP states is physically impossible. But we can produce approximate versions of them and still
I'll add a sentence here

2022-05-27 18:10 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +# The state of the art
Yes, but that'd of the point of this section, to state where technology is at architecture-wise.

2022-05-27 19:47 UTC, co9olguy approved these changes
Thanks @alvaro-at-xanadu, happy to approve. 
All my suggestions at this stage are final polish :trophy:

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
>  ax1.set_xlabel("Position", fontsize=11)
Minor/optional: 
due to a quirk of plotting, Momentum has 10 ticks, while Position has 5. In order to reinforce that the axes have the same scale, I think it would be good if the ticks were the same for both

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# by carefully isolating a system from any environmental influences, and a coherent state can be produced
vacuum state would also require to "cool" the system to its lowest state, but I don't think we should get into this subtlety here

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# The vacuum is centered at the origin in phase space. But our objective is to generate states that
It's not exactly clear why this is our objective. I would just say something like "It is advantageous to generate states ..."

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +dev_exact = qml.device("default.gaussian", wires=1)  # No explicit shots gives analytic calculations
There are 2-3 code blocks which are *just slightly* too long and a horizontal scrollbar appears. Would be good to trim these so there are no scrollbars

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# Note that an integral is used here rather than an infinite sum because the eigenvalues of :math:`\hat{X}` and :math: `\hat{P}` are continuous.
```suggestion
# Note that an integral is used here rather than an infinite sum because the eigenvalues of :math:`\hat{X}` and :math:`\hat{P}` are continuous.
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# Note that an integral is used here rather than an infinite sum because the eigenvalues of :math:`\hat{X}` and :math: `\hat{P}` are continuous.
math doesn't render with the space

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# Note that setting :math:`x=3` gave a displacement of 6 units in the horizontal direction in phase space.
```suggestion
# Note that setting :math:`x=3` gave a displacement of 6 units in the horizontal direction in phase space.
# This is because the scale of phase space is set by our choice of units :math:`\hbar=2.`
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# is shown below, which uses a beam splitter and a source of **high-intensity coherent light** [#Paris1996]_.
I noted that you sometimes use "beam splitter" and sometimes "beamsplitter". I'd recommend "beamsplitter" because that matches the `qml.Beamsplitter`

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +ax1.set_xlabel("Position", fontsize=11)
see above note about ticks

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# which rotates the in phase space. Let's take a look at how squeezing changes the distribution
```suggestion
# which rotates the state in phase space. Let's take a look at how squeezing changes the distribution
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +ax1.set_xlim([-4, 4])
Hard to tell if axis scales are equal here (it looks like they are slightly off still)

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# The reason is that light is characterized by its so-called *position and momentum quadratures* :math:`x` and :math:`p`,
```suggestion
# The reason is that light is characterized by its so-called *position and momentum quadratures* :math:`x` and :math:`p,`
```
Always good to put the punctuation inside the math environment because otherwise it sometimes renders like:
p
,

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# :math:`x`, and :math:`\psi` is a complex-valued function known as the *wave function*.
```suggestion
# :math:`x,` and :math:`\psi` is a complex-valued function known as the *wave function*.
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# states only*, the density is exactly equal to the so-called `Wigner function <https://en.wikipedia.org/wiki/Wigner_quasiprobability_distribution>`__ :math:`W(x,p)`,
```suggestion
# states only*, the density is exactly equal to the so-called `Wigner function <https://en.wikipedia.org/wiki/Wigner_quasiprobability_distribution>`__ :math:`W(x,p),`
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# :math:`r` which tells us how much the variance in :math:`x` and :math:`p` changes, and :math:`\phi`,
```suggestion
# :math:`r` which tells us how much the variance in :math:`x` and :math:`p` changes, and :math:`\phi,`
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
>  #    The squeezed states produced above satisfy :math:`\Delta x \Delta p = 1`,
```suggestion
#    The squeezed states produced above satisfy :math:`\Delta x \Delta p = 1,`
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# photon-number observable :math:`\hat{N}`, which has eigenstates denoted :math:`\vert 0 \rangle, \vert 1\rangle, \vert 2 \rangle,...`.
```suggestion
# photon-number observable :math:`\hat{N},` which has eigenstates denoted :math:`\vert 0 \rangle, \vert 1\rangle, \vert 2 \rangle,\dots`
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +#     | Magic state         | .. figure:: ../demonstrations/photonics/Tgate.png            | We use an auxiliary *magic state* :math:`\vert M\rangle`,           |
```suggestion
#     | Magic state         | .. figure:: ../demonstrations/photonics/Tgate.png            | We use an auxiliary *magic state* :math:`\vert M\rangle,`           |
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +#     |                     |                                                              | :math:`\vert -\rangle`, we apply the shown rotations and squeezers  |
```suggestion
#     |                     |                                                              | :math:`\vert -\rangle,` we apply the shown rotations and squeezers  |
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +#     |                     |                                                              | with :math:`r=\cosh^{-1}(3/4)`, :math:`\theta=\tan^{-1}(1/2),`      |
```suggestion
#     |                     |                                                              | with :math:`r=\cosh^{-1}(3/4),` :math:`\theta=\tan^{-1}(1/2),`      |
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +#     |                     |                                                              | and :math:`\phi=-\pi/2-\theta`, resulting in a GKP *T gate*.        |
```suggestion
#     |                     |                                                              | and :math:`\phi=-\pi/2-\theta,` resulting in a GKP *T gate*.        |
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
>  # A similar expansion can be done in terms of the eigenstates :math:`\vert p \rangle` of :math:`\hat{P}`.
```suggestion
# A similar expansion can be done in terms of the eigenstates :math:`\vert p \rangle` of :math:`\hat{P}.`
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# as well as their standard deviations :math:`\Delta x` and :math:`\Delta p`. The most trivial
```suggestion
# as well as their standard deviations :math:`\Delta x` and :math:`\Delta p.` The most trivial
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# We plot 1000 measurement results for both :math:`x` and :math:`p`.
```suggestion
# We plot 1000 measurement results for both :math:`x` and :math:`p.`
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# which are also Gaussian with :math:`\Delta x = \Delta p = 1`. Coherent states, in general,
```suggestion
# which are also Gaussian with :math:`\Delta x = \Delta p = 1.` Coherent states, in general,
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +#     |                     |    :width: 100%                                              | port, and reflects a fraction :math:`R=1-T`. The input qumodes can         |
```suggestion
#     |                     |    :width: 100%                                              | port, and reflects a fraction :math:`R=1-T.` The input qumodes can         |
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +#    This setup displaces the input state :math:`\lvert\psi\rangle` by a quantity proportional to :math:`z`.
```suggestion
#    This setup displaces the input state :math:`\lvert\psi\rangle` by a quantity proportional to :math:`z.`
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# So far, we have focused on changing the mean values of :math:`x` and :math:`p`.
```suggestion
# So far, we have focused on changing the mean values of :math:`x` and :math:`p.`
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# :math:`\hat{X}` and :math:`\hat{P}`. But how do we actually measure them using optical elements?
```suggestion
# :math:`\hat{X}` and :math:`\hat{P}.` But how do we actually measure them using optical elements?
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# we get 0, 1, or 2 photons, each with probability :math:`1/3`.
```suggestion
# we get 0, 1, or 2 photons, each with probability :math:`\frac{1}{3}.`
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
>  # allows us to measure the quadratures :math:`\hat{X}` and :math:`\hat{P}`. Feel free to play around
```suggestion
# allows us to measure the quadratures :math:`\hat{X}` and :math:`\hat{P}.` Feel free to play around
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# :math:`\hat{X}`. Therefore, an arbitrary qubit :math:`\vert \psi \rangle = \alpha\vert 0 \rangle + \beta\vert 1 \rangle`
```suggestion
# :math:`\hat{X}.` Therefore, an arbitrary qubit :math:`\vert \psi \rangle = \alpha\vert 0 \rangle + \beta\vert 1 \rangle`
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# bit-flip gate :math:`\bar{X}`. Similarly, a rotation operator by :math:`\pi/2` implements the Hadamard gate.
```suggestion
# bit-flip gate :math:`\bar{X}.` Similarly, a rotation operator by :math:`\frac{\pi}{2}` implements the Hadamard gate.
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +#     | Rotation            | .. figure:: ../demonstrations/photonics/Rotation.png         | *Hadamard* gate for :math:`\phi=\pi/2`.                             |
```suggestion
#     | Rotation            | .. figure:: ../demonstrations/photonics/Rotation.png         | *Hadamard* gate for :math:`\phi=\frac{\pi}{2}.`                             |
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# The natural number :math:`n` in the Fock :math:`\vert n \rangle` denotes the only possible
```suggestion
# repeated measurements of :math:`\hat{N}` on the same state will yield the same output.
# The natural number :math:`n` in the Fock state :math:`\vert n \rangle` denotes the only possible
```
It seems the word "state" has disappeared in multiple places in the demo :thinking:

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# This squeezed cannot be a Fock state!
```suggestion
# This squeezed state cannot be a Fock state!
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# probability distribution. Are they really different from classical states? Not that much and indeed, to build a universal photonic
the phrasing here was slightly awkward
Possible suggestion:
```suggestion
# probability distribution. Are they really different from classical states? Not that much! To build a universal photonic
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# squeezers and beamsplitters can entangle the input states!
```suggestion
# squeezers and beamsplitters can easily create entangled states!
```
Wasn't clear what "the input states" was here

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# The measurement of the number of photons takes a Gaussian and collapses it into a Fock state (although this destroys the photons);
```suggestion
# The measurement of the number of photons takes a Gaussian state and collapses it into a Fock state (although this destroys the photons);
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# therefore, photon number detection is not a Gaussian operation. Measuring the exact number of photons is not that easy.
```suggestion
# therefore, photon-number detection is not a Gaussian operation. Measuring the exact number of photons is not that easy.
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# We need fancy devices known a photon-number resolving detectors (PNRDs),
```suggestion
# We need fancy devices known a photon-number resolving detectors (commonly abbreviated as PNRs),
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# The circuit earned Jiuzhang, the quantum computer at the University of Science and Technology
```suggestion
# Large-scale versions of this circuit earned Jiuzhang, the quantum computer at the University of Science and Technology
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# application comes from removing the PNRD in the last wire, as shown below.
```suggestion
# application comes from removing the PNR in the last wire, as shown below.
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# The Wigner function does not have the shape of a Gaussian and moreover, it can be negative, a tell-tale feature of
```suggestion
# This Wigner function does not have the shape of a Gaussian and moreover, it can be negative—a tell-tale feature of
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# The figure below gives more detail on how to implement all the gates we need for
```suggestion
# The table below gives more detail on how to implement all the gates we need for
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# low temperatures are needed everywhere, in photonic quantum computers we only need them for the PNRDs to work.
```suggestion
# low temperatures are needed everywhere, in photonic quantum computers we only need them for the PNRs to work.
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# states. The fancy PNRDs are only required for qubit production!
```suggestion
# states. The fancy PNRs are only required for qubit production!
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# Since cryogenics are a bulky part of quantum computing architectures, photonic technology promises to be more scalable than, for example,
```suggestion
# Since cryogenics are a bulky part of quantum computing architectures, photonic technology promises to be more scalable than, for example,
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# Gaussian Boson Sampling circuits in parallel. Moreover, higher quality GKP states need larger circuits,
```suggestion
# Gaussian Boson Sampling circuits in parallel. Moreover, higher-quality GKP states need larger circuits,
```

2022-05-27 19:47 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +# The third criterion of long decoherence times seems inocuous at a first glance. However, although the quantum state of individual photons
```suggestion
# The third criterion of long decoherence times seems innocuous at a first glance. However, although the quantum state of individual photons
```

2022-05-27 20:03 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +# of quadrature measurements for a coherent in three dimensions, we obtain the following plot.
Forgot to change this to "the vacuum state" (I changed this image)

2022-05-27 20:03 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +# states only*, the density is exactly equal to the so-called `Wigner function <https://en.wikipedia.org/wiki/Wigner_quasiprobability_distribution>`__ :math:`W(x,p)`,
I'll add one line on this

2022-05-27 20:07 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
>  #    More generally, a coherent state is one that saturates the uncertainty relation. That is,
I got confused bc some people called squeezed states that saturate Heisenberg "Squeezed coherent states". I guess they just mean "coherent states" that have been squeezed. I've had the definition wrong in my head all this time...

2022-05-27 20:09 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +#     | Beamsplitter        | .. figure:: ../demonstrations/photonics/Beam_splitter.png    | An element with two input and two output qumodes. It transmits a           |
I think the beam splitter is flipped

2022-05-27 20:10 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +# Note that setting :math:`x=3` gave a displacement of 6 units in the horizontal direction in phase space.
I was wondering, don't know how I missed this XD

2022-05-27 20:16 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +ax1.set_xlim([-4, 4])
Yeah forgot to fix this one

2022-05-27 20:17 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +# The natural number :math:`n` in the Fock :math:`\vert n \rangle` denotes the only possible
Yes, sadly I deleted one word state and all got deleted. I noticed after like a day of other changes. I tried to recover them all but it seems I failed XD

2022-05-27 20:19 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +# We need fancy devices known a photon-number resolving detectors (PNRDs),
Let's not change PNRD for PNR everywhere. Name depends on the author (I've seen both used equally)

2022-05-27 20:20 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
>  # .. figure:: ../demonstrations/photonics/GBS.png
I saw it everywhere. Fine I'll change it, but it's risky! We might miss some!

2022-05-27 20:26 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
>  # .. figure:: ../demonstrations/photonics/gkp_wigner.png
It is colourblind (I checked!). I do like the fact that it uses blue (a cold colour) in places where the density is not high, and red (a warm colour) when the density is high. But if you have a preferred palette that you think would look better, do let me know!

2022-05-27 20:41 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +# Since cryogenics are a bulky part of quantum computing architectures, photonic technology promises to be more scalable than, for example,
?

2022-05-27 21:02 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
> +#     | Beamsplitter        | .. figure:: ../demonstrations/photonics/Beam_splitter.png    | An element with two input and two output qumodes. It transmits a           |
I was just following the colours of the beams

2022-05-27 21:03 UTC, co9olguy commented on demonstrations/tutorial_photonics.py
>  # .. figure:: ../demonstrations/photonics/gkp_wigner.png
no preference, anything is better than Jet imo :laughing:

2022-05-27 21:05 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_photonics.py
> +#     | Beamsplitter        | .. figure:: ../demonstrations/photonics/Beam_splitter.png    | An element with two input and two output qumodes. It transmits a           |
It's fixed now :)

2022-05-30 19:23 UTC, merged