[WIP] Demo on measurement-based quantum computation
PennyLaneAI/qml pull request #485
Opened 2022-05-04 21:24 UTC by soosub

### Before submitting

Please complete the following checklist when submitting a PR:

- [] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Add a thumbnail link to your tutorial in `beginner.rst`, or if a
      QML implementation, in `implementations.rst`.

- [ ] All QML tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:** Measurement-based quantum computation

**Summary:** A demo on measurement-based quantum computation

**Relevant references:**
- https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.86.5188
- https://quantum-journal.org/papers/q-2021-02-04-392/

**Possible Drawbacks:**

**Related GitHub Issues:**

2022-06-01 15:19 UTC, soosub commented
Resources:
- https://phas.ubc.ca/~raussen/Supplements/VideoLectures.html
- https://arxiv.org/pdf/1711.04921.pdf

2022-07-14 23:10 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +#
Ideally I automatically generate the html instead of uploading it separately

2022-07-26 15:44 UTC, soosub commented
Can someone add @isschoch and @mauriceweber as reviewers here?

2022-07-26 15:55 UTC, isschoch commented
Cannot wait to learn some cool stuff about MBQC!

2022-07-26 19:23 UTC, soosub commented on demos_quantum-computing.rst
> +    :tags: quantumcomputing
Somehow the gallery looks weird here. I tried to resolve it but have not found a solution yet.

![image](https://user-images.githubusercontent.com/44366402/181094285-c7f29e21-fc2a-4015-999d-493ca28224e3.png)

2022-07-26 19:24 UTC, soosub commented on requirements.txt
> +nbformat>=4.2.0
Some of these might be removed when the demo is finalised

2022-07-27 20:28 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +    qml.cond(m == 1, qml.PauliX)(wires=1)
Just a note that the circuit is not the same as the figure @radras

2022-07-27 20:31 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +print(qml.draw(cluster_state)())
To make the visualisation of the circuit more aesthetic, we can have a look at the comments in [this thread on slack](https://xanaduhq.slack.com/archives/C036VDB901W/p1653595712897369)

2022-07-27 21:53 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# so, we simply have to note that we have a *universal gate set* [#DiVincenzo]_. However, you might wonder - how
I want to reference the DiVincenzo criteria paper here, still need to do that

2022-07-27 21:53 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# 3-dimensional photonic graph state was created that was used to demonstrate quantum advantage.
We can show the Borealis graph state here with FlamingPy and mention that it is not a cluster state.

2022-07-27 21:54 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# ```````````````````````
In this section, we still want to add PennyLane snippets that show the equivalence between MBQC and the gate-based approach

2022-07-27 21:55 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# called quantum Turing machine (WTM) also known as a universal quantum computer. To do this, we
```suggestion
# called quantum Turing machine (QTM) also known as a universal quantum computer. To do this, we
```

2022-07-27 21:57 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +#
We need to explain the distinction between graph states and cluster states here, and why it is physically and QIT-ically different

2022-07-27 21:57 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +nx.draw(G, node_color='black')
Preferably, I want to have the figure a bit smaller

2022-07-27 22:18 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +#
Somehow this does not render properly on the website

2022-07-27 22:20 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# possible the first two Pauli terms. However, we can correct for these additional Pauli gates by
```suggestion
# Now note that this unitary :math:`\hat{U}` is related to our desired unitary :math:`U` up to 
# the first two Pauli terms. However, we can correct for these additional Pauli gates by 
```

2022-07-27 22:23 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +#
This section is still incomplete

2022-07-28 15:45 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +nx.draw(G, node_color='black')
and the linear chain should be straight

2022-07-28 15:47 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +#
I'd still like to explain dual and primal sheets, how it relates to the gate-based surface code etc.

2022-07-28 20:35 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +#
Here are some relevant references:

1. [Persistent Entanglement in Arrays of Interacting Particles](https://journals.aps.org/prl/pdf/10.1103/PhysRevLett.86.910)
2. [Entanglement in Graph States and its Applications](https://arxiv.org/abs/quant-ph/0602096)
3. Section on Cluster States by Hans Briegel in the _Compendium of Quantum Physics_

2022-07-28 20:36 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# 3-dimensional photonic graph state was created that was used to demonstrate quantum advantage.
There are some intricate differences between CV/DV lands that would make it too complicated for this demo so let's not do it.

2022-07-29 14:29 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +print(qml.draw(cluster_state)())
@KetpuntoG do you have any suggestions for this? Is there a better way than using the `draw` method here?

2022-07-29 14:30 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# Let's now see how this pans out in PennyLane. [WORK IN PROGRESS]
@radras can you take care of this?

2022-07-29 14:30 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# Let's now see how this pans out in PennyLane. [WORK IN PROGRESS]
and this too, please @radras?

2022-07-29 17:09 UTC, mauriceweber reviewed
Very nice demo!! I learned quite a bit about MBQC 🎉 

I think the main point from my side is to make a concrete example for translating an arbitrary quantum circuit to a measurement based quantum computation (it's still a bit for me to imagine how exactly this is achieved). 

The quantum error correction section is a nice intro, although probably quite hard for people who don't now anything about QEC. So making a simple example with a small quantum circuit would illustrate MBQC for a wider audience.

2022-08-04 22:25 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +#
Cool, I'll mention that this can be done with an Ising interaction or beamsplitters in case of photonics ⚡

2022-08-04 22:29 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# ... require Pauli measurements ... fully disentangle bla bla.
This is still a TODO

2022-08-05 01:17 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +#   Cluster state entanglement + adaptive arbitrary single-qubit measurements = universal quantum computer
This box quote looks a bit weird rn, we can change this to make it look better

2022-08-05 14:45 UTC, KetpuntoG reviewed
I leave you a few comments from the first part. On Monday I will finish the second half. I'm really enjoying it! Congratulations 😄
I think I understand the problem you commented @soosub . When talking about rotations you talk about 5 qubits but then you can't do more than one measurement, right? You could explain that those examples, the coefficients we know are zero and it is simplified somehow. But if not, it looks strange to see small circuits when you were expecting something with 5 qubits

2022-08-05 14:45 UTC, KetpuntoG commented on demonstrations/tutorial_mbqc.py
> +#    |\psi_{\mathrm{in}}\rangle.
I would have liked to follow the calculations, do you know any reference to put here to see it?

2022-08-05 18:04 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +    return qml.density_matrix(wires=[1])
Hmm in principle this should be a pure state, it's just that PennyLane does not support outputting the state vector if there was a mid-circuit measurement (which in general makes sense). Do you think we should still comment on this @KetpuntoG?

2022-08-05 18:05 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +    return qml.density_matrix(wires=[1])
Maybe we can show that the purity of the state / density matrix to get the point across

2022-08-05 18:05 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# teleportation. We start with one qubit in the state :math:`|\psi\rangle` that we want to transfer
Good call, we'll change that

2022-08-08 14:22 UTC, KetpuntoG commented on demonstrations/tutorial_mbqc.py
> +    return qml.density_matrix(wires=[1])
by putting a link to wikipedia of what the density matrix is the first time it appears, it will be enough :)

2022-08-08 17:37 UTC, radras commented on demonstrations/tutorial_mbqc.py
> +#
If you look at the examples with a single-qubit rotation and a CNOT gate you can see how the state "flows" from left to right and ends up at the rightmost qubits. Looking at this figure you can relate any T shape with a 2-qubit gate and any straight path with a 1-qubit gate. Hence, in a sense, the layout of the MBQC protocol resembles the graphical representation of a circuit in a gate-based form where information flows through time while here information flows through space as well.

2022-08-08 17:46 UTC, radras commented on demonstrations/tutorial_mbqc.py
> +#
Well, this is just a convention we chose, maybe we should briefly mention the other possibility of applying a Hadamard. I think that this is more natural since this is what is actually happening. Take for example a case where you want to first perform a single-qubit unitary and then a CNOT. You can initialize all of the required qubits into the cluster state in the beginning. Then after a single qubit gate, you will have a qubit that will hold the rotated state |psi>. This state can then be considered as an input into a CNOT protocol and there is no need for another Hadamard since it has been performed at the beginning of the entire calculation to generate the cluster state. So basically I did this so it resembles the latter examples but we can change it if you think this might be confusing.

2022-08-08 17:53 UTC, KetpuntoG reviewed
I have become a fan of MBQC! 🚀
I leave a couple more comments but I see it as very consistent

2022-08-08 17:53 UTC, KetpuntoG commented on demonstrations/tutorial_mbqc.py
> +# To start of, we define the :math:`R_z(\theta)` gate using two qubits with the gate-based approach.
remember to comment that being a case with 2 coefficients equal to 0, it is simplified and we do not need 5 qubits but 2. (same RX)

2022-08-08 17:53 UTC, KetpuntoG commented on demonstrations/tutorial_mbqc.py
> +#    ..
I missed the mathematical expression here. As you had done before in which expresses |phi_out> as a function of U and |phi_in>.

2022-08-08 17:53 UTC, KetpuntoG commented on demonstrations/tutorial_mbqc.py
> +# codes, named after Calderbank, Shor and Steane. CSS codes have stabilizers that exclusively contain
It would be great a link to deep into the CSS codes

2022-08-08 17:54 UTC, radras commented on demonstrations/tutorial_mbqc.py
> +#    |\psi_{\mathrm{in}}\rangle.
I added [this reference that I used](https://arxiv.org/pdf/2112.11601.pdf) although it doesn't have detailed derivations, I had to do some by hand to adapt the formulas for Rx and Rz.

2022-08-08 18:21 UTC, KetpuntoG commented on .github/workflows/build-dev.yml
> +          python-version: 3.8
by the way @soosub @radras , what are all these changes you are making in these files. It seems like it's something you shouldn't be modifying

2022-08-08 18:47 UTC, soosub commented on .github/workflows/build-dev.yml
> +          python-version: 3.8
I checked with @josh146 and if it doesn't break anything it's fine. We did it because FlamingPy requires Python 3.8.

2022-08-08 18:59 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# codes, named after Calderbank, Shor and Steane. CSS codes have stabilizers that exclusively contain
I don't understand what you mean @KetpuntoG

2022-08-08 19:36 UTC, KetpuntoG commented on demonstrations/tutorial_mbqc.py
> +# codes, named after Calderbank, Shor and Steane. CSS codes have stabilizers that exclusively contain
Sorry, I mean to put this [link](https://en.wikipedia.org/wiki/CSS_code), or another one for CSS codes

2022-08-08 20:13 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# codes, named after Calderbank, Shor and Steane. CSS codes have stabilizers that exclusively contain
Ah I see, I will find a good reference. The wiki on CSS codes is shit 🙈

2022-08-08 20:15 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +#
We can put your comment above in the demo @radras 😏

2022-08-08 20:22 UTC, KetpuntoG commented on demonstrations/tutorial_mbqc.py
> +#    |\psi_{\mathrm{in}}\rangle.
if it's not too complicated it would be great! 😄

2022-08-09 16:09 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +#
I will put this in text and adjust the figure so that's clear later this week 🖌️

2022-08-10 15:44 UTC, KetpuntoG reviewed
Completing the missing TODO's, for my part it's reviewed!
 As soon as it is ready, a second person will review and give the go-ahead 💪
 A very good demo topic, congratulations  🎉

2022-08-10 15:44 UTC, KetpuntoG commented on demonstrations/tutorial_mbqc.py
> +# condition that the underlying graph has to be a lattice. Physically, this means that TODO ...
I leave the comment so that this will not be forgotten

2022-08-10 15:44 UTC, KetpuntoG commented on demonstrations/tutorial_mbqc.py
> +# [#Hermans2022]_, [#Furusawa1998]_, [#Riebe2004], [#Nielsen1998]. Moreover, it has related applications
Rendering failure, maybe the "_" has something to do with it?

2022-08-10 15:44 UTC, KetpuntoG commented on demonstrations/tutorial_mbqc.py
> +# Note that we return `*density matrices* <https://en.wikipedia.org/wiki/Density_matrix>`_ in the
I think you wanted to put the bold print here. On the other hand, the clarification of the density matrix I would put it in the teleportation part since it is the first time where it appears

2022-08-10 15:44 UTC, KetpuntoG commented on demonstrations/tutorial_mbqc.py
> +# .. bio:: Joost Bus
The biographies have been decided to put in third person (I know that in your how-to it is in first person @soosub, but it will be changed)

2022-08-10 18:38 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# [#Hermans2022]_, [#Furusawa1998]_, [#Riebe2004], [#Nielsen1998]. Moreover, it has related applications
```suggestion
# [#Hermans2022]_, [#Furusawa1998]_, [#Riebe2004]_, [#Nielsen1998]_. Moreover, it has related applications
```

2022-08-10 18:38 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# [#Hermans2022]_, [#Furusawa1998]_, [#Riebe2004], [#Nielsen1998]. Moreover, it has related applications
It would be even nicer if we can group the references between one pair of brackets, do you know if that's possible @KetpuntoG ?

2022-08-10 18:40 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# .. bio:: Joost Bus
doesn't that sound terribly impersonal?

2022-08-10 18:40 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# .. bio:: Joost Bus
I prefer first person

2022-08-10 18:41 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# .. bio:: Joost Bus
*He prefers to speak in first person

2022-08-10 18:51 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# Note that we return `*density matrices* <https://en.wikipedia.org/wiki/Density_matrix>`_ in the
what line do you mean?

2022-08-10 18:53 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# Note that we return `*density matrices* <https://en.wikipedia.org/wiki/Density_matrix>`_ in the
@KetpuntoG do you know how to make the link text cursive?

2022-08-10 19:51 UTC, KetpuntoG commented on demonstrations/tutorial_mbqc.py
> +# Note that we return `*density matrices* <https://en.wikipedia.org/wiki/Density_matrix>`_ in the
I've been looking at a few demos and haven't seen any in cursive. I don't know how to do it 🤔

2022-08-10 19:58 UTC, josh146 commented on demonstrations/tutorial_mbqc.py
> +# Note that we return `*density matrices* <https://en.wikipedia.org/wiki/Density_matrix>`_ in the
Unfortunately, this is a limitation of reStructuredText. While it is generally much more powerful than markdown, unlike markdown it does not allow nested formatting!

There are [workarounds](https://stackoverflow.com/questions/4743845/format-text-in-a-link-in-restructuredtext) however, but they do feel a bit ugly.

2022-08-10 20:36 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# Note that we return `*density matrices* <https://en.wikipedia.org/wiki/Density_matrix>`_ in the
Thanks @josh146!

2022-08-10 20:39 UTC, KetpuntoG commented on demonstrations/tutorial_mbqc.py
> +# .. bio:: Joost Bus
Ok, you can leave the bio in 1 person 👌

2022-08-17 17:33 UTC, KetpuntoG commented
Hey! I cannot pass on the review to the next person until you complete the TODO's
Can you take a look at them? 🙂

2022-08-17 17:55 UTC, soosub commented
We're working on it @KetpuntoG 😌

2022-08-19 18:00 UTC, soosub commented on requirements.txt
> +flamingpy==0.9.0b0
this needs to be updated once FP PR#103 is in for the plotly plot

2022-08-19 19:23 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# :math:`R_x(\theta)` for arbitrary :math:`\theta \in [0, 2 \pi)`. Note that these two operations
Hey @radras, could you add some more explanation of why we use less qubits here? Maybe also include the citation of the paper that you used

2022-08-19 19:24 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +#
Can you include something that makes this clear in the text @radras?

2022-08-19 19:25 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +#    |\psi_{\mathrm{in}}\rangle.
Could you include this reference @radras?

2022-08-19 20:47 UTC, soosub commented
Hey it's ready for another review. I still have two questions though:
- How do I put the floor operation in here? It seems like there are some problems in the surface code figure caption. Is this because it's a caption?
- Can I combine references into one pair of brackets? I have a couple of places where we reference multiple papers but it comes out as [1] [2] [3]. It would be nice to have something like [1, 2, 3] as per usual.

2022-08-19 20:59 UTC, KetpuntoG commented
> Hey it's ready for another review. I have one questions about formatting though:
> 
> * Can I combine references into one pair of brackets? I have a couple of places where we reference multiple papers but it comes out as [1] [2] [3]. It would be nice to have something like [1, 2, 3] as per usual.

Thanks! 
Not to my knowledge. It is something that appears in other demos.
 If I find out, I'll let you know 👌

2022-08-19 21:08 UTC, soosub commented
Ready for review @KetpuntoG

2022-08-22 14:51 UTC, isaacdevlugt requested changes
Really great demo guys! Comments are all very minor. Nice work!

2022-08-22 14:51 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +
```suggestion
```

2022-08-22 14:51 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +
```suggestion
```

2022-08-22 14:51 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +np.allclose(RZ(theta, input_state), RZ_MBQC(theta, input_state))
🤯

2022-08-22 14:51 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +# Finally, we again compare the two implementations with random state as an input.
```suggestion
# Finally, we again compare the two implementations with a random state as an input.
```

2022-08-22 14:51 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +
Just tidying up the code to reduce scroll time!

2022-08-22 14:51 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +# computation, like how a blank sheet of paper is made separately from the text of a book.
Interesting analogy. I dig it 👍

2022-08-22 14:51 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +# Interestingly enough, we do not have to prepare all the entanglement at once. Just like we can
```suggestion
# Interestingly enough, we do not have to prepare all of the entanglement at once. Just like we can
```

2022-08-22 14:51 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +# cluster, while growing it at the same time, as shown in the figure below. That is, we can start
```suggestion
# cluster while growing it at the same time, as shown in the figure below. That is, we can start
```

2022-08-22 14:51 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +# tray!
You really went heavy into the printer paper analogy! 😆 I love it

2022-08-22 14:51 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +#
This is rendering as the figure caption. Is that on purpose?

2022-08-22 14:51 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +# context of photonics by interfering two modes with a beamsplitter.
```suggestion
# platform, and can, for example, be implemented with an Ising interaction [#OneWay2001]_ or, in the
# context of photonics, by interfering two modes with a beamsplitter.
```

2022-08-22 14:51 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +# it is also used in "classical" computing, memories and communication where one also has to deal `with
```suggestion
# reconstructing the logical data without losing any information. It is not exclusive to quantum computing;
# it is also used in "classical" computing, memories, and communication where one also has to deal `with
```

2022-08-22 14:51 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +# an example.
Excellent! :chefskiss:

2022-08-22 14:51 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +# .. figure:: ../demonstrations/mbqc/surface_code_d3.png
Nice!

2022-08-22 14:51 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +#    :file: ../demonstrations/mbqc/rhg-graph.html
Oooooo! Pretty! 

My only concern is that the interactive picture here is _very_ large... Can you make it smaller by default?

2022-08-22 14:51 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +# codes <https://errorcorrectionzoo.org/c/css>`_, named after Calderbank, Shor and Steane. CSS codes have stabilizers that exclusively contain
```suggestion
# codes <https://errorcorrectionzoo.org/c/css>`_, named after Calderbank, Shor, and Steane. CSS codes have stabilizers that exclusively contain
```

2022-08-22 14:51 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +# .. figure:: ../demonstrations/mbqc/gif_measuring.gif
🤩

2022-08-22 14:51 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +# Quantum error correction
I think it needs to be made clear somewhere in this section that you won't be showing any code for error correction in the MBQC formalism. I got to the end of this section and was a little surprised. Obviously, it's totally fine that there's no code in this section! It's already a very long and amazing demo!

2022-08-22 14:51 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +#   arbitrary single-qubit measurements on it is a universal quantum computer!**
Feels out of place 🤔

2022-08-22 14:51 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +# a 3-dimensional photonic graph state was created that was used to demonstrate quantum advantage.
```suggestion
# a 3-dimensional photonic graph state was created that was used to demonstrate quantum computational advantage.
```

2022-08-22 18:18 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# which is naturally limited by the speed of light.
Hmm what I tried to convey is that it's we don't have faster than light communication. Should we rephrase?

2022-08-22 18:19 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# Now, let's prepare a random qubit state and see if the teleportation protocol is working as
Do you want to omit the reason why we use density matrices?

2022-08-22 18:22 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +np.allclose(RX(theta, input_state), RX_MBQC(theta, input_state))
Shout out to @radras 🙌🏼

2022-08-22 18:25 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +#
Yes, do you think we should have a smaller caption and put the rest in the main text @isaacdevlugt?

2022-08-22 18:26 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +#    :file: ../demonstrations/mbqc/rhg-graph.html
I can make it smaller 👍🏼

2022-08-22 18:27 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# Quantum error correction
Alright, what do you think should we put something like "giving the gist of QEC in the MBQC framework" in the section introduction? @isaacdevlugt

2022-08-22 18:57 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +#   arbitrary single-qubit measurements on it is a universal quantum computer!**
Leave it out completely? Place it somewhere else? @isaacdevlugt

2022-08-22 19:54 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# This is a fairly simple cluster state, but we `will later see <#single-qubit-rotations>`_ how even
```suggestion
# This is a fairly simple cluster state, but we will later see how even
```

2022-08-22 20:08 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# Now, let's prepare a random qubit state and see if the teleportation protocol is working as
That seems to leave away a lot of info, don't you think? @isaacdevlugt

2022-08-22 20:38 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +#   arbitrary single-qubit measurements on it is a universal quantum computer!**
I'll leave it out

2022-08-22 20:41 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# Define helper function for random input state on n qubits
Hmm I prefer it this way

2022-08-22 20:43 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# The input qubit :math:`t_\mathrm{in}`, together with the intermediate qubits :math:`a_1`,
That will get a bit messy 🤔 You would have to keep track of density matrices and properly do the projective measurements. I don't think showing it here will make thinks clearer.

2022-08-23 18:18 UTC, soosub commented
```
from flamingpy.codes import SurfaceCode
from plotly.subplots import make_subplots
import plotly.graph_objects as go

# RHG lattice
RHG = SurfaceCode(3)

# Layout
size = 450
fig = make_subplots(rows=1, cols=2, 
                    specs=[[{'type':'scene'}, {'type':'scene'}]], 
                    column_titles=["Primal", "Dual"], 
                    horizontal_spacing = 0.02)
fig.update_layout(width=2*size, height=size)

# Primal
x = 2
fig1 = RHG.draw(backend="plotly", label=["type"], showbackground=True, width=size, height=size)
fig.update_layout(scene = dict(xaxis = {'nticks': 2, 'range': [x+0.5, x-0.5], 'dtick':1}), showlegend=False)
fig.update_layout(scene = dict(yaxis = {'dtick':1}))
fig.update_layout(scene = dict(zaxis = {'dtick':1}))
fig.add_trace(fig1.data[0], row=1, col=1)
fig.add_trace(fig1.data[1], row=1, col=1)

# Dual
x = 1
fig2 = RHG.draw(backend="plotly", label=["type"], showbackground=True, width=size, height=size)
fig.get_subplot(1,2)['xaxis'].update({'nticks': 2, 'range': [x+0.5, x-0.5]})
fig.get_subplot(1,2)['yaxis'].update({'dtick':1})
fig.get_subplot(1,2)['zaxis'].update({'dtick':1})
fig.add_trace(fig2.data[0], row=1, col=2)
fig.add_trace(fig2.data[1], row=1, col=2)

# Showing figure
fig.show(width=size, height=size)

# Saving figure
fig.write_image("primal_dual.jpeg")
fig.write_html("primal_dual.html")
```
![primal_dual](https://user-images.githubusercontent.com/44366402/186234209-c12350cd-46b5-4d2c-8a5d-739adb0f783c.jpeg)

2022-08-23 18:50 UTC, isaacdevlugt requested changes
Just addressing comments

2022-08-23 18:50 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +# Now, let's prepare a random qubit state and see if the teleportation protocol is working as
Hmm yea we can find some middle ground here. How about this?

```suggestion
# Note that we return a `density matrix <https://en.wikipedia.org/wiki/Density_matrix>`_ in the
# function above.
# This allows for us to describe operations beyond unitaries
# such as the teleportation protocol.
#
# Now, let's prepare a random qubit state and see if the teleportation protocol is working as
```

2022-08-23 18:50 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +# Define helper function for random input state on n qubits
okay! I would maybe leave comments in the code block then. E.g., 

```python
def generate_random_state(n=1):
    input_state = np.random.random(2 ** n) + 1j * np.random.random(2 ** n) # psi = alpha |0> + beta |1>`
    return input_state / np.linalg.norm(input_state)
```

or something like that

2022-08-23 18:50 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +# The input qubit :math:`t_\mathrm{in}`, together with the intermediate qubits :math:`a_1`,
Okay! Good to know. Was just wondering if it would be feasible.

2022-08-23 18:50 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +# .. math:: |\psi_{\mathrm{out}}\rangle = \hat{U}(\alpha, \beta, \gamma)|\psi_{\mathrm{in}}\rangle
It's a small pet peeve of mine that we don't put hats on anything to begin with, but it's a settled-upon convention in the quantum community so it is what it is. But, either everything should have a hat on it, or no hats at all in my opinion. 

I'd opt for no hats _anywhere_, and then renaming `\hat{U}` to something else, like `V` for example.

2022-08-23 18:50 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +#
No I think it's fine, but just make it a bit more explicit that it is indeed a figure caption. E.g.

```suggestion
#    A diagrammatic perspective on simultaneously consuming and growing a cluster state.
#    The blue qubits are in a cluster state,
#    where the bonds between them represent entanglement. The gray qubits have been measured,
#    destroying the entanglement and removing them from the cluster. At the same time, the green
#    qubits are being added to the cluster by entangling them with it. Prior measurement outcomes
#    determine the basis for future measurements [#OpticalQuantumComputing]_.
#
```

2022-08-23 18:50 UTC, isaacdevlugt commented on demonstrations/tutorial_mbqc.py
> +# Quantum error correction
Yeah something like that! Maybe slightly less conversational. I wouldn't use "gist"

2022-08-23 19:49 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# .. math:: |\psi_{\mathrm{out}}\rangle = \hat{U}(\alpha, \beta, \gamma)|\psi_{\mathrm{in}}\rangle
Ah I see the confusion. I am using the hat just to make clear that U and \hat{U} are different, not to designate that \hat{U} is a operator. I could use a tilde or apostrophe instead @isaacdevlugt

2022-08-23 19:49 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +#
👍🏼

2022-08-23 20:34 UTC, soosub reviewed
Just adding a note here that the demo should not be posted before these changes are added to FlamingPy

2022-08-23 20:34 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# RHG.draw(backend="plotly", label=["type"], showbackground=True) #TODO: uncomment this line after merging FP#103
TODO ⚠️

2022-08-24 03:51 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +#
@ilantz I think I might have interchanged primal/dual. Am I correct?

2022-08-24 21:44 UTC, josh146 commented on requirements.txt
> +git+https://github.com/XanaduAI/flamingpy@main
```suggestion
git+https://github.com/XanaduAI/flamingpy.git
```

2022-08-24 21:55 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# RHG.draw(backend="plotly", label=["type"], showbackground=True) #TODO: uncomment this line after merging FP#103
Installing it with git causes errors for some reason. We might need to wait for this month's release of FlamingPy before publishing.

2022-08-25 21:21 UTC, ilan-tz commented on demonstrations/tutorial_mbqc.py
> +# universal quantum computation discussed in the previous section. The error correcting code that you want to implement
```suggestion
# In the measurement-based picture, successive rounds of quantum error correction requires generating cluster states
# that are at least 3-dimensional [#XanaduBlueprint]_, contrary to the 2-dimensional cluster states required for
# universal quantum computation discussed in the previous section. The error correcting code that you want to implement
```

2022-08-25 21:21 UTC, ilan-tz commented on demonstrations/tutorial_mbqc.py
> +# For these CSS codes, you can view the primal and dual sheets as measuring the
```suggestion
# For these CSS codes, you can roughly view the primal and dual sheets as measuring the
```

2022-08-25 21:21 UTC, ilan-tz commented on demonstrations/tutorial_mbqc.py
> +#
Primal sheets are at even Z slices, so they are flipped in the figure

2022-08-25 21:21 UTC, ilan-tz commented on demonstrations/tutorial_mbqc.py
> +# entanglement together with adaptive arbitrary single-qubit measurements allows for universal
```suggestion
# entanglement together with adaptive arbitrary single-qubit measurements allows for universal
```
Consider modifying in light of my comments above

2022-08-25 21:21 UTC, ilan-tz commented on demonstrations/tutorial_mbqc.py
> +# reliable way to produce qubits and stitch them together through entanglement, we can use it to
```suggestion
# This feature makes it particularly attractive for photonic quantum computers: we can use
# expendable qubits that don't have to stick around for the full calculation. If we can find a
# reliable way to produce qubits and stitch them together through entanglement, we can use it to
```
The don't stick around, but they also can't, because they are likely to be lost or corrupted by loss

2022-08-25 21:21 UTC, ilan-tz commented on demonstrations/tutorial_mbqc.py
> +# useful in platforms that allow for many expendable qubits, and offers
Consider: platforms with flying qubits and easy physical entangling gates

2022-08-25 21:21 UTC, ilan-tz commented on demonstrations/tutorial_mbqc.py
> +# off-line which is often simpler to implement.
For photonics: the depth of the optical circuit should not increase with the depth of the logical circuit because (a) the losses become intolerable, and (b) for encodings with probabilistic gates, e.g. dual rail entangling gates, the success probability of the computation will exponentially decay

2022-08-25 21:21 UTC, ilan-tz commented on demonstrations/tutorial_mbqc.py
> +# paper <https://arxiv.org/abs/quant-ph/0403025>`_ [#MagicStates]_.
Ah, I see you address this. I think it may be worthwhile to insinuate this earlier on

2022-08-25 21:21 UTC, ilan-tz commented on demonstrations/tutorial_mbqc.py
> +# a 3-dimensional photonic graph state was created that was used to demonstrate quantum computational advantage.
![image](https://user-images.githubusercontent.com/57886357/186771104-8cd3ac7f-0240-4cd7-953d-49bfd4623e84.png)

2022-08-25 21:26 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +nx.draw(G, pos={node: node for node in G}, node_size=500, node_color="black")
I think that might complicate things too much.

2022-08-25 21:37 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# measurements.
first worry, then perform 😌

2022-08-25 21:43 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# a 3-dimensional photonic graph state was created that was used to demonstrate quantum computational advantage.
What do you mean? Don't you think graph state is the right term? @ilan-tz

2022-08-25 22:50 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +#    A distance-3 surface code. Circles represent qubits and bubbles represent operators, called
```suggestion
#    A distance :math:`d=3` surface code. Circles represent qubits and bubbles represent operators, called
```

2022-08-25 22:52 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +#
@josh146 do you happen to know if this is possible? It seems like the plotly output is not shown 😢

2022-08-25 22:53 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +#
I guess this might be related: https://github.com/readthedocs/sphinx_rtd_theme/issues/788

2022-08-25 23:01 UTC, soosub commented on requirements.txt
> +git+https://github.com/XanaduAI/flamingpy@mbqc-demo
> **Warning**: this will fail once the branch is deleted. I opened up a [PR here](https://github.com/XanaduAI/flamingpy/pull/118) to get the changes from the `mbqc-demo` branch in flamingpy, but eventually we'd want to use the `pip` version anyway.

2022-08-26 14:58 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# entanglement together with adaptive arbitrary single-qubit measurements allows for universal
I think it makes sense to assume that ability here, and then later state that this is not a strict requirement. What do you think?

2022-08-26 14:58 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# entanglement together with adaptive arbitrary single-qubit measurements allows for universal
https://github.com/PennyLaneAI/qml/pull/485/files#r955431398 nevermind 😌

2022-08-26 14:59 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# entanglement together with adaptive arbitrary single-qubit measurements allows for universal
I mention the assumption now in the section on universality 👍🏼

2022-08-26 16:13 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# Arbitrary single-qubit rotations are an essential operation for a universal quantum computer. In
imo that's just a different interpretation - they are just implemented in a different way (and still essential)

2022-08-26 18:23 UTC, soosub commented on requirements.txt
> +git+https://github.com/XanaduAI/flamingpy@mbqc-demo
Fixed https://github.com/XanaduAI/flamingpy/pull/118

2022-08-26 18:26 UTC, soosub commented on requirements.txt
> +plotly>=4.5.0
Plotly can be uninstalled when FlamingPy is installed with `pip`. However, this should wait until this month's (August 2022) release of FlamingPy.

2022-08-26 18:44 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +# a 3-dimensional photonic graph state was created that was used to demonstrate quantum computational advantage.
Just had a talk with Raf: he agreed and I will just drop the connection with the Borealis experiment

2022-08-26 18:46 UTC, soosub commented on demonstrations/tutorial_mbqc.py
> +#    ..
@radras

2022-08-26 18:49 UTC, soosub commented
@KetpuntoG @isaacdevlugt I addressed all the comments. There are little things that @radras might want to address still, but I don't think they are strictly necessary. We could always update the demo in the future. I will leave the finalisation in your capable hands 👍🏼

2022-09-09 16:41 UTC, KetpuntoG commented
Don't worry about updating the branch @soosub , the demo is perfect 😄 when we upload it we will update everything

2022-09-09 16:49 UTC, soosub commented
@KetpuntoG I was planning to address [this ](https://github.com/PennyLaneAI/qml/pull/485#discussion_r956315514) now the FlamingPy August release is out but there [seem to be some issues](https://xanadu-quantum.slack.com/archives/C03MEBR3T5E/p1662741868767199?thread_ts=1661910934.558379&cid=C03MEBR3T5E) 🥵

2022-09-09 17:24 UTC, KetpuntoG commented
> @KetpuntoG I was planning to address [this ](https://github.com/PennyLaneAI/qml/pull/485#discussion_r956315514) now the FlamingPy August release is out but there [seem to be some issues](https://xanadu-quantum.slack.com/archives/C03MEBR3T5E/p1662741868767199?thread_ts=1661910934.558379&cid=C03MEBR3T5E) 🥵

Ah okey! Let's see if Narinam answer you :)

2022-09-19 18:56 UTC, isaacdevlugt approved these changes
My comments were addressed or resolved!

2022-12-05 22:18 UTC, merged

2022-12-05 22:20 UTC, KetpuntoG commented
@soosub , @radras thanks for this great demo! 
Tomorrow we will announce the release of this demo on Pennylane twitter 🚀