Demo fewdata
PennyLaneAI/qml pull request #489
Opened 2022-05-13 13:44 UTC by BestQuark

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Add a thumbnail link to your tutorial in `beginner.rst`, or if a
      QML implementation, in `implementations.rst`.

- [ ] All QML tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:** DEMO: Generalization in quantum machine learning from few training data

**Summary:**  This is a demo of the paper "Generalization in quantum machine learning from few training data". We train a QCNN for classifying states in different phases.

**Relevant references:** [https://arxiv.org/abs/2111.05292](https://arxiv.org/abs/2111.05292)

**Possible Drawbacks:**

**Related GitHub Issues:**

2022-05-26 21:25 UTC, Qottmann commented
On another note:
Since there are a lot of for-loops going through the 200 data points, it is really worth it incorporating dask. I dont know too much about it, but basically you can easily parallelize for loops by just doing `dask.delayed(fn)(x)` instead of `fn(x)` in a for loop.

Two empirical examples on the speed ups.  
1. When generating the data
```python
>>> %timeit res = np.array([dask.delayed(ising)(h, n_wires) for h in hs], dtype=object)
26 ms ± 260 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
vs
```python
>>> %timeit res = np.array([ising(h, n_wires) for h in hs], dtype=object)
17.5 s ± 408 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

or when calculating the accuracy or loss function (again looping through the whole or part of the dataset):
```python
>>> %timeit loss_fn_dask(weights, weights_last, data, labels)
54.5 ms ± 318 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
vs
```python
>>> %timeit loss_fn(weights, weights_last, data, labels)
23.9 s ± 92.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

I think it doesnt substantially complicate the code and yields an immense performance boost. In case it is not recommended to use these tools in demos we can just remove the `dask.delayed()` part when we finalize it (and have longer for loop executions, but still within reason, i.e. total demo time ~< 10 min)

2022-05-27 20:01 UTC, mauriceweber commented
@Qottmann the problem might be the optimization -- it shouldn't be that sensitive to the initialization. Can you try using a smaller learning rate (0.01 or 0.001) and the Adam Optimizer?

2022-07-13 13:10 UTC, mauriceweber commented
> 
I think you can wrap the plot creating code under a `with plt.xkcd():` statement to get something which looks like a sketch (https://matplotlib.org/stable/gallery/showcase/xkcd.html#sphx-glr-gallery-showcase-xkcd-py).

2022-07-13 18:56 UTC, Qottmann commented
I have now `vmap` for vectorization and `jax.jit` for just-in-time compilation on the accuracy and cost functions and got a speedup of 3 orders of magnitude per evaluation. The total notebook now executes in 35 seconds or 15 seconds (jitted).

However, the results are nonsensical/constant at the moment, I probably put a global variable somewhere instead of an argument.

2022-07-19 22:08 UTC, Qottmann commented
@josh146 Is there a way to import `optax` for this demo? I am following a comment of yours when optimizing with jax from an older forum post: https://discuss.pennylane.ai/t/jax-and-pennylane-optimizers/1752/4

2022-07-21 19:26 UTC, Qottmann commented
I'm a bit at a loss with the issue upon importing `jax` in the CI actions. Locally everything works fine. I also tried updating to `jax==3.1.14` in the requirements file, still failing.

2022-07-26 21:34 UTC, mauriceweber commented
@CatalinaAlbornoz can you add @soosub as a reviewer here?

2022-08-08 19:34 UTC, soosub reviewed
Very well written! Especially the first part was a pleasure to read. I think the demo could be upgraded with some figures to illustrate the different layers and possibly also depict the quantum layers/parts of the QCNN. In that way, you can communicate the main ideas within a single glance. Other than that, I only left a couple of style/language/consistency comments.

Great work 👍🏼

2022-08-08 19:34 UTC, soosub commented on demonstrations/tutorial_learning_few_data.py
> +# this case, are ``qml.U3`` gates. Then, we apply these conditional measurements to half of the
You can link directly to the docs which might be nice, see https://github.com/PennyLaneAI/qml/pull/533#discussion_r939221467

2022-08-08 19:34 UTC, soosub commented on demonstrations/tutorial_learning_few_data.py
> +# this case, are ``qml.U3`` gates. Then, we apply these conditional measurements to half of the
https://github.com/PennyLaneAI/qml/blob/master/demonstrations/tutorial_vqe.py#L116

```
# In this figure, the gate :math:`G^{(2)}` corresponds to the
# :class:`~.pennylane.DoubleExcitation` operation
```

2022-08-08 19:34 UTC, soosub commented on demonstrations/tutorial_learning_few_data.py
> +# to be updated in each training round.  In ``pennylane``, we model this arbitrary two-qubit unitary
```suggestion
# The convolutional layer requires the weights of the two-qubit unitary as input. These weights are
# to be updated in each training round.  In ``pennylane``, we model this arbitrary two-qubit unitary
```

2022-08-08 19:34 UTC, soosub commented on demonstrations/tutorial_learning_few_data.py
> +# to be updated in each training round.  In ``pennylane``, we model this arbitrary two-qubit unitary
Another small comment: In other tutorials people stylize PennyLane. You are consistent within the demo, but it might be good to be consistent with the other demos too. What do you think?

2022-08-08 19:34 UTC, soosub commented on demonstrations/tutorial_learning_few_data.py
> +# parametrized by one parameter), and end with two additional ``qml.U3`` gates in each of the two
```suggestion
# with a particular sequence of gates: two single-qubit gates ``qml.U3``, each parametrized by three
# parameters, followed by three Ising interactions between both qubits, each parametrized by one parameter, 
# and end with two additional ``qml.U3`` gates in each of the two
```

2022-08-08 19:34 UTC, soosub commented on demonstrations/tutorial_learning_few_data.py
> +# parametrized by one parameter), and end with two additional ``qml.U3`` gates in each of the two
imo "on each of the two qubits" sounds a bit better

2022-08-08 19:34 UTC, soosub commented on demonstrations/tutorial_learning_few_data.py
> +def conv_net(weights, last_layer_weights, features):
Would it be possible to depict the full circuit? Or maybe one layer per figure? That would help a lot for understanding the structure

2022-08-08 19:34 UTC, soosub commented on demonstrations/tutorial_learning_few_data.py
> +def conv_net(weights, last_layer_weights, features):
A small note on what jax is would also be nice

2022-08-08 19:34 UTC, soosub commented on demonstrations/tutorial_learning_few_data.py
> +digits = datasets.load_digits()
why twice? Is there a reason why there is a semicolon? For suppressing the output?
```suggestion
digits = datasets.load_digits()
```

2022-08-08 19:34 UTC, soosub commented on demonstrations/tutorial_learning_few_data.py
> +# In this demo, we are going to classify the digits ``0`` and ``1`` from the classical ``digits`` dataset.
QML $\gg$ classical ML 😉

2022-08-08 19:34 UTC, soosub commented on demonstrations/tutorial_learning_few_data.py
> +#     Further, we use ``jax.vmap`` to vectorize the execution of the QCNN over all input states (as opposed to looping through the training and test set at every execution)
This is not rendered correctly
![image](https://user-images.githubusercontent.com/44366402/183498400-0e6e15d6-4024-4da6-a244-fd9f0eaef6dc.png)

2022-08-08 19:34 UTC, soosub commented on demonstrations/tutorial_learning_few_data.py
> +
there is a UserWarning here

```
train qcnn:   0%|          | 0/100 [00:00<?, ?it/s]/home/runner/work/qml/qml/venv/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py:4488: UserWarning: Explicitly requested dtype <class 'jax.numpy.complex128'> requested in astype is not available, and will be truncated to dtype complex64. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.
  lax_internal._check_user_dtype_supported(dtype, "astype")
```

![image](https://user-images.githubusercontent.com/44366402/183498672-c216024d-ae5b-4ba6-bea1-0b8fc4aee553.png)

2022-08-08 19:34 UTC, soosub commented on demonstrations/tutorial_learning_few_data.py
> +def make_plot(df, n_train):
Nice plot style 😎

2022-08-08 19:34 UTC, soosub commented on demonstrations/tutorial_learning_few_data.py
> +    # plot train acc vs test acc
There is no scale here. What do you guys think, would it be relevant here?

2022-08-17 18:40 UTC, BestQuark commented on demonstrations/tutorial_learning_few_data.py
> +# to be updated in each training round.  In ``pennylane``, we model this arbitrary two-qubit unitary
Sounds good, I'll change this format!

2022-08-17 18:54 UTC, BestQuark commented on demonstrations/tutorial_learning_few_data.py
> +# this case, are ``qml.U3`` gates. Then, we apply these conditional measurements to half of the
Amazing, will change this!

2022-08-17 19:00 UTC, BestQuark commented on demonstrations/tutorial_learning_few_data.py
> +# parametrized by one parameter), and end with two additional ``qml.U3`` gates in each of the two
updated! ✅

2022-08-17 19:03 UTC, BestQuark commented on demonstrations/tutorial_learning_few_data.py
> +# **Let's break down each layer:**
Updated! ✅

2022-08-17 19:04 UTC, BestQuark commented on demonstrations/tutorial_learning_few_data.py
> +#     Further, we use ``jax.vmap`` to vectorize the execution of the QCNN over all input states (as opposed to looping through the training and test set at every execution)
Fixed! ✅

2022-08-17 19:26 UTC, BestQuark commented on demonstrations/tutorial_learning_few_data.py
> +# information about such an array. In addition, depending on the purpose of your CNN, one might want
Figure added ✅

2022-08-18 16:04 UTC, KetpuntoG reviewed
Overall it looks good, good job! 💪
The fundamental point of the demo is the number of samples to be worked with. I think that in the code part is something that you have to put something more emphasis , In the example that you have taken you are using n qubits then we would need m images because blah blah blah blah

maybe comment on what happens if you take less or more images in this case

2022-08-22 15:26 UTC, Qottmann commented on demonstrations/tutorial_ml_classical_shadows.py
> +        kernel_NN.at[i,j].set(
I guess these diffs are coming from someone running black on the whole folder? Can you who is guilty of that reverse that please? 🙏

2022-08-22 18:36 UTC, mauriceweber commented on demonstrations/tutorial_learning_few_data.py
> +.. math:: R(\alpha) = \mathbb{E}_{(x,y)\sim P}[\ell(\alpha;\,x,\,y)].
yep it's the label. I added an explanation for that:)

2022-08-22 18:36 UTC, mauriceweber commented on demonstrations/tutorial_learning_few_data.py
> +.. math:: \mathrm{gen}(\alpha) = \hat{R}_S(\alpha) - R(\alpha)
We don't need an absolute value here, but I realized that I wrote it down in the wrong order. It should be:

$$
\mathrm{gen}(\alpha) =  R(\alpha) - \hat{R}_S(\alpha)
$$

Upper bounding this quantity gives you a bound on the true Risk $R(\alpha)$

2022-08-22 18:36 UTC, mauriceweber commented on demonstrations/tutorial_learning_few_data.py
> +# gates :math:`M` which have been reused. Naively, one could suspect that the generalization error scales as
reused means shared across wires (i.e. reusing the same parameters on different wires). I have changed it to

> However, as is the case for quantum convolutional neural networks, it is possible to get a more fine-grained bound by including knowledge on the number :math:`M` of gates which have been reused (i.e. whose parameters are shared across wires).

What do you think?

2022-08-22 18:36 UTC, mauriceweber commented on demonstrations/tutorial_learning_few_data.py
> +# the number of samples needed for good generalization to the system size :math:`n` since these models
yep, done :+1:

2022-08-22 18:36 UTC, mauriceweber commented on demonstrations/tutorial_learning_few_data.py
> +# perform image processing. To achieve this goal, one uses what is known as a *convolutional layer*,
agreed, I changed the wording of the first sentence to:
> Classical CNNs are a family of neural networks which make use of convolutions and pooling operations to insert an inductive bias, favoring invariances to spatial transformation like translations, rotations and scaling.

2022-08-22 18:40 UTC, BestQuark commented on demonstrations/tutorial_learning_few_data.py
> +
Yes, the repeated convolution layer is expected twice. I've added this to the explanation :)

2022-08-22 19:18 UTC, mauriceweber commented on demonstrations/tutorial_learning_few_data.py
> +# To deal with this dimensionality difference, one uses what is known as a *pooling layer*. These
I put in a reference to the DL book for more in depth explanations -- we don't wanna end up focussing too much on the classical CNNs here

2022-08-22 20:07 UTC, BestQuark commented on demonstrations/tutorial_learning_few_data.py
> +# qubits of the final state using an all-to-all unitary gate.
Great, I've added this in the demo!

2022-08-22 20:19 UTC, BestQuark commented on demonstrations/tutorial_ml_classical_shadows.py
> +        kernel_NN.at[i,j].set(
Reverted ✅ 💃

2022-08-22 20:45 UTC, BestQuark commented on demonstrations/tutorial_learning_few_data.py
> +##############################################################################
Done :) ✅

2022-08-22 20:47 UTC, BestQuark commented on demonstrations/tutorial_learning_few_data.py
> +def conv_net(weights, last_layer_weights, features):
Yes! we've added this :)

2022-08-23 19:01 UTC, KetpuntoG commented on demonstrations/tutorial_learning_few_data.py
> +    ), f"The size of the last layer weights vector is incorrect! \n Expected {4 ** (len(wires)) - 1}, Given {last_layer_weights.size}"
try to make this line shorter

2022-08-23 19:01 UTC, KetpuntoG commented on demonstrations/tutorial_learning_few_data.py
> +
to avoid the warning in the deploy, you have to write plt.plot()

2022-08-23 19:43 UTC, BestQuark commented on demonstrations/tutorial_learning_few_data.py
> +    ), f"The size of the last layer weights vector is incorrect! \n Expected {4 ** (len(wires)) - 1}, Given {last_layer_weights.size}"
Perfect, it's changed now ✅

2022-08-24 15:42 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_learning_few_data.py
> +It is good to know that generalization can be seen as a manifestation of the bias-variance trade-off: models that
```suggestion
Generalization can be seen as a manifestation of the bias-variance trade-off: models that
```

2022-08-24 15:47 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_learning_few_data.py
> +What is Generalization in (Q)ML?
```suggestion
What is generalization in (Q)ML?
```

2022-08-24 15:48 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_learning_few_data.py
> +
Explain terms in your formulas. E.g what is $\ell?, $R$...

2022-08-24 15:49 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_learning_few_data.py
> +.. math:: \hat{R}_S(\alpha) = \frac{1}{N}\sum_{i=1}^N \ell(\alpha;\,x_i,\,y_i)
```suggestion
.. math:: \hat{R}_S(\alpha) = \frac{1}{N}\sum_{i=1}^N \ell(\alpha;\,x_i,\,y_i),
```

2022-08-24 15:49 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_learning_few_data.py
> +.. math:: \mathrm{gen}(\alpha) =  R(\alpha) - \hat{R}_S(\alpha)
```suggestion
.. math:: \mathrm{gen}(\alpha) =  R(\alpha) - \hat{R}_S(\alpha),
```

2022-08-24 15:49 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_learning_few_data.py
> +# Generalization Bounds for Quantum Machine Learning Models
```suggestion
# Generalization bounds for Quantum Machine Learning models
```

2022-08-24 15:52 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_learning_few_data.py
> +# For a more in-depth explanation of CNNs, we highly recommend `chapter 9 <https://www.deeplearningbook.org/contents/convnets.html>`
hyperlink not rendering properly

2022-08-24 15:52 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_learning_few_data.py
> +# in [#DLBook]_ which is dedicated to CNNs.
```suggestion
# in [#DLBook]_..
```

2022-08-24 15:52 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_learning_few_data.py
> +# in [#DLBook]_ which is dedicated to CNNs.
Let's avoid repetition

2022-08-24 15:53 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_learning_few_data.py
> +#
Love this figure 😍

2022-08-24 15:53 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_learning_few_data.py
> +# follow the QCNN construction proposed by [#CongQuantumCNN]_. The former layer
```suggestion
# follow the QCNN construction proposed in [#CongQuantumCNN]_. The former layer
```

2022-08-24 15:53 UTC, Qottmann commented on demonstrations/tutorial_learning_few_data.py
> +# For a more in-depth explanation of CNNs, we highly recommend `chapter 9 <https://www.deeplearningbook.org/contents/convnets.html>`
```suggestion
# For a more in-depth explanation of CNNs, we highly recommend `chapter 9 <https://www.deeplearningbook.org/contents/convnets.html>`_
```

2022-08-24 15:54 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_learning_few_data.py
> +#     QCNN architecture. Taken from [#CongQuantumCNN]_.
Great! I think this figure needs a bit more explaining in the context that you were explaining above. You can explain a little in the caption.

2022-08-24 15:55 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_learning_few_data.py
> +# with a particular sequence of gates: two single-qubit gates :class:`~.pennylane.U3` (parametrized by three
```suggestion
# with a particular sequence of gates: two single-qubit  :class:`~.pennylane.U3` gates (parametrized by three
```

2022-08-24 15:56 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_learning_few_data.py
> +
This whole description could use an image so that it's more clear in the readers' heads.

2022-08-24 15:57 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_learning_few_data.py
> +# The pooling layer has as inputs the weights of the single-qubit conditional unitaries, which in
```suggestion
# The pooling layer's inputs are the weights of the single-qubit conditional unitaries, which in
```

2022-08-24 15:58 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_learning_few_data.py
> +# The pooling layer has as inputs the weights of the single-qubit conditional unitaries, which in
Let's always try to make sentences less wordy 💪

2022-08-24 15:59 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_learning_few_data.py
> +
☝️

2022-08-24 16:02 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_learning_few_data.py
> +
Still there, any way to remove it?

2022-08-24 16:07 UTC, alvaro-at-xanadu requested changes
Great work! I'm not an expert on this topics but I do feel I learned a lot!  I do feel that a closing paragraph is very much needed; as is, the ending is a bit anti-climatic 😅

2022-08-24 19:18 UTC, mauriceweber commented on demonstrations/tutorial_learning_few_data.py
> +
oh right, thanks for pointing that out!

2022-08-24 20:13 UTC, mauriceweber commented on demonstrations/tutorial_learning_few_data.py
> +    :align: center
yeah I agree -- I created a new figure which shows the bias-variance trade off a bit better and also added some explanation before figure. What do you think?

2022-08-25 13:57 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_learning_few_data.py
> +    :align: center
Great!

2022-08-25 20:59 UTC, isaacdevlugt requested changes
Great demo guys! Most comments are grammar. Please add a conclusion that breaks everything down succinctly 😄

2022-08-26 14:46 UTC, mauriceweber commented on demonstrations/tutorial_learning_few_data.py
> +.. math:: \mathrm{gen}(\alpha) =  R(\alpha) - \hat{R}_S(\alpha),
I think generally it is fine because one is only interested in upper bounding the generalization error... it's also the same way how they have defined it in the paper.

2022-08-26 14:47 UTC, BestQuark commented on demonstrations/tutorial_learning_few_data.py
> +
there is no more warning 🚀

2022-08-26 15:00 UTC, BestQuark commented on demonstrations/tutorial_learning_few_data.py
> +    pooling_layer(kernel_weights[15:], n_wires)
It's not clear to me how to do this. One could think on having a window of 3 qubits, or $n$, but there is no generalized `qml.IsingXX`, `qml.IsingYY`, etc. So this convolutional structure could take a lot of forms, and they might not be optimal if chosen incorrectly. I think if we stick to two-qubit neighbouring interaction as it atm is the quickest and cleanest solution

2022-08-26 15:29 UTC, BestQuark commented on demonstrations/tutorial_learning_few_data.py
> +# .. figure:: /demonstrations/learning_few_data/cnn_pic.png
We've added a caption explaining a bit more what these two layers are and added a reference to a chapter on CNNs of a great deep learning book! :)

2022-08-26 18:30 UTC, BestQuark commented on demonstrations/tutorial_learning_few_data.py
> +
It's fixed ✅

2022-08-26 18:32 UTC, BestQuark commented on demonstrations/tutorial_learning_few_data.py
> +# .. figure:: /demonstrations/learning_few_data/cnn_pic.png
We have removed the long caption because it did not look very good! but the reference is kept

2022-08-29 17:48 UTC, isaacdevlugt submitted a review, later dismissed
A few things still needed

2022-08-29 17:48 UTC, isaacdevlugt commented on demonstrations/tutorial_learning_few_data.py
> +#     A graphical representation of a CNN. Obtained using [#LeNailNNSVG]_.
```suggestion
#     A graphical representation of a CNN. Obtained using Ref. [#LeNailNNSVG]_.
```

2022-08-29 17:48 UTC, isaacdevlugt commented on demonstrations/tutorial_learning_few_data.py
> +#     QCNN architecture. Taken from [#CongQuantumCNN]_.
```suggestion
#     QCNN architecture. Taken from Ref. [#CongQuantumCNN]_.
```

2022-08-29 19:02 UTC, isaacdevlugt commented on demonstrations/tutorial_learning_few_data.py
> +For the example of a Quantum Convolutional Neural Network (QCNN), we show how its generalization error behaves as a
```suggestion
For the example of a `Quantum Convolutional Neural Network (QCNN) <https://pennylane.ai/qml/glossary/qcnn.html>`_, we show how its generalization error behaves as a
```

2022-08-29 19:03 UTC, isaacdevlugt commented on demonstrations/tutorial_learning_few_data.py
> +distribution of interest, for example, images of cats and dogs. However, in practice, we are limited to a finite amount of
```suggestion
distribution of interest (e.g., images of cats and dogs). However, in practice, we are limited to a finite amount of
```

2022-08-29 19:03 UTC, isaacdevlugt commented on demonstrations/tutorial_learning_few_data.py
> +called the *generalization error* and indicates how well the model has learned to generalize to unseen data.
```suggestion
called the *generalization error*, and it indicates how well the model has learned to generalize to unseen data.
```

2022-08-29 19:04 UTC, isaacdevlugt commented on demonstrations/tutorial_learning_few_data.py
> +Generalization can be seen as a manifestation of the bias-variance trade-off: models that
```suggestion
Generalization can be seen as a manifestation of the bias-variance trade-off; models that
```

2022-08-29 19:05 UTC, isaacdevlugt commented on demonstrations/tutorial_learning_few_data.py
> +and therefore high generalization error. The low variance maodel, on the other hand, has a higher
```suggestion
Below, we see a canonical example of this trade-off, with a model having a low bias, but a high variance
and therefore a high generalization error. The low variance model, on the other hand, has a higher 
```

2022-08-29 19:05 UTC, isaacdevlugt commented on demonstrations/tutorial_learning_few_data.py
> +to get the final prediction. Now, the goal is to minimize the expected loss over the data generating distribution
```suggestion
to get the final prediction. Now, the goal is to minimize the expected loss over the data-generating distribution
```

2022-08-29 19:06 UTC, isaacdevlugt commented on demonstrations/tutorial_learning_few_data.py
> +:math:`P` indicating how well our model performs on new data. Mathematically, for a loss function :math:`\ell`, the
```suggestion
:math:`P`, indicating how well our model performs on new data. Mathematically, for a loss function :math:`\ell`, the
```

2022-08-29 19:06 UTC, isaacdevlugt commented on demonstrations/tutorial_learning_few_data.py
> +where :math:`x` are the features, :math:`y` are the labels and :math:`P` is their joint distribution.
```suggestion
where :math:`x` are the features, :math:`y` are the labels, and :math:`P` is their joint distribution.```

2022-08-29 19:07 UTC, isaacdevlugt commented on demonstrations/tutorial_learning_few_data.py
> +.. math:: \hat{R}_S(\alpha) = \frac{1}{N}\sum_{i=1}^N \ell(\alpha;\,x_i,\,y_i),
```suggestion
.. math:: R_S(\alpha) = \frac{1}{N}\sum_{i=1}^N \ell(\alpha;\,x_i,\,y_i),```

2022-08-29 19:12 UTC, isaacdevlugt commented on demonstrations/tutorial_learning_few_data.py
> +that more complex models, i.e., models with a larger number of parameters, achieve a lower error on the training data
```suggestion
that more complex models, i.e. models with a larger number of parameters, achieve a lower error on the training data
```

2022-08-29 19:14 UTC, isaacdevlugt commented on demonstrations/tutorial_learning_few_data.py
> +true expected loss and hence lower generalization error. This intuition is made precise in Ref. [#CaroGeneralization]_
```suggestion
true expected loss and hence a lower generalization error. This intuition is made precise in Ref. [#CaroGeneralization]_,
```

2022-08-29 19:14 UTC, isaacdevlugt commented on demonstrations/tutorial_learning_few_data.py
> +where it is shown that :math:`\mathrm{gen}(\alpha)` roughly scales as :math:`\mathcal{O}(\sqrt{T / N})` where :math:`T`
```suggestion
where it is shown that :math:`\mathrm{gen}(\alpha)` roughly scales as :math:`\mathcal{O}(\sqrt{T / N})`, where :math:`T`
```

2022-08-29 19:18 UTC, isaacdevlugt commented on demonstrations/tutorial_learning_few_data.py
> +# Generalization bounds for Quantum Machine Learning models
```suggestion
# Generalization bounds for QML models
```

2022-08-29 21:07 UTC, KetpuntoG approved these changes

2022-08-29 21:09 UTC, merged