[WIP] QFT_demo
PennyLaneAI/qml pull request #507
Opened 2022-06-14 18:46 UTC by KetpuntoG

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Add a thumbnail link to your tutorial in `beginner.rst`, or if a
      QML implementation, in `implementations.rst`.

- [ ] All QML tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2022-06-17 19:37 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +    :property="og:description": Learn how to use the Quantum Fourier Transform (QFT) to implement basic operations
```suggestion
    :property="og:description": Learn how to use the Quantum Fourier Transform (QFT) to do basic arithmetic

```

2022-06-17 19:39 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +Throughout all our material we have seen concepts as varied as the
```suggestion
Throughout our demos we have seen a wide array of

```

2022-06-17 19:39 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +application of quantum computing to the field of `machine learning <https://pennylane.ai/qml/demos_qml.html>`__,
```suggestion
applications of quantum computing to the fields of `machine learning <https://pennylane.ai/qml/demos_qml.html>`__,

```

2022-06-17 19:40 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +`chemistry <https://pennylane.ai/qml/demos_quantum-chemistry.html>`__ or `optimization <https://pennylane.ai/qml/demos_optimization.html>`__ problems.
```suggestion
`chemistry <https://pennylane.ai/qml/demos_quantum-chemistry.html>`__ and `optimization <https://pennylane.ai/qml/demos_optimization.html>`__ problems.

```

2022-06-17 19:40 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +All of them are complex challenges but, can we apply quantum computing to more fundamental
```suggestion
All of them are complex topics. So we might wonder: can we apply quantum computing to more fundamental

```

2022-06-17 19:42 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +how we can work with basic arithmetic using an important tool such as
```suggestion
how we can perform basic arithmetic computations using an ubiquitous tool in quantum computing:

```

2022-06-17 19:42 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +the quantum Fourier Transform (QFT).
```suggestion
the Quantum Fourier Transform (QFT).

```

2022-06-17 19:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +In this case, we will not focus on understanding how the QFT is built,
```suggestion
In this demo, we will not focus on understanding how the QFT is built,

```

2022-06-17 19:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +`Codebook <https://codebook.xanadu.ai/F.1>`__, but we will develop the
```suggestion
`Codebook <https://codebook.xanadu.ai/F.1>`__. Instead, we will develop the

```

2022-06-17 19:53 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +QFT representation
This is a very generic subsection name. Since you do three thing: adding, multiplying, and factoring, it's better to split this tutorial into more subsection so that the reader has more sense of structure.

2022-06-17 19:55 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +operations that are done with them, that is, we will learn to add,
```suggestion
operations that are done with them. Our objective now is to learn how to add,

```

2022-06-17 19:55 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +subtract and multiply numbers. But here something that we must take into
```suggestion
subtract and multiply numbers using quantum devices. But here something that we must take into

```

2022-06-17 19:57 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +account is that since we are working with qubits (which can take the
```suggestion
that, since we are working with qubits, —which can take the

```

2022-06-17 19:58 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +values 0 or 1), we will represent the numbers in binary. For the
```suggestion
values 0 or 1—, we will represent the numbers in binary. For the

```

2022-06-17 19:58 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +values 0 or 1), we will represent the numbers in binary. For the
Is this something worth saying in this way? This is not exclusive to quantum computing, classical computers also do the same!

2022-06-17 19:59 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +integers and therefore if we have :math:`n` qubits, we will be able to
```suggestion
integers. Therefore if we have :math:`n` qubits, we will be able to

```

2022-06-17 20:01 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +Having said that, the first step is to remember what is the Pennylane
```suggestion
The first thing we need to know is what is PennyLane's

```

2022-06-17 20:01 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +Having said that, the first step is to remember what is the Pennylane
We shouldn't assume that the reader already knows this and just needs to "remember".

2022-06-17 20:02 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +represented as a string of 1s and 0s which we will represent as follows:
```suggestion
represented as a string of 1s and 0s which we will represent as the multi-qubit state

```

2022-06-17 20:03 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +.. math:: \vert q_0q_1...q_{n-1}\rangle,
```suggestion
.. math:: \vert \psi \rangle = \vert q_0q_1...q_{n-1}\rangle,

```

2022-06-17 20:03 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +.. math:: \vert q_0q_1...q_{n-1}\rangle,
An equation that's not inline should always have an equal sign.

2022-06-17 20:08 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +where :math:`q_0` refers to the most representative bit, so the formula
what does most representative bit mean? (I have a degree in math and have no idea) Maybe avoid this jargon or define it. You use the word significant elsewhere, so better to agree on one term?

2022-06-17 20:08 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +where :math:`q_0` refers to the most representative bit, so the formula
```suggestion
where :math:`q_0` refers to the most representative bit. The formula

```

2022-06-17 20:09 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +to obtain the equivalent decimal number will be:
```suggestion
to obtain the equivalent decimal number :math:`m` will be:

```

2022-06-17 20:09 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +.. math:: m:= \sum_{i = 0}^{n-1}2^{n-1-i}q_i.
```suggestion
.. math:: m= \sum_{i = 0}^{n-1}2^{n-1-i}q_i.

```

2022-06-17 20:09 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +.. math:: m:= \sum_{i = 0}^{n-1}2^{n-1-i}q_i.
Not a definition

2022-06-17 20:10 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +That means that the number
```suggestion
For instance, the natural number 6

```

2022-06-17 20:11 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +:math:`\vert 110 \rangle = 1 \times 2^2 + 1\times 2^1+0\times 2^0 = 6`.
```suggestion
is represented by the quantum state :math:`\vert 110\rangle` since :math:`\vert 110 \rangle = 1 \times 2^2 + 1\times 2^1+0\times 2^0 = 6`.

```

2022-06-20 14:39 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +
This all looks interesting academically, but why would I want to use a quantum computer to do something a Casio calculator can do? If the interest is purely academic, then it needs to be justified a bit better.

2022-06-20 14:40 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +
Add a bit more on the structure on the demo and the learning objectives.

2022-06-20 14:52 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +qubits and we want to add :math:`6+3`, we will see that we do not have
```suggestion
qubits and we want to calculate :math:`6+3.` We see that we do not have

```

2022-06-20 14:55 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +be :math:`9 \pmod 8 = 1`, or :math:`001` in binary. So be sure to use
```suggestion
be :math:`9 \pmod 8 = 1`, or :math:`001` in binary. Make sure to use

```

2022-06-20 15:00 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +
Need to start using better names for your quantum functions (all of them are called "circuit", which doesn't tell me anything about what they do).

2022-06-20 15:01 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +def circuit():
Wouldn't it be better for this to depend on a parameter m, and then give the example for m=6?

2022-06-20 15:02 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +
This piece of code has no introduction. It'd be best to clarify that you're about to show what the quantum circuit used to encode numbers looks like for n = 3.

2022-06-20 15:08 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# As we can see the qubit 0 is place on top and the rest of the qubit
```suggestion
# As we can see, the first qubit —the 0-th wire— is placed on top and the rest of the qubits are

```

2022-06-20 15:08 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +   :align: center
Need a caption

2022-06-20 15:09 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +will calculate the modulus of the sum. For example, if we have three
```suggestion
will calculate the sum modulo :math :`2^n-1.` For instance, in our three-qubit example, suppose that

```

2022-06-20 15:10 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# below it. However, this is not the only way we have to represent numbers,
```suggestion
# below it. However, this is not the only way we have to represent numbers.

```

2022-06-20 15:10 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# and we can represent them in different bases such as the fourier base.
```suggestion
# We can represent them in different bases such as the Fourier base.

```

2022-06-20 15:14 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# In this basis, all the basic states will be represented with qubits in
```suggestion
# In this basis, all the basic states will be represented via qubits in

```

2022-06-20 15:15 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# the XY plane of the Bloch sphere each of them rotated by a certain
```suggestion
# the XY plane of the Bloch sphere, each rotated by a certain

```

2022-06-20 15:16 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# the XY plane of the Bloch sphere each of them rotated by a certain
Heavy use of Bloch sphere in this tutorial. I would recommend to introduce it in a text-box at some point (so it's an optional read for those who aren't familiar with it).

2022-06-20 15:18 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# amount. How can we know what angle each qubit is rotated to represent a
```suggestion
# amount. How do we know how much we must rotate each qubit to represent a certain number?

```

2022-06-20 15:19 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# certain number? Well, actually is very easy! Suppose we are working with
```suggestion
# certain number? It is actually very easy! Suppose we are working with

```

2022-06-20 15:20 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# :math:`n` qubits and we want to represent the number :math:`m` in
```suggestion
# :math:`n` qubits and we want to represent some the number :math:`m` in

```

2022-06-20 15:20 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# fourier basis. Then the j-th qubit will have the following phase:
```suggestion
# Fourier basis. Then the j-th qubit will have the following phase:

```

2022-06-20 15:22 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# .. math:: \alpha_j = \frac{m\pi}{2^{j}}
```suggestion
# .. math:: \alpha_j = \frac{m\pi}{2^{j}}.

```

2022-06-20 15:22 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# .. math:: \alpha_j = \frac{m\pi}{2^{j}}
Don't forget to punctuate your equation!

2022-06-20 15:27 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# As we can see, the least significant qubit will advance
Here you use significant qubit. This concept needs some explanation!

2022-06-20 15:28 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# :math:`\frac{1}{8}` of a turn as we increase the number. The next qubit,
```suggestion
# :math:`\frac{1}{8}` of a turn counterclockwise as we increase the number. The next qubit,

```

2022-06-20 15:29 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# Let’s see how to represent the numbers in the case of 3 qubits:
```suggestion
# Let’s see how to represent numbers in the Fourier basis using 3 qubits:

```

2022-06-20 15:31 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# :math:`\frac{1}{4}` turn and finally the most significant qubit will go
```suggestion
# rotates :math:`\frac{1}{4}` turn and, finally, the most significant qubit will go

```

2022-06-20 15:33 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# half a turn each time we advance one unit.
```suggestion
# half a turn every time we add one to the number we are representing.

```

2022-06-20 15:43 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# :math:`\text{Sum}(k)` such that it takes a state :math:`\vert m \rangle`
The symbol sum ends up being another operator later, so this math notation is not consistent

2022-06-20 15:44 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# :math:`\text{Sum}(k)` such that it takes a state :math:`\vert m \rangle`
```suggestion
# that takes a state :math:`\vert m \rangle`

```

2022-06-20 15:44 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# and returns the value :math:`\vert m + k\rangle`. The procedure will
```suggestion
# to the state :math:`\vert m + k\rangle`. The procedure will

```

2022-06-20 15:45 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# be as follows:
```suggestion
# is the following.

```

2022-06-20 15:48 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# -  We have therefore that the new phases are
```suggestion
# -  Therefore, the new phases are

```

2022-06-20 15:54 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# new base we can use it in a simple way.
```suggestion
# new basis we can use it in a simple way.

```

2022-06-20 17:53 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +dev = qml.device("default.qubit", wires=n_wires, shots=1)
Here you include shots = 1. This is because this algorithm is deterministic right? If so, this fact is worth mentioning!

2022-06-20 18:09 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# classical way. But let us imagine that what we are interested in is that
How was this way classical? It is a gate parameter, maybe this deserves a bit more explaining.

2022-06-20 18:12 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# classical way. But let us imagine that what we are interested in is that
```suggestion
# classical way. But suppose that what we are in specifying the integer to be added using another register of qubits. 

```

2022-06-20 18:13 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# i.e., we look for a new operator :math:`\text{Sum}` such that:
```suggestion
# we are looking look for a new operator :math:`\text{Sum}` such that

```

2022-06-20 18:13 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# .. math:: \text{Sum}\vert m \rangle \vert k \rangle \vert 0 \rangle = \vert m \rangle \vert k \rangle \vert m+k \rangle
```suggestion
# .. math:: \text{Sum}\vert m \rangle \vert k \rangle \vert 0 \rangle = \vert m \rangle \vert k \rangle \vert m+k \rangle.

```

2022-06-20 18:15 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# at 0) as a counter, and we will add as many units as :math:`m` and
```suggestion
# at 0) as a counter that will tally as many units as :math:`m` and

```

2022-06-20 18:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# :math:`k` indicate. In this case, having the binary decomposition will
```suggestion
# :math:`k` combined. The binary decomposition will

```

2022-06-20 18:22 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# make it simple. If we have :math:`m = \vert q_0q_1q_2 \rangle` we will
```suggestion
# make this simple. If we have :math:`m = \vert q_0q_1q_2 \rangle` we will

```

2022-06-20 18:23 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# make it simple. If we have :math:`m = \vert q_0q_1q_2 \rangle` we will
I am bit confused by notation in general.  :math:`m = \vert q_0q_1q_2 \rangle` makes it feel like m is a ket. But it's a number, so they can't be equal. m _is represented_ by this ket, we need to be careful with putting equal signs willy nilly.

2022-06-20 18:27 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# otherwise. Generically we should add :math:`2^{n-i-1}` units if the i-th
```suggestion
# otherwise. In general, we should add :math:`2^{n-i-1}` units if the i-th

```

2022-06-20 18:28 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# have to add 1 to the counter if :math:`q_2 = 1` and not add anything
```suggestion
# have to add 1 to the counter if :math:`q_2 = 1` and nothing

```

2022-06-20 18:28 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# qubit is a 1 and 0 otherwise. As we can appreciate, this idea it is the
```suggestion
# qubit is a 1 and 0 otherwise. As we can appreciate, this idea is the

```

2022-06-20 18:31 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# same of the controlled gate concept and we will apply a corresponding
```suggestion
# behind the concept of a controlled gate. We will apply a corresponding

```

2022-06-20 18:35 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# phase if indeed the control qubit takes state 1.
```suggestion
# phase if indeed the control qubit is in the state :math:`\vert 1\rangle`.

```

2022-06-20 18:35 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# phase if indeed the control qubit takes state 1.
Then introduce the code below. "Let us now code the Sum operator."

2022-06-20 18:47 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +
Maybe comment here that you'll use an example?

2022-06-20 18:49 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +
Probably should print something like: print("The ket representation of the sum of 3 and 4 is {}".format(circuit(3,4)))

2022-06-20 18:50 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +print(circuit(7, 3, wires_m, wires_k, wires_sol))
Also try to explain why you're printing here by using format method.

2022-06-20 18:52 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# example, when we added :math:`3 + 7` to get :math:`10`, which in binary
```suggestion
# we added :math:`3 + 7` to get :math:`10`, which in binary

```

2022-06-20 18:53 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# have done before, that is, we look for the operator Mul such that:
```suggestion
# did before. This time, we look for an operator Mul such that:

```

2022-06-20 18:54 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# .. math:: \text{Mul}\vert m \rangle \vert k \rangle \vert 0 \rangle = \vert m \rangle \vert k \rangle \vert m\times k \rangle
```suggestion
# .. math:: \text{Mul}\vert m \rangle \vert k \rangle \vert 0 \rangle = \vert m \rangle \vert k \rangle \vert m\times k \rangle.

```

2022-06-20 18:54 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# .. math:: \text{Mul}\vert m \rangle \vert k \rangle \vert 0 \rangle = \vert m \rangle \vert k \rangle \vert m\times k \rangle
**Applies throughout:** Punctuate your sentences.

2022-06-20 18:55 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# .. math:: k \times m = \sum_{i=0}^{n-1}\sum_{j = 0}^{l-1}m_ik_i (2^{n-i-1} \times 2^{l-j-1}),
```suggestion
# .. math:: k \times m = \sum_{i=0}^{n-1}\sum_{j = 0}^{l-1}m_ik_i (2^{n-i-1} \times 2^{l-j-1}).

```

2022-06-20 18:55 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# or in other words, if :math:`k_i = 1` and :math:`m_i = 1` add
```suggestion
# In other words, if :math:`k_i = 1` and :math:`m_i = 1` add

```

2022-06-20 18:57 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# :math:`2^{n-i-1} \times 2^{l-j-1}` units to the counter, where n and l
```suggestion
# :math:`2^{n-i-1} \times 2^{l-j-1}` units to the counter, where :math:`n` and :math:`l`

```

2022-06-20 18:59 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# are the number of qubits with which we encode m and k respectively.
```suggestion
# are the number of qubits with which we encode :math:`m` and :math:`k` respectively.

```

2022-06-20 19:00 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +#
Introduce your codeblock.

2022-06-20 19:00 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +print(circuit(7, 3))
Improve print statement.

2022-06-20 19:01 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# :math:`10101` that is, :math:`21` in binary.
```suggestion
# :math:`10101,` which is :math:`21` in binary.

```

2022-06-20 19:01 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# With this we have already gained a large repertoire of interesting
```suggestion
# With this, we have already gained a large repertoire of interesting

```

2022-06-20 19:02 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# operations that we can do but let’s give the idea one more twist and
```suggestion
# operations that we can do, but let’s give the idea one more twist and

```

2022-06-20 19:02 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# Let’s imagine now that what we want is just the opposite, to factor the
```suggestion
# Let’s imagine now that we want just the opposite: to factor the

```

2022-06-20 19:03 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# following this previous reasoning? The answer is yes! We can make use of
```suggestion
# following this previous reasoning? The answer is yes! We can make use of
```suggestion
# following our previous reasoning? The answer is yes! We can make use of

```
```

2022-06-20 19:03 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# following this previous reasoning? The answer is yes! We can make use of
```suggestion
# following our previous reasoning? The answer is yes! We can make use of

```

2022-06-20 19:04 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# Grover’s algorithm to amplify the states whose product is the number we
Link to Grover's algorithm wiki page or codebook!

2022-06-20 19:04 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# operator such that:
```suggestion
# operator such that

```

2022-06-20 19:05 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# .. math:: U\vert m \rangle \vert k \rangle = \vert m \rangle \vert k \rangle \text{ if }m\times k \not = 21
```suggestion
# .. math:: U\vert m \rangle \vert k \rangle = \vert m \rangle \vert k \rangle \text{ if }m\times k \not = 21,

```

2022-06-20 19:05 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# -  use auxiliary registers to store the product
```suggestion
# -  use auxiliary registers to store the product,

```

2022-06-20 19:06 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# -  check if the product state is 10101 and in that case change the sign
```suggestion
# -  check if the product state is 10101 and, in that case, change the sign,

```

2022-06-20 19:06 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +#
Introduce codeblock below

2022-06-20 19:07 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# By plotting the probabilities of obtaining each basic state we get the
```suggestion
# By plotting the probabilities of obtaining each basic state we see that

```

2022-06-20 19:07 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# prime factors are just amplified! Factorization via Grover’s algorithm
```suggestion
# prime factors are amplified! Factorization via Grover’s algorithm

```

2022-06-20 19:08 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# does not achieve exponential improvement as Shor’s algorithm does but we
```suggestion
# does not the achieve exponential improvement that Shor’s algorithm does, but we

```

2022-06-20 19:11 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +plt.show()
Label your axes

2022-06-20 19:12 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +#
What did we learn? Where can I learn more?

2022-06-20 19:16 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +*Author: Guillermo Alonso-Linaje. Posted:  2022. Last updated: 13 June 2022*
Writing here to remind us to update this.

2022-06-20 20:11 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +the quantum Fourier Transform (QFT).
Link to Wikipedia

2022-06-20 20:13 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# -  We convert the computational basis into Fourier basis by applying QFT on the
```suggestion
# -  We convert the computational basis into Fourier basis by applying the QFT on the

```

2022-06-20 20:13 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# -  We convert the computational basis into Fourier basis by applying QFT on the
Add something like "via the command (refer to qml.QFT)

2022-06-20 20:14 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_qft_arithmetics.py
> +# does not achieve exponential improvement as Shor’s algorithm does but we
Link to Shor's Algorithm wiki

2022-06-20 20:17 UTC, alvaro-at-xanadu requested changes
All done! It's interesting but I think we should motivate the reader a bit more at the beginning and end. Also this tutorial could definitely use some subsections and bibliography!

2022-06-24 16:19 UTC, KetpuntoG commented
Thank you very much for all the comments @alvaro-at-xanadu 😊! It has been a very complete and easy review to do thanks to your suggestions! 🚀
PS: The last graph will not give good results now, we will have to wait for pennylane version 0.25.

2022-09-13 16:16 UTC, jen-dodd commented on demonstrations/tutorial_qft_arithmetics.py
> +
As discussed, it will be clearer if you don't focus on how this topic compares to advanced topics as that suggests the motivation here is simply that arithmetic is simpler. Instead, focus on why it is important to be able to do basic arithmetic.

2022-09-13 16:17 UTC, jen-dodd commented on demonstrations/tutorial_qft_arithmetics.py
> +The second question is why do we work with the QFT? There are other procedures to perform this basic operations, for example
This point could do with more justification or at least a reference.

2022-09-13 16:17 UTC, jen-dodd commented on demonstrations/tutorial_qft_arithmetics.py
> +#
I love the gifs overall but this one moves to fast and could potentially be replaced with a sequence of images.

2022-09-13 16:18 UTC, jen-dodd reviewed
Hey Guillermo - I added a couple of comments summarizing what we discussed. Once those changes are in I'll be ready to quickly do a detailed review.

2022-09-14 20:30 UTC, KetpuntoG commented on demonstrations/tutorial_qft_arithmetics.py
> +#
I thought it would be only 3 but I have some more images in between so I'll just slow it down

2022-09-19 12:37 UTC, ikurecic reviewed
Hoping to discuss these at our meeting later today.

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# Note that this is a deterministic algorithm so that by executing a single shot we have the desired solution.
```suggestion
# Note that this is a deterministic algorithm, which means that we have obtained the desired solution by executing a single shot.
```

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# enough space since :math:`6+3 = 9 > 2^3-1`. The result we will get will
```suggestion
# enough memory space, as :math:`6+3 = 9 > 2^3-1`. The result we will get will
```
Is 'memory space' a good way to refer to it? I'm not sure, but 'space' doesn't quite work.

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# But suppose that what we are in specifying the integer to be added using another register of qubits.
What? I have no idea what you're trying to say, sorry. 😬

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# make this simple. If we have :math:`\vert m \rangle = \vert q_0q_1q_2 \rangle` we will
Possibly a silly question, but wouldn't you have to overline the q₀q₁q₂ in the ket to indicate they're represent a number and not a product?

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# have to add 1 to the counter if :math:`q_2 = 1` and nothing
Math mode?

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# qubit is in state :math:`\vert 1 \rangle` and 0 otherwise. As we can appreciate, this is the same idea
Math mode?

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# qubit is in state :math:`\vert 1 \rangle` and 0 otherwise. As we can appreciate, this is the same idea
```suggestion
# qubit is in state :math:`\vert 1 \rangle` and 0 otherwise. As we can see, this is the same idea that is also
```

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# behind the concept of a controlled gate. Indeed, observe that we will apply a corresponding
```suggestion
# behind the concept of a controlled gate. Indeed, observe that we will, indeed, apply a corresponding
```

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +    # prepare sol-qubits to counting
'sol-qubits' and 'wires_sol' are maybe better renamed with the full word 'solution'?

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# is :math:`1010`.
Do we want this to be in ket format?

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# :math:`m` and :math:`k` and store the result in another register as we
```suggestion
# :math:`m` and :math:`k` and store the result in another register, as we
```

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# did before. This time, we look for an operator Mul such that
Why is it Mul and not Mul₂?

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# .. math:: k \times m = \sum_{i=0}^{n-1}\sum_{j = 0}^{l-1}m_ik_i (2^{n-i-1} \times 2^{l-j-1}).
Too abstract, you should explain why you chose these and what's going on.

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# .. math:: k \times m = \sum_{i=0}^{n-1}\sum_{j = 0}^{l-1}m_ik_i (2^{n-i-1} \times 2^{l-j-1}).
You should probably use \cdot instead of \times, since they're just scalars here.

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# :math:`2^{n-i-1} \times 2^{l-j-1}` units to the counter, where :math:`n` and :math:`l`
\cdot because scalars?

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +wires_sol = [6, 7, 8, 9, 10]
Same sol-related comment as above.
Alternatively you could add comments to explain what everything is — for me, more comments is always better, but I think that's probably not your style, right?

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# :math:`10101,` which is :math:`21` in binary.
Ket format?

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# operations that we can do, but let’s give the idea one more twist and
```suggestion
# operations that we can do, but we can give the idea one more twist and
```
You use 'let's' so often it's getting a bit difficult to read.

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# number 21 as a product of two terms. Is this something we could do
Math mode?

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# following our previous reasoning? The answer is yes! We can make use of
```suggestion
# using our previous reasoning? The answer is yes! We can make use of
```

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# are looking for. All we would need is to construct the oracle U, i.e., an
Math mode for U?

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# .. math:: U\vert m \rangle \vert k \rangle = -\vert m \rangle \vert k \rangle \text{ if }m\times k  = 21
\cdot instead because they're scalars?

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# -  execute the inverse of the circuit to clear the auxiliary qubits.
These are more-or-less consecutive steps, so I suggest writing it out all the way and formatting as an enumeration, with an indentation etc., like above.

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +wires_sol = [6, 7, 8, 9, 10]
Same sol/commenting thoughts as above.

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +n_wires = len(dev.wires)
Maybe comment to say what len is?

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +    # Change sign to n
```suggestion
    # Change sign of n
```

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +    # Apply Grover Operator
```suggestion
    # Apply Grover operator
```

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +    # Apply Grover Operator
Do you want to explain and/or link to a doc re Grover operator? E.g., https://docs.pennylane.ai/en/stable/code/api/pennylane.GroverOperator.html

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# A very cool circuit! let’s calculate the probabilities to see each basic
Linebreak here? The image background is flat white.

2022-09-19 12:37 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +######################################################################
Linebreak here? The image background is flat white.

2022-09-19 12:37 UTC, ikurecic commented on demos_getting-started.rst
> +    :tooltip: Learn how to use the Quantum Fourier Transform (QFT) to implement basic operations
Maybe emph it?

2022-09-19 12:37 UTC, ikurecic reviewed
Hoping to discuss these at our meeting later today.

2022-09-19 15:18 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +   Representation of the computational basis with 3 qubits
Representation of the 8-element computational basis using three qubits.

2022-09-19 15:28 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# Adding :math:`k` to a register
Adding a number to a register? Come up with sth better. 😉

2022-09-19 15:36 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# to the state :math:`\vert m + k\rangle`. A procedure to implement such unitary
define Sum here.

2022-09-21 19:31 UTC, KetpuntoG commented on demonstrations/tutorial_qft_arithmetics.py
> +.. figure:: /demonstrations/qft_arithmetics/qft_com.gif
what is the name of a good image? more complete names like this one?quantum_fourier_transform_computational_basis.gif

2022-09-22 07:45 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +.. figure:: /demonstrations/qft_arithmetics/qft_com.gif
It's better, yeah. :) I think this is something to ask Lara (and tag me in it, please ♥).

2022-09-22 07:52 UTC, ikurecic approved these changes
Nice. :)
Just a small note about the reference is still left hanging (and maybe you should ping Lara about naming conventions, but it's already improved).

2022-10-11 14:00 UTC, ikurecic reviewed
Looks pretty polished. :) I made a few tiny grammar fixes and suggestions.

2022-10-11 14:00 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +addition, multiplication, subtraction and division. Through arithmetic operations we can understand the world around us
```suggestion
addition, multiplication, subtraction and division. Using arithmetic operations we can understand the world around us
```

2022-10-11 14:00 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +In this demo, we will not focus on understanding how the QFT is built
```suggestion
In this demo we will not focus on understanding how the QFT is built,
```

2022-10-11 14:00 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
>  `Codebook <https://codebook.xanadu.ai/F.1>`__. Instead, we will develop the
```suggestion
`Xanadu Quantum Codebook <https://codebook.xanadu.ai/F.1>`__. Instead, we will develop the
```

2022-10-11 14:00 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +intuition of how it works and how we can take advantage of it.
```suggestion
intuition for how it works and how we can best take advantage of it.
```
Alternatively you could use 'about'.

2022-10-11 14:00 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +represented as a string of :math:`1` s and :math:`0` s, which we can represent as the multi-qubit state
```suggestion
represented as a string of :math:`1`s and :math:`0`s, which we can represent as the multi-qubit state
```
Should be without the spaces.

2022-10-11 14:00 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# such as:
```suggestion
# such that:
```

2022-10-11 14:00 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# A procedure to implement such unitary is the following:
```suggestion
# The procedure to implement this unitary operation is the following:
```

2022-10-11 14:00 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# Perfect, we have obtained :math:`\vert 0111 \rangle,` which is equivalent to the number :math:`7` in binary!
Question as above, why comma in math mode?

2022-10-11 14:00 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# value :math:`2^n-1,` we will start again from zero, that is to say, we
Same question about comma in math mode.

2022-10-11 14:00 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# be :math:`9 \pmod 8 = 1,` or :math:`\vert 001 \rangle` in binary. Make sure to use
Same comma in math mode question.

2022-10-11 14:00 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# In this previous algorithm, we had to pass to the operator the value of :math:`k` that we wanted to add.
```suggestion
# In this previous algorithm, we had to pass to the operator the value of :math:`k` that we wanted to add to the starting state.
```

2022-10-11 14:00 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +# make this simple. If we have :math:`\vert m \rangle = \vert \overline{q_0q_1q_2} \rangle,` we will
Same question about comma in math mode.

2022-10-11 14:00 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +wires_solution = [6, 7, 8, 9, 10]  # required qubits to encode the solution
```suggestion
wires_m = [0, 1, 2]           # qubits needed to encode m
wires_k = [3, 4, 5]           # qubits needed to encode k
wires_solution = [6, 7, 8, 9, 10]  # qubits needed to encode the solution
```

2022-10-11 14:00 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +wires_solution = [6, 7, 8, 9, 10]   # required qubits to encode the solution
```suggestion
wires_m = [0, 1, 2]                 # qubits needed to encode m
wires_k = [3, 4, 5]                 # qubits needed to encode k
wires_solution = [6, 7, 8, 9, 10]   # qubits needed to encode the solution
```

2022-10-11 15:42 UTC, KetpuntoG commented on demonstrations/tutorial_qft_arithmetics.py
> +    :math:`\vert 1 \rangle,` and in the rest of the
Sometimes I use $$ maths $$ and if I put the dot outside, it puts it in another line if I am not mistaken

2022-10-11 15:43 UTC, KetpuntoG commented on demonstrations/tutorial_qft_arithmetics.py
> +# Perfect, we have obtained :math:`\vert 0111 \rangle,` which is equivalent to the number :math:`7` in binary!
```suggestion
# Perfect, we have obtained :math:`\vert 0111 \rangle`, which is equivalent to the number :math:`7` in binary!

```

2022-10-11 15:44 UTC, KetpuntoG commented on demonstrations/tutorial_qft_arithmetics.py
> +# value :math:`2^n-1,` we will start again from zero, that is to say, we
```suggestion
# value :math:`2^n-1`, we will start again from zero, that is to say, we

```

2022-10-11 15:45 UTC, KetpuntoG commented on demonstrations/tutorial_qft_arithmetics.py
> +# make this simple. If we have :math:`\vert m \rangle = \vert \overline{q_0q_1q_2} \rangle,` we will
```suggestion
# make this simple. If we have :math:`\vert m \rangle = \vert \overline{q_0q_1q_2} \rangle`, we will

```

2022-10-11 15:47 UTC, KetpuntoG commented
Thanks @ikurecic , corrected! I put the commas outside the math part.

2022-11-07 14:53 UTC, ikurecic reviewed
Tidied up your author/date line and bio.
Please check and merge #620 before this one. (Make sure your author pic JPEG is up)

2022-11-07 14:53 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +*Posted:  2022. Last updated: 13 June 2022*
```suggestion
*Author: Guillermo Alonso-Linaje — Posted: 07 November 2022.*
```

2022-11-07 14:53 UTC, ikurecic commented on demonstrations/tutorial_qft_arithmetics.py
> +#    Guillermo is a mathematics and computer science graduate from the university of Valladolid and is currently working as an educator and quantum researcher at Xanadu. Fun fact, Guillermo is a grea
```suggestion
# .. include:: ../_static/authors/guillermo_alonso.txt

```

2022-11-07 18:41 UTC, merged