Qcut demo
PennyLaneAI/qml pull request #551
Opened 2022-08-15 20:35 UTC by gideonuchehara

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Add a thumbnail link to your tutorial in `beginner.rst`, or if a
      QML implementation, in `implementations.rst`.

- [ ] All QML tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2022-08-15 20:58 UTC, isaacdevlugt requested changes
You know your stuff Gideon! This is quite the demo! General comments:

- Sections feels too long. Try to be more concise, explicit, and to-the-point! This is especially important in a dense demo like this one
- Avoid using QuantumTapes if possible. Can you reframe those examples with concise verbal explanations and QNodes? This is preferable.
- We may end up cutting (no pun intended) your demo into two demos if we can't reduce the overall length enough (which isn't a bad thing!)

Smaller comments:

- Words to avoid: simple, trivial, easy, boring
- Make use of shorter, to-the-point headers and titles
- Maybe use less titles/headers/subheaders overall!
- Code examples (outside of QuantumTapes) need another look (e.g., some parts missing)

I'd love to re-review this when you have a chance to go through your demo again! It's going to be a great addition 💪!

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +Computer" <https://arxiv.org/abs/1904.00102>`__ by Peng et al. (2019).
I recommend having a proper "References" section at the end of the demo so that you can in-line reference things (check out the toric code demo for how to do this 😃 )

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +Introduction to Pauli circuit cutting
```suggestion
Introduction
```

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +~~~~~~~~~~~~~~~
I'm not sure that these subheaders are needed

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
See previous comment about subheader

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +    \rho &= \frac{1}{2}\sum_{i=1}^{8} c_i Tr(\rho O_i)\rho_i
Not compiling properly. Might be because you have an & before the equals sign but there's no align environment 🤔

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +and :math:`c_i = \pm 1`.
There's a lot of in-line math here. I recommend putting it into an align environment to make it more legible

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +:math:`\left(Tr(\rho I), Tr(\rho X), Tr(\rho Y), Tr(\rho Z) \right)` for
Only need 3 measurements actually since Trace(rho Identity) = 1 😄

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +Quantum computers are projected to accomplish tasks that are far beyond
Comment on this entire section: needs to be shortened. Stick to your main points and don't wonder off too much! Your main points that you want to drive home are:

Problem: circuits with a lot of qubits are not easily simulate-able, nor can they be programmed on actual hardware due to sheer size constraints (not enough qubits) but also they'd be error-prone
Propose a solution: what if we "cut" a large circuit into many smaller, more manageable chunks? (Then you can go on to say why this proposal solution seems like a viable option)
Preview the demo contents: "In this demo, we will ..." don't be too specific here. Just outline what the demo will be doing from a birds-eye view.

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +To implement the above equation, each term :math:`Tr(\rho O_i)\rho_i` in
General comment on the next couple paragraphs: I'm not understanding why I need all of this math 🤔. What are you trying to accomplish here? I.e., what is it that you want the reader to be aware of so that they can get to the next section feeling informed?

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +    :width: 80%
Figure not rendering

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +Pennylane using the circuit below.
Introduce the qcut package with a little more grandeur!

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# With the above 3-qubit quantum circuit, we will assume the following:
Try to be a bit more explicit here with this motivating example. I.e., you want to simulate a "real-world" scenario with this toy example.

Also, it's not entirely obvious to me why the best cut location is where you say it is 🤔

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# the resulting subcircuits have at most 2 qubits.
Can you highlight / separate out the two subcircuits in the figure?

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# Next, we have to apply Pennylane’s ``qml.cut_circuit`` operation as a
I think we generally avoid referring to modules, features, functions, etc., as "PennyLane's". I.e., you can just say "... we have to apply the qml.cut_circuit operation..."

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# Next, we have to apply Pennylane’s ``qml.cut_circuit`` operation as a
Also, why do we have to apply `qml.cut_circuit`? The circuit you just made has a cut in there... so why do I have to do anything else?

^ Trying to simulate a new reader trying to learn more about circuit cutting 😅. Just make sure to explain why you need it

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +circuit(x)  # Executing the quantum circuit
Same circuit as before? I.e., no `qml.cut_circuit` here.

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# **Graph partitioning and automatic cut placement with Pennylane**
More user-friendly title here. Maybe "Automatic cut placement". Or, maybe, no subheader here!

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# It was easy to identify the optimal cut location for the above circuit
This whole text section can be condensed quite a bit. Here are your main talking points:

- We manually found a good cut position, but what if we didn't know where it was in general?
- All cut positions don't have the same outcomes in terms of efficiency for simulating the larger circuit, so choosing the optimal one is important
- Introducing auto_cutter!

Don't get bogged down in specifics, tangents, etc. Be concise and get to the point!

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +    qml.WireCut(wires=1)  # Cut location
You say in the text above that WireCut is removed, but it's still there!

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +with QuantumTape() as uncut_tape:
In my opinion, I think we should cut (no pun intended) everything out here about QuantumTapes. I get that it offers a nice explanation of what's happening under the hood, but it is far too long. Can we offer something here that's much shorter but gets across the same point? Maybe just 1-2 paragraphs explaining what's happening under the hood?

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# measurements" <https://arxiv.org/abs/2207.14734>`__ by Lowe et. al. .
nice!

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# average over Haar random measure.
Maybe refer people to the Haar measure demo in case they don't know what it is.

https://pennylane.ai/qml/demos/tutorial_haar_measure.html

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# dedicated to this wonderful topic!
I would honestly just skip a lot of explanation here and reference the tutorial on unitary designs. I'm a little more confused 😅

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# Theory of Randomized Circuit Cutting
```suggestion
# Randomized Circuit Cutting
```

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# Numerical experiments
A bit more explicit title

```suggestion
# Comparison
```

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# \_:raw-latex:`\mathcal{C}` $:
not rendering properly

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +#     Figure 5. An example of mapping an input interaction graph to a QAOA
not sure this figure is needed

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +with QuantumTape() as tape:
Let's avoid QuantumTapes again here. Is there a way to translate most of this next section such that it's more condensed and uses QNodes only?

2022-08-15 20:58 UTC, isaacdevlugt commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +#    Gideon is a super cool person who works at Xanadu.
💯

2022-08-16 19:14 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +Computer" <https://arxiv.org/abs/1904.00102>`__ by Peng et al. (2019).
Makes sense, will do!

2022-08-16 19:15 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +~~~~~~~~~~~~~~~
Will remove

2022-08-16 19:16 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +    \rho &= \frac{1}{2}\sum_{i=1}^{8} c_i Tr(\rho O_i)\rho_i
Will remove

2022-08-16 19:22 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +and :math:`c_i = \pm 1`.
@gideonuchehara tried that and `align` seems to not render correctly. Putting it all into markdown syntax was a kind of a fix in itself. Can you give a code example of what you had in mind specifically?

2022-08-16 19:28 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +To implement the above equation, each term :math:`Tr(\rho O_i)\rho_i` in
@gideonuchehara 

The main message is: There is a resolution of identity along a wire that we can interpret as circuit cutting. In the following section, we want to be able to say that there is actually a more clever way of resolving the same identity that leads to fewer shots needed to estimate observables.

2022-08-16 19:35 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +:math:`\left(Tr(\rho I), Tr(\rho X), Tr(\rho Y), Tr(\rho Z) \right)` for
@gideonuchehara got this one

2022-08-16 19:36 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +    :width: 80%
Changed

2022-08-16 19:37 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Removed

2022-08-16 19:53 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +#     Figure 5. An example of mapping an input interaction graph to a QAOA
@gideonuchehara found it useful as someone who wasn't familiar with QAOA too much so we left it in

2022-08-16 19:55 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +with QuantumTape() as tape:
It's very difficult. Both existing `qcut` code in PennyLane and our research code for the paper operate on tapes as it is much easier. Adding more code to connect the two ways of thinking will just bloat the already long demo imho.

How bad is it if we leave it in?

2022-08-17 09:56 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +Quantum computers are projected to accomplish tasks that are far beyond
done

2022-08-17 22:22 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# \_:raw-latex:`\mathcal{C}` $:
Fixed

2022-08-22 16:04 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +Quantum circuits with large number of qubits are difficult to simulate.
```suggestion
Quantum circuits with a large number of qubits are difficult to simulate.
```

2022-08-22 16:05 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +PennyLane. This method was first introduced in the paper [#Peng2019]_.
```suggestion
PennyLane. This method was first introduced in [#Peng2019]_.
```

2022-08-22 16:05 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +Consider a :math:`2`-level quantum system in an arbitrary state, with a
```suggestion
Consider a two-level quantum system in an arbitrary state, with a
```

2022-08-22 16:06 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +density matrix :math:`\rho`. :math:`\rho` can be expressed as a linear
```suggestion
density matrix :math:`\rho`. The quantum state :math:`\rho` can be expressed as a linear
```

2022-08-22 16:07 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
In the equations above, we can probably save some lines by not putting each equality in a separate line.

2022-08-22 16:07 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +    \rho = \frac{1}{2}\sum_{i=1}^{8} c_i Tr(\rho O_i)\rho_i
```suggestion
    \rho = \frac{1}{2}\sum_{i=1}^{8} c_i Tr(\rho O_i)\rho_i.
```

2022-08-22 16:08 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +combination of the Pauli matrices as shown below.
```suggestion
combination of the Pauli matrices
```

2022-08-22 16:10 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +to the measurement of Pauli observables :math:`O_i` for a quantum circuit
Just saying measurement is a bit vague. $Tr(\rho O_i)$ is the expectation value of the observable $O_i$, when the system is on the state $\rho$.

2022-08-22 16:13 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
Talking about left and right here does not make much sense unless there is a visual. A visual before this paragraph, or referred to by this paragraph, is definitely needed.

2022-08-22 16:18 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
This whole paragraph is a bit confusing for me. I think it was  better when this explanation was a bit longer. You may consider reintroducing some elements that may make this clearer. In particular, conflating circuits with quantum states is a bit puzzling for me.

2022-08-22 16:20 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +we can interpret as circuit cutting. In the following section, we want to be
```suggestion
we can interpret as circuit cutting. In the following section, we will
```

2022-08-22 16:20 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +able to say that there is actually a more clever way of resolving the same
```suggestion
provide a more clever way of resolving the same
```

2022-08-22 16:20 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Section without name?

2022-08-22 16:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
Are there no related demos? The QAOA ones definitely need to be referred to here.

2022-08-22 16:22 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
I would import these as needed, instead of all at the beginning. That way it's more clear for the user when we are using which libraries.

2022-08-22 16:24 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +PennyLane has a quantum circuit cutting algorithm, ``qml.cut_circuit`` that
```suggestion
PennyLane's built-in  circuit cutting algorithm, ``qml.cut_circuit``,
```

2022-08-22 16:24 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +takes a large quantum circuit, decomposes it into smaller subcircuits that
```suggestion
takes a large quantum circuit and decomposes it into smaller subcircuits that
```

2022-08-22 16:27 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# postprocessing. This is not quite trivial to determine in most cases, but
```suggestion
# post-processing. This is not quite trivial to determine in most cases, but
```

2022-08-22 16:27 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# postprocessing. This is not quite trivial to determine in most cases, but
Please ensure that post-processing is hyphenated throughout.

2022-08-22 16:29 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# for the above circuit, we have determined the best cut location to be between
```suggestion
# for the above circuit, the best cut location turns out to be between
```

2022-08-22 16:29 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# above figure shows where we have chosen to cut. This is where the ``WireCut``
```suggestion
# above figure show where we have chosen to cut. This is where the ``WireCut``
```

2022-08-22 18:50 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
Something isn't that clear for me here. What I understand from this is: Placing WireCut like in the circuit before doesn't do anything except for marking it in the circuit drawing. You need the decorator for PennyLane to actually run the cut circuit. Is this right?

2022-08-22 18:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +    qml.WireCut(wires=1)  # Cut location
I'm not the only one who's confused!

2022-08-22 18:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# Let's explore what happens behind the scene in  ``qml.cut_circuit``. When the
```suggestion
# Let's explore what happens behind the scenes in  ``qml.cut_circuit``. When the
```

2022-08-22 18:52 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# ``circuit`` qnode function is executed, the quantum circuit is converted to a
```suggestion
# ``circuit`` qnode function is executed, the quantum circuit is converted to
```

2022-08-22 18:52 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# shown in figure 2. ``MeasureNode`` and ``PrepareNode`` are placeholder
```suggestion
# shown in figure 2.  Both ``MeasureNode`` and ``PrepareNode`` are placeholder
```

2022-08-22 18:53 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# over measurement of Pauli observables and preparation of their corresponding
```suggestion
# over measurements of Pauli observables and preparation of their corresponding
```

2022-08-22 18:54 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# a quantum tape and then to a graph. Any ``WireCut`` in the quantum
link to quantum tape

2022-08-22 18:55 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# separete these fragments into different subcircuit graphs, the
```suggestion
# separate these fragments into different subcircuit graphs, the
```

2022-08-22 18:58 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
``MeasureNode`` and ``PrepareNode`` aren't really properly defined in the text. I think it's worth it to go into a bit of detail on how they are defined without letting the reader figure it out from what you said. This is used often in this tutorial, it needs to be very clear.

2022-08-22 20:14 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
Figure needs some work. The measurement devices look different, and the arrows do not look like arrows. It might be better to rework this so that it looks more like figure Figure 4. I would save these "blue circuit drawings" for the instances when we're explicitly using ``qml.draw``.

2022-08-22 20:18 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
Figure 2 and Figure 3 also clash with the theme and are low resolution. Let's also try to rework them to look more like Figure 4.

2022-08-22 20:18 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +#     Figure 3. Separate fragmments into different subcircuits
```suggestion
#     Figure 3. Separate fragments into different subcircuits
```

2022-08-22 20:20 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# was in general? All cut positions don't have the same outcomes in terms of
```suggestion
# was in general? Changing cut positions results in different outcomes in terms of
```

2022-08-22 20:20 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# efficiency for simulating the larger circuit, so choosing the optimal one is
```suggestion
# simulation efficiency, so choosing the optimal one is
```

2022-08-22 20:24 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +#
Change above sentence. "Important" is anti-climatic. What do we really achieve by choosing the optimal cut, that other cuts wouldn't give us? Reduce overhead, etc.?

2022-08-22 20:26 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# Automatic cut placment is employed in quantum circuit cutting to help  with
```suggestion
# Automatic cut placment is a Pennylane functionality that aids us in
```

2022-08-22 20:27 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# finding the optimal cut that fragments a circuit such that it results in the
```suggestion
# finding the optimal cut that fragments a circuit such that
```

2022-08-22 20:27 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# least classical postprocessing overhead after measurement. The main algorithm
```suggestion
# the classical post-processing overhead is minimized. The main algorithm
```

2022-08-22 20:28 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# behind automatic cut placement is graph partitioning.
Link to graph partitioning (or relevant tutorial).

2022-08-22 20:29 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# If ``auto_cutter`` is enabled in ``qml.cut_circuit`` it make attempts in
```suggestion
# If ``auto_cutter`` is enabled in ``qml.cut_circuit``, PennyLane makes attempts to
```

2022-08-22 20:29 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# finding an optimal cut using graph partitioning. Where it is difficult to
```suggestion
# find an optimal cut using graph partitioning. Whenever it is difficult to
```

2022-08-22 20:30 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# approach into circuit cutting. The following examples shows this capability
```suggestion
# approach to circuit cutting. The following examples shows this capability
```

2022-08-22 20:30 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# on the same circuit as above but with the ``WireCut`` removed.
```suggestion
# on the same circuit as above with ``WireCut`` removed.
```

2022-08-22 20:31 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +######################################################################
This line of # isn't necessary (and I'm worried it could lead to rendering errors if something changes).

2022-08-22 20:38 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# The concept of 2-designs is simple - a unitary 2-design is finite
```suggestion
# The concept of 2-designs is simple — a unitary 2-design is finite
```

2022-08-22 20:38 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# The concept of 2-designs is simple - a unitary 2-design is finite
When a dash replaces a comma, you need to use the "emdash" —

2022-08-22 20:40 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# Let :math:`P(U)` be a polynomial with homogeneous degree at most two in
```suggestion
# More precisely, let :math:`P(U)` be a polynomial with homogeneous degree at most two in
```

2022-08-22 20:49 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# dedicated to this wonderful topic!
Yes, I would skip all the technical stuff and maybe keep the first paragraph, together with references to relevant demos.

2022-08-22 20:50 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# cutting procedure, we trace out the qubits and a prepare a random basis
```suggestion
# cutting procedure, we trace out the :math:`k` qubits and a prepare a random basis
```

2022-08-22 20:50 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# cutting procedure, we trace out the qubits and a prepare a random basis
This specifies which qubits are traced out, it was unclear to me.

2022-08-22 20:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# :math:`X \in \mathbf{L}(\mathbb{C}^{d})` acting on the :math:`k`-qubits,
```suggestion
# :math:`X \in \mathbf{L}(\mathbb{C}^{d})` acting on the :math:`k` qubits,
```

2022-08-22 20:53 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +#
$\cup$ overloads notations, probably better to just express the Kraus operators within brackets $\left\lbrace Kraus_1, \Kraus_2 right\rbrace$.

2022-08-22 20:54 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# Together these two channels can be used to obtain a resolution of the
```suggestion
# Together, these two channels can be used to obtain a resolution of the
```

2022-08-22 20:55 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# The set of Kraus operators for channels :math:`\Psi_{1}, \Psi_{0}` are
```suggestion
# The sets of Kraus operators for channels :math:`\Psi_{1}, \Psi_{0}` are
```

2022-08-22 21:05 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# procecdure effectively doubles the number of qubits which can be
```suggestion
# procedure effectively doubles the number of qubits which can be
```

2022-08-22 21:06 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# simulated given a quantum device since the overhead is :math:`O(4^k)`
```suggestion
# simulated given a quantum device, since the overhead is :math:`O(4^k)`
```

2022-08-22 21:07 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# measurements. Note that although the overhead incurred is smaller, the
```suggestion
# measurements. Note that, although the overhead incurred is smaller, the
```

2022-08-22 21:07 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# over the :math:`k` qubits has to implemented when randomized measurement
```suggestion
# over the :math:`k` qubits has to be implemented when randomized measurement
```

2022-08-22 21:08 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +#
What is $z$ in this figure? The notation has not been introduced.

2022-08-22 21:11 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# Otherwise, we perform a randomized measure-and-prepare protocol based on
What does otherwise refer to here? If qubits are not being cut? Then why would I add measure and prepare anything?

2022-08-22 21:16 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +#
What is happening above is that one of two channels is chosen at random (hence the name random circuit cutting). This is not mentioned/ not clear from the exposition above! Some simple rephrasing should fix this :)

2022-08-22 21:18 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +#
Since this figure has been taken _as is_ from paper [2], you need to explicitly mention this!

2022-08-22 21:32 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# where one may care about accurately estiamting an observale is the
```suggestion
# where one may care about accurately estimating an observable is the
```

2022-08-22 21:33 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# values do not leave the :math:`[-1,1]` interval.
```suggestion
# values do not lie outside the :math:`[-1,1]` interval.
```

2022-08-22 21:34 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# someone already provided us with optimal QAOA angles :math:`\gamma` and
```suggestion
# someone already provided us with optimal angles :math:`\gamma` and
```

2022-08-22 21:34 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +#     Figure 5. An example of mapping an input interaction graph to a QAOA
I think it's fine to leave it in.

2022-08-22 21:36 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
Some comments needs to be put in the code above since it uses some rare functions readers may not be familiar with.

2022-08-22 21:36 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# Let’s make a quick and simple QAOA circuit in PennyLane. Before we, we
Before we ...?

2022-08-22 21:37 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# all ZZ rotation gates corresponding to the ``top`` edges, place the wire
```suggestion
# all ZZ rotation gates corresponding to the ``top_edges``, place the wire
```

2022-08-22 21:37 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# cut, and then the ``bottom``, to ensure that the circuit actually splits
```suggestion
# cut, and then the ``bottom_edges``, to ensure that the circuit actually splits
```

2022-08-23 12:53 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +to the measurement of Pauli observables :math:`O_i` for a quantum circuit
done

2022-08-23 12:53 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +combination of the Pauli matrices as shown below.
done

2022-08-24 13:00 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +we can interpret as circuit cutting. In the following section, we want to be
done

2022-08-24 13:02 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +able to say that there is actually a more clever way of resolving the same
done

2022-08-24 13:06 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Added a name

2022-08-24 13:14 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
Yes, that's right. WireCut just indicates where to cut in the circuit

2022-08-24 13:16 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# ``circuit`` qnode function is executed, the quantum circuit is converted to a
done

2022-08-24 13:16 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# shown in figure 2. ``MeasureNode`` and ``PrepareNode`` are placeholder
done

2022-08-24 13:17 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# over measurement of Pauli observables and preparation of their corresponding
done

2022-08-24 13:48 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +with QuantumTape() as tape:
It's fine to leave in. We've shown "developer stuff" before in demos.

2022-08-24 14:00 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +device = qml.device("default.mixed", wires=tape.wires)
dev_mixed would be a more appropriate name for this device.

2022-08-24 14:03 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
Code above could use one or two comments, or some simplification. Prefer clear code over smart code (the above is smart code).

2022-08-24 14:05 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# place. However, this is just an artefact of the way we chose to
```suggestion
# place. However, this is just an artifact of the way we chose to
```

2022-08-24 14:08 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# case of a single cut, the general expression discussed earlier
```suggestion
# case of a single cut, the resolution of the identity discussed earlier
```

2022-08-24 14:08 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# specializes to:
```suggestion
# implies
```

2022-08-24 14:08 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +#    \left\langle H_\mathcal{C} (x) \right\rangle  = (d +1) \left\langle H_\mathcal{C} (x) \right\rangle _{z=0} - d \left\langle H_\mathcal{C} (x) \right\rangle _{z=1}
```suggestion
#    \left\langle H_\mathcal{C} (x) \right\rangle  = (d +1) \left\langle H_\mathcal{C} (x) \right\rangle _{z=0} - d \left\langle H_\mathcal{C} (x) \right\rangle _{z=1},
```

2022-08-24 14:09 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# where :math:`d=2^k`, :math:`z=0,1` correspond to circuits with inserted
```suggestion
# where :math:`d=2^k` and :math:`z=0,1` corresponds to circuits with inserted
```

2022-08-24 14:10 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
Feel free to omit this and simply insert the plot. It's also showing some unwanted output.

2022-08-24 14:11 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# practice, for larger cuts, we see that it offers orders of magnitude
```suggestion
# practice, for larger cuts, we see that it offers a performance that is orders of magnitude
```

2022-08-24 14:12 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# better performance than the Pauli method. For larger circuits, even at
```suggestion
# better than that of the Pauli method. For larger circuits, even at
```

2022-08-24 14:14 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# structure, we can just measure all qubits at once - a part of the
```suggestion
# structure, we can just measure all qubits at once —a part of the
```

2022-08-24 14:14 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# applied on the wires what now hold a reduced state. This is the other
```suggestion
# applied on the wires that now hold a reduced state. This is the other
```

2022-08-24 14:14 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# deveices don’t have such limitations, of course.
```suggestion
# devices don’t have such limitations, of course.
```

2022-08-24 14:15 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +#
Need a closing paragraph. What did we learn? Where/how can we learn more?

2022-08-24 14:15 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +#
Please complete this bio!

2022-08-24 14:17 UTC, alvaro-at-xanadu requested changes
Great job everyone! Overall great job in making the demo shorter :) Most comments are style/grammar. But there are some places I've spotted where some crucial information may have been left off in the process of reducing the demo size, so let's try to reinsert some of it in a very succint way.

2022-08-24 16:25 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
done

2022-08-26 15:22 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# on the same circuit as above but with the ``WireCut`` removed.
Resolved manually by @gideonuchehara

2022-08-26 15:22 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# The concept of 2-designs is simple - a unitary 2-design is finite
Resolved manually by @gideonuchehara

2022-08-26 15:22 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# Let :math:`P(U)` be a polynomial with homogeneous degree at most two in
Resolved manually by @gideonuchehara

2022-08-26 15:23 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# :math:`X \in \mathbf{L}(\mathbb{C}^{d})` acting on the :math:`k`-qubits,
Resolved manually by @gideonuchehara

2022-08-26 15:36 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
Added in the next commit

2022-08-26 15:51 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
Fixed in the next commit

2022-08-26 15:53 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +    qml.WireCut(wires=1)  # Cut location
Handled by @gideonuchehara

2022-08-26 15:54 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
I shared the tool I used to make my plots with @gideonuchehara . We are working on this.

2022-08-26 15:56 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +#
I removed the z label from the figure.

2022-08-26 15:58 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# Otherwise, we perform a randomized measure-and-prepare protocol based on
Otherwise means in the case of the other channel being applied, with probability 1 - d/(2d+1). I'll add a sentence.

2022-08-26 15:59 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# Otherwise, we perform a randomized measure-and-prepare protocol based on
@apteanuj

2022-08-26 16:00 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +#
@apteanuj

2022-08-26 16:00 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +#
@apteanuj

2022-08-26 16:01 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +#     Figure 5. An example of mapping an input interaction graph to a QAOA
Ok, cool

2022-08-26 16:06 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
Added comments

2022-08-26 16:06 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# Let’s make a quick and simple QAOA circuit in PennyLane. Before we, we
Added a clause

2022-08-26 16:06 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +with QuantumTape() as tape:
Cool!

2022-08-26 16:07 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +device = qml.device("default.mixed", wires=tape.wires)
Ok. But this is okay for this demo?

2022-08-26 16:09 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
It's easer to just leave it as-is. Do you feel this code bloats the demo?

2022-08-26 16:10 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +#
@apteanuj

2022-08-26 16:10 UTC, Matematija commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +#
@apteanuj

2022-08-29 17:52 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +Quantum circuits with large number of qubits are difficult to simulate.
fixed

2022-08-29 17:52 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +PennyLane. This method was first introduced in the paper [#Peng2019]_.
fixed

2022-08-29 17:52 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +Consider a :math:`2`-level quantum system in an arbitrary state, with a
fixed

2022-08-29 17:52 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +density matrix :math:`\rho`. :math:`\rho` can be expressed as a linear
fixed

2022-08-29 17:53 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
Isaac's review suggested that I format them so that they are separate

2022-08-29 17:53 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +    \rho = \frac{1}{2}\sum_{i=1}^{8} c_i Tr(\rho O_i)\rho_i
done

2022-08-29 17:55 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +PennyLane has a quantum circuit cutting algorithm, ``qml.cut_circuit`` that
done

2022-08-29 17:55 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +takes a large quantum circuit, decomposes it into smaller subcircuits that
done

2022-08-29 17:59 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# postprocessing. This is not quite trivial to determine in most cases, but
done

2022-08-29 17:59 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# for the above circuit, we have determined the best cut location to be between
done

2022-08-29 17:59 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# Let's explore what happens behind the scene in  ``qml.cut_circuit``. When the
done

2022-08-29 18:00 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# a quantum tape and then to a graph. Any ``WireCut`` in the quantum
done

2022-08-29 18:00 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# separete these fragments into different subcircuit graphs, the
done

2022-08-29 18:01 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
done

2022-08-29 18:01 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
done

2022-08-29 18:01 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +#     Figure 3. Separate fragmments into different subcircuits
done

2022-08-29 18:01 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# was in general? All cut positions don't have the same outcomes in terms of
done

2022-08-29 18:02 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# efficiency for simulating the larger circuit, so choosing the optimal one is
done

2022-08-29 18:04 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# Automatic cut placment is employed in quantum circuit cutting to help  with
done

2022-08-29 18:04 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# finding the optimal cut that fragments a circuit such that it results in the
done

2022-08-29 18:04 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# least classical postprocessing overhead after measurement. The main algorithm
done

2022-08-29 18:05 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# behind automatic cut placement is graph partitioning.
done

2022-08-29 18:05 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# If ``auto_cutter`` is enabled in ``qml.cut_circuit`` it make attempts in
done

2022-08-29 18:06 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# finding an optimal cut using graph partitioning. Where it is difficult to
done

2022-08-29 18:06 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# approach into circuit cutting. The following examples shows this capability
done

2022-08-29 18:06 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +######################################################################
deleted

2022-08-30 17:28 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
I think we still need to make clear what circuit-u and circuit-v mean. You choose a point p in some wire w of circuit C. Subcircuit u is C with p replaced by a measuring device, and none of the elements in w *after* p. Subcircuit-v is C with p replaced by a preparation of $\rho_i$, and none of the elements in w *before* p.  Or something to this effect. As written, it reads like subcircuit-u is just MeasureNode, and subcircuit-v is a PrepareNode.

2022-08-30 17:29 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +This means that we only have to do three measurements
```suggestion
This means that we only have to do three measurements
```
```suggestion
It turns out that we only have to do three measurements
```

2022-08-30 17:30 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +This means that we only have to do three measurements
Nothing in the previous paragraph implies this.

2022-08-30 17:41 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +*Authors: Gideon Uchehara, Matija Medvidović, Anuj Apte*
```suggestion
*Authors: Gideon Uchehara, Matija Medvidović, Anuj Apte*. Posted: 06 September 2022. Last updated: 06 September 2022.
```

2022-08-30 17:42 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +PennyLane Implementation
```suggestion
PennyLane implementation
```

2022-08-30 17:44 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
Image needs a bit of blank space below (lower border of box is too close to the caption).

2022-08-30 17:45 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
Okay!

2022-08-30 17:46 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
Great images!

2022-08-30 17:47 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +    qml.WireCut(wires=1)  # Cut location
@gideonuchehara Would be good to clarify somewhere that WireCut does not actually cut the circuit, and you need the decorator (or quantum transform) for that to happen.

2022-08-30 17:49 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +#
Please add: Taken from [2]

2022-08-30 17:50 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +#   \Psi_{0}(X) \xrightarrow{} \left\{ \frac{\mathbf{1}}{\sqrt{d+1}} \right\} \cup \left\{ \frac{|i\rangle \langle j|}{\sqrt{d+1}} \right\}~,
```suggestion
#   \Psi_{0}(X) \xrightarrow{} \left\{ \frac{\mathbf{1}}{\sqrt{d+1}} , \frac{|i\rangle \langle j|}{\sqrt{d+1}} \right\}~,
```

2022-08-30 17:53 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
Thank you!

2022-08-30 17:56 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# compared with the :math:`O(16^k)` overhead of cutting with single-qubit
```suggestion
# which is much lower than the :math:`O(16^k)` overhead of cutting with single-qubit
```

2022-08-30 17:58 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +device = qml.device("default.mixed", wires=tape.wires)
We can just leave it as is. It's just better practice to name devices (and variables in general) in ways that are more self explanatory.

2022-08-30 17:59 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# -  Otherwise, just apply the same exisitng gate to both new tapes
```suggestion
# -  Otherwise, just apply the same exisiting gate to both new tapes.
```

2022-08-30 18:00 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# We only need to run each of the two generated tapes, ``tape0`` and
```suggestion
# We only need a single run each of the two generated tapes, ``tape0`` and
```

2022-08-30 18:00 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# ``tape1``, once, collecting the appropriate number of samples. NumPy can
```suggestion
# ``tape1``, collecting the appropriate number of samples. NumPy can
```

2022-08-30 18:02 UTC, alvaro-at-xanadu submitted a review, later dismissed
Just minor comments and we're ready to go! @apteanuj Please act on the review as soon as you can, since this demo will be merged on Friday.

2022-08-30 19:42 UTC, apteanuj commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# Otherwise, we perform a randomized measure-and-prepare protocol based on
The process is probabilistic and the other refers to the other outcome of applying channel 0 instead of channel 1

2022-08-30 19:58 UTC, apteanuj commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +#
Added a line explaining this.

2022-08-30 19:59 UTC, apteanuj commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +#
changed the notation as per request.

2022-08-30 21:06 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
will add some blank space

2022-08-30 21:08 UTC, gideonuchehara commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
thanks

2022-08-31 14:50 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +
As long as the undesired output is gone I'm game.

2022-08-31 14:55 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +#     Figure 4. Illustration of Randomized Circuit Cutting based on Two-Designs
```suggestion
#     Figure 4. Illustration of Randomized Circuit Cutting based on Two-Designs. Taken from [#Lowe2022]_.
```

2022-08-31 15:19 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_quantum_circuit_cutting.py
> +# -  Otherwise, just apply the same exisiting gate to both new tapes.
```suggestion
# -  Otherwise, just apply the same existing gate to both new tapes.
```

2022-09-02 15:03 UTC, KetpuntoG approved these changes
Amazing demo! I love this topic 🤩

2022-09-02 15:04 UTC, merged

2022-09-07 18:28 UTC, KetpuntoG commented on test-results/sphinx-gallery/junit.xml
> +<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="0" name="sphinx-gallery" skipped="0" tests="1" time="647.217170715332"><testcase classname="tutorial_quantum_circuit_cutting" fil
I just saw that change, what's the reason?