[WIP] add quantum resource estimation demo
PennyLaneAI/qml pull request #558
Opened 2022-08-25 14:55 UTC by soranjh

**Title:**
Quantum Resource Estimation

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2022-09-19 21:59 UTC, ixfoduap requested changes
Looking good overall. I made several changes directly plus a good number of suggestions.

Main thing is that we should add a bit more substance with some nice concluding plots for each algorithm

2022-09-19 21:59 UTC, ixfoduap commented on demonstrations/tutorial_resource_estimation.py
> +# ---------------------------------
```suggestion
# Variational quantum eigensolver
# ------------------------------------------
```
For consistency in naming both sections after the algorithms, but also for keywords in the demo

2022-09-19 21:59 UTC, ixfoduap commented on demonstrations/tutorial_resource_estimation.py
> +# Hamiltonian as an example.
```suggestion
# In variational quantum algorithms such as VQE, the expectation value of an observable is
# typically computed by decomposing the observable into a linear combination of Pauli strings,
# which are tensor products of Pauli and Identity operators. The expectation values is calculated
# through linearity by measuring the expectation value for each of these terms and combining the results. 
# The number of qubits required for the measurement is trivially determined by
# the number of qubits the observable acts on. The number of gates required to implement the
# variational algorithm is determined by a circuit ansatz that is also known a priori. However,
# estimating the number of circuit measurements required to achieve a certain error in computing the
# expectation value is not as straightforward. Let's now use PennyLane to estimate
# the number of measurements needed to computing the expectation value of the water
# Hamiltonian.
```
The Pauli strings are not always local; they can generally act on all qubits

2022-09-19 21:59 UTC, ixfoduap commented on demonstrations/tutorial_resource_estimation.py
> +# Hamiltonian as an example.
```suggestion
# In variational quantum algorithms such as VQE, the expectation value of an observable is
# typically computed by decomposing the observable into a linear combination of Pauli words,
# which are tensor products of Pauli and Identity operators. The expectation values is calculated
# through linearity by measuring the expectation value for each of these terms and combining the results. 
# The number of qubits required for the measurement is trivially determined by
# the number of qubits the observable acts on. The number of gates required to implement the
# variational algorithm is determined by a circuit ansatz that is also known a priori. However,
# estimating the number of circuit measurements required to achieve a certain error in computing the
# expectation value is not as straightforward. Let's now use PennyLane to estimate
# the number of measurements needed to computing the expectation value of the water
# Hamiltonian.
```
The Pauli strings are not always local; they can generally act on all qubits

2022-09-19 21:59 UTC, ixfoduap commented on demonstrations/tutorial_resource_estimation.py
> +# Hamiltonian as an example.
Also, let's consider using the word "shots" here, to make a connection to the actual circuit

2022-09-19 21:59 UTC, ixfoduap commented on demonstrations/tutorial_resource_estimation.py
> +# The number of measurements needed to compute :math:`\left \langle H \right \rangle` within the
```suggestion
# The number of measurements needed to compute :math:`\left \langle H \right \rangle` with
```

2022-09-19 21:59 UTC, ixfoduap commented on demonstrations/tutorial_resource_estimation.py
> +# m = qml.resource.estimate_shots(H.coeffs, H.ops, error=0.0016)
This seems a bit abrupt. For example, we are not explaining why we need to pass the coefficients and operators separately

2022-09-19 21:59 UTC, ixfoduap commented on demonstrations/tutorial_resource_estimation.py
> +
It would maybe be nice to mention that `estimate_shots` generally takes grouped observables and coefficients

2022-09-19 21:59 UTC, ixfoduap commented on demonstrations/tutorial_resource_estimation.py
> +
As in the QPE case, I think it would be nice to bring it all together and create a nice plot. There are many possibilities, but one of them can be to create a plot as a function of epsilon to confirm the 1/epsilon^2 dependency. 

I also think the demo could use a nice concluding paragraph

2022-09-20 17:58 UTC, soranjh commented on demonstrations/tutorial_resource_estimation.py
> +qml.resource.FirstQuantization.norm(planewaves, electrons, volume, error=0.001)
Here I am showing that the `norm` method can be called directly by the user without initiating the class. No sure if it is important to be highlighted here, so can remove it.

2022-09-21 16:56 UTC, antalszava commented
PR was closed automatically as the `dev` branch was recreated. Re-opened the PR and now it targets `master`.

If the demo does use any post-v0.26.0 features from PennyLane, the target branch should be changed again to `dev`.

2022-09-23 22:05 UTC, ixfoduap requested changes
Just a few minor suggestions. Overall the demo looks great! Main things are:
- Let's add more links to our demos, external websites, and internal docs
- I don't like the rotated ticks in the x-axes of the plots

2022-09-23 22:05 UTC, ixfoduap commented on demonstrations/tutorial_resource_estimation.py
> +# Can you interpret the plotted results?
:thinking:

2022-09-23 22:05 UTC, ixfoduap commented on demonstrations/tutorial_resource_estimation.py
> +
Maybe god to add a short couple of sentences that PL allows users to get more fine-grained information about cost of the algorithm, and link to the documentation. In general, we should have lots of link to our docs in this demo, so consider adding them throughout

2022-09-23 22:05 UTC, ixfoduap commented on demonstrations/tutorial_resource_estimation.py
> +# which are tensor products of Pauli and Identity operators. The expectation values is calculated
```suggestion
# which are tensor products of Pauli and Identity operators. The expectation values are calculated
```

2022-09-23 22:05 UTC, ixfoduap commented on demonstrations/tutorial_resource_estimation.py
> +# estimating the number of circuit evaluations, shots, required to achieve a certain error in
```suggestion
# estimating the number of circuit evaluations, i.e., the number of shots, required to achieve a certain error in
```

2022-09-26 13:43 UTC, soranjh commented on demonstrations/tutorial_resource_estimation.py
> +We study the double low-rank Hamiltonian factorization algorithm of [#vonburg2021]_ and [#lee2021]_.
There are few papers on low-rank factorization algorithms but the “double low rank” factorization is introduced in [#vonburg2021]_ and summarised very well, with explicit cost equations, in [#lee2021]_. Modified the sentence for more clarity.

2022-09-26 13:59 UTC, soranjh commented on demonstrations/tutorial_resource_estimation.py
> +equilibrium geometry as an example.
We now use 6-31g, added it.

2022-09-27 17:33 UTC, PabloAMC commented on demonstrations/tutorial_resource_estimation.py
> +# `Bohr radius <https://en.wikipedia.org/wiki/Bohr_radius>`_. We also use 100000 plane waves.
Perhaps use 10^5 instead of 100000. I makes it more legible

2022-09-27 18:02 UTC, PabloAMC requested changes
Perhaps in the first figure, it would be good to indicate which wires represent the eigenstate  (both before and after the QPE) and add the measurements at the end too.

2022-09-28 18:42 UTC, ixfoduap approved these changes

2022-09-29 13:21 UTC, PabloAMC commented on demonstrations/tutorial_resource_estimation.py
> +# This estimation is for a target error that is set to the chemical accuracy, 0.0016
Can we also add the chemical accuracy definition here, and use 
`error = 10* chemical_accuracy`  
when we do
`algo = qml.resource.DoubleFactorization(one, two, error=0.016)`

2022-09-29 14:03 UTC, PabloAMC approved these changes

2022-10-17 20:03 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +`variational quantum eigensolver <https://pennylane.ai/qml/demos/tutorial_vqe.html>`_ (VQE).
Just moved the acronym + hyperlinks for QPE and VQE to where the expanded form occurs first.

2022-10-17 20:04 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +`variational quantum eigensolver <https://pennylane.ai/qml/demos/tutorial_vqe.html>`_ (VQE).
I wonder if we should be linking to the codebook 🤔

2022-10-17 20:18 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +# and obtain the estimated number of non-Clifford gates and logical qubits
```suggestion
# and obtain the estimated number of non-Clifford gates and logical qubits.

```

2022-10-17 20:19 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +print(f'Estimated gates : {algo.gates:.2e} \nEstimated qubits: {algo.qubits}')
`3e8` 😲 🤯

2022-10-17 20:21 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +chemical_accuracy = 0.0016
Same accuracy as before, so the output is the same as the codeblock above.

2022-10-17 20:21 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +In this demo, we describe how to estimate the total number of non-Clifford gates and logical qubits
Maybe a good idea to remind ourselves what non-Clifford gates are? 🤔

2022-10-17 20:26 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +# for discarding the negligible factors in the factorized Hamiltonian and plot the estimated
Is a slightly elaboration on "negligible factors in the factorized Hamiltonian" needed? Admittedly I'm not sure what you're talking about 😅

2022-10-17 20:26 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +ax.plot(threshold, n_gates, ':o', markerfacecolor='none', color='teal')
:o 😮

2022-10-17 20:27 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +# using Hamiltonians in first quantization and in a plane wave basis. We first need to define the
```suggestion
# using Hamiltonians represented in first quantization and in a plane wave basis. We first need to define the

```

2022-10-17 20:28 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +# number of plane waves, the number of electrons and the volume of the unit cell that constructs
```suggestion
# number of plane waves, the number of electrons, and the volume of the unit cell that constructs

```

2022-10-17 20:28 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +# and has dimensions :math:`9.49 \times 10.20 \times 11.83` in atomic units, which amount to a
```suggestion
# and has dimensions :math:`9.49 \times 10.20 \times 11.83` in atomic units, amounting to a

```

2022-10-17 20:30 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +planewaves = 100000
Any reason for choosing 100000?

2022-10-17 20:31 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +# The algorithm uses a decomposition of the Hamiltonian as a linear combination of unitaries.
```suggestion
# The algorithm uses a decomposition of the Hamiltonian as a linear combination of unitaries,

```

2022-10-17 20:32 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +print(f'1-norm of the Hamiltonian: {algo.lamb}')
🐑

2022-10-17 20:33 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +# explained in the documentations of :class:`~.pennylane.resource.FirstQuantization`
```suggestion
# explained in the documentation for :class:`~.pennylane.resource.FirstQuantization`

```

2022-10-17 20:35 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +# estimating the number of circuit evaluations, i.e., the number of shots, required to achieve a
```suggestion
# estimating the number of circuit evaluations, i.e. the number of shots, required to achieve a

```

2022-10-17 20:36 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +# First, we construct the molecular Hamiltonian
```suggestion
# First, we construct the molecular Hamiltonian.

```

2022-10-17 20:37 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +# obtained with the :func:`~.pennylane.resource.estimate_shots` function which requires the
```suggestion
# obtained with the :func:`~.pennylane.resource.estimate_shots` function, which requires the

```

2022-10-17 20:37 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +# :math:`\text{Ha}`, is obtained with
```suggestion
# :math:`\text{Ha}`, is obtained as follows.

```

2022-10-17 20:40 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +# terms that can be measured simultaneously.
```suggestion
# independently. The number can be reduced by using :func:`~.pennylane.grouping.group_observables()`, which partitions the Pauli words into groups of commuting
# terms that can be measured simultaneously.

```

2022-10-17 20:42 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +# interesting information form the plot?
... :stonks: ?

2022-10-17 20:44 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +# observable using the variational quantum eigensolver algorithm. The functionality allows to obtain
Wait... this can be used for any algorithm involving a calculation of the expectation value of a Hamiltonian. So doesn't _have_ to be VQE, right? 🤔

2022-10-17 20:45 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +# and first-quantized Hamiltonians of periodic materials in the plane wave basis. We also discuss
```suggestion
# and first-quantized Hamiltonians of periodic materials in the plane wave basis. We also discussed

```

2022-10-17 20:45 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +# observable using the variational quantum eigensolver algorithm. The functionality allows to obtain
```suggestion
# observable using the variational quantum eigensolver algorithm. The functionality allows one to obtain

```

2022-10-17 20:46 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +#    :photo: ../_static/Soran.png
🙌

2022-10-18 13:51 UTC, josh146 commented on demonstrations/tutorial_resource_estimation.py
> +Quantum Resource Estimation
> Or, it can appear in both Quantum Computing and Quantum Chemistry.

🤯 this is a great idea. If we think someone will look in either category for this demo... why not just list it in both.

2022-10-18 13:55 UTC, soranjh commented on demonstrations/tutorial_resource_estimation.py
> +In this demo, we describe how to estimate the total number of non-Clifford gates and logical qubits
Do we have a good link somewhere in PL or the code book?

2022-10-18 14:05 UTC, soranjh commented on demonstrations/tutorial_resource_estimation.py
> +planewaves = 100000
Not really, it is just a round and reasonable number, we can go for something like 100001 as well.

2022-10-18 14:07 UTC, soranjh commented on demonstrations/tutorial_resource_estimation.py
> +print(f'1-norm of the Hamiltonian: {algo.lamb}')
Maybe we should use `lambda` instead?

2022-10-18 14:31 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +In this demo, we describe how to estimate the total number of non-Clifford gates and logical qubits
I think the Wikipedia should suffice! 

https://en.wikipedia.org/wiki/Clifford_gates

2022-10-18 14:31 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +print(f'1-norm of the Hamiltonian: {algo.lamb}')
Does using `lambda` cause issues with defining `lambda` _functions_? 🤔

2022-10-18 14:32 UTC, soranjh commented
> Looks good! Couple general comments:
> 
> * I know the applications for this module in PennyLane only reach QChem, but the placement of the demo (in QChem demos) seems off at first glance
> * Should we be more explanatory when introducing terms like "one-electron integrals" or "first-quantized Hamiltonians"?

Thanks @isaacdevlugt.

I agree with your concern that this demo is about a general topic, resource estimation, but it is too qchem-specific in its current form. The reason is that the `qml.resorce` module supports very advanced qchem algorithms at the moment and we cannot really have a general demo. This also explains why the demo is technical in terms of qchem jargon. For these reasons, I prefer the demo to appear in `Quantum Chemistry` for now. This also gives the users a hint that they should expect a lot of qchem when they want to estimate quantum resources. 

In the future, when we support more general algorithms in `qml.resorce`, we can expand the demo and bring the qchem part to a dedicated section.

I can provide more links to our demos and wiki pages for the qchem concepts. But explaining the concepts here, very likely, changes the focus of the demo. 

Please let me know what you think.

2022-10-18 14:33 UTC, isaacdevlugt commented
Agreed! I like the idea of re-titling the demo. Maybe, "Resource estimation for quantum chemistry"? Or, we can put it into two demo categories as was stated in a different thread.

2022-10-18 14:39 UTC, soranjh commented on demonstrations/tutorial_resource_estimation.py
> +chemical_accuracy = 0.0016
> Same accuracy as before, so the output is the same as the codeblock above.

Used a larger error here. It was a mistake happened during code review.

2022-10-18 14:40 UTC, soranjh commented on demonstrations/tutorial_resource_estimation.py
> +This algorithm requires the one- and two-electron integrals as input. These integrals can be
Please see my comment [here](https://github.com/PennyLaneAI/qml/pull/558#issuecomment-1282493965).

2022-10-18 14:40 UTC, soranjh commented on demonstrations/tutorial_resource_estimation.py
> +# for discarding the negligible factors in the factorized Hamiltonian and plot the estimated
Please see my comment [here](https://github.com/PennyLaneAI/qml/pull/558#issuecomment-1282493965).

2022-10-18 14:42 UTC, soranjh commented on demonstrations/tutorial_resource_estimation.py
> +print(f'1-norm of the Hamiltonian: {algo.lamb}')
Yes, I think that was the reason we did not use `lambda`.

2022-10-18 15:00 UTC, isaacdevlugt requested changes
LGTM! Just need to deal with the comment [here](https://github.com/PennyLaneAI/qml/pull/558/files#r997457735) still. I'm fine with retitling the demo, or putting it in 2 places 😄

2022-10-19 20:43 UTC, soranjh commented on demonstrations/tutorial_resource_estimation.py
> +Quantum Resource Estimation
I am using the title "Resource Estimation for Quantum Chemistry" for now until we support more general algorithms in `qml.resource`.

2022-10-20 10:38 UTC, PabloAMC approved these changes

2022-10-20 12:13 UTC, isaacdevlugt approved these changes
Looks good! Ran the tutorial through grammarly and found a couple minor grammar things.

2022-10-20 12:13 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +Resource estimation for quantum chemistry
💯

2022-10-20 12:13 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +logical qubits and the number of gates which are needed to implement the algorithm. We focus on
```suggestion
logical qubits and the number of gates that are needed to implement the algorithm. We focus on

```

2022-10-20 12:13 UTC, isaacdevlugt commented on demonstrations/tutorial_resource_estimation.py
> +# interesting information form the plot :stonks: ?
LOL! How did this end up here! 😆 
```suggestion
# interesting information from the plot?

```

2022-10-24 19:01 UTC, PabloAMC approved these changes

2022-10-24 21:11 UTC, PabloAMC approved these changes

2022-11-04 23:30 UTC, PabloAMC approved these changes

2022-11-08 22:53 UTC, PabloAMC approved these changes

2022-11-15 01:28 UTC, josh146 commented on _templates/filters.html
>            <li><label for="autograd">NumPy/Autograd</label></li>
```suggestion
          <li><label for="autograd">NumPy/Autograd</label></li>

```

2022-11-15 01:28 UTC, josh146 commented on demonstrations/tutorial_diffable_shadows.py
> +#
```suggestion
# .. include:: ../_static/authors/korbinian_kottmann.txt

```

2022-11-21 19:58 UTC, ikurecic reviewed
@KetpuntoG — does this work?

2022-11-21 19:58 UTC, ikurecic commented on demonstrations/tutorial_resource_estimation.py
> +Despite these difficulties, it is still possible to estimate the amount of resources required to
```suggestion
Despite these difficulties, it is still possible to perform **resource estimation**
```

2022-11-21 19:58 UTC, ikurecic commented on demonstrations/tutorial_resource_estimation.py
> +implement such quantum algorithms.
```suggestion
to assess what we need to implement such quantum algorithms.
```

2022-11-21 19:58 UTC, ikurecic commented on demonstrations/tutorial_resource_estimation.py
> +In this demo, we describe how to estimate the total number of logical qubits and gates required to
```suggestion
In this demo, we describe how to use PennyLane's resource estimation functionality to estimate the total number of logical qubits and gates required to
```

2022-11-21 19:58 UTC, ikurecic commented on demonstrations/tutorial_resource_estimation.py
> +quantization. We focus on `non-Clifford gates <https://en.wikipedia.org/wiki/Clifford_gates>`_ which
```suggestion
quantization. We focus on `non-Clifford gates <https://en.wikipedia.org/wiki/Clifford_gates>`_, which
```

2022-11-21 20:51 UTC, KetpuntoG commented
great job! We will announce it this Wednesday morning 🚀

2022-11-21 20:51 UTC, merged