[WIP] Add ansatz using tapered excitations to qubit tapering demo
PennyLaneAI/qml pull request #560
Opened 2022-08-29 00:37 UTC by obliviateandsurrender

This PR modifies the circuit ansatz in the tapering demo to now use tapered excitations. This update correction does not have any effect on the conclusion/results in the demo.

2022-08-29 17:17 UTC, soranjh requested changes
Thanks @obliviateandsurrender, left few comments. The main one is about the format of the tapered excitations. I think it is better to have tapered excitation gates that are directly applicable to the state not with `qml.PauliRot`. You might also consider this:

> If your demo uses the latest release of PennyLane, simply make your PR against the master branch. If you instead require the cutting-edge development versions of PennyLane or any relevant plugins, make your PR against the dev branch instead.

2022-08-29 17:17 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +            qml.PauliRot(params[idx][itx],
The tapered excitations cannot be directly applied?

2022-09-12 13:54 UTC, obliviateandsurrender commented on demonstrations/tutorial_qubit_tapering.py
> +            qml.PauliRot(params[idx][itx],
It can be now!

2022-09-21 16:56 UTC, antalszava commented
PR was closed automatically as the `dev` branch was recreated. Re-opened the PR and now it targets `master`.

If the demo does use any post-v0.26.0 features from PennyLane, the target branch should be changed again to `dev`.

2022-10-24 19:57 UTC, soranjh commented on demonstrations/tutorial_qubit_tapering.py
> +                                generators, paulixops, paulix_sector, H.wires)
Does it need to be updated regarding this [PR](https://github.com/PennyLaneAI/pennylane/pull/3121)?

2022-11-08 07:04 UTC, closed without merging