Small language fix
PennyLaneAI/qml pull request #565
Opened 2022-09-07 19:44 UTC by ikurecic

2022-09-12 15:07 UTC, AndrewGardhouse approved these changes

2022-09-12 15:20 UTC, josh146 requested changes
Thanks Ivana! One small change, to keep the existing flow of the sentence

2022-09-12 15:20 UTC, josh146 commented on demonstrations.rst
> +                                    <p class="mb-1 grey-text px-3">Explore general quantum computing tasks and algorithms, from measuring quantum volume to boson sampling.</p>
```suggestion
                                    <p class="mb-1 grey-text px-3">Explore general quantum computing concepts and algorithms, from quantum volume to boson sampling.</p>
```

2022-09-12 15:46 UTC, josh146 approved these changes
💯

2022-09-13 14:22 UTC, jen-dodd approved these changes
Looks good!

2022-09-13 14:45 UTC, merged