[WIP] add demo for using external quantum chemistry libraries
PennyLaneAI/qml pull request #578
Opened 2022-09-19 15:23 UTC by soranjh

**Title:**
Using external  quantum chemistry libraries

**Summary:**
This demo shows ho to build molecular Hamiltonian using external libraries such as PySCF and OpenFermion. 

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2022-09-21 16:53 UTC, antalszava commented
PR was closed automatically as the `dev` branch was recreated. Re-opened the PR and now it targets `master`.

If the demo does use any post-v0.26.0 features from PennyLane, the target branch should be changed again to `dev`.

2022-10-13 20:19 UTC, ixfoduap requested changes

2022-10-13 20:19 UTC, ixfoduap commented on demonstrations/tutorial_qchem_external.py
> +    :property="og:description": Learn how to use external quantum libraries with PennyLane.
```suggestion
    :property="og:description": Learn how to integrate external quantum chemistry libraries with PennyLane.
```

2022-10-13 20:19 UTC, ixfoduap commented on demonstrations/tutorial_qchem_external.py
> +r"""
Love the thumbnail!!! :star_struck:

2022-10-13 20:19 UTC, ixfoduap commented on demonstrations/tutorial_qchem_external.py
> +will learn how to use PennyLane with the electronic structure package
```suggestion
will learn how to integrate PennyLane with the electronic structure packages
```

2022-10-13 20:19 UTC, ixfoduap commented on demonstrations/tutorial_qchem_external.py
> +:func:`~.pennylane.qchem.molecular_hamiltonian`. # This backend requires the ``OpenFermion-PySCF``
```suggestion
:func:`~.pennylane.qchem.molecular_hamiltonian`. This requires the ``OpenFermion-PySCF``

```

2022-10-13 20:19 UTC, ixfoduap commented on demonstrations/tutorial_qchem_external.py
> +# fermionic Hamiltonians which can be mapped to a qubit Hamiltonian. The two-electron integrals
```suggestion
# fermionic Hamiltonians which can be mapped to a qubit Hamiltonian. The two-electron integral
```

2022-10-13 20:19 UTC, ixfoduap commented on demonstrations/tutorial_qchem_external.py
> +# calculations to compute:
to compute what? I find this text confusing. Consider revising

2022-10-13 20:19 UTC, ixfoduap commented on demonstrations/tutorial_qchem_external.py
> +##############################################################################
The way I understand it is that after running RHF on `mol_pyscf`, the molecule object gets updated to store the integrals. Is that correct? Then we can retrieve them using `intor_symmetric` and `intor`. It's then not clear to me why we need to perform the `einsum` to obtain the molecular orbitals instead of `ao2mo`.

Basically, since not everyone reading this demo will be an expert in pyscf, it may eb good to add more explanation on what is going on and/or provide links to relevant pyscf tutorials

2022-10-13 20:19 UTC, ixfoduap commented on demonstrations/tutorial_qchem_external.py
> +# Let's not look at an interesting example where these molecular integrals can be used to estimate
```suggestion
# Let's now look at an example where these molecular integrals can be used to estimate
```

2022-10-13 20:19 UTC, ixfoduap commented on demonstrations/tutorial_qchem_external.py
> +# This tutorial demonstrates using pennylane with external quantum chemistry libraries such as
Not a fan of this conclusion. I suggest instead to finish the demo by summarizing the main take-aways:
- We can easily convert OF operators to Pennylane ones using `import_operator`
- We can construct Hamiltonians using a user-installed version of pyscf by passing the argument `method=pyscf` to `molecular_hamiltonian`
- We can directly use one- and two-electron integral tensors from pyscf, but we need to convert from chemist to physicist notation

2022-10-13 21:32 UTC, josh146 commented on demonstrations/tutorial_qchem_external.py
> +========================
Minor comment, but this title may not mean much to users unless they know what we mean by an 'external library', and how this relates to pennylane and qchem.

Suggest replacing with a title that is more descriptive, and has a higher change of showing up in google if someone google 'how to use pennylane with openfermion' (for example).

2022-10-13 21:33 UTC, josh146 commented on demonstrations/tutorial_qchem_external.py
> +fully-differentiable molecular Hamiltonians. PennyLane also allows users to use external libraries
@soranjh can you add a link here to the diff HF demo :)

2022-10-14 13:54 UTC, soranjh commented on demonstrations/tutorial_qchem_external.py
> +# calculations to compute:
Changed to this:

> First, we define the PySCF molecule object and run a restricted Hartree-Fock calculation:

Was it just this sentence or the whole paragraph is not clear?

2022-10-14 14:24 UTC, soranjh commented on demonstrations/tutorial_qchem_external.py
> +# This tutorial demonstrates using pennylane with external quantum chemistry libraries such as
Done.

2022-10-14 21:45 UTC, branedrane reviewed
Nice! The demo has a clear structure and well-chosen use cases. My feedback is all on the stylistic end.

2022-10-14 22:07 UTC, josh146 commented on demonstrations/tutorial_qchem_external.py
> +    :property="og:image": https://pennylane.ai/qml/_images/external_libs.png
We also have a sketchy version of the PL logo :) 
![image](https://user-images.githubusercontent.com/2959003/195950980-4a2d3b0a-2ab4-4026-9294-a69528e122c3.png)

2022-10-17 17:35 UTC, soranjh commented on demonstrations/tutorial_qchem_external.py
> +##############################################################################
I took the example from the PySCF [Quickstart](https://pyscf.org/quickstart.html#and-2-electron-integrals) page. Apparently PySCF has the `ao2mo` module for two-electron integral transformation but the one-electron integrals should be transformed manually. I agree that the PySCF code block is a bit strange but seems to me that this is the cleanest code we can have. 

I preferred not to not go beyond what PySCF docs provide, but we can explain things a bit more if you think it will be helpful.

Added the link to the PySCF Quickstart page.

2022-10-18 13:19 UTC, soranjh commented
> Nice! The demo has a clear structure and well-chosen use cases. My feedback is all on the stylistic end.

Thanks @branedrane. I added majority of your comments except few of them that were about corrections suggested by other reviewers in previous reviews.

2022-10-18 18:03 UTC, branedrane reviewed
I picked up a couple of very minor typos, but other than that looks great to me!

2022-10-18 20:45 UTC, ixfoduap requested changes
Looking great! A few more minor suggestions, then should be good to go from my side!

2022-10-18 20:45 UTC, ixfoduap commented on demonstrations/tutorial_qchem_external.py
> +##############################################################################
Looks much better now, great change!

2022-10-18 20:45 UTC, ixfoduap commented on demonstrations/tutorial_qchem_external.py
> +# function.
```suggestion
# This tutorial demonstrates how to use pennylane with external quantum chemistry libraries such as
# PySCF and OpenFermion-PySCF. To summarize:
# 1. We can construct molecular Hamiltonians using a user-installed version of PySCF by passing
# the argument ``method=pyscf`` to the :func:`~.pennylane.qchem.molecular_hamiltonian` function. 
# 2. We can directly use one- and two-electron integrals from PySCF, but we need to convert the
# tensor containing the two-electron integrals from chemists' notation to physicists' notation. 
# 3. Finally, we can easily convert OpenFermion operators to PennyLane operators using the 
# :func:`~.pennylane.qchem.import_operator` function.
```
I think it works better as an explicit list. Please check that I didn't mess up the formatting with my suggestion

2022-10-18 20:45 UTC, ixfoduap commented on demonstrations/tutorial_qchem_external.py
> +methods for computing molecular integrals, solving Hartree-Fock equations and constructing
```suggestion
methods for computing molecular integrals, solving Hartree-Fock equations, and constructing
```

2022-10-18 20:45 UTC, ixfoduap commented on demonstrations/tutorial_qchem_external.py
> +with the electronic structure package `PySCF <https://github.com/sunqm/pyscf>`_ and
```suggestion
with `PySCF <https://github.com/sunqm/pyscf>`_ and
```

2022-10-18 20:45 UTC, ixfoduap commented on demonstrations/tutorial_qchem_external.py
> +`OpenFermion <https://github.com/quantumlib/OpenFermion>`_ tools to compute molecular integrals and
```suggestion
`OpenFermion <https://github.com/quantumlib/OpenFermion>`_ to compute molecular integrals and
```

2022-10-18 20:45 UTC, ixfoduap commented on demonstrations/tutorial_qchem_external.py
> +In PennyLane, molecular Hamiltonians are built with the
```suggestion
In PennyLane, Hamiltonians for quantum chemistry are built with the
```
to avoid repetition of molecular Hamiltonian

2022-10-18 20:45 UTC, ixfoduap commented on demonstrations/tutorial_qchem_external.py
> +The molecular Hamiltonian can then be constructed for a water molecule, as an example, with
```suggestion
For example, the molecular Hamiltonian can then be constructed for a water molecule:
```

2022-10-18 20:45 UTC, ixfoduap commented on demonstrations/tutorial_qchem_external.py
> +# example. First, we define the PySCF molecule object and run a restricted Hartree-Fock
```suggestion
# `6-31G basis <https://en.wikipedia.org/wiki/Basis_set_(chemistry)#Pople_basis_sets>`_ as
# an example. First, we define the PySCF molecule object and run a restricted Hartree-Fock
```

2022-10-31 18:36 UTC, branedrane approved these changes
Looks great!

One quick comment: on deployment, your headshot isn't appearing, so just make sure that's there :)

2022-10-31 18:45 UTC, KetpuntoG commented
> Looks great!
> 
> One quick comment: on deployment, your headshot isn't appearing, so just make sure that's there :)

don't worry about it @soranjh . I'll take care of it before the publication 😄 We have changed the format of the bio. Now it is centralized in the same place and we have changed some paths of the images.

2023-01-02 10:48 UTC, ikurecic reviewed
@KetpuntoG — here are the language-related comments. :)

2023-01-02 10:48 UTC, ikurecic commented on demonstrations/tutorial_qchem_external.py
> +*Author: Soran Jahangiri — Posted: 30 December 2022. Last updated: 30 December 2022.*
```suggestion
*Author: Soran Jahangiri — Posted: 3 January 2023.*
```

2023-01-02 10:48 UTC, ikurecic commented on demonstrations/tutorial_qchem_external.py
> +construct molecular Hamiltonians.
```suggestion
The quantum chemistry module in PennyLane, :mod:`qml.qchem  <pennylane.qchem>`, provides built-in
methods to compute molecular integrals, solve Hartree-Fock equations, and construct
`fully-differentiable <https://pennylane.ai/qml/demos/tutorial_differentiable_HF.html>`_ molecular
Hamiltonians. However, there are many other interesting and widely used quantum chemistry libraries out there. Instead of reinventing the wheel, PennyLane lets you to take advantage of various external resources and libraries to build upon existing research. In this demo we will show you how to integrate PennyLane with `PySCF <https://github.com/sunqm/pyscf>`_ and
`OpenFermion <https://github.com/quantumlib/OpenFermion>`_ to compute molecular integrals and
construct molecular Hamiltonians.
```
Changed verb forms to fit key term definitions better and integrated with Guillermo's suggestion.

2023-01-02 10:48 UTC, ikurecic commented on demonstrations/tutorial_qchem_external.py
> +Hartree-Fock equations. The default backend is the differentiable Hartree-Fock solver of the
```suggestion
Hartree–Fock equations. The default backend is the differentiable Hartree–Fock solver of the
```

2023-01-02 10:48 UTC, ikurecic commented on demonstrations/tutorial_qchem_external.py
> +:mod:`qml.qchem <pennylane.qchem>` module. A Molecular Hamiltonian can also be constructed with a
```suggestion
:mod:`qml.qchem <pennylane.qchem>` module. A molecular Hamiltonian can also be constructed with a

```

2023-01-02 10:48 UTC, ikurecic commented on demonstrations/tutorial_qchem_external.py
> +# following the example `here <https://pyscf.org/quickstart.html#and-2-electron-integrals>`_:
```suggestion
# by following the example `here <https://pyscf.org/quickstart.html#and-2-electron-integrals>`_:
```

2023-01-02 10:48 UTC, ikurecic commented on demonstrations/tutorial_qchem_external.py
> +# These integrals are then mapped to the basis of molecular orbitals
```suggestion
# These integrals are then mapped to the basis of molecular orbitals:
```

2023-01-02 10:48 UTC, ikurecic commented on demonstrations/tutorial_qchem_external.py
> +# `physicists' notation <http://vergil.chemistry.gatech.edu/notes/permsymm/permsymm.pdf>`_:
```suggestion
# Note that the two-electron integral tensor is represented in
# `chemists' notation <http://vergil.chemistry.gatech.edu/notes/permsymm/permsymm.pdf>`_. To use it
# in PennyLane, we need to convert it into the so-called
# *physicists' notation*:
```
Removed link, it was repetitive.

2023-01-02 10:48 UTC, ikurecic commented on demonstrations/tutorial_qchem_external.py
> +# that computes the expectation value of a double-factorized Hamiltonian in second quantization.
```suggestion
# that computes the expectation value of a double-factorized Hamiltonian in the second quantization.
```

2023-01-02 10:48 UTC, ikurecic commented on demonstrations/tutorial_qchem_external.py
> +plugin to be installed by the user with
```suggestion
plugin to be installed by the user with the following:
```
Adding structure, since we're not ending the sentence with a period.

2023-01-02 10:48 UTC, ikurecic commented on demonstrations/tutorial_qchem_external.py
> +For example, the molecular Hamiltonian for a water molecule can be constructed with
```suggestion
For example, the molecular Hamiltonian for a water molecule can be constructed like this:
```

2023-01-02 10:48 UTC, ikurecic commented on demonstrations/tutorial_qchem_external.py
> +# This tutorial demonstrates how to use PennyLane with external libraries such as
```suggestion
# This tutorial demonstrates how to use PennyLane with external quantum chemistry libraries such as

```

2023-01-02 10:48 UTC, ikurecic commented on demonstrations/tutorial_qchem_external.py
> +# 1. We can construct molecular Hamiltonians using a user-installed version of PySCF by passing
```suggestion
# 1. We can construct molecular Hamiltonians in PennyLane by using a user-installed version of PySCF by passing
```

2023-01-02 10:48 UTC, ikurecic commented on demos_quantum-chemistry.rst
> +Quantum chemistry is one of the leading application areas of quantum computers. Master how to use PennyLane to construct molecular Hamiltonians, design quantum circuits for quantum chemistry, and sim
```suggestion
Quantum chemistry is one of the leading application areas of quantum computers. Master the use of PennyLane to construct molecular Hamiltonians, design quantum circuits for quantum chemistry, and simulate properties of molecules and materials.
```

2023-01-03 16:32 UTC, merged