[WIP] What is QChem
PennyLaneAI/qml pull request #584
Opened 2022-09-23 20:57 UTC by isaacdevlugt

### Checklist

- [ ] Images in relevant places

- [ ] All metadata is properly populated

- [ ] Renders properly

2022-10-18 20:56 UTC, branedrane reviewed
Hey! I've created some doodles, and made copious but largely superficial comments on the copy.

2022-10-18 20:56 UTC, branedrane commented on whatisqchem.rst
> +it quantum mechanical..."
Haha, love the Feynman quote. Why not include the whole thing! Also, maybe we should avoid using the phrase "computational complexity", since I gather you intend this informally but might be confusing to those who have seen it in a formal context. Perhaps:

```suggestion
Richard Feynman famously said that "Nature isn't classical, dammit, and if you want to make a simulation of nature, you'd better make it quantum mechanical." To simulate a general quantum system on a classical computer, we need to store values for every basis state. The resources needed scale exponentially, so a classical system cannot efficiently simulate a quantum one.
```

2022-10-18 20:56 UTC, branedrane commented on whatisqchem.rst
> +efficiently.** We can leverage the physical laws of nature to tell us its secrets.
```suggestion
Following Feynman's suggestion, we note that **nature is quantum**. This suggests that if our simulation platform is also quantum, we should be able to simulate nature efficiently, with resources scaling as the size of the target system. For quantum chemistry, this offers a dramatic improvement on traditional, exponentially-costly methods.
```

2022-10-18 20:56 UTC, branedrane commented on whatisqchem.rst
> +of small molecules to a high-precision.
Suggest we rearrange things to emphasize applications first, then discuss size/hardware/scalability:

```suggestion
Quantum properties of materials are of growing importance in a wide range of industries. As a result, quantum chemistry is viewed as the leading candidate for a practical application of quantum computing. Current quantum devices are small, and therefore limited to small systems even if they simulate efficiently. Hence, there is a push to develop scalable algorithms which will work on the larger devices which we expect to become available as current hardware limitations pass.
Progress in this direction includes the ability 
`simulate chemical reactions <https://pennylane.ai/qml/demos/tutorial_chemical_reactions.html>_`, 
`optimize molecular geometries <https://pennylane.ai/qml/demos/tutorial_mol_geo_opt.html>_`, and 
`retrieve low-energy states <https://pennylane.ai/qml/demos/tutorial_vqe.html>_` 
of small molecules to a high-precision.
```

2022-10-18 20:56 UTC, branedrane commented on whatisqchem.rst
> +Leverage Quantum Machine Learning
```suggestion
Leveraging Quantum Machine Learning
```

2022-10-18 21:00 UTC, josh146 commented on whatisqchem.rst
> +.. figure:: /_static/whatisqchem/???.png
I have a chemistry (not properly qchem but close enough?) illustration backlog!

![image](https://user-images.githubusercontent.com/2959003/196543659-7f457b09-5c0f-47af-8f57-c1ce77cf8ca7.png)
![image](https://user-images.githubusercontent.com/2959003/196543681-699cf448-e0dd-4eea-964a-0870ac909392.png)
![image](https://user-images.githubusercontent.com/2959003/196543697-aa6a7871-d4db-4ce4-b431-73f1262f4328.png)
![image](https://user-images.githubusercontent.com/2959003/196543719-c40d32bf-2ae9-41f2-b976-75d285fcdb98.png)

Feel free to use whatever where-ever :)

2022-10-18 21:08 UTC, branedrane commented on whatisqchem.rst
> +.. figure:: /_static/whatisqchem/???.png
Thanks @josh146 !

2022-10-19 18:01 UTC, isaacdevlugt commented on whatisqchem.rst
> +matter is a ubiquitous task in many industries.
Good point! I still like having the last sentence though. How about this? ⬇️ 

```suggestion
Quantum chemistry is an area of research focused on calculating properties of molecules, and the materials built out of them, using quantum mechanics. As an application of quantum computing, it is paramount to the commercial adoption of quantum computers, as simulating properties of
matter is a ubiquitous task in many industries.
```

2022-10-19 18:05 UTC, isaacdevlugt commented on whatisqchem.rst
> +.. image:: /_static/whatisqchem/???.png
hahaha I love any reference to potatoes 🥔

2022-10-19 18:31 UTC, isaacdevlugt commented on whatisqchem.rst
> +it quantum mechanical..."
Not sure we should include "dammit" lol 😆 that's why I left the first half out.

2022-10-19 18:34 UTC, isaacdevlugt commented on whatisqchem.rst
> +efficiently.** We can leverage the physical laws of nature to tell us its secrets.
Love it!

2022-10-19 18:34 UTC, isaacdevlugt commented on whatisqchem.rst
> +.. image:: /_static/whatisqchem/???.png
I dig it

2022-10-19 20:17 UTC, isaacdevlugt commented on whatisqchem.rst
> +of small molecules to a high-precision.
Yeah looks good to me! Couple things ⬇️ 

```suggestion
Understanding the quantum properties of materials are of growing importance in a wide range of industries. As a result, quantum chemistry is viewed as the leading candidate for a practical application of quantum computing. Current quantum devices are small, and are therefore limited to small systems even if they simulate them efficiently. Hence, there is a push to develop scalable algorithms that will work on larger devices which we expect to become available as current hardware limitations pass.
Progress in this direction is being made in earnest with the ability to
	`simulate chemical reactions <https://pennylane.ai/qml/demos/tutorial_chemical_reactions.html>_`, 
	`optimize molecular geometries <https://pennylane.ai/qml/demos/tutorial_mol_geo_opt.html>_`, and 
	`retrieve low-energy states <https://pennylane.ai/qml/demos/tutorial_vqe.html>_` 
	of small molecules to a high precision.
```

2022-10-19 20:18 UTC, isaacdevlugt commented on whatisqchem.rst
> +.. image:: /_static/whatisqchem/???.png
Hmm... might look weird when compiled since the images are so similar.

2022-10-19 20:24 UTC, isaacdevlugt commented on whatisqchem.rst
> +all of which are relevant in quantum chemistry algorithms.
Hmm... Not sure I'm that enticed

2022-10-19 20:24 UTC, isaacdevlugt commented on whatisqchem.rst
> +.. figure:: /_static/whatisqchem/???.png
Lol @branedrane

2022-10-19 20:47 UTC, branedrane commented on whatisqchem.rst
> +.. image:: /_static/whatisqchem/???.png
Fair. What about we get rid of the computer, and just have the circuit "dreaming up" the molecule?

2022-10-20 19:26 UTC, branedrane commented on whatisqchem.rst
> +it quantum mechanical..."
Hmm, that's true. I don't want to take it out since it's so Feynman and adds a bit of colour! But if you're okay leaving it in, we can see whether subsequent reviewers are upset 😅

2022-10-20 19:26 UTC, branedrane commented on whatisqchem.rst
> +and long-term.
Ooh, nice catch!

2022-10-20 19:28 UTC, branedrane commented on whatisqchem.rst
> +and long-term.
I can remove the sentence "as such..." since we have the earlier sentence about commercial adoption?

2022-10-21 13:50 UTC, isaacdevlugt commented on whatisqchem.rst
> +.. image:: /_static/whatisqchem/???.png
Yeah that should work!

2022-10-21 13:58 UTC, isaacdevlugt commented on whatisqchem.rst
> +all of which are relevant in quantum chemistry algorithms.
```suggestion
Many algorithms in quantum chemistry involve an optimization step, where the algorithm contains a *parameterized* quantum circuit whose parameters must be fine-tuned for the application at hand.
Although optimizing quantum circuits is non-trivial in general, we can leverage insights from the adjacent field of quantum machine learning (QML), which provides a guide for training quantum circuits with adjustable parameters.
QML concepts and techniques such as `barren plateaus <https://pennylane.ai/qml/demos/tutorial_barren_plateaus.html>_`, `quantum-inspired optimization routines <https://pennylane.ai/qml/demos/qnspsa.html>_`, and `hardware-compatible differentiation methods <https://pennylane.ai/qml/demos/tutorial_general_parshift.html>_` have all proved to be relevant for quantum chemistry.
```

2022-10-21 13:58 UTC, isaacdevlugt commented on whatisqchem.rst
> +all of which are relevant in quantum chemistry algorithms.
How about that?

2022-10-25 19:14 UTC, branedrane reviewed
Minor adjustments

2022-10-25 19:17 UTC, branedrane commented on whatisqchem.rst
> +.. image:: /_static/whatisqchem/???.png
E.g.

<img width="244" alt="Screen Shot 2022-10-25 at 3 17 41 PM" src="https://user-images.githubusercontent.com/113920759/197862406-df61e35f-499c-47d9-b634-c072b758860b.png">

2022-12-16 18:39 UTC, co9olguy requested changes
Thanks for this! 

Overall it looks good, but major recommendation would be to merge the two sections drawing links between QML and QChem into one. I wasn't quite sure there was sufficiently clear motivation/explanation to draw it out into two sections

2022-12-16 18:39 UTC, co9olguy commented on glossary.rst
> +        A research area focused on addressing classically intractable chemistry problems with quantum computing.
Nice!

2022-12-16 18:39 UTC, co9olguy commented on whatisqchem.rst
> +Research stemming from quantum chemistry could be used to calculate the time evolution of a complex system, estimate the ground state energy of a Hamiltonian, or determine the electronic band structu
```suggestion
Research stemming from quantum chemistry could be used to calculate the time evolution of a complex system, estimate the ground-state energy of a Hamiltonian, or determine the electronic band structure of an exotic material, all of which go *beyond classical physics*. Since quantum computers are also quantum-mechanical, they offer a potential computational advantage in simulating the quantum properties of matter. It is also possible that we can exploit quantum computers to learn new classical methods, using techniques such as `quantum machine learning <https://pennylane.ai/qml/whatisqml.html>`_.
```

2022-12-16 18:39 UTC, co9olguy commented on whatisqchem.rst
> +.. image:: /_static/whatisqchem/quantum_chemistry.svg
Nice image. Is the potato meant to be a cell/bacteria/microbe?

If so, that might be a scale that is a bit too large for a QM-description to be relevant (so the image would be potentially misrepresentative). Would be better if this was a molecule (could be a large one, e.g., dozens-hundreds of atoms).

2022-12-16 18:39 UTC, co9olguy commented on whatisqchem.rst
> +What is Quantum Chemistry?
Overall, this page has fewer bold phrases to catch the eye of someone skimming, compared to QML and QC pages. Anything more that makes sense to have stand out?

2022-12-16 18:39 UTC, co9olguy commented on whatisqchem.rst
> +.. image:: /_static/whatisqchem/computational_quantum_chemistry.svg
Great image :nerd_face:

2022-12-16 18:39 UTC, co9olguy commented on whatisqchem.rst
> +Hence, there is a push to develop **scalable algorithms** that will work on larger devices, which we expect to become available as current hardware limitations pass. Progress in this direction is bei
Slight overflow/wraparound at end of text. Would be good to make small adjustments to image size or text to prevent this overflow
![image](https://user-images.githubusercontent.com/7213358/208164472-84072b51-fd60-4dd4-9a26-482be6a549b1.png)

2022-12-16 18:39 UTC, co9olguy commented on whatisqchem.rst
> +Understanding the quantum properties of materials is of growing importance in a wide range of industries. As a result, quantum chemistry is viewed as the **leading candidate for a practical applicati
found the use of the two pronounrs "they" and "them" so close together to be a bit unclear. I believe the first one is for "current quantum devices" and second one is for "small systems"? Any way to rephrase to avoid potential confusion?

2022-12-16 18:39 UTC, co9olguy commented on whatisqchem.rst
> +another area of research within quantum computing; quantum machine learning (QML).
```suggestion
another area of research within quantum computing: quantum machine learning (QML).
```

2022-12-16 18:39 UTC, co9olguy commented on whatisqchem.rst
> +.. image:: /_static/whatisqchem/QChem_circuit.svg
very cool image :100:

2022-12-16 18:39 UTC, co9olguy commented on whatisqchem.rst
> +Generally, QML algorithms are a non-trivial topic. Luckily, we are still able to transfer concepts from QML to quantum
This short paragraph could do better imo.

> Generally, QML algorithms are a non-trivial topic.
Why say/mention this? It doesn't seem to add info relevant to the stated topic of quantum chemistry

> Luckily, we are still able to transfer concepts from QML to quantum chemistry algorithms like the variational quantum eigensolver.

This is the natural link to make here, but I think it gets the causality backwards. One could argue that VQE was among the first (the first?) algorithm that kicked off modern thinking on QML. Would be good to rephrase things here, because it gives the (incorrect) sense that QML was its own field and someone took ideas from there to arrive at VQE. So focus instead on the idea that quantum chemistry and QML have a mutually symbiotic relationship

2022-12-16 18:39 UTC, co9olguy commented on whatisqchem.rst
> +Quantum chemistry for quantum machine learning
I feel like there is a single coherent story to tell between these two subsections. I actually wasn't able to discern what distinction was being made between the two. Recommend merging into one section (though both images are :kissing::ok_hand:)

2022-12-16 20:50 UTC, isaacdevlugt commented
> Thanks for this!
> 
> Overall it looks good, but major recommendation would be to merge the two sections drawing links between QML and QChem into one. I wasn't quite sure there was sufficiently clear motivation/explanation to draw it out into two sections

This was originally one section, but @ikurecic raised the point that the other "What is X" articles each have one more section compared to this one, so we split it in two. @ikurecic you okay if I revert this?

2022-12-18 11:59 UTC, ikurecic commented
> > Thanks for this!
> > Overall it looks good, but major recommendation would be to merge the two sections drawing links between QML and QChem into one. I wasn't quite sure there was sufficiently clear motivation/explanation to draw it out into two sections
> 
> This was originally one section, but @ikurecic raised the point that the other "What is X" articles each have one more section compared to this one, so we split it in two. @ikurecic you okay if I revert this?

@isaacdevlugt — by all means, revert it, but we also do need a bit more content + to look at copy concerns Nathan pointed out. Since you wrote this one and have a much better idea of the intended meaning, any chance you'd want to do that?
We have until January.

2022-12-18 12:03 UTC, ikurecic commented on whatisqchem.rst
> +.. image:: /_static/whatisqchem/quantum_chemistry.svg
The idea was just to have a potato, to represent 'natural materials' in a cartoony way. I'll ask Tarik to make an alternative, thanks.

2022-12-20 17:23 UTC, isaacdevlugt commented on whatisqchem.rst
> +Research stemming from quantum chemistry could be used to calculate the time evolution of a complex system, estimate the ground-state energy of a Hamiltonian, or determine the electronic band structu
```suggestion
Research stemming from quantum chemistry could be used to calculate the time evolution of a complex system, estimate the ground-state energy of a Hamiltonian, or determine the electronic band structure of an exotic material, all of which go *beyond classical physics*. Since quantum computers are also quantum-mechanical, they offer a potential quantum computational advantage in simulating the quantum properties of matter. It is also possible that we can exploit quantum computers to learn new classical methods, using techniques such as `quantum machine learning <https://pennylane.ai/qml/whatisqml.html>`_.
```

2022-12-20 17:24 UTC, isaacdevlugt commented on whatisqchem.rst
> +Research stemming from quantum chemistry could be used to calculate the time evolution of a complex system, estimate the ground-state energy of a Hamiltonian, or determine the electronic band structu
Maybe this can be made more bold? Just going off of @co9olguy's comment above

2022-12-20 17:25 UTC, isaacdevlugt commented on whatisqchem.rst
> +Following Feynman's suggestion, we note that **nature is quantum**. This suggests that if our simulation platform is also quantum, we should be able to simulate nature efficiently, with resources sca
trying to be more bold here as well 

```suggestion
Following Feynman's suggestion, we note that **nature is quantum**. This suggests that if our simulation platform is also quantum, we should be able to simulate nature better than classical computers can, with resources scaling as the size of the target system rather than exponential. For quantum chemistry, this offers a dramatic improvement on traditional, exponentially-costly methods.
```

2022-12-20 17:26 UTC, isaacdevlugt commented on whatisqchem.rst
> +Understanding the quantum properties of materials is of growing importance in a wide range of industries. As a result, quantum chemistry is viewed as the **leading candidate for a practical applicati
```suggestion
Understanding the quantum properties of materials is of growing importance in a wide range of industries. As a result, quantum chemistry is viewed as the **leading candidate for a practical application of quantum computing**. Current quantum devices are small, and are therefore limited to efficiently simulating *small systems*.
```

2022-12-20 17:29 UTC, isaacdevlugt commented on whatisqchem.rst
> +.. image:: /_static/whatisqchem/quantum_chemistry.svg
🥔

2022-12-20 17:35 UTC, isaacdevlugt commented on whatisqchem.rst
> +Quantum chemistry for quantum machine learning
These sections were originally just one section:

From https://github.com/PennyLaneAI/qml/pull/584/commits/c68a17970611a7143a2b80683b08914c3e0733a0

```
Many quantum chemistry algorithms require *optimization* as a critical step; an algorithm may contain parameters that must be 
fine-tuned for a specific application. Optimization within quantum computing is a non-trivial topic, 
but luckily we can transfer concepts from quantum machine learning or **QML**, another research area within quantum computing.

The advent of machine learning in the physical sciences has spurred countless generalizable techniques for the simulation of
matter. Applying such techniques to trainable quantum circuits has led to invaluable discoveries, like `barren plateaus <https://pennylane.ai/qml/demos/tutorial_barren_plateaus.html>_`, `quantum-inspired optimization routines <https://pennylane.ai/qml/demos/qnspsa.html>_`, and `hardware-compatible differentiation methods <https://pennylane.ai/qml/demos/tutorial_general_parshift.html>_`, all of which are relevant in quantum chemistry algorithms.
```

2022-12-20 17:41 UTC, isaacdevlugt commented on whatisqchem.rst
> +Quantum chemistry for quantum machine learning
I can't make a proper suggestion here because of the comments, but the `Quantum machine learning for quantum chemistry` and `Quantum chemistry for quantum machine learning` sections would be merged into:

```
Leveraging quantum machine learning
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Many quantum chemistry algorithms require *optimization* as a critical step; an algorithm may contain parameters that must be 
fine-tuned for a specific application. Optimization within quantum computing is a non-trivial topic, but luckily we can transfer 
concepts from quantum machine learning or **QML**, another research area within quantum computing.

The advent of machine learning in the physical sciences has spurred countless generalizable techniques for the simulation of
matter. Applying such techniques to trainable quantum circuits has led to invaluable discoveries, like
`barren plateaus <https://pennylane.ai/qml/demos/tutorial_barren_plateaus.html>_`, 
`quantum-inspired optimization routines <https://pennylane.ai/qml/demos/qnspsa.html>_`, 
and 
`hardware-compatible differentiation methods <https://pennylane.ai/qml/demos/tutorial_general_parshift.html>_`, 
all of which are relevant in quantum chemistry algorithms.
```

2022-12-20 17:42 UTC, isaacdevlugt commented on whatisqchem.rst
> +Quantum chemistry for quantum machine learning
@ikurecic you ok with this?

2022-12-20 18:47 UTC, ikurecic commented on whatisqchem.rst
> +Following Feynman's suggestion, we note that **nature is quantum**. This suggests that if our simulation platform is also quantum, we should be able to simulate nature better than classical computers
```suggestion
Following Feynman's suggestion, we note that **nature is quantum**. This suggests that if our simulation platform is also quantum, we should be able to simulate nature better than classical computers can, with resources scaling as the size of the target system, rather than exponentially. For quantum chemistry, this offers a dramatic improvement on traditional, exponentially-costly methods.
```

2022-12-20 19:38 UTC, isaacdevlugt commented on whatisqchem.rst
> +What is Quantum Chemistry?
Made some minor tweaks here and there. Let me know how you feel about them!

2023-01-06 17:02 UTC, co9olguy approved these changes
Nice, reads well!

Just a couple very easy minor tweaks/suggestions. Please check those and remedy, and when they are dealt with, it's g2g

2023-01-06 17:02 UTC, co9olguy commented on whatisqchem.rst
> +Hence, there is a push to develop **scalable algorithms** that will work on larger devices, which we expect to become available as current hardware limitations pass. Progress in this direction is bei
```suggestion
Hence, there is a push to develop **scalable algorithms** that will work on larger devices, which we expect to become
available as current hardware limitations pass. Progress in this direction is being made in earnest with the ability to
`simulate chemical reactions <https://pennylane.ai/qml/demos/tutorial_chemical_reactions.html>`_, `optimize
molecular geometries <https://pennylane.ai/qml/demos/tutorial_mol_geo_opt.html>`_, and `retrieve low-energy states
<https://pennylane.ai/qml/demos/tutorial_vqe.html>`_ of small molecules to a high precision.
```

2023-01-06 17:02 UTC, co9olguy commented on whatisqchem.rst
> +Hence, there is a push to develop **scalable algorithms** that will work on larger devices, which we expect to become available as current hardware limitations pass. Progress in this direction is bei
(noticed there was an extraneous EOL tab character; took the liberty to break up the paragraph while I was at it)

2023-01-06 22:48 UTC, isaacdevlugt commented on index.rst
> +                                <strong>What is QML?</strong>
```suggestion
                                <strong>What is QChem?</strong>
```

2023-01-06 22:48 UTC, isaacdevlugt commented on index.rst
> +                                <img src="_static/brain_board.png" class="img-fluid" style="max-width: 86px;"></img>
```suggestion
                                <img src="_static/whatisqchem/QChem_circuit.svg" class="img-fluid" style="max-width: 86px;"></img>
```

2023-01-06 22:49 UTC, isaacdevlugt commented on whatisqchem.rst
> +.. role:: html(raw)
Nope! Good point. Will stick it somewhere 👀

2023-01-06 22:50 UTC, isaacdevlugt commented on whatisqchem.rst
> +Research stemming from quantum chemistry could be used to calculate the time evolution of a complex system, estimate the ground-state energy of a Hamiltonian, or determine the electronic band structu
```suggestion
Research stemming from quantum chemistry could be used to calculate the time evolution of a complex system, estimate the ground-state energy of a molecule, or determine the electronic band structure of an exotic material, all of which go *beyond classical physics*. Since quantum computers are also quantum-mechanical, they offer a potential quantum computational advantage in simulating the quantum properties of matter. It is also possible that we can exploit quantum computers to learn new classical methods, using techniques such as `quantum machine learning <https://pennylane.ai/qml/whatisqml.html>`_.
```

2023-01-06 22:51 UTC, isaacdevlugt commented on whatisqchem.rst
> +optimization algorithms within quantum computing falls back on another area of research
```suggestion
may contain parameters that must be fine-tuned for a specific application. What we know about 
optimizing quantum algorithms falls back on another area of research 
```

2023-01-06 22:52 UTC, isaacdevlugt commented on whatisqchem.rst
> +within quantum computing: quantum machine learning (QML).
See above

2023-01-06 22:58 UTC, isaacdevlugt commented on index.rst
> +                                <strong>What is QML?</strong>
@co9olguy is there somewhere else where this issue can be documented so that it can be fixed later? Maybe as an issue is best?

2023-01-06 22:58 UTC, isaacdevlugt commented on whatisqchem.rst
> +check out the gallery of hands-on :doc:`quantum chemistry demonstrations <demonstrations>`.
Good point!

2023-01-06 22:59 UTC, isaacdevlugt commented on whatisqchem.rst
> +check out the gallery of hands-on :doc:`quantum chemistry demonstrations <demonstrations>`.
```suggestion
check out the gallery of hands-on :doc:`quantum chemistry demonstrations <demos_quantum-chemistry>`.
```

2023-01-13 20:11 UTC, BM7878 approved these changes

2023-01-21 20:59 UTC, ikurecic commented on whatisqchem.rst
> +.. role:: html(raw)
We're still missing the image, right? The structure should be consistent with the other two pages, so it would really be helpful if you could do that, @isaacdevlugt . If you can't, please tell me and I'll take over.

2023-01-21 20:59 UTC, ikurecic commented on index.rst
> +                                <strong>What is QML?</strong>
No worries with that, this PR won't be ingested as is — the structure is beyond our scope. :)

2023-01-23 01:21 UTC, josh146 commented on index.rst
> +                                <strong>What is QML?</strong>
@ikurecic so will all modified/added files (except for `whatisqchem`) be deleted from this PR?

2023-01-23 14:10 UTC, ashishks0522 requested changes

2023-01-23 14:10 UTC, ashishks0522 commented on glossary.rst
> +    :doc:`Quantum Chemistry <whatisqchem>`
```suggestion
    :doc:`Quantum Chemistry <what-is-quantum-chemistry>`
```

2023-01-23 14:10 UTC, ashishks0522 commented on index.rst
> +                    <a href="whatisqchem.html">
```suggestion
                    <a href="what-is-quantum-chemistry.html">
```

2023-01-23 14:10 UTC, ashishks0522 commented on index.rst
> +    whatisqchem
```suggestion
    what-is-quantum-chemistry
```

2023-01-23 14:10 UTC, ashishks0522 commented on whatisqchem.rst
> +.. role:: html(raw)
if we could rename the file name to `what-is-quantum-chemistry.rst` as per product requirements [here](https://docs.google.com/document/d/12TTsdBTTBoJ9aYi2NgMnDct_5Sxa7k-K2Xo7fbUAjqY/edit).

2023-01-23 16:06 UTC, ashishks0522 approved these changes

2023-01-23 16:11 UTC, ashishks0522 reviewed
Also if we could change the base from `master` to `sc-30752-create-quantum-chemistry-subhub` for this PR

That would help us manage merging sub-hubs into superhub PR as they get completed.

2023-01-23 16:43 UTC, isaacdevlugt commented
> Also if we could change the base from `master` to `sc-30752-create-quantum-chemistry-subhub` for this PR
> 
> That would help us manage merging sub-hubs into superhub PR as they get completed.

After I rebased, the deployment didn't render the actual "What is qchem" page:

<img width="803" alt="Screenshot 2023-01-23 at 11 43 06 AM" src="https://user-images.githubusercontent.com/34751083/214097865-161e4525-ca8f-4e3d-aaa5-d4a992eda9f2.png">

2023-01-23 16:49 UTC, josh146 commented
@isaacdevlugt this is because the card link needs to be changed to `what-is-quantum-chemistry`; the actual page is https://qml-build-previews.pennylane.ai/pull_request_build_preview/584/what-is-quantum-chemistry.html

2023-01-23 16:49 UTC, josh146 commented
BTW something seems to have gone wrong in the rebase, there are now a lot of files marked as modified that shouldn't be modified 😬

2023-01-23 17:55 UTC, isaacdevlugt commented
@josh146 I fixed the rebasing errors, but not sure why there's a diff for `.github/workflows/build-dev.yml` and `.github/workflows/build-master.yml` 🤔

2023-01-23 18:24 UTC, isaacdevlugt commented
I think we're good @josh146 !

2023-01-23 21:11 UTC, josh146 commented on index.rst
> +    what-is-quantum-chemistry
@isaacdevlugt this will need to be moved to the subhub TOC :)

2023-01-24 22:10 UTC, co9olguy commented on what-is-quantum-chemistry.rst
> +`quantum-inspired optimization routines <https://pennylane.ai/qml/demos/qnspsa.html>`_,
Think this one would be better to link here
```suggestion
`quantum-inspired optimization routines <https://pennylane.ai/qml/demos/tutorial_quantum_natural_gradient.html>`_, 
```

2023-01-26 14:37 UTC, josh146 approved these changes
Thanks everyone, just some small suggestions and then I think it is ready to merge :)

2023-01-26 14:37 UTC, josh146 commented on README.md
> +- [What is quantum chemistry?](https://pennylane.ai/qml/whatisqml.html) Understand why
```suggestion
- [What is quantum chemistry?](https://pennylane.ai/qml/what-is-quantum-chemistry.html) Understand why
```

2023-01-26 14:37 UTC, josh146 commented on what-is-quantum-chemistry.rst
> +   :property="og:description": Quantum chemistry is a research area focused on addressing classically intractable chemistry problems with quantum computing.
```suggestion
   :property="og:description": Learn why quantum chemistry is one of the leading applications of quantum computing through our collection of articles, tutorials, and demos. 
```

2023-01-26 14:37 UTC, josh146 commented on what-is-quantum-chemistry.rst
> +   :property="og:description": Quantum chemistry is a research area focused on addressing classically intractable chemistry problems with quantum computing.
While the original description answers the question of 'What is quantum chemistry?', if I were to see the social media preview on another website for this page, I would want to know 'why should I click on this link?'. 

So I think it is more important to describe the _outcomes_ of reading this page, rather than answering the page title question 🙂

2023-01-26 14:37 UTC, josh146 commented on what-is-quantum-chemistry.rst
> +To find out more, visit the `PennyLane Documentation <https://pennylane.readthedocs.io>`_, or
```suggestion
To find out more, visit the `PennyLane Documentation <https://docs.pennylane.ai>`_, or
```

2023-01-26 17:33 UTC, merged