First batch of authorships added/modified
PennyLaneAI/qml pull request #607
Opened 2022-10-13 18:34 UTC by ikurecic

Lots of small things changed. Might be broken beyond recognition. I did my best. ♥
Changes for other demos/authors will be made in due time, as more information (and time) becomes available.

Also, I removed email addresses (next to author names under titles) in anticipation of adding two items in the future: author pages with summaries and contact information; calls to action to ask about demos on our Slack, where we can redirect to the author. This might be a bad idea, so please feel free to roll that back.

2022-10-17 16:01 UTC, KetpuntoG requested changes
Incredible work! Thank you very much for the effort😄
Here are some comments :)

2022-10-17 16:01 UTC, KetpuntoG commented on demos_quantum-chemistry.rst
> +    demos/vqe_parallel
when changing from "tutorial_name" to "name", we have to adapt the demo, we would have to manually enter the outputs. In that case, I think it is something to be done in a different PR in the future

2022-10-17 16:01 UTC, KetpuntoG commented on demos_qml.rst
> +    demos/ensemble_multi_qpu
Same here:

when changing from "tutorial_name" to "name", we have to adapt the demo, we would have to manually enter the outputs. In that case, I think it is something to be done in a different PR in the future

2022-10-26 17:52 UTC, KetpuntoG approved these changes
All good! Great PR Ivana, good job 💪

2022-10-26 17:52 UTC, KetpuntoG commented on demos_quantum-chemistry.rst
> +    demos/vqe_parallel
Okey, as far as I see the change was made (so for this PR there is no problem), although there is some cell that was not updated. I add it in the database @ikurecic 

<img width="1026" alt="Captura de Pantalla 2022-10-26 a las 13 47 27" src="https://user-images.githubusercontent.com/65235481/198099210-b4a5b815-5f53-46c5-a793-8fe796f42cf9.png">

2022-10-26 17:52 UTC, KetpuntoG commented on demonstrations/tutorial_rotoselect.py
> +*Author: Angus Lowe — Posted: 16 October 2019. Last updated: 20 Jan 2021.*
This suggestion is still here

2022-10-26 19:31 UTC, ikurecic commented on demonstrations/tutorial_mol_geo_opt.py
>  *Author: Alain Delgado. Posted: 30 June 2021. Last updated: 25 June 2022.*
Sorry, I don't think I understand. What do you mean?

2022-10-27 09:48 UTC, ikurecic commented on demonstrations/tutorial_quantum_gans.py
> +# About the author
I've tried a million things: fixed references, used different heading levels in five different ways, and I can figure it out. 😬
I don't have Sphinx locally (yet), so maybe this would be easier for you to fix?

2022-10-27 14:42 UTC, merged