[Demo] Perturbative Gadgets for Variational Quantum Algorithms
PennyLaneAI/qml pull request #610
Opened 2022-10-18 16:55 UTC by SimonCichy

**Title:** Perturbative Gadgets for Variational Quantum Algorithms

**Summary:**
A tutorial to explore the application of perturbative gadgets in variational quantum algorithms to delay the onset of cost-function-dependent barren plateaus. Substituting a global Hamiltonian with its gadgetized equivalent allows to train the algorithm on a local cost function and still finding the target minimum, thus avoiding the issue of cost-function-dependent barren plateaus.

**Relevant references:**
https://github.com/SimonCichy/barren-gadgets/tree/main/Pennylane-tutorial
https://arxiv.org/pdf/2210.03099.pdf

**Possible Drawbacks:**

**Related GitHub Issues:** #593

2022-10-18 17:20 UTC, SimonCichy commented
Of course, I did not pay attention when translating the changes from the clone to the fork. Hopefully the checks are successful now

2022-10-18 17:22 UTC, josh146 commented
Looking good so far! Thanks @SimonCichy. Note that the first builds of a PR here may take awhile, but once successful, subsequent builds are much faster :)

2022-10-18 18:23 UTC, josh146 commented on demonstrations/tutorial_barren_gadgets.py
> +barren plateaus, as proposed in Ref.[#cichy2022]
```suggestion
barren plateaus, as proposed in Ref.[#cichy2022]_
```
This will ensure it automatically links to the Bibliography at the bottom

2022-10-18 18:25 UTC, josh146 commented on demonstrations/tutorial_barren_gadgets.py
> +- https://pennylane.ai/qml/demos/tutorial_local_cost_functions.html
```suggestion
If you are not familiar yet with the concept of barren plateaus, I recommend you
first check out the demonstrations on :doc:`barren plateaus </demos/tutorial_barren_plateaus>`
and :doc:`avoiding barren plateaus with local cost functions </demos/tutorial_local_cost_functions>`.
```

Using this style of local link ensure that the tutorial is not affected if we ever change the URL of the website :)

2022-10-18 18:25 UTC, josh146 commented on demonstrations/tutorial_barren_gadgets.py
> +#    :width: 90%
```suggestion
.. figure:: ../demonstrations/barren_gadgets/gadget-terms-tutorial.png
    :align: center
    :width: 90%
```

2022-10-18 18:28 UTC, josh146 commented on demonstrations/tutorial_barren_gadgets.py
> +# works on cost function dependent barren plateaus [#cerezo2021].
```suggestion
# works on cost function dependent barren plateaus [#cerezo2021]_.
```

2022-10-18 18:28 UTC, josh146 commented on demonstrations/tutorial_barren_gadgets.py
> +As shown in Ref. [#cichy2022], this construction results in a spectrum that is similar
```suggestion
As shown in Ref. [#cichy2022]_, this construction results in a spectrum that is similar
```

2022-10-19 18:05 UTC, KetpuntoG reviewed
Again, great job! 😊 Here are some first comments and suggestions about the demo to work on them

2022-10-19 18:05 UTC, KetpuntoG commented on demonstrations/tutorial_barren_gadgets.py
> +
<img width="715" alt="Captura de Pantalla 2022-10-19 a las 13 59 22" src="https://user-images.githubusercontent.com/65235481/196769014-6ce3fdac-bf1d-4aff-959f-0b8be8b3dbbe.png">

In this case I think it is not necessary to show the prints, the graph gives all the necessary information of the final result :)

2022-10-19 18:05 UTC, KetpuntoG commented on demonstrations/tutorial_barren_gadgets.py
> +import matplotlib.pyplot as plt
It is more didactic to put the imports when you need them. I would put `matplotlib` library in the last cell and add the "seaborn" style to make it more elegant.

```python
import matplotlib.pyplot as pet
plt.style.use("seaborn")
```

2022-10-19 18:27 UTC, josh146 commented on demonstrations/tutorial_barren_gadgets.py
> +#    <https://doi.org/10.1038/s41467-021-21728-w>`__, 2021.
@SimonCichy you can also add an author bio here :) It looks like this:

```suggestion
#    <https://doi.org/10.1038/s41467-021-21728-w>`__, 2021.
#
# About the author
# ----------------
#
# .. bio:: Simon Cichy
#    :photo: ../_static/authors/simon_cichy.jpg
# 
#    Simon is...
```

You can also feel free to add any links (e.g., to personal websites) in your bio if you would like to!

2022-10-20 07:30 UTC, SimonCichy commented on demonstrations/tutorial_barren_gadgets.py
> +term1 = qml.operation.Tensor(qml.PauliX(0), qml.PauliX(1), qml.PauliY(2), qml.PauliZ(3))
Does it generate the same kind of object? I am aware one can write it in that way, but I have the feeling that at some point when working on my code it made a difference whether I used one or the other. It has been a few months, so I'm probably wrong about that, but was it always the case, that generating the Hamiltonian as you propose you could still obtain the Hcomp.ops and Hcomp.coeffs?

2022-10-20 07:34 UTC, SimonCichy commented on demonstrations/tutorial_barren_gadgets.py
> +
Sure! I'll remove it at the end. It's just helpful for me when checking that it runs as expected, to have a quick reaction and not waiting for the full run to know it works

2022-10-20 13:05 UTC, SimonCichy commented on demonstrations/tutorial_barren_gadgets.py
> +.. figure:: ../demonstrations/barren_gadgets/gadget-terms-tutorial.png
Thanks!

2022-10-20 17:41 UTC, SimonCichy commented on demonstrations/tutorial_barren_gadgets.py
> +term1 = qml.operation.Tensor(qml.PauliX(0), qml.PauliX(1), qml.PauliY(2), qml.PauliZ(3))
Found the issue: for this example, where the Hamiltonian has several terms, it's fine and everything works out. However, in the next example where the Hamiltonian has only one term the object is a Tensor, and does not have the attribute ops (which I use in the gadgetization)

2022-10-20 17:43 UTC, SimonCichy commented on demonstrations/tutorial_barren_gadgets.py
> +Hcomp = qml.Hamiltonian([1], [term1])
Oh, I see, the '1 *' was not decorative. With this added Hcomp is indeed a Hamiltonian object

2022-10-20 17:47 UTC, SimonCichy commented on demonstrations/tutorial_barren_gadgets.py
> +term1 = qml.operation.Tensor(qml.PauliX(0), qml.PauliX(1), qml.PauliY(2), qml.PauliZ(3))
Solved (kind of): I had missed the factor 1 you added in the second example. With the factor it indeed becomes a Hamiltonian object. I had never realized that, that's probably why I used the Hamiltonian class throughout my code.

2022-10-20 19:15 UTC, KetpuntoG commented on demonstrations/tutorial_barren_gadgets.py
> +term1 = qml.operation.Tensor(qml.PauliX(0), qml.PauliX(1), qml.PauliY(2), qml.PauliZ(3))
That's right, it may seem counterintuitive but a PauliZ gate by itself we do not consider a Hamiltonian in Pennylane. When we multiply it by 1 we interpret it as a Hamiltonian

2022-10-20 20:39 UTC, KetpuntoG reviewed
Here are a few other comments :)
It's usually a good practice when working on the review, to start accepting the suggestions when there is the option (if you agree 😄) and then work on the comments. 
On the other hand, If you have already worked on a particular comment, it would be good for me if you put 👍 to be sure that you have worked on it
And of course, if you have any questions, feel free to ask

2022-10-20 20:39 UTC, KetpuntoG commented on demonstrations/tutorial_barren_gadgets.py
> +while the perturbation part implements one of the operators in the Pauli word
```suggestion
On the other hand, the perturbation part implements one of the operators in the Pauli word

```

2022-10-20 20:39 UTC, KetpuntoG commented on demonstrations/tutorial_barren_gadgets.py
> +# :file:`../demonstrations/barren_gadgets/barren_gadgets.py`
```suggestion
```

2022-10-20 20:39 UTC, KetpuntoG commented on demonstrations/tutorial_barren_gadgets.py
> +# you can find the code here (
```suggestion
# you can find the code `here <https://pennylane.ai/qml/demos/barren_gadgets/barren_gadgets.py>`__

```

2022-10-20 20:39 UTC, KetpuntoG commented on demonstrations/tutorial_barren_gadgets.py
> +# you can find the code here (
I think this solves the problem

2022-10-20 20:39 UTC, KetpuntoG commented on demonstrations/tutorial_barren_gadgets.py
> +# ).
```suggestion
# .

```

2022-10-20 20:39 UTC, KetpuntoG commented on demonstrations/tutorial_barren_gadgets.py
> +# ``build_ansatz`` (for the details:
```suggestion
# ``build_ansatz`` (more details `here <https://pennylane.ai/qml/demos/barren_gadgets/layered_ansatz.py>`__

```

2022-10-20 20:39 UTC, KetpuntoG commented on demonstrations/tutorial_barren_gadgets.py
> +# :file:`../demonstrations/barren_gadgets/layered ansatz.py`
```suggestion
```

2022-10-20 20:39 UTC, KetpuntoG commented on demonstrations/tutorial_barren_gadgets.py
> +# `qml.Hamiltonian <https://pennylane.readthedocs.io/en/stable/code/api/pennylane.Hamiltonian.html>`_
This comment is a reminder to me to update this link. We use to reference our classes in other ways

2022-10-20 20:39 UTC, KetpuntoG commented on demonstrations/tutorial_barren_gadgets.py
> +# Using the class PerturbativeGadgets, we can automatedly
```suggestion
# Using the class `PerturbativeGadgets`, we can automatedly

```

2022-10-20 20:39 UTC, KetpuntoG commented on demonstrations/tutorial_barren_gadgets.py
> +# `qml.SimplifiedTwoDesign <https://pennylane.readthedocs.io/en/latest/code/api/pennylane.SimplifiedTwoDesign.html#pennylane.SimplifiedTwoDesign>`_,
same here, I will update this link

2022-10-20 20:39 UTC, KetpuntoG commented on demonstrations/tutorial_barren_gadgets.py
> +# It is a very simple example. but we see that the training of our circuit using
```suggestion
# It is a very simple example but we see that the training of our circuit using

```

2022-10-20 21:09 UTC, josh146 commented on demonstrations/tutorial_barren_gadgets.py
> +Hcomp = qml.Hamiltonian([1], [term1])
Note that we are in the process of updating/improving our operators in PennyLane. this is a long term project, but it will start to get better/more consistent with each release 😆 

Soon the 1 will no longer be needed!

2022-10-20 21:14 UTC, josh146 commented on demonstrations/tutorial_barren_gadgets.py
> +# :file:`../demonstrations/barren_gadgets/barren_gadgets.py`
```suggestion
# :download:`../demonstrations/barren_gadgets/barren_gadgets.py` 
```

2022-10-20 21:14 UTC, josh146 commented on demonstrations/tutorial_barren_gadgets.py
> +# :file:`../demonstrations/barren_gadgets/barren_gadgets.py`
@KetpuntoG sorry I think this was my fault - I think this will fix it!

2022-10-20 21:14 UTC, josh146 commented on demonstrations/tutorial_barren_gadgets.py
> +# :file:`../demonstrations/barren_gadgets/layered ansatz.py`
```suggestion
# :download:`../demonstrations/barren_gadgets/layered ansatz.py` 
```

2022-10-20 21:15 UTC, josh146 commented on demonstrations/tutorial_barren_gadgets.py
> +# you can find the code here (
Lets see if the `:file:` -> `:download:` fix solves it 🤞

2022-10-20 21:15 UTC, josh146 commented on demonstrations/tutorial_barren_gadgets.py
> +# ``build_ansatz`` (for the details:
Lets see if the :file: -> :download: fix solves it 🤞

2022-10-21 08:38 UTC, SimonCichy commented
Thanks @KetpuntoG for your comment on good practices, that helps a lot. Should I also add the changes I make as suggestions? I'll have to check how to do that

2022-10-21 21:19 UTC, josh146 commented
> Should I also add the changes I make as suggestions?

@SimonCichy completely up to you, whichever you prefer :) Feel free to commit/push locally using git. For small/one liner changes, you could also use the Suggestions functionality on GitHub

2022-10-21 21:20 UTC, josh146 commented on demonstrations/tutorial_barren_gadgets.py
> +# :download:`../demonstrations/barren_gadgets/barren_gadgets.py`
```suggestion
# :download:`barren_gadgets.py <../demonstrations/barren_gadgets/barren_gadgets.py>` 
```

2022-10-21 21:20 UTC, josh146 commented on demonstrations/tutorial_barren_gadgets.py
> +# :download:`../demonstrations/barren_gadgets/layered_ansatz.py`
```suggestion
# :download:`layered_ansatz.py <../demonstrations/barren_gadgets/layered_ansatz.py>` 
```

2022-10-26 13:20 UTC, KetpuntoG commented
Hey @SimonCichy , it would help me for follow the review if you mark comments with a "👍" if you have already worked with them. 

<img width="840" alt="Captura de Pantalla 2022-10-26 a las 9 16 30" src="https://user-images.githubusercontent.com/65235481/198035758-ef9c5630-ed5c-4733-8eed-c193ec1a3669.png">

On the other hand, if you have already worked with all of them, you can let me know by requesting a new review here:

<img width="384" alt="Captura de Pantalla 2022-10-26 a las 9 18 40" src="https://user-images.githubusercontent.com/65235481/198036309-1842a1e7-4852-4ad5-8444-c35a5ace0c5d.png">

Simply click on the symbol 🔄

2022-10-28 13:00 UTC, SimonCichy commented
Hi @KetpuntoG, I will try to remember reacting to your comments when working on them. There are a few on which I had worked but not notified you yet (mainly on adding explanations), because I thought I would re-read later to see if my explanations where clear. Then I could not get back for some days due to other things. I will get back to it soon, and mark your comments once I am happy with it

2022-10-28 13:20 UTC, SimonCichy commented on demonstrations/tutorial_barren_gadgets.py
> +from barren_gadgets.barren_gadgets import PerturbativeGadgets
If you consider the explanations sufficient, and now that we have the download links, this could be resolved, right?

2022-10-31 14:11 UTC, KetpuntoG commented
Great, I look forward to the re-review notification! 😄

2022-11-02 12:08 UTC, SimonCichy commented
I seem to have a bit of an issue: I have changed quite a few things according to the comments, but the changes are not reflected in the latest deployments. Not sure if there is something wrong with what I added, but I don't know how to debug it either.

2022-11-02 14:20 UTC, KetpuntoG commented
> @KetpuntoG, @josh146, I seem to have a bit of an issue: I have changed quite a few things according to the comments, but the changes are not reflected in the latest deployments. Not sure if there is something wrong with what I added, but I don't know how to debug it either.

Hey @SimonCichy !This may be due to the fact that you are loading the demo from cache. To fix it, copy the link and open it in an incognito window :)

2022-11-02 17:06 UTC, SimonCichy commented on demonstrations/tutorial_barren_gadgets.py
> +# `QNode <https://docs.pennylane.ai/en/stable/code/api/pennylane.QNode.html>`_.
And here I added a reference to the QNode, maybe it is not necessary, but since I was adding references to the other classes I did this one too

2022-11-02 17:20 UTC, SimonCichy commented on demonstrations/tutorial_barren_gadgets.py
> +#    `Simon <https://simoncichy.github.io/about.html/>`__ is a graduate in quantum engineering from ETH Zürich. He is interested in quantum machine learning and near-term quantum algorithms in genera
And that link does not seem to work, I am not sure why yet

2022-11-02 17:43 UTC, KetpuntoG reviewed
Awesome job! For my part, with this last comments, the demo would be ready 😊 we will give a second review before publication. The next reviewer will comment if there are new things to modify

2022-11-02 17:43 UTC, KetpuntoG commented on demonstrations/tutorial_barren_gadgets.py
> +
to prevent the output from appearing, add `plt.show()` to the end of the cell.
(import matplotlib before if you haven't done so)

2022-11-02 17:43 UTC, KetpuntoG commented on demonstrations/tutorial_barren_gadgets.py
> +.. figure:: ../demonstrations/barren_gadgets/gadget-terms-tutorial.png
I don't know if it will be very difficult but in the image you would have to change "s" for "i" if I'm not mistaken.

2022-11-04 11:36 UTC, SimonCichy commented
Great! Happy to see it slowly taking shape :) I believe I have implemented all the comments on my side, the only things I see left are the comments from you @KetpuntoG about updating the links to reference pennylane classes (Hamiltonian x2, QNode and SimplifiedTwoDesign). Also, for some reason the link in the author bio does not seem to work when writing it like the other links.

2022-11-04 12:00 UTC, SimonCichy commented
> Also, for some reason the link in the author bio does not seem to work when writing it like the other links.
All the other author bios including links to personal websites have them in plain text, so maybe it can't be done as is now?

2022-11-04 21:47 UTC, josh146 commented
> All the other author bios including links to personal websites have them in plain text, so maybe it can't be done as is now?

Ah, this might be a bug in our bio setup. Feel free to just use plain text for now, I will investigate and attempt to fix this. But this shouldn't block this demo :)

2022-11-09 23:28 UTC, CatalinaAlbornoz submitted a review, later dismissed
Very interesting demo Simon! 

I suggested a few changes but they should be easy to commit.

2022-11-09 23:28 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_barren_gadgets.py
> +qubit individually, while the perturbations couple target with auxiliary qubits.
```suggestion
qubit individually, while the perturbations couple the target with the auxiliary qubits.
```

2022-11-09 23:28 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_barren_gadgets.py
> +and using that for training instead. That is what we will do in the following
```suggestion
and using that for training instead. That is what we will do in the rest
```

2022-11-09 23:28 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_barren_gadgets.py
> +# First, a few imports. Pennylane and numpy of course, and additionally a few
```suggestion
# First, a few imports. PennyLane and NumPy of course, and additionally a few
```

2022-11-09 23:28 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_barren_gadgets.py
> +# For those who want to check the inner workings,
```suggestion
# For those who want to check its inner workings,
```

2022-11-09 23:28 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_barren_gadgets.py
> +# you can find the code here (
```suggestion
# you can find the code here (
```

2022-11-09 23:28 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_barren_gadgets.py
> +# ).
```suggestion
# :download:`barren_gadgets.py <../demonstrations/barren_gadgets/barren_gadgets.py>`
# ).
```

2022-11-09 23:28 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_barren_gadgets.py
> +# Indeed, there are :math:`(X_4X_5, X_5X_6, X_6X_7, X_7X_4)` and
```suggestion
# Indeed, they are :math:`(X_4X_5, X_5X_6, X_6X_7, X_7X_4)` and
```

2022-11-09 23:28 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_barren_gadgets.py
> +# That is we choose a circuit ansatz with randomly initialized weights,
```suggestion
# That is, we choose a circuit ansatz with randomly initialized weights,
```

2022-11-14 16:37 UTC, KetpuntoG commented on demonstrations/tutorial_barren_gadgets.py
> +# ``build_ansatz`` (for the details:
Hey @josh146 , If we click in the link we get this xml file

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>GK9B1D0DDGCGDV5Y</RequestId><HostId>eMLLUZDSVw1cXaAUfnwGAwwFMsNNre/X1yHKPZDeK3z2RIgTLCpxnQdh/8/ivsLDp2uOzxQMTXg=</HostId></Error>

```

Maybe it won't work in the current deployment but it will once merged?

2022-11-14 19:25 UTC, josh146 commented on demonstrations/tutorial_barren_gadgets.py
> +# ``build_ansatz`` (for the details:
I just tried to fix this!

2022-11-15 11:48 UTC, SimonCichy commented on demonstrations/tutorial_barren_gadgets.py
> +the minimum. That is a problem because increasing the resolution on a quantum
Sorry for this abuse of language, I would have to check the proper definitions of resolution, accuracy and precision. I mean that to obtain a good expectation value of a quantity one has to perform many measurements to overcome the randomness of the shot noise

2022-11-15 11:52 UTC, SimonCichy commented on demonstrations/tutorial_barren_gadgets.py
> +the minimum. That is a problem because increasing the resolution on a quantum
Ok, the use of the word resolution was clearly wrong (that is fixed by the hardware, so does not enter in the consideration here). According to this visualization, I mean increase the precision (in the assumption that it is already accurate)
![image](https://user-images.githubusercontent.com/70891818/201912717-cb6afc3c-a48b-404c-8320-ca0c2fec7eb2.png)

2022-11-15 12:00 UTC, SimonCichy commented
> Very interesting demo Simon!
> 
> I suggested a few changes but they should be easy to commit.

Thank you a lot! Thanks for the detailed review, and sorry for all the typos that slipped through my fingers. About your comments, I had accepted the easy suggested changes, and will go in the following days over those that need a bit of thinking ;)

2022-11-15 12:22 UTC, SimonCichy commented on demonstrations/tutorial_barren_gadgets.py
> +#    Simon is a graduate in quantum engineering from ETH Zürich. He is interested in quantum machine learning and near-term quantum algorithms in general. More on his personal website https://simonci
Well, that depends a bit on how long this this process still takes. I have finished all the requirements for the master, but still waiting for the paperwork to be done. And I will start a PhD, but same there, it is not yet formally the case. I will change it to graduate student and update it later if the PR is still open by then

2022-11-15 12:31 UTC, SimonCichy commented on demonstrations/tutorial_barren_gadgets.py
> +measurements would render the algorithm impractical.
```suggestion
the minimum. That is a problem because increasing the precision on a quantum 
computer comes at the cost of more measurements.
Shot noise adds some randomness in the computed expectation value
and the smaller the difference to observe, the more measurements
are needed. An exponential number of 
measurements would render the algorithm impractical.

```

2022-11-15 12:34 UTC, SimonCichy commented on demonstrations/tutorial_barren_gadgets.py
> +computer comes at the cost of more measurements, and an exponential number of
```suggestion
computer comes at the cost of more measurements.
Shot noise adds some randomness in the computed expectation value
and the smaller the difference to observe, the more measurements
are needed. An exponential number of 
measurements would render the algorithm impractical.
```

2022-11-15 12:37 UTC, SimonCichy commented on demonstrations/tutorial_barren_gadgets.py
> +measurements would render the algorithm impractical.
```suggestion
the minimum. That is a problem because increasing the precision on a quantum 
computer comes at the cost of more measurements.
Shot noise adds some randomness in the computed expectation value
and the smaller the difference to observe, the more measurements
are needed. An exponential number of 
measurements would render the algorithm impractical.

```

2022-11-15 16:26 UTC, josh146 commented
@KetpuntoG: it turns out the `:download:` issue is a bug, currently waiting here on a fix :)

2022-11-18 21:31 UTC, rashidnhm commented
Hi all, the download issue should now be resolved, if you are able to pull in the latest master to your branch, the download links to begin working.

2022-11-21 16:32 UTC, KetpuntoG commented
> Hi all, the download issue should now be resolved, if you are able to pull in the latest master to your branch, the download links to begin working.

Awesome! Thanks @rashidnhm @josh146 , now it is working for me 💪

2022-11-23 17:15 UTC, KetpuntoG commented
Hey @SimonCichy , did you make all the requested changes already? 
I just want to make sure before I give it another look :)

2022-11-23 18:32 UTC, SimonCichy commented
> Hey @SimonCichy , did you make all the requested changes already? I just want to make sure before I give it another look :)

@KetpuntoG I believe I did! I have accepted most of the proposed changes, suggested improvements in some places and there is one where I discuss my choice of formulation. I am not aware of any that is pending of me right now

2022-12-06 18:57 UTC, isaacdevlugt requested changes
Some grammar comments, but will approve once addressed!

2022-12-06 18:57 UTC, isaacdevlugt commented on demonstrations/tutorial_barren_gadgets.py
> +Thinking about VQE applications, let us consider cost functions that are
```suggestion
Thinking about Variational Quantum Eigensolver (VQE) applications, let us consider cost functions that are 

```

2022-12-06 18:57 UTC, isaacdevlugt commented on demonstrations/tutorial_barren_gadgets.py
> +to minimize.
```suggestion
whose expectation value we need to minimize.  

```

2022-12-06 18:57 UTC, isaacdevlugt commented on demonstrations/tutorial_barren_gadgets.py
> +measurements would render the algorithm impractical.
```suggestion
the minimum. That is a problem because increasing the resolution of the cost function requires more measurements from the quantum device, and an exponential number of 
measurements would render the algorithm impractical.

```

2022-12-06 18:57 UTC, isaacdevlugt commented on demonstrations/tutorial_barren_gadgets.py
> +and using that for training instead. That is what we will do in the rest
```suggestion
and use that for training instead. That is what we will do in the rest

```

2022-12-06 18:57 UTC, isaacdevlugt commented on demonstrations/tutorial_barren_gadgets.py
> +# First, a few imports. PennyLane and NumPy of course, and additionally a few
```suggestion
# First, a few imports. PennyLane and NumPy of course, and a few

```

2022-12-06 18:57 UTC, isaacdevlugt commented on demonstrations/tutorial_barren_gadgets.py
> +# ).
```suggestion
# you can find the code here:
# :download:`barren_gadgets.py </demonstrations/barren_gadgets/barren_gadgets.py>`.

```

2022-12-06 18:57 UTC, isaacdevlugt commented on demonstrations/tutorial_barren_gadgets.py
> +# The functions ``get_parameter_shape``, ``generate_random_gate_sequence`` and
```suggestion
# The functions ``get_parameter_shape``, ``generate_random_gate_sequence``, and

```

2022-12-06 18:57 UTC, isaacdevlugt commented on demonstrations/tutorial_barren_gadgets.py
> +# Now, let's take the example given above
```suggestion
# Now, let's take the example given above:

```

2022-12-06 18:57 UTC, isaacdevlugt commented on demonstrations/tutorial_barren_gadgets.py
> +# class
```suggestion
# class.

```

2022-12-06 18:57 UTC, isaacdevlugt commented on demonstrations/tutorial_barren_gadgets.py
> +# We indeed have a Hamiltonian composed of two terms, with the expected Pauli
```suggestion
# We indeed have a Hamiltonian composed of two terms with the expected Pauli

```

2022-12-06 18:57 UTC, isaacdevlugt commented on demonstrations/tutorial_barren_gadgets.py
> +# Classical simulation of qubit systems is expensive, so we will simplify further
```suggestion
# Classical simulations of qubit systems are expensive, so we will simplify further

```

2022-12-06 18:57 UTC, isaacdevlugt commented on demonstrations/tutorial_barren_gadgets.py
> +# So, let us construct the two Hamiltonians of interest
```suggestion
# So, let us construct the two Hamiltonians of interest.

```

2022-12-06 18:57 UTC, isaacdevlugt commented on demonstrations/tutorial_barren_gadgets.py
> +# the training cost function, the optimizer with its step size, the number of
```suggestion
# the cost function, the optimizer with its step size, the number of

```

2022-12-06 18:57 UTC, isaacdevlugt commented on demonstrations/tutorial_barren_gadgets.py
> +# optimization steps and the device to run the circuit on.
```suggestion
# optimization steps, and the device to run the circuit on.

```

2022-12-06 18:57 UTC, isaacdevlugt commented on demonstrations/tutorial_barren_gadgets.py
> +# As ansatz, we will use a variation of the
```suggestion
# For an ansatz, we will use a variation of the

```

2022-12-06 18:57 UTC, isaacdevlugt commented on demonstrations/tutorial_barren_gadgets.py
> +# Now we build the circuit for our actual experiment
```suggestion
# Now we build the circuit for our actual experiment.

```

2022-12-06 18:57 UTC, isaacdevlugt commented on demonstrations/tutorial_barren_gadgets.py
> +# That's the one the gradient descent will try to minimize.
Not needed IMO 

```suggestion
```

2022-12-06 18:57 UTC, isaacdevlugt commented on demonstrations/tutorial_barren_gadgets.py
> +# will not be used in the optimization.
```suggestion
# For the training, we use the gadget Hamiltonian. To ensure
# that our gadget optimization is proceeding as intended, 
# we also define another cost function based on the target Hamiltonian.
# We will evaluate its value at each iteration for monitoring purposes, but it
# will not be used in the optimization.

```

2022-12-06 18:57 UTC, isaacdevlugt commented on demonstrations/tutorial_barren_gadgets.py
> +# Since our example of target Hamiltonian is a single Pauli string, we know
```suggestion
# Since our example target Hamiltonian is a single Pauli string, we know

```

2022-12-06 18:57 UTC, isaacdevlugt commented on demonstrations/tutorial_barren_gadgets.py
> +# It is a very simple example but we see that the training of our circuit using
```suggestion
# It is a very simple example, but we see that the training of our circuit using

```

2022-12-06 18:57 UTC, isaacdevlugt commented on demonstrations/tutorial_barren_gadgets.py
> +# quickly becomes a lot.
```suggestion
# problems! However, be aware of the exponential scaling of classical 
# simulations of quantum systems; adding linearly many auxiliary qubits
# quickly becomes hard to simulate.

```

2022-12-08 14:24 UTC, KetpuntoG commented
Hey @SimonCichy , we plan to publish the demo next Tuesday 
Once you correct the last changes, it will be ready 😄
You could also share me your Twitter username for the publication

2022-12-08 16:29 UTC, KetpuntoG commented
> Hey @SimonCichy , we plan to publish the demo next Tuesday
> Once you correct the last changes, it will be ready 😄
> You could also share me your Twitter username for the publication

Also, if you could add a hook to your first paragraph (the two lines you have) that would be amazing. Something that would make the user want to read the whole demo 💪

2022-12-09 11:33 UTC, SimonCichy commented on demonstrations/tutorial_barren_gadgets.py
> +In some cases, it is easy to find a local cost function which can substitute a global one with the same ground state.
@isaacdevlugt sorry, but this rephrasing sounds weird to me. If you don't like the "which",  I understand using "that" instead but the "for" does not feel right to me there. Or alternatively using "that can act as a substitute for"

2022-12-09 11:36 UTC, SimonCichy commented on demonstrations/tutorial_barren_gadgets.py
> +measurements would render the algorithm impractical.
@CatalinaAlbornoz what do you think? Since these suggestions also relate to your doubt about the use of the word "resolution"
> What do you mean by resolution here? Do you mean accuracy? Or precision? Or something else? It may be worth describing what this means in this context.

2022-12-09 12:21 UTC, SimonCichy commented
Hey @KetpuntoG! Sure, I'll get to it, and it seems that the changes requested by @isaacdevlugt are quick to go through. There are a few from @CatalinaAlbornoz however about which I was not sure, and left some comments. Those are not settled yet.

2022-12-09 12:22 UTC, SimonCichy commented
> You could also share me your Twitter username for the publication
@sdcichy

2022-12-09 15:21 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_barren_gadgets.py
> +#    Simon is a graduate in quantum engineering from ETH Zürich. He is interested in quantum machine learning and near-term quantum algorithms in general. More on his personal website https://simonci
Sounds good!

2022-12-09 15:31 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_barren_gadgets.py
> +the minimum. That is a problem because increasing the resolution on a quantum
Awesome! Yes, precision seems like the right word to use!

2022-12-09 17:27 UTC, SimonCichy commented
> Don't forget to add a hook in the first two lines you've written. Apart from summarizing what they are going to see, we are trying to make the user curious about the demo

I added a few sentences, but I am happy to hear suggestions if you have better ones! It is oversimplifying things and I don't know how much hype it builds, but I don't want to sell what we did for more than it is

2022-12-09 19:30 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_barren_gadgets.py
> +measurements would render the algorithm impractical.
Hi @SimonCichy, I believe that Isaac didn't see your suggestion because you hadn't committed it. 

Maybe a combination of the 2 is better. Something like:

That is a problem because increasing the precision while using a quantum 
computer requires more measurements from the quantum device.
Shot noise adds some randomness in the computed expectation value
and the smaller the difference to observe, the more measurements
are needed. An exponential number of 
measurements would render the algorithm impractical.

2022-12-09 19:40 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_barren_gadgets.py
> +Since it is a local cost function, it is better behaved with respect to
My comment was more about the "it is better behaved" statement. It is unclear what it is. Maybe something like the following is best. What do you think?

Since it is a local cost function, it will not exhibit barren plateaus, making it more trainable than the global cost function.

2022-12-09 19:46 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_barren_gadgets.py
> +cost functions compared to local ones.
There are some weird spaces like this one appearing in several places. This requires a good review to make sure we catch them all.

2022-12-09 19:47 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_barren_gadgets.py
> +of this tutorial.
```suggestion
and using that for training instead. That is what we will do in the rest of this tutorial.
```

2022-12-09 21:19 UTC, josh146 commented on demonstrations/tutorial_barren_gadgets.py
> +# References
```suggestion
# `this repository <https://github.com/SimonCichy/barren-gadgets>`_.
#
# References
```

2022-12-09 21:53 UTC, KetpuntoG approved these changes
Awesome demo! Thank you very much @SimonCichy 🚀

2022-12-09 21:55 UTC, merged

2022-12-12 12:54 UTC, SimonCichy commented
Thank you guys a lot!! And sorry I could not be more responsive on the last part... But really happy this is out now 😃