Add Page for Data Module
PennyLaneAI/qml pull request #613
Opened 2022-10-25 00:29 UTC by obliviateandsurrender

**Title:** Add page for Data Module

**Summary:** This would make documentation related to the data module independent of the PL release cycle and make it more accessible.

**Relevant references:** 

**Possible Drawbacks:**

**Related GitHub Issues:**

2022-10-27 15:00 UTC, timmysilv reviewed
looks good! I haven't reviewed the module page because I expect quite a few changes there. My comments are mostly just grammatical changes - will let Josh/product folks talk about the content more, but I dig it

2022-10-30 20:36 UTC, josh146 requested changes
Really nice work @obliviateandsurrender, especially the structure! My comments below are more related to the content/copy.

2022-10-30 20:36 UTC, josh146 commented on datasets_intro.rst
> +~~~~~~~~~~~~~~
```suggestion
Examples of quantum data
~~~~~~~~~~~~~~~~~~~~~~~~
```

Just trying to make this clearer; when I first read this section, I thought it was describing _categories_ of quantum data, but on-rereading it is more _examples_ of quantum date.

2022-10-30 20:36 UTC, josh146 commented on datasets_intro.rst
> +In a more general sense, we consider the quantum data to encompass the following things:
```suggestion
Examples of quantum data include the following:
```

2022-10-30 20:36 UTC, josh146 commented on datasets_intro.rst
> +#. Any useful **unitary transformations** of the system such as the Clifford operator required for tapering.
```suggestion
#. Any useful **unitary transformations** of the system such as the Clifford operator required for qubit tapering.
```

A good opportunity to link to the qubit tapering demo (using `:doc:`)

2022-10-30 20:36 UTC, josh146 commented on datasets_intro.rst
> +#. **Never-ending quest for useful research:** Readily available data reduces the work required for cross-collaboration among different disciplines, ultimately fostering better advancements in curren
Nice!

2022-10-30 20:36 UTC, josh146 commented on datasets_intro.rst
> +PennyLane is an **open-source software framework built around the concept of quantum differentiable programming**. It seamlessly integrates quantum simulators and hardware with machine-learning libra
```suggestion
PennyLane is an **open-source software framework built around the concept of quantum differentiable programming**, seamlessly integrating quantum simulators and hardware with machine-learning libraries.

PennyLane datasets give you the power to use the provided datasets to develop novel algorithms, and benchmark them against problems in applied quantum computation, such as the simulation of physical systems.

For more information on accessing hosted data from PennyLane, please see the :doc:`datasets <introduction/quantum_datasets>` documentation.
```

2022-10-30 20:36 UTC, josh146 commented on datasets_intro.rst
> +To find out more, visit the `PennyLane Documentation <https://pennylane.readthedocs.io>`_, or check out the `Accessing Datasets` section of :doc:`quantum datasets <datasets>`.
```suggestion
```

2022-10-30 20:36 UTC, josh146 commented on datasets_qchem.rst
> +===========================
```suggestion
Quantum Chemistry Datasets
==========================
```

2022-10-30 20:36 UTC, josh146 commented on datasets_qchem.rst
> +One of the most promising directions for current research in quantum algorithms is quantum chemistry, a field of critical importance, as it allows one to inquire about the quantum properties of matte
```suggestion
One of the most promising directions for current research in quantum algorithms is quantum chemistry, a field of critical importance, as it allows one to inquire about the quantum properties of matter.

Explore our available quantum chemistry datasets below, providing data related to some popularly examined molecular systems.
```

2022-10-30 20:36 UTC, josh146 commented on datasets_qchem.rst
> +For the smaller molecules such as H\ :sub:`2`, HeH\ :sup:`+`, and H\ :sub:`3`\ :sup:`+`, data has been obtained for both minimal basis-set `STO-3G` and the split-valence double-zeta basis set `6-31G`
@obliviateandsurrender this is great, but it is hard to determine from these paragraphs:

- the strings you would pass in as a user to load each dataset
- an overview of the properties of each molecule.

2022-10-30 20:36 UTC, josh146 commented on datasets_qchem.rst
> +For the smaller molecules such as H\ :sub:`2`, HeH\ :sup:`+`, and H\ :sub:`3`\ :sup:`+`, data has been obtained for both minimal basis-set `STO-3G` and the split-valence double-zeta basis set `6-31G`
I see two options:

- provide a code block underneath this paragraph showing how to programmatically display this in your terminal/notebook, or

- provide a table underneath this paragraph listing the name and properties for each molecule.

I think I prefer the second option (a table).

2022-10-30 20:36 UTC, josh146 commented on datasets_qchem.rst
> +For each of the molecules mentioned above, users will be able to extract the following characteristics for a geometry:
```suggestion
For each of the molecules mentioned above, the following geometry characteristics can be extracted:
```

Here, just rewording this into the passive voice (to remove 'user').

2022-10-30 20:36 UTC, josh146 commented on datasets_qchem.rst
> +        | `molecule`                 | PennyLane Molecule object                                                         |
all of these should have double backticks.

2022-10-30 20:36 UTC, josh146 commented on datasets_qchem.rst
> +        :widths: auto
You can replace this with 

```rest
.. rst-class:: docstable
```

for a PL-themed table :)

2022-10-30 20:36 UTC, josh146 commented on datasets_qchem.rst
> +#. **Molecular Data**
I find it odd that these are numbered. Perhaps these should be subsubsection headings?

Or even subsection headings to appear in the TOC?

I also suggest having 1-2 sentence beneath each to describe what they mean.

2022-10-30 20:36 UTC, josh146 commented on datasets_qchem.rst
> +        | `molecule`                 | PennyLane Molecule object                                                         |
I strongly suggest having `type` information here if possible

2022-10-30 20:36 UTC, josh146 commented on datasets_qchem.rst
> +        | `hamiltonian`              | PennyLane Hamiltonian in string format                                            |
What does string format mean here?

2022-10-30 20:36 UTC, josh146 commented on datasets_qchem.rst
> +        | `fci_spectrum`             | First few eigenvalues obtained from exact diagonalization.                        |
How many?

2022-10-30 20:36 UTC, josh146 commented on datasets_qchem.rst
> +        | `meas_groupings`           | Measurement groupings for the Hamiltonian                                         |
What grouping method was used?

2022-10-30 20:36 UTC, josh146 commented on datasets_qchem.rst
> +        | `wire_map`                 | Wire map for the Hamiltonian                                                      |
What does this mean?

2022-10-30 20:36 UTC, josh146 commented on datasets_qchem.rst
> +#. **Tapering Data**
If these correspond to specific PL functions/workflows, I would include them here in the 1-2 sentence introductions (or even a 1-2 line code example if it makes sense?)

2022-10-30 20:36 UTC, josh146 commented on datasets_qspin.rst
> +Quantum many-body Physics Datasets
Yep, we tend to use sentence case for titles. I think? best to have a look at other pages :)

2022-10-30 20:36 UTC, josh146 commented on datasets_qspin.rst
> +Another area for exploring practical quantum advantage is quantum many-body physics, which involves exploring quantum spin models that foster similar quantum-correlations-enabled phenomena than molec
```suggestion
Simulating quantum many-body physics with quantum computation is an important area of research with potential for practical quantum advantage. It involves exploring quantum spin models that --- while more straightforward than simulating molecular Hamiltonian --- foster similar quantum-correlations-enabled phenomena.

Here, we provide quantum many-body physics datasets of popularly studied spin systems.
```

2022-10-30 20:36 UTC, josh146 commented on datasets_qspin.rst
> +We vary a tunable parameter in their Hamiltonian for each spin system to obtain 100 different configurations. For each such configuration, data is being made available for 1-D lattices (linear chain)
@obliviateandsurrender my comments from the QChem page also apply to this page, including:

- displaying the spin system properties in this section.
- Providing more details about the data features below

2022-10-30 20:36 UTC, josh146 commented on datasets_qspin.rst
> +For each spin system, we obtain the following data for `100` different `parameters`.
I'm not sure what this sentence means 🤔

2022-10-30 20:36 UTC, josh146 commented on index.rst
> +        <div class="col">
@obliviateandsurrender I suggest removing the changes in this file for now - after this PR is merged, we can determine how to best link to the new datasets section :)

2022-10-31 17:09 UTC, obliviateandsurrender commented on datasets_qchem.rst
> +        | `meas_groupings`           | Measurement groupings for the Hamiltonian                                         |
It was `qwc`, I will add that in the updated table docs.

2022-10-31 17:13 UTC, obliviateandsurrender commented on datasets_qchem.rst
> +        | `hamiltonian`              | PennyLane Hamiltonian in string format                                            |
It's actually in a dictionary format with Pauli words as `keys` and their coefficients as `values`. This is done to compress them. We will change them to PennyLane Hamiltonian on load internally.

2022-10-31 17:17 UTC, obliviateandsurrender commented on datasets_qspin.rst
> +For each spin system, we obtain the following data for `100` different `parameters`.
This means that we are varying one particular term in the system's Hamiltonian to obtain 100 different configurations. For example, in the case of the Transverse-field Ising model, it is the external field.

2022-11-08 21:28 UTC, timmysilv commented on index.rst
> +    datasets
is this reflected somehow? I would expect it to appear as a 5th box on the front site (do we want that?). I've been going into the glossary to navigate to the datasets sub-page personally

2022-11-09 14:25 UTC, timmysilv commented on datasets_intro.rst
> +For more information on accessing hosted data from PennyLane, please see the :doc:`datasets <introduction/quantum_datasets>` documentation.
is this supposed to be linking to the [PennyLane doc](https://docs.pennylane.ai/en/latest/introduction/data.html)?

2022-11-09 14:27 UTC, timmysilv commented on datasets.rst
> +                    <a href="https://docs.pennylane.ai/en/stable/introduction/quantum_datasets.html">
```suggestion
                    <a href="https://docs.pennylane.ai/en/stable/introduction/data.html">
```
Not sure how this is generated, but that doc is just called [data](https://docs.pennylane.ai/en/latest/introduction/data.html) in PennyLane (already exists on the `latest` version of the site!)

2022-11-09 14:33 UTC, timmysilv commented on datasets_qspin.rst
> +For each spin system, we can obtain the following characteristics for each of the `100` different system configurations:
still not sure why "100" is italicized

2022-11-09 14:39 UTC, timmysilv commented on datasets.rst
> +    datasets_module
```suggestion
```
maybe this non-existent file broke the back arrow?

2022-11-10 15:01 UTC, soranjh commented on datasets_qchem.rst
> +
These table need headers. Something like:

Name  |  Type

2022-11-10 15:03 UTC, soranjh commented on datasets_qchem.rst
> +    | ``fci_energy``             | ``float``                                                                          | Classical energy of the molecule obtained from exact diagonalization.
Ground state energy (Classical could be confusing).

2022-11-10 15:05 UTC, soranjh commented on datasets_qchem.rst
> +Variational data obtained by using the :class:`~.pennylane.AdaptiveOptimizer` to minimize ground state energy.
```suggestion
Variational data obtained by using :class:`~.pennylane.AdaptiveOptimizer` to minimize ground state energy.
```

2022-11-10 15:10 UTC, soranjh commented on datasets_qspin.rst
> +    +----------------------------+--------------------------------+-----------------------------------------------------------------------------------+
The tables need header.

2022-11-10 15:11 UTC, soranjh commented on datasets_qspin.rst
> +    | ``order_parameters``       | ``numpy.array`` | Value of order paramteres for identifying phases                  |
```suggestion
    | ``order_parameters``       | ``numpy.array`` | Value of order parameters for identifying phases                  |
```

2022-11-10 15:54 UTC, obliviateandsurrender commented on datasets_intro.rst
> +#. Control parameters for **system evolution** and data related to **noise descriptions** such as the Kraus operators for channels.
No, but we could have them in the future with some noisy experiments (either on a simulator or hardware).

2022-11-10 16:11 UTC, obliviateandsurrender commented on datasets_qchem.rst
> +    | **Molecule**                 | **Basis set(s)**                    | **#Qubits**  | **Bond length (Å), Bond angle (°)**                                       | **Optimal geometry (Å, °)**
It looks very weird, would prefer to keep it this way.

2022-11-10 18:24 UTC, soranjh commented on datasets_qchem.rst
> +    | H\ :math:`_2`                | | STO\ :math:`-`\3G /               | 4 / 8        | H\ :math:`_A-`\ H\ :math:`_B` :math:`\in\ [0.5, 2.1]`                     | H\ :math:`_A-`\ H\ :math:`_B = 0.
I meant for the basis sets, just the normal hyphen is fine: STO-3G. The current symbol (looks like a dash symbol) is too long and looks like a bond length.

2022-11-10 18:24 UTC, soranjh approved these changes

2022-11-10 19:01 UTC, obliviateandsurrender commented on datasets_qchem.rst
> +    | H\ :math:`_2`                | | STO\ :math:`-`\3G /               | 4 / 8        | H\ :math:`_A-`\ H\ :math:`_B` :math:`\in\ [0.5, 2.1]`                     | H\ :math:`_A-`\ H\ :math:`_B = 0.
Yeah, I have updated it now. The sad emoji was for updating the column length across the table. 😆

2022-11-10 20:29 UTC, DSGuala approved these changes

2022-11-10 20:29 UTC, DSGuala commented on datasets_intro.rst
> +In the context of quantum programming, this can be realized as the input and output of a quantum function that describes a quantum system.
I feel like the definition of "quantum data" is not direct enough here. If quantum data is information that describes quantum systems and their evolution, I would like that to be said explicitly. But I haven't been able to think of a way to make this flow nicely and keep the the statement that "a quantum dataset is a collection of quantum data"

2022-11-10 20:29 UTC, DSGuala commented on datasets_qspin.rst
> ++--------------------------------+---------------+------------------+------------------------------+---------------------------------+
These tables are really nice :100:

2022-11-11 22:26 UTC, josh146 commented on datasets_intro.rst
> +In the context of quantum programming, this can be realized as the input and output of a quantum function that describes a quantum system.
I have to admit I keep reading the line "a quantum dataset is a collection of quantum data" now, and I'm not sure it means anything haha. It sounds tautological.

2022-11-11 22:27 UTC, josh146 commented on datasets_qspin.rst
> ++--------------------------------+---------------+------------------+------------------------------+---------------------------------+
They look so good 😍

2022-11-14 15:02 UTC, timmysilv approved these changes
maybe a nit, but `numpy.array` is a function, `numpy.ndarray` is a type. Otherwise 🚢 🚢

2022-11-14 15:02 UTC, timmysilv commented on datasets_qchem.rst
> +    | ``hf_state``               |  ``numpy.array``               | Hartree-Fock state of the chemical system represented by a binary vector          |
```suggestion
    | ``hf_state``               |  ``numpy.ndarray``               | Hartree-Fock state of the chemical system represented by a binary vector          |
```

2022-11-14 15:02 UTC, timmysilv commented on datasets_qchem.rst
> +    | ``fci_spectrum``           | ``numpy.array``                                                                    | First :math:`2\times`\ #qubits eigenvalues obtained from exact diagonalization
```suggestion
    | ``fci_spectrum``           | ``numpy.ndarray``                                                                    | First :math:`2\times`\ #qubits eigenvalues obtained from exact diagonalization    |
```

2022-11-14 15:02 UTC, timmysilv commented on datasets_qchem.rst
> +    | ``tapered_hf_state``       | ``numpy.array``                  | Tapered Hartree-Fock state of the molecule                                        |
```suggestion
    | ``tapered_hf_state``       | ``numpy.ndarray``                  | Tapered Hartree-Fock state of the molecule                                        |
```

2022-11-14 15:02 UTC, timmysilv commented on datasets_qchem.rst
> +    | ``vqe_params``             | ``numpy.array``                                  | Optimal parameters for the gates that prepares ground state
```suggestion
    | ``vqe_params``             | ``numpy.ndarray``                                  | Optimal parameters for the gates that prepares ground state                                                             |
```

2022-11-15 01:47 UTC, josh146 approved these changes

2022-11-15 01:47 UTC, josh146 commented on datasets.rst
> +                    <a href="https://docs.pennylane.ai/en/stable/introduction/data.html" target="_blank">
```suggestion
                    <a href="https://docs.pennylane.ai/en/stable/introduction/data.html">
```

Minor, but since the domain and navbar remain, I don't think this needs to open up in a new tab -- a reader will continue to feel like they are on the same website

2022-11-15 01:47 UTC, josh146 commented on index.rst
> +                    <span style="color:red">NEW! </span><a href="datasets.html">Checkout our latest offerings of Quantum Datasets</a>
```suggestion
                    Explore our new <a href="datasets.html">quantum datasets</a>
```

2022-11-15 03:12 UTC, merged