[WIP] 'What is quantum computing?' webpage
PennyLaneAI/qml pull request #614
Opened 2022-10-25 22:00 UTC by ikurecic

First draft, not to be merged; here for reviews.
Images are placeholders — to be adjusted later.

### Checklist

- [ ] Images in relevant places

- [ ] All metadata is properly populated

- [ ] Renders properly

2022-10-25 22:01 UTC, ikurecic commented
Tagging @branedrane so you're in the loop.

2022-10-26 01:30 UTC, isaacdevlugt commented on whatisqc.rst
> +Quantum computing is a research area that explores **what quantum computers can do and how to make them do it**. It is a highly interdisciplinary field of quantum science and technology, sitting at t
```suggestion
Quantum computing is a research area that explores **what quantum computers can do and how to make them do it**. It is a highly interdisciplinary field of quantum science and technology, sitting at the meeting point of algorithm design, complexity theory, system architecture, and hardware development.
```

2022-10-26 02:02 UTC, isaacdevlugt reviewed
Really well-written and thoughtful! I have no problem with the content, just some grammar suggestions. Even then, I think some of the em-dash/semicolon/comma conventions that are used here versus what I suggested might be subjective to the eye of the beholder.

2022-10-26 02:02 UTC, isaacdevlugt commented on whatisqc.rst
> +PennyLane is an **open-source cross-platform Python library** that supports a wide array of tasks in quantum computing, quantum machine learning, and quantum chemistry. Its capabilities for the diffe
```suggestion
PennyLane is an **open-source cross-platform Python library** that supports a wide array of tasks in quantum computing, quantum machine learning, and quantum chemistry. Its capabilities for the differentiable programming of quantum computers have been designed to seamlessly integrate with classical machine learning libraries, quantum simulators, and hardware, giving users the power to train quantum circuits.
```

2022-10-26 02:02 UTC, isaacdevlugt commented on whatisqc.rst
> +To find out more, visit the [PennyLane Documentation](https://pennylane.readthedocs.io/) or check out the gallery of hands-on :doc:`quantum machine learning demonstrations <demonstrations>`.
```suggestion
To find out more, visit the [PennyLane Documentation](https://pennylane.readthedocs.io/) or check out the gallery of hands-on :doc:`demonstrations <demonstrations>`.
```

2022-10-27 09:58 UTC, ikurecic commented on whatisqc.rst
> +Whether practical algorithmic speedups are possible in the NISQ regime remains an open problem, but some instances of quantum devices solving computational problems that would take classical computer
Absolutely no clue. 😂 Jet-lag + copy-pasting down the highway in the wrong direction. Will fix.

2022-10-27 10:11 UTC, ikurecic commented on whatisqc.rst
> +PennyLane is an **open-source cross-platform Python library** that supports a wide array of tasks in quantum computing, quantum machine learning, and quantum chemistry. Its capabilities for the diffe
Deciding against Oxford comma here because simulators and hardware are in the same category of things.

2022-10-27 10:12 UTC, ikurecic commented on whatisqc.rst
> +To find out more, visit the [PennyLane Documentation](https://pennylane.readthedocs.io/) or check out the gallery of hands-on :doc:`quantum machine learning demonstrations <demonstrations>`.
Duh, thanks. I thought I changed it. Need to start drinking coffee.

2022-10-27 11:06 UTC, ikurecic reviewed
Thanks a lot for the suggestions, @isaacdevlugt !
An okay starting point, hopefully. :)

2022-10-27 11:06 UTC, ikurecic commented on whatisqc.rst
> +Examples span the gamut from low-level hardware problems that engage a variety of phenomena in quantum mechanics, such as the implementation of physical schemes to control and stabilize quantum units
Split into two sentences instead.

2022-10-27 11:06 UTC, ikurecic commented on whatisqc.rst
> +The art and science of quantum computing lies in designing algorithms that can encode useful information into a computational model, modify it in specific ways and read out the result. But this is fa
Met you half-way, great change.

2022-10-27 11:06 UTC, ikurecic commented on whatisqc.rst
> +Perhaps the primary ambition of the field of quantum computing nowadays is to **develop a scalable, fault-tolerant device on which any and all quantum algorithms can be implemented**. Research in spe
Yeah, why not. Added a connector.

2022-10-27 11:06 UTC, ikurecic commented on whatisqc.rst
> +Whether practical algorithmic speedups are possible in the NISQ regime remains an open problem, but some instances of quantum devices solving computational problems that would take classical computer
Fair play. :)

2022-10-27 11:06 UTC, ikurecic commented on whatisqc.rst
> +Quantum advantage is not necessarily demonstrated on problems that are thought of as useful or practical, but it shows a clear sign toward the bright future of quantum computing. **Scalable, error-re
Deciding to go in the 'uncountable noun' direction because it fits existing mats, let's change it to 'a' if it's wrong.

2022-10-27 11:06 UTC, ikurecic commented on whatisqc.rst
> +Few technological advances hold a real potential to let us speed through entire stages of scientific development, but quantum computers are likely to be the cornerstone *general-purpose technology* o
It should be "widely used" or "used widely" or "a widely-used [noun]," sometimes. So I'll leave it for now (but change 'become' to 'be'.
Mdashes flow better for me, given the existing Xanadu web copy.

2022-11-07 16:14 UTC, ikurecic commented
Uploading a couple of image concepts to have for the implementation. Currently used images in the draft are placeholders.
The SVG files are in the drive.
![drawing_2](https://user-images.githubusercontent.com/4939555/200359341-8ff32360-397c-4297-a001-266adc236bf2.png)
![drawing_1](https://user-images.githubusercontent.com/4939555/200359342-dde0ce57-ebbe-4a0e-9fb2-12209cd7f827.png)

2022-11-07 19:33 UTC, isaacdevlugt commented
> Uploading a couple of image concepts to have for the implementation. Currently used images in the draft are placeholders. The SVG files are in the drive. ![drawing_2](https://user-images.githubusercontent.com/4939555/200359341-8ff32360-397c-4297-a001-266adc236bf2.png) ![drawing_1](https://user-images.githubusercontent.com/4939555/200359342-dde0ce57-ebbe-4a0e-9fb2-12209cd7f827.png)

Can we just... keep these? These are gold

2022-12-16 18:17 UTC, co9olguy requested changes
Left a few smaller suggestions, but my main feedback is that this specific page is trying too hard to shoe-horn in Xanadu references, which is not something we actually need to be doing. PL brand is more focused around the wider quantum computing community

2022-12-16 18:17 UTC, co9olguy commented on whatisqc.rst
> +Examples span the gamut from low-level hardware problems that engage a variety of phenomena in quantum mechanics, such as the implementation of physical schemes to control and stabilize quantum units
btw if the files have line-length limits (say 80 chars), it makes it easier to provide review/suggestion on individual lines rather than all at once :nerd_face:

2022-12-16 18:17 UTC, co9olguy commented on whatisqc.rst
> +Quantum computers **extend the set of physical laws** classical computers operate on by accessing quantum aspects of the physical world and, as a result, gain new ways of processing information. For
this is a much better one-liner than the one used at the start of the first paragraph :100:. Would give a clearer answer if that's all you saw in search results

2022-12-16 18:17 UTC, co9olguy commented on whatisqc.rst
> +.. image:: /_static/whatisqc/quantum_computer.svg
I'd suggest we can leave in the magnifying glass as an easter egg nod to Xanadu's archticture, but remove the blatant logo in the data rack itself

2022-12-16 18:17 UTC, co9olguy commented on whatisqc.rst
> +.. image:: /_static/whatisqc/NISQ_computing.svg
Nice image, like the inclusion of the confetti. Easter egg X logo is subtle enough that it doesn't make it feel like advertising :+1:

2022-12-16 18:17 UTC, co9olguy commented on whatisqc.rst
> +.. image:: /_static/whatisqc/Borealis_quantum_advantage.svg
See below for more thoughts on this section, but I would remove "Borealis" and the X logo from this image were we to use it

2022-12-16 18:17 UTC, co9olguy commented on whatisqc.rst
> +.. figure:: /_static/whatisqc/QC_applications.svg
Neat!

2022-12-16 18:17 UTC, co9olguy commented on whatisqc.rst
> +The art and science of quantum computing lies in the design of algorithms that can encode useful information into a computational model, modify it in specific ways and read out the result. But this i
```suggestion
The art and science of quantum computing lies in the design of algorithms that can encode useful information into a computational model, modify it in specific ways, and read out the result. But this is far from trivial, as the branches of a quantum algorithm cannot be observed simultaneously—they are *collapsed* into a single number by the act of measuring.
```

2022-12-16 18:17 UTC, co9olguy commented on whatisqc.rst
> +Even though the original motivation for studying quantum computers was the efficient simulation of quantum systems, a sequence of breakthroughs in algorithm research in the ‘90s demonstrated that qua
```suggestion
The original motivation for studying quantum computers was the efficient simulation of quantum systems. But a sequence of breakthroughs in algorithm research in the ‘90s demonstrated that quantum computers could also **outperform their classical counterparts** at specific tasks like searching lists and factoring numbers. Subsequently, research in this field began in earnest.
```
this way makes it seem more "additive" in the list of things QCs can do

2022-12-16 18:17 UTC, co9olguy commented on whatisqc.rst
> +.. image:: /_static/whatisqc/NISQ_computing.svg
Would be good to modify image/text slightly so that this one single line isn't wrapping around
![image](https://user-images.githubusercontent.com/7213358/208161546-ae0b2c9c-c5d6-4e7c-9015-5f928aacf6e2.png)

2022-12-16 18:17 UTC, co9olguy commented on whatisqc.rst
> +On top of that, real devices that can carry out useful quantum algorithms consist of **many interacting components** and they must be able to correct errors that inevitably arise from **device–enviro
It's slightly more subtle than that. One could have a device with error correction, but since the error correction itself could be subject to errors, things could still fall apart overall. Fault tolerance refers to being below (above?) the threshold where you can correct errors faster than they occur.

2022-12-16 18:17 UTC, co9olguy commented on whatisqc.rst
> +Few technological advances hold a real potential to let us speed through entire stages of scientific development, but quantum computers are likely to be the cornerstone *general-purpose technology* o
I would steer away from declaring quantum computing as a general-purpose technology. A number of people would argue that we should not see QCs this way, since classical computers are already fairly strong at many things. (I've heard some argue convincingly that—asymptotic worst-case behaviours aside—there are few clear *practical* cases where a quantum computer obviously does better than our classical ones)

I wouldn't say we have to completely change this section (second paragraph is solid), but I would recommend refocusing the emphasis to be around the *variety* of different applications, rather than being about a *general-purpose* technology.

2022-12-16 18:17 UTC, co9olguy commented on whatisqc.rst
> +For example, quantum computers can be used to speedrun the development of new chemical compounds for medicine or agriculture, enable a perfectly secure exchange of private messages, optimize and enha
nice sneaking in speedrun lol

2022-12-16 18:17 UTC, co9olguy commented on whatisqc.rst
> +For example, quantum computers can be used to speedrun the development of new chemical compounds for medicine or agriculture, enable a perfectly secure exchange of private messages, optimize and enha
```suggestion
For example, quantum computers could eventually be used to speedrun the development of new chemical compounds for medicine or agriculture, enable a perfectly secure exchange of private messages, optimize and enhance existing computational algorithms for image classification, traffic management, or product design, and for **thousands of other uses we haven’t thought of yet**.
```

2022-12-16 18:17 UTC, co9olguy commented on whatisqc.rst
> +For example, quantum computers can be used to speedrun the development of new chemical compounds for medicine or agriculture, enable a perfectly secure exchange of private messages, optimize and enha
> thousands of other uses we haven’t thought of yet
Nice, there's a bit of a call-to-action in this :ok_hand:

2022-12-16 20:55 UTC, isaacdevlugt commented on README.md
> +  quantum chemistry is the leading application for quantum computing.
@co9olguy how 'bout this?

```suggestion
- Learning hubs: 
  + [What is quantum computing?](https://pennylane.ai/qml/whatisqml.html) Understand what quantum computers can do and how we can make them do it. 
  + [What is quantum machine learning?](https://pennylane.ai/qml/whatisqml.html) Understand what
  quantum computing means for machine learning. 
  + [What is quantum chemistry?](https://pennylane.ai/qml/whatisqml.html) Understand why
  quantum chemistry is the leading application for quantum computing.
```

2022-12-18 12:13 UTC, ikurecic commented on whatisqc.rst
> +.. image:: /_static/whatisqc/quantum_computer.svg
Will remove, thanks.

2022-12-20 18:04 UTC, ikurecic commented on whatisqc.rst
> +.. image:: /_static/whatisqc/NISQ_computing.svg
We can't modify the size of the image, but I can attempt to shorten the text, although this wrapping is exclusively subject to the interaction of your screen width and font size... it will look different on different screens.

2023-01-06 17:56 UTC, co9olguy commented on whatisqc.rst
> +.. figure:: /_static/whatisqc/PennyLane_applications.svg
Since this image is used elsewhere, should we put it in a single shared location rather than duplicating in different subfolders?

2023-01-06 17:56 UTC, co9olguy commented on glossary.rst
> +        A research area that explores what quantum computers can do and how to make them do it.
I like the second (more concise), with a small suggested tweak:

```
A research area that extends the set of physical laws classical computers operate on by 
accessing quantum aspects of the physical world, opening up new ways of processing information.
```

It read a bit weird to me that "gains" was a direct verb for the subject/noun "research area"

2023-01-06 17:56 UTC, co9olguy commented on whatisqc.rst
> +   :property="og:image": https://pennylane.ai/qml/_static/whatisqc/quantumt_computer.svg
typo in the URL

2023-01-06 17:56 UTC, co9olguy commented on whatisqc.rst
> +   :property="og:description": Quantum computing is a research area that explores what quantum computers can do and how to make them do it.
The specific discussion took place in the glossary file, but when the dust settles and we have a nice clear and concise description there, would be good to propagate those changes here

2023-01-06 17:56 UTC, co9olguy commented on whatisqc.rst
> +Quantum computing is a research area that explores **what quantum computers can do and how to make them do it**. It is a highly interdisciplinary field of quantum science and technology, sitting at t
ditto here for the change from glossary & description.

2023-01-06 17:56 UTC, co9olguy commented on whatisqc.rst
> +Examples span the gamut from low-level hardware problems that engage a variety of phenomena in quantum mechanics, such as the implementation of physical schemes to control and stabilize quantum units
a nice improvement! :+1:

2023-01-06 17:56 UTC, co9olguy commented on whatisqc.rst
> +Quantum computers **extend the set of physical laws** classical computers operate on by accessing quantum aspects of the physical world and, as a result, gain new ways of processing information. For
once the top-level description is updated, it will likely steal the thunder from this opener, so we'll have to adjust slightly here to compensate

2023-01-06 17:56 UTC, co9olguy commented on whatisqc.rst
> +.. image:: /_static/whatisqc/NISQ_computing.svg
I don't know what others see, but I hope I'm not just a strange outlier. I see spill-over for quite a range of different browser window sizes (using both firefox & chrome on ubuntu). I would expect others are likely to encounter something similar, so would be good to trim. 

Alternatively, we can also get the frontend devs to put in some divs/borders for us which prevent this spilling over. So what I'd recommend is that we keep an eye out for this in the final implementation, and we adjust there as needed (we don't need to over-optimize in this PR, but let's not forget this point later :point_right: :brain:)

2023-01-06 17:56 UTC, co9olguy commented on whatisqc.rst
> +Perhaps the primary ambition of the field of quantum computing nowadays is to develop a **scalable, fault-tolerant device** on which any and all quantum algorithms can be implemented. Research in spe
reads nicely, like the change :)

2023-01-06 17:56 UTC, co9olguy commented on whatisqc.rst
> +On top of that, real devices that can carry out useful quantum algorithms consist of **many interacting components** and they must be able to correct errors that inevitably arise from **device–enviro
Thanks for the suggestion. In my mind, it reads a bit too verbose. I wonder if we can simplify while still hitting the key points? e.g., something like

```suggestion
On top of that, real devices that can carry out useful quantum algorithms consist of **many interacting components** , which must be able to correct errors that inevitably arise from **device–environment interactions**. Architectures where errors can be corrected faster than they occur are referred to as *fault-tolerant*.
```

2023-01-06 17:56 UTC, co9olguy commented on whatisqc.rst
> +Quantum computational advantage does not necessarily need to be demonstrated on problems that are thought of as useful or practical, but it shows a clear sign toward the bright future of quantum comp
you mean the dilution fridge? It's fine. There are also some other abstract "quantum computer" images there so I think its more balanced

2023-01-06 17:56 UTC, co9olguy commented on whatisqc.rst
> +Quantum computational advantage does not necessarily need to be demonstrated on problems that are thought of as useful or practical, but it shows a clear sign toward the bright future of quantum comp
Nice!

2023-01-06 17:56 UTC, co9olguy commented on whatisqc.rst
> +Quantum computational advantage does not necessarily need to be demonstrated on problems that are thought of as useful or practical, but it shows a clear sign toward the bright future of quantum comp
just one small tweak/reordering suggested:
"... but some instances have already been demonstrated of quantum devices solving computational problems that would take classical computers an unfeasible amount of time."

2023-01-06 17:56 UTC, co9olguy commented on whatisqc.rst
> +Quantum computational advantage does not necessarily need to be demonstrated on problems that are thought of as useful or practical, but it shows a clear sign toward the bright future of quantum comp
Could also do a bold highlight in first paragraph? Any proposals? Maybe "quantum computational advantage is already a reality" could be good?

2023-01-06 17:56 UTC, co9olguy commented on whatisqc.rst
> +Few technological advances hold a real potential to let us speed through entire stages of scientific development, but quantum computers are likely to be the cornerstone *general-purpose technology* o
:100:

2023-01-13 20:23 UTC, BM7878 commented on glossary.rst
> +        A research area that explores what quantum computers can do and how to make them do it.
I like the above.

A shorter option if wanted could simply be: 'A research area that explores how universal computation can be achieved through quantum-mechanical systems.'

2023-01-21 21:47 UTC, ikurecic commented on whatisqc.rst
> +Quantum computational advantage does not necessarily need to be demonstrated on problems that are thought of as useful or practical, but it shows a clear sign toward the bright future of quantum comp
That all sounds great, thank you!

2023-01-21 21:48 UTC, ikurecic commented on whatisqc.rst
> +.. figure:: /_static/whatisqc/PennyLane_applications.svg
Yes, ideally. :) I'll point it out to Ana once it's set up.

2023-01-21 22:03 UTC, ikurecic commented on glossary.rst
> +        A research area that explores what quantum computers can do and how to make them do it.
Sorted, thank you!

2023-01-21 22:04 UTC, ikurecic commented on whatisqc.rst
> +.. image:: /_static/whatisqc/NISQ_computing.svg
Definitely, let's see what it looks like at the end! We can add/remove words, just can't touch the images.

2023-01-21 23:35 UTC, ikurecic commented on whatisqc.rst
> +   :property="og:description": Quantum computing is a research area that explores what quantum computers can do and how to make them do it.
Updated

2023-01-21 23:35 UTC, ikurecic commented on whatisqc.rst
> +Quantum computing is a research area that explores **what quantum computers can do and how to make them do it**. It is a highly interdisciplinary field of quantum science and technology, sitting at t
Updated

2023-01-21 23:35 UTC, ikurecic commented on whatisqc.rst
> +Quantum computers **extend the set of physical laws** classical computers operate on by accessing quantum aspects of the physical world and, as a result, gain new ways of processing information. For
Updated with a mish-mash that I think looks fine.

2023-01-21 23:53 UTC, ikurecic commented
Just a tag @co9olguy @BM7878 so you're aware I tidied up the files here based on the comments.

2023-01-23 01:30 UTC, josh146 commented on whatisqc.rst
> +.. image:: /_static/whatisqc/NISQ_computing.svg
One option for the devs is to add padding above and below the image :)

2023-01-23 14:05 UTC, ashishks0522 requested changes

2023-01-23 14:05 UTC, ashishks0522 commented on whatisqc.rst
> +.. role:: html(raw)
Can we update the file name to be `what-is-quantum-computing.rst` to align the URL name with the requirements [here](https://docs.google.com/document/d/12TTsdBTTBoJ9aYi2NgMnDct_5Sxa7k-K2Xo7fbUAjqY/edit)

2023-01-23 14:06 UTC, ashishks0522 requested changes

2023-01-23 14:06 UTC, ashishks0522 commented on glossary.rst
> +    :doc:`Quantum Computing <whatisqc>`
```suggestion
    :doc:`Quantum Computing <what-is-quantum-computing>`
```

When we update the page name as per previous comment

2023-01-23 14:58 UTC, ikurecic commented on whatisqc.rst
> +.. role:: html(raw)
@ashishks0522 — yep, will sort it out.

2023-01-23 16:13 UTC, ashishks0522 reviewed
if we could change the base from `master` to `sc-30754-create-quantum-computing-hub` for this PR

That would help us manage merging sub-hubs into superhub PR as they get completed.

2023-01-23 17:01 UTC, BM7878 approved these changes

2023-01-23 18:31 UTC, isaacdevlugt commented
Rebase issues have been fixed

2023-01-24 22:47 UTC, co9olguy commented on what-is-quantum-computing.rst
> +at once and operate entirely differently form their classical counterparts.
```suggestion
at once and operate entirely differently from their classical counterparts.
```

2023-01-24 22:48 UTC, co9olguy commented on what-is-quantum-computing.rst
> +computers an unfeasible amount of time. Despite this, ****quantum computational advantage is already a reality**,
```suggestion
computers an unfeasible amount of time. Despite this, **quantum computational advantage is already a reality**, 
```

2023-01-24 22:56 UTC, co9olguy commented on what-is-quantum-computing.rst
> +computers an unfeasible amount of time. Despite this, ****quantum computational advantage is already a reality**,
Something's off about these two sentences. :thinking:.
It seems to say:
- Q. advantage has been recently demonstrated
- Despite this, Q. advantage is already a reality

Would be good to use a transition which conveys more a sense of continuation of the previous thought (something like "Because of this"?), rather than a contradiction ("Despite")

2023-01-24 23:14 UTC, co9olguy commented on what-is-quantum-computing.rst
> +.. role:: html(raw)
There are two unused images that seem to have snuck into this PR :thinking: 
Be good to remove them if not needed
(sorry can't leave comment on the images directly; they're the same ones as in QChem page)

2023-01-24 23:15 UTC, co9olguy approved these changes
Spotted a couple small fixes still needed.

Ok to merge once addressed. No need for me to review again

2023-01-25 11:11 UTC, ikurecic commented on what-is-quantum-computing.rst
> +.. role:: html(raw)
Yeah, probably the same issue. I'll fix it.

2023-01-25 11:15 UTC, ikurecic commented on what-is-quantum-computing.rst
> +computers an unfeasible amount of time. Despite this, ****quantum computational advantage is already a reality**,
Thanks for spotting it. I'd just remove the 'intro' altogether, and start with "Quantum advantage is already a reality" ...

2023-01-26 14:54 UTC, josh146 requested changes
Thanks @ikurecic! Looking good, main reason I request changes is just it seems like the images are outdated?

2023-01-26 14:54 UTC, josh146 commented on README.md
> +  + [What is quantum chemistry?](https://pennylane.ai/qml/whatisqml.html) Understand why
```suggestion
  + [What is quantum chemistry?](https://pennylane.ai/qml/what-is-quantum-chemistry.html) Understand why
```

2023-01-26 14:54 UTC, josh146 commented on README.md
> +  + [What is quantum computing?](https://pennylane.ai/qml/whatisqml.html) Understand what quantum computers can do and how we can make them do it.
```suggestion
  + [What is quantum computing?](https://pennylane.ai/qml/what-is-quantum-computing.html) Understand what quantum computers can do and how we can make them do it. 
```

2023-01-26 14:54 UTC, josh146 commented on what-is-quantum-computing.rst
> +.. role:: html(raw)
@ikurecic has this been resolved?

2023-01-26 14:54 UTC, josh146 commented on what-is-quantum-computing.rst
> +.. image:: /_static/whatisqc/quantum_computer.svg
@ikurecic I've noticed that there are newer versions of the images available from Tarik that don't seem to be updated here yet?

2023-01-26 14:54 UTC, josh146 commented on what-is-quantum-computing.rst
> +   :property="og:image": https://pennylane.ai/qml/_static/whatisqc/quantum_computer.svg
```suggestion
   :property="og:description": Quantum computing is a research area that extends the set of physical laws classical computers operate on by accessing quantum aspects of the physical world, opening up new ways of processing information.
   :property="og:image": https://pennylane.ai/qml/_static/whatisqc/quantum_computer.svg
```

2023-01-26 14:54 UTC, josh146 commented on what-is-quantum-computing.rst
> +To find out more, visit the `PennyLane Documentation <https://pennylane.readthedocs.io>`_ or check out the gallery of hands-on :doc:`demonstrations <demonstrations>`.
```suggestion
To find out more, visit the `PennyLane Documentation <https://docs.pennylane.ai>`_ or check out the gallery of hands-on :doc:`demonstrations <demonstrations>`.
```

2023-01-26 14:54 UTC, josh146 commented on what-is-quantum-computing.rst
> +*quantum neural networks*.
Worth making this a link to https://pennylane.ai/qml/demos_qml.html?

2023-01-26 14:54 UTC, josh146 commented on what-is-quantum-computing.rst
> +making their devices publicly available for further research.
I think there is an opportunity to spread some links here, e.g.,

```suggestion
with an `increasing <https://www.nature.com/articles/s41586-022-04725-x>`__ :doc:`number <tutorial_gbs>` of :doc:`commercial <qsim_beyond_classical>` and research organizations announcing their breakthroughs—some even 
making their devices publicly available for further research.
```

2023-01-26 14:54 UTC, josh146 commented on what-is-quantum-computing.rst
> +making their devices publicly available for further research.
the words that should be links in the sentence open to being changed 😆

2023-01-26 14:54 UTC, josh146 commented on what-is-quantum-computing.rst
> +making their devices publicly available for further research.
Went through the docs, no other demos/pages come to mind for linking but I might be missing something.

2023-01-26 14:54 UTC, josh146 commented on what-is-quantum-computing.rst
> +**thousands of other uses we haven’t thought of yet**.
Good opportunity to link to what is qchem!

2023-01-26 14:54 UTC, josh146 commented on what-is-quantum-computing.rst
> +*quantum neural networks*.
Or could also link to what is qml, maybe that is more appropriate.

2023-01-26 15:30 UTC, ikurecic commented on what-is-quantum-computing.rst
> +.. image:: /_static/whatisqc/quantum_computer.svg
Yep, will explain in detail in Slack.

2023-01-26 15:31 UTC, josh146 commented on what-is-quantum-computing.rst
> +.. role:: html(raw)
perfect, thanks!

2023-01-26 15:39 UTC, ikurecic commented on what-is-quantum-computing.rst
> +*quantum neural networks*.
The 'what is QML' link makes more sense to me, will include.

2023-01-26 15:48 UTC, ikurecic commented on what-is-quantum-computing.rst
> +making their devices publicly available for further research.
I'll give it an attempt.

2023-01-26 17:34 UTC, josh146 approved these changes
Awesome, thank you!

2023-01-26 17:34 UTC, merged