[WIP] update adaptive demo
PennyLaneAI/qml pull request #641
Opened 2022-11-17 22:15 UTC by soranjh

**Title:**
Adds code examples using the adaptive optimizer to the adaptive demo.

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2022-11-29 14:20 UTC, KetpuntoG commented
I am fixing the issue, it is not related to this PR. 
I'll let you know here when it's ready :)

2022-12-01 20:56 UTC, KetpuntoG commented on demonstrations/tutorial_adaptive_circuits.py
> +        break
I think the gif could fit here 😄
otherwise, the changes seem good to me

2022-12-01 22:16 UTC, soranjh commented on demonstrations/tutorial_adaptive_circuits.py
> +        break
Do you know why the gif does not show as the thumbnail?

2022-12-01 23:39 UTC, KetpuntoG commented on demonstrations/tutorial_adaptive_circuits.py
> +        break
the thumbnail is the image you put in `.rst`
at the top of the `.py` is the image that will be displayed when the link is sent. Anyway, a thumbnail that moves can be a bit misleading. You can do the test anyway if you want to see how it looks like :)

2022-12-02 01:48 UTC, josh146 commented
Is there a reason this demo is being made to `dev` and not `master`?

2022-12-02 14:10 UTC, soranjh commented
> Is there a reason this demo is being made to `dev` and not `master`?

I created it, locally, before the release. Will be rebased to master.

2022-12-02 14:21 UTC, soranjh commented on demonstrations/tutorial_adaptive_circuits.py
> +        break
Removed the gif file.

2023-01-17 21:25 UTC, ixfoduap requested changes

2023-01-17 21:25 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +use an :class:`~.pennylane.optimize.AdaptiveOptimizer` implemented in PennyLane to perform ADAPT-VQE
Link to AdaptiveOptimizer is not working for me. Applies to all instances where this is called

2023-01-17 21:25 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +    print(qml.draw(circuit)())
This is producing a really large output that is difficult to navigate in the built demo. It would be AMAZING to instead have a gif showing how the circuit is built step by step. Either way, I think an alternative should be found as the output here is very messy

2023-01-17 21:25 UTC, ixfoduap commented on demonstrations/tutorial_adaptive_circuits.py
> +# Adaptive Optimizer
I suggest presenting this before the manual construction so that it is easier to find by the users

2023-01-17 23:46 UTC, KetpuntoG commented on demonstrations/tutorial_adaptive_circuits.py
> +    print(qml.draw(circuit)())
In fact we have made this gif! 😄 It was suggested not to put it as thumbnail and I think there has been a misunderstanding and it was removed from here too. Could you add it?

2023-01-17 23:47 UTC, KetpuntoG commented on demonstrations/tutorial_adaptive_circuits.py
> +    print(qml.draw(circuit)())
![qchem-anim (1)](https://user-images.githubusercontent.com/65235481/213036937-faf308d1-9bac-4464-b8df-752b6cdb1d9a.gif)

2023-01-23 14:38 UTC, obliviateandsurrender requested changes
Looking good from my end, just left a small suggestion.

2023-01-23 14:38 UTC, obliviateandsurrender commented on demonstrations/tutorial_adaptive_circuits.py
> +# grows and optimizes an input quantum circuit by adding gates selected from a user-defined
Could we rewrite this sentence? Currently, it gives me a feeling that you mean to say that adding a new gate operator somehow optimizes the input circuit.

2023-01-23 19:41 UTC, soranjh commented on demonstrations/tutorial_adaptive_circuits.py
> +operator_pool = doubles_excitations + singles_excitations
It is the first time that the operator pool and its content is defined. Please note that the pool contains actual pennylane excitation operations not excitations of the form [wire0, wire1] etc.

2023-01-23 19:52 UTC, obliviateandsurrender commented on demonstrations/tutorial_adaptive_circuits.py
> +operator_pool = doubles_excitations + singles_excitations
They are defined previously on lines `251-253`.

2023-01-23 19:56 UTC, soranjh commented on demonstrations/tutorial_adaptive_circuits.py
> +# grows and optimizes an input quantum circuit by adding gates selected from a user-defined
Rephrased.

2023-01-24 19:57 UTC, soranjh commented on demonstrations/tutorial_adaptive_circuits.py
> +use an :class:`~.pennylane.optimize.AdaptiveOptimizer` implemented in PennyLane to perform ADAPT-VQE
Corrected.

2023-01-24 19:57 UTC, soranjh commented on demonstrations/tutorial_adaptive_circuits.py
> +    print(qml.draw(circuit)())
Added.

2023-01-24 19:58 UTC, soranjh commented on demonstrations/tutorial_adaptive_circuits.py
> +# Adaptive Optimizer
Modified.

2023-01-26 17:29 UTC, obliviateandsurrender approved these changes
Looking good, just leaving a final small suggestion.

2023-01-26 17:29 UTC, obliviateandsurrender commented on demonstrations/tutorial_adaptive_circuits.py
> +# excitation gates [#givenstutorial]_. Let's now use an :class:`~.pennylane.AdaptiveOptimizer`
I think we should follow the citation style mentioned [here](https://pennylane.ai/qml/demonstrations.html) for the Givens demo.

2023-04-10 15:28 UTC, merged

2023-04-10 15:29 UTC, KetpuntoG commented
Thanks for the update @soranjh ! 🚀😄
Sorry to have postponed the merge of this so much