WIP: Tutorial on implicit differentiation
PennyLaneAI/qml pull request #644
Opened 2022-11-20 15:43 UTC by quantshah

**Title:**
Implicit differentiation of variational quantum algorithms

**Summary:**

Implicit differentiation can be used to compute gradients of a function that
cannot be written down explicitly using simple elementary operations. In this
notebook we use the idea of implicit differentiation to compute gradients
through a variational quantum algorithm (VQA) that finds groundstate solutions to
a parameterized Hamiltonian `H(a)` 

I need to 

- [ ] add a thumbnail link in `implementations.rst`. 
- [ ] Make a doodle explaining the concept instead of the exact figure used now
- [ ] Add a doodle for the variational quantum circuit that helps in the understanding. 
- [ ] Make some small changes to the plot to present the results a bit better. 

**Relevant references:**

[1] Ahmed, S., Killoran, K., Carrasquilla Álvarez J. F. "Implicit differentiation
 of variational quantum algorithms." arXiv preprint arXiv:2022.XXXX (2022).

[2] Blondel, Mathieu, et al. "Efficient and modular implicit
differentiation." arXiv preprint arXiv:2105.15183 (2021).

**Possible Drawbacks:**

The computing of these gradients on real hardware, or with `shots=finite` needs more investigation. 
It is extremely slow with finite shots and in most cases not possible as JAXOpt wants to JIT all calculations
while computing implicit gradients. Nevertheless it works as it is for now. 

**Related GitHub Issues:**

2022-11-21 20:35 UTC, KetpuntoG commented
Hey @quantshah The bug has been fixed 😄 There are two things to take into account now to deploy the demo:
- I think you are importing a library that is not in the `requirements.txt` (jaxopt) so it is not going to pass the tests (not sure). Could you add it with the version you are using?
- Don't forget to add the item in `demos_qml.rst`. Don't worry about the thumbnail now. Put any image and we will modify it

2022-11-21 22:44 UTC, co9olguy requested changes
Thanks @quantshah for the demo! Already it's in a pretty advanced state, so hopefully shouldn't take much work to make it camera read.

I've left a number of comments, and I know you're aware of some of the build/rendering issues. To summarize the high-level requests, I would ask for the following:

- Have more of an exciting hook to draw the reader in (1-2 paragraphs) before digging into the more technically specific details. The hook may itself have some technical elements, but it should be more accessible and interesting, e.g., see how [this demo](https://pennylane.ai/qml/demos/quantum_volume.html) does it
- similarly, a brief concluding section to summarize, wrap everything up, and maybe direct the reader to next steps they can follow if they found this material interesting
- break up the code blocks a bit more with plain text. I think you intended to do this, but it didn't render properly, and so it was hard to tell what was deliberately meant to be rendered as plain text and what as code comments

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +    \langle A\rangle = \langle \psi_{z}| A| \psi_{z}\rangle.
```suggestion
    \langle A\rangle = \langle \psi_{z^*}| A| \psi_{z*}\rangle.
```

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +susceptibility. In a similar way, we can now take implicit gradients through
```suggestion
The quantity :math:`\partial_{a} \langle A\rangle` is called *generalized susceptibility*. 
In a similar way, we can now take implicit gradients through
```

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +susceptibility. In a similar way, we can now take implicit gradients through
In a similar way to what? :thinking:

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +are written as gradients w.r.t. the ground state e.g., nuclear forces in
```suggestion
are written as gradients with respect to the ground state, e.g., nuclear forces in
```

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# We build H0 using PennyLane and convert it into a matrix
```suggestion
```
the code itself is already pretty good self-documenting :)

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# Defining the measurement operator
Note that putting these blocks causes the code to be split a bit awkwardly in the build pages
![image](https://user-images.githubusercontent.com/7213358/203168450-f4d43df8-2029-4d1f-a831-e922e7b1d13e.png)

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +    through computed from an eigendecomposition.
```suggestion
    through, computed from an eigendecomposition.
```

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# over different values of `a`.
It'd be good for these parts to render as plain text rather than code comments.

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# over different values of `a`.
overall once the code starts, it becomes just a big single block of code. Would be good to break it up with plain text where appropriate. You know how to do it? See example below for formatting so sphinx can pick the plain text parts out

![image](https://user-images.githubusercontent.com/7213358/203169172-47e799cc-9179-40fb-ba16-be9a36e53cb4.png)

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# over different values of `a`.
so you'll want to replace your hashtags under the subtitles with horizontal lines/dashes, and make sure that the "blank lines" begin with a comment symbol

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# over different values of `a`.
```suggestion
# Let us now compute the susceptibility function by taking gradients of the expectation value
# of our operator :math:`A` with respect to `a`. We can use `jax.vmap` to vectorize the computation
# over different values of `a`.
```

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +
Not sure the cause, but something off with the interpolation in the plot :thinking: 
![image](https://user-images.githubusercontent.com/7213358/203169781-95f27272-e7ab-44fa-b529-d01f66fd442a.png)

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# Computing susceptibility through implicit differentiation using PennyLane
```suggestion
# Computing susceptibility through implicit differentiation
```

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# by taking gradients through the ground state minimization.
```suggestion
# by taking gradients through the ground-state minimization.
```

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +"""
image doesn't render as an image, it is being treated and rendered like code

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# `SimplifiedTwoDesign` that implements the two-design ansatz from Cerezo et al. 2021.
might as well do a proper citation of that paper, so it shows up in footnote at end of page

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# such as susceptibilities.
Is this information necessary to the code or understanding implicit diff? Or is it tangential to the main content?

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# Define the Hamiltonian and variational wavefunction
```suggestion
# Define the Hamiltonian and variational state
```

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# Note that `shots=None` makes the computation of gradients using reverse mode
```suggestion
# Note that `shots=None` makes the computation of gradients using reverse-mode
```

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +dev2 = qml.device("default.qubit.jax", wires=N, shots=None)  # This is good ol backprop
why two devices? :thinking: 
Is it necessary to make two?

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +    # operator arithmetic with JAX device arrays.
:crying_cat_face: 
Could you make a feature request for this? Just to put on the team's roadmap

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# It all works due to Pennylane's excellent Jax integration. The implicit differentiation formulas
Glad to hear it :slightly_smiling_face: 
For readability, would be better to focus on what is going on, since there's been a lot of code to parse through to get to this point. What is "it"? here. What does "works" mean?

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# that computes a ground state and then computes the expectation `<M>` and finally take gradients.
the line lengths are a bit too long here, causes a horizontal scrollbar to appear in the rendered page :scream:

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# that `jaxopt` provides can leverage VJP calculations using the Pennylane Jax interface and provide
"VJP" too technical, and I don't think discussed elsewhere in demo

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# computation ourselves but for this notebook, we use the excellent intergration between Pennylane, Jax
```suggestion
# computation ourselves but for this notebook, we use the integration between Pennylane, Jax,
```

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# computation ourselves but for this notebook, we use the excellent intergration between Pennylane, Jax
```suggestion
# us with the implicit gradients. In a seperate demo we will implement the implicit gradient
# computation ourselves but for this demo, we use the excellent intergration between Pennylane, Jax
```

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# computation ourselves but for this notebook, we use the excellent intergration between Pennylane, Jax
As a suggestion, maybe better to not point out to a separate demo that does not exist yet. When that one is ready, we can update this one to link to it and revise the text here

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# that computes a ground state and then computes the expectation `<M>` and finally take gradients.
a bit too much "A then B then C then D finally E" in these two sentences. Would be good to rephrase a bit to make more readable

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +
Would be good to have a concluding section here, summarizing what was presented/learned, and maybe hinting at what a reader could do next if they found it interesting :)

2022-11-21 22:44 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# References
We can make references generate automatic internal links. You can see how it's done in other demos

2022-11-22 02:17 UTC, josh146 commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +    \partial_a f(z_0, a_0) + \partial_{z} f(z_0, a_0) \partial_{a} z^{*}(a) &=& 0 \\
@quantshah might be a case where you need to do `\begin{align}` etc

2022-11-22 02:28 UTC, josh146 commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +    # operator arithmetic with JAX device arrays.
Looks like it works with the new operator arithmetic! So may just be a matter of deprecating `qml.Hamiltonian` in an upcoming version of PL.

```pycon
>>> coeffs = jnp.array([0.1, 0.2, 0.3])
>>> ops = [qml.PauliX(wires=0), qml.PauliY(wires=1), qml.PauliZ(wires=2)]
>>> H = qml.op_sum(*[qml.s_prod(c, op) for c, op in zip(coeffs, ops)])
>>> qml.simplify(jnp.array(0.6) * H)
(0.06*(PauliX(wires=[0]))) + (0.12*(PauliY(wires=[1]))) + (0.18*(PauliZ(wires=[2])))
```

Although @albi3ro I couldn't work out if there was a better way of taking the 'dot product' of a coefficient array and a list of ops, without requiring a for loop?

2022-11-22 17:08 UTC, quantshah commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +r"""
Done. I was not sure if I should have added it to the beginning or end (went for the beginning).

2022-11-22 21:51 UTC, josh146 commented on requirements.txt
> +jaxopt
@quantshah just a reminder so that we don't forget - do you mind pinning the version of `jaxopt` to the one you use locally when you get a chance. Thanks!

2022-11-23 09:23 UTC, quantshah commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +Implicit differentiation can be used to compute gradients of a function that
Added the hook with folium of Descartes and references to neural ODEs and other applications of implicit diff.

2022-11-23 09:23 UTC, quantshah commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +notebook we use the idea of implicit differentiation to compute gradients
Done, I will refer to it as a demo.

2022-11-23 09:43 UTC, quantshah commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +    \partial_a \langle A \rangle = \partial_a \langle \psi_{z^{*}(a)} | A |\psi_{z^{*}(a)} \rangle.
I think the hook should do it now.

2022-11-23 09:51 UTC, quantshah commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +    \partial_a \langle A \rangle = \partial_a \langle \psi_{z^{*}(a)} | A |\psi_{z^{*}(a)} \rangle.
Done. I talk about implcit diff a bit more here and motivate why we would like to use it.

2022-11-23 09:51 UTC, quantshah commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +steps, it could be computationally expensive.
Done

2022-11-23 09:56 UTC, quantshah commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +the full optimization algorithm would require keeping track of all the steps
Done. In the intro I talk about this now.

2022-11-23 10:33 UTC, quantshah commented on requirements.txt
> +jaxopt
Done

2022-11-23 11:46 UTC, quantshah commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +    \partial_a f(z_0, a_0) + \partial_{z} f(z_0, a_0) \partial_{a} z^{*}(a) &=& 0 \\
Done.

2022-11-23 11:46 UTC, quantshah commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +Therefore we need to find a so-called optimality condition (or fixed-point equation)
Thanks. Makes sense.

2022-11-23 13:43 UTC, quantshah commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# that `jaxopt` provides can leverage VJP calculations using the Pennylane Jax interface and provide
Removed

2022-11-23 13:43 UTC, quantshah commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# It all works due to Pennylane's excellent Jax integration. The implicit differentiation formulas
Done.

2022-11-23 13:59 UTC, quantshah commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +    # operator arithmetic with JAX device arrays.
I leave it as it is now

2022-11-23 14:34 UTC, quantshah commented
@co9olguy Thank you for the very detailed review. I have now implemented all the changes and this is ready to be reviewed/merged from my side. @KetpuntoG is it possible to render the webpage again now?

2022-11-23 16:39 UTC, josh146 commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +##############################################################################
@quantshah couple of things:

- if you intend for this (and other text sections below) to be _subheadings_, you'll need to replace `-----` with `~~~~~`.

- Similarly, to fix the rendering issue, I think this just requires adding a space after the heading, and removing the closing `#################`.

2022-11-23 16:43 UTC, josh146 commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +    """
Suggestion not required for merging :)

2022-11-23 16:44 UTC, josh146 commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# controlled-Z gates. In each layer there are `N - 1` parameters for Pauli-Y gates.
```suggestion
# controlled-Z gates. In each layer there are ``N - 1`` parameters for Pauli-Y gates.
```

2022-11-23 16:44 UTC, josh146 commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# We set `n_layers = 5` but you can redo this example with fewer layers to see
```suggestion
# We set ``n_layers = 5`` but you can redo this example with fewer layers to see
```

2022-11-23 16:44 UTC, josh146 commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +#   The setting `shots=None` makes the computation of gradients using reverse-mode
```suggestion
#   The setting ``shots=None`` makes the computation of gradients using reverse-mode
```

2022-11-23 16:45 UTC, josh146 commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# gradient of any function of the ground state w.r.t. `a`.
```suggestion
# We construct a loss function that defines a ground-state minimization
# task. We are looking for variational parameters ``z`` that minimize the energy
# function. Once we find a set of parameters ``z``, we wish to compute the
# gradient of any function of the ground state w.r.t. ``a``.
```

2022-11-23 16:45 UTC, josh146 commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# It all works due to Pennylane's excellent JAX integration.
```suggestion
# We will use the tool ``jaxopt`` for implicit differentiation. ``jaxopt`` implements
# modular implicit differentiation for various cases, e.g., for fixed-point
# functions or optimization. We can directly use ``jaxopt`` to optimize our loss
# function and then compute implicit gradients through it.
# It all works due to PennyLane's excellent JAX integration.
```

2022-11-23 16:46 UTC, josh146 commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# JAX as shown here: https://jax.readthedocs.io/en/latest/notebooks/Custom_derivative_rules_for_Python_code.html#implicit-function-differentiation-of-iterative-implementations
```suggestion
# The implicit differentiation formulas can even be `implemented manually with
# JAX <https://jax.readthedocs.io/en/latest/notebooks/Custom_derivative_rules_for_Python_code.html#implicit-function-differentiation-of-iterative-implementations>`__.
```

Better for accessibility/people using screen readers :)

2022-11-23 16:46 UTC, josh146 commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# `jaxopt.GradientDescent` optimizer with `implicit_diff=True` lets us compute
```suggestion
# ``jaxopt`` implements these formulas in a modular way such that using the
# ``jaxopt.GradientDescent`` optimizer with ``implicit_diff=True`` lets us compute
```

2022-11-23 16:46 UTC, josh146 commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# plugs it any computation used by `jax.grad`. We can also just-in-time (JIT)
```suggestion
# Differentiating through the ``groundstate_solution_map_variational`` function
# here uses implicit differentiation through the ``jaxopt.GradientDescent``
# optimization. Since everything is written in JAX, simply calling the
# ``jax.grad`` function works as ``jaxopt`` computes the implicit gradients and
# plugs it any computation used by ``jax.grad``. We can also just-in-time (JIT)
```

2022-11-23 16:47 UTC, josh146 commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# We can compute the susceptibility values by simply using `jax.grad`. After the
```suggestion
# We can compute the susceptibility values by simply using ``jax.grad``. After the
```

2022-11-23 16:47 UTC, josh146 commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# Computing gradients through the VQA simply by calling `jax.grad`
```suggestion
# Computing gradients through the VQA simply by calling ``jax.grad``
```

2022-11-23 16:56 UTC, KetpuntoG commented
> @co9olguy Thank you for the very detailed review. I have now implemented all the changes and this is ready to be reviewed/merged from my side. @KetpuntoG is it possible to render the webpage again now?

Thanks for the work done this morning! As you can see, it already renders in this PR😊 I'm now going to give another revision to the demo

2022-11-23 20:56 UTC, KetpuntoG reviewed
Here are a few comments, good job @quantshah ! 💪
I loved the initial hook talking about Descartes and Fermat

2022-11-23 20:56 UTC, KetpuntoG commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# Defining the Hamiltonian and measurement operator
As a personal suggestion: the rendering of these paragraphs does not catch my attention. It might look better to put a normal paragraph (eliminating the title) and putting in bold text the keywords (which are at the beginning).

2022-11-23 20:56 UTC, KetpuntoG commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# adding the parametric to it as a separate term. Note that for the example of
I understand that this is for efficiency reasons, but if you indicate it, it would be better.

2022-11-23 20:56 UTC, KetpuntoG commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +
Do you think it would make sense to end this cell here and send the rest of the functions to the next cell?

2022-11-23 20:56 UTC, KetpuntoG commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +print("Variational parameters for the groundstate", z_star_variational)
Viewing a list of parameters is not something that gives too much information. You could save the print and write in the following paragraph: we have already calculated our parameters z_star, now....

2022-11-23 20:56 UTC, KetpuntoG commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +
Cool results! 🚀

2022-11-23 20:56 UTC, KetpuntoG commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +print(qml.about())
the pennylane version will always be updated with the latest release. You can remove this part to make it more attractive at first sight.

2022-11-23 20:56 UTC, KetpuntoG commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +.. related::
although not super related, it is always good to have references to other demos that do similar things for those who want to continue learning. Maybe the [pennylane and Jax ](https://pennylane.ai/qml/demos/tutorial_jax_transformations.html)one can be useful too.

2022-11-23 20:56 UTC, KetpuntoG commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +Even though for the small number of spins we consider here, eigendecompostion and
```suggestion
Even though for the small number of spins we consider here, eigendecomposition and
```

2022-11-23 20:56 UTC, KetpuntoG commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +gradient computation through it suffices, for larger systems it quickly becomes
```suggestion
gradient computation through it suffice, for larger systems it quickly becomes
```
(not sure)

2022-11-23 20:56 UTC, KetpuntoG commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +algorithm could compute the solution starting from an initial set of values
```suggestion
algorithms could compute the solution starting from an initial set of values
```

2022-11-23 20:56 UTC, KetpuntoG commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +with non-singular Jacobian at the solution, then we can apply chain rule
```suggestion
with non-singular Jacobian at the solution, then we can apply the chain rule
```

2022-11-23 20:56 UTC, KetpuntoG commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# the computation thorough the VQA is more stable.
```suggestion
# the computation through the VQA is more stable.
```

2022-11-23 20:56 UTC, KetpuntoG commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# Suceptibility computation through the ground state solution map
```suggestion
# Susceptibility computation through the ground state solution map
```

2022-11-23 20:56 UTC, KetpuntoG commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# Therefore the ansatz is efficient and as long as it is expressive enough to
Does that "and" make sense?

2022-11-23 20:56 UTC, KetpuntoG commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# The implicit differentiation formulas can eve be implemented manually with
```suggestion
# The implicit differentiation formulas can even be implemented manually with
```

2022-11-23 20:56 UTC, KetpuntoG commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# way, we hope this demo inspires creation of new architectures for quantum
```suggestion
# way, we hope this demo the inspires creation of new architectures for quantum
```

2022-11-23 20:56 UTC, KetpuntoG commented on demos_optimization.rst
> +    :figure: demonstrations/implicit_diff/VQA.png
The image you put here, is the one that will appear in the thumbnail on the web page. The one you put in the `.py` at the beginning, will be the image that will appear when you paste the link somewhere to share it. Normally it is usually the same. That's why I comment it just in case.

2022-11-23 20:56 UTC, KetpuntoG commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +*Authors: Shahnawaz Ahmed, Juan Felipe Carrasquilla Álvarez.
I see a second person who has worked on the demo. It would be interesting to add a photo and bio in such a case

2022-11-23 21:05 UTC, josh146 commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +print(qml.about())
@KetpuntoG it could still be useful in that a user could be using an old version of a package and getting different results; seeing this could let them know what versions they should install.

2022-11-23 21:09 UTC, KetpuntoG commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +print(qml.about())
👌

2022-11-24 12:58 UTC, quantshah commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +The solution changes as we change :math:`H(a)` therefore defining an implicit
You are right, this is the solution and not the implicit function that defines the solution. I will correct it. The implicit function is f(z, a) = 0

2022-11-24 13:05 UTC, quantshah commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +A function :math:`z^{*}(a)` that satisfies :math:`f(z^{*}(a), a) = 0` gives a
In the VQA problem we have a different f(z, a). It is the gradient of the energy, f(z, a) = grad_z (E(z, a)). When f(z, a) = 0, the energy gradient is 0 and therefore we have found a minima of the energy. Its not the same as you have written above here.

2022-11-24 13:21 UTC, quantshah commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +    analytic solution :math:`z^{*}(a)` that satisfies :math:`f(z^{*}(a), a) = 0`.
Thanks. I am keeping it a bit informal rather than state the theorem strictly.

2022-11-24 13:21 UTC, quantshah commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +
Done. Added a reference also for the complex case.

2022-11-24 13:33 UTC, quantshah commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +from functools import reduce
Thanks. While I see the point of it but its one of those things I will find very strange if I read code so I want to keep it as it is now with all the imports at the top. Unless the tutorial had very distinct sections I would prefer all imports at the top.

2022-11-24 14:04 UTC, quantshah commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +*Authors: Shahnawaz Ahmed, Juan Felipe Carrasquilla Álvarez.
Yes that would be nice. Hopefully without delay.

2022-11-24 23:06 UTC, KetpuntoG commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# Defining the Hamiltonian and measurement operator
Great! It looks much better @quantshah , could you apply this to the following paragraphs?

2022-11-25 00:09 UTC, KetpuntoG commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +implementation provided by the tool JAXOpt [#Blondel2021]. We compute the generalized
```suggestion
implementation provided by the tool JAXOpt [#Blondel2021]_. We compute the generalized
```

2022-11-25 00:09 UTC, KetpuntoG commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +the complex domain and we state the theorem (informally) below [#Chang2003].
```suggestion
the complex domain and we state the theorem (informally) below [#Chang2003]_.
```

2022-11-25 13:52 UTC, ikurecic reviewed
Editing (very roughly) for language and clarity. I rearranged the initial section to include a lede — @KetpuntoG , could you please add some good keywords in there?
Some items are missing: the second author's bio, good image metadata

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +*Email: shahnawaz.ahmed95@gmail.com*
The email address should be ingested into the author bio instead.

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +of computing tangents. The curve, now called the folium of Descartes given by
```suggestion
In 1638, René Descartes, intrigued by (then amateur) Pierre de Fermat's method
of computing tangents, challenged Fermat to find the tangent to
a complicated curve — now called the folium of Descartes:
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +and re-arrange the terms to obtain :math:`dy/dx`.
```suggestion
With its cubic terms, this curve represents an implicit equation for which it is not
easy to write as simple of an expression as :math:`y = f(x)`. Therefore, the task of calculating the tangent function
seemed formidable for the method Descartes had then, except for its vertex. 
Fermat successfully provided the tangents at not just the vertex, but at any other point on
the curve, baffling Descartes and legitimizing the intellectual superiority of
his own method. The technique used by Fermat was *implicit differentiation* [#Paradis2004]_.
In the above equation, we can begin by taking derivatives on both sides 
and rearrange the terms to obtain :math:`dy/dx`.
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +called Deep Equilibrium Models (DEQs) [#implicitlayers]_.
```suggestion
Implicit differentiation can be used to compute gradients of such functions that
cannot be written down explicitly using simple elementary operations. It is a
basic technique of calculus that has recently found many applications in machine
learning — from hyperparameter optimization to the training of neural ordinary
differential equations (ODEs), and it has even led to the definition of a whole new class of architectures,
called Deep Equilibrium Models (DEQs) [#implicitlayers]_.
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +that we have the solution
```suggestion
The idea of implicit differentiation can be applied in quantum physics to extend
the power of automatic differentiation to situations where we are not able to
explicitly write down the solution to a problem. As a concrete example, consider
a variational quantum algorithm (VQA) that computes the ground-state solution of
a parameterized Hamiltonian :math:`H(a)` using a variational ansatz
:math:`|\psi_{z}\rangle`, where :math:`z` are the variational parameters. This leads to the solution
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +:math:`A` as
```suggestion
As we change :math:`H(a)`, the solution also changes, but we do not obtain an
explicit function for :math:`z^{*}(a)`. If we are interested in the properties of the
solution state, we could measure the expectation values of some operator
:math:`A` as
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +The solution is only implicitly defined.
```suggestion
With a VQA, we can find a solution to the optimization for a fixed :math:`H(a)`.
However, just like with the folium of Descartes, we do not have an explicit solution,
so the gradient :math:`\partial_a \langle A \rangle (a)` is not easy to compute.
The solution is only implicitly defined.
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +provides an alternative way to efficiently compute such a gradient.
```suggestion
Automatic differentiation techniques that construct an explicit computational
graph and differentiate through it by applying the chain rule for gradient
computation cannot be applied here easily. A brute-force application of automatic
differentiation that finds :math:`z^{*}(a)` throughout the full optimization
would require us to keep track of all intermediate variables and steps in the optimization
and differentiate through them. This could quickly become computationally
expensive and memory-intensive for quantum algorithms. Implicit differentiation
provides an alternative way to efficiently compute such a gradient. 
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +variational quantum algorithms [#Ahmed2022]_.
```suggestion
Similarly, there exist various other
interesting quantities that can be written as gradients of a ground-state solution, 
e.g., nuclear forces in quantum chemistry, permanent electric dipolestatic
polarizability, the static hyperpolarizabilities of various orders,
fidelity susceptibilities, and geometric tensors. All such
quantities could possibly be computed using implicit differentiation on quantum
devices. In our recent work we present a unified way to implement such
computations and other applications of implicit differentiation through
variational quantum algorithms [#Ahmed2022]_.
```
The first sentence basically restates the last sentence of the previous paragraph.

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +infeasible.
```suggestion

```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +
```suggestion
In this demo we show how implicit gradients can be computed using a variational
algorithm written in *PennyLane* and powered by a modular implicit differentiation
implementation provided by the tool *JAXOpt* [#Blondel2021]. We compute the generalized
susceptibility for a spin system by using a variational ansatz to obtain a
ground-state and implicitly differentiating through it. In order to compare
the implicit solution, we find the exact ground-state through eigendecomposition
and determine gradients using automatic differentiation.
Even though this calculation may become unfeasible for larger systems, for a small number of spins, our method suffices.

Introduction
------------

```
@KetpuntoG , I (edited and) transferred this paragraph here as the lede. @co9olguy might want to confirm these are the highlights.

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +We consider differentiating a solution of the root-finding problem defined by
```suggestion
We consider the differentiation of a solution of the root-finding problem, defined by
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +memory intensive.
```suggestion
A function :math:`z^{*}(a)` that satisfies :math:`f(z^{*}(a), a) = 0` gives a
solution map for fixed values of :math:`a`. An explicit analytical solution
is, however, difficult to obtain in general. This means that the direct differentiation of
:math:`\partial_a z^{*}(a)` is not always possible. Despite that, some iterative
algorithms may be able to compute the solution by starting from an initial set of values
for :math:`z`, e.g., using a fixed-point solver. The optimality condition 
:math:`f(z^{*}(a), a) = 0` tells the solver when a solution is found.
```
Can't have 'however' in every sentence.
Also the last two sentences were copy-pasted from a previous paragraph, so I removed them.

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +to differentiate through the solution-finding algorithm [#Blondel2021]_.
```suggestion
Implicit differentiation can be used to compute :math:`\partial_a z^{*}(a)`
more efficiently than brute-force automatic differentiation, using only the
solution :math:`z^{*}(a)` and partial derivatives at the solution point. We do
not have to care about how the solution is obtained and, therefore, do not need
to differentiate through the solution-finding algorithm [#Blondel2021]_.
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +   :alt: circles
@KetpuntoG , can you make the meta more useful?

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +the above equation with respect to :math:`a` as,
```suggestion
In the figure above we can see solutions to the optimality condition 
:math:`f(z, a) = 0 ` (red stars), which defines a curve :math:`z^{*}(a)`. 
According to the IFT, the solution function is analytic, which means it can be
differentiated at the solution points by simply differentiating
the above equation with respect to :math:`a`, as
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +    \partial_a f(z_0, a_0) + \partial_{z} f(z_0, a_0) \partial_{a} z^{*}(a) = 0
```suggestion
    \partial_a f(z_0, a_0) + \partial_{z} f(z_0, a_0) \partial_{a} z^{*}(a) = 0,
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +cost function is zero, i.e.,
```suggestion
This shows that implicit differentiation can be used in situations where we can
phrase our optimization problem in terms of an optimality condition 
or a fixed point equation that can be solved. In case of optimization tasks,
such an optimality condition would be that, at the minima, the gradient of the
cost function is zero — i.e., 
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +a linear problem that can be solved approximately [#Blondel2021]_, [#implicitlayers]_.
```suggestion
Then, as long as we have the solution, :math:`z^{*}(a)`, and the partial derivatives at the solution (in this case the Hessian of the
cost function :math:`g(z, a)`), :math:`(\partial_a f, \partial_z f)`, we can compute implicit gradients. Note that,
for a multivariate function, the inversion
:math:`(\partial_{z} f(z_0, a_0) )^{-1}` needs to be defined and easy to
compute. It is possible to approximate this inversion in a clever way by constructing
a linear problem that can be solved approximately [#Blondel2021]_, [#implicitlayers]_.
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +a linear problem that can be solved approximately [#Blondel2021]_, [#implicitlayers]_.
@KetpuntoG , did you want to 'gather up' the references, or is this format fine for you? With a plaintext comma in between?

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +   :alt: circles
@KetpuntoG , please improve the meta

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +variationally obtained solution.
```suggestion
Now we could find the ground state of this Hamiltonian by simply taking the 
eigendecomposition and applying automatic differentiation through the 
eigendecomposition to compute gradients. We will compare this exact computation
for a small system to the gradients given by implicit differentiation through a
variationally obtained solution.
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +and determine the implicit gradients easily.
```suggestion
In addition, if the conditions of the implicit function theorem
are also satisfied, i.e., :math:`f` is continuously differentiable
with a non-singular Jacobian at the solution, then we can apply the chain rule
and determine the implicit gradients easily.
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +is
```suggestion
At this stage, any other complicated function that depends on the variational ground state
can be easily differentiated using automatic differentiation by plugging in the
value of :math:`partial_a z^{*}(a)` where it is required. The 
expectation value of the operator :math:`A` for the ground state
is
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +Hellmann–Feynman theorem for arbitrary expectation values.
```suggestion
In the case where :math:`A` is just the energy, i.e., :math:`A = H(a)`, the
Hellmann–Feynman theorem allows us to easily compute the gradient. However, for
a general operator we need the gradients :math:`\partial_a z^{*}(a)`, which means that implicit differentiation is a very elegant way to go beyond the
Hellmann–Feynman theorem for arbitrary expectation values.
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +"Talk is cheap. Show me the code." - Linus Torvalds
```suggestion
"Talk is cheap. Show me the code." — Linus Torvalds
```
@KetpuntoG , you sure you want to use an obfuscated section title like this one?

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# gradients :math:`\partial_a z^{*}(a)`.
```suggestion
# We define the Hamiltonian by building the non-parametric part separately and
# adding the parametric part to it as a separate term for efficiency. Note that, for
# the example of generalized susceptibility, we are measuring expectation values
# of the operator :math:`A` that also defines the parametric part of the
# Hamiltonian. However, this is not necessary and we could compute gradients for
# any other operator using implicit differentiation, as we have access to the
# gradients :math:`\partial_a z^{*}(a)`.
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# ground-state computation. JAX has an implementation of differentiating
```suggestion
# ground-state computation. JAX has an implementation of differentiation
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# the computation through the VQA is more stable.
```suggestion
# Note that we have some points in this plot that are ``nan``, where the gradient
# computation through the eigendecomposition does not work. We will see later that
# the computation through the VQA is more stable.
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# so that is expressive enough to represent the ground-state.
```suggestion
# In PennyLane, we can implement a variational state in different ways, by
# defining a quantum circuit. There are also useful template circuits available, such as
# :class:`~pennylane.SimplifiedTwoDesign`, which implements the :doc:`two-design ansatz <tutorial_unitary_designs>`.
# The ansatz consists of layers of Pauli-Y rotations with
# controlled-Z gates. In each layer there are ``N - 1`` parameters for the Pauli-Y gates.
# Therefore, the ansatz is efficient as long as we have enough layers for it 
# so that is expressive enough to represent the ground-state.
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# how a less expressive ansatz leads to error in the susceptibility computation.
```suggestion
# We set ``n_layers = 5``, but you can redo this example with fewer layers to see
# how a less expressive ansatz leads to error in the susceptibility computation.
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +#   using the parameter-shift rule. However this may be slower.
```suggestion
#   The setting ``shots=None`` makes for the computation of gradients using reverse-mode
#   autodifferentiation (backpropagation). It allows us to just-in-time (JIT)
#   compile the functions that compute expectation values and gradients.
#   In a real device we would use a finite number of shots and the gradients would be computed
#   using the parameter-shift rule. However, this may be slower.
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +    # here, we compute the Hamiltonian coefficients and operations
```suggestion
    # here we compute the Hamiltonian coefficients and operations
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# It all works due to :doc:`PennyLane's integration with JAX <tutorial_jax_transformations>`.
```suggestion
# For the implicit differentiation we will use the tool ``jaxopt``, which implements
# modular implicit differentiation for various cases; e.g., for fixed-point
# functions or optimization. We can directly use ``jaxopt`` to optimize our loss
# function and then compute implicit gradients through it.
# It all works due to :doc:`PennyLane's integration with JAX <tutorial_jax_transformations>`.
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# and JAXOpt to compute the susceptibility.
```suggestion
# The implicit differentiation formulas can even be `implemented manually with JAX <https://jax.readthedocs.io/en/latest/notebooks/Custom_derivative_rules_for_Python_code.html#implicit-function-differentiation-of-iterative-implementations>`__.
# These formulas are implemented in a modular way, using the
# ``jaxopt.GradientDescent`` optimizer with ``implicit_diff=True``.
# We use the seamless integration between PennyLane, JAX
# and JAXOpt to compute the susceptibility.
```

Lots of repetition here from the previous paragraph... removed some.

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# all computes run very fast for any parameters.
```suggestion
# Since everything is written in JAX, simply calling the
# ``jax.grad`` function works as ``jaxopt`` computes the implicit gradients and
# plugs it any computation used by ``jax.grad``. We can also just-in-time (JIT)
# compile all functions although the compilation may take some time as the
# number of spins or variational ansatz becomes more complicated. Once compiled,
# all computes run very fast for any parameters.
```
Lots of repetition again.

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# first call, the function is compiled and therefore subsequent calls become
```suggestion
# first call, the function is compiled and subsequent calls become
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# layers.
```suggestion
# We have shown how a combination of JAX, PennyLane and JAXOpt can be used to
# compute implicit gradients through a VQA. The ability to compute such
# gradients opens up new possibilities, e.g., the design of a Hamiltonian such that
# its ground-state has certain properties. It is also possible to perhaps look
# at this inverse-design of the Hamiltonian as a control problem. Implicit
# differentiation in the classical setting allows defining a new type of
# neural network layer --- implicit layers such as neural ODEs. In a similar
# way, we hope this demo the inspires creation of new architectures for quantum
# neural networks, perhaps a quantum version of neural ODEs or quantum implicit
# layers.
```

2022-11-25 13:52 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# .. include:: ../_static/authors/shahnawaz_ahmed.txt
```suggestion
# .. include:: ../_static/authors/shahnawaz_ahmed.txt
# 
# .. include:: ../_static/authors/juan_felipe_carrasquilla_alvarez.txt
```

Please note that we need to build the bio file for the second author.

2022-11-25 14:40 UTC, co9olguy commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +
I'd prefer (and recommended this to @quantshah) that we start demos with an accessible hook before providing a summary

2022-11-25 14:59 UTC, ikurecic commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +
Then I suggest to take this (edited) paragraph and put it back at the end of (what I'm now calling) the Introduction instead. :)
Would prefer a short-and-sweet lede, as well.

2022-11-25 15:41 UTC, quantshah commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +and re-arrange the terms to obtain :math:`dy/dx`.
There are some factual differences between the edited text so I will edit it manually and commit, E.g., the intellectual superiority of not just the method but Fermat himself was legitimised here. Similarly the tangent was found *at* the vertex. Thanks for the great edits @ikurecic. The text reads much better :-)

2022-11-25 15:50 UTC, quantshah commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +"Talk is cheap. Show me the code." - Linus Torvalds
Done.

2022-11-25 15:52 UTC, quantshah commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# Defining the Hamiltonian and measurement operator
I did not understand. Do you mean I should use the same heading for the later parts?

2022-11-25 16:03 UTC, quantshah commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# Defining the Hamiltonian and measurement operator
I tried it now, let us see how it renders.

2022-11-25 16:11 UTC, quantshah commented
Thank you @KetpuntoG and @ikurecic for the edits. I have incorporated everything except those that require some input from @KetpuntoG. Feel free to edit and merge it as you see fit.

2022-11-25 19:52 UTC, co9olguy approved these changes

2022-11-25 20:24 UTC, ikurecic commented
The following still needs to be done:

- bio of the second author
- lede
- fixing the (newly changed) title/subtitle relations

2022-11-28 14:15 UTC, quantshah commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# .. include:: ../_static/authors/shahnawaz_ahmed.txt
@KetpuntoG

2022-11-28 14:27 UTC, KetpuntoG commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# .. include:: ../_static/authors/juan_felipe_carrasquilla_alvarez.txt
I can do it now

2022-11-28 14:35 UTC, quantshah commented on demonstrations/tutorial_implicit_diff_susceptibility.py
> +# .. include:: ../_static/authors/juan_felipe_carrasquilla_alvarez.txt
I added it now.

2022-11-28 15:43 UTC, quantshah commented
I guess this is ready for merge?

2022-11-28 16:49 UTC, merged