[WIP] demo -> qutrits BernsteinVazirani
PennyLaneAI/qml pull request #653
Opened 2022-11-28 20:19 UTC by KetpuntoG

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Add a thumbnail link to your tutorial in `beginner.rst`, or if a
      QML implementation, in `implementations.rst`.

- [ ] All QML tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2023-02-04 01:27 UTC, CatalinaAlbornoz reviewed
Great demo Guille! I left a couple of comments and would love to check it again when you have addressed them. I also didn't run the code but will do next time. Finally, in your bio "University" should have a capital U

2023-02-04 01:27 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +# Great! Everything works as expected, we have just successfully executed the Berstein-vazerani algorithm.
```suggestion
# Great! Everything works as expected, we have just successfully executed the Bernstein-Vazirani algorithm.
```

2023-02-04 01:27 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +# It is important to note that, as we have defined our device, we are only using a shot to find this value!
```suggestion
# It is important to note that, because of how we defined our device, we are only using a single shot to find this value!
```

2023-02-04 01:27 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +# To do this, we must use qutrit operators, and in particular we will use that :class:`~.pennylane.TShift` is the equivalent gate to :class:`~.pennylane.PauliX` for qubits. It has this property:
```suggestion
# To do this we must use qutrit operators. In particular, we will use the :class:`~.pennylane.TShift` which is equivalent to the :class:`~.pennylane.PauliX` gate for qubits. It has the following property:
```

2023-02-04 01:27 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +    # We apply our function
```suggestion
    # We apply our oracle
```

2023-02-04 01:27 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +    # We apply our function
```suggestion
    # We apply our oracle
```

2023-02-04 01:27 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +    # We apply our function
```suggestion
    # We apply our oracle
```

2023-02-04 01:27 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +    # We measure the last qubit
```suggestion
    # We measure the last qutrit
```

2023-02-04 01:27 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +    # We measure the last qubit
```suggestion
    # We measure the last qutrit
```

2023-02-04 01:27 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +    # We measure the last qubit
```suggestion
    # We measure the last qutrit
```

2023-02-04 01:27 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +print(f"El valor de a es [{a0},{a1},{a2}]")
```suggestion
print(f"The value for a is [{a0},{a1},{a2}]")
```

2023-02-04 01:27 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +# The question is, can we perform the same procedure as we have done before to find :math:`\vec{a}` in one shot? I mean, there exists for qutrits the :class:`~.pennylane.THadamard` gate, we could try
```suggestion
# The question is, can we perform the same procedure as we have done before to find :math:`\vec{a}` using a single shot? The :class:`~.pennylane.THadamard` gate exists for qutrits, we could try to simply substitute and see what happens!
```

2023-02-04 01:27 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +    # We run the Hadamard, the operator and the Hadamard again.
```suggestion
    # We run the THadamard
```

2023-02-04 01:27 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +
```suggestion

# We run the oracle
```

2023-02-04 01:27 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +
```suggestion

# We run the THadamard again
```

2023-02-04 01:27 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +    # We measure in the first 3 qubits
```suggestion
    # We measure the first 3 qutrits
```

2023-02-04 01:27 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +# Awesome! The Berstein-Vazerani algorithm generalizes perfectly to qutrits! Let's do the mathematical development again to see that it does indeed make sense!
```suggestion
# Awesome! The Bernstein-Vazirani algorithm generalizes perfectly to qutrits! Let's do the mathematical calculations again to check that it does indeed make sense!
```

2023-02-04 01:27 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +#   In this case we are disregarding the global phase of -i for simplicity.
```suggestion
#   In this case, we are disregarding the global phase of -i for simplicity.
```

2023-02-04 01:27 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +# - As before, the input of our circuit has been :math:`|0001\rangle`.
```suggestion
# - As before, the input of our circuit is :math:`|0001\rangle`.
```

2023-02-04 01:27 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +# - After this, we can enter the coefficient in the left-hand term and, as before, disregard the last qubit since we are not going to use it again
```suggestion
# - After this, we can enter the coefficient in the left-hand term and, as before, disregard the last qutrit since we are not going to use it again
```

2023-02-04 01:27 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +# - After this, we can enter the coefficient in the left-hand term and, as before, disregard the last qubit since we are not going to use it again
Again, which left-hand term?

2023-02-04 01:27 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +# - Finally, we re-apply the THadamard
In all of these steps you have mentioned Hadamard instead of THadamard. Which one is it? Should you maybe change the notation to make it clear that it's the THadamard? How is it done in the literature?

2023-02-04 01:27 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +# In this demo we have practiced the use of basic qutrit gates such as `TShift` or `THadamard` throughout the Berstein-Vazerani algorithm. In this case the generalization has been straightforward and
```suggestion
# In this demo, we have practised the use of basic qutrit gates such as TShift or THadamard throughout the Bernstein-Vazirani algorithm. In this case, the generalization has been straightforward and we have found that it makes mathematical sense, but we cannot always substitute qubit gates for qutrit gates as we have seen in the demo. To give an easy example of this, we know the property that :math:`X = HZH`, but it turns out that this property does not generalize! The general property is :math:`X = H^{\dagger}ZH`. In the case of qubits it holds that :math:`H = H^{\dagger}` but in other dimensions it does not. I invite you to continue practising with other types of algorithms, for instance, will the Deutsch-Jozsa algorithm generalize well? Take a pen and paper and check it out!
```

2023-03-06 00:26 UTC, glassnotes submitted a review, later dismissed
@KetpuntoG it's so great to see the qutrit functionality being used "in the wild"! I also didn't realize that the BV generalized so easily :tada: 

Most comments relate to formatting to improve clarity. In general, there are some parts that are a bit wordy and there is a fair amount of repetition in the code comments that can be removed. My only major recommendation would be to add a bit expository information about qutrits, both at the outset, as well as when the gates are introduced. It is likely that many readers will be unfamiliar with them, so taking some time to explain trits, qutrits, and the generalizations of gates, will help make it more accessible.

BTW: I have not checked in detail all the mathematical expressions, but I didn't see any glaring issues.

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +   Oracle definition.
Clarify in the caption what function the oracle is implementing.

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +In general, :math:`U_f` sends the basic state :math:`|\vec{x} \rangle |y\rangle` into the state :math:`| \vec{x} \rangle |y + \vec{a} \cdot \vec{x} \pmod{2} \rangle`.
```suggestion
In general, :math:`U_f` sends the state :math:`|\vec{x} \rangle |y\rangle` to the state :math:`| \vec{x} \rangle |y + \vec{a} \cdot \vec{x} \pmod{2} \rangle`.

```

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +Suppose, for example, that :math:`\vec{a}=[0,1,0]`. Then :math:`U_f|1110\rangle = |1111\rangle`, since we are evaluating :math:`f` at the point :math:`\vec{x} = [1,1,1]`. The scalar product between t
For consistency with the previous sentence (and clarify), maybe separate out the last qubit into its own ket as well?

```suggestion
Suppose, for example, that :math:`\vec{a}=[0,1,0]`. Then :math:`U_f|1110\rangle = |1111\rangle`, since we are evaluating :math:`f` at the point :math:`\vec{x} = [1,1,1]`. The scalar product between the two values is :math:`1`, so the last qubit of the output will take the value :math:`1`. 

The Bernstein-Vazirani algorithm makes use of this oracle according to the following circuit:

```

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +  .. math::
What about separating out this derivation into its own little box? (Is it possible to do collapsible boxes?) The explanation is quite long and detracts a bit from the explanation of the structure of the algorithm.

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +- First, the input to our circuit is :math:`|0001\rangle`.
As the explanations in most of the bullet points are quite detailed, recommend just making this normal paragraphs for visual clarity.

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +  This expression may seem complicated to obtain but understanding the case of one qubit, we would have to multiply and group. It is simply to realize that :math:`H|x\rangle = \frac{|0\rangle+(-1)^x
```suggestion
  This expression may seem complicated but understanding the case of one qubit, we would have to multiply and group. It is simply to realize that :math:`H|x\rangle = \frac{|0\rangle+(-1)^x |1\rangle}{\sqrt{2}}` where :math:`x \in \{0, 1\}`.

```

In the last ket, maybe use a different letter than x, just to distinguish between the bit string \vec{x} and a single bit x. 

Also, the expression "the case of one qubit, we would have to multiply and group" is a little unclear.

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +  As you can see, we have separated the first three qubits from the fourth for simplicity.
```suggestion
  As you can see, we have separated the first three qubits from the fourth for clarity.

```

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +    qml.CNOT(wires = [2,3])
```suggestion
    qml.CNOT(wires=[1, 3])
    qml.CNOT(wires=[2 ,3])

```
Recommend to run all the code through black for consistent formatting.

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +    # Circuit used to derive a0
```suggestion
    """Circuit used to derive a0"""

```

(For the first comment in all circuits)

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +    # We apply our oracle
```suggestion
    # Apply our oracle

```

For brevity can remove "we" from all comments

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +print(f"El valor de a es {a}")
```suggestion
print(f"The value of a is {a}")

```
:es: :smile:

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +# Great! Everything works as expected, we have just successfully executed the Bernstein-Vazirani algorithm.
```suggestion
# Great! Everything works as expected, and we have successfully executed the Bernstein-Vazirani algorithm.

```

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +# Now things get more interesting, let's imagine that our basic unit of information is now not the qubit but the qutrit.
```suggestion
# Now things get more interesting: let's imagine that our basic unit of information is not the qubit, but rather the qutrit.

```

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +# To do this we must use qutrit operators. In particular, we will use the :class:`~.pennylane.TShift` which is equivalent to the :class:`~.pennylane.PauliX` gate for qubits. It has the following prop
Spend a little more time explaining the qutrit operations before jumping into the code. For example, explain that we need things that are analogous to X and CNOTs, and that these are generalized to TShift and TAdd, and that we are shifting from addition modulo 2 to addition modulo 3. Since TAdd is also used in the code below it would be good to explain it here.

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +dev = qml.device("default.qutrit", wires = 4, shots = 1)
```suggestion
dev = qml.device("default.qutrit", wires=4, shots=1)

```

Reformat the code blocks here as well

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +    # We apply our oracle
Since this (and the next) circuit are pretty much the same as the first, recommend to remove the comments that indicate application of oracle and measurement.

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +    # We apply our oracle
Same suggestion as above re. removing the comments from subsequent definitions of the same kind of circuit.

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +a2 = circuit2()
```suggestion
# Run to obtain the three trits of a
a0 = circuit0()
a1 = circuit1()
a2 = circuit2()

```

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +# The question is, can we perform the same procedure as we have done before to find :math:`\vec{a}` using a single shot? The Hadamard gate exists for qutrits (also denoted as :class:`~.pennylane.THad
```suggestion
# The question is, can we perform the same procedure as we have done before to find :math:`\vec{a}` using a single shot? The Hadamard gate also generalizes to qutrits (also denoted as :class:`~.pennylane.THadamard`), so we could try to simply substitute it and see what happens!

```

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +# Awesome! The Bernstein-Vazirani algorithm generalizes perfectly to qutrits! Let's do the mathematical calculations again to check that it does indeed make sense!
```suggestion
# Awesome! The Bernstein-Vazirani algorithm generalizes perfectly to qutrits! Let's do the mathematical calculations again to check that it does indeed make sense.

```

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +# - As before, the input of our circuit is :math:`|0001\rangle`.
Same comment as above, re. turning this into paragraphs for clarity.

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +#   Therefore, applying it to the state :math:`|0001\rangle`, we obtain the state
```suggestion
#   Applying this to the state :math:`|0001\rangle`, we obtain

```

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +#         |\phi_1\rangle:=H^4|0001\rangle = H^3|000\rangle\otimes H|1\rangle = \frac{1}{\sqrt{3^3}}\left(\sum_{z \in \{0,1,2\}^3}|\vec{z}\rangle\frac{|0\rangle+w|1\rangle+w^2|2\rangle}{\sqrt{3}}\righ
```suggestion
#         |\phi_1\rangle:=H^{\otimes 4}|0001\rangle = H^{\otimes 3}|000\rangle\otimes H|1\rangle = \frac{1}{\sqrt{3^3}}\left(\sum_{z \in \{0,1,2\}^3}|\vec{z}\rangle\frac{|0\rangle+w|1\rangle+w^2|2\rangle}{\sqrt{3}}\right).

```

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +#            H^n|\vec{x}\rangle = \frac{1}{\sqrt{3^n}}\sum_{\vec{z} \in \{0,1,2\}^n}w^{\vec{x}\cdot\vec{z}}|\vec{z}\rangle.
```suggestion
#            H^{\otimes n}|\vec{x}\rangle = \frac{1}{\sqrt{3^n}}\sum_{\vec{z} \in \{0,1,2\}^n}w^{\vec{x}\cdot\vec{z}}|\vec{z}\rangle.

```

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +        |\phi_3\rangle := H^3|\phi_2\rangle = \frac{1}{2^3}\sum_{\vec{z} \in \{0,1\}^3}(-1)^{\vec{a}\cdot\vec{z}}\left(\sum_{\vec{y} \in \{0,1\}^3}(-1)^{\vec{z}\cdot\vec{y}}|\vec{y}\rangle\right).
```suggestion
        |\phi_3\rangle := H^{\otimes 3}|\phi_2\rangle = \frac{1}{2^3}\sum_{\vec{z} \in \{0,1\}^3}(-1)^{\vec{a}\cdot\vec{z}}\left(\sum_{\vec{y} \in \{0,1\}^3}(-1)^{\vec{z}\cdot\vec{y}}|\vec{y}\rangle\right).

```

Please check all instances of this to ensure the tensor product is included in the definitions (otherwise it reads as just applying the Hadamard multiple times!)

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +#           |\phi_3\rangle := H^3|\phi_2\rangle = \frac{1}{3^3}\sum_{\vec{z} \in \{0,1,2\}^3}w^{-\vec{a}\cdot\vec{z}}\left(\sum_{\vec{y} \in \{0,1,2\}^3}w^{\vec{z}\cdot\vec{y}}|\vec{y}\rangle\right).
```suggestion
#           |\phi_3\rangle := H^{\otimes 3}|\phi_2\rangle = \frac{1}{3^3}\sum_{\vec{z} \in \{0,1,2\}^3}w^{-\vec{a}\cdot\vec{z}}\left(\sum_{\vec{y} \in \{0,1,2\}^3}w^{\vec{z}\cdot\vec{y}}|\vec{y}\rangle\right).

```

2023-03-06 00:26 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +# In this demo, we have practised the use of basic qutrit gates such as TShift or THadamard throughout the Bernstein-Vazirani algorithm. In this case, the generalization has been straightforward and
```suggestion
# In this demo, we have practised the use of basic qutrit gates such as TShift or THadamard throughout the Bernstein-Vazirani algorithm. In this case, the generalization has been straightforward and we have found that it makes mathematical sense, but we cannot always substitute qubit gates for qutrit gates as we have seen in the demo. To give an easy example of this, we know the property that :math:`X = HZH`, but it turns out that this property does not generalize! The general property is :math:`X = H^{\dagger}ZH`. In the case of qubits it holds that :math:`H = H^{\dagger}` but in other dimensions it does not. I invite you to continue practising with other types of algorithms. For instance, will the Deutsch-Jozsa algorithm generalize well? Take a pen and paper and check it out!

```

Include a link to the DJ algorithm?

2023-03-06 00:27 UTC, glassnotes commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +#   \text{THadamard}=\frac{-i}{\sqrt{3}}\begin{pmatrix}
Maybe worth mentioning why the phase is here? Is it needed? (And is it included in the implementation of `THadamard`?)

2023-03-18 20:41 UTC, KetpuntoG commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +One of the best-known quantum gates is the Toffoli gate. It is an operator that we use all the time but surprisingly it is not implemented natively in hardware. To build it, we will have to decompose
Hmm I think it will be misleading to put the image because it is not exactly 3 cnots, they are slightly different operators that in fact do not match TAdd (at least the definition I worked with)
<img width="503" alt="Captura de pantalla 2023-03-18 a las 16 35 45" src="https://user-images.githubusercontent.com/65235481/226137375-b25f3885-f733-489d-9865-f8d37f0b5b98.png">

The control quirt says when exactly to activate de target

2023-03-18 21:09 UTC, KetpuntoG commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +- First, the input to our circuit is :math:`|0001\rangle`.
I have removed the explanation as I also find it distracting 👌

2023-03-24 17:05 UTC, ikurecic commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +
```suggestion
```

2023-03-24 17:05 UTC, ikurecic commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +#   \text{THadamard}=\frac{-i}{\sqrt{3}}\begin{pmatrix}
Agreed here. :)

2023-03-24 17:06 UTC, ikurecic commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +# We will then use the Hadamard definition in qutrits:
```suggestion
# We will then use the Hadamard definition applied to qutrits:
```

2023-03-24 17:07 UTC, ikurecic commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +# In this case, we are disregarding the global phase of -i for simplicity.
```suggestion
# In this case, we are disregarding the global phase of :math:`-i` for simplicity.
```

2023-03-24 17:07 UTC, ikurecic commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +#       |\phi_1\rangle:=H^{\otimes 4}|0001\rangle = H^{\otimes 3}|000\rangle\otimes H|1\rangle = \frac{1}{\sqrt{3^3}}\left(\sum_{z \in \{0,1,2\}^3}|\vec{z}\rangle\frac{|0\rangle+w|1\rangle+w^2|2\rang
```suggestion
#       |\phi_1\rangle=H^{\otimes 4}|0001\rangle = H^{\otimes 3}|000\rangle\otimes H|1\rangle = \frac{1}{\sqrt{3^3}}\left(\sum_{z \in \{0,1,2\}^3}|\vec{z}\rangle\frac{|0\rangle+w|1\rangle+w^2|2\rangle}{\sqrt{3}}\right).
```

2023-03-24 17:07 UTC, ikurecic commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +#       |\phi_2\rangle:= U_f |\phi_1\rangle = \frac{1}{\sqrt{3^3}}\left(\sum_{\vec{z} \in \{0,1,2\}^3}|\vec{z}\rangle\frac{|0 + \vec{a}\cdot\vec{z} \pmod 3 \rangle+w|1+ \vec{a}\cdot\vec{z} \pmod 3 \r
```suggestion
#       |\phi_2\rangle= U_f |\phi_1\rangle = \frac{1}{\sqrt{3^3}}\left(\sum_{\vec{z} \in \{0,1,2\}^3}|\vec{z}\rangle\frac{|0 + \vec{a}\cdot\vec{z} \pmod 3 \rangle+w|1+ \vec{a}\cdot\vec{z} \pmod 3 \rangle+w^2|2+ \vec{a}\cdot\vec{z} \pmod 3 \rangle}{\sqrt{3}}\right).
```

2023-03-24 17:08 UTC, ikurecic commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +# After this, we can enter the coefficient in the :math:`|\vec{z}\rangle` term and, as before, disregard the last qutrit since we are not going to use it again
```suggestion
# After this, we can enter the coefficient in the :math:`|\vec{z}\rangle` term and, as before, disregard the last qutrit, since we are not going to use it again:
```

2023-03-24 17:08 UTC, ikurecic commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +# Finally, we re-apply the THadamard:
```suggestion
# Finally, we reapply the THadamard:
```

2023-03-24 17:09 UTC, ikurecic commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +# Rearranging this expression we obtain that
```suggestion
# Rearranging this expression, we obtain:
```

2023-03-24 17:11 UTC, ikurecic commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +# In this demo, we have practised the use of basic qutrit gates such as TShift or THadamard throughout the Bernstein-Vazirani algorithm. In this case, the generalization has been straightforward and
```suggestion
# In this demo, we have practised the use of basic qutrit gates such as TShift or THadamard by applying the Bernstein–Vazirani algorithm. In this case, the generalization has been straightforward and we have found that it makes mathematical sense, but we cannot always substitute qubit gates for qutrit gates as we have seen in the demo. To give an easy example of this, we know the property that :math:`X = HZH`, but it turns out that this property does not generalize! The general property is actually :math:`X = H^{\dagger}ZH`. In the case of qubits it holds that :math:`H = H^{\dagger}`, but in other dimensions it does not. I invite you to continue practising with other types of algorithms. For instance, will the `Deutsch–Jozsa algorithm <https://en.wikipedia.org/wiki/Deutsch–Jozsa_algorithm>`__ generalize well? Take a pen and paper and check it out!
```

2023-03-24 17:12 UTC, ikurecic commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +# In this demo, we have practised the use of basic qutrit gates such as TShift or THadamard throughout the Bernstein-Vazirani algorithm. In this case, the generalization has been straightforward and
The "we can't generalize from qubits to qutrits" should appear somewhere in the "main body" of the demo, too. 🤔 Then you can just repeat/summarize it here in the conclusion. What do you think?

2023-03-24 17:14 UTC, ikurecic requested changes
It's short and sweet and I like it a lot, great job! :) 
I left some language suggestions and a few comments for things that you might want to change up before publishing.

2023-04-10 14:28 UTC, KetpuntoG commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +#   \text{THadamard}=\frac{-i}{\sqrt{3}}\begin{pmatrix}
I really don't know why it is there 🤔 In fact I later say that we ignore this global phase because it does not intervene in the reasoning

2023-04-10 14:28 UTC, KetpuntoG commented on demonstrations/tutorial_qutrits_bernstein_vazirani.py
> +    :property="og:image": https://pennylane.ai/qml/_images/oracle_qutrit.jpg
Yep, I'll have it this week

2023-05-08 11:42 UTC, ikurecic approved these changes
LGTM

2023-05-08 11:45 UTC, merged