[Draft] ZX calculus demo
PennyLaneAI/qml pull request #664
Opened 2022-12-13 21:56 UTC by rmoyard

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Add a thumbnail link to your tutorial in `beginner.rst`, or if a
      QML implementation, in `implementations.rst`.

- [ ] All QML tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2022-12-15 10:06 UTC, RDPEast commented on demonstrations/tutorial_zx_calculus.py
> +The ZX calculus is a graphical language that can represent any linear maps. Therefore it can be used to reason
Should be linear 'map' rather than 'maps'.

2022-12-15 10:06 UTC, RDPEast commented on demonstrations/tutorial_zx_calculus.py
> +quantum computations and quantum circuits. Its foundations are based on category theory, which makes it a rigorous
I think it should be 'reason about'

2022-12-15 10:06 UTC, RDPEast commented on demonstrations/tutorial_zx_calculus.py
> +considered as a generalization of the circuit representation of quantum computations.
I think it should be 'any linear map'

2023-03-13 21:10 UTC, rmoyard commented
So the intro is short and sweet which is always nice but it might be nice to talk about the why of ZX calculus, why do people care? Where did it come from? Similarly with the reference to category theory, you are right that it offers formal guarantees of correctness but it feels a smidge off hand to just say it's based on category theory so it's rigorous.
From @RDPEast:

The presentation of the meat of the calculus is pretty good overall and it's clear you have the gist of it. There are some second order corrections to be made though. Ultimately I think the way this tutorial should proceed is based on 'whys'. So when we start we say okay we want a complete language for quantum information, that we can use to do rewrites etc. Okay so we need these diagrams with these rules. Now you have separated off all of the H-box stuff from ZX which is very slightly wrong, in ZX you need the 2 wire H box, so where you write from example 'How to transform an Z spider to a X spider. in the ZXH section this is actually ZX.

You bring up ZXH via a 'why' when you say "The universality of the ZX-calculus does not guarantee to have a simple representation of any linear map. For example, The Toffoli gate (quantum AND gate) has no simple way of being represented, as a ZX-diagram it contains around 25 spiders. Therefore, another generator is introduced: the H-box. It allows for a simple representation of the AND gate." - this is perfect. Maybe just a diagram rewrite of showing how it works is needed, this is also an excuse to say adding a new element (i.e the multi leg H box) means new rules are added to integrate it into the language - the pi explosion and absorption rules are the only ones you need to show the CCnot at work.

This actually raises a point about the ZX section, doing the example of the cnot acting on basis states here  would probably clarify how you work with the calculus to calculate things. At the moment you show the rules but don't show how they let you derive things in an example

Nice teleport example, only comment is that you only need ZX for this as there are not non-2 leg H boxes. For the ZXH section perhaps another motivating point to keep this in is that, PYZX already does it, though in a dodgy way (it's only really optimised for ZX).

Graph simplification looks good for now, looking forward to seeing the final thing with the plots showing.

Parameter shift rule derivation is nice, I think it's important to note that we care moving beyond normal ZX stuff here and saying something like the 'why' of the situation is that it is desirable theoretically, to do calculus, and practically, for QML etc, to be able to take derivatives of systems. Then you show how this actually comes out quite nicely in ZX and how it has been used in the literature. You should probably note that these aren't features in pyzx and we are moving to analytic theory here to show off what might come in the future.

2023-03-20 19:01 UTC, branedrane commented on demonstrations/tutorial_zx_calculus.py
> +AND gate.
```suggestion
The universality of the ZX calculus does not guarantee the existence of a simple representation, even for simple linear maps. For example, the Toffoli gate (quantum AND gate) requires around 25
spiders! This motivates the introduction of a new generator: the multi-leg H-box, defined as follows:
```

2023-03-20 19:03 UTC, branedrane commented on demonstrations/tutorial_zx_calculus.py
> +which is \ :math:`a`.
```suggestion
The parameter :math:`a` can be any complex number, and the sum  is over all :math:`i1, ... , im, j1, ... , jn \in {0,
1}`, therefore an H-box represents a matrix where all entries are equal to :math:`1`, except for the bottom right element,
which is \ :math:`a`.
This will allow us to concisely express the Toffoli gate, as we will see shortly.
```

2023-03-20 19:05 UTC, branedrane commented on demonstrations/tutorial_zx_calculus.py
> +simplicity it is often replaced by a blue edge.
```suggestion
An H-box with one input wire and one output wire, with :math:`a=-1`, is a Hadamard gate up to global phase. Thus, we omit the parameter when it is equal to :math:`-1`. The Hadamard gate is sometimes represented by a blue edge rather than a box.
```

2023-03-20 19:06 UTC, branedrane commented on demonstrations/tutorial_zx_calculus.py
> +simple Hadamard gate and one three-ary H-box).
```suggestion
Thanks to the introduction of the multi-leg H-box, the Toffoli gate can be represented with three Z spiders and three H-boxes — two
simple Hadamard gates and one three-ary H-box — as shown below:
```

2023-03-20 19:06 UTC, branedrane commented on demonstrations/tutorial_zx_calculus.py
> +[#East2021].
```suggestion
The ZXH-calculus contains a new set of rewriting rules. You can find details in the literature
[#East2021]_.
```

2023-03-20 19:07 UTC, branedrane commented on demonstrations/tutorial_zx_calculus.py
> +Now that we have introduced the ZXH-calculus, let's dive into the coding part and show what you can do with PennyLane.
```suggestion
Now that we have introduced the formalism of the ZXH calculus, let's dive into some code and show what you can do with PennyLane!
```

2023-03-20 19:09 UTC, branedrane commented on demonstrations/tutorial_zx_calculus.py
> +back to PennyLane.
```suggestion
PennyLane release 0.28.0 added ZX calculus functionality to the language. You can use the `to_zx` transform decorator to get a ZXH-diagram from a PennyLane QNode, and also the `from_zx` to transform a
ZX-diagram to a PennyLane tape.  We are using the PyZX library [#PyZX]_ under the hood to represent the ZX diagram. Once your circuit is a PyZX graph, you can draw it, apply some optimization, extract the underlying circuit and go
back to PennyLane.
```

2023-03-20 19:11 UTC, branedrane commented on demonstrations/tutorial_zx_calculus.py
> +PyZX diagram.
```suggestion
PyZX diagram:
```

2023-03-20 19:12 UTC, branedrane commented on demonstrations/tutorial_zx_calculus.py
> +# figure and therefore you can save it locally with `savefig` function, or simply show it locally.
Weird, `savefig` is displaying in italics rather than teletype...?

2023-03-20 19:14 UTC, branedrane commented on demonstrations/tutorial_zx_calculus.py
> +# circuit generator, get the corresponding ZX diagram and transform it to PennyLane QNode.
```suggestion
# You can also take a ZX-diagram in PyZX, convert it into a PennyLane tape and use it in your QNode. Invoking the PyZX circuit generator:
```

2023-03-20 19:15 UTC, branedrane commented on demonstrations/tutorial_zx_calculus.py
> +# functionality will be very useful for circuit optimization which is our next topic.
```suggestion
# We get a tape corresponding to the randomly generated circuit which we can use it in any QNode. This
# functionality will be very useful for our next topic: circuit optimization.
```

2023-03-20 19:24 UTC, branedrane commented on demonstrations/tutorial_zx_calculus.py
> +ZXH-diagrams
I understand that, for completeness, it's nice to have this section, but as far as I can tell it isn't used subsequently. Since the rewriting rules aren't presented, I wonder if it can be omitted?

2023-03-20 19:32 UTC, branedrane commented on demonstrations/tutorial_zx_calculus.py
> +# can be better understood by the following diagram.
```suggestion
# The ZX calculus is more general and more flexible than the usual circuit representation.
# We can therefore represent circuits with ZX-diagrams and apply rewriting rules to simplify, like we did for teleportation. But not every ZX-diagram has a corresponding circuit. To get back to circuits, a method called circuit extraction is needed. For a rigorous introduction to this active and promising field of application, see [#Duncan2017]_. 
# The basic idea is captured below:
```

2023-03-20 19:34 UTC, branedrane commented on demonstrations/tutorial_zx_calculus.py
> +# From the definition introduced by [#Duncan2017]_ , a ZX-diagram is graph-like if
```suggestion
# To simplify ZX-diagrams, we can not only use the rewriting rules defined previously, but additional graph-theoretic transformations called local complementation and pivoting.
# These are special transformations that can only be applied to "graph-like" ZX-diagrams.
# As defined in [#Duncan2017]_ , a ZX-diagram is graph-like if
```

2023-03-20 19:35 UTC, branedrane commented on demonstrations/tutorial_zx_calculus.py
> +# then possible to use graph-theoretic tools on all ZX-diagrams after transformation.
```suggestion
# phaseless spiders. Furthermore, it was proved that every ZX-diagram is equal to a graph-like ZX-diagram. Thus, after conversion into graph-like form, we can use graph-theoretic tools on all ZX-diagrams.
```

2023-03-20 19:39 UTC, branedrane commented on demonstrations/tutorial_zx_calculus.py
> +# graph-like diagram that has the following properties:
```suggestion
# The basic idea is [#Duncan2017]_ is to use the graph-theoretic transformations to
# get rid of as many interior spiders as possible. Interior spiders are the one without inputs or outputs connected to
# them.
# To this end, Theorem 5.4 [#Duncan2017]_ provides an algorithm which takes a graph-like diagram and performs the following:
```

2023-03-20 19:42 UTC, branedrane commented on demonstrations/tutorial_zx_calculus.py
> +# n^3)`. Let's create an example with a the circuit mod 5 4:
What is this mysterious circuit? Perhaps draw attention to the naming more explicitly so the user doesn't feel they are supposed to know why it is called this, e.g.

```suggestion
# n^3)`. Let's create an example with the circuit `mod_5_4`:
```

2023-03-20 19:44 UTC, branedrane commented on demonstrations/tutorial_zx_calculus.py
> +# up with a graph like ZX-diagram that does not represent a quantum circuit.
```suggestion
# We see that after applying the procedure we end up with only 16 interior Z-spiders and 5 boundary spiders. We also see
# that all non-Clifford phases appear on the interior spiders. The simplification procedure was successful, but we have a graph-like ZX-diagram with no quantum circuit equivalent. We need to extract a circuit!
```

2023-03-20 19:46 UTC, branedrane commented on demonstrations/tutorial_zx_calculus.py
> +# procedure giving the extraction of Clifford circuits with in eight layers and only one CNOT layer.
What is local Clifford form? I guess local Clifford gates?

```suggestion
# The extraction of circuits is a highly non-trivial task and can be a #P-hard problem [#Beaudrap2021]_. There are two
# different algorithms introduced in the same paper. First, for Clifford circuits, the procedure will erase all
# interior spiders, and therefore the diagram is left in a graph-state from which a Clifford circuit can be extracted, using a total of eight layers with only one layer of CNOTs.
```

2023-03-20 19:49 UTC, branedrane commented on demonstrations/tutorial_zx_calculus.py
> +# resynthesize techniques. The extraction procedure is implement in PyZX as the function `pyzx.circuit.extrac_circuit`.
```suggestion
# For non-Clifford circuits the problem is more complex, because we are left with non-Clifford interior spiders.
# From the diagram produced by the simplification procedure, the extraction progresses through the diagram from
# right-to-left, consuming on the left and adding gates on the right. It produces better results than other cut and
# resynthesize techniques. The extraction procedure is implement in PyZX as the function `pyzx.circuit.extrac_circuit`. We can apply this procedure to the example `mod_5_4` above:
```

2023-03-20 19:50 UTC, branedrane commented on demonstrations/tutorial_zx_calculus.py
> +# results [#Kissinger2021]_ .
```suggestion
# A concrete application of these ZX optimization techniques is the reduction of the expensive, non-Clifford T count of a quantum
# circuit. Indeed, T-count optimization is an area where ZX-calculus has very good
# results [#Kissinger2021]_ .
```

2023-03-20 19:52 UTC, branedrane commented on demonstrations/tutorial_zx_calculus.py
> +# extracted.
```suggestion
# extracted. Let's see how it does:
```

2023-03-20 19:53 UTC, branedrane commented on demonstrations/tutorial_zx_calculus.py
> +# and 1 `qml.PauliX()` and 10 `qml.S()`. We successfully reduced the T-count by 20 and have 10 additional S gates.
```suggestion
# We have reduced the T count! Taking a full census, the circuit contains :math:`53` gates: :math:`8` `qml.T()` gates, :math:`28` `qml.CNOT()`, :math:`6` `qml.Hadmard()`
#, :math:`1` `qml.PauliX()` and :math:`10` `qml.S()`. We successfully reduced the T-count by 20 and have 10 additional S gates.
```

2023-03-20 19:54 UTC, branedrane commented on demonstrations/tutorial_zx_calculus.py
> +# The from_zx() transform can now convert the optimized circuit back into PennyLane operations:
```suggestion
# The `from_zx()` transform converts the optimized circuit back into PennyLane format:
```

2023-03-20 19:56 UTC, branedrane commented on demonstrations/tutorial_zx_calculus.py
> +# Deriving the parameter shift rule
Not sure about this section. See overall comments!

2023-03-21 10:38 UTC, RDPEast reviewed
It's definitely getting more polished, clearly some of the diagrams need sorting a bit and replacing with in-house ones. The last section with the derivatives feels a bit tacked on it would be nice to have this introduced with more motivation as an intersting extension for people to consider.

2023-03-21 10:38 UTC, RDPEast commented on demonstrations/tutorial_zx_calculus.py
> +# for quantum derivatives more specifically for the parameter-shift rule. What is following is not implemented in
```suggestion
# for quantum derivatives more specifically for the parameter-shift rule. What follows is not implemented in
```

2023-03-21 10:38 UTC, RDPEast commented on demonstrations/tutorial_zx_calculus.py
> +# Indeed, not only ZX-calculus is useful for representing and simplifying quantum circuits, but it was shown that we
> @```suggestion # Indeed, not only is ZX-calculus useful for representing and simplifying quantum circuits, but it was shown that we
```

2023-03-21 10:38 UTC, RDPEast commented on demonstrations/tutorial_zx_calculus.py
> +# states and use the fuse rule for the Z-spider. We obtain the parameter shift rule!
```suggestion
# states and use the fuse rule for the Z-spider. We obtain the parameter shift rule!
```
```suggestion
# states and using the fusion rule for the Z-spider. We obtain the parameter shift rule!
```

2023-03-21 10:38 UTC, RDPEast commented on demonstrations/tutorial_zx_calculus.py
> +#
Could probably do with a summary of what has been discussed here.

2023-03-21 18:54 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +The introduction of the yellow box allows us to write the relationship between the X and Z spider as:
Thanks added!

2023-03-21 19:00 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +
I think it is what is done just before and this one is the resulting CNOT. The derivation is done with the matrices as well. What do you think?

2023-03-23 14:08 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +    The (:math:`/pi`)copy rule.
@KetpuntoG I will double check that with you

2023-03-23 14:34 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +In this tutorial, we first give an overview of the building blocks of the ZX calculus, called <i>ZX-diagrams</i>, and
@branedrane What was the goal of <i>...</i> did you want to use italics?

2023-03-23 19:02 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +# phaseless spiders. Furthermore, it was proved that every ZX-diagram is equal to a graph-like ZX-diagram. It makes
Lemma 3.2 https://arxiv.org/pdf/1902.03178.pdf

2023-03-23 19:03 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +The ZXH-calculus contains a new set of rewriting rules, for more details you can find these rules in the literature
I rephrased it, @RDPEast it would be great if you can send me the calculation :+1:

2023-03-23 19:14 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +#
Done!

2023-03-23 19:42 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +ZXH-diagrams
We plan to add the CCNOT derivation, to make it less useless

2023-04-03 15:58 UTC, RDPEast commented on demonstrations/tutorial_zx_calculus.py
> +# phaseless spiders. Furthermore, it was proved that every ZX-diagram is equal to a graph-like ZX-diagram. It makes
Fair enough, so it is

2023-04-12 19:44 UTC, isaacdevlugt requested changes
Really comprehensive! Quite a long demo, but it's a complicated topic that is still new. So, it makes sense that we try and cover as much ground here as possible 🚀 

90% of my comments are grammatical or convention-related. I didn't make a suggestion on every single instance, but I'm sure you'll pick up on instances here and there as you go through the tutorial again 😄

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +Let us convert this quantum circuit into a ZX-diagram. The measurements are represented by the state X-spider
```suggestion
Let us convert this quantum circuit into a ZX-diagram. The measurements are represented by the state X spider
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +between Alice and Bob, and as you might expect from earlier comments about bending wires, is the state
```suggestion
between Alice and Bob. As you might expect from earlier comments about bending wires, their shared state is
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +Choi-Jamiolkowski equivalent to the identity linear map.
```suggestion
Choi-Jamiolkowski-equivalent to the identity linear map.
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +X-spider of the CNOT. We also merge the Hadamard gate with the :math:`b` state, because together it represents a
Conventions are changing here for X-spider (X spider). Similar to "X-gate" versus "X gate"

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +Z-spider. Then we can fuse the three Z-spiders by simply adding their phases. After that we see that the Z-spider
```suggestion
Z-spider. Then we can fuse the three Z-spiders by simply adding their phases. After that, we see that the Z-spider
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +phase vanishes modulo of :math:`2\pi` and can therefore be simplified using the identity rules. Then we can fuse the
```suggestion
phase vanishes (modulo :math:`2\pi`) and can therefore be simplified using the identity rules. Then we can fuse the
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +introduced the Hadamard gate as a yellow box, this motivates the introduction of a new generator: the multi-leg H-box,
```suggestion
introduced the Hadamard gate as a yellow box, and using it here gives a new generator: the multi-leg H-box,
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +introduced the Hadamard gate as a yellow box, this motivates the introduction of a new generator: the multi-leg H-box,
does this make sense?

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +1}`, therefore an H-box represents a matrix where all entries are equal to :math:`1`, except for the bottom right
```suggestion
1}`. Therefore, an H-box represents a matrix where its entries are equal to :math:`1` except for the bottom right
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +An H-box with one input wire and one output wire, with :math:`a=-1`, is an Hadamard gate up to global phase. Thus,
```suggestion
An H-box with one input wire and one output wire, with :math:`a=-1`, is a Hadamard gate up to global phase. Thus,
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +H-boxes — two simple Hadamard gates and one three-ary H-box — as shown below:
```suggestion
H-boxes — two simple Hadamard gates and one ternary H-box — as shown below:
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +The addition of the multi-leg H-box together with an additional set of rewriting rules form the ZXH calculus. You can
```suggestion
The addition of the multi-leg H-box together with an additional set of rewriting rules forms the ZXH calculus. You can
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +find more details and the rewriting rules in the literature [#East2021]_.
```suggestion
find more details in [#East2021]_.
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +X-gate on the target wire, it means that only the state 110 and 111 will not map to themselves (110 to 111 and 111 to
"-" convention

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +110). We will show that if one provides the state 11 on the two first wires, it results by a bit flip on the third wire
```suggestion
110). We will show that if one provides the state 11 on the two first wires, it results to a bit flip on the third wire
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +(X-gate). For that purpose, we need to add a new rewriting rule that is part of the ZXH-calculus, the absorb rule:
```suggestion
(X-gate). For that purpose, we need to add a new rewriting rule that is part of the ZXH-calculus: the absorb rule.
```

Probably a good idea to bold / italicize all rewriting rule names.

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +    The (ab)sorb rule.
Same thing here regarding brackets

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +We start by applying our Toffoli diagram on a 11 state, which corresponds simply to two X-spiders with phase
```suggestion
We start by applying our Toffoli diagram on a 11 state, which corresponds to two X-spiders with a phase of
```

"-" convention as well

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +:math:`\pi` stacked with our diagram. We apply the copy rule on the two groups of  X-spider and Z-spider on the wires 0
Is this right?

```suggestion
:math:`\pi` stacked with our diagram. We apply the copy rule on the two groups of X-spiders and Z-spiders on the wires 0
```

"-" convention also

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +and 1. After that we can apply the newly introduced absorb rule on one of the X-spider connected to the H-Box. Then
```suggestion
and 1. After that we can apply the newly introduced absorb rule on one of the X-spiders connected to the H-Box. Then
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +we recognize the Fourier relation and can replace the X-spider and H-Box by a Z-spider. Then it is easy to apply the
Maybe a good idea to show math here when you reference the Fourier relation

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +fuse rule on the two Z-spiders. Again we recognize the Fourier relation and finally obtain a single X-spider on the
```suggestion
fuse rule on the two Z-spiders. Again we recognize the Fourier relation and, finally, obtain a single X-spider on the
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +target wire. We just proved that the by providing the 11 state on the two control wires, it always applies a X-spider
```suggestion
target wire. We just proved that by providing the 11 state on the two control wires, it always applies an X-spider
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +ZX-calculus for quantum machine learning
```suggestion
The ZX-calculus for quantum machine learning
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +If you do the same procedure with the others states on the two controls (00, 11, 10, 01), with slightly different rules
```suggestion
If you do the same procedure with the others states on the two controls (00, 11, 10, 01) with slightly different rules
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +We now move away from the standard use ZX-calculus, in order to show its utility for calculus and more specifically
```suggestion
We now move away from the standard use ZX-calculus, in order to show its utility for calculus and, more specifically,
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +follows is not implemented in PennyLane or PyZX. By adding derivatives to the framework, it shows that ZX-calculus
```suggestion
follows is not implemented in PennyLane or PyZX. By adding derivatives to the framework, it shows that the ZX-calculus
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +convinced that ZX-calculus can be used to study any kind of quantum related problems.
```suggestion
convinced that the ZX-calculus can be used to study any kind of quantum related problem.
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +Indeed, not only ZX-calculus is useful for representing and simplifying quantum circuits, but it was shown that we
```suggestion
Indeed, not only is the ZX-calculus useful for representing and simplifying quantum circuits, but it was shown that we
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +given a parametrized state can be derived as a ZX-diagram (theorem 2 of Zhao et al. [#Zhao2021]_ ). We will also show
```suggestion
given a parametrized state can be derived as a ZX-diagram (theorem 2 of Zhao et al. [#Zhao2021]_). We will also show
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +:math:`\ket{0}` on all n qubits. Then we apply a parametrized unitary :math:`U` that depends on :math:`\vec{
```suggestion
:math:`\ket{0}` on all :math:`n` qubits. Then we apply a parametrized unitary :math:`U` that depends on :math:`\vec{
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +\theta}=(\theta_1, ..., \theta_m)`, where each angle :math:`\theta_i \in [0, 2\pi]`.
1. ```suggestion

\theta}=(\theta_1, ..., \theta_m)`, where :math:`\teheta_i \in [0, 2\pi]`.
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +Consequently the expectation value of a Hamiltonian :math:`H` is given by:
```suggestion
Consequently, the expectation value of a Hamiltonian :math:`H` is given by:
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +We have seen that any circuit can be translated to a ZX diagram but once again we want to use the graph-like form (see
```suggestion
We have seen that any circuit can be represented by a ZX diagram, but once again, we want to use the graph-like form (see
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +Now we will investigate what is the partial derivative of the diagram of the expectation value. The theorem is
```suggestion
Now we will investigate the partial derivative of the diagram representing the expectation value. The theorem is
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +Let's consider a spider that depends on the angle :math:`\theta_j` that is in the partial derivative. The spider
```suggestion
Let's consider a spider that depends on the angle :math:`\theta_j`. The spider
```

Is this ok?

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +necessarily appears on both sides, but they have opposite sign angle and inverse inputs/outputs. By simply writing
> opposite sign angle

Not sure what this means

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +their definitions and expanding the formula we obtain:
```suggestion
their definitions and expanding the formula, we obtain:
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +The theorem is proved, we just expressed the partial derivative as a ZX-diagram!
```suggestion
The theorem is proved — we just expressed the partial derivative as a ZX-diagram!
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +\ket{-}\bra{-}`, we can then separate the diagram into two parts. By recalling the definition of the plus and minus
```suggestion
\ket{-}\bra{-}`. We can then separate the diagram into two parts by recalling the definition of the :math:`+` and :math:`-`
```

might be better to actually write the kets: |+> and |->

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +    By using theorem 2, we can add a X spider and shift the phases in the Z spiders, then by
```suggestion
    By using theorem 2, we can add an X spider and shift the phases in the Z spiders. Then, by
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +    explicitly decomposing the spider with the plus and minus state, we prove the parameter-shift proof!
```suggestion
    explicitly decomposing the spider with the plus and minus state, we prove the parameter-shift rule!
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +following paper [#Wang2022]_.
```suggestion
You can find more information about the differentiation and integration of ZX-diagrams with QML applications in [#Wang2022]_.
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +a PennyLane tape.  We are using the PyZX library [#PyZX]_ under the hood to represent the ZX diagram. Once your
```suggestion
transform decorator to get a ZX-diagram from a PennyLane QNode, while `from_zx` transforms a ZX-diagram into
a PennyLane tape. We are using the PyZX library [#PyZX]_ under the hood to represent the ZX diagram. Once your
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +circuit is a PyZX graph, you can draw it, apply some optimization, extract the underlying circuit and go back to
```suggestion
circuit is a PyZX graph, you can draw it, apply some optimization, extract the underlying circuit, and go back to
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# Now that you have a ZX-diagram as a PyZx object, you can use all the tools from the library to transform the graph.
```suggestion
# Now that you have a ZX-diagram as a PyZx object, you can use all the tools from the PyZX library to transform the graph.
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# We get a tape corresponding to the randomly generated circuit which we can use it in any QNode. This
```suggestion
# We get a tape corresponding to the randomly generated circuit which we can use in any QNode. This
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# applied to "graph-like" ZX-diagrams. As defined in [#Duncan2017]_ , a ZX-diagram is graph-like if
```suggestion
# applied to "graph-like" ZX-diagrams. As defined in [#Duncan2017]_, a ZX-diagram is graph-like if
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# 4. Every input or output is connected to a Z-spider and every Z-spider is connected to at most one input or output.
```suggestion
# 1. all spiders are Z-spiders.
# 2. Z-spiders are only connected via Hadamard edges.
# 3. there are no parallel Hadamard edges or self-loops.
# 4. every input or output is connected to a Z-spider and every Z-spider is connected to at most one input or output.
```

"-" convention

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# A ZX-diagram is called a graph state if it is graph-like, every spider is connected to an output, and there are no
```suggestion
# A ZX-diagram is called a graph state if it is graph-like: every spider is connected to an output and there are no
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# The basic idea is [#Duncan2017]_ is to use the graph-theoretic transformations to get rid of as many interior
```suggestion
# The basic idea is to use the graph-theoretic transformations to get rid of as many interior
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# Theorem 5.4 [#Duncan2017]_ provides an algorithm which takes a graph-like diagram and performs the following:
```suggestion
# Theorem 5.4 in [#Duncan2017]_ provides an algorithm which takes a graph-like diagram and performs the following:
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# 3. Remove interior Pauli spiders adjacent to a boundary spider.
```suggestion
# 1. removes all interior proper Clifford spiders,
# 2. remove adjacent pairs of interior Pauli spiders,
# 3. remove interior Pauli spiders adjacent to a boundary spider.
```

"Pauli spiders" introduced here. You mean X or Z spiders?

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# :math:`\mathcal{O}(n^3)`. Let's create an example with the circuit `mod_5_4
What is n?

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# <https://github.com/njross/optimizer/blob/master/Arithmetic_and_Toffoli/mod5_4_before>`__. The circuit :math:`63`
🤔

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# We see that after applying the procedure we end up with only 16 interior Z-spiders and 5 boundary spiders. We also
```suggestion
# We see that after applying the procedure, we end up with only 16 interior Z-spiders and 5 boundary spiders. We also
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# The extraction of circuits is a highly non-trivial task and can be a #P-hard problem [#Beaudrap2021]_. There are
Isn't it P#, not #P? Could be wrong 🤔

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# interior spiders, and therefore the diagram is left in a graph-state from which a Clifford circuit can be
```suggestion
# interior spiders, and the diagram is left in a graph-state from which a Clifford circuit can be
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# extracted, using a total of eight layers with only one layer of CNOTs.
```suggestion
# extracted using a total of eight layers with only one layer of CNOTs.
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# For non-Clifford circuits the problem is more complex, because we are left with non-Clifford interior spiders. From
```suggestion
# For non-Clifford circuits, the problem is more complex because we are left with non-Clifford interior spiders. From
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# A concrete application of these ZX optimization techniques is the reduction of the expensive, non-Clifford T count
```suggestion
# A concrete application of these ZX optimization techniques is the reduction of the expensive non-Clifford T count
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# of a quantum circuit. Indeed, T-count optimization is an area where ZX-calculus has very good results [
```suggestion
# of a quantum circuit. Indeed, T-count optimization is an area where the ZX-calculus has shown very good results [
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# in order to transform our circuit to a ZX graph. You can get this PyZX graph by simply calling the QNode:
```suggestion
# in order to transform our circuit to a ZX graph. You can get this PyZX graph by calling the QNode:
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# PyZX gives multiple options for optimizing ZX graphs (`pyzx.full_reduce()`, `pyzx.teleport_reduce()`, …). The
```suggestion
# PyZX gives multiple options for optimizing ZX graphs: `pyzx.full_reduce()` and `pyzx.teleport_reduce()` to name a couple. The
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# `pyzx.teleport_reduce()`, as it preserves the diagram structure. Because of this the circuit does not be to be
```suggestion
# `pyzx.teleport_reduce()`, as it preserves the diagram structure. Because of this, the circuit does not need to be
```

2023-04-12 19:44 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# The `from_zx()` transform converts the optimized circuit back into PennyLane format, and this is possible because we
```suggestion
# The `from_zx()` transform converts the optimized circuit back into PennyLane format, which is made possible because we
```

2023-04-12 19:44 UTC, isaacdevlugt requested changes
Really comprehensive! Quite a long demo, but it's a complicated topic that is still new. So, it makes sense that we try and cover as much ground here as possible 🚀 

90% of my comments are grammatical or convention-related. I didn't make a suggestion on every single instance, but I'm sure you'll pick up on instances here and there as you go through the tutorial again 😄

2023-04-18 16:56 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +The ZX-calculus is a graphical language for reasoning about quantum computations and circuits. It was introduced in
I think that's the usual way of talking about ZX calculus, so I would keep it as it is.

2023-04-18 17:04 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +does not always end up with diagram-like graph, and that circuit extraction is a main pain point of the ZX framework.
No it is correct.

2023-04-18 17:07 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +A simple green node is a Z spider with zero phase and a simple red node is an X spider with zero phase.
Yes thanks!

2023-04-18 17:15 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +    The (f)use rule.
That's how they usually show how to use the rule: `(f) (c)` over an equality means that you used (fu)se and (c)opy

2023-04-18 17:40 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +\theta}=(\theta_1, ..., \theta_m)`, where each angle :math:`\theta_i \in [0, 2\pi]`.
Not sure what you want here? @isaacdevlugt

2023-04-18 17:41 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +Let's consider a spider that depends on the angle :math:`\theta_j` that is in the partial derivative. The spider
I would keep the information.

2023-04-18 17:42 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +necessarily appears on both sides, but they have opposite sign angle and inverse inputs/outputs. By simply writing
phases of opposite signs

2023-04-18 18:07 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +# 3. Remove interior Pauli spiders adjacent to a boundary spider.
I added details about the names :+1:

2023-04-18 18:09 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +# The extraction of circuits is a highly non-trivial task and can be a #P-hard problem [#Beaudrap2021]_. There are
https://arxiv.org/abs/2202.09194

2023-04-18 18:18 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +It is easy to see that the usual Z-gate can be represented with a single-wire Z-gate:
I will not add Pauli expect if we speak about PennyLane

2023-04-18 18:20 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +   verify and details can be found in this paper [#JvdW2020]_ .
I think it is better for accessibility, but maybe I am wrong.

2023-04-18 18:20 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +find more details and the rewriting rules in the literature [#East2021]_.
I think it is better for accessibility, but maybe I am wrong.

2023-04-18 18:20 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +following paper [#Wang2022]_.
I think it is better for accessibility, but maybe I am wrong.

2023-04-20 15:04 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +    Two Z-spiders depending on the j-th angle.
```suggestion
    Two Z-spiders depending on the :math:`j`-th angle.
```

2023-04-20 15:06 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +Let's consider a spider that depends on the angle :math:`\theta_j` that is in the partial derivative. The spider
Maybe this instead:

```suggestion
Let's consider a partial derivative on the spider with respect to :math:`\theta_j`. The spider
```

2023-04-20 15:06 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +This theorem can be used to prove the parameter shift rule. Let's consider the following ansatz that we transform to
```suggestion
This theorem can be used to prove the parameter-shift rule. Let's consider the following ansatz that we transform to
```

2023-04-20 15:07 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +for quantum derivatives (`the parameter shift rule <https://pennylane.ai/qml/glossary/parameter_shift.html>`__). What
```suggestion
for quantum derivatives (`the parameter-shift rule <https://pennylane.ai/qml/glossary/parameter_shift.html>`__). What
```

2023-04-20 15:08 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +    Preparation for the parameter-shift proof.. We can then separate the diagram into two parts by recalling the definition of the :math:`+` and :math:`-`
```suggestion
    Preparation for the parameter-shift proof. We can then separate the diagram into two parts by recalling the definition of the :math:`+` and :math:`-`
```

2023-04-20 15:09 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +    Preparation for the parameter-shift proof.. We can then separate the diagram into two parts by recalling the definition of the :math:`+` and :math:`-`
By + / - here, do you mean the +/- states?

2023-04-20 15:10 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +with PennyLane! PennyLane v0.28 added ZX-calculus functionality to the fold. You can use the `to_zx`
Maybe link to the v0.28 blog post or something else here (e.g., release notes)?

2023-04-20 15:10 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +with PennyLane! PennyLane v0.28 added ZX-calculus functionality to the fold. You can use the `to_zx`
Not necessary

2023-04-20 15:26 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# graph. You can simplify the circuit, draw it and get a new understanding of your quantum computation.
```suggestion
# graph. You can simplify the circuit, draw it, and get a new understanding of your quantum computation.
```

2023-04-20 15:26 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# For example, you can use the matplotlib drawer to get a visualization of the diagram. The drawer returns a matplotlib
```suggestion
# For example, you can use the matplotlib drawer to get a visualization of the diagram. The drawer returns a ``matplotlib``
```

2023-04-20 15:26 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# For example, you can use the matplotlib drawer to get a visualization of the diagram. The drawer returns a matplotlib
Two backticks? Or one 🤔...

2023-04-20 15:27 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# We get a tape corresponding to the randomly generated circuit which we can use in any QNode. This
```suggestion
# We get a tape corresponding to the randomly generated circuit that we can use in any QNode. This
```

2023-04-20 15:34 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# circuits with ZX-diagrams and apply rewriting rules to simplify, like we did for teleportation. But not every
```suggestion
# circuits with ZX-diagrams and apply rewriting rules to simplify them — like we did for teleportation. But, not every
```

2023-04-20 15:39 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +#     The simplification and extraction of ZX-diagrams, content from [#Duncan2017]_ page 2.
```suggestion
#     The simplification and extraction of ZX-diagrams, content from page 2 of [#Duncan2017]_.
```

2023-04-20 15:45 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# 1. Removes all interior proper Clifford spiders,
```suggestion
# 1. Remove all interior proper Clifford spiders,
```

2023-04-20 15:46 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# :math:`\mathcal{O}(n^3)` where :math:`n` is the number of spiders. Let's create an example with the circuit `mod_5_4
```suggestion
# :math:`\mathcal{O}(n^3)`, where :math:`n` is the number of spiders. Let's create an example with the circuit `mod_5_4
```

2023-04-20 15:48 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# right-to-left, consuming on the left and adding gates on the right. It produces better results than other cut and
Is this correct?

```suggestion
# right-to-left, consuming gates on the left and adding gates on the right. It produces better results than other cut and
```

2023-04-20 15:50 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# resynthesize techniques. The extraction procedure is implemented in PyZX as the function
```suggestion
# right-to-left, consuming on the left and adding gates on the right. It produces better results than other cut-and-resynthesize
# techniques. The extraction procedure is implemented in PyZX as the function
```

2023-04-20 15:51 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# A concrete application of these ZX optimization techniques is the reduction of the expensive non-Clifford T count
```suggestion
# A concrete application of these ZX optimization techniques is the reduction of the expensive non-Clifford T-count
```

2023-04-20 15:53 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# Converting back to a quantum circuit from a fully reduced graph may be difficult or impossible. Therefore,
```suggestion
# Converting back to a quantum circuit from a fully reduced graph might be difficult or impossible. Therefore,
```

2023-04-20 15:53 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# the circuit does not need to be extracted and can be directly sent back to PennyLane. Let's see how it does:
```suggestion
# the circuit does not need to be extracted and can be directly sent back to PennyLane. Let's see how it works:
```

2023-04-20 15:55 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# We have reduced the T count! Taking a full census, the circuit contains :math:`53` gates: :math:`8` `qml.T()` gates,
```suggestion
# We have reduced the T-count! Taking a full census, the circuit contains :math:`53` gates: :math:`8` `qml.T()` gates,
```

2023-04-20 15:56 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# The author would also like to acknowledge the helpful inputs of Richard East, David Wakeham and Isaac De Vlugt. The
You're too kind! 🤗

2023-04-20 15:58 UTC, isaacdevlugt requested changes
Nice! Looking a lot better. Found some more grammatical errors. Also, there are some inconsistencies — at least I'm perceiving them as such — with when you hyphenate things. E.g., 

- "ZX framework", "ZX-diagrams"
- "X basis", "X-gate"

I don't think it's a huge deal and it's not worth dwelling on too long. Use your best judgement!

2023-04-21 11:45 UTC, RDPEast reviewed
The pictures still need updating obviously with the root 2's to the powers of whatever is relevant rather than what is written now. There are also a few minor scalar things knocking about but it looks like we are very close.

2023-04-21 11:45 UTC, RDPEast commented on demonstrations/tutorial_zx_calculus.py
> +# The extraction of circuits is a highly non-trivial task and can be a #P-hard problem [#Beaudrap2021]_. There are
```suggestion
# The extraction of circuits is a highly non-trivial task and can be a #P-hard problem as shown in this paper [#Beaudrap2021]_ by de Beaudrap et al . There are
```

Without mentioning the paper explicitly the next sentence sounds weird

2023-04-25 19:45 UTC, KetpuntoG reviewed
Great job, I finally understand the ZX calculus! 😄 A couple of comments and suggestions

- first correct Isaac's changes because if you make modifications in the code before that, they could become "outdated".

- When introducing the theorems with the drawing it was not clear to me if you were proving it afterwards or not. I would try to make this structure clearer. 1º Theorem 2ºdemonstration

2023-04-25 19:45 UTC, KetpuntoG commented on demonstrations/tutorial_zx_calculus.py
> +The theorem is proved — we just expressed the partial derivative as a ZX-diagram!
Is there any visual way to check this with the above properties? Or is it observed from the matrix multiplication?

<img width="692" alt="Captura de pantalla 2023-04-25 a las 15 14 44" src="https://user-images.githubusercontent.com/65235481/234379703-df144bb0-319e-450e-a55f-c14dd9ba8583.png">

2023-04-25 19:45 UTC, KetpuntoG commented on demonstrations/tutorial_zx_calculus.py
> +
Are you sure that the nodes on the left change to green?
<img width="295" alt="Captura de pantalla 2023-04-25 a las 15 20 06" src="https://user-images.githubusercontent.com/65235481/234380751-d15436d4-8b01-490f-ad4e-c64e36bb5309.png">

2023-04-25 19:45 UTC, KetpuntoG commented on demonstrations/tutorial_zx_calculus.py
> +The theorem is proved — we just expressed the partial derivative as a ZX-diagram!
I understood it later with the parameter shift rule but it was not clear here

2023-04-25 19:45 UTC, KetpuntoG commented on demonstrations/tutorial_zx_calculus.py
> +
<img width="407" alt="Captura de pantalla 2023-04-25 a las 15 24 34" src="https://user-images.githubusercontent.com/65235481/234381621-4c577650-df43-4d76-ba44-74730fb8c618.png">

What are the black points?

2023-04-25 19:45 UTC, KetpuntoG commented on demonstrations/tutorial_zx_calculus.py
> +# You can also take a ZX-diagram in PyZX, convert it into a PennyLane tape and use it in your QNode. Invoking the
Curiosity, what happens when there is no equivalent circuit? As far as I understood ZX maps > circuits

2023-04-26 14:19 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +
Thanks!

2023-04-26 14:42 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +    Preparation for the parameter-shift proof.. We can then separate the diagram into two parts by recalling the definition of the :math:`+` and :math:`-`
Yes I updated it!

2023-04-26 14:42 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +# For example, you can use the matplotlib drawer to get a visualization of the diagram. The drawer returns a matplotlib
let's try two haha

2023-04-26 17:01 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +wires, and represent the dimensions on which the linear maps are acting. Therefore, the edges represent qubits in
The dimension is the number of degrees of freedom, so I would say it is fine as it is.

2023-04-26 18:04 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +The Z-spider takes a real phase :math:`\alpha \in \mathbb{R}` and represents the following linear map (it accepts any
Thanks I will mention it!

2023-04-26 18:06 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +The Z-spider takes a real phase :math:`\alpha \in \mathbb{R}` and represents the following linear map (it accepts any
`(it accepts any
number of inputs and outputs, and the number of inputs does not need to match the number of outputs):`

2023-04-26 18:13 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +
I added a comment in the stack drawing.

2023-04-26 18:14 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +is only valid for states that are multiples of :math:`\pi`, so we have computational basis states (in the X or Z
Yes I will add that thanks

2023-04-26 18:17 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +
I think it is a bit hard without giving a lot of details, any suggestions?

2023-04-26 18:18 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +parametrized with boolean parameters :math:`a` and :math:`b`. The cup represents the maximally entangled state shared
Yes thanks!

2023-04-26 18:20 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +
In PyZx they add black point to specify the start of a wire.

2023-04-26 18:21 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +# You can also take a ZX-diagram in PyZX, convert it into a PennyLane tape and use it in your QNode. Invoking the
It will fail if you did not extract the circuit first.

2023-04-26 19:19 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +
That's how they defined it https://quantum-journal.org/papers/q-2021-06-04-466/pdf/ (page 6) but I think you are right the minus sign is not necessary.

2023-04-26 19:19 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +to its graph-like ZX diagram. We call the obtained diagram :math:`G_U(\vec{\theta})`.
It is just a constant I will add a definition

2023-04-26 19:30 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +their definitions and expanding the formula, we obtain:
No I think it is correct, because they imply there are diagrams in between the two spiders.

2023-04-26 19:32 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +
Yes it changes to green because we use the hadamard box as blue vertices

2023-04-26 19:33 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +The theorem is proved — we just expressed the partial derivative as a ZX-diagram!
Here I think you need to write down the formula and apply derivative on it. Then it becomes a visual rules.

2023-04-26 19:51 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +3. The ***:math:`\pi`-copy*** rule describes how to pull an X-gate through a Z-spider (or a Z-gate through an X-spider).
I failed to make this list looks nice. What is the needed indentation? @KetpuntoG @isaacdevlugt

2023-04-28 08:56 UTC, RDPEast requested changes
The diagrams need adjusting (but I understand you are on this atm anyway).

2023-04-28 08:56 UTC, RDPEast commented on demonstrations/zx_calculus/11ccnot.jpeg
Requires a scalar correction with the last diagram

2023-04-28 08:56 UTC, RDPEast commented on demonstrations/zx_calculus/b_rule.jpeg
My feeling is that we should keep the root 2 as it emphasizes that all scalars coming from these sorts of rewrites come from root(2)^(stuff)

2023-04-28 08:56 UTC, RDPEast commented on demonstrations/zx_calculus/c_rule.jpeg
should be root(2)^(n-1)

2023-04-28 08:56 UTC, RDPEast commented on demonstrations/zx_calculus/hxhz.jpg
should be (root 2)^(n+m)

2023-04-28 08:56 UTC, RDPEast commented on demonstrations/zx_calculus/hzhx.jpg
should be (root 2)^(n+m)

2023-04-28 13:27 UTC, rmoyard commented on demonstrations/zx_calculus/11ccnot.jpeg
@KetpuntoG

2023-04-28 13:27 UTC, rmoyard commented on demonstrations/zx_calculus/b_rule.jpeg
@KetpuntoG

2023-04-28 13:28 UTC, rmoyard commented on demonstrations/zx_calculus/c_rule.jpeg
@KetpuntoG

2023-04-28 13:28 UTC, rmoyard commented on demonstrations/zx_calculus/hxhz.jpg
@KetpuntoG

2023-04-28 13:28 UTC, rmoyard commented on demonstrations/zx_calculus/hzhx.jpg
@KetpuntoG

2023-05-02 17:50 UTC, isaacdevlugt approved these changes
Looks good Romain! 🥳 Just make sure that all of the images have their background removed. You can use the site https://remove.bg for this 👍. Also, we still need some help with formatting the figures within an itemized list :notlikethis:... But, once those two things are resolved, it's good to me.

2023-05-16 08:41 UTC, RDPEast reviewed
So some slightly annoying changes originating in the fact we've mixed conventions (see comments). Luckily the fix is quick and once they're done as far as I can tell it's complete.

2023-05-16 08:41 UTC, RDPEast commented on demonstrations/zx_calculus/hadamard_gate.jpeg
I've realised that we are mixing scalar conventions, this should in fact have a e^(ipi/4)/root(2) -  we should also point out that due our convention differs slightly from https://arxiv.org/pdf/2012.13966.pdf . More on this in another comment

2023-05-16 08:41 UTC, RDPEast commented on demonstrations/tutorial_zx_calculus.py
> +This introduction follows the works of the East et al. [#East2021]_ and van de Wetering [#JvdW2020]_. Our goal is to
We want to add a comment saying that we follow the scalar conventions of [#East2021]_ which are more suitable to the multi-H box situations, though highlight the differences are very slight and only appear in the scalars. Also comment that the reason for the varying conventions are discussed in https://arxiv.org/abs/2006.02557 and in https://arxiv.org/abs/2304.03310 .

2023-05-16 08:41 UTC, RDPEast commented on demonstrations/tutorial_zx_calculus.py
> +
I would cite [#JvdW2020]_ but point out there is a root 2 difference due to the scalar convention difference.

2023-05-16 08:41 UTC, RDPEast commented on demonstrations/zx_calculus/teleportation.jpg
Apologies for the minor change, it all needs to be scaled by 1/root(2), so the initial diagram has a scalar 1/root(2), the rest then don't have a scalar and the final diagram is simply the identity.

2023-05-16 13:15 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +
Ok no worries

2023-05-16 13:17 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +This introduction follows the works of the East et al. [#East2021]_ and van de Wetering [#JvdW2020]_. Our goal is to
Thanks I will add that!

2023-05-16 13:18 UTC, rmoyard commented on demonstrations/zx_calculus/hadamard_gate.jpeg
@KetpuntoG

2023-05-16 13:19 UTC, rmoyard commented on demonstrations/zx_calculus/teleportation.jpg
@KetpuntoG

2023-05-16 19:29 UTC, KetpuntoG commented on demonstrations/zx_calculus/hadamard_gate.jpeg
![IMG_7873CC0B8E3D-1](https://github.com/PennyLaneAI/qml/assets/65235481/8afed00e-389d-4098-832e-a748937cd2af)

2023-05-16 19:34 UTC, KetpuntoG commented on demonstrations/zx_calculus/teleportation.jpg
![IMG_6FEEE69D12BF-1](https://github.com/PennyLaneAI/qml/assets/65235481/b68b2cf7-7b2f-448a-9c6a-018015383c5c)

2023-05-16 20:47 UTC, RDPEast approved these changes
Looks good to me!

2023-06-01 17:44 UTC, KetpuntoG reviewed
last comments! 😄 great demo, great topic ! 🚀

2023-06-01 17:44 UTC, KetpuntoG commented on demonstrations/tutorial_zx_calculus.py
> +    The zero state and plus state as a ZX-diagram.
could you reorder this paragraph? Maybe put the drawing after the first paragraph?

2023-06-01 17:44 UTC, KetpuntoG commented on demonstrations/tutorial_zx_calculus.py
> +   splitting a wire into two wires) where, roughly speaking, we can pull a product through a coproduct at the cost of
```suggestion
splitting a wire into two wires) where, roughly speaking, we can pull a product through a coproduct at the cost of
```

2023-06-01 17:44 UTC, KetpuntoG commented on demonstrations/tutorial_zx_calculus.py
> +`the MBQC demo <https://pennylane.ai/qml/demos/tutorial_mbqc.html?highlight=teleportation#information-propagation-and-teleportation>`__.
```suggestion
`the MBQC demo <https://pennylane.ai/qml/demos/tutorial_mbqc.html>`__.
```

2023-06-01 17:44 UTC, KetpuntoG commented on demonstrations/tutorial_zx_calculus.py
> +    scalar convention.
a good time to refer to the image at the beginning. Something like saying and with this you can go back to the initial gif to see each step!

2023-06-01 17:44 UTC, KetpuntoG commented on demonstrations/tutorial_zx_calculus.py
> +The parameter :math:`a` can be any complex number, and the sum  is over all :math:`i1, ... , im, j1, ... , jn \in {0,
it would be better i_1, i_2,...

2023-06-01 17:44 UTC, KetpuntoG commented on demonstrations/tutorial_zx_calculus.py
> +The parameter :math:`a` can be any complex number, and the sum  is over all :math:`i1, ... , im, j1, ... , jn \in {0,
Also, for { to appear you have to put /{

2023-06-01 17:44 UTC, KetpuntoG commented on demonstrations/tutorial_zx_calculus.py
> +X-gate on the target wire, it means that only the state 110 and 111 will not map to themselves (110 to 111 and 111 to
Do make sense talk about kets here? instead of a string of 1s and 0s?

2023-06-01 17:44 UTC, KetpuntoG commented on demonstrations/tutorial_zx_calculus.py
> +Theorem 2: partial derivative as a ZX-diagram
I dont like too much Theorem 2 appears in the title. Do you think it makes sense to remove it from the title?

2023-06-01 17:44 UTC, KetpuntoG commented on demonstrations/tutorial_zx_calculus.py
> +:math:`-` states and using the fusion rule for the Z-spider. We obtain the parameter-shift rule!
the definition of |+> and |-> would be better

2023-06-01 17:44 UTC, KetpuntoG commented on demonstrations/tutorial_zx_calculus.py
> +with PennyLane! PennyLane v0.28 added ZX-calculus functionality to the fold. You can use the `to_zx`
Could you follow the standard way to reference our functions?
Look the following examples for functions or classes
```
:func:`~.pennylane.fourier.qnode_spectrum` 
:class:`~.pennylane.QNode`
```

2023-06-01 17:44 UTC, KetpuntoG commented on demonstrations/tutorial_zx_calculus.py
> +with PennyLane! PennyLane v0.28 added ZX-calculus functionality to the fold. You can use the `to_zx`
this comment applies to several parts of the demo from here onwards

2023-06-01 17:44 UTC, KetpuntoG commented on demonstrations/tutorial_zx_calculus.py
> +# :math:`\mathcal{O}(n^3)`, where :math:`n` is the number of spiders. Let's create an example with the circuit `mod_5_4
\mathcal{O} is not rendering properly in Safari 😅
It would be ugly to just put O?

2023-06-01 17:44 UTC, KetpuntoG commented on demonstrations/tutorial_zx_calculus.py
> +#
Could you give a final conclusion? For example comment on what we have seen and where we can learn more

2023-06-02 17:48 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +    The zero state and plus state as a ZX-diagram.
Yes!

2023-06-02 17:56 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +X-gate on the target wire, it means that only the state 110 and 111 will not map to themselves (110 to 111 and 111 to
I will add the ket

2023-06-02 18:01 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +Theorem 2: partial derivative as a ZX-diagram
Removed!

2023-06-02 18:21 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +#
Yes of course!

2023-06-02 21:02 UTC, isaacdevlugt approved these changes
Awesome job Romain!

2023-06-02 21:02 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# circuit. We have proved its utility for the optimization of quantum circuits. We have also shown that the
```suggestion
# Furthermore, you can use the simplifying rules to get another view of the underlying structure of your
# circuit. We have proved its utility for optimizing quantum circuits and shown that the
```

2023-06-02 21:02 UTC, isaacdevlugt commented on demonstrations/tutorial_zx_calculus.py
> +# call ZX-calculus the "Swiss army knife" of the quantum computing tools!
```suggestion
# ZX-calculus is more than promising for quantum machine learning. It was not covered in this introduction, but the
# ZX-calculus can also be used for quantum-error correction — it's no wonder why some quantum physicists
# call ZX-calculus the "Swiss army knife" of quantum computing tools!
```

2023-06-03 15:53 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +# a rigorous introduction to this active and promising field of application, see [#Duncan2017]_. The basic idea is
```suggestion
# a rigorous introduction to this active and promising field of application, see [#Duncan2020]_. The basic idea is
```

2023-06-03 15:53 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +# Theorem 5.4 in [#Duncan2017]_ provides an algorithm which takes a graph-like diagram and performs the following:
```suggestion
# Theorem 5.4 in [#Duncan2020]_ provides an algorithm which takes a graph-like diagram and performs the following:
```

2023-06-03 15:53 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +#     The simplification and extraction of ZX-diagrams, content from page 2 of [#Duncan2017]_.
```suggestion
#     The simplification and extraction of ZX-diagrams, content from page 2 of [#Duncan2020]_.
```

2023-06-03 15:53 UTC, rmoyard commented on demonstrations/tutorial_zx_calculus.py
> +# applied to "graph-like" ZX-diagrams. As defined in [#Duncan2017]_, a ZX-diagram is graph-like if
```suggestion
# applied to "graph-like" ZX-diagrams. As defined in [#Duncan2020]_, a ZX-diagram is graph-like if
```

2023-06-05 17:41 UTC, KetpuntoG approved these changes
🚀🚀🚀

2023-06-05 17:42 UTC, merged