QML tutorial for Quantum Variational Rewinding.
PennyLaneAI/qml pull request #679
Opened 2023-01-12 02:03 UTC by jackbaker1001

------------------------------------------------------------------------------------------------------------

**Title:** Quantum Variational Rewinding for Time Series Anomaly Detection

**Summary:** A simple and didactic/pedagogical look into the quantum variational rewinding (QVR) algorithm, also acting as a first-stepping stone on the way to using Covalent: the heterogeneous workflow management/scheduling tool. The reader is first introduced to the algorithm in the simplest way and then  uses QVR to learn the normal behaviour of a univariate (one dimensional) time series using a 1-qubit neural network. The threshold value is then tuned to maximize the accuracy score then the model is compared against random models, which is convincingly beats, to demonstrate that the normal behaviour of the time series was indeed learnt in the training process.

**Relevant references:**  

(1) Baker, Jack S. et al. “Quantum Variational Rewinding for Time Series
    Anomaly Detection.” arXiv, <https://arxiv.org/abs/2210.16438>, 2022

 (2) Stone, Marshall H. “On one-parameter unitary groups in Hilbert
     space.” Annals of Mathematics, 643-648,
     <https://doi.org/10.2307/1968538>, (1932).

 (3) Welch, Jonathan et al. “Efficient quantum circuits for diagonal
     unitaries without ancillas”, New Journal of Physics, **16**, 033040
     <https://doi.org/10.1088/1367-2630/16/3/033040>, (2014).

 (4) Cîrstoiu, Cristina et al. “Variational fast forwarding for quantum
    simulation beyond the coherence time”, npj Quantum Information,
     **6**,  <https://doi.org/10.1038/s41534-020-00302-0>, (2020)

**Possible Drawbacks:**

To run the tutorial script, a Covalent server needs to be running. This has already been added to `requirements.txt` if it is to be run at build time, (during the call to `sphinx`), the below command need to be issued in a terminal:

```bash
covalent start
```

**Related GitHub Issues:**
N/A

2023-01-12 16:32 UTC, KetpuntoG commented
Hey! Thanks for working on this demo 😄  Just to let you know that all our demos work with the same  [requirements.txt](https://github.com/PennyLaneAI/qml/blob/master/requirements.txt) file so make sure there are no incompatibilities with it

2023-01-13 16:20 UTC, KetpuntoG commented
On the other hand, the python version used to build the demos is `3.9`

2023-01-13 16:59 UTC, jackbaker1001 commented
Hey @KetpuntoG. I'm working on having things working in Python 3.9. I am finding a few problems with installing the requirements here though.

For example, for PyTorch:

```
ERROR: Could not find a version that satisfies the requirement torch==1.10.0+cpu (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1)
ERROR: No matching distribution found for torch==1.10.0+cpu
```

Pip version is 22.3.1
Python version is 3.9.15

2023-01-13 18:50 UTC, jackbaker1001 commented
@KetpuntoG after upgrading the Dask version in `requirements.txt` to `dask[delayed]==2022.9.0`, many more tests pass in the checks. Where it fails in build (78) is where I expect it to fail. 

As the PR states, Covalent needs to be running before this notebook is executed. Can you suggest to me where in the code I should be putting the `covalent start` command?

2023-01-13 19:08 UTC, KetpuntoG commented
I see you have managed to solve that problem! 💪 The new issue may come with the part of setting the connection with `http://localhost:48008/` . There is another way to write the demo in this situation. If when writing the name of the demo you avoid the `tutorial_` part it will not run, and you can manually put the outputs, as you can see in this [demo](https://pennylane.ai/qml/demos/vqe_parallel.html) (this is the [code](https://github.com/PennyLaneAI/qml/blob/master/demonstrations/vqe_parallel.py))
This is not ideal for the maintenance of the demo and may be changed in the future but I think it is a good solution for the moment 🙂

2023-01-13 19:12 UTC, KetpuntoG commented
> I see you have managed to solve that problem! 💪 The new issue may come with the part of setting the connection with `http://localhost:48008/` . There is another way to write the demo in this situation. If when writing the name of the demo you avoid the `tutorial_` part it will not run, and you can manually put the outputs, as you can see in this [demo](https://pennylane.ai/qml/demos/vqe_parallel.html) (this is the [code](https://github.com/PennyLaneAI/qml/blob/master/demonstrations/vqe_parallel.py))
> This is not ideal for the maintenance of the demo and may be changed in the future but I think it is a good solution for the moment 🙂

Although I'm not really sure if it would solve the problem 🤔 being able to put manual outputs could be useful for this demo? or precisely what you want to show is the access to covalent?

2023-01-15 20:46 UTC, josh146 commented
Hey @jackbaker1001, looks like the build is still failing 🤔 

```
 /home/runner/work/qml/qml/demonstrations/tutorial_univariate_qvr.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/runner/work/qml/qml/demonstrations/tutorial_univariate_qvr.py", line 781, in <module>
    plt.plot(results_dict["loss_history"], ".-")
TypeError: 'NoneType' object is not subscriptable
```

2023-01-16 02:54 UTC, jackbaker1001 commented
Hey @josh146. Yeah we are having some problems getting this working on the the testing pipeline. If that takes too long to figure out we shall take @KetpuntoG 's suggestion to have it as a non-running demo. I will get back to you on which choice is made after consulting my colleagues :)

2023-01-16 03:03 UTC, KetpuntoG commented
> Hey @josh146. Yeah we are having some problems getting this working on the the testing pipeline. If that takes too long to figure out we shall take @KetpuntoG 's suggestion to have it as a non-running demo. I will get back to you on which choice is made after consulting my colleagues :)

Okey, I'll stay tuned! If we can, let's try to keep the non-running demo as the last option 💪

2023-01-16 18:00 UTC, KetpuntoG commented
> ok @josh146 @KetpuntoG Tests now pass for the tutorial running. I'm just gonna make some small edits to non-vital parts then there is the final matter of the placeholder figure and who is drawing it etc.

🤩 Awesome! Thanks @jackbaker1001

2023-01-17 19:24 UTC, KetpuntoG commented
Nice catch @josh146 ! Thanks for fixing that last problem 💪
@jackbaker1001, let me know if everything is done so I can start with the review process of the content (don't worry about the images).

2023-01-17 21:12 UTC, jackbaker1001 commented
Hey @KetpuntoG and @josh146 . Firstly, thanks for the fix @josh146. I have made my changes now which, among other things, includes cartoons for the tutorial and the thumbnail. Provided the pipleline still passes (I think it will), we are good to move on to content review. Having looked at the previous version of the built wesbsite, it seemed there were a couple of rendering/formatting bugs, but i'm sure we can deal with these before release.

2023-01-18 05:17 UTC, jackbaker1001 commented
@KetpuntoG I noticed a strange bug in the preview website deployment. On this tutorial, (not mine) https://qml-build-previews.pennylane.ai/pull_request_build_preview/679/demos/tutorial_vqt.html, the thumbnail becomes mine! It seems because both me and Jack Cernoni share a first name, something strange happens...

2023-01-18 15:48 UTC, KetpuntoG commented
Fixed, the problem was that the image name was already being used by that other demo. That's why we try to give unique names to the images 😄

2023-01-18 16:13 UTC, jackbaker1001 commented
Good catch @KetpuntoG . Ok, so I think this is ready for content review now. Do you think you could provide an ETA for this please? Thanks again!

2023-01-18 19:36 UTC, KetpuntoG requested changes
It looks great! Thanks for your work! Here are a few comments to work on 😄
The review process usually goes through two or three reviewers in which we will do some iterations. I attach a small document to keep in mind how to act in a review to facilitate the process

[review.pdf](https://github.com/PennyLaneAI/qml/files/10450080/review.pdf)

2023-01-18 19:36 UTC, KetpuntoG commented on demonstrations/tutorial_univariate_qvr.py
> +######################################################################
I think this may fix the rendering here

2023-01-19 06:03 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +
Got it. I will add sentence communicating this.

2023-01-19 06:06 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +#    A cartoon describing the quantum variational rewinding algorithm.
Yeah I agree. We can just have this as an informal explanation before the more technical background section. We have to be careful a little though, because the figure (and caption) has math in it which isn't formally described until the "background" section. In that sense, it is almost better to have the image after the "background" section, but then the image isn't immediately visible on clicking the tutorial, which it should be, as it adds a bit of a draw to read the rest of the tutorial. 

Do you have an opinion on this @KetpuntoG ?

2023-01-19 06:08 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +#    \boldsymbol{y} := (\boldsymbol{y}_t: t \in T), \quad T := (t_l: 1 \leq l \leq p).
Your second comment is correct. Normal parentheses are used here to denote a sequence (which is of course ordered). This part has to stay!

2023-01-19 06:09 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +# :math:`x \in X` (:math:`x` is defined analogously to :math:`y` in the
Good catch. I will add a definition.

2023-01-19 06:09 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +        lexographical order or the bit strings.
Good catch!

2023-01-19 06:54 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +# :math:`|x_t \rangle = e^{-iH_E(x_t)}|0\rangle^{\otimes n} = U(x_t)|0\rangle^{\otimes n}`
Yeah, second comment is correct!

2023-01-19 07:12 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +# for efficient quantum circuits for doing so). Next, We operate on each
hmmm, i'm not sure what you mean by "after" here. This is all part of the first step. Any unitary operator $U$ can be written as $e^{-iM}$ where $M$ is hermitian. In this case, $U(x_t) = e^{-iH_E(x_t)}$. The operation that "actually happens" is the application of $U(x_t)$ to $|0\rangle^{\otimes n}$. It just so happens that we can write this unitary as the matrix exponential (although we don't actually calculate $H_E$).  This fact is useful for the later math.

2023-01-19 15:18 UTC, KetpuntoG commented on demonstrations/tutorial_univariate_qvr.py
> +#    A cartoon describing the quantum variational rewinding algorithm.
Good point, maybe the best thing here is to put the picture with a short description ("This picture describes the quantum variational rewinding algorithm, which will be developed in this demo").
and then at the end of "Background", say, "as an example of this, let's look at the start picture again (without repainting it), <and here you put the long description>.

2023-01-19 15:23 UTC, KetpuntoG commented on demonstrations/tutorial_univariate_qvr.py
> +# for efficient quantum circuits for doing so). Next, We operate on each
I got the feeling that I had to know why you were multiplying by that operator, but then you explain it. Maybe comment it out, "for the next step, we'll need to multiply by this operator and now we'll see why." or something like that. Feel free to ignore this comment if you think it is correct :)

2023-01-19 15:25 UTC, KetpuntoG commented
> Good catch @KetpuntoG . Ok, so I think this is ready for content review now. Do you think you could provide an ETA for this please? Thanks again!

If all goes well, everything should be ready in ~3 weeks

2023-01-19 16:16 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +#    \forall t, |0\rangle^{\otimes n} \langle 0|^{\otimes n}e^{-iH(\boldsymbol{\alpha}, \boldsymbol{\gamma})t}e^{-iH_E(x_t)}|0\rangle^{\otimes n} = 1 \iff \forall t, H(\boldsymbol{\alpha}, \boldsymbo
You're correct that this is wrong. To make sense with the previous paragraph we need either to (i) removed the first $|0 \range^{\otimes n}$ on the left or change the $1$ to $|0 \range^{\otimes n}$.  To make sense with the next time this is wrong (which you caught below), I will go with your suggestion.

Correct math:

$P(\)$

2023-01-19 16:23 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +#    F(\boldsymbol{\phi}, x_t) = \mathop{\mathbb{E}_{\boldsymbol{\gamma} \sim \mathcal{N}(\mu, \sigma)}}\left[|0\rangle^{\otimes n} \langle 0|^{\otimes n} |x_t, \boldsymbol{\alpha}, \boldsymbol{\gamm
Correct. I  removed it

2023-01-19 16:27 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +# for efficient quantum circuits for doing so). Next, We operate on each
So I think in this case what is written is correct. So if it's ok with you, I shall leave it put!

2023-01-19 17:04 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +# eigendecomposition
I'm not sure what is meant here. What particular way are you saying H should be defined? In our view, the decomposition $e^{-iH(\alpha, \gamma)} = W^{\dagger}(\alpha)D(\gamma, r)W(\alpha)$ can generalize to any $n$-qubit time evolution unitary provided enough variational layers are used to implement $W$ and $D$ is fully connected ($k=n$).

2023-01-19 17:23 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +
I've gone through and put imports as they are used.

2023-01-20 00:50 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +######################################################################
I added this. Bear in mind since we are only using one qubit, the resulting circuit is mere a R_z gate. I think it's nice for the general function to stay though in case people want to experiement with/modify stuff. I added this in the text

2023-01-20 00:50 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +# Like many machine learning algorithms, training is done in mini-batches.
Added!

2023-01-20 00:53 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +# While any sigmoidal-type function can be used, we choose
I'll add some clarification. But basically, it's because, for positive sigma (sigma is always positive) the arctan function we use is bounded in (0, 0.5) (we have a factor of 1/2 in there). This means that the loss function is defined in (0, 1).

2023-01-20 04:25 UTC, jackbaker1001 reviewed
LGTM!

2023-01-20 04:28 UTC, jackbaker1001 commented
I think I'm done here now @KetpuntoG . Thanks again for your detailed feedback. I think the whole thing reads better now.

2023-01-20 15:29 UTC, KetpuntoG reviewed
Good job 💪 with these last changes that I suggest, I will finish my review, I will contact the second reviewer to take a look at the demo :)

2023-01-20 15:29 UTC, KetpuntoG commented on demonstrations/tutorial_univariate_qvr.py
> +Before getting into the technical details of the algorithm, let's get high level overview with the help of the below cartoon
```suggestion
Before getting into the technical details of the algorithm, let's get high level overview with the help of the below cartoon:
```

2023-01-20 15:29 UTC, KetpuntoG commented on demonstrations/tutorial_univariate_qvr.py
> +# :math:`t_l \in \mathbb{R}_{>0}`
```suggestion
# :math:`t_l \in \mathbb{R}_{>0}`.
```

2023-01-20 15:29 UTC, KetpuntoG commented on demonstrations/tutorial_univariate_qvr.py
> +# :math:`y`, This function produces a real number:
```suggestion
# :math:`y`, this function produces a real number:
```

2023-01-20 15:29 UTC, KetpuntoG commented on demonstrations/tutorial_univariate_qvr.py
> +# `Covalent <https://www.covalent.xyz/>`__
```suggestion
# `Covalent <https://www.covalent.xyz/>`__.
```

2023-01-20 15:29 UTC, KetpuntoG commented on demonstrations/tutorial_univariate_qvr.py
> +#
Very wise to put this code here separately👌

2023-01-20 15:29 UTC, KetpuntoG commented on demonstrations/tutorial_univariate_qvr.py
> +# for quick checks like this
```suggestion
# for quick checks like this:
```

2023-01-20 15:29 UTC, KetpuntoG commented on demonstrations/tutorial_univariate_qvr.py
> +# use Qiskit device here because the circuit rendering is nice with mpl
in pennylane we have two ways to paint circuits:

`qml.draw` and `qml.draw_mpl`. The first one paints it in text and the second one with matplotlib. In this case the code would look like this:

```python

dev = qml.device("default.qubit", wires = 1)

D_one_qubit = qml.qnode(dev)(D)
qml.draw_mpl(D_one_qubit, decimals = 2)(torch.tensor([1,0]), 1, 1, True)
```

Check to see if you like it

2023-01-20 16:30 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +#
Thanks. It looks better that way right?

2023-01-20 16:44 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +# use Qiskit device here because the circuit rendering is nice with mpl
That's certainly more elegant than the present code. First thing that came up in google wsa the solution I put from this blog: https://pennylane.ai/blog/2021/05/how-to-visualize-quantum-circuits-in-pennylane/ 

One thing I always found a little frustrating in Pennylane  was drawing sections of circuits. Is there a way of doing this with having any measurements?

2023-01-20 17:47 UTC, jackbaker1001 commented
Hey @KetpuntoG I made your second set of changes. Just waiting on second reviewer now!

2023-01-23 14:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +Rewinding* algorithm, or, QVR, proposed by `Baker, Horowitz, Radha et.
```suggestion
Rewinding* algorithm, or QVR, proposed by `Baker, Horowitz, Radha et.
```

2023-01-23 14:23 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +learn a model of *normal* behaviour for time series data. Given a new (i.e, unseen in training) time
```suggestion
learn a model of *normal* behaviour for time series data. Given a new (i.e., unseen in training) time
```

2023-01-23 14:25 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +series, the normal model produces a value, which beyond a threshold,
```suggestion
series, the normal model produces a value that, beyond a threshold,
```

2023-01-23 14:28 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +Before getting into the technical details of the algorithm, let's get a high level overview with the help of the below cartoon:
```suggestion
Before getting into the technical details of the algorithm, let's get a high-level overview with the help of the cartoon below:
```

2023-01-23 14:29 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# Going left-to-right, a time series is sampled at three points in time, corresponding to a
```suggestion
# Going left-to-right, a time series is sampled at three points in time, corresponding to
```

2023-01-23 14:31 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# Hamiltonian operator (in practice, there are a distribution of such operators).
```suggestion
# Hamiltonian operator (in practice, there is a distribution of such operators).
```

2023-01-23 14:36 UTC, KetpuntoG commented on demonstrations/tutorial_univariate_qvr.py
> +# use Qiskit device here because the circuit rendering is nice with mpl
Currently we can't but I'm going to suggest them to create the functionality since as the code stands, it shouldn't be difficult to do 😊

2023-01-23 14:43 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +#
I'm a bit confused by this definition and I think it could be stated a bit more clearly. I don't know what is an _integer length-p sequence_. Is it a series that is indexed by integers (this is true for all sequences, by [definition](https://en.wikipedia.org/wiki/Sequence))? Or does the variable take integer values (does not make much sense if it's a vector, actually). The last sentence also seems to imply that $t_\l$ (the index?) is a real number, which doesn't make much sense to me.

2023-01-23 14:46 UTC, josh146 commented on demonstrations/tutorial_univariate_qvr.py
> +        set T
@jackbaker1001 a minor suggestion here, but you'll notice that our other demos don't have docstrings (or when they do, the docstrings are very minimal).

The reason for this is that, in tutorial formats, we aim to ensure that the text adequately describes the function -- so that after reading the preceding paragraph, it is clear what the function is doing without needing a large docstring, which can disrupt the 'flow' of the story.

Having function arguments with descriptive names (e.g., `time_series_len` rather than `p`) can also help in reducing the need to have large docstrings in tutorials :)

2023-01-23 14:51 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# analogously to :math:`y` in the above) from which the anomaly score function
```suggestion
# analogously to :math:`y` in the above), from which the anomaly score function 
```

2023-01-23 14:52 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# :math:`a_X(x) \rightarrow 0, \forall x \in X`. Then, for an unseen time
```suggestion
# :math:`a_X(x) \approx 0, \forall x \in X`. Then, for an unseen time
```

2023-01-23 14:53 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# :math:`a_X(x) \rightarrow 0, \forall x \in X`. Then, for an unseen time
$\rightarrow$ makes sense in the context of limits of sequences. This is not the case here.

2023-01-23 14:55 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# :math:`a_X(x) \rightarrow 0, \forall x \in X`. Then, for an unseen time
Let's avoid the use of $\forall$, etc. It's good practice for math readability.

2023-01-23 15:02 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# series :math:`y`, the series is said to be anomalous should
```suggestion
# series :math:`y` and a threshold :math:`\xi \in \mathbb{R}`, the series is said to be anomalous should
```

2023-01-23 15:02 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# :math:`a_X(y) > \zeta` and normal otherwise for threshold
```suggestion
# :math:`a_X(y) > \zeta` and normal otherwise.
```

2023-01-23 15:09 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# :math:`\zeta \in \mathbb{R}`. We show a strategy for setting
```suggestion
# series :math:`y` and a threshold $\zeta \in \mathbb{R}$, the series is said to be anomalous should
# :math:`a_X(y) > \zeta,` and normal otherwise. We show a strategy for setting
```

2023-01-23 15:09 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# :math:`\zeta \in \mathbb{R}`. We show a strategy for setting
Rewritten for clarity.

2023-01-23 15:19 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# for embedding unitary operator :math:`U(x_t)` implementing a quantum
```suggestion
# for an embedding unitary operator :math:`U(x_t)` implementing a quantum
```

2023-01-23 15:22 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +#    |x_t, \boldsymbol{\alpha}, \boldsymbol{\gamma}\rangle := e^{-iH(\boldsymbol{\alpha}, \boldsymbol{\gamma})t}|x_t\rangle
```suggestion
#    |x_t, \boldsymbol{\alpha}, \boldsymbol{\gamma}\rangle := e^{-iH(\boldsymbol{\alpha}, \boldsymbol{\gamma})t}|x_t\rangle,
```

2023-01-23 15:46 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# unitary groups [#Stone1932]_.
Rewritten for clarity, but please check that it renders properly since suggestions ruin my #

2023-01-23 15:47 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# To answer this, we must find
```suggestion
# To answer this, we impose
```

2023-01-23 15:48 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# :math:`P(|0\rangle^{\otimes n}) = |\langle 0|^{\otimes n}|x_t, \boldsymbol{\alpha}, \boldsymbol{\gamma} \rangle|^2 = 1`
```suggestion
# :math:`P(|0\rangle^{\otimes n}) = |\langle 0|^{\otimes n}|x_t, \boldsymbol{\alpha}, \boldsymbol{\gamma} \rangle|^2 = 1.`
```

2023-01-23 15:48 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# Playing with the algebra a little we have the condition
```suggestion
# Playing with the algebra a little, we have the condition
```

2023-01-23 15:50 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +#    \forall t, \langle 0|^{\otimes n}e^{-iH(\boldsymbol{\alpha}, \boldsymbol{\gamma})t}e^{-iH_E(x_t)}|0\rangle^{\otimes n} = 1 \iff \forall t, H(\boldsymbol{\alpha}, \boldsymbol{\gamma})t = -H_E(x_t
```suggestion
#   \langle 0|^{\otimes n}e^{-iH(\boldsymbol{\alpha}, \boldsymbol{\gamma})t}e^{-iH_E(x_t)}|0\rangle^{\otimes n} = 1 \iff  H(\boldsymbol{\alpha}, \boldsymbol{\gamma})t = -H_E(x_t).
```

2023-01-23 15:50 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +#    \forall t, \langle 0|^{\otimes n}e^{-iH(\boldsymbol{\alpha}, \boldsymbol{\gamma})t}e^{-iH_E(x_t)}|0\rangle^{\otimes n} = 1 \iff \forall t, H(\boldsymbol{\alpha}, \boldsymbol{\gamma})t = -H_E(x_t
for all symbols crowd notation.

2023-01-23 15:52 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# applied: :math:`|0\rangle^{\otimes n}`.
```suggestion
# state :math:`|0\rangle^{\otimes n}` before the embedding unitary operator :math:`U(x_t)` was
# applied.
```

2023-01-23 15:53 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# :math:`x \in X` (in fact this is impossible to do so exactly if each
```suggestion
# :math:`x \in X` (in fact, this is impossible to do if each
```

2023-01-23 16:01 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# The goal is for the above to be :math:`\approx 1`
```suggestion
# The goal is for the function :math:`F` defined above to be as close to :math:`1` as possible,
```

2023-01-23 16:01 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# :math:`\forall x \in X` and :math:`\forall t`. With this in mind, we can
```suggestion
#  for all :math:`x \in X.` With this in mind, we can
```

2023-01-23 16:03 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# hyperparameter :math:`\tau`.
```suggestion
# hyperparameter :math:`\tau:`
```

2023-01-23 16:03 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +#    \mathcal{L(\boldsymbol{\phi})} = \frac{1}{2|X||T|}\sum_{x \in X} \sum_{t \in T}[1 - F(\boldsymbol{\phi}, x_t)]^2 + P_{\tau}(\sigma)
```suggestion
#    \mathcal{L(\boldsymbol{\phi})} = \frac{1}{2|X||T|}\sum_{x \in X} \sum_{t \in T}[1 - F(\boldsymbol{\phi}, x_t)]^2 + P_{\tau}(\sigma).
```

2023-01-23 16:04 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# Where we shall show the exact form of :math:`P_{\tau}(\sigma)` later.
```suggestion
# We will show the exact form of :math:`P_{\tau}(\sigma)` later.
```

2023-01-23 16:04 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# The general purpose of the penalty function, however, is to penalize
```suggestion
# The general purpose of the penalty function is to penalize
```

2023-01-23 16:14 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# Presently, many QML algorithms are *heterogeneous* in nature. That is,
```suggestion
# Presently, many QML algorithms are *heterogeneous* in nature. This means that
```

2023-01-23 16:15 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# they require compute resources from different computation paradigms:
```suggestion
# they require computational resources from different computation paradigms:
```

2023-01-23 16:15 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# classical and quantum computation. Covalent is a tool that can be used
```suggestion
# Covalent is a tool that can be used
```

2023-01-23 16:18 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# tutorial, to begin we define two key components.
```suggestion
# tutorial, we define two key components to being with.
```

2023-01-23 16:19 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +#    computation.
```suggestion
#  a computation.
```

2023-01-23 16:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +#    different hardware and multiple compute paridigms (classical, quantum etc.: see the `Covalent executors <https://covalent.readthedocs.io/en/stable/plugins.html>`__),
```suggestion
#    different hardware and multiple computational paradigms (classical, quantum etc.: see the `Covalent executors <https://covalent.readthedocs.io/en/stable/plugins.html>`__),
```

2023-01-23 16:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +#    in this tutorial, to keep things simple, things are run on a local
```suggestion
#    In this tutorial, to keep things simple, things are run on a local
```

2023-01-23 16:24 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# signals normally distributed about the origin: :math:`x_t \sim \mathcal{N}(0, 0.1)` and the
```suggestion
# signals normally distributed about the origin, for example, :math:`x_t \sim \mathcal{N}(0, 0.1).` The
```

2023-01-23 16:24 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# spikes with random duration and amplitude.
```suggestion
# spikes with random durations and amplitudes.
```

2023-01-23 16:27 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# (big spikes). We of course don't need a complicated algorithm to be able to detect
```suggestion
# (big spikes). Of course, we don't need a complicated algorithm to be able to detect
```

2023-01-23 16:27 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# Moving on, like many machine learning algorithms, training is done in mini-batches.
```suggestion
# Like many machine learning algorithms, training is done in mini-batches.
```

2023-01-23 16:28 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# `pickleable <https://docs.python.org/3/library/pickle.html#:~:text=%E2%80%9CPickling%E2%80%9D%20is%20the%20process%20whereby,back%20into%20an%20object%20hierarchy.>`__
```suggestion
# `pickleable, <https://docs.python.org/3/library/pickle.html#:~:text=%E2%80%9CPickling%E2%80%9D%20is%20the%20process%20whereby,back%20into%20an%20object%20hierarchy.>`__
```

2023-01-23 16:29 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# training set, we need to build our loss function
```suggestion
# training set. We need to build our loss function
```

2023-01-23 16:33 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# lexicographic order)
```suggestion
# lexicographic order).
```

2023-01-23 16:34 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +
I wonder if you need to put these docstrings in every single function, since a lot of them have already been defined before.

2023-01-23 16:37 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# electron
```suggestion
# electron.
```

2023-01-23 16:39 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# before running this workflow, we define all of the input parameters.
```suggestion
# Before running this workflow, we define all of the input parameters.
```

2023-01-23 16:40 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# Covalent GUI. It will look like the below, showing nicely how all of the
```suggestion
# Covalent GUI. It will look like the screenshot below, showing nicely how all of the
```

2023-01-23 16:42 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# accuracy score as defined using the below three electrons.
```suggestion
# accuracy score as defined using the three electrons below.
```

2023-01-23 16:43 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# set, we can scan through various zetas on a fine 1D grid and calcuate
```suggestion
# set, we can scan through various values of $:math:`zeta`$ on a fine 1D grid and calcuate
```

2023-01-23 16:44 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +# and set the input parameters.
```suggestion
# We set the input parameters.
```

2023-01-23 16:49 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +
Thanks!

2023-01-23 16:54 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_univariate_qvr.py
> +Before getting into the technical details of the algorithm, let's get a high level overview with the help of the below cartoon:
This happens in many places and needs fixing. "Cartoon below" stands for "the cartoon (that is shown) below", so _below_ does not modify cartoon and must not go before it. It is an adverb, and it must go after.

2023-01-23 16:55 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +# tutorial, to begin we define two key components.
I think there is a typo above, I think you mean "begin" with.

2023-01-23 16:55 UTC, alvaro-at-xanadu requested changes
Great tutorial over all, I learned a lot. There are quite a few grammar/style fixes that need to be addressed, and a few definitions that are unclear. Excellent work!

2023-01-23 16:59 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +# tutorial, to begin we define two key components.
Added manually with new commit

2023-01-23 17:12 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +# signals normally distributed about the origin: :math:`x_t \sim \mathcal{N}(0, 0.1)` and the
I don't think "for example" makes sense here. There are not other examples, the normal signals are always drawn from N(0, 0.1).

I will change to:

"signals normally distributed about the origin. In our case, :math:`x_t \sim \mathcal{N}(0, 0.1)."

2023-01-23 17:17 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +# spikes with random duration and amplitude.
Made this change in another commit

2023-01-23 17:23 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +# `pickleable <https://docs.python.org/3/library/pickle.html#:~:text=%E2%80%9CPickling%E2%80%9D%20is%20the%20process%20whereby,back%20into%20an%20object%20hierarchy.>`__
We don't want to have the comma hyperlinked no? Added it after

2023-01-23 17:52 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +
Having taken a look through a fair few, it seems some tutorials include docstrings and others don't. I can certainly reduce the size of these docstrings by making sure there are no repeat definitions, but, I do think docstrings in general need to stay. Although variables are already named to match the math in the text, I think it just easier to see them defined in the function rather than back-track through the tutorial to find definitions.

2023-01-23 18:12 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +        set T
Ok since you and @alvaro-at-xanadu made similar comments, I will slash the variable definitions in docstrings entirely. I will try and use informative variable names where possible, but please note, things like `p` were used to match the math notation in the text cells. Does your opinion change with this or do you still want these change to `time_series_len` etc? @josh146

2023-01-23 18:15 UTC, josh146 commented on demonstrations/tutorial_univariate_qvr.py
> +        set T
I'm happy with `p` as long as it is explained in the text/maths!

2023-01-23 21:21 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +#    different hardware and multiple compute paridigms (classical, quantum etc.: see the `Covalent executors <https://covalent.readthedocs.io/en/stable/plugins.html>`__),
Added in another commit

2023-01-23 21:43 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +#
Thanks for pointing this out. I will clarify things here.

It indeed is indexed by an integer. What I mean is the sequence has p-many elements where p is an integer. I don't understand your last comment though, it is stated that $t_l \in \mathbb{R}_{>0}$ not that $l$ is a real number. $l$ is an integer in $1 \leq l \leq p$.

I think I will change this last inequality to $l \in \mathbb{Z}^{+}_{\leq p}$ to avoid ambiguity

2023-01-24 01:34 UTC, jackbaker1001 commented
Ok @alvaro-at-xanadu , thank you for your detailed review, it was very helpful. I have made your changes and the PR should now be up to date. 

Where do we go from here @KetpuntoG @josh146 ?

2023-01-24 20:41 UTC, KetpuntoG commented
> Ok @alvaro-at-xanadu , thank you for your detailed review, it was very helpful. I have made your changes and the PR should now be up to date.
> 
> Where do we go from here @KetpuntoG @josh146 ?

Hey @jackbaker1001 , I would like to take a last review to check that everything is ok but the work is going fast so I think it can be published before QHack 😊

2023-01-24 23:18 UTC, jackbaker1001 commented
Thanks @KetpuntoG . I'll standby for your last review then!

2023-01-27 16:07 UTC, jackbaker1001 commented
@KetpuntoG are there any action items for me on here?

2023-01-27 20:20 UTC, KetpuntoG commented
> @KetpuntoG are there any action items for me on here?

Hi @jackbaker1001 ! @ikurecic will be the person who will do the final review, soon you will have her suggestions :)
On the other hand, the estimated release date of the demo is Tuesday February 7th

2023-02-01 13:03 UTC, ikurecic reviewed
Very cool demo!
I made just very simple language correction suggestions.
However, I got stuck around the end ([line 1050](https://github.com/PennyLaneAI/qml/blob/bfa280726304bcc91adf91782d1454d39c78229f/demonstrations/tutorial_univariate_qvr.py#L1049-L1051)). Is it on my end?

2023-02-01 13:03 UTC, ikurecic commented on demonstrations/tutorial_univariate_qvr.py
> +accs_list, scores_list = ct_val_results.result
Unfortunately, I got stuck here. Is it something on my end?

> Node get_norm_and_anom_scores failed:
Traceback (most recent call last):
File "/home/ikurecic/miniconda3_9/lib/python3.9/site-packages/covalent_dispatcher/_core/execution.py", line 353, in _run_task
output, stdout, stderr = await execute_callable()
File "/home/ikurecic/miniconda3_9/lib/python3.9/site-packages/covalent/executor/base.py", line 387, in execute
result = await self.run(function, args, kwargs, task_metadata)
File "/home/ikurecic/miniconda3_9/lib/python3.9/site-packages/covalent/executor/executor_plugins/dask.py", line 112, in run
result, worker_stdout, worker_stderr = await dask_client.gather(future)
File "/home/ikurecic/miniconda3_9/lib/python3.9/site-packages/distributed/client.py", line 2089, in _gather
raise exception.with_traceback(traceback)
distributed.scheduler.KilledWorker: ('dask_wrapper-af3cea404e772fc9c72d220417abe2b7', <WorkerState 'tcp://127.0.0.1:38265', name: 13, status: closed, memory: 0, processing: 1>)

2023-02-01 13:04 UTC, ikurecic reviewed
Very cool demo!
I made just very simple language correction suggestions.
However, I got stuck around the end ([line 1050](https://github.com/PennyLaneAI/qml/pull/679/files#diff-783d37dde04a8455b37a02139dd341b4171f1783f51cb4745764ab77df3ff8ecR1049-R1051)). Is it on my end?

2023-02-01 22:00 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +     given an optimal model and set of random models. We use the optimal zetas found in threshold tuning.
I think you may have accidentally introduced a typo here. I will keep the old version!

2023-02-01 22:08 UTC, jackbaker1001 commented on demonstrations/tutorial_univariate_qvr.py
> +accs_list, scores_list = ct_val_results.result
Hey @ikurecic. So, this happened because one of Dask workers ran out of memory during this part of the tutorial. Under the hood, when you run Covalent locally, it attempts to parallelize tasks using workers/threads in Dask. It just so happens that on your local machine, the default Dask cluster had workers (which have their memory managed by Dask) which didn't have enough memory.

You can try running again by replacing the `covalent start` at the beginning of the script specifically requesting memory:

`covalent start -m "2GiB" -n 2`

This starts a a covalent server with two processes and 2 Gigs of memory each.

Long story short, this only happens when RAM on somebody's laptop becomes a factor. Does this make sense @ikurecic ?

2023-02-01 22:36 UTC, jackbaker1001 commented
Thank you so much @ikurecic! You certainly have a keen eye for typos and language. Things look much better now!

@KetpuntoG Does this conclude review?

2023-02-02 12:12 UTC, ikurecic commented on demonstrations/tutorial_univariate_qvr.py
> +accs_list, scores_list = ct_val_results.result
That makes sense, thanks @jackbaker1001 — do you mind adding that note to the demo? It's a simple enough fix.

2023-02-02 18:59 UTC, KetpuntoG commented
> Thank you so much @ikurecic! You certainly have a keen eye for typos and language. Things look much better now!
> 
> @KetpuntoG Does this conclude review?

Yes, the only thing left to do is to write the little note that has been suggested about the dask problem, and then the review would be finished 💯

2023-02-02 20:32 UTC, jackbaker1001 commented
@KetpuntoG @ikurecic  I put a comment near where the Covalent server is started on how to troubleshoot memory issues.

2023-02-03 20:04 UTC, jackbaker1001 commented
@KetpuntoG Could you please confirm the URL for this demo once it goes live? (are we still planning on Feb 7th?)

2023-02-03 20:10 UTC, KetpuntoG commented
> @KetpuntoG Could you please confirm the URL for this demo once it goes live? (are we still planning on Feb 7th?)

No problem, I'll share the link right here when it's published 😄
Yes, the date is still the 7th. We will do the merge the day before for security but we will not announce it until the 7th

2023-02-03 20:19 UTC, josh146 commented
@jackbaker1001 the URL is based on the filename, so assuming no changes, it _should_ be https://pennylane.ai/qml/demos/tutorial_univariate_qvr.html. But I would still double check before release :)

2023-02-06 14:54 UTC, KetpuntoG commented
Hey @jackbaker1001 , the title is too long and fits too tightly inside the card. Do you have any suggestion how to shorten it?

2023-02-06 17:00 UTC, jackbaker1001 commented
@KetpuntoG I also noticed this some time back but didn't know if it was an issue or not (it seemed to be that it did just about fit in the box).

I struggled to think of a shorter title. But perhaps: "Time series anomaly detection, Quantumly". Is good?

2023-02-06 17:03 UTC, jackbaker1001 commented
@KetpuntoG what's the character limit?

2023-02-06 17:47 UTC, KetpuntoG commented
> @KetpuntoG what's the character limit?

not sure, what about "Quantum detection of time series anomalies"?

2023-02-06 22:05 UTC, KetpuntoG approved these changes
Amazing job in this demo 🚀💯

2023-02-06 22:07 UTC, merged

2023-02-06 23:26 UTC, KetpuntoG commented
There you go @jackbaker1001 ! https://pennylane.ai/qml/demos/tutorial_univariate_qvr.html
Tomorrow we will announce it on our social networks :)

2023-02-07 01:05 UTC, jackbaker1001 commented
Thanks again to everybody who reviewed this demo! @KetpuntoG @ikurecic @alvaro-at-xanadu @josh146

2023-02-07 04:04 UTC, jackbaker1001 commented
FYI @KetpuntoG it appears that the link is broken!

2023-02-07 04:25 UTC, KetpuntoG commented
Oh that's weird, It is working for me and I have tried it in two different browsers @jackbaker1001 . Could you double check? Try clearing the cache in case you are getting an old version 🤔

2023-02-07 04:55 UTC, jackbaker1001 commented
@KetpuntoG Clearing the cache fixed it. A few others were having this issue on my side too haha. I will tell them to clear the cache also