Sc 30752 Create Quantum Chemistry subhub
PennyLaneAI/qml pull request #683
Opened 2023-01-19 15:28 UTC by Anakhom

[sc-30752-add-quantum-chemistry-hub-page-in-qml-project](https://app.shortcut.com/xanaduai/story/30752/add-quantum-chemistry-hub-page-in-qml-project)

@josh146 @BM7878, content/copy missing in this PR:
- `whatisqchem.html` page is still being worked on according to this [PR](https://github.com/PennyLaneAI/qml/pull/584/files)
- missing copy for meta description, meta image, two of the cards' descriptions and the title above the video.
- same situation with missing high quality thumbnail for the video as with other subhubs, we can discuss hiding the video section to roll out the subhubs earlier

2023-01-23 02:37 UTC, josh146 reviewed
Thanks @Anakhom! Have also gone through and provided the missing copy here

2023-01-23 02:37 UTC, josh146 commented on quantum-chemistry.rst
> +==============================
```suggestion
Quantum Chemistry
=================
```

2023-01-23 02:37 UTC, josh146 commented on quantum-chemistry.rst
> +   :property="og:description": Placeholder until copy is provided
```suggestion
   :property="og:description": Sit back and learn about quantum chemistry. Explore key concepts, download and run demonstrations, and view our selection of curated videos.
```

2023-01-23 02:37 UTC, josh146 commented on quantum-chemistry.rst
> +        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, p
```suggestion
        Quantum chemistry is an area of research focused on calculating properties of molecules, and the materials built out of them, using quantum mechanics. 
        <br><br>
        Learn why quantum chemistry is one of the leading applications of quantum computing, as well as the fundamental concepts and applications, through our collection of articles, tutorials, and demos.
```

2023-01-23 02:37 UTC, josh146 commented on quantum-chemistry.rst
> +                            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
```suggestion
                            Explore different concepts underpinning quantum chemistry and quantum computation.
```

2023-01-23 02:37 UTC, josh146 commented on quantum-chemistry.rst
> +                            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur tempus urna at turpis condimentum lobortis.
```suggestion
                            Take a dive into quantum chemistry and explore the physics, concepts, and applications through code.
```

2023-01-23 02:37 UTC, josh146 commented on quantum-chemistry.rst
> +                <h2 class="fw-normal text-center mt-1 mb-5 border-0">Curabitur tempus urna at turpis lobortis. Ut commodo efficitur neque.</h2>
```suggestion
                <h2 class="fw-normal text-center mt-1 mb-5 border-0">Sit back and explore quantum chemistry with our curated selection of expert videos.</h2>
```

2023-01-23 14:14 UTC, ashishks0522 requested changes

2023-01-23 14:14 UTC, ashishks0522 commented on quantum-chemistry.rst
> +                    <a href="whatisqchem.html">
```suggestion
                    <a href="what-is-quantum-chemistry.html">
```

2023-01-23 14:14 UTC, ashishks0522 commented on quantum-chemistry.rst
> +    whatisqchem
```suggestion
    what-is-quantum-chemistry
```

2023-01-24 17:33 UTC, BM7878 commented
As with the QML hub, let's remove the videos section for now until the new preview image is complete. We can add it back in once it is.

2023-01-30 01:34 UTC, josh146 commented
Hey @Anakhom and @ikurecic! Just wondering what else needs to be done here, is it just a matter of review? Or are we still waiting for new graphics?

2023-01-30 11:48 UTC, ikurecic commented
@josh146 I think everything is here.

2023-01-31 10:19 UTC, ikurecic reviewed
I added a few text-based suggestions, and have two separate thoughts.

![image](https://user-images.githubusercontent.com/4939555/215732581-f06393b3-d4dd-48d5-a550-52edef1d9063.png)
I think we want to vertically align the text, as well as the headings here. I think this should be adjusted for all three hubs, but it's really obvious in this one.

There's also a vertical gap we could reduce, right above the footer.

2023-01-31 10:19 UTC, ikurecic commented on quantum-chemistry.rst
> +        Quantum chemistry is an area of research focused on calculating properties of molecules, and the materials built out of them, using quantum mechanics.
```suggestion
        Quantum chemistry is an area of research focused on calculating properties of molecules and the materials built out of them, using quantum mechanics. 
```

2023-01-31 10:19 UTC, ikurecic commented on quantum-chemistry.rst
> +        Learn why quantum chemistry is one of the leading applications of quantum computing, as well as the fundamental concepts and applications, through our collection of articles, tutorials, and d
```suggestion
        Learn why quantum chemistry is one of the leading applications of quantum computing, and discover its fundamental concepts and applications through our collection of articles, tutorials, and demos.
```
Changing formulation because of repetition (application) and a weird grammar issue.

2023-01-31 10:19 UTC, ikurecic commented on what-is-quantum-chemistry.rst
> +Following Feynman's suggestion, we note that **nature is quantum**. This suggests that if our simulation platform is also quantum, we should be able to simulate nature better than classical computers
```suggestion
Following Feynman's suggestion, we note that **nature is quantum**. If our simulation platform is also quantum, we should be able to simulate nature better than classical computers can, with resources scaling as the size of the target system, rather than exponentially. For quantum chemistry, this offers a dramatic improvement on traditional, exponentially costly methods.
```
Suggesting removal so text doesn't wrap under the image (@co9olguy ).

2023-01-31 15:33 UTC, Anakhom commented
> I added a few text-based suggestions, and have two separate thoughts.
> 
> ![image](https://user-images.githubusercontent.com/4939555/215732581-f06393b3-d4dd-48d5-a550-52edef1d9063.png) I think we might(?) want to vertically align the text, as well as the headings here. In that case, this should be adjusted for all three hubs, but it's really obvious in this one. And maybe there's a bit too much empty space above the 'Read more' links.
> 
> There's also a vertical gap we could reduce right above the footer.

Hi @ikurecic , the titles are actually vertically aligned. Because the title of the first card, 'What is Quantum Chemistry' is simply longer than the rest of the titles, it is wrapping around and creating and extra line that kind of moves the heading one line down as well. It is, unfortunately, the affects of the content. 

Also if you feel like there is too much space above the 'Read More' we can either add more text in the cards (which would be preferable), bump up the font size (which might break the consistency between the subhubs) or change the height of the cards (which also might break the consistency in the subhubs). I would prefer not to touch the rest of the hubs as the cards do look perfect in terms of the content.

Also FYI, everything above applies to the [Quantum Computing hub](https://github.com/PennyLaneAI/qml/pull/684) as well. 

Unfortunately, possibly the cards were designed for the specific amount of text so it might look off sometimes if the content is not unified for all three cards. 

P.S.: white space above the footer is reduced :slightly_smiling_face:

2023-01-31 15:38 UTC, ikurecic commented
> Hi @ikurecic , the titles are actually vertically aligned. Because the title of the first card, 'What is Quantum Chemistry' is simply longer than the rest of the titles, it is wrapping around and creating and extra line that kind of moves the heading one line down as well. It is, unfortunately, the affects of the content.

@Anakhom yep, I'm with you there — I guess that means there's no way to align the actual _text_, in addition to the headings, in the current setup? (I'm sorry, I didn't look at the code in detail.)

> Also if you feel like there is too much space above the 'Read More' we can either add more text in the cards (which would be preferable), bump up the font size (which might break the consistency between the subhubs) or change the height of the cards (which also might break the consistency in the subhubs). I would prefer not to touch the rest of the hubs as the cards do look perfect in terms of the content.

I see what you mean now, thanks for explaining! :) Let's see if anybody else has a comment about these. Adding text isn't a huge problem, but it might inhibit the 'legibility' of the page. @BM7878 , maybe worth a quick thought?

2023-01-31 16:05 UTC, josh146 approved these changes
Amazing seeing it all come together!

2023-01-31 16:14 UTC, ashishks0522 approved these changes
Looks good!

2023-01-31 16:38 UTC, BM7878 approved these changes
I'd say this is good to go. I think the alignment issues with the card headings are unlikely to be noticed by a typical user scan-reading the page, and won't draw the eye, so I don't think we should worry about them too much.

2023-01-31 16:47 UTC, LucasSilbernagel reviewed
Overall looks good to me!

2023-01-31 16:47 UTC, LucasSilbernagel commented on quantum-chemistry.rst
> +        -->
Can this be removed, or is it being saved for some reason?

2023-01-31 16:51 UTC, LucasSilbernagel approved these changes
👍

2023-01-31 19:39 UTC, merged