Change ibm device
PennyLaneAI/qml pull request #703
Opened 2023-02-21 18:07 UTC by rmoyard

2023-02-21 18:44 UTC, timmysilv commented
is it expected that this device expands the circuit differently? the results look completely different, just wondering if that's alright for the results being demonstrated.

2023-02-21 18:47 UTC, josh146 commented
Might be good to tag @glassnotes in that case :)

2023-02-21 19:12 UTC, mudit2812 approved these changes
Just curious about why we switched to a 7-qubit device, but other than that, looks good

2023-02-21 19:12 UTC, mudit2812 commented on demonstrations/quantum_volume.py
> +dev_ourense = qml.device("qiskit.ibmq", wires=5, backend="ibm_oslo")
Why are we switching to `ibm_oslo`? Oslo is a 7 qubit device. We could use a 5 qubit device like manila, lima, etc.

2023-02-21 19:16 UTC, glassnotes commented
> is it expected that this device expands the circuit differently? the results look completely different, just wondering if that's alright for the results being demonstrated.

@timmysilv Thanks for keeping this up to date, it's a challenging one to maintain! This is no problem, the protocol works by generating random SU(4) *and* random permutations, which is why it looks so different. It looks like the results at the end are sensible (log2(QV) = 3), though it is probably worth checking that the QV of Oslo is, in fact, reported as 8 and not significantly higher or lower. 

Side note: there are numerous explicit references to the previous device (Ourense) in the demo, which would have to be updated in addition to numerical results.

2023-02-21 19:47 UTC, mudit2812 commented
@glassnotes `ibm_oslo` has QV=32 😅

2023-02-21 20:14 UTC, mudit2812 commented
I might have approved prematurely. As @glassnotes pointed out, there are a lot of references to `ourense` in the demo itself. Moreover, the QV is incorrect as `ibm_oslo` has QV 32, so our result should be `log2(32)=5`. I think that can be fixed by changing the number of wires to 7.

2023-02-21 20:21 UTC, glassnotes commented
> I might have approved prematurely. As @glassnotes pointed out, there are a lot of references to `ourense` in the demo itself. Moreover, the QV is incorrect as `ibm_oslo` has QV 32, so our result should be `log2(32)=5`. I think that can be fixed by either changing `num_wires` to 7, or changing the backend to a 5-qubit device.

Part of the reason for the discrepancy is that we're using a simulated noise model in the demo, and only 1000 shots.

But @mudit2812 as you point out, `num_wires` should be 7. QV takes into account the compilation process, which involves qubit placement and routing. If not enough wires are specified, it might not be able to access to the "good" qubits and full connectivity of the hardware. I don't think that will totally account for the jump from 3 to 5, but it should at least help.

2023-02-21 21:27 UTC, rmoyard commented on demonstrations/quantum_volume.py
> +dev_ourense = qml.device("qiskit.ibmq", wires=5, backend="ibm_oslo")
Change to Lima, same # qubits, same connectivity and same QV!

2023-02-21 22:15 UTC, mudit2812 reviewed
This looks much better. Thanks for the changes! Some of the documentation needs minor updates, but other than that, this looks good!

2023-02-21 22:15 UTC, mudit2812 commented on demonstrations/quantum_volume.py
> +#     m = 5: 0.639500 below threshold.
Since the mena probability for `m=5` is below the threshold, I would update the documentation below (lines 710-719) accordingly as well, as they currently state that ALL noisy device probabilities are above the threshold.

2023-02-21 22:16 UTC, mudit2812 requested changes
I think this is ready to merge once the updates from my review are added

2023-02-22 17:07 UTC, mudit2812 approved these changes
Thanks for the changes @rmoyard

2023-02-22 18:03 UTC, timmysilv approved these changes
looks great!

2023-02-22 18:14 UTC, merged