Add demo on equivariant graph embedding
PennyLaneAI/qml pull request #714
Opened 2023-03-09 17:08 UTC by mariaschuld

**Title:** A permutation equivariant graph embedding

**Summary:** Implements an ansatz proposed in https://arxiv.org/pdf/2205.06109.pdf. Adds more material on geometric quantum ML to the demos.

2023-03-15 09:47 UTC, mariaschuld commented
I am a bit confused about this : 
![Screenshot from 2023-03-15 11-43-42](https://user-images.githubusercontent.com/23052011/225271638-e66b4d29-1c24-4276-bb0b-d06d8fd65b83.png)

2023-03-15 12:59 UTC, mariaschuld commented
One thing todo: use seed for networkx so that graphs do not look weird

2023-03-16 18:49 UTC, KetpuntoG reviewed
Very good job 😊 very well explained and easy to follow! 🚀
Here are a few comments. 
As soon as you work on them I will assign another person to do a second review

2023-03-16 18:49 UTC, KetpuntoG commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +# .. figure:: ../demonstrations/equivariant_graph_embedding/circuit.png
Here I would clarify what is epsilon and alpha since the paper's notation is not the same as defined above. If you prefer I can draw the circuit by hand writing `a_ij` for epsilon and `a_ii` for alpha.

2023-03-16 18:49 UTC, KetpuntoG commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +
if you import matplotlib and set the line `plt.show()`at the end, the strange output of the graph will disappear

2023-03-16 18:49 UTC, KetpuntoG commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +def eqc(A, observable, betas, gammas):
could you put more self-explanatory names? even if it is a bit longer

2023-03-16 18:49 UTC, KetpuntoG commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +
Now in demos we include the author. We already have some demos with your name so you just have to include the final lines:

```python
# About the author
# -----------------
# .. include:: ../_static/authors/maria_schuld.txt
```

2023-03-16 18:49 UTC, KetpuntoG commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +# not an *invariant* one! The final state before measurement is only the same if we
Great! It's a very nice result but it seemed short for me in this concluding line. Do you think it would be good to extend a little more even if it is repetitive? 
"because as we had said, invariant means ... and equivariant ... therefore ..."

2023-03-16 18:49 UTC, KetpuntoG commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +# any simultateous permutation of the rows and columns of this matrix represents the same graph:
```suggestion
# any simultaneous permutation of the rows and columns of this matrix represents the same graph: 
```

2023-03-23 06:30 UTC, mariaschuld commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +    for i,j in zip(range(len(permutation)),permutation):
Of course, I was overthinking it!

2023-03-23 06:31 UTC, mariaschuld commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +#     P_{\pi} |q_1,...,q_n \rangle = |q_{\pi(1)}, ... q_{\pi(n)} \rangle
You are right!

2023-03-23 06:39 UTC, mariaschuld commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +#     P_{\pi} |q_1,...,q_n \rangle = |q_{\pi(1)}, ... q_{\pi(n)} \rangle
```suggestion
#     P_{\pi} |q_1,...,q_n \rangle = |q_{\textit{perm}_{\pi}(1)}, ... q_{\textit{perm}_{\pi}(n)} \rangle
# 
#  The function :math:`\text{perm}_{\pi}` maps each index to the permuted index according to :math:`\pi`. 
#    
```

2023-03-23 06:44 UTC, mariaschuld commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +# embedding suggested in `Skolik et al. (2022) <https://arxiv.org/pdf/2205.06109.pdf>`_ which has this structure:
```suggestion
# embedding suggested in `Skolik et al. (2022) <https://arxiv.org/pdf/2205.06109.pdf>`_ which has this structure (see Figure 4 in the paper):
```

2023-03-23 06:45 UTC, mariaschuld commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +# .. figure:: ../demonstrations/equivariant_graph_embedding/circuit.png
I had it in the caption but somehow the caption did not show. Sorry!

2023-03-23 06:47 UTC, mariaschuld commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +# :math:`\beta`, :math:`\gamma` are variational parameters.
```suggestion
#    Permutation-invariant embedding circuit that we are implementing in this demo. Figure taken from `Skolik et al. (2022) <https://arxiv.org/pdf/2205.06109.pdf>`_. The :math:`\epsilon` are our edge weights while :math:`\alpha` describe the node weights, and the :math:`\beta`, :math:`\gamma` are variational parameters.
# 
```

2023-03-23 06:48 UTC, mariaschuld commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +    return qml.expval(observable)
```suggestion
def eqc(adjacency_matrix, observable, trainable_betas, trainable_gammas):
    """Circuit that uses the permutation equivariant embedding"""
    
    perm_equivariant_embedding(adjacency_matrix, trainable_betas, trainable_gammas)
    return qml.expval(observable)
```

2023-03-23 06:49 UTC, mariaschuld commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +qml.draw_mpl(eqc, decimals=2)(A, observable, betas, gammas)
```suggestion
qml.draw_mpl(eqc, decimals=2)(A, observable, betas, gammas)
plt.show()
```

2023-03-23 06:50 UTC, mariaschuld commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +print("Model output for A:", resA)
```suggestion
result_A = eqc(A, observable, betas, gammas)
print("Model output for A:", result_A)
```

2023-03-23 06:50 UTC, mariaschuld commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +print("Model output for permutation of A: ", resAperm)
```suggestion
result_Aperm = eqc(A_perm, observable, betas, gammas)
print("Model output for permutation of A: ", result_Aperm)
```

2023-03-23 07:01 UTC, mariaschuld commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +# not an *invariant* one! The final state before measurement is only the same if we
```suggestion
# Why are the two values different? Well, we constructed an *equivariant* ansatz, 
# not an *invariant* one! Remember, an *invariant* ansatz means that embedding a permutation of 
# the adjacency matrix leads to the same state as an embedding of the original matrix. 
# An *equivariant* ansatz embeds the permuted adjacency matrix into a state where the qubits 
# are permuted as well. The final state before measurement is only the same if we 
```

2023-03-23 07:07 UTC, mariaschuld commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +#
```suggestion
#
# References
# ----------
#
# 1. Andrea Skolik, Michele Cattelan, Sheir Yarkoni,Thomas Baeck and Vedran Dunjko (2022). Equivariant 
#    quantum circuits for learning on weighted graphs. `arXiv:2205.06109
#    <https://arxiv.org/abs/2205.06109>`__.
# 
# # .. [#Nguyen2022]
#
# 2. Quynh T. Nguyen, Louis Schatzki, Paolo Braccia, Michael Ragone,
#   Patrick J. Coles, Frédéric Sauvage, Martín Larocca, and M. Cerezo (2022).
#   Theory for Equivariant Quantum Neural Networks.
#   `arXiv:2210.08566 <https://arxiv.org/abs/2210.08566>`__
# 
# About the author 
# -------------------------
# .. include:: ../_static/authors/maria_schuld.txt
```

2023-03-23 16:05 UTC, mariaschuld commented
I think I am ready for re-review. One small known issue is still the padding in the networkx plot, but I'm working on it!

2023-03-23 19:48 UTC, KetpuntoG commented
> I think I am ready for re-review. One small known issue is still the padding in the networkx plot, but I'm working on it!

Great! Looks great to me! I will pass the demo to a second reviewer 🚀

2023-04-06 21:12 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +# .. figure:: ../demonstrations/equivariant_graph_embedding/circuit.png
It still isn't there 😢

2023-04-06 21:13 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +#
I se that it's here. It may be a Sphinx shenanigan

2023-04-06 21:15 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +#
Took me a little while to understand what "simultaneous perturbation" is. Isn't the easier intuition that changing the node labels changes the matrices as well? In any case, we could simply add a line on what this means, or even in the caption of the figure. 😛

2023-04-06 21:16 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +
Some nodes in the plot appear chopped ✂️ !

2023-04-06 21:23 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +#
Would be great to link qml.Permute to the docs! There's a sphinx command, something like :func:`~penny.Permute`

2023-04-06 21:25 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +#     |\phi(A) \rangle = P_{\pi}|\phi(\pi(A))\rangle \;\; \text{ for all } \pi
**Applies throughout.** We've been consistent in punctuating equations in demos. While some still debate whether they should be, let's just err on the side of caution and punctuate 😀.

2023-04-06 21:26 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +# Taking the example of a twitter user retweet network, the nodes would be users,
```suggestion
# Taking the example of a Twitter user retweet network, the nodes would be users, 
```

2023-04-06 21:27 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +# Et voila!
```suggestion
# Et voilà!
```

2023-04-06 21:27 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +# Et voila!
But never mind if it doesn't render!

2023-04-06 21:29 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +
Let's improve on the thumbnail 😛 😬

2023-04-06 21:29 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +# Taking the example of a twitter user retweet network, the nodes would be users,
:doge:

2023-04-06 21:31 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +"""
@KetpuntoG are we still requiring r"""?

2023-04-06 21:38 UTC, alvaro-at-xanadu requested changes
An amazing demo! Very minor fixes, although I'm confused in one part. I thought the point was to dump all the permutations in one equivalence class through the embedding. But then, to recover the correct expectation value, you need to know the particular permutation that takes one element in the class to the other! I understand that the point is to see that it works, but the I feel that the usefulness of the embedding is moot?

2023-04-06 22:35 UTC, josh146 commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +#
```
:func:`~pennylane.Permute`
```

_should_ work 🤞

2023-04-13 09:19 UTC, mariaschuld commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +"""
```suggestion
r"""
```

2023-04-13 09:20 UTC, mariaschuld commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +
You don't like it? :) Any suggestions?

2023-04-13 09:34 UTC, mariaschuld commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +
Wait I am confused now - I think I just changed this randomly from the template I used. This should be the name of the thumb picture used when adding the demo in `demos_qml.rst`, right?

Do you not like that picture, or was it just the wrong path?

2023-04-13 09:48 UTC, mariaschuld commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +# Taking the example of a twitter user retweet network, the nodes would be users,
Good catch

2023-04-13 09:49 UTC, mariaschuld commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +
Eish, still!

2023-04-13 09:50 UTC, mariaschuld commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +#
I can never remember the syntax :) Thanks!

2023-04-13 14:58 UTC, mariaschuld commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +# .. figure:: ../demonstrations/equivariant_graph_embedding/circuit.png
I turned it into normal text, enough fighting with Sphinx. (I am also sure it DID work before!)

2023-04-17 08:51 UTC, mariaschuld commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +# The :math:`\epsilon` are our edge weights while :math:`\alpha` describe the node weights, and the :math:`\beta`, :math:`\gamma` are variational parameters.
```suggestion
# The image can be found in `Skolik et al. (2022) <https://arxiv.org/pdf/2205.06109.pdf>`_ and shows one layer of the circuit.  
# The :math:`\epsilon` are our edge weights while :math:`\alpha` describe the node weights, and the :math:`\beta`, :math:`\gamma` are variational parameters.
```

2023-04-17 08:52 UTC, mariaschuld commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +plt.margins(x=1)
```suggestion
plt.margins(x=2)
```

2023-04-18 08:29 UTC, mariaschuld commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +ax2.margins(x=1)
```suggestion
ax1.margins(x=2)
ax2.margins(x=2)
```

2023-04-18 14:27 UTC, mariaschuld commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +ax2.margins(x=2)
```suggestion
ax1.set_xlim([1.2*x for x in ax1.get_xlim()])
ax2.set_xlim([1.2*x for x in ax2.get_xlim()])
```

2023-04-19 06:27 UTC, mariaschuld commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +
Who must I reach out to?

2023-04-19 06:27 UTC, mariaschuld commented on demonstrations/tutorial_equivariant_graph_embedding.py
> +
It works!

2023-04-19 06:29 UTC, mariaschuld commented
Ready for final review, thanks for the helpful comments :) 

The  two outstanding things are to get a professional thumbnail, and to add the date once it goes live.

Must I reach out to someone about the image?

2023-04-27 15:30 UTC, KetpuntoG commented
Thank you very much Maria, a great demo 😄
 From this point on I'll take care of the thumbnail and the date. 
 Great work here 🚀

2023-07-14 13:30 UTC, alvaro-at-xanadu approved these changes

2023-07-14 14:02 UTC, KetpuntoG approved these changes
Good job here 😊

2023-07-14 14:03 UTC, merged