Contextuality demo
PennyLaneAI/qml pull request #719
Opened 2023-03-17 17:13 UTC by josephbowles

Demo: Contextuality and inductive bias in quantum machine learning

This is a demo for my recent paper https://arxiv.org/abs/2302.01365 

In the demo we study the toy learning problem described in the paper, and build and train a quantum model that encodes the relevant inductive bias. The model is shown to outperform a 'generic' quantum model that does not encode this bias.

The demo is not focused much on contextuality (because it would require a lot of explanation), but rather focuses on the type of learning problem (inspired from contextuality) that is presented in the paper. 

JAX is used for vectorization and JIT compilation.

2023-03-24 15:58 UTC, KetpuntoG reviewed
Nice demo Joseph! That's a very clear example to work with 😄 Here I leave you a few comments. On the other hand, as the demo is called this way it would be nice if you could define a bit more in depth each of these concepts. A short paragraph to give the idea would be enough

2023-03-24 15:58 UTC, KetpuntoG commented on demonstrations/tutorial_contextuality.py
> +    n0 = jnp.matmul(jnp.matmul(X[0], A01), X[1]) + jnp.matmul(jnp.matmul(X[0], A02), X[2])
it would help to write a short comment saying that n0 here is n0_wins - n0_lose

2023-03-24 15:58 UTC, KetpuntoG commented on demonstrations/tutorial_contextuality.py
> +# The data set
this title could be improved:

defining the dataset and its implementation

or something like this

2023-03-24 15:58 UTC, KetpuntoG commented on demonstrations/tutorial_contextuality.py
> +
There is a weird CPU/GPU output here. I think that if you write:

`jax.config.update('jax_platform_name', 'cpu')
`

after import Jax, you solve this issue

2023-03-24 15:58 UTC, KetpuntoG commented on demonstrations/tutorial_contextuality.py
> +X, Y, P = generate_data(1500)
if so, you could also print the first terms of Y to make it clear

2023-03-24 15:58 UTC, KetpuntoG commented on demonstrations/tutorial_contextuality.py
> +expvals = 2 * P - 1  # convert probs to expvals
Hmm it is not very clear to me. From the way it was defined before, I thought P was a vector , now I see it as a matrix 🤔

2023-03-24 15:58 UTC, KetpuntoG commented on demonstrations/tutorial_contextuality.py
> +    n2 = jnp.matmul(jnp.matmul(X[2], A20), X[0]) + jnp.matmul(jnp.matmul(X[2], A21), X[1])
Actually it is curious that there is no need to indicate transpositions here. it may be ok but i am writing this just in case

2023-03-24 15:58 UTC, KetpuntoG commented on demonstrations/tutorial_contextuality.py
> +# This kind of reasoning is an example of geometric quantum machine
You can also link this demo

2023-03-24 15:58 UTC, KetpuntoG commented on demonstrations/tutorial_contextuality.py
> +    qml.PauliRot(weights, "XX", wires=wires)
Is this equivalent to e^i theta(xx + yy + zz)? No need to do any troterization?

2023-03-24 15:58 UTC, KetpuntoG commented on demonstrations/tutorial_contextuality.py
> +
I think that the output that appears is not intentional, to delete it I think it is enough to write plt.show() at the end of the cell.

2023-03-24 15:58 UTC, KetpuntoG commented on demonstrations/tutorial_contextuality.py
> +# That is all for this demo. In the paper, it is also shown how models of
could you include this paragraph under the heading conclusion?
In the conclusion, although it sounds a bit repetitive, we usually summarize quickly what we have seen in the demo. It is common to say at the end where to learn more. This is the perfect place to comment on what they will find in the paper

2023-03-24 15:58 UTC, KetpuntoG commented on demonstrations/tutorial_contextuality.py
> +#
Please use the format of the other demos to be able to link easily to the bio.

2023-03-24 15:58 UTC, KetpuntoG commented on demonstrations/tutorial_contextuality.py
> +*Author: Joseph Bowles — Posted: 21 March 2023*
Would you say that this demo is related to any other demo? Maybe the geometric machine learning demo? It is usually indicated here in the header. Take a look at the header

example:
```
.. related::
    tutorial_quantum_chemistry Quantum chemistry with PennyLane
    tutorial_vqe A brief overview of VQE
  ```

2023-03-24 15:58 UTC, KetpuntoG commented on demonstrations/tutorial_contextuality.py
> +# player 2 then necessarily player 2 loses to player 1. This imples
```suggestion
# player 2 then necessarily player 2 loses to player 1. This implies
```

2023-04-17 13:54 UTC, josephbowles commented on demonstrations/tutorial_contextuality.py
> +# quantum machine learning* [1] by
Have changed the links. And haha I thought the same about the third person but I find it a bit weird to say 'be me'. I changed the language a bit in this paragraph to use 'we' rather than 'the authors' though. 

and thanks for such a thorough review!!

2023-04-17 13:56 UTC, josephbowles commented on demonstrations/tutorial_contextuality.py
> +# -  Construct a train a quantum model that is tailored to the symmetries
Have implemented all commit suggestions in the new version.

2023-04-17 13:56 UTC, josephbowles commented on demonstrations/tutorial_contextuality.py
> +import jax
ok done!

2023-04-17 13:56 UTC, josephbowles commented on demonstrations/tutorial_contextuality.py
> +# This demo is based on the article *Contextuality and inductive bias in
Makes sense. Have rewritten a bit.

2023-04-17 13:58 UTC, josephbowles commented on demonstrations/tutorial_contextuality.py
> +# -  If two players play the same action, the one who plays their special
Dueling. Have tried to make it clearer: I say 'The actions of the players are then compared pairwise with the following rules'

2023-04-17 13:58 UTC, josephbowles commented on demonstrations/tutorial_contextuality.py
> +
thanks

2023-04-17 14:06 UTC, josephbowles commented on demonstrations/tutorial_contextuality.py
> +# .. math:: \mathbb{E}(y_k) = \frac{n^k_{\text{win}}-n^k_{\text{lose}}}{2}
The 2 is there to make sure the expectation value is bounded in [-1,1]. For example, a player could beat two players and lose to none. 

E is the definition of what they win on average (until now I haven't specified what the payoffs are, only the rules for who beats whom). What they win on average is a function of the number of players they beat in the round.

I agree this can be quite confusing, but I'm not sure how to make it clearer.

2023-04-17 14:06 UTC, josephbowles commented on demonstrations/tutorial_contextuality.py
> +# ‘special’ action. For player 1 it is R, for player 2 it is P and for
indeed, thanks

2023-04-17 14:07 UTC, josephbowles commented on demonstrations/tutorial_contextuality.py
> +#
have made it clearer

2023-04-17 14:11 UTC, josephbowles commented on demonstrations/tutorial_contextuality.py
> +# of a *strategy*. A strategy is a list of probabilities that a player
According to the wiki page (https://en.wikipedia.org/wiki/Zero-sum_game) they are called strategies. Did you see them called policies somewhere?

2023-04-17 14:12 UTC, josephbowles commented on demonstrations/tutorial_contextuality.py
> +def get_strat_mats(N):
changed

2023-04-17 14:12 UTC, josephbowles commented on demonstrations/tutorial_contextuality.py
> +    n0 = jnp.matmul(jnp.matmul(X[0], A01), X[1]) + jnp.matmul(jnp.matmul(X[0], A02), X[2])
good point, have changed

2023-04-17 14:13 UTC, josephbowles commented on demonstrations/tutorial_contextuality.py
> +X, Y, P = generate_data(1500)
Have tried to make it clearer. and I print the first elements now. is that better?

2023-04-17 14:13 UTC, josephbowles commented on demonstrations/tutorial_contextuality.py
> +
thanks

2023-04-17 14:16 UTC, josephbowles commented on demonstrations/tutorial_contextuality.py
> +    n2 = jnp.matmul(jnp.matmul(X[2], A20), X[0]) + jnp.matmul(jnp.matmul(X[2], A21), X[1])
oh my indeed I think you are correct! Have changed this. Think this is an issue for the paper as well then. Fortunately it seems the results are basically the same :p

2023-04-17 14:16 UTC, josephbowles commented on demonstrations/tutorial_contextuality.py
> +# This kind of reasoning is an example of geometric quantum machine
done

2023-04-17 14:16 UTC, josephbowles commented on demonstrations/tutorial_contextuality.py
> +    qml.PauliRot(weights, "XX", wires=wires)
Can't do sums of Pauli words in PaulRot

2023-04-17 14:17 UTC, josephbowles commented on demonstrations/tutorial_contextuality.py
> +# That is all for this demo. In the paper, it is also shown how models of
Good idea, have done that.

2023-04-17 14:17 UTC, josephbowles commented on demonstrations/tutorial_contextuality.py
> +*Author: Joseph Bowles — Posted: 21 March 2023*
have added the GQML one

2023-04-28 11:50 UTC, ikurecic requested changes
Here are some minor copy editing changes and suggestions. Everything else looks good to me. :)

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# We can also define the matrices ``A10``, ``A20``, ``A21``. Since
```suggestion
# We can also define the matrices ``A10``, ``A20``, and ``A21``. Since
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# switching the players corresponds to taking the transpose matrix and
```suggestion
# switching the players corresponds to taking the transpose matrix, and
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# For example, a strategy for player k is a
```suggestion
# For example, a strategy for player :math:`k` is a
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# .. math:: x_k=(P(a_k=R), P(a_k=P), P(a_k=S))
```suggestion
# .. math:: x_k=(P(a_k=R), P(a_k=P), P(a_k=S)),
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# into a strategy matrix X
```suggestion
# into a strategy matrix :math:`X`:
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +#        \end{pmatrix}
```suggestion
#        P(a_2=R) & P(a_2=P) & P(a_2=S) 
#        \end{pmatrix}.
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# .. math:: P(y_k=+1\vert X) = \frac{\mathbb{E}(y_k\vert X)+1}{2} =  \frac{(\mathbb{E}[n_{\text{wins}}^k - n_{\text{lose}}^k])/2+1}{2}
```suggestion
# .. math:: P(y_k=+1\vert X) = \frac{\mathbb{E}(y_k\vert X)+1}{2} =  \frac{(\mathbb{E}[n_{\text{wins}}^k - n_{\text{lose}}^k])/2+1}{2} .
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# Note that since strategies are probabilistic mixtures of actions, our
```suggestion
# Note that, since strategies are probabilistic mixtures of actions, our
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# We can verify this using the payoff probability matrix ``P`` that we
```suggestion
# We can verify this using the payoff probability matrix :math:`P` that we
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# strategy matrices and payoff values, however we don’t know what the
```suggestion
# strategy matrices and payoff values, but we don't know what the
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# (we’ll write them as :math:`\lambda`), that comprise our quantum states.
```suggestion
# (we'll write them as :math:`\lambda`), that comprise our quantum states.
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# Can we learn the rock, paper scissors game from this data? More
```suggestion
# Can we learn the rock-paper-scissors game from these data? More
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# :math:`X_{\text{test}}` our task is to sample from the three
```suggestion
# :math:`X_{\text{test}}`, our task is to sample from the three
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# Note we are not asking to sample from the joint distribution
```suggestion
# Note that we are not asking to sample from the joint distribution
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# :math:`P(\vec{y}\vert X_{\text{test}})` but the three marginal
```suggestion
# :math:`P(\vec{y}\vert X_{\text{test}})`, but the three marginal
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# Here we describe a simple three qubit model to tackle this problem.
```suggestion
# Here we describe a simple three-qubit model to tackle this problem.
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# the data we want our model to satisfy
```suggestion
# the data, we want our model to satisfy
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +#   on how this looks in practice. Luckily for us quantum theory is a
```suggestion
#   may therefore hinder their performance (see `our paper <https://arxiv.org/abs/2302.01365>`__ for more details
#   on how this looks in practice). Luckily for us, quantum theory is a
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# :math:`\vert \psi(\alpha,\theta,X)\rangle` the zero sum condition will
```suggestion
# :math:`\vert \psi(\alpha,\theta,X)\rangle`, the zero-sum condition will
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# paper. We’ll first look at the parameterised unitary :math:`V_{\alpha}`,
```suggestion
# Let’s see how we can create a model class that satisfies this. (For
# precise details on the structure of the model, check out Figure 6 in 
# `our paper <https://arxiv.org/abs/2302.01365>`__). We’ll first look at the parameterised unitary :math:`V_{\alpha}`,
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# The second unitary is a *bias invariant layer*: it preserves the value
```suggestion
# The second unitary is a *bias-invariant layer*: it preserves the value
```
I understand you may not write it like this 'usually', but this would be the correct way. So your choice. :)

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# of :math:`\langle Z_0+Z_1+Z_2 \rangle` for all input states into the
```suggestion
# of :math:`\langle Z_0+Z_1+Z_2 \rangle` for all input states of the
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# must commute with the operator :math:`Z_0+Z_1+Z_2`. For example the
```suggestion
# must commute with the operator :math:`(Z_0+Z_1+Z_2)`. For example, the
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# operator :math:`X\otimes X + Y\otimes Y + Z\otimes Z` (on any pair of
```suggestion
# operator :math:`(X\otimes X + Y\otimes Y + Z\otimes Z)` (on any pair of
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# qubits) commutes with :math:`Z_0+Z_1+Z_2` and so a valid parameterised
```suggestion
# qubits) commutes with :math:`(Z_0+Z_1+Z_2)` and so a valid parameterised
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# `demo <https://pennylane.ai/qml/demos/tutorial_geometric_qml.html>`__ for an awesome introduction to the subject).
```suggestion
# `PennyLane demo <https://pennylane.ai/qml/demos/tutorial_geometric_qml.html>`__ for an awesome introduction to the subject).
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# bias invariant layer: note that all the generators commute with
```suggestion
# bias-invariant layer: note that all the generators commute with
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +    The full bias invariant layer.
```suggestion
    The full bias-invariant layer.
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# jax vectorisation, we vectorise over the data input (the second argument)
```suggestion
# JAX vectorisation, we vectorise over the data input (the second argument)
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# number of parameters (46 vs 45 parameters).
```suggestion
# number of parameters (46 vs. 45 parameters).
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# hereon since these values have been cached for JIT compilation.
```suggestion
# here on, since these values have been cached for JIT compilation.
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# labels given the data
```suggestion
# labels given the data.
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# :math:`k` label from the model, :math:`y_i^{(k)}` is the kth element
```suggestion
# :math:`k` label from the model, :math:`y_i^{(k)}` is the :math:`k`-th element
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# the size of the training dataset. We remark that
```suggestion
# the size of the training data set. We remark that
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# As generative modeling in QML progresses, we can hope however that
```suggestion
# As generative modeling in quantum machine learning progresses, we can hope, however, that
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# data distribution and the model distribution
```suggestion
# data distribution and the model distribution:
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# To optimise the model we make use of the JAX optimization library optax.
```suggestion
# To optimise the model we make use of the JAX optimization library `optax`.
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# We will use the adam gradient descent optimizer.
```suggestion
# We will use the Adam gradient descent optimizer.
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# We are now ready to generate a dataset and optimize our models!
```suggestion
# We are now ready to generate a data set and optimize our models!
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# In this demo we have constructed a dataset whose structure is
```suggestion
# In this demo we have constructed a data set with a structure that is
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# considerations like this should be at the front of one’s mind when
```suggestion
# considerations like this should be at the front of one's mind when
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# That is all for this demo. In the paper, it is also shown how models of
```suggestion
# That is all for this demo. In our paper [#paper]_, it is also shown how models of
```

2023-04-28 11:50 UTC, ikurecic commented on demonstrations/tutorial_contextuality.py
> +# link between contextuality and QML, check out the paper.
```suggestion
# link between contextuality and QML, check out the full paper.
```

2023-04-28 11:50 UTC, ikurecic requested changes
Here are some minor copy editing changes and suggestions. Everything else looks good to me. :)

2023-05-12 09:50 UTC, josephbowles commented
> Here are some minor copy editing changes and suggestions. Everything else looks good to me. :)

Thanks @ikurecic :D

2023-05-12 19:04 UTC, KetpuntoG commented
A problem has been detected with the jax version (it is not a problem of this demo). Next week it will be fixed :)

2023-06-12 08:25 UTC, josephbowles commented on demonstrations/tutorial_contextuality.py
> +# .. math:: \mathbb{E}(y_k) = \frac{n^k_{\text{win}}-n^k_{\text{lose}}}{2}
\mathbb{E} already has a definition as the expected value of a random variable, so I don't think we need the definition symbol here.

2023-06-16 07:23 UTC, ikurecic approved these changes
👌
(Guillermo is on holiday at the moment, but at least I can leave this as a lgtm from my end.)

2023-09-01 19:41 UTC, KetpuntoG approved these changes
🚀 Really cool topic!

2023-09-01 19:41 UTC, merged