Jsonschema poc
PennyLaneAI/qml pull request #726
Opened 2023-03-29 20:26 UTC by doctorperceptron

Adds a (JSON Schema)[https://json-schema.org/] defining the structure of the new metadata files for demos. I implemented the schema as defined in `demonstrations_metadata.md`.

New metadata files for demos can be validated against the schema manually via:
```bash
pip install check-jsonschema 'jsonschema[format]'
check-jsonschema --schemafile ./metadata_schemas/demo.metadata.schema.0.1.0.json ./demonstrations/<your_demo_name>.metadata.json
```

I also created an Action to validate all the metadata files on PRs. We should consider combining this with the `build` Action going forward if it's something we want to keep.

NOTE: I started cleaning up some fields (e.g. `date-time` ones and `categories`) to be consistent with the schema. A lot of the current metadata files don't pass validation because they either lack references entirely, or are missing reference fields that are required.

2023-06-15 12:26 UTC, BM7878 requested changes

2023-06-15 12:26 UTC, BM7878 commented on metadata_schemas/demo.metadata.schema.0.1.0.json
> +          "enum": ["Getting Started", "Optimization", "QML", "Quantum Chemistry", "Quantum Computing", "Community"]
We'll need to update these to the new categories, which are in `demonstrations/demonstrations-categories.metadata.json`.

2023-06-15 12:26 UTC, BM7878 commented on metadata_schemas/objects/author.schema.0.1.0.json
> +    "title": "Authors",
'Author Object'?

2023-06-15 12:26 UTC, BM7878 commented on metadata_schemas/objects/preview.image.schema.0.1.0.json
> +            "enum": ["thumbnail"]
This can now also be 'hero_image' as well.

2023-06-16 14:59 UTC, Mandrenkov commented on metadata_schemas/demo.metadata.schema.0.1.0.json
> +          "enum": ["Getting Started", "Optimization", "QML", "Quantum Chemistry", "Quantum Computing", "Community"]
Done!

2023-06-16 15:06 UTC, Mandrenkov commented on metadata_schemas/objects/preview.image.schema.0.1.0.json
> +            "enum": ["thumbnail"]
Thanks! This can also be `large_thumbnail` too, right?

2023-06-16 15:09 UTC, Mandrenkov commented on metadata_schemas/objects/author.schema.0.1.0.json
> +    "title": "Authors",
Good catch! 🎣

2023-06-16 18:52 UTC, Mandrenkov commented
Thanks for the review, @BM7878! 🚀 

Note that there are still a number of validation errors. These are:

1. Two demos (**Adjoint Differentiation** and **Multiclass margin classifier**) are not associated with any categories.
2. One demo (**The stochastic parameter-shift rule**) lists a type of related content as `glossary_entry`.
3. Some demos are missing one or more of the following related content fields:
    * `authors`
    * `id`
    * `title`
    * `type`
    * `year`
4. Some demos have blank strings (`""`) for one or more of the following related content fields:
    * `authors`
    * `id`
    * `title`
    * `year`

What should we do to resolve these issues? Try to fix the demos? Or adapt the schema accordingly?

2023-06-16 19:09 UTC, Mandrenkov commented
Oh, and another (minor) issue is that some of the canonical URLs only include the path component e.g.
```
/qml/demos/ahs_aquila
```
instead of the full URL
```
https://pennylane.ai/qml/demos/ahs_aquila
```
Is this intentional?

2023-06-16 19:53 UTC, josh146 commented
> Two demos (Adjoint Differentiation and Multiclass margin classifier) are not associated with any categories.

Oh I can comment on this one. This is because we want the demos on the website, but we don't want them appearing within any of the categories.

For Adjoint diff, this is 'supplementary' information that is linked from one demo.

For Multiclass, I believe there is a bug in the demo, and we want to 'hide' it from the demos page without it coming down completely.

2023-06-16 20:12 UTC, doctorperceptron commented
> > Two demos (Adjoint Differentiation and Multiclass margin classifier) are not associated with any categories.
> 
> Oh I can comment on this one. This is because we want the demos on the website, but we don't want them appearing within any of the categories or carousels for end-users who are browsing.
> 
> For Adjoint diff, this is 'supplementary' information that is linked from one demo.
> 
> For Multiclass, I believe there is a bug in the demo, and we want to 'hide' it from the demos page without it coming down completely.

Maybe we could add something like a "Hidden" category? Allowing no category makes it tricky to enforce having a category for "regular" demos.

2023-07-19 19:46 UTC, rashidnhm commented on requirements-dev.txt
This PR was likely opened while the QML repo used requirements files, however it's been ported over to using Poetry. Would you be able to update this branch with the changes from master, and add these as a poetry dev group?

2023-07-19 22:12 UTC, Mandrenkov commented on requirements-dev.txt
Good call, @rashidnhm! I've created a Poetry group `metadata-validation` and updated the lock file.

2023-07-20 17:24 UTC, rashidnhm commented on .github/workflows/validate-demo-metadata.yml
> +
Let's add a concurrency group here as well so older buids are auto-cancelled.

```suggestion
concurrency:
  group: metadata-validation-${{ github.ref }}
  cancel-in-progress: true
```

2023-07-20 20:04 UTC, rashidnhm commented on pyproject.toml
> +
```suggestion

[tool.poetry.group.metadata-validation]
optional = true

```

So the metadata validation group isn't installed by default

2023-07-25 13:26 UTC, Mandrenkov commented
Looks like the CI is finally passing! 🥳 

Are there any other changes you would like to see, @BM7878 or @rashidnhm? The PR is still in need of an approval.

2023-07-25 13:33 UTC, BM7878 approved these changes

2023-07-25 13:34 UTC, BM7878 commented
All's good from my end!

2023-07-25 13:45 UTC, rashidnhm approved these changes

2023-07-25 13:45 UTC, rashidnhm commented on metadata_schemas/README.md
> +$ poetry run check-jsonschema --schemafile demo.metadata.schema.[VERSION].json ../demonstrations/*.metadata.json
Let's update this to exclude the metadata categories file

2023-07-25 13:51 UTC, Mandrenkov commented on metadata_schemas/README.md
> +$ poetry run check-jsonschema --schemafile demo.metadata.schema.[VERSION].json ../demonstrations/*.metadata.json
Good idea! 💡 

Instead of listing the complicated `find` command from the GitHub Actions workflow though, I chose to simplify the README to show how to validate a single metadata JSON file.

2023-07-25 14:01 UTC, merged