Update `qchem` datasets page for new molecules
PennyLaneAI/qml pull request #732
Opened 2023-04-11 04:37 UTC by obliviateandsurrender

We are extending the quantum chemistry datasets with new molecules. These changes need to be reflected on the page for users to see.

2023-04-11 20:39 UTC, DSGuala requested changes

2023-04-11 20:39 UTC, DSGuala commented on datasets_qchem.rst
> +    | ``basis_rot_groupings``    | tuple(list[``tensor_like``], list[list[\ :class:`~.pennylane.operation.Operator`]], list[``tensor_like``]])  | List of grouped Hamiltonian terms obstained using :fu
```suggestion
    | ``basis_rot_groupings``    | tuple(list[``tensor_like``], list[list[\ :class:`~.pennylane.operation.Operator`]], list[``tensor_like``]])  | List of grouped Hamiltonian terms obtained using :func:`~.pennylane.qchem.basis_rotation`                             |
```

2023-04-11 20:39 UTC, DSGuala commented on datasets_qchem.rst
> +Samples data obtained the optimized variational circuit with available Hamiltonian groupings.
```suggestion
Samples obtained from the optimized variational circuit with available Hamiltonian groupings.
```

2023-04-11 20:39 UTC, DSGuala commented on datasets_qchem.rst
> +    | ``fci_energy``             | ``float``                         | Ground state energy of the molecule obtained from exact diagonalization           |
```suggestion
    | ``fci_energy``             | ``float``                         | Ground-state energy of the molecule obtained from exact diagonalization           |
```

2023-04-13 15:40 UTC, DSGuala approved these changes
Looks good, approved as soon as the explanation of the available data is clear.

2023-04-13 18:19 UTC, obliviateandsurrender commented
[sc-36436]

2023-04-13 20:02 UTC, soranjh requested changes
Thanks @obliviateandsurrender, left some comments and suggestions.

2023-04-13 20:02 UTC, soranjh commented on datasets_qchem.rst
> +.. note::
It might be better to bring the note right after the title and before the table. Now, it is hard to see which data the note refers to.

2023-04-17 19:39 UTC, obliviateandsurrender commented on datasets_qchem.rst
> +and the correlation-consistent polarized valence-only basis set `CC-PVDZ`. For He\ :sub:`2` and H\ :sub:`3`\ :sup:`+`, data is
There was a bug in my xyzfile for `He2`. The data is only available for 6-31G. Updated the docs.

2023-04-17 19:40 UTC, obliviateandsurrender commented on datasets_qchem.rst
> +    | H\ :math:`_4`                | STO\ :math:`\text{-}`\3G     | 8            | | H\ :math:`_A-`\ H\ :math:`_B` :math:`\in\ [0.5, 1.3, 41]` Å,            |          N/A
No, not all of them are repulsive. I have added geometries for some of them and left the remaining ones as N/A.

2023-04-18 16:27 UTC, soranjh approved these changes

2023-04-18 16:27 UTC, soranjh commented on datasets_qchem.rst
> +    |                              | | 6\ :math:`\text{-}`\31G /  | | 8 /        | |                                                                         |
The range of bond lengths is not defined for 6-31G.

2023-04-18 16:27 UTC, soranjh commented on datasets_qchem.rst
> +    |                              | | 6\ :math:`\text{-}`\31G /  | | 8 /        | |                                                                         |
The range of bond lengths is not defined for 6-31G.

2023-04-18 18:38 UTC, merged