Qubo tutorial
PennyLaneAI/qml pull request #733
Opened 2023-04-11 07:24 UTC by alejomonbar

### Before submitting

Please complete the following checklist when submitting a PR:

- [x] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [x] Add a thumbnail link to your tutorial in `beginner.rst`, or if a
      QML implementation, in `implementations.rst`.

- [x] All QML tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**
The Quadratic Unconstrained Binary Optimization (QUBO)
**Summary:**
A tutorial to learn how to represent combinatorial optimization problems using the QUBO formulation. The method is used to represent the Knapsack problem as a QUBO and it is solved using the quantum approximate optimization algorithm.

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2023-04-12 19:14 UTC, KetpuntoG requested changes
Thank you very much for this new demo!😄 
I can see that there is a lot of work behind it 💪 
Here is a first round of comments. 
 I also share with you a brief document that I suggest you read to facilitate the review process.
 
[review.pdf](https://github.com/PennyLaneAI/qml/files/11215056/review.pdf)

2023-04-12 19:14 UTC, KetpuntoG commented on demonstrations/tutorial_QUBO.py
> +
Feel free to post the link to your QHack project as well if you like as possible aplication 😄

2023-04-17 18:27 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +
what about this:

Solving combinatorial optimization problems using quantum computing is one of those promising applications for the near term. But, why are combinatorial optimization problems even important? well, we care about them because we have useful applications that can be translated into combinatorial optimization problems, in fields such as logistics, finance, and engineering. But having useful applications is not enough, and it is here where the second ingredient comes in, combinatorial optimization problems are complex! and finding good solutions (classically) for large instances of them requires an enormous amount of computational resources 😮‍💨. 

In this demo, we will be using a quantum algorithm called the Quantum Approximate Optimization Algorithm (QAOA) to solve a combinatorial optimization problem. QAOA is an algorithm that leverages the power of quantum computers to find the ground state of a target Hamiltonian. We will show throughout this demo how to encode your combinatorial optimization problem into that target Hamiltonian.

2024-01-26 19:37 UTC, KetpuntoG commented on demonstrations/tutorial_QUBO.py
> +        # Loading the data from an execution on D-Wave Advantage
```suggestion
        df[method].to_json(f"/_static/demonstration_assets/QUBO/dwave_results_{method}.json")  # save the results
else:
    df = {}
    for method in ["slack", "unbalanced"]:
        df[method] = pd.read_json(f"/_static/demonstration_assets/QUBO/dwave_results_{method}.json")
        # Loading the data from an execution on D-Wave Advantage
```

2024-01-26 21:45 UTC, KetpuntoG commented on demonstrations/tutorial_QUBO.py
> +        # Loading the data from an execution on D-Wave Advantage
```suggestion
        df[method].to_json(f"QUBO/dwave_results_{method}.json")  # save the results
else:
    df = {}
    for method in ["slack", "unbalanced"]:
        df[method] = pd.read_json(f"QUBO/dwave_results_{method}.json")
        # Loading the data from an execution on D-Wave Advantage
```

2024-01-31 14:09 UTC, KetpuntoG reviewed
Good job @alejomonbar ! A topic that we certainly needed to have 🚀
As a general comment, the demo is very long so I have made some comments suggesting how to simplify it. Read all the comments before you start modifying them to see if the overview makes sense 💪

2024-01-31 14:09 UTC, KetpuntoG commented on demonstrations/tutorial_QUBO.py
> +######################################################################
Instead of making a comparison between unbalanced and slack, I would take one of the two. Think that this is the first time someone is working with QUBO and what they want is to see how it is solved from start to finish with one method. In my opinion, I would use the standard form (probably slack) and in the conclusion I would invite the user to read about the unbalanced method to improve the results.

2024-01-31 14:09 UTC, KetpuntoG commented on demonstrations/tutorial_QUBO.py
> +# ===========
```suggestion
# Conclusion
# ------------
```

2024-01-31 14:09 UTC, KetpuntoG commented on demonstrations/tutorial_QUBO.py
> +# ==========
```suggestion
# -----------
```

2024-01-31 14:09 UTC, KetpuntoG commented on demonstrations/tutorial_QUBO.py
> +
In the end what a user has to look at is the combination of the objects obtained and see that it matches the brute force calculation rather than simply looking at the energy value. That will give that feeling of having understood everything that a beginner will be looking for 😄

2024-01-31 14:09 UTC, KetpuntoG commented on demonstrations/tutorial_QUBO.py
> +#
Based on previous comments, the demo may have changed a lot so the conclusion should be updated.

2024-01-31 14:09 UTC, KetpuntoG commented on demonstrations/tutorial_QUBO.py
> +# optimization algorithms. 23–25. http://arxiv.org/abs/2211.13914
Take a look to other demo in order to follow the same format in the references

2024-02-03 05:26 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +import pennylane as qml
done

2024-02-03 05:27 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +# %matplotlib inline
done

2024-02-03 05:27 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +# .. math:: S = 2^0 s_0 + 2^1 s_1 + 2^2 s_2 + 2^3 s_3 + 2^4 s_4 + 2^5 s_5
done

2024-02-04 06:05 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +)
done

2024-02-04 06:18 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +# :math:`\mathrm{x} = \{x_0:⚽️ , x_1:💻, x_2:📸, x_3:📚, x_4:🎸\}` and multiply such variable for the
done

2024-02-04 06:26 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +# representation <https://en.wikipedia.org/wiki/Quadratic_unconstrained_binary_optimization>`__, i.e.,
done

2024-02-04 06:29 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +#    constraint right :math:`22 + S = 26 \rightarrow S = 4`.
donde

2024-02-04 06:33 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +#
I saw it renders well so I prefer to keep it

2024-02-06 10:55 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +# optimization algorithms. 23–25. http://arxiv.org/abs/2211.13914
I do not see a clear citation procedure on the different demos. Next time, having a general rule in the readme file could be much better. I tried to modify it accordingly.

2024-02-06 11:02 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +
done

2024-02-06 11:05 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +
done

2024-02-06 11:09 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +# We use QAOA `[1] <https://arxiv.org/pdf/1411.4028.pdf>`__ to find the solution to our Knapsack
I prefer to keep it. I know that is everywhere but the QAOA circuit is something that in the majority of cases is a black box. In this case, as the circuit is there better to have what it means QAOA

2024-02-06 11:11 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +######################################################################
The message I wanted to give in this demo is that the encoding is a big part of the solution. So if we don't have both approaches there is no comparison...

2024-02-06 11:15 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +
I think this is not the general case. Maybe adding an extra sentence to indicate that, but I consider the plot meaningful.

2024-02-06 14:18 UTC, KetpuntoG commented on demonstrations/tutorial_QUBO.py
> +# `**unbalanced penalization**<https://arxiv.org/pdf/2211.13914.pdf>`_ , but we present this method
I would say here we should remove * too. Otherwise the link will not render correctly

2024-02-06 14:19 UTC, KetpuntoG commented on demonstrations/tutorial_QUBO.py
> +######################################################################
Okey, I see your point 👍

2024-02-06 14:48 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +# `**unbalanced penalization**<https://arxiv.org/pdf/2211.13914.pdf>`_ , but we present this method
done

2024-02-07 16:32 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +r"""The Quadratic Unconstrained Binary Optimization (QUBO)
```suggestion
r"""Quadratic Unconstrained Binary Optimization (QUBO)
```

2024-02-07 22:21 UTC, alvaro-at-xanadu requested changes
Hi @alejomonbar. 

I've checked the first section of the demo and so far so good! I think it'll become a valuable resource for everyone. Here are some grammar and style fixes, and also a few comments on notation, and wherever I saw typos I tried to point them out. 

It's a super long demo and it'll take me longer to go through than usual, with QHack knocking at our door, but I'll try to look at the next sections in the next few days.

Good job! 🚀

2024-02-07 22:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# expression just when the condition is satisfied the term inside the parenthesis is zero.
```suggestion
# expression, the condition is satisfied only when the term inside the parentheses is zero.
```

2024-02-07 22:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# always fulfilled.
```suggestion
# :math:`\lambda` is a penalization coefficient that we must tune to make that the constraint will always
# be fulfilled.
```

2024-02-07 22:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +#
Agree with @KetpuntoG. We should change this, it's too long. We always avoid a scroll bar appearing in equations.

2024-02-07 22:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +#
I'm once again confused by the use of $min$ here. This makes it not a function.

2024-02-07 22:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# or compacted:
```suggestion
# or, compacted,
```

2024-02-07 22:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# .. math:: \min_{x,s} f(x) + p(x,s) = -\sum_i v_i x_i +\lambda \left(\sum_i w_i x_i - W\right)^2\tag{7}
The minimum issue is more dramatic here because it means equating a value to a function.

2024-02-07 22:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# .. math:: \min_{x,s} f(x) + p(x,s) = -\sum_i v_i x_i +\lambda \left(\sum_i w_i x_i - W\right)^2\tag{7}
```suggestion
# .. math:: \min_{x,s} f(x) + p(x,s) = -\sum_i v_i x_i +\lambda \left(\sum_i w_i x_i - W\right)^2, \tag{7}
```

2024-02-07 22:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# where :math:`v_i` and :math:`w_i` are the value and weight of the :math:`i^{th}` item. Because of
```suggestion
# where :math:`v_i` and :math:`w_i` are the value and weight of the :math:`i`-th item. Because of
```

2024-02-07 22:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# the square in the second term, :math:`x_i x_i` terms show up, we can apply the property
```suggestion
# the square in the second term, some :math:`x_i x_i` terms show up. We can apply the property
```

2024-02-07 22:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# A quadratic term such as the second one presented in the Equation 7 can be rewritten by
```suggestion
# The quadratic  term on the right-hand side of equation :math:`(7)` can be rewritten as
```

2024-02-07 22:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +#
Too long and makes evil scroll bar appear. We need to rewrite in several lines.

2024-02-07 22:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# can combine Eq.(7) and Eq(8) to get the terms of the matrix :math:`Q`. So we end up with
```suggestion
# can combine equations :math:`(7)` and :math:`(8)` to get the terms of the matrix :math:`Q`. So we end up with
```

2024-02-07 22:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# .. math:: Q_{ii} = - v_i  + \lambda w_i(w_i - 2W),\tag{10}
```suggestion
# .. math:: Q_{ii} = - v_i  + \lambda w_i(w_i - 2W).\tag{10}
```

2024-02-07 22:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# To this point, we have encoded the problem in a format that we can use to solve it on quantum
```suggestion
# At this point, we have encoded the problem in a format that we can use to solve it on quantum
```

2024-02-07 22:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# To this point, we have encoded the problem in a format that we can use to solve it on quantum
I think this comment should be outside the code block.

2024-02-08 14:50 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# problem (`Here <https://pennylane.ai/qml/demos/tutorial_qaoa_intro>`__ a more detailed explanation
```suggestion
# Problem (`read this demo <https://pennylane.ai/qml/demos/tutorial_qaoa_intro>`__ for a more detailed explanation
```

2024-02-08 17:35 UTC, alvaro-at-xanadu requested changes
I think the results here are super good ⭐ ! Even if a beginner might be overwhelmed by the later sections, I think this demo is valuable for beginning and advanced readers alike 📖 . I have added a few comments to the later sections.

Since it's such a long demo, it might need and extra pair of eyes to make sure that everything is super polished—we do have high standards for the content that goes in our website, so please bear with us 🙏🏼 . I can give it a second look once you've acted on these comments.

2024-02-08 17:35 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +#    H_c(\mathrm{z}) = \sum_{i, j > i}^{n} J_{ij} z_i z_j + \sum_{i=1}^n h_{i}z_i + O\tag{13}.
Same issue as before with capital and not capital $z$.

2024-02-08 17:35 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# or we look deeper, our encoding method is really bad. Randomly guessing using the whole set of
```suggestion
# or we look deeper— it turns out our encoding method is really bad. Randomly guessing using the whole set of
```

2024-02-08 17:35 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# Ocean <https://docs.ocean.dwavesys.com/en/stable/>`__. There are two papers describing it
```suggestion
# where :math:`\lambda_{1,2}` are again penalization coefficients. Let's not delve too deeply into the unbalanced penalization approach, but make sure to check out these implementations
# `OpenQAOA <https://openqaoa.entropicalabs.com/>`__ and `D-Wave
# Ocean <https://docs.ocean.dwavesys.com/en/stable/>`__. For the background theory, there are also two papers describing it,
```

2024-02-08 17:35 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# you are interested in knowing the details, please go and check it 😁. **The only important thing is
```suggestion
# you are interested in knowing the details, please go and check the resources out😁. **The cliffnotes are
```

2024-02-08 17:35 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# We have improved the QAOA solution encoding wisely our QUBO with almost 2000 out of the 5000 samples
```suggestion
# We have improved the QAOA solution by encoding our QUBO wisely, with almost 2000 out of the 5000 samples
```

2024-02-08 17:35 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# that depending on the codification method of our problem, we get good or bad results.
```suggestion
# that depending on the encoding method for our problem, we get good or bad results.
```

2024-02-08 17:35 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +
Wow the previous encoding was really bad in comparison 😆. I had tried to solve this problem before with QAOA just for fun, no wonder why I got horrible results.

2024-02-08 17:35 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# We have come to the end of this demo. We have covered what are combinatorial optimization problems,
```suggestion
# We have come to the end of this demo. We have covered the definition of combinatorial optimization problems
```

2024-02-08 17:35 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# and how to formulate one of them, the Knapsack, using QUBOs and two different encodings slack
```suggestion
# and how to formulate one of them, the Knapsack Problem, using QUBO, and two different encodings: slack
```

2024-02-08 17:35 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# variables and unbalanced penalization. Then, we solve them using optimization-free QAOA and QA. Now,
```suggestion
# variables and unbalanced penalization. Then, we solved them using optimization-free QAOA and QA. Now,
```

2024-02-11 01:40 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +
I removed it

2024-02-11 02:01 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +#
I modified it to represent it correctly

2024-02-11 02:01 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +# .. math:: \min_x f(\mathrm{x}) = -(8x_0 + 47x_1 + 10x_2 + 5x_3 + 16x_4 ) \tag{2}
I modified it to represent it correctly

2024-02-11 02:02 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +#
I modified it to represent it correctly

2024-02-11 02:06 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +# :math:`N = \lfloor\log_2(26)\rfloor + 1 = 5`. We need three binary variables to represent the range
done

2024-02-11 02:17 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +#
both are used, but I modified it

2024-02-11 02:25 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +#
Hc is defined below and it is explained in the previous line.

2024-02-11 02:29 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +# The second unitary operator applied is
done

2024-02-11 03:32 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +# RZZ(:math:`2\gamma`) gate, and :math:`e^{-i\gamma_i h_iz_i}` using a RZ(:math:`2\gamma`)
\gamma -> \gamma_i, I fixed it. I think the parameters are needed.

2024-02-11 03:36 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +
I put it here to show the previous equation in action.

2024-02-11 03:42 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +#
how I can do it? in the notebook this is a subsection of QAOA @alvaro-at-xanadu

2024-02-11 03:44 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +#
done

2024-02-11 03:58 UTC, alejomonbar commented
@alvaro-at-xanadu Thank you so much for your comments, I finished with the revision. Please take a look.

2024-02-14 20:30 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# to bring all of them with us. Unfortunately, we our knapsack does not
```suggestion
# to bring all of them with us. Unfortunately, we our knapsack does not fit
```

2024-02-14 21:10 UTC, alvaro-at-xanadu requested changes
Just additional minor typos and comments from me, I would highly recommend sanity-check from a different reviewer though, a new set of eyes is always good. Since it's long, we're bound to miss things 😨 

It's looking much much better though! 🚀

2024-02-14 21:10 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# this way, moving :math:`\beta_i` from :math:`1` to :math`0` and :math:`\gamma_i` from :math`0` to :math`1`. With this approach,
```suggestion
# this way, moving :math:`\beta_i` from :math:`1` to :math:`0` and :math:`\gamma_i` from :math:`0` to :math:`1`. With this approach,
```

2024-02-14 21:10 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +#
Oh what I mean is to eliminate the subtitle Ising Hamiltonian. All what is in this section fits nicely in the QAOA section still.

2024-02-14 21:10 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# Ising Hamiltonian
```suggestion
```

2024-02-14 21:10 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# -----------------
```suggestion
```

2024-02-14 21:10 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +# optimal solutions. Why don’t we get such a good results using QAOA? Maybe we can blame the algorithm
```suggestion
# optimal solutions. Why don’t we get good results using QAOA? Maybe we can blame the algorithm
```

2024-02-14 21:10 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +#
Let's latex every equation in this paragraph (i.e, expressions containing = or ~)

2024-02-14 21:10 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_QUBO.py
> +
I just realized this is printing warning messages together with the result. I don't know the fix, @KetpuntoG do you know?

2024-02-16 12:37 UTC, ludmilaasb submitted a review, later dismissed
Hello @alejomonbar ! Thank you for your demo contribution! I took the liberty of reviewing it, and I must say you are almost there! 🚀 

I left some comments and suggestions. Just minor adjustments (to make the text and code more fluid) and it will be done! 😉

2024-02-16 12:37 UTC, ludmilaasb commented on demonstrations/tutorial_QUBO.py
> +#
Hello, maybe you could move the Ising Hamiltonian part before introducing QAOA? I think it would be helpful to understand the `H_c`.

2024-02-16 12:37 UTC, ludmilaasb commented on demonstrations/tutorial_QUBO.py
> +#    H_c(\mathrm{z}) = \sum_{i, j > i}^{n} J_{ij} z_i z_j + \sum_{i=1}^n h_{i}z_i + O. \tag{13}
This looks just like a generic Ising Hamiltonian. In section 5.2, they present a different Ising Hamiltonian for the Knapsack problem: https://arxiv.org/pdf/1302.5843.pdf

2024-02-16 12:37 UTC, ludmilaasb commented on demonstrations/tutorial_QUBO.py
> +# .. math:: \min_{x,s} \left(f(x) + p(x,s) = -\sum_i v_i x_i - \lambda_1 \left(\sum_i w_i x_i - W\right) + \lambda_2 \left(\sum_i w_i x_i - W\right)^2\right)\tag{14}.
I would avoid using the equality sign inside of this parenthesis.

2024-02-16 12:37 UTC, ludmilaasb commented on demonstrations/tutorial_QUBO.py
> +# you are interested in knowing the details, please go and check the resources out😁. **The cliffnotes are
This part is sounding a bit repetitive. I would suggest reformulating and making it more succinct.

2024-02-16 12:37 UTC, ludmilaasb commented on demonstrations/tutorial_QUBO.py
> +# -  Look at the ``OpenQAOA`` set of problems. There are plenty of them like the bin packing,
"OpenQAOA" appears as a monotype. Maybe you could change it to a link? Or it was intentional?

2024-02-17 03:53 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +# .. math:: \min_{x,s} f(x) + p(x,s) = -\sum_i v_i x_i +\lambda \left(\sum_i w_i x_i - W\right)^2\tag{7}
done

2024-02-17 03:54 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +"""
sure! @KetpuntoG

2024-02-17 04:01 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +
I think is good to have it as a print, so people can look at how to calculate and modify it.

2024-02-17 04:18 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +
about your question, you mean, how do I calculate the time required? It is the number of combinations 2**n times the time required to execute one of these combinations. @ludmilaasb

2024-02-17 04:26 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +
I modified the code to clarify what I mean

2024-02-17 04:44 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +# variables :math:`x_i` that take the value :math:`1` if we bring the :math:`i`-th item and :math:`0`  otherwise. Next, we know that we want to **maximize**
yes, but here we described x_0 and x_1. We don't have that before.

2024-02-17 04:50 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +# transport. Usually, solvers minimize functions, so a simple trick in our case is to minimize the
done

2024-02-18 04:15 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +# .. math:: \min_x \mathrm{x}^TQ \mathrm{x} = \min_x \left(\sum_i \sum_{j\ge i} Q_{ij} x_i x_j = \sum_i Q_{ii} x_i + \sum_i\sum_{j>i} Q_{ij}x_i x_j\right) \tag{3}
done

2024-02-18 04:21 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +
done

2024-02-18 04:26 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +#
done

2024-02-18 04:29 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +#
done

2024-02-18 04:44 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +ax.legend()
done

2024-02-18 04:51 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +#    H_c(\mathrm{z}) = \sum_{i, j > i}^{n} J_{ij} z_i z_j + \sum_{i=1}^n h_{i}z_i + O. \tag{13}
yes, the idea is to show that a generic QUBO can be represented by a generic Ising Hamiltonian. The QUBO in sec 5.2 is for a Knapsack problem with equality constraint (we are using the one with inequality constraint).

2024-02-18 04:53 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +#
done

2024-02-18 04:54 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +# .. math:: \min_{x,s} \left(f(x) + p(x,s) = -\sum_i v_i x_i - \lambda_1 \left(\sum_i w_i x_i - W\right) + \lambda_2 \left(\sum_i w_i x_i - W\right)^2\right)\tag{14}.
done

2024-02-18 05:06 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +# you are interested in knowing the details, please go and check the resources out😁. **The cliffnotes are
I agree! 😅

2024-02-18 05:06 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +# you are interested in knowing the details, please go and check the resources out😁. **The cliffnotes are
done (I tried my best)

2024-02-18 05:08 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +# -  Look at the ``OpenQAOA`` set of problems. There are plenty of them like the bin packing,
done

2024-02-18 05:12 UTC, alejomonbar commented
Thank you so much for the comments @ludmilaasb I tried my best to address all of them, please let me know what you think!

2024-02-20 12:18 UTC, ludmilaasb commented on demonstrations/tutorial_QUBO.py
> +
> I think is good to have it as a print, so people can look at how to calculate and modify it.

I understand what you're saying, but I believe there is no need to present this information this way. But if you insist, I would suggest writing a proper function, so the readers can pass the number of combinations as an input, instead of making them change it by hand a hardcoded string.

2024-02-20 12:46 UTC, ludmilaasb commented on demonstrations/tutorial_QUBO.py
> +# -  Play around with larger problems.
```suggestion
# We have come to the end of this demo. We have covered the definition of combinatorial optimization problems
# and how to formulate one of them, the Knapsack Problem, using QUBO, and two different encodings: slack
# variables and unbalanced penalization. Then, we solved them using optimization-free QAOA and QA. Now,
# it’s your turn to experiment with QAOA! If you need some inspiration:
#
# -  Look at the `OpenQAOA <https://openqaoa.entropicalabs.com/>`__ set of problems. There are plenty of them like bin packing,
#    traveling salesman, and maximal independent set, among others.
#
# -  Play around with larger problems.
```

2024-02-20 12:46 UTC, ludmilaasb commented on demonstrations/tutorial_QUBO.py
> +# -  Look at the `OpenQAOA <https://openqaoa.entropicalabs.com/>`__ set of problems. There are plenty of them like the bin packing,
```suggestion
# -  Look at the `OpenQAOA <https://openqaoa.entropicalabs.com/>`__ set of problems. There are plenty of them like bin packing,
```

2024-02-20 12:48 UTC, ludmilaasb commented on demonstrations/tutorial_QUBO.py
> +# Unbalanced penalization is a function characterized by larger penalty when the inequality
```suggestion
# Unbalanced penalization is a function characterized by a larger penalty when the inequality
```

2024-02-20 12:59 UTC, ludmilaasb commented on demonstrations/tutorial_QUBO.py
> +ax.legend()
I see that you updated the text but not the plot.

2024-02-20 12:59 UTC, ludmilaasb commented on demonstrations/tutorial_QUBO.py
> +ax.legend()
Nice! Would you mind updating the plot as well?

2024-02-24 03:25 UTC, alejomonbar commented on demonstrations/tutorial_QUBO.py
> +
done

2024-02-27 19:59 UTC, KetpuntoG approved these changes
Great job! Thanks for the effort here @alejomonbar 🚀

2024-02-28 14:48 UTC, alvaro-at-xanadu approved these changes
Ready!!

2024-02-28 21:10 UTC, merged