Sc 32461 notebook demo conveter
PennyLaneAI/qml pull request #734
Opened 2023-04-11 21:31 UTC by rashidnhm

**Title:** Added new script that aids conversion from Jupyter Notebook to QML Demo

**Summary:**
This PR adds a new script that is able to convert a Jupyter Notebook to QML Demo.

As noted in the README, there would not be a scenario where a notebook is converted using this script and is instantly ready as a Demo. In most cases, some manual updates will be required, but this script attempts to do most of the initial conversion, which includes:

- Place the first cell of the Notebook as raw docstring.
- Format subsequent non-code cells as Python comments
- For non-executable demos, extract the output from the notebook and add that as a commented output code block in the demo.
- For non-executable demos, extract code image outputs and place them as demo assets and link them in the demo.
- Take author info as an input and automatically add author block at the end of the demo.

**Relevant references:**
[sc-32461](https://app.shortcut.com/xanaduai/story/32461/qml-develop-tool-to-be-able-to-convert-jupyter-notebook-to-python-files-and-vice-versa)

**Possible Drawbacks:**
If there are any major bugs, it can be addressed in subsequent PRs.

**Related GitHub Issues:**
None.

2023-04-13 14:55 UTC, KetpuntoG commented
Thanks for opening this PR! What does this error mean? I have deleted the images, probably this is a plot of the demo.

<img width="1311" alt="Captura de pantalla 2023-04-13 a las 10 53 36" src="https://user-images.githubusercontent.com/65235481/231799436-db185850-7a76-44e6-844e-678e5764a90a.png">

2023-04-13 19:06 UTC, josh146 requested changes
Nice work @rashidnhm! Unfortunately I couldn't get the script to work with my notebook:

```console
Traceback (most recent call last):
  File "notebook_converter/notebook_to_demo.py", line 260, in <module>
    nb_py = convert_notebook_to_python(
  File "notebook_converter/notebook_to_demo.py", line 194, in convert_notebook_to_python
    with open(image_save_loc, "wb") as ifh:
IsADirectoryError: [Errno 21] Is a directory: '/home/josh/xanadu/qml/notebook_converter/../demonstrations/Optimization transform/Optimization transform_91527bf2_1.png'
```

2023-04-13 19:06 UTC, josh146 commented on notebook_converter/README.md
> +The path to the display picture for the author.
Also once I got it working, I got an error 😆 

```python
shutil.SameFileError: PosixPath('/home/josh/xanadu/qml/notebook_converter/../_static/authors/josh_izaac.png') and PosixPath('/home/josh/xanadu/qml/notebook_converter/../_static/authors/josh_izaac.png') are the same file
```

I guess because the script won't work with existing authors, only new ones?

2023-04-13 20:32 UTC, rashidnhm commented on notebook_converter/README.md
> +   --author-file=path/to/author_file.yaml
@josh146 Top level of the repo. I will add this to the README. 

The reason for this is since it extracts images from the notebook (for non executable ones), and put in the link to it on the demo.

The path to the notebook and author file can be anywhere on the PC and it should be fine! But the script itself should be invoked from the root of the repo, I can potentially fix that by hardcoding certain values within the script.

2023-04-13 20:32 UTC, rashidnhm commented on notebook_converter/README.md
> +Details on author file shown below
Required, error will be raised by argparse otherwise

2023-04-13 20:38 UTC, rashidnhm commented on notebook_converter/README.md
> +   --author-file=path/to/author_file.yaml
I thought about doing this, would we accept image this way too then? The other issue I was running into was determining the name the files would be saved as in the authors/ directory, which was easier to implement with the file.

Would you rather scrap the author file and pass everything by cli?

2023-04-13 20:43 UTC, rashidnhm commented on notebook_converter/README.md
> +The path to the display picture for the author.
Oh that has been missed! I can definitely add a check to see if the file exists .. a lot of the issue you and Guillermo have run into seems to be something that occurs on Windows that I was not able to run into in linux. I will try to update the script and address these issues.

2023-04-13 20:46 UTC, josh146 commented on notebook_converter/README.md
> +The path to the display picture for the author.
Oh I am using WSL 😆

2023-04-13 21:06 UTC, KetpuntoG commented
I had time to do a little test today and everything rendered 99% as expected. Great job! 🚀

It took me a while to get the paths right initially. On the other hand I think we could skip the author part for the moment or at least have the option of do it manually . It is clear enough how it is incorporated by looking at any other demo from the user's point of view and the creation of the yaml has confused me.

I still need to do more testing by adding images and non-executable tutorials but so far it is on the right track 😊

2023-04-13 21:10 UTC, KetpuntoG commented on notebook_converter/README.md
> +considered executable.
Is there a reason other than time for making a demo non-executable? 
If it is because of credentials that you do not want to show, this would not be valid, right? 🤔
(I am not sure if this situation can occur)

2023-04-13 21:11 UTC, KetpuntoG commented on notebook_converter/README.md
> +it must be relative to the script's location.
I was in the root of qml and the path was relative to it

2023-04-13 21:11 UTC, josh146 commented on notebook_converter/README.md
> +considered executable.
@KetpuntoG time is one thing, the other is dependencies! E.g., if they are using a package, or even hardware, we don't support or have access to.

2023-04-13 22:09 UTC, KetpuntoG commented on notebook_converter/README.md
> +considered executable.
Ah I had misunderstood you, I thought we would run the demo internally to get the outputs but you are referring to his notebook. That makes sense! 👌😊

2023-04-14 14:56 UTC, rashidnhm commented
@josh146 @KetpuntoG Thank you for all the feedback! Thought I'd address most of the commennts here.

I will be going back to the drawing board and make the following updates:
- Make it so that the script can be called from anywhere and not require to be at the root of the repo.
- Make it so the author file is not required. Instead, introduce `--author-name` `--author-bio` & `--author-picture` cli parameters and make them optional.
- Handle the `SameFileError` that Josh pointed out.

An extra note:
@josh146 the point you made about the script running the non-executable demo locally and capturing the output ... though it is a great idea it might not be very trivial to add :sweat_smile: .  For now, I will add a note in the README that the user would need to run their notebook locally before running the conversion script.

I will convert this PR back to draft, feel free to unsubscribe from the notifications, I will add you all back once the updates are all complete!

2023-04-14 20:20 UTC, rashidnhm commented
@josh146 @KetpuntoG 

The path issue has been fixed! I have updated the README as well.

- The script can now be called from anywhere, you do not need to be within the qml repo
- The path to the notebook can be an absolute path or relative to where you are
- The author-file parameter has been removed, instead there is now `--author-name` `--author-bio` `--author-profile-picture` 
  - The path for author-profile-picture can be absolute or relative to wherever the user is at the time of calling the script.

These changes should make the script a lot easier and intuitive to use. Please let me know on the further experience.

2023-04-16 19:43 UTC, josh146 requested changes
> the point you made about the script running the non-executable demo locally and capturing the output ... though it is a great idea it might not be very trivial to add 😅 . For now, I will add a note in the README that the user would need to run their notebook locally before running the conversion script.

Yep no worries at all, this is definitely a P2 in the grand scheme of things 😅 

@rashidnhm the new version is working really well for me, barring one bug which required me to comment out a bit of the script. Aside from that, I love the ability to capture output as codeblocks!!

2023-04-16 19:43 UTC, josh146 commented on notebook_converter/notebook_to_demo.py
> +    )
Would it make more sense to use
```python
parser.add_argument('--executable', action='store_true')
```

here? It avoids edge case issues with things like "true", "TRUE", etc.

2023-04-16 19:43 UTC, josh146 commented on notebook_converter/notebook_to_demo.py
> +        "If the notebook name startswith tutotial_, "
```suggestion
        "If the notebook name starts with tutorial_, "
```

2023-04-16 19:43 UTC, josh146 commented on notebook_converter/notebook_to_demo.py
> +        "If not passed, this information is inferred "
This is a nice touch!

2023-04-16 19:43 UTC, josh146 commented on notebook_converter/notebook_to_demo.py
> +    author_parser.add_argument("--author-profile-picture", help="Path to profile picture for author", type=str)
Nice, this was working well for me 🙏 

@rashidnhm I have two questions here:

- What should we do if the author already exists in `_static/authors`? I noticed that the current behaviour is to overwrite the file. It would be super nice to also have `--author-file=_static/authors/josh_izaac.txt` which could replace `--author-name` and `--author-bio`. Would this be easy to do?

- It occurred to me that some demos might have multiple authors - but maybe this is a problem for another day 😅

2023-04-16 19:43 UTC, josh146 commented on notebook_converter/notebook_to_demo.py
> +                                image_file_path.mkdir(parents=True)
This branch is causing issues for me, because it is creating a _a directory with the image name_. That is, it is creating a directory of the form

```
demonstrations/notebook_name/notebook_name_3224.png/..
```

Which then causes the line 223 to fail for me, since Python can't write image data to a directory:

```
  File "notebook_converter/notebook_to_demo.py", line 222, in convert_notebook_to_python
    with open(image_file_path, "wb") as ifh:
IsADirectoryError: [Errno 21] Is a directory: '/home/josh/xanadu/qml/demonstrations/Optimization transform/Optimization transform_91527bf2_1.png'
```

To get this working, I commented out this branch and manually created the directory for images 🤔

2023-04-17 14:44 UTC, rashidnhm commented on notebook_converter/notebook_to_demo.py
> +                                image_file_path.mkdir(parents=True)
Yep this was a bug from my end, going to fix shortly!

2023-04-17 17:57 UTC, rashidnhm commented on notebook_converter/notebook_to_demo.py
> +    )
I can change it back to this, the downside to store_true is that since it defaults to `False` if the notebook starts with tutorial_, it would always be treated as executable.

The I have it now is if you pass `--is-executable=<boo>` then it overrides the assumption behaviour.

Also the str_to_bool function definitely handles the true,True,True cases, you can see that [here](https://github.com/PennyLaneAI/qml/blob/1f8146c951d0ccbe95a5a45ed7ef8ca2f2a67505/notebook_converter/notebook_to_demo.py#L26-L38)

2023-04-17 18:06 UTC, rashidnhm commented on notebook_converter/notebook_to_demo.py
> +    author_parser.add_argument("--author-profile-picture", help="Path to profile picture for author", type=str)
> What should we do if the author already exists in _static/authors? I noticed that the current behaviour is to overwrite the file. It would be super nice to also have --author-file=_static/authors/josh_izaac.txt which could replace --author-name and --author-bio. Would this be easy to do?

I would say very easy to do since if you have already made a authors file, there is no parsing to information required by the script! I can take the file drop it in demo in the authors section!

> It occurred to me that some demos might have multiple authors - but maybe this is a problem for another day

Oooo this might a bit tougher to handle with how it is designed now, I can say with the previous yaml setup multiple authors would be a lot simpler to handle, but I can think of something

2023-04-17 18:28 UTC, josh146 commented on notebook_converter/notebook_to_demo.py
> +    )
oh perfect! Ignore my comment then @rashidnhm

2023-04-18 16:26 UTC, rashidnhm commented on notebook_converter/notebook_to_demo.py
> +                                image_file_path.mkdir(parents=True)
Should be fixed now, let me know

2023-04-25 01:13 UTC, josh146 approved these changes
Apart from a small issue with the author file (I had to manually edit the author file to allow the script to work), everything worked really well @rashidnhm!

2023-04-25 01:13 UTC, josh146 commented on notebook_converter/README.md
> +This converter aids the Jupyter Notebook to QML Demo conversion. Though this converter will not completely convert
```suggestion
# Notebook to PennyLane Demo Converter
This converter aids the Jupyter Notebook to Pennylane Demo conversion. Though this converter will not completely convert
```

2023-04-25 01:13 UTC, josh146 commented on notebook_converter/README.md
> +```
Minor comment @rashidnhm: I ran the script from the root directory of the repo, and got the error

```
Traceback (most recent call last):
  File "/Users/josh/pennylane/qml/notebook_converter/notebook_to_demo.py", line 365, in <module>
    author_sphinx = set_authors(*authors)
  File "/Users/josh/pennylane/qml/notebook_converter/notebook_to_demo.py", line 120, in set_authors
    author_files = [
  File "/Users/josh/pennylane/qml/notebook_converter/notebook_to_demo.py", line 121, in <listcomp>
    AUTHORS['link-dir'] / set_author_info(author).name
  File "/Users/josh/pennylane/qml/notebook_converter/notebook_to_demo.py", line 89, in set_author_info
    shutil.copy(profile_picture_loc, new_profile_picture_save_loc)
  File "/Users/josh/miniconda3/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/josh/miniconda3/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '../_static/authors/josh_izaac.png'
```

after I passed

```
--author-file "_static/authors/josh_izaac.txt"
```

Maybe an issue with relative directories?

2023-04-25 13:28 UTC, rashidnhm commented on notebook_converter/README.md
> +```
@josh146 taking a look into this!

2023-04-25 16:03 UTC, rashidnhm commented on notebook_converter/README.md
> +```
Fixed!

2023-04-26 15:19 UTC, rashidnhm commented
Thank you @josh146 , @KetpuntoG for all the help in testing and reviewing the converter!

2023-04-26 15:19 UTC, merged