LCU tutorial draft
PennyLaneAI/qml pull request #773
Opened 2023-05-04 20:09 UTC by orielkiss

**Title:** LCU tutorial

**Summary:** LCU +  block encoding tutorial

**Relevant references:** None

**Possible Drawbacks:** None

**Related GitHub Issues:** None

2023-05-08 15:00 UTC, Danimhn commented on demonstrations/tutorial_LCU.py
> +# with :math:`\alpha_k \in \mathbb{C}` :math:`\{0\}` and :math:`U_k` unitary. By assuming that
I think you meant C - {0} here right? I think just C would be fine too.

2023-05-08 15:00 UTC, Danimhn commented on demonstrations/tutorial_LCU.py
> +# ```qml.MottonenStatePreparation`` <https://docs.pennylane.ai/en/stable/code/api/pennylane.MottonenStatePreparation.html>`__
The hyperlinks are not showing properly for me in the html file you sent, I don't know if that's also the case with the deployment or not

2023-05-08 15:00 UTC, Danimhn commented on demonstrations/tutorial_LCU.py
> +import numpy as np
I think it's better to have smaller snippets of code throughout the document instead of one big chunk, so the prep and select implementation can be introduced in the previous section with their definition.

2023-05-08 15:00 UTC, Danimhn commented on demonstrations/tutorial_LCU.py
> +# We see that :math:`H` is exactly block encoded into a larger unitary matrix, which can be run on a
We technical end up block encoding H divided by the 1-norm of coefficients so it's not exactly H but I don't know how much we'd want to get into that here.

2023-05-08 15:00 UTC, Danimhn commented on demonstrations/tutorial_LCU.py
> +# We learnt how to decompose a hermitian matrix into a linear combination of Pauli operators, which
learned*. Also, did we actually learn how to decompose Hermitian into LCU of Paulis? I think we just used that fact to explore the utility of LCU.

2023-05-08 15:02 UTC, Danimhn commented
Very informative tutorial!

2023-05-08 16:04 UTC, orielkiss commented on demonstrations/tutorial_LCU.py
> +# perform non unitary operations, by using higher dimensional space. In practice, any matrix :math:`H`
you can always find a LCU, like here https://math.stackexchange.com/questions/1710247/every-matrix-can-be-written-as-a-sum-of-unitary-matrices. We restrict ourselves to hermitian for commodity since in general you can write A as a LCH and then as a LCU. thank you for the rephrasing :)

2023-05-08 16:05 UTC, orielkiss commented on demonstrations/tutorial_LCU.py
> +# where :math:`*` denote arbitrary numbers such that :math:`V` is unitary.
indeed

2023-05-08 16:06 UTC, orielkiss commented on demonstrations/tutorial_LCU.py
> +# with :math:`\alpha_k \in \mathbb{C}` :math:`\{0\}` and :math:`U_k` unitary. By assuming that
yes but then you can add exponentially many terms with 0 coefficient. anyway that is what they are using in the literature

2023-05-08 16:13 UTC, orielkiss commented on demonstrations/tutorial_LCU.py
> +# -  The SELECT subroutine instead applies the :math:`k`-th unitary :math:`U_k` on
ok

2023-05-08 16:13 UTC, orielkiss commented on demonstrations/tutorial_LCU.py
> +import numpy as np
ok I agree

2023-05-08 16:18 UTC, orielkiss commented on demonstrations/tutorial_LCU.py
> +# We see that :math:`H` is exactly block encoded into a larger unitary matrix, which can be run on a
added this precision

2023-05-08 16:18 UTC, orielkiss commented on demonstrations/tutorial_LCU.py
> +# ```qml.MottonenStatePreparation`` <https://docs.pennylane.ai/en/stable/code/api/pennylane.MottonenStatePreparation.html>`__
hm for me they work, let say that on the final website

2023-05-08 17:48 UTC, orielkiss commented
@KetpuntoG I think you need to resolve those conflicts, I don't have the permission. thanks

2023-05-10 15:06 UTC, isaacdevlugt requested changes
Nice work @orielkiss 🎉! There are a few comments (😅) but I like the content of the tutorial. The main things to highlight from my review are:

- Put preamble in "Linear combination of unitaries" section into the introduction and provide some more direction at the end of the introduction
- split up code blocks and comment when needed, making sure to highlight PL features

2023-05-10 15:06 UTC, isaacdevlugt commented on demonstrations/tutorial_LCU.py
> +# :math:`H=\sum_{l=1}^{L} H_l`, where the :math:`H_l` terms are only *hermitian*, is given by
```suggestion
# :math:`H=\sum_{l=1}^{L} H_l`, where the :math:`H_l` terms are only *Hermitian*, is given by
```

2023-05-10 15:06 UTC, isaacdevlugt commented on demonstrations/tutorial_LCU.py
> +# expanding the time evolution operator into a `Taylor serie <https://arxiv.org/abs/1412.4687>`__, and
```suggestion
# expanding the time evolution operator as a `Taylor series <https://arxiv.org/abs/1412.4687>`__ and
```

2023-05-10 15:06 UTC, isaacdevlugt commented on demonstrations/tutorial_LCU.py
> +# truncate it to some order :math:`M`. Hence, we can write
```suggestion
# truncating it to some order :math:`M`. Hence, we can write
```

2023-05-10 15:06 UTC, isaacdevlugt commented on demonstrations/tutorial_LCU.py
> +# which can be brought into a LCU form as above, since :math:`H^k` is hermitian.
```suggestion
# which can be brought into an LCU form as above, since :math:`H^k` is Hermitian.
```

2023-05-10 15:06 UTC, isaacdevlugt commented on demonstrations/tutorial_LCU.py
> +# We learned how to decompose a hermitian matrix into a linear combination of Pauli operators, which
```suggestion
# We learned how to decompose a Hermitian matrix into a linear combination of Pauli operators, which
```

2023-05-10 15:06 UTC, isaacdevlugt commented on demonstrations/tutorial_LCU.py
> +# can be block encoded into a larger unitary matrix. This scheme is useful to perform time evolution
```suggestion
# can be block-encoded into a larger unitary matrix. This scheme is useful to perform time evolution
```

2023-05-10 15:17 UTC, orielkiss commented on demonstrations/tutorial_LCU.py
> + .. math:: V=\begin{pmatrix}H&*\\*&* \end{pmatrix},
I also don't know ..., will try to have a look around

2023-05-10 15:50 UTC, orielkiss commented on demonstrations/tutorial_LCU.py
> +with :math:`\alpha_k \in \mathbb{C}^*` and :math:`U_k` unitary. This can be achieved for any hermitian
it is C without zero. I guess it is not entirely necessary but this is what people are using in the literature. I tried putting C\{0} but had some latex issue

2023-05-10 15:52 UTC, orielkiss commented on demonstrations/tutorial_LCU.py
> +choose a suitable one.
agreed, just removed it

2023-05-10 17:42 UTC, josh146 commented on demonstrations/tutorial_LCU.py
> + .. math:: V=\begin{pmatrix}H&*\\*&* \end{pmatrix},
It is because the `.. math::` is slightly indented :) In ReST, indents correspond to 'block quotes'.

2023-05-10 18:48 UTC, KetpuntoG commented on demonstrations/tutorial_LCU.ipynb
> + "cells": [
Don't forget to remove this notebook

2023-05-10 18:48 UTC, KetpuntoG commented on demonstrations/tutorial_LCU.py
> +Block encoding via LCU decompositions
Take a look to another demo to check this initial lines:

```python
.. meta::
    :property="og:description": Learn how to use the differentiable Hartree-Fock solver
    :property="og:image": https://pennylane.ai/qml/_images/differentiable_HF.png

.. related::
    tutorial_quantum_chemistry Building molecular Hamiltonians
    tutorial_vqe A brief overview of VQE
    tutorial_givens_rotations Givens rotations for quantum chemistry
    tutorial_adaptive_circuits Adaptive circuits for quantum chemistry


*Author: Soran Jahangiri — Posted: 09 May 2022. Last updated: 09 May 2022.*

```

In the first part you should put the description and the name of the thumbnail after /images

if you think there is a related tutorial you could include it as well. 

Finally your name and the date of publication. You can put today's date and I will update it.

2023-05-10 18:49 UTC, KetpuntoG commented on demonstrations/tutorial_LCU.py
> +# (2014)
Now you can add the bio here 😄
Look at the final lines in this [demo](https://github.com/PennyLaneAI/qml/pull/733)

Don't forget to add these files with your information 
<img width="347" alt="Captura de pantalla 2023-05-10 a las 14 46 12" src="https://github.com/PennyLaneAI/qml/assets/65235481/c38bae7b-b7f1-4927-9bbb-555563f9ec64">

2023-05-11 16:11 UTC, isaacdevlugt requested changes
Nice work! It flows much better now. Some modifications to be made yet but we're nearly there!

2023-05-11 16:11 UTC, isaacdevlugt commented on demonstrations/tutorial_LCU.py
> +# selecting on :math:`|\bar{0}\rangle`, using following circuit:
This needs a bit of retooling in order to coherently describe how this algorithm fails or succeeds. You can state the equation and then describe failure/success, just make sure that you follow a straight line and don't jump around too much 🙂

2023-05-11 16:11 UTC, isaacdevlugt commented on demonstrations/tutorial_LCU.py
> +# and perform a block-encoding.
```suggestion
# The following quantum function performs this block-encoding procedure.
#
```

2023-05-11 16:11 UTC, isaacdevlugt commented on demonstrations/tutorial_LCU.py
> +# Congrats!!! You have now completed this tutorial! We will now see how this block-encoding technique can be used
Lol I love the enthusiasm but we can tone it down just a hair 🤠 

```suggestion
# Congrats! We will now see how this block-encoding technique can be used
```

2023-05-11 16:11 UTC, isaacdevlugt commented on demonstrations/tutorial_LCU.py
> +# As a concrete example, let us consider a first order truncation
```suggestion
# As a concrete example, let us consider a first-order truncation
```

2023-05-11 16:52 UTC, isaacdevlugt commented on demonstrations/tutorial_LCU.py
> +# :func:`ctrl <pennylane.ctrl>`operations on
```suggestion
# :func:`~pennylane.ctrl` operations on
```

2023-05-11 19:33 UTC, isaacdevlugt commented on demonstrations/tutorial_LCU.py
> +matrices.  We note that any matrix can be decomposed into a sum of two hermitian matrices,
```suggestion
matrices.  We note that any matrix can be decomposed into a sum of two Hermitian matrices,
```

2023-05-12 19:15 UTC, isaacdevlugt commented
Do we want this in "Getting started" 🤔? Lol

2023-05-12 19:31 UTC, KetpuntoG reviewed
Good job here! 🚀
Some final comments :)

2023-05-12 19:31 UTC, KetpuntoG commented on demonstrations/tutorial_LCU.py
> +with :math:`\alpha_k \in \mathbb{C}^*` and :math:`U_k` unitary. This can be achieved if :math:`H` is a Hermitian matrix
```suggestion
with :math:`\alpha_k \in \mathbb{C}^*` and :math:`U_k` unitary. This can be achieved if :math:`H` is a Hermitian
```

2023-05-12 19:31 UTC, KetpuntoG commented on demonstrations/tutorial_LCU.py
> +matrices.  We note that any matrix can be decomposed into a sum of two Hermitian matrices,
since you are using it later, it would be good to remark what a hermitic matrix is, just say H = H^dagger

2023-05-12 19:31 UTC, KetpuntoG commented on demonstrations/tutorial_LCU.py
> +# The number of ancilla qubits needed can be computed from the number of terms in the LCU.
I think this is not rendering the way you want it to

2023-05-12 19:31 UTC, KetpuntoG commented on demonstrations/tutorial_LCU.py
> +# :math:`\|\vec{\alpha}\|_1 \cdot` PREPARE :math:`^\dagger` SELECT PREPARE :math:`|\bar{0}\rangle`.
you could put \cdot between PREPARE and SELECT ?(here and in the other parts of the text)

2023-05-12 19:31 UTC, KetpuntoG commented on demonstrations/tutorial_LCU.py
> +# is measured in the zero state: |\bar{0}\rangle. Hence, block-encoding is a probabilistic algorithm that succeeds with some probability
you forgot here :math:

2023-05-12 19:31 UTC, KetpuntoG commented on demonstrations/tutorial_LCU.py
> +def Block_encoding(coeffs, phases, unitaries):
I would prefer the function not to start with a capital letter. Could you change it here and in the other parts of the code?

2023-05-12 19:31 UTC, KetpuntoG commented on demonstrations/tutorial_LCU.py
> +#
Nice!

2023-05-12 19:31 UTC, KetpuntoG commented on demonstrations/tutorial_LCU.py
> +#
could you comment on where the next steps could be? Where could I learn more about it?

2023-05-12 19:31 UTC, KetpuntoG commented on demonstrations/tutorial_LCU.py
> +# Given this, we need to extract the coefficients of the LCU and write them as a positive number multiplied by a phase.
This paragraph could be a little clearer. I would comment that the LCU procedure assumes that the coefficients have to be positive real but that this is not a problem since we can introduce the phase inside the operator.

this may be a good time to tell the reader to go to the codebook (link it) if they want to know more about it

2023-05-24 14:54 UTC, KetpuntoG commented
Looks amazing! Thanks for all the changes 🚀😊

2023-05-24 16:47 UTC, isaacdevlugt approved these changes
Nice work Oriel!

2023-05-24 16:47 UTC, isaacdevlugt commented on demonstrations/tutorial_LCU.py
> +matrix (i.e. :math:`H=H^\dagger`) by projecting it onto the Pauli basis since the Pauli basis is a unitary basis for Hermitian
```suggestion
matrix (i.e., :math:`H=H^\dagger`) by projecting it onto the Pauli basis since the Pauli basis is a unitary basis for Hermitian
```

2023-05-24 16:47 UTC, isaacdevlugt commented on demonstrations/tutorial_LCU.py
> +matrices. We note that any matrix can be decomposed into a sum of two Hermitian matrices,
```suggestion
matrices. But, any matrix can be decomposed into a sum of two Hermitian matrices,
```

2023-05-24 16:47 UTC, isaacdevlugt commented on demonstrations/tutorial_LCU.py
> +print("LCU decomposition: \n", LCU)
Nice! Simple and to-the-point.

2023-05-24 16:47 UTC, isaacdevlugt commented on demonstrations/tutorial_LCU.py
> +# .. math:: \text{PREPARE}|\bar{0}\rangle = \sum_{k=0}^{K-1} \sqrt{\frac{\alpha_k}{\|\vec{\alpha}\|_1}} |k\rangle,
The formatting is strange here and I think the way to fix this is to just indent it. However, I don't really think an itemized list is necessary now that I'm reading this again with fresh eyes. Let's just do away with it!

2023-05-24 16:47 UTC, isaacdevlugt commented on demonstrations/tutorial_LCU.py
> +# 1.  The PREPARE subroutine encodes the coefficients of the LCU decomposition in the amplitudes of the quantum state as
```suggestion
# The PREPARE subroutine encodes the coefficients of the LCU decomposition in the amplitudes of the quantum state as
```

2023-05-24 16:47 UTC, isaacdevlugt commented on demonstrations/tutorial_LCU.py
> +# 2. The SELECT subroutine applies the :math:`k`-th unitary :math:`U_k` on
```suggestion
# The SELECT subroutine applies the :math:`k`-th unitary :math:`U_k` on
```

2023-05-24 16:47 UTC, isaacdevlugt commented on demonstrations/tutorial_LCU.py
> +#    :math:`|\psi\rangle` when given access to the state :math:`|k\rangle` as follows
```suggestion
# :math:`|\psi\rangle` when given access to the state :math:`|k\rangle` as follows
```

2023-10-20 18:57 UTC, closed without merging