Aquila hardware demo
PennyLaneAI/qml pull request #776
Opened 2023-05-04 20:29 UTC by lillian542

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Remember to do a grammar check of the content you include.
- [ ] All tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2023-05-07 15:52 UTC, KetpuntoG commented
Do not forget to add the demo to the corresponding .rst (quantum_computing.rst) so that it appears in the demos.
Anyway In this link you can see the current deployment:

https://qml-build-previews.pennylane.ai/pull_request_build_preview/776/demos/ahs_aquila.html

2023-05-09 07:47 UTC, Qottmann reviewed
Outstanding job @lillian542 ! This is going to be an amazing resource for any newbie or pro to know everything they need to know about this device! 

Very well explained and put together. I made a first pass and left some nit-picky comments about the text. There is some problem with rendering text after plots. Potentially starting a new 17-# line could resolve it?

It sometimes reads like you are trying to explain multiple concepts all at once. E.g. the three first paragraphs go a bit back and forth about "pulse programming" and "analog hamiltonian" simulation. I think it could gain in clearness by defining one, then the other. Overall there could be some corners that could be made more concise, though I like the thoroughness and completeness. I'll be more concrete in a second pass :)

2023-05-09 07:47 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +using analog Hamiltonian simulation, an alternative to gate-based quantum computing.
_Might_ be confusing pulse programming vs analog hamiltonian simulation, but not sure how best to defuse that

2023-05-09 07:47 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +different physical parameters, because we study any effects in an engineered system that can be more
The "any" reads a bit awkward here, maybe "the"?

2023-05-09 07:47 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +overhead (and thereby introduce more noise) without providing computational advantages.
Wouldnt use "computational advantages" in this context, might trigger half the readership

2023-05-09 07:47 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +available online in particular windows, which can be found HERE LINK GOES HERE!!!, though you can
particular "time windows" maybe? First thought you were talking about the braket sdk being available in Windows OS

2023-05-09 07:47 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +..note:: Some cells of this notebook will only run when hardware is online. If you want to run it at
```suggestion
.. note:: Some cells of this notebook will only run when hardware is online. If you want to run it at
```

2023-05-09 07:47 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +.. math:: H_{vdW, j, k} = \sum_{j=1}^{N-1}\sum_{k=j+1}^{N} V_{jk}n_jn_k = \sum_{j=1}^{N-1}\sum_{k=j+1}^{N} \frac{C_6}{R^6_{jk}}n_jn_k; \quad R_{jk} = \lvert x_j - x_k \lvert
Divide and conquer 💪 I would first explain the interaction term, and then the drive term, and then put them together

2023-05-09 07:47 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +..note:: To access remote services on Amazon Braket, you must first create an account on AWS and
```suggestion
.. note:: To access remote services on Amazon Braket, you must first create an account on AWS and
```

2023-05-09 07:47 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +..note:: To access remote services on Amazon Braket, you must first create an account on AWS and
Very important to link to the appropriate places to make it as seamless as possible :)

2023-05-09 07:47 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +#  .. code-block:: none
This is suuuper useful! 🙌

2023-05-09 07:47 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +# .. figure:: ../demonstrations/ahs_aquila/rydberg_blockade_coordinates.png
Something happened here, the following text renders on the side of the plot

2023-05-09 07:47 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +plt.legend()
x label

2023-05-09 07:47 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +# .. figure:: ../demonstrations/ahs_aquila/rydberg_blockade_coordinates.png
Actually same goes for all following plots here, see screenshot:
![image](https://user-images.githubusercontent.com/43949391/237028874-8cddf250-7b29-4bb6-bf95-bb5bc3d4dd63.png)

2023-05-09 10:15 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +# -  lots of applications
Is that so 🤔 ?

2023-05-09 10:16 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +# -  lots of applications
(I'm assuming these are not staying bullet points but are for brain storming?)

2023-05-09 10:18 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +#     `pnas.1804949115 <https://doi.org/10.1073/pnas.1804949115>`__, 2018
I'd always link the arxiv version https://arxiv.org/abs/1701.05182 same below

2023-05-09 13:36 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +# -  lots of applications
>Is that so 🤔 ?

Hahahah, yeah, I don't know if I'm going to claim that. It think this will end up saying something like 'potential applications in a range of research fields'. 

But yes, this is just a brainstorm for now.

2023-05-09 14:53 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +using analog Hamiltonian simulation, an alternative to gate-based quantum computing.
I think I'll swap the order of the explanation for pulse programming and AHS, so that we first explain pulse programming, and then explain that one thing that can be implemented via pulse programming is AHS. I think this will be more clear if presented as: pulse programming is the tool, AHS is an example of type of program we can create with the tool. I can't think of a good way to clarify right in this sentence though.

2023-05-09 14:57 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +overhead (and thereby introduce more noise) without providing computational advantages.
Last bit seems unnecessary, actually, I'll just remove it 😆 Wouldn't want to trigger the readership 😅

2023-05-09 20:53 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +.. math:: H_{vdW, j, k} = \sum_{j=1}^{N-1}\sum_{k=j+1}^{N} V_{jk}n_jn_k = \sum_{j=1}^{N-1}\sum_{k=j+1}^{N} \frac{C_6}{R^6_{jk}}n_jn_k; \quad R_{jk} = \lvert x_j - x_k \lvert
I think I may have over-explained the interaction term now, and I still need to flesh out the description for the drive term. But lmk what you think so far.

2023-05-09 22:22 UTC, Qottmann reviewed
I'm wondering if there is a clever way of portraying the simulation vs real device results side by side / interactively in tabs that a user can click? CC @josh146 (context: we basically do the same thing twice, once in simulation and then on real hardware)

I think I actually dont understand the physics of the phase transition example in the last part. Is this a dynamical phase transition? Or are we using the pulse sequence to prepare the ground states in different regimes of the phase diagram?

2023-05-09 22:22 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +# the gaussian pulse envelope via trial-and-error to find settings that result in a pi-pulse.
I think you can scratch most of this and just say "we look at a single / isolated atom and perform a $\pi$-pulse" so you dont have to go into discerning any potential unphysical situations. If I understand it correctly your main point is to showcase the effect of a pi-pulse on a single qubit, right?

2023-05-09 22:22 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +##############################################################################
I would combine this with the previous paragraph and do the circuit definition without the decorator and then have

```python
circuit_qml = qml.QNode(default_qubit, interface="jax")
circuit_ahs = qml.QNode(ahs_local, interface="jax")
```

The text could just say "we can simulate with pennylane or ahs_local, ..." and then go into how for real hardware it makes sense to do these checks

2023-05-09 22:22 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +# To run this without connecting the hardware, switch the aquila device out with the `rydberg_simulator` below.
```suggestion
# To run this without connecting the hardware, switch the aquila device out with the ``rydberg_simulator`` below.
```

2023-05-09 22:22 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +# Now let’s use they physical properties of the device to perform a simple Analogue Hamiltonian
```suggestion
# Now let us use the physical properties of the device to perform a simple Analogue Hamiltonian
```

2023-05-09 22:22 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +# .. figure:: ../demonstrations/ahs_aquila/atom_chain_heatmap.png
cool plot! needs a label for the z axis though, I guess it is the density?

2023-05-09 22:22 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +# .. figure:: ../demonstrations/ahs_aquila/5_by_10_grid_hardware_result.png
Is this how we expect this to look? (i.e. very different from simulation)

2023-05-09 22:37 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +# .. figure:: ../demonstrations/ahs_aquila/5_by_10_grid_hardware_result.png
It looks different because its a plot of a completely different measurement. 

I actually didn't run the above simulated experiment on hardware, because it would cost 80 dollars, and that seemed like a lot. This is a completely different thing, running on a grid of atoms instead of a line, and only measuring at the final timestamp. I.e. it corresponds to the final vertical cut of the plot you are referring to, but if the measurement were done on a 2D grid of atoms instead of a 1D line. 

It sounds like this is not clear in the text, I'll need to work on that. I'll also run this on simulator so there is a comparison to make there. I can potentially change the color scheme so there is a clear separation between the one experiment and the other.

2023-05-09 22:45 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +# the hardware control, and it's not possible to jump abruptly between values.
> So one is a piecewise linear and one a piecewise constant function?

That's what it says, and that's what it means :) One is ramped smoothly, the other jumps. One is piecewise linear, the other is piecewise constant. Currently I've written it both ways, because I think people working with theory are use to thinking of them as piecewise functions, and experimentalist are used to talking about whether or not you ramp between set points. But it will be cleaner if I just stick to one, and everyone will know what piecewise linear vs piecewise constant mean, whereas I'm not sure 'ramping' is a very familiar concept outside of experimental implementations. Will change the language around ramp rates to talk about slopes or derivatives instead.

2023-05-09 22:48 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +# physical constants).
good point, will reorganize

2023-05-09 22:51 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +######################################################################
Maybe? I feel like it makes sense that the 'interaction term' section ends with creating an interaction term, and the 'drive term' section ends with creating a global drive. I think it will be less long and overwhelming once its in a table. But let's see how it turns out, might need to split it up

2023-05-09 22:56 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +# the gaussian pulse envelope via trial-and-error to find settings that result in a pi-pulse.
I guess I felt a need to justify why I'm running it on a `default.qubit` device instead of going straight to the AWS simulator? Here I isolate the atom by 'turning off' the interaction term, rather than actually creating an additional register that is only a single atom, which is unphysical, and I feel like I need to explain myself 😅 

But the same effect could be achieved with a single qubit register and going directly to the AWS simulator, maybe I should to that, and we shouldn't run anything on `default.qubit` in this notebook. And then all of this would definitely go. 

Even if we keep the `default.qubit` thing, this _could_ be simplified, but I do think that there should be some explanation for why we are simulating an 'incorrect' Hamiltonian to calibrate the pi-pulse. And it is a sometimes-useful feature of running the simulation in PennyLane that we can look at isolated Hamiltonian behaviours that we can't study in a physical system.

2023-05-09 22:58 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +# .. figure:: ../demonstrations/ahs_aquila/atom_chain_heatmap.png
Yes, thanks!

2023-05-09 23:04 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +# .. figure:: ../demonstrations/ahs_aquila/5_by_10_grid_hardware_result.png
Tbh I'm not sure we even want this measurement, it doesn't 'work' that well. You can see the effect of Rydberg blockade, but it's by no means a checkerboard. It's "interesting" because its many qubits (the simulated version will have to be 4x4 or possibly even 3x5 instead of 5x10, because it can't handle that many qubits). But it doesn't work that well.

2023-05-10 07:57 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +# the gaussian pulse envelope via trial-and-error to find settings that result in a pi-pulse.
I think simulating on pennylane, ahs local and ahs remote makes sense and is a nice part of the demo. It's really okay to just say you simulate an isolated atom 😇

2023-05-10 08:07 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +# .. figure:: ../demonstrations/ahs_aquila/5_by_10_grid_hardware_result.png
Ah okay, I missed that!
So there is the 1d where you first simulate and then run on real hardware, and then there is this separate rectangular part at the end where you ask in the comment if we want that in the first place? I think the plot looks reasonably ferromagnetic so I wouldnt discard it based on that :)

2023-05-10 13:52 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +# the gaussian pulse envelope via trial-and-error to find settings that result in a pi-pulse.
Alright, I'll just go ahead and do that then 😅

2023-05-10 19:14 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +##############################################################################
updated!

2023-05-11 08:40 UTC, Qottmann reviewed
This is coming along very well, really great job @lillian542 🚀 

I really like the intro paragraphs and the other topics that were raised. I left some minor comments about the text here and there.

The physics part in the end still needs some clarifications on what is going on.

Another point is that it is still quite long and could be made a bit more concise here and there. I tried to be more specific about points where I think things can be combined / left out / shortened. Hope that helps!

2023-05-11 08:40 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +# Rydberg blockade on the QuEra hardware
I wonder if we can rearrange this section a bit to first show the simple execution and then go into the nitty-gritty details of the optional validation process. Currently the impression could arise that all these steps are expected / necessary to run on hardware and might be a bit overwhelming.

2023-05-11 08:40 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +#
I am missing a description of what we are doing here. Are we preparing the ground state of that Hamiltonian, if yes: how? (not clear how this is done with a dynamical drive)

2023-05-11 13:34 UTC, lillian542 commented
>Another point is that it is still quite long and could be made a bit more concise here and there. I tried to be more specific about points where I think things can be combined / left out / shortened. Hope that helps!

It's really long, any suggestions about where it could be more concise are definitely welcome... 😅

2023-05-11 13:55 UTC, trbromley reviewed
Thanks @lillian542! I'm partway through but here are some comments.

2023-05-11 13:55 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +pulse programming.
At this point I'm confused between AHS and pulse programming? Readers might not be clear on the distinction - I think this sentence is trying to address that, but perhaps we can emphasize it just a little more. E.g., "In this demo, we will simulate a simple quantum phase transition on the Aquila hardware
using analog Hamiltonian simulation, an alternative to gate-based quantum computing.  This is possible in PennyLane using the :mod:`~pennylane.pulse` module for pulse-level control."

2023-05-11 13:55 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +hardware hamiltonians. Quantum algorithms are written directly on the hardware level, and pulse
```suggestion
hardware Hamiltonians. Quantum algorithms are written directly on the hardware level, and pulse
```

2023-05-11 13:55 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +is implemented via the functionality provided in the Pennylane ``pulse`` module. For
```suggestion
is implemented via the functionality provided in the Pennylane :mod:`~pennylane.pulse` module. For
```

2023-05-11 13:55 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +`here <https://us-east-1.console.aws.amazon.com/braket/home?region=us-east-1#/devices/arn:aws:braket:us-east-1::device/qpu/quera/Aquila>`__
Are we confident about the URL, or is there some specificity to us/our account?

2023-05-11 13:55 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +distance between atoms, it becomes harder and harder to excite neighboring atoms.
```suggestion
distance between atoms, it becomes harder and harder to excite neighbouring atom pairs.
```

2023-05-11 13:55 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +    :align: center
Are we able to wrap the text around the image?

2023-05-11 13:55 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +.. math:: H_{vdW, j, k} = \sum_{j=1}^{N-1}\sum_{k=j+1}^{N} V_{jk}n_jn_k = \sum_{j=1}^{N-1}\sum_{k=j+1}^{N} \frac{C_6}{R^6_{jk}}n_jn_k
Do we need the vdW? it took me a while to realize it meant van der Waals.

2023-05-11 13:55 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +where :math:`R_{jk} = \lvert x_j - x_k \lvert` is the distance in meters between atoms *j* and *k*, and :math:`C_6`
```suggestion
where :math:`R_{jk} = \lvert x_j - x_k \lvert` is the distance in metres between atoms *j* and *k*, and :math:`C_6`
```
(I think this is the standard Canadian spelling)

2023-05-11 13:55 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +:math:`^{87}Rb atom).
What is `n_j` in the equation?

2023-05-11 13:55 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +:math:`\Omega` and the detuning :math:`\Delta`.
Might be worth leaving out the part from "described by...", since we haven't seen omega and delta yet

2023-05-11 13:55 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +.. math::  H_{drive} = \sum_{k=1}^N \frac{\Omega(t)}{2} (e^{i \phi(t)}\ket{g_k}\bra{r_k} - e^{-i \phi(t)} \ket{r_k}\bra{g_k}) - \Delta(t) \n_k
Should we have a hat on `n_k`?

2023-05-11 13:55 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +.. math::  H_{drive} = \sum_{k=1}^N \frac{\Omega(t)}{2} (e^{i \phi(t)}\ket{g_k}\bra{r_k} - e^{-i \phi(t)} \ket{r_k}\bra{g_k}) - \Delta(t) \n_k
Also what is `r_k` and `g_k`?

2023-05-11 13:55 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +Simulation on Rydberg atom based hardware provided by QuEra.
I don't think we need to capitalize in AHS

2023-05-11 13:55 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +# First we will create a ``ParametrizedHamiltonian`` that describes a Rydberg system and drive we want
Can we link to PL docs in this demo?
```suggestion
# First we will create a :class:`~pennylane.pulse.ParametrizedHamiltonian` that describes a Rydberg system and drive we want
```

2023-05-11 18:03 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +`here <https://us-east-1.console.aws.amazon.com/braket/home?region=us-east-1#/devices/arn:aws:braket:us-east-1::device/qpu/quera/Aquila>`__
I don't think there is anything account specific except the region, but to be on the safe side I can link to the console instead and say to check 'Devices'

2023-05-11 18:04 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +.. math:: H_{vdW, j, k} = \sum_{j=1}^{N-1}\sum_{k=j+1}^{N} V_{jk}n_jn_k = \sum_{j=1}^{N-1}\sum_{k=j+1}^{N} \frac{C_6}{R^6_{jk}}n_jn_k
removed

2023-05-11 18:06 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +where :math:`R_{jk} = \lvert x_j - x_k \lvert` is the distance in meters between atoms *j* and *k*, and :math:`C_6`
That looks so weird to me but Google agrees with you so I accept

2023-05-11 18:28 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +:math:`^{87}Rb atom).
I guess I should comment on that, good point

2023-05-11 18:33 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +.. math::  H_{drive} = \sum_{k=1}^N \frac{\Omega(t)}{2} (e^{i \phi(t)}\ket{g_k}\bra{r_k} - e^{-i \phi(t)} \ket{r_k}\bra{g_k}) - \Delta(t) \n_k
Will add hats to H's and n's and define r_k and g_k

2023-05-11 18:39 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +-  Effect of phase
Yes, but I think I might leave it for the background demo and just sort of state things here. Will coordinate with him.

2023-05-11 18:54 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +#
A problem for another demo now :)

2023-05-11 18:55 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +atoms is only non-zero when both atoms are in the Rydberg state, such that :math:`n_k n_j`\ket{\psi}`=1`, and is
yes there should!

2023-05-11 19:12 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +    :align: center
Yes but I think we might move this image to Alvaro's demo, depending on the content he's planning. Will confer with him regarding what makes most sense.

2023-05-11 19:39 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +computation. With analog Hamiltonian simulation, rather than implementing gates that represent a logical
I'm not sure. You mean AHS is a sub-field of gate-based control? I think in our example it isn't, because we're doing AHS with no gates.

To be honest, I think of gate-based control is a sub-field of pulse programming, and AHS as another sub-field of pulse programming, but I'm not sure how accurate that is. And I don't know anything about doing analog computing on a digital quantum computer. 

So in summary, I'm not sure what to say here, let me know if you have suggestions. 

But I think a super brief version of this will go in the section introducing Aquila as a motivating statement for why the Aquila device is interesting, and most of this will be moved to the second demo, since this one will just be Rydberg blockade, which we aren't really using to _simulate_ anything.

2023-05-11 19:40 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +`here <https://us-east-1.console.aws.amazon.com/braket/home?region=us-east-1#/devices/arn:aws:braket:us-east-1::device/qpu/quera/Aquila>`__
Actually they keep it on the Aquila page of QuEra's website, I'll link to that

2023-05-11 20:20 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +The hardware is accessible via the Braket SDK, and requires an account to access (see below). It is
reorganized

2023-05-11 20:42 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +Interaction term and atom arrangement
I think its better now, but possibly there is further room for improvement

2023-05-11 20:43 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +# Rydberg blockade on the QuEra hardware
I think since the hardware measurement for Rydberg blockade is the 'culmination' of this demo now, we should leave it as the final thing before the conclusion, it would feel a bit out of place between the measurement and the conclusion. What if I reword this to emphasize that this is an optional step?

2023-05-11 20:48 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +# Rydberg blockade on the QuEra hardware
Also while it is not _neccessary_, Peter's response to "what problem do you see users have most often" was that they don't examine the discretized program before running (or at all), and then they don't understand why their results differ so much from simulation (where no discretization occurs). He at least has suggested that he feels everyone _should_ do these things before uploading to hardware.

2023-05-11 21:45 UTC, co9olguy commented on demonstrations/ahs_aquila.py
> +.. figure:: ../demonstrations/ahs_aquila/aquila_demo_image.png
Something I noticed on this demo that I hadn't seen on other demos: with fractional browser windows, the images overflow past the boundaries. Example screenshot below, but also applies to things like matplotlib plots

(firefox browser on linux)

![image](https://github.com/PennyLaneAI/qml/assets/7213358/6203bd33-ac70-4c7b-acac-4cb6a2e4db15)

2023-05-11 21:45 UTC, co9olguy commented on demonstrations/ahs_aquila.py
> +.. figure:: ../demonstrations/ahs_aquila/aquila_demo_image.png
@KetpuntoG have you seen this before?

2023-05-12 11:00 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +# Rydberg blockade on the QuEra hardware
With the reordering that makes sense yes! Could add a small comment that the following is optional but good practice?

2023-05-12 13:03 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +computation. With analog Hamiltonian simulation, rather than implementing gates that represent a logical
I was thinking in terms of digital quantum computers being controlled via pulses on the hardware level with the same Hamiltonians as are used for AHS. If you give individual qubit control to rydberg devices, they _could_ do digital quantum computing as well. With that limitation, they are currently restricted to AHS.

I see your point that no one is actually doing AHS on digital quantum computers, though in theory the devices are capable of doing so with pulse access. This is all probably not so important and "**alternative**" is fine to use here, sorry for the confusion

2023-05-12 14:12 UTC, Qottmann reviewed
Some further comments after code review and minor suggestions :-)

2023-05-12 14:12 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +
Add a sentence saying "We are going to see this effect later in our experiment below" or so.

How do you feel about moving this part discussing the Rydberg blockade here down below to where the experiment is happening though?

2023-05-12 14:12 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +    Some cells of this notebook will only run when hardware is online. If you want to run it at
```suggestion
    Those cells of this notebook that contain the real device ``aquila`` will only run when hardware is online. If you want to run it at
```
To make it more precise what won't work without hardware access, and in particular, what does work without it :)

2023-05-12 14:12 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +# worrying about the effect of Rydberg blockade.
... With the interaction term off, this means that each qubit will evolve according to the unitary evolution $U = \exp\left(-i \frac{1}{2}\int d\tau \Omega(\tau) X_i\right)$ and we construct $\Omega(t)$ such that $\int d\tau \frac{1}{2}\Omega(\tau) = \pi$, i.e. $U = X$

I think this could help, optional though :-)

2023-05-12 15:50 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +the blockade radius is also inversely proportional to how hard we drive the atoms.
yes, adding it here for now, but not sure if it belongs here or in the drive section after introducing amplitude and detuning

2023-05-12 15:56 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +
Sure, that would make sense, I think. Also eliminates the uncertainty about whether to put the explanation in the drive or interaction term section!

2023-05-12 17:02 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +    :align: center
This image in not rendering in the deployment for me

2023-05-12 17:04 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +and use it first simulate a pulse program on Rydberg atoms, and then upload it and measure
```suggestion
and use it to first simulate a pulse program on Rydberg atoms, and then upload it and measure
```

2023-05-12 17:05 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +Pulse programming in PennyLane is a paradigm based on low level control of electromagnetic driving
```suggestion
Pulse programming in PennyLane is a paradigm based on low-level control of electromagnetic driving
```

2023-05-12 17:07 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +The Aquila QPU works with programmable arrays of up to 256 Rb-87 atoms, trapped in vacuum by tightly
```suggestion
The Aquila QPU works with programmable arrays of up to 256 Rubidium-87 atoms (Rb-87), trapped in vacuum by tightly
```

2023-05-12 17:07 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +The Aquila QPU works with programmable arrays of up to 256 Rb-87 atoms, trapped in vacuum by tightly
Since it's the first time you introduce the atom.

2023-05-12 17:10 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +
Need to add related demos ([Nathan's Neutral Atoms demo](https://pennylane.ai/qml/demos/tutorial_pasqal.html), [Pulse programming for VQE](https://pennylane.ai/qml/demos/tutorial_pulse_programming101.html))

2023-05-12 17:10 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +geometries to determine inter-qubit interactions. Different energy levels of these atoms are used to
Probably a good place to link to [Nathan's demo](https://pennylane.ai/qml/demos/tutorial_pasqal.html)

2023-05-12 17:11 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +A primary application of pulse control in Rydberg atom systems like Aquila is implementation of analog
```suggestion
A primary application of pulse control in Rydberg atom systems like Aquila is the implementation of analog
```

2023-05-12 17:12 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +A primary application of pulse control in Rydberg atom systems like Aquila is implementation of analog
I'm not a native English speaker so I may be wrong. But I think an article is needed here.

2023-05-12 17:17 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +where :math:`n_j` is the number operator acting on atom *j*, :math:`R_{jk} = \lvert x_j - x_k \lvert` is the
Number operator might be misleading? $n_j$ is the occupancy number of the Rydberg state.

2023-05-12 17:18 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +where :math:`n_j` is the number operator acting on atom *j*, :math:`R_{jk} = \lvert x_j - x_k \lvert` is the
At this point, I realize it's not too clear to me what system this operators are acting on. Maybe we should specify that it's for a two level system defined by a ground state and the Rydberg state?

2023-05-12 17:19 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +where :math:`n_j` is the number operator acting on atom *j*, :math:`R_{jk} = \lvert x_j - x_k \lvert` is the
```suggestion
where :math:`n_j` is the number operator acting on atom :math:`j`, :math:`R_{jk} = \lvert x_j - x_k \lvert` is the
```

2023-05-12 17:20 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +distance between atoms *j* and *k*, and :math:`C_6` i s a fixed value determined by the nature of the ground
```suggestion
distance between atoms :math:`j` and :math:`k`, and :math:`C_6` i s a fixed value determined by the nature of the ground
```

2023-05-12 17:20 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +distance between atoms *j* and *k*, and :math:`C_6` i s a fixed value determined by the nature of the ground
I just think this looks better 😛

2023-05-12 17:23 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +the interaction between each pair of atoms is thus only non-zero when both atoms are in the Rydberg state,
```suggestion
the interaction between each pair of atoms is only non-zero when both atoms are in the Rydberg state,
```

2023-05-12 17:23 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +such that :math:`\bra{\psi}\hat{n}_k \hat{n}_j\ket{\psi}=1`. Second, the energy contribution for each
```suggestion
so that :math:`\bra{\psi}\hat{n}_k \hat{n}_j\ket{\psi}=1`. Second, the energy contribution for each
```

2023-05-12 17:25 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +
Yep! This is something that maybe should have been said when the Hamiltonian was first introduced!

2023-05-12 17:26 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +access to two states; the low and high energy states are referred to as the ground and Rydberg states
```suggestion
access to two states, a low and a high energy state, referred to as the ground and Rydberg states
```

2023-05-12 17:28 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +The atoms in a Rydberg system can be driven by application of a laser pulse, which can be described by 3 parameters:
```suggestion
The atoms in a Rydberg system can be driven by the application of a laser pulse, which can be described by 3 parameters:
```

2023-05-12 17:28 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +amplitude (also called Rabi frequency) :math:`\Omega`, detuning :math:`\Delta`, and phase :math:`\phi`. While in
```suggestion
the amplitude (also called Rabi frequency) :math:`\Omega`, the detuning :math:`\Delta`, and the phase :math:`\phi`. While in
```

2023-05-12 17:28 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +allows application of a global drive pulse.
```suggestion
allows for the application of a global drive pulse.
```

2023-05-12 17:33 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +is important to be aware that some things that succeed in simulation will not be able to be sent
```suggestion
is important to be aware that some tasks that succeed in simulation will not be able to be sent
```

2023-05-12 17:37 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +
A bit of explanation of the above is in order. What is `s3`. What is this `s3_destination_folder` argument? Some inline comments would be enough I think.

2023-05-12 17:38 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +
Can the scatter dots be drawn a little bit larger?

2023-05-12 17:41 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +#
Love the table!

2023-05-12 17:42 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +# any value in the allowed range. There are no special restriction on start and end points for detuning.
```suggestion
# any value in the allowed range. There are no special restriction on the start and end points for detuning.
```

2023-05-12 17:51 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +# For amplitude, there is an additional restriction that the first and last set-point in the pulse must
```suggestion
# For the amplitude, there is an additional restriction that the first and last set-point in the pulse must
```

2023-05-12 17:52 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +# be 0 MHz. Phase has a similar restriction for the first set-point, though the last set-point can take
```suggestion
# be 0 MHz. The phase has a similar restriction for the first set-point, though the last set-point can take
```

2023-05-12 17:53 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +# -  for hardware upload, the full pulse program must not exceed :math:`4 \, \mu s`
```suggestion
# -  For hardware upload, the full pulse program must not exceed :math:`4 \, \mu s.`
```

2023-05-12 17:54 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +#    time resolution when defining pulses.
```suggestion
# -  The conversion from PennyLane to hardware upload will place set-points every 50ns—consider this
#    time resolution when defining pulses.
```

2023-05-12 17:57 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +# callable, where the callable should respect the above hardware output capabilities at all time-points.
```suggestion
# callable, where the callable should respect the above hardware output capabilities at all time points.
```

2023-05-12 17:58 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +
Let's label our axes properly :)

2023-05-12 18:01 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +# :math:`U = \text{exp}\left(-i \frac{1}{2} \int d\tau \Omega(\tau)X_i\right)` and we construct
What is $X_i$?

2023-05-12 18:03 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +#
This figure would benefit from a caption (not sure what is going on in it).

2023-05-12 18:03 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +#
Very nice! 🤩

2023-05-12 18:04 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +#
Omega and Delta not rendering for me for some reason? Can you double check?

2023-05-12 18:08 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +#
Right! Missing backslash :)

2023-05-12 18:08 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +# Where :math:`Omega` and :math:`Delta` describe the amplitude and detuning of the drive, respectively.
```suggestion
# Where :math:`\Omega` and :math:`\Delta` describe the amplitude and detuning of the drive, respectively.
```

2023-05-12 18:09 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +# :math:` \, \mu s` are 0. For this, we can use a convenience function provided in the pulse module,
This :math: not rendering for me either 😢

2023-05-12 18:10 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +# Float variables are rounded to specific, valid set-points, producing a discretized
```suggestion
# Float variables are rounded to specific, valid set points, producing a discretized
```

2023-05-12 18:11 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +# ``ahs_program.register.coordinate_list`` to see the x and y coordinates that will be passed to
```suggestion
# ``ahs_program.register.coordinate_list`` to see the :math:`x` and :math:`y` coordinates that will be passed to
```

2023-05-12 18:12 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +# Otherwise, the task will be sent to the remote hardware; it will be run when the hardware is online, and we
```suggestion
# Otherwise, the task will be sent to the remote hardware; it will be run when the hardware is online and we
```

2023-05-12 18:13 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +# We observe the same pattern on the hardware that we can see in simulation - a single
```suggestion
# We observe the same pattern on the hardware that we can see in simulation—a single
```

2023-05-12 18:14 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +#
References not rendering!

2023-05-12 18:14 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +# physics - like simulating quantum spin liquids as scales where it is not possible to classically
```suggestion
# physics—like simulating quantum spin liquids as scales where it is not possible to classically
```

2023-05-12 18:16 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +#
Ooooh, that one is weird, they are rendering locally for me. I'll look into it!

2023-05-12 18:17 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +# :math:` \, \mu s` are 0. For this, we can use a convenience function provided in the pulse module,
I think the 1.75 just needs to be moved inside, I'll try it and see

2023-05-12 18:18 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +where :math:`n_j` is the number operator acting on atom :math:`j`, :math:`R_{jk} = \lvert x_j - x_k \lvert` is the
Number operator may be misleading here. This is the occupancy number for the Rydberg state

2023-05-12 18:19 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +
Not clear what system this Hamiltonian is acting on 😨

2023-05-12 18:21 UTC, alvaro-at-xanadu requested changes
Amazing demo @lillian542! Just some minor changes and adjustments to definitions that will hopefully make it a bit clearer. It's almost good to go :)

2023-05-12 18:26 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +    :align: center
I think its rendering now, though its no longer with text wrapping now that it's using :width: instead of :scale: 

@KetpuntoG is there a way to use :width: and also set the text to wrap around the image? With :scale: making the alignment `left` or `right` made the text wrap, but that doesn't seem to work with :width:

2023-05-12 18:29 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +
moved :)

2023-05-12 18:29 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +# :math:` \, \mu s` are 0. For this, we can use a convenience function provided in the pulse module,
that worked!

2023-05-12 18:33 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +
Moved the bit about a two-state ground vs Rydberg system to just above this - is that enough or do you think it could use further clarification?

2023-05-12 18:57 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +where :math:`n_j` is the number operator acting on atom :math:`j`, :math:`R_{jk} = \lvert x_j - x_k \lvert` is the
```suggestion
where :math:`n_j=\ket{r_j}\bra{r_j}` is the number operator acting on atom :math:`j`, :math:`R_{jk} = \lvert x_j - x_k \lvert` is the
```

2023-05-12 19:15 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +where :math:`n_j` is the number operator acting on atom *j*, :math:`R_{jk} = \lvert x_j - x_k \lvert` is the
I think its clarified now, thanks!

2023-05-12 19:19 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +
It's optional and its for if you have some S3 thing set up to store things on AWS. I don't think I do, I usually comment those lines out. Added inline comments to clarify that this is optional and only needed if an S3 bucket is a thing you already know about and have.

2023-05-13 09:20 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +# :math:`U = \text{exp}\left(-i \frac{1}{2} \int d\tau \Omega(\tau)X_i\right)` and we construct
Ah right we wrote everything in the explicit bases, so $X = |g x r| + |r x g|$, i.e. Pauli X in the ground-rydberg basis

2023-05-13 09:22 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +.. math::  \hat{H}_{drive} = \sum_{k=1}^N \frac{\Omega(t)}{2} (e^{i \phi(t)}\ket{g_k}\bra{r_k} - e^{-i \phi(t)} \ket{r_k}\bra{g_k}) - \Delta(t) \hat{n}_k
```suggestion
.. math::  \hat{H}_{drive} = \sum_{k=1}^N \frac{\Omega(t)}{2} (e^{i \phi(t)}\ket{g_k}\bra{r_k} + e^{-i \phi(t)} \ket{r_k}\bra{g_k}) - \Delta(t) \hat{n}_k
```
typo :) there is a minus when writing it as Paulis $\cos(\phi) X - \sin(\phi) Y$, see also https://queracomputing.github.io/Bloqade.jl/dev/hamiltonians/

2023-05-15 09:51 UTC, Qottmann commented on demonstrations/ahs_aquila.py
> +.. math::  \hat{H}_{drive} = \sum_{k=1}^N \frac{\Omega(t)}{2} (e^{i \phi(t)}\ket{g_k}\bra{r_k} - e^{-i \phi(t)} \ket{r_k}\bra{g_k}) - \Delta(t) \hat{n}_k
updated

2023-05-15 12:51 UTC, KetpuntoG commented on demonstrations/ahs_aquila.py
> +Author: Lillian M.A. Frederiksen — Posted: 16 May 2023.
```suggestion
*Author: Lillian M.A. Frederiksen — Posted: 16 May 2023.*
```

2023-05-15 15:59 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +
Cool :) thanks!

2023-05-15 16:03 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +# has been tested in simulation, and scale if up to run on up to 256 qubits on hardware. Manipulating
```suggestion
# has been tested in simulation, and scale up to run on up to 256 qubits on hardware. Manipulating
```

2023-05-15 16:04 UTC, alvaro-at-xanadu commented on demonstrations/ahs_aquila.py
> +# It is important to note that these quantities are in radians rather than Hz where relevant, and
```suggestion
# It is important to note that these quantities are in radians per second rather than Hz where relevant, and
```

2023-05-15 18:52 UTC, trbromley reviewed
Thanks @lillian542! Great demo and excited for this as a demonstration of what we've achieved.

2023-05-15 18:52 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +system’s behaviour. For example, Rydberg atom systems have been used to probe the behaviour
```suggestion
system of interest using a programmable, controllable device that emulates the target
system. For example, Rydberg atom systems have been used to probe the behaviour
```

2023-05-15 18:52 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +.. math:: \hat{H}_{int} = \sum_{j=1}^{N-1}\sum_{k=j+1}^{N} V_{jk}\hat{n}_j\hat{n}_k = \sum_{j=1}^{N-1}\sum_{k=j+1}^{N} \frac{C_6}{R^6_{jk}}\hat{n}_j\hat{n}_k
```suggestion
.. math:: \hat{H}_{int} = \sum_{j=1}^{N-1}\sum_{k=j+1}^{N} \frac{C_6}{R^6_{jk}}\hat{n}_j\hat{n}_k
```
Minor, but do we need the middle part?

2023-05-15 18:52 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +be aware of the hardware specifications and capabilities when planning your pulse program. These
```suggestion
to hardware due to physical constraints of the measurement and control setup. Also,
be aware of the hardware specifications and capabilities when planning your pulse program. These
```

2023-05-15 18:52 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +detail where to find these specifications and where they are relevant as we go through this demo.
I'm not sure if we need the end of this paragraph. Maybe I'm missing something, but doesn't it boil down to saying that the user should be aware of hw limitations, which is mentioned in the preceding sentence.

2023-05-15 18:52 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +
It currently seems a little too small for me.

2023-05-15 18:52 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +#      {'interaction_coeff': 862619.7915580727}
I get `{'interaction_coeff': 5420000.0}` :thinking:

2023-05-15 18:52 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +aquila.hardware_capabilities["rydberg"].dict()
Out of curiosity, what is the difference between `hardware_capabilities` and `settings`?

2023-05-15 18:52 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +#      {'interaction_coeff': 862619.7915580727}
With PL v0.30

2023-05-15 18:52 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +#     | Detuning      | -19.89436788 MHz | +19.89436788 MHz | 3.2e-8 MHz    |  PWL          |  39788735 MHz/s         |
I don't think we need to fix here, but `39788735 MHz/s` feels like units of per microsecond might be more informative.

2023-05-15 18:52 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +
Not sure if this is imposed by CI, but the double spacing around functions could be dropped for a demo

2023-05-15 18:52 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +s3 = ("my-bucket", "my-prefix")
Maybe don't mention the bucket

2023-05-15 18:52 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +# simulate the quantum dymaics of the full experimental system!  [#Semeghini]_ [#Asthana2022]_
```suggestion
# simulate the quantum dynamics of the full experimental system!  [#Semeghini]_ [#Asthana2022]_
```

2023-05-15 18:52 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +#     `Amazon Quantum Computing Blog <https://aws.amazon.com/blogs/quantum-computing/realizing-quantum-spin-liquid-phase-on-an-analog-hamiltonian-rydberg-simulator/>`__, 2021.
Are these references used?

2023-05-15 19:16 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +#     | Detuning      | -19.89436788 MHz | +19.89436788 MHz | 3.2e-8 MHz    |  PWL          |  39788735 MHz/s         |
Good point, and I think we should just fix it here

2023-05-15 19:19 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +#      {'interaction_coeff': 862619.7915580727}
Should be your version of the braket plugin that matters. If you connect to Aquila and do `aquila.settings` it says 5420000?

2023-05-15 19:27 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +aquila.hardware_capabilities["rydberg"].dict()
`settings` includes only the physical parameters of the _quantum_ device, like interaction coefficient, or for transmons, resonant frequencies of the qubits. I don't love `settings` as a name, but we couldn't come up with anything better when we discussed, so that's what we ran with. Its a thing we made up to help us with initializing ParametrizedEvolution operators that have the correct constants to match the quantum hardware.

`hardware_capabilities` also include specifications related to the (classical) control and/or measurement hardware that users might need to be aware of. Its a thing we pull from the underlying device we are accessing on the braket end, and not a thing we own or control on the PL side, though of course we could modify it after retrieving it if we want to at some point in the future.

2023-05-15 19:31 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +
bigger now

2023-05-15 19:32 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +s3 = ("my-bucket", "my-prefix")
removed

2023-05-15 19:33 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +
removed

2023-05-15 19:35 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +#     `Amazon Quantum Computing Blog <https://aws.amazon.com/blogs/quantum-computing/realizing-quantum-spin-liquid-phase-on-an-analog-hamiltonian-rydberg-simulator/>`__, 2021.
3 are mentioned in passing as examples of applications for pulses on Rydberg systems, if people are interested in reading more about that. 

One (the dev guide) is not referenced anywhere in particular, but I think should be included because it was a point of reference when making the demo, though I can't pinpoint exact places where it makes most sense to cite it.

2023-05-15 19:37 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +detail where to find these specifications and where they are relevant as we go through this demo.
I guess its just to reassure the reader that we aren't just going to tell them they have to be aware, we're also going to tell them where to find the information. I've trimmed it down to be more direct.

2023-05-15 19:39 UTC, lillian542 commented on demonstrations/ahs_aquila.py
> +#     | Detuning      | -19.89436788 MHz | +19.89436788 MHz | 3.2e-8 MHz    |  PWL          |  39788735 MHz/s         |
On second thought I've set up the examples further down to be in seconds, and talked about 50ns time bins, and I think its clearer to leave it this way.

2023-05-15 19:56 UTC, trbromley commented on demonstrations/ahs_aquila.py
> +aquila.hardware_capabilities["rydberg"].dict()
Thanks!

2023-05-15 19:57 UTC, trbromley approved these changes

2023-05-15 20:30 UTC, merged