First Draft
PennyLaneAI/qml pull request #777
Opened 2023-05-04 21:58 UTC by Danimhn

**Title: Phase Kickback Tutorial**

**Summary: An engaging and beginner friendly tutorial on quantum phase kickback**

**Relevant references: N/A**

**Possible Drawbacks: N/A**

**Related GitHub Issues: N/A**

2023-05-05 20:19 UTC, frederikwilde requested changes

2023-05-05 20:19 UTC, frederikwilde commented on demonstrations/tutorial_phase_kickback.py
> +    return qml.FlipSign(secret_key, wires=[i for i in range(1, num_wires)])
If you want to pass a list here, you could use `wires=list(range(1, num_wires))`, but you can also pass the range directly to wires: `wires=range(1, num_wires`.

2023-05-05 20:19 UTC, frederikwilde commented on demonstrations/tutorial_phase_kickback.py
> +    return qml.BasisState(key, wires=[i for i in range(1, num_wires)])
Same comment as above.

2023-05-05 20:19 UTC, frederikwilde commented on demonstrations/tutorial_phase_kickback.py
> +def quantum_locking_mechanism(lock, key):
For clarity it would probably good to give this function a doc string with its signature.
```
"""
Computes whether a given key unlocks a given lock.

Args:
    lock (callable): A function executing quantum operations.
    key (Iterable[int]): An iterable of bits (0 or 1), where the number of bits is
        equal to the number of qubits that the lock acts on.

Returns:
    int: Either 0 or 1, where 0 indicates the correct key.
"""
```

2023-05-05 20:19 UTC, frederikwilde commented on demonstrations/tutorial_phase_kickback.py
> +# And just like that, we’ve uncovered the quantum secrets hidden by the lock. Let’s now crack open our
We don't really crack it, right? Maybe say "Let's see how our quantum lock works in practice, by operating it with Pennylane."

2023-05-05 20:19 UTC, frederikwilde commented on demonstrations/tutorial_phase_kickback.py
> +# You’ve successfully explored the remarkable phenomenon of phase kickback and created an unbreakable
Really nice tutorial! It's very accessible and fun to read :-)

2023-05-08 13:58 UTC, Danimhn commented on demonstrations/tutorial_phase_kickback.py
> +# algorithms, including Deutsch’s algorithm, the Deutsch-Jozsa algorithm, and Quantum Phase
Deutsch-Jozsa algorithm is an extension of Deutsch's algorithm. They're both toy algorithms really.

2023-05-08 14:00 UTC, Danimhn commented on demonstrations/tutorial_phase_kickback.py
> +dev = qml.device("default.qubit", wires=num_wires, shots=1)
Hmm, yeah I'm not sure. There are a number of other nuances that we don't discuss here such as the cases where the "key" is a superposition of different eigenstates. Not sure if that complexity is appropriate here or not

2023-05-08 14:03 UTC, Danimhn commented on demonstrations/tutorial_phase_kickback.py
> +#      U|n\rangle =
That's a good idea!

2023-05-08 14:06 UTC, Danimhn commented on demonstrations/tutorial_phase_kickback.py
> +# And just like that, we’ve uncovered the quantum secrets hidden by the lock. Let’s now crack open our
Hmm, here by crack I didn't mean "break", I meant just open in fun language, but I can see how it could come across that way lol

2023-05-08 14:06 UTC, Danimhn commented on demonstrations/tutorial_phase_kickback.py
> +def quantum_locking_mechanism(lock, key):
Yeah I'm not sure whether docstrings are appropriate for a tutorial?

2023-05-08 14:09 UTC, Danimhn commented on demonstrations/tutorial_phase_kickback.py
> +# Now let’s create the most formidable lock in the universe: the “quantum lock”! Here our lock is
"the most formidable lock in the universe" is really for theatrical purposes here to make the tutorial exciting and engaging because there's really no lock, the lock metaphor is just to make it more fun lol

2023-05-10 12:48 UTC, ikurecic requested changes
A great tutorial, well done!

I mostly made some formatting and content suggestions, but I also have to admit I found the story a little bit difficult to follow. 😅 Throughout the text you're going back and forth from setting up the code to explaining how things work, but I'm missing the main motivation. There are some terms that are not explained/introduced in the text, and it's not really clear at a first read what the 'problem' is that you are trying to set up/solve with the lock. I left you a few comments to try to get you through that. :)

Try explicitly setting up the problem at the start and explaining it step-by-step before you dive into the 'fun stuff'. You have a great style with writing and presenting what you're trying to show, so if you put yourself in the shoes of someone who is just "getting started," it will help you figure out where they might need extra help following what you're saying.

Also, it would be fantastic if you could add your bio and photo to this PR (see my comments/suggestions). Let me know if you have any questions (you can also ping me on Slack, if that's simpler :) ).

2023-05-10 12:48 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +*Author: Danial Motlagh.*
```suggestion
r"""

Building a quantum lock using phase kickback
============================================

.. meta::
    :property="og:description": Use phase kickback to create an unbreakable quantum lock
    :property="og:image": TK

.. related::
   tutorial_qubit_rotation Basic tutorial: qubit rotation

*Author: Danial Motlagh — Posted: TK TKTK TKTK.*
```
Please note that the date and image will still need to be updated before publication.

2023-05-10 12:48 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +# -----------------------
```suggestion
# Setting up PennyLane
# --------------------
```

2023-05-10 12:48 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +# ---------------------------------
```suggestion
# Introduction to Phase Kickback
# ------------------------------
```

2023-05-10 12:48 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +# ---------------------------------
```suggestion
# Introduction to phase kickback
# ------------------------------
```

2023-05-10 12:48 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +# ---------------------------------
I think you should start with this section, to motivate what you're going to show. Otherwise it's not really clear what and why you're setting up with PennyLane.

2023-05-10 12:48 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +# -----------------------
I think this section should come after you've introduced the concept of phase kickback. Otherwise it's not really clear what you're setting up and why. :)
Perhaps you could just 'merge' this with the 'building a quantum lock' section?

2023-05-10 12:48 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +world and learn how to create an unbreakable lock? Let’s go!
It would be great if you could add a sentence here to explain what phase kickback is, in case the reader hasn't come across the term yet. :)

2023-05-10 12:48 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +# circuits.
```suggestion
# First, let’s import the PennyLane and NumPy libraries and create a device to run our quantum
# circuits.
```

2023-05-10 12:48 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +# Estimation.
```suggestion
# Phase kickback is a powerful quantum phenomenon that uses entanglement properties to allow for the transfer of phase information from a
# target register to a control qubit. It plays a vital role in many quantum
# algorithms, including Deutsch’s algorithm, the Deutsch–Jozsa algorithm, and quantum phase
# estimation.
```

2023-05-10 12:48 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +# “kicked back” to the control qubit. A subsequent Hadamard gate on the ancilla qubit enables the
Here it would be good to add a sentence explaining what "kicked back" means, mathematically. :)

2023-05-10 12:48 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +#    :width: 50%
Great figure. :) Do you mind referring to it in some way in the text? You can add that the qubit is initialized at $|0\rangle$, the other one is $|ψ\rangle$, the unitary is named U etc. The paragraph you wrote to explain how phase kickback works is great and concise, but if you're new to the topic and looking at this for the first time, a bit more of a step-by-step explanation would be helpful.

2023-05-10 12:48 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +# Now let’s create the most formidable lock in the universe: the “quantum lock”! Here our lock is
Small problem, though. "Quantum lock" is already a term used in physics. 🤔 Altering it a bit might not be the worst idea.

2023-05-10 12:48 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +# which has eigenvalue -1:
```suggestion
# represented by a unitary :math:`U`, which has all but one eigenvalue equal to 1. Our one “key” eigenstate
# has eigenvalue -1:
```

2023-05-10 12:48 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +# unlock the quantum lock with 1 representing unlocking the lock and 0 representing a failure. To make
```suggestion
# If the "key" eigenstate is used to effectively unlock the quantum lock, then the outcome of the measurement on the control qubit tells us whether we were able to successfully
# unlock it. In this case, 1 represents unlocking the lock and 0 represents failure to unlock it. To make
```

2023-05-10 12:48 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +#      U|n\rangle =
Agreed, but this should happen a few paragraphs up, when you first introduce the operator/lock. :)

2023-05-10 12:48 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +# We’ll make use of ``qml.FlipSign`` to build our lock:
It might be helpful if you linked to some useful pages in your tutorial. For example, here you could link to the PL docs page. :)
Here you could also spend a few words to explain what this function does. For example, "[…] qml.FlipSign, which …, to build our lock."

2023-05-10 12:48 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +# We first apply a Hadamard to our control qubit:
I think it's a bit nicer to have _something_ on the left. :) Name your qubit in the sentence and just write it out there. I had to check the color-inverting settings in my browser to make sure it wasn't 'eating' the left sides. 😅

2023-05-10 12:48 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +# Applying the controlled unitay operation we get:
```suggestion
# By applying the controlled unitary operation we get:
```

2023-05-10 12:48 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +# We first apply a Hadamard to our control qubit:
Same comment about the left sides as above.

2023-05-10 12:48 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +# As you can see, we were unable to fool the almighty lock, don’t believe me? See for youself!
```suggestion
# As you can see, we were unable to fool the almighty lock. Don’t believe me? See for youself!
```

2023-05-10 12:48 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +# -------------------
```suggestion
# Conclusion
# ----------
```

2023-05-10 12:48 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +# You’ve successfully explored the remarkable phenomenon of phase kickback and created an unbreakable
```suggestion
# Congratulations! You’ve successfully explored the remarkable phenomenon of phase kickback and created an unbreakable
```

2023-05-10 12:48 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +*Author: Danial Motlagh.*
If you have another 'related' tutorial in mind, feel free to add it here. :)

2023-05-10 12:48 UTC, ikurecic commented on demos_getting-started.rst
> +    :tooltip: Implement a quantum lock using phase kickback.
```suggestion
    :tooltip: Use phase kickback to create an unbreakable quantum lock.
```

2023-05-10 12:48 UTC, ikurecic commented on demos_getting-started.rst
> +    :figure: demonstrations/phase_kickback/Phase_Kickback.png
This would probably need to be replaced with a fancy PL-style illustration at publication.

2023-05-10 12:48 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +#
```suggestion
#
#
# About the author
# ----------------
# .. include:: ../_static/authors/danial_motlagh.txt
```

2023-05-11 14:05 UTC, Danimhn commented on demos_getting-started.rst
> +    :figure: demonstrations/phase_kickback/Phase_Kickback.png
The thumb nail is PL-style, I took it from the codebook.

2023-05-11 14:06 UTC, Danimhn commented on demonstrations/tutorial_phase_kickback.py
> +world and learn how to create an unbreakable lock? Let’s go!
I do that in the introduction section, this is just a hook to get the reader intrigued.

2023-05-11 14:07 UTC, Danimhn commented on demonstrations/tutorial_phase_kickback.py
> +# ---------------------------------
Agreed

2023-05-11 14:09 UTC, Danimhn commented on demonstrations/tutorial_phase_kickback.py
> +# -----------------------
I agree that it should come after the introduction but I think keeping the boilerplate things separate from the "meat" of the tutorial is better

2023-05-12 12:16 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +world and learn how to create an unbreakable lock? Let’s go!
Yeah, but I'm not feeling hooked while reading it. :) "[…] phase kickback, thing-that-shows-up-everywhere-or-is-important-because-reason, and utilizing it […]" would totally cut it.

2023-05-12 12:18 UTC, ikurecic commented on demos_getting-started.rst
> +    :figure: demonstrations/phase_kickback/Phase_Kickback.png
Indeed, but in the meantime we have actually gotten a professional designer on board, who will polish it up to be used in thumbnail form. :) This comment is for you to be aware and for Guillermo to not forget.

2023-05-12 12:20 UTC, ikurecic commented
Hey @Danimhn , I see you requested a review from me, but there are some suggestions/comments that haven't been addressed yet. 😅 Is there something specific you wanted me to look at?

2023-05-12 12:22 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +# .. figure:: ../demonstrations/phase_kickback/Phase_Kickback.png
@KetpuntoG , this is an image @Danimhn took from the Codebook. Since the author didn't create it, to avoid incorrect attributions, I think it would be good to add a small image description in brackets that also links to the correct Codebook node. What do you think?

2023-05-12 14:31 UTC, KetpuntoG commented on demonstrations/tutorial_phase_kickback.py
> +# .. figure:: ../demonstrations/phase_kickback/Phase_Kickback.png
Sounds good to me, I would link to the codebook.
I saw this file demonstrations/phase_kickback/Phase_Kickback.png:Zone.Identifier
I'm not sure what it does but it may be related to this?

2023-05-16 19:37 UTC, Danimhn commented on demonstrations/tutorial_phase_kickback.py
> +# “kicked back” to the control qubit. A subsequent Hadamard gate on the ancilla qubit enables the
I mean it's pretty self-explanatory and we already mention "transfer of phase information from a target register to a control qubit", so I think they can connect the dots.

2023-05-16 19:39 UTC, Danimhn commented on demonstrations/tutorial_phase_kickback.py
> +# ----------------------------
I like the emojis, we got rid of most of them but I think it would look visually nice to leave at least some of them in

2023-05-16 19:44 UTC, Danimhn commented on demonstrations/tutorial_phase_kickback.py
> +#    :width: 50%
I mean I think it's fairly self-explanatory. We we're told to assume the reader has some basic understanding of the concept. If they can't read a circuit diagram, then this is not the right tutorial for them to start with no?

2023-05-16 19:46 UTC, Danimhn commented on demonstrations/tutorial_phase_kickback.py
> +# Next, we need to prepare the corresponding input state given a trial key. We’ll make use of
I mean that's what exactly what we're doing up to this point in the tutorial no?

2023-05-16 19:47 UTC, Danimhn commented on demonstrations/tutorial_phase_kickback.py
> +# We first apply a Hadamard to our control qubit:
Not sure what you mean here

2023-05-16 19:47 UTC, Danimhn commented on demonstrations/tutorial_phase_kickback.py
> +# ----------------------------------------------
I like the emojis, we got rid of most of them but I think it would look visually nice to leave at least some of them in

2023-05-17 12:06 UTC, ikurecic requested changes

2023-05-17 12:06 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +# Next, we need to prepare the corresponding input state given a trial key. We’ll make use of
I think it won't hurt you to add a sentence at the start of the section to explain what you are attempting to do. A person who knows about this topic will know what you're doing. A person who's never seen it before will feel confused. Let's say, you can extend the last sentence of the first paragraph like this: "the lock is unlocked by only one eigenstate, the "key" eigestate with the eigenvalue -1."

2023-05-17 12:06 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +# ---------------------------
```suggestion
# Opening the Quantum Lock
# ------------------------
```
Same comment as everywhere else, you should remove emoji from section titles.

2023-05-17 12:06 UTC, ikurecic commented on demonstrations/tutorial_phase_kickback.py
> +# .. math:: \rightarrow |0\rangle|\text{incorrect key}\rangle
Same comment as above.

2023-05-17 14:59 UTC, Danimhn commented on demonstrations/tutorial_phase_kickback.py
> +#    :width: 50%
But that's the thing, you don't need to know about phase kick back to tell which is a control qubit, if you have a filled dot on a wire and then a vertical line coming out from it, that's a control qubit. I believe it's clear from the paragraphs above, what's happening especially given that we make reference to the Hadamards. If you think something is not clear, please feel free to suggest a commit and I will commit them.

2023-05-18 23:18 UTC, Danimhn commented on demonstrations/tutorial_phase_kickback.py
> +# If the "key" eigenstate is used to effectively unlock the quantum lock, then the outcome of the measurement on the control qubit tells us whether we were able to successfully
Updated this to make things more clear

2023-05-18 23:19 UTC, Danimhn commented on demonstrations/tutorial_phase_kickback.py
> +# .. figure:: ../demonstrations/phase_kickback/Phase_Kickback.png
Done

2023-05-24 18:55 UTC, KetpuntoG reviewed
Last couple of comments and it's done! Very interesting content 🚀

2023-05-24 18:55 UTC, KetpuntoG commented on demonstrations/tutorial_phase_kickback.py
> +# We’ll make use of `[qml.FlipSign] <https://docs.pennylane.ai/en/stable/code/api/pennylane.FlipSign.html>`_ to build our lock:
```suggestion
# We’ll make use of :class:`~.pennylane.FlipSign` to build our lock:
```

I think this will render better

2023-05-24 18:55 UTC, KetpuntoG commented on demonstrations/tutorial_phase_kickback.py
> +# `[qml.BasisState] <https://docs.pennylane.ai/en/stable/code/api/pennylane.BasisState.html>`_ to build the key:
```suggestion
# :class:`~.pennylane.BasisState`to build the key:
```

2023-05-24 18:55 UTC, KetpuntoG commented on demonstrations/tutorial_phase_kickback.py
> +    qml.ctrl(lock, 0)  # Controlled unitary operation
```suggestion
    qml.ctrl(lock, control=0)  # Controlled unitary operation
```

2023-07-29 13:19 UTC, KetpuntoG approved these changes
🚀 Great job!

2023-07-29 13:20 UTC, merged