Grover's Algorithm Tutorial
PennyLaneAI/qml pull request #781
Opened 2023-05-05 13:53 UTC by ludmilaasb

**Title:**
Grover's Algorithm

**Summary:**
In this tutorial, we showcase the basic aspect of Grover's algorithm. We briefly introduce the reader to how to perform a search on a list with n-bitstring entries building the circuit step-by-step:

- Initial state preparation
- Oracle
- Grover Diffusor
- Measurement

The state transformation along the circuit is inspected with `qml.Snapshot`. The Oracle and Diffusor operators are implemented using `qml.FlipSign` and `qml.templates.GroverOperator`, respectively.  The tutorial starts with searching a single entry using a 2-qubit circuit. Following this, the tutorial concludes with a more generalized version. 

**Relevant references:**

https://docs.pennylane.ai/en/stable/code/api/pennylane.snapshots.html
https://docs.pennylane.ai/en/stable/code/api/pennylane.GroverOperator.html

**Possible Drawbacks:**
N/A

**Related GitHub Issues:**
N/A

I hope you enjoy :)

2023-05-09 01:20 UTC, BorjaRequena reviewed
Really cool tutorial overall! It was nice to revisit Grover's algorithm step by step and I think it was a nice idea to use snapshots to show the intermediate steps. Also, I love the gif!

2023-05-09 01:20 UTC, BorjaRequena commented on demonstrations/tutorial_grovers_algorithm.py
> +# the Oracle and inspect their action in the circuit.
Here, we could stick with the same example $\omega=|01\rangle$ instead of changing to $\omega=|00\rangle$. I think this may be confusing, particularly for non-avid coders who may overlook the first line of code below. At least, I would explicitly mention here that we change target state.

2023-05-09 01:20 UTC, BorjaRequena commented on demonstrations/tutorial_grovers_algorithm.py
> +# verify in the circuit below that iterating the *Grover iterator* :math:`U_\omega U_D` once is enough
Minor suggestions:
```suggestion
# Now, we have all the building blocks to implement a single-item search in a 2-qubit circuit. We can
# verify in the circuit below that applying the *Grover iterator* :math:`U_\omega U_D` once is enough
```

2023-05-09 01:20 UTC, BorjaRequena commented on demonstrations/tutorial_grovers_algorithm.py
> +qml.snapshots(circuit)()
Here I'd try to format the output nicely, like mentioned before.

2023-05-09 01:20 UTC, BorjaRequena commented on demonstrations/tutorial_grovers_algorithm.py
> +# Now, let us consider the problem with higher :math:`N`, accepting :math:`M` solutions, with
Minor suggestions:
```suggestion
# Now, let us consider the generalized problem with large :math:`N`, accepting :math:`M` solutions, with
```

2023-05-09 01:20 UTC, BorjaRequena commented on demonstrations/tutorial_grovers_algorithm.py
> +# which is easily implemented using ``qml.template.GroverOperator``.
Link to docs (not too confident about this one):
```suggestion
# which is easily implemented using :class:`~.GroverOperator`.
```

2023-05-09 01:20 UTC, BorjaRequena commented on demonstrations/tutorial_grovers_algorithm.py
> +
```suggestion
plt.show()

```

2023-05-09 01:20 UTC, BorjaRequena commented on demonstrations/tutorial_grovers_algorithm.py
> +# In conclusion, you learned the basic steps of Grover's algorithm and how to implement it to search
Same as at the beginning. Again, personal preference.
```suggestion
# In conclusion, we have learned the basic steps of Grover's algorithm and how to implement it to search
```

2023-05-09 11:00 UTC, ludmilaasb commented on demonstrations/tutorial_grovers_algorithm.py
> +following problem: suppose that you are searching for a specific phone number in a random-ordered
Indeed!

2023-05-09 11:08 UTC, ludmilaasb commented on demonstrations/tutorial_grovers_algorithm.py
> +5. Measurement
Indeed, looks more better this way

2023-05-09 11:09 UTC, ludmilaasb commented on demonstrations/tutorial_grovers_algorithm.py
> +plt.bar(bit_strings, y)
Thank you so much! Those outputs were bugging me as well xD

2023-05-09 11:10 UTC, ludmilaasb commented on demonstrations/tutorial_grovers_algorithm.py
> +# ``qml.Snapshot`` to see how the states change on each step. Let us check the probability of finding
Good idea!

2023-05-09 11:13 UTC, ludmilaasb commented on demonstrations/tutorial_grovers_algorithm.py
> +results
Yeah, right? I was also wondering how to manipulate that bar but this solution looks simpler. Thanks for the suggestion!

2023-05-09 11:18 UTC, ludmilaasb commented on demonstrations/tutorial_grovers_algorithm.py
> +    # return qml.state()
Definitely!

2023-05-09 12:26 UTC, ludmilaasb commented
Thank you @BorjaRequena for the comments! I am working on it! :D

2023-05-09 12:35 UTC, ludmilaasb commented on demonstrations/tutorial_grovers_algorithm.py
> +# where :math:`\omega` corresponds to the state which encondes the solution, and :math:`U_\omega` acts
Indeed, that's better!

2023-05-09 12:36 UTC, ludmilaasb commented on demonstrations/tutorial_grovers_algorithm.py
> +print(results)
Changed in the last commit!

2023-05-09 12:37 UTC, ludmilaasb commented on demonstrations/tutorial_grovers_algorithm.py
> +
Agreed! Changed the bar plot in the last commit

2023-05-09 12:39 UTC, ludmilaasb commented on demonstrations/tutorial_grovers_algorithm.py
> +qml.snapshots(circuit)()
Agreed! Changed!

2023-05-09 16:44 UTC, alvaro-at-xanadu commented on demos_quantum-computing.rst
> +    :description: :doc:`demos/grovers_algorithm`
```suggestion
    :description: :doc:`demos/tutorial_grovers_algorithm`
```

2023-05-09 16:56 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +algorithm, proposed by Lov Grover[1]. In the original description, the author approaches the
There are ways to cite in restructured text, so that you can click and it brings you to the reference section! Check out other tutorials to see how. E.g. tutorial_photonics.py

2023-05-09 16:56 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +
Nice intro :)

2023-05-09 16:58 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +answer, whereas any classical algorithm would require :math:`O(N)` queries for the same problem.
```suggestion
answer, whereas any classical algorithm would require :math:`O(N)` queries.
```

2023-05-09 16:59 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +answer, whereas any classical algorithm would require :math:`O(N)` queries for the same problem.
Just trimming down words :) Always a good exercise.

2023-05-09 17:00 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +4. Repeat steps 2 and 3 :math:`\approx \frac{\pi}{4}\sqrt{N}` times
```suggestion
4. Repeat steps 2 and 3  approximately :math:`\frac{\pi}{4}\sqrt{N}` times
```

2023-05-09 17:07 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +plt.bar(bit_strings, y)
Now I'm getting warnings about the imaginary part being discarded, but idk if this is only locally. We'll see when it builds in the deployed version!

2023-05-09 17:10 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +
I like the plots, but let's try to make them a bit more complete. E.g Title, x-axis label, y-axis label. They would also benefit from being less "matplotlib-ey". E.g, we could use PennyLane colours, or more pastel colours like you have for your circuits!

2023-05-09 17:13 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +# Let's assume for now that only one index satisfies $f(x) = 1$. We are going to call this index $\omega$.
```suggestion
# Let's assume for now that only one index satisfies :math:`f(x) = 1`. We are going to call this index $\omega$.
```

2023-05-09 17:13 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +# Let's assume for now that only one index satisfies $f(x) = 1$. We are going to call this index $\omega$.
This happens to me all the time 😅

2023-05-09 17:15 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +# To access :math:`f(x)` with an Oracle, we can formulate a unitary operator such that:
Colons are used less than we use them in Spanish and Portuguese. Too bad cause I like them 😞

2023-05-09 17:16 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +# Let us take a look at the following example: if we pass the array ``[0,0]``, the sign of the state
```suggestion
# Let us take a look at an example. If we pass the array ``[0,0]``, the sign of the state
```

2023-05-09 17:18 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +# the Oracle and inspect their action in the circuit.
I am confused 😅 I think this just needs to be changed to $\vert oo \rangle$.

2023-05-09 17:18 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +# the Oracle and inspect their action in the circuit.
```suggestion
# the Oracle and inspect its action in the circuit.
```

2023-05-09 17:19 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +# We can see that the amplitude of the state :math:`\vert 01\rangle` flipped. Following, we can prepare
```suggestion
# We can see that the amplitude of the state :math:`\vert 01\rangle` flipped. Now, let us prepare
```

2023-05-09 17:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +# The unitary :math:`U_D` also acts as a rotation, but this time through :math:`\vert s \rangle`.
```suggestion
# The unitary :math:`U_D` also acts as a rotation, but this time through the uniform superposition :math:`\vert s \rangle`.
```

2023-05-09 17:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +# The unitary :math:`U_D` also acts as a rotation, but this time through :math:`\vert s \rangle`.
Easy to forget what $\vert s \rangle$ is (I forgot and had to scroll up)

2023-05-09 17:22 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +#
Love the gif so much 🤩

2023-05-09 17:28 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +# which is easily implemented using ``qml.template.GroverOperator``.
I think you might not even need the "template" part! See [here](https://docs.pennylane.ai/en/stable/code/api/pennylane.GroverOperator.html) and try doing it with `qml.GroverOperator` It's just less wordy 😅

2023-05-09 17:29 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +# code below. For simplicity, we are going to implement the search for states
```suggestion
# code below. For simplicity, we are going to search for the states
```

2023-05-09 17:30 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +# :math:`M` items in a list of size :math:`N` with high probability.
I think this would look better as a paragraph than as a bulleted list

2023-05-09 17:31 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +# **Next Step:** *Amplitude Amplification*
Not needed! You already finished strong by referring them to amplitude amplification :)

2023-05-09 17:33 UTC, alvaro-at-xanadu requested changes
Amazing job @ludmilaasb ! As you see, most of my comments are minor style and presentation fixes and presentation! Thank you for this very clear and succinct tutorial :)

2023-05-10 08:49 UTC, ludmilaasb commented on demonstrations/tutorial_grovers_algorithm.py
> +# which is easily implemented using ``qml.template.GroverOperator``.
Ok! Let me check it locally, thanks for the correction! :)

2023-05-10 10:52 UTC, ludmilaasb commented on demonstrations/tutorial_grovers_algorithm.py
> +plt.bar(bit_strings, y)
True, the complex numbers warning is also appearing here. Is there a nice/elegant way to suppress it?

2023-05-10 11:07 UTC, ludmilaasb commented on demonstrations/tutorial_grovers_algorithm.py
> +catalog containing :math:`N` entries. To find such a number with a probability of
Hmm, I am not sure... 

I mean, if you have a random list I think this information is kind of implicit, isn't it? Besides, I feel that it would require a bit more explanation, maybe using conditional probability and so on to get from 1/N to 1/2 probability of finding the answer. 

I don't know, I am afraid that would be a digression.

2023-05-10 11:09 UTC, ludmilaasb commented on demonstrations/tutorial_grovers_algorithm.py
> +catalog containing :math:`N` entries. To find such a number with a probability of
And kind of makes sense if you have a list/domain and check half of the content it is intuitive that you would get a 50% chance of finding what you want, that's why I didn't explain this in detail.

2023-05-10 14:38 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +plt.bar(bit_strings, y)
Maybe using np.real for the amplitudes?

2023-05-10 14:39 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +# computational basis states, represented via :math:`N` :math:`n-`\ bit strings
Yes, I think this works!

2023-05-10 18:44 UTC, KetpuntoG commented on demonstrations/tutorial_grovers_algorithm.py
> +
Take a look to another demo to check this initial lines:

```python
.. meta::
    :property="og:description": Learn how to use the differentiable Hartree-Fock solver
    :property="og:image": https://pennylane.ai/qml/_images/differentiable_HF.png

.. related::
    tutorial_quantum_chemistry Building molecular Hamiltonians
    tutorial_vqe A brief overview of VQE
    tutorial_givens_rotations Givens rotations for quantum chemistry
    tutorial_adaptive_circuits Adaptive circuits for quantum chemistry


*Author: Soran Jahangiri — Posted: 09 May 2022. Last updated: 09 May 2022.*

```

In the first part you should put the description and the name of the thumbnail after /images

if you think there is a related tutorial you could include it as well. 

Finally your name and the date of publication. You can put today's date and I will update it.

2023-05-10 18:46 UTC, KetpuntoG commented on demonstrations/tutorial_grovers_algorithm.py
> +#     Cambridge University Press.
Now you can add the bio here 😄
Look at the final lines in this [demo](https://github.com/PennyLaneAI/qml/pull/733)

Don't forget to add these files with your information 
<img width="347" alt="Captura de pantalla 2023-05-10 a las 14 46 12" src="https://github.com/PennyLaneAI/qml/assets/65235481/c38bae7b-b7f1-4927-9bbb-555563f9ec64">

2023-05-11 09:00 UTC, ludmilaasb commented on demonstrations/tutorial_grovers_algorithm.py
> +
All right! Added!

2023-05-11 09:08 UTC, ludmilaasb commented on demonstrations/tutorial_grovers_algorithm.py
> +plt.bar(bit_strings, y)
All right. I think there is no problem since the imaginary part is equal to zero anyway.

2023-05-11 09:10 UTC, ludmilaasb reviewed
Thank you guys for revising my tutorial! :D

2023-05-11 18:22 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +plt.ylabel("Probability Amplitute")
```suggestion
plt.ylabel("Probability Amplitude")
```

2023-05-11 18:23 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +plt.title("States probabilities amplitutes")
```suggestion
plt.title("States probabilities amplitudes")
```

2023-05-11 18:23 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +plt.ylabel("Probability Amplitute")
```suggestion
plt.ylabel("Probability Amplitude")
```

2023-05-11 18:23 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +plt.title("States probabilities amplitutes")
```suggestion
plt.title("States probabilities amplitudes")
```

2023-05-11 18:24 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +    qml.Snapshot("Amplitute after diffusion")
```suggestion
    qml.Snapshot("Amplitude after diffusion")
```

2023-05-11 18:24 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +    qml.Snapshot("Amplitute after diffusion")
```suggestion
    qml.Snapshot("Amplitude after diffusion")
```

2023-05-11 18:24 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +plt.ylabel("Probability Amplitute")
```suggestion
plt.ylabel("Probability Amplitude")
```

2023-05-11 18:24 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +plt.title("States probabilities amplitutes")
```suggestion
plt.title("States probabilities amplitudes")
```

2023-05-11 18:25 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +# If you would like to watch more about Grover's Algorithm check `this video <https://youtu.be/KeJqcnpPluc>`__!
```suggestion
# If you would like to learn more about Grover's Algorithm, check `this video <https://youtu.be/KeJqcnpPluc>`__! 
```

2023-05-11 18:29 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +catalog containing :math:`N` entries. To find such a number with a probability of
```suggestion
catalogue containing :math:`N` entries. To find such a number with a probability of
```

2023-05-11 18:31 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +    # Fliping the marked state
```suggestion
    # Flipping the marked state
```

2023-05-11 18:31 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_grovers_algorithm.py
> +plt.legend(["Initial state |00>", "After fliping it"])
```suggestion
plt.legend(["Initial state |00>", "After flipping it"])
```

2023-05-11 18:32 UTC, alvaro-at-xanadu approved these changes
Approved! But please commit the grammar changes :)

2023-05-11 20:02 UTC, KetpuntoG commented on demonstrations/tutorial_grovers_algorithm.py
> +# # Let us take a look at an example. If we pass the array ``[0,0]``, the sign of the state
```suggestion
# Let us take a look at an example. If we pass the array ``[0,0]``, the sign of the state
```

2023-05-11 20:03 UTC, KetpuntoG commented on demonstrations/tutorial_grovers_algorithm.py
> +# This can be easily implemented with :class:`~.FlipSign`, which takes a binary array and flips the sign
```suggestion
# This can be easily implemented with :class:`~.pennylane.FlipSign`, which takes a binary array and flips the sign
```

2023-05-11 20:03 UTC, KetpuntoG commented on demonstrations/tutorial_grovers_algorithm.py
> +# :class:`~.Snapshot` to see how the states change on each step. Let us check the probability of finding
```suggestion
# :class:`~.pennylane.Snapshot` to see how the states change on each step. Let us check the probability of finding
```

2023-05-11 20:04 UTC, KetpuntoG commented on demonstrations/tutorial_grovers_algorithm.py
> +# .. math:: U_\omega = \mathbb{I} - \vert \omega \rangle \langle \omega \vert.
```suggestion
#
# .. math:: U_\omega = \mathbb{I} - 2\vert \omega \rangle \langle \omega \vert.
```

I would say you forgot a 2

2023-05-11 20:04 UTC, KetpuntoG commented on demonstrations/tutorial_grovers_algorithm.py
> +# which is easily implemented using :class:`~.GroverOperator`.
```suggestion
# which is easily implemented using :class:`~.pennylane.GroverOperator`.
```

2023-05-11 20:06 UTC, KetpuntoG commented on demonstrations/tutorial_grovers_algorithm.py
> +#    U_D = | s \rangle\langle s| - \mathbb{I}.
```suggestion
#    U_D = 2| s \rangle\langle s| - \mathbb{I}.
```
doublecheck it just in case

2023-05-11 20:09 UTC, KetpuntoG commented on demonstrations/tutorial_grovers_algorithm.py
> +# verify in the circuit below that applying the *Grover iterator* :math:`U_\omega U_D` once is enough
```suggestion
# verify in the circuit below that applying the *Grover iterator* :math:`U_D U_\omega` once is enough
```
doublecheck it just in case

2023-05-11 20:09 UTC, KetpuntoG commented on demonstrations/tutorial_grovers_algorithm.py
> +# is given by :math:`r \approx \lceil \frac{\pi}{4} \sqrt{\frac{N}{M}} \rceil`\ [#NandC2000]_.
```suggestion
# is given by :math:`r \approx \left \lceil \frac{\pi}{4} \sqrt{\frac{N}{M}} \right \rceil`\ [#NandC2000]_.
```

2023-05-11 20:11 UTC, KetpuntoG commented on demonstrations/tutorial_grovers_algorithm.py
> +# verify in the circuit below that applying the *Grover iterator* :math:`U_\omega U_D` once is enough
```suggestion
# verify in the circuit below that applying the *Grover iterator* :math:`U_D U_\omega` once is enough
```
doublecheck it just in case

2023-07-01 00:31 UTC, KetpuntoG commented on demonstrations/tutorial_grovers_algorithm.py
> +# Wrapping up
```suggestion
# Conclusion
```

2023-07-01 02:00 UTC, KetpuntoG approved these changes
Nice tutorial!

2023-07-01 02:00 UTC, merged