Intro to QSVT tutorial
PennyLaneAI/qml pull request #787
Opened 2023-05-08 15:33 UTC by ixfoduap

------------------------------------------------------------------------------------------------------------

**Title:** Intro to QSVT

**Summary:** 
Short-and-sweet tutorial covering the basics of QSVT. Tailored for people that are curious about QSVT but have not studied it much

2023-05-09 13:48 UTC, ixfoduap commented on demonstrations/tutorial_intro_qsvt.py
> +# In PennyLane, implementing the QSVT transformation is as simple as using :class:`~pennylane.qsvt`. Let's revisit
This link is not working for me. Does anyone know how to fix it?

2023-05-09 13:52 UTC, ixfoduap commented on demonstrations/tutorial_intro_qsvt.py
> +As you will soon learn, QSP can be viewed as a special case of QSVT. We thus use the :class:`~pennylane.qsvt`.
This link not working. Anyone know how to fix?

2023-05-09 16:58 UTC, Jaybsoni reviewed
Looks good so far! Left a quick review, will add more comments this evening!

2023-05-09 17:18 UTC, ixfoduap commented on demonstrations/tutorial_intro_qsvt.py
> +There are multiple choices for the "other unitary", for example
I see what you mean about emphasis, but I am not a fan of italics here

2023-05-09 17:20 UTC, ixfoduap commented on demonstrations/tutorial_intro_qsvt.py
> +applicability.
I concluded that the emoji was not helping, so I removed and change some punctuation

2023-05-09 17:20 UTC, ixfoduap commented on demonstrations/tutorial_intro_qsvt.py
> +# ----------
I haven't checked the references. Reviewers please take a close look!

2023-05-09 19:40 UTC, Jaybsoni commented on demonstrations/tutorial_intro_qsvt.py
> +methods is an active area of research.
```suggestion
The main quantum signal processing theorem states that there exist a sequence of :math:`d+1` angles
that can implement *any* complex polynomial of degree :math:`d`.
Finding the desired angles can be done efficiently in practice, but identifying the best
methods is an active area of research.
```

2023-05-09 19:45 UTC, Jaybsoni commented on demonstrations/tutorial_intro_qsvt.py
> +    return out[0, 0]  # top-left entry
Just a suggestion to keep things more compact: 

```suggestion
def qsvt_output(a):
    # output matrix
    out = qml.matrix(qml.qsvt(a, angles, wires=[0]))
    return out[0, 0]  # top-left entry
```

2023-05-09 20:47 UTC, Jaybsoni reviewed
Fixing links

2023-05-09 20:47 UTC, Jaybsoni commented on demonstrations/tutorial_intro_qsvt.py
> +As you will soon learn, QSP can be viewed as a special case of QSVT. We thus use the :class:`~pennylane.qsvt`
```suggestion
As you will soon learn, QSP can be viewed as a special case of QSVT. We thus use the :func:`~.pennylane.qsvt`
```

2023-05-09 20:47 UTC, Jaybsoni commented on demonstrations/tutorial_intro_qsvt.py
> +# the `:class:`~pennylane.BlockEncode` operation that follows construction above. Let's test
```suggestion
# the :class:`~pennylane.BlockEncode` operation that follows construction above. Let's test
```

2023-05-09 20:47 UTC, Jaybsoni commented on demonstrations/tutorial_intro_qsvt.py
> +# In PennyLane, implementing the QSVT transformation is as simple as using :class:`~pennylane.qsvt`. Let's revisit
```suggestion
# In PennyLane, implementing the QSVT transformation is as simple as using :func:`~.pennylane.qsvt`. Let's revisit
```

2023-05-09 20:47 UTC, Jaybsoni commented on demonstrations/tutorial_intro_qsvt.py
> +# ..[#unification]
```suggestion
# .. [#unification]
```

2023-05-09 21:25 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qsvt.py
> +# In PennyLane, implementing the QSVT transformation is as simple as using :class:`~pennylane.qsvt`. Let's revisit
I would say that `qml.qsvt` is a function and the class is `qml.QSVT`
If you want to add the function try `:func:` instead

2023-05-10 14:31 UTC, Jaybsoni commented on demonstrations/tutorial_intro_qsvt.py
> +print("U(A) = ", np.round(qml.matrix(U1), 2))
I think the best option is to add a new line and print the matrix under the label:

```
U(A): 
[[..., ..., ..., ...],
 [..., ..., ..., ...],
 [..., ..., ..., ...],
 [..., ..., ..., ...]]
```

2023-05-10 14:44 UTC, Jaybsoni reviewed
Final polish work

2023-05-10 14:44 UTC, Jaybsoni commented on demonstrations/tutorial_intro_qsvt.py
> +#    \end{pmatrix}.
Equation is wrong: 

```suggestion
# .. math:: \left[\prod_{k=1}^{d/2}\Pi_{\phi_{2k-1}}U(A)^\dagger \tilde{\Pi}_{\phi_{2k}} U(A)\right]\Pi_{\phi_{d+1}}=
#    \begin{pmatrix} P(A) & *\\
#    * & *
#    \end{pmatrix}.
```

2023-05-10 14:44 UTC, Jaybsoni commented on demonstrations/tutorial_intro_qsvt.py
> +# states that
I think its more clear this way, and makes the formula below easier to digest.
```suggestion
# Mathematically, when the polynomial degree :math:`d` is even (number of angles is :math:`d + 1`), the QSVT result
# states that
```

2023-05-10 14:44 UTC, Jaybsoni commented on demonstrations/tutorial_intro_qsvt.py
> +#    \end{pmatrix}.
Equation was wrong: 

```suggestion
# .. math:: \tilde{\Pi}_{\phi_1}\left[\prod_{k=1}^{(d-1)/2}\Pi_{\phi_{2k}}U(A)^\dagger \tilde{\Pi}_{\phi_{2k+1}} U(A)\right]\Pi_{\phi_{d+1}}=
#    \begin{pmatrix}
#    P(A) & *\\
#    * & *
#    \end{pmatrix}.
```

2023-05-10 14:44 UTC, Jaybsoni commented on demonstrations/tutorial_intro_qsvt.py
> +print("U(A) = ", np.round(qml.matrix(U1), 2))
Fix alignment

```suggestion
print("U(A):")
print(np.round(qml.matrix(U1), 2))
```

2023-05-10 14:44 UTC, Jaybsoni commented on demonstrations/tutorial_intro_qsvt.py
> +print("U(B) = ", np.round(qml.matrix(U2), 2))
Fix alignment
```suggestion
print("U(B):")
print(np.round(qml.matrix(U2), 2))
```

2023-05-10 14:44 UTC, Jaybsoni commented on demonstrations/tutorial_intro_qsvt.py
> +print("Pi = ", np.round(qml.matrix(pi), 2))
Fix alignment
```suggestion
print("Pi:")
print(np.round(qml.matrix(pi), 2))
```

2023-05-10 16:09 UTC, Jaybsoni commented on demonstrations/tutorial_intro_qsvt.py
> +# One of my favourite uses of QSVT is to transform a molecular Hamiltonian by a polynomial approximation of a step function [#lintong].
```suggestion
# One of my favourite uses of QSVT is to transform a molecular Hamiltonian by a polynomial approximation of a step function [#lintong]_.
```

2023-05-10 16:16 UTC, Jaybsoni approved these changes
Update: links fixed, polished up the equations, typos and alignment of the print statements. The only remaining task is to update the "posted" date at the beginning of the demo. 

Overall, I think the demo looks great 💯! Ready to merge from my end!

One comment I would like to add (this is not blocking), the demo feels a little bit incomplete to me. We claim that this demo will teach you the "core principal" of QSVT, but then we have one paragraph where we simply state 'qsp: multiply matrices => polynomials'. 

The rest of the demo does a great job of showing how QSVT is a natural generalization of QSP, and how we can recover the same polynomial transformations. Overall, it feels like we are saying "QSVT reduces to QSP", but I think we can do more to make the QSP result feel natural / intuitive rather than just asking the user to trust in the theorem via one example. 

If we have time, I would recommend adding another paragraph near the beginning, trying to naturally arrive at the result of QSP. I think it's as simple as showing that if you repeatedly apply `W(a)` by itself, you will get polynomials anyways.

2023-05-10 17:45 UTC, josh146 commented
Note that, before merging: we are making some changes to the demo process, that includes creating a new metadata file to include information about the demo, alongside other process changes :) @KetpuntoG can walk you through the changes

2023-05-11 15:46 UTC, Danimhn commented on demonstrations/tutorial_intro_qsvt.py
> +that can implement *any* complex polynomial of degree :math:`d`.
This isn't true, in the original QSP/QSVT framework, for an arbitrary complex polynomial you would need 4 separate instances of QSP combined together using LCU (This isn't needed in the new formalism I developed tho ;) but the version introduced here would require 4d+4 for an arbitrary complex polynomial) The result you're thinking of might be the following: Any real polynomial of definite parity can be built, and then using this result we get that any complex polynomial can be built from 4 instances of QSP! (Technically we'd need 8 instances because the LCU would give us P(H)/4 so we'd need to do a single iteration of OAA to get P)

2023-05-11 15:46 UTC, Danimhn commented on demonstrations/tutorial_intro_qsvt.py
> +# :math:`d` can be implemented by the QSVT sequence. In fact, as long as we're careful with conventions,
Same comment as above

2023-05-11 15:46 UTC, Danimhn commented on demonstrations/tutorial_intro_qsvt.py
> +
If you wanted to fill in *, you could do it with the following:

\begin{pmatrix}
    P(a) & iQ(a)\sqrt{1-a^2}\\
    iQ*(a)\sqrt{1-a^2} & P*(a)
    \end{pmatrix}

2023-05-11 17:57 UTC, KetpuntoG reviewed
Very good tutorial!!! 🚀Here are a few final suggestions :)

2023-05-11 17:57 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qsvt.py
> +Author: Juan Miguel Arrazola — Posted: May 23, 2023.
```suggestion
*Author: Juan Miguel Arrazola — Posted: May 23, 2023.*
```

2023-05-11 17:57 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qsvt.py
> +
You could include as `.. related::` demo the QSP one
Even if it appears linked in text, this is very useful for us :)

2023-05-11 17:57 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qsvt.py
> +# and define associated :math:`\text{PREP}` (prepare) and :math:`\text{SEL}` (select) operators.
```suggestion
# and define associated :math:`\text{PREPARE}` and :math:`\text{SELECT}` operators.
```

In Oriel's tutorial on LCU they are called directly PREPARE and SELECT, I suggest the change to maintain consistency when publishing

2023-05-11 17:57 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qsvt.py
> +pi = qml.PCPhase(phi, dim, wires=range(2))
I think the name is a bit misleading, it could be better "projector"

2023-05-11 17:57 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qsvt.py
> +# .. math:: P(A) = \sum_k P(\sigma_k)|w_k\rangle \langle v_k|,
I'm not sure so I'm asking just in case. Is it correct w and v? or would it be two w?

2023-05-11 17:57 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qsvt.py
> +plt.show()
It is worthwhile to put the axes of this plot

2023-05-11 17:57 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qsvt.py
> +# Quantum signal procesing is a result about multiplication of 2x2 matrices, yet it is the core principle
```suggestion
# Quantum signal processing is a result about multiplication of 2x2 matrices, yet it is the core principle
```

2023-05-11 17:57 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qsvt.py
> +# the :class:`~pennylane.BlockEncode` operation that follows construction above. Let's test
```suggestion
# the :class:`~pennylane.BlockEncode` operation that follows the construction above. Let's test
```

2023-05-11 17:57 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qsvt.py
> +# and the phase :math:`e^{-i \phi}` everywhere else. For example, revisting the square matrix :math:`A` in
not sure about the "revisting" word

2023-05-11 17:57 UTC, KetpuntoG commented on demos_quantum-computing.rst
> +.. gallery-item::
For some reason it is placed second to last?

2023-05-11 17:57 UTC, KetpuntoG commented on git
You can remove this file

2023-05-12 00:51 UTC, Danimhn commented on demonstrations/tutorial_intro_qsvt.py
> +that can implement *any* complex polynomial of degree :math:`d`.
Yes but you only need access to e^{iH} and don't need a block encoding

2023-05-12 20:13 UTC, DSGuala requested changes
Excellent demo! Left a lot of comments about wording (which depend on preference/interpretation) and a few comments about typos.

2023-05-12 20:13 UTC, DSGuala commented on demonstrations/tutorial_intro_qsvt.py
> +# :math:`S(\phi)`. This can be done by using a diagonal unitary where we apply the phase
> For this to be possible, we need to generalize the signal-processing operator

I think it would be useful to express that we are generalizing it to larger than 2x2. The reader needs to know that QSP won't work because it's limited to 2x2 (as you mentioned earlier) and now we want to expand to nxn.

2023-05-12 20:13 UTC, DSGuala commented on demonstrations/tutorial_intro_qsvt.py
> +# We look forward to seeing the innovations that will result from your journey.
Very inspirational :clap:

2023-05-12 20:13 UTC, DSGuala requested changes
Excellent demo! Left a lot of comments about wording (which depend on preference/interpretation) and a few comments about typos.

2023-05-17 15:37 UTC, KetpuntoG commented on demonstrations/tutorial_intro_qsvt.py
> +find :math`d+1` angles that implement any real polynomial of parity :math:`d \mod 2` and maximum degree :math:`d`.
```suggestion
find :math:`d+1` angles that implement any real polynomial of parity :math:`d \mod 2` and maximum degree :math:`d`.
```

2023-05-17 19:18 UTC, DSGuala approved these changes
Two typos and then approved :+1:

2023-05-17 19:18 UTC, DSGuala commented on demonstrations/tutorial_intro_qsvt.py
> +theorem can then be extended to show that using additional rotations, it is posisble to
```suggestion
theorem can then be extended to show that using additional rotations, it is possible to
```

2023-05-17 19:18 UTC, DSGuala commented on demonstrations/tutorial_intro_qsvt.py
> +# These are known as a **projector-controlled phase gates**, for which we use the symbol :math:`\Pi(\phi)`.
```suggestion
# These are known as **projector-controlled phase gates**, for which we use the symbol :math:`\Pi(\phi)`.
```

2023-05-18 20:21 UTC, ixfoduap commented on demonstrations/tutorial_intro_qsvt.py
> +The answer to our crucial question is encapsulated in a method known as **quantum signal processing** (QSP).
```suggestion
The answer to our question is encapsulated in a method known as **quantum signal processing** (QSP).
```

2023-05-18 20:47 UTC, ixfoduap commented on demonstrations/tutorial_intro_qsvt.py
> +and its coefficients depend on the choice of angles.
```suggestion
```

2023-05-18 20:47 UTC, ixfoduap commented on demonstrations/tutorial_intro_qsvt.py
> +theorem can then be extended to show that using additional rotations, it is possible to
```suggestion
parity determined by the number of angles [#unification]_. 

The results of the
theorem can then be extended to show that using additional rotations, it is possible to
```

2023-05-18 20:47 UTC, ixfoduap commented on demonstrations/tutorial_intro_qsvt.py
> +# it out with an example:
```suggestion
# it out with an example encoding first a square matrix:
```

2023-05-18 20:47 UTC, ixfoduap commented on demonstrations/tutorial_intro_qsvt.py
> +# rectangular matrix
```suggestion
# And also a rectangular matrix
```

2023-05-18 20:47 UTC, ixfoduap commented on demonstrations/tutorial_intro_qsvt.py
> +# Mathematically, when the polynomial degree :math:`d` is even (number of angles is :math:`d + 1`), the QSVT result
```suggestion
# Mathematically, when the polynomial degree :math:`d` is even (number of angles is :math:`d + 1`), the QSVT algorithm
```

2023-05-18 20:47 UTC, ixfoduap commented on demonstrations/tutorial_intro_qsvt.py
> +# The :func:`~pennylane.qsvt` operation is tailored for use in simulators and uses standard forms for block encodings
```suggestion
# The :func:`~pennylane.qsvt` operation is tailored for use in simulators and employs standard forms for block encodings
```

2023-05-18 21:53 UTC, merged