A user-friendly guide for making the demonstrations metadata files
PennyLaneAI/qml pull request #799
Opened 2023-05-17 17:25 UTC by BM7878

We already have a more technical description of the metadata files - this markdown file is just an explanation of what they are for people who are writing a demo and need to create a metadata file for it.

2023-05-17 21:19 UTC, josh146 commented on demonstrations_metadata_guide.md
> +Each demonstration has an associated metadata file. This file is a JSON file; it has the same name, but a different ending - always `.metadata.json`.
Might be good to mention the file location as well

2023-05-18 01:03 UTC, josh146 requested changes
Thanks Ben! Just a couple of minor comments

2023-05-18 01:03 UTC, josh146 commented on demonstrations_metadata_guide.md
> +This file contains information that needs to be picked up by other systems and services. This is information like the title of the demonstration, the categories it's in, and the description and thumb
Nice, definitely a good idea to motivate _why_ this is needed!

2023-05-18 01:03 UTC, josh146 commented on demonstrations_metadata_guide.md
> +* The `previewImages` field is a list of images used in search results and other listings for the demonstration. One must be the default thumbnail to use, and must have the type `thumbnail`. Another
Do we need to document where these image files should live in terms of the repo structure?

2023-05-22 14:45 UTC, ikurecic reviewed
Looks good (added just one suggestion, thanks ☺), but I'm struggling to follow the naming conventions at some points. Could you maybe add an example and follow it? Even just inserting a name instead of naming extensions would make it easier to orient yourself.

2023-05-22 14:45 UTC, ikurecic commented on demonstrations_metadata_guide.md
> +This file contains information that needs to be picked up by other systems and services. This is information like the title of the demonstration, the categories it's in, and the description and thumb
```suggestion
This file contains information that needs to be picked up by other systems and services. This is information like the title of the demonstration, the categories it's in, and the description and thumbnail image. By placing this information in a JSON file, it's easier for other systems — such as (and primarily) the pennylane.ai React website — to know what demonstrations exist, where they should be placed on the site, and how they are connected. You can think of the metadata file as 'registering' the demonstration with the system.
```
😉

2023-05-22 14:45 UTC, ikurecic commented on demonstrations_metadata_guide.md
> +* The `categories` field is a list of strings. These strings will determine which categories the demonstration shows up in on the live site. The category string must exactly match that given for the
Are we limiting one demo to one category? If so, might also mention it here.

2023-05-22 14:45 UTC, ikurecic commented on demonstrations_metadata_guide.md
> +This file contains information that needs to be picked up by other systems and services. This is information like the title of the demonstration, the categories it's in, and the description and thumb
I would also think about adding a piece of tantalizing info there, stress that adding these data will allow more people to find their demo in the vast depths of the internet (or the pennylane.ai website).

2023-05-22 14:45 UTC, ikurecic commented on demonstrations_metadata_guide.md
> +* The `canonicalURL` field must be `/qml/demos/` + the file name of the demo without the `.py` ending.
By this point in the file I'm starting to feel like there's a lof of opportunity for a lapsus. Would it be better to have a fixed example to refer to?

2023-05-22 18:23 UTC, josh146 commented on demonstrations_metadata_guide.md
> +* The `canonicalURL` field must be `/qml/demos/` + the file name of the demo without the `.py` ending.
Never heard the word lapsus before!

2023-05-25 13:16 UTC, BM7878 commented on demonstrations_metadata_guide.md
> +Each demonstration has an associated metadata file. This file is a JSON file; it has the same name, but a different ending - always `.metadata.json`.
Added.

2023-06-08 14:43 UTC, BM7878 commented on demonstrations_metadata_guide.md
> +* The `categories` field is a list of strings. These strings will determine which categories the demonstration shows up in on the live site. The category string must exactly match that given for the
Multiple categories are now allowed.

2023-06-08 14:44 UTC, BM7878 commented on demonstrations_metadata_guide.md
> +This file contains information that needs to be picked up by other systems and services. This is information like the title of the demonstration, the categories it's in, and the description and thumb
Good idea - will do.

2023-06-08 14:48 UTC, BM7878 commented on demonstrations_metadata_guide.md
> +* The `previewImages` field is a list of images used in search results and other listings for the demonstration. One must be the default thumbnail to use, and must have the type `thumbnail`. Another
Added

2024-07-18 19:26 UTC, closed without merging