Teleportation tutorial
PennyLaneAI/qml pull request #812
Opened 2023-05-31 21:57 UTC by timmysilv

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Remember to do a grammar check of the content you include.
- [ ] All tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2023-07-04 18:48 UTC, timmysilv commented on demonstrations/tutorial_teleportation.py
> +.. figure:: ../demonstrations/teleportation/teleportation-4part.svg
this should probably be a cooler image 😄

2023-07-06 15:16 UTC, ludmilaasb commented on demonstrations/tutorial_teleportation.py
> +    \tag{1}\end{align*}
```suggestion
    \end{align*}
```

2023-07-06 15:20 UTC, ludmilaasb commented on demonstrations/tutorial_teleportation.py
> +    \tag{1}\end{align*}
I didn't find any reference to this equation through the text

2023-07-06 15:42 UTC, ludmilaasb commented on demonstrations/tutorial_teleportation.py
> +We will now prove that no such :math:`U` exists! First, note that the inner product
```suggestion
We will now prove that no such :math:`U` exists! First, let's take the inner product
```

2023-07-06 15:53 UTC, ludmilaasb commented on demonstrations/tutorial_teleportation.py
> +teleported, and not a physical particle.
This is fine but it could be more naturally integrated to the text with a briefly description of the protocol. See above.

2023-07-06 18:49 UTC, timmysilv commented on demonstrations/tutorial_teleportation.py
> +    \tag{1}\end{align*}
Good point - I originally just kept the tags from the codebook page. In my recent commit, I removed all tags that aren't referenced later (and re-indexed the remaining ones accordingly)

2023-07-06 18:50 UTC, timmysilv commented on demonstrations/tutorial_teleportation.py
> +product is 0, the states are orthogonal. Therefore, we can't clone arbitrary states!
I kinda like how it's done in the tutorial itself, since the math is pretty straightforward/quick and the reader can follow along without having to leave our page, and hopefully learn something new! if they already know it, they'll probably just skip this part anyway 😄

2023-07-06 18:53 UTC, ludmilaasb requested changes
Hello! 

Thanks for preparing this very nice demo!

The pace is good, also the content. I suggested some minor changes to make the text more fluid. 

Good job!

2023-07-06 19:08 UTC, timmysilv commented on demonstrations/tutorial_teleportation.py
> +"""
I think I'd wanna re-draw the whole picture with trendy PennyLane graphics style, then at the top of each sub-section, re-post the picture but only highlighting the component being discussed. I can take a crack at it but I am not much of an illustrator...

2023-07-06 19:30 UTC, timmysilv commented on demonstrations/tutorial_teleportation.py
> +# basis, so shouldn't we be good to go? Not quite, but almost!
totally agreed, and I actually had a hard time with this, because I wanted to explain only traditional stuff first too. I ended up writing it in this way to match the 4-part diagram (which has CZ and CNOT), but I'm only now realizing that we could just change that diagram to show classical measurements!

2023-07-06 21:05 UTC, timmysilv commented on demonstrations/tutorial_teleportation.py
> +_ = qml.draw_mpl(teleport, style="sketch")(state)
do you mean how it went from the classical double-wires to the regular CNOT gate? if so - that was the intention:) perhaps I can make it clearer that it's what I'm trying to demonstrate? (if a QNode binds a quantum function to a device that does not support mid-circuit measurements, it applies the deferred measurement principle)

2023-07-06 21:07 UTC, timmysilv commented on demonstrations/tutorial_teleportation.py
> +#     \vert 0\rangle_A \vert 0\rangle_a \vert 0\rangle_B.\tag{2}
I mention it before the basis-change math (`Expanding out the terms from (1) (and removing the subscripts for brevity)`), but I'll make it more obvious.

2023-07-06 21:25 UTC, timmysilv commented on demonstrations/tutorial_teleportation.py
> +# etc. Let's perform this change of basis, one step at a time.
I think it's better here actually - it's not related to wire $B$ being in the desired $\vert \psi\rangle$ state, but rather it's just generally describing a change of basis. I think moving it down might confuse the reader

2023-07-07 14:52 UTC, timmysilv commented on demonstrations/tutorial_teleportation.py
> +_ = qml.draw_mpl(teleport, style="sketch")(state)
oh my, slipped right by me! the `defer_measurements` function must be making something like `qml.ctrl(qml.PauliX)`, which _should_ get turned into a `CNOT` but doesn't. This is a bug imo:
```python
def c():
    m0 = qml.measure(0)
    qml.cond(m0, qml.PauliX)(1)

mid_circuit = qml.tape.make_qscript(c)()
deferred = qml.defer_measurements(mid_circuit)
print(deferred.operations)
# [Controlled(PauliX(wires=[1]), control_wires=[0])]
```

we should register `qml.ctrl` to make `CNOT` gates when possible

2023-07-07 20:25 UTC, timmysilv commented on demonstrations/tutorial_teleportation.py
> +_ = qml.draw_mpl(teleport, style="sketch")(state)
opened PennyLaneAI/pennylane#4339

2023-07-17 13:01 UTC, ikurecic commented on demonstrations/tutorial_teleportation.py
> +#     \end{align*}
This part should be within step 2.

2023-07-17 13:01 UTC, ikurecic commented on demonstrations/tutorial_teleportation.py
> +# Now let's apply a :math:`CNOT` between Alice's two qubits:
```suggestion
# Now let's apply a CNOT between Alice's two qubits:
```

2023-07-17 13:03 UTC, ikurecic commented on demonstrations/tutorial_teleportation.py
> +# teleportation <https://quantum.country/teleportation>`__ [#Teleportation1993]_,
```suggestion
# quantum teleportation <https://quantum.country/teleportation>`__ [#Teleportation1993]_,
```

2023-07-17 13:11 UTC, ikurecic commented on demonstrations/tutorial_teleportation.py
> +_ = qml.draw_mpl(teleport, style="sketch")(state)
Yeah, whoops. 😅

2023-07-17 13:17 UTC, ikurecic commented on demonstrations/tutorial_teleportation.py
> +# gates. This is exactly what the principle of deferred measurement gives us -
```suggestion
# gates. This is exactly what the principle of deferred measurement gives us —
```

2023-07-17 13:19 UTC, ikurecic commented on demonstrations/tutorial_teleportation.py
> +# Conclusion
Can you only use *emph* here? Or make (some of) the emphasized segments in the rest of the file **bold**? There's a lot here, feels a bit harsh.

2023-07-17 14:25 UTC, timmysilv commented on demonstrations/tutorial_teleportation.metadata.json
> +        }
the codebook homepage says "please cite us like this", but I'm happy to cite the particular node (I.15) if it makes sense

2023-07-17 14:25 UTC, timmysilv commented on demonstrations/tutorial_teleportation.py
> +    tutorial_mbqc Measurement-based quantum computation
sorry, I should have deleted all this metadata at the top with the new way of doing things

2023-07-17 14:25 UTC, timmysilv commented on demonstrations/tutorial_teleportation.py
> +*Author: Matthew Silverman - Posted: 1 June 2023. Last Updated 1 June 2023.*
just removing the whole thing 😄

2023-07-17 14:28 UTC, timmysilv commented on demonstrations/tutorial_teleportation.py
> +2. Entanglement - A pair of entangled qubits is created and distributed to
I'll mention a Bell state since it fits the rest of the language, and we'll be teaching them what it is shortly

2023-07-17 14:30 UTC, timmysilv commented on demonstrations/tutorial_teleportation.py
> +would like to design a circuit (unitary) :math:`U` that can perform the following
I took this from the codebook and kinda liked it as it is, which is to say we are conceptually designing a circuit, but mathematically just constructing a unitary transformation. Perhaps I could say "design a circuit (unitary transformation)"?

2023-07-17 14:35 UTC, timmysilv commented on demonstrations/tutorial_teleportation.py
> +# .. figure:: ../demonstrations/teleportation/teleportation-4part.svg
the images are placeholders for now, @ludmilaasb is helping me out and making better, more informative ones

2023-07-17 14:42 UTC, timmysilv commented on demonstrations/tutorial_teleportation.py
> +# Bell state. If we run them in the opposite direction, we transform the basis
I'll add a detail to step 2 introducing Bell states by name

2023-07-17 14:44 UTC, timmysilv commented on demonstrations/tutorial_teleportation.py
> +# Conclusion
for sure, I'll switch it over

2023-07-17 14:47 UTC, timmysilv commented on demonstrations/tutorial_teleportation.py
> +_ = qml.draw_mpl(teleport, style="sketch")(state)
it's fixed in the latest pennylane, I'll change this to be against `dev` : )

2023-07-18 09:26 UTC, ikurecic commented on demonstrations/tutorial_teleportation.py
> +    tutorial_mbqc Measurement-based quantum computation
Yeah, you're right. I'm not entirely sure where that process is at the moment, so proceed as you were. 😁

2023-07-18 09:27 UTC, ikurecic commented on demonstrations/tutorial_teleportation.py
> +would like to design a circuit (unitary) :math:`U` that can perform the following
Hmm. I thought you were just saying "unitary circuit," as some people do. 🤔 I'd add the word, yeah.

2023-07-19 14:32 UTC, ludmilaasb commented on demonstrations/tutorial_teleportation.py
> +.. figure:: ../demonstrations/teleportation/teleportation-4part.svg
Something like this? 

![teleport_circuit_full_circuit](https://github.com/PennyLaneAI/qml/assets/39570941/231eacb6-b95b-4926-b438-eded00bdb366)

2023-07-19 19:14 UTC, timmysilv commented on demonstrations/tutorial_teleportation.py
> +.. figure:: ../demonstrations/teleportation/teleportation-4part.svg
looks awesome! I was thinking that in the intro, we should just have the component titles ("State prep", "Shared entanglement", etc.) then build up to this complete image at the end. thoughts?

2023-07-19 20:32 UTC, timmysilv commented on demonstrations/tutorial_teleportation.py
> +_ = qml.draw_mpl(teleport, style="sketch")(state)
ok it wasn't enough so I also created PennyLaneAI/pennylane#4370 and this time I confirmed locally that it does what I want : )

2023-07-24 13:59 UTC, ludmilaasb commented on demonstrations/tutorial_teleportation.py
> +.. figure:: ../demonstrations/teleportation/teleportation-4part.svg
![teleport_circuit_full_text](https://github.com/PennyLaneAI/qml/assets/39570941/359fd6df-5566-469e-818b-6008e3c107d7)

2023-07-24 14:01 UTC, ludmilaasb commented on demonstrations/tutorial_teleportation.py
> +.. figure:: ../demonstrations/teleportation/teleportation-4part.svg
![teleport_circuit_full_text](https://github.com/PennyLaneAI/qml/assets/39570941/51191bcc-905f-4f6f-9bce-ca1d72a20de0)

2023-08-01 18:25 UTC, timmysilv commented
update for reviewers: I did a full CI build because something seemed cached, and I've confirmed the Controlled-X/Z become proper CNOT and CZ ops respectively! All the images are updated (ty @ludmilaasb!!), and I snuck the full circuit drawing into the conclusion to summarize it all

2023-10-19 17:20 UTC, KetpuntoG reviewed
Nice! 😊
A small change and it will be ready to merge

2023-10-19 17:20 UTC, KetpuntoG commented on demonstrations/tutorial_teleportation.metadata.json
> +    "dateOfLastModification": "2023-09-01T00:00:00+00:00",
```suggestion
    "dateOfPublication": "2023-10-20T00:00:00+00:00",
    "dateOfLastModification": "2023-10-20T00:00:00+00:00",
```

2023-10-19 17:20 UTC, KetpuntoG commented on demonstrations/tutorial_teleportation.py
> +# likewise for the (C)Z gate. This is incredibly useful, as it allows us to
```suggestion
# likewise for the CZ gate. This is incredibly useful, as it allows us to
```

2023-10-19 17:20 UTC, KetpuntoG commented on demonstrations/tutorial_teleportation.py
> +# :func:`qml.density_matrix <pennylane.density_matrix>` will trace out and return
Visually it doesn't look too good to start with a lower case. Can you rephrase it so that an article or something appears before the sentence?

2023-10-19 18:20 UTC, timmysilv commented on demonstrations/tutorial_teleportation.py
> +# the specified subsystem, so we use this to verify the final state received by Bob.
```suggestion
# We can use :func:`qml.density_matrix <pennylane.density_matrix>` to trace out
# and return Bob's subsystem as a density matrix, which is a more general
# description of the state of his qubit. We will use this to verify that Alice's
# state was successfully teleported to Bob's qubit.
```

2023-10-19 20:41 UTC, KetpuntoG approved these changes
🚀 Awesome work!

2023-10-19 22:16 UTC, larawatson approved these changes

2023-10-19 23:19 UTC, merged