[wip] add fermionic operators demo
PennyLaneAI/qml pull request #813
Opened 2023-06-01 21:12 UTC by soranjh

**Title:**
Fermionic Operators

**Summary:**
This demo shows how to use PennyLane's in-built functionalities to build fermionic operators, use them to construct Hamiltonians, and map them to the qubit basis.

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2023-06-01 21:13 UTC, soranjh commented on demonstrations/fermionic_operators/creation.jpg
placeholder thumbnail

2023-06-06 17:24 UTC, soranjh commented on demonstrations/tutorial_fermionic_operators.py
> +operators to this state remove the electrons and gives back the original state.
These lines can be eliminated if they sound obvious for a "how to" type of demo.

2023-06-06 17:25 UTC, soranjh commented on demonstrations/tutorial_fermionic_operators.py
> +# Mapping to Pauli operators
This section has more of educational nature than "how to" nature, therefore can be eliminated. I think it will make a very good example for showcasing the Pauli arithmetic.

2023-06-07 20:47 UTC, ixfoduap requested changes

2023-06-07 20:47 UTC, ixfoduap commented on demonstrations/tutorial_fermionic_operators.py
> +# at some interesting examples.
```suggestion
# Now that we have these nice tools to create and manipulate fermionic Hamiltonians, we can look
# at some interesting examples.
```

2023-06-07 20:47 UTC, ixfoduap commented on demonstrations/tutorial_fermionic_operators.py
> +# `Hückel method <https://en.wikipedia.org/wiki/H%C3%BCckel_method>`_ which is a simple method for
```suggestion
# `Hückel method <https://en.wikipedia.org/wiki/H%C3%BCckel_method>`_ , which is a simple method for
```

2023-06-07 20:47 UTC, ixfoduap commented on demonstrations/tutorial_fermionic_operators.py
> +# Our toy model is a simplified version of the Hückel Hamiltonian and assumes only two orbitals and
Maybe you can skip the general form and jump straight to this? So just say our model is a toy version of the Huckel Hamiltonian with two orbitals and a single electron, then present the Hamiltonian

2023-06-07 20:47 UTC, ixfoduap commented on demonstrations/tutorial_fermionic_operators.py
> +# to have
```suggestion
# to get
```

2023-06-07 20:47 UTC, ixfoduap commented on demonstrations/tutorial_fermionic_operators.py
> +# The energy values of :math:`\alpha + \beta` and :math:`\alpha - \beta` correspond to the states
Maybe eigenvalues better than energy values?

2023-06-07 20:47 UTC, ixfoduap commented on demonstrations/tutorial_fermionic_operators.py
> +h = FermiSentence({FermiWord({}): coef[0]})  # initialize with the identity term
This line makes me realize that we should explain before how to use `FermiWord` and `FermiSentence` directly

2023-06-08 15:58 UTC, soranjh commented on demonstrations/tutorial_fermionic_operators.py
> +
> Maybe good to add a line to point to the fact that we are constructing the Hamiltonian by using fermionic arithmetic operations directly.

Added a line explaining that.

> I fear these lines may be a bit hard to follow. Perhaps we could separate them into two parts? First do the one-electron terms more explicitly, then do the two-electron compactly in this form?

They are separated now. I think we have had enough easy examples up to this point and this example is more like for advanced users.

2023-06-08 16:00 UTC, soranjh commented on demonstrations/tutorial_fermionic_operators.py
> +c0 = qml.FermiC(0)
Explained them. Initially had `cr` and `an` but the compact `c0` and `a1` symbols, and `c1` and `a0` later in the demo, are pretty compact and make the code look nicer.

2023-06-08 16:01 UTC, soranjh commented on demonstrations/tutorial_fermionic_operators.py
> +h = FermiSentence({FermiWord({}): coef[0]})  # initialize with the identity term
We don't need that line, so removed. We can just use `h = 0.0`.

2023-06-08 19:33 UTC, trbromley commented on demonstrations/tutorial_fermionic_operators.py
> +# *Fermi Sentence*.
```suggestion
# fermionic operators is called a *fermi word*, and a sum of Fermi words is called a
# *fermi sentence*.
```
No strong preference, just not sure if we need to use capitals.

2023-06-08 19:33 UTC, trbromley commented on demonstrations/tutorial_fermionic_operators.py
> +.. figure:: /demonstrations/fermionic_operators/creation.jpg
@KetpuntoG can help coordinate creating an illustration if needed.

2023-06-08 19:33 UTC, trbromley commented on demonstrations/tutorial_fermionic_operators.py
> +two_spin = two.repeat(2, axis=0).repeat(2, axis=1).repeat(2, axis=2).repeat(2, axis=3) * 0.5
Maybe it's clearer in the built demo, but what are we doing here?

2023-06-08 20:11 UTC, soranjh commented on demonstrations/tutorial_fermionic_operators.py
> +two_spin = two.repeat(2, axis=0).repeat(2, axis=1).repeat(2, axis=2).repeat(2, axis=3) * 0.5
I agree that this example is a bit technical, but I think we have enough simple examples before reaching this advanced one.

What we do here is to expand the matrix/tensor of integrals over **_molecular_** orbitals to the corresponding objects for **_spin-orbitals_**. The integrals computed by our restricted-HF workflow do not account for spin because they assume that spin-up and spin-down electrons in a molecular orbital have exactly the same spatial distribution. 

I have one line of explanation before these lines but my be we need more?

2023-06-08 20:12 UTC, soranjh commented on demonstrations/tutorial_fermionic_operators.py
> +.. figure:: /demonstrations/fermionic_operators/creation.jpg
We don't have any plans, help is definitely is welcome.

2023-06-15 19:34 UTC, isaacdevlugt commented on demonstrations/tutorial_fermionic_operators.metadata.json
> +{
Just commenting on the image:

@soranjh :godmode:

2023-06-15 19:37 UTC, soranjh commented on demonstrations/tutorial_fermionic_operators.metadata.json
> +{
It is a placeholder, a new different one will be added.

2023-06-16 21:06 UTC, isaacdevlugt requested changes
Great job Soran! Mostly small suggestions and comments.

2023-06-16 21:06 UTC, isaacdevlugt commented on demonstrations/tutorial_fermionic_operators.py
> +h = h.to_qubit()
Similar comment to one above (same as `qml.jordan_wigner(h)`?)

2023-06-16 21:06 UTC, isaacdevlugt commented on demonstrations/tutorial_fermionic_operators.py
> +# to get
```suggestion
# to get its eigenpairs:
```

2023-06-16 21:06 UTC, isaacdevlugt commented on demonstrations/tutorial_fermionic_operators.py
> +# the hydrogen molecule as an example. We first define the atom types and the atomic coordinates
```suggestion
# the hydrogen molecule as an example. We first define the atom types and the atomic coordinates:
```

2023-06-16 21:06 UTC, isaacdevlugt commented on demonstrations/tutorial_fermionic_operators.py
> +# different spins
```suggestion
# different spins:
```

2023-06-16 21:06 UTC, isaacdevlugt commented on demonstrations/tutorial_fermionic_operators.py
> +# added first
```suggestion
# added first:
```

2023-06-16 21:06 UTC, isaacdevlugt commented on demonstrations/tutorial_fermionic_operators.py
> +# We simplify the Hamiltonian to remove terms with negligible coefficients and then map it to the
```suggestion
# We then simplify the Hamiltonian to remove terms with negligible coefficients and then map it to the
```

2023-06-16 21:06 UTC, isaacdevlugt commented on demonstrations/tutorial_fermionic_operators.py
> +# qubit basis
```suggestion
# qubit basis:
```

2023-06-16 21:06 UTC, isaacdevlugt commented on demonstrations/tutorial_fermionic_operators.py
> +# We also need to account for the contribution of the nuclear energy
```suggestion
# We also need to account for the contribution of the nuclear energy:
```

2023-06-16 21:06 UTC, isaacdevlugt commented on demonstrations/tutorial_fermionic_operators.py
> +# in the computational basis.
Ah — just seeing that you used a period before code blocks and I've suggested colons everywhere 😅. I have no personal preference! Just needs to be consistent is all.

2023-06-16 21:06 UTC, isaacdevlugt commented on demonstrations/tutorial_fermionic_operators.py
> +# easy as writing the operators on paper. PennyLane supports several arithmetic operations between
```suggestion
# This demo explains how to create and manipulate fermionic operators in PennyLane, which is as
# easy as writing the operators on paper. PennyLane supports several arithmetic operations between

```

2023-06-16 21:06 UTC, isaacdevlugt commented on demonstrations/tutorial_fermionic_operators.py
> +# intuitive to construct complicated fermionic Hamiltonians such as molecular Hamiltonians.
Should we link to the documentation of `qml.fermi` in case people are interested in learning more about features that were/weren't mentioned?

2023-06-16 21:35 UTC, soranjh commented on demonstrations/tutorial_fermionic_operators.py
> +pauli_sentence = fermi_sentence.to_qubit()
We decided not to have `to_qubit` in the code base, updated the demo.

2023-06-16 21:35 UTC, soranjh commented on demonstrations/tutorial_fermionic_operators.py
> +h = h.to_qubit()
We decided not to have `to_qubit` in the code base, updated the demo.

2023-06-16 21:47 UTC, CatalinaAlbornoz reviewed
Great demo Soran! I haven't checked whether the metadata conforms to the latest standards but so far everything looks great!

It so happens that both Isaac and me were reviewing the demo at the same time so if you see conflicting comments please use your best judgement. Regarding the ' : ' and ' . ' comments just make sure to stick to the same always. I personally prefer ' . ' but either is fine.

2023-06-16 21:47 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_fermionic_operators.py
> +# This Fermi sentence can be mapped to the qubit basis using the Jordan-Wigner transformation to get
It's good to link Jordan-Wigner to Wikipedia or somewhere.

https://en.wikipedia.org/wiki/Jordan%E2%80%93Wigner_transformation

2023-06-16 21:47 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_fermionic_operators.py
> +# This Hamiltonian can be constructed with pre-defined values for :math:`\alpha` and :math:`\beta`
```suggestion
# This Hamiltonian can be constructed with pre-defined values for :math:`\alpha` and :math:`\beta`.
```

2023-06-16 21:47 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_fermionic_operators.py
> +# The second quantized molecular electronic Hamiltonian is usually constructed as
```suggestion
# The [second quantized](https://en.wikipedia.org/wiki/Second_quantization) molecular electronic Hamiltonian is usually constructed as
```

2023-06-16 21:47 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_fermionic_operators.py
> +# molecular orbitals that are obtained from Hartree-Fock calculations. These integrals can be
```suggestion
# molecular orbitals that are obtained from [Hartree-Fock calculations](https://pennylane.ai/qml/demos/tutorial_differentiable_HF#the-hartree-fock-method). These integrals can be
```

2023-06-16 21:47 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_fermionic_operators.py
> +# molecular orbitals that are obtained from Hartree-Fock calculations. These integrals can be
I'm not sure if linking the full url is the correct way to linking this demo or if we should use :doc:

2023-06-16 21:47 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_fermionic_operators.py
> +# the hydrogen molecule as an example. We first define the atom types and the atomic coordinates
I see that both Isaac an I are adding comments about adding a ' : ' or a ' . ' at the end of the phrases. I think either option should be fine as long as you stick to the same one throughout the demo.

2023-06-16 21:47 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_fermionic_operators.py
> +# The two-body terms can be added with
```suggestion
# The two-body terms can be added with:
```

2023-06-16 21:47 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_fermionic_operators.py
> +# also compute the ground-state energy by diagonalizing the matrix representation of the Hamiltonian
I would add a mention here about why we're using eigvals and SparseHamiltonian. Maybe saying that we're computing the ground-state energy by finding the minimum eigenvalue of the SparseHamiltonian, which is equivalent to diagonalizing the matrix representation of the Hamiltonian because ...

2023-06-16 21:47 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_fermionic_operators.py
> +# intuitive to construct complicated fermionic Hamiltonians such as molecular Hamiltonians.
This is a great place to mention our demo on molecular Hamiltonians https://pennylane.ai/qml/demos/tutorial_quantum_chemistry

2023-06-16 23:16 UTC, soranjh commented on demonstrations/tutorial_fermionic_operators.py
> +# also compute the ground-state energy by diagonalizing the matrix representation of the Hamiltonian
I replaced the current code with a direct diagonalization for consistency with what we have in the previous example and also to not further advertise `SparseHamiltonian` which will be deprecated.

2023-06-16 23:18 UTC, soranjh commented on demonstrations/tutorial_fermionic_operators.py
> +# in the computational basis.
I used period everywhere unless we have an uncompleted sentence, e.g., ending with _as_, which I did not use any symbol for simplicity. Can change to use `:` though.

2023-06-16 23:20 UTC, soranjh commented on demonstrations/tutorial_fermionic_operators.py
> +a qubit representation for use in quantum algorithms.
This is a bit challenging to do. This is not really a quantum chemistry demo.

2023-06-16 23:26 UTC, soranjh commented on demonstrations/tutorial_fermionic_operators.py
> +# Now that we have these nice tools to create and manipulate fermionic Hamiltonians, we can look
Slightly rephrased your suggestion.

2023-06-17 15:30 UTC, soranjh commented on demonstrations/tutorial_fermionic_operators.py
> +c0 = qml.FermiC(0)
Used `at1` and `a0` to denote `a^{\dagger}_1` and `a_0`.

2023-06-17 15:32 UTC, soranjh commented on demonstrations/tutorial_fermionic_operators.py
> +# intuitive to construct complicated fermionic Hamiltonians such as molecular Hamiltonians.
Added the demo on molecular Hamiltonians.

2023-06-17 15:33 UTC, soranjh commented on demonstrations/tutorial_fermionic_operators.py
> +# molecular orbitals that are obtained from Hartree-Fock calculations. These integrals can be
I used the url.

2023-06-19 15:21 UTC, isaacdevlugt approved these changes
LGTM!

2023-06-20 18:16 UTC, CatalinaAlbornoz reviewed
I've added a couple of comments.

The demo looks very good Soran!

2023-06-20 18:16 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_fermionic_operators.py
> +# added first.
```suggestion
# added first. We will use _itertools_ to efficiently create all of the combinations we need.
```

2023-06-20 18:16 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_fermionic_operators.py
> +# added first.
It would be useful to add a short note about the spin-forbidden terms. Or a link if this is too hard to explain in a few words.

2023-06-20 18:16 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_fermionic_operators.py
> +        h += one[i, j] * FermiC(i) * FermiA(j)
```suggestion
for p, q in itertools.product(range(n), repeat=2):
    if p % 2 == q % 2:  # to account for spin-forbidden terms
        h += one[p, q] * FermiC(p) * FermiA(q)
```

2023-06-20 18:16 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_fermionic_operators.py
> +# second quantized molecular Hamiltonian defined above.
```suggestion
# second quantized molecular Hamiltonian defined above. Here we also obtain the the core constant, which is later used to calculate the contribution of the nuclear energy to the Hamiltonian.
```

2023-06-20 19:11 UTC, soranjh commented on demonstrations/tutorial_fermionic_operators.py
> +# :math:`- \frac{1}{\sqrt{2}} \left ( |10 \rangle + |01 \rangle \right )`, respectively.
Thanks, corrected!

2023-06-20 19:12 UTC, soranjh commented on demonstrations/tutorial_fermionic_operators.py
> +# where :math:`\sigma` denotes the electron spin and the coefficients :math:`c` are integrals over
Thanks, corrected and defined other parameters.

2023-06-20 19:13 UTC, soranjh commented on demonstrations/tutorial_fermionic_operators.py
> +# These integrals are computed over molecular orbitals and we need to extend them to account for
Actually not all of them are computed this way.

2023-06-20 19:14 UTC, soranjh commented on demonstrations/tutorial_fermionic_operators.py
> +# different electron spins.
Please see my comment below.

2023-06-21 18:26 UTC, ixfoduap approved these changes
Just left a few suggestions, please address before merging

2023-06-21 18:26 UTC, ixfoduap commented on demonstrations/tutorial_fermionic_operators.py
> +algorithms.
```suggestion
and Hamiltonians, then map them to a qubit representation for use in quantum
algorithms.

```

2023-06-21 18:26 UTC, ixfoduap commented on demonstrations/tutorial_fermionic_operators.py
> +operators can be constructed in PennyLane similarly to Pauli operators using
```suggestion
operators can be constructed in PennyLane similarly to Pauli operators by using
```
otherwise it sounds like the Pauli operators use FermiC

2023-06-21 18:26 UTC, ixfoduap commented on demonstrations/tutorial_fermionic_operators.py
> +at0 = FermiC(0)
why the t? I find it a bit weird :thinking:

2023-06-21 18:26 UTC, ixfoduap commented on demonstrations/tutorial_fermionic_operators.py
> +# in the same way that you would write down the operator on a piece of paper.
```suggestion
# in the same way that you would write down the operator on a piece of paper:
```

2023-06-21 18:26 UTC, ixfoduap commented on demonstrations/tutorial_fermionic_operators.py
> +pauli_sentence = qml.jordan_wigner(fermi_sentence)
This is cool!

2023-06-21 18:26 UTC, ixfoduap commented on demonstrations/tutorial_fermionic_operators.py
> +# Fermi words and sentences can be thought of as fermionic Hamiltonians. Now that we have nice
This is not strictly true since not all Fermi words or sentences are Hermitian. You can say that when they are Hermitian they can be considered Hamiltonians, but maybe better to just delete the first sentence here

2023-06-21 20:44 UTC, CatalinaAlbornoz approved these changes
It's probably safe to set the publishing date to Tuesday. If something happens we can change the date later.

Great explanation about extending the integrals!

2023-06-21 20:44 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_fermionic_operators.py
> +*Author: Soran Jahangiri — Posted: 01 June 2023. Last updated: 01 June 2023.*
```suggestion
*Author: Soran Jahangiri — Posted: 27 June 2023. Last updated: 27 June 2023.*
```

2023-06-21 20:44 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_fermionic_operators.py
> +# `Hartree-Fock <https://pennylane.ai/qml/demos/tutorial_differentiable_HF#the-hartree-fock-method>`_
```suggestion
#  :doc:`Hartree-Fock </demos/tutorial_differentiable_HF>`
```

2023-06-21 20:44 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_fermionic_operators.py
> +# `molecular Hamiltonians <https://pennylane.ai/qml/demos/tutorial_quantum_chemistry>`_.
```suggestion
# :doc:`molecular Hamiltonians </demos/tutorial_quantum_chemistry>`.
```

2023-06-21 20:44 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_fermionic_operators.py
> +# integrals by duplicating terms to support both spin-up and spin-down electrons.
Great description Soran!!!

2023-06-21 20:45 UTC, CatalinaAlbornoz commented on demonstrations/tutorial_fermionic_operators.metadata.json
> +    "seoDescription": "Learn how to work with fermionic operators",
The suggestion for SEO description is to make it slightly longer and less generic than what you had before. Let me know if you agree with this description or if you prefer to change it.

2023-06-21 20:57 UTC, soranjh commented on demonstrations/tutorial_fermionic_operators.metadata.json
> +    "seoDescription": "Learn how to work with fermionic operators",
Slightly rephrased to make it even more general.

2023-06-21 21:01 UTC, CatalinaAlbornoz reviewed
Added the two thumbnails in the metadata

2023-06-23 17:24 UTC, merged