Optimal control for gate compilation
PennyLaneAI/qml pull request #827
Opened 2023-06-16 12:47 UTC by dwierichs

**Title:**
Optimal control for gate compilation

**Summary:**
This demo showcases the optimization of pulse programs to produce digital quantum gates.
To this end, a brief introduction to pulse programming and optimal control is given, followed by
the definition of a useful pulse shape and two exemplary optimizations to compile a `CNOT` and ` Toffoli`
gate, respectively.

**Relevant references:**
TBD

2023-06-23 15:46 UTC, Qottmann reviewed
This already looks very good @dwierichs ! Mostly left minor and very subjective comments that are free to be ignored 😇 

I like the conclusion that clarifies the limitations of these toy models. I think the demo could benefit from already making that disclaimer somewhere early / in the intro to set the expectations right.

2023-06-23 15:46 UTC, Qottmann commented on demonstrations/tutorial_optimal_control.py
> +evolution falls under the field of *quantum optimal control*.
A lot of convoluted Schachtelsätze, I think this could do with some grammatical simplifications. 100% subjective though 😇

2023-06-23 15:46 UTC, Qottmann commented on demonstrations/tutorial_optimal_control.py
> +programming with Rydberg atoms.
👌

2023-06-23 15:46 UTC, Qottmann commented on demonstrations/tutorial_optimal_control.py
> +system from the target gate.
not sure about "to measure" and "qubit system"
```suggestion
free parameters and define a cost function that quantifies the deviation of the qubit
operation from the target gate.
```

2023-06-23 15:46 UTC, Qottmann commented on demonstrations/tutorial_optimal_control.py
> +[Frobenius norm]
?

2023-06-23 15:46 UTC, Qottmann commented on demonstrations/tutorial_optimal_control.py
> +    :target: javascript:void(0);
lol! love it!

2023-06-23 15:46 UTC, Qottmann commented on demonstrations/tutorial_optimal_control.py
> +   can be changed at a bounded rate and in a smooth manner. :math:`R_\infty` is not
```suggestion
   In reality, the pulses describe some electromagnetic control field that can only
   be changed at a bounded rate and in a smooth manner. :math:`R_\infty` is not
```

2023-06-23 15:46 UTC, Qottmann commented on demonstrations/tutorial_optimal_control.py
> +    return 2 * sigmoid(t, k) - 1.0
move to the section where it is used later

2023-06-23 15:46 UTC, Qottmann commented on demonstrations/tutorial_optimal_control.py
> +num_pulses = 3  # Number of rectangles P
why not call it `P` like in the text?

2023-06-23 15:46 UTC, Qottmann commented on demonstrations/tutorial_optimal_control.py
> +def plot_optimal_pulses(hist, pulse_fn, ops, T, target_name, separate_two_qubit=False):
purely subjective, almost philosophical: Personally, I'd just do two separate plot codes instead of one big function that takes into account the two cases. Makes it more readable and more copy-pastable/modifiable as no one is going to go into the depths of deciphering this 😅

2023-06-23 15:46 UTC, Qottmann commented on demonstrations/tutorial_optimal_control.py
> +# to a future tutorial--or maybe your work?
genius 😆 !

2023-07-03 10:29 UTC, dwierichs reviewed
Thanks for the first comments, @qottmann! 
I'll incorporate all of them, they all seem very reasonable to me :)

2023-07-03 10:29 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +Instead, it allows us to play sequences of analogue electromagnetic pulses,
```suggestion
Instead, the hardware allows us to play sequences of analogue electromagnetic pulses,
```

2023-07-03 10:29 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +pulses acting on superconducting qubits.
```suggestion
for example by shining laser pulses on trapped ions or Rydberg atoms, or by sending microwave
pulses onto superconducting qubit cavities.
```

2023-07-03 10:29 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +evolution falls under the field of *quantum optimal control*.
```suggestion
For this, we parametrize a pulse sequence, which leads to a whole *space* 
of possible sequences. Then we optimize the pulse parameters in order to
find a configuration in this space that behaves as closely to the gate 
of interest as possible.
This training of control parameters to achieve a specific time
evolution is a standard task in the field of *quantum optimal control*.
```

2023-07-03 10:29 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +evolution falls under the field of *quantum optimal control*.
Changed a bit, I hope it is better now :D :)

2023-07-03 10:29 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +[Frobenius norm]
whoops, missing wiki link.

2023-07-03 10:29 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +[Frobenius norm]
```suggestion
`Frobenius norm <https://en.wikipedia.org/wiki/Matrix_norm#Frobenius_norm>`__
```

2023-07-03 10:29 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +while training the pulse parameters:
```suggestion
With a distance measure in our hands, we can write out the cost function that we want to
minimize by training the pulse parameters:
```

2023-07-03 10:29 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +def plot_optimal_pulses(hist, pulse_fn, ops, T, target_name, separate_two_qubit=False):
Very good call

2023-07-03 10:29 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +# to a future tutorial--or maybe your work?
:stuck_out_tongue:

2023-07-03 10:38 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +def plot_optimal_pulses(hist, pulse_fn, ops, T, target_name, separate_two_qubit=False):
Actually, what do you think about always plotting the two-qubit terms in a separate axis? Might be a better visualization?

2023-07-03 13:35 UTC, Qottmann commented on demonstrations/tutorial_optimal_control.py
> +def plot_optimal_pulses(hist, pulse_fn, ops, T, target_name, separate_two_qubit=False):
sure :)

2023-07-05 08:35 UTC, Qottmann reviewed
Thanks for the updates @dwierichs looks good !

I was wondering if it could be nice to add explicit prints of the execution times in the optimization loops to showcase how fast the jax jit business is :-) Comparable demos with qutip took much longer, right?

2023-07-05 08:35 UTC, Qottmann commented on demonstrations/tutorial_optimal_control.py
> +evolution is a standard task in the field of *quantum optimal control*.
Very nice 🙂

2023-07-05 08:35 UTC, Qottmann commented on demonstrations/tutorial_optimal_control.py
> +def sigmoid_rectangle(t, t_0, t_1, k=1.0):
👌

2023-07-05 08:35 UTC, Qottmann commented on demonstrations/tutorial_optimal_control.py
> +plot_optimal_pulses(hist, f, ops_param, T, target_name)
In my preview this plot is capped at the bottom, can you check if it is also for you?

2023-07-05 09:17 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +plot_optimal_pulses(hist, f, ops_param, T, target_name)
Seems to be fine for me: :grimacing: 
![image](https://github.com/PennyLaneAI/qml/assets/20772922/6d6d44f0-562c-49da-8aa1-4ac61e5f10cb)

2023-07-05 11:58 UTC, Qottmann commented on demonstrations/tutorial_optimal_control.py
> +plot_optimal_pulses(hist, f, ops_param, T, target_name)
Okay was just my cache that is sometimes acting strange on demo builds, with emptied cache it looks fine as well 👍

2023-07-11 15:05 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +Today, quantum computations largely are phrased in the language of quantum circuits
```suggestion
Today, quantum computations are largely phrased in the language of quantum circuits
```

2023-07-11 15:06 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +that are composed of digital quantum gates.
```suggestion
composed of digital quantum gates.
```

2023-07-11 15:07 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +
One line paragraph - should be merged with paragraph above.

2023-07-11 15:08 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +Instead of optimizing pulses to yield digital gates that are used in quantum circuits,
```suggestion
Instead of optimizing pulses to yield digital quantum gates,
```

2023-07-11 15:09 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +Instead of optimizing pulses to yield digital gates that are used in quantum circuits,
Too lengthy and you defined this before, so let's use the word!

2023-07-11 15:10 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +task, and it is important to specify underlying assumptions and constraints on
```suggestion
task, and it is important to specify the underlying assumptions and constraints on
```

2023-07-11 15:11 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +with the goal to produce a given target, namely a digital gate, to the highest-possible
```suggestion
with the goal to produce a given target, namely a digital gate, to the highest possible
```

2023-07-11 15:12 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +For the training phase we will make use of fully-differentiable classical simulations
```suggestion
For the training phase, we will make use of fully-differentiable classical simulations
```

2023-07-11 15:15 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +differentiation technique widely used in machine learning, and of gradient-based
```suggestion
of the qubit dynamics, allowing us to make use of backpropagation -- an efficient
differentiation technique widely used in machine learning -- and of gradient-based
```

2023-07-11 15:18 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +(to some degree) realistic to be implemented, including bounded
```suggestion
(to some degree) realistically feasible, including bounded
```

2023-07-11 15:22 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +obtain a CNOT and a Toffoli gate.
```suggestion
More concretely, we will optimize simple pulse programs on two and three qubits to
obtain a CNOT and a Toffoli gate.
This training of control parameters to achieve a specific time
evolution is a standard task in the field of *quantum optimal control*.
```

2023-07-11 15:33 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +Here we briefly discuss the general setup of pulse programs that we will use for our
```suggestion
Here, we briefly discuss the general setup of pulse programs that we will use for our
```

2023-07-11 15:45 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +    H(\boldsymbol{p}, t) = H_d + \sum_{i=1}^K f_i(\boldsymbol{p_i}, t) H_i.
$p_i$ has a subscript $i$ here, which makes the left and right hand side notations inconsistent. Should it just be $\boldsymbol{p}$ on the right hand side?

2023-07-11 16:22 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +    H(\boldsymbol{p}, t) = H_d + \sum_{i=1}^K f_i(\boldsymbol{p_i}, t) H_i.
I meant to express that $\mathbf{p}$ is a vector of vectors, where we call the inner vectors $\mathbf{p_i}$. Does that make sense?

2023-07-11 17:05 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +    H(\boldsymbol{p}, t) = H_d + \sum_{i=1}^K f_i(\boldsymbol{p_i}, t) H_i.
Sounds good, makes sense, but it would be good to state it explicitly!

2023-07-11 17:10 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +
The calligraphy in this drawing needs a bit of love (namely, the p looks weird 😅). Lmk if you would like help with this!

2023-07-11 17:11 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +but allows us to ignore differences in the global phase.
```suggestion
It is similar to the distance measure obtained from the
`Frobenius norm <https://en.wikipedia.org/wiki/Matrix_norm#Frobenius_norm>`__
but it allows us to ignore differences in the global phase.
```

2023-07-11 17:12 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +consider it as a constraint to the optimization problem, rather than a free variable.
```suggestion
Here :math:`U_\text{target}` is the unitary matrix of the gate that we want to compile.
We exclude the total duration :math:`T` from :math:`C` of the pulse sequence because we will
consider it as a constraint to the optimization problem, rather than a free variable.
```

2023-07-11 17:12 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +consider it as a constraint to the optimization problem, rather than a free variable.
So you mean to say we consider $T$ is fixed?

2023-07-11 17:13 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +We can then minimize the cost function :math:`C`, for example using gradient-based
```suggestion
We can then minimize the cost function :math:`C`, for example, using gradient-based
```

2023-07-11 17:13 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +optimization algorithms like adam [#KingmaBa14]_.
```suggestion
optimization algorithms like Adam [#KingmaBa14]_.
```

2023-07-11 17:14 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +the pulse shape that we will use:
```suggestion
the pulse shape that we will use.
```

2023-07-11 17:17 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +
Not sure this is the best part to include this figure. Maybe later is better once we've defined $R_{\infty}$ and $R_k$. It could be good to plot them using pyplot, even if we don't show the code. Also, it would be great to label the plots ($R_{\infty}$ and $R_k$).

2023-07-11 17:19 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +Let's implement the smooth-rectangle function using JAX's ``numpy``. We
```suggestion
Let's implement the smooth rectangle function using JAX's ``numpy``. We
```

2023-07-11 17:25 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +# abstract cross resonance driving term. Due to this choice, the :math:`Z_0` term
Can we write this Hamiltonian explicitly, for clarity?

2023-07-11 17:25 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +#
Does this Hamiltonian correspond to anything in reality, or is it a toy model?

2023-07-11 17:28 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +# For the normalization steps we define a ``sigmoid`` and a ``normalize`` function.
```suggestion
# For the normalization steps, we define a ``sigmoid`` and a ``normalize`` function.
```

2023-07-11 17:28 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +# The first is a straight-forward implementation of :math:`R_k` whereas the second
```suggestion
# The first is a straightforward implementation of :math:`R_k` whereas the second
```

2023-07-11 17:36 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +# ``sigmoid_rectangle`` functions, including two normalization steps:
```suggestion
# ``sigmoid_rectangle`` functions, including two normalization steps.
```

2023-07-11 17:41 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +
Was this remark for the original ugly sketch of mine or is it for the updated illustration? :)

2023-07-11 17:41 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +consider it as a constraint to the optimization problem, rather than a free variable.
Yes :laughing:

2023-07-11 17:42 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +# step, but again a smooth function. As a consequence, the values ``1.9`` and ``-2.``
```suggestion
# step, but again a smooth function. As a consequence, the amplitudes ``1.9`` and ``-2.``
```

2023-07-11 17:43 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +
Mhm. Yeah I thought it might be nice as a "teaser" for this rather dry step of making the pulse work :thinking:

2023-07-11 17:51 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +consider it as a constraint to the optimization problem, rather than a free variable.
Rephrased.

2023-07-11 17:52 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +
This is the first time I see the word infidelity. We called it "average gate fidelity before".

2023-07-11 17:53 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +
Ah, the build I was seeing had the previous one. Sorry to bash on it!

2023-07-11 17:54 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +
Ok! I think we can keep it, but maybe not right at the start of the section!

2023-07-11 17:55 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +# abstract cross resonance driving term. Due to this choice, the :math:`Z_0` term
It would look like this:
$H(\boldsymbol{p}, t) = Z_0+Z_1+F(\boldsymbol{p_1}, t) Z_0 + F(\boldsymbol{p_2}, t) X_1+F(\boldsymbol{p_3}, t) Y_1 + F(\boldsymbol{p_4}, t) Z_1+F(\boldsymbol{p_5}, t) Z_0X_1$
I'm not sure how informative this is? :thinking:

2023-07-11 17:59 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +# pulse shapes :math:`R_k`
I think it's good to answer this question, but probably this needs to be done consistently across the demo. I'll incorporate that. :)

2023-07-11 17:59 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +#
It's a toy model. Added a comment :)

2023-07-11 18:00 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +
Haha no, no worries, it _was_ ugly! :D

2023-07-11 18:01 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +
Moved it to inbetween the math and the code implementation :)

2023-07-11 18:03 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +
Ah, this is `1-fidelity`, hence infidelity :) (It's used in the literature, e.g. [here](https://journals.aps.org/pra/abstract/10.1103/PhysRevA.105.022437) but if it is too uncommon I can try to replace :) )

2023-07-11 18:03 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +# our target gate, the CNOT. We will use the adam optimizer [#KingmaBa14]_, implemented in the
```suggestion
# our target gate, the CNOT. We will use the Adam optimizer [#KingmaBa14]_, implemented in the
```

2023-07-11 18:04 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +# As we can see, adam steadily reduces the cost function, bringing the pulse program
```suggestion
# As we can see, Adam steadily reduces the cost function, bringing the pulse program
```

2023-07-11 18:05 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +# that plots the pulse sequence which we can reuse later on.
```suggestion
# that plots the pulse sequence, which we can reuse later on.
```

2023-07-11 18:16 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +# For the single-qubit terms we encode their qubit in the color and the type of Pauli
```suggestion
# For the single-qubit terms, we encode their qubit in the color and the type of Pauli
```

2023-07-11 18:25 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +# in the optimization with adam. Our ``run_adam`` function from above comes
```suggestion
# in the optimization with Adam. Our ``run_adam`` function from above comes
```

2023-07-11 18:25 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +# This looks promising: adam minimized the cost function successfully and we thus compiled
```suggestion
# This looks promising: Adam minimized the cost function successfully and we thus compiled
```

2023-07-11 18:26 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +# optimize the sequence regarding the number of generators and pulse duration!
```suggestion
# optimize the sequence with respect to the number of generators and pulse duration!
```

2023-07-11 18:28 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +# quantum hardware: We did not take into account the interaction terms
```suggestion
# quantum hardware. We did not take into account the interaction terms
```

2023-07-11 18:29 UTC, alvaro-at-xanadu requested changes
Amazing demo! Only minor grammar suggestions and comments, and we'll be good to go!

2023-07-12 08:03 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +# pulse shapes :math:`R_k`
Done :) It ended up being an explanation at this point in the demo mostly, with two comments in other places.

2023-07-12 08:19 UTC, dwierichs commented
Thanks @alvaro-at-xanadu for the thorough review! :) 
I incorporated all but a few changes, the others I answered in the comments here. Let me know how to proceed with those :)

2023-07-17 15:16 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +# abstract cross resonance driving term. Due to this choice, the :math:`Z_0` term
More informative than just explaining through text, which is super confusing! If you feel it's too long, write the drift and parametrized parts separately.

2023-07-17 15:16 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_optimal_control.py
> +#
Thank! It seems you did have that in the conclusion, but it's good to say this from the start!

2023-07-17 15:22 UTC, alvaro-at-xanadu approved these changes
All good on my side, just some minor things pending to address

2023-07-18 08:13 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +
Oh, sorry, I misunderstood your initial comment on this!

After looking at this again, I think I'd prefer to switch to _fidelity_ altogether. It's anyways the nicer concept than infidelity, leads to a maximization instead of a minimization problem for a change, and it better matches the first illustration in the demo :)

2023-07-18 08:47 UTC, dwierichs commented
Thanks a lot @alvaro-at-xanadu 
Left an answer to the last open point (which should also be resolved now) and resolved the other closed ones.
I switched from infidelity/cost functions/minimization to fidelity/profit/maximization, matching the image of "climbing mount fidelity" :)
Also made the images a bit larger, as they were already made with the total size in mind, unlike the previous sketches.

2023-07-19 18:11 UTC, KetpuntoG commented on demonstrations/tutorial_optimal_control.py
> +    with steepness parameter ``k``."""
```suggestion
    """Smoothly normalize a real input value to the interval (-1, 1) using 'sigmoid'
    with steepness parameter k."""
```

2023-07-19 18:14 UTC, KetpuntoG commented on demonstrations/tutorial_optimal_control.py
> +    with steepness parameter ``k``."""
This applies to everything after that. In pennylane it is defined the other way because it renders on the web but here I would try to do it the way it reads best in code

2023-07-19 18:19 UTC, KetpuntoG commented on demonstrations/tutorial_optimal_control.py
> +    return 1 - jnp.abs(jnp.trace(target @ op_mat)) / 2**num_wires
In this case you have done it this way because target = target ^dagg but it might not be the case. Maybe it is more accurate to make the adjoint or leave a note to be faithful to the definition of distance

2023-07-19 18:29 UTC, KetpuntoG commented on demonstrations/tutorial_optimal_control.py
> +#
How cool! I've missed a simple example where you can see it works. Could you do something like this?

```python
def circuit():
   qml.PauliX(wires = 0)
   qml.PauliX(wires = 1)
   qml.evolve(H,.... params)....
   return qml.probs(wires = [0,1,2])

```

to see that the output is indeed |111> as a toffoli would do.
Maybe it's not that easy, in that case, ignore this comment

2023-07-20 07:39 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +    d(U,V) = 1 - \frac{1}{2^N}\big|\operatorname{tr}[U^\dagger V]\big|.
> I thought it was a commutator, could you use tr() instead of tr[]?

Sure :)

> we usually put n as the number of qubits and N = 2^n, do you think it makes sense to change this?

Oh, I didn't know there was a convention! I'll update.

2023-07-20 07:40 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +def sigmoid_rectangle(t, t_0, t_1, k=1.0):
That's a fair point. I think there is no particular reason, I can change that :)

2023-07-20 07:49 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +def sigmoid_rectangle(t, t_0, t_1, k=1.0):
:heavy_check_mark:

2023-07-20 07:49 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +    d(U,V) = 1 - \frac{1}{2^N}\big|\operatorname{tr}[U^\dagger V]\big|.
:heavy_check_mark:

2023-07-20 07:51 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +    """Sigmoid function with steepness parameter ``k``."""
:heavy_check_mark:

2023-07-20 07:51 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +    f"which has an infidelity of {arb_cost:.6f}."
Sorry, I had switched to fidelity instead of infidelity already ,but missed to push the change. Let me know what you think of the current phrasing :)

2023-07-20 07:53 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +#
There is a number of options here. I'll try something :)

2023-07-20 08:48 UTC, Qottmann approved these changes
Great work @dwierichs 😇

2023-07-20 08:48 UTC, Qottmann commented on _static/large_demo_thumbnails/thumbnail_large_optimal_control.png
absolutely adore this 🤩 ❤️

2023-07-20 08:48 UTC, Qottmann commented on demonstrations/optimal_control/OptimalControl_control_quantum_systems.png
[Optional] can we add two horizontal qubit lines for the CNOT gate, at first glance this looked like an upside down ♀️ to me

2023-07-20 08:48 UTC, Qottmann commented on demonstrations/tutorial_optimal_control.py
> +    print(f"The optimization took {end_time-start_time:.1f} (CPU) seconds.")
🚀 nice!

2023-07-20 11:42 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +#
I added the example you provided, together with an additional plot that shows that the pulse sequence looks like a Toffoli gate :)

2023-07-21 08:05 UTC, dwierichs commented on demonstrations/optimal_control/OptimalControl_control_quantum_systems.png
Done :)

2023-07-21 08:48 UTC, Qottmann commented on demonstrations/optimal_control/OptimalControl_control_quantum_systems.png
So sorry but I meant to comment on the demo image, not the thumbnail, i.e. https://github.com/PennyLaneAI/qml/pull/827/files#diff-566fa175ca0060d0897c4a6f38c95d4e8aa785834b5a0f61b67e25c6418738db

2023-07-21 12:41 UTC, dwierichs commented on demonstrations/optimal_control/OptimalControl_control_quantum_systems.png
All good :) Updated that one as well :+1:

2023-07-21 13:26 UTC, Qottmann commented on demonstrations/optimal_control/OptimalControl_control_quantum_systems.png
Looks great! 👌

2023-07-25 19:46 UTC, BorjaRequena reviewed
Pretty cool demo! Thanks @dwierichs for putting together such a great work 🔥 

I left a few minor comments. The most important one is regarding the $S_k$ notation in the first parametrized Hamiltonian.

2023-07-25 19:46 UTC, BorjaRequena commented on demonstrations/tutorial_optimal_control.py
> +f = partial(smooth_rectangles, k=k, max_amp=max_amp, eps=eps, T=T)
Maybe we could give this partial a more meaningful name. When I reached the next code cell, in the `[f for op in ops_param]` I knew this was supposed to be the sum of smooth rectangles, but still I scrolled back up to check what `f` was again. Maybe something like `sr` would already work (?) It is not a critical thing though.

2023-07-25 19:46 UTC, BorjaRequena commented on demonstrations/tutorial_optimal_control.py
> +# generating terms in the Hamiltonian, and we see that their shape is closer to
I am not sure I would say "most terms". If I understand the plot correctly, only the $Z_0X_1$ and the $Z_1$ terms have a single rectangle, and the rest have two at least. Maybe we could soften this sentence?
```suggestion
# We observe that a single rectangular pulse is sufficient for many of the
# generating terms in the Hamiltonian, and we see that their shape is closer to
```

2023-07-25 19:46 UTC, BorjaRequena commented on demonstrations/tutorial_optimal_control.py
> +# or by increasing the precision with which we run the ODE solver.
The result is pretty nice! Fidelity 1 up to 1e-6 is pretty impressive 🚀

2023-07-25 19:46 UTC, BorjaRequena commented on demonstrations/tutorial_optimal_control.py
> +ops_param = [P(w) for P in [X, Y, Z] for w in range(num_wires)]
Maybe we should avoid using `P` here since it is the number of rectangles in every sum.
```suggestion
ops_param = [pauli(w) for pauli in [X, Y, Z] for w in range(num_wires)]
```
I am not very happy with the `pauli` name. It's mainly to avoid any possible confusion. Feel free to use any other name 😄 Again, not too critical.

2023-07-25 19:46 UTC, BorjaRequena commented on demonstrations/tutorial_optimal_control.py
> +coeffs = [1.0, 1.0, 1.0] + [f for op in ops_param]
If you decide to change the name of the previous `f` in the end, we should also update this one.

2023-07-25 19:46 UTC, BorjaRequena commented on demonstrations/tutorial_optimal_control.py
> +# and zeros else.
I am not sure this is a proper suggestion. It just sounded a bit odd to me, take it or leave it 😄
```suggestion
# flip the third qubit, returning a probability of one in the last entry
# and zeros elsewhere.
```

2023-07-25 19:46 UTC, BorjaRequena commented on demonstrations/tutorial_optimal_control.py
> +
Badass plot! 🔥

2023-07-26 07:27 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +# or by increasing the precision with which we run the ODE solver.
It's way easier without hardware constraints than with :P :) Thanks though!

2023-07-26 07:30 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +Consider a quantum system comprised of :math:`N` two-level systems, or qubits, described
Yes, it should indeed be lower case! Great catch!

2023-07-26 07:40 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +#     + \underset{\text{interaction}}{\underbrace{S_k(\boldsymbol{p_5}, t) Z_0X_1}}
Thanks, good call! 
I now did the following: Before the equation you marked, I explicitly say $f_i=S_k \forall i$, because previously, the coefficient functions are called $f_i$ and in the large equation, they suddenly are called $S_k$.
Essentially, I moved a bit of the commentary on the coefficient function above the equation, which to me seems to fix the problem.
Let me know what you think :)

2023-07-26 07:47 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +f = partial(smooth_rectangles, k=k, max_amp=max_amp, eps=eps, T=T)
How about `S_k`? :)

2023-07-26 07:48 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +# generating terms in the Hamiltonian, and we see that their shape is closer to
Yeah, you're right! I'll modify it further, thanks! :)

2023-07-26 07:51 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +ops_param = [P(w) for P in [X, Y, Z] for w in range(num_wires)]
Went for `pauli_op` :)

2023-07-26 12:55 UTC, BorjaRequena commented on demonstrations/tutorial_optimal_control.py
> +ops_param = [P(w) for P in [X, Y, Z] for w in range(num_wires)]
Much better!

2023-07-26 13:04 UTC, BorjaRequena commented on demonstrations/tutorial_optimal_control.py
> +# generating terms in the Hamiltonian, and we see that their shape is closer to
I like it!

2023-07-26 13:04 UTC, BorjaRequena commented on demonstrations/tutorial_optimal_control.py
> +f = partial(smooth_rectangles, k=k, max_amp=max_amp, eps=eps, T=T)
Oh ye! 😄

2023-07-26 13:05 UTC, BorjaRequena commented on demonstrations/tutorial_optimal_control.py
> +#     + \underset{\text{interaction}}{\underbrace{S_k(\boldsymbol{p_5}, t) Z_0X_1}}
Nice, I think it is much clearer now!

2023-07-26 13:07 UTC, BorjaRequena approved these changes
Thanks for the changes @dwierichs!! Looking good 🚀

2023-07-26 13:07 UTC, BorjaRequena commented on demonstrations/tutorial_optimal_control.py
> +# Each coefficient function :math:`f_i` sums :math:`P` smooth rectangles
Just this sneaky boi here 🥷 
```suggestion
# Each coefficient function :math:`S_k` sums :math:`P` smooth rectangles
```

2023-07-26 14:20 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +# Each coefficient function :math:`f_i` sums :math:`P` smooth rectangles
Hahaha.
Yeah, I was unsure about this one, because before this point, the Hamiltonian functions are still called $f_i$ :thinking:

2023-07-26 14:21 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.metadata.json
> +    "relatedDemonstrations": [
Not sure, I don't remember changing this. :thinking:

2023-07-26 14:24 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.metadata.json
> +    "relatedDemonstrations": [
It's actually coming from [`demonstrations_metadata.md`](https://github.com/PennyLaneAI/qml/blob/c185dd4a90ab3e2dc47d318d193cebfbb87fb4bd/demonstrations_metadata.md?plain=1#L55)

2023-07-26 14:25 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +# Each coefficient function :math:`f_i` sums :math:`P` smooth rectangles
Ah no, you are right, I confused them! :)

2023-07-26 15:54 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.metadata.json
> +    "relatedDemonstrations": [
@KetpuntoG I modified the linked line in `demonstrations_metadata.md` as well as in the metadata for the demo added here.

2023-08-01 20:53 UTC, trbromley commented
[SC-37123]

2023-08-04 14:13 UTC, KetpuntoG approved these changes

2023-08-04 14:13 UTC, KetpuntoG commented on demonstrations/tutorial_optimal_control.py
> +Instead, the hardware allows us to play sequences of analogue electromagnetic pulses,
```suggestion
Instead, the hardware allows us to play sequences of analog electromagnetic pulses,
```

2023-08-04 14:13 UTC, KetpuntoG commented on demonstrations/tutorial_optimal_control.py
> +        eps (float): Margin to beginning and end of the pulse sequence within which the
```suggestion
        eps (float): Margin to the beginning and end of the pulse sequence within which the
```

2023-08-04 14:13 UTC, KetpuntoG commented on demonstrations/tutorial_optimal_control.py
> +    # Extract start and end times of single rectangles
```suggestion
    # Extract the start and end times of single rectangles
```

2023-08-04 14:13 UTC, KetpuntoG commented on demonstrations/tutorial_optimal_control.py
> +# Finally, also not that the start and end times of the smooth rectangles are being
```suggestion
# Finally, also note that the start and end times of the smooth rectangles are being
```

2023-08-04 14:13 UTC, KetpuntoG commented on demonstrations/tutorial_optimal_control.py
> +# We create initial parameters similar to above but allow for a larger number
```suggestion
# We create initial parameters similar to the above but allow for a larger number
```

2023-08-04 14:13 UTC, KetpuntoG commented on demonstrations/tutorial_optimal_control.py
> +# The technique shown here reduces the parameter count signficantly
```suggestion
# The technique shown here reduces the parameter count significantly
```

2023-08-04 14:46 UTC, KetpuntoG commented on demonstrations/tutorial_optimal_control.metadata.json
> +    "dateOfLastModification": "2023-07-25T00:00:00+00:00",
```suggestion
    "dateOfPublication": "2023-08-08T00:00:00+00:00",
    "dateOfLastModification": "2023-08-08T00:00:00+00:00",
```

2023-08-04 14:46 UTC, dwierichs commented on demonstrations/tutorial_optimal_control.py
> +or :doc:`the tutorial on the QuEra Aquila device </demos/ahs_aquila>`, which treat pulse
I think both mentioned tutorials treat Rydberg atoms, so I'd keep the plural :)

2023-08-04 15:55 UTC, KetpuntoG commented on demonstrations/tutorial_optimal_control.py
> +*Author: David Wierichs. Posted: xx July, 2023.*
```suggestion
```

2023-08-04 15:56 UTC, KetpuntoG commented on demonstrations/tutorial_optimal_control.py
> +# Bibliography
```suggestion
# References
```

2023-08-04 16:23 UTC, merged