Demo on QSVT for matrix inversion
PennyLaneAI/qml pull request #836
Opened 2023-06-22 20:39 UTC by Jaybsoni

**Title: How To: Use QSVT for Matrix Inversion**

**Summary:**
A demo on how to use qsvt for matrix inversion.

2023-07-10 14:19 UTC, KetpuntoG reviewed
What a great job! Glad to see that it is so easy to apply qsvt to new applications 😍
Here are a few comments

2023-07-10 14:19 UTC, KetpuntoG commented on demonstrations/tutorial_apply_qsvt_real.py
> +# Final Thoughts and Applications
Do you think you could put "conclusion" for consistency? or do you prefer to leave it like this?

2023-07-10 14:19 UTC, KetpuntoG commented on demonstrations/tutorial_apply_qsvt_real.py
> +# unanswered questions yourself, and we hope that PennyLane can help you along the way
Great way to end the demo! 😊

2023-07-10 14:19 UTC, KetpuntoG commented on demonstrations/tutorial_apply_qsvt_real.py
> +======================================
In order to ask for the thumbnail you can read [here](https://www.notion.so/xanaduai/React-changes-in-the-demos-for-creators-71df8bbc58654318aa828b1e7a2d938d) the process.

Also, don't forget to include the metadata as mention in the Readme of the qml repo

2023-07-10 18:17 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt_real.py
> +#         >>> import pyqsp
Actually, the reason to have this in a comment is because for a user to run this code they need to have `pyqsp` installed. This is not a requirement for PennyLane. I don't think we even install it on GitHub when we build the website. For that reason I kept the code separate from the code we actually require with Pennylane

2023-07-10 19:24 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt_real.py
> +dev = qml.device("default.qubit", wires=[0, 1])
lightning qubit is not supported here

2023-07-10 19:25 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt_real.py
> +
Yes, The block encoded matrix and its adjoint appear in the expression for QSVT. This comes up when we generalize to support non hermitian, non square matrices.

2023-07-10 19:28 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt_real.py
> +# of the form :math:`A * \vec{x} = \vec{b}` for a valid :math:`\vec{x}`. This ultimately
Replaced with dot or nothing

2023-07-10 19:29 UTC, trbromley commented on demonstrations/tutorial_apply_qsvt_real.py
> +dev = qml.device("default.qubit", wires=[0, 1])
@Jaybsoni what issues do you run into with lightning qubit?

2023-07-10 19:30 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt_real.py
> +#         >>> kappa = 4
Kappa specifies the domain for the approximation. For example kappa = 4 means we are approximating 1/x on the domain [1/4, 1]. If the eigen spectrum of our matrix is limited to this domain and we have a good approximation of the 1/x function, then we get a good inverse to the matrix 👍🏼

Its a bit beyond the scope of the demo since we don't want to explain too much theory, but just show that its possible to do in practice

2023-07-10 19:31 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt_real.py
> +kappa = 5
I know it currently doesn't support Jax. I am not sure about Torch. This is using autograd under the hood, are we removing support for that soon? I thought that was the current default framework ?

2023-07-10 19:38 UTC, KetpuntoG commented on demonstrations/tutorial_apply_qsvt_real.py
> +kappa = 5
From this quarter we are trying to avoid the use of autograd and tensorflow whenever necessary. I am not sure if it will continue to be supported or is simply a new direction. @trbromley may be able to clarify more here

2023-07-11 17:31 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt_real.py
> +dev = qml.device("default.qubit", wires=[0, 1])
@trbromley, The BlockEncoding operator is currently not supported on Lightning. I think it should be easy to add support for it, but it was just out of scope last quarter.

2023-07-11 17:38 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt_real.py
> +
Added the heading, still need to add an illustration

2023-07-11 17:38 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt_real.py
> +algorithms [#qsvt]_, for a refresher on the basics of QSVT checkout our other
Added 👍🏼

2023-07-11 17:41 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt_real.py
> +#
This is more of a feature of QSVT itself, and is true even with the phase angles generated from external packages, I am not sure if we need to include it. What are your thoughts on this @ixfoduap?

2023-07-11 18:03 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt_real.py
> +###############################################################################
Added

2023-07-11 18:20 UTC, soranjh commented on demonstrations/tutorial_apply_qsvt_real.py
> +# match our target function, while the imaginary part is forced to 0.
I think the text is better to appear before the code. So the reader gets an idea about what we will be doing in the code block.

2023-07-11 18:20 UTC, soranjh commented on demonstrations/tutorial_apply_qsvt_real.py
> +# Optimization:
From here up to the plotting, there is too much code without enough text. We might break down the code examples a bit and provide some explanation.

2023-07-11 18:20 UTC, soranjh commented on demonstrations/tutorial_apply_qsvt_real.py
> +# transformed to represent our target state (excluding scale factors)!
I feel that this paragraph could appear at the beginning of this section. And then, have a step by step explanation followed by the relevant code blocks.

2023-07-11 18:20 UTC, soranjh commented on demonstrations/tutorial_apply_qsvt_real.py
> +# Notice that the target state and computed state agree well with only some slight
Can we have a visualisation of this?

2023-07-11 18:20 UTC, soranjh commented on demonstrations/tutorial_apply_qsvt_real.py
> +# Final Thoughts and Applications
Conclusions makes more sense to me.

2023-07-12 10:54 UTC, jsmallz333 commented on demonstrations/tutorial_apply_qsvt.py
> +# .. math::  p(a) = \frac{1}{\kappa} a^{-1},
Do we want to mention the kappa as this ration relating to how 'easy' it is to invert the matrix?

2023-07-12 11:05 UTC, jsmallz333 commented on demonstrations/tutorial_apply_qsvt.py
> +# non-zero imaginary component in our compute state is caused because the imaginary
```suggestion
# non-zero imaginary component in our computed state is caused because the imaginary
```

2023-07-12 11:38 UTC, jsmallz333 commented on demonstrations/tutorial_apply_qsvt.py
> +*Authors: Jay Soni, Jarret Smalley — Posted: <date>, 2023.*
```suggestion
*Authors: Jay Soni, Jarrett Smalley — Posted: <date>, 2023.*
```

2023-07-12 12:59 UTC, mlxd commented on demonstrations/tutorial_apply_qsvt_real.py
> +dev = qml.device("default.qubit", wires=[0, 1])
I can make a 1 line change to lightning to add support for this op. It won't work with the adjoint diff gradients, but it'll work in the forward pass and with param-shift for gradients. Would that help?

2023-07-12 13:42 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt_real.py
> +dev = qml.device("default.qubit", wires=[0, 1])
We are just using the default method for training which I think is just backprop here? If that is supported with your change @mlxd, then it would be nice! I could change the device to lightning everywhere in the demo!

2023-07-12 14:12 UTC, ixfoduap requested changes
Demo is looking good overall but it is currently too long and needs polishing

2023-07-12 14:12 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +epoch = 0
Epoch has a very specific meaning in ML, which I believe is not exactly just the number of steps (I think it's to do with number of batches? something like that) I suggest revising this, maybe changing

2023-07-12 14:12 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# Notice that the real component of our transformation approximates our target
```suggestion
# Notice that the real component of our transformation approximates the target
```

2023-07-12 14:12 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# function while the imaginary component is suppressed to 0 in the same domain.
```suggestion
# function while the imaginary component is suppressed to zero in the same domain.
```

2023-07-12 14:12 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# Lets begin by defining the specific :math:`A` and :math:`\vec{b}` quantities. Our target
```suggestion
# Let's begin by defining the specific :math:`A` and :math:`\vec{b}` quantities. Our target
```

2023-07-12 14:12 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# transformed to represent our target state (excluding scale factors)!
```suggestion
# transformed to represent our target state (excluding scale factors).
```

2023-07-12 14:12 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# Yay 🎉! We have solved the linear system!
```suggestion
# We have solved the linear system 🎉!
```
Double Yay seemed like too much, even for Jay

2023-07-12 14:12 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# component in our approximation isn't completely 0 on the entire domain.
```suggestion
# approximately the identity operator. 
```
No need to justify/explain. It just makes things weaker

2023-07-12 14:12 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +]
```suggestion
```
I don't think any of this is needed. This demo should just be teaching how to use the code

2023-07-12 14:12 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +
```suggestion
```
Again, not needed

2023-07-12 14:12 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# to the next big discovery.
```suggestion
# In this demo, we showcased the :code:`qml.qsvt()` functionality in PennyLane,
# specifically to solve the problem of matrix inversion. We showed how to use
# phase angles computed with external packages and how to use PennyLane
# to optimize the phase angles directly.  We finally described how to apply qsvt to an example linear system.
#
# While the matrix we inverted was a simple example, the general problem of matrix
# inversion is often the bottleneck in many applications from regression analysis in
# financial modelling to simulating fluid dynamics for jet engine design. We hope that PennyLane can help you # along the way to your next big discovery in quantum algorithms. 
```

2023-07-12 14:36 UTC, ixfoduap requested changes
Demo is looking good overall but it is currently too long and needs polishing

2023-07-14 18:50 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt_real.py
> +#         >>> import pyqsp
This is true, but we also don't want to introduce unwanted dependancies into the qml repo. Maybe I can make a note just linking to the repo and a single api call instead of the whole workflow. My goal here was to be as explicit as possible. That might be overkill

2023-07-17 12:47 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +# This is an active area of research, and we welcome users to take advantage of these resources.
removed

2023-07-17 12:48 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +epoch = 0
Replaced with `tier`

2023-07-18 18:27 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +# The phase angles are the keys that unlock the power of QSVT because they define the
Removed

2023-07-20 12:45 UTC, KetpuntoG commented on demonstrations/tutorial_apply_qsvt.py
> +# :math:`kappa` to get :math:`A^{-1}`:
```suggestion
# :math:`\kappa` to get :math:`A^{-1}`:
```

2023-07-20 12:48 UTC, KetpuntoG commented on demonstrations/tutorial_apply_qsvt.py
> +# In this demo, we showcased the :code:`qml.qsvt()` functionality in PennyLane, specifically to
```suggestion
# In this demo, we showcased the :func:`~.pennylane.qsvt` functionality in PennyLane, specifically to
```

This is how the link is created

2023-07-20 12:50 UTC, KetpuntoG commented on demonstrations/tutorial_apply_qsvt.py
> +# .. include:: ../_static/authors/jarrett_smalley.txt
[This is a note to myself]

Make sure the new author is in the React repository

2023-07-20 16:13 UTC, ixfoduap requested changes
In much better shape, but still needs substantial improvements

2023-07-20 16:13 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# is equivalent to applying :math:`\frac{1}{\kappa} \cdot A^{-1}` to the prepared state. Finally,
Not clear to the reader why this is equivalent to 1/kappa A^-1

2023-07-20 16:13 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +###############################################################################
I think this is unnecessary. If you obtain approximately the right solution state, then that's all we need to show. Also, the fact that you round the matrix to one decimal point is a bit misleading

2023-07-20 16:13 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +###############################################################################
So I suggest removing this section

2023-07-20 16:13 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# Solving a Linear System with QSVT
It seems to me like we would be better off using the pyQSP angles here. What we see from the optimization is that the result is good but not amazing. If it works great, then no need to discuss things that could be done to make it better

2023-07-21 13:55 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +def sum_even_odd_circ(a, phi, ancilla_wire, wires):
One thing to note, since we are only interested in the fit on the domain [1/kappa, 1]. The parity of the function we are trying to fit doesn't matter. This is because the symmetry of the polynomial only plays a role when your domain crosses 0.

2023-07-21 13:56 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +    qml.ctrl(qml.qsvt, control=(ancilla_wire,), control_values=(1,))(a, phi2, wires=wires)
Diego is working on exactly this feature!

2023-07-24 13:28 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +# The sum is achieved by using a simple LCU structure. We first split the phase angles
Added 👍🏼

2023-07-24 13:29 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +print("computed x:", np.round(normalized_computed_x, 3))
👍🏼

2023-07-24 13:42 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +###############################################################################
I cleaned it up a bit, let me know if it still seems excessive / misleading

2023-07-24 13:43 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +# use a simple LCU trick when applying the transformation for matrix inversion.
shortened it

2023-07-25 19:48 UTC, KetpuntoG reviewed
It's almost done! 😊There would only be one change that would require some work. Reviewing the comments, I commented about use torch instead of numpy if possible. By default we are dropping numpy for differentiation tasks. As this is a demo that takes 10 minutes to run, I think it would be a good idea to try to adapt to it 💪

It should not change too much. Check this [demo](https://pennylane.ai/qml/demos/tutorial_qnn_module_torch) in case you need a template of the training process

2023-07-25 19:48 UTC, KetpuntoG commented on demonstrations/tutorial_apply_qsvt.py
> +@qml.qnode(qml.device("default.qubit", wires=["ancilla1", "ancilla2", 0, 1, 2]))
There was a conversation about add support for the block encoding in lightning.qubit, was it include at the end @mlxd ?

2023-07-25 21:04 UTC, soranjh reviewed
Thanks @Jaybsoni, looks very good. I left some comments and suggestions.

2023-07-25 21:05 UTC, soranjh commented on demonstrations/tutorial_apply_qsvt.py
> +# (`LCU <https://codebook.xanadu.ai/H.6>`_) structure. We first split the phase angles into
[nonblocking] Mentioning LCU seems a bit overkill.

2023-07-25 21:27 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# However, :math:`\frac{1}{x}` is greater than or equal to one on this domain.
The domain [-1, 1] includes numbers like 0.5, and 1/0.5 = 2 >= 1

2023-07-26 23:30 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# Matrix Inversion
I feel like this section could be just a couple of sentences. We focus on computing A^{-1} = \sum 1/s |v><u|, where s are singular values and u,v are right and left singular vectors. This can help us solve a linear system Ax=b by setting x = A^-1 b. We do this by using QSVT to implement a polynomial transformation of A that approximates the inverse function 1/x. We introduce the parameter kappa that determine the smallest singular value we want to accurately invert, and a scaling factor

2023-07-26 23:30 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# have a particular one in mind, it's not always easy to know which phase angles produce it
remove the second sentence

2023-07-26 23:30 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# 1. Using external packages that provide numerical angle solvers (`pyqsp <https://github.com/ichuang/pyqsp>`_)
```suggestion
# 1. Using external packages that provide numerical angle solvers (`pyqsp <https://github.com/ichuang/pyqsp>`_).
```

2023-07-26 23:30 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# 2. Using PennyLane's differentiable workflow to optimize the phase angles
```suggestion
# 2. Using PennyLane's differentiable workflow to optimize the phase angles.
```

2023-07-26 23:30 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +#
Consider removing this. It's redundant given the explanation above about matrix inversion

2023-07-26 23:30 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# convention as a keyword argument, for example :code:`qml.qsvt(A, phases, wires, convention="Wx")`.
I find it weird to have a line of code in the text. Just say it's a kwarg and then later in the code highlight it

2023-07-26 23:30 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# to generate a polynomial approximation from QSVT.
```suggestion
# take advantage of this as an alternate approach to obtaining the phase angles by using gradient-based 
# optimization. This approach is very versatile because we can use the target function directly
# to generate a polynomial approximation from QSVT.
```
An example of how writing can be more elegant and easy to read by increasing information density

2023-07-26 23:30 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# (`LCU <https://codebook.xanadu.ai/H.6>`_) structure. We first split the phase angles into
```suggestion
# (`LCU <https://codebook.xanadu.ai/H.6>`_) . We first split the phase angles into
```

2023-07-26 23:30 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# (`LCU <https://codebook.xanadu.ai/H.6>`_) structure. We first split the phase angles into
I think it's ok. Really LCU is a simple idea

2023-07-26 23:30 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# LCU trick when applying the transformation for matrix inversion.
```suggestion
# our target function. In this case, we ignore the imaginary component.
```

2023-07-26 23:30 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# Awesome, we successfully optimized the phase angles! While we used a standard loss function
The plots look much better now

2023-07-26 23:30 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# function, although other choices could be made. The error is computed using samples from the
```suggestion
# function. The error is computed using samples from the
```
Later you say that users can make different choices, so no need here

2023-07-26 23:30 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# In general, the imaginary part of this transformation will *NOT* be zero. In order to perform
```suggestion
# In general, the imaginary part of this transformation will not be zero. In order to perform
```
Relax no need to *YELL*!

2023-07-26 23:30 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# Let's take everything we have learned and apply it to solve a linear system of equations!
```suggestion
# Let's take everything we have learned and apply it to solve a linear system of equations.
```

2023-07-26 23:30 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# defining the specific :math:`A` and :math:`\vec{b}` quantities:
```suggestion
# defining the specific matrix :math:`A` and vector :math:`\vec{b}`:
```

2023-07-26 23:30 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +transformed_state = linear_system_solver_circuit(phi)[:4]  # first 4 entries of the state vector
This demo has a lot of code that needs horizontal scrolling in the built version, which leads to a bad reading experience. Can we please do something to avoid that? Shorter variable names would help

2023-07-26 23:30 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# vector :math:`\vec{b}` in the working qubit register. Next we call :code:`real_u(A, phi)`
```suggestion
# vector :math:`\vec{b}` in the working qubit register. Next we call the :code:`real_u(A, phi)`
```

2023-07-26 23:30 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +###############################################################################
It's better

2023-07-26 23:30 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# We have solved the linear system 🎉!
```suggestion
```
This is again conflating matrix inversion and solving a linear system, you're celebrating solving a linear system when a matrix is correctly inverted

2023-08-03 20:59 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +#     We generated the angles using the following api calls:
yes, but it sounds weird so I changed it 👍🏼

2023-08-03 21:04 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +# invertible. Recall that computing :math:`A^{-1}` is the same as inverting the singular
I don't know of a clear reference, this is just a standard result in linear algebra we learn in school. I think it should be fine to leave without reference.

2023-08-03 21:07 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +phi_pyqsp = [-2.287, 2.776, -1.163, 0.408, -0.16, -0.387, 0.385, -0.726, 0.456, 0.062, -0.468, 0.393, 0.028, -0.567, 0.76, -0.432, -0.011, 0.323, -0.573, 0.82, -1.096, 1.407, -1.735, 2.046, -2.321, 2
I think the numbers aren't that important, so it's fine if people need to scroll to the side to see them all. Id rather not fill up the page with numbers that mean nothing.

2023-08-03 21:13 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +# Both of the methods above produce phase angles :math:`\vec{\phi}` such that:
yes 👍🏼

2023-08-03 21:26 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +# convention as a keyword argument, for example :code:`qml.qsvt(A, phases, wires, convention="Wx")`.
Removed 👍🏼

2023-08-03 21:30 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +# In general, the imaginary part of this transformation will *NOT* be zero. In order to perform
I get excited easily

2023-08-03 21:32 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +transformed_state = linear_system_solver_circuit(phi)[:4]  # first 4 entries of the state vector
yes!

2023-08-08 21:01 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +of a matrix [#qsvt]_. For a refresher on the basics of QSVT check out our
Re-ordered references

2023-08-08 21:07 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +*Authors: Jay Soni, Jarrett Smalley [Rolls-Royce] — Posted: <date>, 2023.*
Reminder to add a Posted date

2023-08-08 21:15 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +# and the :code:`scale` factor was extracted from the pyqsp module. Remember that the number of
Swapped everything to 's'

2023-08-09 14:14 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +#
It is redundant, but I like that it highlights `P(x)` which is what we use to refer to our target transformation throughout the rest of the demo. It doesn't take up too much extra space to keep.

2023-08-09 14:17 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +# real component corresponds to our target function :math:`P(x)`.
This just comes from the definition of QSVT.

2023-08-09 14:19 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +# qubit is reset.
I think it might take away from the main goal of this demo. We just want to use LCUs, not teach users what they are or how they work. For that they can click the codebook link and learn about them directly.

2023-08-09 14:20 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +@qml.qnode(qml.device("default.qubit", wires=["ancilla1", "ancilla2", 0, 1, 2]))
In the interest of time, its best to leave the demo as is.

2023-08-10 18:45 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +# Now let's look at an application of QSVT --- solving a linear system of equations.
Rephrased

2023-08-10 18:45 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +functionality in PennyLane, focusing on matrix inversion as a guiding example.
Rephrased

2023-08-10 18:46 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +# The quantity :math:`\kappa` defines the domain :math:`[\frac{1}{\kappa}, 1]` for which the
Not required

2023-08-10 18:53 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +# To remedy this, we instead approximate :math:`s \cdot \frac{1}{x}`, where :math:`s`
It rescales 1/x to fit inside the bounds on our target domain, so at most s = 1 / kappa, otherwise it can be as small as the user decides. From optimization perspective, its unclear what the best `s` value is, but from trial and error it seems to be easier to fit the flat "tail" of the function then the steep drop. Either way this is left for the user to determine.

2023-08-10 18:53 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +# We have solved the linear system 🎉!
Rephrased

2023-08-10 19:03 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +# Matrix Inversion
I have rephrased parts of this section, but for the most part I have left it the same. I think we need the context for why kappa and the scale factor are required in the first place.

2023-08-14 16:56 UTC, Jaybsoni commented
[sc-43374]

2023-08-14 19:27 UTC, ixfoduap requested changes
Minor but important changes

2023-08-14 19:27 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# function. This is equivalent to applying :math:`s \cdot A^{-1}` to the prepared state.
```suggestion
# function that we previously constructed. This is equivalent to applying :math:`s \cdot A^{-1}` to the prepared state.
```

2023-08-14 19:27 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# We showed how to integrate phase angles computed with external packages and how to use
```suggestion
# We explained how to integrate phase angles computed with external packages and how to use
```

2023-08-14 19:27 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# PennyLane to optimize the phase angles directly. Finally, we described how to apply qsvt
here you're using lowercase qsvt I believe in reference to the PL function. If so, consider linking to the code. If not, then capitalize for the acronym of the algorithm

2023-08-14 19:27 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# While this demo covered simple example, the general problem of solving LSEs is often the
```suggestion
# While this demo covered simple example, the general problem of solving linear systems of equations is often the
```

2023-08-15 12:23 UTC, KetpuntoG commented on demonstrations/tutorial_apply_qsvt.metadata.json
> +    "dateOfLastModification": "2022-07-26T00:00:00+00:00",
```suggestion
    "dateOfPublication": "2023-08-22T00:00:00+00:00",
    "dateOfLastModification": "2023-08-22T00:00:00+00:00",
```

2023-08-16 13:17 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +*Authors: Jay Soni, Jarrett Smalley [Rolls-Royce] — Posted: <date>, 2023.*
```suggestion
*Authors: Jay Soni, Jarrett Smalley [Rolls-Royce] — Posted: 22 August 2023.*
```

2023-08-16 13:22 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +# PennyLane to optimize the phase angles directly. Finally, we described how to apply qsvt
```suggestion
# PennyLane to optimize the phase angles directly. Finally, we described how to apply QSVT
```

2023-08-16 13:22 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +# PennyLane to optimize the phase angles directly. Finally, we described how to apply qsvt
Replaced with QSVT

2023-08-16 13:26 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +# convention as a keyword argument to the qsvt function.
```suggestion
# convention as a keyword argument to the :func:`~.pennylane.qsvt()` function.
```

2023-08-16 16:17 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +# polynomial approximation to the transformation :math:`\frac{1}{x}`. This may seem simple
Updated with Leigh's comment

2023-08-16 19:46 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +def sum_even_odd_circ(x, phi, ancilla_wire, wires):
Added 👍🏼

2023-08-17 14:29 UTC, jsmallz333 commented on demonstrations/tutorial_apply_qsvt.py
> +        x, phi_pyqsp, wires=[0], convention="Wx"  # specify angles using convention=`Wx`
comment could include that this matches the signal_operator of the pyqsp generator, eg ``` # specify angles using convention=`Wx` matching pyqsp signal_operator ```

2023-08-17 14:29 UTC, jsmallz333 commented on demonstrations/tutorial_apply_qsvt.py
> +# vector :math:`\vec{b}` in the working qubit register. Next we call the :code:`real_u(A.T, phi)`
While introducing `real_u()`, should there be an explanation for why one would now use `A.T` instead of the standard `A`?

2023-08-17 15:16 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +# This ultimately requires computing math:`\vec{x} = A^{-1} \cdot \vec{b}`, where for simplicity we
```suggestion
# This ultimately requires computing :math:`\vec{x} = A^{-1} \cdot \vec{b}`, where for simplicity we
```

2023-08-17 15:18 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +# angles which produce a transformation of degree 43.
```suggestion
# angles which produce a polynomial of degree 43.
```

2023-08-17 15:20 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +        x, phi_pyqsp, wires=[0], convention="Wx"  # specify angles using convention=`Wx`
I had that before, but I received feedback that the comment was too long. We also mention it in the paragraph above, so we should be fine 👍🏼

2023-08-17 17:10 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +# vector :math:`\vec{b}` in the working qubit register. Next we call the :code:`real_u(A.T, phi)`
This context was added in the Problem section: "`A^{-1}` can be constructed directly by inverting the singular values of `A^{T}`". This section is just conforming to that.

2023-08-17 17:10 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +# This ultimately requires computing math:`\vec{x} = A^{-1} \cdot \vec{b}`, where for simplicity we
Added 👍🏼

2023-08-17 17:11 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +# angles which produce a transformation of degree 43.
Added 👍🏼

2023-08-17 17:33 UTC, Jaybsoni commented
[sc-43370]

2023-08-17 18:53 UTC, KetpuntoG reviewed
Thanks for the effort here! 🚀
Two last comments, otherwise good to go

2023-08-17 18:53 UTC, KetpuntoG commented on demonstrations/tutorial_apply_qsvt.py
> +:doc:`Intro to QSVT </demos/tutorial_intro_qsvt>` tutorial. This demo, written in
"For a refresher on the basics of QSVT check out our tutorial"

I would put this phrase in the preliminaries instead of in the intro

2023-08-17 18:53 UTC, KetpuntoG commented on demonstrations/tutorial_apply_qsvt.py
> +    qsvt_y_vals.append(np.real(poly_x[0, 0]))
I guess that it is ok because the graph looks correct but I have a doubt. The transformation should be performed on eigenvalues, not on the element [0,0]. In case the matrix is diagonal it would match but if the encoding is not a diagonal matrix (as in this case), it throws me off

2023-08-17 19:22 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +    qsvt_y_vals.append(np.real(poly_x[0, 0]))
Haha, good question. The way to think about this is QSVT acts on the Eigen-values of A. If A is itself a scalar (in this case) then it acts directly on A. We are block encoding it in a 2x2 matrix. 

If A was a 2x2 matrix, our QSVT circuit would have block encoded it in a 4x4 and applied the transformation to the eigenvalues of A in the top left corner of the matrix 💯

2023-08-17 19:39 UTC, KetpuntoG commented on demonstrations/tutorial_apply_qsvt.py
> +    qsvt_y_vals.append(np.real(poly_x[0, 0]))
Ah I see, I thought A was a 2x2 matrix and something seemed strange!

2023-08-17 19:44 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +:doc:`Intro to QSVT </demos/tutorial_intro_qsvt>` tutorial. This demo, written in
Added 👍🏼

2023-08-17 20:37 UTC, ixfoduap approved these changes
Just please address these last few suggestions before merging

2023-08-17 20:37 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# .. math::  P(x) = s \cdot \frac{1}{x},
```suggestion
# .. math::  P(x) = s \cdot \frac{1}{x}.
```

2023-08-17 20:37 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +# of the QSVT circuit. The top left entry is a polynomial approximation whose
```suggestion
# of the QSVT circuit. The top-left entry is a polynomial approximation whose
```

2023-08-17 20:37 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +    qml.Hadamard(wires=ancilla_wire)  # collapse superposition to recover the sum of both
```suggestion
    qml.Hadamard(wires=ancilla_wire)  # unprepare superposition
```

2023-08-17 20:37 UTC, ixfoduap commented on demonstrations/tutorial_apply_qsvt.py
> +#    \hat{U}_{real}(\vec{\phi}) = \frac{1}{2} \ ( \hat{U}_{qsvt}(\vec{\phi}) + \hat{U}^{\dagger}_{qsvt}(\vec{\phi}) )
```suggestion
#    \hat{U}_{real}(\vec{\phi}) = \frac{1}{2} \ ( \hat{U}_{qsvt}(\vec{\phi}) + \hat{U}^{\dagger}_{qsvt}(\vec{\phi}) ).
```

2023-08-17 21:12 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +    qml.Hadamard(wires=ancilla_wire)  # collapse superposition to recover the sum of both
```suggestion
    qml.Hadamard(wires=ancilla_wire)  # un-prepare superposition
```

2023-08-17 21:12 UTC, Jaybsoni commented on demonstrations/tutorial_apply_qsvt.py
> +    qml.Hadamard(wires=ancilla_wire)  # collapse superposition to recover the sum of both
Adde 👍🏼

2023-08-17 22:03 UTC, KetpuntoG approved these changes
🚀🚀🚀

2023-08-17 22:18 UTC, merged