LCU + Block encoding demo
PennyLaneAI/qml pull request #888
Opened 2023-08-11 21:35 UTC by ixfoduap

Last demo in the Rolls Royce QSVT series

2023-08-17 21:21 UTC, DSGuala commented on demonstrations/tutorial_lcu_blockencoding.py
> +# FOn the other hand, it's good to remember that many types of Hamiltonians are already compactly expressed
```suggestion
# On the other hand, it's good to remember that many types of Hamiltonians are already compactly expressed
```

2023-08-17 21:21 UTC, DSGuala commented on demonstrations/tutorial_lcu_blockencoding.py
> +# in the Pauli basis, for example in various Ising models [] and for molecular Hamiltonians using the
```suggestion
# in the Pauli basis, for example in various `Ising models <https://en.wikipedia.org/wiki/Ising_model>`_ and for molecular Hamiltonians using the
```

2023-08-17 21:21 UTC, DSGuala commented on demonstrations/tutorial_lcu_blockencoding.py
> +# Jordan-Wigner transformation []. This is very useful since we get one LCU decomposition
```suggestion
# `Jordan-Wigner transformation <https://en.wikipedia.org/wiki/Jordan%E2%80%93Wigner_transformation>`_. This is very useful since we get one LCU decomposition
```

2023-08-17 21:21 UTC, DSGuala commented on demonstrations/tutorial_lcu_blockencoding.py
> +# The way to understand this equation is that if apply PREP, SEL, and then invert PREP. After, if
```suggestion
# The way to understand this equation is that we apply PREP, SEL, and then invert PREP. After, if
```

2023-08-17 21:21 UTC, DSGuala commented on demonstrations/tutorial_lcu_blockencoding.py
> +# measure :math:`|0\rangle` in the auxiliary qubits, the input state will be transformed by
```suggestion
# we measure :math:`|0\rangle` in the auxiliary qubits, the input state will be transformed by
```

2023-08-17 21:21 UTC, DSGuala commented on demonstrations/tutorial_lcu_blockencoding.py
> +# PennyLane supports direct implementation of prepare and select operators. Let's go through them
```suggestion
# PennyLane supports direct implementation of `prepare <https://docs.pennylane.ai/en/latest/code/api/pennylane.StatePrep.html>`_ and `select <https://docs.pennylane.ai/en/latest/code/api/pennylane.Select.html?highlight=select>`_ operators. Let's go through them
```

2023-08-17 21:21 UTC, DSGuala commented on demonstrations/tutorial_lcu_blockencoding.py
> +# our demos []. PennyLane supports a :class:`~.pennylane.BlockEncode` operation that is designed for
```suggestion
# our `demos <https://pennylane.ai/qml/demos/tutorial_intro_qsvt>`_. PennyLane supports a :class:`~.pennylane.BlockEncode` operation that is designed for
```

2023-08-17 21:40 UTC, ixfoduap commented on demonstrations/tutorial_lcu_blockencoding.py
> +My colleague Nathan Wiebe [] once told me that some of his early research was motivated by a simple
Thanks, but google scholar probably better

2023-08-17 21:40 UTC, ixfoduap commented on demonstrations/tutorial_lcu_blockencoding.py
> +linear combination of unitaries; or LCUs for short. You will also understand how to
Wow good catch! Both work but the s is more appropriate here

2023-08-17 21:40 UTC, ixfoduap commented on demonstrations/tutorial_lcu_blockencoding.py
> +singular value transformation (QSVT) [].
But I think we need to remove one parenthesis

2023-08-17 21:40 UTC, ixfoduap commented on demonstrations/tutorial_lcu_blockencoding.py
> +[Main Tarik image here]
Does not exist. Let's request indeed!

2023-09-05 20:36 UTC, Jaybsoni requested changes
Left a bunch of comments. I think the demo will still require some work before we can consider pushing it forward.

2023-09-05 20:36 UTC, Jaybsoni commented on demonstrations/tutorial_lcu_blockencoding.py
> +# ..include::../ _static / authors / diego_guala.txt
```suggestion
# .. include:: ../_static/authors/jay_soni.txt
# .. include:: ../_static/authors/diego_guala.txt
```

2023-09-05 20:36 UTC, Jaybsoni commented on demonstrations/tutorial_lcu_blockencoding.py
> +# (Tip: calculate the action of :math:`\text{PREP}^\dagger on :math:`|0\rangle`, not on the output
```suggestion
# (Tip: calculate the action of :math:`\text{PREP}^\dagger` on :math:`\langle 0|`, not on the output
```

2023-09-05 20:36 UTC, Jaybsoni commented on demonstrations/tutorial_lcu_blockencoding.py
> +# defined by the subspace of all states where the auxiliary qubits are in state :math:`|0\rangle`.
```suggestion
# The reason for this name is that if we write down as a matrix, the operator :math:`A` is encoded inside a block of :math:`U`
# defined by the subspace of all states where the auxiliary qubits are in state :math:`|0\rangle`.
```

2023-09-05 20:36 UTC, Jaybsoni commented on demonstrations/tutorial_lcu_blockencoding.py
> +# defined by the subspace of all states where the auxiliary qubits are in state :math:`|0\rangle`.
Maybe add an equation under here with A in the top left of a matrix U:

![image](https://github.com/PennyLaneAI/qml/assets/21964864/9186e35b-a3f5-4ed1-af9f-8a0a84698a20)

`\hat{U}\  =  \ \begin{bmatrix}
A & \cdot \\
\cdot & \cdot
\end{bmatrix}`

2023-09-05 20:36 UTC, Jaybsoni commented on demonstrations/tutorial_lcu_blockencoding.py
> +
It's unclear from the description of this section why the expected output is what it is. Requires a little more content.

2023-09-05 20:36 UTC, Jaybsoni commented on demonstrations/tutorial_lcu_blockencoding.py
> +# We can now combine these to construct a full LCU circuit. Here we make use of :fun:`~.pennylane.adjoint`
```suggestion
# We can now combine these to construct a full LCU circuit. Here we make use of the :func:`~.pennylane.adjoint` function
```

2023-09-05 20:36 UTC, Jaybsoni commented on demonstrations/tutorial_lcu_blockencoding.py
> +print(A)
For a cleaner print output. Also, as it displays currently in the build, the example is wrong and needs to be fixed.

```suggestion
output_matrix = qml.matrix(lcu_circuit)()
print("A:\n", A, "\n")
print("Block-encoded A:\n")
print(np.real(np.round(output_matrix)))
```

2023-09-05 20:36 UTC, Jaybsoni commented on demonstrations/tutorial_lcu_blockencoding.py
> +# probably master. PennyLane is equipped with the tools to help you get there.
```suggestion
# master. PennyLane is equipped with the tools to help you get there.
```

2023-09-05 20:36 UTC, Jaybsoni commented on demonstrations/tutorial_lcu_blockencoding.py
> +print(out_matrix(np.pi / 2))
I think we can come up with a better example which is more compelling in showing how we used the block encoding with QSVT. I would suggest re-working this example.

2023-09-07 20:56 UTC, DSGuala commented on demonstrations/tutorial_lcu_blockencoding.py
> +encoded in quantum states, and information is processed using `unitary operations <https://en.wikipedia.org/wiki/Unitary_operator>`_.
Feels strange to change a sentence that says "If I (Juan Miguel) ..." :laughing:

2023-09-08 14:04 UTC, KetpuntoG commented on demonstrations/tutorial_lcu_blockencoding.py
> +The concept of an LCU is straightforward --- it’s already explained in the name: we
"a" or just remove it:

```suggestion
The concept of LCU is straightforward --- it’s already explained in the name: we
```

2023-09-08 14:05 UTC, KetpuntoG commented on demonstrations/tutorial_lcu_blockencoding.py
> +The concept of an LCU is straightforward --- it’s already explained in the name: we
Since the complete name is important , I would put it again

2023-09-08 14:09 UTC, KetpuntoG commented on demonstrations/tutorial_lcu_blockencoding.py
> +# the Walsh-Hadamard transform, as described `here <https://quantumcomputing.stackexchange.com/questions/31788/how-to-write-the-iswap-unitary-as-a-linear-combination-of-tensor-products-betw/31790#317
Maybe another source?

2023-09-08 14:13 UTC, KetpuntoG commented on demonstrations/tutorial_lcu_blockencoding.py
> +# .. math:: PREP|0\rangle = \sum_k \sqrt{\frac{|\alpha|_k}{\lambda}}|k\rangle,
I have seen that you have taken the notation of the summations from k = 1 to N. I would suggest changing to k = 0 to N-1. This here is the first reason. Since in the way you propose now, you would be storing the first element in the |1>, instead of |0>.

2023-09-08 14:16 UTC, KetpuntoG commented on demonstrations/tutorial_lcu_blockencoding.py
> +# .. math:: PREP|0\rangle = \sum_k \sqrt{\frac{|\alpha|_k}{\lambda}}|k\rangle,
On the other hand, this formula is only valid if the coefficients are positive real. It seems that putting the absolute value solves it but you are forgotten the sign then. Somehow it should be commented that they are positive, or that the phases should be introduced in the operators.

2023-09-08 14:23 UTC, KetpuntoG commented on demonstrations/tutorial_lcu_blockencoding.py
> +# The final trick is to combine PREP and SEL to make :math:`A` appear 🪄:
I'm not sure if it's worth writing this paragraph. The notation is confusing. Maybe it is better to explain it directly after the circuit

2023-09-08 14:26 UTC, KetpuntoG commented on demonstrations/tutorial_lcu_blockencoding.py
> +# Prepare circuits can be constructed using the :func:`~.pennylane.StatePrep` operation, which takes
I would suggest use the doc class:

:class:\`~.Prepare\`

2023-09-08 14:32 UTC, KetpuntoG commented on demonstrations/tutorial_lcu_blockencoding.py
> +def sel_circuit(state):
"State" seems confusing to me here. Perhaps simply "n" following the BasisState documentation would be better.

2023-09-08 14:38 UTC, KetpuntoG commented on demonstrations/tutorial_lcu_blockencoding.py
> +@qml.qnode(dev2)
It does not affect the demo but I put

@qml.compile()

because I wanted to plot it and it doesn't work

2023-09-08 14:41 UTC, KetpuntoG commented on demonstrations/tutorial_lcu_blockencoding.py
> +##############################################################################
It seems it is not correct 🤔 

<img width="440" alt="Captura de pantalla 2023-09-08 a las 10 40 57" src="https://github.com/PennyLaneAI/qml/assets/65235481/5d83cf86-87b6-41db-a202-0f6330519b59">

2023-09-08 14:44 UTC, KetpuntoG commented on demonstrations/tutorial_lcu_blockencoding.py
> +# The :class:`.~pennylane.QSVT` uses these as input to build the full algorithm.
:class:\`~.QSVT\` 

:class:\`~.PCPhase\`

should work

2023-09-08 14:48 UTC, KetpuntoG commented on demonstrations/tutorial_lcu_blockencoding.py
> +                               qml.adjoint(qml.StatePrep(alphas, wires=0)))
In pennylane it is very dangerous to do this. Calling operators within a qnode and then using them. This will cause things to appear in the queue that you didn't count on:

<img width="361" alt="Captura de pantalla 2023-09-08 a las 10 48 02" src="https://github.com/PennyLaneAI/qml/assets/65235481/bb431fc7-bff3-4200-854d-de0be2945c8e">

If you plot it, an extra Select will appear (or at least I think it should not be there)

2023-09-08 14:51 UTC, KetpuntoG commented on demonstrations/tutorial_lcu_blockencoding.py
> +print(out_matrix(np.pi / 2))
Same feeling here. It was not clear to me how this applied to QSVT

2023-09-08 19:42 UTC, DSGuala commented on demonstrations/tutorial_lcu_blockencoding.py
> +# the Walsh-Hadamard transform, as described `here <https://quantumcomputing.stackexchange.com/questions/31788/how-to-write-the-iswap-unitary-as-a-linear-combination-of-tensor-products-betw/31790#317
We can change to the wikipedia link: https://en.wikipedia.org/wiki/Hadamard_transform

2023-09-11 18:37 UTC, KetpuntoG commented on demonstrations/tutorial_lcu_blockencoding.py
> +                               qml.adjoint(qml.StatePrep(alphas, wires=0)))
Let's avoid the user having to stop the tape as this is not well known. If you remove the `.decompose()`, you can remove the "stop recording" too

2023-09-11 20:12 UTC, DSGuala commented on demonstrations/tutorial_lcu_blockencoding.py
> +                               qml.adjoint(qml.StatePrep(alphas, wires=0)))
Unfortunately, we can't remove the decomposition. :(
This is because of a bug in `Select` which is getting fixed in the next release.

2023-10-11 19:01 UTC, DSGuala commented on demonstrations/tutorial_lcu_blockencoding.py
> +If I (Juan Miguel) had to summarize quantum computing in one sentence, it would be this: information is
Not sure how to address this. We could switch to "If we had to.." and "Our colleague once told us..."
But I'm also okay keeping it this way

2023-10-13 16:52 UTC, soranjh commented on demonstrations/tutorial_lcu_blockencoding.py
> +If I (Juan Miguel) had to summarize quantum computing in one sentence, it would be this: information is
Let's keep this way.

2023-10-17 16:36 UTC, Jaybsoni approved these changes
Looks good, two small suggestions

2023-10-17 17:50 UTC, DSGuala approved these changes
Looks good to me. I just left one suggestion to consider.

2023-10-19 11:27 UTC, ikurecic reviewed
Looks nice! :)
I have some minor comments/suggestions and some possible glossary terms @KetpuntoG might want to get made to replace the Wikipedia links.

2023-10-19 11:27 UTC, ikurecic commented on demonstrations/tutorial_lcu_blockencoding.py
> +# the `Walsh-Hadamard transform <https://en.wikipedia.org/wiki/Hadamard_transform>`_,
@KetpuntoG Another opportunity for Ben to make a glossary page. We also recently had a user question about this — I don't think he actually made it, though?

2023-10-19 11:27 UTC, ikurecic commented on demonstrations/tutorial_lcu_blockencoding.py
> +# but the cost still scales as ~ :math:`O(n 4^n)` for :math:`n` qubits. Be careful.
```suggestion
# but the cost still scales as ~ :math:`O(n 4^n)` for :math:`n` qubits, so be careful.
```
To make it sound less ominous. 😅

2023-10-19 11:27 UTC, ikurecic commented on demonstrations/tutorial_lcu_blockencoding.py
> +# and molecular Hamiltonians using the `Jordan-Wigner transformation <https://en.wikipedia.org/wiki/Jordan%E2%80%93Wigner_transformation>`_.
@KetpuntoG J–W is an easy glossary page.

2023-10-19 11:27 UTC, ikurecic commented on demonstrations/tutorial_lcu_blockencoding.py
> +#   * :math:`\lambda` is a normalization constant, defined as :math:`\lambda = \sum_k |\alpha_k|`.
I'd rather have the λ definition _before_ PREP/SEL are introduced.

2023-10-19 11:27 UTC, ikurecic commented on demonstrations/tutorial_lcu_blockencoding.py
> +# .. math:: \langle 0| \text{PREP}^\dagger \cdot \text{SEL} \cdot \text{PREP} |0\rangle|\psi\rangle = A/\lambda |\psi\rangle.
```suggestion
# .. math:: \langle 0| \text{PREP}^\dagger \cdot \text{SEL} \cdot \text{PREP} |0\rangle|\psi\rangle = \frac{A}{\lambda} |\psi\rangle.
```
For consistency.

2023-10-19 11:27 UTC, ikurecic commented on demonstrations/tutorial_lcu_blockencoding.py
> +# .. math:: U = \text{PREP}^\dagger \cdot \text{SEL} \cdot \text{PREP},
```suggestion
# .. math:: U = \text{PREP}^\dagger \cdot \text{SEL} \cdot \text{PREP}
```

2023-10-19 11:27 UTC, ikurecic commented on demonstrations/tutorial_lcu_blockencoding.py
> +# and `select <https://docs.pennylane.ai/en/stable/code/api/pennylane.Select.html>`_
```suggestion
# PennyLane supports the direct implementation of `prepare <https://docs.pennylane.ai/en/stable/code/api/pennylane.StatePrep.html>`_
# and `select <https://docs.pennylane.ai/en/stable/code/api/pennylane.Select.html>`_
```

2023-10-19 11:27 UTC, ikurecic commented on demonstrations/tutorial_lcu_blockencoding.py
> +# Prepare circuits can be constructed using the :class:`~.pennylane.StatePrep` operation, which takes
Same issue as before with the inline code link: it's not visible. It might be helpful to either make it plaintext or separate the link to the docs with brackets.

2023-10-19 11:27 UTC, ikurecic commented on demonstrations/tutorial_lcu_blockencoding.py
> +# from the unitaries. Since :func:`~.pennylane.pauli_decompose` uses a canonical wire ordering, we
Inline code links not obvious.

2023-10-19 11:27 UTC, ikurecic commented on demonstrations/tutorial_lcu_blockencoding.py
> +# relabeling wires 0 --> 1, and 1 --> 2
```suggestion
# relabeling wires: 0 → 1 and 1 → 2
```

2023-10-19 11:27 UTC, ikurecic commented on demonstrations/tutorial_lcu_blockencoding.py
> +print(qml.draw(sel_circuit)([0]))
Perhaps a pretier option? 😁
![image](https://github.com/PennyLaneAI/qml/assets/4939555/f97e0ae7-6f8e-4815-aaec-a2c5fdd1338c)

2023-10-19 11:27 UTC, ikurecic commented on demonstrations/tutorial_lcu_blockencoding.py
> +#      | \phi \rangle\langle \phi | = \frac{1}{2} \cdot (\mathbb{I}) + \frac{1}{2} \cdot (2 \cdot | \phi \rangle\langle \phi | - \mathbb{I})
```suggestion
#      | \phi \rangle\langle \phi | = \frac{1}{2} \cdot \mathbb{I} + \frac{1}{2} \cdot (2 \cdot | \phi \rangle\langle \phi | - \mathbb{I})
```

2023-10-19 11:27 UTC, ikurecic commented on demonstrations/tutorial_lcu_blockencoding.py
> +# master. PennyLane is equipped with the tools to help you get there.
```suggestion
# master, and PennyLane is equipped with the tools to help you get there.
```

2023-10-19 14:37 UTC, soranjh commented on demonstrations/tutorial_lcu_blockencoding.py
> +question: Quantum computers can implement products of unitaries --- after all
I agree but removing `:` breaks the natural flow of the text. What do you think?

2023-10-19 14:38 UTC, soranjh commented on demonstrations/tutorial_lcu_blockencoding.py
> +# relabeling wires 0 --> 1, and 1 --> 2
Replaced with →

2023-10-20 01:22 UTC, soranjh commented on demonstrations/tutorial_lcu_blockencoding.py
> +:func:`~.pennylane.pauli_decompose` function. The coefficients :math:`\alpha_k` and the unitaries
Talked with @KetpuntoG abiut it, this seems to be the common style.

2023-10-20 01:22 UTC, soranjh commented on demonstrations/tutorial_lcu_blockencoding.py
> +# Prepare circuits can be constructed using the :class:`~.pennylane.StatePrep` operation, which takes
Talked with @KetpuntoG abiut it, this seems to be the common style.

2023-10-20 01:22 UTC, soranjh commented on demonstrations/tutorial_lcu_blockencoding.py
> +# from the unitaries. Since :func:`~.pennylane.pauli_decompose` uses a canonical wire ordering, we
Talked with @KetpuntoG abiut it, this seems to be the common style.

2023-10-20 14:26 UTC, ikurecic approved these changes
Nice, looks great! :)

2023-10-20 17:20 UTC, KetpuntoG commented on demonstrations/tutorial_lcu_blockencoding.py
> +# .. math:: \text{PREP}|0\rangle = \sum_k \sqrt{\frac{|\alpha|_k}{\lambda}}|k\rangle,
```suggestion
# .. math:: \text{PREP}|0\rangle = \sum_k \sqrt{\frac{|\alpha_k|}{\lambda}}|k\rangle,
```

2023-10-20 17:20 UTC, KetpuntoG commented on demonstrations/tutorial_lcu_blockencoding.py
> +dev2 = qml.device("default.qubit", wires=3)
```suggestion
import matplotlib.pyplot as plt

dev2 = qml.device("default.qubit", wires=3)
```

2023-10-20 17:20 UTC, KetpuntoG commented on demonstrations/tutorial_lcu_blockencoding.py
> +qml.draw_mpl(sel_circuit, style='pennylane')([0])
```suggestion
qml.draw_mpl(sel_circuit, style='pennylane')([0])
plt.show()
```

This will remove the unwanted output from the cell

2023-10-20 17:20 UTC, KetpuntoG commented on demonstrations/tutorial_lcu_blockencoding.py
> +_linear combinations of unitaries_, or LCUs for short. You will also understand how to
```suggestion
*linear combinations of unitaries*, or LCUs for short. You will also understand how to
```

2023-10-20 17:20 UTC, KetpuntoG commented on demonstrations/tutorial_lcu_blockencoding.metadata.json
> +    "dateOfLastModification": "2023-08-31T00:00:00+00:00",
```suggestion
    "dateOfPublication": "2023-10-20T00:00:00+00:00",
    "dateOfLastModification": "2023-10-20T00:00:00+00:00",
```

2023-10-23 20:02 UTC, DSGuala approved these changes
Found a few typos. Otherwise good to go.

2023-10-23 20:02 UTC, DSGuala commented on demonstrations/tutorial_lcu_blockencoding.py
> +decompose operators into a weighted sum of unitaries. Mathematically, this means expresssing
```suggestion
decompose operators into a weighted sum of unitaries. Mathematically, this means expressing
```

2023-10-23 20:02 UTC, DSGuala commented on demonstrations/tutorial_lcu_blockencoding.py
> +# input is :math:`|0\rangle`. The output expecation values correspond to these states:
```suggestion
# input is :math:`|0\rangle`. The output expectation values correspond to these states:
```

2023-10-26 00:34 UTC, merged