Not numpy from pennylane getting started
PennyLaneAI/qml pull request #932
Opened 2023-09-20 15:12 UTC by KetpuntoG

In this PR I will replace "numpy from pennylane" with other alternatives. 
(I had a meeting with Tom to decide what to use in each case)

2023-11-30 19:48 UTC, DanielNino27 requested changes
Looks good - does the 'Last updated' date need to be changed in the metadata? I noticed only the noisy circuits one is updated.

2023-12-01 04:20 UTC, josh146 commented on demonstrations/adjoint_diff_benchmarking.py
> -from pennylane import numpy as np
@KetpuntoG I would be careful with this one, and get @albi3ro to have a look to see if this changes the benchmarking results

2023-12-01 04:20 UTC, josh146 commented on demonstrations/adjoint_diff_benchmarking.py
> -from pennylane import numpy as np
Similar for the tutorial on adjoint below :)

2023-12-01 04:21 UTC, josh146 commented on demonstrations/tutorial_backprop.py
> -print(qml.gradients.param_shift(circuit)(params))
How come this was removed?

2023-12-01 04:23 UTC, josh146 commented on demonstrations/tutorial_vqe.py
> +# The library ``jaxopt`` offers different `optimizers <https://jaxopt.github.io/stable/`__.
@KetpuntoG I recommend perhaps using optax here instead, it seems to be better maintained

2023-12-04 15:14 UTC, KetpuntoG commented on demonstrations/tutorial_adjoint_diff.py
> +# PennyLane al# Backpropagation demonstrates decent time scaling, but requires more and more
Thanks Daniel! It seems I modified this paragraph accidentally

2023-12-04 15:24 UTC, KetpuntoG commented on demonstrations/tutorial_backprop.py
> -print(qml.gradients.param_shift(circuit)(params))
I considered this to be autograd, added!

2023-12-05 18:00 UTC, albi3ro commented on demonstrations/adjoint_diff_benchmarking.py
> -from pennylane import numpy as np
Should be ok as long as the benchmarks are re-run and the image updated.

2023-12-06 17:40 UTC, KetpuntoG commented on demonstrations/tutorial_qubit_rotation.py
>  #     * combine quantum functions (evaluated on quantum hardware/simulators) and
updated :)

2023-12-06 17:44 UTC, KetpuntoG commented on demonstrations/tutorial_backprop.py
>  fig, ax = plt.subplots(1, 1, figsize=(6, 4))
Contrasted with Christina, the benchmarks are not significantly affected. There is still some discussion but for now it can be left as it is

2023-12-06 17:58 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_backprop.py
> +# In this demo, we will use jax interface.
Should Jax be caplitalized or not?

2023-12-06 18:01 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_phase_kickback.py
Above it says import the necessary PennyLane libraries. Should it just be "libraries?"

2023-12-06 18:19 UTC, josh146 commented on demonstrations/tutorial_backprop.py
> +# In this demo, we will use jax interface.
It should be JAX everywhere

2023-12-07 21:47 UTC, alvaro-at-xanadu approved these changes
LGTM

2023-12-08 15:24 UTC, trbromley commented on demonstrations/tutorial_backprop.py
> +jax.config.update('jax_enable_x64', True)
Do we need both of these?

2023-12-08 15:24 UTC, trbromley commented on demonstrations/tutorial_backprop.py
> +jax.config.update('jax_enable_x64', True)
Maybe the first is just to remove a JAX warning? For float32 vs 64 - this is typically a worry with finite-diff, but I think the float32 default should be ok here.

2023-12-08 15:24 UTC, trbromley commented on demonstrations/tutorial_gaussian_transformation.py
> +# by Jax:
```suggestion
# by JAX:
```

2023-12-08 15:24 UTC, trbromley commented on demonstrations/tutorial_qubit_rotation.py
> +#     the power of NumPy with PennyLane and Jax:
Could alternatively remove this box

2023-12-08 15:24 UTC, trbromley commented on demonstrations/tutorial_qubit_rotation.py
> +#     In PennyLane, a device could be a hardware device (take a look at our `plugins <https://pennylane.ai/plugins/#plugins>`_), or a software simulator (such as Strawberry Fields, via the
Could we mention lightning instead of SF?

2024-01-02 15:22 UTC, merged