[WIP] OQC Lucy pulse demo
PennyLaneAI/qml pull request #939
Opened 2023-09-26 11:16 UTC by Qottmann

Continuing https://github.com/PennyLaneAI/qml/pull/892

OQC hardware control demo 

Content:
- [ ] Intro
- [ ] Single qubit pulse physics
- [x] Calibration
- [ ] Effective generator method
- [ ] VQE

2023-10-04 14:19 UTC, Qottmann commented
Updated the demo to the point where we have data right now. There are two blockers currently prohibiting moving forward with this.

- [ ] OQC bug on setting the phase does not actually work (see last plot). Waiting for feedback from aws / OQC to look for the bug on their side
- [ ] OQC device access needs to be released before demo. Currently working on `oqc_main` branch https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/pull/191

2023-10-23 08:30 UTC, Qottmann commented on demonstrations/oqc_pulse.py
> +# the last paragraph of the transmon physics section above.
I dont understand why this renders like that: 
![Uploading image.png…]()

2023-10-24 21:49 UTC, DanielNino27 requested changes
Just a couple of changes requested... :D

2023-10-24 21:49 UTC, DanielNino27 commented on demonstrations/oqc_pulse.py
> +Transmon Physics
Good to stay consistent in the choice of title case vs. sentence case in section titles. The next section title uses sentence case and the section after that (X-Y Rotations) goes back to title case.

2023-10-24 21:49 UTC, DanielNino27 commented on demonstrations/oqc_pulse.py
> +physical device in ``PennyLane`` via ``AWS Braket`` on OQC's Lucy quantum computer. In this demo,
OQC as an acronym has not been defined yet - the abstract is a good place to do that and then the acronym can be used for the remainder of the demo

2023-10-24 21:49 UTC, DanielNino27 commented on demonstrations/oqc_pulse.py
> +Oxford Quantum Circuit's Lucy is a quantum computer with 8 superconducting transmon qubits based on the coaxmon design [#Rahamim]_.
```suggestion
Oxford Quantum Circuit's Lucy is a quantum computer with 8 superconducting transmon qubits based on the Coaxmon design [#Rahamim]_.
```

2023-10-24 21:49 UTC, DanielNino27 commented on demonstrations/oqc_pulse.py
> +In order to control a transmon qubit, it is driven by an electromagnetic microwave pulse. This can be modeled by the Hamiltonian
'electromagnetic' seems redundant here since a microwave pulse is an electromagnetic pulse.

2023-10-24 21:49 UTC, DanielNino27 commented on demonstrations/oqc_pulse.py
> +of the driven qubit with qubit frequency :math:`\omega_q`, drive amplitude :math:`\Omega(t)`, drive frequency :math:`\nu_q` and phase :math:`\phi`.
Z_q and Y_q are not defined (it's clear from context what they might be, but I find it's always better to be explicit).

2023-10-24 21:49 UTC, DanielNino27 commented on demonstrations/oqc_pulse.py
> +The first term leads to a constant precession around the Z axis on the Bloch sphere, whereas the second term introduces
```suggestion
The first term leads to a constant precession around the Z-axis on the Bloch sphere, whereas the second term introduces
```

2023-10-24 21:49 UTC, DanielNino27 commented on demonstrations/oqc_pulse.py
> +where we evolve the state in the Bloch sphere from :math:`|0\rangle` with a constant pulse of :math:`\Omega(t) = 2 \pi \text{GHz}`
add a space between pi and GHz

2023-10-24 21:49 UTC, DanielNino27 commented on demonstrations/oqc_pulse.py
> +for :math:`1\text{ns}`. We choose :math:`\omega = 5 \times 2\pi \text{GHz}` as the drive and qubit frequency.
add space between quantity and units (ns and GHz)

2023-10-24 21:49 UTC, DanielNino27 commented on demonstrations/oqc_pulse.py
> +# We looked at transmon physics in the so-called lab frame. Another common way of understanding transmon physics
```suggestion
# So far, We have looked at transmon physics in the so-called lab frame. Another common way of understanding transmon physics
```

2023-10-24 21:49 UTC, DanielNino27 commented on demonstrations/oqc_pulse.py
> +# is done via transforming the drive Hamiltonian to the so-called qubit frame that is rotating with the qubit-frequency.
```suggestion
# is done via transforming the drive Hamiltonian to the so-called qubit frame that is rotating at the qubit frequency.
```

2023-10-24 21:49 UTC, DanielNino27 commented on demonstrations/oqc_pulse.py
> +# For a detailed derivation of the qubit frame Hamiltonian above, we refer to reference [#Krantz]_, section IV, D1 (eq. (79) onwards therein).
```suggestion
# For a detailed derivation of the qubit-frame Hamiltonian above, we refer to reference [#Krantz]_, section IV, D1 (eq. (79) onwards therein).
```

2023-10-24 21:49 UTC, DanielNino27 commented on demonstrations/oqc_pulse.py
> +# The attenuation :math:`\xi` accounts for all losses between the arbitrary waveform generator (AWG) that outputs the signal in
Two different greek letters have been used to refer to attenuation (nu and xi) - it would be good to clarify this.

2023-10-24 21:49 UTC, DanielNino27 commented on demonstrations/oqc_pulse.py
> +# We again define the drive Hamiltonian in ``PennyLane``, where we control the constant amplitude and phase, set by the callable
I don't think PennyLane needs to be in a different font (or font that is used for in-text code).

2023-10-24 21:49 UTC, DanielNino27 commented on demonstrations/oqc_pulse.py
> +# We can estimate it by ratio of the measured Rabi frequency for simulation and device execution.
What's "it" referring to? From the context, it would be the attenuation, but better to have it more clear: 

"We can estimate the attenuation by ..."

2023-10-24 21:49 UTC, DanielNino27 commented on demonstrations/oqc_pulse.py
> +# We can estimate it by ratio of the measured Rabi frequency for simulation and device execution.
```suggestion
# We can estimate it by the ratio of the measured Rabi frequency for the simulation and device execution.
```

2023-10-24 21:49 UTC, DanielNino27 commented on demonstrations/oqc_pulse.py
> +# while changing the phase :math:`\phi` at a fixed duration of :math:`15 \text{ns}` and output amplitude of :math:`0.3` (arbitrary unit :math:`\in [0, 1]`).
add space between quantity and units (15 and ns)

2023-10-24 21:49 UTC, DanielNino27 commented on demonstrations/oqc_pulse.py
> +# while changing the phase :math:`\phi` at a fixed duration of :math:`15 \text{ns}` and output amplitude of :math:`0.3` (arbitrary unit :math:`\in [0, 1]`).
```suggestion
# while changing the phase :math:`\phi` at a fixed duration of :math:`15 \text{ns}` and output amplitude of :math:`0.3` (arbitrary units :math:`\in [0, 1]`).
```

2023-10-24 21:49 UTC, DanielNino27 commented on demonstrations/oqc_pulse.py
> +# Overall, We have demonstrated the basic working principles of transmon qubit devices and have shown how one can perform such hardware-level manipulations
```suggestion
# Overall, we have demonstrated the basic working principles of transmon qubit devices and have shown how one can perform such hardware-level manipulations
```

2023-10-24 21:49 UTC, DanielNino27 commented on demonstrations/oqc_pulse.py
> +# on a physical device in ``PennyLane``. Stay tuned for more content on differentiating pulse circuits natively on hardware in a future demo on ``ODEgen`` [#Kottmann]_.
Again, not sure if PennyLane needs to be in a  different font - have not seen that in other demos.

2023-10-24 21:49 UTC, DanielNino27 commented on demonstrations/oqc_pulse/calibration2.png
change y-axis range to be the same in both graphs (right now, the OQC one goes from -1 to 1, and the simulation goes from -0.75 to 1)

2023-10-24 21:49 UTC, DanielNino27 commented on demonstrations/oqc_pulse/qubit_rotation2.png
If it does not mess up the rendering, make the vertical axis the same as the one in qubit_rotation.png above (to change upper limit to 1, instead of 0.75)

2023-10-25 10:28 UTC, Qottmann commented on demonstrations/oqc_pulse.py
> +# For a detailed derivation of the qubit frame Hamiltonian above, we refer to reference [#Krantz]_, section IV, D1 (eq. (79) onwards therein).
Hm I consistently used qubit frame and lab frame, wouldnt change that to qubit-frame and lab-frame. I think that spelling is pretty standard: https://en.wikipedia.org/wiki/Local_reference_frame

2023-10-25 10:29 UTC, Qottmann commented on demonstrations/oqc_pulse.py
> +# The attenuation :math:`\xi` accounts for all losses between the arbitrary waveform generator (AWG) that outputs the signal in
Yep, thanks! Good catch, missed that one!

2023-10-25 11:12 UTC, Qottmann commented on demonstrations/oqc_pulse.py
> +# We can estimate it by ratio of the measured Rabi frequency for simulation and device execution.
corrected 🙂

2023-10-25 11:14 UTC, Qottmann commented on demonstrations/oqc_pulse.py
> +# on a physical device in ``PennyLane``. Stay tuned for more content on differentiating pulse circuits natively on hardware in a future demo on ``ODEgen`` [#Kottmann]_.
Yep, I corrected them throughout now :)

2023-10-25 11:14 UTC, Qottmann commented on demonstrations/oqc_pulse/calibration2.png
good point! Corrected ✅

2023-10-25 11:19 UTC, Qottmann commented on demonstrations/oqc_pulse/qubit_rotation2.png
Done 🙂

2023-10-25 12:08 UTC, Qottmann commented
Thanks for the detailed review @DanielNino27 🙂 
I implemented your suggestions ✅, let me know if there is anything else!

2023-10-25 14:11 UTC, DanielNino27 commented on demonstrations/oqc_pulse.py
> +# For a detailed derivation of the qubit frame Hamiltonian above, we refer to reference [#Krantz]_, section IV, D1 (eq. (79) onwards therein).
in line 388 below, you have it as  "qubit-frame", so then the comment would be more about consistency.

2023-10-25 14:29 UTC, Qottmann commented on demonstrations/oqc_pulse.py
> +# For a detailed derivation of the qubit frame Hamiltonian above, we refer to reference [#Krantz]_, section IV, D1 (eq. (79) onwards therein).
Yep that line has been updated already 🙂

2023-10-25 14:52 UTC, DanielNino27 approved these changes
Looks good!

2023-10-25 15:38 UTC, alvaro-at-xanadu requested changes
I think this is a great demo! 🚀 It makes the concepts easy to understand. Aside from some copy suggestions to make the reading flow a bit better, these are a few high-level comments:

- We could use some comments in the code to explain what is going on. Not a lot are needed, but it'd be great to see the steps that are being followed, especially in long blocks of code.
- There are some rendering issues, and I think we'll need to change stuff here and there making sure our sphinx syntax is 100% correct. Sometimes these errors are dragged from several paragraphs before 😓 
Looking forward to seeing the demo in its final form 🏎️ !

2023-10-25 15:38 UTC, alvaro-at-xanadu commented on demonstrations/oqc_pulse.py
> +# is done via transforming the drive Hamiltonian to the so-called qubit frame that is rotating at the qubit frequency.
```suggestion
# is via the Hamiltonian expressed in the `qubit frame,` which rotates at the qubit frequency.
```

2023-10-25 15:38 UTC, alvaro-at-xanadu commented on demonstrations/oqc_pulse.py
> +# This is done via the unitary transformation
```suggestion
# We can transform between frames via the unitary transformation
```

2023-10-25 15:38 UTC, alvaro-at-xanadu commented on demonstrations/oqc_pulse.py
> +# For a detailed derivation of the qubit frame Hamiltonian above, we refer to reference [#Krantz]_, section IV, D1 (eq. (79) onwards therein).
```suggestion
# For a detailed derivation of the qubit frame Hamiltonian above, see reference [#Krantz]_, section IV, D1 (eq. (79) onwards).
```

2023-10-25 15:38 UTC, alvaro-at-xanadu commented on demonstrations/oqc_pulse.py
> +# that we set on the device, :math:`V_0`, and the actual voltage the superconducting qubit receives, :math:`V_\text{device} = \xi V_0`.
```suggestion
#  and the actual voltage :math:`V_\text{device} = \xi V_0` that the the superconducting qubit receives
```

2023-10-25 15:38 UTC, alvaro-at-xanadu commented on demonstrations/oqc_pulse.py
> +def fit_sinus(x, y, initial_guess=[1., 0.1, 1]):
fit_sine might be a better name. "sinus" is not a word in math.

2023-10-25 15:38 UTC, alvaro-at-xanadu commented on demonstrations/oqc_pulse.py
> +    """[A, omega, phi]"""
```suggestion
    """initial guess = [A, omega, phi]"""
```

2023-10-25 15:38 UTC, alvaro-at-xanadu commented on demonstrations/oqc_pulse.py
> +    """[A, omega, phi]"""
Is this what you mean? 🤔

2023-10-25 15:38 UTC, alvaro-at-xanadu commented on demonstrations/oqc_pulse.py
> +# In particular, we see a match in both Rabi frequencies. The error in terms of the magnitude of the Rabi oscillation
Super cool! 🤩

2023-10-25 15:38 UTC, alvaro-at-xanadu commented on demonstrations/oqc_pulse.py
> +# may be due to different sources. For one, the qubit has a read-out fidelity of :math:`93\%`, according to the vendor.
```suggestion
# may be due to different sources. For one, the qubit has a readout fidelity of :math:`93\%`, according to the vendor. 
```

2023-10-25 15:38 UTC, alvaro-at-xanadu commented on demonstrations/oqc_pulse.py
> +# Another possible source is classical and quantum cross-talk not considered in our model. We suspect the main source
```suggestion
# Another possible source is that classical and quantum crosstalk are not considered in our model. We suspect the main source
```

2023-10-25 15:38 UTC, alvaro-at-xanadu commented on demonstrations/oqc_pulse.py
> +# for error beyond read-out fidelity to come from excitations to higher levels, caused by strong amplitudes and rapid
```suggestion
# for error beyond readout fidelity to come from excitations to higher levels, caused by strong amplitudes and rapid
```

2023-10-25 15:38 UTC, alvaro-at-xanadu commented on demonstrations/oqc_pulse.py
> +# ============================
```suggestion
# --------------------------------------
```

2023-10-25 15:38 UTC, alvaro-at-xanadu commented on demonstrations/oqc_pulse.py
> +# Another possible source is classical and quantum cross-talk not considered in our model. We suspect the main source
Idk if this is what you mean. Is it only some of the crosstalk that isn't allowed. This sentence needs a bit of rephrasing though 🤔

2023-10-25 15:38 UTC, alvaro-at-xanadu commented on demonstrations/oqc_pulse.py
> +# =============
```suggestion
# --------------------
```

2023-10-25 15:38 UTC, alvaro-at-xanadu commented on demonstrations/oqc_pulse.py
> +# We now want to experiment with performing X-Y-rotations by setting the phase.
```suggestion
# We now want to experiment with performing X- and Y-rotations by setting the phase.
```

2023-10-25 15:38 UTC, alvaro-at-xanadu commented on demonstrations/oqc_pulse.py
> +# For that, we compute expectation values of :math:`\langle X \rangle`, :math:`\langle Y \rangle`, and :math:`\langle Z \rangle`
```suggestion
# For that, we compute the expectation values of :math:`\langle X \rangle`, :math:`\langle Y \rangle`, and :math:`\langle Z \rangle`
```

2023-10-25 15:38 UTC, alvaro-at-xanadu commented on demonstrations/oqc_pulse.py
> +# while changing the phase :math:`\phi` at a fixed duration of :math:`15 \text{ ns}` and output amplitude of :math:`0.3` (arbitrary unit :math:`\in [0, 1]`).
```suggestion
# for variable phase :math:`\phi` and fixed duration of :math:`15 \text{ ns}` and output amplitude of :math:`0.3` (arbitrary unit :math:`\in [0, 1]`).
```

2023-10-25 15:38 UTC, alvaro-at-xanadu commented on demonstrations/oqc_pulse.py
> +# As expected, we see a constant :math:`\langle Z \rangle` contribution, as changing :math:`\phi` delays the precession around the Z-axis
This is not rendering properly. We need to look out for sphinx syntax error. Maybe @KetpuntoG has more experience finding these things.

2023-10-25 15:38 UTC, alvaro-at-xanadu commented on demonstrations/oqc_pulse.py
> +#
Conclusion header also not rendering

2023-10-25 15:38 UTC, alvaro-at-xanadu commented on demonstrations/oqc_pulse.py
> +# ==========
```suggestion
# ---------------
```

2023-10-25 15:38 UTC, alvaro-at-xanadu commented on demonstrations/oqc_pulse.py
> +#
Again let's avoid making promises!

2023-10-25 15:38 UTC, alvaro-at-xanadu commented on demonstrations/oqc_pulse.py
> +#
Not rendering either

2023-10-25 15:42 UTC, Qottmann commented on demonstrations/oqc_pulse.py
> +
I think this was an old version, it should look like this on the latest version: 
![image](https://github.com/PennyLaneAI/qml/assets/43949391/c3619eef-7349-45b7-a7f1-9a618623232d)

Can you check in a new browser / with deleted cookies to confirm?

2023-10-25 15:49 UTC, Qottmann commented on demonstrations/oqc_pulse.py
> +also have the possibility to access _Lucy_ by Oxford Quantum Computing (OQC), a 8-qubit superconducting quantum computer with a ring-like connectivity.
Why is "Additionally" redundant? Updating the rest ✅

2023-10-25 15:57 UTC, Qottmann commented on demonstrations/oqc_pulse.py
> +will discuss in detail in a future demo.
The contents of that one is already generated and the release already planned for end of November, is that low risk enough to tease at already here?

2023-10-25 16:03 UTC, Qottmann commented on demonstrations/oqc_pulse.py
> +The operators :math:`\{X_q, Y_q, Z_q\}` refer to the single qubit Pauli operators acting on qubit :math:`q`.
Every qubit has a different resonance frequency $\omega_q$ and, accordingly, a different drive frequency $\nu_q$. Will try to clarify if that is not clear 👍

2023-10-25 16:10 UTC, Qottmann commented on demonstrations/oqc_pulse.py
> +for :math:`1 \text{ ns}`. We choose :math:`\omega = 5 \times 2\pi \text{ GHz}` as the drive and qubit frequency.
good idea! added it in parenthesis

2023-10-25 16:26 UTC, Qottmann commented on demonstrations/oqc_pulse.py
> +# Another possible source is classical and quantum cross-talk not considered in our model. We suspect the main source
I made a small change to the sentence to make it more clear what is meant

2023-10-25 16:27 UTC, Qottmann commented on demonstrations/oqc_pulse.py
> +#
see above

2023-10-26 08:38 UTC, Qottmann commented on demonstrations/oqc_pulse.py
> +##############################################################################
The problem was the empty lines here? 😨

2023-10-26 08:39 UTC, Qottmann commented on demonstrations/oqc_pulse.py
> +
fixed :-)

2023-10-26 18:37 UTC, trbromley commented
I am assuming the URL when published will be https://pennylane.ai/qml/demos/oqc_pulse.html - please let me know if this changes!

2023-10-26 19:38 UTC, KetpuntoG commented
> I am assuming the URL when published will be https://pennylane.ai/qml/demos/oqc_pulse.html - please let me know if this changes!

That's correct :)
(not sure if html is necessary)

2023-10-26 19:38 UTC, KetpuntoG commented on demonstrations/oqc_pulse.py
> +##############################################################################
I think so 😅

2023-10-27 08:06 UTC, Qottmann commented
I made some minor polishment adjustments for best UX, where, in particular, I explain a little more in detail the code.
Further, all comments from the two reviews are addressed and implemented.
I am happy with the demo now, looks good to go if @alvaro-at-xanadu agrees and approves 👍

2023-10-27 13:47 UTC, KetpuntoG commented
Nice! Thanks @Qottmann :)
Could you change the name of the thumbnail following the standard naming in other demos? (check [this](https://github.com/PennyLaneAI/qml/blob/master/demonstrations/tutorial_intro_qsvt.metadata.json) metadata)
Also, I see there is not `large_thumbnail_` could you include it in ` /_static/large_thumbnails`? It should be the same as the other thumbnail but with blue background

2023-10-27 14:57 UTC, Qottmann commented
Done ✅ @KetpuntoG

2023-10-27 16:52 UTC, alvaro-at-xanadu approved these changes
Done and done! Agree, if the new demo is almost ready, then  we can promise. *However,* once that future demo is published, let's also make sure edit this one so that it links to it.

2023-10-27 17:36 UTC, merged