Initial Commit
PennyLaneAI/qml pull request #94
Opened 2020-05-24 00:11 UTC by Tstorwick

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Add a thumbnail link to your tutorial in `beginner.rst`, or if a
      QML implementation, in `implementations.rst`.

- [ ] All QML tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2020-05-24 11:20 UTC, josh146 commented
<h3>Website build</h3>
<strong>Commit:</strong> edd4206ac2d97bccc97b8515c6b5ab44d68330c6

<strong>Circle build number:</strong> 764

<strong>Built <code>demos</code> directory:</strong> <a href=https://764-214003948-gh.circle-artifacts.com/0/tmp/qml_demos.zip>https://764-214003948-gh.circle-artifacts.com/0/tmp/qml_demos.zip</a>

<strong>Backreferences zip:</strong> <a href=https://764-214003948-gh.circle-artifacts.com/0/tmp/qml_backreferences.zip>https://764-214003948-gh.circle-artifacts.com/0/tmp/qml_backreferences.zip</a>

<strong>Website zip:</strong> <a href=https://764-214003948-gh.circle-artifacts.com/0/tmp/qml_html.zip>https://764-214003948-gh.circle-artifacts.com/0/tmp/qml_html.zip</a>

<strong>Website url:</strong> <a href=https://764-214003948-gh.circle-artifacts.com/0/_build/html/index.html>https://764-214003948-gh.circle-artifacts.com/0/_build/html/index.html</a>

<em>Please double check the rendered website build to make sure everything is correct.</em>

2020-05-24 18:22 UTC, co9olguy commented
Hi @Tstorwick, thanks for the PR contribution! Looking forward to having a deeper look.

2020-05-31 18:53 UTC, Tstorwick commented
> Hi @Tstorwick, thanks for the PR contribution! Looking forward to having a deeper look.

No problem! Thanks for taking a look at it :)

2020-06-12 16:27 UTC, Tstorwick commented
@josh146 This new version still has the wrong incoding, but for the life of me i cant seem to fix it. I've tried even manually replacing the characters and it still doesnt work.

2020-06-23 15:03 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +# :math:`\theta`\ 's for each rotation
I like the look of θ’s, but probably best to say 'parameters' 😆 
```suggestion
# parameters for each rotation
```

2020-06-23 15:04 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +plt.show()
Visualization plots are really nice, and very effective!

2020-06-23 15:05 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +plt.show()
I suppose a big question I have is, are we solving the same problem when we switch between a global observable and a local observable? It might be the case that the problem can _only_ be formulated in terms of a global cost function!

2020-06-23 15:10 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +# landscape is :math:`(\pi,0)`, so lets use that.
For example, here the two optimization landscapes have identical local minima. I wonder if this is always guaranteed; can we construct a counterexample?

2020-06-23 15:10 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +# function and see how it performs.
This is a very effective way of showing the inability to train the system 😆

2020-06-23 15:14 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +# have we trained it?
When you say faithful, is this due to the local minima intersecting from the landscape plots, or via some other intuition/result?

2020-06-23 15:28 UTC, mariaschuld commented on demonstrations.rst
> +
I wonder why this entry is duplicated?

2020-06-23 15:29 UTC, mariaschuld commented on demonstrations/tutorial_local_cost_functions.py
> +algorithm.
That's a great explanation of barren plateaus @Tstorwick !

2020-06-23 16:12 UTC, mariaschuld commented on demonstrations/tutorial_local_cost_functions.py
> +# To start, lets look at the toy problem of learning the identity gate
```suggestion
# To start, lets look at the task of learning the identity gate
```

Better to avoid repetition of "problem"?

2020-06-23 21:10 UTC, trbromley commented on demonstrations.rst
> +    :tooltip: Local and global cost functions
```suggestion
    :tooltip: Understand the difference between local and global cost functions
```
The tooltips seem to typically be stated in an imperative style.

2020-06-23 21:13 UTC, trbromley commented on demonstrations.rst
> +    :figure: demonstrations/local_cost_functions/Cerezo_et_al_local_cost_functions.png
Is it ok to use this image here, since it's taken directly from the paper?
The other two plots in the tutorial look good:
![image](https://user-images.githubusercontent.com/49409390/85463574-cbe77980-b574-11ea-99ac-3702bdac6d92.png)

2020-06-23 21:16 UTC, trbromley commented on demonstrations/tutorial_local_cost_functions.py
> +Barren plateaus are large regions of the cost functions parameter space
```suggestion
Barren plateaus are large regions of the cost function's parameter space
```

2020-06-23 21:24 UTC, trbromley commented on demonstrations/tutorial_local_cost_functions.py
> +#    :width: 90%
It feels like this image is better suited earlier on, around the second paragraph where we're talking about literature.

It would also be good to:
- make the image a bit smaller, it is quite big on my screen and you can tell some blurriness/pixelation
- Give credit for the image

2020-06-23 21:26 UTC, trbromley commented on demonstrations/tutorial_local_cost_functions.py
> +# .. math:: C = 1-(P_{|0>})
Do we need the brackets in these equations?

2020-06-23 21:29 UTC, trbromley commented on demonstrations/tutorial_local_cost_functions.py
> +# .. math:: C_{L} = 1-(P_{|0>,1}).
It would be good to define P here, I was originally thinking of them as projectors but I think they are probabilities (maybe p could be lower case).

2020-06-23 21:29 UTC, trbromley commented on demonstrations/tutorial_local_cost_functions.py
> +# .. math:: C_{G} = 1-(P_{|0>})
```suggestion
# .. math:: C_{G} = 1-(P_{|00 \ldots 0\rangle})
```
This makes it look more multiqubit

2020-06-23 21:30 UTC, trbromley commented on demonstrations/tutorial_local_cost_functions.py
> +# .. math:: C_{L} = 1-(P_{|0>,1}).
```suggestion
# .. math:: C_{L} = 1-(P_{|0\rangle}).
```
Given the above change, we can probably drop the 1

2020-06-23 21:30 UTC, trbromley commented on demonstrations/tutorial_local_cost_functions.py
> +# To implement this, we will define a separate qnode for the local cost
Note this occurs a few times.

2020-06-23 21:32 UTC, trbromley commented on demonstrations/tutorial_local_cost_functions.py
> +    for i in range(wires):
```suggestion
```
Can probably skip this line.

2020-06-23 21:32 UTC, trbromley commented on demonstrations/tutorial_local_cost_functions.py
> +    for i in range(wires):
```suggestion
```

2020-06-23 21:41 UTC, trbromley commented on demonstrations/tutorial_local_cost_functions.py
> +# However, when we change to the local cost function, the cost lanscape
```suggestion
# However, when we change to the local cost function, the cost landscape
```

2020-06-23 21:42 UTC, trbromley commented on demonstrations/tutorial_local_cost_functions.py
> +# Those are some nice pictures, but how do they refect actual
```suggestion
# Those are some nice pictures, but how do they reflect actual
```

2020-06-23 21:43 UTC, trbromley commented on demonstrations/tutorial_local_cost_functions.py
> +# landscape is :math:`(\pi,0)`, so lets use that.
```suggestion
# landscape is :math:`(\pi,0)`, so let's use that.
```

2020-06-23 21:44 UTC, trbromley commented on demonstrations/tutorial_local_cost_functions.py
> +# landscape is :math:`(\pi,0)`, so lets use that.
Is it local minima or maxima? Looked like the highest point to me.

2020-06-23 21:46 UTC, trbromley commented on demonstrations/tutorial_local_cost_functions.py
> +rotations = [[3 for i in range(wires)], [0 for i in range(wires)]]
```suggestion
rotations = [[np.pi for i in range(wires)], [0 for i in range(wires)]]
```
If we put exactly on that point do things not train?

2020-06-23 21:47 UTC, trbromley commented on demonstrations/tutorial_local_cost_functions.py
> +# function and see how it performs.
It might also be interesting to print the gradient.

2020-06-23 21:49 UTC, trbromley commented on demonstrations/tutorial_local_cost_functions.py
> +# have we trained it?
Yeah I also was wondering what we mean by faithful :thinking:

2020-06-23 21:50 UTC, trbromley commented on demonstrations/tutorial_local_cost_functions.py
> +# Instead the making the backend analytic gives us the exact
```suggestion
# Instead making the backend analytic gives us the exact
```

2020-06-23 21:53 UTC, trbromley commented on demonstrations/tutorial_local_cost_functions.py
> +print(local_circuit.draw())
I like that you print the circuit as a way to visualize the end result!
However, when I look at the output, we seem to have only trained the first qubit parameters and hence broken out of our 2D space:
![image](https://user-images.githubusercontent.com/49409390/85468361-5e3e4c00-b57a-11ea-8b5a-4b2dafb599ef.png)

2020-06-23 21:54 UTC, trbromley commented on demonstrations/tutorial_local_cost_functions.py
> +print(local_circuit.draw())
Which I guess makes sense since we do not have any entangling gates and it is a local measurement :thinking: But then it feels like a departure from what we plotted above.

2020-06-23 21:56 UTC, trbromley commented on demonstrations/tutorial_local_cost_functions.py
> +print(local_circuit.draw())
Maybe the plots above need to vary the angle only on the first qubit in both cases, and adopt a fixed angle for all the other qubits.

2020-06-23 21:56 UTC, trbromley commented on demonstrations/tutorial_local_cost_functions.py
> +# attempt to use this circuit, we are no better than random chance.
What do you mean by "no better than random chance"?

2020-06-23 22:04 UTC, trbromley commented on demonstrations/tutorial_local_cost_functions.py
> +print(local_circuit.draw())
Maybe it's ok as is... I'm confused :laughing:

2020-06-24 07:48 UTC, mariaschuld commented on demonstrations/tutorial_local_cost_functions.py
> +# a sense of what is happening in the cost landscape
```suggestion
# a sense of what is happening in the cost landscape.
```

2020-06-24 07:48 UTC, mariaschuld commented on demonstrations/tutorial_local_cost_functions.py
> +# how many quibits we train on will effect our results.
```suggestion
# how many qubits we train on will effect our results.
```

2020-06-25 17:08 UTC, Tstorwick commented on demonstrations/tutorial_local_cost_functions.py
> +    # return sum(abs(result[i]) for i in range(wires))
Thanks!

2020-06-25 17:27 UTC, Tstorwick commented on demonstrations/tutorial_local_cost_functions.py
> +# attempt to use this circuit, we are no better than random chance.
Changed to : "Our circuit has definitely been trained, but not a useful amount. If we attempt to use this circuit, it would act the same as if we never trained at all."

2020-06-25 17:32 UTC, Tstorwick commented on demonstrations/tutorial_local_cost_functions.py
> +# Let's use a more likely number of qubits: n=10. We will say that after
Changed to "Let's use a number of qubits we are more likely to use in a real variational circuit: n=10."

2020-06-25 17:32 UTC, Tstorwick commented on demonstrations/tutorial_local_cost_functions.py
> +# Now the circuit can be trained, even though we started from a place
Thanks!

2020-06-25 17:35 UTC, Tstorwick commented on demonstrations/tutorial_local_cost_functions.py
> +print(local_circuit.draw())
I think i just need to be more clear in the explanation. I compress the parameter space to 2D for the purposes of plotting, but  for the actual training I was going by the assumption that we would train this "blind", and in the full 2n space.

2020-06-25 17:39 UTC, Tstorwick commented on demonstrations.rst
> +    :tags: barren plateaus cost functions local global autograd
Done!

2020-06-25 17:40 UTC, Tstorwick commented on demonstrations/tutorial_local_cost_functions.py
> +# To implement this, we will define a separate qnode for the local cost
changed!

2020-06-25 17:40 UTC, Tstorwick commented on demonstrations/tutorial_local_cost_functions.py
> +plt.show()
Thanks Josh :)

2020-06-25 18:08 UTC, Tstorwick commented on demonstrations/tutorial_local_cost_functions.py
> +rotations = [[3 for i in range(wires)], [0 for i in range(wires)]]
Haha, no, unfortunately things do not train directly on the point. I didn't realize this and tore my hair out over it for a week.

2020-06-25 18:32 UTC, Tstorwick commented on demonstrations/tutorial_local_cost_functions.py
> +algorithm.
Thanks!

2020-06-29 00:54 UTC, Tstorwick commented
> Hey @Tstorwick, thanks for contributing the tutorial. The idea is great, and your explanations clear, but I think there is a bit more work needed.
> 
> @josh146 and @trbromley have already left such a detailed review. Let me only add some high-level comments.
> 
> Something is still off in the way things are designed. If the RX and RY rotation turns a qubit into state a|0> + b|1>, then the "local circuit" produces |a|^2. The global circuit should be just (|a|^2)*6 (since you use the same rotation angle on every qubit, and the chance of each qubit being in state 0 is |a|^2). I checked, and this is consistent with your code.
> 
> But this is why I don't think you are actually reproducing the results from the paper. Your results may not a property of a local or global measurement, but a property of smaller and larger probabilities, if I am not mistaken. (But I could be wrong). So I think it would be good to go back to the paper and really check that what you are doing contains the complexity of what they prove. Especially since it is not clear if the entire observation could be made on circuits where the qubits are not entangled.
> 
> And here a few more things that sprung to my mind:
> 
> * Why do you initialise all rotation angles for RX in the same value, and also for RY?
> * the original circuit ansatz proposed in the paper is actually implemented as a [PennyLane template](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.templates.layers.SimplifiedTwoDesign.html)...would that help? You are using unentangled qubits in the tutorial. So would you consider using the ansatz instead, which uses entanglers and actually corresponds to the paper?
> * my local build fails due to this line missing for 3D plotting: `from mpl_toolkits.mplot3d import Axes3D` Include in the imports?
> * It would be great to add a sentence explaining P_{|0>} (and what quantum observable it corresponds to, since the paper uses expectation values as outputs).
> * The tutorial takes very long to build. I like the idea to "artificially shorten" the runtime (i.e. number of training steps), and load pre-trained parameters in the tutorial, telling the user that they can reproduce by increasing the number of steps to XYZ. (See embeddings_metric_learning tutorial)

Hi Maria! I couldn't figure out how to reply directly, but the quote option will do :). 

So, as I understood the paper, the local vs global measurement advantage was linked to smaller and large probabilities. A local function means a simpler state, and therefore a more "drastic" gradient when training. I thought it was just trivially easier to see when the qubits arent entangled. That said, a proper implementation should have entanglements, so I added them. I originally had a more complex problem after this toy version, that included entanglements and non-trivial search spaces, but runtimes were getting extreme (~2-3 hours) so I cut it. 

"Why do you initialise all rotation angles for RX in the same value, and also for RY?", Originally, I was showing all the starting points on a plot, but decided to cut it for readability. This is just a relic I missed. Good catch!

"my local build fails due to this line missing for 3D plotting: `from mpl_toolkits.mplot3d import Axes3D` Include in the imports?" I tried on a clean python environment locally, and it seemed to work for me. Any more information on the error?

"The tutorial takes very long to build. I like the idea to "artificially shorten" the runtime (i.e. number of training steps), and load pre-trained parameters in the tutorial, telling the user that they can reproduce by increasing the number of steps to XYZ. (See embeddings_metric_learning tutorial)" Good Idea, I'll give implementing this a shot!

2020-06-29 01:07 UTC, Tstorwick commented on demonstrations/tutorial_local_cost_functions.py
> +# landscape is :math:`(\pi,0)`, so lets use that.
It should be minima, it is on my machine at least. I think I constructed a counter-example earlier; however remember that this plot is a subspace of our problem space (that I had to do for plotting), and the two functions might not have the same minima in a different subspace. That, in turn, begs some questions: is there always a subspace where they have a minima in the same location? Is it easier to find this space and then solve the local version than solving the global version?

2020-06-29 01:08 UTC, Tstorwick commented on demonstrations/tutorial_local_cost_functions.py
> +# have we trained it?
Updated the discription

2020-06-29 01:09 UTC, Tstorwick commented on demonstrations.rst
> +    :figure: demonstrations/local_cost_functions/Cerezo_et_al_local_cost_functions.png
I actually meant to ask this question. Do I need permission to reproduce this? Or do I only need a citation?

2020-06-29 01:24 UTC, Tstorwick commented on demonstrations/tutorial_local_cost_functions.py
> +plt.show()
I'm honestly not 100% sure. I cant construct an example of a global only problem in my head (aside from the trivial one of 1 qubit, but one could equally as well call that only local), but there may well be one.

2020-06-30 14:17 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +by Cerezo, then its corrisponding local cost function will always be
```suggestion
by Cerezo, then its corresponding local cost function will always be 
```

2020-06-30 14:17 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +Cerezo et al. also handily prove that these local cost functions are bounded by the
Nice word, handily!

2020-06-30 14:18 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +# Cerezo et al. shows that circuits are trainible under certain regimes, so
```suggestion
# Cerezo et al. shows that circuits are trainable under certain regimes, so
```

2020-06-30 14:18 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +# Next, we want to define our QNodes, containing our ansatz. For this
```suggestion
# Next, we want to define our QNodes and our circuit ansatz. For this
```

2020-06-30 14:19 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +# .. math:: C_{L} = 1-p_{|0>}.
```suggestion
# .. math:: C_{L} = 1-p_{| 0\rangle}.
```

2020-06-30 14:19 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +# We will apply this across all qubits for our global cost function, i.e.:
```suggestion
# We will apply this across all qubits for our global cost function, i.e.,:
```

2020-06-30 14:20 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +# .. math:: C_{L} = 1-p_{|0>}.
In this particular case, do we want to define _which_ qubit the marginal probability `p_{| 0\rangle}` refers to?

2020-06-30 14:20 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +# .. math:: C = 1-p_{|0\rangle}
Might be good to define `p_{}` in the text, so that it can be better intepreted by the reader :)

2020-06-30 14:21 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +# parameters for each rotation
```suggestion
# parameters for each rotation.
```

2020-06-30 14:22 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +# And look at the results:
It sounds a bit better to avoid starting the sentence with 'and', e.g.,
```suggestion
# Examining the results:
```

2020-06-30 14:22 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +# the barren plateau effect graphically. Although there are 2n (where n is the
(so that it renders using LaTeX :))
```suggestion
# the barren plateau effect graphically. Although there are :math:`2n` (where :math:`n` is the 
```

2020-06-30 14:23 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +# same, and all the Y rotations are the same.
Does it make more sense to say 'We will consider the case where all X rotations have the same value, and...'?

2020-06-30 14:24 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +# local cost function, why hasnt the global cost function changed?
```suggestion
# local cost function, why hasn't the global cost function changed?
```

2020-06-30 14:25 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +# --------------
Good practice in restructured text markup to have the title underline match the length of the title:
```suggestion
# A more thorough analysis
# ------------------------
```

2020-06-30 14:32 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +        qml.CNOT(wires=[i,i+1])
@Tstorwick it might be good to use the 'ring' pattern here; this ensures that the entanglement is non-local (and not classically simulatable by a tensor network simulator!)

E.g.:

```suggestion
    qml.broadcast(qml.CNOT, wires=wires, pattern="ring")
```

(see the broadcast documentation here: https://pennylane.readthedocs.io/en/stable/code/api/pennylane.broadcast.html)

2020-06-30 14:33 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +#   arXiv:2001.00550<https://arxiv.org/abs/2001.00550>
```suggestion
#   `arXiv:2001.00550 <https://arxiv.org/abs/2001.00550>`__
```

2020-07-09 11:41 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +# becomes much more trainable.
It might be worth specifying the figure number in the paper that these plots reproduce

2020-07-09 11:48 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +# becomes much more trainable.
```suggestion
# However, when we change to the local cost function, the cost landscape
# becomes much more trainable as the size of the barren plateau decreases.
```

2020-07-09 11:50 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +# Where we sum the marginal probabilities of each quibt, to:
```suggestion
# To simplify this model, let's modify our cost function from
# 
# .. math:: C_{L} = 1-\sum p_{|0\rangle},
#
# where we sum the marginal probabilities of each qubit, to
```

2020-07-09 11:50 UTC, josh146 commented on demonstrations/tutorial_local_cost_functions.py
> +# This is also a valid local cost function.
```suggestion
# .. math:: C_{L} = 1-p_{|0\rangle},
# 
# where we only consider the probability of a single qubit to be in the 0 state. 
```

2020-07-23 15:49 UTC, mariaschuld commented
@Tstorwick Sorry, I missed your reply from a while back (must be because I wasn't mentioned by @). But it makes a lot of sense, thanks for the comments. Is this ready for final review?

2020-07-25 16:22 UTC, Tstorwick commented
@mariaschuld It is! Let me know what you think.

2020-07-27 16:00 UTC, mariaschuld commented on demonstrations/tutorial_local_cost_functions.py
> +#
I still feel strange about this, we are doing a single-qubit computation n times here and sum the result :)

2020-07-27 16:01 UTC, mariaschuld commented on demonstrations/tutorial_local_cost_functions.py
> +#
Maybe one could mention that this is essentially what this circuit does, to pre-empt the comment from readers?

2020-07-27 16:03 UTC, mariaschuld commented on demonstrations/tutorial_local_cost_functions.py
> +# number of qubits) parameters, in order to make the cost landscape plot-able
Love plot-able :) but is it a word?

```suggestion
# number of qubits) parameters, in order to plot the cost landscape 
```

2020-07-27 16:05 UTC, mariaschuld commented on demonstrations/tutorial_local_cost_functions.py
> +# have the same value, and all the Y rotations have the same value.
I love your plots, but one should be careful to note here that of course, this is not conclusive: It only shows the phenomenon for a very restricted case. For example, what if the barren plateau is related to this nice trick of making parameters constant?

2020-07-27 16:07 UTC, mariaschuld commented on demonstrations/tutorial_local_cost_functions.py
> +# To start, lets look at the task of learning the identity gate
```suggestion
# To start, let's look at the task of learning the identity gate
```

2020-07-27 16:07 UTC, mariaschuld commented on demonstrations/tutorial_local_cost_functions.py
> +# trainability? Lets try training both the local, and global cost
```suggestion
# trainability? Let us try training both the local, and global cost
```

2020-07-27 16:07 UTC, mariaschuld commented on demonstrations/tutorial_local_cost_functions.py
> +# While we're at it, lets make our ansatz a little more like one we would encounter while
```suggestion
# While we're at it, let us make our ansatz a little more like one we would encounter while 
```

2020-07-27 16:07 UTC, mariaschuld commented on demonstrations/tutorial_local_cost_functions.py
> +# Now, lets get back to training the local, and global cost functions.
```suggestion
# Now, let us get back to training the local, and global cost functions.
```

2020-07-27 16:08 UTC, mariaschuld commented on demonstrations/tutorial_local_cost_functions.py
> +# an untrainable area. Now, lets limit the ourselves to the local cost
```suggestion
# an "untrainable" area. Now, let us limit ourselves to the local cost
```

2020-07-27 16:09 UTC, mariaschuld commented on demonstrations/tutorial_local_cost_functions.py
> +    return 1 - np.sum(local_circuit(rotations)[:,0])/wires
You use the non-entangled cost here if I am not mistaken?

2020-07-27 16:09 UTC, mariaschuld commented on demonstrations/tutorial_local_cost_functions.py
> +    return 1 - global_circuit(rotations)[0]
And here too. I guess that is a bug? I hope the plots will still be nice! :)

2020-07-27 16:10 UTC, mariaschuld commented on demonstrations/tutorial_local_cost_functions.py
> +# lets pick a point to exaggerate the problem. The worst point in the
Why is that the worst point?

2020-07-27 16:16 UTC, mariaschuld commented on demonstrations/tutorial_local_cost_functions.py
> +print(local_circuit.draw())
It's great you added entanglers, but they don't do anything to the first qubit you measure, unfortunately. 

If you want to fix this, measure the last qubit, which should get information from every other one, or use boradcasting pattern "ring" so the last qubit gets entangled with the first before you measure!

2020-07-28 20:18 UTC, Tstorwick commented on demonstrations/tutorial_local_cost_functions.py
> +    return 1 - np.sum(local_circuit(rotations)[:,0])/wires
@mariaschuld So, the tutorial has changed a little bit. The large confusion was that Patrick Coles has two papers with *almost* identical cost functions. We original had contacted him for some questions we had on one of them, and he directed us to the other; it has better explanations. This is what caused this whole confusion on smaller and larger probability. Firstly, in the paper we are replicating, he demonstrates with a simple example how the global cost function of the zero state over all qubits is more-barren than a local cost function which is the sum of the marginal probabilities of each qubit. This is what I've implemented first.

After that we change the circuit to include entanglements (to be like a more common ansatz) and change the cost function to be the marginal probability of 1 qubit (to a: work with pennylane, currently a cost function with multiple terms throws an error in qml.jacobian when attempting optimization, and b: so that we can implement a version of a local cost function that we can slowly increase to a global one). This other 1 qubit cost function is the cost function implemented in the second Patrick Coles paper. The transitioning from local to global was not implemented in any paper, is probably novel work, and I think is the most interesting part of this tutorial.

2020-07-28 20:21 UTC, Tstorwick commented on demonstrations/tutorial_local_cost_functions.py
> +Traditionally, most variational quantum algorithms are constructed to use global cost functions.
Perhaps it is a little soon to call anything in quantum variational circuits "traditional" .

2020-07-28 23:50 UTC, Tstorwick commented on demonstrations/tutorial_local_cost_functions.py
> +    return 1 - global_circuit(rotations)[0]
See the other comment, but I'll leave this open so I don't forget to change it based on your response.

2020-07-28 23:55 UTC, Tstorwick commented on demonstrations/tutorial_local_cost_functions.py
> +In this notebook, we investigate the effect of barren plateaus in
Done!

2020-07-29 00:35 UTC, Tstorwick commented on demonstrations/tutorial_local_cost_functions.py
> +# zero state, denoted here as :math:`p_{|0\rangle}`.
Good catch!

2020-07-29 00:39 UTC, Tstorwick commented on demonstrations/tutorial_local_cost_functions.py
> +#
Done!

2020-07-29 00:40 UTC, Tstorwick commented on demonstrations/tutorial_local_cost_functions.py
> +# lets pick a point to exaggerate the problem. The worst point in the
It's in the center of the plateau. I've updated the text to reflect this.

2020-08-05 12:07 UTC, mariaschuld commented on demonstrations/tutorial_local_cost_functions.py
> +    return 1 - np.sum(local_circuit(rotations)[:,0])/wires
Great, thanks for the explanation, that clarifies a lot for me!

It would be great to put a bit of this background info into the tutorial, so people can go and look the example up, and they understand where you add new stuff.

Just a minor point though!

2020-08-05 12:11 UTC, mariaschuld commented
Hey @Tstorwick , with your explanation about where to find the example and how it is meant in the bigger context, I finally understand the scope of the tutorial. Really nice!

Since I blocked you for so long I approve the PR, but would recommend these two minor changes:

- As mentioned I'd put the repeated plotting code into a function and make calls to that function, so the reader can focus on the important bits
- Thanks for changing the title - I am now not so sure any more my request was so clever. "Alleviating" is more accurate but much less catchy. If you prefer "Avoid" I'm happy for you to change back, but something like "Getting out of barren plateaus" could also work.

Good job!

2020-09-08 21:34 UTC, co9olguy requested changes
Thanks for the submission @Tstorwick! Hope you had fun making it :smile: 

We'd like to push this towards release now, ideally this week. 

I've left a few suggestions for final polish, spelling and grammar, etc. before release, but all of them are minor. If you are happy with the suggestions, we can merge it and :shipit:

2020-09-08 21:34 UTC, co9olguy commented on demonstrations/tutorial_local_cost_functions.py
> +rotations = [[3 for i in range(wires)], [0 for i in range(wires)]]
Just as a Python tip, you can also do something like
```
[[3] * len(wires), [0] * len(wires)]
```

2020-09-08 21:34 UTC, co9olguy commented on demonstrations/tutorial_local_cost_functions.py
> +    # return sum(abs(result[i]) for i in range(wires))
```suggestion
```

2020-09-08 21:34 UTC, co9olguy commented on demonstrations/tutorial_local_cost_functions.py
> +Alleviating barren plateaus with local cost functions
@Tstorwick Please credit yourself as the author of this tutorial! :smile: 
See the [barren plateaus example](https://pennylane.ai/qml/demos/tutorial_barren_plateaus.html) for how to do this (email not needed if you don't want)

2020-09-08 21:34 UTC, co9olguy commented on demonstrations/tutorial_local_cost_functions.py
> +# ansatz, and the number of qubits increases, this factor will increase.
```suggestion
# untrainable, a significant number. It is likely that, as the complexity of our
# ansatz—and the number of qubits—increases, this factor will increase.
```

2020-09-08 21:34 UTC, co9olguy commented on demonstrations/tutorial_local_cost_functions.py
> +# Comparing that to our local cost function, every single area trained,
```suggestion
# We can compare that to our local cost function, where every single area trained,
```

2020-09-08 21:34 UTC, co9olguy commented on demonstrations/tutorial_local_cost_functions.py
> +#   Cerezo, M., Sone, A., Volkoff, T., Cincio, L., &amp; Coles, P. (2020, February 04).
```suggestion
#   Cerezo, M., Sone, A., Volkoff, T., Cincio, L., and Coles, P. (2020). 
```

2020-09-08 21:34 UTC, co9olguy commented on demonstrations/tutorial_local_cost_functions.py
> +Networks" <https://arxiv.org/abs/2001.00550>`__ Cerezo et al. demonstrate the
```suggestion
In `"Cost-Function-Dependent Barren Plateaus in Shallow Quantum Neural
Networks" <https://arxiv.org/abs/2001.00550>`__ [#Cerezo2020]_, Cerezo et al. demonstrate the
```

2020-09-08 21:36 UTC, co9olguy commented on demonstrations/tutorial_local_cost_functions.py
> +Barren plateaus are large regions of the cost function's parameter space
Might be nice to cross-link to the [barren plateau tutorial](https://pennylane.ai/qml/demos/tutorial_barren_plateaus.html) here?
```suggestion
`Barren plateaus <https://pennylane.ai/qml/demos/tutorial_barren_plateaus.html>`__ are large regions of the cost function's parameter space
```

2020-09-09 12:37 UTC, josh146 commented on .circleci/config.yml
> +          no_output_timeout: 60m
It might not be anymore. Previously it was, as the tutorial used to take quite long to build (now it only takes ~10 minutes)

2020-09-09 14:01 UTC, Tstorwick commented on demonstrations/tutorial_local_cost_functions.py
> +Alleviating barren plateaus with local cost functions
Thanks! Done :)

2020-09-09 14:03 UTC, Tstorwick commented on demonstrations/tutorial_local_cost_functions.py
> +where the variance of the gradient is almost 0; or, put another way, the
It is, (at least, the gradient must be almost 0) but that's not how I've seen barren plateaus typically defined. Papers seem to prefer this definition, so I went with it.

2020-09-09 14:06 UTC, Tstorwick commented on demonstrations/tutorial_local_cost_functions.py
> +    if (i + 1) % 1 == 0:
Right, haha. I had that for testing and forgot about it ._.

2020-09-09 14:07 UTC, Tstorwick commented on .circleci/config.yml
> +          no_output_timeout: 60m
I think it shouldnt be, but I dont think i have the permissions to change this file?

2020-09-09 14:14 UTC, josh146 commented on .circleci/config.yml
> +          no_output_timeout: 60m
I changed this file originally 🙂 It's fine to leave it as is for now.

2020-09-09 14:43 UTC, co9olguy commented on demonstrations/tutorial_local_cost_functions.py
> +# .. math:: C = \langle  \psi(\theta) | \left(I - |0\rangle \langle 0|\right) \rangle  | \psi(\theta)  \rangle   =1-p_{|0\rangle}
```suggestion
# .. math:: C = \langle  \psi(\theta) | \left(I - |0\rangle \langle 0|\right)  | \psi(\theta)  \rangle   =1-p_{|0\rangle}
```

2020-09-09 14:44 UTC, co9olguy commented on demonstrations/tutorial_local_cost_functions.py
> +
```suggestion
```

2020-09-09 14:45 UTC, co9olguy commented on demonstrations/tutorial_local_cost_functions.py
> +
```suggestion
```

2020-09-09 14:46 UTC, co9olguy commented on demonstrations/tutorial_local_cost_functions.py
> +
```suggestion
```

2020-09-09 14:46 UTC, co9olguy commented on demonstrations/tutorial_local_cost_functions.py
> +
```suggestion
```

2020-09-09 14:48 UTC, co9olguy approved these changes
Thanks for this @Tstorwick!

2020-09-09 15:08 UTC, merged