Getting Started with Amazon Braket Hybrid Jobs
PennyLaneAI/qml pull request #940
Opened 2023-09-26 13:44 UTC by mbeach-aws

**Title:** Getting Started with Amazon Braket Hybrid Jobs 

**Summary:** This notebook provides an introduction to running hybrid quantum-classical algorithms using PennyLane on Amazon Braket. With Amazon Braket, you gain access to both real quantum devices and both scalable classical compute, enabling you to push the boundaries of your algorithm. 

**Relevant references:**

**Possible Drawbacks:** 

**Related GitHub Issues:**

2023-09-26 14:17 UTC, KetpuntoG commented
The folder name must match the name of the tutorial. I just updated it. Let's see if it passes the tests now 😄

2023-09-26 22:07 UTC, KetpuntoG reviewed
This new feature is really cool! 🤩 Great job!
Here iss a first round of comments and suggestions :)

2023-09-26 22:07 UTC, KetpuntoG commented on demonstrations/getting_started_with_hybrid_jobs.py
> +# is a lot noisier than our ideal simulator.
I would finish with a slightly more positive sentence 😄
 "[...] but the minimum is detected correctly!"
or something similar

2023-09-26 22:07 UTC, KetpuntoG commented on demonstrations/getting_started_with_hybrid_jobs.py
> +# =======
```suggestion
# Conclusion
# ------------
```

2023-09-26 22:07 UTC, KetpuntoG commented on demonstrations/getting_started_with_hybrid_jobs.py
> +# In this notebook, we showed how to migrate from local Python functions to algorithms running on AWS.
```suggestion
# In this tutorial, we showed how to migrate from local Python functions to algorithms running on AWS.
```

2023-09-26 22:07 UTC, KetpuntoG commented on demonstrations/getting_started_with_hybrid_jobs.py
> +# In the next tutorial, we will cover uploading additional training data and additional Python code.
I would avoid this final sentence until the content exists. Once it is created, we can modify the demo by saying "here you can continue learning".

2023-09-26 22:07 UTC, KetpuntoG commented on demonstrations/getting_started_with_hybrid_jobs.py
> +
In all demos we usually end with some references, is there anything here that can be included?

2023-09-27 15:40 UTC, LucasSilbernagel requested changes

2023-09-27 15:40 UTC, LucasSilbernagel commented on demonstrations/getting_started_with_hybrid_jobs.metadata.json
> +}
```suggestion
    "relatedContent": [],
     "hardware": [
        {
            "id": "aws",
            "link": "", <-- Please put the URL to the demo GitHub repository here 🙂
            "logo": "/_static/hardware_logos/aws.png"
        }
    ]
}
```

2023-09-27 17:36 UTC, mbeach-aws commented on demonstrations/getting_started_with_hybrid_jobs.py
> +
I think the links are not live yet, so not much to add.

2023-09-27 17:37 UTC, mbeach-aws commented on demonstrations/getting_started_with_hybrid_jobs.py
> +# In the next tutorial, we will cover uploading additional training data and additional Python code.
good point, removed it now

2023-09-27 18:09 UTC, mbeach-aws commented on demonstrations/getting_started_with_hybrid_jobs.py
> +# will have priority access to. In this example, we set ``device=None`` since we don’t require
okay changed to:
# The required device argument in the ``@hybrid_job`` decorator specifies the QPU that the hybrid job
# will have priority access to. 
# The device string you give is accessible in the hybrid job instance as the environment variable "AMZN_BRAKET_DEVICE_ARN". 
# When using on-demand simulators or `embedded simulators <https://docs.aws.amazon.com/braket/latest/developerguide/pennylane-embedded-simulators.html>`__, 
# you may provide the device argument as string of the form: "local:<provider>/<simulator_name>" or simply `None`. 
# For example, you may set "local:pennylane/lightning.qubit" for the PennyLane lightning simulator.

2023-09-27 18:41 UTC, mbeach-aws commented on demonstrations/getting_started_with_hybrid_jobs.py
> +First, we import the necessary packages for the algorithm:
okay tried to separate them now

2023-09-27 19:16 UTC, KetpuntoG commented on demonstrations/getting_started_with_hybrid_jobs.metadata.json
> +            "link": "", <-- Please put the URL to the demo GitHub repository here 🙂
```suggestion
            "link": "https://github.com/PennyLaneAI/qml/pull/940",
```

2023-09-28 13:21 UTC, KetpuntoG commented on demonstrations/getting_started_with_hybrid_jobs.py
> +Importantly, on specific QPUs, running your algorithm a hybrid job benefits from `parametric compilation <https://docs.aws.amazon.com/braket/latest/developerguide/braket-jobs-parametric-compilation.h
```suggestion
Importantly, on specific QPUs, running your algorithm in a hybrid job benefits from `parametric compilation <https://docs.aws.amazon.com/braket/latest/developerguide/braket-jobs-parametric-compilation.html>`__. 
```

2023-09-28 13:21 UTC, KetpuntoG commented on demonstrations/getting_started_with_hybrid_jobs.py
> +
```suggestion
Let’s setup an algorithm that makes use of both classical and quantum resources. We adapt the :doc:`PennyLane qubit rotation tutorial<tutorial_qubit_rotation>`.
```

2023-09-28 13:22 UTC, KetpuntoG commented on demonstrations/getting_started_with_hybrid_jobs.py
> +# When running on AWS, ``log_metric`` records the metrics in `Amazon CloudWatch <https://aws.amazon.com/cloudwatch/>`__, which as accessible
```suggestion
# When running on AWS, ``log_metric`` records the metrics in `Amazon CloudWatch <https://aws.amazon.com/cloudwatch/>`__, which is accessible
```

2023-09-28 13:23 UTC, KetpuntoG commented on demonstrations/getting_started_with_hybrid_jobs.py
> +# can train the a larger circuit, or increase the number of iterations. Note that each hybrid job has
```suggestion
# can train a larger circuit, or increase the number of iterations. Note that each hybrid job has
```

2023-09-28 13:23 UTC, KetpuntoG commented on demonstrations/getting_started_with_hybrid_jobs.py
> +# result of the function. To retrieve the results after it has completed, use ``job.result()``.
```suggestion
# result of the function. To retrieve the results after it has been completed, use ``job.result()``.
```

2023-09-28 13:24 UTC, KetpuntoG commented on demonstrations/getting_started_with_hybrid_jobs.py
> +# Now we create a hybrid job by calling the function as usual. This returns a ``AwsQuantumJob`` object
```suggestion
# Now we create a hybrid job by calling the function as usual. This returns an ``AwsQuantumJob`` object
```

2023-09-28 13:25 UTC, KetpuntoG commented on demonstrations/getting_started_with_hybrid_jobs.py
> +# should take approximate 2 minutes.
```suggestion
# should take approximately 2 minutes.
```

2023-09-28 13:26 UTC, KetpuntoG commented on demonstrations/getting_started_with_hybrid_jobs.py
> +# libraries such as numpy, use the ``.tolist()`` method to create a Python list object that are
```suggestion
# libraries such as numpy, use the ``.tolist()`` method to create a Python list object that is
```

2023-09-28 13:26 UTC, KetpuntoG commented on demonstrations/getting_started_with_hybrid_jobs.py
> +# Using hybrid jobs for iterative algorithms is very benefit because you retain priority access to the
```suggestion
# Using hybrid jobs for iterative algorithms is very beneficial because you retain priority access to the
```

2023-09-28 13:27 UTC, KetpuntoG commented on demonstrations/getting_started_with_hybrid_jobs.py
> +# waiting in the regular quantum task queue. This is because hybrid jobs has a separate queue from
```suggestion
# waiting in the regular quantum task queue. This is because hybrid jobs have a separate queue from
```

2023-09-28 13:27 UTC, KetpuntoG commented on demonstrations/getting_started_with_hybrid_jobs.py
> +# predictably. However, hybrid jobs has a separate queue from standalone tasks so that only a single
```suggestion
# predictably. However, hybrid jobs have a separate queue from standalone tasks so that only a single
```

2023-09-28 13:28 UTC, KetpuntoG commented on demonstrations/getting_started_with_hybrid_jobs.py
> +# local simulator and a real QPU. It was beneficial to run as a hybrid jobs so that we offload all
```suggestion
# local simulator and a real QPU. It was beneficial to run as a hybrid job so that we offload all
```

2023-09-28 13:29 UTC, KetpuntoG commented on demonstrations/getting_started_with_hybrid_jobs.metadata.json
> +    ],
```suggestion
    "categories": [
        "Devices and Performance",
    ],
```

2023-09-28 13:31 UTC, KetpuntoG commented on demonstrations/getting_started_with_hybrid_jobs.py
> +# ipy
```suggestion
#
```

I'm not sure what this ipy was doing here. I delete it

2023-10-01 19:02 UTC, josh146 commented on demonstrations/getting_started_with_hybrid_jobs.py
> +*Author: Matthew Beach — Posted: 1 October 2023.
```suggestion
```
@KetpuntoG this is no longer needed right?

2023-10-01 19:03 UTC, josh146 commented on demonstrations/getting_started_with_hybrid_jobs.py
> +=========================
```suggestion
Amazon Braket Hybrid Jobs
-------------------------
```

2023-10-01 19:03 UTC, josh146 commented on demonstrations/getting_started_with_hybrid_jobs.py
> +==============================
```suggestion
Getting started with PennyLane
------------------------------
```

2023-10-01 19:05 UTC, josh146 commented on demonstrations/getting_started_with_hybrid_jobs.py
> +  This demo is only compatible with Python version 3.10.
```suggestion

.. warning::

  The following demo is only compatible with Python version 3.10.
```

2023-10-01 19:07 UTC, josh146 commented on demonstrations/getting_started_with_hybrid_jobs.py
> +# The device string you give is accessible in the hybrid job instance as the environment variable "AMZN_BRAKET_DEVICE_ARN".
```suggestion
# The device string you give is accessible in the hybrid job instance as the environment variable ``AMZN_BRAKET_DEVICE_ARN``.
```

2023-10-01 19:08 UTC, josh146 commented on demonstrations/getting_started_with_hybrid_jobs.py
> +# For example, you may set "local:pennylane/lightning.qubit" for the PennyLane lightning simulator.
```suggestion
#
# When using on-demand simulators or `embedded simulators <https://docs.aws.amazon.com/braket/latest/developerguide/pennylane-embedded-simulators.html>`__,
# you may provide the device argument as string of the form: ``"local:\<provider\>/\<simulator_name\>"`` or simply ``None``.
# For example, you may set ``"local:pennylane/lightning.qubit"`` for the `PennyLane lightning simulator <https://pennylane.ai/performance>`__.
```

2023-10-01 20:08 UTC, josh146 commented on demonstrations/getting_started_with_hybrid_jobs.metadata.json
> +            "link": "https://github.com/PennyLaneAI/qml/pull/940",
a reminder to update this to the correct `amazon-braket` github link when ready :)

2023-10-01 22:16 UTC, josh146 commented on demonstrations/getting_started_with_hybrid_jobs.py
> +#       Metrics - timestamp=1695043649.822114; expval=0.38894534132396147; iteration_number=0;
```suggestion
##############################################################################
# .. rst-class:: sphx-glr-script-out
#
#  .. code-block:: none
#
#       Metrics - timestamp=1695043649.822114; expval=0.38894534132396147; iteration_number=0;
```

2023-10-01 22:33 UTC, josh146 commented on demonstrations/getting_started_with_hybrid_jobs.py
> +#  .. code-block:: none
```suggestion
##############################################################################
# .. rst-class:: sphx-glr-script-out
#
#  .. code-block:: none
```

2023-10-02 15:11 UTC, isaacdevlugt approved these changes
Looks good to me! Made some minor grammar suggestions. PR preview looks good as well. Good stuff 😎

2023-10-02 15:11 UTC, isaacdevlugt commented on demonstrations/getting_started_with_hybrid_jobs.py
> +# create a hybrid job with the Rigetti devices as the priority QPU. We also increase the number of
"device" or "devices"?

```suggestion
# create a hybrid job with the Rigetti device as the priority QPU. We also increase the number of
```

2023-10-02 15:11 UTC, isaacdevlugt commented on demonstrations/getting_started_with_hybrid_jobs.py
> +# recommended to create quantum tasks instead of hybrid jobs.
Some repetition here but I don't mind it

2023-10-02 15:11 UTC, isaacdevlugt commented on demonstrations/getting_started_with_hybrid_jobs.py
> +# the function scope. This is avoid unintentional sharing of AWS credentials.
```suggestion
# the function scope. This avoids unintentional sharing of AWS credentials.
```

2023-10-13 13:45 UTC, LucasSilbernagel approved these changes

2023-10-13 13:54 UTC, mbeach-aws commented on demonstrations/getting_started_with_hybrid_jobs.metadata.json
> +            "link": "https://github.com/PennyLaneAI/qml/pull/940",
Do you mean this link?  https://github.com/amazon-braket/amazon-braket-examples/tree/main/examples/hybrid_jobs

2023-10-13 18:45 UTC, KetpuntoG commented
Thanks for the latest changes 🚀

2023-10-16 14:17 UTC, merged