[WIP] add introduction to block encoding demo
PennyLaneAI/qml pull request #943
Opened 2023-10-02 14:54 UTC by soranjh

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2023-10-02 15:27 UTC, soranjh commented on demonstrations/tutorial_block_encoding.py
> +# Let's look at O_A, O_s for the Banded circulant matrix
@Jaybsoni , Could you please expand these points?
We also need a small code example.

2023-10-04 19:38 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.metadata.json
> +}
```suggestion
}

```

2023-11-02 20:48 UTC, Jaybsoni commented
Added some more theory, just needs to be polished once the CI runs, then I will approve 👍🏼

2023-11-03 14:45 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +# these tips and tricks to find a more efficient block encoding your matrix!
```suggestion
# these tips and tricks to find a more efficient block encoding for your matrix! 
```

2023-11-03 15:45 UTC, Jaybsoni approved these changes
Looks good from my side 👍🏼

2023-11-06 14:22 UTC, KetpuntoG reviewed
Great job team! It's great to see how good the results are 🚀
Here I leave a few comments :)
I missed the "why is it done this way" but I assume that is outside the scope of this tutorial

2023-11-06 22:48 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +# ([#sparse]_).
```suggestion
# The :math:`U_B` oracle is defined in terms of the so-called "Left" and "Right" shift operators.
# They correspond to the modular arithmetic operations :math:`+1` or :math:`-1` respectively ([#sparse]_).
```

2023-11-06 22:49 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +    qml.ctrl(qml.RY, control=wire_l, control_values=[0, 1])(theta[2], wires=ancilla)
```suggestion
def UA(ancilla, wire_i, theta):
    qml.ctrl(qml.RY, control=wire_i, control_values=[0, 0])(theta[0], wires=ancilla)
    qml.ctrl(qml.RY, control=wire_i, control_values=[1, 0])(theta[1], wires=ancilla)
    qml.ctrl(qml.RY, control=wire_i, control_values=[0, 1])(theta[2], wires=ancilla)
```

2023-11-06 22:49 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +    qml.ctrl(shift_op, control=wires_l[1])(wires_j, shift="Right")
```suggestion
def UB(wires_i, wires_j):
    qml.ctrl(shift_op, control=wires_i[0])(wires_j, shift="Left")
    qml.ctrl(shift_op, control=wires_i[1])(wires_j, shift="Right")
```

2023-11-06 22:50 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +dev = qml.device("default.qubit", wires=["ancilla", "l1", "l0", "j2", "j1", "j0"])
```suggestion
dev = qml.device("default.qubit", wires=["ancilla", "i1", "i0", "j2", "j1", "j0"])
```

2023-11-06 22:53 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +    for w in ["l0", "l1"]:  # hadamard transform over |l> register
```suggestion
    for w in ["i0", "i1"]:  # hadamard transform over |i> register
```

2023-11-06 22:53 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +    UB(["l0", "l1"], ["j0", "j1", "j2"])
@soranjh or @DSGuala is it possible to reactor the code above for this? Otherwise I can change this for consistency.

2023-11-06 22:54 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +    UB(["l0", "l1"], ["j0", "j1", "j2"])
```suggestion
    UA("ancilla", ["i0", "i1"], theta)

    UB(["i0", "i1"], ["j0", "j1", "j2"])
```

2023-11-06 22:55 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +    for w in ["l0", "l1"]:  # hadamard transform over |l> register
```suggestion
    for w in ["i0", "i1"]:  # hadamard transform over |l> register
```

2023-11-06 22:55 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +dev = qml.device("default.qubit", wires=["ancilla", "l1", "l0", "j2", "j1", "j0"])
That's the index name they used in the paper, changed it to index "I".

2023-11-06 22:55 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +def shift_op(s_wires, shift="Left"):
Added 👍🏼

2023-11-07 16:04 UTC, DSGuala requested changes
Left several comments. I'm not sure I'm happy with the overall structure of the demo. The first section: `Circuits with matrix access oracles` doesn't connect well to the next section: `Block encoding with FABLE`.

2023-11-10 23:28 UTC, KetpuntoG reviewed
A big difference from the last time I reviewed it 💯 
Much clearer, and the drawings look great in PL style 🚀
Here are some suggestions

2023-11-10 23:28 UTC, KetpuntoG commented on demonstrations/tutorial_block_encoding.py
> +# and need to be able to encode :math:`A` itself, so they will both have :math:`4` qubits for our
maybe 2 instead of 4?

2023-11-10 23:28 UTC, KetpuntoG commented on demonstrations/tutorial_block_encoding.py
> +                 n_selections], 2))) for i in range(n_selections)]
I don't understand this line, can it be expressed in another way?

2023-11-10 23:28 UTC, KetpuntoG commented on demonstrations/tutorial_block_encoding.py
> +qml.draw_mpl(circuit, style='pennylane')()
at the end of all plots, put plt.show()
(import matplotlib if necessary)
This will prevent unnecessary text from coming out when displaying

2023-11-10 23:28 UTC, KetpuntoG commented on demonstrations/tutorial_block_encoding.py
> +on :math:`n` qubits. Finding the optimal sequence of the quantum gates that implement :math:`U_A`
Is it possible to explain super quickly what each one does? I understand that the part of b(i,j) has been removed because it was confusing but maybe you can comment on the idea.

I haven't read the paper so maybe this is wrong but I imagine something like:

U_A is able to do the necessary rotation in the auxiliary qubit for a specific i,j coordinates of the matrix.

U_B selects exactly which elements are those we want to encode. This oracle is important since it is not always necessary to encode all the elements and in sparse matrices it will play will considerably boost the algorithm.

For more information on its construction, I invite you to read the original paper.

2023-11-10 23:28 UTC, KetpuntoG commented on demonstrations/tutorial_block_encoding.py
> +# tensor product of Hadamard gates. Note that :math:`U_B` in FABLE is constructed as a set of SWAP
I think something like this would be better:

Note that in the particular case where we have no non-zero elements in the matrix [...] as a set of SWAPs. I invite you to think about why this is so.

2023-11-10 23:28 UTC, KetpuntoG commented on demonstrations/tutorial_block_encoding.py
> +# the dimension of :math:`A` should be :math:`2^n, n = 1, 2, 3, ...`. For matrices with an arbitrary
It renders a little strange that n = 1,2,3. I think it would be better to eliminate it or say for n an integer.

2023-11-10 23:28 UTC, KetpuntoG commented on demonstrations/tutorial_block_encoding.py
> +# good this approximation is in the case of our example.
It would be good to clarify what is going to be done so as not to scare the reader. Something like:

We will make a small modification to UA so that it removes those CNOTs that, as we have seen, we do not need

2023-11-10 23:28 UTC, KetpuntoG commented on demonstrations/tutorial_block_encoding.py
> +ancilla_wires = ["ancilla"]   # always 1 qubit for controlled rotations
In the previous example it was `ancilla_wire = "ancilla" ` and it was pass in the device as [ancilla_wire]. I like the current notation better, so I would change the above notation to consistency.

2023-11-13 15:52 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +# the dimension of :math:`A` should be :math:`2^n, n = 1, 2, 3, ...`. For matrices with an arbitrary
natural number :)

2023-11-13 15:53 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +# and need to be able to encode :math:`A` itself, so they will both have :math:`4` qubits for our
Yes correct!

2023-11-13 15:54 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +# and need to be able to encode :math:`A` itself, so they will both have :math:`4` qubits for our
```suggestion
# and need to be able to encode :math:`A` itself, so they will both have :math:`2` qubits for our
```

2023-11-16 17:43 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +ancilla_wires = ["ancilla"]   # always 1 qubit for controlled rotations
Fixed the previous case to use `ancilla_wires = ["ancilla"]` as well!

2023-11-16 17:43 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +qml.draw_mpl(circuit, style='pennylane')()
Add plt.show()

2023-11-16 20:29 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +The FABLE circuit is constructed from a set of rotation and C-NOT gates. The rotation angles,
Added 👍🏼

2023-11-16 20:29 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +# The :code:`"ancilla"` register will always contain a single qubit, this is the target where we
Added 👍🏼

2023-11-16 20:29 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +on :math:`n` qubits. Finding the optimal sequence of the quantum gates that implement :math:`U_A`
Added 👍🏼

2023-11-16 20:29 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +# tensor product of Hadamard gates. Note that :math:`U_B` in FABLE is constructed as a set of SWAP
Added 👍🏼

2023-11-16 20:31 UTC, Jaybsoni commented
@KetpuntoG, I addressed some of your comments and added a thumbnail. We also have a large thumbnail file, which I am not sure where it goes, please add it into the right place 👍🏼

2023-11-16 21:01 UTC, DSGuala commented on demonstrations/tutorial_block_encoding.py
> +                 n_selections], 2))) for i in range(n_selections)]
This is copied from [MottonenStatePreparation](https://github.com/PennyLaneAI/pennylane/blob/3dee10187e0698d521daa841e5d146e92a50f343/pennylane/templates/state_preparations/mottonen.py#L133).

I don't think we know a better way to express it. It creates the following kind of patterns:
[0, 1, 0, 2, 0, 1, 0, 2]
[0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 1, 0, 3]

I'm thinking of another way to express it, but it's difficult.

2023-11-16 21:08 UTC, soranjh commented on demonstrations/tutorial_block_encoding.py
> +                 n_selections], 2))) for i in range(n_selections)]
If possible, we can add 1-2 sentences to briefly explain what this does.

2023-11-17 15:07 UTC, KetpuntoG approved these changes
A great improvement! Everything much clearer and cleaner than the first review, well done! 💯 I did a final commit with some [smalls modifications](https://github.com/PennyLaneAI/qml/pull/943/commits/aadd90e2ddd7bfa4b5ffb9ac11bdc82b9cdce381)
It's ready for me 😄 (but don't merge it)

2023-11-21 19:34 UTC, Jaybsoni commented on demonstrations/block_encoding/general_circuit.png
@DSGuala, could you update this image by adding a subscript "anc" to the |0> qubit? So it looks something like:  `|0>_anc` I refer to it as an ancilla qubit and denote it as such in the math sections.

2023-11-23 15:43 UTC, KetpuntoG commented on demonstrations/tutorial_block_encoding.py
> +# then :math:`U_B` in FABLE is constructed as a set of SWAP gates. We invite you to think about why this is so.
the invitation to deduce the SWAP was put in the previous review because b(i,j) was previously defined. Now that it's not there, it's not something I think the user can infer so you can remove it.

2023-11-23 16:33 UTC, KetpuntoG commented
From what we have discussed in person, the confusion may come since you don't see the clear separation between the two algorithms. It may seem that the spare matrix case is a particular case of Fable but they work differently. For that reason, I would clarify it in the introduction. After showing the structure of this type of encodings, say:


"In this demo we are going to work with two particular algorithms based on oracles: the FABLE method and another method that focuses on sparse matrices."

So here you already start talking about FABLE, you talk about UA with the formulas and say that we will always take the same size |i> and |j>, representing the row and column indexes (I think). Remark that in this **algorithm** you always take UB as a SWAP gate whose goal is to order the indices in the right way. 


Then you get to the sparse matrix block. Here you start by saying that this is a different method that seeks to optimize the algorithm for situations where the matrix is sparse. You also say something like "Unlike the FABLE algorithm, in this case the |j> register will not store the column "j" but will store b(i,j). b(i, j) means [...]. In this way we can greatly improve the efficiency since the number of qubits will not grow with the size of the matrix but with the number of non-empty entries. With this in mind, note that we will find a small difference in the construction of UA, we will simply have to adapt the indexes to the new definition:


[formula]

On the other hand UB is in charge of returning precisely that b(i,j) value we were commenting:

[formula]

2023-11-23 18:26 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +combination of :math:`(i,j)`.
Ahh, meant to remove one. Nice catch!

2023-11-23 19:30 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +    return qml.probs(wires=ancilla_wires + wires_i)
We could remove it since we don't use the output of the qnode. I personally think it's nice to keep the measurements in because in the paper, we need to measure out those qubits to post select the states that ensure we correctly block-encoded. (ancilla_wires + wires_i need to be in the all |0> state to access A).

2023-11-23 19:31 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +# then :math:`U_B` in FABLE is constructed as a set of SWAP gates. We invite you to think about why this is so.
Removed it.

2023-11-23 19:31 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +# the same size and need to be able to encode :math:`A` itself, so they will both have :math:`2` qubits
Added 👍🏼

2023-11-23 19:32 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +          M \begin{pmatrix} \alpha_1 \\ \cdots \\ \alpha_n \end{pmatrix},
Added 👍🏼

2023-11-23 19:32 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +this case simplifies to be the :math:`SWAP` gate:
I added the link to the class :class:`~.pennylane.SWAP`

2023-11-23 21:58 UTC, KetpuntoG commented on demonstrations/tutorial_block_encoding.py
> +The Fast Approximate BLock Encodings (FABLE) technique is a method for block encoding matrices [#fable]_
Check this sentence

2023-11-23 21:58 UTC, KetpuntoG commented on demonstrations/tutorial_block_encoding.py
> +# apply the rotation gates methioned above. The :code:`"wires_i"` and :code:`"wires_j"` registers are
```suggestion
# apply the rotation gates mentioned above. The :code:`"wires_i"` and :code:`"wires_j"` registers are 
```

2023-11-23 22:06 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +The Fast Approximate BLock Encodings (FABLE) technique is a method for block encoding matrices [#fable]_
Updated

2023-11-24 14:22 UTC, KetpuntoG reviewed
Just some typos :)

2023-11-24 14:22 UTC, KetpuntoG commented on demonstrations/tutorial_block_encoding.py
> +matrix entries of :math:`A` into the amplitude of an auxillary qubit :math:`|0\rangle_{\text{anc}}`:
```suggestion
matrix entries of :math:`A` into the amplitude of an auxilary qubit :math:`|0\rangle_{\text{anc}}`:
```

2023-11-24 14:22 UTC, KetpuntoG commented on demonstrations/tutorial_block_encoding.py
> +# :code:`"ancilla"` register will always contain a single qubit, this is the auxillary qubit where we
```suggestion
# :code:`"ancilla"` register will always contain a single qubit, this is the auxilary qubit where we
```

2023-11-24 14:22 UTC, KetpuntoG commented on demonstrations/tutorial_block_encoding.py
> +    qml.Barrier()  # to seperate the sections in the circuit
```suggestion
    qml.Barrier()  # to separate the sections in the circuit 
```

2023-11-24 14:22 UTC, KetpuntoG commented on demonstrations/tutorial_block_encoding.py
> +# In this case the :math:`U_B` oracle is responsible for implmenting the :math:`b(i,j)` function
```suggestion
# In this case the :math:`U_B` oracle is responsible for implementing the :math:`b(i,j)` function 
```

2023-11-24 14:22 UTC, KetpuntoG commented on demonstrations/tutorial_block_encoding.py
> +# Lets work through an example. Consider the sparse matrix given by:
```suggestion
# Let's work through an example. Consider the sparse matrix given by:
```

2023-11-24 14:22 UTC, KetpuntoG commented on demonstrations/tutorial_block_encoding.py
> +For the exact block-encoding of :math:`A`. The :math:`U_A` oracle is responsible for encoding the
```suggestion
for the exact block-encoding of :math:`A`. The :math:`U_A` oracle is responsible for encoding the 
```

is this change correct, right?

2023-11-24 14:22 UTC, KetpuntoG commented on demonstrations/tutorial_block_encoding.py
> +The Fast Approximate BLock Encoding (FABLE) technique is a method for block encoding matrices [#fable]_
I think you have not change this, make sure you pushed all your changes

2023-11-24 14:22 UTC, KetpuntoG commented on demonstrations/tutorial_block_encoding.py
> +be obtained with the :func:`~.pennylane.templates.state_preparations.mottonen.compute_theta()`
```suggestion
be obtained with the :func:`~.pennylane.templates.state_preparations.mottonen.compute_theta`
```

2023-11-24 14:22 UTC, KetpuntoG commented on demonstrations/tutorial_block_encoding.py
> +# Once again we identify and prepare the qubit registers used in the oracle access framework:
```suggestion
# Once again we identify and prepare the qubit registers used in the oracle access framework.
```

2023-11-24 15:34 UTC, soranjh commented on demonstrations/tutorial_block_encoding.py
> +Block encoding structured matricies
```suggestion
Block encoding structured matrices 
```

2023-11-24 15:34 UTC, soranjh commented on demonstrations/tutorial_block_encoding.py
> +In order to better understand the oracle access framework let us first define :math:`U_A` and :math:`U_B`
```suggestion
In order to better understand the oracle access framework, let us first define :math:`U_A` and :math:`U_B`
```

2023-11-24 15:34 UTC, soranjh commented on demonstrations/tutorial_block_encoding.py
> +be obtained with the :func:`~.pennylane.templates.state_preparations.mottonen.compute_theta()`
The link to compute_theta does not work for some reason. Maybe use " ... obtained with the compute_theta() function in PennyLane."

2023-11-24 15:34 UTC, soranjh commented on demonstrations/tutorial_block_encoding.py
> +# translate the :code:`control_wires` into the wire registers we prepared.
```suggestion
# translate the control wires into the wire registers we prepared.
```

2023-11-24 15:34 UTC, soranjh commented on demonstrations/tutorial_block_encoding.py
> +# translate the :code:`control_wires` into the wire registers we prepared.
[optional suggestion]

2023-11-24 15:34 UTC, soranjh commented on demonstrations/tutorial_block_encoding.py
> +
Please consider removing the empty lines for a more compact code.

2023-11-24 15:34 UTC, soranjh commented on demonstrations/tutorial_block_encoding.py
> +# Like in the structured approach the :math:`U_A` oracle is responsible for encoding the matrix
```suggestion
# Like in the structured approach, the :math:`U_A` oracle is responsible for encoding the matrix 
```

2023-11-24 15:34 UTC, soranjh commented on demonstrations/tutorial_block_encoding.py
> +# The :code:`"ancilla"` register will still contain a single qubit, the target where for the
```suggestion
# The :code:`"ancilla"` register will still contain a single qubit, the target for the
```

2023-11-24 15:34 UTC, soranjh commented on demonstrations/tutorial_block_encoding.py
> +
Might consider removing the blank lines to make the circuit compact.

2023-11-24 15:34 UTC, soranjh commented on demonstrations/tutorial_block_encoding.py
> +using the oracle access framework and some clever approximations 🧠. The level of approximation in FABLE
Note that the original paper uses "Encodings".

2023-11-24 15:36 UTC, soranjh commented on demonstrations/tutorial_block_encoding.py
> +using the oracle access framework and some clever approximations 🧠. The level of approximation in FABLE
```suggestion
that this requires :math:`O(N^{4})` gates and is very inefficient. A more efficient approach is the 
Fast Approximate BLock Encodings (FABLE) technique [#fable]_, which
uses the oracle access framework and some clever approximations 🧠. The level of approximation in FABLE 
```

2023-11-24 20:56 UTC, Jaybsoni commented on demonstrations/tutorial_block_encoding.py
> +#     |A_{l,j}\rangle_{\text{anc}} \equiv A_{l,j}|0\rangle_{\text{anc}} + \sqrt{1 - A_{l,j}^2}|1\rangle_{\text{anc}}.
```suggestion
```

2023-11-24 21:55 UTC, KetpuntoG commented
Great Job @Jaybsoni ! It was not an easy topic but now it's clear 🚀
You can have the honors of clicking on the merge button 😉

2023-11-27 14:26 UTC, merged