[WIP] Initial state preparation demo
PennyLaneAI/qml pull request #950
Opened 2023-10-05 23:12 UTC by Chiffafox

**Title:**

Initial state preparation for quantum chemistry

**Summary:**

This demo is explaining the concept of an initial state -- a primer for a quantum algorithm that improves its chances of success specifically for the task of obtaining the ground-state energy of a molecule. It showcases the newly built functionality in PennyLane for importing outputs from sophisticated computational chemistry methods to initialize better initial states. Finally, it shows how the choice of initial state affects the execution of VQE on a simple molecule, demonstrating the importance of initial state for quantum algorithms and that this can of algorithms R&D can be now performed in PennyLane.

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2023-10-06 19:15 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +in the gigantic Hilbert space of a typical molecule requires expert guidance -- an
This is nice but not suitable for this advanced "how-to" type document. We can keep it for a future introductory demo on initial states.

2023-10-06 19:16 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +From the variational quantum eigensolver (VQE) to quantum phase estimation (QPE), to even
I like this. We should start the document with this.

2023-10-06 19:21 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +    detect the jump and thus resolve the position of the ground-state energy.
This is nice, we might get rid of the numbered lists and just have a paragraph.

2023-10-06 19:26 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +:math:`\Delta` between the ground and first excited states: and this gap turns out to
This is a bit too much of details for a method that we will not be discussing here. You can just mention it like "quantum imaginary-time evolution" and "variational methods" without explaining it.

2023-10-06 19:27 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +        as a cross-check.
It will be good if we have sub-sections for each method and provide the code block there. We can still mention in one like which methods we support.

2023-10-06 19:29 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +##############################################################################
This part could have a dedicated section and a title.

2023-10-12 12:31 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +    detect the jump and thus resolve the position of the ground-state energy.
Sounds good!

2023-10-12 12:33 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +:math:`\Delta` between the ground and first excited states: and this gap turns out to
Good point, done.

2023-10-12 13:25 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +in the gigantic Hilbert space of a typical molecule requires expert guidance -- an
Agreed, will keep for future.

2023-10-12 13:25 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +From the variational quantum eigensolver (VQE) to quantum phase estimation (QPE), to even
Done.

2023-10-13 16:46 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +##############################################################################
Agreed, done.

2023-10-13 20:43 UTC, soranjh commented on _static/authors/stepan_fomichev.txt
> +   Stepan Fomichev is a quantum scientist working at Xanadu. His background is in condesned matter physics, with a focus on lattice vibrations and electron-phonon coupling. As part of the Algorithms
```suggestion
   Stepan Fomichev is a quantum scientist working at Xanadu. His background is in condensed matter physics, with a focus on lattice vibrations and electron-phonon coupling. As part of the Algorithms team, he focuses on researching and developing prospective applications for quantum algorithms.
```

2023-10-13 20:43 UTC, soranjh commented on demonstrations/initial_state_preparation/hf_vs_ccsd_for_vqe.png
We probably don't need plots, just printing the number of iterations will be fine.

2023-10-13 20:43 UTC, soranjh commented on demonstrations/initial_state_preparation/hf_vs_ccsd_for_vqe_stretched.png
We probably don't need plots, just printing the number of iterations will be fine.

2023-10-13 20:43 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +    return qml.expval(ham)
You can just merge these to make it compact.

2023-10-13 20:43 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +    return energy_VQE, theta_opt
Probably we do not need a function, we define the opt etc and in two different while/for loops print the energy:
```
step: 1, energy = ...
step: 2, energy = ...
...
```

2023-10-13 20:43 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +# energy_dmrg, theta_dmrg = run_VQE(wf_dmrg, ham=H2mol_corr)
Not sure it adds anything. We might think of using LiH instead of H2.

2023-10-13 20:43 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +ovlp = np.dot(wf_ccsd, wf_hf)
Not sure it is very useful/informative, any objection?

2023-10-13 21:04 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +    qml.QubitStateVector(initstate, wires=wires)
Please use `qml.StatePrep`.

2023-10-13 21:06 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +get us _most of the way_ to an initial state. Such an initial state will not be the
_most of the way_ does not render correctly.

2023-10-13 21:14 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +# as a tuple `(list([int]), array(float])). The first element expresses a given Slater
Please use double accent,  i.e., ``var``, for variable names.

2023-10-13 21:14 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +# The crucial part is calling `get_csf_coefficients()` on the solution stored in
This paragraph is a bit too technical.

2023-10-13 21:15 UTC, soranjh commented on demos_quantum-chemistry.rst
> +    :figure: demonstrations/resource_estimation/resource_estimation.jpeg
Please use the correct folder and image. If not created, we need the "initial_state" folder or something similar.

2023-10-13 21:16 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +The first line of attack for initial state preparation is CISD calculations performed with the PySCF
Need links for PySCF, Block2 and Dice.

2023-10-16 14:15 UTC, Chiffafox commented on demos_quantum-chemistry.rst
> +    :figure: demonstrations/resource_estimation/resource_estimation.jpeg
Without the image, it does not build, hence the use of a stub for now. Can we get the image that Tom shared?

2023-10-16 14:56 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +# as a tuple `(list([int]), array(float])). The first element expresses a given Slater
Done.

2023-10-16 14:56 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +The first line of attack for initial state preparation is CISD calculations performed with the PySCF
Done.

2023-10-16 14:56 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +get us _most of the way_ to an initial state. Such an initial state will not be the
Fixed.

2023-10-16 14:56 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +    qml.QubitStateVector(initstate, wires=wires)
Done

2023-10-16 14:57 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +ovlp = np.dot(wf_ccsd, wf_hf)
In my mind it is a good reminder of what you can do in PennyLane, i.e. evaluate states using their overlaps.

2023-10-16 19:29 UTC, alvaro-at-xanadu requested changes
Great demo! I learned a lot and now I'm curious about all the post HF methods! It has a lot of potential to get our users started in some cool QChem methods. Aside from minor typos and minor style edits, I think there are a few more things that need refining:

- Comments on code that is long and not too self-explanatory. We don't need to have a lot of comments, but something to guide the reader. Remember that interpreting other people's code is always super exhausting 🤣 
- Some print statement are inside non-executable code blocks. I think this is fine if the libraries that we need aren't in requirements.txt and would be a pain to install. However, we need to show the reader the outputs so they can see what we achieved. 
- We need to actually show that VQE did speed up, that was the exciting promise of the demo! Some print statements when running VQE and showing iterations could be of use here. 
- Some more user friendly print statements, namely by the end of the demo, could also be really useful!

Good luck, I'm looking forward to reading the finalized version! 🚀

2023-10-16 19:29 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_initial_state_preparation.py
> +wf_hf[3] = 1.
This may be a stupid question, but why is the hf_state `[0,0,0,1]` and not `[1,0,0,0]`? I see this is something that happens from the start? Is there a convention here that we need to be aware of?

2023-10-16 19:29 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_initial_state_preparation.py
> +# energy_dmrg, theta_dmrg = run_VQE(wf_dmrg, ham=H2mol_corr)
I don't necessarily agree that we need to change the molecule at this point, but I thought the point was to make VQE more efficient by making it converge faster. Is there something more explicit we can show here to drive this point home? Maybe some print statement to explicitly compare what happens of we start from the HF state vs the post HF states that we've prepared?

2023-10-16 19:29 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_initial_state_preparation.py
> +
We get 0.1. This is a dramatic difference. I wouldn't expect the HF state to differ so dramatically from the post HF states. (I don't know much QChem, so I may be completely wrong, but this is almost an orthogonal state!)

2023-10-16 19:29 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_initial_state_preparation.py
> +
I think it'd look nicer if we print all of the overlaps labelled by post HF method, showing how they compare. Why are methods commented?

2023-10-16 19:29 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_initial_state_preparation.py
> +# example of VQE, it demonstrates how a better choice of state -- obtained, for example
```suggestion
# example of VQE, it demonstrates how a better choice of state--obtained, for example 

```

2023-10-16 19:29 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_initial_state_preparation.py
> +# from a sophisticated computational chemistry method like CCSD, SHCI or DMRG -- can lead
```suggestion
# from a sophisticated computational chemistry method like CCSD, SHCI or DMRG--can lead

```

2023-10-17 00:21 UTC, soranjh commented
[sc-39264]

2023-10-17 01:59 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +# The crucial part is calling `get_csf_coefficients()` on the solution stored in
Agreed to keep as is.

2023-10-17 02:07 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +intermediate-scale quantum (ISQ) algorithms, obtaining the ground state of a chemical system requires
Great idea, done!

2023-10-17 12:20 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +an object that can be turned into a PennyLane statevector. We have already done this hard
It is not, but it is being treated here as the name of a format type. Still, probably okay to separate.

2023-10-17 12:21 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +# initial state in a quantum circuit in PennyLane -- we will showcase this below for VQE.
Understood, will remember for the future!

2023-10-17 12:23 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +#
Agreed, moved to the top.

2023-10-17 12:25 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +#
Thanks for the comments, will work to simplify. It's not the run time that is the concern, it's that it requires the block2 dependency which we want to avoid. Will add output manually.

2023-10-17 12:26 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +#
Copy that, will do!

2023-10-17 12:27 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +
Commented because they are not executed above to avoid dependencies on block2 and Dice. Will add output manually when not executed. Values modified as I switched to H3+ molecule, not as stark anymore.

2023-10-17 13:36 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +# generate initial states from them, you should try Overlapper, our internal
Not available yet -- will add it later this week.

2023-10-17 13:36 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +    return energy_VQE, theta_opt
Worked to improve readability, but sticking with plotting -- more visual.

2023-10-17 13:36 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +# energy_dmrg, theta_dmrg = run_VQE(wf_dmrg, ham=H2mol_corr)
Removed this section.

2023-10-17 18:32 UTC, soranjh requested changes
Thanks @Chiffafox, looks great. I left some suggestions.

2023-10-17 18:32 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +print(f"CISD-based state vector\n{wf_cisd}")
Using `print(f"CISD-based state vector: \n {wf_cisd.real}")` prints a cleaner output.

2023-10-17 18:32 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +print(f"CCSD-based state vector\n{wf_ccsd}")
Please try printing the real part only.

2023-10-17 18:32 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +#       [ 0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
Please try printing the real part only.

2023-10-17 18:32 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +#    [ 0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
Please try printing the real part only.

2023-10-17 18:32 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +# generate initial states from them, you should try Overlapper, our internal
I suggest removing this line, until Overlapper is public. We might simply forget adding the link and merge the demo.

2023-10-17 18:32 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +    qml.StatePrep(wf_hf, wires=wires)
please use:

```
def circuit_VQE(theta, initial_state):
    qml.StatePrep(initial_state, wires=wires)
```

This allows reusing the same function for different initial states.

2023-10-17 18:32 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +    new_energy = circuit_VQE(theta)
Regarding the comment above, please use:

```
theta, prev_energy = opt.step_and_cost(circuit_VQE, theta, initial_state = wf_hf)
new_energy = circuit_VQE(theta,  initial_state = wf_hf)
```

2023-10-17 18:32 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +    return qml.expval(H2mol)
You can remove this and use the circuit created before.

2023-10-17 18:32 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +    new_energy = circuit_VQE(theta)
Please use `initial_state = wf_cisd` as kwqrg.

2023-10-17 18:32 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +    delta_E = new_energy - prev_energy
Please print iteranion_number, new_energy and delta_E. They will look very nice. Otherwise, the code feels like a block box. You can still keep the plot.

2023-10-17 18:32 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +    delta_E = new_energy - prev_energy
Please print iteranion_number, new_energy and delta_E. They will look very nice. Otherwise, the code feels like a block box. You can still keep the plot.

2023-10-17 19:02 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +print(f"CISD-based state vector\n{wf_cisd}")
Done.

2023-10-17 19:02 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +print(f"CCSD-based state vector\n{wf_ccsd}")
Done.

2023-10-17 19:02 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +#       [ 0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
Done.

2023-10-17 19:03 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +#    [ 0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
Done.

2023-10-17 19:07 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +    qml.StatePrep(wf_hf, wires=wires)
Copy that, this is what I had before -- will do.

2023-10-17 19:12 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +    new_energy = circuit_VQE(theta)
Done.

2023-10-17 19:12 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +    return qml.expval(H2mol)
Done.

2023-10-17 19:12 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +    new_energy = circuit_VQE(theta)
Done.

2023-10-17 19:12 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +    delta_E = new_energy - prev_energy
Done.

2023-10-17 19:12 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +    delta_E = new_energy - prev_energy
Done.

2023-10-17 20:35 UTC, KetpuntoG commented on demonstrations/tutorial_initial_state_preparation.py
> +*Author: Stepan Fomichev — Posted: 20 October 2023. Last updated: 20 October 2023.*
all this is no longer necessary. It is obtained from the `.metadata`

2023-10-17 20:35 UTC, KetpuntoG commented on demonstrations/tutorial_initial_state_preparation.py
> +^^^^^^^^^^^
```suggestion
~~~~~~~~~~
```

2023-10-17 20:35 UTC, KetpuntoG commented on demonstrations/tutorial_initial_state_preparation.py
> +# ^^^^^^^^^^^
```suggestion
# ~~~~~~~~~
```

2023-10-17 20:35 UTC, KetpuntoG commented on demonstrations/tutorial_initial_state_preparation.py
> +# ^^^^^^^^^^^
```suggestion
# ~~~~~~~~~
```

2023-10-17 20:35 UTC, KetpuntoG commented on demonstrations/tutorial_initial_state_preparation.py
> +# which is installed from ``pip``
```suggestion
# which is installed from ``pip``:

```

2023-10-17 20:35 UTC, KetpuntoG commented on demonstrations/tutorial_initial_state_preparation.py
> +#
What do you mean here, it would not work without the dependency? It seems strange to me to put the output by hand in an executable demo 🤔

2023-10-17 20:35 UTC, KetpuntoG commented on demonstrations/tutorial_initial_state_preparation.py
> +# ^^^^^^^^^^^
```suggestion
# ~~~~~~~~~~~~~~
```

2023-10-17 20:35 UTC, KetpuntoG commented on demonstrations/tutorial_initial_state_preparation.py
> +# Now let's run VQE with the Hartree-Fock initial state
```suggestion
# Now let's run VQE with the Hartree-Fock initial state:
```

2023-10-17 20:35 UTC, KetpuntoG commented on demonstrations/tutorial_initial_state_preparation.py
> +# And compare with how things go when you run it with the CISD initial state
```suggestion
# And compare with how things go when you run it with the CISD initial state:
```

2023-10-17 20:35 UTC, KetpuntoG commented on demonstrations/tutorial_initial_state_preparation.py
> +#    >>> 0.9745302156443371
I would try to have all prints follow the same format

2023-10-17 20:35 UTC, KetpuntoG commented on demonstrations/tutorial_initial_state_preparation.py
> +# -------
```suggestion
# Conclusion 
# -----------
```

This is to follow the standard

2023-10-17 20:35 UTC, KetpuntoG commented on demonstrations/tutorial_initial_state_preparation.py
> +
```suggestion

.. figure:: ../demonstrations/initial_state_preparation/qchem_input_states.png
    :align: center
    :width: 50%
    :target: javascript:void(0)

```

simply to make it a little more attractive

2023-10-17 20:48 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +*Author: Stepan Fomichev — Posted: 20 October 2023. Last updated: 20 October 2023.*
Understood, removed.

2023-10-17 20:50 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +#    >>> 0.9745302156443371
Sounds good -- any suggestions on the best format?

2023-10-18 14:35 UTC, KetpuntoG commented on demonstrations/tutorial_initial_state_preparation.py
> +
```suggestion
```

2023-10-18 14:39 UTC, KetpuntoG commented on demonstrations/tutorial_initial_state_preparation.py
> +#    >>> 0.9745302156443371
Maybe you can skip that part since it is not executable. You may invite the reader to check that the overlar with DMRG and SHCI also matches.

2023-10-18 17:53 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +#    >>> 0.9745302156443371
Done.

2023-10-18 17:55 UTC, Chiffafox commented on demos_quantum-chemistry.rst
> +    :figure: demonstrations/resource_estimation/resource_estimation.jpeg
I believe we are now good on the thumbnail and main image.

2023-10-18 21:06 UTC, soranjh reviewed
Thanks @Chiffafox. Left some small comments. Please modify the conclusion to better reflect the purpose of the demo.

2023-10-18 21:06 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +# metric of success for initial states in quantum algorithms. Because in PennyLane these
Please use "in our examples" instead of PennyLane.

2023-10-18 21:06 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +# DMRG and SHCI in a tougher molecule). If a ground state in such a case was known,
`tougher` might be changed to something like: `a molecule with strong correlations`.

2023-10-18 21:06 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +# This demo explains the concept of the initial state for quantum algorithms. Using the
No! This demo shows how to import initial states obtained from ... classical quantum chemistry calculations to PL.

2023-10-18 21:06 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +# molecules, we generally recommend DMRG or SHCI initial states. Here we showcased
We should not recommend anything. However, we can say something like: in more correlated 
 molecules DMRG or SHCI initial states are generally better ...

2023-10-18 21:20 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +tutorial, we show how to *use traditional computational chemistry techniques* to
Yup already switched to bold. Just wanted something in that paragraph to catch the eye.

2023-10-18 21:22 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +The first line of attack for initial state preparation are CISD calculations performed with the `PySCF <https://github.com/pyscf/pyscf>`_
Done.

2023-10-18 21:22 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +We now show how this works on the example of the H:math:`_3^+` molecule.
Thanks!

2023-10-18 21:23 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +orbitals, but the unrestricted version is available too.
Done.

2023-10-18 21:24 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +ax.plot(range(len(results_cisd)), results_cisd, color="b", marker="o", label="CISD")
Done.

2023-10-18 21:25 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +# metric of success for initial states in quantum algorithms. Because in PennyLane these
Done.

2023-10-18 21:26 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +# DMRG and SHCI in a tougher molecule). If a ground state in such a case was known,
Changed to "more correlated".

2023-10-18 21:27 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +# This demo explains the concept of the initial state for quantum algorithms. Using the
Changed.

2023-10-18 21:27 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +# molecules, we generally recommend DMRG or SHCI initial states. Here we showcased
Done.

2023-10-18 21:31 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +# For Dice, the installation process is more complicated than for Block2, but the execution process is similar:
Done.

2023-10-18 21:32 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +#    (dets, coeffs) = [post-process shci_output.out to get tuple of
Done.

2023-10-18 21:37 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +# VQE circuit with wf_hf as initial state and all possible excitations
Done.

2023-10-18 21:38 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +@qml.qnode(dev, interface="autograd")
Done.

2023-10-18 22:03 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +)
Done.

2023-10-18 22:03 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +print(f"CISD-based state vector: \n {wf_cisd.real}")
Done.

2023-10-18 22:05 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +# CI coefficients to appropriate determinants.
There are two sentences here, which one?

2023-10-18 22:06 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +# CI coefficients to appropriate determinants.
I separated it out on purpose, to improve readability by splitting one large paragraph.

2023-10-18 22:10 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +    print(f"Step = {len(results_hf)},  Energy = {new_energy:.6f} Ha, dE = {delta_E} Ha")
Done.

2023-10-18 22:10 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +    print(f"Step = {len(results_cisd)},  Energy = {new_energy:.6f} Ha, dE = {delta_E} Ha")
Done.

2023-10-19 02:28 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +tutorial, we show how to *use traditional computational chemistry techniques* to
It is too much destruction to go from regular to bold then to italic in one sentence. I do not think this phrase deserves to be highlighted.

2023-10-19 02:30 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +H2mol, qubits = qchem.molecular_hamiltonian(
If you do not want to change the geometry, please still use this format:

```
symbols = ["H", "H", "H"]
geometry = np.array([[...],  [...],  [...]])

H, qubits = qchem.molecular_hamiltonian(symbols, geometry, charge = 1)
```

2023-10-19 02:31 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +# This demo shows how to import initial states from traditional quantum chemistry methods
"methods" or "calculations"?

2023-10-19 02:32 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +# chemistry method like CCSD, SHCI or DMRG--can lead to much better algorithmic
This sentence needs rephrasing. Too complicated.

2023-10-19 02:32 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +# performance. Especially in more correlated molecules, generally DMRG and SHCI initial
Please remove `Especially` and `generally`.

2023-10-19 02:33 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +# converted to PennyLane's state vector format with a single line of code.
This sentence should be at the beginning of this section.

2023-10-19 13:28 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +H2mol, qubits = qchem.molecular_hamiltonian(
Done.

2023-10-19 13:32 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +# performance. Especially in more correlated molecules, generally DMRG and SHCI initial
Done.

2023-10-19 13:36 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +# converted to PennyLane's state vector format with a single line of code.
Done.

2023-10-19 13:38 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +tutorial, we show how to *use traditional computational chemistry techniques* to
Sounds good.

2023-10-19 19:21 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_initial_state_preparation.py
> +
You need a # at the start of this line, it's not rendering properly

2023-10-19 19:26 UTC, alvaro-at-xanadu commented on demonstrations/tutorial_initial_state_preparation.py
> +
```suggestion

#
```

2023-10-19 19:28 UTC, alvaro-at-xanadu requested changes
Amazing improvement! Loved the plot at the end and the comparison between the convergence rates. Code is also much more friendly to read 🚀 

Let me know if the suggestion for fixing the rendering error works. If it does, I'll approve 🎉

2023-10-19 20:14 UTC, alvaro-at-xanadu approved these changes

2023-10-19 20:21 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +
Worked, thanks for catching!

2023-10-20 01:38 UTC, KetpuntoG commented
Great work here! Ready to merge, I'll take care of it tomorrow 😊

2023-10-20 04:11 UTC, soranjh reviewed
Thanks @Chiffafox, left a mall comment on splinting the VQE code block.

2023-10-20 04:11 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +# Now let's run VQE with the Hartree-Fock initial state:
Please use:

Now let's run VQE with the Hartree-Fock initial state. We first build the VQE circuit:

2023-10-20 04:11 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +# create the VQE optimizer, initialize the variational parameters, set start params
Please use (to reduce the size of the code block and split it to 2 parts):

```
##############################################################################
# Now, we create the VQE optimizer, initialize the variational parameters and run the VQE optimization.
```

2023-10-20 14:14 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +# Now let's run VQE with the Hartree-Fock initial state:
Done.

2023-10-20 14:15 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +# create the VQE optimizer, initialize the variational parameters, set start params
Done.

2023-10-20 15:00 UTC, soranjh approved these changes
Great job @Chiffafox, left one final comment in Conclusions.

2023-10-20 15:00 UTC, soranjh commented on demonstrations/tutorial_initial_state_preparation.py
> +# for use in PennyLane-based algorithms. We showcased simple workflows for how to run
Please use "for use in PennyLane." and remove "-based algorithms".

2023-10-20 15:59 UTC, Chiffafox commented on demonstrations/tutorial_initial_state_preparation.py
> +# for use in PennyLane-based algorithms. We showcased simple workflows for how to run
Done.

2023-10-20 18:38 UTC, merged