ODEgen demo
PennyLaneAI/qml pull request #951
Opened 2023-10-09 13:21 UTC by Qottmann

A demo for ODEgen, our in-house method for evaluating analytic gradients of pulse programs on quantum computers

https://arxiv.org/abs/2309.16756

2023-11-22 16:37 UTC, Qottmann commented
@KetpuntoG this is ready for review now, just fyi 🙂

2023-11-22 20:14 UTC, KetpuntoG commented
> @KetpuntoG this is ready for review now, just fyi 🙂

Thanks! We'll take a look 🚀

2023-11-29 16:27 UTC, KetpuntoG reviewed
Great job @Qottmann ! I enjoyed following the math, simple and effective  💪

2023-11-29 16:27 UTC, KetpuntoG commented on demonstrations/tutorial_odegen.py
> +T_CR = 100.            # gate time for two qubit drive (cross resonance)
```suggestion
T_CR = 100.   # gate time for two qubit drive (cross resonance)
```

2023-11-29 16:27 UTC, KetpuntoG commented on demonstrations/tutorial_odegen.py
> +plt.show()
Really impressive :)

2023-11-29 16:27 UTC, KetpuntoG commented on demonstrations/tutorial_odegen.py
> +#
```suggestion
```

2023-11-29 16:27 UTC, KetpuntoG commented on demonstrations/tutorial_odegen.py
> +#
```suggestion

```

2023-11-29 16:27 UTC, KetpuntoG commented on demonstrations/tutorial_odegen.py
> +In this demo, we are going to take a look at the recently introduced ODEgen method for computing analytic gradiens
```suggestion
In this demo, we are going to take a look at the recently introduced ODEgen method for computing analytic gradients 
```

2023-11-29 16:27 UTC, KetpuntoG commented on demonstrations/tutorial_odegen.py
> +# The second term desribes the driving with drive amplitudes :math:`\Omega_q`, drive frequencies :math:`\nu_q` and phases :math:`\phi_q`.
```suggestion
# The second term describes the driving with drive amplitudes :math:`\Omega_q`, drive frequencies :math:`\nu_q` and phases :math:`\phi_q`. 
```

2023-11-29 16:27 UTC, KetpuntoG commented on demonstrations/tutorial_odegen.py
> +        # SPS gradients dont allow for full jitting of the update step
```suggestion
        # SPS gradients don't allow for full jitting of the update step
```

2023-11-29 16:27 UTC, KetpuntoG commented on demonstrations/tutorial_odegen.py
> +# towards the minimum due to the stochasticity of the gradient estimates. Note that both optimizations start from the same (random) initial point.
```suggestion
# toward the minimum due to the stochasticity of the gradient estimates. Note that both optimizations start from the same (random) initial point.
```

(ignore it if wrong)

2023-11-29 16:30 UTC, KetpuntoG commented on demonstrations/tutorial_odegen.py
> +*Author: Korbinian Kottmann — Posted: 31 November 2023.*
```suggestion
```

2023-11-30 07:58 UTC, Qottmann commented on demonstrations/tutorial_odegen.py
> +r"""Evaluating analytic gradients of pulseprograms on quantum computers
typo! Thanks for spotting it!

2023-11-30 08:01 UTC, Qottmann commented on demonstrations/tutorial_odegen.py
> +ODEgen allows you to compute analytic gradients with high accuracy at lower cost! Learn about how ODEgen achieves this
I added the sentence like you suggested :)

2023-11-30 08:15 UTC, Qottmann commented on demonstrations/tutorial_odegen.py
> +:math:`H_q` in :math:`H(\theta, t)` to be Pauli words, which will make SPS rule below a bit more digestible. For more details on the general cases we refer to the original paper [#Kottmann]_.
Ah I see where the confusion is coming from. I updated that part (and the definition of the pulse Hamiltonian above). A sole pulse gate U still involves all pulse generators (i.e. summing over $j$). I tried to make that more explicit in the text now

2023-11-30 08:38 UTC, Qottmann commented on demonstrations/tutorial_odegen.py
> +shifted evolutions :math:`| \psi_q^\pm(\tau) \rangle = U(T, \tau) e^{-i\left(\pm\frac{\pi}{4}\right)H_q} U(\tau, 0)`. Here, we use the notation :math:`U(t_1, t_0)`
I tried to make it bit more digestible, let me know if this is better now or if it need further tweaking

2023-11-30 08:38 UTC, Qottmann commented on demonstrations/tutorial_odegen.py
> +.. math:: \frac{\partial}{\partial \theta_j} U(\theta) = -i U(\theta) \mathcal{H}_j
Yes :)

2023-11-30 08:39 UTC, Qottmann commented on demonstrations/tutorial_odegen.py
> +.. math:: \frac{\partial}{\partial \theta_j} U(\theta) = -i U(\theta) \mathcal{H}_j
Added a comment to stress that :) good point!

2023-11-30 16:36 UTC, KetpuntoG commented
Thanks for the changes @Qottmann ! Looks great :)
@DanielNino27 will take a second look  🚀

2023-11-30 18:59 UTC, DanielNino27 requested changes
Very nicely explained with a nice simple example showcasing the strength of ODEgen. Just a few relatively minor comments.

2023-11-30 18:59 UTC, DanielNino27 commented on demonstrations/tutorial_odegen.py
> +Learn about how ODEgen achieves this and convince yourself with a numerical demonstration in this demo.
convince yourself of what? I can infer from context that it's that ODEgen can compute gradiets of pulse programs with higher accuracy at lower cost, but it's not too clear.  Perhaps something like ".. achieves this and explore its capabilities with a numerical..."

2023-11-30 18:59 UTC, DanielNino27 commented on demonstrations/tutorial_odegen.py
> +    Illustration of ODEgen and stochastic parameter-shift for computing gradients of quantum pulse programs.
```suggestion
    Illustration of ODEgen and stochastic parameter-shift (SPS) for computing gradients of quantum pulse programs.
```

2023-11-30 18:59 UTC, DanielNino27 commented on demonstrations/tutorial_odegen.py
> +.. math:: \mathcal{H}_j = \sum_\ell \omega_\ell^{(j)} P_\ell
omega is not defined anywhere  - I understand they are coefficients for the linear superposition of Pauli words, but that should be stated.

2023-11-30 18:59 UTC, DanielNino27 commented on demonstrations/tutorial_odegen.py
> +# .. math:: H(\theta, t) = - \sum_i \frac{\omega_i}{2} Z_i + \sum_i \Omega_i(t) \sin(\nu_i t + \phi_i(t)) Y_i + \sum_{q, p \in \mathcal{C}} \frac{g_{qp}}{2} (X_i X_p + Y_i Y_p).
g_qp is not defined (I assume it's a coupling constant from context).

2023-11-30 18:59 UTC, DanielNino27 commented on demonstrations/tutorial_odegen.py
> +H_pulse += 2 * np.pi * 0.0123 * (qml.PauliX(wires[0]) @ qml.PauliX(wires[1]) + qml.PauliY(wires[0]) @ qml.PauliY(wires[1]))
I think it would be more clear if 0.0123 were associated with a variable (like g = 0.0123, or some more instructive name). Makes it cleaner to change if a user wants to.

2023-11-30 18:59 UTC, DanielNino27 commented on demonstrations/tutorial_odegen.py
> +# We note that for as long as we are in simulation, there is naturally no difference between the gradients obtained
```suggestion
# We note that for as long as we use a simulator, there is naturally no difference between the gradients obtained
```

2023-11-30 18:59 UTC, DanielNino27 commented on demonstrations/tutorial_odegen.py
> +# We now have all ingredients to run VQE with ODEgen and SPS. We define the following standard
```suggestion
# We now have all the ingredients to run VQE with ODEgen and SPS. We define the following standard
```

2023-11-30 18:59 UTC, DanielNino27 commented on demonstrations/tutorial_odegen.py
> +# We also want to make sure that this is a fair comparison in terms of quantum resources. In the case of ODEgen we maximally have :math:`\mathcal{R}_\text{ODEgen} = 2 (4^n - 1) = 30` expectation valu
```suggestion
# We also want to make sure that this is a fair comparison in terms of quantum resources. In the case of ODEgen, we maximally have :math:`\mathcal{R}_\text{ODEgen} = 2 (4^n - 1) = 30` expectation values.
```

2023-11-30 18:59 UTC, DanielNino27 commented on demonstrations/tutorial_odegen.py
> +# We introduced ODEgen for computing analytic gradients of pulse gates and showcased its advantages in simulation for a VQE example.
```suggestion
# We introduced ODEgen for computing analytic gradients of pulse gates and showcased its advantages in simulation with an example using VQE.
```

2023-11-30 18:59 UTC, DanielNino27 commented on demonstrations/tutorial_odegen.py
> +# For SPS we have :math:`2 N_s 2 = 32` (due to :math:`N_g = 2` and :math:`N_s=8` time samples per gradient that we chose in ``num_split_times`` above). Thus, overall, we require fewer
```suggestion
# For SPS we have :math:`2 N_s N_g = 32` (due to :math:`N_g = 2` and :math:`N_s=8` time samples per gradient that we chose in ``num_split_times`` above). Thus, overall, we require fewer 
```

2023-12-01 13:00 UTC, Qottmann commented on demonstrations/tutorial_odegen.py
> +Learn about how ODEgen achieves this and convince yourself with a numerical demonstration in this demo.
updated ✅

2023-12-01 13:02 UTC, Qottmann commented on demonstrations/tutorial_odegen.py
> +    Illustration of ODEgen and stochastic parameter-shift for computing gradients of quantum pulse programs.
✅

2023-12-01 13:03 UTC, Qottmann commented on demonstrations/tutorial_odegen.py
> +where we compute the expectation value of some objective Hamiltonian :math:`H_\text{obj}` (think quantum many-body Hamiltonian whose ground state energy we want to estimate).
If it's not strictly a typo or grammar mistake I'd like to leave my personal writing style 🙃

2023-12-01 13:03 UTC, Qottmann commented on demonstrations/tutorial_odegen.py
> +    a Pauli word :math:`H` (think e.g. :math:`H = X_0 Y_1`), one can compute the gradient in a hardware compatible manner via the parameter-shift rule
see https://github.com/PennyLaneAI/qml/pull/951#discussion_r1412079647

2023-12-01 13:11 UTC, Qottmann commented on demonstrations/tutorial_odegen.py
> +    Pulse gates generated from :math:`H(\theta, t)` introduce two complications: First, the generators of the gates are now time-dependent. Second, the generator consists of a sum of non-commuting te
Thanks I didnt know that! I just removed the colon 😅

2023-12-01 13:14 UTC, Qottmann commented on demonstrations/tutorial_odegen.py
> +# .. math:: H(\theta, t) = - \sum_i \frac{\omega_i}{2} Z_i + \sum_i \Omega_i(t) \sin(\nu_i t + \phi_i(t)) Y_i + \sum_{q, p \in \mathcal{C}} \frac{g_{qp}}{2} (X_i X_p + Y_i Y_p).
✅

2023-12-01 13:15 UTC, Qottmann commented on demonstrations/tutorial_odegen.py
> +H_pulse += 2 * np.pi * 0.0123 * (qml.PauliX(wires[0]) @ qml.PauliX(wires[1]) + qml.PauliY(wires[0]) @ qml.PauliY(wires[1]))
Yes good point! ✅

2023-12-01 13:16 UTC, Qottmann commented on demonstrations/tutorial_odegen.py
> +# We note that for as long as we are in simulation, there is naturally no difference between the gradients obtained
lol good point 
![image](https://github.com/PennyLaneAI/qml/assets/43949391/1d524efe-acdd-4f1f-8380-b4f11fe8ca60)

2023-12-01 13:18 UTC, Qottmann commented on demonstrations/tutorial_odegen.py
> +# We now have all ingredients to run VQE with ODEgen and SPS. We define the following standard
Can I not say: "We have all ingredients"? Is this personal preference or a grammatical error? I changed it anyway, just curious if this is technically wrong

2023-12-01 13:18 UTC, Qottmann commented on demonstrations/tutorial_odegen.py
> +# We also want to make sure that this is a fair comparison in terms of quantum resources. In the case of ODEgen we maximally have :math:`\mathcal{R}_\text{ODEgen} = 2 (4^n - 1) = 30` expectation valu
✅

2023-12-01 13:19 UTC, Qottmann commented on demonstrations/tutorial_odegen.py
> +# We introduced ODEgen for computing analytic gradients of pulse gates and showcased its advantages in simulation for a VQE example.
✅

2023-12-01 14:19 UTC, DanielNino27 commented on demonstrations/tutorial_odegen.py
> +where we compute the expectation value of some objective Hamiltonian :math:`H_\text{obj}` (think quantum many-body Hamiltonian whose ground state energy we want to estimate).
Yes not strictly a typo or grammar mistake as far as I know, I think I'm just used to seeing 'e.g' at the start. I think you can leave it as is unless any one else brings something up.

2023-12-01 22:16 UTC, DanielNino27 commented on demonstrations/tutorial_odegen.py
> +# For SPS we have :math:`N_g N_s 2 = 32` (due to :math:`N_g = 2` and :math:`N_s=8` time samples per gradient that we chose in ``num_split_times`` above). Thus, overall, we require fewer
```suggestion
# For SPS we have :math:`2N_g N_s = 32` (due to :math:`N_g = 2` and :math:`N_s=8` time samples per gradient that we chose in ``num_split_times`` above). Thus, overall, we require fewer 
```

2023-12-04 15:38 UTC, KetpuntoG commented
> Great! The only thing missing now is the thumbnail 🥳

Awesome job!
Tarik will come the 11th, so we will have to wait until then 🏖️

2023-12-04 15:57 UTC, DanielNino27 approved these changes

2023-12-07 19:55 UTC, KetpuntoG commented on demonstrations/tutorial_odegen.metadata.json
> +            "uri": "/_images/thumbnail_tutorial_optimal_control.png"
Now the path will appear relative to `_static`, look at the metadata of another demo in master

2023-12-07 19:56 UTC, KetpuntoG commented on demos_optimization.rst
This file has been removed from the master branch. You will get conflict when merge so just delete the file also in your branch

2023-12-12 13:19 UTC, alvaro-at-xanadu approved these changes
All looks good to me

2023-12-12 13:53 UTC, merged