Add a how-to on JAX optimization
PennyLaneAI/qml pull request #970
Opened 2023-10-31 22:16 UTC by josh146

2023-11-01 20:48 UTC, KetpuntoG reviewed
Great job! This will be very useful 😍
I leave a few comments

2023-11-01 20:48 UTC, KetpuntoG commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax.py
> +from jax import numpy as jnp
Is `jnp` a stsandar or do people use `np` as well?

2023-11-01 20:48 UTC, KetpuntoG commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax.py
> +#
I think it is worth commenting on what `jax.jit` does or at least providing a link

2023-11-01 20:48 UTC, KetpuntoG commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax.py
> +# We can now use Optax to create an Adam optimizer, and train our circuit.
Could you link to the other posible optimizers?
https://optax.readthedocs.io/en/latest/api.html

2023-11-01 20:48 UTC, KetpuntoG commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax.py
> +    return params, opt_state, loss_val
It is about confusing to have `update`, `updates` and `opt.update`.
If this is the standard way to write it, ignore this comment.

2023-11-01 20:48 UTC, KetpuntoG commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax.py
> +    jax.lax.cond((jnp.mod(i, 5) == 0) & print_training, print_fn, lambda: None)
First time I see "&" in the code 😄 is it exactly the same as "and"?

2023-11-01 20:48 UTC, KetpuntoG commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax.py
> +print(f"JIT compiling entire optimization loop (best of {reps}): {result} sec per loop")
That's super cool! Could you finish with a sentence highlighting the difference between the two times?

2023-11-01 20:48 UTC, KetpuntoG commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax.py
> +print(f"JIT compiling entire optimization loop (best of {reps}): {result} sec per loop")
Don't forget to put the authors at the end

2023-11-01 20:48 UTC, KetpuntoG commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax.py
> +    # local Z would only be afffected by params on that qubit.
```suggestion
    # local Z would only be affected by params on that qubit.
```

2023-11-01 20:48 UTC, KetpuntoG commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_JAXopt.py
> +# circuit architecture, and cost function, in order to build models that may have use. This is still
```suggestion
# circuit architecture, and cost function, in order to build models that may have used. This is still
```

2023-11-01 20:48 UTC, KetpuntoG commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_JAXopt.py
> +# not happening in Python, but is compiled and executed native. This avoids (potentially costly) data
```suggestion
# not happening in Python, but is compiled and executed natively. This avoids (potentially costly) data
```

2023-11-01 20:48 UTC, KetpuntoG commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax.py
> +# not happening in Python, but is compiled and executed native. This avoids (potentially costly) data
```suggestion
# not happening in Python, but is compiled and executed natively. This avoids (potentially costly) data
```

2023-11-01 20:48 UTC, KetpuntoG commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_JAXopt.py
> +    # local Z would only be afffected by params on that qubit.
```suggestion
    # local Z would only be affected by params on that qubit.
```

2023-11-01 20:48 UTC, KetpuntoG commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax.py
> +# circuit architecture, and cost function, in order to build models that may have use. This is still
```suggestion
# circuit architecture, and cost function, in order to build models that may have used. This is still
```

2023-11-01 20:48 UTC, KetpuntoG commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_JAXopt.py
> +
I use to put this to silence the messages in the demo:

jax.config.update("jax_platform_name", "cpu")
jax.config.update('jax_enable_x64', True)

2023-11-01 20:48 UTC, KetpuntoG commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax.py
> +# Note that we use ``jax.lax.fori_loop`` and ``jax.lax.cond``, rather than a standard Python for loop
Could you add jax.debug.print too?

2023-11-02 02:11 UTC, josh146 commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax.py
> +    return params, opt_state, loss_val
Yes good point, I will update this!

2023-11-02 02:12 UTC, josh146 commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax.py
> +    jax.lax.cond((jnp.mod(i, 5) == 0) & print_training, print_fn, lambda: None)
In this specific case yes, but in general it is different :) This is the _bitwise_ and operator, while `and` is the logical and operator.

2023-11-02 02:12 UTC, josh146 commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax.py
> +print(f"JIT compiling entire optimization loop (best of {reps}): {result} sec per loop")
I thought we didn't need this any more with the react website?

2023-11-02 02:13 UTC, josh146 commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_JAXopt.py
> +# circuit architecture, and cost function, in order to build models that may have use. This is still
'may have use' is the intended one here :)

2023-11-03 00:50 UTC, josh146 commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax.py
> +from jax import numpy as jnp
jnp is the standard :) JAX recommends:

```python
from jax import numpy as jnp # for when you need JAX version
import numpy as np  # for when you don't need JAX
```

2023-11-03 00:54 UTC, josh146 commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_JAXopt.py
> +
```suggestion
jax.config.update("jax_platform_name", "cpu")
```

2023-11-03 01:04 UTC, josh146 commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax.py
> +    return params, opt_state, loss_val
@KetpuntoG I've left in `updates` and `opt.update`, as this is what is used in the Optax docs

2023-11-03 01:06 UTC, josh146 commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax.py
> +print(f"JIT compiling entire optimization loop (best of {reps}): {result} sec per loop")
@KetpuntoG I've added a short sentence, but unlike a demo I'm not sure I want to draw any conclusions here -- I'm not trying to teach the reader the 'best' way, I'm just showing a comparison between the two methods I used.

In all honesty, I shouldn't even be including this appendix here, I just thought it was nice to show the times 😆

2023-11-06 06:52 UTC, mariaschuld commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_JAXopt.py
> +# cost function to minimize a quantity of interest), the next step is **optimization**. That is,
```suggestion
# Once you have set up a quantum machine learning model, data to train with and 
# cost function to minimize as an objective, the next step is to perform the **optimization**. That is,
```

The brakets introduce a lot of bulky detail for the first sentence. I think if people don't know what data, cost and model are they are not on the right page, so this lean version should suffice?

2023-11-06 06:54 UTC, mariaschuld commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax.py
> +# We first define our ``update`` function, which needs to do a couple of things:
```suggestion
# We first define our ``update_step`` function, which needs to do a couple of things:
```
I would go with `update` everywhere - the `_step` does not add much information because an update is kind of a step?

2023-11-06 06:54 UTC, mariaschuld commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax.py
> +# We first define our ``update`` function, which needs to do a couple of things:
Unless you want to distinguish it from `opt.update`? Could then just use `step`?

2023-11-06 06:56 UTC, mariaschuld commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax.py
> +# cost function to minimize a quantity of interest), the next step is **optimization**. That is,
```suggestion
# Once you have set up a quantum machine learning model, data to train with and 
# cost function to minimize as an objective, the next step is to perform the **optimization**. That is,
```

2023-11-06 06:58 UTC, mariaschuld commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax.py
> +from jax import numpy as jnp
I always found it super confusing that we did the `from pennylane import numpy as np` because one totally looses the idea of what is trainable and what not. Happy we are slowly changing standards as well!

2023-11-06 07:05 UTC, mariaschuld commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_JAXopt.py
> +# also JIT compile the entire optimization loop; this means that the for-loop around optimization is
```suggestion
# In the above example, we JIT compiled our cost function ``loss_fn`` (and JAXopt automatically JIT compiled the `loss_and_grad` function behind the scenes). However, we can
# also JIT compile the entire optimization loop; this means that the for-loop around optimization is
```

This omission confused me, so maybe be explicit here?

2023-11-06 07:06 UTC, mariaschuld commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_JAXopt.py
> +# Note that we use ``jax.lax.fori_loop`` and ``jax.lax.cond``, rather than a standard Python for loop
```suggestion
# Note that -- similar to above -- we use ``jax.lax.fori_loop`` and ``jax.lax.cond``, rather than a standard Python for loop
```

2023-11-06 07:07 UTC, mariaschuld commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_JAXopt.py
> +
Oh-oh: Check the print-out, somehow this example is not converging during training any more (while the above one is!)

2023-11-06 07:08 UTC, mariaschuld requested changes
Very good how-to's, they contained a lot of information that I didn't know of, and which is very valuable for me!!

The only critical comment is that the JAXopt second example does not converge for some reason...

2023-11-06 19:14 UTC, josh146 commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_JAXopt.py
> +        return (params, *args[1:])
```suggestion
        params, opt_state = opt.update(*args, i)
        return (params, opt_state, *args[2:])
```

2023-12-14 08:31 UTC, josh146 commented on demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_JAXopt.py
> +# cost function to minimize as an objective, the next step is to **perform the optimization**. That is,
```suggestion
# Once you have set up a quantum machine learning model, data to train with, and 
# cost function to minimize as an objective, the next step is to **perform the optimization**. That is,
```

2024-01-10 19:46 UTC, KetpuntoG reviewed
Thanks @josh146 ! Great job here :) Ideal for the performance year! For your part it is ready ✅ Do you mind if I work directly on the branch to correct some final typos and fixes, add thumbnails, etc?

2024-01-18 17:53 UTC, KetpuntoG approved these changes
Great job, ready to go! 🚀

2024-01-19 11:05 UTC, mariaschuld approved these changes

2024-01-19 16:54 UTC, merged