[WIP] Demo Quantum Phase Estimation
PennyLaneAI/qml pull request #978
Opened 2023-11-09 17:06 UTC by KetpuntoG

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] Ensure that your tutorial executes correctly, and conforms to the
      guidelines specified in the [README](../README.md).

- [ ] Remember to do a grammar check of the content you include.
- [ ] All tutorials conform to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      To auto format files, simply `pip install black`, and then
      run `black -l 100 path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Title:**

**Summary:**

**Relevant references:**

**Possible Drawbacks:**

**Related GitHub Issues:**

----
If you are writing a demonstration, please answer these questions to facilitate the marketing process.

* GOALS — Why are we working on this now?

  *Eg. Promote a new PL feature or show a PL implementation of a recent paper.*

* AUDIENCE — Who is this for?

  *Eg. Chemistry researchers, PL educators, beginners in quantum computing.*

* KEYWORDS — What words should be included in the marketing post?

* Which of the following types of documentation is most similar to your file? 
(more details [here](https://www.notion.so/xanaduai/Different-kinds-of-documentation-69200645fe59442991c71f9e7d8a77f8))
    
- [ ] Tutorial
- [ ] Demo
- [ ] How-to

2023-12-11 19:43 UTC, ixfoduap requested changes
Some very good sections, and others that need a major overhaul for such an important demo

2023-12-11 19:43 UTC, ixfoduap commented on demonstrations/tutorial_quantum_phase_estimation.py
> +Applying the Fourier transform to this vector gives us a new vector that contains information about
```suggestion
Applying the Fourier transform gives us a new vector that contains information about
```

2023-12-11 19:43 UTC, ixfoduap commented on demonstrations/tutorial_quantum_phase_estimation.py
> +the frequency, and hence the period, of the original function. This is a technique widely used in
I think that we may benefit from briefly explaining what we mean by the period of a function and how it relates to a frequency. It isn't obvious at this stage and it'd dangerous to assume readers will understand this connection

2023-12-11 19:43 UTC, ixfoduap commented on demonstrations/tutorial_quantum_phase_estimation.py
> +period :math:`T = 10`. The :math:`x_i` can be simply chosen as integers from :math:`0` to
```suggestion
period :math:`T = 10`. (Can you see why the period is 10?) The :math:`x_i` can be simply chosen as integers from :math:`0` to
```

2023-12-11 19:43 UTC, ixfoduap commented on demonstrations/tutorial_quantum_phase_estimation.py
> +period :math:`T = 10`. The :math:`x_i` can be simply chosen as integers from :math:`0` to
This is optional, but in my experience little challenges like this can help explain and engage the reader

2023-12-11 19:43 UTC, ixfoduap commented on demonstrations/tutorial_quantum_phase_estimation.py
> +period :math:`T = 10`. The :math:`x_i` can be simply chosen as integers from :math:`0` to
Not clear why we choose the x_is this way. Seems like it may be convenient to set them to be a power of 2, in which case good to mention

2023-12-11 19:43 UTC, ixfoduap commented on demonstrations/tutorial_quantum_phase_estimation.py
> +    qml.ControlledSequence(U(wires = 0), control=estimation_wires)
The demo should be talking a lot about the strategy in PL to support QPE through the more general primitive ` qml.ControlledSequence`. This allows i to be used elsewhere, and we can vary the way we prepare state and process it, so not just Hadamards and QFT

2023-12-11 19:43 UTC, ixfoduap commented on demonstrations/tutorial_quantum_phase_estimation.py
> +# Goodbye *leaks*! As you can see, a small modification in the algorithm has *filtered* the noise.
But why does this matter if anyway we pick the largest value? Before we need to explain that in the q algorithm we sample the output state, and sometimes get the wrong value

2023-12-11 19:43 UTC, ixfoduap commented on demonstrations/tutorial_quantum_phase_estimation.py
> +# This demo provides a brief introduction to quantum phase estimation. We learned that the QPE
Revise conclusion [for Juan Miguel]

2023-12-12 01:22 UTC, soranjh commented on demonstrations/tutorial_quantum_phase_estimation.py
> +estimation_wires = [1, 2, 3]
Used 8 qubits which gives `\theta =  0.19921875`. But the peak is so sharp that makes it hard to visualise "cleaning the signal".

2023-12-12 01:30 UTC, soranjh commented on demonstrations/tutorial_quantum_phase_estimation.py
> +# .. note::
@ixfoduap  I added this note, feel free to remove if it contains unnecessary details.

2024-01-10 13:04 UTC, closed without merging